Clarify where Context.Key lives, and API to insert/extract from a Context instance
open-telemetry/opentelemetry-specification pull request #1020
Opened 2020-09-25 22:33 UTC by bogdandrutu

Signed-off-by: Bogdan Drutu <bogdandrutu@gmail.com>

Updates #1019

2020-09-25 22:50 UTC, jkwatson commented on specification/trace/api.md
> +The above first two methods MUST be equivalent to a single parameterized method
I think it will be clearer if you move this comment directly below what it is referencing, rather than after all of the methods.

2020-09-26 02:59 UTC, jmacd approved these changes

2020-09-26 04:01 UTC, anuraaga reviewed
I have been brainstorming integrating trace context methods into `Span` itself

```java
static Span.current()
Scope Span.makeCurrent()
static Span fromContext(Context ctx)
Context addToContext(Context ctx)
```

I think this could be a simpler Java API where static util methods are not so idiomatic. Does the spec preclude merging pieces pieces together (Span and TraceContextUtils) in this sort of way?

2020-09-26 14:00 UTC, bogdandrutu commented
@anuraaga please add this comment to the issue linked by this PR. You still need 2 static methods in your example, not sure if that solves that problem, but let's discuss in the issue where I have more examples and explanations.

2020-09-27 04:26 UTC, toumorokoshi commented on specification/trace/api.md
> +the `Context.Key`.
question on this: is there a standardized key name for the context?

I feel like that's an easy win that could apply to all implementations. Would help make debugging knowledge transferable across implementations.

2020-09-27 08:29 UTC, Oberon00 commented on specification/trace/api.md
> +The above first two methods MUST be equivalent to a single parameterized method
I think we should instead specify that all these methods SHOULD be equivalent to a single call (I think MUST is too much here), although I think we can specify that it MUST be implementable with only the context system and the key, no other magic must be involved.

2020-09-29 07:15 UTC, jmacd approved these changes

2020-09-29 08:00 UTC, Oberon00 requested changes

2020-09-29 08:00 UTC, Oberon00 commented on specification/trace/api.md
> +The above first two methods MUST be equivalent to a single parameterized method
Blocking comment: Please either comment on why the first two methods are special here, change the sentence to include all methods (I'd prefer that) or maybe we could remove the sentence.

2020-09-29 08:00 UTC, Oberon00 commented on specification/trace/api.md
> +The above last two methods are necessary because external API users don't have
What are "external" API users as opposed to other API users?

2020-09-29 08:00 UTC, Oberon00 commented on specification/trace/api.md
> +- Extract the `Span` from a `Context` instance
Should we also allow (not necessarily recommend) to just expose the key instead? With that, all the methods provided here should "be equivalent to a single parameterized method call of the `Context` management system".

2020-09-29 20:30 UTC, bogdandrutu commented on specification/trace/api.md
> +- Extract the `Span` from a `Context` instance
We discussed that, please look for history in the context PR why not to do that.

2020-09-30 19:14 UTC, bogdandrutu commented on specification/trace/api.md
> +The above first two methods MUST be equivalent to a single parameterized method
All of them :)

2020-10-01 12:28 UTC, arminru commented on specification/trace/api.md
> +the `Context.Key` (the name MAY be `"span_context_key"`).
It's unclear what `Context.Key` is. How about this?
```suggestion
the `Context` key used for storing the currently active span
(usually called `Context.Key` or `span_context_key` in implementations).
```

2020-10-01 12:28 UTC, arminru commented on specification/trace/api.md
> +The above last two methods are necessary because API users don't have access to
```suggestion
The last two methods listed above are necessary because API users don't have access to
```

2020-10-01 16:40 UTC, bogdandrutu commented on specification/trace/api.md
> +the `Context.Key` (the name MAY be `"span_context_key"`).
It is not necessary to store the `active` Span. Is to store a span in the context. The fact that context is active or not is an orthogonal thing.

2020-10-02 12:27 UTC, arminru commented on specification/trace/api.md
> +the `Context.Key` (the name MAY be `"span_context_key"`).
What about the "the span active in a particular `Context`"?

2020-10-02 14:30 UTC, anuraaga commented on specification/trace/api.md
> +the `Context.Key` (the name MAY be `"span_context_key"`).
I guess reference to context key is too much of an implementation detail. The semantic way of saying it is, "the only way of setting the active span is through methods on the trace context utilities". Does that sound right? 

Note, of course I'm hoping the "trace context utilities" are allowed to be merged into other concepts like `TracerProvider` if it makes sense for the language as per my previous comment ;)

2020-10-05 17:03 UTC, jmacd commented
Update from the TC meeting: @bogdandrutu will re-do this PR to show the desired final state of the world.

2020-10-06 17:24 UTC, bogdandrutu commented
This is no longer needed, a different PR has been filed that fixes the entire issue, see #1063

2020-10-06 17:24 UTC, closed without merging