Resolve semantic inconsistencies for non traditional messaging
open-telemetry/opentelemetry-specification pull request #1027
Opened 2020-09-28 14:00 UTC by kenfinnigan

Fixes #977

## Changes

Update tracing semantic conventions for messaging systems to better reflect "non-traditional" approaches such as Apache Kafka.

Include recommended semantic attributes for Apache Kafka

2020-09-28 14:03 UTC, kenfinnigan commented
Can anyone share what the "check-errors" failures are?

2020-09-28 14:58 UTC, arminru commented on specification/trace/semantic_conventions/messaging.md
> +
```suggestion
```

@kenfinnigan

`markdownlint` fails with:
```
./specification/trace/semantic_conventions/messaging.md:164 MD012/no-multiple-blanks Multiple consecutive blank lines [Expected: 1; Actual: 2]
```

2020-09-28 15:34 UTC, kenfinnigan commented on specification/trace/semantic_conventions/messaging.md
> +
Thanks @arminru!

2020-09-28 16:09 UTC, kenfinnigan commented on specification/trace/semantic_conventions/messaging.md
> +| `process`      | A message that was previously received from a destination is received for processing by a message consumer/server. |
In that case I'd recommend changing the name to "processed".

For me the name "process" meant it was ready to process, not that it already had been

2020-09-28 16:11 UTC, kenfinnigan commented on specification/trace/semantic_conventions/messaging.md
> -| `messaging.temp_destination` | A boolean that is `true` if the message destination is [temporary](#temporary-destinations). | If temporary (assumed to be `false` if missing). |
"temp_destination" is meaningless in the sense that you may not know when performing the trace that a topic/queue is temporary or not.

That can happen internally within messaging systems. It's not possible to guarantee you know it is or isn't a temp destination.

In addition, does it really matter if it is or isn't temporary?

2020-09-28 16:13 UTC, kenfinnigan commented on specification/trace/semantic_conventions/messaging.md
> +| `messaging.destination_kind` | The kind of message destination: One of `queue`, `topic`, `kafka-topic`, or `mqtt-topic`. | Yes |
But a Kafka Topic is very different from a JMS Topic, for instance.

That was the reason for this addition.

If it's set to "Topic", the meaning differs depending on what the messaging system type is. It's clearer to have a separate kind.

2020-09-28 16:14 UTC, kenfinnigan commented on specification/trace/semantic_conventions/messaging.md
> -| `messaging.url` | Connection string such as `tibjmsnaming://localhost:7222` or `https://queue.amazonaws.com/80398EXAMPLE/MyQueue`. | No |
The previous attribute was removed because it's a security hole, and is also often meaningless or undeterminable.

When sending a message to a broker that's clustered, how do you know exactly which URL the message went to?

2020-09-28 16:16 UTC, kenfinnigan commented on specification/trace/semantic_conventions/messaging.md
> -| `net.peer.port` | `1234` | `1234` | `1234` |
Was deliberately removed as it's not reasonable to capture that information.

What is it meant to represent in a clustered broker situation? You don't know which of the possible brokers the message actually was processed by when sending a message

2020-09-28 16:23 UTC, kenfinnigan commented on specification/trace/semantic_conventions/messaging.md
> +| `messaging.destination_kind` | The kind of message destination: One of `queue`, `topic`, `kafka-topic`, or `mqtt-topic`. | Yes |
Put another way, how do we preclude a messaging system of "kafka" and a destination kind of "queue", as it's an invalid combination. The same with MQTT

2020-09-28 16:45 UTC, cescoffier commented on specification/trace/semantic_conventions/messaging.md
> +Traditional messaging brokers, such as JMS, use the concept of topics when a message is dispatched to potentially multiple consumers and queues when a message is dispatched to a single consumer.
Kafka, for example, but it's not limited to Kafka, uses consumer groups. Each record (message in Kafka lingo) is sent to a single consumer per consumer group. So, it's both a topic and a queue depending on the consumer groups and their composition.

2020-09-28 16:47 UTC, cescoffier commented on specification/trace/semantic_conventions/messaging.md
> -| `messaging.temp_destination` | A boolean that is `true` if the message destination is [temporary](#temporary-destinations). | If temporary (assumed to be `false` if missing). |
Kafka does not do temporary topics. It can be pretty expensive to do so.

2020-09-28 16:50 UTC, Oberon00 commented on specification/trace/semantic_conventions/messaging.md
> -| `messaging.temp_destination` | A boolean that is `true` if the message destination is [temporary](#temporary-destinations). | If temporary (assumed to be `false` if missing). |
> It's not possible to guarantee you know it is or isn't a temp destination.

> Kafka does not do temporary topics. It can be pretty expensive to do so.

OK to both statements, but why is this an argument for removing this optional attribute? It is still useful for traditional messaging systems at least.

2020-09-28 16:50 UTC, cescoffier commented on specification/trace/semantic_conventions/messaging.md
> -| `messaging.url` | Connection string such as `tibjmsnaming://localhost:7222` or `https://queue.amazonaws.com/80398EXAMPLE/MyQueue`. | No |
It's also not compatible with Kafka where you have bootstrap servers (plural). You don't know to which one you are actually sending (you write to the one hosting the leader of the partition of the topic on which you are writing).

2020-09-28 16:50 UTC, cescoffier commented on specification/trace/semantic_conventions/messaging.md
> +For Apache Kafka, the following messaging attributes are useful:
+1

2020-09-28 16:52 UTC, cescoffier commented on specification/trace/semantic_conventions/messaging.md
> +| `messaging.kafka.message_key` | Differs from `messaging.message_id` in that it's not unique, and can be `null`. |
message keys are not ids. Kafka does not have message-id (well, not visible to the user at least, there are ids for de-duplication purposes).

2020-09-28 16:52 UTC, Oberon00 commented on specification/trace/semantic_conventions/messaging.md
> +| `process`      | A message that was previously received from a destination is received for processing by a message consumer/server. |
> For me the name "process" meant it was ready to process, not that it already had been

`process` is simply what the span should set that traces the operation of the message being processed. So when you start the span, the message was ready to be processed from some unknown time before and by ending the span you signal that processing of the message is finished.

2020-09-28 16:52 UTC, cescoffier commented on specification/trace/semantic_conventions/messaging.md
> +| `messaging.kafka.consumer_group` | Name of the Kafka Consumer Group that is handling the message. |
No, consumer only (for the consumer group).

Both producer and consumer could have a client.id.

2020-09-28 16:53 UTC, kenfinnigan commented on specification/trace/semantic_conventions/messaging.md
> -| `messaging.temp_destination` | A boolean that is `true` if the message destination is [temporary](#temporary-destinations). | If temporary (assumed to be `false` if missing). |
Mostly because it's a security concern to expose that information.

If the consensus is it's not, I can add it back as optional

2020-09-28 16:53 UTC, cescoffier commented on specification/trace/semantic_conventions/messaging.md
> +| `messaging.kafka.consumer_client_id` | Client Id for the Consumer within a Consumer Group that is handling the message. |
It would make sense to just use client_id, which would apply for both producer and consumer.

2020-09-28 16:56 UTC, Oberon00 requested changes
While it is nice that messaging semantic conventions are made fit for non-traditional messaging, please also keep compatibility with traditional messaging systems (they are still in use).
It seems to me that rather just than adding support for modern messaging systems, this PR changes the old messaging conventions quite a bit more than necessary. I think at this stage it is totally OK to have a few breaking changes, but they need to be justified.

EDIT: E.g. you often remove attributes with the argument that they cannot be filled out reasonably. While this may be true for the modern messaging systems you think of, it is not true for traditional messaging systems. Equivalents of almost all of the attributes here have been successfully used within Dynatrace for a long time, and are thus certainly useful for at least some messaging systems (often JMS based).

2020-09-28 16:56 UTC, kenfinnigan commented on specification/trace/semantic_conventions/messaging.md
> +| `process`      | A message that was previously received from a destination is received for processing by a message consumer/server. |
so the span is intended to go from "receipt" by the processor, to the point of "success" or completion?

If `process` is the preferred name, I can adjust the verbiage to make it clearer about what the operation name actually refers to

2020-09-28 17:04 UTC, kenfinnigan commented on specification/trace/semantic_conventions/messaging.md
> -| `messaging.temp_destination` | A boolean that is `true` if the message destination is [temporary](#temporary-destinations). | If temporary (assumed to be `false` if missing). |
I was getting confused, it's not related to security, ignore me

2020-09-28 17:07 UTC, kenfinnigan commented on specification/trace/semantic_conventions/messaging.md
> -| `messaging.url` | Connection string such as `tibjmsnaming://localhost:7222` or `https://queue.amazonaws.com/80398EXAMPLE/MyQueue`. | No |
I can add it back with a note it only applies to traditional messaging

2020-09-28 17:11 UTC, kenfinnigan commented
@Oberon00 @arminru, thanks for the feedback.

I've revised the PR to hopefully align better with the consensus view. Apologies for being too zealous in removing some things that only apply to traditional messaging

2020-09-28 18:03 UTC, yurishkuro commented on specification/trace/semantic_conventions/messaging.md
> +Whether a specific record, or message, is processed as if it were sent to a topic or queue entirely depends on the consumer groups and their composition.
> Each record, or message
> Whether a specific record, or message

Just refer to them as messages, per semantics established in the previous sentences.

2020-09-28 18:10 UTC, yurishkuro commented on specification/trace/semantic_conventions/messaging.md
> +Destination name can be statically derived from configuration in this case, as it should contain the mapping from logical internal names to the real destination name.
In the trivial cases the application code can serve as configuration. That is different from aliasing of what's in the config to what application calls the resource. 

> This should not be statically derived from application code

There can be situations where the logical name known to the application is the only thing that is accessible to the instrumentation. I don't think it's is wrong to the application to describe the span using the logical name of the destination (the physical identity, if available, can be added as attributes).

2020-09-28 18:10 UTC, kenfinnigan commented on specification/trace/semantic_conventions/messaging.md
> +Whether a specific record, or message, is processed as if it were sent to a topic or queue entirely depends on the consumer groups and their composition.
Fixed, thanks

2020-09-28 18:20 UTC, kenfinnigan commented on specification/trace/semantic_conventions/messaging.md
> +Destination name can be statically derived from configuration in this case, as it should contain the mapping from logical internal names to the real destination name.
If the span is described with a name known only to the application internally, what is the benefit of having that on a trace?

Wouldn't it require knowledge from the person interrogating the trace to understand it's an application internal name, and thus have some way of translating that into an actual name?

2020-09-29 07:06 UTC, iNikem commented
I don't think this PR makes a clear definition of what is a traditional system and what not. If spec has wording like "Only applicable to traditional messaging systems", then we have to define in a more precise manner, which systems are "traditional" and which not.

2020-09-29 09:05 UTC, Oberon00 commented on specification/trace/semantic_conventions/messaging.md
> +Destination name can be statically derived from configuration in this case, as it should contain the mapping from logical internal names to the real destination name.
@kenfinnigan

> If the span is described with a name known only to the application internally, what is the benefit of having that on a trace?

The main purpose of the span name is to be able to group similar traces or spans together using an equal span name as the grouping criterion. So the span name should approximately indicate which code is run for that span.

Also, if you found a span to be important, you might send a trace to the development team for investigation, and they will be able to make sense of this "internal" name.

2020-09-29 09:07 UTC, Oberon00 commented on specification/trace/semantic_conventions/messaging.md
> +| `process`      | A message that was previously received from a destination is received for processing by a message consumer/server. |
> "from "receipt" by the processor,"

Well, I would not use "receipt" here, I would rather say "from the point where the processor gets passed the message". I think the usual case is that the processor is invoked with a previously received and (pre)parsed message object.

2020-09-29 09:11 UTC, Oberon00 commented on specification/trace/semantic_conventions/messaging.md
> +| `messaging.destination_kind` | The kind of message destination: One of `queue`, `topic`, `kafka-topic`, or `mqtt-topic`. | Yes |
> how do we preclude a messaging system of "kafka" and a destination kind of "queue", as it's an invalid combination

We don't. How do we preclude a messaging system of "rabbitmq" and a destination kind of "kafka-topic"? Ultimately, the onus of using the semantic conventions correctly and producing semantically valid data is on the instrumentation writer.

2020-09-29 09:25 UTC, arminru commented on specification/trace/semantic_conventions/messaging.md
> +Traditional messaging brokers, such as JMS, use the concept of topics when a message is dispatched to potentially multiple consumers and queues when a message is dispatched to a single consumer.
I see that this description was added below, thanks!

2020-09-29 09:25 UTC, arminru commented on specification/trace/semantic_conventions/messaging.md
> +Whether a specific message is processed as if it were sent to a topic or queue entirely depends on the consumer groups and their composition.
```suggestion
Whether a specific message is processed as if it was sent to a topic or queue entirely depends on the consumer groups and their composition.
```

2020-09-29 09:25 UTC, arminru commented on specification/trace/semantic_conventions/messaging.md
> +| `messaging.destination_kind` | The kind of message destination: One of `queue`, `topic`, `kafka-topic`, or `mqtt-topic`. | Yes |
`queue` would just not be used in these cases but from the combination of system=`kafka`/`mqtt` and kind=`topic`, consumers aware of this distinction will be able to detect it properly. Would these two additions be the only ones you can think of or would you expect more to come here?

Apart from that, you made it required but kept it limited to the set of values defined, which will block uses where neither of them applies. If we extend the "enum" beyond topic and queue, I'd be fine with making it required but allow custom values here. This should be well-considered, however, since custom values usually don't have any semantics known to consumers and will therefore not be available for any automated analysis.

2020-09-29 09:25 UTC, arminru commented on specification/trace/semantic_conventions/messaging.md
> +| `messaging.temp_destination` | A boolean that is `true` if the message destination is [temporary](#temporary-destinations). Only applicable to traditional messaging systems. | If temporary (assumed
```suggestion
| `messaging.temp_destination` | A boolean that is `true` if the message destination is [temporary](#temporary-destinations). | If temporary (assumed to be `false` if missing). |
```

I wouldn't say that, especially if the distinction is unclear. If a particular system has a concept of temporary destination, set the value, otherwise just don't - that's the only distinction I would make and which we already do.

2020-09-29 09:25 UTC, arminru commented on specification/trace/semantic_conventions/messaging.md
> +| `messaging.url` | Connection string such as `tibjmsnaming://localhost:7222` or `https://queue.amazonaws.com/80398EXAMPLE/MyQueue`. Only applicable to traditional messaging systems. | No |
```suggestion
| `messaging.url` | Connection string such as `tibjmsnaming://localhost:7222` or `https://queue.amazonaws.com/80398EXAMPLE/MyQueue`. | No |
```
I wouldn't say that either here since there's no clear distinction. It's an optional attribute so it's fine to only set it if it fits and is reasonable/noteworthy.

2020-09-29 09:25 UTC, arminru commented on specification/trace/semantic_conventions/messaging.md
> +| `messaging.service` | Name of the external broker, or name of the service being interacted with. | No |
```suggestion
| `messaging.service` | Name of the external broker, or name of the service being interacted with. See note below for a definition. | No |
```

2020-09-29 09:25 UTC, arminru commented on specification/trace/semantic_conventions/messaging.md
> +`messaging.service` refers to the logical name of the external broker or messaging system where a message was sent to, or received from. In an environment such as Kubernetes, it would be the Kubernet
Can you please clarify how this differs from the `peer.service` [general span attribute](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/semantic_conventions/span-general.md#general-remote-service-attributes)?

2020-09-29 09:25 UTC, arminru commented on specification/trace/semantic_conventions/messaging.md
> -Additionally at least one of `net.peer.name` or `net.peer.ip` from the [network attributes][] is required and `net.peer.port` is recommended.
Did you remove this sentence on purpose? Why?

2020-09-29 09:25 UTC, arminru commented on specification/trace/semantic_conventions/messaging.md
> +| `messaging.kafka.message_key` | Differs from `messaging.message_id` in that it's not unique, can be `null`, and doesn't have a pre-defined type. |
Which type does the attribute have? It has to be either of the attribute types defined here:
https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/common/common.md#attributes
We can't simply say "any" here because neither the API nor wire protocols support this.
You could define it as the string representation of whatever type the object has.

2020-09-29 09:25 UTC, arminru commented on specification/trace/semantic_conventions/messaging.md
> -| `net.peer.port` | `1234` | `1234` | `1234` |
This is to specify the endpoint to which the message was sent to (or received from) which should also be available in a clustered situation. Can you please elaborate?

2020-09-29 18:12 UTC, kenfinnigan commented on specification/trace/semantic_conventions/messaging.md
> +| `messaging.destination_kind` | The kind of message destination: One of `queue`, `topic`, `kafka-topic`, or `mqtt-topic`. | Yes |
My main concern was the wrong thing being done and setting "kafka" and "queue", for instance.

If there's no way to prevent that, and there's a preference for not constraining the possible values for `destination_kind` I can remove the change

2020-09-29 18:14 UTC, kenfinnigan commented on specification/trace/semantic_conventions/messaging.md
> +| `messaging.url` | Connection string such as `tibjmsnaming://localhost:7222` or `https://queue.amazonaws.com/80398EXAMPLE/MyQueue`. Only applicable to traditional messaging systems. | No |
Can you clarify what you mean by "no clear distinction"?

2020-09-29 18:16 UTC, kenfinnigan commented on specification/trace/semantic_conventions/messaging.md
> -Additionally at least one of `net.peer.name` or `net.peer.ip` from the [network attributes][] is required and `net.peer.port` is recommended.
`net.peer.name` or `net.peer.ip` are not required for Kafka, MQTT, etc.

I can change it to say it's recommended instead?

2020-09-29 18:22 UTC, kenfinnigan commented on specification/trace/semantic_conventions/messaging.md
> +`messaging.service` refers to the logical name of the external broker or messaging system where a message was sent to, or received from. In an environment such as Kubernetes, it would be the Kubernet
My impression of `peer.service` is a service running on a specific peer, or host, of a network.

In an environment like Kubernetes a single "peer", or node, can have many different services exposed on it. Meaning that sending a message to a Kafka service named "my-kafka" means more than a `peer.service` of "mycluster.kube", or some permutation thereof.

It's possible I'm missing something, but that's my impression, which is why I felt a separate `message.service` was needed. Granted there might be situations where they are the same, but in Kubernetes that would be rare

2020-09-29 18:24 UTC, kenfinnigan commented on specification/trace/semantic_conventions/messaging.md
> +| `messaging.kafka.message_key` | Differs from `messaging.message_id` in that it's not unique, can be `null`, and doesn't have a pre-defined type. |
Thanks

2020-09-29 18:36 UTC, kenfinnigan commented on specification/trace/semantic_conventions/messaging.md
> -| `net.peer.port` | `1234` | `1234` | `1234` |
If I'm sending/receiving messages with Kafka, there is no information on the consumer or producer side that knows what actual broker sent/received the message.

All the producer/consumer knows is it communicated with a particular bootstrap server to send/receive. That server is not the one that sent/received the message, nor is it constant as the cluster can be repartitioned.

2020-09-30 12:19 UTC, arminru commented on specification/trace/semantic_conventions/messaging.md
> +| `messaging.url` | Connection string such as `tibjmsnaming://localhost:7222` or `https://queue.amazonaws.com/80398EXAMPLE/MyQueue`. Only applicable to traditional messaging systems. | No |
There is no clear definition about what's considered to be a traditional or untraditional messaging system and even if there was, I don't think whether a connection string is applicable or not is dependent on that. Since it's an optional attribute, one would only set it if suitable and applicable anyway. If you think that for Kafka in particular it should be advised to _not_ set this, you could mention this in the Kafka section below including an explanation why this is the case.

2020-09-30 12:23 UTC, arminru commented on specification/trace/semantic_conventions/messaging.md
> -Additionally at least one of `net.peer.name` or `net.peer.ip` from the [network attributes][] is required and `net.peer.port` is recommended.
Wouldn't you just specify the hostname (or IP) of the broker that particular message is sent to here in case of Kafka? Or are you saying there are client libraries where this information is not available and therefore  instrumentations would merely be able to specify (one of) the bootstrap server(s) here?

2020-09-30 12:26 UTC, arminru commented on specification/trace/semantic_conventions/messaging.md
> +`messaging.service` refers to the logical name of the external broker or messaging system where a message was sent to, or received from. In an environment such as Kubernetes, it would be the Kubernet
I would interpret `peer.service` to be the particular service this span is directed at, which also works if a given peer or host exposes multiple different services.

@anuraaga do you think we could clarify this further in the spec?

2020-09-30 12:27 UTC, kenfinnigan commented on specification/trace/semantic_conventions/messaging.md
> +| `messaging.url` | Connection string such as `tibjmsnaming://localhost:7222` or `https://queue.amazonaws.com/80398EXAMPLE/MyQueue`. Only applicable to traditional messaging systems. | No |
That's fine, I think I've removed the addition of the comment in the latest version

2020-09-30 12:28 UTC, arminru commented on specification/trace/semantic_conventions/messaging.md
> -| `net.peer.port` | `1234` | `1234` | `1234` |
Would it still make sense to specify the bootstrap server as this is the direct counterpart for this span here, or would you not deem this information valuable?

2020-09-30 12:28 UTC, kenfinnigan commented on specification/trace/semantic_conventions/messaging.md
> +Destination name can be statically derived from configuration in this case, as it should contain the mapping from logical internal names to the real destination name.
I've revised the description to prefer real destination names over virtual/logical ones

2020-09-30 12:29 UTC, kenfinnigan commented on specification/trace/semantic_conventions/messaging.md
> +| `process`      | A message that was previously received from a destination is received for processing by a message consumer/server. |
I *think* I've reverted this to the original definition

2020-09-30 12:29 UTC, kenfinnigan commented on specification/trace/semantic_conventions/messaging.md
> +| `messaging.destination_kind` | The kind of message destination: One of `queue`, `topic`, `kafka-topic`, or `mqtt-topic`. | Yes |
I've removed the change.

2020-09-30 12:30 UTC, arminru commented
@kenfinnigan Please try to avoid force-pushing since this makes it harder to follow the revisions. We'll squash it anyway when merging so don't worry if you accumulate a couple of commits on your branch here 🙂

2020-09-30 12:34 UTC, kenfinnigan commented on specification/trace/semantic_conventions/messaging.md
> +`messaging.service` refers to the logical name of the external broker or messaging system where a message was sent to, or received from. In an environment such as Kubernetes, it would be the Kubernet
@arminru am I correct in saying your interpretation of `peer.service` is actually the name of the service?

From my perspective, all the other `peer.*` or `net.peer.*` information relates to specific host or network node information, which is why I see `peer.service` as referring to a service on a specific host, as opposed to a virtual service name that could be clustered across many hosts/nodes

2020-09-30 12:36 UTC, kenfinnigan commented on specification/trace/semantic_conventions/messaging.md
> -| `net.peer.port` | `1234` | `1234` | `1234` |
I don't think so, as it could disappear at any point in time.

It's the initial point to which a consumer/producer retrieves the partitions, but where messages are sent can change as the partitioned cluster changes.

From a traceability perspective, I don't think the bootstrap server names would be meaningful

2020-09-30 12:38 UTC, kenfinnigan commented on specification/trace/semantic_conventions/messaging.md
> -Additionally at least one of `net.peer.name` or `net.peer.ip` from the [network attributes][] is required and `net.peer.port` is recommended.
Such information as to where the message was sent to or received from, is not available in the Kafka clients.

As mentioned in another comment, I don't think bootstrap servers is the right information to be capturing instead

2020-09-30 12:38 UTC, arminru commented on specification/trace/semantic_conventions/messaging.md
> +| `messaging.destination_kind` | `"topic"` | `"topic"` | `"topic"` | `"topic"` | `"topic"` |
Ah, now I see why you were concerned about queue being used in conjunction with Kafka. These examples are rather intended to illustrate how the general concept of batch receiving and processing from a queue is intended to work rather than addressing technical details of a particular messaging system. Feel free to just use another value for `messaging.system` to fix this inconsistency of Kafka and queue being used in conjunction.
It would be great if you could add a separate example for Kafka in particular that shows appropriate values for attributes in the `messaging.kafka.*` namespace.

2020-09-30 12:39 UTC, kenfinnigan commented
@arminru it was easier to collapse my commits to rebase as the entire structure of the attribute table was changed yesterday.

Sorry if that made things confusing

2020-09-30 12:42 UTC, arminru commented on specification/trace/semantic_conventions/messaging.md
> +`messaging.service` refers to the logical name of the external broker or messaging system where a message was sent to, or received from. In an environment such as Kubernetes, it would be the Kubernet
Yes. `net.*` is about lower-level networking information where `net.peer.*` is about the host on the other end. `peer.service` on the other hand is about the higher-level service. I don't think there's any other `peer.*` attribute.

2020-09-30 12:45 UTC, arminru commented
@kevingosse I see, yes, adding the YAML representation of the semantic convention which is used for automatically generating the table unfortunately interfered with your PR. Feel free to keep editing the Markdown manually and discussing things there if that's easier for you and then adapt the respective YAML file (`semantic_conventions/trace/messaging.yaml`) afterwards in order to be consistent (and have a green build).

2020-09-30 17:21 UTC, kenfinnigan commented on specification/trace/semantic_conventions/messaging.md
> +`messaging.service` refers to the logical name of the external broker or messaging system where a message was sent to, or received from. In an environment such as Kubernetes, it would be the Kubernet
That's where I don't see it aligning.

A virtual service, such as in Kubernetes, happens to be running a node (peer) of the network but that doesn't define the name it's known by. Nodes (peers) come and go, but the name of the virtual service will be the same. It's in that context that I don't see `peer.service` being the same as `messaging.service`

2020-10-01 05:25 UTC, iNikem commented on specification/trace/semantic_conventions/messaging.md
> +`messaging.service` refers to the logical name of the external broker or messaging system where a message was sent to, or received from. In an environment such as Kubernetes, it would be the Kubernet
`peer.service`
> SHOULD be equal to the actual service.name resource attribute of the remote service if any

Resource's `service.name`:
> Logical name of the service. MUST be the same for all instances of horizontally scaled services.

Therefore `peer.service` is not related anyhow to a physical or virtual node. Your definition of `messaging.service` duplicates the above definition of `peer.service`.

2020-10-01 05:30 UTC, iNikem commented on specification/trace/semantic_conventions/messaging.md
> -Additionally at least one of `net.peer.name` or `net.peer.ip` from the [network attributes][] is required and `net.peer.port` is recommended.
This is not technically correct. There is `org.apache.kafka.clients.consumer.Consumer#partitionsFor` which gives you a leader node for a given topic and partition. `Producer` gives the same metadata. `ConsumerRebalanceListener` can be used to refresh that metadata when it changes.

Thus you can get that information for Kafka. Is it feasible or not is totally separate question.

2020-10-01 05:46 UTC, cescoffier commented on specification/trace/semantic_conventions/messaging.md
> -Additionally at least one of `net.peer.name` or `net.peer.ip` from the [network attributes][] is required and `net.peer.port` is recommended.
Yes, you can have an idea of the leader, however, this data may not be fresh as you may be checking while rebalancing is in progress (I'm not sure what would be the returned value in this case especially if the partition gets revoked). In general, in Kafka, don't need to know who's the leader of a partition.

2020-10-01 09:06 UTC, arminru commented on specification/trace/semantic_conventions/messaging.md
> +| Links |  |  | Span Rcv1 | Span Prod1 |  |
```suggestion
| Parent |  | Span Prod1 | Span Rcv1 | Span Proc1 | Span Prod2 |
| Links |  |  | Span Prod1 |  |  |
```
Proc1's parent would be Rcv1 in this case as it's Proc1's direct predecessor and Prod1 would be added as a link.
Same for Prod2 being a child of Proc1.

2020-10-01 09:18 UTC, arminru commented on specification/trace/semantic_conventions/messaging.md
> +`messaging.service` refers to the logical name of the external broker or messaging system where a message was sent to, or received from. In an environment such as Kubernetes, it would be the Kubernet
I agree with @iNikem. If you find the `peer.service` particularly useful for messaging service, you could add a note in this semantic convention referencing it and saying that it is recommended to be added for messaging services. There is no need, however, to duplicate it. This would only lead to confusion since instrumentation authors would not know if they should leave out `peer.service` in this case or provide the same value for both attributes, which wouldn't make sense either. Consumers will also likely pick up `peer.service` in a generic handler and would have to handle collisions if `messaging.service` having the same meaning would be set additionally.

2020-10-01 11:00 UTC, Oberon00 commented on specification/trace/semantic_conventions/messaging.md
> +`messaging.service` refers to the logical name of the external broker or messaging system where a message was sent to, or received from. In an environment such as Kubernetes, it would be the Kubernet
I'm not sure about that. The peer.service attribute is something that is expected to be manually configured by the user, not automatically determined by the instrumentation.

See https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/semantic_conventions/span-general.md#general-remote-service-attributes 

>  Users can define what the name of a service is based on their particular semantics in their distributed system. Instrumentations SHOULD provide a way for users to configure this name.
...
> Examples of peer.service that users may specify:

CC @anuraaga who introduced peer.service in #652

Still it sounds like this concept is not specific to messaging, so maybe we should have peer.detected_service if peer.service is otherwise fitting.

2020-10-01 12:52 UTC, kenfinnigan commented on specification/trace/semantic_conventions/messaging.md
> +`messaging.service` refers to the logical name of the external broker or messaging system where a message was sent to, or received from. In an environment such as Kubernetes, it would be the Kubernet
@iNikem did you mean `messaging.service` duplicates `peer.service` or Resource's `service.name`? Personally, it maybe overlaps with the latter and not the former.

I don't see `peer.service` being a great name for what it is, but if that's the preferred approach I will remove `messaging.service`

2020-10-01 13:20 UTC, kenfinnigan commented on specification/trace/semantic_conventions/messaging.md
> +| Links |  |  | Span Rcv1 | Span Prod1 |  |
I can understand the reasoning for Proc1's parent being Rcv1, but Prod2 is not a child of Proc1.

The reasoning is that in Kafka the producing of a message is disconnected in time from when, or how often, that message is processed.

In this situation, Prod2 may be processed quickly, or it could be days/weeks/months before it's processed. From a span perspective, I don't think it should have a parent of Proc1 due to that timing disconnect.

2020-10-01 13:24 UTC, kenfinnigan commented on specification/trace/semantic_conventions/messaging.md
> -Additionally at least one of `net.peer.name` or `net.peer.ip` from the [network attributes][] is required and `net.peer.port` is recommended.
@iNikem Saying information is available somewhere is meaningless if it can't be proven to be accessible. From an instrumentation perspective, it might be possible to retrieve that information, but if it can't be done by frameworks or user applications, for me that makes it unusable.

Separate to that is the meaning. If it's an ephemeral value that is subject to frequent change, what is the value in capturing that information?

Why is there a concern about messaging systems such as Apache Kafka not defining these values?

2020-10-01 13:50 UTC, arminru commented on specification/trace/semantic_conventions/messaging.md
> +`messaging.service` refers to the logical name of the external broker or messaging system where a message was sent to, or received from. In an environment such as Kubernetes, it would be the Kubernet
They actually belong together.
Given, for example, a client A sending a request to a server process B exposing a service called `X`:
A creates a span for the request and sets `peer.service="X"`
B, on the other end, sets `service.name="X"` on its resource, which will be added to a span it creates for tracking the processing of A's request

2020-10-01 14:13 UTC, kenfinnigan commented on specification/trace/semantic_conventions/messaging.md
> +`messaging.service` refers to the logical name of the external broker or messaging system where a message was sent to, or received from. In an environment such as Kubernetes, it would be the Kubernet
Thanks @arminru, it hasn't been clear where Resource fits, that helps.

I will drop `message.service` and use `peer.service`

2020-10-01 14:21 UTC, arminru commented on specification/trace/semantic_conventions/messaging.md
> +`messaging.service` refers to the logical name of the external broker or messaging system where a message was sent to, or received from. In an environment such as Kubernetes, it would be the Kubernet
Thanks! Please add a note in the Kafka section saying it is recommended to set this and how to determine the appropriate value to make sure instrumentation writers are aware of it.

@anuraaga please verify if you think it's fine that instrumentations set this automatically (while still allowing users to override it, although I'm not really sure how this will work in practice).

2020-10-01 14:26 UTC, kenfinnigan commented on specification/trace/semantic_conventions/messaging.md
> +| Links |  |  | Span Rcv1 | Span Prod1 |  |
Yes it is performed as part of processing the first message. However, in reactive messaging and event-driven architectures there isn't always a "parent-child" connection, it's more like a correlation or link relationship. They *may* be "parent-child", but not always.

If it is added as a parent, and it hasn't had any further span, doesn't that leave the parent span/trace unclosed? Does that make sense for reporting?

2020-10-01 14:54 UTC, Oberon00 commented on specification/trace/semantic_conventions/messaging.md
> +| Links |  |  | Span Rcv1 | Span Prod1 |  |
Related #958 / CC @anuraaga wanted kinda the opposite there.

2020-10-01 15:04 UTC, kenfinnigan commented on specification/trace/semantic_conventions/messaging.md
> +| Links |  |  | Span Rcv1 | Span Prod1 |  |
Thanks @Oberon00, I knew there was a better term but couldn't think of it. Reading the issue made me realize it was "follows-from".

So for reactive messaging and event-driven, producing a new message while processing an existing message is more a "follows-from" relationship as opposed to parent-child, which is why I had used Links

2020-10-01 17:24 UTC, iNikem commented on specification/trace/semantic_conventions/messaging.md
> -Additionally at least one of `net.peer.name` or `net.peer.ip` from the [network attributes][] is required and `net.peer.port` is recommended.
`net.*` attributes, which by semantic convention can be applied to all spans, allow for constructing an accurate network-level map of monitored distributed system. Together with metrics it can help end-user to discover that these specific nodes has higher than usual error rate. And potentially even take a remedial action, such as take faulty nodes down.

>it's an ephemeral value that is subject to frequent change

Frequency of change is very subjective. You may have a fixed cluster of Kafka brokers. In fact, Kafka being a "storage service", I would expect Kafka nodes to live at least days, if not weeks, but certainly not minutes or hours. To call them "ephemeral" is an exaggeration.

2020-10-01 17:46 UTC, kenfinnigan commented on specification/trace/semantic_conventions/messaging.md
> -Additionally at least one of `net.peer.name` or `net.peer.ip` from the [network attributes][] is required and `net.peer.port` is recommended.
It might be a stretch, it's not a complete exaggeration.

What diagnosis can happen in a situation where a network-level map contains `net.*` attributes for nodes that are no longer present in the system?

I can certainly see there would be situations where it's necessary to "spin up" another Kafka broker to handle a spike in messages and then disappear again. Isn't that what Kubernetes offers, the power and ease to scale up and then down again?

Granted, there will definitely be peers that are essentially "always there", or near enough, but I still think that information should be a "recommendation" and not a "requirement"

2020-10-01 18:06 UTC, iNikem commented on specification/trace/semantic_conventions/messaging.md
> -Additionally at least one of `net.peer.name` or `net.peer.ip` from the [network attributes][] is required and `net.peer.port` is recommended.
I am fine with recommendation.

I hope you don't tear down your Kafka nodes after incoming spike ends. At least wait for all messages to be processed :) Also, event-sourcing systems cannot allow for node disappearing. You have to persist all relevant data. All in all, short-lived Kafka nodes in production is a novel concept to me.

2020-10-01 18:39 UTC, kenfinnigan commented
@arminru @Oberon00 I *think* I've resolved any problems or concerns, please let me know if I missed something.

Can someone also let me know what the error is on the markdown job, thanks?

2020-10-02 10:20 UTC, arminru reviewed
@kenfinnigan

Regarding the build: It verifies that the entire text between `<!-- semconv messaging -->` and `<!-- endsemconv -->` in the markdown is identical to what the markdown generator would generate (since we wanted to have both the YAML definition as well as the rendered MD stored in the repo for better accessibility). If you remove your change in line 128/132, it will be identical and the build will pass. If you think specifying the host is not possible in some cases (as you laid out in https://github.com/open-telemetry/opentelemetry-specification/pull/1027#discussion_r496567330), you can edit the YAML to not make them not required but recommended.

This can be done by adding
```
- ref: net.peer.name
  required:
    conditional: If available.
- ref: net.peer.ip
  tag: connection-level
  required:
    conditional: If available.
```

instead of

```
constraints:
  - any_of:
    - 'net.peer.name'
    - 'net.peer.ip'
```

Please also add the Kafka attributes you introduced at the end of `messaging.yaml` and have the table generated by adding `<!-- semconv messaging.kafka -->` and `<!-- endsemconv -->` markers in the Kafka section in the Markdown. By updating the YAML, you'll also make your attributes available to code generators creating constants for use by (auto) instrumentations.

```
    - id: messaging.kafka
      prefix: messaging.kafka
      extends: messaging
      brief: >
        Attributes for Apache Kafka
      attributes:
        - id: message_key
          type: string
          brief: >
            Message keys in Kafka are used for ...
            They differ from `messaging.message_id` in that they're not unique.
            If they key is `null`, the attribute MUST NOT be set.
          note: >
            If the key type is not string, it's string representation has to be supplied for the attribute.
          examples: 'myKey'
...
```

`null` values for span attributes are undefined behavior, therefore the "If they key is `null`, the attribute MUST NOT be set.".

2020-10-02 10:20 UTC, arminru commented on specification/trace/semantic_conventions/messaging.md
> +For Apache Kafka producers, `peer.service` should be set to the name of the broker or external service the message will be sent to.
```suggestion
For Apache Kafka producers, [`peer.service`](./span-general.md#general-remote-service-attributes) SHOULD be set to the name of the broker or external service the message will be sent to.
```

This could also be achieved by using `- ref` with a note in the Kafka section of the YAML file.

2020-10-02 10:20 UTC, arminru commented on specification/trace/semantic_conventions/messaging.md
> +Consumers should set `service.name` as the Resource receiving the message. The value should match `peer.service` set by a Producer.
This sentence is unclear to me and I think it can be left out as it does not really add anything to the definition we have here:
https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/resource/semantic_conventions/README.md#service

2020-10-02 11:09 UTC, Oberon00 commented on specification/trace/semantic_conventions/messaging.md
> -Additionally at least one of `net.peer.name` or `net.peer.ip` from the [network attributes][] is required and `net.peer.port` is recommended.
> What diagnosis can happen in a situation where a network-level map contains net.* attributes for nodes that are no longer present in the system?

You can cross-reference logs, where the kafka nodes may log their IP when starting.

2020-10-02 15:30 UTC, kenfinnigan commented
Thanks @arminru for the detailed explanation of what was needed.

Hopefully I've got it right and the build passes

2020-10-05 12:27 UTC, arminru commented
@kenfinnigan Yes, it looks better now. Now that you've added your Kafka attributes in the YAML and the markers in the Markdown, you'll have to run the table generator once to have the tables generated as described here:
https://github.com/open-telemetry/opentelemetry-specification/blob/master/semantic_conventions/README.md
Afterwards the PR check verifying that YAML+MD are in sync should pass.

2020-10-05 14:21 UTC, kenfinnigan commented
Thanks @arminru, I hadn't seen that note on how to generate the table.

I've updated the PR with the result of running it

2020-10-07 15:31 UTC, kenfinnigan commented
I believe I've resolved all the concerns that were raised.

If that's the case, what's the "next steps" for getting approvals and merging?

2020-10-07 15:47 UTC, arminru reviewed
Thanks, @kenfinnigan!
Your PR looks good to me so far, except for where I left a few final comments.

@open-telemetry/specs-approvers @open-telemetry/specs-trace-approvers please take a look as well.

2020-10-07 15:47 UTC, arminru commented on specification/trace/semantic_conventions/messaging.md
> +Consumers SHOULD identify the [Resource](../../resource/semantic_conventions/README.md#service) that received the message.
I don't understand this sentence. Please clarify.

2020-10-07 15:47 UTC, arminru commented on specification/trace/semantic_conventions/messaging.md
> +The `service.name` of a Consumer's Resource SHOULD match the `peer.service` of the Producer.
As per the sentence above, `peer.service` on the producer span refers to the broker the message is sent to. `service.name` on the consumer's resource will be its own service name and not the name of the broker.

2020-10-07 15:47 UTC, arminru commented on specification/trace/semantic_conventions/messaging.md
> +| `messaging.service` | `"myRabbitMQ"` | `"myRabbitMQ"` | `"myRabbitMQ"` |
```suggestion
```

You've removed this attribute again in the meantime in favor of using `peer.service`. Same for the two examples below.

2020-10-07 15:47 UTC, arminru commented on specification/trace/semantic_conventions/messaging.md
> -| `messaging.message_id` | `"a1"` | `"a1"`| `"a1"` |
Please leave this as-is since Message IDs are fine here.

2020-10-07 17:22 UTC, kenfinnigan commented on specification/trace/semantic_conventions/messaging.md
> +Consumers SHOULD identify the [Resource](../../resource/semantic_conventions/README.md#service) that received the message.
It was an attempt to indicate that the Consumer trace should have a `Resource` associated with it of the broker service that received the message.

If it's not important, I can remove, or alternative wording appreciated

2020-10-07 17:23 UTC, kenfinnigan commented on specification/trace/semantic_conventions/messaging.md
> +The `service.name` of a Consumer's Resource SHOULD match the `peer.service` of the Producer.
Ok, which is different that I think what was mentioned in another comment where it was stated the `peer.service` on producer should match `service.name` on Consumer.

Is there no direct link/association/matching needed? If not I can remove this bit

2020-10-07 17:27 UTC, kenfinnigan commented on specification/trace/semantic_conventions/messaging.md
> -| `messaging.message_id` | `"a1"` | `"a1"`| `"a1"` |
Oops, will fix

2020-10-07 17:30 UTC, kenfinnigan commented on specification/trace/semantic_conventions/messaging.md
> +| `messaging.service` | `"myRabbitMQ"` | `"myRabbitMQ"` | `"myRabbitMQ"` |
Will remove, looks like I missed it in the examples

2020-10-07 17:54 UTC, iNikem commented on specification/trace/semantic_conventions/messaging.md
> +The `service.name` of a Consumer's Resource SHOULD match the `peer.service` of the Producer.
In this case, when there is an intermediary (broker), they indeed will not match.

2020-10-07 18:50 UTC, kenfinnigan commented
I've updated the wording around `peer.service` and `service.name`, hopefully making it clearer.

2020-10-09 13:39 UTC, arminru commented on specification/trace/semantic_conventions/messaging.md
> +Consumers SHOULD identify the [Resource](../../resource/semantic_conventions/README.md#service) that received the message.
With the wording in 2f442b3ff0, it now makes sense. Thanks!

2020-10-09 13:41 UTC, arminru approved these changes
LGTM now, thanks @kenfinnigan!

2020-10-09 13:41 UTC, kenfinnigan commented
Thanks @arminru for the feedback and helping me resolve the issues

2020-10-09 13:50 UTC, Oberon00 commented on semantic_conventions/trace/messaging.yaml
> +            conditional: If available.
I did not follow recent discussion, so maybe this is redundant but: Note that in theory this also makes sense for cluster-based brokers. In the end, each span represents one message and each message is sent to one broker only (I think). So in theory, this would be the IP/hostname of the broker this specific message is sent to, instead of some IP of some cluster master node or something.

Maybe a `note` should be added here in addition to the `ref`.

2020-10-09 13:52 UTC, kenfinnigan commented on semantic_conventions/trace/messaging.yaml
> +            conditional: If available.
What would you suggest for a note?

2020-10-09 14:05 UTC, Oberon00 commented on specification/trace/semantic_conventions/messaging.md
> +Traditional messaging brokers, such as JMS, use the concept of topics when a message is dispatched to potentially multiple consumers and queues when a message is dispatched to a single consumer.
It seems this should be merged/moved into the Destination section that follows.

2020-10-09 14:05 UTC, Oberon00 commented on specification/trace/semantic_conventions/messaging.md
> +Traditional messaging involves two kinds of destinations: *topic*s and *queue*s.
Here I would expect a description of "consumer group" along with the "traditional" types.

2020-10-09 14:05 UTC, Oberon00 commented on specification/trace/semantic_conventions/messaging.md
> +In some messaging systems, a message can receive a reply message, or possibly multiple, that answers a particular other message that was sent earlier. All messages that are grouped together by such a
```suggestion
In some messaging systems, a message can receive one or more a reply messages that answers a particular other message that was sent earlier. All messages that are grouped together by such a reply-relationship are called a *conversation*.
```

2020-10-09 14:05 UTC, Oberon00 commented on specification/trace/semantic_conventions/messaging.md
> +Wherever possible, the preference is to use real destination names over logical or aliased names.
What does "real" mean here? Would "canonical" or "resolved" be better?

2020-10-09 14:07 UTC, Oberon00 commented on semantic_conventions/trace/messaging.yaml
> +            conditional: If available.
What about this:

> This should be the IP/hostname of the broker (or other network-level peer) this specific message is sent to/received from.

2020-10-09 14:41 UTC, kenfinnigan commented on semantic_conventions/trace/messaging.yaml
> +            If the key type is not string, it's string representation has to be supplied for the attribute.
I'll add mention of JSON, but also add a note that if the key value can't be represented as a string in any way, don't include it.

2020-10-09 14:42 UTC, kenfinnigan commented on semantic_conventions/trace/messaging.yaml
> +          examples: 'myKey'
Is there an alternative you'd prefer?

Keys can literally be anything

2020-10-09 14:47 UTC, kenfinnigan commented on semantic_conventions/trace/messaging.yaml
> +          examples: '5'
I'll modify the example, as it's definitely a string

2020-10-09 14:47 UTC, kenfinnigan commented on semantic_conventions/trace/messaging.yaml
> +          examples: '2'
Will change type to `number`

2020-10-09 14:50 UTC, kenfinnigan commented on specification/trace/semantic_conventions/messaging.md
> -* Physically: some message *broker* (which can be e.g., a single server, or a cluster, or a local process reached via IPC). The broker handles the actual routing, delivery, re-delivery, persistence,
For Kafka, there is a leader of the cluster, but all the instances are brokers. There is not a single broker.

2020-10-09 14:55 UTC, kenfinnigan commented on specification/trace/semantic_conventions/messaging.md
> +Wherever possible, the preference is to use real destination names over logical or aliased names.
by "real" I meant the actual name of the topic/queue that the message is being sent to.

I'm not sure "canonical" or "resolved" align with "real". Maybe "actual"?

2020-10-09 15:02 UTC, kenfinnigan commented on specification/trace/semantic_conventions/messaging.md
> +In a messaging system such as Apache Kafka, consumer groups are used. Each record, or message, is sent to a single consumer per consumer group.
I'll add "For instance, there can be multiple consumer groups retrieving records from the same topic in Kafka." to the end of the section.

Yes it acts as a queue if there is only one consumer group, but when there are multiple consumer groups it doesn't

2020-10-09 15:03 UTC, kenfinnigan commented on specification/trace/semantic_conventions/messaging.md
> +Whether a specific message is processed as if it was sent to a topic or queue entirely depends on the consumer groups and their composition.
I think the extra line I'm adding, mentioned in the previous comment, will resolve the confusion

2020-10-09 15:10 UTC, Oberon00 commented on semantic_conventions/trace/messaging.yaml
> +            If the key type is not string, it's string representation has to be supplied for the attribute.
Is JSON really suitable here? What kinds of keys are we talking about?

2020-10-09 15:11 UTC, Oberon00 commented on semantic_conventions/trace/messaging.yaml
> +          examples: 'myKey'
If keys are something user-defined, that's fine. However, if you decide to go with JSON, you should probably add the inner quotes (hopefully this looks sensible in the generated markdown then).

2020-10-09 15:12 UTC, kenfinnigan commented on specification/trace/semantic_conventions/messaging.md
> +Traditional messaging brokers, such as JMS, use the concept of topics when a message is dispatched to potentially multiple consumers and queues when a message is dispatched to a single consumer.
Will move and adjust

2020-10-09 15:13 UTC, Oberon00 commented on specification/trace/semantic_conventions/messaging.md
> -* Physically: some message *broker* (which can be e.g., a single server, or a cluster, or a local process reached via IPC). The broker handles the actual routing, delivery, re-delivery, persistence,
OK, but I don't see how this contradicts the wording here? Physically each single message is still sent to a single broker within the cluster.

2020-10-09 15:14 UTC, kenfinnigan commented on semantic_conventions/trace/messaging.yaml
> +            If the key type is not string, it's string representation has to be supplied for the attribute.
They could be objects, or basically anything, even `null`

2020-10-09 15:14 UTC, Oberon00 commented on specification/trace/semantic_conventions/messaging.md
> +Wherever possible, the preference is to use real destination names over logical or aliased names.
Maybe this would be more clear:

```suggestion
Wherever possible, the preference is to use real destination names after resolving logical or aliased names.
```

2020-10-09 15:16 UTC, kenfinnigan commented on semantic_conventions/trace/messaging.yaml
> +          examples: 'myKey'
They're definitely user-defined, so what's the best way to represent that here?

2020-10-09 15:26 UTC, kenfinnigan commented on specification/trace/semantic_conventions/messaging.md
> -* Physically: some message *broker* (which can be e.g., a single server, or a cluster, or a local process reached via IPC). The broker handles the actual routing, delivery, re-delivery, persistence,
I'm going to try and reword to re-add, as Kafka doesn't do routing in the brokers, it's done before it gets to the brokers

2020-10-09 15:26 UTC, Oberon00 commented on semantic_conventions/trace/messaging.yaml
> +          examples: 'myKey'
According to https://cwiki.apache.org/confluence/display/KAFKA/A+Guide+To+The+Kafka+Protocol, the key is a just a bytestring to Kafka. If that is correct I'd suggest using either a lowercase hex string (since most SDKs will have this implemented already for trace/span ID handling) or, if we expect large keys, a base64 string (without the trailing `=`)

2020-10-09 15:30 UTC, Oberon00 commented on specification/trace/semantic_conventions/messaging.md
> -* Physically: some message *broker* (which can be e.g., a single server, or a cluster, or a local process reached via IPC). The broker handles the actual routing, delivery, re-delivery, persistence,
The "routing" meant here is the routing of the received message to other brokers, the consumers, permanent storage, etc. The routing you mean is probably the client-side selection of a broker? But anyway, since it already says, "delivery, re-delivery, persistence, etc.", writing "routing" here is actually redundant/misleading, so I'm fine with removing that word.

2020-10-09 15:43 UTC, kenfinnigan commented on semantic_conventions/trace/messaging.yaml
> +          examples: 'myKey'
I'm still learning as I go too!

I will add a note about not including the key value if it can't be represented as a string, and will see if we need to tweak it in the future.

Does that sound ok?

2020-10-09 15:55 UTC, kenfinnigan commented
I *think* I covered your feedback @Oberon00. If I missed something, let me know

2020-10-09 16:19 UTC, Oberon00 commented on semantic_conventions/trace/messaging.yaml
> +          examples: 'myKey'
That certainly sounds like the safest option 👍

2020-10-09 16:23 UTC, Oberon00 commented on semantic_conventions/trace/messaging.yaml
> +            If the key can not be represented in string form, don't include its value.
I think you can find a string representation for everything if you try. So maybe we should say

```suggestion
            If the key has no unambiguous, canonical string form, don't include its value.
```

2020-10-09 16:26 UTC, Oberon00 commented on specification/trace/semantic_conventions/messaging.md
> +In a messaging system such as Apache Kafka, all destinations are *topic*s.
Hmm, that wording is dangerous, you make readers think that they should use "destination_kind=topic"

2020-10-09 16:33 UTC, Oberon00 approved these changes
Thank you very much for this PR & all the work of processing comments!

I think this is mostly ready now, though I would prefer if https://github.com/open-telemetry/opentelemetry-specification/pull/1027#discussion_r502542605 was resolved before merging (confirmed to be OK or reworded).

2020-10-09 16:35 UTC, kenfinnigan commented on specification/trace/semantic_conventions/messaging.md
> +In a messaging system such as Apache Kafka, all destinations are *topic*s.
For Kafka, `destination_kind` should always be `topic`

2020-10-12 12:20 UTC, kenfinnigan commented
Do this need more approvals or can it be merged? It's needed for work around metrics for messaging systems, thanks

2020-10-12 12:28 UTC, Oberon00 commented
@kenfinnigan Approvals need to come from at least two different companies I think and @arminru and me are both from @Dynatrace. So this would indeed need at least one more approval. See https://github.com/open-telemetry/opentelemetry-specification/blob/master/CONTRIBUTING.md#how-to-get-your-pr-merged

CC @open-telemetry/specs-approvers If you have time, this PR is ready for review.

2020-10-12 12:36 UTC, kenfinnigan commented
Thanks @Oberon00

2020-10-12 15:58 UTC, arminru approved these changes

2020-10-15 12:30 UTC, kenfinnigan commented
@anuraaga do you have a few minutes to review/approve this, it would be good to get it included. Thanks

2020-10-15 13:12 UTC, anuraaga reviewed
So sorry for the slow review on this - been procrastinating context switching back to messaging, a hard problem which I appreciate the help with :)

Left one comment since it'd be great to make sure we get the spec and instrumentation in sync.

2020-10-15 13:12 UTC, anuraaga commented on specification/trace/semantic_conventions/messaging.md
> +#### Apache Kafka
We have a tombstone filled in the instrumentation currently, is it useful to have here?

https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/f23ad29187ecea4e742e1dd6a5baeb84020298d4/instrumentation/kafka-clients-0.11/src/main/java/io/opentelemetry/javaagent/instrumentation/kafkaclients/KafkaProducerTracer.java#L52

If not it's ok and we can remove it from the Instrumentation. But this seems like the right time to get out instrumentation synced up with the spec.

2020-10-15 13:12 UTC, anuraaga commented on specification/trace/semantic_conventions/messaging.md
> +#### Apache Kafka
I might also consider separating out a subfolder for messaging implementations as per #968 - there are so many of them that I worry a single doc just gets unwieldy.

2020-10-15 13:23 UTC, kenfinnigan commented on specification/trace/semantic_conventions/messaging.md
> +#### Apache Kafka
No problems with the delay, I appreciate everyone is super busy right now and context switching IS difficult.

I can see it being beneficial to identify if a particular trace is related to a tombstone record. I can add it to the Kafka section.

Can the splitting be done in a subsequent PR, or you'd prefer to include it here as well? I can certainly follow up with such a change.

2020-10-15 15:25 UTC, kenfinnigan commented
I've added "tombstone" for Kafka as instrumentation already utilizes it.

2020-10-19 17:13 UTC, kenfinnigan commented
@anuraaga @arminru @Oberon00 is one of you able to restart the CI, looks like "EasyCLA" check hung.

Thanks

2020-10-19 19:09 UTC, Oberon00 commented
Closed & reopened to trigger EasyCLA

2020-10-20 00:38 UTC, anuraaga commented on specification/trace/semantic_conventions/messaging.md
> +#### Apache Kafka
Splitting in a separate PR sounds great, thanks

2020-10-20 00:38 UTC, anuraaga approved these changes
Thanks!

2020-10-20 14:54 UTC, kenfinnigan commented
Is this good to be merged or does it require additional approvers?

2020-10-20 16:05 UTC, arminru commented
@iNikem had quite some comments/opinions here, so if he deems these solved or otherwise properly addressed, we should be good to merge it. This PR has been open long enough for others to take a look already.

2020-10-21 08:04 UTC, iNikem approved these changes

2020-10-21 08:04 UTC, iNikem commented
@arminru good to go from me

2020-10-21 13:28 UTC, merged

2020-10-21 13:29 UTC, arminru commented
Thanks again for your contribution, @kenfinnigan!

2020-10-21 13:33 UTC, kenfinnigan commented
No problem, thanks for the help in getting it merged