Clarify context interaction for trace module
open-telemetry/opentelemetry-specification pull request #1063
Opened 2020-10-06 17:21 UTC by bogdandrutu

Signed-off-by: Bogdan Drutu <bogdandrutu@gmail.com>

Fixes #1019

2020-10-06 21:30 UTC, mwear commented on specification/trace/api.md
> -The `Tracer` MAY provide functions to:
I would prefer that we keep the option for these methods to be on a tracer instance. I made a prototype for Ruby (https://github.com/open-telemetry/opentelemetry-ruby/pull/425) that is implemented this way. Instead of implementing them as class methods, I introduced the notion of a default tracer. When a user doesn't already have a handle on a tracer, they can use the default tracer for span operations such as these. These allows for a clean API as all span operations live on a tracer instance.

2020-10-06 22:04 UTC, bogdandrutu commented on specification/trace/api.md
> -The `Tracer` MAY provide functions to:
See line 157, what is wrong with that? It says the functionality can leave on the tracer class, but avoids duplicating of the same functionality

2020-10-07 01:15 UTC, carlosalberto commented on specification/trace/api.md
> +All the above functionalities operate solely on the context API, and they MAY be
Use "either" here? Otherwise it may be interpreted as languages having the freedom to expose this one or more of the mentioned locations - which is exactly what we don't want :)

2020-10-07 02:39 UTC, anuraaga commented on specification/trace/api.md
> +exposed as static methode on the trace module, as static methods on a class
```suggestion
exposed as static methods on the trace module, as static methods on a class
```

2020-10-07 02:39 UTC, anuraaga commented on specification/trace/api.md
> +If the languages has support for implicitly propagated `Context`, see
```suggestion
If the language has support for implicitly propagated `Context`, see
```

2020-10-07 02:39 UTC, anuraaga commented on specification/trace/api.md
> +All the above functionalities operate solely on the context API, and they MAY be
I don't understand the difference between "all" and "either". So I'm trying to interpret the point about not having the freedom to expose in one or more locations - are you saying we don't want e.g., `TracerProvider` to give access to the current span, and `Tracer` to delegate to that as a shortcut? Or `static Span.current` delegate to something like `getGlobalTracerProvider().getCurrentSpan()`? Shortcuts can make users delighted, and I don't think the spec should forbid them.

2020-10-07 02:39 UTC, anuraaga commented on specification/trace/api.md
> +This section defines all operations within trace module that interact with the
I think this is the first time I see the word "trace module", is tracing like before more consistent?

2020-10-07 11:33 UTC, Oberon00 commented on specification/trace/api.md
> +[`Tracer`](#tracer) class.
I think we are again missing notes on overridablility here. Probably we want this to be fully implemented in the API again and not overridable. If it's in the tracer or tracerprovider, that would be different, then I would expect it to be overridable.

2020-10-07 14:14 UTC, bogdandrutu commented on specification/trace/api.md
> +All the above functionalities operate solely on the context API, and they MAY be
Are you suggesting to encourage duplicate code and functionality in the API? I feel that is very dangerous for us, and will require a lot of work to maintain backwards compatibility, and will make progress harder.

I would be against us allowing duplicate functionality in the API (avoid confusion for the user), but I am ok to split this into 2 parts (as described by the specs) if that makes things simpler to use.

2020-10-07 15:35 UTC, arminru commented on specification/trace/api.md
> +access to the [Context's Key](../context/context.md#create-a-key).
There can be many keys in a context. What about:
```suggestion
access to the [Context Key](../context/context.md#create-a-key) used by the Tracing API implementation.
```

2020-10-07 15:35 UTC, arminru commented on specification/trace/api.md
> +This section defines all operations within trace module that interact with the
```suggestion
This section defines all operations within the Tracing API that interact with the
```

2020-10-07 15:35 UTC, arminru commented on specification/trace/api.md
> +the following functionality:
```suggestion
If the language has support for implicitly propagated `Context` (see
[here](../context/context.md#optional-global-operations)), the API SHOULD also provide
the following functionality:
```

Otherwise it's not clear that the condition applies to that sentence as well and not only to when to "see here".

2020-10-07 15:50 UTC, carlosalberto commented on specification/trace/api.md
> +[`Tracer`](#tracer) class.
Would a note on users NOT being encouraged to override this would be enough? I feel that for some languages it makes more sense to have these methods in the `Tracer`, and being overridable is only an unintended side effect.

2020-10-07 16:05 UTC, mwear commented on specification/trace/api.md
> -The `Tracer` MAY provide functions to:
The wording led me to be believe that the methods should be class (static) methods and not instance methods on the class. As long as it allows for them to be instance methods on the tracer, I'm 👍.

2020-10-07 16:28 UTC, anuraaga commented on specification/trace/api.md
> +All the above functionalities operate solely on the context API, and they MAY be
I'm not familiar enough with every programming language to know whether allowing or denying multiple ways to do the same thing is a pattern or antipattern. In Java, shortcuts are common I think FWIW. 

But anyways I would want the language SIGs to focus on making the API that they feel is easiest to use for users and the spec must not block that. It can provide suggestions for sure but it must not block languages from creating a proper, but of course functional (as defined by spec) API.

This is instrumentation, so it's very different from defining remote APIs with a single protobuf and accepting it's at times annoying API where reduction of idioms is more accepted.

2020-10-07 21:18 UTC, bogdandrutu commented on specification/trace/api.md
> +All the above functionalities operate solely on the context API, and they MAY be
Sure, let's get an example where you say (Java):
* https://github.com/open-telemetry/opentelemetry-java/blob/master/api/src/main/java/io/opentelemetry/trace/TracingContextUtils.java#L43
* https://github.com/open-telemetry/opentelemetry-java/blob/master/api/src/main/java/io/opentelemetry/trace/Tracer.java#L76

Can you explain how this improve usability? I am worried more that this confuses users:
* which one do I use?
* The tracer version seems to be implementation specific, so that should be used?

I am all about having shortcuts for "getCurrentSpan" instead of asking users to do "getSpan(getCurrentContext())" which is improvement in usability. But having the same shortcut "getCurrentSpan" in multiple places I cannot see how that can improve usability and not confuse users.

I know that it can be said that Java did a poor job (which I agree), but Java was following what was documented in the Spec, which was 2 different shortcuts to achieve the same thing.

2020-10-07 21:19 UTC, bogdandrutu commented on specification/trace/api.md
> +[`Tracer`](#tracer) class.
Not sure, that's why I did not have any opinion about this. Should I document that it is "not encouraged to override this"?

2020-10-07 22:48 UTC, carlosalberto commented on specification/trace/api.md
> +[`Tracer`](#tracer) class.
> Should I document that it is "not encouraged to override this"?

Sounds good to me. Opinion on this @Oberon00 ?

cc @mwear

2020-10-08 04:40 UTC, anuraaga approved these changes

2020-10-08 04:40 UTC, anuraaga commented on specification/trace/api.md
> +All the above functionalities operate solely on the context API, and they MAY be
I agree that a confusing shortcut isn't helpful :) `TracingContextUtils` is a special, and somewhat unnecessary concept so it's not really a helpful API IMO. But if a user wants a current `Span`, having a shortcut on the `Span` itself seems very easy to use, even if it's a shorcut for getting the current tracer provider and its current span. The locations are somewhat different, but it's intuitive I think. Maybe it isn't though - I just wouldn't have the spec define this strictly. I don't see a problem with the current language, it uses `MAY`. But I hope people are on the same page that whether a shortcut is a good idea or not can be a language-issue and not a spec issue.

2020-10-08 04:43 UTC, anuraaga commented on specification/trace/api.md
> +[`Tracer`](#tracer) class.
For context interoperability, I think we will override methods related to context similar to here

https://github.com/open-telemetry/opentelemetry-java/blob/master/context/src/otelAsGrpcTest/java/io/opentelemetry/context/GrpcContextStorageProvider.java

I wouldn't add a point about not encouraging overriding since for interop of implicit context with other libraries it can be very important.

2020-10-08 05:50 UTC, bogdandrutu commented on specification/trace/api.md
> +All the above functionalities operate solely on the context API, and they MAY be
I agree that sometimes shortcuts are useful, my advice start small, provide a way, if feedback suggest not enough extend. it is simpler to add more ways than removing things, so if we add too many shortcuts and we confuse users it is harder to fix.

2020-10-08 16:14 UTC, carlosalberto commented on specification/trace/api.md
> +[`Tracer`](#tracer) class.
@anuraaga Overriding the low-level `Context` storage has always existed and is totally fine (Python also does it, IIRC).

What we don't want however, for simplicity purposes, is to have users override either the more-public `TracingContextUtils` or `Tracer`/`Baggage` active handling members.

2020-10-09 14:35 UTC, arminru approved these changes
The proposed note on discouraging overridability sounds reasonable, otherwise LGTM.

2020-10-09 14:39 UTC, Oberon00 commented on specification/trace/api.md
> +[`Tracer`](#tracer) class.
I think by default if something is described in the API, I would assume:

* It MUST be overridable
* The API-only implementation MUST be no-op.

For this functionality, I don't think we want any of these, so I suggest to use the same wording we already have for the propagated span and SpanContext creation:

> This functionality MUST be fully implemented in the API, and SHOULD NOT be overridable.

2020-10-12 08:40 UTC, carlosalberto commented on specification/trace/api.md
> +[`Tracer`](#tracer) class.
@Oberon00 Agreed, that's the idea.

2020-10-12 09:10 UTC, Oberon00 commented
@arminru More important than discouraging overridability would be to specify that this functionality must be implemented in the API.

2020-10-13 00:17 UTC, carlosalberto approved these changes

2020-10-13 08:08 UTC, Oberon00 requested changes

2020-10-13 08:08 UTC, Oberon00 commented on specification/trace/api.md
> +[`Tracer`](#tracer) class.
I generally agree with this PR but I feel the sentence

> This functionality MUST be fully implemented in the API, and SHOULD NOT be overridable.

(especially the first part) is really important to not muddle the distinction between API and SDK and make every implementer guess what is to be implemented where.

Thus I'm requesting changes here. But please dismiss my request changes once you fixed that and count my review as an approval (I probably won't be here later today).

2020-10-14 11:21 UTC, carlosalberto commented
Ping @bogdandrutu ;)

2020-10-15 01:26 UTC, bogdandrutu commented on specification/trace/api.md
> +[`Tracer`](#tracer) class.
@Oberon00 added a less strict sentence, there may be case where this cannot be achieved. Take a look and let me know if you are ok with that.

2020-10-15 01:59 UTC, tigrannajaryan approved these changes
LGTM. Just added minor suggestion to make the intent with implicit context clearer. I am fine if it is merged with or without my suggestion.

2020-10-15 01:59 UTC, tigrannajaryan commented on specification/trace/api.md
>  - Set the currently active span
```suggestion
- Get the currently active span from the implicit context. This is equivalent to getting the implicit context, then extracting the `Span` from the context.
- Set the currently active span to the implicit context. This is equivalent to getting the implicit context, then inserting the `Span` to the context.
```

2020-10-15 07:55 UTC, jmacd approved these changes

2020-10-15 08:20 UTC, Oberon00 commented on specification/trace/api.md
> +[`Tracer`](#tracer) class.
If we expect cases where this is not possible, why doesn't the same apply to propagated span creation and spancontext creation?

2020-10-15 08:21 UTC, Oberon00 approved these changes

2020-10-15 12:24 UTC, bogdandrutu commented on specification/trace/api.md
> +[`Tracer`](#tracer) class.
> Ok, maybe because we have a dependency on a context module only from the SDK implementation, right? Could be the case in JS @dyladan ?

That's what I have in mind, if Context cannot be fully implemented and needs an implementation, then we need to have a way to use that implementation to implement this functionality, so we cannot implement this. Unless we pass the "implementation" to these methods/funcs.

2020-10-15 12:47 UTC, anuraaga commented on specification/trace/api.md
> +[`Tracer`](#tracer) class. This functionality SHOULD be fully implemented in the
Breaking news - there seems to be a lot of support for removing the mention of `Tracer` here. What do you think?

https://github.com/open-telemetry/opentelemetry-java/issues/1807

2020-10-15 12:50 UTC, Oberon00 commented on specification/trace/api.md
> +[`Tracer`](#tracer) class. This functionality SHOULD be fully implemented in the
The spec here does not say that this should be on the tracer, and if it is, it says it should be static.

2020-10-15 13:39 UTC, anuraaga commented on specification/trace/api.md
> +[`Tracer`](#tracer) class. This functionality SHOULD be fully implemented in the
Ah static is written twice, but not a third time. So with this wording, static does not apply to Tracer I think and I didn't read it that way. If it's also static it makes sense to me.

2020-10-15 14:46 UTC, carlosalberto commented on specification/trace/api.md
> +[`Tracer`](#tracer) class. This functionality SHOULD be fully implemented in the
What one language decided to do is not breaking news :) In the Ruby implementation they want to work directly with `Tracer` (cc @mwear). The options are given above, and the language is free to implement them either way they want. 

@bogdandrutu to just clarify, we still allow this to exist as instance methods in `Tracer`, correct?

2020-10-15 14:53 UTC, Oberon00 commented on specification/trace/api.md
> +[`Tracer`](#tracer) class. This functionality SHOULD be fully implemented in the
I think we should discourage an instance method on tracer, as this has been known to cause confusion and has caused people to call for allowing an unnamed tracer just to access the current span.

2020-10-15 16:37 UTC, SergeyKanzhelev commented
reopened to reset EasyCLA

2020-10-15 16:37 UTC, jmacd commented on specification/trace/api.md
> +[`Tracer`](#tracer) class. This functionality SHOULD be fully implemented in the
> I think we should discourage an instance method on tracer

I agree.

2020-10-15 16:53 UTC, bogdandrutu commented on specification/trace/api.md
> +[`Tracer`](#tracer) class. This functionality SHOULD be fully implemented in the
I think the current text does exactly that, and in edge cases where that cannot be avoided, it allows to be an instance method.

2020-10-15 16:53 UTC, merged

2020-10-16 14:58 UTC, fbogsany commented on specification/trace/api.md
> +[`Tracer`](#tracer) class. This functionality SHOULD be fully implemented in the
https://github.com/open-telemetry/opentelemetry-ruby/pull/425#issuecomment-710096680

TL;DR: I agree, including for Ruby.