Include k8s.pod.hostname and k8s.container.id and image
open-telemetry/opentelemetry-specification pull request #1072
Opened 2020-10-07 19:27 UTC by pmm-sumo

Include `k8s.pod.hostname`, `k8s.container.id` and `k8s.container.image` in `k8s` semantic conventions.

Since this is a relatively small change (and it follows the naming scheme used right now), I didn't open a separate issue. Will be happy to update the upcoming YAML definitions if this gets accepted.

Related issues #
https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/141

2020-10-07 19:41 UTC, bogdandrutu commented on specification/resource/semantic_conventions/k8s.md
> +| k8s.container.id | The Container ID | `docker://22b7d5e3a376c22dd2f7358b2f85bd6c2432c04294cd4cbbef17b6ae1ac40603` |
This is the "container.id". Why does it need to be here as well? Same for image.

2020-10-07 19:43 UTC, bogdandrutu commented on specification/resource/semantic_conventions/k8s.md
> +| k8s.container.id | The Container ID | `docker://22b7d5e3a376c22dd2f7358b2f85bd6c2432c04294cd4cbbef17b6ae1ac40603` |
The difference with `k8s.container.name` is that it is an overwrite in the Pod template.

2020-10-07 19:49 UTC, pmm-sumo commented on specification/resource/semantic_conventions/k8s.md
> +| k8s.container.id | The Container ID | `docker://22b7d5e3a376c22dd2f7358b2f85bd6c2432c04294cd4cbbef17b6ae1ac40603` |
`container.image` refers to optional configuration that can sometimes override value set in e.g. Deployment. I had my own set of doubts with including it. Missed the fact that the running container conventions capture the other part. 

So, less is more, removing it and leaving just the `hostname`

2020-10-07 20:17 UTC, bogdandrutu approved these changes

2020-10-07 20:31 UTC, pmm-sumo commented
On the second thought, this got me wondering if maybe [`host.hostname`](https://github.com/open-telemetry/opentelemetry-collector/blob/master/translator/conventions/opentelemetry.go#L33) should be used instead? It's not clearly documented (missing from the [host](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/resource/semantic_conventions/host.md) semantic conventions though mentioned in e.g. [Logs Data Model](https://github.com/open-telemetry/opentelemetry-specification/blob/b0fb442e2492a63793e32d744adbac5ff168146f/specification/logs/data-model.md#rfc5424-syslog)

2020-10-07 20:39 UTC, dmitryax approved these changes

2020-10-07 20:41 UTC, dmitryax commented
@pmm-sumo the `host.hostname` was recently remove from the conventions https://github.com/open-telemetry/opentelemetry-specification/pull/838

2020-10-07 21:17 UTC, pmm-sumo commented
Thanks for the clarification @dmitryax I have opened a draft update for the collector (which is ready to be converted into a normal PR after this one gets merged). I am not sure how is it impacted by the focus on GA, though then it's a rather minimal change

2020-10-08 07:01 UTC, Oberon00 commented
What is the difference of that attribute to host.name?

2020-10-08 07:20 UTC, Oberon00 requested changes
Requesting changes because I think this is redundant with host.name (https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/resource/semantic_conventions/host.md) and I think this needs a proper explanation of what the difference would be.

2020-10-08 07:20 UTC, Oberon00 commented on specification/resource/semantic_conventions/k8s.md
> +| k8s.pod.hostname | The hostname of the Pod, if set, or [name, otherwise](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-hostname-and-subdomain-fields). | `openteleme
Why default it to the pod name which is already stored in pod.name? As a result you can never be sure if you actually got a hostname, or just the pod name (since the two are probably often but not always equal)

2020-10-08 08:16 UTC, pmm-sumo commented on specification/resource/semantic_conventions/k8s.md
> +| k8s.pod.hostname | The hostname of the Pod, if set, or [name, otherwise](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-hostname-and-subdomain-fields). | `openteleme
I think this becomes the effective hostname. Which leads to the conclusion that `host.name` is probably a better fit for it, as suggested. What do you think @dmitryax ?

2020-10-08 13:32 UTC, tigrannajaryan commented on specification/resource/semantic_conventions/k8s.md
> +| k8s.pod.hostname | The hostname of the Pod, if set, or [name, otherwise](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-hostname-and-subdomain-fields). | `openteleme
@Oberon00 if I am reading the K8s documentation correctly then that's how K8s behaves, it is not our choice. By default Pod's hostname fetched from K8s will be equal to the Pod's name unless `hostname` field is explicitly specified in the Pod's configuration.

2020-10-08 14:58 UTC, Oberon00 commented on specification/resource/semantic_conventions/k8s.md
> +| k8s.pod.hostname | The hostname of the Pod, if set, or [name, otherwise](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-hostname-and-subdomain-fields). | `openteleme
That's not what the semantic convention says. If I read this, I would have expected to implement it by

1. Use gethostname to find my hostname
2. If it's empty, use the same value as set for k8s.pod.name

Nowhere does it say that we should ask k8s for that hostname.

2020-10-08 16:01 UTC, pmm-sumo commented on specification/resource/semantic_conventions/k8s.md
> +| k8s.pod.hostname | The hostname of the Pod, if set, or [name, otherwise](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-hostname-and-subdomain-fields). | `openteleme
While I introduced this PR, following the discussion I am thinking that simply using `host.name` might work better... The only concern I have is how the hostname value of `Pod` maps to computer instance. E.g. when the Kubernetes Node runs on, say, EC2, each of the pods running there would have a different `host.name` value. Should the latter refer to EC2 instance hostname or Pod hostname?

2020-10-08 16:07 UTC, Oberon00 commented on specification/resource/semantic_conventions/k8s.md
> +| k8s.pod.hostname | The hostname of the Pod, if set, or [name, otherwise](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-hostname-and-subdomain-fields). | `openteleme
Good question. I would say the "inner" hostname. With nested contairerization and possibly nested VMs, it is hard to determine a "real" host. But maybe we should duplicate the host resource to a physical_host, which is the app's best guess at the "real" host. Or outer_host which is the app's best guess at the outer-next host.

2020-10-08 16:55 UTC, tigrannajaryan commented on specification/resource/semantic_conventions/k8s.md
> +| k8s.pod.hostname | The hostname of the Pod, if set, or [name, otherwise](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-hostname-and-subdomain-fields). | `openteleme
Node's host vs Pod's host is a general problem with how our resources/attributes (not just for "hostname"). We commingle them without specifying which entity the attributes apply to. I deliberately avoided raising this topic close to GA and this is something I plan to address after GA since it may require conceptual changes in how we understand resources in 2.0.

For now the best we can do is to avoid the problem. "Avoiding" here means not to record ambiguous attributes. "hostname" is ambiguous in Kubernetes context.

I would advise to do one of the following:
- Don't record the host name at all in the Collector's k8s processor. This would be my preference unless there are other arguments.
- If we absolutely must record the host name then either accept k8s.pod.hostname+k8s.node.hostname as a semantic convention or just record it in the Collector as an experimental capability without corresponding semantic convention. Time will tell if it needs to stay and become a semantic convention in the spec.

2020-10-08 17:51 UTC, pmm-sumo commented on specification/resource/semantic_conventions/k8s.md
> +| k8s.pod.hostname | The hostname of the Pod, if set, or [name, otherwise](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-hostname-and-subdomain-fields). | `openteleme
BTW, the `k8s.node.name` is frequently the hostname of the machine where the node resides.

In either case - I wouldn't want this problem to take the focus out of the GA. If nobody objects I would suggest to skip adding this capability until after-GA and with a solid discussion.

2020-10-09 07:48 UTC, pmm-sumo commented
Closing this issue per the conversation. Lets go back to this after GA

2020-10-09 07:48 UTC, closed without merging