Add semantic conventions for the AWS SDK.
open-telemetry/opentelemetry-specification pull request #1095
Opened 2020-10-15 08:56 UTC by anuraaga

Fixes #968 (by being the first instrumentation-specific instrumentation)

## Changes

This defines semantic attributes for instrumentation of the AWS SDK. We have instrumentation in several languages and they fill in some traditional semantic fields with varying coverage. AWS has also identified fields in request / response that are valuable for monitoring and we think this is a good list, though will naturally grow more, of attributes to get meaningful information from AWS API calls without the problems of copying the entire request/response.

The attributes are sort of "denormalized" as they are intended to be extracted from API calls, with instructions for each, and some attributes are common among the calls. This seems easy to implement, but let me know how this structure looks. Particularly interested in @thisthat's advice in terms of the YAML representations.

2020-10-15 09:06 UTC, Oberon00 commented on specification/trace/semantic_conventions/instrumentation/aws-sdk.md
> +|awssdk.operation | string | The operation name of the request, as returned by the AWS SDK | `GetItem`, `PutObject` |
For new trace semantic conventions, please use the YAML format.

2020-10-15 09:15 UTC, anuraaga commented on specification/trace/semantic_conventions/instrumentation/aws-sdk.md
> +|awssdk.operation | string | The operation name of the request, as returned by the AWS SDK | `GetItem`, `PutObject` |
I can't find any documentation on how to define conventions with YAML can you point me at it? I just see our tool to automatically convert MD to YAML, which seems to make sense since I figure we want the readable representation? 

https://github.com/open-telemetry/opentelemetry-specification/tree/master/semantic_conventions

2020-10-15 09:19 UTC, Oberon00 commented on specification/trace/semantic_conventions/instrumentation/aws-sdk.md
> +|awssdk.operation | string | The operation name of the request, as returned by the AWS SDK | `GetItem`, `PutObject` |
There is no such tool, the tool converts YAML to MD not the other way round 😃 The docs are in https://github.com/open-telemetry/opentelemetry-specification/blob/master/semantic_conventions/syntax.md but I think it's easiest to look at an existing YAML file.

However, since I just saw #1054 is not merged yet, I think it should be OK to convert these conventions later.

2020-10-15 09:25 UTC, anuraaga commented on specification/trace/semantic_conventions/instrumentation/aws-sdk.md
> +|awssdk.operation | string | The operation name of the request, as returned by the AWS SDK | `GetItem`, `PutObject` |
Oh man, I completely misread that README and thought @thisthat was autogenerating those PRs!

2020-10-15 10:15 UTC, thisthat reviewed
That's a lot of attributes! :) thank you for collecting them! 
Going through it quickly, I noticed some style errors. I would suggest to follow the recommendation of @Oberon00 and start with the YAML definition and then, generate the tables. 
In YAML, I would create a general `awssdk` semantic convention which contains
the `service` and `operation` attributes. Then, one semantic convention for each type that extends the general `awssdk` convention. Does it make sense? If you need further help, let me know :)

2020-10-15 10:15 UTC, thisthat commented on specification/trace/semantic_conventions/instrumentation/aws-sdk.md
> +|awssdk.operation | string | The operation name of the request, as returned by the AWS SDK | `GetItem`, `PutObject` |
It has always been hard manual work :innocent: the first step at least, everything else is automatic :wink:

2020-10-15 10:15 UTC, thisthat commented on specification/trace/semantic_conventions/instrumentation/aws-sdk.md
> +|awssdk.service | string | The service name of the request, as returned by the AWS SDK | `DynamoDB`, `S3` |
```suggestion
| `awssdk.service` | string | The service name of the request, as returned by the AWS SDK | `DynamoDB`, `S3` |
```

2020-10-15 10:15 UTC, thisthat commented on specification/trace/semantic_conventions/instrumentation/aws-sdk.md
> +| `awssdk.provisioned_throughput. | int | te_capacity_units` - Copy the `ProvisionedThroughput.ReadCapacityUnits` request parameter |
There is some strange errors here

2020-10-15 10:43 UTC, anuraaga commented
Thanks I'll try to migrate! First impression was that it seems I always duplicate ID and name, I wonder if one can be made optional.

2020-10-15 11:47 UTC, Oberon00 commented
You mean for enums? Yeah, I think defaulting value to id would make sense.

2020-10-24 03:28 UTC, anuraaga commented
Sorry for the delay on this, will be getting to the large YAML refactoring next week

2020-10-26 09:25 UTC, anuraaga commented on semantic_conventions/trace/instrumentation/aws-sdk.yml
> +        brief: Extract the keys of the `RequestItems` object field in the request
@thisthat I have gotten to the point where the generator gives this error

Empty examples for string are not allowed - @29:9

For these attributes, the approach is to describe how to construct the convention based on the API call rather than giving examples, so it'd be nice if that's not required. Do you think it makes sense to loosen the restriction?

Another restriction which loosening would be a bit nice but much less important, if `id` didn't have to be all lowercase they would match exactly the name of the API being described.

2020-10-26 09:30 UTC, anuraaga commented
By the way, no need to review the yml yet I'm still working out generation issues to get to an MD file where I can confirm I wrote it correctly :)

2020-10-27 09:39 UTC, thisthat commented on semantic_conventions/trace/instrumentation/aws-sdk.yml
> +        brief: Extract the keys of the `RequestItems` object field in the request
I think this restriction is important. Especially for this use case, I think an example is very beneficial. The example should show how the `tables_names` are extracted from the request, i.e. are they concatenated by comma or are they JSON encoded? 
I would add in the MD an example of `batchGetItem` invocation, so the examples directly take from the example and show how the attributes should be filled. 

For your second point, we could remove that. In the [specification](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/common/common.md), we don't have any restriction on the case for keys. However, so far, we have only used lowercase names :thinking: I don't have a clear position on this. Would you consider `example_id` equal to `eXaMpLe_iD`?

2020-10-27 12:08 UTC, Oberon00 commented on semantic_conventions/trace/instrumentation/aws-sdk.yml
> +        brief: Extract the keys of the `RequestItems` object field in the request
The attribute IDs are the keys sent over the wire. I think we should keep them lowercase for consistency.

2020-10-27 12:32 UTC, anuraaga commented on semantic_conventions/trace/instrumentation/aws-sdk.yml
> +        brief: Extract the keys of the `RequestItems` object field in the request
Ah I meant the group IDs not the attribute IDs. But not a big deal :)

2020-11-06 00:20 UTC, andrewhsu commented
at the metrics sig mtg today talked about this issue's staleness

2020-11-06 15:09 UTC, Oberon00 requested changes
General notes:
- Blocking: You do not reference the new YAML convention in any md file. You need to add a new md file in the usual place with the `<!-- semconv` markers etc.
- I think it's best practice to use quotes in multi-word YAML values, even if not required.
- Please end the sentences with a period.

2020-11-06 15:09 UTC, Oberon00 commented on semantic_conventions/trace/instrumentation/aws-sdk.yml
> +        brief: Extract the keys of the `RequestItems` object field in the request
This is worded like an instruction for instrumentation writers. Since backend writers will also be interested in what this is, I suggest

```suggestion
        brief: "The keys in the request's `RequestItems` object field."
```

2020-11-06 15:09 UTC, Oberon00 commented on semantic_conventions/trace/instrumentation/aws-sdk.yml
> +      - id: db.name
This will be `dynamodb.deleteitem.db.name` which is quite long. If this was intentional, I'm OK with it though.

2020-11-06 15:09 UTC, Oberon00 commented on semantic_conventions/trace/instrumentation/aws-sdk.yml
> +      - id: db.name
Is this different from `dynamodb.deleteitem.db.name`? Maybe you could extract some shared attributes and use them with `constraints: include` (as e.g. done for `net` in `http`).

2020-11-06 15:10 UTC, Oberon00 commented on semantic_conventions/trace/instrumentation/aws-sdk.yml
> +        brief: Extract the keys of the `RequestItems` object field in the request
I'm also not sure what this means (is it an object or string field now?) but I assume someone familiar with AWS would know.

2020-11-21 03:20 UTC, closed without merging

2020-12-04 16:25 UTC, jgals commented
Hey @anuraaga, it looks like this issues was closed prematurely by the bot. Did you want to reopen it?

2021-07-26 23:28 UTC, NathanielRN commented
Just in case anyone comes looking later, @anuraaga got all the comments addressed and merged in #1422 as a replacement for this PR 🥳