contrib specification directory for vendor specs
open-telemetry/opentelemetry-specification pull request #1111
Opened 2020-10-19 17:31 UTC by tsloughter

Fixes #1110

2020-10-19 17:35 UTC, jkwatson commented on contrib/README.md
> +components, such as propagators, processors, resources, exporters, etc
```suggestion
components, such as propagators, processors, resources, exporters, etc.
```

2020-10-19 17:35 UTC, jkwatson approved these changes

2020-10-19 23:58 UTC, SergeyKanzhelev commented on contrib/README.md
> +components, such as propagators, processors, resources, exporters, etc.
let's add a note on support statement like this: https://github.com/open-telemetry/opentelemetry-dotnet-contrib/#support

2020-10-19 23:59 UTC, SergeyKanzhelev requested changes
let's add clarification on the folder supportability. Like I suggested in the comment.

2020-10-20 16:09 UTC, SergeyKanzhelev commented
I think adding the comment about supportability like this https://github.com/open-telemetry/opentelemetry-dotnet-contrib/#support will address today's meeting concerns. But I'd let @reyang, @tedsuo, and @alolita to comment here

2020-10-26 06:28 UTC, alolita commented
@SergeyKanzhelev As we discussed in the maintainers meeting - I am working on a proposal for hosting vendor contribs. Will discuss w @tedsuo and link the issue here as soon as I file it. Thanks for sharing the .net guidelines by @reyang

2020-10-26 17:44 UTC, SergeyKanzhelev commented
@tsloughter I'll close this PR for now than unless the decision is made. Thank you for filing PR!

2020-10-26 17:44 UTC, closed without merging