Revert: Define Propagation-only Span to simplify active Span logic in Context
open-telemetry/opentelemetry-specification pull request #1125
Opened 2020-10-21 15:53 UTC by tsloughter

This reverts commit d14c9b7a74328c22e5d2223c4ddcaca5630aceae.

Fixes #1124

2020-10-21 16:48 UTC, bogdandrutu commented
@tsloughter can we document the reasons?

2020-10-21 19:26 UTC, jkwatson commented on specification/trace/api.md
> +  * [StatusCanonicalCode](#statuscanonicalcode)
This can't be right. I think your revert is reverting too much.

2020-10-21 19:51 UTC, tsloughter commented on specification/trace/api.md
> +  * [StatusCanonicalCode](#statuscanonicalcode)
Oh, damn, yea. There were some conflicts I had to resolve and must have got this one wrong, though I thought the other part of the diff was empty.. but I'll get this fixed.

2020-10-22 08:35 UTC, Oberon00 requested changes
Blocking this for now -- please see discussion on issue.

2020-10-27 01:29 UTC, closed without merging