Add an option to limit span attribute length
open-telemetry/opentelemetry-specification pull request #1130
Opened 2020-10-22 13:27 UTC by jtmalinowski

Docs are based on existing Java implenetation https://github.com/open-telemetry/opentelemetry-java/pull/1484

Fixes #

## Changes

Please provide a brief description of the changes here. Update the
`CHANGELOG.md` for non-trivial changes. If `CHANGELOG.md` is updated,
also be sure to update `spec-compliance-matrix.md` if necessary.

Related issues #

Related [oteps](https://github.com/open-telemetry/oteps) #

2020-10-22 13:54 UTC, Oberon00 commented
Please create an issue for this PR.

2020-10-22 14:00 UTC, iNikem commented on specification/trace/sdk.md
> +Similarly SDK Spans can be configured to truncate attribute values. By default,
Please try to rewrite this section to use normative language (MAY and SHOULD NOT), as does the previous section.

2020-10-22 19:42 UTC, jtmalinowski commented on specification/trace/sdk.md
> +Similarly SDK Spans can be configured to truncate attribute values. By default,
I hope it's correct now.

2020-10-23 11:51 UTC, jtmalinowski commented
PR extended to include metric label values.

2020-10-23 13:20 UTC, arminru commented on specification/metrics/sdk.md
> +exceeds that limit, SDK Spans SHOULD truncate that value, so that its length is
```suggestion
exceeds that limit, SDKs SHOULD truncate that value, so that its length is 
```

2020-10-23 13:20 UTC, arminru commented on specification/metrics/sdk.md
> +Erroneous code can add unintended labels to a span. If they are unbounded, they
```suggestion
Erroneous code can add unintended labels to a metric. If they are unbounded, they 
```

2020-10-23 15:02 UTC, Oberon00 commented
> PR extended to include metric label values.

👍 

I was just reminded that resource values might also be relevant here

2020-10-23 15:03 UTC, Oberon00 commented
One more thing @jtmalinowski: Please either fill out the PR description or remove the part of the template that you don't use.

2020-10-23 16:26 UTC, iNikem commented on specification/trace/sdk.md
> +if it exceeds that limit, SDKs SHOULD truncate that value, so that its length
```suggestion
if it exceeds that limit, SDKs MUST truncate that value, so that its length
```

if SDK provides a configuration, it MUST follow it :)

2020-10-23 16:26 UTC, iNikem approved these changes

2020-10-27 07:37 UTC, jmacd commented on specification/metrics/sdk.md
> +not be emitted more than once per metric or value.
I would accept "per metric", but "or value" sounds extreme to me.

2020-10-27 07:37 UTC, jmacd commented on specification/sdk-environment-variables.md
> +## Span Limits
FWIW I'd prefer to see a default limit for all kinds of attribute. 

Do you intend to apply this limit to resource attributes as well?

2020-10-27 17:19 UTC, jtmalinowski commented on specification/sdk-environment-variables.md
> +## Span Limits
it totally makes sense to be applied to all attributes

2020-10-27 18:21 UTC, jtmalinowski commented on specification/metrics/sdk.md
> +not be emitted more than once per metric or value.
changed to "the log MUST NOT be emitted more than once per item on which an attribute is set"

2020-10-27 18:43 UTC, iNikem approved these changes

2020-10-27 18:43 UTC, iNikem commented on specification/common/common.md
> +if it exceeds that limit, SDK Spans SHOULD truncate that value, so that its length
```suggestion
if it exceeds that limit, SDK Spans MUST truncate that value, so that its length
```

2020-10-27 18:43 UTC, iNikem commented on specification/common/common.md
> +size limit, then it shouldn't be serialized.
```suggestion
size limit, then it SHOULD NOT be serialized.
```
?

2020-10-27 18:43 UTC, iNikem commented on specification/common/common.md
> +an exceeded size limit, its value SHOULD be a string.
Where this came from? :) In Java SDK we implement attribute value truncation by truncating each individual value in an array, if it exceeds the limits. We don't try to cut the array itself.

2020-10-27 18:43 UTC, iNikem commented on specification/common/common.md
> +is not valuable for preventing SDKs from exhausting large amounts of memory.
Although I don't oppose this, I wonder when is this problem possible? I mean in Java we apply limits just to String-typed attributes, not to others. Is this a problem for some specific language?

2020-10-27 19:12 UTC, jtmal-signalfx commented on specification/common/common.md
> +an exceeded size limit, its value SHOULD be a string.
If we say that the attribute value size limit is x, and an array is the value, then I'd presume that the size of the value is the size of the whole array. I'd be surprised if it applied to items within the array. But sure, we can reword it so that it's clear that for arrays it's applied per cell.

2020-10-27 19:13 UTC, jtmalinowski commented on specification/common/common.md
> +an exceeded size limit, its value SHOULD be a string.
If we say that the attribute value size limit is x, and an array is the value, then I'd presume that the size of the value is the size of the whole array. I'd be surprised if it applied to items within the array. But sure, we can reword it so that it's clear that for arrays it's applied per cell.

2020-10-27 19:15 UTC, jtmalinowski commented on specification/common/common.md
> +is not valuable for preventing SDKs from exhausting large amounts of memory.
It came up during the review of implementation in JS, so as I understand it specs should clearly state what the expectations are, but also common sense. If someone sets a limit of 4 characters, then it should truncate `false` to "fals" and `1e100/3` to '3.333', which is ridiculous.

2020-11-01 13:09 UTC, iNikem commented on specification/common/common.md
> +an exceeded size limit, its value SHOULD be a string.
> we can reword it so that it's clear that for arrays it's applied per cell

I think this is a right thing to do.

2020-11-03 23:30 UTC, obecny commented on specification/common/common.md
> +is not valuable for preventing SDKs from exhausting large amounts of memory.
I would argue if such limit is needed. We should not think if it makes sense to have `fals` instead of `false` as we are creating sdk which gives user full control over it and user should be able to decide if that makes sense for him or not. 

Some analogy: if in linux you want to delete all folders as a root you can do it, it won't ask you or block you from doing it, in windows it won't be possible. I prefer linux approach because it is a final user who decides about it according to needs.

I'm wondering if we should think of splitting this into 3 categories and allow user to decide if length of attribute should be truncated based on its type. This way user would have full control and could decide not to truncate boolean, not to truncate numbers and only truncate strings. So in fact this limit would only apply to string values by default but user could still override it for numbers and boolean - if for any reason he wants to do it like this (doesn't matter if that makes sense or not, for user it can make sense)

2020-11-03 23:34 UTC, obecny commented on specification/common/common.md
> +an exceeded size limit, its value SHOULD be a string.
> In Java SDK we implement attribute value truncation by truncating each individual value

I think this is safer approach. If we truncate array in the middle it won't be possible to parse this back from string to json / array and the whole attribute value is gone.

2020-11-03 23:44 UTC, obecny commented on specification/sdk-environment-variables.md
> +| OTEL_SPAN_ATTRIBUTE_VALUE_SIZE_LIMIT  | Maximum allowed span attribute length |         | See notes for OTEL_ATTRIBUTE_VALUE_SIZE_LIMIT |
I think `size` should be replaced with `length`

OTEL_SPAN_ATTRIBUTE_VALUE_LENGTH_LIMIT

2020-11-03 23:45 UTC, obecny commented on specification/sdk-environment-variables.md
> +| OTEL_METRIC_LABEL_SIZE_LIMIT | Maximum allowed metric value length |         | See notes for OTEL_ATTRIBUTE_VALUE_SIZE_LIMIT |
I think size should be replaced with length

OTEL_METRIC_LABEL_LENGTH_LIMIT

2020-11-06 13:20 UTC, jtmalinowski commented on specification/common/common.md
> +is not valuable for preventing SDKs from exhausting large amounts of memory.
That sounds reasonable, let me amend the PR.

2020-11-06 13:21 UTC, jtmalinowski commented on specification/sdk-environment-variables.md
> +| OTEL_SPAN_ATTRIBUTE_VALUE_SIZE_LIMIT  | Maximum allowed span attribute length |         | See notes for OTEL_ATTRIBUTE_VALUE_SIZE_LIMIT |
Agreed, `length` is more accurate.

2020-11-06 13:23 UTC, jtmalinowski commented on specification/common/common.md
> +an exceeded size limit, its value SHOULD be a string.
Sure, but we still have one issues outstanding then, which is that you might add too many items to an array accidentally,  so should we have another separate limit for that?

2020-11-06 14:04 UTC, obecny commented on specification/common/common.md
> +an exceeded size limit, its value SHOULD be a string.
I think it make sense

2020-11-11 00:57 UTC, MrAlias commented on specification/common/common.md
> +if it exceeds that limit, SDK Spans MUST truncate that value, so that its length
How should this truncation be performed? From the head, tail, or random elements dropped?

2020-11-11 00:57 UTC, MrAlias commented on specification/common/common.md
> +SDKs SHOULD choose any serialization protocol, which is performant and appropriate
```suggestion
SDKs SHOULD choose any serialization protocol which is performant and appropriate
```

2020-11-11 00:57 UTC, MrAlias commented on specification/common/common.md
> +on which an attribute is set.
This seems idiomatic of a language that has first class logging. I don't think it applies well universally and should not be a recommendation, but perhaps an option.

If we are specifying logging should be not be at a one-to-one cadence, can we also provide a positive recommendation? Like, once per ten items, once per minute?

2020-11-11 00:57 UTC, MrAlias commented on specification/common/common.md
> +which that SDK implements truncation mechanism.
```suggestion
SDKs SHOULD only offer environment variables for the types of attributes
that SDK implements truncation mechanism.
```

2020-11-11 00:57 UTC, MrAlias commented on specification/common/common.md
> +MUST NOT be set to any number lower than 32. Please note that certain very low limits
Attribute sizes need to be specified with a unit here. Does 32 represent bytes, bits, characters, runes ...

Also, I'm guessing this is implying that this is a configured value (not the default), what should an SDK do if they are configured with a size smaller than this? Ignore it and revert to a default, or maybe just don't truncate?

2020-11-18 22:30 UTC, jkwatson commented on specification/common/common.md
> +limit and the limit is set, then for each attribute value, serialized into a string,
I really think we should only be truncating string-valued attributes, based on character length, rather than having this "serialized into a string" clause. it doesn't make sense to truncate booleans, or numbers, as mentioned by another reviewer.

2020-11-18 22:31 UTC, jkwatson commented on specification/common/common.md
> +if it exceeds that limit, SDK Spans MUST truncate that value, so that its length
doesn't "truncate" usually imply removing the end of the string?

2020-11-18 22:32 UTC, jkwatson commented on specification/common/common.md
> +aforementioned behavior MAY yield a previously unexpected type. For example, if
I think this is a very bad idea. We should never change the type of someone's attribute.

2020-11-18 22:35 UTC, jkwatson commented on specification/common/common.md
> +There SHOULD be a log emitted to indicate to the user that an attribute was truncated.
I don't think we should recommend logging in this particular piece of the spec. We should have general logging recommendations, especially emphasizing the "do no harm" aspect. I don't think it's something that should specifically be in here, though.

2020-11-20 13:46 UTC, jtmalinowski commented
hey everybody, I will surely update the content taking all your comments into consideration. However, the PR is waiting for GA, so I've put a pin in it for now. I hope that's ok.

2020-11-20 13:47 UTC, jtmalinowski commented on specification/common/common.md
> +MUST NOT be set to any number lower than 32. Please note that certain very low limits
Since your comment there's been many voices to not truncate non-string values, so this particular part doesn't make sense anymore.

2020-11-20 13:50 UTC, jtmalinowski commented on specification/common/common.md
> +on which an attribute is set.
Again, since you've added this comment, @jkwatson said that, we should not require/recommend any logging here. Instead, it should be covered by general logging guidelines.

2021-01-27 11:25 UTC, iNikem commented
@open-telemetry/specs-approvers @open-telemetry/technical-committee  Can this and similar PRs proceed now? They introduce new optional functionality fo SDKs, so they don't interfere with neither spec's nor SDK's 1.0 or GA releases. Are we allowed to proceed with them?

2021-05-08 23:34 UTC, owais commented
@jtmalinowski @iNikem @open-telemetry/specs-approvers would be great to move forward this. We've similar features in multiple Python Otel exporters all implemented independently with their own configuration. Would be great to have this in spec.

2021-05-11 16:35 UTC, jtmalinowski commented
@owais yeah, definitely, I was actually planning to get it into shape tomorrow

2021-05-27 20:47 UTC, jtmalinowski commented on specification/common/common.md
> +limit and the limit is set, then for each attribute value, serialized into a string,
I think we can revisit this. Right now the spec says that the possible types of values are: string, boolean, number, or a homogenous array of either of these three. So we agree that truncating strings is acceptable, even though they could be storing something serialized, like JSON. Obviously, bools and numbers will never be truncated. That leaves us with arrays. The goal of this change in the spec is to reduce COGS - so truncating arrays makes sense from this perspective, is there a case against doing so?

2021-05-27 20:53 UTC, jtmalinowski commented on specification/common/common.md
> +There SHOULD be a log emitted to indicate to the user that an attribute was truncated.
If we don't log anything, then you won't learn that truncation happens until you go look into a particular piece of data and you find out it is missing. What if we added a piece of metadata stating that at least one attribute value of a span was truncated, and then backend can present it as it wishes - this could be as simple as saying that if the last character of a value is an ellipsis (U+2026) then it was truncated.

2021-05-27 21:03 UTC, jkwatson commented on specification/common/common.md
> +limit and the limit is set, then for each attribute value, serialized into a string,
My opinion is still that we shouldn't introduce some kind of ad-hoc serialization of arrays in order to perform truncation of them. I would very much prefer that we don't try to tackle limiting array-valued attributes in this PR. If we want to try to figure out some sort of scheme for doing that, I think it would be better to have it be a separate PR/issue, as I think handling of arrays (or binary data) is much more complex and deserves its own independent discussion.

2021-05-27 21:07 UTC, jkwatson commented on specification/common/common.md
> +There SHOULD be a log emitted to indicate to the user that an attribute was truncated.
If the user has configured their SDK to do truncation, why would they be surprised if values were being truncated?

2021-06-15 15:58 UTC, jtmalinowski commented on specification/common/common.md
> +limit and the limit is set, then for each attribute value, serialized into a string,
Okay, I changed it to only truncate strings, and in case of string arrays to only truncate the individual items which are too long.

2021-06-15 16:00 UTC, jtmalinowski commented
@reyang Feel free to take a look at changes related to metrics.

2021-06-15 16:04 UTC, jtmalinowski commented on specification/common/common.md
> +There SHOULD be a log emitted to indicate to the user that an attribute was truncated.
Alright, I checked it again, and the reason I added the part about logging is that it was already in place for span collection limits. I think that less changes = better. But we could raise a new PR to change this part about logging.

2021-06-15 19:38 UTC, jkwatson commented on specification/common/common.md
> +To define a limit SDKs SHOULD honor the environment variables specified in
I don't think we should mix up the *what* with the *how*. The primary thing is to make sure the SDK has support for the feature. That support *must* be programmatic at the very least. We should describe the *how* of environment variable support in the documentation of environment variables, not here.

2021-06-15 19:38 UTC, jkwatson commented on specification/common/common.md
> +`<Record>Limits` (where `<Record>` is a type of a record, e.g. `Span`). Names of
I don't think we should bother to mention this; it's an implementation detail that is language-specific and generally not relevant for the spec.

2021-06-15 19:39 UTC, jkwatson commented on specification/common/common.md
> +its language.
This is also not relevant, as it is assumed to be the case for any SDK options. I'd remove it.

2021-06-16 11:12 UTC, jtmalinowski commented on specification/common/common.md
> +its language.
done

2021-06-16 11:12 UTC, jtmalinowski commented on specification/common/common.md
> +`<Record>Limits` (where `<Record>` is a type of a record, e.g. `Span`). Names of
done

2021-06-16 11:13 UTC, jtmalinowski commented on specification/common/common.md
> +To define a limit SDKs SHOULD honor the environment variables specified in
Relevant parts moved to ENV variables doc.

2021-06-16 11:22 UTC, jtmalinowski commented
@MrAlias summoning you back if you have some final comments. @obecny Could you take a look please? I'm planning to implement the above functionality in JS SDK.

2021-06-16 15:11 UTC, jkwatson commented on specification/metrics/sdk.md
> +Configuration of [Measurement Limits](#measurement-limits) MUST be managed
I wonder if we should not try to tackle anything metrics related here until we've got a solid SDK specification. What do you think, @reyang ?

2021-06-18 17:38 UTC, MrAlias commented on specification/common/common.md
> +    1), SDK Spans MUST truncate that value, so that its length is at most equal
Counting a character as 1 is not in line with the purpose of adding limits to protect memory usage. This should likely be defined in terms of memory used as character width is not universal.

2021-06-18 17:38 UTC, MrAlias commented on specification/common/common.md
> +- set an attribute value length limit and the limit is set, then for each
What unit is a limit define in? Bytes?

2021-06-18 17:38 UTC, MrAlias commented on specification/common/common.md
> +  - otherwise a value MUST NOT be truncated;
If a limit is set smaller than a numeric value can be represented in (`float64` or `int64`), what is to be done there?

2021-06-18 17:38 UTC, MrAlias commented on specification/common/common.md
> +    key/value pair.
Is this defined as FIFO or FILO? The way I read this currently is sounds like the whole set is dropped.

2021-06-18 17:38 UTC, MrAlias commented on specification/common/common.md
> +- set an attribute value length limit and the limit is set, then for each
Is there planned a limit on the size an attribute key can be?

2021-06-18 17:38 UTC, MrAlias commented on specification/common/common.md
> +truncated. To prevent excessive logging, the log MUST NOT be emitted more than
Should a log message be emitted when an attribute key/value pair is dropped as well?

2021-06-18 17:38 UTC, MrAlias commented on specification/common/common.md
> +once per parent record.
What is the top level "parent record" here? All spans are in a trace, is that a valid parent?

2021-06-18 17:38 UTC, MrAlias commented on specification/common/common.md
> +such as `AttributePerEventCountLimit` or `AttributePerLinkCountLimit`.
If we plan to allow these, they need to be specified. Otherwise, there is potential for different implementations to use different values.

2021-06-18 17:38 UTC, MrAlias commented on specification/common/common.md
> +<a name="attribute-limits-configuration"></a>
Why the HTML and not a markdown link?

2021-06-18 17:38 UTC, MrAlias commented on specification/common/common.md
> +* `AttributeCountLimit` (Default=128) - Maximum allowed attribute count per record;
Having a default of 128 is at odds with the statement:

> By default, attribute lists and values SHOULD NOT be truncated.

2021-06-18 17:38 UTC, MrAlias commented on specification/metrics/sdk.md
> +Configuration of [Measurement Limits](#measurement-limits) MUST be managed
Agreed, I would like to have a better defined metrics telemetry pipeline before adding this. Especially if the common definitions can be written in a way that they would apply to all signals.

2021-06-18 17:38 UTC, MrAlias commented on specification/sdk-environment-variables.md
> +| OTEL_ATTRIBUTE_VALUE_LENGTH_LIMIT | Maximum allowed attribute value size |         | Empty value is treated as infinity. Non-integer and negative values are invalid. |
How are invalid values handled? Should the default infinite be used?

2021-06-18 19:19 UTC, jkwatson commented on specification/common/common.md
> +    1), SDK Spans MUST truncate that value, so that its length is at most equal
I don't disagree, but if we had to implement byte-counting for characters in java, that would be tricky, as it would depend on the encoding to use, which isn't really known until export time.

2021-06-18 19:29 UTC, MrAlias commented on specification/common/common.md
> +    1), SDK Spans MUST truncate that value, so that its length is at most equal
Hmm. @jkwatson does character counting the best we can do then in Java (and I'm guessing in other languages)?

Is it possible to use the maximum character width allowed (if that is possible to know?) multiplied by the characters?

2021-06-18 20:27 UTC, jkwatson commented on specification/common/common.md
> +    1), SDK Spans MUST truncate that value, so that its length is at most equal
maximum character width is generally 4 bytes (I think?), so that would be 4x what people are normally going to use for this stuff, which is probably standard ASCII. I'd suggest just counting characters and users who know that they are using multi-byte characters frequently could adjust their limits accordingly.

2021-06-18 20:40 UTC, reyang commented on specification/common/common.md
> +limits programatically. Names of the configuration options SHOULD be the same as
```suggestion
limits programmatically. Names of the configuration options SHOULD be the same as
```

2021-06-18 20:41 UTC, reyang commented on specification/metrics/sdk.md
> +Configuration of [Measurement Limits](#measurement-limits) MUST be managed
+1 @jkwatson

2021-06-18 20:43 UTC, reyang commented on specification/common/common.md
> +- set a limit of unique attribute keys, and the limit is set:
This is a complex topic.
Do we set the limit on the SDK instance level, or provider level (e.g. if there are two TracerProviders and one provider is going crazy, do we want the other one to work independently? - my personal answer is YES)

2021-06-18 21:18 UTC, MrAlias commented on specification/common/common.md
> +    1), SDK Spans MUST truncate that value, so that its length is at most equal
> maximum character width is generally 4 bytes (I think?), so that would be 4x what people are normally going to use for this stuff, which is probably standard ASCII. I'd suggest just counting characters and users who know that they are using multi-byte characters frequently could adjust their limits accordingly.

:+1: sounds like a plan

2021-06-21 09:57 UTC, jtmalinowski commented on specification/common/common.md
> +- set an attribute value length limit and the limit is set, then for each
I think the statement a couple lines above
> (counting any character in it as 1)

is understandable.

2021-06-21 09:59 UTC, jtmalinowski commented on specification/common/common.md
> +  - otherwise a value MUST NOT be truncated;
There was a discussion about this earlier in this PR, and that's why non-strings are explicitly excluded.

2021-06-21 10:18 UTC, jtmalinowski commented on specification/common/common.md
> +- set an attribute value length limit and the limit is set, then for each
That doesn't seem like a risk worth addressing. For this to happen you'd need to have a complex logic of generating keys. That said, maybe someone with longer instrumentation tenure can chime in.

2021-06-21 10:32 UTC, jtmalinowski commented on specification/common/common.md
> +truncated. To prevent excessive logging, the log MUST NOT be emitted more than
Yes, done.

2021-06-21 10:35 UTC, jtmalinowski commented on specification/sdk-environment-variables.md
> +| OTEL_ATTRIBUTE_VALUE_LENGTH_LIMIT | Maximum allowed attribute value size |         | Empty value is treated as infinity. Non-integer and negative values are invalid. |
I think `common/common.md` addresses this by saying
> otherwise a value MUST NOT be truncated

2021-06-21 10:47 UTC, jtmalinowski commented on specification/common/common.md
> +- set a limit of unique attribute keys, and the limit is set:
It's stated elsewhere that the limit is per data record on which the attributes are set, which to me implies that they are independent.

2021-06-21 11:45 UTC, jtmalinowski commented on specification/common/common.md
> +<a name="attribute-limits-configuration"></a>
Can I create an anchor in pure markdown? I thought [this was how everyone does it](https://stackoverflow.com/questions/5319754/cross-reference-named-anchor-in-markdown).

2021-06-21 11:55 UTC, jtmalinowski commented on specification/common/common.md
> +* `AttributeCountLimit` (Default=128) - Maximum allowed attribute count per record;
Fixed.

2021-06-21 12:00 UTC, jtmalinowski commented on specification/common/common.md
> +    key/value pair.
I don't know if queue terminilogy applies that well here, but hopefully it's clear now:
> [...] addition of which [attribute] would result in exceeding the limit, SDK MUST discard that key/value pair

2021-06-21 15:45 UTC, jkwatson commented on specification/common/common.md
> +* `AttributeCountLimit` (Default=128) - Maximum allowed attribute count per record;
I don't think we should have a default value for this. I think we should stay with the current behavior as the default, which is no truncation. Otherwise people are going to have a surprising potentially breaking change to their telemetry when they upgrade to a version of the SDK that has a default.

2021-06-21 21:23 UTC, jtmalinowski commented on specification/common/common.md
> +* `AttributeCountLimit` (Default=128) - Maximum allowed attribute count per record;
@jkwatson This default is the same as the one which currently exists for spans, and metrics are exempt per the ask from Reiley.

2021-06-21 21:25 UTC, jtmalinowski commented
@carlosalberto hey! You were recently reviewing a quite similar https://github.com/open-telemetry/opentelemetry-specification/pull/1751, any chance you could take a look at this one?

2021-06-21 21:50 UTC, jkwatson commented on specification/common/common.md
> +* `AttributeCountLimit` (Default=128) - Maximum allowed attribute count per record;
🤦🏼  sorry, you are correct!

2021-06-21 21:51 UTC, jkwatson approved these changes

2021-06-21 22:03 UTC, obecny reviewed
overall lgtm, one comment

2021-06-21 22:03 UTC, obecny commented on specification/trace/sdk.md
>  configuration such as `AttributePerEventCountLimit` and `AttributePerLinkCountLimit`.
should those params be also reflected in environment variables as others variables for example `OTEL_SPAN_*` ?

2021-06-22 09:52 UTC, jtmalinowski commented on specification/trace/sdk.md
>  configuration such as `AttributePerEventCountLimit` and `AttributePerLinkCountLimit`.
That's being done in #1751

2021-06-22 09:56 UTC, obecny approved these changes

2021-06-23 12:16 UTC, carlosalberto approved these changes

2021-06-25 14:14 UTC, carlosalberto commented
I'd like to get one more approval from somebody of the @open-telemetry/specs-metrics-approvers group, if possible. Let's try to merge this ASAP!

2021-06-30 22:07 UTC, carlosalberto commented
@reyang @jsuereth opinion on this one?

2021-06-30 22:31 UTC, jmacd commented on specification/common/common.md
> +There SHOULD be a log emitted to indicate to the user that an attribute was
I agree with the sentiment of this paragraph -- we should tell the user when we discard or modify their telemetry data and we should be careful not to overwhelm a telemetry collection system by providing too many error messages about bad data.

This, to me, is the wrong place to specify error handling behavior. I'd like to see statements about error handling in general in the [library guidelines](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/library-guidelines.md) part of the specification. For errors like this which may occur as a result of user data, I typically configure them to print once per minute or so. I believe we should use metrics to count occurrences of excessive metric value length and/or count. 

Both of these outputs, logs and/or metrics about these events, are a form of "meta" telemetry, and the specification's SDK guidelines should say we aim to (1) do this well, (2) at low cost. For meta-telemetry logs this means once rarely per log statement, for metrics this means a requirement to have low cardinality, for example.

I propose removing this paragraph and filing an issue to update the library guidelines with general guidance on handling errors of this nature.

2021-07-02 12:01 UTC, jtmalinowski commented on specification/common/common.md
> +There SHOULD be a log emitted to indicate to the user that an attribute was
Given that this is in line with existing spec here <https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk.md#span-limits>, do you think we could leave the paragraph as is, create the issue, and once we reach a consensus, I'll create a PR which will address this?

2021-07-02 12:18 UTC, jtmalinowski commented on specification/common/common.md
> +There SHOULD be a log emitted to indicate to the user that an attribute was
@jmacd please feel free to amend the issue #1787 if you'd like to describe the problem in a different way

2021-07-05 08:31 UTC, jtmalinowski commented on specification/common/common.md
> +There SHOULD be a log emitted to indicate to the user that an attribute was
@jmacd does the above work for you?

2021-07-05 08:32 UTC, iNikem commented
@open-telemetry/technical-committee This PR has enough approvals for a long time already. Can it be merged now?

2021-07-06 13:56 UTC, carlosalberto commented
@iNikem I'd suggest to wait for @jmacd to answer (he should be back online), and if in a pair of days there wasn't answer, then let's definitely merge this.

2021-07-06 15:33 UTC, bogdandrutu commented on specification/sdk-environment-variables.md
> +| OTEL_ATTRIBUTE_COUNT_LIMIT        | Maximum allowed span attribute count | 128     |       |
What is the diff with OTEL_SPAN_ATTRIBUTE_COUNT_LIMIT?

2021-07-06 17:37 UTC, jtmalinowski commented on specification/sdk-environment-variables.md
> +| OTEL_ATTRIBUTE_COUNT_LIMIT        | Maximum allowed span attribute count | 128     |       |
Applies to all attributes, except Metrics (temporarily exempted due to experimental status), so effectively that means spans and events.

2021-07-09 10:10 UTC, jtmalinowski commented
@carlosalberto Do you think we can merge now? It seems like we've given everyone who's interested ample time for comments.

2021-07-09 16:12 UTC, MrAlias approved these changes
:rocket:

2021-07-09 16:12 UTC, MrAlias commented on specification/common/common.md
> +    1), SDK Spans MUST truncate that value, so that its length is at most equal
nit: it is the SDK that does the truncation.

```suggestion
    1), SDKs MUST truncate that value, so that its length is at most equal
```

2021-07-09 16:12 UTC, MrAlias commented on specification/sdk-environment-variables.md
> +SDK MUST first try to use the unscoped variable, if it isn't set, only then try
```suggestion
the SDK MUST first try to use the unscoped variable, if it isn't set, only then try
```

2021-07-12 10:02 UTC, jtmalinowski commented on specification/common/common.md
> +    1), SDK Spans MUST truncate that value, so that its length is at most equal
If I remember correctly, this is to specify that the truncation is done at the Span level and not elsewhere, but @carlosalberto feel free to make this call when merging.

2021-07-12 10:03 UTC, jtmalinowski commented
@carlosalberto ping!

2021-07-12 16:28 UTC, jmacd commented on specification/common/common.md
> +There SHOULD be a log emitted to indicate to the user that an attribute was
Yes.

2021-07-12 16:29 UTC, jmacd approved these changes

2021-07-12 20:05 UTC, iNikem commented
@carlosalberto Can you merge this please? :)

2021-07-12 21:05 UTC, carlosalberto commented on specification/sdk-environment-variables.md
> +| OTEL_ATTRIBUTE_COUNT_LIMIT        | Maximum allowed span attribute count | 128     |       |
Before we go ahead: how does this interact with the rest of the related environment variables? What if the user sets `OTEL_SPAN_ATTRIBUTE_COUNT_LIMIT` and also `OTEL_ATTRIBUTE_COUNT_LIMIT`? I'm guessing what you expect here, but it's not clarified anywhere.

For what is worth, if you remove this, we can totally merge this (and have this single environment variable done as a follow up, etc).

2021-07-16 10:01 UTC, jtmalinowski commented
@carlosalberto anything else I can help with here?

2021-07-16 15:16 UTC, iNikem commented
@open-telemetry/technical-committee This PR is ready to be merged for quire some time already. Anything else we shoul do before it happens?

2021-07-16 15:41 UTC, yurishkuro commented on specification/common/common.md
> +There SHOULD be a log emitted to indicate to the user that an attribute was
I think solving this issue with logging is not the ideal solution. It assumes that logging is always available, which is not always the case - many languages have no standard log framework, and even if they do, using std log is not always what the rest of the application is using. In other words, logger must always be treated as a dependency, which may or may not be available.

In addition, the throttling of the logs effectively requires keeping a state per span. So why not report truncations as part of the span itself?

Regarding #1787, why not leave this paragraph out of this PR until an agreement on #1787 is reached? We are changing the spec, after all, it's better to leave the behavior unspecified than to change it.

2021-07-17 14:10 UTC, jtmalinowski commented on specification/common/common.md
> +There SHOULD be a log emitted to indicate to the user that an attribute was
@yurishkuro I have changed "SHOULD" to "SHOULD NOT" to satisfy this criteria:
- your ask to not prescribe a solution
- don't immediately invalidate existing solutions, which may already be logging
- don't make it hard for implementors in case they really needed to log (until we have a prescribed solution)

This isn't exactly what you asked for, but I think it does the job

2021-07-17 14:29 UTC, jkwatson approved these changes

2021-07-17 14:29 UTC, jkwatson commented on specification/common/common.md
> +Execution of erroneous code can result in unintended attributes. If there is no
s/is/are/

2021-07-20 08:31 UTC, jtmalinowski commented on specification/common/common.md
> +Execution of erroneous code can result in unintended attributes. If there is no
thanks!

2021-07-20 08:35 UTC, jtmalinowski commented
@open-telemetry/technical-committee I think we addressed all concerns, could we merge it?

2021-07-20 12:32 UTC, carlosalberto commented
@jtmalinowski I still don't get a clear idea of `OTEL_ATTRIBUTE_COUNT_LIMIT` (however, the rest looks rights and definitely ready to be merged). You mentioned that

> So previously there was a paragraph about this in sdk-environment-variables

But I don't see it **right now** in the Specification (or else probably I missed what you meant). If we remove that one for now, I'm happy to merge it right away (and we can do a follow up for this one in another PR, so we don't get stuck).

2021-07-20 15:03 UTC, jtmalinowski commented
@carlosalberto `OTEL_ATTRIBUTE_COUNT_LIMIT` is for any record which can have attributes, so currently it's Span, Event, and Resource. It would also cover Metric, if it wasn't explicitly excluded. `OTEL_SPAN_ATTRIBUTE_COUNT_LIMIT` is for limiting the attributes on spans only.

The paragraph which describes it is <https://github.com/open-telemetry/opentelemetry-specification/pull/1130/files#diff-500cb43b9725373c25ea03660c293e59681e6e2f6ba3eb588188ed3b83dcbdcdR77>.

2021-07-21 21:28 UTC, cijothomas commented on specification/common/common.md
> +There SHOULD NOT be a log emitted to indicate to the user that an attribute was
```suggestion
There SHOULD be a log emitted to indicate to the user that an attribute was
```

2021-07-21 21:36 UTC, jtmalinowski commented on specification/common/common.md
> +There SHOULD NOT be a log emitted to indicate to the user that an attribute was
This is not a mistake, see https://github.com/open-telemetry/opentelemetry-specification/pull/1130#discussion_r671702102

2021-07-21 22:39 UTC, cijothomas commented on specification/common/common.md
> +There SHOULD NOT be a log emitted to indicate to the user that an attribute was
Aah! I see it now :)
When read in combination with the next sentence, it feels like "you should log, but be careful to not do excessive log."

I think your intent is "You should not log. (not a Must, so libraries may still do the logging). But if you decide to log anyway, you *must* not do excessive log"

I'll resolve this comment!

2021-07-22 00:22 UTC, jsuereth requested changes

2021-07-22 00:22 UTC, jsuereth commented on specification/metrics/sdk.md
> +the experimental status of the Metrics SDK specification.
I don't think this is true.

Our data model is stable and in it, the attributes contribute to the identity of a metric.  If we truncate attributes we need to denote how that changes the identity of the point.

I'm not sure the SDK exiting experimental status will change this point

2021-07-22 00:22 UTC, jsuereth commented on specification/metrics/sdk.md
> +[common rules of attribute limits](../common/common.md#attribute-limits) due to
It's confusing to have this here and not in the common section.

2021-07-22 14:40 UTC, jsuereth commented
To clarify my concernss on this CL:

I don't think the SDK being experimental has anything to do with metrics wanted to opt-out of Attribute limits.  This is an inherit problem to metrics, as Attributes are used to identify unique streams and there's a slew of issues that could pop up limiting them.

That said, I'd like to also see this PR get through.  My asks are for one of the following:

1. Do not have any global attribute limits (`AttributeCountLimit` or `AttributeValueLengthLimit`) in this PR.
2. For Metrics *explicitly* call out that limiting attribute lengths can alter metric identity.  
   Specifically we should say the following:
   - Limiting attribute length can lead to duplicate (identity) metric points being exported, especially for verbose labels where the tailing-end of the label contains the important part.   E.g. `"processor"; "com.java.really.long.package.name.FooBar".   In this case, we should be encouraging users to use the shortest, readable metric attributes.
   - Limiting the # of attributes could lead to duplicate metric time series being emitted from the SDK.  Here we should inform users that this is considered a configuration error, and we expect them to provide a high enough value for metric streams *or* provide `View` aggregation to unify duplicate strings.   We can leave the error reporting + mechanism for this TBD, but we need to call out this is a very real problem in the current (stable) data model.

2021-07-22 16:44 UTC, jtmalinowski commented
@jsuereth

> Do not have any global attribute limits (AttributeCountLimit or AttributeValueLengthLimit) in this PR.

This might be tough because it means renegotiating the models (Span, Resource, Event, Metric, Measurement) on which we're going to put the limits. Or undo all the discussions and stick to just Spans.

> For Metrics explicitly call out that limiting attribute lengths can alter metric identity.

Okay that's fine, we can easily add the reasoning and explanations, but then shouldn't @reyang green light this? He was in favor of exempting Metrics from the attribute limits.

2021-07-26 09:47 UTC, jtmalinowski commented
Hey all, I very much appreciate all the comments and suggestions on this PR, but I have doubts as to whether a full consensus is reachable soon. Perhaps it'd be useful to limit change requests to problems which are blockers, and I'll do my best to followup on all non-blocking comments by creating and owning issues to follow up on them.

2021-07-26 13:11 UTC, yurishkuro commented on specification/common/common.md
> +- set an attribute value length limit and the limit is set, then for each
```suggestion
- set an attribute value length limit such that for each
```

2021-07-26 13:11 UTC, yurishkuro commented on specification/common/common.md
> +- set a limit of unique attribute keys, and the limit is set:
```suggestion
- set a limit of unique attribute keys such that:
```

2021-07-26 13:11 UTC, yurishkuro commented on specification/common/common.md
> +There SHOULD NOT be a log emitted to indicate to the user that an attribute was
```suggestion
There MAY be a log emitted to indicate to the user that an attribute was
```

2021-07-26 13:13 UTC, jsuereth commented
@jtmalinowski and I discussed this offline.


Action Items:

1. @jtmalinowski is going to update this PR so the metric-exemption is called out where the global attribute limit is defined, making it clear to implementers (and hopefully their documentation) that metrics are NOT impacted by this setting.
2. @jtmalinowski is going to open a bug/feature request to support metrics for Attribute limits.   Specifically we need to deal with the issues of:
  - Metric Identity overlap post-truncation
  - Which attributes should be kept for metrics? (@reyang has this hint-api idea for preserving important attributes)
  - Should attribute truncation happen before or after `View` attribute truncation?
  - Should attribute truncation in metrics be considered user configuration error?

2021-07-27 11:14 UTC, jtmalinowski commented on specification/common/common.md
> +There SHOULD NOT be a log emitted to indicate to the user that an attribute was
Okay, if you prefer it this way.

2021-07-27 12:13 UTC, jtmalinowski commented
@arminru @jsuereth @yurishkuro All issues addressed!

2021-07-27 14:08 UTC, yurishkuro commented on specification/common/common.md
> +Attributes which belong to Metrics MUST NOT implement the aforementioned
again, you cannot put MUST's into spec if the intention is to change the rules in the near future. It's not a backwards compatible change. Either leave the behavior unspecified or use the weak MAY.

2021-07-27 14:36 UTC, yurishkuro approved these changes

2021-07-27 17:18 UTC, jmacd approved these changes

2021-07-27 18:27 UTC, iNikem commented
@jsuereth Do you approve or something else should be changed?

2021-07-29 13:32 UTC, jsuereth approved these changes

2021-07-29 13:33 UTC, jsuereth commented
Sorry for delay @iNikem.  Changes LGTM

2021-07-29 13:42 UTC, jtmalinowski commented
@arminru Let's do it 🚀

2021-07-29 19:03 UTC, carlosalberto commented
Fine to merge but I **really** want to have a follow up having what happens when you define both `OTEL_ATTRIBUTE_COUNT_LIMIT` and related variables, e.g. `OTEL_SPAN_ATTRIBUTE_COUNT_LIMIT`. At this moment it's not clear which one has higher priority.

2021-07-30 09:55 UTC, jtmalinowski commented
@carlosalberto https://github.com/open-telemetry/opentelemetry-specification/pull/1130/files#diff-500cb43b9725373c25ea03660c293e59681e6e2f6ba3eb588188ed3b83dcbdcdR78 describes it like so:
> An SDK MAY implement model-specific limits, for example `SpanAttributeCountLimit`. If both a general and a model-specific limit are implemented, then the SDK MUST first attempt to use the model-specific limit [...]

I think that it can be inferred from the context that it extends to environment variables, ie. if `OTEL_SPAN_ATTRIBUTE_COUNT_LIMIT` is set or has a default then for Span Attributes it takes priority.

2021-08-03 13:33 UTC, iNikem commented
@open-telemetry/technical-committee can anybody press merge?

2021-08-03 22:25 UTC, carlosalberto commented
> I think that it can be inferred from the context that it extends to environment variables, ie. if OTEL_SPAN_ATTRIBUTE_COUNT_LIMIT is set or has a default then for Span Attributes it takes priority.

I think we can do better than leave things inferred and we can put a link to this section from the env vars ;) But let's definitely do that as a minor amendment after this PR.

2021-08-03 22:26 UTC, merged