Span processor clarifications
open-telemetry/opentelemetry-specification pull request #1135
Opened 2020-10-23 00:20 UTC by rachelleahklein

## Changes

This PR attempts to clarify information about span processors in the Trace SDK spec. It contains:
* More information about when one might want to use a simple vs. batching span processor
* More information about scenarios in which span processors may be used without exporters
* Minor grammatical fixes

Related issues #
The need for clarification in the spec came to my attention when it was mentioned in this ticket: https://github.com/open-telemetry/opentelemetry-ruby/issues/397.

2020-10-23 00:32 UTC, SergeyKanzhelev commented on specification/trace/sdk.md
> +Typically, the simple processor will be most suitable for use in testing and/or
it may be used in production for adding attributes like here: https://medium.com/opentelemetry/opentelemetry-beyond-getting-started-5ac43cd0fe26#ffbb:~:text=Custom%20attributes%20in%20code%20scopes

2020-10-23 00:33 UTC, SergeyKanzhelev requested changes
thank you for PR. I added comment on one more scenario for processor. Current edit may mislead

2020-10-23 00:37 UTC, rachelleahklein commented
Thanks for the quick response! I will add that further clarification.

2020-10-23 02:49 UTC, reyang commented on specification/trace/sdk.md
> +exportable representation and passing batches to exporters or alternatives to
Not sure if a GA spec should point to an experimental spec, thoughts?

2020-10-23 08:03 UTC, Oberon00 commented on specification/trace/sdk.md
>  configured `SpanExporter`.
```suggestion
This is an implementation of `SpanProcessor` which collects finished spans into batches
and passes the export-friendly span data representations to the associated `SpanExporter`.
```

2020-10-23 08:03 UTC, Oberon00 commented on specification/trace/sdk.md
> +than the simple processor.
Depends on the language, e.g. in Java exporters do batching themselves sometimes. But typically, I think that BatchSpanProcessor should be the expected scenario, yes.

2020-10-23 08:03 UTC, Oberon00 commented on specification/trace/sdk.md
>    dropped. The default value is `2048`.
This is now misleading because the spans cannot really be dropped (as in sampled out) because the SpanProcessor has no back-channel to the TracerProvider. Would be nice if this was possible, but for now I'd say

```suggestion
  skipped by this BatchSpanProcessor. The default value is `2048`.
```

2020-10-23 08:04 UTC, Oberon00 commented on specification/trace/sdk.md
I think we should remove this paragraph. Or do you know what is meant by it? AFAIK the TracerProvider must allow the registration of multiple SpanProcessors, but each built-in span processor only supports a single exporter.

```suggestion
```

2020-10-23 08:11 UTC, Oberon00 commented on specification/trace/sdk.md
I think we should remove this paragraph too. Unless someone can tell what "tagging" means here or how the SDK can allow "filtering". CC @lmolkova 

```suggestion
```

2020-10-23 17:06 UTC, rachelleahklein commented on specification/trace/sdk.md
> +exportable representation and passing batches to exporters or alternatives to
Would it be true then to say "and passing batches to exporters or other span processors," or are there still other alternatives?

2020-10-23 17:31 UTC, rachelleahklein commented on specification/trace/sdk.md
> +Typically, the simple processor will be most suitable for use in testing and/or
Thanks for your valuable feedback on this section as well as the batch processor one, @Oberon00. Do you think more should be added to clarify that while these statements may "typically" be true, it also depends on language implementation? I'm not sure how much detail to get into here.

2020-10-23 17:37 UTC, rachelleahklein commented on specification/trace/sdk.md
Personally, I don't feel qualified to recommend whether this paragraph should be removed. I wasn't trying to clarify any concepts here, just cleaning up. Hopefully others can weigh in.

2020-10-23 18:00 UTC, rachelleahklein commented on specification/trace/sdk.md
> +exportable representation and passing batches to exporters or alternatives to
Also, to @reyang's point, I am not even sure referring to zPages specifically makes sense here. My only goal is to have a clear definition of span processors in this sentence. Reading this section, I was confused by the fact that span processors were defined as "responsible for... passing batches to exporters" but then a few lines down, exporters are described as optional.

2020-10-24 10:41 UTC, iNikem commented on specification/trace/sdk.md
The paragraph itself is needed, at least the part about adding custom processors. Examples "tagging or filtering" are indeed misleading and may be removed.

2020-10-24 10:46 UTC, iNikem commented on specification/trace/sdk.md
I think we definitely need some better description of the possible compositions of `SpanProcessors` and `SpanExporters`. E.g. we MUST indicate somewhere that there should be a `SpanProcessor` before each `SpanExporter` (purely from methods signatures point of view). We also MUST stress and clearly describe that multiple registered `SpanProcessor` are "siblings" and do NOT call each other. All this has already created some confusion in the past.

2020-10-24 10:48 UTC, iNikem approved these changes
This PR does not solve existing problems with the current description, but it is a nice cleanup. Thank you! :)

2020-10-26 17:50 UTC, rachelleahklein commented
I have attempted to address @SergeyKanzhelev's requested change. Please let me know if more clarification is needed there.

Thanks to all who have submitted feedback. I think there are a few things that are potentially outside the scope of this PR, but I have tried to incorporate fixes that are straightforward.

One outstanding question I have: does the overall definition of span processors (see discussion on ln. 290) need to be further fixed?

2020-10-26 18:21 UTC, SergeyKanzhelev commented on specification/trace/sdk.md
> +exportable representation and passing batches to exporters or alternatives to
I don't see a problem referring to experimental feature as it makes the point that this is an extensibility point in SDK that can be useful for purposes including experimentation with the new features.

2020-10-26 18:24 UTC, SergeyKanzhelev commented on specification/trace/sdk.md
> +Typically, the simple processor will be most suitable for use in testing. Exceptions to this
I don't want to position these non-testing scenarios as exceptions. These should be used with caution, but they are valid use cases for production use

2020-10-26 18:25 UTC, SergeyKanzhelev commented on specification/trace/sdk.md
> +than the simple processor.
I like how it's written. Wdyt @Oberon00?

2020-10-26 18:26 UTC, SergeyKanzhelev commented
@rachelleahklein thanks again for the PR. The only outstanding feedback from me is to position simple span processor scenarios as dangerous, but valid for production (not as exceptions).

2020-10-26 20:04 UTC, Oberon00 commented on specification/trace/sdk.md
> +than the simple processor.
I think the PR's wording is fine here 👍

2020-10-26 20:51 UTC, SergeyKanzhelev approved these changes
This is an improvement to the wording without semantical change. Thank you!

2020-10-26 22:45 UTC, justinfoote approved these changes
Thank's for the clarifications @rachelleahklein!

2020-10-27 06:36 UTC, jmacd commented on specification/trace/sdk.md
I support removing this paragraph. We don't need to specify that pipelines end in exporters, just that the two builtin span processors end in exporters. The metric SDK hasn't thus far mentioned support for multiple processors, and why should we? It's possible to define a multi-processor that calls a series of individual processors. Should the default trace SDK include a builtin multi-processor? I suppose they should if it's common to implement multiple trace exporters with different processor settings, but that does not sound common. Wouldn't you prefer to have a single processor call multiple exporters? Why do we need to specify these things?

> multiple registered SpanProcessor are "siblings" and do NOT call each other

If you only specify SDK support for a single processor, this problem vanishes. Potentially you can also specify a multi-processor and/or a multi-exporter, but are you sure these are commonly needed?

2020-10-28 20:39 UTC, rachelleahklein commented on specification/trace/sdk.md
For what it's worth, as someone relatively new to OpenTelemetry concepts, it was helpful to me to have a textual description the span processor pipeline in addition to the diagram that also exists in this section. There may be some additional nuance that needs to be added, but having some form of this paragraph seems like a good idea to me.

2020-10-30 15:09 UTC, cijothomas commented on specification/trace/sdk.md
> +Typically, the simple processor will be most suitable for use in testing; it should be used with
Not sure this should be mentioned here.
We have production systems running using SimpleProcessors. In those systems, the OpenTelemetry SDK uses SimpleProcessor and exports the span as they arrive, without any batching. 
The export may be done to some agent, which in turn may do batching.
Or Export could be done to the actual backend, to enable scenarios like "Live telemetry".  Eg in Azure: https://docs.microsoft.com/azure/azure-monitor/app/live-stream

2020-11-07 06:57 UTC, SergeyKanzhelev commented on specification/trace/sdk.md
> +caution in production. It may be appropriate for production use in scenarios where creating
```suggestion
Typically, the simple processor will be most suitable for use in testing; it should be used with
The simple processor must not be used lightly in production. It runs on application thread and may
degrade performance. It may be appropriate for production use in scenarios where creating
```

2020-11-07 07:00 UTC, SergeyKanzhelev commented on specification/trace/sdk.md
```suggestion
custom attributes should be added to individual spans based on code scopes. Simple processors
might also be used for scenarios where the callback needs to be called before sampling. For
example, z-pages can be implemented this way.

```

2020-11-07 07:00 UTC, SergeyKanzhelev commented on specification/trace/sdk.md
> +Typically, the simple processor will be most suitable for use in testing; it should be used with
Added couple suggestions. @anuraaga, @cijothomas are these suggestions looks OK for you?

2020-11-07 08:13 UTC, Oberon00 commented on specification/trace/sdk.md
This is wrong though. The simple processor is also not invoked for DROPped spans.

2020-11-09 02:54 UTC, rachelleahklein commented on specification/trace/sdk.md
> +Typically, the simple processor will be most suitable for use in testing; it should be used with
Thank you for adding more suggestions, @SergeyKanzhelev. I have incorporated the first (though happy to revert or refine if there are further comments).

The second is still open and I'm hoping @Oberon00 or others can help clarify a more accurate version.

Thank you all!

2020-11-09 20:02 UTC, SergeyKanzhelev commented on specification/trace/sdk.md
hm, I'm referring to the sampled flag as oppose to the recorded flag. Recorded, but sampled out spans should not make it to the batch processor, correct? Recorded will be processed by simple processors. dropped will not reach either

2020-11-17 04:21 UTC, rachelleahklein commented
I don't seem to be able to reopen this PR, but I still do hope to work on it and get it approved. It sounds like there are some clarifications that people have found helpful. Please let me know if there is any further feedback I can address. Thank you.

2020-11-17 19:48 UTC, bogdandrutu commented on specification/trace/sdk.md
> +exportable representation and passing batches to exporters or alternatives to
I think we are mixing 2 different things in this sentence:
1. What is a SpanProcessor, and how can this be used to interact with the SDK.
  - The SpanProcessor in general does not need to batch or talk to the exporter, it is a simple "hook" that allows custom processors to interact with the Span lifetime events (on start and on end). For example somebody can implement a processor that tracks all the active requests (one of the functionality that we want to offer in the zPages). Others can implement different other functionality.
2. What are the "built-in" SpanProcessors.
  - We will provide 2 flavors of SpanProcessors (Simple/Batch) that are able to batch (or not in case of simple), transform the Spans in an "exportable" format, and call the "exporter".

2020-12-02 03:25 UTC, closed without merging