Add db.table to database semantic conventions
open-telemetry/opentelemetry-specification pull request #1141
Opened 2020-10-23 19:27 UTC by justinfoote

Fixes #1104

## Changes

This PR adds a new attribute to the trace semantic conventions for database operations: `db.table`, and adds guidance that this attribute should be set only if the value is readily available from the library being instrumented. 
It also changes the guidance around `db.operation` to indicate that it should be set to the SQL keyword, but also only if the value is readily available from the library being instrumented.

2020-10-24 10:37 UTC, iNikem approved these changes

2020-10-24 10:48 UTC, anuraaga approved these changes
Table is important, this seems nice

2020-10-24 10:48 UTC, anuraaga commented on specification/trace/semantic_conventions/database.md
> +**[4]:** It is not recommended to attempt any client-side parsing of `db.statement` just to get this property, but it should be set if  the operation name is provided by the library being instrumente
```suggestion
**[4]:** It is not recommended to attempt any client-side parsing of `db.statement` just to get this property, but it should be set if the operation name is provided by the library being instrumented. If the statement has an ambiguous operation, or performs more than one operation, this value may be omitted.
```

2020-10-24 11:00 UTC, Oberon00 commented on semantic_conventions/trace/database.yaml
> +            If the statement has an ambiguous operation, or performs more than
This seems to imply that operation is always derived from statement, which is not true. In fact, the main purpose of this attribute is to support DBs that do not use a statement/query language as their API, such as CouchDB.

2020-10-25 16:29 UTC, justinfoote commented on semantic_conventions/trace/database.yaml
> +            If the statement has an ambiguous operation, or performs more than
Yeah, I see your point. This certainly was not my intention.  

In the main "brief" description of this attribute, we still list the mongo example first. We could add a few more examples there. 

Or I wonder if it would be better to include something in the footnote like this:

```yaml
note: >
    In the case of SQL databases, the operation should be set to the SQL keyword
    (example: `SELECT` or `INSERT`). 
    It is not recommended to attempt any client-side parsing of
    `db.statement` just to get this property, but it should be set if 
    the operation name is provided by the library being instrumented.
    If the statement has an ambiguous operation, or performs more than
    one operation, this value may be omitted.
```

Is this redundant with the note in the 'required' column: "Required, if `db.statement` is not available."

What do you think?

2020-10-27 00:18 UTC, jmacd approved these changes

2020-10-27 08:55 UTC, thisthat commented on semantic_conventions/trace/database.yaml
> +            If the operation is acting upon an anonymous table, or more than one
```suggestion
            it is provided by the library being instrumented. If the operation
            is acting upon an anonymous table, or more than one
```
See https://github.com/open-telemetry/opentelemetry-specification/pull/1141/files#r511390753

2020-10-29 20:36 UTC, justinfoote commented
@open-telemetry/technical-committee Is this ready to merge?

2020-10-30 16:31 UTC, Oberon00 commented on semantic_conventions/trace/database.yaml
> +            It is not recommended to attempt any client-side parsing of
```suggestion
            When setting this to an SQL keyword, it is not recommended to attempt any client-side parsing of
```

2020-10-30 16:31 UTC, Oberon00 commented on semantic_conventions/trace/database.yaml
> +            If the statement has an ambiguous operation, or performs more than
```suggestion
            If the SQL statement has an ambiguous operation, or performs more than
```

2020-10-30 16:31 UTC, Oberon00 commented on semantic_conventions/trace/database.yaml
> +            If the statement has an ambiguous operation, or performs more than
I suggested a simpler change by emphasizing that that part only applies to SQL.

2020-10-30 16:34 UTC, Oberon00 commented on semantic_conventions/trace/database.yaml
> +        - id: table
Actually I just realized that the term `table` is probably specific to SQL. Thus I recommend adding this to a new semantic convention `db.sql` in this file that `extends: db` and has this table attribute, so that the full name is `db.sql.table`.

2020-10-30 16:35 UTC, Oberon00 requested changes
Requesting changes because I have concerns for adding this SQL-specific attribute to the very general DB conventions.

2020-10-30 16:36 UTC, Oberon00 commented on semantic_conventions/trace/database.yaml
> +        - id: table
An alternative might be to have a more generic term, but since a table likely has no 1:1 mapping to other DB concepts (there might be several concepts that match a bit), I think having this in a SQL-specific convention would be easier.

2020-10-30 16:45 UTC, justinfoote commented on semantic_conventions/trace/database.yaml
> +        - id: table
This is a good idea.  I'll leave the operation where it is, but more the table to an SQL specific section in _Call-level attributes for specific technologies_.

2020-10-30 16:54 UTC, justinfoote commented on semantic_conventions/trace/database.yaml
> +            If the statement has an ambiguous operation, or performs more than
:+1: changed in ff2e13b

2020-10-30 16:54 UTC, justinfoote commented on semantic_conventions/trace/database.yaml
> +            It is not recommended to attempt any client-side parsing of
:+1: changed in ff2e13b

2020-10-30 16:54 UTC, justinfoote commented on semantic_conventions/trace/database.yaml
> +        - id: table
Done in 657670c

2020-10-30 16:56 UTC, Oberon00 approved these changes
LGTM! Thanks for responding to my comments so quickly!

2020-11-02 18:27 UTC, justinfoote commented
@open-telemetry/technical-committee I think this actually is ready to merge now.

2020-11-03 09:59 UTC, arminru approved these changes

2020-11-03 09:59 UTC, arminru commented on semantic_conventions/trace/database.yaml
> +            value may be omitted.
```suggestion
            value SHOULD be omitted.
```
We could even make this a SHOULD.

2020-11-03 10:09 UTC, Oberon00 commented on semantic_conventions/trace/database.yaml
> +            value may be omitted.
Or must, as it does not make sense.

2020-11-03 12:12 UTC, arminru commented on semantic_conventions/trace/database.yaml
> +            value may be omitted.
```suggestion
            value MUST NOT be set.
```
then

2020-11-06 03:15 UTC, justinfoote commented
@bogdandrutu @jmacd -- this is the PR I mentioned in the metrics SIG today that's holding up the [database metrics semantic conventions](https://github.com/open-telemetry/opentelemetry-specification/pull/1076).

2020-11-09 16:53 UTC, arminru commented
@justinfoote Sorry I've missed that before: Could you please add an entry in the changelog to make people aware of the new `table` and the changed `operation` attribute? Once that's done we can merge this PR right away.

2020-11-09 18:07 UTC, justinfoote commented
@arminru Added to the changelog in 862361f.

2020-11-09 18:47 UTC, merged

2020-11-10 16:17 UTC, jamal commented
One question about this change, I noticed that we still have `db.mongodb.collection`. Is it expected to use both or should the other be deprecated in favor of `db.table`?

2020-11-10 16:27 UTC, arminru commented
@jamal Actually we should have updated the PR name and changelog entry - it is called `db.sql.table` now and explicitly only applies to SQL-like databases and is thus _not_ a replacement for the dedicated `db.mongodb.collection`.

2020-11-10 18:12 UTC, jamal commented
@arminru Ah, I missed that, thank you. This definitely solves _some_ of the problems I wanted to solve.

An aside but being new to all of this, I'm a bit curious. Was this discussed in a specification meeting? I don't see any conversations around this in the PR, and I would have loved to be able to provide some feedback.

Having a specific solution for sql makes sense, since table is not a generic name (for example, Mongo). But, there are cases I wanted to cover as well that don't make sense. For example, Redis doesn't have a concept of table / collection. But, in our own implementation we introduced a wrapper over Lettuce to allow us to specify a collection name at the connection level. This allows us to segment metrics / traces, and I was hoping to extend our own instrumentation to tag this in traces. Obviously, this is not standard so it wouldn't be part of the spec.

But, because this change is specific to SQL, vendors / backends may not support this for Redis and allow us to provide this enhancement. I wonder if there are any thoughts on how to support cases like this?

I'll review other cases to see if I can think of other gaps I would want to make sure are covered and will open a separate issue if it comes up.

Thanks so much!

2020-11-10 18:17 UTC, Oberon00 commented
> Was this discussed in a specification meeting? I don't see any conversations around this in the PR, and I would have loved to be able to provide some feedback.

There is more discussion in the linked issue #1104. I don' remember this being discussed in a meeting.

2020-11-10 19:05 UTC, jamal commented
@Oberon00 Oh, sorry, I feel silly. Totally missed that conversation when I checked the Issue again. Thanks! I'll think through this and will start a separate conversation if I have any recommendations on how this could be extended. Thanks so much!