Updating gRPC status semantic conventions
open-telemetry/opentelemetry-specification pull request #1156
Opened 2020-10-30 04:39 UTC by toumorokoshi

Since the simplification of trace status codes,
they no longer align with gRPC.

Clarifying the expected status code field for gRPC, as
well as the mappings between gRPC and OpenTelemetry status.

Fixes #1044 

Related issues #

* https://github.com/open-telemetry/opentelemetry-python/pull/1308

2020-10-30 07:39 UTC, iNikem approved these changes

2020-10-30 08:19 UTC, Oberon00 commented on specification/trace/semantic_conventions/rpc.md
> +`rpc.grpc.status_code` MUST be set to the status code of the gRPC operation.
While I generally agree with that, you cannot write it like that. Please make sure a new `rpc.grpc` convention that `extends: rpc` is added to the YAML model and the property is defined there.
In doing that, you will notice that you do not say here whether this semantic convention should use the code (number) or any name of that code (string). I think it must use the integer code, because the names can vary across languages.

2020-10-30 09:19 UTC, Oberon00 requested changes
Requesting changes, because it is not clear whether numeric or symbolic status code must be used (and if symbolic, which symbolic name)

2020-10-31 17:50 UTC, Oberon00 reviewed
Thank you for the update! 😃  Just a few smaller bits & pieces left before I think this is ready.

Were you able to find the documentation for the markdown tool? If not, where would you have looked? Maybe we can improve the situation here by placing more links to it in different places?

2020-10-31 17:50 UTC, Oberon00 commented on semantic_conventions/trace/rpc.yaml
> +          examples: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]
OK, unfortunately the examples are kinda pointless here, but since they are required, maybe use a bit fewer at least.

```suggestion
          examples: [0, 1, 16]
```

2020-10-31 17:50 UTC, Oberon00 commented on semantic_conventions/trace/rpc.yaml
> +          type: number
Hmm, this would logically be an integer enum but I don't think we support that yet, @thisthat ?

2020-10-31 17:50 UTC, Oberon00 commented on specification/trace/semantic_conventions/rpc.md
> +`rpc.grpc.status_code` MUST be set to the status code number of the gRPC operation.
This should now be replaced by the generated attribute table for grpc:

```suggestion

### Attributes

<!-- semconv rpc.grpc -->
<!-- endsemconv -->
```

And then run `make table-generation` (see https://github.com/open-telemetry/opentelemetry-specification/tree/master/semantic_conventions#generation)

2020-10-31 17:50 UTC, Oberon00 commented on semantic_conventions/trace/rpc.yaml
> +          tag: call-level-tech-specific
Since you never filter by tag in the markdown, I think you don't need this.

2020-10-31 17:50 UTC, Oberon00 commented on semantic_conventions/trace/rpc.yaml
> +          brief: "the status code number of the gRPC request."
```suggestion
          brief: "The [numeric status code](https://github.com/grpc/grpc/blob/v1.33.2/doc/statuscodes.md) of the gRPC request."
```

2020-10-31 17:51 UTC, Oberon00 commented on semantic_conventions/trace/rpc.yaml
> +      brief: 'Call-level attributes for gRPC'
Why Call-level?

```suggestion
      brief: 'Tech-specific attributes for gRPC.'
```

2020-10-31 21:19 UTC, toumorokoshi commented on semantic_conventions/trace/rpc.yaml
> +          examples: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]
not strongly opinionated, can do. I figured since it was short might as well enumerate all values.

2020-11-01 06:49 UTC, anuraaga commented on specification/trace/semantic_conventions/rpc.md
> +`rpc.grpc.status_code` MUST be set to the status code number of the gRPC operation.
I guess if we replace the MD we lose the other attributes for measage. Should we move those into the yml too?

2020-11-01 12:08 UTC, Oberon00 commented on semantic_conventions/trace/rpc.yaml
> +          examples: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]
No strong opinion either. Fine for me to keep as-is.

2020-11-01 12:10 UTC, Oberon00 commented on specification/trace/semantic_conventions/rpc.md
> +`rpc.grpc.status_code` MUST be set to the status code number of the gRPC operation.
Which do you mean? The message attributes are still literally in the markdown after my suggestion.

The generator does not really support events yet.

2020-11-02 13:47 UTC, toumorokoshi commented on semantic_conventions/trace/rpc.yaml
> +          type: number
I didn't see any... https://github.com/open-telemetry/build-tools/issues/19

2020-11-02 13:52 UTC, toumorokoshi commented on semantic_conventions/trace/rpc.yaml
> +          tag: call-level-tech-specific
I was considering adding tags to make them consistent with what I've seen the in the YAML, but can remove.

2020-11-02 13:56 UTC, Oberon00 approved these changes
Thank you!

2020-11-02 13:59 UTC, toumorokoshi commented on semantic_conventions/trace/rpc.yaml
> +          examples: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]
for posterity, I did go with the suggestion because otherwise the generated table results in a very tall row (due to each example being on a different row).

2020-11-03 11:02 UTC, arminru approved these changes

2020-11-03 11:02 UTC, arminru commented on specification/trace/semantic_conventions/rpc.md
> +### Attributes
Please run `markdown-toc` or add it manually above

2020-11-03 11:02 UTC, arminru commented on specification/trace/semantic_conventions/rpc.md
> +The [Span Status](../api.md#set-status) MUST be left unset for an OK gRPC status code, and `Error` for all others.
```suggestion
The [Span Status](../api.md#set-status) MUST be left unset for an `OK` gRPC status code, and set to `Error` for all others.
```

2020-11-04 21:17 UTC, toumorokoshi commented on specification/trace/semantic_conventions/rpc.md
> +### Attributes
done! the headings ended up colliding so I renamed them.

2020-11-05 07:48 UTC, thisthat approved these changes

2020-11-05 07:48 UTC, thisthat commented on semantic_conventions/trace/rpc.yaml
> +          type: number
Sorry for the late response :sweat_smile: 
It is already possible to declare an integer enum with the current tool :sunglasses: 
```suggestion
          type:
            allow_custom_values: false
            members:
              - id: OK
                value: 0
              - id: CANCELLED
                value: 1
              ....
```

2020-11-05 21:53 UTC, SergeyKanzhelev commented on semantic_conventions/trace/rpc.yaml
> +          type: number
let's add this?

2020-11-06 07:36 UTC, Oberon00 approved these changes

2020-11-06 12:46 UTC, Oberon00 approved these changes

2020-11-06 23:05 UTC, SergeyKanzhelev approved these changes

2020-11-06 23:06 UTC, SergeyKanzhelev commented
No semantical change for 2 days and enough approvals. Merging

2020-11-06 23:06 UTC, merged