Rename trace/ to tracing/.
open-telemetry/opentelemetry-specification pull request #1166
Opened 2020-10-31 18:06 UTC by Oberon00

"A Trace can be thought of as a directed acyclic graph (DAG) of Spans"

but this is not exactly what the tracing spec is about.

Fixes #1165

Related issues open-telemetry/opentelemetry-java#1948

2020-10-31 18:27 UTC, Oberon00 commented
One issue here is that we already have `TRACE_`  as prefix in environment variable names. I do not change this here as it would be more than an editorial change, and for envvar names, the shortness might actually even matter.

2020-10-31 18:30 UTC, Oberon00 commented on .github/ISSUE_TEMPLATE/trace.md
> +labels: spec:tracing
The label itself would have to be renamed in the github repository settings when merging this.

2020-10-31 18:30 UTC, Oberon00 commented on specification/library-layout.md
> +   ├── tracing
As this is only a guideline, I think changing this is OK as SIGs can still keep the old name if they want (Java was actually using `tracing`, see e.g. https://github.com/open-telemetry/opentelemetry-java/tree/v0.9.1/sdk/tracing.

2020-11-01 04:09 UTC, anuraaga approved these changes

2020-11-03 00:05 UTC, carlosalberto commented on specification/library-layout.md
> +   ├── tracing
(Although, to be clear, the package name itself still uses `trace`)

2020-11-03 00:10 UTC, carlosalberto commented
We already had this discussion long time ago, although I can't find the issue right now (@bogdandrutu @yurishkuro or @SergeyKanzhelev may remember this).

Personally I don't see any actual value in this, and I'm _slightly_ opposed to it - this is not a big change in itself, but we would probably end up de facto forcing SIGs to change their packages.

2020-11-03 14:56 UTC, tigrannajaryan requested changes
We are breaking external links to spec files with this rename (I personally used plenty in outside repos, source codes and documents). I am opposed to this change unless I hear a good justification or someone knows a way to avoid breaking the links (there is no way to 301 redirect github content, is it?).

2020-11-03 14:59 UTC, Oberon00 commented
@tigrannajaryan You should usually not link to master but a specific commit or version tag (e.g. https://github.com/open-telemetry/opentelemetry-specification/blob/v0.6.0/specification/trace/api.md will never break, also not after this PR). That said, in practice many probably don't follow this best-practice.

2020-11-03 15:12 UTC, tigrannajaryan commented
> @tigrannajaryan You should usually not link to master but a specific commit or version tag (e.g. https://github.com/open-telemetry/opentelemetry-specification/blob/v0.6.0/specification/trace/api.md will never break, also not after this PR). That said, in practice many probably don't follow this best-practice.

@Oberon00 that's a good advice that I will follow for the future, but unfortunately doesn't help with already existing links. It will be very difficult for me to go back, find and fix all links that I used in the past. I am guessing it is not just me, others may have done it too.

2020-11-03 16:35 UTC, Oberon00 commented
Shortly talked about this in SIG spec, too little value, too risky now. See issue.

2020-11-03 16:35 UTC, closed without merging