Map `Error` `Status` to `error` tag in Zipkin & Jaeger
open-telemetry/opentelemetry-specification pull request #1257
Opened 2020-11-23 18:42 UTC by CodeBlanch

## Changes

* Switched from `ERROR`, `OK`, & `UNSET` to `Error`, `Ok`, & `Unset` in Zipkin exporter spec. Those seemed like the official names, I suspect the casing was an oversight. I will revert if that casing was intentional.
* Added `Status` mapping to Jaeger which is the same as Zipkin.
* Defined mapping of `Error` `Status` to `error` tag for Zipkin & Jaeger.
* Added a row in the compliance matrix for the `Error` mapping.

/cc @cijothomas @yurishkuro @tedsuo @adriancole

2020-11-23 18:45 UTC, yurishkuro approved these changes

2020-11-23 19:12 UTC, cijothomas approved these changes

2020-11-23 19:37 UTC, Oberon00 commented
I think we use all-lowercase in all other enums in semantic conventions. So I'd rather keep it as-is or use all-lowercase.

2020-11-24 09:30 UTC, jmacd approved these changes

2020-11-24 11:35 UTC, Oberon00 requested changes
I think this PR needs a better motivation. It is a breaking change after all. Also, it seems that the Zipkin change to `error` needs polishing.

2020-11-24 11:37 UTC, Oberon00 commented on specification/trace/sdk_exporters/zipkin.md
> +|Code | `otel.status_code` | Name of the code, either `Ok` or `Error`. MUST NOT be set if the code is `Unset`. |
How valuable is sending this? We can use it to distinguish OK and UNSET, but ERROR is already marked with the `error` attribute.

2020-11-24 17:47 UTC, CodeBlanch commented
For motivation, check out https://github.com/open-telemetry/opentelemetry-dotnet/pull/1579. There are 2 screenshots on there that show what Zipkin & Jaeger do with the error flag. Basically, the UI highlights the spans as errors when the flag is present. There's also some stuff that shows on the search results, but I don't have a screenshot handy for that.

2020-11-24 17:52 UTC, Oberon00 commented
Sorry, my complaint was worded ambiguous: I *am* in favor of adding `error` when the status equals ERROR.

I meant a motivation to change the casing.

2020-11-24 17:54 UTC, CodeBlanch commented on specification/trace/sdk_exporters/zipkin.md
> +When Span `Status` is set to `Error` an `error` tag SHOULD be added with the
Thanks @adriancole! Updated.

2020-11-24 18:14 UTC, CodeBlanch commented
> I think we use all-lowercase in all other enums in semantic conventions. So I'd rather keep it as-is or use all-lowercase.

I put them back to uppercase.

2020-11-24 18:34 UTC, CodeBlanch commented on specification/trace/sdk_exporters/zipkin.md
> +|Code | `otel.status_code` | Name of the code, either `Ok` or `Error`. MUST NOT be set if the code is `Unset`. |
Good question. Definitely redundant to have `otel.status_code=ERROR` with the `error` flag also present on either Jaeger or Zipkin. But having `otel.status_code` does keep things consistent and allows for easier translation to/from OTLP? Might also be better to leave with both in there for now so this is an additive change and not a breaking one?

2020-11-24 18:45 UTC, Oberon00 approved these changes
Thank you!

2020-11-25 01:48 UTC, anuraaga approved these changes
One small clarification comment but generally looks good

2020-11-25 01:48 UTC, anuraaga commented on specification/trace/sdk_exporters/zipkin.md
> +empty string value (eg. `{"error":""}`). The added `error` tag MAY override any
I'm a bit confused on the "override previous value" - does it mean that if the user set an error tag themselves, this may unset it if `Status` is `UNSET`? Or if a user sets `error=cats`, we override to `error=`? Just want to have an idea (maybe we can add some clarification)

2020-11-25 02:58 UTC, adriancole commented
In general I'd advise looking at this as it has a lot of information about nuance of where and from who data is collected https://github.com/openzipkin/brave/blob/master/brave/src/main/java/brave/handler/MutableSpan.java#L37-L87

2020-11-25 04:07 UTC, CodeBlanch commented on specification/trace/sdk_exporters/zipkin.md
> +empty string value (eg. `{"error":""}`). The added `error` tag MAY override any
I was trying to say that exporters can simply add the `error` tag on the end of the tag list which will effectively override anything already there (with the same `error` key). My motivation for that was 1) I didn't want to leave it undefined and 2) checking for an existing tag is particularly expensive (`O(n)`) in the .NET implementation so I was hoping to avoid needing to do that. Open to suggestions for change or improvement.

2020-12-02 18:26 UTC, tigrannajaryan commented on specification/trace/sdk_exporters/zipkin.md
> +empty string value (eg. `{"error":""}`). The added `error` tag MAY override any
Why are we setting an `error` tag with empty string value and additionally add `otel.status_description` instead of just setting the `error` tag with a string value equal to Status message?

Doesn't Status message fit nicely in the `error` tag?

2020-12-02 18:39 UTC, CodeBlanch commented on specification/trace/sdk_exporters/zipkin.md
> +empty string value (eg. `{"error":""}`). The added `error` tag MAY override any
@tigrannajaryan The only issue with that is `error` tag must ONLY be sent if there was an actual error. So what we would need to do is set `error` instead of `otel.status_description` when `otel.status_code=ERROR` otherwise send `otel.status_description` (if it has a value for `OK` or `UNSET` cases). I don't have strong feelings either way. I will say that as-is is easier to implement (always sending `otel.status_description` when it has a value and then adding the `error` tag (empty) for `otel.status_code=ERROR`) and it's non-breaking.

2020-12-02 19:18 UTC, tigrannajaryan commented on specification/trace/sdk_exporters/zipkin.md
> +empty string value (eg. `{"error":""}`). The added `error` tag MAY override any
I believe Status.message is not supposed to be set for OK or UNSET cases. We should explicitly call it out in the spec. This means `error` tag will only be set equal to Spatus.message when Status.status==ERROR and for all other statuses there is no error message to record.

2020-12-03 21:00 UTC, CodeBlanch commented on specification/trace/sdk_exporters/zipkin.md
> +empty string value (eg. `{"error":""}`). The added `error` tag MAY override any
@tigrannajaryan I added some text on `Status` to clarify `Description` should only be used with `Error` and then updated Zipkin & Jaeger based on that.

2020-12-03 23:50 UTC, adriancole commented on specification/trace/sdk_exporters/zipkin.md
> -Boolean values must use lower case strings `"true"` and `"false"`, except an
this special case is still true. For example, you have an opentracing bridge which has in the past littered folks stuff with "error"->"false" data. can you please verify that false should never be sent as a value of "error" regardless of if being mapped from the grpc status or not?

2020-12-04 00:23 UTC, CodeBlanch commented on specification/trace/sdk_exporters/zipkin.md
> -Boolean values must use lower case strings `"true"` and `"false"`, except an
OK I added it back with different words as part of the Status section.

2020-12-07 14:32 UTC, tigrannajaryan approved these changes
Please add this change to the changelog.

2020-12-07 18:05 UTC, CodeBlanch commented
@tigrannajaryan CHANGELOG updated.

2020-12-08 18:00 UTC, tigrannajaryan commented
Let's keep this open until tomorrow since there were substantial changes. If there are no further comments we can merge tomorrow.

2020-12-08 18:39 UTC, yurishkuro approved these changes

2020-12-08 18:39 UTC, yurishkuro commented on specification/trace/api.md
> +  appropriate for the language. `Description` MUST be IGNORED for `StatusCode`
> either as individual parameters or as an immutable object encapsulating them, whichever is most appropriate for the language.

This sounds like a general guideline that would apply to _any_ API function, we don't need to be cluttering individual function descriptions with it.

2020-12-08 18:39 UTC, yurishkuro commented on specification/trace/sdk_exporters/jaeger.md
> +`BOOL` value (`vBool`) set to `true`. The added `error` tag MAY override any
```suggestion
Boolean value of `true`. The added `error` tag MAY override any
```

The references to `BOOL` and `vBool` are out of place, they are not standard terms, and even in the Jaeger schema they are format-specific.

2020-12-09 06:36 UTC, CodeBlanch commented on specification/trace/sdk_exporters/jaeger.md
> +`BOOL` value (`vBool`) set to `true`. The added `error` tag MAY override any
Good point.

2020-12-09 06:39 UTC, CodeBlanch commented on specification/trace/api.md
> +  appropriate for the language. `Description` MUST be IGNORED for `StatusCode`
That was there before my addition you want me to update here?

2020-12-09 06:43 UTC, yurishkuro commented on specification/trace/api.md
> +  appropriate for the language. `Description` MUST be IGNORED for `StatusCode`
could be done in another PR

2020-12-09 06:45 UTC, yurishkuro commented on specification/trace/sdk_exporters/jaeger.md
> +When Span `Status` is set to `ERROR` an `error` tag SHOULD be added with the
What's the reasoning for using SHOULD instead of MUST here?

2020-12-09 07:15 UTC, CodeBlanch commented on specification/trace/sdk_exporters/jaeger.md
> +When Span `Status` is set to `ERROR` an `error` tag SHOULD be added with the
My thinking was it works fine without it, you just lose the coloring/icon, so it shouldn't be an absolute type of thing?

2020-12-09 18:37 UTC, yurishkuro commented on specification/trace/sdk_exporters/jaeger.md
> +When Span `Status` is set to `ERROR` an `error` tag SHOULD be added with the
I think it should be a MUST, because `error` tag is a very strong signal (coloring is just the UI aspect), and it does not make sense to lose that signal in the conversion when OTEL user explicitly bothered to record the error status.

2020-12-10 19:25 UTC, CodeBlanch commented on specification/trace/sdk_exporters/jaeger.md
> +When Span `Status` is set to `ERROR` an `error` tag SHOULD be added with the
Updated

2020-12-10 21:12 UTC, yurishkuro approved these changes

2020-12-10 21:14 UTC, merged

2020-12-15 01:54 UTC, ChrisJBurns commented on specification/trace/sdk_exporters/zipkin.md
> +empty string value (eg. `{"error":""}`). The added `error` tag MAY override any
Just verifying that the `otel-java` code follows the specification and I've given the above a read and _may_ have noticed a slight difference between the `jaeger` and `zipkin` exporter specs regarding the error `Status`.

In the `jaeger` specification it says
> `otel.status_description` : Description of the Status if it has a value otherwise not set.

So this means that for `jaeger` it sets the `otel.status_description` if the status description is set - it does not mandate that it is ONLY set if there is an error. Additionally, if the status is an error, it shall add an `error` tag. 

However for `zipkin` it says the following:
> `error` : Description of the Status. MUST be set if the code is ERROR, use an empty string if Description has no value. MUST NOT be set for OK and UNSET codes.

This describes that the `otel.status_description` tag isn't set anymore, an the `error` tag is the only thing that is set providing that there is an ERROR code and not OK or UNSET.

Is there a reason why for `jaeger` we provide the `otel.status_code`, `otel.status_description` AND the `error` tag but for `zipkin` we only provide `otel.status_code` and the `error` tag.

2020-12-15 02:19 UTC, CodeBlanch commented on specification/trace/sdk_exporters/zipkin.md
> +empty string value (eg. `{"error":""}`). The added `error` tag MAY override any
@ChrisJBurns Slight differences in the implementations, basically. Zipkin `error` is a string where you can put the description. Jaeger `error` is a bool (true/false) so it has `otel.status_description` for the description. The Zipkin text is a bit more specific because if you send something like `error=OK` or `error=false` to Zipkin, it's still going to treat that span as failed.