Allow cloud.* ad faas.* resource attributes to be set on span
open-telemetry/opentelemetry-specification pull request #1265
Opened 2020-11-30 15:49 UTC by mateuszrzeszutek

Fixes #1261

## Changes

Add a note to `faas` and `cloud` resource attributes that allows them to be used as span attributes in serverless functions.

2020-11-30 16:54 UTC, Oberon00 approved these changes
Nit: Use "Note:" only for explanations, not for specifying/allowing additional things.

2020-11-30 16:54 UTC, Oberon00 commented on specification/resource/semantic_conventions/cloud.md
> +Note: When used in serverless function, all `cloud` resource attributes MAY also be used as span attributes.
```suggestion
When used in serverless function, some or all `cloud` resource attributes MAY also be used as span attributes.
```

2020-11-30 16:54 UTC, Oberon00 commented on specification/resource/semantic_conventions/faas.md
> +Note: All `faas` resource attributes MAY also be used as span attributes.
```suggestion
Some or all `faas` resource attributes MAY also be used as span attributes.
```

2020-12-07 16:28 UTC, mateuszrzeszutek commented
@open-telemetry/technical-committee @open-telemetry/specs-approvers Please take a look at this PR when you get a minute.

2020-12-08 13:14 UTC, anuraaga approved these changes
We might consider a general statement at the resource level that any attribute that cannot be determined at startup time can be added as span attributes.

Even better might be wording that it's ok for a resource to be mutable or dynamic. I think we assume it's constant, but I think it limits some use cases for attributes (docker cgroup CPU limit?).

But this still seems like a fine step to me.

2020-12-09 22:32 UTC, carlosalberto approved these changes

2020-12-09 22:33 UTC, carlosalberto commented
Overall good, but I'd like to get more eyes before we merge as I feel this change could be needed in other components too (I will add it to the agenda of the next SIG meeting, in case we haven't resolved this issue/PR by then).

2020-12-18 10:55 UTC, Oberon00 requested changes
Blocking merge for now, I think it would be best to discuss the feasibility of #1298 first.

2020-12-26 03:37 UTC, closed without merging