Define the fallback case for service.name
open-telemetry/opentelemetry-specification pull request #1269
Opened 2020-12-01 05:44 UTC by carlosalberto

Fixes #1241, #1237 

This is a very minimalistic clarification based on what currently many SIGs do (providing a fallback based on the running service), finally defaulting to the `unknown_service` literal.

2020-12-01 06:16 UTC, yurishkuro approved these changes

2020-12-01 08:46 UTC, arminru commented on specification/resource/semantic_conventions/README.md
> +If this fallback fails, the name MUST default to `unknown_service`.
The part between those two semconv markers is generated, you'll have to add to the note in `semantic_conventions/resource/service.yaml` and then run the generator as described in `semantic_conventions/README.md`. The build is failing since the current markdown and the one that would be generated from the YAML don't match.

2020-12-01 08:46 UTC, arminru commented on specification/resource/semantic_conventions/README.md
> +If this fallback fails, the name MUST default to `unknown_service`.
Should we use a name that makes it more obvious this was not set by user code or an instrumentation but by the OpenTelemetry SDK itself?

2020-12-01 08:46 UTC, arminru commented on specification/resource/semantic_conventions/README.md
> +Although this is a required attribute, if the value could not be specified SDKs
```suggestion
Although this is a required attribute, if the value was not specified, SDKs
```

2020-12-01 08:46 UTC, arminru commented on specification/resource/semantic_conventions/README.md
> +MUST fallback to a language-specific name based on the running service.
Can we provide some guidance on how this could or should be done?

2020-12-01 13:09 UTC, Oberon00 reviewed
In my opinion, this is the wrong place to specify this. I mean, it's fine to additionally specify it here, but we need a list of required resources in the SDK specification. Maybe https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/resource/sdk.md, although in principle it applies to tracing, metrics and probably logging SDK.
I think we should not assume that SDK implementers will read all resource semantic conventions.

2020-12-01 16:56 UTC, carlosalberto commented on specification/resource/semantic_conventions/README.md
> +If this fallback fails, the name MUST default to `unknown_service`.
Open to suggestions :)

2020-12-01 16:58 UTC, carlosalberto commented
> I think we should not assume that SDK implementers will read all resource semantic conventions.

Fair point. I think this documentation *needs* to be here, but we also need to mention this in the main `sdk.md` document, with a link to the specific case of `service.name`, as this is a rather important item.

2020-12-01 17:01 UTC, Oberon00 commented
We probably also want that for the telemetry.sdk resources BTW.

2020-12-02 06:09 UTC, carlosalberto commented on specification/resource/semantic_conventions/README.md
> +MUST fallback to a language-specific name based on the running service.
This is actually language specific - but I added a mention of typically used components, such as process name, language or platform where the service is running.

2020-12-02 09:29 UTC, Oberon00 commented on specification/resource/sdk.md
> +See [Resource standard attributes]((semantic_conventions/README.md)).
```suggestion
See [Resource standard attributes](semantic_conventions/README.md).
```

2020-12-02 09:29 UTC, Oberon00 commented on specification/resource/sdk.md
> +See [Resource standard attributes]((semantic_conventions/README.md)).
But there is no such "Resource standard attributes" section in there. I don't think we can require all the Required attributes in that markdown file, since there are many (linked) there.

2020-12-02 22:49 UTC, carlosalberto commented on specification/resource/sdk.md
> +See [Resource standard attributes]((semantic_conventions/README.md)).
Sure, that's why I used "certain" (agree that not all Required attributes should have fallback values).

2020-12-02 23:21 UTC, jmacd commented on specification/resource/semantic_conventions/README.md
> +If this fallback fails, the name MUST default to `unknown_service`.
How about`$(telemetry.sdk.name)_service` or `openetemetry_service`?

2020-12-02 23:27 UTC, jmacd commented on specification/resource/semantic_conventions/README.md
> +If this fallback fails, the name MUST default to `unknown_service`.
After reading the other comments, I think that it would be best if we didn't offer a vague recommendation and then a fallback. A simpler rule will be: when the user does not set a required attribute, a determined value will be used (e.g., the two suggestions above). There are probably other semantic conventions for the attributes that might be used to infer "language-specific name based on the running service (typically inferred from process name, language, plaform, etc)."

Maybe just remove the "language-specific name" part and jump to a MUST and one of the suggestions above?

2020-12-03 17:03 UTC, andrewhsu commented
@open-telemetry/specs-approvers should this really be `P1` since the linked issues #1241, #1237 are also `P1`?

2020-12-03 17:08 UTC, jmacd commented
Based on this comment, https://github.com/open-telemetry/opentelemetry-specification/issues/1241#issuecomment-735972286, I'm inclined to promote my own suggestion above:

https://github.com/open-telemetry/opentelemetry-specification/pull/1269#discussion_r534552116

Explicitly, it means that we can remove some of the words in this PR and simply specify one of the two options in my comment.

2020-12-03 17:13 UTC, austinlparker commented
Just as a note, I think whatever the decision is here needs to be something that is obvious to an operator/consumer of the telemetry and something that is non-suitable for actual usage (such as a 'smart' derived name based on command line or whatnot). Ultimately the name of a service is a logical decision made by humans who are interpreting data, but if we're too clever about it, some users may defer to the cleverness which is good up until the moment it isn't. An obvious default that isn't suitable for long-term usage satisfies both of these conditions.

2020-12-03 17:27 UTC, jmacd commented
The semantic conventions in https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/resource/semantic_conventions/process.md already contain the command name, and the telemetry SDK details are built in (https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/resource/semantic_conventions/README.md), so based on @austinlparker's comment I think when `service.name` is not set exporters MUST use `opentelemetry_service` as a fallback.

2020-12-03 23:31 UTC, carlosalberto commented
After a few iterations myself, I think we either go with:

1) Something **standard** based on the semantic conventions (as @jmacd proposed), such as `process.executable.name` or `process.command` - with a fallback to `opentelemetry_service` or `unknown_service`, **OR**
2) Fallback directly to `opentelemetry_service` or `unknown_service`.

Opinions? cc @yurishkuro @Oberon00

2020-12-03 23:47 UTC, yurishkuro commented
I prefer "unknown" to be in the name. I don't have a strong opinion on auto-resolvers, but I share Austin's concern with them not doing the right thing and being worse than the default.

2020-12-04 16:41 UTC, jmacd commented
I support "unknown"

2020-12-05 01:52 UTC, carlosalberto commented
Ping @Oberon00 (as I'm also slightly inclined to use `unknown_service` without the fallback, for the operators interaction that Austin mentioned).

2020-12-05 09:03 UTC, Oberon00 commented
"unknown" is fine. Or "unknown:EXE-NAME".

2020-12-07 10:54 UTC, arminru commented on specification/resource/sdk.md
> +See [Resource standard attributes]((semantic_conventions/README.md)).
I would list the attributes required to be set by the SDK (currently only `service.name` and `telemetry.sdk.*`, right?) explicitly in `sdk.md`. This way, SDK authors/maintainers only have to refer to the SDK spec and everything that's relevant for the SDK is versioned therein rather than having to check the semantic convention docs separately for changes.

2020-12-07 11:53 UTC, Oberon00 commented on specification/resource/sdk.md
> +See [Resource standard attributes]((semantic_conventions/README.md)).
In any case, if you say "certain" you must specify what these "certain" are. Right now, I would not know.

2020-12-07 23:29 UTC, carlosalberto commented on specification/resource/sdk.md
> +See [Resource standard attributes]((semantic_conventions/README.md)).
Sounds fair, will add a note.

2020-12-08 17:36 UTC, austinlparker commented
+1 for 'unknown_service'

2020-12-09 04:54 UTC, carlosalberto commented
Updated with:

1) `unknown_service:{process.executable.name}`, e.g. `unknown_service:bash`
2) `unknown_service` if `process.executable.name` is not available.

Let me know whether this looks acceptable, and whether this fallback case is sane ;)

2020-12-10 16:58 UTC, jmacd approved these changes

2020-12-10 23:06 UTC, carlosalberto commented
Ping @Oberon00 @austinlparker

2020-12-11 01:09 UTC, austinlparker commented
lgtm

2020-12-11 01:09 UTC, austinlparker approved these changes

2020-12-11 08:16 UTC, Oberon00 requested changes

2020-12-11 08:16 UTC, Oberon00 commented on specification/resource/semantic_conventions/README.md
> +The SDK MUST set a default value for the following attributes if they were not specified:
```suggestion
The SDK MUST set a default value for the following attributes if they were not specified, even if the resource would otherwise not be present at all:
```

2020-12-11 16:46 UTC, carlosalberto commented on specification/resource/semantic_conventions/README.md
>  | `service.instance.id` | string | The string ID of the service instance. [3] | `627cc493-f310-47de-96bd-71410b7dec09` | Yes |
I'd suggest going ahead with this PR (as it has been standing for long time now) and follow up with #1034 right after (Priority 2) so we can either set it as well or remote it altogether.

2020-12-11 17:17 UTC, Oberon00 commented on specification/resource/semantic_conventions/README.md
>  | `service.instance.id` | string | The string ID of the service instance. [3] | `627cc493-f310-47de-96bd-71410b7dec09` | Yes |
If we do that, we need to raise #1034 to P1 required-for-ga. If you think this is OK, I'm fine with merging as the PR is now. Note that doing it the other way round (resolving  #1034 first) would not result in the spec temporarily being in a contradictory state though.

2020-12-11 17:17 UTC, Oberon00 commented on specification/resource/semantic_conventions/README.md
>  | `service.instance.id` | string | The string ID of the service instance. [3] | `627cc493-f310-47de-96bd-71410b7dec09` | Yes |
FYI @anuraaga

2020-12-11 17:19 UTC, Oberon00 commented on specification/resource/semantic_conventions/README.md
>  | `service.instance.id` | string | The string ID of the service instance. [3] | `627cc493-f310-47de-96bd-71410b7dec09` | Yes |
A "quickfix" would be to make the instance-ID non-required.

2020-12-11 18:07 UTC, jmacd commented on specification/resource/semantic_conventions/README.md
>  | `service.instance.id` | string | The string ID of the service instance. [3] | `627cc493-f310-47de-96bd-71410b7dec09` | Yes |
I am in favor of marking the instance-ID as non-required to let us merge this PR. Thanks for pointing out the inconsistency in #1034.

2020-12-12 01:08 UTC, carlosalberto commented on specification/resource/semantic_conventions/README.md
>  | `service.instance.id` | string | The string ID of the service instance. [3] | `627cc493-f310-47de-96bd-71410b7dec09` | Yes |
+1 for making instance-ID non-required (after all, there's the related issue). Will update, thanks!

2020-12-12 01:15 UTC, carlosalberto commented
> I think there is awareness now for the problem with #1034, so not blocking this PR (trusting you to sort this out properly)

Thanks! Have made `service.instance.id` non-required, so this can be properly addressed in #1034

2020-12-14 15:59 UTC, merged