vendors: add details about vendors offering instrumented services
open-telemetry/opentelemetry-specification pull request #1277
Opened 2020-12-05 17:05 UTC by tsloughter

## Changes

This patch expands the spec related to vendors to include vendors providing non-observability services, but instead provde services or applications that are instrumented, like a proxy or a database.

This change was motivated by the AWS announcments and distros which seem to still require their custom trace propagators: https://aws.amazon.com/blogs/opensource/distributed-tracing-with-opentelemetry/

2020-12-05 17:24 UTC, yurishkuro requested changes
GC had a discussion this week on this topic. There are many nuances that need to be worked out into a coherent policy. Until then I don't this we should be making rush changes. And I think the compliance requirements must be clearly rationalized.

2020-12-05 19:55 UTC, tsloughter commented
Ok. Good to know it is already being discussed and will be addressed. I'd argue it'd be good to get a clarification like this one in now, before working out all the nuances and a policy that covers all cases. The spec already defines the need to support the default SDK to claim to "support OpenTelemetry", but it only made explicit reference to exporting while forgetting propagation.

Let me know if I can help with developing the full policy and whether, assuming the decision is to stick to waiting until that fully policy is complete to change anything, if I should close this PR.

2020-12-05 20:08 UTC, yurishkuro commented
@tedsuo can provide more details

2020-12-05 20:10 UTC, yurishkuro commented
> The spec already defines the need to support the default SDK to claim to "support OpenTelemetry"

I think that is the challenge, "support OpenTelemetry" is very vague and likely has many different levels.

2020-12-06 05:42 UTC, anuraaga commented
While I suspect this may have been discussed at the GC, can't find notes. Let me add some insight here in case it helps the discussion.

First, want to confirm @tsloughter, have you seen any messaging that seems to indicate that AWS managed services, for example ELB, "support OpenTelemetry"? I don't think I've seen any, I agree that this would be misleading if it's mentioned anywhere - even before the consideration of w3c propagation, none of them can export in OTLP format anyways. In my blog post, I say the opposite, that "OpenTelemetry fully supports the AWS Tracing Header", which seems correct given we have artifacts supporting propagation using it, as well as many other formats.

But a broader statement of "AWS supports OpenTelemetry" seems fair - AWS is dedicated to providing support for our users in their journey through OpenTelemetry, no need to use x-ray even. So I suspect that the current document is already reasonable - perhaps it could be renamed to `tracing-vendors.md` to make clear it applies to tracing vendors. A different doc is probably needed for `cloud-vendors.md` and I suspect it'll have vastly different content, including distinction of overall support vs support by specific managed services.

2020-12-06 15:50 UTC, tsloughter commented
@anuraaga "OpenTelemetry fully supports the AWS Tracing Header" is what stuck out to me. I don't think this PR applies to the AWS posts, but it was that wording that got me thinking about the potential issue and lack of propagation being covered in this spec.

My hope would be that vendors will want to say they "support OpenTelemetry" so will work on using the W3C Trace Context if it is a requirement in this spec.

The "fully supports the AWS Tracing Header" is really more of a separate concern which is whether a pluggable piece of OpenTelemetry can be said to "support" something simply because it can be made to do "anything".

I would argue it can't be said otel "supports" any individual tracing header aside from W3C and B3 because those are the only ones required in the API. What it does support is implementing and plugging in alternative third party propagation headers.

2020-12-06 16:12 UTC, tsloughter commented
I also now notice the X-Ray TraceId has a specific format itself, requiring a custom generator. I don't know if that is required to send traces to X-Ray or just means better support/sorting if they are done using the custom generator?

I think a "distribution" spec is needed, in addition to this doc on what vendor support/implementation means -- possibly being split into separate "tracing-vendor" and "cloud-vendor"  docs ("cloud-vendor" doesn't really cover it since this should apply to projects like the many proxies and service meshes as well).

2020-12-07 03:06 UTC, anuraaga commented
> I would argue it can't be said otel "supports" any individual tracing header aside from W3C and B3 because those are the only ones required in the API. What it does support is implementing and plugging in alternative third party propagation headers.

I see - yeah admittedly I had Java strongly in my mind when writing that blog post but it's not really an OpenTelemetry concern. Perhaps the better wording would have been OpenTelemetry supports propagating context to managed AWS services without mentioning any header format. Since this doc is about "X supports OpenTelemetry", if adding guidelines for "OpenTelemetry supports X", perhaps that is yet another doc :)

> I also now notice the X-Ray TraceId has a specific format itself, requiring a custom generator. I don't know if that is required to send traces to X-Ray or just means better support/sorting if they are done using the custom generator?

It's required - X-Ray very much does not support / implement OpenTelemetry as per this spec, and if we ever stated that in any material, that would be an error for sure. In general, we'd consider it "possible for a user to use OpenTelemetry with X-Ray" and where we can, we may provide a distro or wrapper library to "provide an out-of-the-box experience with OpenTelemetry and X-Ray" as well as other tracing providers. I'm providing these quotes just as examples that might drive the spec discussions.

Agree in general though that an instrumentation or distro specific doc can be useful. For example, the Java distro enables tracecontext, aws, and b3 propagators by [default](https://github.com/aws-observability/aws-otel-java-instrumentation/blob/main/awsagentprovider/src/main/java/software/amazon/opentelemetry/javaagent/providers/AwsAgentProperties.java#L25). So it confirms to the spirit of what you propose here, but that was only because I thought it's natural to support tracecontext, but it may be worth making that extra clear in the spec.

2020-12-07 21:54 UTC, tsloughter commented
> it's not really an OpenTelemetry concern

It is. I think the propagation and export format being defined is one of the most important parts of OpenTelemetry and how it differs from OpenTracing.

Working in Erlang has meant no vendors provide libraries, everything has to be implemented and maintained by the community, then discovered and configured by our users, so we are extra sensitive to these concerns :)

2020-12-11 18:31 UTC, jmacd commented on specification/vendors.md
> +### Observability Services and Applications
Not a problem per se, but all the examples and requirements here relate to tracing.

We've recently identified that in Metrics and the current OTLP, there are "Supports OpenTelemetry" statements that we should consider perfectly valid but may be additionally described by the subset of aggregation temporalities they accept. A system can be said to support OpenTelemetry without supporting DELTA points, for example, but that's why we've specified built-in DELTA-to-CUMULATIVE conversion by default.

2020-12-26 03:37 UTC, closed without merging