Give guideline of not using unit names in attributes (#1053)
open-telemetry/opentelemetry-specification pull request #1307
Opened 2020-12-28 18:40 UTC by alexvanboxel

Add a paragraph in the attribute name guidelines that discourage the use
of unit names and prefixes.

Add note about historical naming violation in messaging.md, the attribute names
message_payload_size_bytes and message_payload_compressed_size_bytes about the
incorrect use of bytes in the name.

Fixes #1053

## Changes

Please provide a brief description of the changes here. Update the
`CHANGELOG.md` for non-trivial changes. If `CHANGELOG.md` is updated,
also be sure to update `spec-compliance-matrix.md` if necessary.

Related issues #

Related [oteps](https://github.com/open-telemetry/oteps) #

2020-12-29 10:43 UTC, Oberon00 commented on specification/common/attribute-and-label-naming.md
> +  smallest practical unit size. For example, `http.request_content_length` does not
I would agree but it seems that sometimes other units are more natural, e.g. see https://github.com/open-telemetry/opentelemetry-specification/pull/1296#discussion_r545178077, where faas.max_memory is introduced which will use MiB instead of B (but does not use a unit suffix).

2020-12-29 10:43 UTC, Oberon00 commented on specification/common/attribute-and-label-naming.md
> +  unit is a fraction, the prefix is not part of the name.
I think you need an example here. Would this mean that we use `execution_time` instead of `execution_time_nanos`?.

2020-12-29 10:43 UTC, Oberon00 commented on specification/common/attribute-and-label-naming.md
> +- Names should not contain unit names, and their values should be measured in the
What is the justification for that vs they should always contain unit names?

2020-12-29 16:39 UTC, yurishkuro commented on specification/common/attribute-and-label-naming.md
> +  smallest practical unit size. For example, `http.request_content_length` does not
There may be many situations where "smallest practical unit" is not well defined, easiest example - durations. A guideline for not including units in the name needs to be accompanied by an alternative way of capturing units as metric metadata.

2020-12-29 17:59 UTC, alexvanboxel commented on specification/common/attribute-and-label-naming.md
> +  smallest practical unit size. For example, `http.request_content_length` does not
I will remove the sentence that talks about the smallest practical unit.

2020-12-29 18:03 UTC, alexvanboxel commented on specification/common/attribute-and-label-naming.md
> +  unit is a fraction, the prefix is not part of the name.
I've been going over all the attributes defined in the spec and none mention the **unit fraction**. The only attribute that uses the **unit name** is `message_payload_size_bytes`.  So yes, I think having `execution_time` would be more consistent with the rest of the attributes.

2020-12-29 18:14 UTC, alexvanboxel commented on specification/common/attribute-and-label-naming.md
> +- Names should not contain unit names, and their values should be measured in the
Having the **unit names** in the attribute names would in most cases redundant. Example `execution_time` would be silly to have `seconds` in the name.  The same for `message_payload_size_bytes`, the fact that it's `bytes` is redundant information.

We could _discuss_ the fraction names (nanos, MiB, ...) separately: here it's about the fact that it's not used in any of the attributes yet.

2021-01-07 18:23 UTC, tigrannajaryan commented on specification/common/attribute-and-label-naming.md
> +- Names should not contain unit names, and their values should be measured in the
This change is reasonable for metric names which support units natively. Span or log attributes have no such support. I don't think this is a good blanket recommendation for all cases. There may be cases when units are ambiguous. In the example given `execution_time` it is not obvious to me that the execution time should be in seconds. Why would I assume that? Why not milliseconds?

2021-01-08 09:27 UTC, Oberon00 commented on specification/common/attribute-and-label-naming.md
> +- Names should not contain unit names, and their values should be measured in the
I think it would make sense to require all spec semantic conventions to always use nanoseconds for any timespans. That way it would be unambiguous.

2021-01-12 20:13 UTC, alexvanboxel commented on specification/common/attribute-and-label-naming.md
> +  smallest practical unit size. For example, `http.request_content_length` does not
I've changed to wording that it shouldn't rely on the `smallest practical` unit. I'll flag this conversation as resolved.

2021-01-12 20:18 UTC, alexvanboxel commented on specification/common/attribute-and-label-naming.md
> +- Names should not contain unit names, and their values should be measured in the
I reworded the wording not to talk about the smallest practical unit, just to focus on the naming. Talking about this could be interesting, but I propose that someone takes this out of the scope of this PR.

2021-01-13 15:50 UTC, tigrannajaryan requested changes
@alexvanboxel sorry, I am not convinced that this change is an improvement for Spans. For metrics, sure, I completely agree, it is wrong to have units in the names. For span attributes, I disagree.
I would be fine to merge a change like this if it applied only to metric names. As-is it applies to spans too so I am blocking it until we figure this out (I am willing to be convinced).

2021-01-13 15:58 UTC, alexvanboxel commented
> @alexvanboxel sorry, I am not convinced that this change is an improvement for Spans. For metrics, sure, I completely agree, it is wrong to have units in the names. For span attributes, I disagree.
> I would be fine to merge a change like this if it applied only to metric names. As-is it applies to spans too so I am blocking it until we figure this out (I am willing to be convinced).

are you opposed to units (ex. bytes) or fractions (ex. nano, milli, ...) or both?

2021-01-13 16:29 UTC, tigrannajaryan commented
> are you opposed to units (ex. bytes) or fractions (ex. nano, milli, ...) or both?

I am opposed to the blanket requirement which says we cannot have units in attribute names. I think there are valid cases when it is useful to have units in span attribute names, because not having the unit in the name makes the value ambiguous. For example `execution_time` attribute does not convey in any way whether the attribute value is in seconds or maybe milliseconds? How would the recipient of such attribute know?

2021-01-13 17:46 UTC, jmacd commented on specification/trace/semantic_conventions/messaging.md
> +**Note:** The payload size names (`message_payload_compressed_size_bytes` and `message_payload_size_bytes`) don't comply with the [Attribute and Label Naming](../../common/attribute-and-label-naming.
Should we change this spec?

2021-01-21 07:01 UTC, alexvanboxel commented
> > are you opposed to units (ex. bytes) or fractions (ex. nano, milli, ...) or both?
> 
> I am opposed to the blanket requirement which says we cannot have units in attribute names. I think there are valid cases when it is useful to have units in span attribute names, because not having the unit in the name makes the value ambiguous. For example `execution_time` attribute does not convey in any way whether the attribute value is in seconds or maybe milliseconds? How would the recipient of such attribute know?

I'm fine with dropping this PR if no consensus can be reached. I like to have consistency, and this PR only resulted from the issue I created. Do we drop this PR?

2021-01-22 15:00 UTC, carlosalberto commented
@alexvanboxel For metrics it looks right IMHO, so worth considering going metrics-only from here.

2021-02-11 03:27 UTC, closed without merging