Remove MILLIS from BatchSpanProcessor variables and allow support for…
open-telemetry/opentelemetry-specification pull request #1325
Opened 2021-01-07 06:23 UTC by anuraaga

… SDKs to parse duration strings.

Fixes #1312

## Changes

Removes MILLIS from BatchSpanProcessor time variables in favor of defining durations to always be interpreted as milliseconds, and allow also supporting formatted strings.

2021-01-07 06:25 UTC, anuraaga commented on specification/sdk-environment-variables.md
> +### Duration
@mwear I'm imaging Endpoint to also be added to this list after #1234 (awesome PR number!)

2021-01-07 06:52 UTC, yurishkuro commented on specification/sdk-environment-variables.md
> +### Duration
I am not sure this is worth it. In Go this can be parsed with stdlib, but that's not always the case in other langs, so it introduces an extra burden on SDK implementations with not a lot of benefits.

2021-01-07 06:54 UTC, anuraaga commented on specification/sdk-environment-variables.md
> +### Duration
@yurishkuro We're discussing on #1312. @jsuereth has started working on adding it to all the languages and not sure how best to proceed with it without a definition of the unit strings. https://github.com/open-telemetry/opentelemetry-java/pull/2439 I'm personally fine with anything that makes the variable names consistent :)

2021-01-07 17:49 UTC, jsuereth requested changes

2021-01-07 17:49 UTC, jsuereth commented on specification/sdk-environment-variables.md
> +Any value that represents a duration, for example a timeout, MUST interpret a purely numeric value as a number of
FYI - I didn't notice you already had this PR.   I described this a bit differently: https://github.com/open-telemetry/opentelemetry-specification/compare/master...jsuereth:wip-duration-defaults?expand=1

I think your specification is a lot smaller, but is missing the bit about `PositiveInteger`, i.e. I think we also need to limit the numeric value so it's reasonable to contribute a parser in all languages.


Suggested change:

```
Any value that represents a duration, for example a timeout, MUST interpret a purely positive integer value as a number of milliseconds. Formatted strings with a positive integer followed immediately by a unit string MAY be interpreted for the following units:
```

2021-01-07 18:17 UTC, carlosalberto commented on specification/sdk-environment-variables.md
> +Any value that represents a duration, for example a timeout, MUST interpret a purely numeric value as a number of
> Formatted strings with a positive integer followed immediately by a unit string MAY be interpreted for the following units:

I'm afraid that languages not supporting this specific sentence will soon be approached by users asking: "Hey, why doesn't this work? In Go it does but it doesn't in X language", converting it the de facto required.

(I know this is a small piece of work - but if we allow this to creep, we then may allow other 20 small additions and drag the release more than it is - and, well, we can *easily* add support for this parsing by the time we do the next release, which should include **stable** metrics :) )

2021-01-07 19:24 UTC, jsuereth commented on specification/sdk-environment-variables.md
> +Any value that represents a duration, for example a timeout, MUST interpret a purely numeric value as a number of
I understand the concern.

1. I'm not sure how else you would phrase this in a way to ALLOW Go's handling of duration and also allow parsing units in the future to become required (post-GA).  If you have a recommendation for how we *allow* this change to occur post-GA, let us know.  Currently, I think having `_MILLIS` in env names actually prevents this format from being a good idea post-GA so at a minimum I'd like to remove that from the ENV variable.
2. I think it's on the maintainers of those langauge maintainers to PUNT the request or ask community for PRs.  i.e. This spec change is intended to NOT force languages to implement parsers, but allow them to come post GA, but will need discipline from maintainers to focus on more important issues.
3. I'm more than happy to contribute parsers for this to languages which need it, feel free to assign it to me.  Anything I can do to help maintainers focus on stable metrics :)

2021-01-13 00:39 UTC, bogdandrutu commented
@jsuereth looks like you requested changes, is there any concrete issue/reason that we need to solve?

2021-01-13 14:36 UTC, jsuereth commented
@bogdandrutu Yeah, here's the quote:

> FYI - I didn't notice you already had this PR. I described this a bit differently: https://github.com/open-telemetry/opentelemetry-specification/compare/master...jsuereth:wip-duration-defaults?expand=1
> 
> I think your specification is a lot smaller, but is missing the bit about `PositiveInteger`, i.e. I think we also need to limit the numeric value so it's reasonable to contribute a parser in all languages.
> 
> Suggested change:
> 
> ```
> Any value that represents a duration, for example a timeout, MUST interpret a purely positive integer value as a number of milliseconds. Formatted strings with a positive integer followed immediately by a unit string MAY be interpreted for the following units:
> ```

2021-01-14 05:57 UTC, anuraaga commented
@jsuereth Sorry for missing the comment about positive numbers! Will address

@carlosalberto So do you want to leave out discussion of duration units in this PR? What happens if different languages end up with different units? Maybe a low enough probability not to matter though.

2021-01-14 17:06 UTC, carlosalberto commented
> So do you want to leave out discussion of duration units in this PR?

Not quite, but have milliseconds being the default. IIRC the parsers @jsuereth mentioned take milliseconds as the default, unless I'm wrong?

2021-01-14 19:11 UTC, jsuereth commented
@carlosalberto The parser I contributed to Java (and plan for other languages) takes milliseconds as the default. 

 I think your plan for "allow-for-GA" with specific changes is exactly in line with what I was hoping to accomplish!

Parsers can be added when it makes sense to do so.

2021-01-15 00:22 UTC, anuraaga commented
@carlosalberto Ah ok - I just added the note about negative numbers not being supported. I think my wording of MUST vs MAY captured the aspect of the default being numeric milis, let me know if this is still missing anything.

2021-01-19 21:55 UTC, carlosalberto commented
Based on the discussion we had today at the Spec call, we decided to go with:

1) Remove `_MILLIS` for all related environment variables and have milliseconds as the actual default unit.
2) Fill a follow-up issue (allowed for GA) to have the duration unit parsing in place. We will merge this as soon as the main SIGs have support in place. See #1351 

@anuraaga Please amend appropriately ;)

2021-01-20 05:03 UTC, anuraaga commented
@carlosalberto Ok updated to only talk about the number.

2021-01-20 14:50 UTC, carlosalberto approved these changes

2021-01-20 14:50 UTC, carlosalberto commented
@anuraaga Thanks for the update!

@open-telemetry/specs-approvers please review/approve ;)

2021-01-20 15:54 UTC, tigrannajaryan approved these changes

2021-01-20 15:54 UTC, tigrannajaryan commented on specification/sdk-environment-variables.md
> +gracefully ignore the setting.
```suggestion
milliseconds. The value is non-negative - if a negative value is provided, the SDK MUST generate a warning,
gracefully ignore the setting and use the default value if it is defined.
```

2021-01-21 17:47 UTC, jmacd approved these changes

2021-01-21 18:51 UTC, tedsuo approved these changes
LGTM. Appreciate the simplification and, dare I say it, standardization.

2021-01-21 22:41 UTC, merged