Document how to generate OTLP gRPC clients
open-telemetry/opentelemetry-specification pull request #1343
Opened 2021-01-15 03:04 UTC by Frapschen

## Changes

Update the `otlp.md` for demonstrating how to create new gRPC clients for the OTLP receiver.

Related issues [#2328](https://github.com/open-telemetry/opentelemetry-collector/issues/2328)

2021-01-15 03:45 UTC, yurishkuro commented on specification/protocol/otlp.md
> +  * [Create New gRPC Client](#create new gRPC client)
```suggestion
  * [Creating New gRPC Client](#creating new gRPC client)
```

2021-01-15 14:54 UTC, tigrannajaryan requested changes

2021-01-15 14:54 UTC, tigrannajaryan commented on specification/protocol/otlp.md
> +Please refer to the [opentelemetry-proto](https://github.com/open-telemetry/opentelemetry-proto)
The link does not describe how to create a new gRPC client. I don't see how this change is helping.

2021-01-18 02:53 UTC, Frapschen commented on specification/protocol/otlp.md
> +Please refer to the [opentelemetry-proto](https://github.com/open-telemetry/opentelemetry-proto)
I follow the #2328 sugest to just add a link,I think the proto file can automatic gen any language gRPC client by goolge proto compiler

2021-01-18 15:37 UTC, tigrannajaryan commented on specification/protocol/otlp.md
> +Please refer to the [opentelemetry-proto](https://github.com/open-telemetry/opentelemetry-proto)
If the proto repository contained any docs that describe how to generate gRPC client perhaps linking to it would be helpful. However, there is no such content in the proto repository. 
There are already several existing links from this document to proto repo already. I do not think creating a new section just to link to the root page of the proto repo one more time is adding any value to this document.

2021-01-19 01:38 UTC, Frapschen commented on specification/protocol/otlp.md
> +Please refer to the [opentelemetry-proto](https://github.com/open-telemetry/opentelemetry-proto)
ok,got it

2021-01-20 09:59 UTC, Frapschen commented
how do I contiune this pr?  just close?

2021-01-21 18:49 UTC, bogdandrutu commented on specification/protocol/otlp.md
> +Please refer to the [opentelemetry-proto](https://github.com/open-telemetry/opentelemetry-proto)
The proto repository has a makefile that allows to generate clients for few languages. We can add rules there to generate for all the languages and maybe just refer to that?

2021-01-21 22:23 UTC, bogdandrutu commented on specification/protocol/otlp.md
> +Please refer to the [opentelemetry-proto](https://github.com/open-telemetry/opentelemetry-proto)
PR to show how to build for few more languages https://github.com/open-telemetry/opentelemetry-proto/pull/248

2021-01-25 17:11 UTC, bogdandrutu commented
@Frapschen I think you need to sign the CLA before anything else :)

2021-02-11 03:27 UTC, closed without merging