Add metric for currently-in-flight HTTP requests
open-telemetry/opentelemetry-specification pull request #1378
Opened 2021-01-26 17:57 UTC by evankanderson

## Changes

I was starting to implement some monitoring using the HTTP semantic conventions, and realized that it was also useful to have a count of the current in-flight HTTP requests (those which had started but not yet completed). This allows monitoring both the concurrency of the server and detecting unfortunate queueing or backlog events before the requests have completed (for example, if the request is blocked indefinitely).

(Will update CHANGELOG.md once I have a PR #)

2021-02-04 03:46 UTC, jkwatson commented on specification/metrics/semantic_conventions/http-metrics.md
> +| `http.server.requests` | ValueObserver | requests     | measures the number of concurrent HTTP requests handled |
To me, this name evokes the total number of requests served, rather than concurrent requests. I recommend having a naming pattern that evokes the concurrent nature of what is being measured.

2021-02-04 07:00 UTC, anuraaga commented on specification/metrics/semantic_conventions/http-metrics.md
> +| `http.server.requests` | ValueObserver | requests     | measures the number of concurrent HTTP requests handled |
Suggestion is active_requests

2021-02-05 00:18 UTC, evankanderson commented on specification/metrics/semantic_conventions/http-metrics.md
> +| `http.server.requests` | ValueObserver | requests     | measures the number of concurrent HTTP requests handled |
`active_requests` would be fine with me, and answers #1370 as well.

2021-02-07 09:45 UTC, evankanderson commented
(Merged CHANGELOG.md -- let me know if I should squash)

2021-02-15 06:53 UTC, evankanderson commented
Is this a reasonable addition? Do I need to bring this up at a contributor meeting?

2021-02-15 06:55 UTC, anuraaga commented on specification/metrics/semantic_conventions/http-metrics.md
> +The following labels SHOULD be included in the `http.server.requests` observation:
```suggestion
The following labels SHOULD be included in the `http.server.active_requests` observation:
```

2021-02-15 06:58 UTC, evankanderson commented on specification/metrics/semantic_conventions/http-metrics.md
> +The following labels SHOULD be included in the `http.server.requests` observation:
Thanks, fixed!

2021-02-15 07:16 UTC, anuraaga approved these changes
Thanks!

2021-02-18 02:58 UTC, reyang commented on specification/metrics/semantic_conventions/http-metrics.md
> +| `http.server.active_requests` | ValueObserver | requests     | measures the number of concurrent HTTP requests handled |
Do we want "Active Requests", or "Requests that we've received" and "Requests that we've finished processing" (so we can calculate the currently-in-flight ones)?

2021-02-18 02:59 UTC, reyang commented on specification/metrics/semantic_conventions/http-metrics.md
> +| `http.server.active_requests` | ValueObserver | requests     | measures the number of concurrent HTTP requests handled |
```suggestion
| `http.server.active_requests` | ValueObserver | requests     | measures the number of concurrent HTTP requests that are currently in-flight |
```

2021-02-18 03:00 UTC, reyang requested changes
Please see my comment [here](https://github.com/open-telemetry/opentelemetry-specification/pull/1378/files#r578093122).

2021-02-24 08:44 UTC, jmacd commented
@reyang In other cases, we've discussed how it may be acceptable to specify semantic conventions without saying how they should be generated. For the case of "in flight HTTP requests" we could either materialize a dedicated metric or we could calculate the number in-flight by subtracting one metric from another. It's clearly much harder to do the second, so most users will prefer the first. But if you have a sophisticated metric system, it's redundant to record an additional metric and you shouldn't have to.

The example we discussed was metrics with `.utilization`, `.usage`, and `.limit` suffixes. With any two of these you can calculate the third, so which should we record? All three are useful to monitor, so it's hard to argue that in some cases you shouldn't just record all three.

2021-02-26 06:02 UTC, evankanderson commented on specification/metrics/semantic_conventions/http-metrics.md
> +| `http.server.active_requests` | ValueObserver | requests     | measures the number of concurrent HTTP requests handled |
I think `http.server.duration` includes "requests we've finished processing".

It would be possible to calculate `http.server.started - count_of_distribution(http.server.duration)` to get the currently in-flight requests, but I think "started requests over all time" is probably the least useful of the three measures (I have no idea what I'd use it for), and you could derive it as `count_of_distribution(http.server.duration) + http.server.active_requests` if necessary.

In my dream world, I could actually have a histogram of "requests in flight by current in-flight time" here, but I don't have enough interest to make people suffer through temporary-histogram-buckets as yet another metric type for this resource.

2021-02-26 06:03 UTC, evankanderson commented
Sorry for the delay, the extra comments caught me in the middle of vacation/school break, and it took some time to dig out.

2021-03-02 04:09 UTC, reyang approved these changes
LGTM.

2021-03-12 16:47 UTC, evankanderson commented
I'm not authorized to merge this PR, but it looks like it does have the requisite reviews. What's the next step?

2021-03-13 00:51 UTC, evankanderson commented
@jmacd -- I think this is ready for merge?

2021-03-15 23:44 UTC, jmacd commented on specification/metrics/semantic_conventions/http-metrics.md
> +| `http.server.active_requests` | ValueObserver | requests     | measures the number of concurrent HTTP requests that are currently in-flight |
I'd like this to be UpDownSumObserver, which is what you'd get from using an UpDownCounter instrument (delta temporality) with cumulative conversion.

2021-03-16 01:36 UTC, evankanderson commented on specification/metrics/semantic_conventions/http-metrics.md
> +| `http.server.active_requests` | ValueObserver | requests     | measures the number of concurrent HTTP requests that are currently in-flight |
Done. Not sure how I'd missed that.

2021-03-16 16:07 UTC, jmacd approved these changes

2021-03-16 16:17 UTC, jmacd commented on specification/metrics/semantic_conventions/http-metrics.md
> +| `http.server.active_requests` | ValueObserver | requests     | measures the number of concurrent HTTP requests handled |
> requests in flight by current in-flight time

This is a GaugeHistogram :grinning: please add feedback on https://github.com/open-telemetry/opentelemetry-proto/issues/274

2021-03-16 16:18 UTC, jmacd commented
@evankanderson sorry for the long delay. Thank you for this contribution!

2021-03-16 16:19 UTC, merged