Add lifecycle statuses to all documents
open-telemetry/opentelemetry-specification pull request #1385
Opened 2021-01-27 21:42 UTC by tedsuo

## Changes

Adds the current lifecycle stage to each document's status. Clarifies that the feature-freeze status is a community process, not a definition of stability or feature-completeness.

Related issues #

* https://github.com/open-telemetry/opentelemetry-specification/pull/1372
* https://github.com/open-telemetry/opentelemetry-specification/issues/1373

2021-01-27 23:05 UTC, bogdandrutu commented
Please rebase and checks will run

2021-01-28 02:57 UTC, tedsuo commented
@bogdandrutu resolved

2021-01-28 07:27 UTC, iNikem approved these changes

2021-01-28 15:15 UTC, carlosalberto approved these changes

2021-01-28 15:44 UTC, cijothomas commented on specification/resource/semantic_conventions/README.md
> +**Status**: [Experimental](../../document-status.md)
https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/resource/semantic_conventions/README.md#semantic-attributes-with-sdk-provided-default-value - This section of the semantic convention is reffered to by the main Resource spec (https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/resource/sdk.md#sdk-provided-resource-attributes). We need to get this portion to the main Resource spec, else it'll be difficult to justify the MUST requirement for "SDK-provided resource attributes", since it refers to an experimental portion.

2021-01-28 18:49 UTC, lzchen commented
I know that environment variables are deemed optional in the [spec matrix](https://github.com/open-telemetry/opentelemetry-specification/blob/main/spec-compliance-matrix.md#environment-variables) but some languages have already implemented some of them. In this case, will the env var names be marked as "stable" [here](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/sdk-environment-variables.md) as well or will there possible breaking changes in the future (such as the recent OTEL_EXPORTERS -> OTEL_METRICS_EXPORTER + OTEL_TRACE_EXPORTER)? We need to know whether or not we can release env var functionality as part of 1.0.0.

2021-01-29 14:41 UTC, jsuereth approved these changes

2021-01-29 14:47 UTC, jsuereth commented
> I know that environment variables are deemed optional in the [spec matrix](https://github.com/open-telemetry/opentelemetry-specification/blob/main/spec-compliance-matrix.md#environment-variables) but some languages have already implemented some of them. In this case, will the env var names be marked as "stable" [here](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/sdk-environment-variables.md) as well or will there possible breaking changes in the future (such as the recent OTEL_EXPORTERS -> OTEL_METRICS_EXPORTER + OTEL_TRACE_EXPORTER)? We need to know whether or not we can release env var functionality as part of 1.0.0.

I'd be nice if we could lock down the semantics folks were already relying on here without having to fully lock down everything about environment variables.  The OTEL_EXPORTERS change was one where we likely WILL be doing deprecation + migration in the future, and we could have done that here for existing SDKs rather than force migrate prior to 1.0.0.

It'd be nice if we agreed to "1.0" environment variables (even if they're optional, we still won't change semantics in breaking ways).  so +1 to answering this question.

2021-01-29 18:15 UTC, bogdandrutu commented on specification/context/api-propagators.md
> +**Status**: [Stable, Feature-Freeze](../document-status.md)
Since you removed `Feature-Freeze` from the status should we remove it from here as well?

2021-01-30 05:13 UTC, tedsuo commented on specification/context/api-propagators.md
> +**Status**: [Stable, Feature-Freeze](../document-status.md)
Feature freeze is still a status, just separate from the lifecycle statuses. If we are once again open to reviewing new (backwards compatible) propagator features, then we can remove it. Otherwise, we can keep it.

2021-01-30 05:54 UTC, tedsuo commented on specification/resource/semantic_conventions/README.md
> +**Status**: [Experimental](../../document-status.md)
That is a good point. But I don't think this link is wrong – we have not agreed to make the conventions stable yet, but we have agreed to use them. So from a spec perspective, the reference from a stable SDK to an experimental section is correct, in that it reflects the current state of affairs that we've agreed to as a group. The MUST in that section of the SDK means that the current set of default resources must be provided, not that the default resources themselves cannot change.

However, I don't really like this state of affairs – it would be better to make the conventions stable. You are correctly pointing out that it is problematic to leave them experimental. There's no way for the SDK to avoid referencing an experimental package until we make them stable. 

Changing any semantic convention means that bumping to the latest version of the SDK could cause a transitive compilation error, if the SDK forces an update to a newer version of the semantic conventions. We can mitigate that issue by having the SDK maintain its own internal copy of the conventions that it uses. That isn't pretty.

But, again, this situation is what we have explicitly decided to live with, by leaving the semantic conventions experimental. 

Since all of our instrumentation relies on these conventions, the user is in for a bumpy ride if we break any convention – especially if we fail to roll those changes out quickly. We better respect that fact when we touch the conventions – experimental doesn't mean we can be thoughtless. We can't dribble out breaking changes to the conventions.

2021-01-30 06:00 UTC, tedsuo commented
@lzchen @jsuereth I think there are two questions about env vars.

* Have we marked them as stable yet? The answer to that is no.
* Should we mark them as stable? We better do that soon, IMHO.

Since they are currently experimental, I would like to mark them here as such, and then a separate issue can be opened about making them stable. Does that sound good to you two?

2021-02-01 17:40 UTC, lzchen commented
@tedsuo 
Discussed during 02/01/2021 maintainer's meeting.
Environment variables that are related to tracing will be marked as stable by the 1.0.0 release.

2021-02-01 17:47 UTC, bogdandrutu approved these changes

2021-02-01 18:10 UTC, bogdandrutu requested changes

2021-02-01 18:10 UTC, bogdandrutu commented on specification/protocol/otlp.md
> +**Status**: [Stable](../document-status.md)
There is are discussion in this document about JSON being supported for OTLP/HTTP which I think we are not yet ready to make it stable. How can we solve that?

2021-02-02 15:35 UTC, cijothomas approved these changes

2021-02-02 17:18 UTC, tedsuo commented on specification/protocol/otlp.md
> +**Status**: [Stable](../document-status.md)
Ok, I marked OTLP/HTTP as experimental. The JSON and binary formats for HTTP were intermixed; if we want proto over OTLP/HTTP to be stable this section should be re-written.

2021-02-02 18:15 UTC, tigrannajaryan commented on specification/protocol/otlp.md
> +**Status**: [Stable](../document-status.md)
OTLP/HTTP-Protobufs are stable. Only OTLP/HTTP-JSON is unstable. Please file a TODO to fix this.

We should probably also note that only Traces are currently stable. Looks like we are going to end up with a lot of clarifications for our stability declarations in this file to be true, but that's the reality.

2021-02-03 14:49 UTC, carlosalberto commented on specification/protocol/otlp.md
> +**Status**: [Stable](../document-status.md)
@bogdandrutu Please review. I think that we are ready to merge this and tune the OTLP/JSON part in the related follow up.

2021-02-03 22:53 UTC, reyang approved these changes
:shipit:

2021-02-04 03:40 UTC, bogdandrutu approved these changes

2021-02-04 06:06 UTC, anuraaga approved these changes

2021-02-04 14:06 UTC, merged

2022-02-04 14:56 UTC, Sachin1O1 commented
I guess, we need to update the status of the doc again or is it still in experimental?