Add OT Trace Propagator.
open-telemetry/opentelemetry-specification pull request #1402
Opened 2021-02-05 15:22 UTC by carlosalberto

Fixes #1391 

Adds  `OT Trace` propagator as a (very) optional extension component.

cc @yurishkuro

2021-02-05 18:53 UTC, mwear approved these changes
LGTM

2021-02-05 19:03 UTC, ocelotl requested changes

2021-02-05 19:03 UTC, ocelotl commented on specification/context/api-propagators.md
> +This a list of additional propagators that MAY be maintained and distributed
```suggestion
This is a list of additional propagators that MAY be maintained and distributed
```

2021-02-05 19:03 UTC, ocelotl commented on specification/context/api-propagators.md
> +  propagator name as it is not wide adopted format in the OpenTracing ecosystem.
```suggestion
  propagator name as it is not widely adopted format in the OpenTracing ecosystem.
```

2021-02-05 19:59 UTC, yurishkuro approved these changes

2021-02-05 19:59 UTC, yurishkuro commented on specification/context/api-propagators.md
> +  used by the OpenTracing Basic Tracers. It MUST not use `OpenTracing` in the resulting
```suggestion
  used by the OpenTracing Basic Tracers. It MUST NOT use `OpenTracing` in the resulting
```

https://tools.ietf.org/html/rfc2119

2021-02-05 20:01 UTC, ocelotl approved these changes

2021-02-05 20:43 UTC, codeboten approved these changes

2021-02-06 01:04 UTC, bogdandrutu approved these changes

2021-02-06 01:14 UTC, merged