Mark SDK ENV VAR and Versioning documents as stable
open-telemetry/opentelemetry-specification pull request #1409
Opened 2021-02-08 23:22 UTC by tedsuo

Fixes #
Resolves v1.0 blocker identified here: [](https://github.com/open-telemetry/opentelemetry-specification/pull/1372#issuecomment-775278062)

## Changes
* Marks "OpenTelemetry Environment Variable Specification" document as stable
* Marks "Versioning and stability for OpenTelemetry clients" document as stable

2021-02-08 23:24 UTC, carlosalberto approved these changes

2021-02-08 23:30 UTC, cijothomas approved these changes

2021-02-08 23:32 UTC, tedsuo commented
Actually looks like this is redundant with https://github.com/open-telemetry/opentelemetry-specification/pull/1407

2021-02-08 23:32 UTC, bogdandrutu requested changes

2021-02-08 23:32 UTC, bogdandrutu commented on specification/sdk-environment-variables.md
> +**Status**: [Stable](document-status.md)
This is not stable correct? See comments in https://github.com/open-telemetry/opentelemetry-specification/pull/1407

2021-02-08 23:33 UTC, bogdandrutu commented
@tedsuo I missed the version document, we can make this one only for that.

2021-02-08 23:34 UTC, bogdandrutu commented on specification/sdk-environment-variables.md
> +**Status**: [Stable](document-status.md)
Consider to remove the env variables from this and make it only for versioning, so we can merge this quick :)

2021-02-08 23:58 UTC, bogdandrutu approved these changes

2021-02-08 23:59 UTC, cijothomas approved these changes

2021-02-09 00:02 UTC, bogdandrutu commented
Trivial PR, we can merge fast :)

2021-02-09 00:02 UTC, merged