Finalize SpanLimits definition, add option to configure it
open-telemetry/opentelemetry-specification pull request #1416
Opened 2021-02-09 19:20 UTC by bogdandrutu

2021-02-09 20:06 UTC, tigrannajaryan commented on specification/trace/sdk.md
> +example bellow (the name of the cofiguration class MAY be `SpanLimits`, and the
```suggestion
example bellow. The name of the cofiguration class MAY be `SpanLimits`, and the
```

2021-02-09 20:06 UTC, tigrannajaryan commented on specification/trace/sdk.md
> +`LinkCountLimit` to be consistent with the environment variables; implementation
```suggestion
`LinkCountLimit` to be consistent with the environment variables. Implementation
```

2021-02-09 20:06 UTC, tigrannajaryan commented on specification/trace/sdk.md
> +`AttributePerLinkCountLimit`):
```suggestion
`AttributePerLinkCountLimit`:
```

2021-02-09 20:06 UTC, tigrannajaryan commented on specification/trace/sdk.md
> +`LinkCountLimit` to be consistent with the environment variables; implementation
Maybe remove the actual names used here and simply say that names should be consistent with environment variables.

2021-02-09 20:06 UTC, tigrannajaryan commented on specification/trace/sdk.md
> +* `AttributePerLinkCountLimit` - Maximum allowed attribute per span link count;
It is not clear what this section describes.

2021-02-09 20:45 UTC, bogdandrutu commented on specification/trace/sdk.md
> +`LinkCountLimit` to be consistent with the environment variables; implementation
Everywhere else we define the names in the code, and env follows that not the other way around. See BatchSpanProcessor. So probably just remove the part `to be consistent with the environment variables` and maybe keep the link to the env as suggested.

2021-02-09 20:46 UTC, bogdandrutu commented on specification/trace/sdk.md
> +example bellow (the name of the cofiguration class MAY be `SpanLimits`, and the
Done.

2021-02-09 20:47 UTC, bogdandrutu commented on specification/trace/sdk.md
> +`AttributePerLinkCountLimit`):
Done.

2021-02-09 20:47 UTC, bogdandrutu commented on specification/trace/sdk.md
> +`LinkCountLimit` to be consistent with the environment variables; implementation
Done.

2021-02-09 20:47 UTC, bogdandrutu commented on specification/trace/sdk.md
> +* `AttributePerLinkCountLimit` - Maximum allowed attribute per span link count;
Consistency with other parts of the document.

2021-02-09 21:50 UTC, tigrannajaryan approved these changes

2021-02-09 22:32 UTC, carlosalberto approved these changes

2021-02-09 22:51 UTC, jmacd approved these changes

2021-02-10 00:15 UTC, tedsuo approved these changes
Since these limits are not required to be implemented, I think it is fine to add these limits now. We don't currently define what happens when these limits are surpassed. That is also fine; it should be left to the implementor to take what whatever action makes these limits effective in their language, should they need to implement them.

2021-02-10 02:20 UTC, anuraaga approved these changes

2021-02-10 02:20 UTC, anuraaga commented on specification/trace/sdk.md
> +* `AttributePerEventCountLimit` - Maximum allowed attribute per span event count;
This generally seems like a safe change but I would double check these two variables. For example, an alternative approach could be to allow the attribute count limit above to apply to all of the span, events, and links. Less knobs for similar safety - without properly evaluating the options I'm uncomfortable if this blocks other approaches or not. If it doesn't, it's fine.

2021-02-10 03:04 UTC, bogdandrutu commented on specification/trace/sdk.md
> +* `AttributePerEventCountLimit` - Maximum allowed attribute per span event count;
I think usually people would like a limit way large for the span attributes than what they want for the attributes per event. I don't expect users to set the limit of attributes per event to be 1000, more or less around 32.

2021-02-10 03:09 UTC, yurishkuro commented on specification/trace/sdk.md
> +The SDKs MAY provide a way to change these limits, via a configuration to the
L30 says MUST, which makes more sense, given that the default value of 1000 is completely arbitrary (and imho completely unreasonable in the general case - a span with 1000 attributes / events?)

2021-02-10 03:15 UTC, bogdandrutu commented on specification/trace/sdk.md
> +The SDKs MAY provide a way to change these limits, via a configuration to the
Good call, I think the default is unreasonable.

2021-02-10 03:16 UTC, bogdandrutu commented on specification/trace/sdk.md
> +The SDKs MAY provide a way to change these limits, via a configuration to the
Maybe `128`, but I will do a separate PR.

2021-02-10 03:16 UTC, bogdandrutu commented
@yurishkuro please approve if you think is ok, I updated to must

2021-02-10 03:24 UTC, yurishkuro approved these changes

2021-02-10 03:28 UTC, bogdandrutu commented
@tedsuo your comment is no longer applying based on the feedback from @yurishkuro.

2021-02-10 07:20 UTC, iNikem approved these changes

2021-02-10 08:44 UTC, arminru commented on specification/trace/sdk.md
> +TracerProvider, by allowing users to configure individual limits like the java
```suggestion
TracerProvider, by allowing users to configure individual limits like in the Java
```

2021-02-10 08:44 UTC, arminru commented on specification/trace/sdk.md
> +example bellow. The name of the cofiguration class MAY be `SpanLimits`, and the
```suggestion
example bellow. The name of the configuration class MAY be `SpanLimits`, and the
```

2021-02-10 08:44 UTC, arminru commented on specification/trace/sdk.md
> +`AttributePerEventCountLimit`, `AttributePerLinkCountLimit`.
```suggestion
and `LinkCountLimit`. Implementations MAY provide additional configuration such as
`AttributePerEventCountLimit` and `AttributePerLinkCountLimit`.
```

2021-02-10 08:44 UTC, arminru commented on specification/trace/sdk.md
> +`AttributePerEventCountLimit`, `AttributePerLinkCountLimit`.
```suggestion
example bellow. The name of the configuration options SHOULD be `AttributeCountLimit`, `EventCountLimit`, and `LinkCountLimit`.
The options MAY be bundled in a class, which then SHOULD be called `SpanLimits`.
Implementation MAY provide additional configuration such as
`AttributePerEventCountLimit` and `AttributePerLinkCountLimit`.
```
Alternative to the two comments since I'd make it optional to group them in a class.

2021-02-10 08:44 UTC, arminru commented on specification/trace/sdk.md
>  To protect against such errors, SDK Spans MAY discard attributes, links, and
Since the limits MUST be configurable anyway now, should we also make this a MUST?

2021-02-10 08:44 UTC, arminru commented on specification/trace/sdk.md
> +* `AttributePerEventCountLimit` - Maximum allowed attribute per span event count;
Should we also adapt the default for these two then? Currently it's 1000 for all.

2021-02-10 08:44 UTC, arminru commented on specification/trace/sdk.md
> +If there is a configurable provided, the SDK SHOULD honor the environment variables
```suggestion
If there is a configuration provided, the SDK SHOULD honor the environment variables
```

2021-02-10 08:44 UTC, arminru commented on specification/trace/sdk.md
> +If there is a configurable provided, the SDK SHOULD honor the environment variables
The meaning of "SHOULD honor" is not clear to me. I'd clearly specify if the environment variables overrule the limits set on the TracerProvider in code or the other way round.
Also, "SHOULD honor" sounds like if the environment variables would _only_ be applicable if a configuration was provided in code.

2021-02-10 08:44 UTC, arminru commented on specification/trace/sdk.md
> +The SDKs MUST provide a way to change these limits, via a configuration to the
Please add an entry to the spec compliance matrix for the new MUST requirements.

2021-02-10 08:56 UTC, Oberon00 requested changes
This adds a nontrivial new MUST requirement right before release. Note that support for environment variables in SDKs is only a MAY, so SDKs are likely to not have this implemented at all.
Also, since we immediately make this stable without review period (except for this PR), our options to fix issues later are limited.

I don't understand why this seems to be so urgent. The affected env vars are marked experimental now, so this is not blocking release of 1.0, right?

2021-02-10 08:58 UTC, Oberon00 commented
@tedsuo 

> Since these limits are not required to be implemented, I think it is fine to add these limits now.

The PR makes it a MUST to make it configurable though. Technically you could make the configuration interface a no-op I suppose, but is this really the intention here?

2021-02-10 14:33 UTC, yurishkuro commented
> This adds a nontrivial new MUST requirement right before release.

Good call. I think it's better to say "*if the SDK implements the limits* then the limits MUST be configurable"

2021-02-10 15:17 UTC, carlosalberto commented
> if the SDK implements the limits then the limits MUST be configurable

I like this, seems like a good trade-off.

2021-02-10 15:25 UTC, bogdandrutu commented
@Oberon00 please unblock the PR just in case I don't fix this until you close the day, if you are ok with @yurishkuro suggestion and I will do that.

2021-02-10 15:31 UTC, bogdandrutu commented on specification/trace/sdk.md
> +TracerProvider, by allowing users to configure individual limits like the java
Done.

2021-02-10 15:31 UTC, bogdandrutu commented on specification/trace/sdk.md
> +example bellow. The name of the cofiguration class MAY be `SpanLimits`, and the
Done.

2021-02-10 15:32 UTC, bogdandrutu commented on specification/trace/sdk.md
> +`AttributePerEventCountLimit`, `AttributePerLinkCountLimit`.
done.

2021-02-10 15:40 UTC, bogdandrutu commented on specification/trace/sdk.md
> +* `AttributePerEventCountLimit` - Maximum allowed attribute per span event count;
Done.

2021-02-10 15:41 UTC, bogdandrutu commented on specification/trace/sdk.md
>  To protect against such errors, SDK Spans MAY discard attributes, links, and
We agreed that if the limits are implemented then this is a MUST.

2021-02-10 15:45 UTC, Oberon00 commented
I still don't understand why we must rush this into 1.0, but since the TC seems to be in broad agreement and the MAY/MUST issue was fixed, I will do as requested and lift my request-changes.

2021-02-10 15:50 UTC, carlosalberto commented
@Oberon00 

One factor is the desire to keep environment variables (if implemented by the SIG) as stable as possible, as they are user-facing API points. At the same time, I think there are potential improvements that can be done on top without breaking this (as #1425

2021-02-10 15:55 UTC, bogdandrutu commented
@Oberon00 all languages that are in RC or close to GA implemented this functionality in different ways, I made a search and saw that js has something, java has something else etc. That configuration was in the RC so I think is better to have it in the specs since at least 5 different languages implemented this (indeed differently).

2021-02-10 16:00 UTC, yurishkuro approved these changes

2021-02-10 16:01 UTC, Oberon00 commented on specification/trace/sdk.md
> -MUST provide some way to configure them, at least when creating or initializing it.
This MUST did not include span limits.

2021-02-10 16:03 UTC, Oberon00 commented on specification/trace/sdk.md
> +the `TracerProvider` and it MUST provide some way to configure them, at least
```suggestion
the `TracerProvider` and it MUST provide some way to configure all of them that are implemented in the SDK, at least
```

Otherwise we may accidentally introduce a MUST for the SpanLimits.

2021-02-10 16:04 UTC, Oberon00 commented on specification/trace/sdk.md
> +a recommended limit.
```suggestion
a configured limit.
```

2021-02-10 16:05 UTC, Oberon00 commented on specification/trace/sdk.md
> +If there is a configuration provided, the SDK SHOULD honor the environment variables
This seems counter-intuitive. The env vars SHOULD override programmatic setting of these values?

2021-02-10 16:07 UTC, Oberon00 commented
Seeing as there are many comments / discussion is still somewhat active I think we should at least white the usual 48 h period before merging this.

2021-02-10 16:09 UTC, bogdandrutu commented on specification/trace/sdk.md
> +a recommended limit.
Done.

2021-02-10 16:11 UTC, bogdandrutu commented on specification/trace/sdk.md
> +the `TracerProvider` and it MUST provide some way to configure them, at least
Done.

2021-02-10 16:14 UTC, bogdandrutu commented
@Oberon00 all the comments are about "wording" not about the meaning of the change. I think we all agreed that this is a MUST is you implement the limits which is a MAY. I don't think the discussion is controversial in any way.

2021-02-10 16:17 UTC, Oberon00 commented
I agreee the discussion is not controversial. But on the other hand, if the goal is to keep this stable, a review period of the *usual* length will help to have a solid wording where we don't need any "hotfixes" later. I just have a bad feeling about rushing this in so fast for 1.0.

2021-02-10 16:22 UTC, bogdandrutu commented on specification/trace/sdk.md
> +The SDKs MUST provide a way to change these limits, via a configuration to the
Done.

2021-02-10 17:12 UTC, bogdandrutu commented on specification/trace/sdk.md
> +If there is a configurable provided, the SDK SHOULD honor the environment variables
What about removing this sentence completely?

2021-02-10 17:19 UTC, bogdandrutu commented on specification/trace/sdk.md
> +If there is a configurable provided, the SDK SHOULD honor the environment variables
Decided to remove it, since we don't have the same statement in any other place where we offer env options. Consistency wins.

2021-02-10 17:20 UTC, bogdandrutu commented on specification/trace/sdk.md
> +If there is a configuration provided, the SDK SHOULD honor the environment variables
This sentence is not necessary, anywhere else we don't refer to the env, so I think it is better to just remove it.

2021-02-10 17:20 UTC, arminru commented on specification/trace/sdk.md
> +If there is a configurable provided, the SDK SHOULD honor the environment variables
I think we should clearly specify if the environment variables overrule the limits set on the TracerProvider in code or the other way round. Ideally we would specify such precedence globally to be consistent but that's out of scope of this PR.

2021-02-10 17:30 UTC, bogdandrutu commented on specification/trace/sdk.md
> +`AttributePerEventCountLimit`, `AttributePerLinkCountLimit`.
Done.

2021-02-10 18:16 UTC, cijothomas commented on spec-compliance-matrix.md
> +| [SpanLimits](specification/trace/sdk.md#span-limits) ]                                           |          |    |      |    |        |      |        |     |      |     |      |       |
Should we mark this as optional in this matrix, as the span-limits are optional sdk feature?

2021-02-10 18:23 UTC, bogdandrutu commented on spec-compliance-matrix.md
> +| [SpanLimits](specification/trace/sdk.md#span-limits) ]                                           |          |    |      |    |        |      |        |     |      |     |      |       |
Sure.

2021-02-10 18:30 UTC, bogdandrutu commented
@Oberon00 I documented in the PR description the decision discussed with the TC members.

2021-02-10 19:01 UTC, merged