[Proposal] A pre-release review process for new major releases of any client library
open-telemetry/opentelemetry-specification pull request #1418
Opened 2021-02-10 00:41 UTC by bogdandrutu

The main idea is that before every major release or the release of a new telemetry type (metrics)
we would like to do a technical and specification conformance review that will ensure consistency
and same "look and feel" for all officially released libraries.

2021-02-10 07:05 UTC, iNikem commented
Can I ask why does TC think it needs such strict gating process?

2021-02-10 07:24 UTC, alolita reviewed
Great start on the TC helping regularize the release process. 

Some suggestions - 
* Add an overall purpose statement for this pre-release review process - what does this process aim to accomplish, outline benefits to the project.
* Add a checklist or list of questions maintainers can use for a spec compliance review. 
* Add a table to outline process milestones and timelines.

2021-02-10 15:34 UTC, tigrannajaryan commented
> Can I ask why does TC think it needs such strict gating process?

A few reasons from the top of my head:
- To help language SIGs to find out whether they are ready for GA.
- To independently certify that language implementation is spec-compliant.
- To ensure uniform experience across languages (spec is useful, but does not fully capture usability aspects and how the API compares for different languages).
- To uncover gaps in the implementation (additional untrained pair of eyes often helps).

There is probably more.

2021-02-10 17:00 UTC, jmacd approved these changes
I think this will be great fort consistency! I'd like to add some kind of commitment to do these reviews swiftly, but could leave that out.

2021-02-10 18:45 UTC, reyang commented on releases/new-telemetry-release-process.md
> +The name of the file MUST be `technical-specification-review-${language}.md`.
Would this cause name conflict? (e.g. `technical-specification-review-python.md` for tracing, and the same name for metrics later?)

2021-02-10 18:52 UTC, lzchen commented on releases/new-telemetry-release-process.md
> +The name of the file MUST be `technical-specification-review-${language}.md`.
As well, what if there are multiple reviews done?

2021-02-10 18:53 UTC, reyang commented on releases/new-telemetry-release-process-template.md
> +time in a reasonable amount of time to not delay the review process.
Later in the doc we mentioned "every decision will be made in less than 14 days after the process is started", so there is no way a language maintainer could delay the process.

Perhaps we can rephrase this to "All the questions and feedbacks will be communicated as GitHub issues filed against the language client repo. If the language maintainers don't respond before the deadline (which is two weeks after the initial filing of the PR), the PR will be closed as REJECTED.".

2021-02-10 18:54 UTC, reyang commented on releases/new-telemetry-release-process-template.md
> +Status: [PROPOSAL|REJECTED|APPROVED]
Do we intend to merge these files anyways? If we only merge approved ones, there is no need to have `Status`.

2021-02-10 18:57 UTC, lzchen commented on releases/new-telemetry-release-process-template.md
> +time in a reasonable amount of time to not delay the review process.
Is 14days the deadline for the ENTIRE process (beginning of process, TC review, language contributors addressing/fixing change, new release), or just the deadline for the contributors' response?

2021-02-10 18:57 UTC, reyang commented on releases/new-telemetry-release-process-template.md
> +Spec Compliance Matrix is up to date: [YES|NO]
This will cause issue since other folks could add new requirements to the spec compliance matrix (unless we lock the spec during language client release). Consider putting a permanent link here pointing to a specific version of the spec compliance matrix.

2021-02-10 18:58 UTC, reyang commented on releases/new-telemetry-release-process-template.md
> +Versioning And Stability Document: [LINK to version document]
We only need this once? (when metrics come, we don't need to redo this work)

2021-02-10 19:00 UTC, reyang commented on releases/new-telemetry-release-process-template.md
> +# Technical Review and Specification Conformance for ${Language}/${TELEMETRY}/${MAJOR_VERSION} library
Need to clarify what `Telemetry` is, and (assuming it is "telemetry signal") what should people do when they have more than 1 signals in a single release.

2021-02-10 19:02 UTC, reyang commented on releases/new-telemetry-release-process-template.md
> +* Ensure no experimental features (signals) are part of the main API package.
Why API but not SDK (and other packages)?

2021-02-10 19:04 UTC, bogdandrutu commented on releases/new-telemetry-release-process-template.md
> +Status: [PROPOSAL|REJECTED|APPROVED]
If we find big issues (probably will not happen), then we can end-up merging it as REJECTED.

2021-02-10 19:05 UTC, reyang commented on releases/new-telemetry-release-process.md
> +# New Telemetry Release Process
Should we stick with the term ["signal"](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/glossary.md#signals)?

2021-02-10 19:06 UTC, bogdandrutu commented on releases/new-telemetry-release-process-template.md
> +Versioning And Stability Document: [LINK to version document]
If it uses the same document (probably most of the time) then will be the same link.

2021-02-10 19:07 UTC, reyang submitted a review, later dismissed
Most of my comments are non-blocking.

One blocker I'm seeing - in this PR we've introduced new terms without definition, and some of them seem to be different from what we've already defined - e.g. `telemetry type` vs. `signal`.

2021-02-10 19:09 UTC, reyang commented on releases/new-telemetry-release-process-template.md
> +Status: [PROPOSAL|REJECTED|APPROVED]
I don't see why we want to merge it as REJECTED, would you help to explain?

2021-02-10 19:15 UTC, bogdandrutu commented
@reyang have we documented `telemetry type vs. signal` somewhere, if yes happy to change to `signal` everywhere

2021-02-10 19:24 UTC, bogdandrutu commented on releases/new-telemetry-release-process-template.md
> +Status: [PROPOSAL|REJECTED|APPROVED]
Sure, we can do it binary, if it is merged is approved otherwise is not merged. We do have the same thing in otep process but we can remove status.

2021-02-10 19:25 UTC, bogdandrutu commented
Found we have signal defined, will change

2021-02-10 20:19 UTC, bogdandrutu commented on releases/new-telemetry-release-process-template.md
> +time in a reasonable amount of time to not delay the review process.
@lzchen that is our hope, but we will probably learn more during the first few reviews.

2021-02-10 20:30 UTC, bogdandrutu commented on releases/new-telemetry-release-process-template.md
> +# Technical Review and Specification Conformance for ${Language}/${TELEMETRY}/${MAJOR_VERSION} library
Open multiple reviews?

2021-02-10 20:30 UTC, bogdandrutu commented on releases/new-telemetry-release-process-template.md
> +Spec Compliance Matrix is up to date: [YES|NO]
Done.

2021-02-10 20:30 UTC, bogdandrutu commented on releases/new-telemetry-release-process-template.md
> +* Ensure no experimental features (signals) are part of the main API package.
Done.

2021-02-10 20:30 UTC, bogdandrutu commented on releases/new-telemetry-release-process.md
> +# New Telemetry Release Process
Sure.

2021-02-10 20:31 UTC, bogdandrutu commented on releases/new-telemetry-release-process.md
> +The name of the file MUST be `technical-specification-review-${language}.md`.
`technical-specification-review-python-trace.md` is the new recommended name. Probably we should include the version if a major version bump happens

2021-02-10 20:32 UTC, bogdandrutu commented on releases/new-telemetry-release-process.md
> +The name of the file MUST be `technical-specification-review-${language}.md`.
Done.

2021-02-10 21:02 UTC, bogdandrutu commented
@alolita 

> Add an overall purpose statement for this pre-release review process - what does this process aim to accomplish, outline benefits to the project.

From @tigrannajaryan :

A few reasons from the top of my head:

To help language SIGs to find out whether they are ready for GA.
To independently certify that language implementation is spec-compliant.
To ensure uniform experience across languages (spec is useful, but does not fully capture usability aspects and how the API compares for different languages).
To uncover gaps in the implementation (additional untrained pair of eyes often helps).
There is probably more.

> Add a checklist or list of questions maintainers can use for a spec compliance review.

There is a TODOs section in the template

> Add a table to outline process milestones and timelines.

Not sure I can think of how this would look like, can you provide a small example

2021-02-10 22:03 UTC, jsuereth commented on releases/new-signal-release-process.md
> +During the review process, breaking changes MAY be needed to comply with the
nit: `breaking changes related to the signal`.

2021-02-10 22:19 UTC, tigrannajaryan commented on releases/new-signal-release-process-template.md
> +* Ensure consistent names across implementations (e.g. TraceId vs Id)
I think it is will be a delicate balance. Try to be consistent but also try to avoid coming up with solutions that are not idiomatic for the language.

Very subjective, I know. :-)

2021-02-10 22:19 UTC, tigrannajaryan commented on releases/new-signal-release-process-template.md
> +* Avoid confusions across implementation (e.g same function returns has different behaviors)
Maintainers usually know everything about the one language they work on, but not much about other language implementations. I'd rather burden TC than maintainers with this job.

2021-02-10 22:27 UTC, bogdandrutu commented
For all maintiners, please do not release a stable version until a decision is made on this PR:

@open-telemetry/cpp-maintainers

@open-telemetry/go-maintainers

@open-telemetry/dotnet-maintainers

@open-telemetry/erlang-maintainers

@open-telemetry/java-maintainers

@open-telemetry/javascript-maintainers

@open-telemetry/php-maintainers  

@open-telemetry/python-maintainers 

@open-telemetry/ruby-maintainers 

@open-telemetry/swift-maintainers

2021-02-10 22:38 UTC, aabmass commented on releases/new-signal-release-process.md
> +existing signal release) for OpenTelemetry client libraries.
```suggestion
existing released signal) for OpenTelemetry client libraries.
```

2021-02-10 22:38 UTC, aabmass commented on releases/new-signal-release-process-template.md
> +# Technical Review and Specification Conformance for ${Language}/${SIGNAL}/${MAJOR_VERSION} library
It would be good to indicate the released client library version somewhere in the template, since it may not be the same as `${MAJOR_VERSION}`

2021-02-10 22:39 UTC, bogdandrutu commented on releases/new-signal-release-process-template.md
> +# Technical Review and Specification Conformance for ${Language}/${SIGNAL}/${MAJOR_VERSION} library
A signal is only one added per major version, maybe in the section of TODOs to add that

2021-02-10 22:43 UTC, reyang commented on releases/new-signal-release-process-template.md
> +Versioning And Stability Document: [LINK to version document]
```suggestion
Versioning And Stability Document: [Link to version document]
```

2021-02-10 22:49 UTC, bogdandrutu commented on releases/new-signal-release-process-template.md
> +Versioning And Stability Document: [LINK to version document]
Done.

2021-02-10 22:49 UTC, bogdandrutu commented on releases/new-signal-release-process-template.md
> +# Technical Review and Specification Conformance for ${Language}/${SIGNAL}/${MAJOR_VERSION} library
Done.

2021-02-10 22:50 UTC, bogdandrutu commented on releases/new-signal-release-process.md
> +existing signal release) for OpenTelemetry client libraries.
Done.

2021-02-10 22:52 UTC, bogdandrutu commented on releases/new-signal-release-process.md
> +During the review process, breaking changes MAY be needed to comply with the
Done.

2021-02-10 23:10 UTC, reyang commented on releases/new-signal-release-process-template.md
> +Expected Version Number: []
Do we want folks to list the components that are to be released (e.g. SDK, Zipkin exporter, OpenTracing Shim) or we should review "everything" in the repo? What if the new release has significant changes in one component, but only version bump in another component - do we review both of them or just the one that has the actual change?

2021-02-10 23:16 UTC, bogdandrutu commented on releases/new-signal-release-process-template.md
> +Expected Version Number: []
Just the one that changed

2021-02-10 23:17 UTC, cijothomas commented
> For all maintiners, please do not release a stable version until a decision is made on this PR:
> 
> @open-telemetry/cpp-maintainers
> 
> @open-telemetry/go-maintainers
> 
> @open-telemetry/dotnet-maintainers
> 
> @open-telemetry/erlang-maintainers
> 
> @open-telemetry/java-maintainers
> 
> @open-telemetry/javascript-maintainers
> 
> @open-telemetry/php-maintainers
> 
> @open-telemetry/python-maintainers
> 
> @open-telemetry/ruby-maintainers
> 
> @open-telemetry/rust-maintainers
> 
> @open-telemetry/swift-mainteiners

@bogdandrutu This requirement conflicts with the decision made with TC members (Carlos, Sergey) and .NET Maintainers at the .NET SIG meeting on 2/9, where it was decided to release 1.0 once https://github.com/open-telemetry/opentelemetry-specification/pull/1372 is merged.

https://github.com/open-telemetry/opentelemetry-dotnet/pull/1826

2021-02-10 23:17 UTC, bogdandrutu commented on releases/new-signal-release-process-template.md
> +Expected Version Number: []
I think it is mentioned in the main document:

>Every OpenTelmetry official major release MUST follow the release process
proposed in this document. A  "major release" refers to a new version of any
[signal](../specification/glossary.md#signals) (adding a new signal to an
already released major version of the library, or a major version bump for an
existing released signal) for OpenTelemetry client libraries.

2021-02-10 23:21 UTC, bogdandrutu commented
@cijothomas I think during the maintainers meeting we talked about this and decided for everyone to wait until Wed for this to be published and reviewed. I don't think we asked for postponing too much time but here we are, too late to complain anyway.

2021-02-11 00:00 UTC, bogdandrutu commented
@reyang I think you can dismiss the request changes because the main concern was addressed, unless you have other big concerns

2021-02-11 00:06 UTC, lzchen commented on releases/new-telemetry-release-process-template.md
> +time in a reasonable amount of time to not delay the review process.
@bogdandrutu 
I asked for clarification between two options. Could you clarify which one it is? xD

2021-02-11 00:06 UTC, cijothomas commented on releases/new-signal-release-process.md
> +Every OpenTelmetry official major release MUST follow the release process
```suggestion
Every OpenTelemetry official major release MUST follow the release process
```

2021-02-11 00:14 UTC, bogdandrutu commented on releases/new-signal-release-process.md
> +Every OpenTelmetry official major release MUST follow the release process
done.

2021-02-11 00:43 UTC, jsuereth commented on releases/new-signal-release-process-template.md
> +* Avoid confusions across implementation (e.g same function returns has different behaviors)
AH, I misread this as implementation differences within an SDK.

I assume, though, some leniency is allowed here (e.g. Java's Completable-Returns vs. other languages)?

2021-02-11 00:45 UTC, bogdandrutu commented on releases/new-signal-release-process-template.md
> +* Avoid confusions across implementation (e.g same function returns has different behaviors)
Yes :) we are not robots :))

2021-02-11 00:49 UTC, yurishkuro commented on releases/new-signal-release-process-template.md
> +* Avoid confusions across implementation (e.g same function returns has different behaviors)
> we are not robots

speak for yourself

2021-02-11 00:57 UTC, bogdandrutu commented on releases/new-telemetry-release-process-template.md
> +time in a reasonable amount of time to not delay the review process.
TC aims and will put effort into finishing the entire process in 14 days, for this language maintainers need to be responsive :) I think this is how I would rephrase everything

2021-02-11 02:15 UTC, ramthi requested changes

2021-02-11 03:33 UTC, lalitb commented on releases/new-signal-release-process-template.md
> +as sponsors. Any Technical Committee can be a sponsor, and any Technical
```suggestion
as sponsors. Any Technical Committee member can be a sponsor, and any Technical
```

2021-02-11 03:40 UTC, lalitb commented on releases/new-signal-release-process-template.md
> +* Ensure no experimental features (signals) are part of the released packages (e.g. api, sdk, etc.).
For opentelemetry-cpp, the releases are the source distributions, and the experimental (unstable) telemetry signals and features will be introduced behind feature flag protected by a preprocessor macro. So though metrics and logging signal would be distributed, they wouldn't be included in builds unless the feature flag is explicitly enabled. This has been clarified in our versioning doc too ( https://github.com/open-telemetry/opentelemetry-cpp/blob/main/Versioning.md )

2021-02-11 03:47 UTC, lalitb commented on releases/new-signal-release-process-template.md
> +* Avoid confusions across implementation (e.g same function returns has different behaviors)
Not sure if I understand this clearly. Functions are internal to language implementation, and it is possible for them to behave differently across language implementations, and should be fine as long as external api/sdk interfaces are consistent across languages, and compliant with specs.

2021-02-11 03:52 UTC, lalitb commented on releases/new-signal-release-process.md
> +commits to ensure that every decision will be made in less than 14 days after
Will it be 14 days ( 2 weeks ) or 14 weekdays/working days (~3 weeks )?

2021-02-11 05:22 UTC, reyang commented on releases/new-signal-release-process-template.md
> +* Ensure no experimental features (signals) are part of the released packages (e.g. api, sdk, etc.).
@open-telemetry/cpp-maintainers

2021-02-11 05:28 UTC, reyang commented on releases/new-signal-release-process-template.md
> +Committee members are not language experts, and it is expected to work with the
```suggestion
Committee members are not language experts, and are expected to work with the
```

2021-02-11 05:34 UTC, reyang commented on releases/new-signal-release-process-template.md
> +process. Language maintainers SHOULD respond to any question during the review
It is hard to understand what "any question" means here, and how the communication will be done (e.g. private chat, public meeting with recording enabled, GitHub issues, Google doc).

I suggest that we make it explicit - all the communications from the TC members (and invited language experts if there is any) to the maintainers will be summarized and published as GitHub issues against the language implementation repo, with a top level issue which contains the links to individual issues.

2021-02-11 05:36 UTC, reyang commented on releases/new-signal-release-process-template.md
> +time in a reasonable amount of time to not delay the review process.
It is unclear what is the common understanding of "reasonable amount of time", probably just put something like "two working days" similar like what we did [here](https://github.com/open-telemetry/opentelemetry-specification/blob/main/CONTRIBUTING.md#how-to-get-your-pr-merged)?

2021-02-11 05:41 UTC, reyang commented on releases/new-signal-release-process.md
> +MUST submit a PR and complete this [template](new-signal-release-process-template.md).
This will have potential conflict with the [current process](https://github.com/open-telemetry/opentelemetry-specification/blob/main/CONTRIBUTING.md#how-to-get-your-pr-merged), which mentioned that we require at minimum two valid approvals + two working days. If a "release-review-xyz-metrics-v1.0.md" PR was sent and got two valid approvals and merged by the owner, we still should not merge it if we follow this doc.

2021-02-11 05:42 UTC, reyang commented on releases/new-signal-release-process.md
> +MUST submit a PR and complete this [template](new-signal-release-process-template.md).
Minor, consider putting a recommendation on the PR title (or having a PR template and put a link here).

2021-02-11 05:43 UTC, reyang commented on releases/new-signal-release-process.md
> +the process as soon as possible, but after all features and planned changes are merged.
If I understand it correctly, we encourage people to do this right before they move from beta to rc (release candidate)?
Or the actual recommendation is to go through the process when they want to go from rc to stable release?

2021-02-11 05:48 UTC, reyang commented on releases/new-signal-release-process.md
> +After the review is approved, it is highly recommended to not make any major
it is very vague what "major change" (e.g. is moving one API from one namespace to another considered as major change? is package name change considered as major change?) - can we require each client to implement public API enforcement rule as part of CI. In this way we can make it clear that "if any public API is changed, it must go through the process again".

2021-02-11 05:50 UTC, reyang commented on releases/new-signal-release-process-template.md
> +# Technical Review and Specification Conformance for ${Language}/${SIGNAL}/${MAJOR_VERSION} library
```suggestion
# Technical Review and Specification Conformance for ${LANGUAGE}/${SIGNAL}/${MAJOR_VERSION} library
```

2021-02-11 05:53 UTC, reyang commented on releases/new-telemetry-release-process-template.md
> +time in a reasonable amount of time to not delay the review process.
> @lzchen that is our hope, but we will probably learn more during the first few reviews.

If the goal is to learn by trying out the process with few reviews, we should go through OTEP first.

2021-02-11 15:08 UTC, tigrannajaryan commented on releases/new-signal-release-process-template.md
> +* Ensure no experimental features (signals) are part of the released packages (e.g. api, sdk, etc.).
Hiding experimental features behind feature flags is a great approach. It lets you make progress, yet prevents exposing half-baked features to end users. We should encourage all SIGs to take this approach.

2021-02-11 15:42 UTC, bogdandrutu commented on releases/new-telemetry-release-process-template.md
> +time in a reasonable amount of time to not delay the review process.
OTEP of what?

2021-02-11 15:44 UTC, bogdandrutu commented on releases/new-signal-release-process-template.md
> +* Avoid confusions across implementation (e.g same function returns has different behaviors)
@lalitb we are only talking about public API here. I will clarify.

2021-02-11 15:47 UTC, bogdandrutu commented on releases/new-signal-release-process-template.md
> +as sponsors. Any Technical Committee can be a sponsor, and any Technical
Done.

2021-02-11 15:47 UTC, bogdandrutu commented on releases/new-signal-release-process-template.md
> +* Avoid confusions across implementation (e.g same function returns has different behaviors)
I think now is clear, please open if not.

2021-02-11 15:48 UTC, bogdandrutu commented on releases/new-signal-release-process.md
> +commits to ensure that every decision will be made in less than 14 days after
2 weeks is the wish

2021-02-11 15:53 UTC, bogdandrutu commented on releases/new-signal-release-process.md
> +MUST submit a PR and complete this [template](new-signal-release-process-template.md).
Added a statement that this is an exception from the rule.

2021-02-11 15:54 UTC, bogdandrutu commented on releases/new-signal-release-process-template.md
> +# Technical Review and Specification Conformance for ${Language}/${SIGNAL}/${MAJOR_VERSION} library
done.

2021-02-11 15:55 UTC, bogdandrutu commented on releases/new-signal-release-process.md
> +MUST submit a PR and complete this [template](new-signal-release-process-template.md).
done.

2021-02-11 15:57 UTC, bogdandrutu commented on releases/new-signal-release-process-template.md
> +* Ensure no experimental features (signals) are part of the released packages (e.g. api, sdk, etc.).
I think there are multiple ways to ensure experimental features are not public. So this can be one of them.

2021-02-11 15:58 UTC, bogdandrutu commented on releases/new-signal-release-process-template.md
> +Spec Compliance Matrix is up to date: [Permanent link to the matrix]
That is a possibility, let's not over specified. I think any link that proves and shows the current status of the matrix is good :)

2021-02-11 15:59 UTC, bogdandrutu commented on releases/new-signal-release-process-template.md
> +Committee members are not language experts, and it is expected to work with the
done.

2021-02-11 16:15 UTC, bogdandrutu commented on releases/new-signal-release-process-template.md
> +time in a reasonable amount of time to not delay the review process.
sure, added "ideally 1 business day".

2021-02-11 16:16 UTC, bogdandrutu commented on releases/new-signal-release-process-template.md
> +process. Language maintainers SHOULD respond to any question during the review
Done. clarify the communication channels

2021-02-11 16:18 UTC, bogdandrutu commented on releases/new-signal-release-process.md
> +the process as soon as possible, but after all features and planned changes are merged.
done.

2021-02-11 16:20 UTC, bogdandrutu commented on releases/new-signal-release-process.md
> +After the review is approved, it is highly recommended to not make any major
if you rename the package from `opentelemetry.trace` to `opentelemetry.foobar` I would say yes :).

2021-02-12 05:30 UTC, reyang commented on releases/new-telemetry-release-process-template.md
> +time in a reasonable amount of time to not delay the review process.
I suggest that we pick two language clients that are willing to try out this process, go through the steps proposed in this PR until they release a stable version. After two language clients released, we can take the learning/feedback and see whether we should move forward or back out.

Whether this PR should be here or somewhere else (e.g. in the community repo) - I don't know, probably not here as it is weird to put some process document and request form in a spec repo (unless the process is about the spec itself). No strong opinion though.

2021-02-12 11:22 UTC, iNikem commented
Should autoinstrumentation repos follow the same review process?

2021-02-12 18:29 UTC, bogdandrutu commented on releases/new-telemetry-release-process-template.md
> +time in a reasonable amount of time to not delay the review process.
that is what we will do naturally, not all the languages are ready for this. So not sure if anything is needed to be said here.

2021-02-15 17:23 UTC, bogdandrutu commented
@open-telemetry/technical-committee please review, this blocks progress if we do not merge or reject this proposal.

2021-02-15 18:19 UTC, yurishkuro reviewed
I am in favor of the formalized process with a checklist to follow / template doc to fill out. But I'm not as certain that the TC must always be involved. We're operating on the honor system. A language team could just release a new version without following the process. If they do follow the process then I would rather trust them to follow it all the way, without an extra friction of involving TC.

2021-02-16 06:03 UTC, bogdandrutu commented
@yurishkuro point taken. But I think it is hard to come with that list with going through the process couple of times to identify all the requirements.

Alternatively I can see us just requiring the checklist and as a best effort TC members do what I suggest here once or twice and bring the learnings to the process back

2021-02-16 06:40 UTC, yurishkuro commented
> it is hard to come with that list 

That's fair, we can certainly do a few test runs, especially since many TC members are actually involved in some of the SIGs. I would just prefer to take it easy on the MUST wording for TC involvement (I am ok with MUST for the process itself).

2021-02-16 22:33 UTC, carlosalberto approved these changes

2021-02-16 22:34 UTC, carlosalberto commented
LGTM - as there are still standing questions (and doubts), I suggest we give this a shot to a few **volunteering** SIGs and document our findings/feedback in further PRs to tune this process.

2021-02-17 01:53 UTC, ThomsonTan commented on CONTRIBUTING.md
> +New signal release reviews are subject to different rules that and do not follow
```suggestion
New signal release reviews are subject to different rules and do not follow
```

2021-02-17 02:06 UTC, ThomsonTan commented on releases/new-signal-release-process-template.md
> +* Avoid confusions across implementation (e.g same public API has different behaviors)
```suggestion
* Avoid confusions across implementation (e.g. same public API has different behaviors)
```

2021-02-17 02:12 UTC, ThomsonTan commented on releases/new-signal-release-process-template.md
> +* Ensure no experimental features (signals) are part of the released packages (e.g. api, sdk, etc.).
As we could include experimental feature in the released package, should we say "Ensure no experimental features/signals are enabled by default in the released packages?

2021-03-01 15:50 UTC, tigrannajaryan approved these changes
LGTM.

To make it clear: for me this process is a way for TC members to help language SIGs to make a release, to help ensure the language implementation is consistent with other languages, confirms with the spec. We want the TC member to be another pair of fresh eyes who can help the SIG to go over the release checklist.
 
There is absolutely no intent to introduce a process that "controls" the language SIGs or introduces obstacles in the release process. If any of the language SIGs notice that the process is not helpful the TC would like to know about it immediately so that we can fix (or eliminate) the process.

2021-03-01 18:07 UTC, lzchen commented
@tigrannajaryan 
The Python SIG has been trying this out in a non-formal way. @carlosalberto has volunteered to go through our API/SDK surface and review it thoroughly for discrepancies, and as a maintainer I find this to be of great value.

Personally, I find the wording of the PR to be quite aggressive and way more formal than it needs to be. Having to go through a process just adds more overheads onto the maintainers and TC member(s) responsible for reviewing. I am totally fine with working offline directly with a TC member as a maintainer to discuss any of the logistics, but a whole process seems to be overkill.

The only benefit I see from having a process is that it will encourage reviewers/approvers/maintainers/TC members to prioritize the tasks outlined in the "review" process as something to be done as soon as possible. The two week timeline "lights a fire" under contributors and I think that is valuable (it certainly caused Python contributors to prioritize a lot of the tasks that @carlosalberto had found). Just my thoughts from the first few days of going through this process "informally".

2021-03-01 18:08 UTC, dyladan commented on releases/new-signal-release-process-template.md
> +Spec Compliance Matrix is up to date: [Permanent link to the matrix]
Link to the latest matrix or the matrix commit at the time of the review?

2021-03-22 22:44 UTC, carlosalberto commented
After trying this out with the Python SIG, I suggest with this along the following points:

* Define this as general review process that SIGs can opt in.
* The issues and changes that the reviewer points out can be further discussed with the maintainers, and they MAY be applied or not, at the discretion of the maintainers themselves.

@bogdandrutu Sounds like a good compromise? And in general, having this document as a general starting point is something really valuable to have, even if not _all_ SIGs end up doing it.

2021-04-06 03:19 UTC, closed without merging