Add none for exporter selection enums.
open-telemetry/opentelemetry-specification pull request #1439
Opened 2021-02-12 07:29 UTC by anuraaga

## Changes

Adds `none` as an option for exporter selection. Because the default is `otlp`, there is no way to disable signal export via env vars.

2021-02-12 09:59 UTC, Oberon00 approved these changes

2021-02-12 09:59 UTC, Oberon00 commented on specification/sdk-environment-variables.md
> +- `"none"`: Disables export of traces.
Nit: No sure about "disable". If the application adds its own exporter, it probably won't get disabled by this setting.

2021-02-12 10:18 UTC, anuraaga commented on specification/sdk-environment-variables.md
> +- `"none"`: Disables export of traces.
Thanks tried tweaking

2021-02-12 10:38 UTC, iNikem approved these changes

2021-02-12 12:53 UTC, arminru approved these changes

2021-02-12 12:53 UTC, arminru commented on CHANGELOG.md
> +- Adds `none` as a possible value for OTEL_TRACES_EXPORTER and OTEL_METRICS_EXPORTER to disable export([#1439](https://github.com/open-telemetry/opentelemetry-specification/pull/1439))
```suggestion
- Adds `none` as a possible value for OTEL_TRACES_EXPORTER and OTEL_METRICS_EXPORTER to disable export
  ([#1439](https://github.com/open-telemetry/opentelemetry-specification/pull/1439))
```

2021-02-12 15:52 UTC, carlosalberto approved these changes

2021-02-12 18:31 UTC, bogdandrutu requested changes
I am confused about this change. What is the scenario that we want people to "disable" trace but still link all the trace SDK?

2021-02-12 20:16 UTC, trask approved these changes
> What is the scenario that we want people to "disable" trace but still link all the trace SDK?

We use this in the javaagent, so that vendors can disable the OTLP exporter and provide their own exporter, while still getting all of the other auto-configuration goodness.

2021-02-13 01:28 UTC, reyang approved these changes

2021-02-13 02:41 UTC, anuraaga commented
@bogdandrutu Yeah this is for the case we provide a batteries included package like the Java agent. Another case is wanting to only export traces without metrics.

2021-02-14 06:00 UTC, SergeyKanzhelev approved these changes

2021-02-15 00:51 UTC, bogdandrutu approved these changes

2021-02-15 00:53 UTC, bogdandrutu commented
@anuraaga @trask thanks for the explanation. Next time please describe this in the PR description or an issue, it is important to make sure that we have good reasons (documented) for what we change/add :) Every API/property we add will add support cost so we need to understand why we are paying this cost :)

2021-02-15 03:10 UTC, jsuereth approved these changes

2021-02-15 15:04 UTC, merged