erlang process.runtime attributes: remove TODO note and update descriptions
open-telemetry/opentelemetry-specification pull request #1445
Opened 2021-02-17 18:38 UTC by tsloughter

No real change here, simply removes the TODO since it is done and updates the attributes into a table.

Related issue: https://github.com/open-telemetry/opentelemetry-erlang/issues/96

2021-02-17 18:42 UTC, yurishkuro approved these changes
Does Erland SDK populate these already?

2021-02-17 18:57 UTC, tsloughter commented
I don't know what the semantic convention failure is about. Are docs on this in the repo?

2021-02-17 18:57 UTC, tsloughter commented
@yurishkuro in the latest `main` branch, yes.

2021-02-17 19:12 UTC, tsloughter commented
This reminded me to update the spec matrix, so I've now included that in this PR as well.

2021-02-17 20:25 UTC, SergeyKanzhelev approved these changes

2021-02-17 20:27 UTC, arminru approved these changes

2021-02-17 20:27 UTC, arminru commented on specification/resource/semantic_conventions/process.md
> +<!-- semconv process.runtime -->
This would add the same table as above when running the semantic conventions generator tool. Since this table is maintained manually, you'll have to remove those markers or the build fails. Currently it's complaining about a mismatch with the (potentially) generated files. See how it's done with the other tables below.

2021-02-17 20:27 UTC, SergeyKanzhelev commented on specification/resource/semantic_conventions/process.md
> +<!-- semconv process.runtime -->
this requires the yaml update: https://github.com/open-telemetry/opentelemetry-specification/tree/main/semantic_conventions#yaml-model-for-semantic-conventions

2021-02-17 20:51 UTC, tsloughter commented
Ah, woops, thanks @arminru and @SergeyKanzhelev :). I had copied from the earlier table in the document without thinking, should be fixed now.

2021-02-17 21:14 UTC, Oberon00 commented on specification/resource/semantic_conventions/process.md
> +| Attribute  | Type | Description  | Examples  | Required |
To be consistent with other languages, I would keep the list form above.

2021-02-19 05:18 UTC, bogdandrutu approved these changes
Please resolve conflicts

2021-02-19 12:17 UTC, Oberon00 requested changes

2021-02-19 12:17 UTC, Oberon00 commented on specification/resource/semantic_conventions/process.md
> +| Attribute  | Type | Description  | Examples  | Required |
Looking at it again, this even repeats the `Type` and `Required` column. I think this is rather misleading. Please either:

1. Revert to the list notation as above, just remove the TODO, maybe add a table with examples (as for other runtimes like Java) if you have more than one; or
2. remove the Type and Required column from the table.

2021-02-19 13:52 UTC, tsloughter commented
Switched it back to a list and merged the spec matrix with the latest in `main`.

2021-02-19 13:53 UTC, Oberon00 approved these changes
OK, but you might want to keep the example somehow.

2021-02-19 13:58 UTC, tsloughter commented
Ok, added an example table.

2021-02-19 18:30 UTC, merged