Add SpanExporter.ForceFlush.
open-telemetry/opentelemetry-specification pull request #1467
Opened 2021-02-25 14:20 UTC by Oberon00

Fixes #1454.

## Changes

Adds `ForceFlush` (which already existed in SdkTracerProvider and SpanProcessor) to SpanExporter, and adds wording that SpanProcessor.ForceFlush must call that new SpanExporter.ForceFlush.

2021-02-25 17:33 UTC, arminru commented on CHANGELOG.md
> +- Add `ForceFlush` to `Span Exporter` interface [#1467](https://github.com/open-telemetry/opentelemetry-specification/pull/1467).
```suggestion
- Add `ForceFlush` to `Span Exporter` interface ([#1467](https://github.com/open-telemetry/opentelemetry-specification/pull/1467))
```

2021-02-25 17:33 UTC, arminru commented on specification/trace/sdk.md
> +invocation, but before the `Processor` exports the completed spans.
```suggestion
invocation, but before the exporter exports the completed spans.
```

2021-02-25 17:33 UTC, arminru commented on specification/trace/sdk.md
> +call to `ForceFlush` SHOULD be completed as soon as possible, preferably before
```suggestion
call to `ForceFlush` SHOULD be exported as soon as possible, preferably before
```
to avoid confusion with `end`ing spans

2021-02-25 17:33 UTC, arminru commented on specification/trace/sdk.md
> +`ForceFlush` SHOULD complete or abort within some timeout. `ForceFlush` can be
```suggestion
`ForceFlush` SHOULD complete or abort within some timeout. `ForceFlush` MAY be
```

2021-02-25 17:33 UTC, arminru commented on specification/trace/sdk.md
>  `ForceFlush` SHOULD complete or abort within some timeout. `ForceFlush` can be
```suggestion
`ForceFlush` SHOULD complete or abort within some timeout. `ForceFlush` MAY be
```

2021-02-25 17:41 UTC, Oberon00 commented on specification/trace/sdk.md
>  `ForceFlush` SHOULD complete or abort within some timeout. `ForceFlush` can be
I think this should be done for all the ForceFlush definitions and also Shutdown at once, it would be confusing if TracerProvider/SpanProcessor/Exporter differed only there.

2021-02-25 17:42 UTC, Oberon00 commented on specification/trace/sdk.md
> +This is a hint to ensure that any `Spans` passed to the exporter prior to the
```suggestion
This is a hint to ensure that the export of any `Spans` passed to the exporter prior to the
```

2021-02-25 17:43 UTC, Oberon00 commented on specification/trace/sdk.md
> +call to `ForceFlush` SHOULD be completed as soon as possible, preferably before
I will do this instead: https://github.com/open-telemetry/opentelemetry-specification/pull/1467/files#r583035984

2021-02-25 17:44 UTC, Oberon00 commented on specification/trace/sdk.md
> +`ForceFlush` SHOULD complete or abort within some timeout. `ForceFlush` can be
Same as https://github.com/open-telemetry/opentelemetry-specification/pull/1467/files#r583035024

2021-02-25 22:38 UTC, carlosalberto commented
Overall LGTM, although this is precisely one of the interfaces that are exposed to the users and needs special care and some thought on whether some kind of 'default method' can be offered in the different SIGs.

cc @bogdandrutu

2021-02-26 01:42 UTC, bogdandrutu approved these changes

2021-02-26 01:42 UTC, bogdandrutu commented on specification/trace/sdk.md
> +#### `ForceFlush()`
I think we can say, in case of stable releases a "no-op" implementation can be offered as a default. I think that is the best we can do :)

2021-02-26 04:45 UTC, reyang commented on specification/trace/sdk.md
> +the exporter's `Export` with all spans for which this was not already done and
I think this shouldn't be "MUST". For example, if the processor has 1000 items, and it is calling the `exporter.Export` with a maximum size of 100 items, on the 200 items timeout limit is hit - the `processor.ForceFlush` should return as early as possible with an indication of timeout rather than push more items to the exporter.

2021-02-26 04:49 UTC, reyang requested changes
I think timeout has higher priority, so the processor should not try to push more items to the exporter when timeout happened.

2021-02-26 05:00 UTC, reyang commented on specification/trace/sdk.md
> +This is a hint to ensure that the export of any `Spans` passed to the exporter prior to the
This is a bit vague, if another thread is calling `exporter.Export(batch)`, what do we expect `exporter.ForceFlush` to do?

2021-02-26 10:52 UTC, Oberon00 commented on specification/trace/sdk.md
> +This is a hint to ensure that the export of any `Spans` passed to the exporter prior to the
This is up to the exporter I think. But if Export and ForceFlush are called concurrently, then by definition we have a race condition, even if the Exporter does locking internally, so we cannot possibly guarantee that any Spans in that Export call are exported or not. The most we could offer would be a "all or none Spans of each concurrent Export call are affected" gurantee, but I don't think that would be helpful.

2021-02-26 11:06 UTC, Oberon00 commented on specification/trace/sdk.md
> +the exporter's `Export` with all spans for which this was not already done and
Interesting point, we could add wording on the timeout here. But I don't know how close we want to specify that. For example: It might make sense to heuristically determine in the SpanProcessor "Oh no, we are coming close to the timeout, we took average x seconds per batch but still have y batches left and only z seconds of the timeout. Better call exporter.ForceFlush now and only then Export more spans if time is still left".

Probably that wouldn't make sense though because if Export takes so long that we run into the timeout, ForceFlush would maybe be a no-op -- but it might also not be, e.g. `write` for a filebased exporter can take long, and still needs a `flush` at the end.

Specifying the details is complicated here, so maybe we should say:

> `ForceFlush` MUST be implemented such that these conditions are fulfilled:
>
> * If there was no timeout, `ForceFlush`MUST have been called after all spans were passed to `Export` of the Exporter.
> * If there was a timeout, at least one `Export` or `ForceFlush` operation was attempted.
> * ForceFlush MAY be called more than once if at least one Export call is in-between. Note: SpanProcessors might want to heuristically determine that they could run into a timeout and in response call `ForceFlush` before finishing export.
>
> If `ForceFlush` does not support a timeout, or an infinite timeout was given, then a stricter condition is required: The operation MUST call the exporter's `Export` with all spans for which this was not already done and invoke ForceFlush on the export afterwards exactly once.

2021-02-26 11:15 UTC, Oberon00 commented on specification/trace/sdk.md
> +the exporter's `Export` with all spans for which this was not already done and
We could additionally specify that the timeout expressed as a deadline timepoint SHOULD be passed on to the exporter, i.e. if I call processor.ForceFlush(timeout=5) at T=2, then the deadline is D = T + timeout = 7, so the first export call may get timeout=5, and if it took 1, then the next export call invoked at T=3 will get timeout=4 (= D - T).

2021-02-26 18:35 UTC, reyang commented on specification/trace/sdk.md
> +the exporter's `Export` with all spans for which this was not already done and
The "most permissive but maybe still useful spec" looks reasonable to me 👍

2021-02-26 18:42 UTC, reyang commented on specification/trace/sdk.md
> +This is a hint to ensure that the export of any `Spans` passed to the exporter prior to the
I guess we could change it from "any `Spans` passed to the exporter" to "any `Spans` that the exporter has received"?

2021-02-26 18:54 UTC, bogdandrutu commented on specification/trace/sdk.md
> +the exporter's `Export` with all spans for which this was not already done and
> I think this shouldn't be "MUST". For example, if the processor has 1000 items, and it is calling the exporter.Export with a maximum size of 100 items, on the 200 items timeout limit is hit - the processor.ForceFlush should return as early as possible with an indication of timeout rather than push more items to the exporter.

I feel we are too picky, and try to over specify things. Maybe as simple as "In particular, if the `SpanProcessor` has any associated exporters, it MUST call the exporter's `Export` with all spans for which this was not already done and then invoke `ForceFlush` on it. " If a timeout is given then the operation should return when deadline is hit.

If users calls with such a small timeout they get half of the work done. We should not try to ensure at least one export and one flush is called. If timeout is 1us then maybe only an export can be called, etc. So just explain the order of execution and describe that timeout should be interrupt this.

2021-02-26 18:55 UTC, bogdandrutu commented
> I think timeout has higher priority, so the processor should not try to push more items to the exporter when timeout happened.

I agree with @reyang here, we should should return when the deadline happens and not try to over-engineer the logic, if too short you get done what was possible during the amount of time.

2021-02-26 19:09 UTC, Oberon00 commented on specification/trace/sdk.md
> +the exporter's `Export` with all spans for which this was not already done and
>  We should not try to ensure at least one export and one flush is called

I agree, that's why I suggested "or". But I also feel that my suggestion in the comment above is overly complicated.

2021-02-26 19:10 UTC, Oberon00 commented on specification/trace/sdk.md
> +This is a hint to ensure that the export of any `Spans` passed to the exporter prior to the
```suggestion
This is a hint to ensure that the export of any `Spans`  the exporter has received prior to the
```

2021-02-26 19:18 UTC, Oberon00 commented on specification/trace/sdk.md
> +the exporter's `Export` with all spans for which this was not already done and
I added 04e3e29.

2021-02-26 19:32 UTC, reyang approved these changes
LGTM. Thanks for driving this! 💯

2021-02-26 20:20 UTC, ThomsonTan commented on specification/trace/sdk.md
> +make the flush timeout configurable.
For blocking API, I think it is very hard to abort within some timeout. Like the implementation complies to the spec if it just does abort its entry point without doing any work. Should we say `ForceFlush` should return (complete or abort) as soon as possible if the given `timeout` is reached?

2021-03-08 17:59 UTC, bogdandrutu commented
@Oberon00 please rebase :) that will also remove the stale

2021-03-08 19:53 UTC, jsuereth approved these changes

2021-03-11 16:49 UTC, bogdandrutu commented
Please rebase

2021-03-15 08:20 UTC, Oberon00 commented on specification/trace/sdk.md
> +make the flush timeout configurable.
This is copy & past from shutdown and the other ForceFlush. Please open an issue if you want tor reword this (should be consistent everywhere).

2021-03-15 16:24 UTC, bogdandrutu commented
@arminru can you rebase & review & and merge if you are ok with this change :)

2021-03-15 16:34 UTC, arminru approved these changes

2021-03-15 16:34 UTC, arminru commented on specification/trace/sdk.md
> +The [built-in SpanProcessors](#built-in-span-processors) MUST do so.
@Oberon00 Please add an entry in the compliance matrix for that, otherwise it might be overlooked easily.

2021-03-15 16:45 UTC, arminru commented on spec-compliance-matrix.md
> +| [SpanProcessor implements ForceFlushes spec](specification/trace/sdk.md#force-flush-1)                                             |          |    |      |    |        |      |        |     |
```suggestion
| [Built-in `SpanProcessor`s implement `ForceFlush` spec](specification/trace/sdk.md#forceflush-1)                                             |          |    |      |    |        |      |        |     |      |     |      |       |
```

2021-03-15 16:45 UTC, arminru commented on spec-compliance-matrix.md
> +| [Exporter interface has `ForceFlush`](specification/trace/sdk.md#forceflush-1) |          |    | + |    |                                                                         |      |        |
```suggestion
| [Exporter interface has `ForceFlush`](specification/trace/sdk.md#forceflush-2) |          |    | + |    |                                                                         |      |        |     |      |     |      |       |
```

2021-03-15 16:47 UTC, Oberon00 commented on spec-compliance-matrix.md
> +| [SpanProcessor implements ForceFlushes spec](specification/trace/sdk.md#force-flush-1)                                             |          |    |      |    |        |      |        |     |
Outdated, will add the name change.

2021-03-15 16:48 UTC, Oberon00 commented on spec-compliance-matrix.md
> +| [SpanProcessor implements ForceFlushes spec](specification/trace/sdk.md#forceflush-1)            |          |    |      |    |        |      |        |     |      |     |      |       |
```suggestion
| [Built-in `SpanProcessor`s implement `ForceFlush` spec](specification/trace/sdk.md#forceflush-1)               |          |    |      |    |        |      |        |     |      |     |      |       |
```

Thank you @arminru

2021-03-15 17:01 UTC, merged