Add SetAllAttributes to allow setting multiple attributes at once to …
open-telemetry/opentelemetry-specification pull request #1473
Opened 2021-02-26 08:23 UTC by anuraaga

…a Span.

## Changes

We've gotten use feedback that it would be convenient to have a way to set multiple attributes at once. This is particularly useful in languages like Java where because of the way generics work, something like `attributes.forEach(span::setAttribute)` can't be offered.

https://github.com/open-telemetry/opentelemetry-java/pull/2799

2021-02-26 08:26 UTC, Oberon00 commented on specification/trace/api.md
> +  single argument. This MAY be called `SetAllAttributes`.
```suggestion
- An API to set multiple `Attributes` at once, where the `Attributes` are passed as a
  in a single method call. This MAY be called `SetAllAttributes`.
```

Whether this would be a single (map) argument or multiple arguments (e.g. `**kwargs` in Python) is language dependent.

2021-02-26 08:29 UTC, anuraaga commented on specification/trace/api.md
> +  single argument. This MAY be called `SetAllAttributes`.
Yup thanks

2021-02-26 08:31 UTC, iNikem approved these changes

2021-02-26 08:46 UTC, Oberon00 commented
This being a "MAY", I *think* it should be fine anyway, but this is another example where we should think of interface stability #1457. This is what we have in the spec:

> Major versions of the API MUST be supported for a minimum of three years after the release of the next major API version.

and

> A version of the SDK which supports the latest minor version of the last major version of the API will continue to be maintained during LTS.

so the question is now if this should be a major or minor version bump for the API. It probably is only minor because calls against earlier versions will continue to compile:

> Backward-incompatible changes to API packages MUST NOT be made unless the major version number is incremented. All existing API calls MUST continue to compile and function against all future minor versions of the same major version.

although you could argue that

> Major version bumps MUST occur when there is a breaking change to a stable interface

is also fulfilled in languages where there are no default interface implementations, although, as discussed in #1457, there are always ways to make it backwards compatible by using a new interface instead of modifying an existing one.

2021-02-26 17:05 UTC, tigrannajaryan commented
> 
> although you could argue that
> 
> > Major version bumps MUST occur when there is a breaking change to a stable interface
> 
> is also fulfilled in languages where there are no default interface implementations, although, as discussed in #1457, there are always ways to make it backwards compatible by using a new interface instead of modifying an existing one.

Given that `Span` interface is not intended to be implemented by the end user, I do not think addition of a method to the interface constitutes a breaking change.

2021-02-26 17:14 UTC, yurishkuro commented
> Given that `Span` interface is not intended to be implemented by the end user

I would disagree. If that was the case why bother having an API at all, instead of just SDK. This may not cause immediate problems since the API is too new, but it is theoretically possible that it's been already implemented somewhere.

2021-02-26 17:39 UTC, Oberon00 commented
I just noticed we also have this in the spec under "Design goals" https://github.com/open-telemetry/opentelemetry-specification/blob/v1.0.1/specification/versioning-and-stability.md#design-goals:

> Ensure that application owners stay up to date with the latest release of the SDK. We want all users to stay up to date with the latest version of the OpenTelemetry SDK. We do not want to create hard breaks in support, of any kind, which leave users stranded on older versions. It MUST always be possible to upgrade to the latest minor version of the OpenTelemetry SDK, without creating compilation or runtime errors.

If I interpret this correctly, then newer SDKs must continue supporting older APIs? But I can't find a "normative" reference to that outside this "Design goals" section.

2021-02-26 18:03 UTC, carlosalberto commented
> This may not cause immediate problems since the API is too new, but it is theoretically possible that it's been already implemented somewhere.

Well, .Net was released and it doesn't have this functionality, but otherwise, yes ;)

And overall, I'd say user-interfaces (such as `SpanProcessor`) sit next to API when it comes to compatibility (as opposed to internals and relatively internal members of the SDK).

2021-02-26 19:36 UTC, reyang commented on specification/trace/api.md
> +  single method call. This method MAY be called `SetAllAttributes`.
I would vote for `SetAttributes` instead of `SetAllAttributes`.
`SetAllAttributes` gives a feeling that it will make previous calls invalid:
```text
span.SetAllAttributes(foo: 1, bar: 2);
span.SetAllAttributes(baz: 3);
// do we have foo, bar and baz, or we only have baz?
```

```text
span.SetAttributes(foo: 1, bar: 2);
span.SetAttributes(baz: 3);
// we know that we will have foo, bar and baz
```

2021-02-26 19:36 UTC, reyang requested changes
Please see my comment [here](https://github.com/open-telemetry/opentelemetry-specification/pull/1473/files#r583872561)

2021-02-27 02:08 UTC, anuraaga commented on specification/trace/api.md
> +  single method call. This method MAY be called `SetAllAttributes`.
Heh this is the obvious of Java, we would expect `SetAttributes` to clear existing ones and `SetAll` to keep them, similar to `putAll` in a Map. I can remove the naming recommendation if it seems too language specific?

2021-02-27 10:53 UTC, iNikem commented
> > Given that `Span` interface is not intended to be implemented by the end user
> 
> I would disagree. If that was the case why bother having an API at all, instead of just SDK. This may not cause immediate problems since the API is too new, but it is theoretically possible that it's been already implemented somewhere.

I find this line of thought very disturbing. I hear again and again that any changes, even additive ones, to our API are breaking and should not happen. Do we really believe that our API is perfect and should not be evolved? Or that any change must produce a new major version?

2021-02-27 18:42 UTC, yurishkuro commented
> I find this line of thought very disturbing. I hear again and again that any changes, even additive ones, to our API are breaking and should not happen. Do we really believe that our API is perfect and should not be evolved? Or that any change must produce a new major version?

The stdlib in Go language has evolved for 10yrs without breaking changes (and without major versions). I think it's fair to say the complexity of Go's stdlib is orders of magnitude higher that OTEL. Evolution of the APIs does not have to mean breaking users' code.

2021-02-27 19:48 UTC, iNikem commented
> > I find this line of thought very disturbing. I hear again and again that any changes, even additive ones, to our API are breaking and should not happen. Do we really believe that our API is perfect and should not be evolved? Or that any change must produce a new major version?
> 
> The stdlib in Go language has evolved for 10yrs without breaking changes (and without major versions). I think it's fair to say the complexity of Go's stdlib is orders of magnitude higher that OTEL. Evolution of the APIs does not have to mean breaking users' code.

I absolutely don't argue with that. But it seems there are different opinions about what is a breaking change. Adding a new method to the interface, which is not meant to be implemented by end users, is not a breaking change. See #1457 as well.

2021-03-01 13:47 UTC, carlosalberto commented on specification/trace/api.md
> +  single method call. This method MAY be called `SetAllAttributes`.
@anuraaga Probably yes. We had in the past a (now forgotten) PR that tried to add this, and it was suggested to define the operation as a very general thing, and don't make the name a hard requirement (and mention languages can adapt it to their own guidelines, etc).

2021-03-01 16:18 UTC, yurishkuro commented on specification/trace/api.md
> +  single method call. This method MAY be called `SetAllAttributes`.
`AddAttributes` is shorter and unambiguous

2021-03-09 08:29 UTC, anuraaga commented on specification/trace/api.md
> +  single method call. This method MAY be called `SetAllAttributes`.
Sorry for the delay, went ahead and removed the naming recommendation.

> AddAttributes is shorter and unambiguous

I think it's a bit ambiguous, previous attributes (especially for list attributes) we could expect to remain in some form if it's just `Add`.

2021-03-10 04:19 UTC, anuraaga commented
@reyang Is your comment addressed now that the method name suggestion is removed?

2021-03-15 02:32 UTC, anuraaga commented
@open-telemetry/technical-committee any way to proceed with this PR? Thanks!

2021-03-15 23:01 UTC, carlosalberto approved these changes

2021-03-15 23:04 UTC, carlosalberto commented
I think @reyang request for changes has indeed been addressed, as we don't impose a formal name for the new operation. Also, we have now a clear path regarding compatibility (see https://github.com/open-telemetry/oteps/pull/147) so we should be fine to go ;)

2021-03-16 17:26 UTC, merged