Allow to collect host architecture
open-telemetry/opentelemetry-specification pull request #1483
Opened 2021-03-01 05:58 UTC by rakyll

Host type is not enough to represent the processor architecture
of the host. Add "arch" to allow users to collecting processor
architecture. We may predefine some commonly used architecture
as a follow up to this change.

2021-03-01 08:49 UTC, anuraaga commented on semantic_conventions/resource/host.yaml
> +            The CPU architecture the host system is running on.
If it seems manageable I think an enum could work better for this - if a specialized architecture exists and can use OpenTelemetry, then we'd always be able to add it anyways, otherwise there aren't that many archs.

Otherwise I'd recommend doing similar to runtime and add descriptions of how to get this value in various languages to include any normalization that could be needed, eg replacing hyphen with underscore, etc.

2021-03-01 09:06 UTC, Oberon00 commented on semantic_conventions/resource/host.yaml
> +            The CPU architecture the host system is running on.
@rakyll You wrote in the PR description

> We may predefine some commonly used architecture as a follow up to this change.

But I think we should already have these in the first version. Restricting a free-form string to an enum (even if one with `allow_custom_values: true`) would be a breaking change.

2021-03-01 09:13 UTC, Oberon00 commented
I think we should look a bit into how this would work with "mixed-arch" scenarios. E.g. it is common to have a 32 bit process running on an 64 bit OS on x86_64. That gives potential for `os.arch`, `process.arch` in addition to `host.arch` in this PR. Or is `host.arch` the only architecture, and the rest would only be ABIs? Interesting in that regard is the existence of the [x32 ABI](https://en.wikipedia.org/wiki/X32_ABI), i.e. 64 bit instructions with 32 bit pointers on a 64 bit Linux.

2021-03-01 18:53 UTC, rakyll commented
@Oberon00 good point about how this will affect the architecture we may collect for the process and OS. Let me think about this a bit before we merge anything. @anuraaga I'll also provide a predefined list on the next iteration.

2021-03-02 04:02 UTC, reyang commented on semantic_conventions/resource/host.yaml
> +            The CPU architecture the host system is running on.
Is this the host CPU architecture or the host OS architecture?

For example, one could run x86 version of Windows OS on an AMD64 hardware. The architecture of an executable image, a process, an operating system (including a subsystem) and a hardware could be all different.

2021-03-02 06:46 UTC, Oberon00 commented on semantic_conventions/resource/host.yaml
> +            The CPU architecture the host system is running on.
Can the image really have a different arch from it's process?

2021-03-02 16:16 UTC, rakyll commented on semantic_conventions/resource/host.yaml
> +            The CPU architecture the host system is running on.
This is the CPU architecture of the host system, the VM's CPU.

The OS architecture would be in the os.yaml.

2021-03-02 17:25 UTC, reyang commented on semantic_conventions/resource/host.yaml
> +            The CPU architecture the host system is running on.
> Can the image really have a different arch from it's process?

An image could be `AnyCPU` for .NET Core app. It could be an architecture independent package (e.g. Mach-O).

2021-03-02 17:27 UTC, reyang approved these changes
LGTM.

2021-03-02 20:40 UTC, Oberon00 commented on semantic_conventions/resource/host.yaml
> +            The CPU architecture the host system is running on.
> An image could be AnyCPU for .NET Core app. It could be an architecture independent package (e.g. Mach-O).

The process image would then be the image of the .NET Runtime executable IMHO.

2021-03-02 20:43 UTC, Oberon00 commented on semantic_conventions/resource/host.yaml
> +            The CPU architecture the host system is running on.
@rakyll 
> This is the CPU architecture of the host system, the VM's CPU.

Sounds good 👍  Can you add that point to the PR?

2021-03-02 20:51 UTC, jmacd approved these changes

2021-03-03 00:38 UTC, rakyll commented on semantic_conventions/resource/host.yaml
> +            The CPU architecture the host system is running on.
Done. Added predefined options as well.

Are you happy with formatting? ALLCAPS_WITHUNDERSCORES?

2021-03-03 00:38 UTC, rakyll commented
PTAL

2021-03-03 14:22 UTC, carlosalberto approved these changes

2021-03-03 14:27 UTC, Oberon00 commented on semantic_conventions/resource/host.yaml
> +            The CPU architecture the host system is running on.
Looking at other enums (e.g. faas.trigger, messaging.operation) it seems that we use all-lowercase with underscores elsewhere.
Note that when generating code from the semantic convention it is possible to uppercase if that is the target language's convention.

2021-03-03 14:28 UTC, Oberon00 requested changes

2021-03-03 14:28 UTC, Oberon00 commented on semantic_conventions/resource/host.yaml
> +            - id: x86_64
I think AMD 64 and x86_64 are synonyms.

2021-03-03 17:34 UTC, maxgolov commented on specification/resource/semantic_conventions/host.md
> +`host.arch` MUST be one of the following or, if none of the listed values apply, a custom value:
Values here neither match the common convention for Linux / Debian arch, e.g. not matching what's reported by `uname -m`, nor match what Node.js `os.arch()` API would have reported; nor what Rust architecture uses for the standard set of arch.... For different languages - you'd have different strings. And none of them would match the list proposed here 😄  So it's going to be quite an adventure to normalize to that proposed list 🤷 

I believe a better set could be this:

Architecture | Applies to
-- | --
x86 | x86, wow64, i386, i486, etc.
amd64 | x86_64, amd64, x64
arm32 | arm32
arm64 | arm64, aarch64
ppc32 | 32-bit PowerPC
ppc64 | 64-bit PowerPC
ia64 | Itanium
other | indistinguishable, or not listed here. **Architecture as reported by the language of choice without normalizing it / without bringing it to common denominator.**

C++, Rust, or Node - typically have their own API to obtain the process arch string. This string is going to be in their own common format. For Node - this list is well-described here: https://nodejs.org/api/os.html#os_os_arch - I personally believe Node's list is quite reasonable.

More complete set of architectures is described here in Linux kernel tree:
https://github.com/torvalds/linux/tree/master/arch

If you truly intend to describe the host arch , it would be reasonable to respect the Linux standard names for the archs, as the most prominent host OS. That's also what `uname -m` command would _typically_ report, namely `[arm|arm64|ia64|mips|x86]`. I would've left the loophole in this list to allow reporting what OS language-specific API reports as architecture. Any data analysis within a slice of data reported by agents written in specific language is consistent: a language (e.g. `node`) would report only a fixed set of archs. There is also not going to be any need to normalize.

I don't like this proposed list because it does not seem to align with the arch lists typically captured by prominent language APIs, neither matches the Linux kernel arch list.

2021-03-03 17:56 UTC, maxgolov commented on semantic_conventions/resource/host.yaml
> +            The CPU architecture the host system is running on.
Don't restrict this to enum, please.

2021-03-03 22:14 UTC, rakyll commented on specification/resource/semantic_conventions/host.md
> +`host.arch` MUST be one of the following or, if none of the listed values apply, a custom value:
This looks so much better. Go has a similar approach here. I initially wanted to propose something more aligned with uname but the formatting of OS names made me want to follow the UPPER_CASE style here. I'm modifying this PR in a bit.

2021-03-03 22:15 UTC, rakyll commented
PTAL

2021-03-04 00:24 UTC, anuraaga commented on semantic_conventions/resource/host.yaml
> +            - id: other
Can we just leave out the attribute if unknown instead of having an enum for it?

2021-03-04 06:22 UTC, rakyll commented
PTAL

2021-03-04 15:08 UTC, carlosalberto commented
@Oberon00 @maxgolov Please confirm this is ready to go (I _think_ it is ;) )

@rakyll Usually marking comments as resolved makes it easier to review, btw.

2021-03-05 07:19 UTC, anuraaga approved these changes

2021-03-05 18:36 UTC, rakyll commented
@carlosalberto will resolve them from this point on, thanks for pointing it out.

2021-03-05 18:49 UTC, carlosalberto commented
@maxgolov @Oberon00 Feedback as been properly addressed. In case of any further detail, please fill a follow up ;)

2021-03-05 18:50 UTC, merged