Add information about metric staleness and temporal alignment
open-telemetry/opentelemetry-specification pull request #1648
Opened 2021-04-26 21:57 UTC by jmacd

## Changes

Adds information about staleness markers using Prometheus-style NaN values.
Adds basic information about temporal alignment.

Related issues #1297

2021-04-28 13:30 UTC, jsuereth commented on specification/metrics/datamodel.md
> +Implementations have implicit and explicit means of detecting when a
`<putting on my author hat>`
This paragraph struggles in introducing the concept and transitioning to the meat of the technical details.

Suggestion:

> Staleness is a property of a metric stream.   When a metric stream that previously produced data is no longer > producing new (valid) data, the stream is considered "stale", i.e. we know the stream existed, but we're not
> sure whether or not to expect data going forward.

> Consumers and Producers of metric streams have two mechanisms to denote "staleness" of a metric stream:  > An implicit mechanism that leverages expectation on when metric points should arrive, and an explicit 
> mechanism where staleness is denoted directly in metric data points.


I think the helps motivate the next to sections/details a bit better.  I'm not certain if you want to outline the use-case of staleness better.
`</removing the author hat>`

2021-04-28 13:30 UTC, jsuereth commented on specification/metrics/datamodel.md
> +The explicit mechanism, characteristic of the Prometheus Remote-Write
nit: "The explicit staleness detection mechanism"

2021-04-28 13:30 UTC, jsuereth commented on specification/metrics/datamodel.md
> +NaN values can be used to indicate an explicit gap in an metric stream
Nit:  I'd rework this wording to point at the actual OTLP types.


> Nan values can be used to indicate an explicit gap in a metric stream.
> - For Gauge and Sum streams, place NaN in `NumberDataPoint.as_double`
> - For Histogram streams, place NaN in `HistogramDataPoint.sum`
> - For Summary streams, place NaN in `SummaryDataPoint.sum`

2021-04-28 13:30 UTC, jsuereth commented on specification/metrics/datamodel.md
> +these systems, data is expected to arrive more often than a specified
Is it worth denoting that this tends to be associated with "push-based" metric protocols?

2021-04-28 13:30 UTC, jsuereth commented on specification/metrics/datamodel.md
> +Temporal alignment describes how to modify a stream of metric data
I think this may need an image to help outline it better.  I'm happy to provide one if you want.

2021-04-28 13:30 UTC, jsuereth commented on specification/metrics/datamodel.md
> +Temporal alignment is performed after overlapping data points have
One question I have around temporal-alignment *and* streaming metric data is what kind of "look-behind" we need on the stream.  I.e. how much buffering do we need/plan to have to perform something like temporal alignment.

Does it make sense to outline the streaming use case specifically?  E.g. my (naive) brain keeps coming back to the notion that it may make sense to define a "simple" temporal alignment that:

- Keeps *one* TTL of data at any given time.
- Performs alignment within the "current window" and drops points that fall entirely before the "current" window after aligning them. (not sure I used good english here)
- A heuristic for when to stop collecting/aligning for a given bucket where the next piece of data is fired out.

That's likely way to detailed for just outlining the concept and ensuring implementations know where and how to use the data in the data model, but wanted to run the idea by you.

2021-04-28 13:30 UTC, jsuereth commented on specification/metrics/datamodel.md
> +For cumulative aggregation temporality, Sum values, Histogram bucket
I think this is good enough to demonstrate feasibility.

Couldn't you just use the same fractional contribution as done in the delta aggregation, except you'd *also* preserve the previous time-window values and aggregate those in?

2021-04-28 13:30 UTC, jsuereth commented on specification/metrics/datamodel.md
> +the logic for Gauge values to its `ValueAtQuantile` field.
(curiousity, non-blocking) Is this how it's done in prometheus?  I mean I can't see any other alternatives here.

2021-04-28 19:16 UTC, victlu commented on specification/metrics/datamodel.md
> +as "staleness".
Just a commentary...

I always thought of these as two different concepts. Invalid values are just that, and has no association with staleness. 

In my mind, staleness has to do with timeliness of observed value (even if it's invalid) and I think of it as "freshness". Thus, we provide, in our UI, a freshness timestamp of the last known value. And, we leave it to our users to apply their own "TTL" values for each metric (on UI side). This helps when they see "invalid" values that is fresh as of 1 minute ago. When we showed no value or invalid value only or no freshness timestamp, our users constantly ask if the telemetry system is up or down.

2021-05-05 15:27 UTC, brian-brazil commented on specification/metrics/datamodel.md
> +protocol, uses IEEE 754 floating point NaN values to encode invalid
Not quite, it's not any NaN but rather one particular bit pattern which happens to be a NaN. This is distinct from a NaN that can be scrapped directly, which will have a different bit pattern.

2021-05-25 07:20 UTC, jmacd commented on specification/metrics/datamodel.md
> +as "staleness".
I tried to reword this sentence after your feedback and the feedback above.

2021-05-25 07:22 UTC, jmacd commented on specification/metrics/datamodel.md
> +protocol, uses IEEE 754 floating point NaN values to encode invalid
👍 I've written a recommendation for "any IEEE 754 floating point NaN value" to indicate invalid values. I want to just use what IEEE says about NaN values as the definition for what these mean as observations.

2021-05-25 07:23 UTC, jmacd commented on specification/metrics/datamodel.md
> +Temporal alignment describes how to modify a stream of metric data
I've removed the content about temporal alignment. I will preserve your feedback.

2021-05-25 07:24 UTC, jmacd commented on specification/metrics/datamodel.md
> +the logic for Gauge values to its `ValueAtQuantile` field.
Yes.

2021-05-25 07:30 UTC, jmacd commented
@open-telemetry/specs-metrics-approvers PTAL.

2021-05-25 08:11 UTC, brian-brazil commented on specification/metrics/datamodel.md
> +protocol, uses IEEE 754 floating point NaN values to encode invalid
That's still incorrect, as written you're saying that any NaN means stale and that NaNs are never valid values.

2021-05-25 14:46 UTC, MrAlias approved these changes

2021-05-25 14:54 UTC, jsuereth requested changes

2021-05-25 14:54 UTC, jsuereth commented on specification/metrics/datamodel.md
> +- For `Histogram` data points, use the `HistogramDataPoint.count` field
`HistogramDataPoint.count` is `fixed64` which is an integer type and NaN is unrepresentable here.

Similar concern for Summary count.

2021-05-25 15:08 UTC, jsuereth commented
I'd like to talk about this at Today's data-model SiG.

I have some open questions:

1. Should NaN be used to represent staleness?
2. How do we represent staleness in Histogram / Summary where we have an aggregation of data with lots of optional points?

This PR answers:

1. Yes
2. Use `count` as it's required (unfortunately, it's also not a double).

I know 2 is a problem, not sure I agree with 1, want to talk that through.

2021-05-25 15:47 UTC, bogdandrutu commented on specification/metrics/datamodel.md
> +- For `Histogram` data points, use the `HistogramDataPoint.sum` field
Why not `Count`? Seems more natural than `Sum`.

2021-05-25 16:41 UTC, jmacd commented
We have discussed replacing this PR with a data model proposal that takes advantage of optional bits to encode staleness and potentially last-data records. @victlu will begin working on a prototype. :tada:

2021-05-25 16:41 UTC, closed without merging

2021-05-25 17:17 UTC, jsuereth commented on specification/metrics/datamodel.md
> +- For `Histogram` data points, use the `HistogramDataPoint.sum` field
count is an integer :(