Add InstrumentationLibrary and Resource to ShouldSample.
open-telemetry/opentelemetry-specification pull request #1658
Opened 2021-04-28 11:17 UTC by Oberon00

Fixes #1588

## Changes

- Add InstrumentationLibrary and Resource as Sampler arguments.

2021-04-28 12:09 UTC, iNikem approved these changes

2021-04-28 12:10 UTC, iNikem commented on specification/trace/sdk.md
> +* `Resource` of the `Span` to be created.
How can we make this change in backward compatible way?

2021-04-28 12:14 UTC, Oberon00 commented on specification/trace/sdk.md
> +* `Resource` of the `Span` to be created.
In Java it is trivial to do so by adding the new method with extended parameters as a default method to the interface, and the implementation calls the old method, ignoring the additional parameters. The same works for other languages that allow default implementations in interfaces (only C++ comes to mind).

A solution that will work in all object-oriented languages is to have a new interface (Sampler2) and have the `SetSampler` (or equivalent) API accept either the new or the old interface.

2021-04-28 14:24 UTC, carlosalberto approved these changes

2021-04-28 14:26 UTC, carlosalberto commented
@open-telemetry/specs-approvers please review this.

Worth mentioning this change again in the next maintainers meeting, and also worth having a prototype for a language that does not support default implementation/parameters.

2021-04-28 15:12 UTC, jkwatson commented on specification/trace/sdk.md
> +* `Resource` of the `Span` to be created.
I think in Java we would want to make *both* methods have default implementations, since otherwise those who only wanted to use the new method would have to also implement the old-one as a no-op, which would be a pretty annoying dev experience. But, that will also make it somewhat confusing to Sampler implementors about what they're supposed to do. I guess documentation is the key.

2021-04-28 15:14 UTC, yurishkuro commented on specification/trace/sdk.md
> +* `Resource` of the `Span` to be created.
Passing the resource, which is not supposed to change during Sampler's life cycle, is a constant unnecessary performance overhead. Why can't it be given to sampler during sampler construction?

2021-04-28 15:16 UTC, yurishkuro commented on specification/trace/sdk.md
> +* `InstrumentationLibrary` (name and version) of the `Span` to be created.
Instrumentation library is given to tracer on construction, and presumable included in the spans this tracer creates. I think it's better to make it retrievable from the span rather than passing it to sampler as argument (which adds constant perf overhead).

2021-05-06 07:09 UTC, Oberon00 commented on specification/trace/sdk.md
> +* `InstrumentationLibrary` (name and version) of the `Span` to be created.
>  I think it's better to make it retrievable from the span rather than passing it to sampler as argument (which adds constant perf overhead).

This is not a "rather than". We need to do both. The span does not exist when ShouldSample is called.

That said two ideas how this could be implemented instead:

1. Pass a `ReadableSpanBuilder` to the sampler, that should cover all existing parameters.
2. Instead of passing Resource and InstrumentationLibrary separately, pass a `ReadableTracer` to ShouldSample.

I'd like to leave this choice up to the SIGs.

2021-05-06 07:13 UTC, Oberon00 commented on specification/trace/sdk.md
> +* `InstrumentationLibrary` (name and version) of the `Span` to be created.
We had this discussion with exporters already and I think the conclusion was that an Exporter must in general be prepared for each span to have a different resource, because the same exporter might be attached to different SpanProcessors and the same SpanProcessor to different TracerProviders with different resources. I think the same (minus the intermediate SpanProcessor) applies to the sampler.

I would have been all for adding a restriction to the spec to forbid this, but it might be too late now.

> which adds constant perf overhead

That is really neglegible. Depending on how you implement it, it might boil down to a single assembly instruction and a single pointer stack space.

2021-05-06 07:14 UTC, Oberon00 commented on specification/trace/sdk.md
> +* `Resource` of the `Span` to be created.
We had this discussion with exporters already and I think the conclusion was that an Exporter must in general be prepared for each span to have a different resource, because the same exporter might be attached to different SpanProcessors and the same SpanProcessor to different TracerProviders with different resources. I think the same (minus the intermediate SpanProcessor) applies to the sampler.

I would have been all for adding a restriction to the spec to forbid this, but it might be too late now.

> which adds constant perf overhead

That is really neglegible. Depending on how you implement it, it might boil down to a single assembly instruction and a single pointer stack space.

2021-05-06 12:59 UTC, iNikem approved these changes

2021-05-10 23:01 UTC, bogdandrutu requested changes

2021-05-10 23:01 UTC, bogdandrutu commented on spec-compliance-matrix.md
> +| ShouldSample gets Resources and InstrumentationLibrary                                           |          |    |      |    |        |      |        |     |      |     |      |       |
I would like to be able to implement this differently. Maybe we can actually keep ShouldSample the same and apply the same stricture as "Tracer" for "Sampler":

* Have a "SamplerProvider" with a "getSampler(InstrumentationLibrary).
* Have a "SamplerProviderFactory" that has a "getSamplerProvider(Resource)"

The reason to do this is because then Sampler can be optimized to pre-compute things for Resource/InstrumentationLibrary.

Is this reasonable?

2021-05-10 23:06 UTC, bogdandrutu commented on spec-compliance-matrix.md
> +| ShouldSample gets Resources and InstrumentationLibrary                                           |          |    |      |    |        |      |        |     |      |     |      |       |
Also the need for Resource is very unclear since a Sampler is installed in a Provider which has immutable Resource, any filtering/sampling logic that applies to Resource can be evaluated before installing

2021-05-11 12:35 UTC, Oberon00 commented on spec-compliance-matrix.md
> +| ShouldSample gets Resources and InstrumentationLibrary                                           |          |    |      |    |        |      |        |     |      |     |      |       |
> Also the need for Resource is very unclear since a Sampler is installed in a Provider which has immutable Resource

This is the same concern that @yurishkuro had and I answered it at https://github.com/open-telemetry/opentelemetry-specification/pull/1658#discussion_r627143176

2021-05-11 12:42 UTC, Oberon00 commented on spec-compliance-matrix.md
> +| ShouldSample gets Resources and InstrumentationLibrary                                           |          |    |      |    |        |      |        |     |      |     |      |       |
That SamplerProviderFactory + SamplerProvider design sounds rather complex to me. If we are concerned about sampling performance we should start with #620 😃 Returning an AlwaysOff sampler for certain instrumentationlibraries from the SamplerProvider might be a usecase.

Regarding backwards compatibility, I don't see this as an advantage, as you can have the same backwards-compat behavior by adding a SamplerV2 interface as alternative to the current sampler.

I think it's a reasonable alternative, but I don't like it very much, as introducing two new classes seems more complex than two new parameters.

2021-05-12 16:03 UTC, bogdandrutu commented on specification/trace/sdk.md
> +* `Resource` of the `Span` to be created.
The exporter is very different in the way that it does not run on the critical path, hence the small overhead is negligible compare with this. I would say that indeed consistency would be good, but we need to be careful with the overhead in this case.

2021-05-12 16:05 UTC, bogdandrutu commented on spec-compliance-matrix.md
> +| ShouldSample gets Resources and InstrumentationLibrary                                           |          |    |      |    |        |      |        |     |      |     |      |       |
If we don't expose the Resource at all in the Sampler.ShouldSample, samplers that need resource will be forced to evaluate that at the beginning when available during construction of the Sdk provider. So I think we can at least do a good thing and not add the Resource, maybe just the Instrumentation Library since that is a smaller object.

2021-05-14 10:21 UTC, Oberon00 commented on specification/trace/sdk.md
> +* `Resource` of the `Span` to be created.
One more point: Currently, it should be fine in most language implementations to call GetTracer each time when creating a span. Some languages may even require this, as calling GetTracer in a static initializer or similar may be executed before the SDK is configured and yield you a no-op tracer. With this change, we would make GetTracer call a "plugin interface", so the call can become arbitrarily expensive. That cost would then be recovered because StartSpan is cheaper by that, but still, it would have some more implications.

2021-05-25 15:16 UTC, bogdandrutu commented
@Oberon00 let's split this into 2 PRs to allow progress:
1. that adds the InstrumentationLibrary which we've already agreed to support sampling by instrumentation library, then when we find a very good use-case for Resource we can discuss, before that point as pointed in the issue an implementation can be done anyway.
2. The second PR will be when we have good use-case for Resource and prove that the alternative does not work.

2021-06-02 05:58 UTC, iNikem commented
> @Oberon00 let's split this into 2 PRs to allow progress:
> 
> 1. that adds the InstrumentationLibrary which we've already agreed to support sampling by instrumentation library, then when we find a very good use-case for Resource we can discuss, before that point as pointed in the issue an implementation can be done anyway.
> 2. The second PR will be when we have good use-case for Resource and prove that the alternative does not work.

@Oberon00 Do you agree with this suggestion?

2021-08-10 14:04 UTC, Oberon00 commented on specification/trace/sdk.md
> +* `InstrumentationLibrary` (name and version) of the `Span` to be created.
@yurishkuro This was now merged without any opposition on #1850, so I'm resolving this.

2021-08-10 14:05 UTC, Oberon00 commented on spec-compliance-matrix.md
> +| ShouldSample gets Resources and InstrumentationLibrary                                           |          |    |      |    |        |      |        |     |      |     |      |       |
@bogdandrutu  We now went the simpler route in #1850, so I think we can do the same for Resources. Please re-open the conversation if you disagree.

2021-08-10 14:06 UTC, Oberon00 commented on specification/trace/sdk.md
> +* `Resource` of the `Span` to be created.
Backwards-compatibility is not more of an issue with Resources than with InstrumentationLibrary, which was merged in #1850.

2021-08-10 14:08 UTC, Oberon00 commented
I re-opened this PR since we are "breaking" compatibility anyway through #1850. @anuraaga said he had a use case for resources with the X-Ray sampler: https://github.com/open-telemetry/opentelemetry-specification/issues/1588#issuecomment-893245998

2021-08-11 08:39 UTC, anuraaga approved these changes
Thanks @Oberon00. I agree that there is no conceptual difference between InstrumentationLibrary and Resource in terms of this method signature. Also, there should be no real extra "cost" to adding two parameters to the method vs just one in a single release.

For reference, Resource is associated with a `TracerProvider`
> When used with distributed tracing, a resource can be associated with the TracerProvider when the TracerProvider is created. That association cannot be changed later. When associated with a TracerProvider, all Spans produced by any Tracer from the provider MUST be associated with this Resource.

And Sampler is part of TracerProvider

> Configuration (i.e., SpanProcessors, IdGenerator, SpanLimits and Sampler) MUST be managed solely by the TracerProvider and it MUST provide some way to configure all of them that are implemented in the SDK, at least when creating or initializing it.

I think this means it is the TracerProvider's job to provide the Resource information to the Sampler - it is the holder of all this configuration. And in the end, any alternative results in an awkward user experience

```java
Resource resource = createResource();
AwsXrayRemoteSampler sampler = AwsXrayRemoteSampler.create(resource);
TracerProvider tracerProvider = SdkTracerProvider.builder()
  .setResource(resource)
  // Passed resource above, why also pass to sampler? What if it's out of sync? etc
  .setSampler(sampler)
  .build();
```

2021-08-11 11:46 UTC, iNikem commented
> I think this means it is the TracerProvider's job to provide the Resource information to the Sampler

How exactly should this happen?

2021-08-11 11:48 UTC, Oberon00 commented
I think @anuraaga means that the tracerprovider (indirectly) calls ShouldSample with the resource as argument in the end.

2021-08-14 04:31 UTC, trask approved these changes

2021-08-16 08:00 UTC, Oberon00 commented
@bogdandrutu Can you please check if your "Request changes" still applies?

2021-08-17 15:09 UTC, arminru approved these changes

2021-08-17 15:38 UTC, jkwatson commented
I'm against this change. Anyone who wants to write a sampler that uses the Resource can provide a constructor (or whatever is language-equivalent) for that Sampler and it can use the Resource however it wants. I'd rather not add more stuff to the sampler API that we need, and I don't see how this is a necessary addition.

2021-09-01 23:06 UTC, jkwatson commented
> > Resource can provide a constructor (or whatever is language-equivalent) for that Sampler and it can use the Resource however it wants
> 
> I think this creates an awkward user experience - the SDK already has a resource registered, registering it again for the Sampler, but not for the export pipeline, adds some tedium and isn't symmetric. Given the way the APIs are structured, I'd expect Sampler and Exporter to act similarly (just use the Resource I passed into the SDK). This is particularly true given for many users they won't even create a Resource - some sort of autoconfiguration would set it up. It's unnecessary to expose this autoconfigured Resource to the user just to register a Sampler.

I don't deny this might be a bit awkward, but I also know that users can use this technique today, with no spec changes necessary to implement it. Do we have more than one use-case for this?

2021-09-02 02:52 UTC, anuraaga commented
> Do we have more than one use-case for this?

Hmm - it's hard to word it, but I think that there indeed may only be one precise use case. It is the concept of "sampling by attribute" - the attributes for a span are both what's set in its builder and its Resource I think. So we could never consider attribute-based sampling complete without the Resource. We currently have a PoC of attribute-based sampling for Java

https://github.com/open-telemetry/opentelemetry-java-contrib/pull/70

which I would suspect to be spec'd in some form some day. Currently this sampler can't look at Resource but it seems like it should be able to.

The attribute sampler would likely be a primitive type used by more complex sampling - does each of them count as a use case? Then we'd probably have several :P Providing the primitive itself (the ability to sample on a span's resource attributes) seems fundamentally important and worth making less awkward for the user. I don't know if I'd want to add a API addition twice for it, which is why hoping to bundle this into the same release as the InstrumentationLibrary update - in that case, it seems like a minor addition with a good gain in functionality.

2021-09-03 06:42 UTC, Oberon00 commented
I think a good argument just came to my mind:
If we pass the resource in the sampler constructor, we close the door to allowing multiple different resources per TracerProvider. Allowing different resources e.g. per Tracer is something that has been discussed in the past e.g. in #579 and related discussions in #335, #734. Passing the resource in the constructor may also decrease implementation flexibility for post-creation resources / resource attributes (#1298).

2021-09-07 19:39 UTC, iNikem commented
Just raising my voice that we definitely should not close the door for #1298

2021-09-15 08:27 UTC, Oberon00 commented
@bogdandrutu As you still have "Changes Requested", what is your take on this?

2021-09-16 12:40 UTC, carlosalberto commented
> I'm against this change. Anyone who wants to write a sampler that uses the Resource can provide a constructor (or whatever is language-equivalent) for that Sampler and it can use the Resource however it wants. I'd rather not add more stuff to the sampler API that we need, and I don't see how this is a necessary addition.

This (written by @jkwatson ) was the _general_ feeling during a SIG call a few weeks ago (hence the comment), namely: do not add stuff to the API at all, unless absolutely necessary. 

@bogdandrutu would you mind answering the latest's answers on this topic?

2021-09-16 13:00 UTC, Oberon00 commented
I agree that adding stuff to the API (the SDK's plugin API in this case) should be minimized generally. But one goal behind this is IMHO keeping the implementation flexible, allowing later changes, by not exposing too many internals.
But in this case, by *not* providing the Resource, we are forcing sampler developers that need the resource to make the assumption that the resource is something static that will always be the same for all spans that the sampler processes.
Crucially, this *contradicts* the fact that the readable span ("SpanData") has the Resource as a public property, which would allow the assumption that different Spans provided to the same SpanProcessor (exporter) can have different resources.
In effect, exporters need to go through the trouble of preparing for distinct resource objects across a batch or different batches, while samplers (configured on the same level as spanprocessors) have to be coded with the limitation that all spans have the same resource. It follows, that at least one of the following is currently broken:
* A sampler that needs a Resource
* Different resources within the same TracerProvider (see https://github.com/open-telemetry/opentelemetry-specification/pull/1658#issuecomment-912297271)
* Reusing the same sampler instance across different TracerProviders

I think the last one doesn't matter much (though we seem to support it for spanprocessors/exporters). But the first and second one are a problem.

2021-09-16 13:30 UTC, bogdandrutu commented
@Oberon00 I think exposing the Resource in the SpanData was a mistake that hurts a lot the performance having to do the mapping for OTLP. So I would not repeat that mistake, also the reasoning was because SpanProcessor can be shared across multiple TraceProviders which in practice (never seen this case) could have been avoided and share exporter if needed.

So I think as explained before unless we prove with clear real code example that this does not work we should not do it.

2021-09-16 13:34 UTC, bogdandrutu commented
Also the example and the motivation that an object is shared between multiple instances is not a good reason to add unnecessary APIs that will limit performance, see https://github.com/open-telemetry/opentelemetry-specification/pull/1658#pullrequestreview-727210068

2021-09-16 13:41 UTC, bogdandrutu commented
> Hmm - it's hard to word it, but I think that there indeed may only be one precise use case. It is the concept of "sampling by attribute" - the attributes for a span are both what's set in its builder and its Resource I think. So we could never consider attribute-based sampling complete without the Resource. We currently have a PoC of attribute-based sampling for Java

> open-telemetry/opentelemetry-java-contrib#70

> which I would suspect to be spec'd in some form some day. Currently this sampler can't look at Resource but it seems like it should be able to.

@anuraaga please give me a real example when sampling by resource attributes is useful in practice.

I've seen extremely limited number of Applications with more than one Provider (personally 0, but let's say they exists) and usually in all these cases I expect that the attributes that are different in the Resource to be the "service" (or at least that was the motivation before to support multiple Providers) and if that is the case you can simply just ignore the resource attributes and set different Samplers per service instance of the Provider.

2021-09-16 14:38 UTC, Oberon00 commented
> I think exposing the Resource in the SpanData was a mistake that hurts a lot the performance having to do the mapping for OTLP. So I would not repeat that mistake, also the reasoning was because SpanProcessor can be shared across multiple TraceProviders which in practice (never seen this case) could have been avoided and share exporter if needed.

I agree with that actually. I think exporters and span processors and samplers should only ever used with a single TracerProvider (span processor). There is also #508 open which would change how resources are passed (probably we need to close that one as its too late).

But now we have the Resource in the SpanData and I feel we already have reached consensus that #1298 is worthwhile to implement. If we pass the resource to the sampler, we can just start passing the new resource with the new attributes.
If the resource is given to the sampler outside the SDK's control, we now need to have a callback like OnResourceChanged. And the sampler developers would need to implement that callback to update their resource. Probably the callback could also fire at initial resource creation... Then we have the same features for samplers that this PR would provide plus much more flexibility but also some complexity.

@anuraaga What do you think of adding an OnResourceChanged callback once we implement #1298? Would that improve usability?

2021-09-16 15:18 UTC, bogdandrutu commented
@Oberon00 if we were to do a breaking change (since this one is) I would suggest to better investigate the path where all of these components are associated with only one Resource and maybe have a hook when the "Resource" changes to support late Resource resolution :)

This is my thought, I would better invest my time in doing something that we know is more performant and can improve things than adding more "simple" but not optimal changes.

2021-09-16 15:22 UTC, Oberon00 commented
> if we were to do a breaking change (since this one is)

We have already "broken" this interface for 1.7 because we added the InstrumentationLibrary, which is why we are discussing this PR now.

2021-09-16 21:24 UTC, jmacd commented
Could we resolve this PR with an additional statement that language SIGs MAY provide optimized Sampler interfaces that bind certain arguments such as Resource and InstrumentationLibrary when they are known to be constant? That way we allow this PR in but @bogdandrutu's reservations are met, and we don't block #1298 (because I wrote "when they are known to be constant", any optimized API the language SIGs create will have to contend with 1298 when the time comes).

2021-09-17 08:03 UTC, Oberon00 commented
How could that optimized interface look like?

2021-09-17 11:20 UTC, jmacd commented
There is already language in the SDK specification that offers SDKs a lot of freedom in how TraceID and SpanIDs are generated, I'm referring to "When asked to create a Span, the SDK MUST act as if doing the following in order:"

Step 2 is "Query the `Sampler`'s `ShouldSample` method".

I imagine the specification just saying what the act of calling `ShouldSample` does, then we shouldn't have to specify any alternate APIs. The optimized Sampler API MUST act the same as the non-optimized Sampler API, that's all.

In Go, `ShouldSample` takes a struct with some possibly-constant fields. The optimized Sampler API would provide a factory method for binding constant fields which returns the former Sampler implementation.

2021-09-17 12:18 UTC, Oberon00 commented
I think @bogdandrutu has switched arguments over the course of the review: Originally, the suggestion was to add a more complex family of interfaces in order to gain some performance. Now, the main issue with this PR seems to be that we should keep the API minimal and not add unneeded things.
I think adding more implementation options would actually be worse in that regard.

2021-09-17 15:02 UTC, jmacd commented
I believe the underlying problem is that we do not have a data model for Resources.

2021-09-17 16:00 UTC, Oberon00 commented
> I believe the underlying problem is that we do not have a data model for Resources.

Hmm, we do have a data model for the resources themselves IMHO, but the current solution of how they are connected to the actual telemetry is unsatisfying. E.g. you pass it to a tracer provider and separately to a meter?

2021-09-17 19:10 UTC, jmacd commented
> > I believe the underlying problem is that we do not have a data model for Resources.

> Hmm, we do have a data model for the resources themselves IMHO

I apologize, I over-stated that. I meant to say the data model we have is not strong enough, but that's a topic we should continue discussing in #1298. The resource SDK spec says:

```
A Resource is an immutable representation of the entity producing telemetry as Attributes.
```

We haven't made any requirements about the "entity" described there, and it means everyone has a different opinion about what **this** PR means.

> the current solution of how they are connected to the actual telemetry is unsatisfying

Yes. Also, as with #1298, the resource data model is not strong enough to accommodate Prometheus and OpenMetrics (https://github.com/open-telemetry/opentelemetry-specification/issues/1298#issuecomment-775749864).

In #1588 you wrote:

> Suppressing unwanted spans depending on the instrumentation library name 

Let me suggest that the problem is you're trying to use a Sampler API to suppress Spans. When DynaTrace originally introduced the Named Tracer and instrumentation library concept, it was stated that an SDK may decide to suppress spans based on their library. I.e., it's the `Tracer`'s responsibility to suppress spans.

I've made statements about how treating Sampler as a means of filtering spans is causing confusion which is an obstacle for probability sampling here: https://github.com/open-telemetry/opentelemetry-specification/issues/1844#issuecomment-920216604

If your goal is to suppress spans based on instrumentation library, that should happen before the Sampler is called. If your goal is to suppress spans based on resource, you can likewise do that before the Sampler is called. If your goal is to setup sampling rules that are applied on a per-instrumentation library basis, we should be specifying a View Configuration mechanism for spans that will configure a per-library Sampler (for example).

Based on this above reasoning, I'm on the fence about whether InstrumentationLibrary belongs in the sampler API at all. The reason InstrumentationLibrary is different than Resource, and why it was easier to accept, is that InstrumentationLibrary is at least a variable across the "entity producing telemetry", whereas Resource is not.

2021-09-17 19:11 UTC, jmacd reviewed
I'm removing my approval, now that I've understood the motivation better. If the goal is to suppress spans based on Resource (or Instrumentation Library), better to do that before the Sampler is called.

2021-09-17 21:18 UTC, Oberon00 commented
> If your goal is to suppress span ... better to do that before the Sampler is called.

That's not really possible, the sampler is the only hook that is exposed for that purpose. Replacing the TracerProvider with a custom implementation is usually not practical (one reason being that Resource APIs are only defined in the default SDK).

2021-09-18 01:22 UTC, anuraaga commented
> If the goal is to suppress spans based on Resource (or Instrumentation Library), better to do that before the Sampler is called.

At least for me the goal is to change sample rate based on service name, or k8s pod name, or hostname, type of resource attributes. Often this is something like seeing metrics report failure on one service and wanting to crank up the sampling rate for that service temporarily.

This works when sampling configuration is managed centrally, for example with X-ray remote sampling, or even if it just reads a file from etcd.

So attributes in the resource seem useful to have available when configuring sampling. I guess instrumentation library may be more geared to suppression, not sure but not resource.

2021-09-18 08:17 UTC, iNikem commented
> > If your goal is to suppress span ... better to do that before the Sampler is called.
> 
> That's not really possible, the sampler is the only hook that is exposed for that purpose. Replacing the TracerProvider with a custom implementation is usually not practical (one reason being that Resource APIs are only defined in the "official" SDK).

@jmacd I have to agree with @Oberon00 here: where else can we suppress spans (and how) if not by calling Sampler and returning `SamplingDecision.DROP`?

2021-09-20 23:22 UTC, anuraaga commented
> What about instead ask the remote service to tell your config and pass the Resource then?

This seems like a nice design, especially for an OTel configuration service API. AFAIK current remote sampling APIs can't accept a Resource so this approach doesn't seem to support them well. And I think for medium size teams with a dozen or so microservices on on-prem hosts, a single file pushed through Ansible or such seems reasonable - I've done similar for experiment configs before, not specifically sampling. I hope OTel doesn't just assume these are bad use cases.

A span has many attributes, some of them happen to be on the span, others on the Resource. It seems inconsistent to only provide one of these when sampling though.

2021-09-22 10:36 UTC, Oberon00 commented
I will close this PR if/when #1942 is merged.

2021-09-22 14:27 UTC, Oberon00 commented
Closing due to merge of #1942.

2021-09-22 14:27 UTC, closed without merging

2021-09-22 14:29 UTC, jmacd commented
> It seems inconsistent to only provide one of these when sampling though

We've made an argument that performance suffers when every Sampler invocation considers the resource or instrumentation library. 

It sounds like you're asking for a standard mechanism. In the Go SDK, what you're asking for is two new interfaces:

```
type SDKSampler interface {
  SamplerForResource(resource.Resource) InstrumentationLibrarySampler
}

type InstrumentationLibrarySampler interface {
  SamplerForLibrary(instrumentation.Library) Sampler
}
```

Since all of the machinery implied by these two new interfaces is part of setting up and configuring an SDK, it falls outside the scope of OTel's current specification. You could build these and use them, and have what you want. 

Should OpenTelemetry offer these interfaces? Users want configurable tracer SDKs, so I think the answer is yes.

For your simple application of a file containing resource and library parameters for sampling configuration, you can: 
(1) parse the intended resource attribute to sampler settings map
(2) inspect the resource of the current SDK
(3) apply all resource attributes to the predicates used in the mapping
(4) some of the sampler settings mapped in your resource file are unreachable, their predicates are already false if resources do not match
(5) configure only the non-false predicates as the `SDKSampler`

the `SamplerForLibrary` method does roughly the same, evaluate any remaining predicates with the instrumentation library details, now the returned `Sampler` does exactly what you want and uses the current API -- the decisions about instrumentation library and resource are pre-bound by the time a Span arrives, and no further computation has to be done for any of the resource or library predicates.