Add `OTEL_SERVICE_NAME` environment variable
open-telemetry/opentelemetry-specification pull request #1677
Opened 2021-05-07 10:32 UTC by iNikem

Closes #709

## Changes

Add `OTEL_SERVICE_NAME` environment variable to SDK configuration

2021-05-07 11:13 UTC, pellared approved these changes

2021-05-07 12:35 UTC, arminru reviewed
@SergeyKanzhelev You seemed to have a strong opinion on #709, so please take a look at this proposal.

2021-05-07 12:35 UTC, arminru commented on specification/sdk-environment-variables.md
> +| OTEL_SERVICE_NAME        | Value of the [`service.name`](./resource/semantic_conventions/README.md#service) resource attribute | | If both this and `OTEL_RESOURCE_ATTRIBUTES` are provided then `OTE
I think the fact that both are merged into `OTEL_RESOURCE_ATTRIBUTES` is an implementation detail that we don't have to expose to users.
More important would be to specify which one is taking precedence if `service.name` is also provided in `OTEL_RESOURCE_ATTRIBUTES`.

2021-05-07 12:35 UTC, arminru commented on specification/sdk-environment-variables.md
> +| OTEL_SERVICE_NAME        | Value of the [`service.name`](./resource/semantic_conventions/README.md#service) resource attribute | | If both this and `OTEL_RESOURCE_ATTRIBUTES` are provided then `OTE
The description "_Value of the [`service.name`](./resource/semantic_conventions/README.md#service) resource attribute_" could be interpreted as "_you have to specify the same value here_" or even "_the value defined for `service.name` is exposed in this env var_".

How about this?
> Defines a default value for the [`service.name`](./resource/semantic_conventions/README.md#service) resource attribute

2021-05-07 12:35 UTC, arminru commented on specification/sdk-environment-variables.md
> +| OTEL_SERVICE_NAME        | Value of the [`service.name`](./resource/semantic_conventions/README.md#service) resource attribute | | If both this and `OTEL_RESOURCE_ATTRIBUTES` are provided then `OTE
```suggestion
| OTEL_SERVICE_NAME        | Value of the [`service.name`](./resource/semantic_conventions/README.md#service) resource attribute | | If both this and `OTEL_RESOURCE_ATTRIBUTES` are provided then `OTEL_SERVICE_NAME` is [merged into](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/resource/sdk.md#merge) `OTEL_RESOURCE_ATTRIBUTES` |
```

2021-05-07 12:41 UTC, pellared commented on specification/sdk-environment-variables.md
> +| OTEL_SERVICE_NAME        | Value of the [`service.name`](./resource/semantic_conventions/README.md#service) resource attribute | | If both this and `OTEL_RESOURCE_ATTRIBUTES` are provided then `OTE
For me "merged into" means that `OTEL_SERVICE_NAME` overrides the value from `OTEL_RESOURCE_ATTRIBUTES`.

2021-05-07 12:42 UTC, iNikem commented on specification/sdk-environment-variables.md
> +| OTEL_SERVICE_NAME        | Value of the [`service.name`](./resource/semantic_conventions/README.md#service) resource attribute | | If both this and `OTEL_RESOURCE_ATTRIBUTES` are provided then `OTE
I agree with the assessment, but I am not sure about "default value". I usually interpret "default" as "value used unless user provided their opinion". Here is exactly user's opinion :) Maybe just

> Sets the value of `service.name` resource attribute?

2021-05-07 12:43 UTC, iNikem commented on specification/sdk-environment-variables.md
> +| OTEL_SERVICE_NAME        | Value of the [`service.name`](./resource/semantic_conventions/README.md#service) resource attribute | | If both this and `OTEL_RESOURCE_ATTRIBUTES` are provided then `OTE
I can do it this way, sure :)

2021-05-07 13:06 UTC, arminru commented on specification/sdk-environment-variables.md
> +| OTEL_SERVICE_NAME        | Value of the [`service.name`](./resource/semantic_conventions/README.md#service) resource attribute | | If both this and `OTEL_RESOURCE_ATTRIBUTES` are provided then `OTE
The "default" wording would stress that values provided by application/instrumentation in code take precedence over the env var but this is already stated in https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/resource/sdk.md#specifying-resource-information-via-an-environment-variable which is linked in the line above anyway. Your proposal sounds good as well!

2021-05-07 13:09 UTC, arminru commented on specification/sdk-environment-variables.md
> +| OTEL_SERVICE_NAME        | Sets the value of the [`service.name`](./resource/semantic_conventions/README.md#service) resource attribute | | If `service.name` is also provided in `OTEL_RESOURCE_ATTR
```suggestion
| OTEL_SERVICE_NAME        | Sets the value of the [`service.name`](./resource/semantic_conventions/README.md#service) resource attribute | | If `service.name` is also provided in `OTEL_RESOURCE_ATTRIBUTES`, then `OTEL_SERVICE_NAME` takes precedence. |
```

2021-05-07 13:32 UTC, owais approved these changes

2021-05-07 15:30 UTC, iNikem commented on specification/sdk-environment-variables.md
> +| OTEL_SERVICE_NAME        | Sets the value of the [`service.name`](./resource/semantic_conventions/README.md#service) resource attribute | | If `service.name` is also provided in `OTEL_RESOURCE_ATTR
I usually prefer to keep PR scope small, if possible. This PR solves one specific issue. I am happy to file a follow-up one, if you feel this is needed :)

2021-05-07 15:31 UTC, jkwatson approved these changes

2021-05-07 15:42 UTC, MrAlias approved these changes

2021-05-07 16:03 UTC, SergeyKanzhelev commented on specification/sdk-environment-variables.md
> +| OTEL_SERVICE_NAME        | Sets the value of the [`service.name`](./resource/semantic_conventions/README.md#service) resource attribute | | If `service.name` is also provided in `OTEL_RESOURCE_ATTR
somewhere needs to be a note on what wins - environment variable or code.

2021-05-07 16:04 UTC, SergeyKanzhelev requested changes
I am ok with the suggestion, but before merging, let's clarify whether environment variable should take precedence over the value set in code.

2021-05-07 16:16 UTC, SergeyKanzhelev approved these changes

2021-05-07 16:16 UTC, SergeyKanzhelev commented on specification/sdk-environment-variables.md
> +| OTEL_SERVICE_NAME        | Sets the value of the [`service.name`](./resource/semantic_conventions/README.md#service) resource attribute | | If `service.name` is also provided in `OTEL_RESOURCE_ATTR
yep, sorry

2021-05-07 20:22 UTC, yurishkuro approved these changes

2021-05-08 03:10 UTC, anuraaga approved these changes

2021-05-10 22:16 UTC, bogdandrutu commented on CHANGELOG.md
> +- Add `OTEL_SERVICE_NAME` environment variable. ([#1677](https://github.com/open-telemetry/opentelemetry-specification/pull/1677))
I would add NAMESPACE and INSTANCE as well. Service name should not be treated special than the others.

2021-05-10 22:17 UTC, bogdandrutu submitted a review, later dismissed
Question that is not answer:

Why service name is treated differently than any other resource attribute?

2021-05-11 11:52 UTC, iNikem commented on CHANGELOG.md
> +- Add `OTEL_SERVICE_NAME` environment variable. ([#1677](https://github.com/open-telemetry/opentelemetry-specification/pull/1677))
I usually prefer to keep PR scope small, if possible. This PR solves one specific issue. I am happy to file a follow-up one, if you feel this is needed :)

2021-05-11 11:56 UTC, iNikem commented
> Question that is not answer:
> 
> Why service name is treated differently than any other resource attribute?

1. It is the only de-facto "required" resource attribute
2. The majority of vendors already have similar variable (https://github.com/open-telemetry/opentelemetry-specification/issues/709#issuecomment-813260663), so this is what end-users already expect
3. This PR does not preclude any other PR which adds support for other resource attributes.

2021-05-11 11:59 UTC, arminru commented on specification/sdk-environment-variables.md
> +| OTEL_SERVICE_NAME        | Sets the value of the [`service.name`](./resource/semantic_conventions/README.md#service) resource attribute | | If `service.name` is also provided in `OTEL_RESOURCE_ATTR
That's reasonable. If we add it, it would ideally be in the same spec version, however, so SDK maintainers/implementers can tackle this tightly coupled feature at once. The next release is scheduled for early June, so we should be good here, as the follow-up should be as uncontroversial as this PR.

2021-05-14 07:58 UTC, iNikem commented
@bogdandrutu as discussed during spec SIG meeting, I tried to stress the significance of this specific attribute. Please check my changes in `README.md`

2021-05-14 08:05 UTC, Oberon00 approved these changes

2021-05-14 08:05 UTC, Oberon00 commented on CHANGELOG.md
> +- Add `OTEL_SERVICE_NAME` environment variable. ([#1677](https://github.com/open-telemetry/opentelemetry-specification/pull/1677))
I have never heard of anyone using namespace (but maybe it just works so well that there are no questions?). instance.id has is currently IMHO too vaguely defined to be useful, as discussed in #1034. So the service name is IMHO definitely the most useful one.

2021-05-14 08:06 UTC, Oberon00 commented on specification/sdk-environment-variables.md
> +| OTEL_SERVICE_NAME        | Sets the value of the [`service.name`](./resource/semantic_conventions/README.md#service) resource attribute | | If `service.name` is also provided in `OTEL_RESOURCE_ATTR
Same as https://github.com/open-telemetry/opentelemetry-specification/pull/1677#discussion_r629718065: I don't think the service version is used often enough to warrant it's own attribute. We did receive user requests for service.name AFAIK, but not for any others.

2021-05-14 08:07 UTC, Oberon00 commented on CHANGELOG.md
> +- Add `OTEL_SERVICE_NAME` environment variable. ([#1677](https://github.com/open-telemetry/opentelemetry-specification/pull/1677))
(If exporter specs are updated to include service.namespace in their reported service, which maybe they should, then adding a special envvar for service.namespace might make sense)

2021-05-17 12:52 UTC, arminru commented on specification/resource/semantic_conventions/README.md
> +Given their significance some resource attributes receive a special treatment as described below.
Nit: This sounds quite colloquial (at least for me as a non-native speaker). How about this?
```suggestion
Given their significance some resource attributes are treated specifically as described below.
```

2021-05-17 14:20 UTC, carlosalberto commented
Ping @bogdandrutu

2021-05-18 15:44 UTC, bogdandrutu commented on CHANGELOG.md
> +- Add `OTEL_SERVICE_NAME` environment variable. ([#1677](https://github.com/open-telemetry/opentelemetry-specification/pull/1677))
> If exporter specs are updated to include service.namespace in their reported service, which maybe they should, then adding a special envvar for service.namespace might make sense

I think the "service name" as defined right now is unique within a namespace, and the fact that Jaeger/Zipkin don't have this concept made us use just "service name" which is wrong. 

@Oberon00 I agree that exporters that only have a "service name" concept should use actually "{service.namespace}/{service.name" as the name.

2021-05-18 15:51 UTC, bogdandrutu commented on CHANGELOG.md
> +- Add `OTEL_SERVICE_NAME` environment variable. ([#1677](https://github.com/open-telemetry/opentelemetry-specification/pull/1677))
https://github.com/open-telemetry/opentelemetry-specification/pull/1710

2021-05-18 15:58 UTC, SergeyKanzhelev commented on CHANGELOG.md
> +- Add `OTEL_SERVICE_NAME` environment variable. ([#1677](https://github.com/open-telemetry/opentelemetry-specification/pull/1677))
https://github.com/open-telemetry/opentelemetry-specification/blob/d001d5d25ea11a28bd4c4ec2652e2db1a41fc064/specification/trace/sdk_exporters/zipkin.md#:~:text=note%2C%20the%20attribute%20service.namespace%20must%20not%20be%20used%20for%20the%20zipkin%20service%20name%20and%20should%20be%20sent%20as%20a%20zipkin%20tag. 

> Note, the attribute service.namespace MUST NOT be used for the Zipkin service name and should be sent as a Zipkin tag.

https://github.com/open-telemetry/opentelemetry-specification/blob/b46bcab5fb709381f1fd52096a19541370c7d1b3/specification/resource/semantic_conventions/README.md#:~:text=Note,same%20string

> Note: service.namespace and service.name are not intended to be concatenated for the purpose of forming a single globally unique name for the service. For example the following 2 sets of attributes actually describe 2 different services (despite the fact that the concatenation would result in the same string):

2021-05-18 15:59 UTC, SergeyKanzhelev commented on CHANGELOG.md
> +- Add `OTEL_SERVICE_NAME` environment variable. ([#1677](https://github.com/open-telemetry/opentelemetry-specification/pull/1677))
We can change that, but it was intentionally not suppose to be concatenated to avoid the need to parse the namespace out of the name

2021-05-18 16:06 UTC, bogdandrutu commented on CHANGELOG.md
> +- Add `OTEL_SERVICE_NAME` environment variable. ([#1677](https://github.com/open-telemetry/opentelemetry-specification/pull/1677))
I do understand that, and I've just added an open question to my PR. I think in case of one value string like Jaeger/Zipkin we have to guarantee the uniqueness somehow, otherwise we will have conflicts. For example 2 service names named "kafka" run by 2 teams/namespaces "a" and "b" will be seen as same service by these backends.

2021-05-18 16:25 UTC, SergeyKanzhelev commented on CHANGELOG.md
> +- Add `OTEL_SERVICE_NAME` environment variable. ([#1677](https://github.com/open-telemetry/opentelemetry-specification/pull/1677))
happy to change that. Given that namespace is empty in many cases now it is not such a breaking change

2021-05-18 16:48 UTC, iNikem commented on CHANGELOG.md
> +- Add `OTEL_SERVICE_NAME` environment variable. ([#1677](https://github.com/open-telemetry/opentelemetry-specification/pull/1677))
Does this discussion/related PR block this PR from merging?

2021-05-20 05:01 UTC, trask approved these changes

2021-05-20 12:24 UTC, carlosalberto commented
@bogdandrutu  ;)

2021-05-23 07:18 UTC, iNikem commented
@open-telemetry/technical-committee Anybody feeling confident enough to merge this?

2021-05-24 13:52 UTC, carlosalberto commented
@bogdandrutu Thanks for going on with the compromise, really appreciated. Merging (we will see in the long run how things unfold! ;) )

2021-05-24 13:54 UTC, merged