Add semantic conventions for k8s tagger
open-telemetry/opentelemetry-specification pull request #1723
Opened 2021-05-26 00:02 UTC by chaitanyaphalak

Changes:
Adds k8s.namespace.uid k8s.namespace.start_time k8s.pod.start_time from k8s-tagger to semantic conventions
Related issues https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/3384

2021-05-26 17:25 UTC, chaitanyaphalak commented
@arminru running make table-generation
removed all the entries I made ?
Am I doing something wrong?

2021-05-26 22:40 UTC, chaitanyaphalak commented
Also will these conventions be available at https://github.com/open-telemetry/opentelemetry-collector/blob/main/translator/conventions/opentelemetry.go for using in code after the PR is merged or after a release?

2021-05-26 23:00 UTC, tigrannajaryan commented
> Also will these conventions be available at https://github.com/open-telemetry/opentelemetry-collector/blob/main/translator/conventions/opentelemetry.go for using in code after the PR is merged or after a release?

You will need add the corresponding convention in that go file. No need to wait for the release, add it in Collector as soon as this PR is merged.

2021-05-27 07:54 UTC, arminru commented on semantic_conventions/resource/k8s.yaml
> +        examples: [ '2021-05-25 23:36:44 +0000 UTC' ]
Please specify the expected time format and ideally mention in a `note:` where this value can be retrieved from.
From https://kubernetes.io/docs/tasks/debug-application-cluster/debug-application-introspection/, for example, it doesn't look as if the time zone was present in the output of `kubectl describe`.

2021-06-01 15:05 UTC, pmm-sumo approved these changes

2021-06-01 15:11 UTC, pmm-sumo commented on specification/resource/semantic_conventions/k8s.md
> +| `k8s.namespace.start_time` | string | The creation time of the namespace. | `2021-05-13 17:23:11 +0000 UTC` | No |
In other areas (e.g. [faas.document.time](https://github.com/open-telemetry/opentelemetry-specification/blob/b46bcab5fb709381f1fd52096a19541370c7d1b3/specification/trace/semantic_conventions/faas.md#datasource)) the format is specifically mentioned as ISO 8601, I think we should follow this approach here?

2021-06-01 15:13 UTC, pmm-sumo requested changes
I think the timestamp format needs to be explicitly stated

2021-06-01 20:56 UTC, chaitanyaphalak commented
@arminru @pmm-sumo i checked the docs for the field in k8s architecture docs and the description for the timestamp is "a string representing an RFC 3339 date of the date and time an object was created" 
reference - check creationTimestamp in https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#metadata
I can add this as a doc

2021-06-02 14:16 UTC, tigrannajaryan commented
> @arminru @pmm-sumo i checked the docs for the field in k8s architecture docs and the description for the timestamp is "a string representing an RFC 3339 date of the date and time an object was created"
> reference - check creationTimestamp in https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#metadata
> I can add this as a doc

We should be consistent in Otel semantic conventions. Timestamps should follow the same format for all Otel semantic conventions. This simplifies handling of timestamps by consumers of telemetry (backends). Since other conventions already use ISO 8601 let's go with that.
Kubernetes collector should convert from whatever format it sees in Kubernetes to ISO 8601.

2021-06-10 15:09 UTC, tigrannajaryan commented
> > @arminru @pmm-sumo i checked the docs for the field in k8s architecture docs and the description for the timestamp is "a string representing an RFC 3339 date of the date and time an object was created"
> > reference - check creationTimestamp in https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#metadata
> > I can add this as a doc
> 
> We should be consistent in Otel semantic conventions. Timestamps should follow the same format for all Otel semantic conventions. This simplifies handling of timestamps by consumers of telemetry (backends). Since other conventions already use ISO 8601 let's go with that.
> Kubernetes collector should convert from whatever format it sees in Kubernetes to ISO 8601.

@chaitanyaphalak do you plan to continue working on this?

2021-06-10 20:55 UTC, tigrannajaryan commented
> @tigrannajaryan I am currently focusing on getting [open-telemetry/opentelemetry-collector-contrib#3384](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/3384) merged as we need it urgently. For this spec PR, i can change the spec to specify ISO 8601 for timestamps. Will i have to make changes to k8s-tagger implementation to convert the timestamps to ISO 8601 as a followup to this one? If that is the case, I can discuss with the team if we want to continue the PR.

Yes, the Collector must follow spec. It should not be complicate to update your Collector code to format the timestamps in a different way, right? So you can continue and merge your Collector PR and then fix the format in another PR once the specification is approved.

2021-06-18 15:04 UTC, chaitanyaphalak commented
Its not stale bot :)

2021-06-18 16:27 UTC, SergeyKanzhelev requested changes
Need clarifications. Also please find more people interested in reviewing this proposal to confirm that this metadata is useful

2021-06-18 16:27 UTC, SergeyKanzhelev commented on semantic_conventions/resource/k8s.yaml
> +          This is a string representing an RFC 3339 date of the date and time the namespace object was created.
```suggestion
          This is a string representing of date and time the namespace object was created, formatted as RFC 3339.
```

2021-06-18 16:27 UTC, SergeyKanzhelev commented on semantic_conventions/resource/k8s.yaml
> +          This is a string representing an RFC 3339 date of the date and time the pod object was created.
```suggestion
          This is a string representing a date and time the pod object was created formatted as RFC 3339.
```

2021-06-18 16:27 UTC, SergeyKanzhelev commented on semantic_conventions/resource/k8s.yaml
> +      - id: start_time
why `start_time` and not a `creation_time`?

2021-06-18 16:27 UTC, SergeyKanzhelev commented on semantic_conventions/resource/k8s.yaml
> +        examples: [ '2021-05-25 23:36:44' ]
why no timezone indication? `Z` at the end?

2021-06-18 16:27 UTC, SergeyKanzhelev commented on semantic_conventions/resource/k8s.yaml
> +          The creation time of the Pod.
please clarify whether it's when pod is created or scheduled

2021-06-18 16:27 UTC, SergeyKanzhelev commented on semantic_conventions/resource/k8s.yaml
> +      - id: start_time
is start_time a good name here? Is it when Pod has actually started running?

2021-06-18 16:27 UTC, SergeyKanzhelev commented on semantic_conventions/resource/k8s.yaml
> +        examples: [ '2021-05-13 17:23:11' ]
timezone?

2021-06-18 16:27 UTC, SergeyKanzhelev commented on semantic_conventions/resource/k8s.yaml
> +      - id: start_time
typically namestpaces are quite stable and not being re-created often. What information the creation time carries in these cases? What scenarios it is helpful? Wouldn't it be better for end users to send creation time once on namespace creation or something?

2021-06-22 16:04 UTC, tigrannajaryan commented on specification/resource/semantic_conventions/k8s.md
> +| `k8s.namespace.start_time` | string | The creation time of the namespace. | `2021-05-13 17:23:11 +0000 UTC` | No |
This does not seem to be resolved. The document still says RFC 3339. Let's make sure we are consistent use ISO 8601 everywhere for date/time.

2021-07-08 15:50 UTC, tigrannajaryan commented
@chaitanyaphalak can you address/resolve the comments?

2021-07-19 20:43 UTC, closed without merging