Clarify some details about span kind and the meanings of the values.
open-telemetry/opentelemetry-specification pull request #1738
Opened 2021-06-01 20:00 UTC by jkwatson

Fixes #1360

## Changes
Provides some additional clarity around Span.Kind and the meanings of the various values.

2021-06-01 20:23 UTC, yurishkuro approved these changes

2021-06-01 22:05 UTC, carlosalberto approved these changes

2021-06-02 02:29 UTC, reyang approved these changes

2021-06-02 06:05 UTC, iNikem requested changes
I am not sure that these changes resolved #1360 completely.

Also, if the goal of these changes is to allow nested CLIENT spans, then I am against it :) For a very specific reason: if we have several CLIENT spans during one remote call, which of those spans should be propagated?

2021-06-02 06:05 UTC, iNikem commented on specification/trace/api.md
> +the span is logically a remote child or parent, from the point of view
In this section you say both "remote child" and "span with a remote parent". I am afraid "remote child" will be somewhat confusing term. Or at least we have to explicitly define what is "remote child".

2021-06-02 15:30 UTC, jkwatson commented
> I am not sure that these changes resolved #1360 completely.
> 
> Also, if the goal of these changes is to allow nested CLIENT spans, then I am against it :) For a very specific reason: if we have several CLIENT spans during one remote call, which of those spans should be propagated?

I think it's very simple: the last one to touch the headers is the one that is propagated. Is there more complication that I'm not considering?

2021-06-02 15:45 UTC, iNikem commented
I removed my objection after offline discussion with @jkwatson

2021-06-03 05:12 UTC, trask commented
I agree it's needed to relax this constraint on nesting. I'm wondering if there's anything we can do to make it easier on backends that use CLIENT/SERVER and PRODUCER/CONSUMER spans to draw service maps, e.g. we had this discussion in Java a while ago before we started suppressing nested CLIENT spans: https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/440

2021-06-05 11:02 UTC, carlosalberto commented
Let's merge this after the 1.4 release as we ha enough approvals.

2021-06-08 13:55 UTC, merged