Update instrument names
open-telemetry/opentelemetry-specification pull request #1792
Opened 2021-07-05 15:10 UTC by pirgeo

Fixes #1788
Fixes #1650 

## Changes

* Updated the Instruments that should be used with metrics specified in the semantic conventions.
* Reformatted the markdown tables.

2021-07-07 12:17 UTC, arminru approved these changes
LGTM!

2021-07-07 13:19 UTC, jsuereth requested changes
Glad to see someone doing this!

Think maybe the difference between `ObservableCounter` and `CounterObserver` may not be clear in the new API specification, but basically that's the only change that happened to those.

2021-07-07 13:19 UTC, jsuereth commented on specification/metrics/semantic_conventions/system-metrics.md
> +| system.memory.usage       |             | By    | UpDownCounter   | Int64      | state         | used, free, cached, etc. |
`UpDownSumObserver` should no be called either `Asynchronous UpDownCounter` or `ObservableUpDownCounter`, see: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/api.md#asynchronous-updowncounter


Similar comment for remaining sum-observer types in this PR.

2021-07-09 06:57 UTC, pirgeo commented on specification/metrics/semantic_conventions/system-metrics.md
> +| system.memory.usage       |             | By    | UpDownCounter   | Int64      | state         | used, free, cached, etc. |
I wasn't sure about that since #1788 explicitly calls out that synchronicity is not of consequence here. Happy to change it, though. Would that also mean updating all the `Counter`s to `ObservableCounter`s, or is this only relevant to the `UpDownCounter`s?

2021-07-14 16:34 UTC, arminru commented on specification/metrics/semantic_conventions/system-metrics.md
> +| system.memory.usage       |             | By    | UpDownCounter   | Int64      | state         | used, free, cached, etc. |
@jmacd Please take a look 🙂

2021-07-27 15:43 UTC, arminru commented on specification/metrics/semantic_conventions/system-metrics.md
> +| system.memory.usage       |             | By    | UpDownCounter   | Int64      | state         | used, free, cached, etc. |
@jmacd friendly ping since you specified this on #1788.

2021-08-05 03:17 UTC, closed without merging