Add details for Aggregator in Metric spec
open-telemetry/opentelemetry-specification pull request #1804
Opened 2021-07-07 23:21 UTC by victlu

Add into Metric spec details for defining a Metric Aggregator.

2021-07-08 01:33 UTC, reyang commented on specification/metrics/sdk.md
> +and is default aggregator for the following instruments.
```suggestion
and is default aggregator for the following instruments:
```

2021-07-08 01:36 UTC, reyang commented on specification/metrics/sdk.md
> +* Last Value (latest Measurement given, avoid any time comparison.)
I think we also need to maintain the "timestamp when the value was sampled".

2021-07-08 01:38 UTC, reyang commented on specification/metrics/sdk.md
> +Histogram Aggregator maintains the following in memory:
I guess we can copy from https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/datamodel.md#histogram (the section under "A set of data points, each containing")?

2021-07-08 01:41 UTC, reyang commented
Do we intend to cover MIN and MAX?

2021-07-08 01:59 UTC, reyang commented
Some high level questions:
1. Is `Aggregator` intended to be exposed by the SDK as a type/class? (my answer would be NO, we don't need such type/class, we probably want some enum/flags that we can consume while defining the View).
2. If the answer to 1) is yes, do we intend to provide extensibility (e.g. one could build their own Aggregator)? (my answer would be eventually YES, for the first stable release probably NO)
3. If the answer to 1) is no, what's the purpose or it is just the SDK internal details?
4. Do we allow multiple aggregators to co-exist for the same event(s)? For example, if I have _temperature_, could I have Histogram, Min/Max and Average at the same time? If the answer is yes, do we end up with one stream or multiple streams? (my answer would be - we'll have multiple streams)

2021-07-08 13:41 UTC, jsuereth commented on specification/metrics/sdk.md
> +An `Aggregator` MUST have read/write access to memory storage (`In-Memory
If an aggregator is *given* state be some other owner, is that ok?

E.g.  can an aggregator pass back some state in its callback that someone else stores and restores to it, or does the Aggregator HAVE to be stateful?

2021-07-08 13:41 UTC, jsuereth commented on specification/metrics/sdk.md
> +cardinality attributes).
This `MUST` could be a really hard reach depending on language.

E.g. in Java do you expect aggregators to throw try-catch around everything to catch OOM?

More importantly, this implies aggregators need to *pre-allocate* log messages to fire when OOM so they don't re-cause an OOM in GC languages.


Second - The implicit notion we can drop high cardinality attributes due to memory limitations.   I *think* there are global SDK limits on attributes length that can be placed.  This implies we may also do something like that for high-cardinality metrics.   Should that be called out somewhere?

2021-07-08 13:41 UTC, jsuereth commented on specification/metrics/sdk.md
> +configuration so it can be properly configure. e.g. Configure a Sum aggregator
I think the opposite should be true.   a `View` determines how an `Aggregator` is configured, but an `Aggregator` should be naive of `View`s.

2021-07-08 13:41 UTC, jsuereth commented on specification/metrics/sdk.md
> +SDK MUST route measurements to the configured aggregator/s. e.g. SDK
Can you comment on the interaction between "MeasurementProcessor" and "Aggregator" here?

In my prototype I have "MeasurementProcessor" responsible for setting up the channel of `Measurements -> Aggregators`.

2021-07-08 13:41 UTC, jsuereth commented on specification/metrics/sdk.md
> +Sum Aggregator maintains the following in memory:
I've found that the memory footprint is actually highly different between Synchronus + Asynchronous instruments.

For the Java implementation, I fragmented Aggregator into a "stateless" component and I have separate storage mechanisms for  Synchronous + Asynchronous instruments that leverage an Aggregator for *what* to store.

The important point here, though, is I found the need to store a few different things.

## Synchronous Instruments.
- Delta-Accumulations per-exporter (see Reiley's fun multi-exporter design)
- Last-Reported Cumulative sums per-exporter (if CUMULATIVE sum)
- Last-Reported Timestamp per-exporter
- Application-start timestamp

## Asycnhronous Instruments
- Last collected CUMMULATIVE sum (for DELTA export)
- Last reported timestamp per-exporter

2021-07-08 13:41 UTC, jsuereth commented on specification/metrics/sdk.md
> +* Time window (e.g. start time, end time)
Where does `end time` come from (i.e. how do we have a  windo where)?

2021-07-08 17:41 UTC, jkwatson commented on specification/metrics/sdk.md
> +[Pre-Aggregated Metric](./datamodel.md#timeseries-model).
```suggestion
[Pre-Aggregated Metric](./datamodel.md#timeseries-model)s.
```

2021-07-08 17:47 UTC, jkwatson commented on specification/metrics/sdk.md
> +* Last Value (latest Measurement given, avoid any time comparison.)
```suggestion
* Last Value (latest Measurement given, avoiding any time comparison.)
```

2021-07-08 17:51 UTC, jkwatson commented
I was surprised not to see any mention of attributes/labels in here, and how an Aggregator needs to handle them. Is this something that is just so obvious that it doesn't need mentioning, or was this missed in writing up the details?

2021-07-08 21:56 UTC, ocelotl commented on specification/metrics/sdk.md
> +for delta temporality instruments.
[This](https://en.wikipedia.org/wiki/Aggregate_function#Decomposable_aggregate_functions) article mentions that there are 3 "kinds" of aggregate functions:

1. Some functions compute the aggregate by computing the aggregate for subsets, and then aggregating these aggregates, for example `COUNT`, `MAX`, `MIN`, and `SUM`.
2. Some functions compute the aggregate by computing auxiliary numbers for subsets, aggregating these auxiliary numbers, and finally computing the overall aggregate at the end, for example `AVERAGE` (aggregate with `SUM` and `COUNT`, then aggregate by dividing the former with the latter) and `RANGE` (aggregate with `MIN` and `MAX`, then aggregate by subtracting the former from the latter).
3. Some functions must compute the aggregate by computing the whole data set at once, for example `DISTINCT COUNT`, `MEDIAN`, and `MODE`.

Let's consider that aggregators use one function that can be of one of the kinds defined above. Aggregators that use a function of kind 1 can aggregate with one single value, aggregators that use a function of kind 2 can only aggregate with 2 or more values and aggregators that use a function of kind 3 can only aggregate using all the values.

Should the aggregator interface reflect this? Maybe we can have 3 kinds of aggregators each with different, matching interfaces?

2021-07-08 22:00 UTC, ocelotl commented on specification/metrics/sdk.md
> +An `Aggregator` MUST have read/write access to memory storage (`In-Memory
Not all aggregators have to be stateful. An aggregator that uses `MIN` does not need to be stateful, but an aggregator that uses `DISTINCT COUNT` does in the sense that the former can perform aggregation with every single value that is being aggregated and the latter needs to have all the values before aggregating.

2021-07-09 01:26 UTC, victlu commented on specification/metrics/sdk.md
> +Histogram Aggregator maintains the following in memory:
Yup, that's what we should have (unless I missed a field).

2021-07-09 01:28 UTC, victlu commented on specification/metrics/sdk.md
> +configuration so it can be properly configure. e.g. Configure a Sum aggregator
I agree also, and that was what I intended. But, definitely not what I wrote. I reworded so PTAL.

2021-07-09 16:16 UTC, victlu commented
> Do we intend to cover MIN and MAX?

An `Aggregator` is intended to target a [Metric Point](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/datamodel.md#metric-points) in Metrics Data Model. Thus, an Aggregator internally (`in-memory state`) stores a composite of data required to generate a Metric Point (Sums, Gauge, Histogram).

Currently, our OTLP protocol and Metric Points do not require MIN and/or MAX. ("Legacy" Summary Metric Point has that concept but wrapped as Quantiles).

2021-07-09 16:23 UTC, victlu commented on specification/metrics/sdk.md
> +for delta temporality instruments.
An `Aggregator` is intended to target a [Metric Point](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/datamodel.md#metric-points) in Metrics Data Model. Thus, an Aggregator internally (`in-memory state`) stores a composite of data required to generate a Metric Point (Sums, Gauge, Histogram).

At the Metric Data Model level, each Metric Point (Sum, Gauge, Histogram) are intended to support decomposable aggregation functions. Merging and combining of Metric Time Series is primarily effort downstream from the API/SDK.

2021-07-09 16:47 UTC, victlu commented on specification/metrics/sdk.md
> +The Histogram Aggregator MUST be configurable to support different Temporality.
> I was surprised not to see any mention of attributes/labels in here, and how an Aggregator needs to handle them.

Handling of Attributes is indeed a central concept. I did have a few mention and examples of how to address this. But, it likely needs it's own section to clarify. In the meantime, I did add a statement regarding SDK needing to route/map measurements to aggregators. It needs to be more flushed out in spec-level details.

In summary, A `MeasurementProcessor` ("Aggregator MeasurementProcessor") will route a measurement to zero or more pre-configured `Aggregators`. This Processor supports a mapping scheme which maps Attributes to Key/Value pair combinations. And for support of multiple exporters, mapping scheme which map per collection frequency.

At the last SIG meeting, I asked where this "routing" task should reside. As part of SDK (which I currently have spec) or part of a `MeasurmentProcessor` (call it the "Aggregator" measurement processor?). This is unfortunately confusing between a "Aggregator MeasurementProcessor" and an `Aggregator`.

Aggregator `MeasurmentProcessor` = concern with taking a measurement and breaking it up to zero or more instances.
`Aggregator` = concern with how to "aggregate" (sum/count/bucket/etc...) values.

2021-07-09 16:48 UTC, victlu commented
> I was surprised not to see any mention of attributes/labels in here, and how an Aggregator needs to handle them.

Handling of Attributes is indeed a central concept. I did have a few mention and examples of how to address this. But, it likely needs it's own section to clarify. In the meantime, I did add a statement regarding SDK needing to route/map measurements to aggregators. It needs to be more flushed out in spec-level details.

In summary, A `MeasurementProcessor` ("Aggregator MeasurementProcessor") will route a measurement to zero or more pre-configured `Aggregators`. This Processor supports a mapping scheme which maps Attributes to Key/Value pair combinations. And for support of multiple exporters, mapping scheme which map per collection frequency.

At the last SIG meeting, I asked where this "routing" task should reside. As part of SDK (which I currently have spec) or part of a `MeasurmentProcessor` (call it the "Aggregator" measurement processor?). This is unfortunately confusing between a "Aggregator MeasurementProcessor" and an `Aggregator`.

Aggregator `MeasurmentProcessor` = concern with taking a measurement and breaking it up to zero or more instances.
`Aggregator` = concern with how to "aggregate" (sum/count/bucket/etc...) values.

2021-07-09 16:49 UTC, victlu commented on specification/metrics/sdk.md
> +SDK MUST route measurements to the configured aggregator/s. e.g. SDK
Please see my comments below.  Also I've updated specs. PTAL

2021-07-09 16:52 UTC, victlu commented on specification/metrics/sdk.md
> +An `Aggregator` MUST have read/write access to memory storage (`In-Memory
I suspect most `Aggregators` will need some state. Even for `MIN`, we need to know the latest min to update min.

2021-07-09 16:55 UTC, jkwatson commented on specification/metrics/sdk.md
> +cardinality attributes.
I don't think we should include this paragraph. It doesn't provide any direction on what/how it should be accomplished, and thus won't be helpful for SDK implementors who are reading this spec and working on implementations.

2021-07-09 16:58 UTC, victlu commented on specification/metrics/sdk.md
> +An `Aggregator` MUST have read/write access to memory storage (`In-Memory
> If an aggregator is given state be some other owner, is that ok?

The spec's callout of `In-Memory State` somewhat complicates this `Aggregator` spec. An `Aggregator` internally has in-memory states, and does not necessarily need to be called out (this naturally maps to a "class" and private member fields in most languages).

Given my description above, `In-Memory State` and `Aggregator` is the same object. Thus, an Aggregator can never be given someone else's state. And management and scope is controlled by different instances of Aggregator (e.g. Per instrument).

2021-07-09 17:26 UTC, victlu commented
> 1. Is `Aggregator` intended to be exposed by the SDK as a type/class? (my answer would be NO, we don't need such type/class, we probably want some enum/flags that we can consume while defining the View).

I think this is more of a style question. In the end, we need to expose the concept of an aggregation and potentially any configuration (e.g. Monotonic and/or Cumulative/Delta and/or Bucket scaling).

## Enum

```
  .AddView(..., ENUM_AGGREGATOR_SUM_MONOTONIC_DELTA);
```

pro:
- Only need to expose one ENUM type
- If we support file based configs (i.e. json/xml), ENUMs are easier to encode.

con:
- Need to enumerate all possible configurations upfront.
- Need to update ENUM if we extend in future.

## Class/Type

```
  .AddView(..., new SumAggregator(monotonic=true, temporality=DELTA);
```

pro:
- Allows for finer control (e.g. new Histogram(bucket_boundaries=new int[] { 1, 10, 100 } ;)
- Potential for easy extensions in future.

con:
- Need to expose several classes/types.

2021-07-09 17:39 UTC, victlu commented
> 4. Do we allow multiple aggregators to co-exist for the same event(s)? For example, if I have _temperature_, could I have Histogram, Min/Max and Average at the same time? If the answer is yes, do we end up with one stream or multiple streams? (my answer would be - we'll have multiple streams)

I also think it would be valuable to allow one measurement to generate multiple metrics. (i.e. a Temperature Instrument can produce a Gauge timeseries and a Histogram timeseries and a Summary timeseries.

An `Aggregator` as defined here, does not care, as each instance of an aggregator represent one timeseries. The SDK is poised to route a measurement to zero or more aggregators as configured by the View API.

2021-07-12 13:24 UTC, jsuereth commented on specification/metrics/sdk.md
> +An `Aggregator` MUST have read/write access to memory storage (`In-Memory
So in the Java SDK prototype, we actually have Aggregators that are stateless: https://github.com/jsuereth/opentelemetry-java/blob/wip-metrics-api/sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/aggregator/Aggregator.java

They defer all state to the following:

- For Async instruments it is expected that someone else stores metrics on behalf of the aggregator and just uses the aggregator to determine WHAT to store, not how.
- For Performance reasons, Aggregators  define a "SynchronousStorageHandle".   This is a highly concurrency friendly storage to directly aggregate synchronous measurements when-reported (vs. using a disrupter/queue).

2021-07-12 18:22 UTC, victlu commented on specification/metrics/sdk.md
> +An `Aggregator` MUST have read/write access to memory storage (`In-Memory
In your prototype, who then actually manages the in-memory state? And what relationship does that component have with other components in terms of our SDK concepts?

2021-07-12 19:58 UTC, jsuereth commented on specification/metrics/sdk.md
> +for delta temporality instruments.
This is an important point though.  Should we tie *view* aggregators to Meric Data Model?  The Metric Data Model is meant to provide a *default* aggregation semantic.  It could be:

`MAX` -> Gauge
`MIN` -> Gauge
`COUNT` -> Sum
`SUM` -> Sum
`MEDIAN` -> Gauge
etc.


I.e. I'm not convinced we should ONLY support "LastValue", "Sum" and "HIstogram Distribution" as our only aggregations, but I think they're a good first step.

2021-07-12 21:37 UTC, jmacd approved these changes

2021-07-12 21:37 UTC, jmacd commented on specification/metrics/sdk.md
> +An `Aggregator` MUST have read/write access to memory storage (`In-Memory
In earlier drafts of the SDK specification, and in my OTel-Go prototype, I tried to maintain another requirement for the measurement processor about it's ability to release memory. I was state that the measurement processor MUST be able to forget (i.e., "expunge") records that are not in use to avoid perpetual buildup of memory, especially when high-cardinality metrics are combined with delta aggregation temporality. 

I assumed that each Aggregator instance would have some fixed memory requirement, the question is not how much memory each takes, but how many of them there are. In other words, I would address the state question here by allowing the measurement processor to forget Aggregators.

2021-07-12 21:37 UTC, jmacd commented on specification/metrics/sdk.md
> +Sum Aggregator maintains the following in memory:
:+1:

2021-07-12 21:37 UTC, jmacd commented on specification/metrics/sdk.md
> +
This may take more than a github comment thread to answer, but I'd like all of your opinions on the OTel-Go prototype, which looks about the same, but from reading the above it sounds different. The OTel-Go "Accumulator" (like "Measurement processor") computes only deltas and has a mechanism for forgetting Aggregators. The "Processor" (like "Metric processor") handles delta-to-cumulative conversion. 

This means that in a cumulative setup, there are really two copies of the data. One being maintained by the measurement processor (as a delta, if in use), and one being maintained by the metric processor (as a cumulative).

2021-07-12 21:52 UTC, cijothomas commented on specification/metrics/sdk.md
> +* Start Time<sup>2</sup>
EndTime as well needed?

2021-07-12 21:54 UTC, cijothomas commented on specification/metrics/sdk.md
> +* [Asynchronous Counter](./api.md#asynchronous-counter) instrument.
it sounds incorrect if both sync and async versions of Counter defaults to the same aggregator, as sync version of counter instrument gives delta, whereas async version gives cumulative.

2021-07-12 22:26 UTC, jmacd approved these changes

2021-07-12 22:26 UTC, jmacd commented on specification/metrics/sdk.md
> +* [Asynchronous Counter](./api.md#asynchronous-counter) instrument.
On the other hand, the Aggregation being performed (i.e., addition, computing a sum of the inputs) is the same.

2021-07-12 22:26 UTC, jmacd commented on specification/metrics/sdk.md
> +* Start Time<sup>2</sup>
EndTime should be captured somehow during Collect, I think.

2021-07-14 22:47 UTC, jsuereth commented on specification/metrics/sdk.md
> +An `Aggregator` MUST have read/write access to memory storage (`In-Memory
@victlu To answer your quesiton, the Measurement processor in my prototype is responsible for configuring the Storage and assocaited an Aggregator to it.  The Storage is its own component, configured based on Instrument + View configuration.  The aggregator just calculates bits and passes them to the storage.

2021-07-14 22:53 UTC, jsuereth commented on specification/metrics/sdk.md
> +e.g. [View](./sdk.md) configuration specify which Attribute Keys to include,
The phrasing (specifically verb `route`) implies a "push" or active control flow.

What about asynchronous measurements and aggregation?   When does the pull happen, and how does the aggregator support this?


Side note, one reason we divorced aggregator from storage is this.  In the Java prototype async insturments can be polled on demand and aggregation is run.   for Synchronous instruments, aggregation happens as measurements come in.

2021-07-14 22:54 UTC, jsuereth commented on specification/metrics/sdk.md
> +SDK MUST provide aggregators to support the default configured aggregator
Can you explicitly provide a table of these mappings rather than just a .e.g.?  I'm not sure we've captured this (appropriately) as a MUST specification anywhere else.

2021-07-14 23:04 UTC, jsuereth commented on specification/metrics/sdk.md
> +
@jmacd I actually went a different approach to this as well.

- Synchronous insturments 
  - have an impelemntation of "storage" that allows for forgetting "storage handles" when attributes disappear.
  - Can ask an Aggregator for a new high-concurrent handle for storing synchronous measurements.
  - Always report "DELTA".
  -  Will join with past value if the aggregator informs Storage to preserve last collected value.
- Asynchronous instruments
  - Only pull measuremnets -> Aggregator on demand.
  - Remember past value *IF* aggregator informs storage it's necessary (e.g. DELTA aggregation)
  
  
  From what I can tell, this is similar to what you did, but the "MetricsProcessor" actually receives "as close to OTLP" data as possible.
  
  I think it makes a ton of sense to allow (internally) Synchronous = Delta accumulation, Asynchronous = Cumulative accumulation and allow adapters.
  
Alll this said, from a *Specification* standpoint, I don't think any of that has to be specified.   The real question is, have we achieved the same semantics *and* are those semantics specified?  If users configure the same way and get the same data, the implementation shouldn't matter.


So my question:

- Does your metric processor expose the DELTAs as DELTAs?  Do we need to "hide" your Delta => Cumulative converter or do we want to specify that behavior or leave it language specific?
- Do we need to specify storage requirements in memory for Aggregators, or just what values they produce when configured?

2021-07-15 17:54 UTC, victlu commented on specification/metrics/sdk.md
> +cardinality attributes.
Given multiple likes, I'll remove this.

2021-07-15 17:58 UTC, victlu commented on specification/metrics/sdk.md
> +e.g. [View](./sdk.md) configuration specify which Attribute Keys to include,
I'm wondering if we leave the concept of In-Memory State to be implementation details. Thus, we only have concept of an Aggregator at the spec level.

2021-07-16 00:32 UTC, cijothomas commented on specification/metrics/sdk.md
> +An `Aggregator` MUST have read/write access to memory storage (`In-Memory
Could we just say - aggregator has access to the raw measurements?

2021-07-19 23:12 UTC, victlu commented on specification/metrics/sdk.md
> +cardinality attributes).
I took this out of spec.

2021-07-19 23:12 UTC, victlu commented on specification/metrics/sdk.md
> +and/or data lost occurs due to memory mitigation strategy. (e.g dropping high
I took this out of spec.

2021-07-19 23:13 UTC, victlu commented on specification/metrics/sdk.md
> +aggregators.
I reworded and simplified. PTAL

2021-07-19 23:14 UTC, victlu commented on specification/metrics/sdk.md
> +* [Asynchronous Counter](./api.md#asynchronous-counter) instrument.
I reworded and simplified. PTAL

2021-07-19 23:14 UTC, victlu commented on specification/metrics/sdk.md
> +e.g. [View](./sdk.md) configuration specify which Attribute Keys to include,
I reworded and simplified. PTAL

2021-07-19 23:16 UTC, victlu commented on specification/metrics/sdk.md
> +
I like to keep the implementation details out of the spec if possible. I reworded several sections to allow for more abstract wording that hopefully covers the implementation details. PTAL

2021-07-19 23:20 UTC, victlu commented on specification/metrics/sdk.md
> +for delta temporality instruments.
I think we need to discuss the "scope" of an Aggregator. Is it limited to one function, or is it a proxy for a Metric Point?

Let's discuss in SIG meeting.

2021-07-19 23:22 UTC, victlu commented on specification/metrics/sdk.md
> +Sum Aggregator maintains the following in memory:
I think these are details for each Aggregator implementation. (At least I'm currently not seeing us defining memory structure that is shared?)

I'm thinking we create an Aggregator (with parameters i.e. Temporality, Monotonicity) instance, and it can manage the appropriate in-memory states.

2021-07-19 23:23 UTC, victlu commented on specification/metrics/sdk.md
> +An `Aggregator` MUST have read/write access to memory storage (`In-Memory
I reworded the spec to avoid having to deal with implementation details. PTAL.

2021-07-19 23:26 UTC, victlu commented on specification/metrics/sdk.md
> +The Histogram Aggregator MUST be configurable to support different Temporality.
I think you have a good point. I think each language implementation can tackle this.

2021-07-22 16:05 UTC, jsuereth requested changes

2021-07-22 16:05 UTC, jsuereth commented on specification/metrics/sdk.md
> +### HistogramAggregator
Again, I think we should focus on inputs (configuration or defaults) and outputs rather than internal state.

Here's what I'd have for Histogram Aggregator:

```
### ExplicitBucketHistogramAggregator
The ExplicitBucketHistogramAggregator collects measurements and produces the [Histogram Metric Point](./datamodel.md#histogram).

The ExplicitBucketHistogramAggregator MUST allow specification of histogram bucket boundaries.

The ExplicitBucketHistogramAggregator MUST compute a count per-bucket of how many measurements fall within the bucket.

The ExplicitBucketHistogramAggregator MUST compute count of all measurements seen.

The ExplicitBucketHistogramAggregator SHOULD compute a sum of all measurements seen.
- The sum MUST default to monotonic for `Histogram` or `Counter` instruments.
- The sum MUST default to nonmontonic for `UpDownCounter` instruments.
- The sum MUST be calculated with the natural `+` operation for the numeric type.
```

2021-07-26 19:05 UTC, victlu commented on specification/metrics/sdk.md
> +### HistogramAggregator
I reworded. PTAL.

2021-07-26 19:05 UTC, victlu commented on specification/metrics/sdk.md
> +### SumAggregator
I reworded. PTAL.

2021-07-26 19:06 UTC, victlu commented on specification/metrics/sdk.md
> +### Aggregator
I reworded. PTAL.

2021-07-26 19:06 UTC, victlu commented on specification/metrics/sdk.md
> +### GaugeAggregator
I reworded. PTAL.

2021-07-26 19:06 UTC, victlu commented on specification/metrics/sdk.md
> +| Instrument Kind | Default Aggregator | Monotonic | Temporality | Notes |
I reworded. PTAL.

2021-07-26 19:06 UTC, victlu commented on specification/metrics/sdk.md
> +
I reworded. PTAL.

2021-07-26 19:07 UTC, victlu commented on specification/metrics/sdk.md
> +The Histogram Aggregator MUST be configurable to support different Temporality.
Please reopen if this is still a concern.

2021-07-26 19:07 UTC, victlu commented on specification/metrics/sdk.md
> +for delta temporality instruments.
I reworded. PTAL.

2021-07-26 19:07 UTC, victlu commented on specification/metrics/sdk.md
> +Sum Aggregator maintains the following in memory:
I reworded. PTAL.

2021-07-27 11:19 UTC, pirgeo commented on specification/metrics/sdk.md
> +This Aggregator may be configured for monoticity and temporality.
```suggestion
This Aggregator may be configured for monotonicity and temporality.
```

2021-07-27 11:19 UTC, pirgeo commented on specification/metrics/sdk.md
> +This Aggregator may be configured for custom bucket boundaries, monoticity, and
```suggestion
This Aggregator may be configured for custom bucket boundaries, monotonicity, and
```

2021-07-29 10:42 UTC, weyert commented on specification/metrics/sdk.md
> +\[1\]: Default Bucket Boundaries: (-&infin;, 0], (0, 5.0], (5.0, 10.0], (10.0, 25.0], (25.0, 50.0], (50.0, 75.0], (75.0, 100.0], (100.0, 250.0], (250.0, 500.0], (500.0, 1000.0], (1000.0, +&infin;)
Do we want to specify a default unit of measure for this?

2021-08-02 15:31 UTC, victlu commented
After discussion in SIG meeting, a new PR is created #1842 to continue with this spec.

2021-08-02 15:31 UTC, closed without merging