Add distro name and version to Resource.
open-telemetry/opentelemetry-specification pull request #1821
Opened 2021-07-20 12:26 UTC by carlosalberto

Fixes #1786 

Added as well an entry in the glossary for "OpenTelemetry Distro". One interesting thing @trask mentioned was deprecation of `telemetry.auto.version`.

2021-07-20 13:02 UTC, jsuereth approved these changes

2021-07-20 13:15 UTC, iNikem commented
> Fixes #1786
> 
> Added as well an entry in the glossary for "OpenTelemetry Distro". One interesting thing @trask mentioned was deprecation of `telemetry.auto.version`.

Unless we want to call auto-instrumentation agent, such as https://github.com/open-telemetry/opentelemetry-java-instrumentation a "distro", I don't think we can deprecated `telemetry.auto.version`. Moreover, at least in Java, we totally expect that vendor distros will be based on Otel Java Instrumentation, thus both versions are of interest.

2021-07-20 13:15 UTC, iNikem commented on specification/glossary.md
> +### OpenTelemetry Distro
Do we want to call it "distro" or "distribution"?

2021-07-20 13:20 UTC, carlosalberto commented on specification/glossary.md
> +### OpenTelemetry Distro
Probably we can actually call them "Distribution" formally, and "distro" as both informal/resource term.

2021-07-21 19:46 UTC, trask commented
> > Fixes #1786
> > Added as well an entry in the glossary for "OpenTelemetry Distro". One interesting thing @trask mentioned was deprecation of `telemetry.auto.version`.
> 
> Unless we want to call auto-instrumentation agent, such as https://github.com/open-telemetry/opentelemetry-java-instrumentation a "distro", I don't think we can deprecated `telemetry.auto.version`. Moreover, at least in Java, we totally expect that vendor distros will be based on Otel Java Instrumentation, thus both versions are of interest.

If vendors build their own SDK based on OTel SDK, how should they populate `telemetry.sdk.version`?

2021-07-22 03:36 UTC, bogdandrutu requested changes
Wait?!?!?

Why is the `telemetry.sdk` not good for this?

```
| `telemetry.sdk.name` | string | The name of the telemetry SDK as defined above. | `opentelemetry` | No |
| `telemetry.sdk.language` | string | The language of the telemetry SDK. | `cpp` | No |
| `telemetry.sdk.version` | string | The version string of the telemetry SDK. | `1.2.3` | No |
```

2021-07-22 06:53 UTC, iNikem commented
> Wait?!?!?
> 
> Why is the `telemetry.sdk` not good for this?
> 
> ```
> | `telemetry.sdk.name` | string | The name of the telemetry SDK as defined above. | `opentelemetry` | No |
> | `telemetry.sdk.language` | string | The language of the telemetry SDK. | `cpp` | No |
> | `telemetry.sdk.version` | string | The version string of the telemetry SDK. | `1.2.3` | No |
> ```

If we replace sdk name and version with vendor distribution name and version, then SDK version is not available "in band". Meaning that if some backend is actually interested in the SDK version used by that distribution, they cannot find that data in the telemetry itself. They have to fetch that data somehow separately and join.

Second, let's take an example of vendor distribution based on Otel auto-intrumentation agent, e.g. Java. We have vendor distro version V, which is based on otel-java-instrumentation version A, which used SDK version S: V->A->S. If we continue to use `telemetry.auto.version` to record the version A, then we will have all of a sudden that V replaces S in `telemetry.sdk.version` and A is still separate. Sounds like A is more important than V and S, which is not true, IMO. I mean, if we disregard my first objection above, then we should have just 1 version recorded.

For the record: I support this PR and recording of all 3 versions right inside telemetry.

2021-07-26 23:05 UTC, jmacd approved these changes
"Distro" is fine with me (I'm not the language police).  The word has been in common use for decades in the this industry.

2021-07-27 15:00 UTC, tedsuo approved these changes
This is a helpful addition! LGTM.

2021-07-27 15:00 UTC, tedsuo commented on specification/glossary.md
> +### OpenTelemetry Distro
+1 for distro, we've been using that shorthand everywhere.

2021-07-28 13:25 UTC, carlosalberto commented
From yesterday's meeting: @bogdandrutu is afraid we will end up adding too many items to `Resource`, and that we could potentially _override_ the `telemetry.sdk` fields instead, as a potential alternative (to which, for the record, I disagree with). This is because once a vendor knows about its own version (say, `acme,version=1.1`), the vendor will in turn know what version of the SDK (and language) is being used.

If somebody has additional details to add, please do so. Otherwise I will close this issue by EOW ;)

2021-07-29 08:48 UTC, iNikem commented
If we close this PR, how the original issue will be solved? The only other proposed alternative is to reuse `telemetry.sdk.*` and at least two people are against it (Carlos and I).

2021-07-29 12:15 UTC, Oberon00 commented on specification/glossary.md
> +### OpenTelemetry Distro
Normally, we use full names in resource, e.g. `rt` is a common abbreviation for `runtime` but we still choose the latter.
I think there was even a general discussion about this on some issue/PR quite some time ago, but I can't find it and https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/common/attribute-naming.md does not mention this.

So I'm weakly in favor of `distribution` instead of the abbreviated `distro`.

2021-07-29 12:20 UTC, Oberon00 commented
> @bogdandrutu is afraid we will end up adding too many items to Resource

I think we already have a very large number of resource conventions, so if you set all applicable ones, you will probably have a few kB of resource info.

The distro would not be set by default by the SDK, right? Only if there actually is a distro?

2021-07-29 12:24 UTC, Oberon00 commented on semantic_conventions/resource/telemetry.yaml
> +          The name string of the distribution, if used.
The "if used" is unclear.

We need to define here what constitutes a "distribution" and what not. E.g. is opentelemetry-java, as uploaded to Maven Central, with all the BOM files, etc., a distribution? Or is only the agent a distribution?

It seems you added a glossary entry, which is good. Please link to it.

And nitpicking some more: "used" is still the wrong word here, probably should use

```suggestion
          The name of the distribution, if applicable.
```

2021-07-30 17:39 UTC, carlosalberto commented
> Only if there actually is a distro?

Only if there's a distro, i.e. a vanilla agent will **not** set this.

> The only other proposed alternative is to reuse telemetry.sdk.* and at least two people are against it (Carlos and I).

Good point. Maybe keep this issue open? And then we can discuss in a way to solve this, one way or another.

cc @trask

2021-07-31 16:43 UTC, Oberon00 commented
> Only if there's a distro, i.e. a vanilla agent will not set this.

That's very confusing to me. I would view the agent as a distro of the SDK+API.

2021-07-31 16:44 UTC, Oberon00 commented on semantic_conventions/resource/telemetry.yaml
> +          The name string of the distribution, if used.
Unresolving, there is more to this comment than just this suggestion (and the suggestion also applies to distro.version)

2021-08-16 03:17 UTC, closed without merging

2022-03-21 17:17 UTC, tsloughter commented
What happened with this?

I could have swore I had run into `telemetry.distro.version` in the spec but when I searched the repo I only found this issue.

The SDK name/version can't be used because distros aren't the same thing. A distro can be just a wrapper that configures and sets up the SDK, and could technically even work with multiple SDKs.