Add event semantic conventions.
open-telemetry/opentelemetry-specification pull request #1843
Opened 2021-08-03 16:17 UTC by Oberon00

This is a demo for open-telemetry/build-tools#57, which is in need of reviewers 😃

(also needs open-telemetry/build-tools#58)

## Changes

* Mark exception as semconv type "event" (default is span)
* Add YAML definitions for grpc events.

2021-08-04 19:37 UTC, carlosalberto commented on .vscode/settings.json
> +        "https://raw.githubusercontent.com/dynatrace-oss-contrib/build-tools/events/semantic-conventions/semconv.schema.json": [
dynatrace-oss-contrib?

2021-08-04 19:39 UTC, carlosalberto approved these changes

2021-08-05 09:00 UTC, arminru approved these changes

2021-08-05 09:00 UTC, arminru commented on semantic_conventions/trace/rpc.yaml
> +    prefix: "message" # TODO: Change the prefix to rpc.grpc.message?
```suggestion
    prefix: "message"  # TODO: Change the prefix to rpc.grpc.message?
```
To make yamllint happy.

2021-08-05 09:10 UTC, Oberon00 commented on .vscode/settings.json
> +        "https://raw.githubusercontent.com/dynatrace-oss-contrib/build-tools/events/semantic-conventions/semconv.schema.json": [
No, this was intentionally committed, but of course can't be merged as-is.

After open-telemetry/build-tools#57 is merged and a release is cut, the PR needs to be updated to bump the generator version, and then I will also update this line to not point to `main`, but to that version.

2021-08-17 15:15 UTC, arminru commented
@open-telemetry/specs-approvers / @open-telemetry/specs-trace-approvers Please also take a look at https://github.com/open-telemetry/build-tools/pull/57 on which this change is based.

2021-08-24 12:08 UTC, Oberon00 commented
As open-telemetry/build-tools#57 was merged, this now includes an update of the semantic convention generator to v0.5.0.

2021-09-01 11:07 UTC, arminru requested changes

2021-09-01 11:07 UTC, arminru commented on specification/trace/semantic_conventions/rpc.md
> +client and server spans.
```suggestion
client and server spans.

The event name MUST be `"message"`.
```
@Oberon00 This was previously defined and would now be lost otherwise.

2021-09-03 14:30 UTC, Oberon00 commented
Sorry for being slow on this one, suggestion applied & conflicts resolved & build still green now!

2021-09-03 14:59 UTC, arminru approved these changes

2021-09-03 14:59 UTC, merged