Add OTLP protocol configuration options
open-telemetry/opentelemetry-specification pull request #1880
Opened 2021-08-19 18:52 UTC by jack-berg

Fixes #1879 

## Changes

Add `OTEL_EXPORTER_OTLP_PROTOCOL`, `OTEL_EXPORTER_OTLP_TRACES_PROTOCOL`, and `OTEL_EXPORTER_OTLP_METRICS_PROTOCOL` environment variables for specifying the OTLP protocol.

2021-08-19 19:27 UTC, jkwatson approved these changes

2021-08-19 23:22 UTC, anuraaga approved these changes

2021-08-20 12:12 UTC, carlosalberto commented
cc @jsuereth (maybe I'm wrong but I think you were interested in this ;) )

2021-08-20 16:54 UTC, jsuereth requested changes
We need to confirm with maintainers that the meaning of these enums i the same across SDKs.

There was concern (previously), that "http/protobuf" and "http/json" are not specific enough in what they mean, and that existing "http/protobuf" or "http/json" exporters in SDKs are actually incompatible with each other.

Opening this as a blocking comments until we have verification from language SDK maintainers that they're comfortable with this as written given the previous attempt to specify this.

2021-08-24 20:55 UTC, jack-berg commented on specification/sdk-environment-variables.md
> +| `http/protobuf`   | "otlp_http_proto" | Protobuf-encoded data over HTTP connection |
Opted to `otlp_http_proto` instead of `otlp_http_protobuf` to be inline with `zipkin_proto` added [here](https://github.com/open-telemetry/opentelemetry-specification/pull/1869).

2021-08-24 21:00 UTC, jack-berg commented
I've added new commits which revert my first attempt in favor of the approach discussed in the sig meeting of adding new exporter options for the different protocols instead of adding a new configuration option.

2021-08-25 04:39 UTC, anuraaga commented on specification/sdk-environment-variables.md
> +- `"otlp_grpc"`: [OTLP](./protocol/otlp.md) with the `otlp/grpc` protocol.
Using values `_EXPORTER` doesn't seem to fit well with the other variables we have defined. Notably, variables such as `OTEL_EXPORTER_OTLP_ENDPOINT` would need to be extended with `OTEL_EXPORTER_OTLP_GRPC_ENDPOINT`? It seems like an unnecessary explosion.

I understand this was discussed verbally at the sig meeting so am probably missing detail of the motivation for the switcheroo, but I can't find a signficant downside of a `_PROTOCOL` approach - it requires looking at multiple environment variables to configure an exporter anyways (_EXPORTER, _ENDPOINT, _ETC) so adding another one to represent a knob for wire format seems natural. It's true that in most cases, the different formats represent different exporter artifacts, but that seems like an implementation detail that is still compatible with this approach - in fact we've already implemented it in Java with experimental variable names. It doesn't seem to have the downside of allowing multiple exporters like otlp_grpc, otlp_http_proto defined at the same time without being able to configure them.

2021-08-31 13:28 UTC, carlosalberto commented on specification/sdk-environment-variables.md
> +- `"otlp_grpc"`: [OTLP](./protocol/otlp.md) with the `otlp/grpc` protocol.
Ping @tedsuo ;)

2021-09-02 01:06 UTC, tedsuo commented on specification/sdk-environment-variables.md
> +- `"otlp_grpc"`: [OTLP](./protocol/otlp.md) with the `otlp/grpc` protocol.
@anuraaga the original proposal does not reflect how exporters are actually implemented in any language. So the result is a bizarre mismatch. And with both proposals, there is no way to configure multiple OTLP exporters, even though it is possible to install them. So, no design is right here. 

I general, I am more and more unhappy about this ad-hoc approach to environment variables as a way to drive the conversation forwards. I'm watching "design theories" be lifted and then dropped as they are convenient. This is a terrible approach to designing the primary surface area that our users are going to interact with. I really want to see a more consistent and coherent approach to configuration design. 

Sorry @jack-berg, I know you're just trying to solve some annoying configuration issues that currently exist. But should we really be adding more env vars when we know they may not fit very well? 

Looking again, I do agree that if what we want is to allow multiple exporters to be installed, but only allow one _OTLP_ exporter to be installed, the original proposal has fewer side effects. But is that what we actually want? Down the line, it will definitely be possible to install multiple exporters. If it's possible to install both `otel_grpc` and `otel_http_json`, how would these env vars be expected to interact with that configuration?

Ironically, the proposal @anuraaga dislikes the most (seperate env vars for each exporter, e.g. OTEL_EXPORTER_OTLP_GRPC_ENDPOINT) is actually the one which correctly maps to our architecture. 

Env vars are sadness. If we had a conf file, I don't think we'd even be asking these questions.

2021-09-02 02:36 UTC, anuraaga commented on specification/sdk-environment-variables.md
> +- `"otlp_grpc"`: [OTLP](./protocol/otlp.md) with the `otlp/grpc` protocol.
> the original proposal does not reflect how exporters are actually implemented in any language. So the result is a bizarre mismatch. 

I don't see the coupling between the exporter implementation and how the configuration knob is presented. @jack-berg has validated this by implementing some experimental variables in Java and I don't think anyone has found it to be bizarre. What concretely do you think is bizarre about it?

> But is that what we actually want? Down the line, it will definitely be possible to install multiple exporters. 

We currently do allow multiple exporters to be installed with a CSV to `OTEL_*_EXPORTER`, we probably shouldn't have as it has caused a huge explosion in configuration surface in the env vars. Anyways, there seems to be no conceptual basis for allowing `otel,otel_grpc` and not `otel,otel`, which the `_PROTOCOL` approach avoids. I agree that this is where a configuration file approach would allow more flexibility. But it doesn't have to be one or the other - perhaps we are missing text but the env vars still provide a good, simple approach. Perhaps we are missing some text in this MD file that the goal of the env vars is to provide a simple configuration, without maximum flexibility. A way to think about it could be that env vars are likely the primary mechanism when using the collector - you just need a simple set of variables to get the data into the collector which has the flexible pipelines to process them.

At least that's what I figure they're for - it's why I would advocate the `OTEL_EXPORTER_OTLP_PROTOCOL` variable. At a glance it might seem like creep by adding another variable, but it actually does not add as much configurability as adding to the OTEL_EXPORTER types, which opens up the greater configuration surface of handling the case of multiple OTLP exporters being defined.

But freezing variables until there is a more well defined story seems ok too - I'm mostly concerned about adding the new exporter types as currently proposed. My goal I think is the same as @tedsuo's, to reduce the expansion of the configuration surface. Ironically, it is an additional variable that does that I think.

> Env vars are sadness. If we had a conf file, I don't think we'd even be asking these questions.

This isn't fair - personally I've had a much easier time with env vars when deploying apps to k8s for example, and the config file requirement of the OTel collector is actually somewhat annoying. Others probably have different experiences though. I doubt one approach is clearly better - I suspect that a simple set of environment variables along with the ability to define something more flexibly with a file can satisfy both itches.

2021-09-03 01:09 UTC, tedsuo commented on specification/sdk-environment-variables.md
> +- `"otlp_grpc"`: [OTLP](./protocol/otlp.md) with the `otlp/grpc` protocol.
@anuraaga I agree that env vars are very useful. Sorry, I didn't mean to slight them. In fact, I would prefer that OTel be designed so that env vars and conf files keep a 1:1 basis – anything that can be defined in a conf file should be overridable with an env var. I believe that env vars are critical in that regard, and should be treated as first class citizens. Like you say, there are many situations where it is easier to set an env var than it is to change a conf file, especially in cloud environments where changing a conf file means deploying a new image.

But when I say env vars make me sad, it's more about the nefarious way they seem to make good design difficult. I've been on multiple projects which accidentally painted themselves into a corner by taking our current approach. We would steadily add env vars which made sense at the time but later created headaches, and couldn't be removed for compatibility reasons.

That's actually my concern with these particular proposals (both of them!). It's not the way they expand the surface area now, it's that I can see how they may force us to make a complicated set of rules later, when we expose planned features in the future.

In this case, if we had a proper design and layout, I suspect it might have lead us to a solution which exposed more env vars, but didn't feel "clunky" because it fit a regular pattern we were applying everywhere.

I've learned that it is better to start by designing the conf file and env vars at the same time, always make them match, and always lay out the options in a way that reflects the architecture of the system. For whatever reason, the presence of the conf file seems to help with all of that. Maybe because we are visual critters. We didn't do that with OTel. Oh well. I'm glad we're trying to do it now. We'll fix it in post. :)

At any rate, I propose we add these env vars, as they were originally defined by @jack-berg and @anuraaga. We need to clean our design up, but it's been two weeks now and it's not fair to keep blocking this feature. If we want to freeze future env vars while we bang out a design, fine, but let's not hold up needed additions that have already been waiting. 

Again, many apologies to Jack for having to put up with us while we went around and around. Turns out this was trivial but also important. :)

2021-09-03 01:10 UTC, tedsuo approved these changes
Having now discussed this at leeeeeeeeeength, I'm fine with adding the original proposal.

2021-09-03 17:18 UTC, lonewolf3739 commented on specification/sdk-environment-variables.md
> +SDKs have an unspecified default protocol, which is used if the exporter selection is "otlp".
Small question, what does unspecified default protocol mean here?

2021-09-03 21:43 UTC, jack-berg commented on specification/sdk-environment-variables.md
> +SDKs have an unspecified default protocol, which is used if the exporter selection is "otlp".
My understanding is that it means that language SDKs have a default, but that default isn't dictated by the specification. 

See [this convo](https://github.com/open-telemetry/opentelemetry-specification/pull/1358#discussion_r564498561) for context.

2021-09-03 22:02 UTC, jack-berg commented on specification/sdk-environment-variables.md
> +- `"otlp_grpc"`: [OTLP](./protocol/otlp.md) with the `otlp/grpc` protocol.
A great discussion! And definitely agree with the need for a well designed conf file (especially thinking about configuring metric views 😬!), which env vars can be neatly mapped to. I do think that these new environment variables will be straight forward to map to whatever conf file spec otel lands on.

2021-09-04 04:41 UTC, anuraaga approved these changes
Thanks everyone!

2021-09-06 14:34 UTC, carlosalberto approved these changes

2021-09-06 14:34 UTC, carlosalberto commented
Ping @jsuereth

2021-09-13 12:50 UTC, carlosalberto commented
@jsuereth Ping ;) Is your original changes request still standing? Else, let's merge this one.

2021-09-13 23:19 UTC, jsuereth approved these changes
Think we've left this open with sufficient time for SDK concerns and raised it multiple SiGs.  I left ONE comment in the maintainer channel for last-minute discussions.

I don't think this belongs in the specificatoin but taking note here:

Compliance to protocol should be evaluated via Otel Collector ingestion of telemetry.

2021-09-14 14:39 UTC, carlosalberto commented
@jack-berg Oops, looks like we don't have a CHANGELOG entry, please add one ;)

2021-09-14 15:21 UTC, jack-berg commented
All set @carlosalberto!

2021-09-14 22:56 UTC, merged

2021-09-14 23:26 UTC, alolita reviewed
+1