Capture HTTP request/response headers as span attributes
open-telemetry/opentelemetry-specification pull request #1898
Opened 2021-08-30 17:32 UTC by mateuszrzeszutek

Fixes #1061

## Changes

- Add semantic conventions for capturing HTTP request and response headers.

2021-08-30 17:53 UTC, jkwatson commented on specification/trace/semantic_conventions/http.md
> +**[2]:** The attribute value MAY contain separate header value as separate items, or concatenated header values as one item, depending on the way the HTTP library provides access to headers.
is this footnote actually referenced anywhere?

2021-08-30 17:53 UTC, jkwatson approved these changes

2021-08-30 17:56 UTC, mateuszrzeszutek commented on specification/trace/semantic_conventions/http.md
> +**[2]:** The attribute value MAY contain separate header value as separate items, or concatenated header values as one item, depending on the way the HTTP library provides access to headers.
Oops🤭 
Thanks for catching this!

2021-08-31 08:17 UTC, Oberon00 reviewed
This convention is breaking new ground, because it only defines a prefix, not a full semantic convention. We don't really have support for that in the semantic convention generator (yet?), so it's fine to only have it as a markdown table.

There are a few questions that arise from this convention, that I'll post as separate comments.

2021-08-31 08:17 UTC, Oberon00 commented on specification/trace/semantic_conventions/http.md
> +| `http.request.header.<key>` | string[] | HTTP request headers, `<key>` being the HTTP Header name (case preserving), the value being the header values. [1] [2] | `http.request.header.Content-Type=[
We have quite a few HTTP semantic conventions that will usually (but not necessarily) be just copies of respective headers, namely `http.host`, `http.user_agent`. What is the guidance on these? I would propose to prefer the specific semantic convention for now and not duplicate them with this by default.

2021-08-31 08:17 UTC, Oberon00 commented on specification/trace/semantic_conventions/http.md
> +| `http.request.header.<key>` | string[] | HTTP request headers, `<key>` being the HTTP Header name (case preserving), the value being the header values. [1] [2] | `http.request.header.Content-Type=[
I think it is important to provide guidance which headers should be captured by default. Capturing all headers will certainly be too much. I propose that instrumentations need to have captured headers explicitly configured. We should even have an standardized configuration (envvar) for this. The details are outside of scope of this PR probably, but in this PR I think it is important to at least state that capturing everything by default is wrong.

2021-08-31 09:19 UTC, mateuszrzeszutek commented on specification/trace/semantic_conventions/http.md
> +| `http.request.header.<key>` | string[] | HTTP request headers, `<key>` being the HTTP Header name (case preserving), the value being the header values. [1] [2] | `http.request.header.Content-Type=[
I imagined that a user would have to configure an allowlist of headers that are to be included as span attributes, capturing all headers is definitely not a good idea from the security perspective.

2021-08-31 12:03 UTC, Oberon00 commented on specification/trace/semantic_conventions/http.md
> +**[1]:** Instrumentations SHOULD require an explicit configuration of which headers are to be captured (e.g. an allowlist).
```suggestion
**[1]:** Instrumentations SHOULD require an explicit configuration of which headers are to be captured (e.g. a capturelist).
```

Or remove the sample. I think "allowlist" does not fit here (allowlist cannot replace all usages of the old term).

2021-08-31 12:03 UTC, Oberon00 approved these changes

2021-08-31 13:27 UTC, carlosalberto commented on specification/trace/semantic_conventions/http.md
> +**[1]:** Instrumentations SHOULD require an explicit configuration of which headers are to be captured (e.g. an allowlist).
Also, any reason to not use MUST here? I think this is sensitive enough that should be explicit all the time.

2021-08-31 13:52 UTC, mateuszrzeszutek commented on specification/trace/semantic_conventions/http.md
> +**[1]:** Instrumentations SHOULD require an explicit configuration of which headers are to be captured (e.g. an allowlist).
I used the `db.statement` attribute as an analogy: the DB query can contain very sensitive information too but the spec says that `The value may be sanitized to exclude sensitive information` and doesn't place any hard requirements on instrumentations to make sanitization required (or even configurable).

2021-08-31 15:19 UTC, jsuereth commented
Should HTTP Request/Response be an "Event" with these as attributes on that event?

2021-08-31 15:22 UTC, yurishkuro commented
> Should HTTP Request/Response be an "Event" with these as attributes on that event?

I'd say no, because there are no meaningful timestamps one could attach to such events that are different from the span start/end.

2021-09-01 16:25 UTC, owais commented on specification/trace/semantic_conventions/http.md
> +These headers SHOULD NOT be captured as a part of this convention.
Can we remove this to simplify implementation a bit? Users will most likely not configure this feature to capture headers that are already part of the spec and supported by their SDK.

2021-09-01 16:25 UTC, owais commented on specification/trace/semantic_conventions/http.md
> +| `http.request.header.<key>` | string[] | HTTP request headers, `<key>` being the HTTP Header name (case preserving), the value being the header values. [1] [2] | `http.request.header.Content-Type=[
Since users will have to explicitly mention all headers they want to capture, I think it is unlikely they'll specify headers that their SDK already captures. Can we leave it out to simplify a bit?

2021-09-01 16:25 UTC, owais commented on specification/trace/semantic_conventions/http.md
> +**[1]:** Instrumentations SHOULD require an explicit configuration of which headers are to be captured.
Should we specify the env vars that should be used to configure this?

2021-09-01 17:04 UTC, Oberon00 commented on specification/trace/semantic_conventions/http.md
> +These headers SHOULD NOT be captured as a part of this convention.
I'd see this as a suggestion for the user how to use the configuration. An explicit request by the user is a valid reason not to honor the SHOULD.

2021-09-06 09:07 UTC, mateuszrzeszutek commented on specification/trace/semantic_conventions/http.md
> +**[1]:** Instrumentations SHOULD require an explicit configuration of which headers are to be captured.
I don't think that we have any instrumentation config prop/env var spec in this repo - I agree that this needs to be done, but as a separate effort and not a part of this PR.

2021-09-06 11:16 UTC, owais commented on specification/trace/semantic_conventions/http.md
> +These headers SHOULD NOT be captured as a part of this convention.
I'm concerned SDK authors might not read it like that. Your comment is very clear. Perhaps we can re-word it to sound more like that?

2021-09-06 13:05 UTC, mateuszrzeszutek commented on specification/trace/semantic_conventions/http.md
> +These headers SHOULD NOT be captured as a part of this convention.
Done 👍

2021-09-07 11:53 UTC, Oberon00 commented
After seeing #1907, I wonder if my proposal to preserve casing was so good after all, or if we need something additional. IMHO a good goal would be to be able to capture header information in such a way that #1907 is resolved as well. Some ideas:
1. Normalize header names to lowercase, `-` to `_` (like lowercased CGI envvars), do not preserve casing.
2. Optionally capture a list of configured headers normalized (in addition to case-preserving or only). The prefix could be the same or `http.(request|response).normalized_header` or similar. Or we could rename the current capturing to `raw_header`. The normalization could be done by the instrumentation, a span processor (if we have #1089), the exporter, the collector or even the backend.
3. Just state that normalization / accessing keys in a case-insensitive way is the responsibility of whoever processes the data (maybe in addition to defining the normalization but define nothing more. I don't think that would be good enough to satisfy proposals like #1907 in the future though.

CC @Blacksmoke16

2021-09-07 12:52 UTC, Blacksmoke16 commented
@Oberon00 HTTP/2 requires headers be lowercase while in HTTP/1 it doesn't matter. Normalizing them to all however would be backwards compatible, while also being future proof.

2021-09-08 16:03 UTC, mateuszrzeszutek commented
> 1. Normalize header names to lowercase, `-` to `_` (like lowercased CGI envvars), do not preserve casing.

I like this idea because it's the simplest out of the three you suggested - and the most intuitive one ("why don't we lowercase headers" was the first question I asked in the linked issue 😄 ). We do lose a little bit of information that way, but since HTTP headers are supposed to be case insensitive by design it's probably not worth that much.
I'll rework my PR with idea 1. in mind.

2021-09-09 11:59 UTC, bogdandrutu commented on specification/trace/semantic_conventions/http.md
> +| `http.response.header.<key>` | string[] | HTTP response headers, `<key>` being the normalized HTTP Header name (lowercase, with `-` characters replaced by `_`), the value being the header values. [
Why not have this as attributes with "type" `map[string][]string` (too much golang)? Then the key would be fixed.

2021-09-09 15:30 UTC, yurishkuro commented on specification/trace/semantic_conventions/http.md
> +| `http.response.header.<key>` | string[] | HTTP response headers, `<key>` being the normalized HTTP Header name (lowercase, with `-` characters replaced by `_`), the value being the header values. [
I had the same suggestion on the ticket itself https://github.com/open-telemetry/opentelemetry-specification/issues/1061#issuecomment-908447921. I think nested map is a much cleaner approach than inventing bespoke translation rules and polluting the overall attributes namespace.

2021-09-10 11:43 UTC, mateuszrzeszutek commented on specification/trace/semantic_conventions/http.md
> +| `http.response.header.<key>` | string[] | HTTP response headers, `<key>` being the normalized HTTP Header name (lowercase, with `-` characters replaced by `_`), the value being the header values. [
So what should we do with this PR then? Should we wait with it until we reach a consensus on #376 and implement headers as nested structures?

2021-09-13 09:59 UTC, iNikem commented on specification/trace/semantic_conventions/http.md
> +| `http.response.header.<key>` | string[] | HTTP response headers, `<key>` being the normalized HTTP Header name (lowercase, with `-` characters replaced by `_`), the value being the header values. [
If we accept this PR, will it possible later to define `http.request.headers` attribute to contain a map of headers? I assume "yes", so we can proceed and merge this PR for now. Although @bogdandrutu may object to having two separate semantic conventions to represent the same entity :)

2021-09-13 11:05 UTC, mateuszrzeszutek commented on specification/trace/semantic_conventions/http.md
> +| `http.response.header.<key>` | string[] | HTTP response headers, `<key>` being the normalized HTTP Header name (lowercase, with `-` characters replaced by `_`), the value being the header values. [
> If we accept this PR, will it possible later to define `http.request.headers` attribute to contain a map of headers?

It will - although having 2 conventions that basically do the same thing will be far from elegant.
I also had some question in #376, maybe answering them will make the whole picture a bit clearer.

2021-09-17 12:18 UTC, carlosalberto commented
> Why not have this as attributes with "type" map[string][]string

Since we don't support this now (and probably it will take a little while before we do so), should we proceed with this approach for now? @bogdandrutu @yurishkuro

2021-09-17 12:19 UTC, carlosalberto approved these changes

2021-09-17 12:21 UTC, Oberon00 commented
> and probably it will take a little while before we do so

You are assuming that we will support it 😉 That's not decided at all.

2021-09-17 12:23 UTC, carlosalberto commented
> That's not decided at all.

Yeah, definitely. More the reason to go with the current approach.

2021-09-17 12:25 UTC, Oberon00 commented
I'm somewhat strongly against adding support for more complex attributes, like maps. I think this PR should be merged as-is, and then we should close #376 because the only use case that came up so far has been solved differently. What would the purpose of adding maps *after* this PR be? The added-value of maps is already very small (negative IMHO), and if we add maps after this PR, there is one more negative to it, namely the disruption it causes for this semantic convention.

2021-09-17 12:27 UTC, yurishkuro approved these changes

2021-09-17 12:27 UTC, yurishkuro commented on specification/trace/semantic_conventions/http.md
> +**[2]:** The attribute value MAY contain separate header value as separate items, or concatenated header values as one item, depending on the way the HTTP library provides access to headers.
```suggestion
**[2]:** The attribute value MAY contain multiple header values as an array of strings, or as a single, possibly comma-concatenated, string, depending on the way the HTTP library provides access to headers.
```

2021-09-17 12:28 UTC, Oberon00 commented on specification/trace/semantic_conventions/http.md
> +**[2]:** The attribute value MAY contain separate header value as separate items, or concatenated header values as one item, depending on the way the HTTP library provides access to headers.
@yurishkuro, no the current wording is right: We want to always have an array, even if it has just a single element.

2021-09-17 12:29 UTC, Oberon00 commented on specification/trace/semantic_conventions/http.md
> +**[2]:** The attribute value MAY contain separate header value as separate items, or concatenated header values as one item, depending on the way the HTTP library provides access to headers.
See #831

2021-09-17 12:32 UTC, yurishkuro commented on specification/trace/semantic_conventions/http.md
> +**[2]:** The attribute value MAY contain separate header value as separate items, or concatenated header values as one item, depending on the way the HTTP library provides access to headers.
Ok, but it doesn't mention array and the wording is confusing. Not a blocker.

2021-09-17 12:34 UTC, Oberon00 requested changes
I'm against having the value be set as a single string instead of single-element array, as it makes typing more complicated. See https://github.com/open-telemetry/opentelemetry-specification/pull/1898#discussion_r711013196

2021-09-17 12:35 UTC, Oberon00 commented on specification/trace/semantic_conventions/http.md
> +**[2]:** The attribute value MAY contain separate header value as separate items, or concatenated header values as one item, depending on the way the HTTP library provides access to headers.
The array is in the type column (note the `[]`).

2021-09-17 12:40 UTC, mateuszrzeszutek commented on specification/trace/semantic_conventions/http.md
> +**[2]:** The attribute value MAY contain separate header value as separate items, or concatenated header values as one item, depending on the way the HTTP library provides access to headers.
I've changed the wording so that it's somewhat in between those two versions, but strongly saying that it should be an array.

2021-09-17 12:43 UTC, arminru approved these changes

2021-09-17 12:43 UTC, arminru commented on specification/trace/semantic_conventions/http.md
> +### HTTP request and response headers
Changelog please 🙂

2021-09-17 13:28 UTC, Oberon00 approved these changes

2021-09-17 13:37 UTC, mateuszrzeszutek commented on specification/trace/semantic_conventions/http.md
> +### HTTP request and response headers
Done 👍

2021-09-17 13:51 UTC, Oberon00 commented on specification/trace/semantic_conventions/http.md
> +**[2]:** The attribute value MAY contain multiple header values as an array of strings, or as a single-item array containing a possibly comma-concatenated string, depending on the way the HTTP librar
Actually, the wording is a bit odd here with the "MAY". If we opt to not use the "MAY", what else can we set? Nothing, right? So instead of "MAY ... or ...", I suggest "MUST either ... or ...".

2021-09-20 10:54 UTC, carlosalberto commented
Will merge by EOD unless somebody opposes.

2021-09-21 17:47 UTC, iNikem approved these changes

2021-09-21 18:04 UTC, Oberon00 approved these changes

2021-09-21 18:10 UTC, merged