Revert "Add InstrumentationLibrary to Sampler.ShouldSample (#1850)"
open-telemetry/opentelemetry-specification pull request #1942
Opened 2021-09-20 16:46 UTC by iNikem

This reverts commit f936f2e941ad10bf9b16b5ab15067f775f479cdb.

As discussed during today Maintainers meeting.

2021-09-20 17:03 UTC, Oberon00 requested changes
> As discussed during today Maintainers meeting.

Please provide a more detailed justification for those that did not attend (feel free to dismiss my review after that)

2021-09-20 17:07 UTC, yurishkuro commented
> Please provide a more detailed justification for those that did not attend (feel free to dismiss my review after that)

+ 1. Do we need to improve our community guidelines to make it clear that "was discussed in a meeting" is never a justification for any change?

2021-09-20 17:30 UTC, iNikem commented
Sorry, updated PR's description

2021-09-20 17:41 UTC, yurishkuro approved these changes

2021-09-20 23:19 UTC, carlosalberto approved these changes

2021-09-21 07:30 UTC, bogdandrutu approved these changes

2021-09-21 07:36 UTC, Oberon00 commented
Please ensure a follow-up issue for this new configuration design is created before merging.

2021-09-21 14:49 UTC, jsuereth commented
@Oberon00 I'm not sure what you mean here.  Can you clarify?  I'd like to understand what you'd like to see before moving this PR forward.

2021-09-22 08:41 UTC, iNikem commented
Added https://github.com/open-telemetry/opentelemetry-specification/issues/1588#issuecomment-924712956

2021-09-22 11:53 UTC, carlosalberto commented
@Oberon00 Wanted to double confirm you are fine with Nikita's comment, and we can merge this one?

2021-09-22 12:18 UTC, Oberon00 commented
I need to correct my previous comment: I meant to suggest "Closes #1658", #1588 is obviously not resolved.

But yes, I'm OK with merging this PR, although with a somewhat uneasy feeling, as I fear this will keep #1588 in the backlog for quite some time.

2021-09-22 12:46 UTC, merged