Allow unit to be specified in View
open-telemetry/opentelemetry-specification pull request #1972
Opened 2021-09-27 18:03 UTC by reyang

Fixes #1822.

2021-09-27 18:36 UTC, jsuereth approved these changes

2021-09-27 18:44 UTC, cijothomas approved these changes

2021-09-27 20:04 UTC, jkwatson commented on specification/metrics/sdk.md
> +  * The `unit`. If not provided, the Instrument `unit` would be used by default.
this doesn't imply any sort of auto-conversion of units, correct?

2021-09-28 00:51 UTC, SergeyKanzhelev commented on specification/metrics/sdk.md
> +  * The `unit`. If not provided, the Instrument `unit` would be used by default.
+1, would be nice to clarify in text.

2021-09-28 15:12 UTC, bogdandrutu requested changes

2021-09-28 15:12 UTC, bogdandrutu commented on specification/metrics/sdk.md
> +  * The `unit`. If not provided, the Instrument `unit` would be used by default.
It is not correct to say that "the Instrument `unit` would be used by default". As discussed previously please provide examples/use cases when this is needed. I cannot find any use-case besides the auto-conversion in case of "Count" to drop the unit since no longer apply, but besides that I cannot find any other example. I am reluctant on adding more configs unless we prove they are needed.

2021-09-28 17:09 UTC, reyang commented
Discussed during the [09/28/2021 Metrics SIG Meeting](https://docs.google.com/document/d/1pdvPeKjA8v8w_fGKAN68JjWBmVJtPCpqdi9IZrd6eEo/edit#), moving this to post-Stable release, abandon the PR for now.

2021-09-28 17:09 UTC, closed without merging