Define how to enable Meter attributes for Prometheus Exporter
open-telemetry/opentelemetry-specification pull request #2035
Opened 2021-10-19 13:13 UTC by hdost

Fixes #1906

## Changes

* Add `OTEL_METRICS_LIBRARY_ATTRIBUTES` variable
* Update Metric SDK to clarify when Meter attributes should be exported.

Related issues #1953

2021-10-30 10:14 UTC, hdost commented
> > > 1. @hdost Would you be willing to put together a prototype or more example use case here around what attributes across all of OTLP should be in prometheus?  I'm happy to help, just overloaded in time at the moment trying to build the otel roadmap.
> 
> > I think I can arrange time to do that. What is the timeframe we are looking so I can prioritize?
> 
> I'd like to see a prototype/usage example in prometheus prior to merging the specification change, if that's feasible.

@jsuereth  Yup, I was more wondering in the context of timeline, is the goal to have this behavior defined before Feature freeze of he SDK or just stabilization.

2021-11-08 13:50 UTC, jsuereth commented
@hdost IIUC - Prometheus Exporter specification can happen post SDK-freeze unless you need a feature from the SDK for this.

It's my understanding that we do not need SDK features for this, so we're free to take some time to get this right.   I'd like to make sure whatever you do here lines up with the formal specification for prometheus.

I think the only thing I'm objecting too on this PR right now is that I think adding `otel.library` (or whatever the label is we'll use for insturmentation library) should be *default on* for prometheus export.

2021-11-10 16:53 UTC, jmacd commented
We discussed this at length in the Prometheus working group SIG and consulted with @brian-brazil.

There is a fundamental question which is practically orthogonal to the issue at hand, which is when can we ever say that two metrics are the "same". This question borders on philosophical--we discussed a hypothetical set of two libraries both with a "request_count" metric. Brian's experience says that rarely are two implementations exactly the same, so they should be considered different almost always. While `cpu.seconds` may be given a single meaning, very often "request_count" differs slightly based on where in a pipeline you are counting requests, so a more-refined metric name should be used. E.g., if you were counting Kafka requests and Redis requests, you should probably use different metric names. 

Here are the recommendations we arrived at when we landed this discussion:
- Inside the same binary, 
  - two instruments with the same name SHOULD use the same instrument kind, SDK MUST warn the user and reject one
  - two instruments with the same name SHOULD use distinct attribute sets, because the collector can't validate
-  Inside a collector, when exporting to Prometheus:
  - do nothing by default; if the application follows the rules, nothing bad happens except possibly combining metrics w/ slightly different implementations
  - optionally, if the user wants to consistently apply an instrumentation-library attribute, this should be an option, but it's not a good default behavior because it has to be done consistently across a system
- General recommendations
  - Prefix the library name to the metric name if two libraries might use the same attribute set inside a single binary
  - Follow distinct resource practices to avoid breaking the single-writer rule, so ultimately this issue boils down to another case of #1782

2021-11-10 18:50 UTC, hdost commented
> Prefix the library name to the metric name if two libraries might use the same attribute set inside a single binary

Oh so now that is quite interesting 🤔 basically this would namespace things, so if you're instrumenting
"io.otel.metrics" and "io.otel.traces" then the metrics could optionally be appended with those names sanitized for prometheus as an example:`io_otel_traces_<metric_name>`

I could see this exploding the metric name length depending on what comes through.

2021-11-11 06:31 UTC, reyang commented on specification/sdk-environment-variables.md
> +- `true` : Add the Meter `name` and `version` as Attributes on the metrics exported.
I did some quick prototype in .NET https://github.com/open-telemetry/opentelemetry-dotnet/pull/2593.

Couple findings:
1. the label name `name` and `version` are concerning, I think it is very likely to conflict with existing labels (it is totally possible to invent some rule although I didn't cover it in the prototype).
2. the [Metrics API Spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/api.md#get-a-meter) guarantees a non-empty meter name, however there is no guarantee on the meter version. I think we should call out here what's the behavior if version is not available or is an empty string.
3. I think there are many cases people might care about the meter name, but not the version, I think the current proposal (having both or nothing) might be less useful.

2021-11-11 06:34 UTC, reyang requested changes
Please find addition feedback based on the prototype https://github.com/open-telemetry/opentelemetry-specification/pull/2035/files#r747236300.

2021-11-11 06:34 UTC, reyang commented on specification/sdk-environment-variables.md
> +- `false` : Don't add Meter `name` and `version` as Attributes on the metrics exported.
I guess it meant to be "Prometheus labels" instead of "Attributes"?

2021-11-12 01:23 UTC, jonatan-ivanov reviewed
Since some backends has reserved words for tag name, I would try to choose something more specific than `name` and `version`, like `meter_name` and `meter_version`. Also, if I see name and version on the tags, I'm not sure it will be clear to me what these exactly mean.

(Not really Prometheus-related but [datadog reserves `version`](https://docs.datadoghq.com/getting_started/tagging/))

2021-11-16 17:18 UTC, jmacd commented
As discussed in the SIG call today, we should be using the same attribute names already specified for tracing systems for consistency. This means "otel.library.name" and "otel.library.version", which in a Prometheus setting should have dots converted to underscores.

2021-12-01 03:17 UTC, closed without merging