Probability sampling in `tracestate` specification
open-telemetry/opentelemetry-specification pull request #2047
Opened 2021-10-20 17:06 UTC by jmacd

## Changes

Specifies how to interpret and use p-value and r-value for consistent probability sampling decisions, including two optional samplers named `ConsistentProbabilityBased` and `ConsistentParentProbabilityBased`.

Does not modify existing built-in Sampler definitions.

This is ready for general review.

Implemented in https://github.com/open-telemetry/opentelemetry-go-contrib/pull/1379

OTEPs 
https://github.com/open-telemetry/oteps/blob/main/text/trace/0168-sampling-propagation.md
https://github.com/open-telemetry/oteps/blob/main/text/trace/0170-sampling-probability.md

Part of #1414 
Part of #1412 
Part of #1524 
Part of #570 
Another take on #1899 
Fixes #2224
Part of #2179

2021-11-02 08:56 UTC, jmacd commented on specification/trace/tracestate-probability-sampling.md
> +##### Requirement 1
Got it, will fix.

2021-11-02 20:59 UTC, jmacd commented
@open-telemetry/specs-trace-approvers the two optional samplers specified here are implemented by this PR in opentelemetry-go-contrib: https://github.com/open-telemetry/opentelemetry-go-contrib/pull/1379

2021-11-03 13:42 UTC, yurishkuro commented on specification/trace/tracestate-probability-sampling.md
> +R-value determines which sampling probabilities and will not sample
"determines which sampling probabilities" - incomplete sentence?

2021-11-03 13:48 UTC, yurishkuro commented on specification/trace/tracestate-probability-sampling.md
> +approach used in OpenTelemetry, defined in greater detail below.
> defined in greater detail below

do you mean some specific section?

2021-11-03 13:50 UTC, yurishkuro commented on specification/trace/tracestate-probability-sampling.md
> +A simple sampling scheme can be implemented using a random bit string
Suggestion: give this string a variable name and refer to it later, e.g. `using a random bit string B as the input".

2021-11-03 13:54 UTC, yurishkuro commented on specification/trace/tracestate-probability-sampling.md
> +2. Count `r`, the number of consecutive zero bits in the input string
Q: is the bit string really relevant here? It seems like a (possible) implementation detail, couldn't we explain the actual methodology without it? I.e. I would prefer to separate math definition from algorithmic implementation.

2021-11-03 13:57 UTC, yurishkuro commented on specification/trace/tracestate-probability-sampling.md
> +## Probability sampling
should this be titled Consistent Probability Sampling?

2021-11-03 13:59 UTC, yurishkuro commented on specification/trace/tracestate-probability-sampling.md
> +### Conformance
I would expect the text to first explain how p/r are actually used in the algorithm & sampling, before going into conformance etc. We must assume this is the first time a person reads this material.

2021-11-03 14:00 UTC, yurishkuro commented on specification/trace/tracestate-probability-sampling.md
> +| r-value          | Probability of r-value   | Implied sampling probabilities |
I recommend explaining "Probability of r-value" column - why is it here?

2021-11-04 00:14 UTC, PeterF778 commented on specification/trace/tracestate-probability-sampling.md
> +time.
There's a potential trouble here - a consistent probability sampler is defined as one "that supports independent sampling decisions at each span in a trace while maintaining that traces will be complete with probability equal to the minimum sampling probability across the trace". Now, let's assume that we have multiple probability samplers configured with 5% sampling rate, handling different branches of the trace, and that 5% is actually the minimum sampling probability across the trace. If those samplers select their nearest powers of two probabilistically and independently, completeness of the trace will be less likely than 5%. This can be "fixed" by a number of ways, none of them seems ideal though.

2021-11-04 05:50 UTC, oertl commented on specification/trace/tracestate-probability-sampling.md
> +time.
Yes, this needs to be reformulated. Completeness is only guaranteed with a probability that is the largest power of 1/2 smaller than or equal to the mimum sampling rate across the trace.

2021-11-04 07:59 UTC, oertl commented on specification/trace/tracestate-probability-sampling.md
> +`sampled` is equivalent to the expression `p <= r || p == 63`.
If the parent uses an always-off sampler, which behaves like a consistent probability sampler with probability 0, I would expect that `sampled == FALSE` and `p == 63`. That means an always-off sampler would always break this invariant.

The invariant `(p <= r) == sampled` must always hold except for the case that `sampled == TRUE` while `p == 63` which has a special meaning and leads to zero adjusted counts. Therefore, I think the invariant should rather be
`((p <= r) == sampled) OR (sampled AND (p == 63)) == TRUE`.

2021-11-04 17:34 UTC, robbkidd commented on specification/trace/tracestate-probability-sampling.md
> +| 0 <= r <= 61     | 1/(2**(-r-1))            | 2**(-r) and above              |
Is the inclusion of `1/` a typo here? Combined with a negative exponent, `1/...` produces a dramatically invalid probability. `1/` is not present in the rows for r-value 59-62.

```ruby
> (0..61).map{|r| 2**(-r-1)}.reduce(&:+)
=> (4611686018427387903/4611686018427387904)
> (0..61).map{|r| 2**(-r-1)}.reduce(&:+).to_f
=> 1.0

> (0..61).map{|r| 1/2**(-r-1)}.reduce(&:+)
=> (9223372036854775806/1)
```

2021-11-04 17:39 UTC, robbkidd commented on specification/trace/tracestate-probability-sampling.md
> +| 62               | 2**-62                   | 2**-62 and above               |
Possibly silly question: what's special about r = 62 that the "probably of r-value formula" is computed differently than for 0 <= r <= 61? I assume it _is_ a special case because the range given above in the row for "r" stops at 61, but I'm missing the importance of special handling.

```suggestion
| 62               | 2**-63                   | 2**-62 and above               |
```

2021-11-04 18:59 UTC, jmacd commented on specification/trace/tracestate-probability-sampling.md
> +| 62               | 2**-62                   | 2**-62 and above               |
This is a subtle detail, but stands correct. The last row in the table of r-values does not follow the pattern, so that the probabilities sum to 1. This detail caused confusion during review of the OTEPs (myself included) and I wrote this [section to explain why this detail is correct using a small example](https://github.com/open-telemetry/oteps/blob/main/text/trace/0168-sampling-propagation.md#worked-3-bit-example).

2021-11-04 19:54 UTC, jmacd commented on specification/trace/tracestate-probability-sampling.md
> +`sampled` is equivalent to the expression `p <= r || p == 63`.
Fixed.

2021-11-04 19:56 UTC, jmacd commented on specification/trace/tracestate-probability-sampling.md
> +| 0 <= r <= 61     | 1/(2**(-r-1))            | 2**(-r) and above              |
Fixed. Except for the final row, the `r=x` has probability 2**-(x+1).

2021-11-04 23:09 UTC, jmacd commented on specification/trace/tracestate-probability-sampling.md
> +time.
Since I've use "power of two" to describe negative powers of two throughout, I prefer to phrase this as:

"only ensured at the smallest power of two greater than or equal to the minimum sampling rate across the trace." 

Hope that sounds good.

2021-11-05 00:35 UTC, robbkidd commented on specification/trace/tracestate-probability-sampling.md
> +| 62               | 2**-62                   | 2**-62 and above               |
… Ooooh. This is "[snub Zeno, let Atalanta get to the end of the path](https://en.m.wikipedia.org/wiki/Zeno's_paradoxes#Dichotomy_paradox)?" Our series is finite. We'll declare the last item equal to the next-to-last item, making the sum of all the possible probabilities exactly equal 1 instead of approaching 1, and everyone gets to move on with life.

![a square showing the series 1/2, 1/4, … 1/64](https://user-images.githubusercontent.com/517302/140438689-8cfb9be2-e34a-4efd-a0f8-ade69da41263.png)

2021-11-05 07:21 UTC, jmacd commented on specification/trace/tracestate-probability-sampling.md
> +| 62               | 2**-62                   | 2**-62 and above               |
Yes! Another way I've found to think about this is that in a 62-bit random signed integer, there is exactly one "1" and exactly one "0", corresponding with r=61 and r=62, which therefore have the same probabilities.

2021-11-05 07:22 UTC, jmacd commented
@yurishkuro Thank you! Your feedback pointed to several rearrangements, which I've now applied.

2021-11-05 07:23 UTC, jmacd commented on specification/trace/tracestate-probability-sampling.md
> +A simple sampling scheme can be implemented using a random bit string
I removed this example, found a simpler way to explain how p- and r- relate to simple sampling.

2021-11-05 07:23 UTC, jmacd commented on specification/trace/tracestate-probability-sampling.md
> +approach used in OpenTelemetry, defined in greater detail below.
Fixed. The sections have been reordered.

2021-11-05 07:24 UTC, jmacd commented on specification/trace/tracestate-probability-sampling.md
> +R-value determines which sampling probabilities and will not sample
It was supposed to read "determines which sampling probabilities WILL and will not ...". I've edited this section.

2021-11-05 07:25 UTC, jmacd commented
@PeterF778 I've added the recommendation that we discussed in today's SIG stating that users are recommended to use power-of-two sampling probability for non-root spans, explaining that only at the root will non-power-of-two sampling work w/o incomplete traces.

2021-11-05 08:07 UTC, oertl commented
> @PeterF778 I've added the recommendation that we discussed in today's SIG stating that users are recommended to use power-of-two sampling probability for non-root spans, explaining that only at the root will non-power-of-two sampling work w/o incomplete traces.

This is not root-specific.

2021-11-05 13:49 UTC, robbkidd commented on specification/trace/tracestate-probability-sampling.md
> +| 62               | 2**-62                   | 2**-62 and above               |
> […] in a 62-bit random signed integer, there is exactly one "1" and exactly one "0", corresponding with r=61 and r=62, which therefore have the same probabilities.

I look forward to understanding this.

2021-11-05 14:57 UTC, jmacd commented
@oertl  You are correct. I'll adjust the wording here to say something different about root probability. It's true that a trace can be incomplete, but it can only be missing one span (the root) and this condition is testable, so we have an easy test for completeness.

As discussed in yesterday's SIG there are a bunch of other ways traces can be incomplete and OTel users can't verify completeness, so I consider this acceptable and part of a larger issue.

2021-11-08 20:21 UTC, jmacd commented
@oertl and @PeterF778 please see a38e321.

2021-11-09 15:11 UTC, ocelotl requested changes

2021-11-09 15:11 UTC, ocelotl commented on specification/trace/tracestate-probability-sampling.md
> +sample.
Missing RFC 2119 keyword

2021-11-09 15:11 UTC, ocelotl commented on specification/trace/tracestate-probability-sampling.md
> +Sampler should round down to zero probability and make the same
```suggestion
Sampler SHOULD round down to zero probability and make the same
```

2021-11-09 15:11 UTC, ocelotl commented
Just for fun, this would be the generated JSON file from the requirements in this PR:

``` json
[
    {
        "id": "Inconsistent p-values are unset",
        "clean id": "inconsistent_p_values_are_unset",
        "content": "Samplers SHOULD unset `p` when the invariant between the `sampled`,\n`p`, and `r` values is violated before using the `tracestate` to make\na sampling decision or interpret adjusted count.",
        "RFC 2119 keyword": "SHOULD"
    },
    {
        "id": "Out-of-range p-values are unset",
        "clean id": "out_of_range_p_values_are_unset",
        "content": "Consumers SHOULD unset `p` from the `tracestate` if the unsigned value\nis greater than 63 before using the `tracestate` to make a sampling\ndecision or interpret adjusted count.",
        "RFC 2119 keyword": "SHOULD"
    },
    {
        "id": "Out-of-range r-values unset both p and r",
        "clean id": "out_of_range_r_values_unset_both_p_and_r",
        "content": "Samplers SHOULD unset both `r` and `p` from the `tracestate` if the\nunsigned value is of `r` is greater than 62 before using the\n`tracestate` to make a sampling decision.",
        "RFC 2119 keyword": "SHOULD"
    },
    {
        "id": "ParentBased API compatibility",
        "clean id": "parentbased_api_compatibility",
        "content": "The `ParentConsistentProbabilityBased` Sampler MUST have the same\nconstructor signature as the built-in `ParentBased` sampler in each\nOpenTelemetry SDK.",
        "RFC 2119 keyword": "MUST"
    },
    {
        "id": "ParentConsistentProbabilityBased does not modify valid tracestate",
        "clean id": "parentconsistentprobabilitybased_does_not_modify_valid_tracestate",
        "content": "The `ParentConsistentProbabilityBased` Sampler MUST NOT modify a\nvalid `tracestate`.",
        "RFC 2119 keyword": "MUST"
    },
    {
        "id": "ParentConsistentProbabilityBased and ParentBased make identical decisions",
        "clean id": "parentconsistentprobabilitybased_and_parentbased_make_identical_decisions",
        "content": "The `ParentConsistentProbabilityBased` Sampler MUST make the same\ndecision specified for the `ParentBased` sampler.",
        "RFC 2119 keyword": "MUST"
    },
    {
        "id": "TraceIdRatioBased API compatibility",
        "clean id": "traceidratiobased_api_compatibility",
        "content": "The `ConsistentProbabilityBased` Sampler MUST have the same\nconstructor signature as the built-in `TraceIdRatioBased` sampler in\neach OpenTelemetry SDK.",
        "RFC 2119 keyword": "MUST"
    },
    {
        "id": "ConsistentProbabilityBased sampler sets r for root span",
        "clean id": "consistentprobabilitybased_sampler_sets_r_for_root_span",
        "content": "The `ConsistentProbabilityBased` Sampler MUST set `r` when it makes a\nroot sampling decision.",
        "RFC 2119 keyword": "MUST"
    },
    {
        "id": "ConsistentProbabilityBased sampler unsets p when not sampling",
        "clean id": "consistentprobabilitybased_sampler_unsets_p_when_not_sampling",
        "content": "The `ConsistentProbabilityBased` Sampler MUST unset `p` from the\n`tracestate` when it decides not to sample.",
        "RFC 2119 keyword": "MUST"
    },
    {
        "id": "ConsistentProbabilityBased sampler sets p when sampling",
        "clean id": "consistentprobabilitybased_sampler_sets_p_when_sampling",
        "content": "The `ConsistentProbabilityBased` Sampler MUST set `p` when it decides\nto sample.",
        "RFC 2119 keyword": "MUST"
    },
    {
        "id": "ConsistentProbabilityBased sampler sets p using an unbiased algorithm",
        "clean id": "consistentprobabilitybased_sampler_sets_p_using_an_unbiased_algorithm",
        "content": "The `ConsistentProbabilityBased` Sampler MUST set `p` so that the\nadjusted count interpreted from the `tracestate` is an unbiased\nestimate of the number of representative spans in the population.",
        "RFC 2119 keyword": "MUST"
    },
    {
        "id": "ConsistentProbabilityBased sampler sets r for non-root span",
        "clean id": "consistentprobabilitybased_sampler_sets_r_for_non_root_span",
        "content": "If `r` is not set on the input `tracecontext` and the Span is not a\nroot span, `ConsistentProbabilityBased` SHOULD set `r` as if it were a\nroot span and MAY warn the user that a potentially inconsistent trace\nis being produced.",
        "RFC 2119 keyword": "SHOULD"
    },
    {
        "id": "ConsistentProbabilityBased sampler acts like AlwaysOff sampler for probabilities less than 2**-62",
        "clean id": "consistentprobabilitybased_sampler_acts_like_alwaysoff_sampler_for_probabilities_less_than_2___62",
        "content": "If the configured sampling probability is less than `2**-62`, the\nSampler should round down to zero probability and make the same\nsampling decision as the builtin `AlwaysOff` sampler would.",
        "RFC 2119 keyword": null
    },
    {
        "id": "Combining multiple sampling decisions using logical `or`",
        "clean id": "combining_multiple_sampling_decisions_using_logical__or_",
        "content": "When multiple samplers are combined using composition, the sampling\ndecision is to sample if at least of the combined samplers decies to\nsample.",
        "RFC 2119 keyword": null
    },
    {
        "id": "Combine multiple consistent probability samplers using the minimum p-value",
        "clean id": "combine_multiple_consistent_probability_samplers_using_the_minimum_p_value",
        "content": "When combining Sampler decisions for multiple consistent probability\nSamplers and at least one decides to sample, the minimum of the \"yes\"\ndecision `p` values MUST be set in the `tracestate`.",
        "RFC 2119 keyword": "MUST"
    },
    {
        "id": "Unset p when multiple consistent probability samplers decide not to sample",
        "clean id": "unset_p_when_multiple_consistent_probability_samplers_decide_not_to_sample",
        "content": "When combining Sampler decisions for multiple consistent probability\nSamplers and none decides to sample, p-value MUST be unset in the\n`tracestate`.",
        "RFC 2119 keyword": "MUST"
    },
    {
        "id": "Use probability sampler p-value when its decision to sample is combined with non-probability samplers",
        "clean id": "use_probability_sampler_p_value_when_its_decision_to_sample_is_combined_with_non_probability_samplers",
        "content": "When combining Sampler decisions for a consistent probability Sampler\nand a non-probability Sampler, and the probability Sampler decides to\nsample, its p-value MUST be set in the `tracestate` regardless of the\nnon-probability Sampler decision.",
        "RFC 2119 keyword": "MUST"
    },
    {
        "id": "Use p-value 63 when a probability sampler decision not to sample when combined with non-probability sampler decision to sample",
        "clean id": "use_p_value_63_when_a_probability_sampler_decision_not_to_sample_when_combined_with_non_probability_sampler_decision_to_sample",
        "content": "When combining Sampler decisions for a consistent probability Sampler\nand a non-probability Sampler, and the probability Sampler decides not\nto sample but the non-probability does sample, p-value 63 MUST be set\nin the `tracestate`.",
        "RFC 2119 keyword": "MUST"
    },
    {
        "id": "Pass 15 non-power-of-two statistical tests",
        "clean id": "pass_15_non_power_of_two_statistical_tests",
        "content": "For the test with 20 trials and 1 million spans each, the test MUST\ndemonstrate a random number generator seed such that the ChiSquared\ntest statistic is below 0.102587 exactly 1 out of 20 times.",
        "RFC 2119 keyword": "MUST"
    },
    {
        "id": "Pass 5 power-of-two statistical tests",
        "clean id": "pass_5_power_of_two_statistical_tests",
        "content": "For the teset with 20 trials and 1 million spans each, the test MUST\ndemonstrate a random number generator seed such that the ChiSquared\ntest st [...]

2021-11-11 03:05 UTC, kalyanaj commented on specification/trace/tracestate-probability-sampling.md
> +probabilities.
I am looking to understand one thing better: In that case, are there situations where it will still be useful to support non-power-of-two sampling probabilities? Would it be an option to consider a requirement/constraint that samplers should support only power-of-two sampling probabilities (to avoid this situation)?

2021-11-12 03:04 UTC, kalyanaj commented on specification/trace/tracestate-probability-sampling.md
> +subtraces.
I think I understand the intuition behind this, but I have a couple of questions to understand this formal definition better. Let's take the example of the following spans and their sampling rates: 

A (6.25%) -> B (12.5%) -> C (25%) -> D (25%) -> E (25%) -> F (6.25%).  

When we have a partial trace that only has spans from C, D, and E (due to their higher sampling rates ):
1) We would regard the subset of C, D, E to be a complete subtrace at span C, correct?
2) When we apply the above definition to recursively evaluate it for the children of "C", then the formal definition has  "S's parent was not collected" which will be false for D, correct? Since the parent-not-being collected seems like a valid condition only for the "root of that sub-trace", wondering if we should change the formal definition to reflect it.

2021-11-16 19:13 UTC, jmacd commented on specification/trace/tracestate-probability-sampling.md
> +errors).  This property holds even for non-power-of-two sampling
Yes, thank you. I've added "and all other spans use a parent-based sampler".

2021-11-16 19:13 UTC, jmacd commented on specification/trace/tracestate-probability-sampling.md
> +probabilities.
Good question. We could surely specify that consistent probability samplers are restricted to powers of two. One answer is that not every application for trace data cares about completeness. The research by @oertl (https://arxiv.org/pdf/2107.07703.pdf) shows how we can use this data without completeness.

The situation where it may be useful to support a non-power-of-two sampling decisions is the root, where completeness is not broken if all other samplers are parent-based. This sounds contrived, but it is the normal case in historical systems, and as a result the OTel 1.0 tracing specification includes the `TraceIDRatioBased` sampler which is specified to support non-power-of-two probabilities. For the ConsistentProbabilityBased sampler to replace the TraceIDRatioBased sampler, I proposed that we relax the constructor to allow non-powers-of-two. The OTel 1.0 tracing speciication also includes a TODO and a warning against using the TraceIDRatioBased sampler at non-root spans, because it wasn't specified consistently. The consistent probability sampler can replace the TraceIDRatioBased sampler, and this is a replacement warning to be careful configuring this at non-root spans. It was a compromise.

2021-11-16 19:13 UTC, jmacd commented on specification/trace/tracestate-probability-sampling.md
> +subtraces.
I made an error in this section, had it completely wrong as you noticed. I do not consider the set of spans C, D, and E to be complete because F is missing.

I've shortened the definition to "A complete subtrace is defined at span S when every descendent span is collected."

2021-11-17 01:31 UTC, kalyanaj commented on specification/trace/tracestate-probability-sampling.md
> +producing incomplete traces is to use parent-based samplers except forr
```suggestion
producing incomplete traces is to use parent-based samplers except for 
```

2021-11-17 01:31 UTC, kalyanaj commented on specification/trace/tracestate-probability-sampling.md
> +oot spans.
```suggestion
root spans.
```

2021-11-17 01:31 UTC, kalyanaj commented on specification/trace/tracestate-probability-sampling.md
> +probabilities.
Got it, thanks Joshua for the additional context here.

2021-11-17 16:34 UTC, jmacd commented
@open-telemetry/specs-trace-approvers This PR has received a round of reviews from subject matter experts and I recommend that we try to get this merged. 

The OTel-Go implementation sits here: https://github.com/open-telemetry/opentelemetry-go-contrib/pull/1379

@dyladan and @oertl will you please post pointers to the current/best implementation of this work in Javascript and Java?

2021-11-17 18:20 UTC, ocelotl approved these changes

2021-11-17 19:26 UTC, oertl commented
@jmacd 
> @open-telemetry/specs-trace-approvers This PR has received a round of reviews from subject matter experts and I recommend that we try to get this merged.
> 
> The OTel-Go implementation sits here: [open-telemetry/opentelemetry-go-contrib#1379](https://github.com/open-telemetry/opentelemetry-go-contrib/pull/1379)
> 
> @dyladan and @oertl will you please post pointers to the current/best implementation of this work in Javascript and Java?

This is my proof of concept written in Java: https://github.com/dynatrace-research/opentelemetry-sampling-poc. But that needs to be updated according to the latest specification proposal.

2021-11-26 20:55 UTC, oertl commented on specification/trace/tracestate-probability-sampling.md
> +
I think keeping `ParentConsistentProbabilityBased` fully compatible with the current `ParentBased` Sampler is a problem. The delegation to other samplers based on the parent's sampling decision may lead to inconsistencies. For example, when delegating to an Always-on consistent probability sampler, the p-value will be set to 0 (corresponding to 100% sampling probability). This overwrites the p-value of the parent which represents the correct sampling probability. Therefore, I think `ParentConsistentProbabilityBased` must not delegate to other samplers. It should should just reuse the parent's p- and r-values which also leads to the same sampling decision.

2021-11-29 19:48 UTC, oertl commented
@jmacd 

Preliminary Java implementations of consistent samplers can be found in this branch:
https://github.com/dynatrace-oss-contrib/opentelemetry-java/tree/consistent-sampling
It also includes a prototype of a new span processor realizing consistent reservoir sampling. This span processor allows to sample a maximum number of spans per period.

2021-11-29 21:35 UTC, jmacd commented on specification/trace/tracestate-probability-sampling.md
> +
Good catch! You're right that this configuration mechanism can lead to incorrect interpretation. This has to be fixed.

My understanding of the existing ParentBased interface is that a user might use it to configure alternate samplers, which might for example add new span attributes. This is worthy of maintaining, and I hope we can do this without too much complicated new wording. This may require a bit more study, but the following rules seem to do it:

1. The delegated-to Sampler's _input_ tracestate will be stripped of `r` and `p`
2. The delegated-to Sampler's _output_ tracestate will be stripped of `r` and `p` and the original `r` always passes through
3. The delegated-to Sampler can change the sampling decision; if no change, `p` passes through unmodified
4. If the parent's decision was to sample and the delegated-to's decision is not to sample, `p` must be dropped
5. If the parent's decision was not to sample and the delegated-to's decision is to sample, `p` must be set to 63

2021-11-30 05:10 UTC, oertl commented on specification/trace/tracestate-probability-sampling.md
> +
I think, this will not fix it. `p` represents the parent sampling probability and allows to determine the adjusted count. According to 3) `p` is only passed through with a certain probability, which requires increasing `p` to get adjusted counts right. 

Consistent sampling requires that the sampling probability of any sampler does not depend on `r`. The sampled flag is given by the parent sampling decision `r >= p` and therefore the sampled flag depends on `r`. Since the parent-based sampler delegates dependent on this flag, its sampling probability will be dependent on `r` which leads to inconsistent sampling. To follow the parent sampling decision in a consistent way, a sampler could just set its `p` equal to the propagated parent `p` as demonstrated by https://github.com/dynatrace-oss-contrib/opentelemetry-java/blob/consistent-sampling/sdk/trace/src/main/java/io/opentelemetry/sdk/trace/samplers/ConsistentParentBasedSampler.java.

I am interested in particular use cases of the current ParentBased sampler. I am pretty sure that those can be covered with consistent sampling, but not by delegating to different samplers based on the sampled flag.

2021-11-30 08:06 UTC, jmacd commented
@oertl @kalyanaj I have added more recommendations for trace producers to avoid inconsistent configurations. 

In my comment above (https://github.com/open-telemetry/opentelemetry-specification/pull/2047#discussion_r758753139), I've described how I think we can extend the ConsistentParentProbabilityBased sampler to check and constrain its delegating sampler specifically to avoid the inconsistencies that @oertl referred to. I support doing that in a future PR. Since this spec is already marked experimental, I think we can leave that out of this PR, sound good?

2021-11-30 16:32 UTC, jmacd commented on specification/trace/tracestate-probability-sampling.md
> +
You're right!  A correction is required, and I'm not sure what we should do with this. The correction needed was described in OTEP 170 while describing the [Dapper inflationary sampling approach](https://github.com/open-telemetry/oteps/blob/main/text/trace/0170-sampling-probability.md#dappers-inflationary-sampler). I feel that we could specify how to do this correctly but that we should not.

I have included warnings against improper configuration, so the question is whether the risk of misconfiguration outweighs the cost of not having those interfaces. AFAICT the reason for `ParentBased` to support conditional delegation is not to provide a means of changing the sampling decision, but to provide a way to change the attribute set on the resulting span. Choosing a different sampler delegate for unsampled contexts appears useful to limit the cost of sampling -- there's no reason to synthesize attributes for unsampled contexts.

To summarize, the `ParentBased` sampler supports conditional delegation, and I see reasons for this to exist, but this facility also makes it easy to accidentally subvert our adjusted count logic. I would like to ask @yurishkuro or any @open-telemetry/specs-trace-approvers -- can anyone remember why `ParentBased` has this facility to choose the delegating sampler based on the parent's sampled flag? It's risky.

A "safer" version of the `ConsistentParentProbabilityBased` sampler could break from the `ParentBased` interface, allow configuring the delegating sampler for remote and non-remote contexts, but not based on the `sampled` flag. Is the added safety worth the loss of control over performance? If I could choose my own solution to this problem, I would return us to #620 -- the problem of expensive attributes that are conditionally evaluated should be separated from the `Sampler` API with the use of lazy attributes. If we had lazy attributes, there would be no "good" reason for `ParentBased` samplers to support delegation based on the sampled flag.

2021-11-30 19:42 UTC, yurishkuro commented on specification/trace/tracestate-probability-sampling.md
> +
> can anyone remember why ParentBased has this facility to choose the delegating sampler based on the parent's sampled flag? It's risky

This PR/discussion notwithstanding, the original motivation for ParentBased was to support consistent head-based sampling, where if you have parent context, you just respect it without any additional sampling decisions, and if there isn't, you delegate to whichever sampler. This was the default behavior supported by most existing SDKs (Zipkin, Jaeger, OC -- in Jaeger it wasn't even configurable, it was built into the Tracer logic).

2021-11-30 21:29 UTC, oertl commented on specification/trace/tracestate-probability-sampling.md
> +
> the original motivation for ParentBased was to support consistent head-based sampling, where if you have parent context, you just respect it without any additional sampling decisions, and if there isn't, you delegate to whichever sampler. 

This could also be achieved with a consistent sampler that sets the sampling probability according to the parent's `p` value. Since `p` and `r` will be the same, the consistent sampling condition `r >= p` will lead to the same sampling decision as the parent. In case there is no parent, it could delegate to any other consistent sampler (e.g ConsistentProbabilityBased or ConsistentAlwaysOn).

2021-11-30 22:06 UTC, jmacd commented on specification/trace/tracestate-probability-sampling.md
> +
Thank you @yurishkuro. Given what we know, it's starting to look like the OTel-1.0 built-in `ParentBased` can and should be replaced by a more-primitive set of samplers. I want to find a way to avoid blocking this PR, and @oertl's suggestion is the way to go. `ConsistentParentProbabilityBased` only needs one parameter in the current framing, which is the sampler to use when the context is a root.

I'll find another place to discuss the larger issue. 

----

It looks like we ought to have two sampler APIs, one for root spans and one for non-root spans. A built-in sampler named `DelegatingSampler(root, localParent, remoteParent)` takes one root sampler and two non-root samplers and calls the appropriate one. A new non-root `FlagSampler` would simply honor the `sampled` flag and requires zero parameters. The default-parameter `ParentBased` Sampler is equivalent to `DelegatingSampler(root, localParent=FlagSampler(), remoteParent=FlagSampler())`.

Under this formulation, we'd have a zero-parameter non-root `ConsistentParentProbabilitySampler` which first validates the tracestate and then acts like `FlagSampler`. 

Returning to consistency problem that prompted this discussion (https://github.com/open-telemetry/opentelemetry-specification/pull/2047#discussion_r757691632), the problem stems from the `DelegatingSampler` aspect of `ParentBased`, and to enforce consistent adjusted counts will require consistency checking whenever non-root sampler delegation happens. We can say something like that for non-root sampler decisions, the delegating sampler MUST prevent bias (i.e., ensure consistency) and spell out the rules for doing so. I think they amount to preventing `r` and `p` values from changing except to permit explicit change of the sampled flag. If sampling changes from on (parent) to off (child), the effective behavior should be equivalent to `AlwaysOff`. If sampling changes from off (parent) to on (child), the effective behavior is spelled out in the composition rules: the context takes on zero adjusted count.

2021-11-30 22:08 UTC, jmacd commented on specification/trace/tracestate-probability-sampling.md
> +
I've changed the requirements as @oertl suggested.

2021-11-30 22:30 UTC, jmacd commented on specification/trace/tracestate-probability-sampling.md
> +
Leaving this comment thread open, now referred to by https://github.com/open-telemetry/opentelemetry-specification/pull/2047#discussion_r759697500.

2021-12-01 16:00 UTC, jmacd commented
@open-telemetry/specs-trace-approvers There are no outstanding comments on this PR and this design has already been through the OTEPs process. If there are reasons not to merge this work, please speak up, otherwise please approve.

2021-12-01 16:26 UTC, oertl approved these changes

2021-12-02 06:11 UTC, carlosalberto approved these changes

2021-12-02 06:21 UTC, carlosalberto commented
Sorry for the late review. LGTM!

As a follow up I'd love to have a few clarifications for probabilistic sampling newcomers (like me) - I will create an issue after this PR is merged.

Namely:

* Even though there are value tables, I feel actual examples of P/R values in a trace/spans would be a great thing to have.
* I feel there are some places where the special case of the R-value being `63` could be more concise/clear, e.g. `The adjusted count of spans sampled by a non-probability sampler is unknown.` and then `A special p-value of 63 is defined to mean zero adjusted count...`.
* In the R-value section there is a value table with “probability of r” and “implied sampling probabilities” columns, and the related values may not be super clear during a first read.

2021-12-07 00:33 UTC, jmacd commented
Thanks @carlosalberto 
Please see: 0c2b1cd 318bdd2 5879cfa

2021-12-08 18:09 UTC, PeterF778 commented on specification/trace/tracestate-probability-sampling.md
> +r-value 62 which will sample every span.
There's still a corner case of ConsistentAlwaysOffSampler which will not sample even for r-value of 62.

2021-12-09 22:54 UTC, jmacd commented on specification/trace/tracestate-probability-sampling.md
> +r-value 62 which will sample every span.
Thank you @PeterF778, please see if 7c374c2 helps.

2021-12-09 23:14 UTC, jmacd commented
@open-telemetry/specs-trace-approvers I've added a few more examples.

2021-12-10 20:06 UTC, jmacd commented
@yurishkuro Because you reviewed the OTEPs on this topic, will you please review the finished specification? The Sampling SIG would like to focus on configurable samplers (a.k.a., span "Views"), and as far as I can tell there's nothing left to do here. After this merges we can lobby the W3C trace context group to add support for embedding r-value in the TraceId using a new trace flag, when there is sufficient randomness, after which point the cost of probability sampling and transmitting adjusted counts will be 0 for untraced contexts.

2021-12-17 19:17 UTC, bdarfler reviewed
@jmacd here is my offering of a short overview section. Feel free to adapt as you see fit. I tried to borrow heavily from #2224.

2021-12-17 19:17 UTC, bdarfler commented on specification/trace/tracestate-probability-sampling.md
> +
```suggestion

### Overview

This document specifies an approach to sampling based on an "r-value" and a 
"p-value". At a very high level the "r-value" is a source of randomness and the 
"p-value" encodes the sampling probability. A span is then sampled if `p <= r`.

For efficient representation, the number of supported sampling probabilities is limited 
to powers-of-two. Rather than encoding the sampling probably directly, the "p-value" 
represents the base-2 exponent of the sampling probability. The true sampling 
probability is then `2**p`.

Since the W3C trace context does not specify that any of the 128 bits in a TraceID are
true uniform-distributed random bits, the "r-value" is introduced as an additional source
of randomness is. The amount of randomness in the "r-value" is then tailored to the 
number of supported sampling probabilities. This allows the r-value to be represented 
in just 6-bits.

Finally, by including the "r-value" and "p-value" in the `tracestate`, these two values 
automatically propagate through the context and are recorded on every span. This 
allows Trace consumers to correctly count spans by recognizing the "p-value" on
a given span.

```

2022-01-04 18:28 UTC, bogdandrutu commented on specification/trace/tracestate-probability-sampling.md
> +##### Requirement: ConsistentProbabilityBased sampler unsets p when not sampling
"Sampling" sounds like the process, should this be "sampled"?

2022-01-04 18:28 UTC, bogdandrutu commented on specification/trace/tracestate-probability-sampling.md
> +configured with greater sampling probability.
is the current `TraceIdRatioBased` not a consistent probability sampler? It feel it is based on your requirements, then the problem is that the `ConsistentProbabilityBased` suggests that the current `TraceIdRatioBased` is not.

2022-01-04 18:28 UTC, bogdandrutu commented on specification/trace/tracestate-probability-sampling.md
> +complete subtraces are [discussed below](#trace-producer-completeness).
OpenCensus had a "number" of child spans, to make this a two way check. Please think if that would help.

2022-01-04 18:29 UTC, jmacd commented on specification/trace/tracestate-probability-sampling.md
> +
I integrated your text and the other few leading paragraphs, see how this looks?

2022-01-04 18:32 UTC, jmacd commented on specification/trace/tracestate-probability-sampling.md
> +##### Requirement: ConsistentProbabilityBased sampler unsets p when not sampling
Fixed (twice).

2022-01-04 18:34 UTC, bogdandrutu commented on specification/trace/tracestate-probability-sampling.md
> +R-value determines which sampling probabilities and will not sample
I also have hard time reading this.

2022-01-04 18:34 UTC, jmacd commented on specification/trace/tracestate-probability-sampling.md
> +configured with greater sampling probability.
I think we could say it was _intended to be_ the definition given here, but the TODO and WARNING in the current specification are not so easily fixed without making changes at the W3C level. This specification is a deliberate compromise.

2022-01-04 18:38 UTC, jmacd commented on specification/trace/tracestate-probability-sampling.md
> +complete subtraces are [discussed below](#trace-producer-completeness).
I documented this in OTEP 170:

> One approach,
[lost in the transition from OpenCensus to OpenTelemetry is to count
the number of children of each
span](https://github.com/open-telemetry/opentelemetry-specification/issues/355).

Let's use https://github.com/open-telemetry/opentelemetry-specification/issues/355 for this topic.

2022-01-04 18:52 UTC, jmacd commented on specification/trace/tracestate-probability-sampling.md
> +R-value determines which sampling probabilities and will not sample
I rewrote this sentence as:

R-value determines which sampling probabilities will decide to sample
or not decide to sample for spans of a given trace, as follows:

2022-01-04 23:04 UTC, bogdandrutu reviewed
Overall these looks great as a starting point. I wish we could merge more the current samplers with the newly proposed once, but maybe we can do that as a followup before marking this as stable and once we have couple of concrete prototypes.

2022-01-05 03:21 UTC, jmacd commented on specification/trace/tracestate-probability-sampling.md
> +`ParentConsistentProbabilityBased` Sampler is called for a root span.
Discussed here: https://github.com/open-telemetry/opentelemetry-specification/pull/2047#discussion_r759697500

I documented this in issue #2179.

2022-01-05 03:22 UTC, jmacd commented on specification/trace/tracestate-probability-sampling.md
> +order to signal unknown adjusted count.
That is correct. There is no contradiction here.

2022-01-05 03:22 UTC, jmacd commented on specification/trace/tracestate-probability-sampling.md
> +#### ParentConsistentProbabilityBased sampler
I described what I hoped we can do in #2179.

2022-01-05 03:24 UTC, jmacd commented on specification/trace/tracestate-probability-sampling.md
> +`sampled` flag in the W3C traceparent.
I prefer the proposed `DelegatingSampler` concept in #2179.  I don't think the `TextMapPropagator` interface as specified has access to the `sampled` flag.

2022-01-05 03:26 UTC, jmacd commented on specification/trace/tracestate-probability-sampling.md
> +tracestate: ot=r:5;p:2
This was an arbitrary decision, not easily made. In other versions of this proposal I've specified base16 because that's how `traceparent` is specified, but in the specification of `./tracestate-handling.md` it just permits alpha-numeric characters and the choice of number base is not fixed by the format.

2022-01-05 22:19 UTC, jmacd commented on specification/trace/tracestate-probability-sampling.md
> +configured with greater sampling probability.
I take it your goal is to keep two primary samplers, which are today TraceIDRatioBased and ParentBased. I agree these are the two important concepts. There have been disagreements over whether the new functionality should be on-by-default or an option; since this is still experimental, my goal was to provide always-on probability samplers, not to entertain the possibility of _turning it off_ as an option.

Simply, I'd rather have two samplers than one sampler with two behaviors as an option. However, if we could agree to have the functionality on by default, which I think means waiting for a W3C trace flag to encode r-value in the TraceID, then it would make sense to roll probability sampling into the built-in samplers.

Also #2179 mentions how `ParentBased` has an API specified that unintentionally breaks probability sampling and proposes a fix. If we accept the proposed fixes, and standardize a W3C randomness flag, the outcome you are looking for will likely happen.

2022-01-05 22:19 UTC, jmacd commented on specification/trace/tracestate-probability-sampling.md
> +order to signal unknown adjusted count.
Note this is the basis of saying that you can modify only the root to use probability sampling, all the existing ParentBased samplers will do the right thing by default. It's the ParentBased options that create trouble, see #2179.

2022-01-05 22:19 UTC, jmacd commented on specification/trace/tracestate-probability-sampling.md
> +valid `tracestate`.
I believe you would configure a ConsistentProbabilitySampler (i.e., ignore the parent decision) if you want to change p to capture a sub-trace.

2022-01-05 22:19 UTC, jmacd commented on specification/trace/tracestate-probability-sampling.md
> +tracestate: ot=r:3;p:63
```suggestion
tracestate: ot=r:4;p:63
```

2022-01-06 01:14 UTC, bogdandrutu commented on specification/trace/tracestate-probability-sampling.md
> +tracestate: ot=r:5;p:2
Probably we should do it since otherwise this cannot be put on the wire correct?

2022-01-07 16:35 UTC, jmacd commented
@bogdandrutu I'm leaving open the discussions you opened above. I wonder if issues #2224 and #2179 capture enough of the state required to understand these compromises that you would consider approving this in its current form?

2022-01-07 16:37 UTC, jmacd commented on specification/trace/tracestate-probability-sampling.md
> +tracestate: ot=r:5;p:2
Are you saying we should use base64 for `r` and `p`? I am not sure that the characters for code 62 and 63 are currently allowed by our `tracestate-handling.md` spec, and this makes it less readable to humans. I can be convinced this is OK. OTOH, if we ever admit a "directly-stated" adjusted count option such as `c:15` (e.g., discussed in #2224), I would argue it should be decimal because it's meant to be somewhat human-readable.

2022-01-07 19:21 UTC, PeterF778 commented on specification/trace/tracestate-probability-sampling.md
> +tracestate: ot=r:5;p:2
I think both r and p should be encoded as decimals. There's hardly anything to gain with alternate encodings, and readability would suffer.

2022-01-10 17:20 UTC, bogdandrutu approved these changes
Happy to approve as long as we make sure we resolve the 2 issues you pointed before stable.

2022-01-10 18:07 UTC, ocelotl requested changes

2022-01-10 18:07 UTC, ocelotl commented on specification/trace/tracestate-probability-sampling.md
> +bits.  See the appendix for details.
```suggestion
bits.
```

That suggestion should be added outside this normative seciton.

2022-01-10 18:07 UTC, ocelotl commented on specification/trace/tracestate-probability-sampling.md
> +A test specification for this requirement is given in the appendix.
```suggestion
```

2022-01-10 18:07 UTC, ocelotl commented on specification/trace/tracestate-probability-sampling.md
> +root span and MAY warn the user that a potentially inconsistent trace
Two RFC keywords are present in this normative section, this should be separated in two.

2022-01-12 00:56 UTC, ocelotl reviewed
Changing to comment instead of requesting changes since these are not critical changes needed.

2022-01-12 00:57 UTC, ocelotl approved these changes

2022-01-18 17:51 UTC, jmacd commented on specification/trace/tracestate-probability-sampling.md
> +bits.  See the appendix for details.
I removed this sentence. The reader will have to keep reading. :-)

2022-01-18 17:51 UTC, jmacd commented on specification/trace/tracestate-probability-sampling.md
> +A test specification for this requirement is given in the appendix.
Done.

2022-01-18 17:51 UTC, jmacd commented on specification/trace/tracestate-probability-sampling.md
> +root span and MAY warn the user that a potentially inconsistent trace
I changed the MAY into a SHOULD by making this requirement compound, as in "SHOULD do A and B" instead of "SHOULD do A and MAY do B". 

Error handling doesn't really need to be specified, there are guidelines in place. I think this is OK.

2022-01-18 18:47 UTC, ocelotl approved these changes

2022-01-18 20:43 UTC, oertl approved these changes

2022-01-24 16:27 UTC, jmacd commented
@open-telemetry/specs-trace-approvers This meets our minimum criteria for merging. I have been trying to get more stamps of approval, but it's not happening (or not happening quickly). I propose to merge this PR.

2022-01-24 18:29 UTC, codeboten approved these changes

2022-01-25 16:37 UTC, reyang approved these changes

2022-01-26 01:18 UTC, mtwo commented
Looks good, a bit long but that's likely necessary given the topic. I couldn't find an example for what I suspect might be a common scenario: when an edge service uses a probability-based sampler but a downstream service decides to sample when it sees a trace with a sampled flag OR some other condition is satisfied (an error, for example).

I think (?) that this is similar to the "interoperability with TraceIDRatioBased sampler" example, though the second sampler in that case uses different criteria.

2022-01-26 01:18 UTC, mtwo approved these changes
Looks good, a bit long but that's likely necessary given the topic. I couldn't find an example for what I suspect might be a common scenario: when an edge service uses a probability-based sampler but a downstream service decides to sample when it sees a trace with a sampled flag OR some other condition is satisfied (an error, for example).

I think (?) that this is similar to the "interoperability with TraceIDRatioBased sampler" example, though the second sampler in that case uses different criteria.

2022-01-26 19:24 UTC, jmacd commented
@mtwo There isn't an exact example corresponding to your question. The section "Example: Probability and non-probability sampler in a root context" comes close, and there is a related discussion in #2179. As discussed in the issue, a better Delegating sampler API would be nice, but is not critical to the answer here. Sampler API details aside (it's a bit messy, we could use a v2 API proposal to clear things up--see #2179), the child span is expected to have adjusted count equal to the parent when the span is sampled, and adjusted count 0 when the parent was not sampled but there were errors (`p=63`).

2022-01-26 21:02 UTC, carlosalberto commented
We have more than enough reviews and no standing questions. Let's merge this now and address any improvements in future PRs.

2022-01-26 21:02 UTC, merged