no-op StartSpan: always return the parent
open-telemetry/opentelemetry-specification pull request #2121
Opened 2021-11-13 00:08 UTC by tsloughter

## Changes

This change makes it so no span id generation is required in the API's no-op tracer. My understanding from the discussion back when this part was added to the spec the implementation is supposed to create a new span id in the no-op tracer if the parent is a recording span -- while saying this is almost never the case it still would require it to be possible.

This is what we had implemented in the Erlang API:

```
    %% Spec: Behavior of the API in the absence of an installed SDK
    case otel_tracer:current_span_ctx(Ctx) of
        Parent=#span_ctx{trace_id=TraceId,
                         is_recording=false} when TraceId =/= 0 ->
            %% if the parent is a non-recording Span it MAY return the parent Span
            Parent;
        Parent=#span_ctx{trace_id=TraceId} when TraceId =/= 0 ->
            %% API MUST create a non-recording Span with the SpanContext in the parent Context
            SpanCtx = Parent#span_ctx{span_id=opentelemetry:generate_span_id(),
                                      is_recording=false},
            SpanCtx;
        _ ->
            %% If the parent Context contains no valid Span,
            %% an empty non-recording Span MUST be returned
            ?NOOP_SPAN_CTX
    end.
```

After implementing configurable IdGenerators which required moving the id generators to the SDK, https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk.md#id-generators, I realized the above code could no longer be possible and would not make sense even if it were.

Go and Java both always return the parent or the empty non-recording span, and maybe others. If this is the case for those two and others then this change is an attempt to bring the spec inline with existing implementations. So I think that makes it a non-breaking change :)

2021-11-16 18:26 UTC, bogdandrutu commented on specification/trace/api.md
> +`Span` in the parent `Context` (whether explicitly given or implicit current).
What do we do in the "extractor" part I think is missing from here.

2021-11-19 19:43 UTC, tsloughter commented on specification/trace/api.md
> +`Span` in the parent `Context` (whether explicitly given or implicit current).
The extractor part doesn't change. It still extracts the propagated trace context to a non-recording span as before.

2021-11-29 23:30 UTC, bogdandrutu approved these changes

2021-11-30 06:17 UTC, iNikem approved these changes

2021-11-30 18:11 UTC, jmacd approved these changes

2021-11-30 18:11 UTC, jmacd commented on specification/trace/api.md
> +and that is related to propagation of a `SpanContext`: The API MUST return the
```suggestion
and that is related to propagation of a `SpanContext`: The Tracer API to get the `Span` from the `Context` MUST return the
```

2021-11-30 22:10 UTC, tsloughter commented on specification/trace/api.md
> +and that is related to propagation of a `SpanContext`: The API MUST return the
This isn't the API for getting the Span from the Context but is the API for starting a Span.

2021-12-01 09:14 UTC, Oberon00 requested changes

2021-12-01 09:14 UTC, Oberon00 commented on specification/trace/api.md
> -This means that operations on a Tracer, or on Spans, should have no side effects and do nothing. However, there
Can you try to do the change without additional line-break changes? This way it will be easier to spot the differences.

2021-12-01 09:14 UTC, Oberon00 commented on specification/trace/api.md
> +`Span` in the parent `Context` (whether explicitly given or implicit current).
I would like to preserve the post-condition that a Span returned by a no-op tracer is always non-recording:

```suggestion
and that is related to propagation of a `SpanContext`: The API MUST return a
non-recording `Span` with the `SpanContext` in the parent `Context` (whether explicitly given or implicit current).
If the `Span` in the parent `Context` is already non-recording, it SHOULD be returned directly
without instantiating a new `Span`.
```

This could be achieved by using the mechanisms for "wrapping a SpanContext in a Span".

2021-12-01 18:20 UTC, tsloughter commented on specification/trace/api.md
> +`Span` in the parent `Context` (whether explicitly given or implicit current).
I was wondering about that. So should the parent be set to non-recording even if it was recording?

2021-12-01 19:00 UTC, jmacd approved these changes

2021-12-01 19:00 UTC, jmacd commented on specification/trace/api.md
> +`Span` in the parent `Context` (whether explicitly given or implicit current).
> This could be achieved by using the mechanisms for "wrapping a SpanContext in a Span".

I also noticed the relationship, I guess you could write "if the parent-span is already non-recording the SDK MUST behave as if wrapping the parent's span context in a span". I think that's less clear, and wish to accept this suggestion and then merge this PR.

2021-12-02 07:39 UTC, Oberon00 approved these changes

2021-12-02 18:36 UTC, carlosalberto approved these changes

2021-12-02 19:15 UTC, merged

2021-12-03 00:14 UTC, carlosalberto commented
Hey, we forgot to add a CHANGELOG entry! @tsloughter think you could cook one?

2021-12-03 11:57 UTC, tsloughter commented
@carlosalberto woops, yup, will open a PR in a minute.