Mark Metrics SDK as Stable
open-telemetry/opentelemetry-specification pull request #2150
Opened 2021-11-23 06:19 UTC by reyang

This moves the Metrics SDK specification to Stable:
1. Once the spec is marked as "Stable", **breaking changes are no longer allowed**.
2. Additive changes are allowed.

These are the issues that should be resolved before we could merge this PR:
https://github.com/open-telemetry/opentelemetry-specification/issues?q=is%3Aissue+is%3Aopen+label%3Aspec%3Ametrics+label%3Arelease%3Arequired-for-ga+-label%3Aarea%3Asemantic-conventions

2021-11-23 22:42 UTC, MrAlias reviewed
I am not able to approve this as the Go implementation is still being built.

2021-11-23 23:41 UTC, tigrannajaryan commented
> I am not able to approve this as the Go implementation is still being built.

I believe this change says the SDK spec is stable. It does not mean that the SDK implementations are stable.

2021-11-24 00:13 UTC, MrAlias commented
> > I am not able to approve this as the Go implementation is still being built.
> 
> I believe this change says the SDK spec is stable. It does not mean that the SDK implementations are stable.

Right, sorry, I wasn't clear. Without an implementation it is hard to say if this specification should be marked stable, specifically from the Go SIGs perspective. There are possibilities that parts of the specification are not implementable in the Go implementation. If that is the case there may need to be modifications that would not be compliant with our stability guarantee.

2021-11-24 02:02 UTC, carlosalberto commented
@jmacd you have been prototyping something for Go, right?

2021-11-24 02:54 UTC, anuraaga commented
There are a couple of TODOs in `sdk.md` they make the file "feel" not stable - perhaps they should be moved to issues and removed?

2021-11-24 05:37 UTC, reyang commented
> There are a couple of TODOs in `sdk.md` they make the file "feel" not stable - perhaps they should be moved to issues and removed?

There are two places where we have `TODO`s, and both of them are post-Stable topics (and have issues tracking them).

It seems to be an _okay_ practice? - we've discussed this in the previous Metrics SIG meeting and actually confirmed that the [Stable tracing spec](https://github.com/open-telemetry/opentelemetry-specification/blob/29e776a160893e155fe9d59e9675524035821920/specification/trace/sdk.md) also has `TODO`s.

2021-11-24 05:50 UTC, reyang commented
> > > I am not able to approve this as the Go implementation is still being built.
> > 
> > 
> > I believe this change says the SDK spec is stable. It does not mean that the SDK implementations are stable.
> 
> Right, sorry, I wasn't clear. Without an implementation it is hard to say if this specification should be marked stable, specifically from the Go SIGs perspective. There are possibilities that parts of the specification are not implementable in the Go implementation. If that is the case there may need to be modifications that would not be compliant with our stability guarantee.

We've discussed this in the previous Spec SIG meeting. In order to mark the spec as Stable, the following things are required:
1. All the issues that are tagged as `area:sdk` + `spec:metrics` + `release:required-for-ga` are resolved.
2. The Metrics SIG has a good confidence that the spec won't have breaking changes.
3. There are multiple (e.g. 3) language SIGs which are able to follow the spec and implement the metrics SDK.

These are non-goal for Stable:
1. All languages SIGs could finish the implementation.
2. All the clarification questions are answered. Many of them are nice-to-have and can be post Stable (e.g. `area:allowed-for-ga` or `area:after-ga` or `editorial`).

2021-11-29 18:33 UTC, reyang commented on specification/metrics/sdk.md
> +  * **Status**: [Experimental](../document-status.md) - the `extra dimensions`
@anuraaga FYI.

2021-11-29 19:23 UTC, cijothomas approved these changes
LGTM.

2021-11-29 19:26 UTC, cijothomas commented
The data model and proto are stable already, so can we also mark the exporters , except Prometheus, (i.e [OTLP](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk_exporters/otlp.md) , stdout, inmemory) as stable as well? (separate topic, but related,  hence mentioning it here.)

2021-11-29 19:42 UTC, reyang commented
> The data model and proto are stable already, so can we also mark the exporters , except Prometheus, (i.e [OTLP](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk_exporters/otlp.md) , stdout, inmemory) as stable as well? (separate topic, but related, hence mentioning it here.)

#2175

2021-11-30 00:28 UTC, carlosalberto approved these changes

2021-11-30 00:28 UTC, carlosalberto commented
Sounds like a good trade off going forward!

2021-11-30 05:18 UTC, anuraaga approved these changes

2021-12-01 00:18 UTC, jack-berg approved these changes

2021-12-01 17:55 UTC, jmacd approved these changes
I propose several components remain in Feature-freeze. This topic was discussed by the technical committee today and the consensus is that we believe the specification is practically Stable, but that an uninitiated member of the community could probably not implement it from scratch in a way that conforms with our group understanding.

We expect to do a bit of editorial work on this specification as the next 1 or 2 prototypes are completed, and then we can finish marking this Stable.

2021-12-01 17:55 UTC, jmacd commented on specification/metrics/sdk.md
> +**Status**: [Stable](../document-status.md)
```suggestion
**Status**: [Feature-freeze](../document-status.md)
```

2021-12-01 17:55 UTC, jmacd commented on specification/metrics/sdk.md
> +**Status**: [Stable](../document-status.md)
```suggestion
**Status**: [Feature-freeze](../document-status.md)
```

2021-12-01 17:55 UTC, jmacd commented on specification/metrics/sdk.md
> +**Status**: [Stable](../document-status.md)
```suggestion
**Status**: [Feature-freeze](../document-status.md)
```

2021-12-01 17:56 UTC, jmacd requested changes
@open-telemetry/technical-committee as discussed I think we can merge this PR after accepting the three changes proposed by me.

2021-12-01 17:57 UTC, jmacd commented
@cijothomas please take a look at my proposal for merging this PR.

2021-12-01 18:08 UTC, cijothomas commented
> @cijothomas please take a look at my proposal for merging this PR.

[This](https://github.com/open-telemetry/opentelemetry-specification/pull/2175#issuecomment-983880044) comment was calling out that, the Exporter section of the SDK spec is not stable, so the exporters themselves (OTLP/Stdout/InMemory), should not be marked stable.

2021-12-01 18:36 UTC, jmacd commented
> Exporter section of the SDK spec is not stable, so the exporters themselves (OTLP/Stdout/InMemory), should not be marked stable.

I'm not sure I agree -- can't a specific exporter specification be stable even if the general interface specification is not? For components of an SDK I see this dependency being real (i.e., an SDK exporter can't be stable of other components it depends on are not stable), but for a specification I don't see a hard connection there. 

E.g., the stderr exporter says the "StderrExporter is an Exporter". This is true and stable and will not change even if we change the specification for Exporter, right?

2021-12-01 18:44 UTC, jmacd requested changes
With the suggestion to leave MeterProvider in Feature-freeze, these two sections are redundant.

2021-12-01 18:44 UTC, jmacd commented on specification/metrics/sdk.md
> +  * **Status**: [Feature-freeze](../document-status.md) - the `extra dimensions`
```suggestion
  * the `extra dimensions`
```

2021-12-01 18:44 UTC, jmacd commented on specification/metrics/sdk.md
> +  * **Status**: [Feature-freeze](../document-status.md) - the
```suggestion
  * the
```

2021-12-17 03:17 UTC, closed without merging