Define semantic conventions and instrumentation stability
open-telemetry/opentelemetry-specification pull request #2180
Opened 2021-11-30 23:52 UTC by tigrannajaryan

Summary of changes:

- Explain that schemas define what changes are allowed.
- Clarify that additive changes are an exception and are always allowed.
- Prohibit instrumentation changes until July 1, 2022 to allow recipients
  (backends/vendors) to start understanding Schema URLs/Schema Files.

2021-12-01 02:23 UTC, pyohannes commented on specification/versioning-and-stability.md
> +- Renaming of metrics
```suggestion
- Renaming of metrics.
```

2021-12-01 02:23 UTC, pyohannes commented on specification/versioning-and-stability.md
> +capable of describing such changes.
Can such changes be made if the major version number is incremented?

2021-12-01 02:23 UTC, pyohannes commented on specification/versioning-and-stability.md
> +instrumentations, such as OpenTelemetry SDKs.
I'm a bit confused by calling OpenTelemetry SDKs "instrumentations". Is "instrumentations" synonymous with [instrumentation libraries](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/glossary.md#instrumentation-library)?

2021-12-01 14:59 UTC, tigrannajaryan commented on specification/versioning-and-stability.md
> +URL in the produced telemetry or no.
>Is this saying that if an OpenTelemetry SDK is incorrectly producing telemetry not described in semantic conventions, it must continue to do so indefinitely?

Not indefinitely. The produced telemetry can be added to the semantic conventions and after that changes to that telemetry can be described by schemas.

This only says that telemetry that for some reason did not follow the rules and is not described in the semantic conventions must be kept unchanged to avoid breaking recipients. Once it begins to follow the rules and is part of conventions it is back on track to be handled the normal way via schemas.

2021-12-01 15:25 UTC, tigrannajaryan commented on specification/versioning-and-stability.md
> +capable of describing such changes.
I think the answer in theory is yes, but we already have this in the doc:
>Note that we currently have no plans for creating a major version of OpenTelemetry past v1.0.

If this plan changes we should also rethink what happens with semantic conventions.

2021-12-01 15:26 UTC, tigrannajaryan commented on specification/versioning-and-stability.md
> +URL in the produced telemetry or no.
Added a sentence to clarify this. Let me know if it helps.

2021-12-01 15:26 UTC, tigrannajaryan commented on specification/versioning-and-stability.md
> +- Renaming of metrics
Fixed.

2021-12-01 15:28 UTC, tigrannajaryan commented on specification/versioning-and-stability.md
> +instrumentations, such as OpenTelemetry SDKs.
Reworded. See if it is clearer now.

2021-12-01 16:41 UTC, jsuereth submitted a review, later dismissed
ADDITIVE changes to metrics can break user alerts by creating new timeseries and adjusting thresholds.  I think we need to be a lot more careful around changes, particularly around metrics here.

2021-12-01 17:02 UTC, tigrannajaryan commented
> ADDITIVE changes to metrics can break user alerts by creating new timeseries and adjusting thresholds. I think we need to be a lot more careful around changes, particularly around metrics here.

@jsuereth I can change the PR to explicitly prohibit this but I think this contradicts with an existing understanding that attributes are optional, see this discussion https://github.com/open-telemetry/opentelemetry-specification/issues/2077

2021-12-01 19:12 UTC, tigrannajaryan commented
> ADDITIVE changes to metrics can break user alerts by creating new timeseries and adjusting thresholds. I think we need to be a lot more careful around changes, particularly around metrics here.

@jsuereth I modified the PR to disallow addition of new attributes to existing metrics. PTAL.

2021-12-02 00:32 UTC, jsuereth reviewed
thanks for resolving my blocking comment!   I still have some concerns, but not as strongly blocking :)

For clarity - I agree with the sentiment and goal of this PR and approve, just nits on details/scope of what's stated here, including implications on instrumentation development.

2021-12-02 00:32 UTC, jsuereth commented on specification/versioning-and-stability.md
> +- Adding new attributes to the existing semantic conventions for resources,
For the purpose of expediency we should disallow adding new attributes to resources UNTIL we've figured out meta-issues around how that correlates with metrics, e.g. [this one](https://github.com/open-telemetry/opentelemetry-specification/issues/1782) on mapping resource into prometheus.

2021-12-02 00:32 UTC, jsuereth commented on specification/versioning-and-stability.md
> +capable of describing such changes.
+1 to @tigrannajaryan's response here.   (1) Yes if we break anything it's a major version number but (2) stability-is-a-feature.   We should strive to avoid any significant breaking of our API (where API => usages of telemetry) here

2021-12-02 00:32 UTC, jsuereth commented on specification/versioning-and-stability.md
> +OpenTelemetry instrumentations SHOULD NOT produce telemetry that is not
How does this statement align with our goal of prototyping instrumentation *prior* to specification.


Additionally, how does it align with the specification being a "minimal" standard with expansion possible on case-by-case basis (e.g. MySQL instrumentation vs. "DB" instrumentation).


I have concerns that instrumentaiton-itself is *expensive*, for us and for users.   This kind of lockdown makes sense from one point of view, but I think is highly restrictive on instrumentation authors, and puts huge bars on OTel-delivered instrumentation.

Can we somehow rephrase this to allow prototyping/experimentation within the otel project (in additon to non-otel projects) around instrumentation?

2021-12-02 00:42 UTC, pyohannes commented on specification/versioning-and-stability.md
> +instrumentations, such as OpenTelemetry SDKs.
It's somewhat clearer. I assume "instrumentation libraries that are part of OpenTelemetry" comprise all instrumentation libraries in `opentelemetry-*` repositories, like [opentelemetry-dotnet](https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/src), [opentelemetry-java-instrumentation](https://github.com/open-telemetry/opentelemetry-java-instrumentation), [opentelemetry-dotnet-contrib](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/tree/main/src), or [opentelemetry-cpp-contrib](https://github.com/open-telemetry/opentelemetry-cpp-contrib/tree/main/instrumentation).

2021-12-02 00:44 UTC, pyohannes commented on specification/versioning-and-stability.md
> +#### Telemetry Stability
I guess this note can be removed in this PR:

> NOTE: Until telemetry stability is defined, Contrib instrumentation MUST NOT be marked as stable. See below.

2021-12-02 03:44 UTC, tigrannajaryan commented on specification/versioning-and-stability.md
> +- Adding new attributes to the existing semantic conventions for resources,
This is a good point. It is unfortunate that we have to disallow this. Let me think and see if there is a workaround possible.

2021-12-02 08:10 UTC, Oberon00 commented on specification/versioning-and-stability.md
> +- Adding new attributes to the existing semantic conventions for resources,
Couldn't we just add new resource attributes and metric labels (or just everything new) to the schema?

2021-12-02 15:54 UTC, kenfinnigan commented on specification/versioning-and-stability.md
> +URL in the produced telemetry or no.
Thanks!

2021-12-02 17:33 UTC, tigrannajaryan commented on specification/versioning-and-stability.md
> +instrumentations, such as OpenTelemetry SDKs.
Yes, that's correct.

2021-12-02 17:34 UTC, tigrannajaryan commented on specification/versioning-and-stability.md
> +- Adding new attributes to the existing semantic conventions for resources,
@Oberon00 we can if we introduce such an operation in schema files. Currently it is not possible. To introduce it we need to add a new revision of schema files. It is doable if we think it is necessary. So far I refrained adding capabilities to schema files for which I did not see a clear demand.

2021-12-02 17:47 UTC, tigrannajaryan commented on specification/versioning-and-stability.md
> +OpenTelemetry instrumentations SHOULD NOT produce telemetry that is not
Good point. Added an exception `unless the instrumentation is clearly marked as unstable`. Does this help? Prototypes obvious are unstable so this should cover it.

2021-12-02 17:48 UTC, tigrannajaryan commented on specification/versioning-and-stability.md
> +#### Telemetry Stability
Good catch. Removed and added a reference from here to the Telemetry Stability section.

2021-12-06 01:06 UTC, jsuereth commented on specification/versioning-and-stability.md
> +OpenTelemetry instrumentations SHOULD NOT produce telemetry that is not
I think it's ok for now, we can debate if we need to lossen this. In practice, it's only as good as folks are willing to experiment :)

2021-12-06 15:25 UTC, tigrannajaryan commented on specification/versioning-and-stability.md
> +allowed to change the produced telemetry after July 1, 2022 if both of the
Is this a sufficient notice? It may not be enough since implement support for schemas may take time.

2021-12-10 03:45 UTC, trask commented
Can you clarify how this applies to auto-instrumentation distributions?

Should we hide all telemetry producing auto-instrumentation in a distribution behind an experimental flag, and only enable them by default once their respective semantic conventions have reached stability and we can commit to telemetry stability?

2021-12-10 13:59 UTC, tigrannajaryan commented
> Can you clarify how this applies to auto-instrumentation distributions?
> 
> Should we hide all telemetry producing auto-instrumentation in a distribution behind an experimental flag, and only enable them by default once their respective semantic conventions have reached stability and we can commit to telemetry stability?

No, I believe it is fine to produce telemetry from auto-instrumentation. This PR only says that after you declare your auto-instrumentation "Stable" you cannot change the produced telemetry until certain conditions are met (SchemaURL in the output and wait until certain date). If the text in the PR is unclear I will fix it. Let me know which part you find unclear.

2021-12-10 17:04 UTC, jack-berg commented on specification/versioning-and-stability.md
> +the instrumentation includes the Schema URL in the produced telemetry or no.
```suggestion
the instrumentation includes the Schema URL in the produced telemetry or not.
```

2021-12-10 17:06 UTC, jack-berg commented on specification/versioning-and-stability.md
> +clearly marked as unstable. If, however, this rule is broken the
How does instrumentation indicate that its unstable? Is there some sort of marker in the exported data? Could we include a special schema url that indicates instability?

2021-12-10 17:07 UTC, jack-berg commented on specification/versioning-and-stability.md
> +  spans, span events or log records.
Are metrics intentionally omitted from this list? Metrics are included in a similar list on line [215](https://github.com/open-telemetry/opentelemetry-specification/pull/2180/files#diff-e7de8bed9eb1605a44c385930415011d900acccecc8b48398a75ce9fa707cdd3R215-R216) which is confusing.

2021-12-10 17:13 UTC, tigrannajaryan commented on specification/versioning-and-stability.md
> +  spans, span events or log records.
Yes, metrics are intentionally omitted. Adding a new attribute to a metric is considered a breaking change. See https://github.com/open-telemetry/opentelemetry-specification/pull/2180#pullrequestreview-820513856
I will fix line 215.

2021-12-10 19:37 UTC, tigrannajaryan commented on specification/versioning-and-stability.md
> +clearly marked as unstable. If, however, this rule is broken the
Is there a need to indicate this to the receivers? Potentially lack of SchemaURL in the telemetry or version number <1.0 can be these indicators.

2021-12-10 19:59 UTC, trask commented
> > Can you clarify how this applies to auto-instrumentation distributions?
> > Should we hide all telemetry producing auto-instrumentation in a distribution behind an experimental flag, and only enable them by default once their respective semantic conventions have reached stability and we can commit to telemetry stability?
> 
> No, I believe it is fine to produce telemetry from auto-instrumentation. This PR only says that after you declare your auto-instrumentation "Stable" you cannot change the produced telemetry until certain conditions are met (SchemaURL in the output and wait until certain date). If the text in the PR is unclear I will fix it. Let me know which part you find unclear.

For individual instrumentations, we use the version number to "clearly mark" them as unstable, e.g. `0.x` or `1.x-alpha`.

For distributions (e.g. the opentelemetry javaagent), should we be marking them as "unstable" (e.g. `0.x` or `1.x-alpha`) if they emit any unstable instrumentation?

2021-12-10 20:03 UTC, tigrannajaryan commented on specification/versioning-and-stability.md
> +the instrumentation includes the Schema URL in the produced telemetry or no.
Fixed.

2021-12-10 20:12 UTC, tigrannajaryan commented on specification/versioning-and-stability.md
> +  spans, span events or log records.
Should be fixed now, PTAL.

2021-12-10 20:23 UTC, tigrannajaryan commented
> For individual instrumentations, we use the version number to "clearly mark" them as unstable, e.g. `0.x` or `1.x-alpha`.
> 
> For distributions (e.g. the opentelemetry javaagent), should we be marking them as "unstable" (e.g. `0.x` or `1.x-alpha`) if they emit any unstable instrumentation?

The "unstable" vs "stable" labeling of a library or of a package (or individual instrumentations if that's the granularity of labeling you choose to maintain) is done based on the fact whether you are able to take the responsibility to fulfill the requirements of the "stable" labeling. What "stable" label means is described in this document.

Particularly with regards to telemetry emitted by the instrumentation this document (after accepting this PR) says that if you label the instrumentation "stable" then you must fulfil the following obligation:
- If you are not including Schema URL in the emitted telemetry then you are not allowed to modify the telemetry (with certain exceptions carved out in the doc).
- If you are including Schema URL then you are allowed to modify the telemetry after certain date, provided that they are described by a published Schema File (with the same exceptions as above applicable).

If you are not labeling the instrumentation as "stable" then you free to do whatever you want. Any changes are fine.

2021-12-10 20:37 UTC, trask commented
> The "unstable" vs "stable" labeling of a library or of a package (or individual instrumentations if that's the granularity of labeling you choose to maintain) is done based on the fact whether you are able to take the responsibility to fulfill the requirements of the "stable" labeling. What "stable" label means is described in this document.

Thanks @tigrannajaryan. Given that we don't want to mark the entire javaagent distribution as "unstable", it sounds like we will need to disable all "unstable" auto-instrumentation in the distribution by default, and only enable them (by default) once their respective semantic conventions have reached stability and we can commit to the telemetry stability described in this document.

2021-12-10 21:36 UTC, jmacd approved these changes
There are a number of questions about metrics here. The Views support in each metrics SDK should show it's possible to perform attribute removal safely (correctly, and relatively easily compared with doing so after-the-fact). This topic came up in #2208. I expect we will eventually be able to support metrics schema translation via Views and relax these restrictions, but it's good to be conservative for now.

2021-12-13 13:55 UTC, jsuereth commented
> Thanks @tigrannajaryan. Given that we don't want to mark the entire javaagent distribution as "unstable", it sounds like we will need to disable all "unstable" auto-instrumentation in the distribution by default, and only enable them (by default) once their respective semantic conventions have reached stability and we can commit to the telemetry stability described in this document.

I think we need room here for the Java Agent *itself* to be stable with stable instrumentation but bundle in unstable components that users can make use.  

Specifically, I think we need to walk a fine tightrope of the following "features" for users:

- We need to provide users stability, and a GA offering.  New users won't leverage our offerings if they're not marked stable, and "churn" in instrumentation will drive away our existing users.
- We need the ability to experiment across the huge SCOPE that is instrumentation.   As an example, there was a discussion in the Java instrumentation SiG about DB/ORM span instrumentation not being super useful and a first cut for users (not even on by default in some of the vendor releases).

I think *if* this restriction made it extremely clear to users what is considered stable and what may change in the Java agent, with clear enable/disable flags that'd be ideal.   However, I still feel like we're missing the configuration/enablement story for how the instrumentation SiG can continue experimenting/building instrumentation.  @trask is it clear to you what you would do here?

2021-12-13 20:43 UTC, trask commented
> @trask is it clear to you what you would do here?

Yes, I believe we would hide all unstable auto-instrumentations in the OpenTelemetry Javaagent behind an experimental flag.

2021-12-13 20:49 UTC, tigrannajaryan commented
> > @trask is it clear to you what you would do here?
> 
> Yes, I believe we would hide all unstable auto-instrumentations in the OpenTelemetry Javaagent behind an experimental flag.

@trask This may be the right approach regardless of this PR, right?

2021-12-13 22:39 UTC, trask commented
> > Yes, I believe we would hide all unstable auto-instrumentations in the OpenTelemetry Javaagent behind an experimental flag.
> 
> @trask This may be the right approach regardless of this PR, right?

It may be. Though I'm pretty sure all the vendors are going to enable this experimental flag in their downstream distribution/extension right away, as the OpenTelemetry Javaagent is not very useful when it emits no telemetry (and we currently have no stable semantic conventions, therefore no stable telemetry producing auto-instrumentation).

2021-12-14 05:55 UTC, iNikem commented
Is it a requirement for ALL telemetry that auto-instrumentation produces and wants to declare stable to have a corresponding semantic convention in the spec? E.g. some library-specific attributes in addition to the established db semantic convention - do they need all be described in the spec?

2021-12-14 13:03 UTC, iNikem commented
And related question to the one above: if some language-specific (as in "library exists only for one language") auto-instrumentation e.g. for some DB client wants to provide stable attributes both from DB semantic convention and some library-specific ones, which schema should this client use? We want to reference official Otel schema for DB semantic convention AND we want some schema for library-specific attributes.

2021-12-14 14:30 UTC, tigrannajaryan commented
> > > Yes, I believe we would hide all unstable auto-instrumentations in the OpenTelemetry Javaagent behind an experimental flag.
> > 
> > 
> > @trask This may be the right approach regardless of this PR, right?
> 
> It may be. Though I'm pretty sure all the vendors are going to enable this experimental flag in their downstream distribution/extension right away, as the OpenTelemetry Javaagent is not very useful when it emits no telemetry (and we currently have no stable semantic conventions, therefore no stable telemetry producing auto-instrumentation).

@trask If every vendor is going to enable the experimental flag then we should consider that that is the normal situation and not really "experimental". If that's what is going to happen I think the declarations we make in this spec become useless. The point of declaring the stability is to help real users to avoid breakage because instrumentations change. 

It seems like you are saying instrumentations are not ready to be stable, they are still in a phase where they need to experiment. To me this sounds like we have a couple choices:
1. Declare the entire artifact (e.g. java jar) that contains multiple instrumentations as unstable. I think instrumentation stability is essential part of stability guarantees. If we as artifact cannot provide the guarantees then let's label it honestly.
2. Change the granularity of stable/unstable labelling. Instead of declaring the entire java-instrumentation jar as stable or unstable let's apply the stable/unstable label to individual instrumentations, e.g. `instrumentation/apache-httpclient/` is stable while `instrumentation/cassandra/` is not.
3. Perhaps an alternate approach is to split the artifact into 2 parts: stable and unstable. The stable jar contains stable instrumentations only. As some instrumentation becomes stable move it from the unstable jar to stable.
There are probably other approaches possible. I do not think the approach that "we will declare everything unstable, then expect every vendor to enable all unstable instrumentation by default in their distro" works. To me it sounds like we don't want to take the responsibility and actually provide stability guarantees users expect.

2021-12-14 15:02 UTC, iNikem commented
> 2\. Change the granularity of stable/unstable labelling. Instead of declaring the entire java-instrumentation jar as stable or unstable let's apply the stable/unstable label to individual instrumentations, e.g. `instrumentation/apache-httpclient/` is stable while `instrumentation/cassandra/` is not.

That is more or less what we probably will do. We already explicitly declare that changes in telemetry are still possible until we have stable semantic convention. When http semantic convention is declared stable, we will say that "these and these instrumentation are now stable and here is schema file for them. All remaining are still unstable".

2021-12-14 15:33 UTC, tigrannajaryan commented
> That is more or less what we probably will do. We already explicitly declare that changes in telemetry are still possible until we have stable semantic convention. When http semantic convention is declared stable, we will say that "these and these instrumentation are now stable and here is schema file for them. All remaining are still unstable".

This sounds good to me. If we go with this approach then the wording proposed in this PR only applies to the parts that are declared stable. The unstable parts are free to change.

2022-01-03 07:31 UTC, iNikem commented
> 

@tigrannajaryan Can you please clarify this?

2022-01-05 18:17 UTC, tigrannajaryan commented
> > 
> 
> @tigrannajaryan Can you please clarify this?

I think to move forward with this PR we need to clarify how unstable instrumentations can work without being stifled by these requirements. For this we are going to:
1. Define how to indicate unstable instrumentation in the emitted telemetry (on the wire). I will work on this.
1. Come up with a way to correctly label instrumentation libraries (stable/unstable or alpha/beta/stable). @jsuereth is going to work on this.

2022-01-06 19:09 UTC, tigrannajaryan commented
@jsuereth @trask @iNikem @jack-berg 

I spent a bit of time thinking about unstable instrumentations.

I believe that we need to allow unstable instrumentations to change over time without being subject to the restrictions imposed by schemas.

I was initially thinking that we need to somehow indicate that the telemetry is emitted by such unstable instrumentation by having a specific way to record this fact on the wire. However, I no longer think so. I believe it is sufficient for unstable instrumentations to simply omit the Schema URL on the wire. For receivers of such telemetry the fact that the Schema URL is omitted is an indication that the telemetry is not subject to the concept of schemas. There may be multiple reasons for such omission, unstable instrumentation being one of the possible reasons. I do not see a need for receivers of the telemetry to be able to differentiate unstable instrumentations from instrumentations that omit the Schema URL on the wire for some other reason. (If you see such a reason please tell).

Because of this I suggest to slightly modify this PR in the following way:

### Unstable instrumentations
- Do not include Schema URL in the emitted telemetry.
- Authors of unstable instrumentations are free to modify the instrumentation, provided that the instrumentation is clearly labeled as unstable.
- Receivers of telemetry emitted by unstable instrumentations cannot make any assumptions about the schema of the telemetry since the Schema URL is not present on the wire.


### Stable instrumentations
- If you are not including Schema URL in the emitted telemetry then you are not allowed to modify the telemetry (with certain exceptions carved out in the doc).
- If you are including Schema URL then you are allowed to modify the telemetry after certain date, provided that they are described by a published Schema File (with the same exceptions as above applicable).

### What is Stable vs Unstable Instrumentation

We need a clear labeling approach that should be adopted by all instrumentation. It should be possible to label as stable or unstable each individual library in our instrumentation packages (that may include more than one library). The labels should be clearly communicated to the users of such instrumentation, the labels are an essential part of the instrumentation documentation. Based on how each individual library is labeled they must follow the Schema-related rules described above. @jsuereth I assume you will work on this labelling approach and will propose it in a separate PR or OTEP.

--

Let me know what you all think.

2022-01-07 07:33 UTC, iNikem commented
I am confused about what receivers of telemetry should think about its stability when telemetry does NOT have schema associated with it. Both stable and unstable instrumentations may produce such data. Receiver cannot reason about it.

Would it be better to make schema a requirement for stable instrumentations?

2022-01-07 15:09 UTC, tigrannajaryan commented
> I am confused about what receivers of telemetry should think about its stability when telemetry does NOT have schema associated with it. Both stable and unstable instrumentations may produce such data. Receiver cannot reason about it.

@iNikem Why do the receivers need to reason about it? What difference does it make for receivers?

2022-01-07 15:49 UTC, iNikem commented
> > I am confused about what receivers of telemetry should think about its stability when telemetry does NOT have schema associated with it. Both stable and unstable instrumentations may produce such data. Receiver cannot reason about it.
> 
> @iNikem Why do the receivers need to reason about it? What difference does it make for receivers?

I think what I am confused about is that I, as an author, can omit schema url from my telemetry both for experimental instrumentation (that I can change however I want) and for stable instrumentation (that I cannot change in almost any way).

And I don't understand why do we need stable instrumentations without schema? Why do we allow that?

2022-01-07 16:17 UTC, tigrannajaryan commented
> And I don't understand why do we need stable instrumentations without schema? Why do we allow that?

If you want to declare your instrumentation stable but did not yet have a chance to add support for schemas to your instrumentation it should be OK to do to so temporarily, until you have time to add the support for schemas. If we do not allow this then the support for schemas becomes a pre-requisite for anyone to ever release any stable instrumentation and I don't want to create this limitation for everyone in Otel. I want to ask for a less restrictive limitation: it is OK to declare your instrumentation stable even if you don't support schemas yet, but if you do so please make sure you do not change the emitted telemetry. I think it is an acceptable limitation and allows instrumentation authors here at Otel to choose their own priorities, and decide when exactly they want to start supporting schemas.

Maybe I am being overly cautious but I want to avoid potentially creating roadblocks for lots of contributors here at Otel. I prefer to introduce support for schemas gradually were possible.

2022-01-07 17:07 UTC, iNikem commented
I see your reason. I do think you are too cautious, but I will not pick this battle :) Other than this particular question, I like and support your proposal in https://github.com/open-telemetry/opentelemetry-specification/pull/2180#issuecomment-1006846264

2022-01-07 20:34 UTC, trask commented
@tigrannajaryan thanks 👍

I think the last remaining item that we need clarity on from the javaagent perspective is:

> It should be possible to label as stable or unstable each individual library in our instrumentation packages (that may include more than one library) ... @jsuereth I assume you will work on this labelling approach and will propose it in a separate PR or OTEP.

It sounds like as long as we document the varying stability of each individual instrumentation, then we don't have to declare the entire javaagent as "unstable", but looking forward to this being clarified in the follow-up PR/OTEP.

2022-01-07 21:40 UTC, tigrannajaryan commented
> It sounds like as long as we document the varying stability of each individual instrumentation, then we don't have to declare the entire javaagent as "unstable", but looking forward to this being clarified in the follow-up PR/OTEP.

Yes, I think we should be able to release a "stable" javaagent where some subset of individual instrumentation libraries are marked as "unstable". Kind of like how Kubernetes marks individual features as "alpha", but which does not mean that the entire product is "alpha".

2022-01-17 16:41 UTC, tigrannajaryan commented
Not stale, need time to update this.

2022-03-03 20:41 UTC, tigrannajaryan commented
@trask @jsuereth @iNikem @jack-berg I made substantial changes to this PR, separated Unstable vs Stable instrumentations with clear rules for each category.

Please have a look.

2022-03-04 02:52 UTC, trask approved these changes

2022-03-04 16:25 UTC, Aneurysm9 commented on specification/telemetry-stability.md
> +restrictions. All produced telemetry MUST have an unspecified Schema URL.
Why this restriction?  If telemetry is unstable but conforms to a scheme, why can it not declare that?

2022-03-04 18:20 UTC, tigrannajaryan commented on specification/telemetry-stability.md
> +restrictions. All produced telemetry MUST have an unspecified Schema URL.
My thinking was that "conforms to a schema" and "unstable" are mutually exclusive. If it conforms to a schema then it falls into the "Schema-File Driven Telemetry Producers" bucket. These are prohibited from emitting telemetry that is not described by semantic convention OR if they do so they are prohibited from changing such telemetry over time. Essentially this rules out the possibility of any unstable telemetry to be a "Schema-File Driven Telemetry Producer".

So, the presence of the Schema URL in the emitted telemetry is a signal to the recipient that the producer is schema-file driven and the recipient can make certain assumptions about it. If we allow unstable instrumentations to also specify Schema URL this assumption is no longer valid and we have to indicate by some other means that the telemetry is unstable. 

Anyway, "Unstable, but conform to a schema" sounds like a contradiction to me. Perhaps I am wrong and there is a use case for this?

2022-03-04 23:09 UTC, tsloughter commented on specification/telemetry-stability.md
> +restrictions. All produced telemetry MUST have an unspecified Schema URL.
Maybe the use of the term unstable and stable is confusing here? Since one would consider a schema version of 0.x.y to be unstable, but in a different way.

I don't know of a better term off the top of my head, just a thought.

2022-03-08 10:28 UTC, pirgeo commented on specification/telemetry-stability.md
> +Such instrumentation are prohibited from changing any produced telemetry. If the
```suggestion
Such instrumentations are prohibited from changing any produced telemetry. If the
```

2022-03-08 10:28 UTC, pirgeo commented on specification/telemetry-stability.md
> +specification changes over time and the semantic conventions are updated the
```suggestion
specification changes over time and the semantic conventions are updated, the
```

2022-03-08 10:28 UTC, pirgeo commented on specification/telemetry-stability.md
> +After April 1, 2023 Sgable instrumentations are allowed to change the produced telemetry
```suggestion
After April 1, 2023, stable instrumentations are allowed to change the produced telemetry
```
Unsure if I got this right.

2022-03-08 10:28 UTC, pirgeo commented on specification/telemetry-stability.md
> +- The change is part of OpenTelemetry semantic conventions and are in a released
```suggestion
- The change is part of OpenTelemetry semantic conventions and is in a released
```

2022-03-08 10:28 UTC, pirgeo commented on specification/telemetry-stability.md
> +April 1, 2023 the instrumentations must wait until April 1, 2023 before they can adopt
```suggestion
April 1, 2023, the instrumentations must wait until April 1, 2023 before they can adopt
```

2022-03-08 14:36 UTC, tigrannajaryan commented on specification/telemetry-stability.md
> +specification changes over time and the semantic conventions are updated the
Fixed.

2022-03-08 14:36 UTC, tigrannajaryan commented on specification/telemetry-stability.md
> +After April 1, 2023 Sgable instrumentations are allowed to change the produced telemetry
Fixed.

2022-03-08 14:36 UTC, tigrannajaryan commented on specification/telemetry-stability.md
> +April 1, 2023 the instrumentations must wait until April 1, 2023 before they can adopt
Fixed.

2022-03-08 14:37 UTC, tigrannajaryan commented on specification/telemetry-stability.md
> +Such instrumentation are prohibited from changing any produced telemetry. If the
Fixed.

2022-03-08 16:05 UTC, Aneurysm9 commented on specification/telemetry-stability.md
> +restrictions. All produced telemetry MUST have an unspecified Schema URL.
I think it is possible for an instrumentation's implementation to be unstable while it is still using a schema and exporting likely stable telemetry using a schema.  I don't think it is necessary to prohibit emitting a schema version until the implementation reaches v1.0.

2022-03-08 16:12 UTC, arminru commented on specification/telemetry-stability.md
> +
```suggestion

**Status**: [Experimental](document-status.md)

```

2022-03-09 16:20 UTC, tigrannajaryan commented on specification/telemetry-stability.md
> +restrictions. All produced telemetry MUST have an unspecified Schema URL.
Changed the wording to allow unstable instrumentation to specify Schema URL. Also added a TODO to decide if we need to define how unstable instrumentation is indicated on the wire.

2022-03-09 18:41 UTC, trask approved these changes

2022-03-10 07:12 UTC, iNikem commented on specification/telemetry-stability.md
> +restrictions. The produced telemetry MAY specify a Schema URL if the telemetry data
If unstable instrumentation uses schema, is it required to record all its changes in that schema and make only those changes that can be described in its schema file?

2022-03-10 07:12 UTC, iNikem commented on specification/telemetry-stability.md
> +TODO: decide if it is necessary to indicate on the wire if the produced telemetry is
I still think that the presence of schema url on the wire could serve as a good indicator of telemetry stability. Why exactly do we need "Fixed Schema Telemetry Producers"?

2022-03-18 16:27 UTC, tigrannajaryan commented on specification/telemetry-stability.md
> +restrictions. The produced telemetry MAY specify a Schema URL if the telemetry data
Unstable instrumentation can change any time and it is not required that these changes are reflected in schema files. That's the point of unstable instrumentation: they can break the schema rules.

2022-03-18 16:29 UTC, tigrannajaryan commented on specification/telemetry-stability.md
> +TODO: decide if it is necessary to indicate on the wire if the produced telemetry is
"Fixed Schema Telemetry Producers" are instrumentations which want to declare themselves "Stable" but do not yet support schemas. This essentially is another way of saying: "if you want to change emitted telemetry you must support the concept of schemas and must include schema URL in the emitted telemetry".

2022-03-18 16:33 UTC, tigrannajaryan commented
@open-telemetry/specs-trace-approvers please review.

2022-03-21 16:22 UTC, Aneurysm9 approved these changes

2022-03-25 16:31 UTC, arminru approved these changes
This looks good to me for a first iteration. Thank you, Tigran!
The open issue about indicating (in)stability can be tackled in a separate follow-up PR as this is still marked experimental.

2022-03-25 16:31 UTC, arminru commented on specification/telemetry-stability.md
> +Unstable instrumentations authored by OpenTelemetry MAY produce telemetry that is
```suggestion
Unstable instrumentations authored by OpenTelemetry MAY produce additional telemetry that is
```
Otherwise it sounds as if it was explicitly allowed to diverge from the spec although a semantic convention is already defined for the instrumented technology/framework/area.

2022-03-25 16:31 UTC, arminru commented on specification/telemetry-stability.md
> +coming from an unstable instrumentation.
This could be indicated by the version number (-alpha, -beta, 0.x) used for the instrumentation library (tracer/meter name)?

2022-03-25 16:31 UTC, arminru commented on specification/telemetry-stability.md
> +  version of the specification,
```suggestion
  version of the specification.
```

2022-03-25 16:31 UTC, arminru commented on specification/telemetry-stability.md
> +- The produced telemetry correctly specifies the Schema URL.
```suggestion
- The produced telemetry correctly specifies the respective Schema URL.
```

2022-03-25 16:31 UTC, arminru commented on specification/versioning-and-stability.md
> +in [Telemetry Stability](telemetry-stability.md)). The goal is to ensure users can
```suggestion
in [Telemetry Stability](telemetry-stability.md).) The goal is to ensure users can
```

2022-03-25 16:31 UTC, arminru commented on specification/versioning-and-stability.md
> +[schemas](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/schemas/overview.md).
```suggestion
[Telemetry Schemas](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/schemas/overview.md).
```

2022-03-25 16:31 UTC, arminru commented on specification/versioning-and-stability.md
> +- Renaming of attributes.
```suggestion
- Renaming of span, metric and log attributes.
```

2022-03-25 16:31 UTC, arminru commented on specification/versioning-and-stability.md
> +See [Telemetry Stability](telemetry-stability.md) document for details on how
```suggestion
See the [Telemetry Stability](telemetry-stability.md) document for details on how
```

2022-03-25 16:31 UTC, arminru commented on specification/versioning-and-stability.md
> +  spans, span events or log records.
```suggestion
  spans, span events or log records.
  Note that adding attributes to existing metrics is NOT considered non-breaking.
```
One might miss this subtle difference between the two points and I think it's worth pointing this out explictly.

2022-03-25 16:31 UTC, arminru commented on specification/versioning-and-stability.md
> +For stability of telemetry produced by instrumentation see
```suggestion
For stability of telemetry produced by instrumentation see the
```

2022-03-25 16:47 UTC, tigrannajaryan commented on specification/telemetry-stability.md
> +Unstable instrumentations authored by OpenTelemetry MAY produce telemetry that is
Added.

2022-03-25 16:47 UTC, tigrannajaryan commented on specification/telemetry-stability.md
> +  version of the specification,
Fixed.

2022-03-25 16:47 UTC, tigrannajaryan commented on specification/versioning-and-stability.md
> +in [Telemetry Stability](telemetry-stability.md)). The goal is to ensure users can
Fixed.

2022-03-25 16:47 UTC, tigrannajaryan commented on specification/versioning-and-stability.md
> +- Renaming of attributes.
Added.

2022-03-25 16:47 UTC, tigrannajaryan commented on specification/versioning-and-stability.md
> +See [Telemetry Stability](telemetry-stability.md) document for details on how
Fixed.

2022-03-25 16:48 UTC, tigrannajaryan commented on specification/versioning-and-stability.md
> +  spans, span events or log records.
Added in a slightly re-worded form.

2022-03-25 16:48 UTC, tigrannajaryan commented on specification/versioning-and-stability.md
> +For stability of telemetry produced by instrumentation see
Fixed.

2022-03-25 16:48 UTC, tigrannajaryan commented on specification/telemetry-stability.md
> +coming from an unstable instrumentation.
Yes, that is a possibility.

2022-03-25 17:47 UTC, dyladan commented on specification/telemetry-stability.md
> +Stable instrumentations authored by OpenTelemetry SHOULD NOT produce telemetry that is
Does this mean an instrumentation should not provide any excess span attributes for instance? Perhaps we should have an extension namespace like `ext.my.custom.attribute` which are specifically not covered by stability guarantees?

2022-03-25 18:32 UTC, jack-berg approved these changes

2022-03-25 18:55 UTC, trask commented on specification/telemetry-stability.md
> +Stable instrumentations authored by OpenTelemetry SHOULD NOT produce telemetry that is
this has been our interpretation in java instrumentation, and we hide all excess span attributes behind a flag, e.g. `otel.instrumentation.grpc.experimental-span-attributes`

2022-03-25 20:08 UTC, tigrannajaryan commented on specification/telemetry-stability.md
> +Stable instrumentations authored by OpenTelemetry SHOULD NOT produce telemetry that is
>Does this mean an instrumentation should not provide any excess span attributes for instance?

Yes, if the instrumentation is declared Stable.

>Perhaps we should have an extension namespace like ext.my.custom.attribute which are specifically not covered by stability guarantees?

This is an interesting suggestion. This way Stable instrumentations will still have a way to continue experimenting more freely without being bound by semantic convention acceptable into specification and Schema File release cycles. If we see the demand we can allow this exception.

2022-03-26 00:09 UTC, reyang commented on specification/versioning-and-stability.md
> +[Telemetry Schemas](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/schemas/overview.md).
Change to relative link.

2022-03-26 00:18 UTC, reyang requested changes
There are several absolute links which need to be changed to relative (please feel free to dismiss it once the links are fixed).

2022-03-28 16:13 UTC, dyladan commented on specification/telemetry-stability.md
> +Stable instrumentations authored by OpenTelemetry SHOULD NOT produce telemetry that is
I can tell you for certain there has been demand in javascript. Also, it's not clear how strictly we're meant to enforce these types of things in contrib repositories for example. In JS at least we have given a lot of control over the packages to the person or org that contributed them in terms of which features are included and when releases are made. Are we meant to be enforcing things like this, or do these restrictions only apply to "official" instrumentations released through the official non-contrib repositories?

2022-03-28 16:23 UTC, tigrannajaryan commented
@dyladan 

> I don't see anything about how to handle cases around early prototypes.

Is "Unstable Instrumentations" section insufficient? The prototypes are supposedly unstable and can be governed by the rules in this section I assume. Are you looking for something else?

> First implementations of instrumentations may not be feature complete, and may not want to strictly adhere even to the schema unstable promise. In alpha versions, breaking changes are an expected part of the development process.

Assuming "first implementation" is unstable this seems to be covered by "Unstable Instrumentations", which allows any changes to the emitted telemetry.


> I also don't see anything about how to handle the case where there is no semantic convention for a particular usecase.

I think this is already covered in the document:
```
Unstable instrumentations authored by OpenTelemetry MAY produce additional telemetry that
is not described by OpenTelemetry semantic conventions.
```
and
```
Stable instrumentations authored by OpenTelemetry SHOULD NOT produce telemetry that is
not described by OpenTelemetry semantic conventions. If, however, this rule is broken the
instrumentations MUST NOT change such telemetry, regardless of whether they
are fixed-schema producers or schema-file driven producers. Once the produced telemetry
is added to the semantic conventions, changes will be allowed as described below.
```
Is this unclear or not specific enough?

2022-03-28 16:25 UTC, dyladan commented
> @dyladan
> 
> > I don't see anything about how to handle cases around early prototypes.
> 
> Is "Unstable Instrumentations" section insufficient? The prototypes are supposedly unstable and can be governed by the rules in this section I assume. Are you looking for something else?
> 
> > First implementations of instrumentations may not be feature complete, and may not want to strictly adhere even to the schema unstable promise. In alpha versions, breaking changes are an expected part of the development process.
> 
> Assuming "first implementation" is unstable this seems to be covered by "Unstable Instrumentations", which allows any changes to the emitted telemetry.
> 
> > I also don't see anything about how to handle the case where there is no semantic convention for a particular usecase.
> 
> I think this is already covered in the document:
> 
> ```
> Unstable instrumentations authored by OpenTelemetry MAY produce additional telemetry that
> is not described by OpenTelemetry semantic conventions.
> ```
> 
> and
> 
> ```
> Stable instrumentations authored by OpenTelemetry SHOULD NOT produce telemetry that is
> not described by OpenTelemetry semantic conventions. If, however, this rule is broken the
> instrumentations MUST NOT change such telemetry, regardless of whether they
> are fixed-schema producers or schema-file driven producers. Once the produced telemetry
> is added to the semantic conventions, changes will be allowed as described below.
> ```
> 
> Is this unclear or not specific enough?

Hmm no I think I must have just misread. I was reading quickly and guess I wasn't careful enough and got the unstable and stable sections mashed together in my head.

2022-03-28 17:39 UTC, alanwest commented on specification/telemetry-stability.md
> +All OpenTelemetry-authored instrumentations are labeled to be either `Unstable` or `Stable`
What does OpenTelemetry-authored mean? Does it mean all instrumentation sourced from a repo in the open-telemetry org? Can there be any exclusions to this - e.g., instrumentations in contrib repositories?

2022-03-28 18:08 UTC, dyladan commented on specification/telemetry-stability.md
> +All OpenTelemetry-authored instrumentations are labeled to be either `Unstable` or `Stable`
> What does OpenTelemetry-authored mean? Does it mean all instrumentation sourced from a repo in the open-telemetry org? Can there be any exclusions to this - e.g., instrumentations in contrib repositories?

That's what I was getting at here: https://github.com/open-telemetry/opentelemetry-specification/pull/2180#discussion_r836607529

2022-03-28 18:14 UTC, tigrannajaryan commented on specification/telemetry-stability.md
> +All OpenTelemetry-authored instrumentations are labeled to be either `Unstable` or `Stable`
>What does OpenTelemetry-authored mean? Does it mean all instrumentation sourced from a repo in the open-telemetry org? 

Yes, that's essentially what it means.

>Can there be any exclusions to this - e.g., instrumentations in contrib repositories?

Do we need any exclusions? We already have a form of exclusion, we call it "Unstable Instrumentation". If this is insufficient and we need another exclusion rule I can add it.

2022-03-29 00:57 UTC, alanwest commented on specification/telemetry-stability.md
> +All OpenTelemetry-authored instrumentations are labeled to be either `Unstable` or `Stable`
> Do we need any exclusions?

I'm not sure yet. Like @dyladan mentions with the JS community, it is also the .NET community's intent to give the original contributor a fair amount of control over packages in the contrib repo. Some of these folks are not even members of the OpenTelemetry org much less well indoctrinated in the requirements of otel instrumentation. Might just be a matter of setting appropriate expectations with these folks.

I plan to bring this topic up in this week's .NET SIG meeting (tomorrow). Will share any suggestions or concerns.

2022-03-29 15:28 UTC, tigrannajaryan commented on specification/telemetry-stability.md
> +All OpenTelemetry-authored instrumentations are labeled to be either `Unstable` or `Stable`
OK, we can keep this topic open. It does not prevent merging of the PR. The status of this document is still experimental so we can add other exclusions as necessary.

2022-04-04 14:26 UTC, tigrannajaryan commented
@Oberon00 please take another look.

2022-04-04 14:30 UTC, tigrannajaryan commented
@open-telemetry/python-maintainers can you please take a look? This affects instrumentations in all languages. It would be good to have your approval if you agree with this approach.

2022-04-04 16:32 UTC, reyang approved these changes

2022-04-04 16:38 UTC, alanwest approved these changes

2022-04-04 16:42 UTC, alanwest commented on specification/telemetry-stability.md
> +All OpenTelemetry-authored instrumentations are labeled to be either `Unstable` or `Stable`
.NET discussed this a bit. Given that releasing packages is in the hands of maintainers of the contrib repo, it's reasonable for them to gate unstable/stable at this point in time.

2022-04-04 17:05 UTC, jmacd commented on specification/telemetry-stability.md
> +Stable instrumentations authored by OpenTelemetry SHOULD NOT produce telemetry that is
> excess span attributes

I am having trouble reconciling this discussion with the statements below, allowing changes to semantic conventions in [versioning and stability of semantic conventions below (this PR)](https://github.com/open-telemetry/opentelemetry-specification/pull/2180/files#diff-e7de8bed9eb1605a44c385930415011d900acccecc8b48398a75ce9fa707cdd3R182), where addition of span attributes is always allowed.

2022-04-04 18:12 UTC, tigrannajaryan commented on specification/telemetry-stability.md
> +Stable instrumentations authored by OpenTelemetry SHOULD NOT produce telemetry that is
>addition of span attributes is always allowed.

@jmacd Addition of attributes to _semantic conventions_ for existing Spans, Resources, Logs is always allowed and considered a non-breaking change (not that I can think of an actual semantic convention that involves a Span, but anyway). Such addition does not require a new Schema version.

However, including a span attribute in the telemetry, where such attribute is not defined in the semantic conventions is strongly discouraged (with a SHOULD NOT clause) for Stable instrumentations. If there is a need like this then the attribute first has to be added to semantic conventions and then it can be added to the telemetry.

2022-04-04 19:43 UTC, tigrannajaryan commented
@dyladan if the PR looks good to you please approve on behalf of JS SIG. I want to have an approval from each (or at least most) language SIG.

2022-04-04 19:58 UTC, dyladan approved these changes
We discussed this at the JS meeting last wednesday and the other @open-telemetry/javascript-maintainers brought up the same points as have been brought up by myself, @alanwest, and others around instrumentation which is not in the semantic conventions. There will always be some instrumentations which for whatever reason are not covered by the semantic conventions whether they have too small of a userbase, are too specific, or provide some custom functionality. This PR seems to prevent those instrumentations from ever being marked as "stable" which will limit their adoption.

From a maintenance standpoint it is not too big of a burden for maintainers to gate stable on the guarantees outlined here, but I believe the restrictions will prevent people from upstreaming contributions to the contrib repo unless we have some way to provide custom functionality that isn't covered by the semantic conventions.

As mentioned earlier, this is still marked experimental so isn't blocking, but I want to make sure the point isn't forgotten before this is finalized and made stable.

2022-04-04 20:27 UTC, tigrannajaryan commented
I believe so far we have approvals from JS, Go, Java, .Net maintainers.

2022-04-04 21:08 UTC, trask commented
> There will always be some instrumentations which for whatever reason are not covered by the semantic conventions whether they have too small of a userbase, are too specific, or provide some custom functionality. This PR seems to prevent those instrumentations from ever being marked as "stable" which will limit their adoption.

@tigrannajaryan I thought there were two options for instrumentation that are not covered by semantic conventions to go stable:

* Fixed Schema Telemetry Producers - decide not to evolve the schema via the standard schema mappings
* Schema-File Driven Telemetry Producers - publish your own schema file (we have discussed doing this in Java for these one-off instrumentations that do not have a future in the specification repo)

2022-04-04 21:51 UTC, tigrannajaryan commented
> > There will always be some instrumentations which for whatever reason are not covered by the semantic conventions whether they have too small of a userbase, are too specific, or provide some custom functionality. This PR seems to prevent those instrumentations from ever being marked as "stable" which will limit their adoption.
> 
> @tigrannajaryan I thought there were two options for instrumentation that are not covered by semantic conventions to go stable:
> 
> * Fixed Schema Telemetry Producers - decide not to evolve the schema via the standard schema mappings
> * Schema-File Driven Telemetry Producers - publish your own schema file (we have discussed doing this in Java for these one-off instrumentations that do not have a future in the specification repo)

@trask that is correct. And for both options they should also follow this rule:
```
Stable instrumentations authored by OpenTelemetry SHOULD NOT produce telemetry that is not described by OpenTelemetry semantic conventions.
```
I think @dyladan's concern is that this is too much limitation and the rules are too rigid for instrumentations contributed by non-core maintainers.

2022-04-04 21:58 UTC, trask commented
> And for both options they should also follow this rule:
> 
> 
> > Stable instrumentations authored by OpenTelemetry SHOULD NOT produce telemetry that is not described by OpenTelemetry semantic conventions.

oh, I missed this, thx! I agree this is too limiting for the reason @dyladan mentions:

> There will always be some instrumentations which for whatever reason are not covered by the semantic conventions whether they have too small of a userbase, are too specific, or provide some custom functionality

2022-04-05 13:45 UTC, carlosalberto approved these changes

2022-04-05 21:40 UTC, cijothomas commented on specification/telemetry-stability.md
> +new attributes to spans, span events, log records or resources are considered
is it intentional that "adding of new attributes to metrics" was not listed?

2022-04-05 22:44 UTC, jack-berg commented on specification/telemetry-stability.md
> +new attributes to spans, span events, log records or resources are considered
Yes, see this [note](https://github.com/open-telemetry/opentelemetry-specification/pull/2180/files#diff-e7de8bed9eb1605a44c385930415011d900acccecc8b48398a75ce9fa707cdd3R183-R184).

2022-04-06 14:33 UTC, tigrannajaryan commented on specification/telemetry-stability.md
> +new attributes to spans, span events, log records or resources are considered
Yes, adding new attributes to metrics is a breaking change and is intentionally not listed.

2022-04-06 14:40 UTC, cijothomas commented on specification/telemetry-stability.md
> +new attributes to spans, span events, log records or resources are considered
Thanks for clarifying.

2022-04-08 14:53 UTC, robertlaurin approved these changes

2022-04-08 14:55 UTC, fbogsany approved these changes

2022-04-08 15:41 UTC, srikanthccv commented on specification/telemetry-stability.md
> +Stable instrumentations authored by OpenTelemetry SHOULD NOT produce telemetry that is
There are instrumentations where we provide callback/hook for end-user to customise the attributes added to span along with standard attributes. This strict restriction would mean instrumentation can't be stable?

2022-04-08 15:44 UTC, tigrannajaryan commented on specification/telemetry-stability.md
> +Stable instrumentations authored by OpenTelemetry SHOULD NOT produce telemetry that is
I think the "SHOULD" clause allows such behavior. By calling a hook you hand over the responsibility to the end user. If  they deviate from expected behavior that's on them.

2022-04-08 16:00 UTC, srikanthccv approved these changes

2022-04-08 16:34 UTC, lzchen approved these changes

2022-04-08 17:51 UTC, tigrannajaryan commented
> I believe so far we have approvals from JS, Go, Java, .Net maintainers.

In addition we now have approvals from Ruby and Python maintainers.

I believe this is good enough and we can move forward with this approach. Merging the PR.

2022-04-08 17:51 UTC, merged