Clarify that attribute keys are unique in collections
open-telemetry/opentelemetry-specification pull request #2248
Opened 2022-01-06 16:31 UTC by tigrannajaryan

Attributes keys must be unique. The key/value pair collections in the specification was always intended to model a map.

There was a recent confusion about this. This change clarifies the spec. This is an editorial change. It does not change any semantics.

Resolves https://github.com/open-telemetry/opentelemetry-specification/issues/2245

2022-01-06 16:46 UTC, yurishkuro commented
Who is supposed to be responsible for the uniqueness?  We cannot impose requirements on the users of the API who can call setAttribute twice with the same key. And streaming implementations of the API cannot enforce key uniqueness (e.g. via last-wins) because they do not hold state.

2022-01-06 17:53 UTC, tigrannajaryan commented
> Who is supposed to be responsible for the uniqueness? We cannot impose requirements on the users of the API who can call setAttribute twice with the same key. And streaming implementations of the API cannot enforce key uniqueness (e.g. via last-wins) because they do not hold state.

I agree, users should't be required to do that. The Trace API [already enforces](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#set-attributes) the behavior:

>Setting an attribute with the same key as an existing attribute SHOULD overwrite the existing attribute's value.

My understanding of this clause is that the uniqueness is enforced (perhaps eventually, but nevertheless). Streaming implementations don't necessarily need to hold state on the sender side to enforce this. They can define the semantics of the receiving side rules in a manner that results uniqueness of attributes from receiver's perspective (the "overwrite if exists" rule can be applied at the receiver end).

I was not able to find an equivalent clause in the Metrics API. It should be probably added.

2022-01-06 18:00 UTC, yurishkuro commented on specification/common/common.md
> +[Log Records](../logs/data-model.md) may contain a collection of attributes. The
```suggestion
[Resources](../resource/sdk.md), 
Metrics [data points](../metrics/datamodel.md#metric-points),
[Spans](../trace/api.md#set-attributes), 
Span [Events](../trace/api.md#add-events), 
Span [Links](../trace/api.md#specifying-links) 
and [Log Records](../logs/data-model.md)
may contain a collection of attributes. The
```
this formatting makes this more readable

2022-01-06 20:36 UTC, tigrannajaryan commented on specification/common/common.md
> +[Log Records](../logs/data-model.md) may contain a collection of attributes. The
Done.

2022-01-07 01:57 UTC, carlosalberto commented on specification/common/common.md
> +one key-value pair with the same key.
Probably adding a link here to https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#set-attributes would keep clear what part is responsible for enforcing it.

2022-01-07 02:45 UTC, tigrannajaryan commented on specification/common/common.md
> +one key-value pair with the same key.
Yes, line 114 links exactly to that.

2022-01-07 07:24 UTC, iNikem approved these changes

2022-01-08 00:48 UTC, carlosalberto approved these changes

2022-01-10 17:22 UTC, bogdandrutu approved these changes

2022-01-11 11:48 UTC, pirgeo approved these changes

2022-01-11 13:28 UTC, Oberon00 commented on specification/common/common.md
> +one key-value pair with the same key.
cannot
```suggestion
The keys in each such collection are unique, i.e. there MUST NOT exist more than
```

And we probably should specify that conflicts SHOULD be resolved by using the attribute set latest.

2022-01-11 13:28 UTC, Oberon00 commented on specification/common/common.md
> +The keys in each such collection are unique, i.e. there cannot exist more than
cannot
```suggestion
The keys in each such collection are unique, i.e. there MUST NOT exist more than
```

And we probably should specify that conflicts SHOULD be resolved by using the attribute set latest.

2022-01-12 00:53 UTC, carlosalberto commented
@yurishkuro Please take a look again.

2022-01-12 02:27 UTC, yurishkuro commented
As I already [commented](https://github.com/open-telemetry/opentelemetry-specification/pull/2248#issuecomment-1006739642), I do not understand what this description refers to. **Something** needs to enforce this uniqueness. It can be users of the API, the implementation of the API (i.e. SDK), or the backend. OTel cannot impose requirements on the users or the backends, and SDKs may not be able to enforce uniqueness (e.g. streaming API). So what is this clause referring to?

2022-01-12 20:41 UTC, tigrannajaryan commented
> As I already [commented](https://github.com/open-telemetry/opentelemetry-specification/pull/2248#issuecomment-1006739642), I do not understand what this description refers to. **Something** needs to enforce this uniqueness. It can be users of the API, the implementation of the API (i.e. SDK), or the backend.

@yurishkuro My reading of the [current requirement](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#set-attributes) is that it is the responsibility of the SDK or of the exporter to enforce uniqueness. 

If it is not clear we should clarify it, but I think it can be a separate PR. This PR does not contradict that, this PR merely sets the broader expectation from the semantics perspective.

2022-01-12 20:44 UTC, yurishkuro commented
The current req says "SHOULD overwrite", so uniqueness is not guaranteed. And that's my concern with the wording in this PR is that it gives a misleading impression that it *is* guaranteed / enforced.

2022-01-12 20:55 UTC, tigrannajaryan commented
> The current req says "SHOULD overwrite", so uniqueness is not guaranteed. And that's my concern with the wording in this PR is that it gives a misleading impression that it _is_ guaranteed / enforced.

That's a good point. I think the only reason it is a SHOULD and not a MUST is because an alternate strategy is possible (drop duplicates), not because duplicates are considered acceptable. I am fine with changing it to MUST or calling our more clearly the uniqueness requirement (or just linking to the wording introduced by this PR).

Again, I think this PR is more fundamental and it reflects our intent. If the existing spec wording contradicts with this PR then that wording needs to change not our guarantee of uniqueness which this PR merely states explicitly.

2022-01-12 22:09 UTC, yurishkuro commented
> Again, I think this PR is more fundamental and it reflects our intent. 

I guess this is where we disagree. First, there is no fundamental problems for the backends (at least tracing backends) to support multiple attributes with the same key (Jaeger always allowed that), and I see it as a function of you-get-back-what-you-put-in, i.e. the users are in control of uniqueness. Second, I think there's definitely room for strict maps, but only in situations with atomic writes to the API. E.g. adding an event to span is atomic, you can't amend the event afterwards, and that gives a clear choke point to enforce uniqueness. Logging API is similar (if we had one), metrics API probably same as well. However, the Span API allows multiple writes, so as long as the user can call `span.setAttribute(k, v)`, they should not expect some magic deduping by default (although it can be opt-in at some point in the pipeline).

Concrete example: Canopy at Meta supports `block.annotate(props)` API (block == span). Props is a map so uniqueness is enforced in this atomic write, but `annotate` can be called multiple times, possibly with conflicting keys. The SDK implementation is streaming, i.e. these writes are flushed independently, no state is stored in the block/span. The storage accepts all writes as is, without fiddling with the data. So the only point to enforce uniqueness (if desired) is in the trace reader when higher-level data model is returned inflated from the raw events.

2022-01-12 22:09 UTC, yurishkuro commented
> Again, I think this PR is more fundamental and it reflects our intent. 

I guess this is where we disagree. First, there is no fundamental problems for the backends (at least tracing backends) to support multiple attributes with the same key (Jaeger always allowed that), and I see it as a function of you-get-back-what-you-put-in, i.e. the users are in control of uniqueness. Second, I think there's definitely room for strict maps, but only in situations with atomic writes to the API. E.g. adding an event to span is atomic, you can't amend the event afterwards, and that gives a clear choke point to enforce uniqueness. Logging API is similar (if we had one), metrics API probably same as well. However, the Span API allows multiple writes, so as long as the user can call `span.setAttribute(k, v)`, they should not expect some magic de-duping by default (although it can be opt-in at some point in the pipeline).

Concrete example: Canopy at Meta supports `block.annotate(props)` API (block == span). Props is a map so uniqueness is enforced in this atomic write, but `annotate` can be called multiple times, possibly with conflicting keys. The SDK implementation is streaming, i.e. these writes are flushed independently, no state is stored in the block/span. The storage accepts all writes as is, without fiddling with the data. So the only point to enforce uniqueness (if desired) is in the trace reader when higher-level data model is returned inflated from the raw events.

2022-01-13 16:32 UTC, jmacd requested changes

2022-01-13 16:32 UTC, jmacd commented on specification/common/common.md
> +The keys in each such collection are unique, i.e. there cannot exist more than
Yes, I believe this was widely discussed and agreed to this point _years ago_, we just never wrote it down clearly. When an attribute map is expressed as a list, duplicate keys should be resolved by taking the last value among the ordered list. This improves efficiency since you can let the receiver de-duplicate.

2022-01-13 16:43 UTC, jmacd commented
@yurishkuro I think you can have your interpretation inside a streaming SDK without changing the spec from Tigran's position. 

OTel added an array-of-strings attribute so that you could have a multi-valued attribute. If the application intends to report a multi-valued attribute, it should built the values in memory and set them as an attribute. If you want to update the attribute to a new set of values through the span's lifetime, that also works, but the set of attributes remains a map and your attribute has multiple string values. The application is required to keep its working set in memory if it wants to change the list of values for an attribute, since it has to update them all in a single call.

The Metrics data model defines more than one way to model data, and there is an analogy to draw with tracing. Metrics defines an event model, wherein each call to a synchronous instrument is an independently observable event. A streaming metric SDK could report each event as an individual (hey let's use column compression for this!) and if you're so inclined you could see every change to a counter this way.   The data model defines a "stream" model which eliminates the individual events and aggregates them together. You can no longer see the individual updates.

For a streaming trace SDK, I would recommend you consider the `SetAttribute()` as an immutable event. Considering a string-valued attribute being set multiple times, you will see one event for every modification to the attribute. When all the events are collected, you will see an attribute that was modified several times. But at each point in time, semantically, the attribute has a single value. The consumer of your streaming SDK may see a timeline of updates to the event, and you can show all the values that were set, but I would say it's off-spec to consider the set of values that were set to be a multi-valued map.

2022-01-13 16:49 UTC, tigrannajaryan commented
> But at each point in time, semantically, the attribute has a single value.

I think this is key observation. I intentionally avoid specifying who and how enforces these semantics because there are many different places and ways to achieve it. As long as we explicitly tell that it is a requirement how exactly it is achieved can and should be left undefined to give enough leeway for implementations to do the best they can.

I will follow up with a PR for OTLP in the proto repo, specifically requiring that senders must not have duplicates in the attributes list. 

Other implementations using other protocols (e.g stream SDK with an exporter that uses an event-based protocol) can move the uniqueness enforcement requirement to the receiver/backend.

2022-01-13 18:43 UTC, yurishkuro commented
I mostly agree with what @jmacd is saying. What I see problematic is that this is clearly a very nuanced topic, as evidenced by this discussion, but the spec change makes a blunt statement that pretends that these nuances do not exist. If I were reading this spec for the first time, I would still have the exact same questions I raised here, because the wording does not answer any of them.

2022-01-13 21:28 UTC, tigrannajaryan commented
> I mostly agree with what @jmacd is saying. What I see problematic is that this is clearly a very nuanced topic, as evidenced by this discussion, but the spec change makes a blunt statement that pretends that these nuances do not exist. If I were reading this spec for the first time, I would still have the exact same questions I raised here, because the wording does not answer any of them.

This is a great feedback. Let me do another round and see if I can add more clarity and capture these nuances.

2022-01-20 01:25 UTC, yurishkuro approved these changes

2022-01-20 01:26 UTC, tigrannajaryan commented
@yurishkuro @jmacd I added some wording to address your comments. Please have another look and see if it helps.

2022-01-20 01:28 UTC, tigrannajaryan commented
CI failure doesn't seem to be related to my change in any way.

2022-01-24 18:07 UTC, tigrannajaryan commented
@jmacd PTAL.

2022-01-26 19:57 UTC, jmacd approved these changes

2022-01-26 21:01 UTC, carlosalberto commented
Tried to merge but it won't allow me, as there's one **outdated** unresolved conversation - which cannot be found now, hence cannot be resolved.

Wondering if anybody has experienced this _feature_ before?

2022-01-26 21:47 UTC, merged