Clarify that Trace/Meter are associated with Instrumentation Scope
open-telemetry/opentelemetry-specification pull request #2276
Opened 2022-01-19 22:36 UTC by tigrannajaryan

This is a slightly different take on https://github.com/open-telemetry/opentelemetry-specification/issues/2203

Instead of renaming instrumentation library to instrumentation scope everywhere
this PR suggests targetted editing of wording of the Trace/Meter obtaining API
to allow not just instrumentation library but other instrumentation scopes to be
used as a parameter.

This change does not force renaming of API parameters and is not a breaking change.
We consider it a clarification of usage to match the intent that we had for the "name"
field.

If this PR is accepted there will be a follow up PR that will suggest to rename
InstrumentationLibrary* messages in OTLP proto to InstrumentationScope* message.
Such a change will not be a breaking change for the OTLP wire format and is acceptable.

If this PR is accepted we will also close https://github.com/open-telemetry/opentelemetry-specification/pull/1236
since it will be no longer necessary. The logger name will be recorded as the
instrumentation scope. This clarification will be a follow up PR that clarifies the
behavior in https://github.com/open-telemetry/oteps/blob/main/text/logs/0150-logging-library-sdk.md

2022-01-19 23:44 UTC, bogdandrutu approved these changes

2022-01-20 01:02 UTC, yurishkuro submitted a review, later dismissed

2022-01-20 10:04 UTC, GraemeF commented on specification/glossary.md
> +associated with. It is typically the developer's choice to decide what denotes a
```suggestion
associated. It is typically the developer's choice to decide what denotes a
```

2022-01-20 16:09 UTC, tigrannajaryan commented on specification/glossary.md
> +associated with. It is typically the developer's choice to decide what denotes a
Fixed, thanks.

2022-01-20 17:54 UTC, carlosalberto approved these changes

2022-01-20 17:55 UTC, carlosalberto commented
Overall LGTM - I'd like to get the opinion of maintainers though.

cc @tedsuo

2022-01-20 18:44 UTC, MrAlias approved these changes

2022-01-21 01:06 UTC, jmacd approved these changes

2022-01-21 14:47 UTC, tigrannajaryan commented
Let's keep this open for at least one week. I want to make sure lots of folks see this.

2022-01-21 14:47 UTC, tigrannajaryan commented
We should also mention this in the Maintainers and Spec SIG meetings next week.

2022-01-21 18:47 UTC, bogdandrutu commented
@tigrannajaryan I created an entry for the next week maintainer agenda meeting, and add this as a discussion point. I will not be there.

2022-01-21 20:09 UTC, jack-berg approved these changes

2022-01-24 15:27 UTC, tigrannajaryan commented
@open-telemetry/specs-approvers I won't be able to attend the Maintainers meeting today. If you are in the meeting please ask maintainers to have a look / be aware of this change.

2022-01-24 16:58 UTC, arminru commented on specification/metrics/api.md
> +  `io.opentelemetry.contrib.mongodb`), such as the instrumentation library,
Please keep the glossary reference for instrumentation library so readers can look it up.

2022-01-24 16:58 UTC, arminru commented on specification/trace/api.md
> +  scope](../glossary.md#instrumentation-scope) (e.g.
Please keep the glossary reference for instrumentation library so readers can look it up.

2022-01-24 17:12 UTC, djaglowski approved these changes

2022-01-24 17:24 UTC, arminru commented on specification/metrics/api.md
> +  package, module or class name. If an application or library has built-in
If one would like to record both the instrumentation library (e.g. `io.opentelemetry.contrib.mongodb`) and the "generic" instrumentation scope (e.g. `MyAppThatsUsingMongoDb` or `com.example.mongodbclient` - both would be applicable now with this definition), they couldn't do that but would need to decide for either, right?

How can telemetry consumers (people looking at the data other than the instrumentation developer, or automated analyzers in backends) distinguish which choice was made and how the value should be interpreted?

2022-01-24 18:40 UTC, tigrannajaryan commented on specification/metrics/api.md
> +  package, module or class name. If an application or library has built-in
>If one would like to record both the instrumentation library (e.g. io.opentelemetry.contrib.mongodb) and the "generic" instrumentation scope (e.g. MyAppThatsUsingMongoDb or com.example.mongodbclient - both would be applicable now with this definition), they couldn't do that but would need to decide for either, right?

Correct, it will not be possible.

This was the exact debate that we had in [LoggerName](https://github.com/open-telemetry/opentelemetry-specification/pull/1236) discussion where I argued that adding LoggerName as an _additional_ field is important because we may want to capture the scope such as class name in _addition_ to the library name. I don't think I was able to convince people, so I am now back to this opposite proposal.

2022-01-25 13:24 UTC, dyladan commented on specification/metrics/api.md
> +  package, module or class name. If an application or library has built-in
Expanding the definition of meter name seems quite dangerous to me. Right now it means something very specific (library name), but if we add this then it could be quite confusing to the user. According to this wording, I could easily just put the class name, losing the information of which library generate the metric.

At the very least, the list should mention "fully qualified class name" or something similar to make it clear that the instrumentation library name is still important here.

A better solution would be to say that in the context of this API, "instrumentation scope" is _always_ the instrumentation library name.

2022-01-25 13:24 UTC, dyladan commented on specification/metrics/api.md
> +  package, module or class name. If an application or library has built-in
Additionally, the list doesn't make it clear if package, module, or class refer to the instrumenting library or the instrumented library. Again, I would prefer to keep the definition restricted here to the instrumentation library name.

This might be fixed by changing the wording to something like "library name, package, module, or class of the instrumentation library" or similar

2022-01-25 13:24 UTC, dyladan commented on specification/trace/api.md
> +  scope](../glossary.md#instrumentation-scope) (e.g.
I have the same complaints here that I do with regards to changes to meter name

2022-01-25 14:11 UTC, tigrannajaryan commented on specification/metrics/api.md
> +  package, module or class name. If an application or library has built-in
> Expanding the definition of meter name seems quite dangerous to me. Right now it means something very specific (library name), but if we add this then it could be quite confusing to the user. According to this wording, I could easily just put the class name, losing the information of which library generate the metric.

This is precisely what I would like us to decide on. Yes, that's exactly the intent of this PR, to make it possible to specify _arbitrary_ string as the instrumentation scope. It is not longer limited to instrumentation library name. I would like the community to either decide that this dilution of the concept is acceptable or reject it. If we as a community do not believe this is the right way I want to see people blocking this PR.

2022-01-25 14:15 UTC, tigrannajaryan commented
@open-telemetry/specs-metrics-approvers @open-telemetry/specs-trace-approvers please review.

2022-01-25 14:21 UTC, dyladan commented on specification/metrics/api.md
> +  package, module or class name. If an application or library has built-in
Even if we don't add logger name separately, it is important not to lose the information of the instrumentation library name. If it is going to be expanded, it needs to be expanded in a way that retains this information (some sort of fully qualified, additional field, etc).

2022-01-25 14:25 UTC, dyladan requested changes
Expanding the definition of a field that was already declared stable such that it is now possible to lose the originally intended information contained in the field  (by using a class name instead of the actual library name) breaks the field.

- This is breaking for receivers who depend on the instrumentation library name being contained in this field, with no way to recover this information
- Logger name will not always refer to the instrumentation library as this field was intended. Actually, it is extremely _unlikely_ to refer to the instrumentation library and would rather refer to the thing being instrumented.

2022-01-25 15:52 UTC, tigrannajaryan commented
@dyladan to clarify, your position is that we should not make this change for Tracer/Meter name because it is a breaking change. You think that it is OK to assign a different meaning to the Logger name field, i.e. accept that it is not going to be consistent with Tracer/Meter name in its semantics.

2022-01-25 15:58 UTC, dyladan commented
> @dyladan to clarify, your position is that we should not make this change for Tracer/Meter name because it is a breaking change. You think that it is OK to assign a different meaning to the Logger name field, i.e. accept that it is not going to be consistent with Tracer/Meter name in its semantics.

Yes. I am against removing the accepted meaning from the tracer and meter name. I would be ok with changing the name of the field for tracer and meter name if the same meaning was retained. This would allow it to be used with a different meaning for logger name. For example, I would say we could call it instrumentation scope if we said for tracer and meter instrumentation scope is always instrumentation name.

WRT the motivation for this PR, I was not involved in the discussion around logger name, but it seems to me that it should be its own field. A single library can and often does create many loggers with many different names, and the names don't always mean the same thing even within the same library (sometimes they refer to the component being monitored, but sometimes they refer to the type of data being monitored, or even the destination the logs are meant to be delivered to). Trying to shoehorn it into an existing field feels like a mistake to me.

2022-01-25 16:04 UTC, Aneurysm9 commented on specification/metrics/api.md
> +  package, module or class name. If an application or library has built-in
I agree with Dan that this seems to be changing the scope of what might be an "instrumentation scope" to the point where it might be impossible to derive any consistent meaning from it.  The prior definition of "instrumentation library" was clear and well-defined and a change away from that at this point feels wrong.

2022-01-25 16:33 UTC, Aneurysm9 commented
> WRT the motivation for this PR, I was not involved in the discussion around logger name, but it seems to me that it should be its own field. A single library can and often does create many loggers with many different names, and the names don't always mean the same thing even within the same library (sometimes they refer to the component being monitored, but sometimes they refer to the type of data being collected, or even the destination the logs are meant to be delivered to). Trying to shoehorn it into an existing field feels like a mistake to me.

I'm still not clear why this data needs to be defined as a top-level, independent field.  As noted here there can be a lot of different meanings when making the concept as general as "scope".  Can this be handled through attributes and semantic conventions?  In my experience with loggers identification of the scope typically happens through the addition of an attribute with a relevant name such as `component` or `scope`.

2022-01-25 16:37 UTC, tigrannajaryan commented
> it seems to me that it should be its own field. A single library can and often does create many loggers with many different names, and the names don't always mean the same thing even within the same library

This was my position as well. I was not able to convince everyone that this is the right approach, particularly @bogdandrutu was against it. Bogdan's reasoning was that instrumentation library name was intended to capture logger name as well. This PR is attempting to solidify that reasoning.

The reason I created this PR is that I want the Spec SIG to rule on one of these 3 approaces:
1. The instrumentation library name is actually meant to be the instrumentation scope, which can be an arbitrary string. In that case I do not need a separate logger name.
2. Or instrument library name is actually just the library name and not an arbitrary string that we can call a "scope". In that case I do need a separate logger name.
3. Logging is inherently different in this subject mater and cannot be consistent with Tracing/Metrics. We should not expect Tracer, Meter and Logger names to have the same semantics.

The current state is neither 1 nor 2 nor 3 and it is blocking the Logging SIG from making progress.

I need us all to choose and settle on one of these approaches (or perhaps there is another way, but I don't see it).

2022-01-25 16:47 UTC, reyang approved these changes

2022-01-25 17:46 UTC, tigrannajaryan commented
Discussed this in Spec SIG meeting and a new idea was brought up: Supply instrumentation library _and_ additional scope (with finer granularity) to obtainer Tracer/Meter/Logger, this would also work if a future Logs API would be added
Would be non-breaking in the API similar to schema_url.

I need some time to think about the feasibility of this idea. If it works this PR will be discarded.

2022-01-25 17:51 UTC, yurishkuro commented
given the concerns with breaking instrumentation library semantic I think an additional (not replacement) scope dimension is the right path

2022-02-01 08:15 UTC, bogdandrutu commented
Also, I hate that I did not push more in https://github.com/open-telemetry/oteps/pull/84 to call that "component", but lots of people were against that :(

2022-02-01 21:08 UTC, bogdandrutu commented on specification/glossary.md
> +  * [Instrumentation Scope](#instrumentation-scope)
Add the "library" as one of the types for scope? or maybe replace it for the moment?

2022-02-01 21:08 UTC, bogdandrutu commented on specification/glossary.md
> +used.
Based on today discussion, make sure we preserve the "uniqueness" suggestion/requirement.

2022-02-01 21:09 UTC, bogdandrutu approved these changes

2022-02-01 21:11 UTC, bogdandrutu commented
@dyladan can you take another look at this after today's discussion?

2022-02-01 23:10 UTC, dyladan reviewed
This proposal hasn't really changed since last week so I have the same concerns I did then.

2022-02-01 23:10 UTC, dyladan commented on specification/glossary.md
> +scopes are also common, e.g. a module, a package, or a class can be chosen as
If a module/package/class is used it should still be globally unique or fully qualified.

2022-02-01 23:10 UTC, dyladan commented on specification/metrics/api.md
> +  package, module or class name. If an application or library has built-in
I still feel the same way I did last week. I thought we had resolved at the spec meeting last week to add an additional scope field and retain library name which was fine with me. This week's spec discussion seemed to indicate that isn't the case anymore though?

2022-02-01 23:11 UTC, bogdandrutu commented on specification/glossary.md
> +scopes are also common, e.g. a module, a package, or a class can be chosen as
https://github.com/open-telemetry/opentelemetry-specification/pull/2276#discussion_r797018366

2022-02-01 23:32 UTC, bogdandrutu commented on specification/metrics/api.md
> +  package, module or class name. If an application or library has built-in
Yes, we discussed this, that the idea of having 2 strings on the wire is fine, but asking users to provide 2 strings will be very confusing. I think we all agreed that the provided string SHOULD be unique as you pointed.

2022-02-04 20:20 UTC, tigrannajaryan commented on specification/metrics/api.md
> +  `io.opentelemetry.contrib.mongodb`), such as the instrumentation library,
Done.

2022-02-04 20:20 UTC, tigrannajaryan commented on specification/trace/api.md
> +  scope](../glossary.md#instrumentation-scope) (e.g.
Done.

2022-02-04 20:20 UTC, tigrannajaryan commented on specification/glossary.md
> +used.
Done.

2022-02-04 20:21 UTC, tigrannajaryan commented on specification/glossary.md
> +  * [Instrumentation Scope](#instrumentation-scope)
We have appropriate references from scope to library in the text. I do not see a good way to restructure the TOC, let's keep as is.

2022-02-04 20:27 UTC, tigrannajaryan commented on specification/glossary.md
> +scopes are also common, e.g. a module, a package, or a class can be chosen as
Done.

2022-02-04 20:27 UTC, tigrannajaryan commented
All, I pushed a new [commit](https://github.com/open-telemetry/opentelemetry-specification/pull/2276/commits/5e7bbf35ec7e1f9d3b61fe21e0007b410ecc07d4) with some additional changes based on the discussions we had so far. What's new in the commit:
- The scope name is explicitly said to be unique (to match previous implicit expectation that library name is unique)
- Added `otel.scope.*` attributes for non-OTLP formats. Kept `otel.library.*` attributes for backwards compatibility reasons, but deprecated and will be removed according to our normal guarantees for "Stable" labels.
- Add InstrumentationScope to ReadableSpan. Kept InstrumentationLibrary as an alias, but deprecated it.

If this PR gets accepted the following additional PRs will be made:
- Change InstrumentationLibrary to InstrumentationScope or to simply Scope in OTLP proto repo. Not breaking wire format.
- Optional: add arbitrary additional `attributes` to InstrumentationScope, with corresponding semantic conventions to record any extra data about the scope we may want. Additive change.

2022-02-04 20:29 UTC, tigrannajaryan commented
@bogdandrutu @carlosalberto @jmacd @djaglowski @MrAlias @reyang @jack-berg please have another look, particularly at the new [commit](https://github.com/open-telemetry/opentelemetry-specification/pull/2276/commits/5e7bbf35ec7e1f9d3b61fe21e0007b410ecc07d4). I did not dismiss all approvals since I don't think the new commit radically changes the PR, but nevertheless it would be good to have another look.

2022-02-04 21:07 UTC, jack-berg commented on specification/trace/api.md
> +  [instrumentation scope](../glossary.md#instrumentation-scope) , such as the
#nit: extra space

2022-02-04 21:09 UTC, jack-berg approved these changes

2022-02-04 21:58 UTC, jmacd approved these changes

2022-02-07 15:07 UTC, tigrannajaryan commented on specification/trace/api.md
> +  [instrumentation scope](../glossary.md#instrumentation-scope) , such as the
Fixed.

2022-02-07 17:19 UTC, mtwo commented
FYI, @dyladan mentioned on the maintainer call that he just got back from vacation and will be able to review this tomorrow

2022-02-07 17:37 UTC, dyladan approved these changes
Looks good to me

2022-02-07 17:49 UTC, arminru commented
> Did we change anything in the `markdownlint` step? It fails on a file that I didn't change.

@tigrannajaryan A breaking change was introduced in markdownlint-cli, #2320 should fix this.

2022-02-07 18:10 UTC, arminru commented on CHANGELOG.md
> +- Clarify that Tracer is associated with Instrumentation Scope
This should reflect that an additional term was introduced and the former occurrences were changed to this new term, it's not just a clarification.
Especially the ReadableSpan representation and non-OTLP exporters need to be changed accordingly which might otherwise be overlooked.

2022-02-07 18:10 UTC, arminru commented on specification/trace/sdk_exporters/non-otlp.md
> +The following deprecated aliases are also reported with exact same values for
```suggestion
The following deprecated aliases MUST also be reported with exact same values for
```

2022-02-07 18:10 UTC, arminru commented on specification/glossary.md
> +code that emits the telemetry. A typical approach to ensure uniqueness is to use
The uniqueness is a normative requirement. Is it sufficient to mention this in the Glossary or should this go into the respective spec sections?

2022-02-07 18:21 UTC, arminru commented on CHANGELOG.md
> +- Clarify that Tracer is associated with Instrumentation Scope
We should also add entries to the spec compliance matrix to track these changes across SDKs so that it will eventually be consistent.

2022-02-07 21:32 UTC, tigrannajaryan commented on specification/trace/sdk_exporters/non-otlp.md
> +The following deprecated aliases are also reported with exact same values for
Fixed.

2022-02-07 21:36 UTC, tigrannajaryan commented on specification/trace/sdk.md
> +  able to access the `InstrumentationScope` [since 1.9.0] and `Resource`
We already have similar references, e.g. here https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#get-a-tracer

They use the form `[since x.y.z]`. I think this is clear enough, there is no need for additional verbosity.

2022-02-07 21:45 UTC, tigrannajaryan commented on CHANGELOG.md
> +- Clarify that Tracer is associated with Instrumentation Scope
Added entries to compliance matrix.

2022-02-07 21:45 UTC, tigrannajaryan commented on specification/glossary.md
> +code that emits the telemetry. A typical approach to ensure uniqueness is to use
The requirement is also listed in respective API section.

2022-02-08 11:34 UTC, arminru commented on specification/trace/sdk_exporters/non-otlp.md
> +| `InstrumentationScope.version`|`otel.scope.version`|since 1.9.0|
Just noticed one more reference to the previous term here:
https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/common/attribute-naming.md#otel-namespace

2022-02-08 14:29 UTC, tigrannajaryan commented on specification/trace/sdk_exporters/non-otlp.md
> +| `InstrumentationScope.version`|`otel.scope.version`|since 1.9.0|
Fixed.

2022-02-08 15:11 UTC, tigrannajaryan commented
@open-telemetry/specs-trace-approvers please review.

2022-02-08 16:06 UTC, pmm-sumo approved these changes

2022-02-09 14:32 UTC, tigrannajaryan commented
@carlosalberto if we are planning the 1.9.0 release in the next couple day I suggest we hold this PR until the release and merge after.

2022-02-09 16:17 UTC, bogdandrutu commented on specification/trace/sdk_exporters/non-otlp.md
> +|`otel.library.version`|`otel.scope.version`|deprecated since since 1.9.0|
Add a note since when.

2022-02-09 17:29 UTC, arminru commented on specification/trace/sdk_exporters/non-otlp.md
> +|`otel.library.name`|`otel.scope.name`|deprecated since since 1.9.0|
Duplicate "since" and as per your last comment you'll need to bump this to v1.10

2022-02-09 19:54 UTC, tigrannajaryan commented on specification/trace/sdk_exporters/non-otlp.md
> +|`otel.library.version`|`otel.scope.version`|deprecated since since 1.9.0|
There is a note next to each attribute. Do you want something additional?

2022-02-10 17:59 UTC, lzchen approved these changes

2022-02-11 08:42 UTC, arminru commented on spec-compliance-matrix.md
>  | Create TracerProvider                                                                            |          | +   | +    | +   | +      | +    | +      | +   | +    | +   | +    | +     |
There are still a few items referencing InstrumentationLibrary in the Metrics and Exporter sections (out of reach for directly commenting on them).

2022-02-14 16:12 UTC, tigrannajaryan commented
@open-telemetry/specs-approvers @open-telemetry/specs-trace-approvers @open-telemetry/specs-metrics-approvers  This is the last chance to object to this PR. I will merge if I don't hear any objections.

2022-02-14 16:59 UTC, jmacd approved these changes

2022-02-14 22:56 UTC, MovieStoreGuy approved these changes

2022-02-15 16:34 UTC, merged

2022-02-18 20:07 UTC, jack-berg commented on specification/trace/api.md
>  - `version` (optional): Specifies the version of the instrumentation library (e.g. `1.0.0`).
Shouldn't `version`'s description have been updated as part of this PR?

2022-02-21 17:58 UTC, arminru commented on specification/trace/api.md
>  - `version` (optional): Specifies the version of the instrumentation library (e.g. `1.0.0`).
Good catch, thanks! I created #2371 to track it since comments on merged PRs are often overlooked.