Add semantic conventions for jvm cpu metrics
open-telemetry/opentelemetry-specification pull request #2292
Opened 2022-01-25 23:27 UTC by jonatan-ivanov

Initial draft at JVM runtime cpu semantic conventions.

/cc @trask @jack-berg

2022-01-26 17:16 UTC, jack-berg commented on specification/metrics/semantic_conventions/runtime-environment-metrics.md
> +| process.runtime.jvm.cpu.usage                  | The "recent cpu usage" for the process                   | 1       | 1                                         | Gauge                      | Double
I believe `usage` should be changed to `utilization` to match conventions elsewhere:
- [system metric semantic conventions](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/system-metrics.md
- Semantic convention [instrument naming](https://github.com/open-telemetry/opentelemetry-specification/tree/main/specification/metrics/semantic_conventions#instrument-naming)

2022-01-26 17:16 UTC, jack-berg commented on specification/metrics/semantic_conventions/runtime-environment-metrics.md
> +| process.runtime.jvm.system.cpu.load.average.1m | Average CPU load of the whole system for the last minute | 1       | 1                                         | Gauge                      | Double
I assume this will come from (OperatingSystemMXBean#getSystemLoadAverage())[https://docs.oracle.com/javase/7/docs/jre/api/management/extension/com/sun/management/OperatingSystemMXBean.html#getSystemCpuLoad()]. 

The definition of load defined in `#getSystemLoadAverage()` seems pretty esoteric. Should we include it in the semantic conventions?

2022-01-26 17:16 UTC, jack-berg commented on specification/metrics/semantic_conventions/runtime-environment-metrics.md
> +| process.runtime.jvm.system.cpu.count           | Number of processors available to use                    | 1       | 1                                         | Gauge                      | Int32
I wonder why there isn't a general (system instrument)[https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/system-metrics.md#systemcpu---processor-metrics] metric for cpu count.

2022-01-26 17:16 UTC, jack-berg commented on specification/metrics/semantic_conventions/runtime-environment-metrics.md
> +| process.runtime.jvm.common.pool.parallelism    | Targeted parallelism level of the common pool            | 1       | 1                                         | Gauge                      | Int32
Does this come from `ForkJoinPool#getPoolsize()`?

2022-01-29 01:02 UTC, jsuereth commented on specification/metrics/semantic_conventions/runtime-environment-metrics.md
> +| process.runtime.jvm.system.cpu.count           | Number of processors available to use                    | 1       | 1                                         | Gauge                      | Int32
that's a good call out.

2022-01-29 05:39 UTC, jonatan-ivanov commented on specification/metrics/semantic_conventions/runtime-environment-metrics.md
> +| process.runtime.jvm.system.cpu.load.average.1m | Average CPU load of the whole system for the last minute | 1       | 1                                         | Gauge                      | Double
Yes, I created a gist where you can see where are these values are coming from: https://gist.github.com/jonatan-ivanov/0449619cb6f851ce67d70e47a6a1fb73

I also included some explanation and examples.
In this exact case, I guess we can copy from the javadoc or refer it in the spec to make the description more concise.

2022-01-29 05:45 UTC, jonatan-ivanov commented on specification/metrics/semantic_conventions/runtime-environment-metrics.md
> +| process.runtime.jvm.common.pool.parallelism    | Targeted parallelism level of the common pool            | 1       | 1                                         | Gauge                      | Int32
Should be either `ForkJoinPool.commonPool().getParallelism()` or `ForkJoinPool.getCommonPoolParallelism()`.

2022-02-10 22:47 UTC, jack-berg commented
Here's a summary of the proposed metrics and their corresponding sources. Hopefully this makes it a bit easier to evaluate the value of these. This summarizes the information from @jonatan-ivanov's [gist](https://gist.github.com/jonatan-ivanov/0449619cb6f851ce67d70e47a6a1fb73).
- `process.runtime.jvm.cpu.time` - [com.sun.management.OperatingSystemMXBean#getProcessCpuTime()](https://docs.oracle.com/javase/7/docs/jre/api/management/extension/com/sun/management/OperatingSystemMXBean.html#getProcessCpuTime())
- `process.runtime.jvm.cpu.utilization` - [com.sun.management.OperatingSystemMXBean#getProcessCpuLoad()](https://docs.oracle.com/javase/7/docs/jre/api/management/extension/com/sun/management/OperatingSystemMXBean.html#getProcessCpuLoad())
- `process.runtime.jvm.common.pool.parallelism` - [java.util.concurrent.ForkJoinPool#getParallelism()](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ForkJoinPool.html#getParallelism--)
- `process.runtime.jvm.system.cpu.utilization` -  [com.sun.management.OperatingSystemMXBean#getSystemCpuLoad()](https://docs.oracle.com/javase/7/docs/jre/api/management/extension/com/sun/management/OperatingSystemMXBean.html#getSystemCpuLoad())
- `process.runtime.jvm.system.cpu.count` - [java.lang.Runtime#availableProcessors()](https://docs.oracle.com/javase/7/docs/api/java/lang/Runtime.html#availableProcessors())
- `process.runtime.jvm.system.cpu.load.average.1m` - [java.lang.management.OperatingSystemMXBean#getSystemLoadAverage()](https://docs.oracle.com/javase/8/docs/api/java/lang/management/OperatingSystemMXBean.html#getSystemLoadAverage--)

2022-02-25 16:04 UTC, jack-berg commented
We discussed in the 2/24/2022 Java SIG meeting. Can java folks take a look at this and comment?

/cc @kittylyst @trask

My thoughts:
- `process.runtime.jvm.cpu.time`, `process.runtime.jvm.cpu.utilization` are obvious and we should merge those quickly.
- `process.runtime.jvm.common.pool.parallelism` seems more related to the thread pool topic we discussed. Maybe we should save it for a future PR where we declare the conventions for thread pools.
- `process.runtime.jvm.system.cpu.utilization` has overlap with the more general `system.cpu.utilization`, but we don't have access to the data required for the attributes. I think we should include this now.
- `process.runtime.jvm.system.cpu.count` I think we should incude this now.
- `process.runtime.jvm.system.cpu.load.average.1m` useful, but overlaps with `process.runtime.jvm.cpu.time` & `process.runtime.jvm.cpu.utilization`. I'd be fine skipping this for now.

2022-02-28 23:28 UTC, trask commented
I'm thinking now that it may be good to reuse `system.cpu.time`, `process.cpu.time`, and `system.cpu.count` since there aren't any JVM-specific attributes that we want to capture on them.

I have sent #2388 to clarify that these should be interpreted as container-level and not host-level metrics when emitted from inside a container.

Should we scale back this PR for now to just these two?
* `process.runtime.jvm.cpu.utilization`
* `process.runtime.jvm.system.cpu.utilization`

I noticed there's already a `system.cpu.utilization` metric (and so seems likely to be a `process.cpu.utilization` metric), but this is [defined](https://github.com/open-telemetry/opentelemetry-specification/tree/main/specification/metrics/semantic_conventions#instrument-naming) in a way that I think is incompatible with what the JVM gives us:

> `system.cpu.utilization` is defined as the difference in `system.cpu.time` measurements divided by the elapsed time

so I don't think we should reuse in this case and need one under `process.runtime.jvm.*`

2022-03-02 18:07 UTC, trask commented
I think we have more clarity now from discussions in #2384 and #2388.

I think there's still one open question https://github.com/open-telemetry/opentelemetry-specification/pull/2392#issuecomment-1057222928 and then I think we'll have clarity on how to proceed.

@jonatan-ivanov thanks for your patience

2022-03-04 03:36 UTC, trask commented on specification/metrics/semantic_conventions/runtime-environment-metrics.md
> +| process.runtime.jvm.cpu.time                   | The CPU time used by the process                         | seconds | `s`                                       | Asynchronous Counter       | Double
let's remove this and optimistically use `process.cpu.time` pending clarification in #2392 about using the `process.*` namespace

```suggestion
```

2022-03-04 03:36 UTC, trask commented on specification/metrics/semantic_conventions/runtime-environment-metrics.md
> +| process.runtime.jvm.system.cpu.count           | Number of processors available to use                    | 1       | 1                                         | Gauge                      | Int32
let's remove this and optimistically use `process.cpu.count` pending clarification in #2392 about using the `process.*` namespace

```suggestion
```

2022-03-04 03:36 UTC, trask commented on specification/metrics/semantic_conventions/runtime-environment-metrics.md
> +| process.runtime.jvm.common.pool.parallelism    | Targeted parallelism level of the common pool            | 1       | 1                                         | Gauge                      | Int32
from @jack-berg above (below?)
> * `process.runtime.jvm.common.pool.parallelism` seems more related to the thread pool topic we discussed. Maybe we should save it for a future PR where we declare the conventions for thread pools.
```suggestion
```

2022-03-04 03:36 UTC, trask commented on specification/metrics/semantic_conventions/runtime-environment-metrics.md
> +| process.runtime.jvm.system.cpu.load.average.1m | Average CPU load of the whole system for the last minute | 1       | 1                                         | Gauge                      | Double
from @jack-berg

> * `process.runtime.jvm.system.cpu.load.average.1m` useful, but overlaps with `process.runtime.jvm.cpu.time` & `process.runtime.jvm.cpu.utilization`. I'd be fine skipping this for now.

I'd lean toward keeping this in the PR, especially if it's something that micrometer and others are already collecting

2022-03-12 04:24 UTC, trask commented
/unstale

2022-03-17 22:55 UTC, jack-berg approved these changes

2022-03-17 22:55 UTC, jack-berg commented on specification/metrics/semantic_conventions/runtime-environment-metrics.md
> +| process.runtime.jvm.system.cpu.load.average.1m | Average CPU load of the whole system for the last minute | 1       | 1                                         | Gauge                      | Double
Can you change `Gauge` => `Asynchronous Gauge` for consistency with the other convetions, e.g. [system](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/system-metrics.md)?

2022-03-17 23:01 UTC, trask approved these changes

2022-03-17 23:01 UTC, trask commented on specification/metrics/semantic_conventions/runtime-environment-metrics.md
> +| process.runtime.jvm.system.cpu.load.average.1m | Average CPU load of the whole system for the last minute | 1       | 1                                         | Gauge                      | Double
based on [this](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/system-metrics.md#systemos---os-specific-system-metrics) (and because it's shorter):

> An instrument for load average over 1 minute on Linux could be named `system.linux.cpu.load_1m`

```suggestion
| process.runtime.jvm.system.cpu.load_1m | Average CPU load of the whole system for the last minute | 1       | 1                                         | Gauge                      | Double     |               |                       |
```

2022-03-19 06:50 UTC, jonatan-ivanov commented
Could somebody please approve the workflow so that the linters can check it?

2022-03-21 17:51 UTC, trask commented
@jonatan-ivanov #2426 will fix the failing `markdown-link-check`

2022-03-22 05:07 UTC, anuraaga approved these changes

2022-03-22 18:02 UTC, trask commented on specification/metrics/semantic_conventions/runtime-environment-metrics.md
> +| process.runtime.jvm.system.cpu.utilization     | The "recent cpu usage" for the whole system              | 1       | 1                                         | Asynchronous Gauge         | Double
```suggestion
| process.runtime.jvm.cpu.utilization            | Recent cpu utilization for the process                   | 1       | 1                                         | Asynchronous Gauge         | Double     |               |                       |
| process.runtime.jvm.system.cpu.utilization     | Recent cpu utilization for the whole system              | 1       | 1                                         | Asynchronous Gauge         | Double     |               |                       |
```

2022-03-23 08:57 UTC, mateuszrzeszutek approved these changes

2022-03-24 04:20 UTC, trask commented on specification/metrics/semantic_conventions/runtime-environment-metrics.md
> +| process.runtime.jvm.system.cpu.utilization     | Recent cpu utilization for the whole system              | 1       | 1                                         | Asynchronous Gauge         | Double
see recent discussion in https://github.com/open-telemetry/opentelemetry-specification/pull/2392#discussion_r833018035 (and follow-ups in #2435 and #2436)

with [2] being something like: These utilizations are not defined as being for the specific interval since last measurement (unlike `system.cpu.utilization`).

```suggestion
| process.runtime.jvm.cpu.utilization            | Recent cpu utilization for the process [2]               | 1       | 1                                         | Asynchronous Gauge         | Double     |               |                       |
| process.runtime.jvm.system.cpu.utilization     | Recent cpu utilization for the whole system [2]          | 1       | 1                                         | Asynchronous Gauge         | Double     |               |                       |
```

2022-03-30 22:16 UTC, bogdandrutu requested changes
Please describe the motivation to have these metrics.

2022-04-06 00:02 UTC, trask commented
> Please describe the motivation to have these metrics.

These are metrics which are captured by Micrometer today. The Micrometer team would like to move to OpenTelemetry semantic conventions once they are stabilized, and this is part of that effort.

These are metrics which the JVM has been producing for a long time, and the JVM metrics working group believes there is a significant benefit to defining standard metric names for them, to promote interoperability in the Java ecosystem.

2022-04-15 02:26 UTC, trask commented
> Please describe the motivation to have these metrics.

@bogdandrutu does my response above address your question/concern?

2022-04-21 00:38 UTC, trask commented
@open-telemetry/technical-committee it would be helpful if we could get some guidance on how/if to move this forward, thx!

2022-04-28 16:52 UTC, trask commented
@bogdandrutu?

2022-05-09 23:54 UTC, trask commented
@open-telemetry/technical-committee is this not the right place to define JVM metrics that we want to emit? should we just document these in the Java repo and create our own "java" schema url? thx

2022-05-10 15:22 UTC, bogdandrutu commented on specification/metrics/semantic_conventions/runtime-environment-metrics.md
>  All JVM metric attributes are required unless otherwise indicated.
What does it mean for a set of metrics to be "required"? If I enable jvm metrics I get all? All metrics are available, I just need to enable them? All are enabled by default if I use otel?

2022-05-10 15:22 UTC, bogdandrutu commented on specification/metrics/semantic_conventions/runtime-environment-metrics.md
> +| process.runtime.jvm.cpu.utilization            | Recent cpu utilization for the process [2]               | 1       | 1                                         | Asynchronous Gauge
I understand this, +1

2022-05-10 15:22 UTC, bogdandrutu commented on specification/metrics/semantic_conventions/runtime-environment-metrics.md
> +| process.runtime.jvm.system.cpu.load_1m         | Average CPU load of the whole system for the last minute | 1       | 1                                         | Asynchronous Gauge
I am not sure "system" metrics should be under "process"... something seems off here. We have different section for process and system, see https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/process-metrics.md and https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/system-metrics.md

2022-05-11 00:40 UTC, trask commented on specification/metrics/semantic_conventions/runtime-environment-metrics.md
>  All JVM metric attributes are required unless otherwise indicated.
> What does it mean for a set of metrics to be "required"?

I may not understand your question here, none of these metrics are required.

> If I enable jvm metrics I get all?

The OTel Java SDK will not emit any JVM metrics.

There will be "JVM metrics" instrumentation which users can apply if they want to get these metrics.

It hasn't been decided yet which JVM metrics this instrumentation would emit by default, and which would require an additional opt-in (beyond enabling the instrumentation).

> All metrics are available, I just need to enable them? All are enabled by default if I use otel?

Let me know if these questions aren't answered by the above.

2022-05-11 00:46 UTC, trask commented on specification/metrics/semantic_conventions/runtime-environment-metrics.md
> +| process.runtime.jvm.system.cpu.load_1m         | Average CPU load of the whole system for the last minute | 1       | 1                                         | Asynchronous Gauge
Would it be ok to put them under `system.*`, and still emit them from the JVM, and let the resource attributes tell the receiver that they are coming from the JVM and not from a "collector"?

2022-05-11 14:54 UTC, bogdandrutu commented on specification/metrics/semantic_conventions/runtime-environment-metrics.md
> +| process.runtime.jvm.system.cpu.load_1m         | Average CPU load of the whole system for the last minute | 1       | 1                                         | Asynchronous Gauge
I think will be ok. I would use the instrumentation scope/name, that will also be different correct? Should we do the same for process CPU then? Still not sure we should do this instrumentation twice but looks like the java folks are really committed to duplicate this work 🤣

2022-05-11 14:57 UTC, bogdandrutu commented on specification/metrics/semantic_conventions/runtime-environment-metrics.md
> +| process.runtime.jvm.system.cpu.load_1m         | Average CPU load of the whole system for the last minute | 1       | 1                                         | Asynchronous Gauge
@trask would ne definitely good to make these metrics that are same with collector an opt in for the JVM metrics package. Since enabling them and using the collector may cause confusion, and trust me that is the standard across all our clients (to use the collector for these) and would be very bad to make these enable by default

2022-05-13 04:20 UTC, trask commented on specification/metrics/semantic_conventions/runtime-environment-metrics.md
> +| process.runtime.jvm.system.cpu.load_1m         | Average CPU load of the whole system for the last minute | 1       | 1                                         | Asynchronous Gauge
> I would use the instrumentation scope/name, that will also be different correct?

👍

> would definitely be good to make these metrics that are same with collector an opt in for the JVM metrics package. Since enabling them and using the collector may cause confusion, and trust me that is the standard across all our clients (to use the collector for these) and would be very bad to make these enable by default

I support this message, that the OTel Collector is the preferred deployment option in the OpenTelemetry ecosystem, and so defaults should be optimized for those users.

I will submit separate spec clarification(s) about these recommendations around emitting `system.*` and `process.*` metrics from a non-"collector".

I think that will address some other metrics we want to emit from the JVM (e.g. #2439), but sadly the particular system and process metrics in this PR pose one additional challenge because:

> These utilizations are not defined as being for the specific interval since last measurement (unlike `system.cpu.utilization`)

Because of this limitation, these metrics are definitely subpar to the existing `system.*` and `process.*` metrics, and we only emit them because they are what's available from the JVM. And so I wonder if we should keep these under the `jvm` metric namespace.

Or do you think we should emit under (e.g.) `system.cpu.utilization` and just call it a best-effort, even though it doesn't match the specification for that metric:

> Difference in system.cpu.time since the last measurement, divided by the elapsed time and number of CPUs

2022-05-24 18:51 UTC, reyang commented
I've removed the `Stale` tag.
Given we've got a good number of approvals from Java experts, I want to see if there is any blocker from @bogdandrutu and @jsuereth. If there is no blocker, I think we should move forward.

2022-05-24 20:34 UTC, trask commented on specification/metrics/semantic_conventions/runtime-environment-metrics.md
> +| process.runtime.jvm.system.cpu.load_1m         | Average CPU load of the whole system for the last minute | 1       | 1                                         | Asynchronous Gauge
btw, discussed this (^^^) with JVM metrics folks, and we are recommending to keep the particular system/process metrics in this PR under the jvm metric namespace since they don't match (and are subpar) to the existing metrics under the system/process metric namespace

2022-05-26 03:26 UTC, reyang commented
@jonatan-ivanov would you resolve the merge conflicts and clear the CI? Thanks!

2022-05-26 03:29 UTC, reyang commented on specification/metrics/semantic_conventions/runtime-environment-metrics.md
> +| process.runtime.jvm.classes.unloaded           | Number of classes unloaded since JVM start               | classes | `{classes}`                               | UpDownCounter
I'm not a Java guy, is the "number of classes unloaded since JVM start" going to go up and \*down\*, or it should be a `Counter`?

2022-05-26 03:29 UTC, reyang commented on specification/metrics/semantic_conventions/runtime-environment-metrics.md
> +| process.runtime.jvm.classes.unloaded           | Number of classes unloaded since JVM start               | classes | `{classes}`                               | UpDownCounter
Doesn't have to be resolved in this PR since it was introduced by other PRs.

2022-05-26 03:58 UTC, trask commented on specification/metrics/semantic_conventions/runtime-environment-metrics.md
> +| process.runtime.jvm.classes.unloaded           | Number of classes unloaded since JVM start               | classes | `{classes}`                               | UpDownCounter
check out https://github.com/open-telemetry/opentelemetry-specification/pull/2478#discussion_r853173523

> represented as an UpDownCounter because the rate of class loading is not an important factor and the absolute number of classes loaded is an important factor

I'll send a PR to document this reasoning (and to see if there are any objections)

2022-05-26 04:10 UTC, trask commented on specification/metrics/semantic_conventions/runtime-environment-metrics.md
> +| process.runtime.jvm.classes.unloaded           | Number of classes unloaded since JVM start               | classes | `{classes}`                               | UpDownCounter
oh wait, we changed it to Counter in #2550

2022-05-26 20:25 UTC, jonatan-ivanov commented
@reyang Would you approve the workflow to run?

2022-05-27 03:28 UTC, reyang approved these changes
LGTM.

2022-05-27 03:29 UTC, merged

2022-05-27 03:30 UTC, reyang commented
@jonatan-ivanov please send a follow up PR to update the changelog (which is an editorial/trivial change).

2022-05-27 05:40 UTC, jonatan-ivanov commented
@reyang Thanks! Here is the PR for the changelog entry: https://github.com/open-telemetry/opentelemetry-specification/pull/2584