Clarify that instrument name conflict only happens within a Meter
open-telemetry/opentelemetry-specification pull request #2372
Opened 2022-02-22 04:54 UTC by reyang

Fixes #2337.

Based on the [2/15/2022 Spec SIG Meeting](https://docs.google.com/document/d/1pdvPeKjA8v8w_fGKAN68JjWBmVJtPCpqdi9IZrd6eEo/edit?pli=1#heading=h.ixd3fm5gwjy1) discussion and reading through [RFC2119](https://www.rfc-editor.org/rfc/rfc2119.html).

2022-02-22 15:32 UTC, jmacd approved these changes

2022-02-22 18:35 UTC, cijothomas approved these changes

2022-02-22 18:47 UTC, bogdandrutu approved these changes

2022-02-23 21:19 UTC, jack-berg approved these changes

2022-02-23 22:47 UTC, ocelotl commented on specification/metrics/sdk.md
> +SDK SHOULD NOT allow Views with a specified name to be declared with instrument
This can't be enforced. When a view is declared, it is not known if it will match more than one instrument in the same meter.

2022-02-23 22:49 UTC, ocelotl commented on specification/metrics/sdk.md
> +in the same Meter.
```suggestion
A view with a specified name should match at most one instrument in the same Meter.
```

2022-02-23 22:51 UTC, ocelotl commented on specification/metrics/sdk.md
> +in the same Meter.
This should also specify which one of the instruments in the same meter that can match the view is the one that would be matched or indicate that it is not specified which one of the instruments in the same meter that can match the view is the one that would be matched.

2022-02-23 22:51 UTC, ocelotl requested changes
The requirement as it is stated now can't be enforced.

2022-02-24 04:10 UTC, reyang commented on specification/metrics/sdk.md
> +SDK SHOULD NOT allow Views with a specified name to be declared with instrument
> This can't be enforced.

Here we picked the wording "SHOULD NOT" rather than "MUST NOT" so it's not enforcement.

> When a view is declared, it is not known if it will match more than one instrument in the same meter.

That's correct, here we are saying that folks should not allow wild card name or something that allows multiple matches.

2022-02-24 04:13 UTC, reyang commented on specification/metrics/sdk.md
> +in the same Meter.
From the SDK perspective, all of them would match.
When it comes to particular exporter, things might be different - e.g. OTLP exporter (based on the data model) supports this scenario. For exporters that don't support this (e.g. Prometheus), we should spec it out in the exporter doc (e.g. that's why Prometheus Exporter spec is in its current state).

2022-02-25 22:59 UTC, ocelotl commented on specification/metrics/sdk.md
> +SDK SHOULD NOT allow Views with a specified name to be declared with instrument
Consider this situation:

``` python
meter_provider = MeterProvider(
    views=[View(instrument_name="foo.bar*", name="baz")],
)
meter1 = meter_provider.get_meter("library1")
meter2 = meter_provider.get_meter("library2")

meter1.create_counter("foo.bar")
meter2.create_counter("foo.bar")
```

Here we have a situation that will not cause conflicts in the output metrics (because the view will match instruments in different meters) but the wording of the spec will not allow it.

The case above can be easily fixed by the user by just removing the `*` in the instrument name, so maybe it is ok that the spec forbids a valid case like this one.

2022-02-25 23:01 UTC, ocelotl commented on specification/metrics/sdk.md
> +selectors that select more than one instrument (e.g. wild card instrument name)
```suggestion
selectors that may select more than one instrument (e.g. wild card instrument name)
```
It is not known when the view is declared if it will match more than one instrument in the same meter or not.

2022-02-25 23:03 UTC, ocelotl commented on specification/metrics/sdk.md
> +in the same Meter.
Ok, I think the intention of the spec is to ban the declaration of a named view with any instrument selector that may end up matching more than one instrument in the same meter _without specifying which instrument selectors can do so_. Changing my request for changes to comment.

2022-02-25 23:04 UTC, ocelotl reviewed
Changed from request changes to comment.

2022-02-26 02:28 UTC, reyang commented on specification/metrics/sdk.md
> +SDK SHOULD NOT allow Views with a specified name to be declared with instrument
Exactly, the intention is to not allow it for now. If later we want to allow it, we can (which is an additive change rather than breaking change).

2022-02-28 15:55 UTC, ocelotl commented on specification/metrics/sdk.md
> +SDK SHOULD NOT allow Views with a specified name to be declared with instrument
All right, resolving.

2022-02-28 15:55 UTC, ocelotl approved these changes

2022-03-01 04:09 UTC, merged