feature/rpc: add rpc.type and rpc.status for metrics.
open-telemetry/opentelemetry-specification pull request #2430
Opened 2022-03-23 11:58 UTC by 1046102779

https://github.com/open-telemetry/opentelemetry-specification/issues/2419

2022-03-23 16:16 UTC, trask commented
hi @1046102779! I liked @arminru's https://github.com/open-telemetry/opentelemetry-specification/issues/2419#issuecomment-1074961559 proposing these as general metric attributes that can be used across all semantic conventions

2022-03-25 05:14 UTC, reyang commented on semantic_conventions/trace/rpc.yaml
> +      - id: type
For traces, the [span kind](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#spankind) already has this information.

2022-03-25 05:15 UTC, reyang commented on semantic_conventions/trace/rpc.yaml
> +      - id: status
Same here, the [span status](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#set-status) has covered this.

2022-03-25 05:19 UTC, reyang requested changes
I understand that the intention is to have something similar like [http.status_code](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/http-metrics.md#attributes) and such intention makes total sense to me. However, I thinking adding this to `semantic_conventions/trace/rpc.yaml` is going to introduce problem to traces as it introduces to span kind/status?

2022-04-10 03:20 UTC, closed without merging