Adding environment variables for capturing Http headers
open-telemetry/opentelemetry-specification pull request #2461
Opened 2022-03-31 09:39 UTC by ashu658

## Changes
Add environment variables to be configured for capturing http headers. 
This [spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/http.md#http-request-and-response-headers) describes  how to capture the http request/response header and add them in the span. It does not specify the environment variables need to be configured to capture the headers. This change specifies these environment variables.

Env vars proposed in the PR are already supported in [Java](https://github.com/open-telemetry/opentelemetry.io/blob/b04b753c9a5c9d14899053b78bbd46bb51dfa97e/content/en/docs/instrumentation/java/automatic/agent-config.md#capturing-http-request-and-response-headers) and [Python](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/util/opentelemetry-util-http/src/opentelemetry/util/http/__init__.py#L21) sdks. 

Related PR: https://github.com/open-telemetry/opentelemetry-specification/pull/1898  

Additional info: 
One thing that I have seen in python is that headers provided by some frameworks/libraries (e.g. wsgi based frameworks like flask) are lowercase and `-` is replaced with `_` which would mean user who configures
`OTEL_INSTRUMENTATION_HTTP_CAPTURE_HEADERS_SERVER_REQUEST="CusTOM_HEAder-1"`
will be able to capture ``custom-header-1`` from request headers for some frameworks/libraries whereas for some other frameworks he won't be able to capture this header as it does not change `-` to `_`.
(All python frameworks/libraries I saw provides case-insensitive headers but only some of them replace `-` with `_`)
Mentioning this info here as I am not sure if it might affect this spec or not.

2022-04-04 16:49 UTC, reyang requested changes
https://github.com/open-telemetry/opentelemetry-specification/pull/2461/files#r841949238

2022-04-04 17:11 UTC, jmacd commented on specification/sdk-environment-variables.md
> +| OTEL_INSTRUMENTATION_HTTP_CAPTURE_HEADERS_SERVER_REQUEST  | A comma-separated list of HTTP header names. HTTP server instrumentations will capture HTTP request header values for all configured head
Are these header names case-sensitive? Can you add a sentence or two saying what implementations are required to do with these variables in explicit terms?

2022-04-05 14:55 UTC, dyladan commented on specification/sdk-environment-variables.md
> +| OTEL_INSTRUMENTATION_HTTP_CAPTURE_HEADERS_SERVER_REQUEST  | A comma-separated list of HTTP header names. HTTP server instrumentations will capture HTTP request header values for all configured head
From [[RFC 7230] Section 3.2: Header Fields](https://datatracker.ietf.org/doc/html/rfc7230#section-3.2)

>Each header field consists of a **case-insensitive** field name followed
   by a colon (":"), optional leading whitespace, the field value, and
   optional trailing whitespace.

emphasis mine

2022-04-05 14:57 UTC, dyladan commented
> One thing that I have seen in python is that headers provided by some frameworks/libraries (e.g. wsgi based frameworks like flask) are lowercase and `-` is replaced with `_` which would mean user who configures
> `OTEL_INSTRUMENTATION_HTTP_CAPTURE_HEADERS_SERVER_REQUEST="CusTOM_HEAder-1"`
> will be able to capture `custom-header-1` from request headers for some frameworks/libraries whereas for some other frameworks he won't be able to capture this header as it does not change `-` to `_`.
> (All python frameworks/libraries I saw provides case-insensitive headers but only some of them replace `-` with `_`)
> Mentioning this info here as I am not sure if it might affect this spec or not.

This seems very Python-specific to me and depends heavily on the library being used and the idioms of the ecosystem. I think this would be considered very confusing by most non-python users.

2022-04-05 15:55 UTC, ashu658 commented
> This seems very Python-specific to me and depends heavily on the library being used and the idioms of the ecosystem. I think this would be considered very confusing by most non-python users.
@dyladan thanks for the feedback! I was not sure if this might affect the spec so, mentioned it here.

2022-04-05 16:06 UTC, yurishkuro commented
@open-telemetry/technical-committee I just did a quick search and did not find any env vars of the patten `OTEL_INSTRUMENTATION_*`. Which is understandable because so far the env vars were limited to configuring the SDKs. Capturing headers is not an SDK function, it's an instrumentation function. We have already heard concerns with having too many env vars that need to be supported by all SDKs. Do we want to extend this even further to configuring instrumentation libraries?

2022-04-05 16:14 UTC, dyladan commented
> @open-telemetry/technical-committee I just did a quick search and did not find any env vars of the patten `OTEL_INSTRUMENTATION_*`. Which is understandable because so far the env vars were limited to configuring the SDKs. Capturing headers is not an SDK function, it's an instrumentation function. We have already heard concerns with having too many env vars that need to be supported by all SDKs. Do we want to extend this even further to configuring instrumentation libraries?

Discussed this briefly on the spec call today and I think the consensus was that instrumentation-specific configuration doesn't belong in the SDK spec. The greater takeaway was the need for a consistent configuration specification and mechanism to ensure we can provide these configurations and others to all instrumentations in a consistent manner and document them appropriately. I can't remember who exactly but I think someone volunteered to get the ball rolling in that area.

2022-04-05 16:24 UTC, ashu658 commented on specification/sdk-environment-variables.md
> +| OTEL_INSTRUMENTATION_HTTP_CAPTURE_HEADERS_SERVER_REQUEST  | A comma-separated list of HTTP header names. HTTP server instrumentations will capture HTTP request header values for all configured head
The spec which describes how to capture the HTTP headers https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/http.md#http-request-and-response-headers requires the captured header names to be normalised (lowercase, with - characters replaced by _) when added as span attributes. So, two different header fields (e.g. `custom-header` and `custom_header`) will have the same span attribute key when added as span attribute. 
I am not sure if this would be okay. Please share your thoughts.

2022-04-05 16:46 UTC, dyladan commented on specification/sdk-environment-variables.md
> +| OTEL_INSTRUMENTATION_HTTP_CAPTURE_HEADERS_SERVER_REQUEST  | A comma-separated list of HTTP header names. HTTP server instrumentations will capture HTTP request header values for all configured head
Looks like the proposal for that behavior was done there by @Oberon00 https://github.com/open-telemetry/opentelemetry-specification/pull/1898#issuecomment-914238509

The motivation for lowercasing is obvious enough, but it seems the motivation to transform `-` to `_` was simply so that it would comply with the naming convention of our other semantic conventions? IMO the transformation was a mistake but one that it might be too late to rectify. In any case, configuring which headers are captured is an entirely different problem than how to represent them in OTLP. I still stand by my case that the `-` to `_` conversion is confusing within this header spec. Lowercasing seems fine and an obvious enough way to comply with case insensitivity.

2022-04-05 18:21 UTC, svrnm commented
> Discussed this briefly on the spec call today and I think the consensus was that instrumentation-specific configuration doesn't belong in the SDK spec. The greater takeaway was the need for a consistent configuration specification and mechanism to ensure we can provide these configurations and others to all instrumentations in a consistent manner and document them appropriately. I can't remember who exactly but I think someone volunteered to get the ball rolling in that area.

Just for our understanding: Does this mean we should close this PR and wait for the configuration specification & mechanism to come? Assuming that this will take some time, what to do with this in the meantime, Java and Python are using it already and if other languages jump on that same topic, it would be good to have used the same variables until the config exists.

2022-04-05 21:34 UTC, tigrannajaryan commented
> Just for our understanding: Does this mean we should close this PR and wait for the configuration specification & mechanism to come? Assuming that this will take some time, what to do with this in the meantime, Java and Python are using it already and if other languages jump on that same topic, it would be good to have used the same variables until the config exists.

I think we need to at least figure out some answers to these general questions so that all instrumentations follow a consistent configuration approach:
- Should instrumentations be configurable via env variables?
- Is the same configuration settable from the code?
- Is naming of instrumentations' env variables dictated by the spec?
- Where in the spec it should live?
- What is the variable naming scheme? Do we choose a particular prefix like this PR suggests?
- How to name variables which are specific for just one instrumentation and are not generic and applicable to many instrumentations like "OTEL_INSTRUMENTATION_HTTP*" is? Should the variable names be prefixed by the instrumentation library name?

This should be ideally opened as a separate issue, discussed and after we come to an agreement on what we want to do generally, we can unblock this PR.

2022-04-06 09:37 UTC, svrnm commented
thanks @tigrannajaryan for the clarification, is #1773 the right issue to continue the conversation or is a new one doing a better job?

2022-04-21 03:43 UTC, closed without merging