Categorize required vs optional HTTP attributes
open-telemetry/opentelemetry-specification pull request #2469
Opened 2022-04-05 00:29 UTC by lmolkova

Fixes #2114

## Changes

Here's a revision of what current instrumentations do (https://github.com/open-telemetry/opentelemetry-specification/issues/2114#issuecomment-1079473468) and discussions on required/optional. 

The TLDR: 
Require HTTP instrumentation to be consistent: 
- define one set of required attributes for server and client, clarify how hostname should be populated
- clarify what required and optional attributes mean
  - required: MUST provide if available
  - optional opt-in: MUST populate by default (if available), MAY allow disabling
  - optional opt-out: MUST NOT populate by default, MAY allow enabling
- categorize all attributes based on it

Proposal:

**Client:  the only set of attributes clients should support is: `http.url`, `net.peer.name`, `net.peer.port`**
1. require `http.url`, `net.peer.name` (use IP if only IP is avaialble), `net.peer.port` (when not default) 
2. Make `net.peer.ip` attribute optional (opt-in)

**Server: the only set of attributes servers should support is: `http.scheme`, `net.host.name`, `net.host.port`, `http.target`, `http.route`**
1. Require `net.host.name`, ask for it's value to be the best available server name with specific priority (server-name, host header, ip address)
2. Require (when available) `http.route` - it's an essential attribute for both server traces and metrics
3. Remove `http.host` - host header should be populated (opt-in) using `http.request.header.host`
4. Remove `http.server_name` - if it's available it's populated in `net.host.name`
5. Make `http.url` optional (opt-in)
6. Make `net.host.ip` attribute optional (opt-in)

Related issues #2028

2022-04-05 15:52 UTC, tigrannajaryan commented
Discussed in spec SIG meeting. Decided that @lmolkova will make it clearer which of these changes are breaking (if any) so that we can understand the impact on existing recipients.

2022-04-05 16:07 UTC, tigrannajaryan commented
It would be also great to categorize the changes into 2 buckets:
- Renaming of an attribute without semantic changes. This is supported by Schema files.
- Any other changes. This is unsupported by Schema files and I would like to understand if changes like this may be common in the future and needs to be supported.

2022-04-06 20:46 UTC, lmolkova commented on specification/trace/semantic_conventions/http.md
> +**Required** attribute: instrumentations MUST provide required attributes when instrumented HTTP framework or client implementation allows to retrieve them with reasonable performance. For example, `
`http.route` is special - it's not always available when server span is started as routing happens later. I can add something like "`http.route` MUST be provided at span creation time if and only if it's available at this time"

2022-04-06 22:38 UTC, lmolkova commented on specification/trace/semantic_conventions/http.md
>  | `net.host.port`    | `8080`                                          |
Here's the delta of changes. **None of these changes are breaking** (except `http.retry_count`, see below).
It requires almost all instrumentations to change, but all consumers, who comply with the current spec fully, should not need to change anything.

I've done analysis of existing instrumentations in Java, .NET, Python, Go and JS (otel or contrib repos) on how they populate attributes to demonstrate inconsistencies and show common patterns https://github.com/open-telemetry/opentelemetry-specification/issues/2114#issuecomment-1079473468. 

There are no attribute renames. Most changes only switch optional attributes to required or remove optional attributes.

## Common attribues:
- `http.url`: 
  - currently common and optional
  - in the PR:
    - clients: required
    - servers: removed 
  - existing instrumentations: 
    - clients: all instrumetnations 
    - servers: most, but usually constructed from components
   
- `http.target`: 
  - currently common and optional
  - in the PR:
    - clients: remove
    - servers: required
  - existing instrumentations:
    - clients: few
    - servers: all
- `http.host`: 
  - currently common and optional
  - in the PR: removed (data now goes to to `net.peer.name` or opt-in header `http.request.header.host`)
  - existing instrumentations: 
    - clients: most
    - server: most, but inconsistently - as URL components (host:port) or `host` header

- `http.scheme`
  - currently common and optional
  - in the PR:
    - clients: removed
    - servers: required
  - existing instrumentations:
    - clients: **a few** set it
    - servers: **most** set it
- `http.flavor`
  - common and optional -> common, optional, opt-out
  - existing instrumentations: most populate it.

`http.request_content_length`, `http.request_content_length_uncompressed`, `http.response_content_length`
  - common and optional -> common, optional, opt-in
  - existing instrumentations:
    - **few** populate them. Uncompressed are only populated by JS, check out all insights here [here](https://github.com/open-telemetry/opentelemetry-specification/issues/2114#issuecomment-1079473468) 
     
- `http.retry_count` moved to client (I belive it was added to common attributes ~ a month ago here https://github.com/open-telemetry/opentelemetry-specification/pull/2078, @denisivan0v, can you please confirm?)

- `net.peer.ip`
 - currently common and optional
  - in the PR:
    - clients: optional (opt-in) - IP is rarely known by HTTP clients 
    - servers: optional (opt-out)
  - existing instrumentations:
    - clients: few, among them Go parses it out of host component (if it happens to be IP)
    - servers: most
- `net.peer.port`:
  - currently common and optional
  - in the PR:
    - clients: required (if not default)
    - servers: optional (opt-in)
 - existing instrumentations:    
    - clients: most
    - servers: some
    
`http.request.header.*`, `http.response.header.*`: nothing changed
  - explicitly categorized as opt-in, current spec already requires explicit configuration to enable

## Client
Sets of attributes (one of them is required):
- currently: 4 sets (url or components)
- in the PR: there is just one - `http.url`, `net.peer.name`, `net.peer.port`, which complies with the previous spec, since it includes url
- existing instrumentations: all populate `http.url`
      
### Attributes
- `net.peer.name` optional -> required
   - existing instrumentations: most
-`net.peer.port`  optional -> required (if not default)
  - existing instrumentations: most

## Server
Sets of attributes (one of them is required):
- currently: 4 sets (url or components)
- in the PR  there is one: `http.scheme`, `net.host.name`, `net.host.port`, `http.target`, which is one of required sets per current spec
- existing instrumentations: 
  - `http.scheme`: most
  - `http.target`: all

### Attributes
- `http.server_name`: optional -> removed
    - when value is available it goes to `net.host.name`
    - existing instrumentations: few
- `http.route`: optional -> required
  - existing instrumentations: most who have it, populate it, but sone fallback to path (which is not right)
- `http.client_ip`: optional -> optional, opt-out
- `net.host.name`: optional -> required
  - it was not clearly specified what goes there, specified it (as best known server name)
  - existing instrumentations: few, it's chosen as the most generic one (among `http.host` and `http.server_name`)
- `net.host.port`: optional -> required
  - existing instrumentations: ~half

2022-04-06 22:42 UTC, lmolkova commented
Here's the delta of changes. **None of these changes are breaking**.
It requires almost all instrumentations to change, but all consumers, who comply with the current spec fully, should not need to change anything.

I've done analysis of existing instrumentations in Java, .NET, Python, Go and JS (otel or contrib repos) on how they populate attributes to demonstrate inconsistencies and show common patterns https://github.com/open-telemetry/opentelemetry-specification/issues/2114#issuecomment-1079473468. 

There are no attribute renames. Most changes only switch optional attributes to required or remove optional attributes.

## Common attribues
- `http.url`: 
  - currently common and optional
  - in the PR:
    - clients: required
    - servers: removed 
  - existing instrumentations: 
    - clients: all instrumetnations 
    - servers: most, but usually constructed from components
- `http.target`: 
  - currently common and optional
  - in the PR:
    - clients: remove
    - servers: required
  - existing instrumentations:
    - clients: few
    - servers: all
- `http.host`: 
  - currently common and optional
  - in the PR: removed (data now goes to to `net.peer.name` or opt-in header `http.request.header.host`)
  - existing instrumentations: 
    - clients: most
    - server: most, but inconsistently - as URL components (host:port) or `host` header
- `http.scheme`
  - currently common and optional
  - in the PR:
    - clients: removed
    - servers: required
  - existing instrumentations:
    - clients: **a few** set it
    - servers: **most** set it
- `http.flavor`
  - common and optional -> common, optional, opt-out
  - existing instrumentations: most populate it.

- `http.request_content_length`, `http.request_content_length_uncompressed`, `http.response_content_length`
  - common and optional -> common, optional, opt-in
  - existing instrumentations:
    - **few** populate them. Uncompressed are only populated by JS, check out all insights here [here](https://github.com/open-telemetry/opentelemetry-specification/issues/2114#issuecomment-1079473468) 
     
- `http.retry_count` moved to client-only. I believe it was added to common attributes by mistake ~ a month ago here https://github.com/open-telemetry/opentelemetry-specification/pull/2078, @denisivan0v, can you please confirm?)).

- `net.peer.ip`
 - currently common and optional
   - in the PR:
     - clients: optional (opt-in) - IP is rarely known by HTTP clients 
     - servers: optional (opt-out)
   - existing instrumentations:
     - clients: few, among them Go parses it out of host component (if it happens to be IP)
     - servers: most
- `net.peer.port`:
  - currently common and optional
  - in the PR:
    - clients: required (if not default)
    - servers: optional (opt-in)
 - existing instrumentations:    
   - clients: most
   - servers: some
    
- `http.request.header.*`, `http.response.header.*`: nothing really changed
  - explicitly categorized as opt-in, current spec already requires explicit configuration to enable

## Client
Sets of attributes (one of them is required):
- currently: 4 sets (url or components)
- in the PR: there is just one - `http.url`, `net.peer.name`, `net.peer.port`, which complies with the previous spec, since it includes url
- existing instrumentations: all populate `http.url`
      
### Attributes
- `net.peer.name` optional -> required
   - existing instrumentations: most
-`net.peer.port`  optional -> required (if not default)
  - existing instrumentations: most

## Server
Sets of attributes (one of them is required):
- currently: 4 sets (url or components)
- in the PR  there is one: `http.scheme`, `net.host.name`, `net.host.port`, `http.target`, which is one of required sets per current spec
- existing instrumentations: 
  - `http.scheme`: most
  - `http.target`: all

### Attributes

- `http.server_name`: optional -> removed
    - when value is available it goes to `net.host.name`
    - existing instrumentations: few
- `http.route`: optional -> required
  - existing instrumentations: most who have it, populate it, but sone fallback to path (which is not right)
- `http.client_ip`: optional -> optional, opt-out
- `net.host.name`: optional -> required
  - it was not clearly specified what goes there, specified it (as best known server name)
  - existing instrumentations: few, it's chosen as the most generic one (among `http.host` and `http.server_name`)
- `net.host.port`: optional -> required
  - existing instrumentations: ~half

2022-04-06 23:12 UTC, lmolkova commented
> Any other changes. This is unsupported by Schema files and I would like to understand if changes like this may be common in the future and needs to be supported.

@tigrannajaryan Can you please share what you think about removals of optional attributes? Backends/exporters should not require those and any instrumentation is free to drop any optional attribute at any moment.

2022-04-06 23:19 UTC, lmolkova commented
@carlosalberto @arminru I have added the delta for each attribute changed in the https://github.com/open-telemetry/opentelemetry-specification/pull/2469#issuecomment-1090885115.

The only change that might be breaking is the removal of optional attributes. I'd really like to explore this option even if we consider it breaking. 
As a last resort, we can keep such attributes as opt-in, but it'd be not ideal to keep redundant information.

2022-04-08 14:15 UTC, tigrannajaryan commented
>Can you please share what you think about removals of optional attributes? Backends/exporters should not require those and any instrumentation is free to drop any optional attribute at any moment.

I think we need to discuss this. There is currently no precise definition of what "Optional" means. You are suggesting that the backends should be ready that the attribute may or may not be present and that the telemetry may include or exclude optional attributes at any time. Alternatively, we could have a stricter definition of what "optional" means, in particular we could say that the developers are free to decide whether to include an optional attribute or no, but once the decision is made they should stick with it and should not change the particular instrumentation (if the instrumentation is considered "Stable").


>http.server_name: renamed
>when value is available it goes to net.host.name

I don't think this is a renaming. Renaming is when the attribute name is changed while preserving its semantics exactly. This is not the case here. `net.host.name` has a different semantic. It can mean the http server name, but it can also be used for other scenarios, where there is no http server at all. `http.server_name` had narrower application than `net.host.name`. We cannot express such changes in schema files. If we mark this as a renaming in schema file then any conversion from the new version to old version will unconditionally rename every `net.host.name` attribute into `http.server_name`, even if the span has nothing to do with http operation, thus breaking the telemetry.

Semantically this change is 2 operations:
- deleting of `http.server_name` attribute.
- adding a new requirement that the server name must be recorded in `net.host.name` if the span represents an http operation.

This is a breaking change. How do we handle it? Technically, this should be allowed, since it is a change in an "Experimental" document. How much pain will this cause in practice? I don't know. I would like to hear opinions.

Informally, in the past we said that we are putting a freeze to the semantic conventions and will not be making breaking changes until we have a good backward compatibility story and the [proposal #2180 that addresses it](https://github.com/open-telemetry/opentelemetry-specification/pull/2180) is hopefully very close to being accepted. If https://github.com/open-telemetry/opentelemetry-specification/pull/2180 gets accepted we will have a formal stance on this and can say that all instrumentations are "Unstable" and thus we are explicitly allowed to make changes introduced by https://github.com/open-telemetry/opentelemetry-specification/pull/2469 (this PR).

2022-04-12 15:02 UTC, lmolkova commented
@tigrannajaryan, correct.

2022-04-12 15:31 UTC, tigrannajaryan commented
> @tigrannajaryan, correct.

@lmolkova OK, this is good. I no longer have any objection to this change from the perspective of removal of `http.server_name`.

The only question that remains for me is whether we consider removal of optional attributes a breaking change or no. I can't make the spec SIG meeting today. If you discuss this in the meeting please post a summary here.

2022-04-13 16:49 UTC, lmolkova commented
@tigrannajaryan thank you! we didn't have a proper discussion on optional attribute removal, but I beleive @carlosalberto wanted to chat with a few folks and share his opinion on this (and this change).

2022-04-14 13:38 UTC, carlosalberto commented
Reviewed this document and it all makes sense to me, and I think it's ok to conver it to a non-draft PR. 

> The only question that remains for me is whether we consider removal of optional attributes a breaking change or no

This point brought by @tigrannajaryan is the only important thing I see now, and we should gather more information. Let's mention that in the next maintainers/Spec meeting again, to double verify this is fine (I'm trying to gather information on that myself, etc).

2022-04-14 21:08 UTC, Oberon00 commented on specification/trace/semantic_conventions/http.md
> +> TODO: `net.peer.ip` is not really supported by many HTTP clients and rarely populated by existing instrumentations - do we really need them for clients?
I can say that it is quite useful for Dynatrace, e.g. we use it to heuristically distinguish requests to public vs. internal networks, or to find network-level relationships. Also it is information that can be extremely useful for debugging if you have a hostname that resolves to multiple IPs, and e.g. only one of them has problems.

2022-04-15 14:58 UTC, arminru commented on specification/trace/semantic_conventions/http.md
> -| `http.target` | string | The full request target as passed in a HTTP request line or equivalent. | `/path/12314/?q=ddds#123` | No |
Some clients have a concept of a base/host property + relative target URIs for each request which could be reported separately by instrumentations. See https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.baseaddress for example.

@lmolkova Do you think it would make sense to keep target as optional for clients instead of defining it only for servers? Otherwise clients will always be able to stitch it together to provide the full URL, so I'm not sure if the split attributes would add any value.

2022-04-15 14:58 UTC, arminru commented on specification/trace/semantic_conventions/http.md
> -| `http.retry_count` | int | The ordinal number of request re-sending attempt. | `3` | If and only if a request was retried. |
Thanks for catching this slipping into common!

2022-04-15 14:58 UTC, arminru commented on specification/trace/semantic_conventions/http.md
> +**[2]:** MUST NOT populate `http.route` when it's not supported by HTTP framework as route attribute should have low-cardinality and path can not substitute it.
```suggestion
**[2]:** MUST NOT populate `http.route` when this is not supported by the HTTP server framework as the route attribute should have low-cardinality and the URI path can NOT substitute it.
```

2022-04-15 14:58 UTC, arminru commented on specification/trace/semantic_conventions/http.md
> +- The primary server name of the matched virtual host. This should be obtained via configuration. If no such configuration can be obtained, this attribute MUST NOT be set ( `net.host.name` should be
> | [`net.host.name`](span-general.md) | string | The best known HTTP server name, see note [1] below | `example.com` | Yes |
> (...)
> **[1]:** (...) If no such configuration can be obtained, this attribute MUST NOT be set ( `net.host.name` should be used instead)

This row and footnote **is** already about `net.host.name` or am I getting this wrong?
This would make sense if we were talking about `http.server_name` which would be taken from the Host header or target URL as opposed to `net.host.name` which could be what the server sees by itself when invoking `hostname` but with the restructuring here this is inconsistent.

2022-04-15 14:58 UTC, arminru commented on specification/trace/semantic_conventions/http.md
> +| `http.url` | string | Full HTTP request URL in the form scheme://host[:port]/path?query[#fragment]. Usually the fragment is not transmitted over HTTP, but if it is known, it should be included neve
```suggestion
| `http.url` | string | Full HTTP request URL in the form `scheme://host[:port]/path?query[#fragment]`. Usually the fragment is not transmitted over HTTP, but if it is known, it should be included nevertheless. [1] | `https://www.example.com/search?q=OpenTelemetry#SemConv` | Yes |
```
This domain would be made for documentation purposes as per https://datatracker.ietf.org/doc/html/rfc6761#section-6.5 whereas foo.bar already belongs to someone else who could put some bad content there or break our spec repo URL checker.

2022-04-15 14:58 UTC, arminru commented on specification/trace/semantic_conventions/http.md
> +| `http.url` | string | Full HTTP request URL in the form scheme://host[:port]/path?query[#fragment]. Usually the fragment is not transmitted over HTTP, but if it is known, it should be included neve
```suggestion
| `http.url` | string | Full HTTP request URL in the form `scheme://host[:port]/path?query[#fragment]`. Usually the fragment is not transmitted over HTTP, but if it is known, it should be included nevertheless. [4] | `https://www.example.com/search?q=OpenTelemetry#SemConv` | Opt-in |
```

2022-04-15 14:58 UTC, arminru commented on specification/trace/semantic_conventions/http.md
> +| `http.retry_count` | int | The ordinal number of request re-sending attempt. | `3` | Opt-out. If and only if a request was retried. |
Not really related to your PR but just to figure out if you interpret this the same way or if it would need to be clarified:
The first retry, i.e., the second attempt, is reported with `1`, right?

2022-04-15 14:58 UTC, arminru commented on specification/trace/semantic_conventions/http.md
> +Instrumentation MAY detect it and populate `http.request.header.host` even if user did not explicitly enable it.
```suggestion
Instrumentation MAY detect it and populate `http.request.header.host` even if the user did not explicitly enable this.
```

2022-04-15 14:58 UTC, arminru commented on specification/trace/semantic_conventions/http.md
> +| `http.route` | string | The matched route (path template). See note [2] below | `/users/:userID?` | Yes |
```suggestion
| `http.route` | string | The matched route (path template in the format used by the respective server framework). See note [2] below | `/users/:userID?` | Yes |
```
Could be helpful to make clear that there is no common format for this. We could also add a second example with a different format.

2022-04-15 14:58 UTC, arminru commented on specification/trace/semantic_conventions/http.md
> +**Required** attribute: instrumentations MUST provide required attributes when instrumented HTTP framework or client implementation allows to retrieve them with reasonable performance. For example, `
Can you think of any way to define "reasonable performance" or should we leave it as-is despite being vague?

2022-04-15 16:03 UTC, carlosalberto commented on specification/trace/semantic_conventions/http.md
> +**Required** attribute: instrumentations MUST provide required attributes when instrumented HTTP framework or client implementation allows to retrieve them with reasonable performance. For example, `
My impression is that we should define this on a more general level, as it's _probably_ not as straightforward as we may think. My suggestion is creating an issue for now, and discuss it in the next Spec call ;)

2022-04-19 00:44 UTC, lmolkova commented on specification/trace/semantic_conventions/http.md
> +> TODO: `net.peer.ip` is not really supported by many HTTP clients and rarely populated by existing instrumentations - do we really need them for clients?
I agree it's useful, my only worry was that very few instrumentations populate it and some of HttpClients don't expose it at all. I'll keep it as optional (opt-out) with the clarification that it should be added when available.

2022-04-19 03:32 UTC, lmolkova commented on specification/trace/semantic_conventions/http.md
> -| `http.target` | string | The full request target as passed in a HTTP request line or equivalent. | `/path/12314/?q=ddds#123` | No |
@arminru it boils down to the question if we want to let clients populate url components instead of URL. 

The .NET HttpRequestMessage which instrumentation has access to, only exposes [a full URI](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httprequestmessage.requesturi?view=net-6.0#remarks) when instrumentation reads it, but going though instrumentations, most (but not all) of them get full URL from the request. 
There are a few (5 our of 35 I checked) in Java and JS that create URL out of fragments: 
[1](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/e15dbea4a683f3ec5d2b35900f4e9d14f3693227/instrumentation/vertx/vertx-http-client/vertx-http-client-3.0/javaagent/src/main/java/io/opentelemetry/javaagent/instrumentation/vertx/v3_0/client/Vertx3HttpAttributesGetter.java#L24), [2](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/e15dbea4a683f3ec5d2b35900f4e9d14f3693227/instrumentation/netty/netty-4-common/javaagent/src/main/java/io/opentelemetry/javaagent/instrumentation/netty/common/client/NettyHttpClientAttributesGetter.java#L23), [3](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/e15dbea4a683f3ec5d2b35900f4e9d14f3693227/instrumentation/netty/netty-3.8/javaagent/src/main/java/io/opentelemetry/javaagent/instrumentation/netty/v3_8/client/NettyHttpClientAttributesGetter.java#L23), [4](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/e15dbea4a683f3ec5d2b35900f4e9d14f3693227/instrumentation/apache-httpclient/apache-httpclient-5.0/javaagent/src/main/java/io/opentelemetry/javaagent/instrumentation/apachehttpclient/v5_0/ApacheHttpClientHttpAttributesGetter.java#L34), [5](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/e15dbea4a683f3ec5d2b35900f4e9d14f3693227/instrumentation/apache-httpclient/apache-httpclient-2.0/javaagent/src/main/java/io/opentelemetry/javaagent/instrumentation/apachehttpclient/v2_0/ApacheHttpClientHttpAttributesGetter.java#L30), [6](https://github.com/open-telemetry/opentelemetry-js/blob/7870e9529f1fc293766357f55f303f889e4154c1/experimental/packages/opentelemetry-instrumentation-http/src/utils.ts#L65). All of them also create scheme://host:port from components too, i.e. base address would also need to be formatted.

If we keep `http.target` for HTTP clients, would we allow to populate it instead of full URL along with other components? I suggest we don't - something in the pipeline will need to normalize this data and that's what I'm trying to avoid with this PR. Populating both url and target would introduce redundancy

So if we agree that consistent data is the right goal, then I don't see a benefit in keeping target.

2022-04-19 04:10 UTC, lmolkova commented on specification/trace/semantic_conventions/http.md
> +- The primary server name of the matched virtual host. This should be obtained via configuration. If no such configuration can be obtained, this attribute MUST NOT be set ( `net.host.name` should be
@arminru it is all about `net.host.name`. Here's the motivation: 
 
In current spec we have 3 attributes identifying server name:
- `http.server_name` - primary server name of the matched virtual host
- `http.host` - host header
- `net.host.name` - a bit vague host name (this is what we have in [span-general](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/span-general.md): "`net.host.name` should be the host name of the local host, preferably the one that the peer used to connect for the current operation.
If that is not known, a public hostname should be preferred over a private one. However, in that case it may be redundant with information already contained in resources and may be left out.")

Thinking about consumers of this data - they want to know the most accurate value and exporters/backends would have to normalize and prioritize - I want instrumentation to do this work as they have the most knowledge, there are also N consumers for every single instrumentation.

So I decided to use the least specific attribute - `net.host.name` as this best available host name, very few instrumentations (Go and JS) populate it, so it's also the least breaking to change it slightly.

Then thinking if should still populate other host attributes:
- `http.server_name` - if it's available, it'd already be on the `net.host.name` and would be redundant if we populate it again
- `http.host` - assuming server_name is available and host header does not match it, those rare apps who want it can opt in into `request.http.header.host`. If server_name is not available, it matches `net.host.name` and is redundant.

So I don't see a benefit in keeping those, let me know if I'm missing something here.

2022-04-19 04:24 UTC, lmolkova commented on specification/trace/semantic_conventions/http.md
> +**Required** attribute: instrumentations MUST provide required attributes when instrumented HTTP framework or client implementation allows to retrieve them with reasonable performance. For example, `
> Can you think of any way to define "reasonable performance" or should we leave it as-is despite being vague?

One way I can think about is when library/client/framework calculates the value of such attribute regardless of presence instrumentation. E.g. route is calculated anyway and should never be done in the instrumentation in low-level HTTP servers. It gets very tricky very soon - many attributes require at least a string allocation (e.g. URL.toString), and usually, it's the necessary evil.

I can elaborate on this in the spec, but let's discuss it first.

2022-04-19 05:10 UTC, lmolkova commented on specification/trace/semantic_conventions/http.md
> +| `http.retry_count` | int | The ordinal number of request re-sending attempt. | `3` | Opt-out. If and only if a request was retried. |
Yes, I believe you're right (examples make it super-clear). I updated the description.

2022-04-19 10:44 UTC, Oberon00 commented on specification/trace/semantic_conventions/http.md
> -| `http.target` | string | The full request target as passed in a HTTP request line or equivalent. | `/path/12314/?q=ddds#123` | No |
> something in the pipeline will need to normalize this data and that's what I'm trying to avoid with this PR

I think that's not something we can avoid completely in the end. The question is if we should try to go into that direction, and how much effort we are willing to spend on it.

2022-04-19 10:45 UTC, Oberon00 commented on specification/trace/semantic_conventions/http.md
> +- The primary server name of the matched virtual host. This should be obtained via configuration. If no such configuration can be obtained, this attribute MUST NOT be set ( `net.host.name` should be
> Thinking about consumers of this data - they want to know the most accurate value

What does "accurate" mean here? There may be different questions that can be answered with different values, especially when (reverse) proxies are involved.

2022-04-19 14:35 UTC, tigrannajaryan commented
> Reviewed this document and it all makes sense to me, and I think it's ok to conver it to a non-draft PR.
> 
> > The only question that remains for me is whether we consider removal of optional attributes a breaking change or no
> 
> This point brought by @tigrannajaryan is the only important thing I see now, and we should gather more information. Let's mention that in the next maintainers/Spec meeting again, to double verify this is fine (I'm trying to gather information on that myself, etc).

I posted some comments above, which upon re-reading don't seem to be very clear. Let me try to clarify my position a bit better.

First, let me start by stating that making a change to a producer of telemetry should be considered separately from making a change to semantic conventions. The spec distinguishes these two and discusses these topics separately (see [semantic convention stability](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/versioning-and-stability.md#semantic-conventions-stability) vs [stability of telemetry producers](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/telemetry-stability.md)). So, with that in mind, here is what I think:
 
1. Removal of attributes from semantic conventions in the specification is a breaking change, even if the attribute is optional. The existing wording [here](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/versioning-and-stability.md#semantic-conventions-stability) is unambiguous about this. Removals of attributes are a breaking changes from semantic convention perspective.
1. This particular document (Semantic conventions for HTTP spans) is marked as "Experimental", so I do not see any formal reasons to prohibit this change. Even though it is a breaking change of semantic conventions, we are allowed to make it.
1. Changing existing telemetry producers to produce `http.scheme`, `net.host.name`, `net.host.port`, `http.target` and stop producing `http.server_name` is not a breaking change because it was already allowed in the past. Recipients of telemetry should be ready for this.
 
Given the above, I think the decision we need to make is to decide on how big we think the pain caused by this change to existing recipients can be and whether we are OK with causing it. One argument in favour of allowing it is that after the change the telemetry recipients will receive telemetry that is still valid even according to old semantic conventions, so perhaps the pains are not very big.

2022-04-19 20:47 UTC, lmolkova commented on specification/trace/semantic_conventions/http.md
> +- The primary server name of the matched virtual host. This should be obtained via configuration. If no such configuration can be obtained, this attribute MUST NOT be set ( `net.host.name` should be
@Oberon00 good question. Accurate - the host name that most precisely describes the hostname that responded to the request. 

- if the client called the app through the reverse proxy, client spans may have `https://host1:port1/path1` url which was rewritten to `http://host2:port2/target2`, the server instrumentation should (to its best knowledge) report `host2` and `port2`, etc. Host header may match `host1` or `host2` depending on proxy (mis)configuration.
- if there are multiple virtual hosts/apps on host:port, this should be the name of the virtual server processing the request. This also usually means different targets, but the target is a high-cardinality field and we'd probably want to give users metrics/queries per virtual host.
  - multiple applications probably fall into the same category (but we don't have them spec-ed out yet)


Regarding different questions: this approach helps normalize and consume data, slightly limiting the ability to debug infra configuration.  Assuming we keep `http.server_name` and/or `http.host` we also preserve current ability to debug configuration. 

Still, this ability is very limited but would mean duplication (or triplication) of host data for everyone. We can also ask instrumentations to populate them conditionally when they don't match the prioritized `net.host.name` so we don't introduce redundancy. Thoughts?

2022-04-19 20:54 UTC, lmolkova commented on specification/trace/semantic_conventions/http.md
> +- The primary server name of the matched virtual host. This should be obtained via configuration. If no such configuration can be obtained, this attribute MUST NOT be set ( `net.host.name` should be
The argument to remove them: if we're not sure if/how an attribute helps, we should not have it in the v1, there is always an opportunity to add it later, but removal is de-facto impossible.

2022-04-20 01:01 UTC, lmolkova commented
Discussed open questions during today's Spec meeting: 
- performance of required attributes: need clarification in the general spec, agreed that expensive calculations are not fine, string formatting is reasonable
- need to dig into the history of attributes being removed or turned into opt-in. The investigation is below:

Most of the attributes in question were added in https://github.com/open-telemetry/opentelemetry-specification/pull/263 by @Oberon00 (thanks @arminru for the pointer!). These attributes haven't changed much since #263. There was no discussion on multiple attribute sets at this time. My understanding was that they were added as an alternative to `http.url` when it's not readily available (on servers). 

@Oberon00 would love to hear your opinion or any context on what can break if we follow current proposal (url for clients, one of the set with fragments for servers).

More details:
  - `http.url`: added in #263, prefferable attribute for clients  
  - `http.target`: added in #263, prefferable for servers  
  - `http.host`: added in #263, 
  - `http.scheme`: added in #263, prefferable for servers
  - `http.server_name`: added in #263, prefferable for servers
  - `http.*_content_length*`: (optional -> opt-in) added in #641, continuing the discussion in https://github.com/open-telemetry/opentelemetry-specification/issues/2028#issuecomment-1103316128

2022-04-26 04:15 UTC, lmolkova commented on semantic_conventions/trace/http.yaml
> +          - Host header
yaml requires multiple extra lines to populate proper markdown

2022-04-27 19:25 UTC, Oberon00 commented on semantic_conventions/trace/http.yaml
> +          - Host header
No, you can instead use a `|` as prefix. The `>` prefix converts all newlines to spaces, except doubled ones. Example: https://github.com/open-telemetry/opentelemetry-specification/blob/main/semantic_conventions/resource/faas.yaml#L23-L37

(and yes, this is plain YAML, not some extension by the tool)

2022-04-28 17:30 UTC, lmolkova commented on specification/trace/semantic_conventions/http.md
> +**Required** attribute: instrumentations MUST provide required attributes when instrumented HTTP framework or client implementation allows to retrieve them with reasonable performance. For example, `
I added a new file to the spec in this PR which talks about levels and mentions performance, LMK what you think [attribute-requirement-level](https://github.com/open-telemetry/opentelemetry-specification/blob/454f77b8b5e8b36e7335ae0bd3c7216aa59b0886/specification/common/attribute-requirement-level.md#performance-considerations)

2022-04-28 22:38 UTC, lmolkova commented on specification/trace/semantic_conventions/http.md
> -| `http.target` | string | The full request target as passed in a HTTP request line or equivalent. | `/path/12314/?q=ddds#123` | No |
>  The question is if we should try to go into that direction, and how much effort we are willing to spend on it.

checked what OTLP exporters do (I have no visibility into what happens on the backends), but 3 exporters that happen to leverage URI components have the following logic:

 - AWS XRay - converts components to URL. https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/174f4388a25c874329df00d471ccce586452d069/exporter/awsxrayexporter/internal/translator/http.go#L207-L232

- AzMon -  converts components to URL. https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/174f4388a25c874329df00d471ccce586452d069/exporter/azuremonitorexporter/trace_to_envelope.go#L263-L289

- Elasic - uses components and breaks down `http.target` even further. https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/174f4388a25c874329df00d471ccce586452d069/exporter/elasticexporter/internal/translator/elastic/traces.go#L457-L492


There are two things that happen in each of those:
1. supporting all possible sets of attributes 
2. translating them into vendor schema

We can't change the latter much, but I'm trying to remove the need for the former.

2022-04-29 00:26 UTC, lmolkova commented
@Oberon00 thank you for the feedback! Can you please share your opinion on limiting supported attribute sets? Do you remember if there are any requirements that made us introduce multiple sets in #263 and if anything (you're aware of) depend on it?

2022-05-03 15:15 UTC, jsuereth approved these changes

2022-05-03 15:17 UTC, jsuereth commented
I'm approving the general direction of consolidating on attributes.  However, as Tigran Suggests, *breaking* existing instrumentation would be bad.   We should attempt to reword some of this in a way that existing instrumentation using some of the expanding attributes isn't "broken".   Right now, I believe they would be.

2022-05-03 15:24 UTC, bogdandrutu commented on specification/common/attribute-requirement-level.md
> +# Attribute Requirement Level
@tigrannajaryan this is the file you want to be split correct?

2022-05-03 15:34 UTC, reyang commented on specification/common/attribute-requirement-level.md
> +- **Required**. All instrumentations MUST populate the attribute. Semantic convention defining required attribute expects that all instrumentation libraries and applications are able to efficiently r
For metrics, we need to at least provide a way for folks to avoid/opt-out high-cardinality attributes.

2022-05-03 15:37 UTC, reyang commented on semantic_conventions/trace/http.yaml
> +        required: always
As I've commented [here](https://github.com/open-telemetry/opentelemetry-specification/pull/2469/files#r863909438), metrics could have different expectations:

1. metrics might want to avoid `url` due to the high cardinality nature
2. metrics might want to use fine granularity parts/components of the URI (e.g. route, host).

2022-05-03 15:41 UTC, reyang commented on specification/trace/semantic_conventions/http.md
> +| `net.host.name`    | `"example.com"`                                 |
`host name` here might be an HTTP semantic instead of generic network semantic (at network layer there is actually no `host name` because it is resolved during DNS lookup):

```text
GET /someresource.html HTTP/1.1
Host: www.example.com
```

2022-05-03 15:43 UTC, reyang commented on specification/trace/semantic_conventions/http.md
> +| `http.target` | string | The full request target as passed in a HTTP request line or equivalent. | `/path/12314/?q=ddds#123` | Yes |
Fragment (e.g. `#123`) is not part of the HTTP request, consider calling it out explicitly.

2022-05-03 18:23 UTC, lmolkova commented on specification/common/attribute-requirement-level.md
> +- **Required**. All instrumentations MUST populate the attribute. Semantic convention defining required attribute expects that all instrumentation libraries and applications are able to efficiently r
metrics and trace conventions are different, it's up to every convention to define the attributes and levels. I'm adding some clarification to the document on this.

2022-05-03 18:24 UTC, lmolkova commented on semantic_conventions/trace/http.yaml
> +        required: always
This is trace HTTP convention, so I believe there is no issue here. It's a good point that I should update both metrics and trace conventions

2022-05-03 18:29 UTC, lmolkova commented on specification/trace/semantic_conventions/http.md
> +| `net.host.name`    | `"example.com"`                                 |
The point I'm making in the comment above (https://github.com/open-telemetry/opentelemetry-specification/pull/2469#discussion_r852576400 ) that we need a way to give telemetry consumers the best possible host value as the instrumentation has the most knowledge about it. Host header (if the user wants it) can be optionally populated by explicitly configuring it. 

Also, the static hostname probably should live on resources and not on spans, so I'm trying to leverage the existing vaguely defined `net.host.name` without introducing more attributes and inconsistencies on instrumentation.

2022-05-05 00:08 UTC, lmolkova commented
> I'm approving the general direction of consolidating on attributes. However, as Tigran Suggests, _breaking_ existing instrumentation would be bad. We should attempt to reword some of this in a way that existing instrumentation using some of the expanding attributes isn't "broken". Right now, I believe they would be.

@jsuereth thank you! Can you please clarify the broken" part?

This change is still a valid subset of the current specification, i.e. from the consumer perspective, nothing breaks.
From the instrumentation side, they eventually would need to adopt a new schema version with this change. Then they would need to remove extra attributes and populate ones they don't.
I've tried to minimize the change though by cataloging what current instrumentations do https://github.com/open-telemetry/opentelemetry-specification/issues/2114#issuecomment-1079473468.

So, instrumentations would need to change, but it would not be a breaking change.

2022-05-06 21:40 UTC, lmolkova commented on semantic_conventions/trace/http.yaml
> +        required: always
updated metrics convention doc to reflect changes there

2022-05-13 20:57 UTC, reyang commented on specification/trace/semantic_conventions/http.md
> -| `http.target` | string | The full request target as passed in a HTTP request line or equivalent. | `/path/12314/?q=ddds#123` | No |
> > something in the pipeline will need to normalize this data and that's what I'm trying to avoid with this PR
> 
> I think that's not something we can avoid completely in the end. The question is if we should try to go into that direction, and how much effort we are willing to spend on it.

+1 my observation is that the industry started with unstructured data:

_The string is a stark data structure and everywhere it is passed there is much duplication of process. It is a perfect vehicle for hiding information._

-- Alan J. Perlis

And as the system become more complex, the demand of having structured data keeps increasing.
URIs are well formatted, which makes it trickier. And given semantic conventions are very subjective, I personally would prefer to learn from things that is well established/recognized, and take the lesson from their learnings and feedback from others. In this case, I think ECS sets a good example https://www.elastic.co/guide/en/ecs/current/ecs-url.html and it does allow components.

2022-05-13 22:40 UTC, lmolkova commented on specification/trace/semantic_conventions/http.md
> -| `http.target` | string | The full request target as passed in a HTTP request line or equivalent. | `/path/12314/?q=ddds#123` | No |
Assuming we have 100+ HTTP instrumentations from different owners, we need a way to achieve consistency between them. As my investigation showed, even OTel-owned instrumentations are not consistent.

If we allow multiple options, it'll hurt. I.e. if I'm a user and I want to measure latency of my microservices and group them by hostname, how would I write the query if some HTTP instrumentations report `url` and others `host`? 

If we focus on down-to-earth problems like this, we'll need consistency in the spec. Whether it means having pure `url`, components, or both, there should be exactly one set of required attributes.

2022-05-23 23:48 UTC, jmacd approved these changes

2022-05-24 14:02 UTC, Oberon00 requested changes
I'm against using net.* which is currently defined to be for socket-level attributes for application-level purposes. If we really want to do this, we would need to change the definition of the net.* conventions to be much more vague, and we'd lose the possibility to report both (which could be useful for debugging issues with (reverse) proxies).

2022-05-26 19:00 UTC, lmolkova commented on semantic_conventions/trace/http.yaml
> +        required: always
The reason to have them here is to support metrics-over-traces (https://github.com/open-telemetry/opentelemetry-specification/issues/2114#issuecomment-1079500714). Java already does it in instrumentation API abstrations. 

I.e. simplify any instrumentations and pipelines not require them to parse URL on the hot path.

I feel it's an  important scenario, but open to relax requirement level to be recommended with future possibility to make it stronger once we have more clarity on metrics over traces.

2022-05-26 19:01 UTC, lmolkova commented on semantic_conventions/trace/http.yaml
> +          conditional: if not default (`80` for `http` scheme, `443` for `https`).
same reason as `net.peer.name` - metrics over traces.

2022-05-26 19:18 UTC, lmolkova commented on semantic_conventions/trace/http.yaml
> +        required: always
I'm open to separate application and socket-level attributes, but I don't believe `net.peer` or `net.host` attributes are currently defined as socket-level

Here's what [we have on them](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/span-general.md):

>
-  General network connection attributes: These attributes may be used for any network related operation.
The `net.peer.*` attributes describe properties of the remote end of the network connection
(usually the transport-layer peer, e.g. the node to which a TCP connection was established),
while the `net.host.*` properties describe the local end.
In an ideal situation, not accounting for proxies, multiple IP addresses or host names,
the `net.peer.*` properties of a client are equal to the `net.host.*` properties of the server and vice versa
- `net.peer.name` Remote hostname or similar, see note below. [1] ([1]: net.peer.name SHOULD NOT be set if capturing it would require an extra DNS lookup.)
- `net.host.name` - Local hostname or similar, see note below.
- `net.*.name` attributes: For IP-based communication, the name should be a DNS host name.
For `net.peer.name`, this should be the name that was used to look up the IP address that was connected to
(i.e., matching `net.peer.ip` if that one is set; e.g., `"example.com"` if connecting to an URL `https://example.com/foo`).
If only the IP address but no host name is available, reverse DNS lookup SHOULD NOT be used to obtain `net.peer.name`,
and `net.peer.name` SHOULD NOT be set. `net.host.name` should be the host name of the local host, preferably the one that the peer used to connect for the current operation.
If that is not known, a public hostname should be preferred over a private one. However, in that case it may be redundant with information already contained in resources and may be left out.
It will usually not make sense to use reverse-lookup to obtain `net.host.name`, as that would result in static information that is better stored as resource information.


According to these definitions, `net.peer.name` on the client-side is exactly the host part of http URL, `net.host.name` is just an abstract hostname with the suggestion to keep a static one in the resource.

So I see several ways :
1. general conventions need clarification that `net.*` are socket attributes and not to be used for anything else. Then HTTP might need to define HTTP-specific (not application) ones where there is a contradiction. In practice, it means that every convention will have to redefine those too. 
2. we keep general attributes vague enough to let other conventions reuse them

2022-05-26 19:20 UTC, lmolkova commented
> I'm against using net.* which is currently defined to be for socket-level attributes for application-level purposes. If we really want to do this, we would need to change the definition of the net.* conventions to be much more vague, and we'd lose the possibility to report both (which could be useful for debugging issues with (reverse) proxies).


I'm open to separate application and socket-level attributes, but I don't believe `net.peer` or `net.host` attributes are currently defined as socket-level

Below is what [we have on them](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/span-general.md).

According to it, `net.peer.name` on the client-side is exactly the host part of http URL, `net.host.name` is just an abstract hostname with the suggestion to keep a static one in the resource.

So I see several ways :
1. general conventions need clarification that `net.*` are socket attributes and not to be used for anything else. Then HTTP might need to define HTTP-specific (not application) ones where there is a contradiction. In practice, it means that every convention will have to redefine those too. 
2. we keep general attributes vague enough to let other conventions reuse them 


>
> -  General network connection attributes: These attributes may be used for any network-related operation.
The `net.peer.*` attributes describe properties of the remote end of the network connection
(usually the transport-layer peer, e.g. the node to which a TCP connection was established),
while the `net.host.*` properties describe the local end.
In an ideal situation, not accounting for proxies, multiple IP addresses or host names,
the `net.peer.*` properties of a client are equal to the `net.host.*` properties of the server and vice versa
> - `net.peer.name` Remote hostname or similar, see note below. [1] ([1]: net.peer.name SHOULD NOT be set if capturing it would require an extra DNS lookup.)
> - `net.host.name` - Local hostname or similar, see note below.
> - `net.*.name` attributes: For IP-based communication, the name should be a DNS host name.
For `net.peer.name`, this should be the name that was used to look up the IP address that was connected to
(i.e., matching `net.peer.ip` if that one is set; e.g., `"example.com"` if connecting to an URL `https://example.com/foo`).
If only the IP address but no host name is available, reverse DNS lookup SHOULD NOT be used to obtain `net.peer.name`,
and `net.peer.name` SHOULD NOT be set. `net.host.name` should be the host name of the local host, preferably the one that the peer used to connect for the current operation.
If that is not known, a public hostname should be preferred over a private one. However, in that case it may be redundant with information already contained in resources and may be left out.
It will usually not make sense to use reverse-lookup to obtain `net.host.name`, as that would result in static information that is better stored as resource information.

2022-05-26 19:36 UTC, lmolkova commented on semantic_conventions/trace/http.yaml
> +          Best known HTTP remote hostname is identified according with the following order:
I like the idea of clarifying proxy scenario (when HTTP instrumentation has the knowledge about it). I don't think though we ever documented that `net.peer.name` would be a proxy address. After reading general conventions multiple times, I *think* it's still the final destination DNS name in host header or host component in absolute request uri.

2022-05-26 19:38 UTC, lmolkova commented on semantic_conventions/trace/http.yaml
> -      - id: url
correct! if you believe servers should be able to report url for something, I'm happy to return it for servers, probably as optional attributes. Asking for recommended level on it would introduce redundancy for everyone by default

2022-05-26 19:41 UTC, lmolkova commented on semantic_conventions/trace/http.yaml
> +          - The primary server name of the matched virtual host. This should be obtained via configuration.
I believe you meant `net.host.name` and the definition for it can't be vaguer than it currently is:
 
> `net.host.name` should be the host name of the local host,
preferably the one that the peer used to connect for the current operation.
If that is not known, a public hostname should be preferred over a private one. However, in that case it may be redundant with information already contained in resources and may be left out.
It will usually not make sense to use reverse-lookup to obtain `net.host.name`, as that would result in static information that is better stored as resource information.

2022-05-28 15:01 UTC, Oberon00 commented on semantic_conventions/trace/http.yaml
> +        required: always
> I.e. simplify any instrumentation and pipeline to not require them to parse URL on the hot path

What I'm saying is that net.peer.name is not necessarily the hostname in the URL. That would more conventionally be http.host.
net.peer.name is the next hop you connect to on the TCP/IP level, which is *usually* the hostname from the URL but may also be an HTTP proxy. E.g. see https://en.wikipedia.org/wiki/Proxy_auto-config#Example: Here you would have net.peer.name=proxy.example.com, net.peer.port=8080, regardless of the URL you request.

2022-05-28 15:03 UTC, Oberon00 commented on semantic_conventions/trace/http.yaml
> -      - id: url
I don't know, have you checked what instrumentations currently do? I think in Java, URL is used also on the server side in the basic framework for HTTP server-side instrumentations.

2022-05-28 15:08 UTC, Oberon00 commented on semantic_conventions/trace/http.yaml
> +          Best known HTTP remote hostname is identified according with the following order:
Granted, it only says "usually", but that's how I always thought about them. https://github.com/open-telemetry/opentelemetry-specification/blob/v1.3.0/specification/trace/semantic_conventions/span-general.md#general-network-connection-attributes

>  The net.peer.* attributes describe properties of the remote end of the network connection (usually the transport-layer peer, e.g. the node to which a TCP connection was established

And if you use an HTTP-level proxy, you don't know if you even contact the host under the hostname in the URL, even indirectly through the proxy, e.g. you may get a cached response. See also https://github.com/open-telemetry/opentelemetry-specification/pull/2469#discussion_r884145017

2022-05-28 15:11 UTC, Oberon00 commented on semantic_conventions/trace/http.yaml
> +          - The primary server name of the matched virtual host. This should be obtained via configuration.
With a reverse-proxy in play, the hostname that an indirect remote client used may not be a hostname under which the final server can be reached.

2022-05-28 15:14 UTC, Oberon00 commented
> In practice, it means that every convention will have to redefine those too.

I don't think there are many protocols beside HTTP that have proxy features built-in at the application level. In fact I don't know any. So I think this logical vs. transport-level peer distinction is an HTTP-specific quirk. (Note, if you have a low-level proxy (VPN or whatever), then the transport-layer peer and the logical peer are the same from any application's perspective.)

2022-05-28 15:20 UTC, Oberon00 commented
> general conventions need clarification that net.* are socket attributes and not to be used for anything else.

This was meant to be covered by

> The net.peer.* attributes describe properties of the remote end of the network connection (usually the transport-layer peer, e.g. the node to which a TCP connection was established)

With an HTTP-proxy (not just any proxy used with HTTP!), the remote end of your network connection, even from an application perspective, is the HTTP proxy. This has to be handled specifically by the application, e.g. it must use full URLs as the target in the request line https://en.wikipedia.org/wiki/Proxy_server#Web_proxy_servers

As said, I don't think there are many other protocols beside HTTP where this distinction really becomes important. But if we have more examples where the distinction could be useful, I think introducing an `net.app.*`  that has all the other `net.*`  attributes nested under it (except `net.transport` I guess, which could be net.app.protocol instead https://github.com/open-telemetry/opentelemetry-specification/issues/2548), would make sense.

2022-05-31 15:02 UTC, lmolkova commented on semantic_conventions/trace/http.yaml
> +        required: always
If I understand your proposal correctly, you suggest that net.peer.* would represent proxy for HTTP if request happened to come through proxy and something else to represent the actual peer. 
This is not what's written in the spec today, these attributes are used in database and messaging specs as the final endpoints (to the best knowledge by instrumentation).

Moreover, the previous version of this spec suggested net.*.name as an alternative to `http.host` never mentioning proxy.

2022-05-31 15:07 UTC, lmolkova commented on semantic_conventions/trace/http.yaml
> -      - id: url
I did an expensive research on this https://github.com/open-telemetry/opentelemetry-specification/issues/2114#issuecomment-1079473468. Java does not report URL as it would be required to be constructed from components. I checked what other languages do and most of them need to reconstruct URL from components, introducing inefficiency and redunduncy.

2022-05-31 15:30 UTC, lmolkova commented on semantic_conventions/trace/http.yaml
> +          - The primary server name of the matched virtual host. This should be obtained via configuration.
Instrumentation has 3 sources of host information (I skipped static hostname intentionally)
- virtual host
- host headers
- request uri in a rare case when it's absolute

Depending on the behavior and configuration of reverse proxy, it can overwrite (or not overwrite)  host header and request uri - HTTP server instrumentation has no knowledge of what it did and what was there initially.

In the same way, there is no way for client instrumentation to know what's the final destination when the reverse proxy is involved.
 
So what I do here is try to specify what instrumentation does with the things it has and it still complies well with general net.* attributes.

2022-05-31 15:48 UTC, lmolkova commented
@Oberon00 

> This was meant to be covered by

>> The net.peer.* attributes describe properties of the remote end of the network connection (usually the transport-layer peer, e.g. the node to which a TCP connection was established)

I don't think this is in any way prescriptive about what `net.peer` attributes mean especially when the proxy is involved, proxy case is not covered in the specification at all.

This PR does not intend to cover it. If I introduced it, I'd use different sets of attributes for the proxy as it would allow using common attributes for all specs to signify the same thing.

Current spec uses `net.host.name`, `http.host` and `http.server_name` as alternatives, which is up to instrumetnation to provide. Same on the client side `net.peer.name` and `http.host` are alternatives. DB and messaging spec use `net.peer` attributes as general-purpose peer information without going into socket specifics or having any alternatives to them for the proxy case.

2022-05-31 19:47 UTC, Oberon00 commented
The scenario is not spelled out explicitly, but the current spec leaves only one way to represent it, and I think it's not too bad that way.

There is also this:
> Note that in some cases http.host might be different from the net.peer.name used to look up the net.peer.ip that is actually connected to. In that case it is strongly recommended to set the net.peer.name attribute in addition to http.host.

It would also be consistent with http.client_ip vs net.peer.ip on the server side, where the note for http.client_ip says:

> This is not necessarily the same as net.peer.ip, which would identify the network-level peer, which may be a proxy.

BTW, way back before the semantic convention generator was created, there was actually an order of preference specified for the alternatives: https://github.com/open-telemetry/opentelemetry-specification/blame/bdf39cb935a6f48badc687daeb78a66dc352761f/specification/trace/semantic_conventions/http.md#L99-L104

> One of the following sets of attributes is required (in order of usual preference unless for a particular web client/framework it is known that some other set is preferable for some reason; all strings must be non-empty):
>
> * `http.url`
> * `http.scheme`, `http.host`, `http.target`
> * `http.scheme`, `net.peer.name`, `net.peer.port`, `http.target`
> * `http.scheme`, `net.peer.ip`, `net.peer.port`, `http.target`

(client, different for server).

2022-06-01 00:48 UTC, lmolkova commented
@Oberon00 

> Note that in some cases http.host might be different from the net.peer.name used to look up the net.peer.ip that is actually connected to. In that case it is strongly recommended to set the net.peer.name attribute in addition to http.host.

There are 3 things HTTP instrumentation can possibly  know (not involving DNS lookup):
- host header
- request-target which might be in absolute form
- proxy address - i hope we can agree this should go into a different attribute set to simplify life of all backends and not requiring them to know how each protocol deals with proxy  - they'd rely on one attribute to represent remote endpoint and no complicate branching conditions.

It leaves us with host header and request-target, which in theory could be different. 

Let' see what  HTTP spec says about them:



[Host header](https://datatracker.ietf.org/doc/html/rfc7230#section-5.4)
> When a proxy receives a request with an absolute-form of
   request-target, the proxy MUST ignore the received Host header field
   (if any) and instead replace it with the host information of the
   request-target.  A proxy that forwards such a request MUST generate a
   new Host field-value based on the received request-target rather than
   forward the received Host field-value.

[request-target: absolute-form](https://datatracker.ietf.org/doc/html/rfc7230#section-5.3.2)
>    When making a request to a proxy, other than a CONNECT or server-wide
   OPTIONS request (as detailed below), a client MUST send the target
   URI in absolute-form as the request-target.

- [CONNECT](https://datatracker.ietf.org/doc/html/rfc7231#section-4.3.6) (HTTPS proxy) - it does not require them to be the same, but some proxies do - e.g. https://github.com/haproxy/haproxy/issues/1159
> A client sending a CONNECT request MUST send the authority form of
   request-target ([Section 5.3 of [RFC7230]](https://datatracker.ietf.org/doc/html/rfc7230#section-5.3)); i.e., the request-target
   consists of only the host name and port number of the tunnel
   destination, separated by a colon.  For example,
>     CONNECT server.example.com:80 HTTP/1.1
     Host: server.example.com:80

- Absolute path (no authority) is a MUST for non-proxy requests
>  When making a request directly to an origin server, other than a
   CONNECT or server-wide OPTIONS request (as detailed below), a client
   MUST send only the absolute path and query components of the target
   URI as the request-target. 


So,
- request-target will have absolute form (with authority) only when proxy is involved (for HTTP 1.1) 
- in this case Host header is blindly overwritten by proxy, so I should actually change the priority to get net.peer.name from request-target rather than host header first.

For very custom and badly formatted HTTP requests, where Host header and request-target are not the same we can actually populate `http.request.header.host` conditionally or users may opt-into this - I assume all popular HTTP clients will conform to the spec and this would not be a widespread problem. Registering a specific attribute to address invalid HTTP request case seems like an overkill.

I hope this resolves the conversation about forward proxy and possibilities around `net.peer.name` being different than authority and host.

2022-06-01 05:31 UTC, reyang commented on specification/trace/semantic_conventions/http.md
> +**[3]:** Best known HTTP server name is identified according with the following order:
minor:

```suggestion
**[3]:** Best known HTTP server name is identified according to the following order:
```

2022-06-01 05:32 UTC, reyang commented on specification/trace/semantic_conventions/http.md
>  Note that following the recommendations above, `http.url` is not set in the above example.
Is this still consistent with the change proposed here?

2022-06-01 05:33 UTC, reyang commented on specification/trace/semantic_conventions/http.md
>  Note that following the recommendations above, `http.url` is not set in the above example.
Or this is just HTTP server (not client) so it is fine?

2022-06-01 15:05 UTC, Oberon00 commented
> proxy address - i hope we can agree this should go into a different attribute set to simplify life of all backends and not requiring them to know how each protocol deals with proxy - they'd rely on one attribute to represent remote endpoint

Sorry, but this is exactly the point where we have the disagreement. I'd maintain that net.peer.* describes what the process ends up passing to the socket-API (transport-level, network-level) calls. And in the case of an application-protocol-level proxy, this would be the address of the proxy. The attribute for the "logical" endpoint would be part of http.url (or http.host, but what you cited from the RFC makes me think that this is a bit unclear without explicit wording). The call may not even end up at the HTTP-level target host. So claiming you connected to it on the net.* level would IMHO be wrong.

> net.peer.ip and http.client_ip would always be different when x-forwarded-for is present, so having special semantics makes sense here. But you didn't mention what would be consistent, so please elaborate.

Here it is the same way round: net.peer.* has the address of the transport-level peer that connected to the server which may be a proxy. A special attribute http.client_ip is used for the "logical" client.

My idea always was that you analyze the net.* attributes only if you are interested in network-level issues.

If we want to have a higher level, we'd need to add one (net.app.peer.name? comm.peer.name?). There is peer.service (https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/span-general.md#general-remote-service-attributes) but this one cannot usually be set by instrumentation as it is specified now.

2022-06-03 06:22 UTC, Oberon00 commented
If you have gRPC behind a HTTP proxy, the semantic conventions seem to be indeed lacking, or you would need to add HTTP conventions like http.url additionally. For databases behind proxies, what kind of proxies are we talking about? If you connect to the DB via a specific TCP-based protocol, you will most likely _only_ know the hostname of the proxy, not of the DB host behind it. So really, you can only set the name of the proxy.

> net.peer.name, this should be the name that was used to look up the IP address that was connected to (i.e., matching net.peer.ip if that one is set; e.g., "example.com" if connecting to an URL example.com/foo).

If your HTTP client is configured to use an HTTP proxy you won't connect to example.com, i.e. your net.peer.ip won't be one of example.com, but of your HTTP-level proxy.

2022-06-03 06:37 UTC, Oberon00 commented
>  In this PR I'm not changing the semantics of net.peer.name or net.host.name, so your concern is not in the scope of this PR.

Clearly we have different ideas of the meaning of net.peer.name. Maybe the current definition of it is unclear. But with this PR you would certainly make it unusable for low-level network information, making its meaning clear as the logical peer. This is a change as well.

2022-06-03 16:23 UTC, lmolkova commented
@Oberon00 I believe the definition of `net.peer.name` is pretty clear and does not mean proxy. The current version of HTTP spec uses `net.peer.name` and `http.host` as alternatives, it's pretty clear they are replaceable. so this PR does **not** change the status quo regarding the meaning of this attribute.

If I did proxy, I would do it differently than putting proxy info into the most general attribute. So now we have different ideas on how to do proxy. But they are ideas and not the spec. I encourage you to implement yours, introduce a new attribute in addition to `net.peer.name` and update specs to it. Introducing this attribute now would mean a huge expansion of this PR.

Regarding DB proxy, some databases work over http, socks5 proxy allows you to tunnel, [mongo supports is](https://github.com/mongodb/specifications/blob/master/source/socks5-support/socks5.rst). 
One point I'd like to make is that proxy conversation needs a lot of clarification and cross-tech investigations before it can come into the spec. this is another reason not to put anything about it into the spec until it's done.

2022-06-03 16:40 UTC, lmolkova commented
As another proof this PR does not change the status quo, I've done a  brief investigation on what Java, ,NET , Python, JS and Golang HTTP Client instrumentations do with regards to proxy address and none of them ever does anything about proxy address on the client. So all OTel instrumentations owners also believe that `net.peer.name` is the final remote destination. 

Proxy only appears in context of `X-Forwarded-For` and `http/client_ip`.

2022-06-04 09:03 UTC, Oberon00 commented
> uses net.peer.name and http.host as alternatives, it's pretty clear they are replaceable.

Because you *usually* do not use a proxy, and the requirements should be minimal. Maybe it was a mistake to allow net.peer.* as replacements and a logical peer should always have been required. And the alternatives are not claimed to be equivalent anyway, as [noted above](https://github.com/open-telemetry/opentelemetry-specification/pull/2469#issuecomment-1142576898), the preference order unfortunately got lost in some rewrite of the semantic conventions, but net.* came last, as a fallback so to speak. Why would we even introduce http.host if it were completely equivalent to net.peer.name? It would make no sense at all to have both.
It's similar to http.server_name and http.host on the server side which are also alternatives but have different definitions and may even be both set.

2022-06-07 06:40 UTC, lmolkova commented
> Note that in some cases http.host might be different from the net.peer.name used to look up the net.peer.ip that is actually connected to. In that case it is strongly recommended to set the net.peer.name attribute in addition to http.host.

Http defines request-target and host header. It never talks about DNS. DNS resolution happens way under http instrumentations, which, in general, don't know about IP addresses. Moreover, they don't usually know if host header or request-target has IP address or a host name in it. 
this sentence above suggest they know way more than they can and I suggest that whatever attributes we end up with, we only mention HTTP-specific features defined in the RFC in this spec.

> Why would we even introduce http.host if it were completely equivalent to net.peer.name?

I assume the motivation was to expose nits and bolts to the consumer and expect them to know what all these details mean and let them show it properly. Please correct me if I'm wrong.
Unfortunately, it led to a lot of inconsistencies in instrumentation and them not following current guidance because it's too hard and not explicit enough. (https://github.com/open-telemetry/opentelemetry-specification/issues/2114#issuecomment-1079473468). plus exporters having to normalize data and support all possible variations. So let's fix it while we still can.

I'll try my best to join Tue 8am PDT meeting tomorrow and bring it up, it would be great if you could join too @Oberon00, so we can have a chance to make any progress on this discussion.

2022-06-09 14:12 UTC, Oberon00 commented
> DNS resolution happens way under http instrumentations, which, in general, don't know about IP addresses. Moreover, they don't usually know if host header or request-target has IP address or a host name in it.

This is IMHO mostly independent of the discussion here. It simply means that the implementable set of alternatives shrinks (probably to only http.url if you really only want to gather information as it is passed between application and library's public API). I do want to remind you though that the vision for OTel was that libraries would have instrumentation built-in. A built-in instrumentation in a library could capture this information in almost all cases, because the library has to do DNS resolution somewhere (unless it delegates to a lower-level HTTP library that does not have such built-in instrumentation).

> Http defines request-target and host header. It never talks about DNS.

It does mention DNS. See https://www.rfc-editor.org/rfc/rfc9110.html#name-http-origins

> If the host identifier is provided as an IP address, the origin server is the listener (if any) on the indicated TCP port at that IP address. If host is a registered name, the registered name is an indirect identifier for use with a name resolution service, such as DNS, to find an address for an appropriate origin server.
>
> When an "http" URI is used within a context that calls for access to the indicated resource, a client MAY attempt access by resolving the host identifier to an IP address, establishing a TCP connection to that address on the indicated port, and sending over that connection an HTTP request message containing a request target that matches the client's target URI ([Section 7.1](https://www.rfc-editor.org/rfc/rfc9110.html#target.resource)).

Here is the spec on where an HTTP client should make a request to: https://www.rfc-editor.org/rfc/rfc9110.html#name-routing-inbound-requests

> Once the target URI and its origin are determined, a client decides whether a network request is necessary to accomplish the desired semantics and, if so, where that request is to be directed.
> 
> [7.3.1. ](https://www.rfc-editor.org/rfc/rfc9110.html#section-7.3.1)[To a Cache](https://www.rfc-editor.org/rfc/rfc9110.html#name-to-a-cache)
> ...
> [7.3.2. ](https://www.rfc-editor.org/rfc/rfc9110.html#section-7.3.2)[To a Proxy](https://www.rfc-editor.org/rfc/rfc9110.html#name-to-a-proxy)
> ...
> [7.3.3. ](https://www.rfc-editor.org/rfc/rfc9110.html#section-7.3.3)[To the Origin](https://www.rfc-editor.org/rfc/rfc9110.html#name-to-the-origin)
> ...

This PR now asserts that the only logical peer is what is called "Origin" here. I'm not completely happy with that, but I guess it will work fine for most practical use cases. Note that I think that the PR should use precise wording with references to the RFC though. The proxy could be seen as the logical target on the HTTP level if using one, if I read this section of the RFC correctly.

2022-06-09 14:38 UTC, Oberon00 commented on specification/trace/semantic_conventions/http.md
> +| [`net.peer.port`](span-general.md) | int | Remote port number. | `80`; `8080`; `443` | Recommended |
I think we need to change this now. With the new semantics, of being the "logical peer", it would be the content of the X-Forwarded-Proto header or similar, and the low-level socket port should not be used at all. We will need to introduce a new attribute loke net.sock.peer.port for the low-level port.

2022-06-09 14:38 UTC, Oberon00 commented on specification/trace/semantic_conventions/http.md
> +| `http.client_ip` | string | The IP address of the original client behind all proxies, if known (e.g. from [X-Forwarded-For](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For
Analogous to net.peer.port: I think this must be removed and its meaning assigned to net.peer.ip now, since we want to define net.peer to correspond to the logical peer IP. Especially here it would be important to not fall back to the socket peer IP in any case, to not loose the distinction introduced by the resolution of https://github.com/open-telemetry/opentelemetry-specification/issues/1845

Low-level peer IP will again need a new attribute.

2022-06-29 09:39 UTC, Oberon00 commented
Reopening, I think this is still in the works & waiting for dependencies.

2022-07-01 18:24 UTC, jack-berg approved these changes
I approve this and think that the discussion about `net.peer.*` is useful, but doesn't need to block this pr. My two cents.

2022-07-01 18:39 UTC, trask approved these changes

2022-07-05 11:43 UTC, Oberon00 commented
@jack-berg

> I approve this and think that the discussion about net.peer.* is useful, but doesn't need to block this pr.

If you merge this PR, the resolution of the discussion about net.peer is set into stone. So further discussion would be no longer very useful then.

I see #2614 as a prerequisite for this PR. I would be OK with fast-tracking this HTTP PR here, but at least some indication that the essence of #2614 is fine & approved would be required IMHO (fine-tuning new attributes and wording can be done after this HTTP PR, but the change/clarification in meaning of net.peer.name is a major thing IMHO, that should be separately approved and is used in this PR)

2022-07-13 18:18 UTC, lmolkova commented
@jmacd I'll rebase and clean this one up by the end of the week. I see @Oberon00 removed the request for changes here (thank you!), so I assume we should be good to go after unless anything else comes up.

2022-07-15 02:04 UTC, lmolkova commented on semantic_conventions/trace/http.yaml
> +        required: always
resolved in #2614

2022-07-15 02:20 UTC, lmolkova commented on specification/trace/semantic_conventions/http.md
> +| [`net.peer.port`](span-general.md) | int | Remote port number. | `80`; `8080`; `443` | Recommended |
I removed `net.peer.port` on the server side. Motivation:
- Server instrumentation could only know the port of the socket peer.  
- Original outgoing client port is not forwarded at all:
  - `x-forwarded-proto` represents protocol
  - `x-forwarded-port` represents original port client used to connect to, same on `x-forwarded-host`. 
  - `forwarded` header does not have port info.

I.e. we only have `net.sock.peer.port`.

2022-07-15 02:23 UTC, lmolkova commented on specification/trace/semantic_conventions/http.md
> +| `http.client_ip` | string | The IP address of the original client behind all proxies, if known (e.g. from [X-Forwarded-For](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For
the guidance [now is](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/span-general.md#connecting-through-intermediary)

> Server semantic conventions SHOULD define additional attribute(s) representing originating peer address for reverse-proxy scenarios when such information is available.

Since `x-forwarded-for` and friends are very HTTP specific, it's nice to have http-specific attribute here and we don't need to rename the attribute..

2022-07-15 02:43 UTC, lmolkova commented
@Oberon00 can you please take another look? Thanks!

2022-07-19 09:43 UTC, Oberon00 reviewed
Here are the my main qualms with this PR:
* It results in some information loss (e.g. configured server name http.server_name may need different handling than the server name in the host header, but the telemetry receiver doesn't know the source anymore.
* It defines different attributes for essentially the same URL-information on the client and server side. On the server side one MUST use the scheme+net.host.name+http.target triplet. On the client side, one MUST use http.url. I believe especially the server-side requirement to separate the URL may be annoying for some instrumentations (@trask?).
* It's a (very) braking change to the probably most widely used semantic conventions.

All in all, I think these new conventions are an improvement in some cases but the old ones were better in others. I don't see any major issues with the PR though (other than maybe the last point above, if you count that). So I'm neither blocking nor explicitly endorsing the PR.

2022-07-19 09:43 UTC, Oberon00 commented on specification/trace/semantic_conventions/http.md
> +| [`net.sock.family`](span-general.md) | string | Protocol [address family](https://man7.org/linux/man-pages/man7/address_families.7.html) which is used for communication. | `inet6`; `bluetooth` | Co
I don't think `bluetooth` is a realistic example here. Maybe just IPv4 and v6? (Only if it's possible to change this here; otherwise it's just a minor nit)

2022-07-19 09:43 UTC, Oberon00 commented on specification/trace/semantic_conventions/http.md
> +**[2]:** If different than `inet` and if any of `net.sock.peer.addr` or `net.sock.host.addr` are set. Consumers of telemetry SHOULD expect to receive IPv6 address in `net.sock.peer.addr` without `net
```suggestion
**[2]:** If different than `inet` and if any of `net.sock.peer.addr` or `net.sock.host.addr` are set. Consumers of telemetry SHOULD accept both IPv4 and IPv6 formats for the address in `net.sock.peer.addr` if `net.sock.family` is not set. This is to support instrumentations that follow previous versions of this document.
```

2022-07-19 09:43 UTC, Oberon00 commented on specification/trace/semantic_conventions/http.md
> +**[3]:** If available and different than `net.peer.name` and if `net.sock.peer.addr` is set.
```suggestion
**[3]:** If available and different from `net.peer.name` and if `net.sock.peer.addr` is set.
```

(etc.)

2022-07-19 09:43 UTC, Oberon00 commented on specification/trace/semantic_conventions/http.md
> +Some HTTP headers - `User-Agent` - is already captured in the `http.user_agent` attributes.
```suggestion
The `User-Agent` header is already captured in the `http.user_agent` attribute.
```

2022-07-19 09:43 UTC, Oberon00 commented on specification/trace/semantic_conventions/http.md
> +  include host identifier.
Does this mean the port should be stripped off? I'm not sure I like that. Also, this note would then need to be added to the Host header as well, I think it's not obvious that it will also contain nonstandard ports.

2022-07-19 21:34 UTC, lmolkova commented on specification/trace/semantic_conventions/http.md
> +  include host identifier.
since we have `net.host.name` and `net.host.port` it's natural to parse authority. It also makes it easy to query by hostname only, e.g. when investigating service-wide issues. Can you please bring up some use-cases where this would be bad?

> Also, this note would then need to be added to the Host header as well, I think it's not obvious that it will also contain nonstandard ports.

Can you please elaborate? I mention that `net.host.name`, `net.host.port` should be extracted from the virtual host config or the `Host` header and set when it's not default - what's missing?

2022-07-19 21:59 UTC, lmolkova commented
> It results in some information loss (e.g. configured server name http.server_name may need different handling than the server name in the host header, but the telemetry receiver doesn't know the source anymore)

instrumentation that supports virtual server name (very few do) can compensate for this loss by adding `http.request.header.host`. It currently comes with MAY, but we can make it stronger if it proves to be needed. This also removes duplication between `http.host` and `http.request.header.host`.

> It requires different attributes for essentially the same URL-information on the client and server side. On the server side one MUST use the scheme+net.host.name+http.target triplet. On the client side, one MUST use http.url. I believe especially the server-side requirement to separate the URL may be annoying for some instrumentations 

Please take a look into what current instrumentations do - https://github.com/open-telemetry/opentelemetry-specification/issues/2114#issuecomment-1079473468 - server instrumentations either do not set URL at all or construct it from the fragments at additional perf cost, client instrumentations on the other side usually only have URL and either don't set components or parse them from URL. Perf and redundancy are two concerns here.  This is common between Java and other instrumentations.

> It's a (very) braking change to the probably most widely used semantic conventions.

Can you please elaborate on what exactly would be (very) breaking here? The new version is a valid subset of current versions, i.e. 
- existing consumers should be ready to receive this telemetry. 
- new consumers that are version-aware and decide to support old versions of conventions would still work for old instrumentations
- Instrumentations that decide to adopt them will work with old and new consumers
- the only thing that breaks is the old instrumentation with the new consumer that does not support the old version. Is this combination worth pursuing in an experimental spec?

2022-07-20 11:19 UTC, Oberon00 commented
For consumers of telemetry, I think this is not breaking, but for producers (instrumentations), it may require adaption.

2022-07-20 11:20 UTC, Oberon00 commented on specification/trace/semantic_conventions/http.md
> +  include host identifier.
"SHOULD only include host identifier." is not written in that way for the host header point below.

Also, I wonder if that should become a MUST.

2022-07-20 15:28 UTC, lmolkova commented
> For consumers of telemetry, I think this is not breaking, but for producers (instrumentations), it may require adaption.

producers are not forced to update and if they populate schema url with version, consumers that support old versions (all that exist today), would still work.
So what'll break are instrumentations that won't update and when used with a consumer that does not support old spec version. It's breaking, but should be expected from an experimental spec.

2022-07-27 17:54 UTC, denisivan0v approved these changes
@lmolkova this is a huge step forward and it helps a lot to clarify and simplify HTTP spec (and make it stable eventually). Many thanks for your hard work!

2022-07-27 18:31 UTC, jmacd commented
Thank you @lmolkova!

2022-07-27 18:31 UTC, merged

2022-07-27 18:32 UTC, lmolkova commented
Thank you all!! 🥳