First draft
open-telemetry/opentelemetry-specification pull request #2515
Opened 2022-04-26 22:15 UTC by ladd

## Changes

- Add configuration semantic conventions for commonly used configuration values.

2022-04-26 22:37 UTC, tigrannajaryan commented
Please describe some use cases to understand if this belong to OpenTelemetry semantic conventions or no. Why one would want to record these as attributes?

2022-04-26 22:51 UTC, ladd commented
> Please describe some use cases to understand if this belong to OpenTelemetry semantic conventions or no. Why one would want to record these as attributes?

Our use case is production troubleshooting for end user applications. Specific types of questions we'd like to be able to answer:

- For a specific trace, does the user have a stale configuration version?
- Does the user's language setting match a supported language in the service?
- For a service computing shipping time, is user's local timezone correctly accounted for?
- In aggregate, what is the distribution of `country`, `language`, `timezone`, `version` values?

2022-04-26 22:56 UTC, yurishkuro reviewed
this looks more like `user.agent.*` attributes, `configuration.` is too broad.

2022-04-26 23:13 UTC, ladd commented
> this looks more like `user.agent.*` attributes, `configuration.` is too broad.

I don't see any existing definition of `user.agent` -- are you proposing I create that?

2022-04-28 03:22 UTC, reyang commented on specification/resource/semantic_conventions/configuration.md
> +| `configuration.language` | string | A BCP 47 language tag [2] | `en-US`; `zh-Hant-CN` | No |
Would you clarify what does this mean?
For example, there could be the operating system level locale setting, and each user session could have its own locale, and a process can have different locale. Even inside a process, a thread can choose to have different locale. https://docs.microsoft.com/windows/win32/api/winnls/nf-winnls-setthreadlocale

2022-04-28 22:24 UTC, ladd commented on specification/resource/semantic_conventions/configuration.md
> +| `configuration.language` | string | A BCP 47 language tag [2] | `en-US`; `zh-Hant-CN` | No |
This is intended to be application-level language setting, which would normally be derived from OS-level language setting.

A few notes of nuance here:

- Language is often separated from Locale (Windows, macOS, iOS, and Android make this distinction, and probably others)
- Language may have multiple options in preference order -- this is intended to reflect the user's "top choice".

2022-04-29 00:51 UTC, reyang commented on specification/resource/semantic_conventions/configuration.md
> +| `configuration.language` | string | A BCP 47 language tag [2] | `en-US`; `zh-Hant-CN` | No |
Thanks @ladd!
I feel this is under specified. E.g. in .NET each thread can have different "culture" which affects which language to be used while formatting an exception https://www.csharpcodi.com/csharp-examples/System.Globalization.CultureInfo.GetCultureInfo(string,%20string)/.

2022-04-29 17:38 UTC, ladd commented
> I think the name is way too generic, and the actual semantic is under specified.

Thanks for the feedback! I'm mostly thinking about this from an end-user application perspective. How would you feel about this being specified in terms of application configuration? `app.configuration.language` or `application.configuration.language` for example? I could create some example mapping from OS default APIs, but there will be some aspects that may be up to the discretion of the implementation.

2022-04-30 03:49 UTC, reyang commented
> How would you feel about this being specified in terms of application configuration?

+1 👍

I think this can be modeled as different schemas (e.g. app.lang, os.lang, etc.) pointing to the same type definition (e.g. what is a `language`).

2022-05-11 16:16 UTC, ladd commented
Reworked this PR into separate `app` and `os` definitions.

2022-05-12 00:45 UTC, scheler requested changes

2022-05-12 00:45 UTC, scheler commented on semantic_conventions/resource/os.yaml
> +        examples: ['America/Los_Angeles', 'UTC', 'GMT-08:00']
Timezone is a changing property of OS and therefore it doesn't fit into a Resource under the current semantics of Resource being immutable.

Same with Languages, as the user can change his preferences. That doesn't mean the source of telemetry, identified by the Resource, has changed.

2022-05-12 00:45 UTC, scheler commented on specification/resource/semantic_conventions/app.md
> +
We tried this before. As Client SIG, we tried asking for `app.name` as the attribute for identify the application name and make `service.name` optional which is currently mandatory. The term service isn't so applicable for client apps. However, the request to make `service.name` optional was turned down and we were suggested to use service.name for naming the client-apps as well. In other words, the `service` namespace is a synonym for app and hence these attributes should be under `service` namespace.  cc: @tedsuo

2022-05-12 12:16 UTC, Oberon00 commented on semantic_conventions/resource/os.yaml
> +        examples: ['America/Los_Angeles', 'UTC', 'GMT-08:00']
This is somewhat fuzzy. The hostname can also change, for example. But if it's uncommon enough for it to change, it may make sense to just use the "initial" value at the time of resource detection.

Timezone, language, do seem tricky though, e.g. servers may handle requests from different users with different settings.

2022-05-12 18:11 UTC, ladd commented on semantic_conventions/resource/os.yaml
> +        examples: ['America/Los_Angeles', 'UTC', 'GMT-08:00']
I'd be happy to define it as being collected at initial time. Different users doesn't seem like a huge issue to me: this is defined as the running OS context. So if you care about distinct users, you would collect telemetry directly from the user's device. Conversely, if you care about server-side settings, you collect there.

2022-05-12 18:12 UTC, ladd commented on specification/resource/semantic_conventions/app.md
> +
I'm OK using `service.version` for this, if that's the existing consensus.

2022-05-27 03:38 UTC, closed without merging