opentelemetry-specification add redis spec
open-telemetry/opentelemetry-specification pull request #2525
Opened 2022-05-05 21:54 UTC by haboy52587

Fixes #

## Changes

Please provide a brief description of the changes here. Update the
`CHANGELOG.md` for non-trivial changes. If `CHANGELOG.md` is updated,
also be sure to update `spec-compliance-matrix.md` if necessary.

Related issues #

Related [oteps](https://github.com/open-telemetry/oteps) #

2022-05-06 04:10 UTC, reyang commented on specification/metrics/semantic_conventions/redis-metrics.md
> +|`redis.uptime`|Asynchronous Counter|seconds|Number of seconds since Redis server start|
@haboy52587 thanks for your contribution.

Please refer to this PR https://github.com/open-telemetry/opentelemetry-specification/pull/2458 where we've decided to focus on "what" do we get from the Instrument, rather than "how". In a nutshell, consider removing "Asynchronous" / "Synchronous".

2022-05-06 04:14 UTC, reyang commented on specification/metrics/semantic_conventions/redis-metrics.md
> +|`redis.slaves.connected`|Asynchronous UpDownCounter||Number of connected replicas| | |
Could this be called `redis.replicas.connected`? (given most oss projects are moving from master branch to main branch, I guess in the long run Redis would be inclined to avoid "slaves")

2022-05-06 04:15 UTC, reyang commented on specification/metrics/semantic_conventions/redis-metrics.md
> +# Semantic conventions for database metrics
```suggestion
# Semantic conventions for Redis metrics
```

2022-05-06 04:16 UTC, reyang approved these changes
The overall direction looks good to me once https://github.com/open-telemetry/opentelemetry-specification/pull/2525/files#r866476318 is addressed.

I'm not Redis expert, it'll be great to get someone who is familiar with Redis (or even better, could we invite folks from the Redis community?). Not necessarily blocking given the status of the doc is Experimental.

2022-05-06 04:17 UTC, reyang commented
@haboy52587 please update the CHANGELOG.

2022-05-06 04:18 UTC, reyang commented
@haboy52587 please clear the CLA.

2022-05-06 14:41 UTC, tigrannajaryan requested changes
@haboy52587  I [commented](https://github.com/open-telemetry/opentelemetry-specification/pull/2521#pullrequestreview-961120472) your previous PR.

Still missing:
- Sign the CLA.
- Write a proper PR description.
- There are already Redis semantic conventions: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/database.md, anything new needs to align with existing.

2022-05-06 15:03 UTC, carlosalberto commented
@tigrannajaryan Actually the existing ones are for traces, and this is for metrics.

Other than that, there are some metric that looks very Redis specific, e.g. `redis.clients.max_output_buffer` or `redis.memory.lua`. Adding this kind would make sense still?

2022-05-06 15:40 UTC, tigrannajaryan commented
> @tigrannajaryan Actually the existing ones are for traces, and this is for metrics.
> 
> Other than that, there are some metric that looks very Redis specific, e.g. `redis.clients.max_output_buffer` or `redis.memory.lua`. Adding this kind would make sense still?

We use `db.redis.` prefix for Redis traces. I think we should do the same for metrics.

2022-05-09 13:31 UTC, carlosalberto commented
>  I think we should do the same for metrics.

Oh, yes, let's definitely go with the same prefix.

2022-05-09 21:02 UTC, reyang commented
> > I think we should do the same for metrics.
> 
> Oh, yes, let's definitely go with the same prefix.

Or maybe we should remove `db.` from Redis semantic convention (why is Redis considered `db`?). https://github.com/open-telemetry/opentelemetry-specification/pull/2485#discussion_r868457772

2022-05-10 14:25 UTC, tigrannajaryan commented
> Or maybe we should remove `db.` from Redis semantic convention (why is Redis considered `db`?). [#2485 (comment)](https://github.com/open-telemetry/opentelemetry-specification/pull/2485#discussion_r868457772)

From https://github.com/redis/redis:
>About
>Redis is an in-memory **database** that persists on disk. The data model is key-value, but many different kind of values >are supported: Strings, Lists, Sets, Sorted Sets, Hashes, Streams, HyperLogLogs, Bitmaps.

Also from https://redis.com/:
>Redis Enterprise is simply the best version of Redis, the most loved **database** in the world.

2022-05-17 21:39 UTC, carlosalberto commented
Closing this one as the author won't be continuing with this - also @codeboten will take on this one.

2022-05-17 21:39 UTC, closed without merging