Add metrics for http request and response size
open-telemetry/opentelemetry-specification pull request #2588
Opened 2022-05-27 20:47 UTC by jack-berg

Resolves #2567.

2022-05-31 18:14 UTC, codeboten commented on specification/metrics/semantic_conventions/http-metrics.md
> +| `http.server.request.size`    | Histogram                                         | Bytes        | `By`                                      | measures the size of HTTP request messages (compressed
Would prefer to remain consistent on capitalizing the units

2022-06-07 17:09 UTC, bertysentry requested changes

2022-06-07 17:09 UTC, bertysentry commented on specification/metrics/semantic_conventions/http-metrics.md
> +| `http.client.request.size`  | Histogram                                         | bytes        | `by`                                      | measures the size of HTTP request messages (compressed)
Unit must be `By` (uppercase B)

2022-06-07 17:09 UTC, bertysentry commented on specification/metrics/semantic_conventions/http-metrics.md
> +| `http.client.response.size` | Histogram                                         | bytes        | `by`                                      | measures the size of HTTP response messages (compressed)
Unit must be `By` (uppercase B)

2022-06-07 17:09 UTC, bertysentry commented on specification/metrics/semantic_conventions/http-metrics.md
> +| `http.client.duration`      | Histogram                                         | milliseconds | `ms`                                      | measures the duration outbound HTTP requests
It's too late, but duration should be expressed in base unit (seconds instead of milliseconds)

2022-06-07 17:09 UTC, bertysentry commented on specification/metrics/semantic_conventions/http-metrics.md
> +| `http.server.request.size`    | Histogram                                         | bytes        | `by`                                      | measures the size of HTTP request messages (compressed
Unit should be `By`

2022-06-07 17:09 UTC, bertysentry commented on specification/metrics/semantic_conventions/http-metrics.md
> +| `http.server.response.size`   | Histogram                                         | bytes        | `by`                                      | measures the size of HTTP response messages (compresse
Unit must be `By`

2022-06-07 18:33 UTC, jack-berg commented on specification/metrics/semantic_conventions/http-metrics.md
> +| `http.client.request.size`  | Histogram                                         | bytes        | `by`                                      | measures the size of HTTP request messages (compressed)
Back and forth - [can't win](https://github.com/open-telemetry/opentelemetry-specification/pull/2588#discussion_r885954559) 😅 

If there's consensus on uppercase, I can update the whole file.

2022-06-07 19:58 UTC, ocelotl commented on specification/metrics/semantic_conventions/http-metrics.md
> +| `http.client.request.size`  | Histogram                                         | bytes        | `by`                                      | measures the size of HTTP request messages (compressed)
[`By`](https://ucum.org/ucum.html) is what UCUM defines. We also use `By` everywhere [else](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/rpc.md#rpc-server). I think [this](https://github.com/open-telemetry/opentelemetry-specification/pull/2588#discussion_r885954559) comment was more about using the right unit (bytes) instead of the wrong one (seconds).

2022-06-08 01:03 UTC, jack-berg commented on specification/metrics/semantic_conventions/http-metrics.md
> +| `http.client.request.size`  | Histogram                                         | bytes        | `by`                                      | measures the size of HTTP request messages (compressed)
Oops sorry linked to the wrong comment. Meant to link to this [one](https://github.com/open-telemetry/opentelemetry-specification/pull/2588#discussion_r885954905).

2022-06-09 19:37 UTC, jack-berg commented on specification/metrics/semantic_conventions/http-metrics.md
> +| `http.client.duration`      | Histogram                                         | milliseconds | `ms`                                      | measures the duration outbound HTTP requests
Not too late since these are still experimental, but that convo is outside the scope of this PR.

2022-06-15 10:58 UTC, ocelotl approved these changes

2022-06-16 19:22 UTC, codeboten approved these changes

2022-06-17 21:33 UTC, trask approved these changes

2022-06-28 13:48 UTC, carlosalberto approved these changes

2022-06-28 13:48 UTC, carlosalberto commented
cc @jmacd

2022-06-28 13:50 UTC, cijothomas approved these changes

2022-06-30 18:37 UTC, merged