[Common] Spec inconsistency with proto definition of Attributes #2581
open-telemetry/opentelemetry-specification pull request #2620
Opened 2022-06-16 21:42 UTC by MSNev

Fixes #
#2581 [Common] Spec inconsistency with proto definition of Attributes

## Changes

- Clarifies the Attribute support as defined by Proto `AnyValue` and clarifies Attribute Collections.
- Clarifies and identifies how nested attributes support (as defined by Proto and some SDK's) should be supported.

Related issues #
#376 Support ~map values and~ nested values for attributes #376

2022-06-28 15:03 UTC, MSNev commented
Not stale

2022-06-28 15:32 UTC, MSNev commented on spec-compliance-matrix.md
> +| `nested` Attribute value                                                                         | x        |     |      | +   |        |      |        |     |      |     |      |       |
On re-reviewing the JS code, this is not technically supported by the typescript type definitions.
 So will remove

2022-06-28 15:46 UTC, Aneurysm9 commented
> Clarifies the Attribute support as defined by Proto AnyValue and clarifies Attribute Collections.
> Clarifies and identifies how nested attributes support (as defined by Proto and some SDK's) should be supported.

To the extent that this would apply to attributes for traces and metrics I think this goes beyond clarification and changes the specification.  To my knowledge there are no trace/metric SDK implementations that allow nested attributes.

2022-07-01 23:55 UTC, MSNev commented
> > Clarifies the Attribute support as defined by Proto AnyValue and clarifies Attribute Collections.
> > Clarifies and identifies `how nested attributes support (as defined by Proto and some SDK's) should be supported.`
> 
> To the extent that this would apply to attributes for traces and metrics I think this goes beyond clarification and changes the specification. To my knowledge there are no trace/metric SDK implementations that allow nested attributes.

If you read the spec changes, I believe that I have not specified that trace/metric implementations have to implement or allow for nested attributes. And even the PR comment from above I am stating how it `should` be supported not that it `must` or `is`

What specific or additional clarification would you suggest?

2022-07-05 11:28 UTC, arminru commented on specification/common/README.md
> +  - It MAY also contain another valid Attribute value resulting in `nested` Attributes
```suggestion
  - **For the [Logs](../logs) signal only:** It MAY also contain another valid Attribute value resulting in `nested` Attributes
```
This would document the status quo and thus resolve the current inconsistency in the spec pointed out in https://github.com/open-telemetry/opentelemetry-specification/issues/2581.
Adding support for nested attributes also for other signals should be proposed and discussed separately. This would be a breaking change as trace and metrics consumers do not have to expect such data as per OTel Traces and Metrics `v1.x`.

2022-07-05 11:28 UTC, arminru commented on specification/common/README.md
> +specific as not all SDKs, exporters or backends support the storing or sending
```suggestion
`nested` Attributes are only supported by the [Logs](../logs) signal.
Only certain protocols, languages, SDKs or Exporters support the storing or sending
```

2022-07-05 11:28 UTC, arminru commented on specification/common/README.md
> +      length limits;
Having a configurable limit like this does not document the current status but would be a new feature and should be proposed in a separate issue and PR.

2022-07-05 11:28 UTC, arminru commented on specification/common/README.md
> +* `AttributeNestedLengthLimit` (Default=10; if supported) - Maximum allowed number of nested attribute value;
Having a configurable limit like this does not document the current status but would be a new feature and should be proposed in a separate issue and PR.

2022-07-05 11:28 UTC, arminru commented on spec-compliance-matrix.md
> +| `nested` Attribute value                                                                         | x        |     |      |     |        |      |        |     |      |     |      |       |
```suggestion
```
see comment above

2022-07-05 11:28 UTC, arminru commented on CHANGELOG.md
> +  ([#376](https://github.com/open-telemetry/opentelemetry-specification/issues/376))
```suggestion
```
see comment above

2022-07-07 20:05 UTC, MSNev commented on spec-compliance-matrix.md
> +| `nested` Attribute value                                                                         | x        |     |      |     |        |      |        |     |      |     |      |       |
Removed from compliance matrix

2022-07-07 20:06 UTC, MSNev commented on specification/common/README.md
> +  - It MAY also contain another valid Attribute value resulting in `nested` Attributes
Reworked to relocate and highlight that this is only support by Logs (and ProtoBuf)

2022-07-07 20:07 UTC, MSNev commented on specification/common/README.md
> +      length limits;
Removed

2022-07-12 15:16 UTC, arminru commented on specification/common/README.md
> +  - It MAY also contain another valid Attribute value resulting in `nested` Attributes
I think it would be better to indicate right here in the list that this only applies to logs as the "See ..." below is easy to overlook. WDYT?

2022-07-12 15:16 UTC, arminru commented on specification/common/README.md
> +name used for the signal.
What's meant by "specific name"? The log attribute name (key)?

2022-07-12 15:16 UTC, arminru commented on specification/common/README.md
> +
I find this table confusing. To me it looks like "For Span and Metrics it is NOT optional and for Logs and ProtoBuf it is undefined whether it is optional".
How about this?
| Signal               | Supported |
|----------------------|-----------|
| Span                 | no        |
| Metrics              | no        |
| Logs                 | yes       |

I don't think it's necessary to mention again in the table that the protobuf AnyValue would support it.

2022-07-12 15:16 UTC, arminru commented on specification/common/README.md
> +While the at the ProtoBuf protocol level the [`AnyValue`](https://github.com/open-telemetry/opentelemetry-proto/blob/main/opentelemetry/proto/common/v1/common.proto#L28-L67)
I hope this does not change again as it's a core message and considered stable but please use a permalink (you can just press `y` on your keyboard to have `main` replaced with the respective commit hash), just in case.

2022-07-22 19:03 UTC, MSNev commented on specification/common/README.md
> +  - It MAY also contain another valid Attribute value resulting in `nested` Attributes
Understanding the concern about it being missed, but I'd still prefer to link out rather than repeat.

I'll move the "see" to the beginning.

2022-07-22 19:11 UTC, MSNev commented on specification/common/README.md
> +name used for the signal.
"beyond the specific name used for the signal" is meant to call out that some signals (Logs) and more specifically Events will define a specific name to allow any Event to support passing user / application (domain) specific structure.

While vendors may also have their own (additional) semantic conventions which define their own domain specific "events"

2022-07-22 19:18 UTC, MSNev commented on specification/common/README.md
> +
Changed to yes/no and removed ProtoBuf

2022-07-25 08:40 UTC, mateuszrzeszutek commented on specification/common/README.md
> +    key-value pair will itself be a key-value pair.
It is unclear to me what impact this has on the API -- since you included this in a general Attribute specification, does that mean that you MAY pass nested attributes to a metric instrument?

Extending the generic Attribute definition has impact on all signals (and I suppose at least some SDKs share Attribute/Attributes classes/modules between signals); if you need to introduce nested attribute support in logs, then how about adding it directly to logs instead? Or introducing a separate "nested attribute collection" just for logs' sake.

2022-07-25 08:40 UTC, mateuszrzeszutek commented on specification/common/README.md
> +| Logs                 | yes       |
This table is kinda confusing, I am not sure what "optional = no" is supposed to mean in the context of spans/metrics.

Consider using the requirement keywords in the table instead

```suggestion
| Area                 | Nested attributes support |
|----------------------|---------------------------|
| Span                 | MUST NOT                  |
| Metrics              | MUST NOT                  |
| Logs                 | MAY                       |
```

2022-07-25 10:39 UTC, arminru commented on specification/common/README.md
> +| Logs                 | yes       |
I agree, to me this currently reads as "For Spans and Metrics it is not optional, i.e., a MUST requirement".

2022-07-25 11:04 UTC, arminru commented on specification/common/README.md
> +name used for the signal.
I'm still confused by the sentence, sorry.
Consumers (processors/exporters/backends) don't provide any attributes, they consume them. Should it say producers (instrumentation/receivers) here?

> some signals (Logs) and more specifically Events will define a specific name to allow any Event to support passing user / application (domain) specific structure.

So that would be the attribute name then, right?

2022-07-26 15:31 UTC, MSNev commented on specification/common/README.md
> +    key-value pair will itself be a key-value pair.
As per the existing released ProtoBuf definition someone CAN already construct and send nested attributes and they WILL be successfully transported. And depending on the receiver / backend this is something that needs to be handled, even if that handling strategy buy converting or dropping the values.

Additional, part of this clarification is driven by the fact that SDK's share Attribute/Attributes classes/modules, so that when the SDK's start implementing the Logs signal they WILL run into this confusion. Which would force them to create a situation where Attributes !== Attributes and therefore they will need to introduce additional mappings which is just additional complexity across the entire API surface rather than defining it as a "possibility" and therefore redirecting the required code changes to "handle" this situation to the relevant signal exported (protocol - i.e.. the point at which the Attributes are converted to the wire format).

So for Span and metrics the strategy would be that is already defined as per
> For protocols that do not natively support non-string values, non-string values SHOULD be represented as JSON-encoded strings. For example, the expression int64(100) will be encoded as 100, float64(1.5) will be encoded as 1.5, and an empty array of any type will be encoded as [].

And for Logs it would be supported

This then removes the need and complexity of having multiple Attribute definition.

2022-07-26 15:38 UTC, MSNev commented on specification/common/README.md
> +name used for the signal.
> they consume them

That is the key point, and also where they should be handled.
When an exporter hits this situation it needs to handle it as it will occur either via Logs / events or some application developer passing in an or constructing their own exported / OTLP exporter (this has already occurred) as it won't be limited to just code produced by the OTel Sdk's.

2022-07-27 17:49 UTC, MSNev commented on specification/common/README.md
> +| Logs                 | yes       |
Will update the "Optional" to "Supported"

2022-08-03 15:39 UTC, Oberon00 commented
Please give this PR a more descriptive title. I think the "inconsistency" issue has been explained. It seems to me this is not solving an inconsistency but proposing a new feature.

2022-08-03 22:28 UTC, MSNev commented
> Please give this PR a more descriptive title. I think the "inconsistency" issue has been explained. It seems to me this is not solving an inconsistency but proposing a new feature.

Renamed.

I don't believe that this PR is identifying any new functionality, it is attempting to properly document what Attribute support is today. 
- The protocol SUPPORTS nesting for Attributes (and has for around 2 years)
- Logs SUPPORTS and requires nested attributes

While Spans and Metrics also use "Attributes" their definition of Attributes does not support nesting (from at the spec level), which if not clarified is going to cause confusion not just at the consumer level (using the API vs Protocol) but also at the implementation level when SDK's start to support the proper definition of the Logs Attributes

2022-08-04 07:14 UTC, Oberon00 commented
> I don't believe that this PR is identifying any new functionality, it is attempting to properly document what Attribute support is today.

Look at any SDK and you will see that this is not a clarification, but an actual new (optional) feature.

2022-08-08 16:05 UTC, MSNev commented
> In practice, you are proposing a new feature. This is not supported today.

That is because none of the SDK's (that I'm aware of) are currently SPEC compliant for LOGS, once they start to correctly implement Attributes for Logs everyone will hit this issue.

2022-08-08 21:49 UTC, Oberon00 commented
What should be "clarified" then, is that Log Attributes are not the general attribute types. You have a clear definition of a general "Attribute" here which does not allow nesting.
You have a clear definition of the "attributes" field on log records at https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/data-model.md#field-attributes, which is of type `map<string, any>`, and you also have a definition of `any` that explicitly allows nesting at https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/data-model.md#type-any

2022-08-16 15:02 UTC, MSNev commented
Not Stale

2022-08-24 17:14 UTC, MSNev commented
This last (forced) push is just to bring the PR up to date and mark as not stale. Forced push was required as git refused to do a normal push.

2022-08-24 17:30 UTC, MSNev commented on specification/common/README.md
> +
Add scopes and resources as not supported

2022-08-24 18:18 UTC, tigrannajaryan commented on specification/common/README.md
> +    and the referenced Attribute MUST not be recursive. i.e. The value of the
@MSNev  What if we say something like this:
"- In addition for LogRecord attributes [Nested Attributes] are supported."

This makes it clear that it only applies to LogRecords and it is clear that it does not change semantics of attributes of any other data types.

2022-08-24 18:18 UTC, tigrannajaryan commented on specification/common/README.md
> +name used for the signal.
Perhaps delete this paragraph. I don't think it helps to achieve what this PR wants to achieve.

2022-08-24 18:18 UTC, tigrannajaryan commented on specification/common/README.md
> +any resulting hierarchy SHOULD be limited and MUST not include recursive references.
I would drop this. If above we say that LogRecords attribute can be nested then it is up to each languages to figure out how to support it.

The specifics of how to convert nested attribute values to non OTLP formats do not belong to this document. They should be in mapping-to-non-otlp.md.

2022-08-24 18:18 UTC, tigrannajaryan commented on specification/common/README.md
> +runtime and storage concerns.
Same here, I don't think the paragraph is necessary.

2022-08-24 18:18 UTC, tigrannajaryan commented on specification/common/README.md
> +it does not infer that `nested` attributes are or MUST be supported.
I suggest to delete this and list all areas explicitly to make sure there is no misreading possible.

2022-08-24 18:18 UTC, tigrannajaryan commented on specification/common/README.md
> +provided by the Attribute Value.
I do not quite understand what this intends to say.

2022-08-29 18:01 UTC, MSNev commented on specification/common/README.md
> +provided by the Attribute Value.
This is attempting to state that Attribute Collections does not mean nested attributes, when I first read this section (because I came from the Protobuf perspective) I "assumed" that a Collection meant nesting. So just attempting to clarify so it's clear so someone elses doesn't make the same assumption.

2022-08-29 19:06 UTC, MSNev commented on specification/common/README.md
> +    key-value pair will itself be a key-value pair.
Reworded a little

2022-08-29 19:07 UTC, MSNev commented on specification/common/README.md
> +    and the referenced Attribute MUST not be recursive. i.e. The value of the
Reworded

2022-08-29 19:07 UTC, MSNev commented on specification/common/README.md
> +any resulting hierarchy SHOULD be limited and MUST not include recursive references.
Moved to mapping-to-non-otlp.md

2022-08-29 19:07 UTC, MSNev commented on specification/common/README.md
> +runtime and storage concerns.
Reworded

2022-08-29 19:08 UTC, MSNev commented on specification/common/README.md
> +it does not infer that `nested` attributes are or MUST be supported.
Removed

2022-08-29 19:24 UTC, MSNev commented on specification/common/README.md
> +provided by the Attribute Value.
Reworded a little as well

2022-10-04 09:45 UTC, Oberon00 requested changes

2022-10-04 09:45 UTC, Oberon00 commented on specification/common/README.md
> +  - When specified via semantic conventions it MAY (see [Nested Attributes](#nested-attributes))
This is not a clarification but allows a new feature.

2022-10-04 14:58 UTC, MSNev commented on specification/common/README.md
> +  - When specified via semantic conventions it MAY (see [Nested Attributes](#nested-attributes))
This line explicitly calls out to see the Nested Attribute support which clarifies that this is NOT automatically supported by this line but must be explicitly defined by the semantic conventions (and is supported by Logs).

2022-10-05 11:01 UTC, Oberon00 commented on specification/common/README.md
> +  - When specified via semantic conventions it MAY (see [Nested Attributes](#nested-attributes))
But it allows semantic conventions to add them, as written now, doesn't it?

2022-10-26 15:32 UTC, MSNev commented
Not stale as this is part of a larger issue like #2888

2022-11-07 17:21 UTC, MSNev commented
> Closed as inactive. Feel free to reopen if this PR is still being worked on.

Don't have the ability (permissions) to re-open...

2022-12-21 03:17 UTC, closed without merging