Make periodic exporting MetricReader env vars stable
open-telemetry/opentelemetry-specification pull request #2658
Opened 2022-07-11 18:08 UTC by pellared

## What

Mark `OTEL_METRIC_EXPORT_INTERVAL`, `OTEL_METRIC_EXPORT_TIMEOUT` environment variables as stable.

## Why

I think this change is representing the current state as all of these env vars are already implemented in OTel PHP, OTel Python, and partially by OTel Java.

See:
- [`OTEL_METRIC_EXPORT_INTERVAL` usage](https://github.com/search?p=1&q=org%3Aopen-telemetry+OTEL_METRIC_EXPORT_INTERVAL&type=Code)
- [`OTEL_METRIC_EXPORT_TIMEOUT` usage](https://github.com/search?p=1&q=org%3Aopen-telemetry+OTEL_METRIC_EXPORT_TIMEOUT&type=Code)

Created because of: https://github.com/open-telemetry/opentelemetry-dotnet/pull/3424

2022-07-11 18:23 UTC, reyang commented on specification/sdk-environment-variables.md
> +**Status**: [Stable](document-status.md)
The `OTEL_METRIC_EXPORT_INTERVAL` and `OTEL_METRIC_EXPORT_TIMEOUT` for Periodic exporting MetricReader might be misleading. For traces, `OTEL_BSP_SCHEDULE_DELAY`, `OTEL_BSP_EXPORT_TIMEOUT` are used for a Batch Span Processor.

In addition, `OTEL_METRIC_EXPORT_INTERVAL` could be misleading if a configured exporter/reader is using pull mode (e.g. Prometheus) - imagine some operator trying to increase the Prometheus scraping frequency and got really puzzled by this environment variable.

2022-07-12 07:13 UTC, pellared commented
PTAL @open-telemetry/java-instrumentation-maintainers @open-telemetry/python-maintainers @open-telemetry/php-approvers @open-telemetry/wg-prometheus

2022-07-13 09:14 UTC, pellared commented on specification/sdk-environment-variables.md
> +**Status**: [Stable](document-status.md)
Do you think the names should be changed or should we just make the description+notes more precise?

2022-07-13 16:41 UTC, reyang commented on specification/sdk-environment-variables.md
> +**Status**: [Stable](document-status.md)
> Do you think the names should be changed or should we just make the description+notes more precise?

I think description/notes.

2022-07-13 16:46 UTC, reyang requested changes
The `OTEL_METRICS_EXEMPLAR_FILTER` is still in very early stage and should remain as Experimental, consider marking the "Metrics SDK Configuration" status as Mixed, and make the "Periodic exporting MetricReader" section Stable.

In addition, consider making an update in https://github.com/open-telemetry/opentelemetry-specification/blob/main/spec-compliance-matrix.md#environment-variables. Doesn't have to be in this PR though.

2022-07-14 09:45 UTC, pellared commented on specification/sdk-environment-variables.md
> +**Status**: [Stable](document-status.md)
@reyang did my best to address it. PTAL

2022-07-14 15:15 UTC, reyang approved these changes

2022-07-15 03:54 UTC, cijothomas approved these changes

2022-07-15 05:47 UTC, merged