Add OTEL_SDK_ENABLED env var to disable opentelemetry SDK.
open-telemetry/opentelemetry-specification pull request #2679
Opened 2022-07-19 14:20 UTC by brunobat

Fixes #2667

## Changes
Add OTEL_SDK_ENABLED environment property
This will allow applications to easily deactivate opentelemetry on deployments where it's not supported or needed.

2022-07-22 13:21 UTC, joaopgrassi commented on CHANGELOG.md
> +- Add the OTEL_SDK_ENABLED environmental variable to the SDK configuration.
```suggestion
- Add the `OTEL_SDK_ENABLED` environment variable to the SDK configuration.
```
Maybe?

2022-07-22 13:22 UTC, joaopgrassi commented on specification/sdk-environment-variables.md
> +| OTEL_SDK_ENABLED         | Activate/deactivate the SDK | true | This deactivates all other properties |
```suggestion
| OTEL_SDK_ENABLED         | Activates/deactivates the SDK | true | This deactivates all other properties |
```

2022-07-22 13:25 UTC, joaopgrassi commented on specification/sdk-environment-variables.md
> +| OTEL_SDK_ENABLED         | Activate/deactivate the SDK | true | This deactivates all other properties |
I think we should also add an entry for this variable in the compliance matrix: https://github.com/open-telemetry/opentelemetry-specification/blob/main/spec-compliance-matrix.md#environment-variables

2022-07-22 14:23 UTC, brunobat commented on specification/sdk-environment-variables.md
> +Setting `OTEL_SDK_ENABLED` to `"false"` will configure Noop SDK implementation providers for Tracing, Metrics and Logs. Propagators will also be a Noop implementation (Equivalent to `OTEL_PROPAGATORS
I has the same thought... But it's quite some text. Will see how it looks like

2022-07-22 14:24 UTC, brunobat commented on specification/sdk-environment-variables.md
> +| OTEL_SDK_ENABLED         | Activate/deactivate the SDK | true | This deactivates all other properties |
will do

2022-07-22 14:58 UTC, jack-berg approved these changes

2022-07-22 14:58 UTC, jack-berg commented on specification/sdk-environment-variables.md
> +| OTEL_SDK_ENABLED         | Activate/deactivate the SDK | true | This deactivates all other properties |
For description, how about `If false, disable the SDK`.

2022-07-25 12:46 UTC, arminru commented on specification/sdk-environment-variables.md
> +| OTEL_SDK_ENABLED         | Activate/deactivate the SDK | true | This deactivates all other properties |
Instead of having an "enable" flag with a default of `true` we could also use `OTEL_SDK_DISABLE(D)` instead which disables it when set, WDYT?

2022-07-25 12:48 UTC, arminru commented on specification/sdk-environment-variables.md
> +| OTEL_SDK_ENABLED         | Activate/deactivate the SDK | true | This deactivates all other properties |
Please describe which possible values are defined.
One can assume that a value `false` disables the SDK and not `0` since the default is `true` but it should be clearly specified nevertheless.

2022-07-25 12:50 UTC, brunobat commented on specification/sdk-environment-variables.md
> +Setting `OTEL_SDK_ENABLED` to `"false"` will configure Noop SDK implementation providers for Tracing, Metrics and Logs. Propagators will also be a Noop implementation (Equivalent to `OTEL_PROPAGATORS
Looks ok

2022-07-25 12:55 UTC, brunobat commented on specification/sdk-environment-variables.md
> +| OTEL_SDK_ENABLED         | Activate/deactivate the SDK | true | This deactivates all other properties |
done

2022-07-25 13:13 UTC, brunobat commented
Did the requested changes @arminru @joaopgrassi .

2022-07-25 14:20 UTC, arminru commented on specification/sdk-environment-variables.md
> +| OTEL_SDK_ENABLED         | Activate/deactivate the SDK | true | If "false", disable the SDK. If "true" will enable the SDK.  <br/>If "false" will configure Noop SDK implementation providers for Tra
Instead of having an "enable" flag with a default of `true` we could also use `OTEL_SDK_DISABLE(D)` instead, which disables it when set. It may feel a bit odd that the lack of the flag called `OTEL_SDK_ENABLED` will actually cause it to be enabled.
WDYT?

2022-07-26 09:59 UTC, brunobat commented on specification/sdk-environment-variables.md
> +| OTEL_SDK_ENABLED         | Activate/deactivate the SDK | true | If "false", disable the SDK. If "true" will enable the SDK.  <br/>If "false" will configure Noop SDK implementation providers for Tra
I actually don't agree because OTEL_SDK_ENABLED has true as default meaning it's naturally optional. No need to set it anywhere. Also having a positive default value is much less confusing. 
Having OTEL_SDK_DISABLE false as default is exactly the same (it's a negation of the above), but more confusing because it has negative semantics.

2022-07-26 11:36 UTC, joaopgrassi commented on specification/sdk-environment-variables.md
> +| OTEL_SDK_ENABLED         | Activate/deactivate the SDK | true | If "false", disable the SDK. If "true" will enable the SDK.  <br/>If "false" will configure Noop SDK implementation providers for Tra
Fair enough. I don't have a strong opinion on which is used.

2022-07-26 11:38 UTC, joaopgrassi submitted a review, later dismissed

2022-07-26 13:12 UTC, mateuszrzeszutek commented on specification/sdk-environment-variables.md
> +| OTEL_SDK_ENABLED         | Activate/deactivate the SDK | true | If "false", disable the SDK. If "true" will enable the SDK.  <br/>If "false" will configure Noop SDK implementation providers for Tra
FWIW the auto-instrumentations agents (I've checked the Java and .NET ones) seem to be using `*_ENABLED` way more often than `*_DISABLED`.

2022-07-26 17:47 UTC, brunobat commented on specification/sdk-environment-variables.md
> +| OTEL_SDK_ENABLED         | Activate/deactivate the SDK | true | If "false", disable the SDK. If "true" will enable the SDK.  <br/>If "false" will configure Noop SDK implementation providers for Tra
mark as solved

2022-07-27 09:28 UTC, brunobat commented
Hi @jmacd, can we move forward with the merge?

2022-07-28 16:13 UTC, Emily-Jiang commented
It seems this PR was blocked from merging as it requires Code Owner to review. Can someone from that group view this and merge this PR? Thanks

2022-07-28 16:49 UTC, tigrannajaryan reviewed
I advise to circulate this PR in the Maintainers meeting on Monday to make sure there are no languages where peculiarities of env variable querying can impact on how the variable's values should be defined. We have had some issues in this area which resulted in the precise behavior specification for Numbers and Enums.

2022-07-28 16:49 UTC, tigrannajaryan commented on specification/sdk-environment-variables.md
> +| OTEL_SDK_ENABLED         | Activate/deactivate the SDK | true | If "false", disable the SDK. If "true" will enable the SDK.  <br/>If "false" will configure Noop SDK implementation providers for Tra
This document defines the behavior of Numeric, Enum and Duration type but not Boolean. I think we need a definition so that this new env variable is clear. For example what happens if a value other than "true" or "false" is used?

2022-07-29 13:05 UTC, brunobat commented on specification/sdk-environment-variables.md
> +| OTEL_SDK_ENABLED         | Activate/deactivate the SDK | true | If "false", disable the SDK. If "true" will enable the SDK.  <br/>If "false" will configure Noop SDK implementation providers for Tra
In java, if it's not explicitly "true", it will be false. We can follow the same approach in here.

2022-07-29 13:15 UTC, brunobat commented on specification/sdk-environment-variables.md
> +| OTEL_SDK_ENABLED         | Activate/deactivate the SDK | true | If "false", disable the SDK. If "true" will enable the SDK.  <br/>If "false" will configure Noop SDK implementation providers for Tra
We can also consider it as an enum with 2 possible values. "true" and "false", meaning if the value is not recognized we follow what we usually do... We throw an error.

2022-08-01 16:06 UTC, arminru commented on specification/sdk-environment-variables.md
> +| OTEL_SDK_ENABLED         | Activate/deactivate the SDK | true | If "false", disable the SDK. If "true" will enable the SDK.  <br/>If "false" will configure Noop SDK implementation providers for Tra
Since disabling the (otherwise readily configured) SDK is rather the exception (at least for my understanding) I think we should have it fall back to "enabled" if in doubt.
I.e., it's enabled unless explicitly set to `OTEL_SDK_ENABLED=false` (or `OTEL_SDK_DISABLED=true`).

2022-08-01 16:20 UTC, MSNev commented on spec-compliance-matrix.md
> +|OTEL_SDK_ENABLED                                  |   |      |   |      |    |      |   |    |   |    |     |
As this is only supported in Java, then all of the other columns should be '-' so that this table represents the current state and we don't end up with issues being raised against languages for "new" unimplemented features.

2022-08-01 16:23 UTC, MSNev commented on spec-compliance-matrix.md
> +|OTEL_SDK_ENABLED                                  |   |      |   |      |    |      |   |    |   |    |     |
Additional, as with the other tables in this matrix, should we consider adding an "Optional" column to the supported environment variables (for completeness). As it sounded like this was potentially a case where (for at least this name) it will never be implemented and therefore should always be considered Optional??

2022-08-02 01:44 UTC, Aneurysm9 commented on specification/sdk-environment-variables.md
> +| OTEL_SDK_ENABLED         | Activate/deactivate the SDK | true | If "false", disable the SDK. If "true" will enable the SDK.  <br/>If "false" will configure Noop SDK implementation providers for Tra
Do we really need this option?  I'm wary of adding yet more environment-based configuration for increasingly niche use cases.

I also think that disabling propagation should not be coupled to this. The propagation system is part of the API and functions in the absence of an SDK.

2022-08-02 09:18 UTC, brunobat commented on spec-compliance-matrix.md
> +|OTEL_SDK_ENABLED                                  |   |      |   |      |    |      |   |    |   |    |     |
It's not set in Java because it currently uses OTEL_EXPERIMENTAL_SDK_ENABLED. Therefore it will need to be updated. I'm ok with the optional. Different languages can opt in if needed.
I can add dashes to the other languages.

2022-08-02 09:26 UTC, brunobat commented on specification/sdk-environment-variables.md
> +| OTEL_SDK_ENABLED         | Activate/deactivate the SDK | true | If "false", disable the SDK. If "true" will enable the SDK.  <br/>If "false" will configure Noop SDK implementation providers for Tra
This is not just about propagation. It disables providers as well. 
In my view other languages might require this. There are some use cases driving this property:
* Make it easier for multi app containers to manage migrations from OpenTracing to OpenTelemetry tracing. 
* Allow deployments on multiple environments that might have or not observability capabilities without the need of repackaging.
* Some app and runtime environment migration use cases might benefit with the property.

2022-08-02 14:18 UTC, carlosalberto commented on CHANGELOG.md
> +- Add the OTEL_SDK_ENABLED environmental variable to the SDK configuration.
This entry must go into a subsection. Maybe the "SDK Configuration" one?

2022-08-02 15:23 UTC, brunobat commented on specification/sdk-environment-variables.md
> +| OTEL_SDK_ENABLED         | Activate/deactivate the SDK | true | If "false", disable the SDK. If "true" will enable the SDK.  <br/>If "false" will configure Noop SDK implementation providers for Tra
That's what's defined. It should be always enabled by default.

2022-08-02 15:24 UTC, brunobat commented on CHANGELOG.md
> +- Add the OTEL_SDK_ENABLED environmental variable to the SDK configuration.
Should't that be moved there after released?

2022-08-02 15:25 UTC, brunobat commented on spec-compliance-matrix.md
> +|OTEL_SDK_ENABLED                                  |   |      |   |      |    |      |   |    |   |    |     |
In the meeting it was mentioned that this table is not part of the spec, just a guidance tool. 
I can add an optional column for clarification, if you guys agree.

2022-08-02 15:27 UTC, brunobat commented on specification/sdk-environment-variables.md
> +| OTEL_SDK_ENABLED         | Activate/deactivate the SDK | true | If "false", disable the SDK. If "true" will enable the SDK.  <br/>If "false" will configure Noop SDK implementation providers for Tra
If we chose boolean, how'd we define a new boolean datatype in the spec?

2022-08-02 22:46 UTC, Aneurysm9 commented on specification/sdk-environment-variables.md
> +| OTEL_SDK_ENABLED         | Activate/deactivate the SDK | true | If "false", disable the SDK. If "true" will enable the SDK.  <br/>If "false" will configure Noop SDK implementation providers for Tra
> This is not just about propagation. It disables providers as well.

Understood.  My point is that the propagation system is not part of the SDK but the API and that disabling the SDK should not disable propagation.  Also, there is already a mechanism for disabling propagation via environment variable (for languages that support `OTEL_PROPAGATORS`).

2022-08-03 08:47 UTC, arminru commented on specification/sdk-environment-variables.md
> +| OTEL_SDK_ENABLED         | Activate/deactivate the SDK | true | If "false", disable the SDK. If "true" will enable the SDK.  <br/>If "false" will configure Noop SDK implementation providers for Tra
I think we could just say:
```suggestion
| OTEL_SDK_ENABLED         | Activate/deactivate the SDK | true | If "false", disable the SDK. This will configure Noop SDK implementation providers for Tracing, Metrics, and Logs. Propagators will also be a Noop implementation (Equivalent to OTEL_PROPAGATORS to "none"). Any other value or absence of the variable will have no effect. |
```

2022-08-03 08:50 UTC, arminru commented on spec-compliance-matrix.md
> +|OTEL_SDK_ENABLED                                  |   |      |   |      |    |      |   |    |   |    |     |
I think with line 266 just above the table it should be clear enough:

> Note: Support for environment variables is optional.

You could consider refining it to:

> Support for environment variables is optional. SDKs can choose to support none, some, or all of them.

2022-08-03 09:02 UTC, joaopgrassi commented on CHANGELOG.md
> +- Add the OTEL_SDK_ENABLED environmental variable to the SDK configuration.
Everything that's under the section `## Unreleased` is moved "out" of it into a final release. For ex, the PR https://github.com/open-telemetry/opentelemetry-specification/pull/2658 was recently merged, into the same section as @carlosalberto proposed.

2022-08-03 10:51 UTC, brunobat commented on specification/sdk-environment-variables.md
> +| OTEL_SDK_ENABLED         | Activate/deactivate the SDK | true | If "false", disable the SDK. If "true" will enable the SDK.  <br/>If "false" will configure Noop SDK implementation providers for Tra
I understand and I don't agree. 
This is a master switch and, if implemented, must have priority over all other configs. I don't think it makes sense to have propagation if you don't want OpenTelemetry on.

2022-08-03 10:53 UTC, brunobat commented on CHANGELOG.md
> +- Add the OTEL_SDK_ENABLED environmental variable to the SDK configuration.
Thanks. Will update.

2022-08-03 10:56 UTC, brunobat commented on specification/sdk-environment-variables.md
> +| OTEL_SDK_ENABLED         | Activate/deactivate the SDK | true | If "false", disable the SDK. If "true" will enable the SDK.  <br/>If "false" will configure Noop SDK implementation providers for Tra
I Agree.

2022-08-03 10:56 UTC, brunobat commented on spec-compliance-matrix.md
> +|OTEL_SDK_ENABLED                                  |   |      |   |      |    |      |   |    |   |    |     |
Will do

2022-08-03 14:25 UTC, arminru commented on specification/sdk-environment-variables.md
> +| OTEL_SDK_ENABLED         | Activate/deactivate the SDK | true | If "false", disable the SDK. If "true" will enable the SDK.  <br/>If "false" will configure Noop SDK implementation providers for Tra
Given the discussion in https://github.com/open-telemetry/opentelemetry-specification/pull/2679/files#r935041483 my suggestion would be:

```suggestion
| OTEL_SDK_ENABLED         | Activate/deactivate the SDK | true | If "false", disable the SDK. This will configure Noop SDK implementation providers for Tracing, Metrics, and Logs. Any other value or absence of the variable will have no effect. |
```

2022-08-03 14:27 UTC, arminru commented on specification/sdk-environment-variables.md
> +| OTEL_SDK_ENABLED         | Activate/deactivate the SDK | true | If "false", disable the SDK. If "true" will enable the SDK.  <br/>If "false" will configure Noop SDK implementation providers for Tra
I agree with @Aneurysm9. Disabling propagation can have unrelated side effects and break instrumentation "outside" of your app. It would break traces incoming from other OTel SDKs or any other instrumentation supporting W3C Trace Context.

Say you have three processes (A, B, C) with A calling B and B calling C. In each of them, only one single operation is instrumented, i.e., one span is produced each.

If all three of them are instrumented, your trace will look like this:

```
Trace id=foo:
Span id=A (no parent) ---> Span id=B (parent=A) ---> Span id=C (parent=B)
```

If you now disable the OTel SDK in B but leave the default propagators configured by the API in there, it will look like this (in languages with implicit context propagation):

```
Trace id=foo:
Span id=A (no parent) -----------------------------> Span id=C (parent=A)
```

There will not be any Span created for B, but since context propagation is still in place, the trace itself stays intact.

If you now disable propagators as well, however, it will break:

```
Trace id=foo:
Span id=A (no parent)

Trace id=bar:
                                                     Span id=C (no parent)
```

Your tracing backend will not be able to tell that A and C are related and show them in different traces.

If it would really be desired to not only disable the SDK in B but to also disable context propagation (and thus willingly break traces, if any), one can just set both the env var you propose along with `OTEL_PROPAGATORS=none` (which is supported in Java).

The env var will still disable the entire SDK but since it has SDK in the name I think it would be surprising if it would also change the default API behavior (w.r.t. context propagation).

2022-08-05 15:49 UTC, reyang commented on CHANGELOG.md
> +- Add the OTEL_SDK_ENABLED environmental variable to the SDK configuration.
https://en.wikipedia.org/wiki/Environment_variable

```suggestion
- Add the OTEL_SDK_ENABLED environment variable to the SDK configuration.
```

2022-08-08 11:09 UTC, brunobat commented on specification/sdk-environment-variables.md
> +| OTEL_SDK_ENABLED         | Activate/deactivate the SDK | true | If "false", disable the SDK. If "true" will enable the SDK.  <br/>If "false" will configure Noop SDK implementation providers for Tra
done

2022-08-08 11:10 UTC, brunobat commented on CHANGELOG.md
> +- Add the OTEL_SDK_ENABLED environmental variable to the SDK configuration.
done

2022-08-08 11:11 UTC, brunobat commented on CHANGELOG.md
> +- Add the OTEL_SDK_ENABLED environmental variable to the SDK configuration.
done

2022-08-08 11:14 UTC, brunobat commented on spec-compliance-matrix.md
> +|OTEL_SDK_ENABLED                                  |   |      |   |      |    |      |   |    |   |    |     |
done

2022-08-08 16:11 UTC, arminru commented on specification/sdk-environment-variables.md
> +| OTEL_SDK_ENABLED         | Activate/deactivate the SDK | true | If "false", disable the SDK. If "true" will enable the SDK.  <br/>If "false" will configure Noop SDK implementation providers for Tra
Resolved in 0ff45a56bf597829cd927ebc9994ce7b3b0175d3.

2022-08-08 16:12 UTC, arminru commented on specification/sdk-environment-variables.md
> +| OTEL_SDK_ENABLED         | Activate/deactivate the SDK | true | If "false", disable the SDK. If "true" will enable the SDK.  <br/>If "false" will configure Noop SDK implementation providers for Tra
Resolved in 0ff45a56bf597829cd927ebc9994ce7b3b0175d3.

2022-08-08 16:13 UTC, arminru approved these changes

2022-08-08 20:57 UTC, trask approved these changes

2022-08-09 08:36 UTC, joaopgrassi approved these changes
As @tigrannajaryan mentioned here:

> We have had some issues in this area which resulted in the precise behavior specification for Numbers and Enums.

The PR now addressed it only for this new variable, but I think it's still valuable to add `Boolean` as a new section in this doc, like we have for `Enums` and `Duration`: https://github.com/brunobat/opentelemetry-specification/blob/main/specification/sdk-environment-variables.md#enum-value . It can be done in a follow up PR, so not blocking this.

2022-08-09 08:36 UTC, joaopgrassi commented on specification/sdk-environment-variables.md
> +| OTEL_SDK_ENABLED         | Activate/deactivate the SDK | true | If "false", disable the SDK. This will configure Noop SDK implementation providers for Tracing, Metrics, and Logs. Any other value or
```suggestion
| OTEL_SDK_ENABLED         | Activate/deactivate the SDK | true | If "false", disable the SDK. This will configure Noop SDK implementation providers for Tracing, Metrics, and Logs. Any other value or absence of the variable will have no effect and the SDK will remain enabled.|
```

I'm not sure if just "will have no effect" is clear that the SDK will remain enabled as usual. Feel free to adopt this or not.

2022-08-09 10:41 UTC, brunobat commented on specification/sdk-environment-variables.md
> +| OTEL_SDK_ENABLED         | Activate/deactivate the SDK | true | If "false", disable the SDK. This will configure Noop SDK implementation providers for Tracing, Metrics, and Logs. Any other value or
will update

2022-08-09 10:41 UTC, brunobat commented on spec-compliance-matrix.md
> +|OTEL_SDK_ENABLED                                  | - |      | - | -    | -  | -    | - | -  | - | -  | -   |
will update

2022-08-09 10:45 UTC, brunobat commented on specification/sdk-environment-variables.md
> +| OTEL_SDK_ENABLED         | Activate/deactivate the SDK | true | If "false", disable the SDK. If "true" will enable the SDK.  <br/>If "false" will configure Noop SDK implementation providers for Tra
I agree propagators should not be affected by the property.

2022-08-09 10:47 UTC, brunobat commented
@Aneurysm9 is this ok for you now?

2022-08-09 11:55 UTC, jmacd commented on specification/sdk-environment-variables.md
> +| OTEL_SDK_ENABLED         | Activate/deactivate the SDK | true | If "false", disable the SDK. This will configure Noop SDK implementation providers for Tracing, Metrics, and Logs. Any other value or
Last week, there was a question about whether this setting impacts the configured propagators. I believe the answer is No and that it should be explicitly stated here.  Is the following correct?
```suggestion
| OTEL_SDK_ENABLED         | Activate/deactivate the SDK | true | If "false", disable the SDK. This will configure Noop SDK implementation providers for Tracing, Metrics, and Logs. Any other value or absence of the variable will have no effect and the SDK will remain enabled. Note that this setting has no effect on propagators configured through the OTEL_PROPAGATORS variable.|
```

2022-08-09 14:35 UTC, arminru approved these changes

2022-08-09 15:01 UTC, reyang approved these changes

2022-08-09 15:13 UTC, jmacd approved these changes

2022-08-09 15:14 UTC, atoulme commented
+1 from me as a SDK user.

2022-08-09 16:45 UTC, MrAlias requested changes
I think this has merit to be included. However, by introducing the new boolean value type to the specification for environment variables it needs to be done with understanding of the impact it will have at large to the specification.

The boolean type needs to be explicitly defined in the [special configuration types section](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/sdk-environment-variables.md#special-configuration-types) before or as a part of this PR for the changes to be accepted.

- Generalizing the type will ensure that if another boolean variable is added it is added with the same interpretation. This will also help future authors understand the need to define variables as the positive action being taken and how values will be interpreted.
- There is still a remaining unspecified aspects to the boolean type, it is not explicit if its values (`false`, `true`, or "any other value") are case sensitive.
- Restricting values for all SIGs to only `true`, `false`, and "any other value" may be too restrictive. It may prevent idiomatic behavior of language implementation. Similar to the other configuration types, booleans should be defined in a way that allows languages to extend their definition.

2022-08-09 16:45 UTC, MrAlias commented on specification/sdk-environment-variables.md
> +| OTEL_SDK_ENABLED         | Activate/deactivate the SDK | true | If "false", disable the SDK. This will configure Noop SDK implementation providers for Tracing, Metrics, and Logs. Any other value or
This should be defined as a disablement, rather than a enablement, and the generic terminology of "signals" should be used for future compatibility.

```suggestion
| OTEL_SDK_DISABLED         | Disable the SDK for all signals | false | If "true", a no-op SDK implementation will be used for all telemetry signals. Any other value or absence of the variable will have no effect and the SDK will remain enabled. This setting has no effect on propagators configured through the OTEL_PROPAGATORS variable.|
```

As currently defined, a user will need to read this specification to determine what unset means. The "zero" value of booleans in many context is `false`, it is not clear in those context that default unset means `true`. Defining this as the positive action it will take, disabling, removes this ambiguity and will alleviate OpenTelemetry user confusion.

2022-08-09 19:31 UTC, ocelotl commented
On the Python side, it looks good in my opinion but I find it a bit unspecific since I imagine a few ways of implementing this, probably being unspecific is intentional.

2022-08-10 09:20 UTC, brunobat commented on specification/sdk-environment-variables.md
> +| OTEL_SDK_ENABLED         | Activate/deactivate the SDK | true | If "false", disable the SDK. This will configure Noop SDK implementation providers for Tracing, Metrics, and Logs. Any other value or
OTEL_SDK_DISABLED has already been discussed and rejected, please read the previous comments. I will not modify the PR on this regard.

2022-08-10 09:21 UTC, brunobat commented
> I think this has merit to be included. However, by introducing the new boolean value type to the specification for environment variables it needs to be done with understanding of the impact it will have at large to the specification.
> 
> The boolean type needs to be explicitly defined in the [special configuration types section](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/sdk-environment-variables.md#special-configuration-types) before or as a part of this PR for the changes to be accepted.
> 
> * Generalizing the type will ensure that if another boolean variable is added it is added with the same interpretation. This will also help future authors understand the need to define variables as the positive action being taken and how values will be interpreted.
> * There is still a remaining unspecified aspects to the boolean type, it is not explicit if its values (`false`, `true`, or "any other value") are case sensitive.
> * Restricting values for all SIGs to only `true`, `false`, and "any other value" may be too restrictive. It may prevent idiomatic behavior of language implementation. Similar to the other configuration types, booleans should be defined in a way that allows languages to extend their definition.

Help is appreciated. Do you have a suggestion on how to define the boolean in the spec?

2022-08-10 09:24 UTC, brunobat commented on specification/sdk-environment-variables.md
> +| OTEL_SDK_ENABLED         | Activate/deactivate the SDK | true | If "false", disable the SDK. This will configure Noop SDK implementation providers for Tracing, Metrics, and Logs. Any other value or
Signals is too vage. When we mention processors is a concrete code construct that we can define as noop, not doing any work.

2022-08-10 14:29 UTC, Emily-Jiang commented on specification/sdk-environment-variables.md
> +| OTEL_SDK_ENABLED         | Activate/deactivate the SDK | true | If "false", disable the SDK. This will configure Noop SDK implementation providers for Tracing, Metrics, and Logs. Any other value or
I also advocate of using `enabled` not `disabled` as the double negative might cause a lot of confusion. OTEL_SDK_ENABLED is a better name.

2022-08-10 15:03 UTC, MrAlias commented on specification/sdk-environment-variables.md
> +| OTEL_SDK_ENABLED         | Activate/deactivate the SDK | true | If "false", disable the SDK. This will configure Noop SDK implementation providers for Tracing, Metrics, and Logs. Any other value or
If [this](https://github.com/open-telemetry/opentelemetry-specification/pull/2679#discussion_r934693167) or [this](https://github.com/open-telemetry/opentelemetry-specification/pull/2679#discussion_r929769171) is the discussion you are referring to, then you are in correct in saying the points I'm raising here have already been discussed.

If you are talking about another conversation, then you are correct and I do not see it. Please provide a link if so.

In both instances you objected to two other reviewers feedback with unjustified reason. You stated that both having `true` as a default naturally makes the value optional and that having a positive value is "much less confusing." As I stated above:

> The "zero" value of booleans in many context is `false`, it is not clear in those context that default unset means `true`.

Therefore, like stated above,

> a user will need to read this specification to determine what unset means.

Having a default value of `true` is not "much less confusing", and I imagine many users will find it quite confusing. Furthermore, this confusion will extend to them not understanding if this option is indeed optional. If they think the default value of a boolean is `false` it is reasonable for them to think that they would need to explicitly set `OTEL_SDK_ENABLED=true` so their SDK is not disabled.

> I will not modify the PR on this regard.

I see this from above, it does not seem like you are willing to accept feedback on this issue when it was suggested by two other users. I would suggest closing the PR if this is truly the case, as I am unwilling to accept the changes as they are currently submitted.

2022-08-10 15:11 UTC, MrAlias commented
> Help is appreciated. Do you have a suggestion on how to define the boolean in the spec?

Sure, I'll comment with a rough-draft of a `Boolean value` sub-section suggestion in a bit.

2022-08-10 15:22 UTC, MrAlias commented
> > Help is appreciated. Do you have a suggestion on how to define the boolean in the spec?
> 
> Sure, I'll comment with a rough-draft of a `Boolean value` sub-section suggestion in a bit.

```markdown
### Boolean value

Any value that represents a boolean MUST interpret the case-insensitive string `"true"` and the integral value of `1` as true values.
An SDK MAY extend this definition and define additional values that are interpreted as true.
Any value not explicitly defined here or by the SDK as a true value, including unset and empty values, MUST be interpreted as false.
```

2022-08-10 16:56 UTC, arminru commented
@MrAlias Your suggestion looks good to me overall, thank you!

> ```gfm
> An SDK MAY extend this definition and define additional values that are interpreted as true.
> ```

Do you already have any value other than `"true"`, `"True"`, `"TRUE"`, or `1` in mind here, or would you add this MAY clause just to make sure all potential (future) languages are covered?

2022-08-10 17:50 UTC, MrAlias commented
> Do you already have any value other than `"true"`, `"True"`, `"TRUE"`, or `1` in mind here

The Linux CLI space will also use `t`, `y`,and `yes` at times for this. Though, I didn't think these common enough to include at the spec level.

> or would you add this MAY clause just to make sure all potential (future) languages are covered?

Mostly this ^. Similar to the integer value being extended by a language, I wanted to make sure idiomatic usage in other languages are supported if they exist.

2022-08-10 17:55 UTC, MrAlias commented
I'm also okay with dropping `1` as a defined value as well and sticking with just `true` (case insensitive) if that is more desired.

2022-08-10 18:06 UTC, lalitb commented
On the C++ side, need to look if we can support this environment variable. The SDK gets enabled automatically once it is linked to the application, and it can't be disabled afterwards. We do however have limited support of dynamic loading the SDK as shared object using dlopen(Linux) / LoadLibrary(Windows) where the env variable can be used.

2022-08-11 07:50 UTC, brunobat commented on specification/sdk-environment-variables.md
> +| OTEL_SDK_ENABLED         | Activate/deactivate the SDK | true | If "false", disable the SDK. This will configure Noop SDK implementation providers for Tracing, Metrics, and Logs. Any other value or
@MrAlias as stated before having OTEL_SDK_ENABLED=true be default or OTEL_SDK_DISABLED=false be default are  logically exactly the same. One is the negation of the other. I've accepted many suggestions, as you can certainly verify by the commit record and the dozens of comments of this PR. 
Being the 2 expressions logically equivalent, the reason I'm inclined to the OTEL_SDK_ENABLED=true it's because I find non negated expressions clearer: 
if( OTEL_SDK_ENABLED){...} 
if( !OTEL_SDK_DISABLED) {...}
I think I'm being reasonable here but if you bloc the PR due to this minutia, I'm willing to bend to your will to make the PR pass.

2022-08-11 08:08 UTC, brunobat commented
@MrAlias Updated the PR to include the Boolean Value definition you proposed.

2022-08-11 14:55 UTC, MrAlias commented on specification/sdk-environment-variables.md
> +| OTEL_SDK_ENABLED         | Activate/deactivate the SDK | true | If "false", disable the SDK. This will configure Noop SDK implementation providers for Tracing, Metrics, and Logs. Any other value or
I appreciate a developer might need to understand how to negate a false value if the variable is defined as such. It is something I considered in making the suggestion. I think it is reasonable and a common thing that OTel developers are able to do.

The reasons I gave to motivate the change promote the ease of use for the end-user. We need to prioritize this in the development of OTel (see https://github.com/open-telemetry/opentelemetry-specification/issues/1113 for a prior example).

As you said, both options are logically equivalent. You can produce the same result with both. Therefore, since `OTEL_SDK_DISABLED` removes user confusion it should be used.

2022-08-11 16:01 UTC, carlosalberto commented
@lalitb This is a rather optional behavior, so it would be perfectly fine to not support it for C++ (although it's good you know about its existence, etc)

2022-08-12 18:28 UTC, cijothomas approved these changes

2022-08-16 15:02 UTC, brunobat commented on specification/sdk-environment-variables.md
> +| OTEL_SDK_ENABLED         | Activate/deactivate the SDK | true | If "false", disable the SDK. This will configure Noop SDK implementation providers for Tracing, Metrics, and Logs. Any other value or
committed

2022-08-16 15:13 UTC, Aneurysm9 commented
> Any value not explicitly defined here or by the SDK as a true value, including unset and empty values, MUST be interpreted as false.

I would invert this and explicitly define falsy values as unset, empty string, `false` or `0` and any other value as truthy.  I think this would align better with the experience of developers used to dynamic languages that treat any non-falsy value as truthy.

2022-08-16 15:58 UTC, brunobat commented
The Boolean definition has now been moved to #2729

2022-08-16 17:05 UTC, rajkumar-rangaraj approved these changes

2022-08-17 12:35 UTC, robbkidd reviewed
As the review of this spec update has evolved, it seems the title, description, and content of the change have diverged.

The current state of the proposal has the env var name ending with `_DISABLED`. 

✅ That's reflected in the title and the tables in compliance matrix and SDK env vars list.

⚠️ The CHANGELOG still states `_ENABLED`.

❓ The PR's original description also says `_ENABLED` which was the original proposal. It could help people reviewing this PR for the first time after all the discussion for the PR description to be edited to include an update describing the current state of the proposal.

2022-08-17 12:35 UTC, robbkidd commented on CHANGELOG.md
> +- Add the OTEL_SDK_ENABLED environment variable to the SDK configuration.
☝🏻 `ENABLED` here is out of sync with the rest of the changes.

```suggestion
- Add the OTEL_SDK_DISABLED environment variable to the SDK configuration.
```

2022-08-17 19:15 UTC, jmacd commented
@MrAlias do you accept the current contents of this PR? I believe the goal of specifying a "DISABLED" variable with exactly one meaningful value ("true") was to avoid the [general problem you described with interpreting booleans](https://github.com/open-telemetry/opentelemetry-specification/pull/2679#pullrequestreview-1067048624).

2022-08-25 12:53 UTC, carlosalberto commented
Ping @MrAlias

2022-08-25 23:57 UTC, MrAlias commented
> @MrAlias do you accept the current contents of this PR? I believe the goal of specifying a "DISABLED" variable with exactly one meaningful value ("true") was to avoid the [general problem you described with interpreting booleans](https://github.com/open-telemetry/opentelemetry-specification/pull/2679#pullrequestreview-1067048624).

This is the correct direction, but a boolean value is still under-specified in this PR. It looks like #2729 needs to be resolved before this can progress, as was discussed in the spec SIG meeting two weeks ago.

2022-09-02 13:22 UTC, jack-berg commented on specification/sdk-environment-variables.md
> +| OTEL_SDK_DISABLED         | Disable the SDK for all signals | false | Boolean value. If "true", a no-op SDK implementation will be used for all telemetry signals. Any other value or absence of the
Is the no-op trace SDK implementation the same as the definition [here](https://github.com/open-telemetry/opentelemetry-specification/blob/2cfad37daf7e0d20851fd8a639a55375c3fc93dd/specification/trace/api.md#behavior-of-the-api-in-the-absence-of-an-installed-sdk)?

Note this no-op definition is different than an SDK tracer provider with the default configuration, which would include the [default random id generator](https://github.com/open-telemetry/opentelemetry-specification/blob/2cfad37daf7e0d20851fd8a639a55375c3fc93dd/specification/trace/sdk.md#id-generators) and [default sampler](https://github.com/open-telemetry/opentelemetry-specification/blob/2cfad37daf7e0d20851fd8a639a55375c3fc93dd/specification/trace/sdk.md#sampling).

2022-09-02 13:28 UTC, jack-berg commented
@marcalff see [this comment](https://github.com/open-telemetry/opentelemetry-specification/issues/2729#issuecomment-1222584006). The current thinking is that any boolean environment variable should be named `*_ENABLED_*` or `*_DISABLED_* such that if a default value of false aligns with the desired default behavior.

2022-09-02 14:44 UTC, marcalff commented
> @marcalff see [this comment](https://github.com/open-telemetry/opentelemetry-specification/issues/2729#issuecomment-1222584006). The current thinking is that any boolean environment variable should be named `*_ENABLED_*` or `*_DISABLED_*` such that if a default value of false aligns with the desired default behavior.

Thanks for the clarification.

I think this is a dangerous path to take : if somehow, for a given variable, we decide to change the default for whatever reason, the variable will not be renamed, creating a weird state.

2022-09-08 08:46 UTC, brunobat commented on specification/sdk-environment-variables.md
> +| OTEL_SDK_DISABLED         | Disable the SDK for all signals | false | Boolean value. If "true", a no-op SDK implementation will be used for all telemetry signals. Any other value or absence of the
Good point to clarify @jack-berg.
That spec mentions: "A TracerProvider could also return a no-op Tracer here if **application owners configure the SDK to suppress telemetry produced by this library**.". This seems to me the same behavior that we want to accomplish with this PR.
In relation to the default random generator and sampler... In practice, the id generator could be the default random, because it should't be used, if Span Processors are not set.
In relation to Sampler, I think the Sampler should discard all tracing data.
I think this reasoning can be applied for the other providers as well. 
I think the rationale in here should be to minimize the work done during runtime, in a safe way. Null implementations should probably be avoided.
What do you think of changing  the line:
"a no-op SDK implementation will be used for all telemetry signals."
by 
"a no-op SDK implementation will be used for all telemetry signals. No-op implementations should be null sabe and minimize the amount of work performed during runtime"

2022-09-16 09:31 UTC, brunobat commented
This is still waiting for https://github.com/open-telemetry/opentelemetry-specification/issues/2729

2022-09-22 21:53 UTC, reyang commented
> This is still waiting for #2729

#2729 is resolved by #2755.

2022-09-22 22:35 UTC, MrAlias approved these changes

2022-09-22 23:05 UTC, merged