Add process.threads.count
open-telemetry/opentelemetry-specification pull request #2705
Opened 2022-08-02 00:53 UTC by atoulme

## Changes

Adds a new metric, `process.threads.count`, to the process metrics available.

Related issues [#](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/12482)

2022-08-02 00:55 UTC, cijothomas commented on specification/metrics/semantic_conventions/process-metrics.md
> +| `process.threads.count`           | UpDownCounter                                     | By   | Process threads count.
the unit is incorrect.

2022-08-02 01:00 UTC, atoulme commented on specification/metrics/semantic_conventions/process-metrics.md
> +| `process.threads.count`           | UpDownCounter                                     | By   | Process threads count.
Oh, I had assumed by was per process. OK. I guess I could go with using `none` ?

2022-08-02 01:36 UTC, atoulme commented on specification/metrics/semantic_conventions/process-metrics.md
> +| `process.threads.count`           | UpDownCounter                                     | By   | Process threads count.
Found the standard - using {threads}

2022-08-02 04:28 UTC, dmitryax approved these changes
Please update https://github.com/open-telemetry/opentelemetry-specification/blob/main/CHANGELOG.md as well

2022-08-02 07:15 UTC, arminru commented on specification/metrics/semantic_conventions/process-metrics.md
> +| `process.threads.count`           | UpDownCounter                                     | {threads}  | Process threads count.
Per our naming guidelines this should be `process.threads` (without the `.count` suffix) unless we expect more attributes to be added under `process.threads.*` and thus forming a namespace:
https://github.com/open-telemetry/opentelemetry-specification/tree/main/specification/metrics/semantic_conventions#pluralization

Are there any other related attributes used in the collector?

2022-08-02 16:12 UTC, atoulme commented on specification/metrics/semantic_conventions/process-metrics.md
> +| `process.threads.count`           | UpDownCounter                                     | {threads}  | Process threads count.
Not at this time. We could report thread time stats, but that's rather heavy. I will go with your suggestion and rename.

2022-08-02 16:14 UTC, atoulme commented
Changelog updated, thanks!

2022-08-02 16:16 UTC, tigrannajaryan commented on specification/metrics/semantic_conventions/process-metrics.md
> +| `process.threads.count`           | UpDownCounter                                     | {threads}  | Process threads count.
If we ever intend to add any other thread related metric in the future then we should keep the `.count` suffix.

2022-08-02 17:01 UTC, ThomsonTan commented on specification/metrics/semantic_conventions/process-metrics.md
> +| `process.threads`           | UpDownCounter                                     | {threads}  | Process threads count.
nit: align `UpDownCounter` with the other rows in the second column.

2022-08-02 21:32 UTC, atoulme commented on specification/metrics/semantic_conventions/process-metrics.md
> +| `process.threads.count`           | UpDownCounter                                     | {threads}  | Process threads count.
I missed this comment. I am not sure. We can wait a bit and discuss in a meeting.

2022-08-05 15:46 UTC, reyang approved these changes

2022-08-05 18:11 UTC, jack-berg approved these changes

2022-08-08 08:20 UTC, arminru approved these changes

2022-08-08 17:39 UTC, atoulme commented
Here is a bit I'll present tomorrow at the spec meeting:
I believe process.threads is a finite metric, and will not be used as a namespace. An other namespace, under thread.*, should be created if we ever standardize data under a thread. This is because listening to thread activity would typically be done via a different type of monitor than a monitor for processes. For threads, we would use instrumentation in-process, such as jmx, to listen to thread activity.

2022-08-09 14:43 UTC, carlosalberto approved these changes

2022-08-09 15:10 UTC, jmacd requested changes
I feel that this semantic convention belongs in the `process.runtime.*` section. In Go, for example, there is no "thread" concept and we already have a runtime-metrics count of goroutines.

The suffix `.count` is problematic because of the way it will translate into Prometheus/OpenMetrics. I would suggest that `process.runtime.threads` is a fine name, however--you will know it's a count because of the point kind.

2022-08-09 15:17 UTC, bogdandrutu commented
@jmacd are you proposing `process.runtime.thread.count`?

2022-08-09 15:18 UTC, reyang commented
> I feel that this semantic convention belongs in the `process.runtime.*` section. In Go, for example, there is no "thread" concept and we already have a runtime-metrics count of goroutines.

I think the fact that Golang and Node.js don't have `thread` is a good reason why this shouldn't be part of `process.runtime.*`. I feel threads is an operating system concept. Although there are indeed operating systems that don't have threads, but it seems pretty common to park it under OS and process.

2022-08-09 15:26 UTC, reyang commented
> @jmacd are you proposing `process.runtime.thread.count`?

`process.runtime.thread.count` might have a different semantic. I'll take .NET as an example, `process.thread.count` could mean "how many threads does this process have (from the operating system's point of view)", while "process.runtime.thread.count` could mean "how many [managed threads](https://docs.microsoft.com/en-us/dotnet/standard/threading/managed-threading-basics) does the .NET runtime inside this process have" (and there could be a more complex situation where multiple instances of runtime coexist, although I've never seen that in reality except for some SQL stored procedure hosting).

2022-08-09 20:44 UTC, atoulme commented
I agree with @reyang - as said on Slack:
> the process.runtime namespace does not allow to set a threads entry in it, since it is supposed to process.runtime.{environment} as per spec: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/runtime-environment-metrics.md
Second, the number of threads is the number of threads exposed at the OS level, not the level of threads or goroutines as experienced inside the program. That's the difference say between looking at Java threads and the number of threads in `top -H -p <pid>`.

2022-08-15 19:35 UTC, atoulme commented
@jmacd and anyone - any insights or follow up?

2022-08-16 13:44 UTC, carlosalberto commented
Let's discuss it on today's call (with whoever can make it) - hopefully we can merge this (either with minor renaming or not) today ;)

2022-08-16 15:24 UTC, bogdandrutu commented
> I feel that this semantic convention belongs in the process.runtime.* section. In Go, for example, there is no "thread" concept and we already have a runtime-metrics count of goroutines.

Inside the go VM indeed cannot read threads, from outside you can actually read the number of OS threads for the go process.

2022-08-17 04:47 UTC, atoulme commented
What is the next step here?

2022-08-17 14:40 UTC, carlosalberto commented
@jmacd Do you have a strong instance against going with `process.threads`? This was briefly discussed in the past Spec call, and the Golang case was deemed as a very-specific case compared to the rest of the languages, when it comes to this item, so we could deem it as a special case (Python also has coroutines, but it _also_ has threads - that is the closest IIRC).

2022-08-17 16:30 UTC, jmacd approved these changes

2022-08-17 16:57 UTC, merged