Add OpenSearch in the database group
open-telemetry/opentelemetry-specification pull request #2718
Opened 2022-08-08 15:48 UTC by sharp-pixel

This PR adds OpenSearch in the database section of semantic conventions.
This is necessary for example to provide support for java instrumentation of OpenSearch clients.

Signed-off-by: Cédric Pelvet <cpelvet@amazon.fr>

2022-08-08 22:38 UTC, reyang submitted a review, later dismissed

2022-08-08 22:39 UTC, reyang commented
@sharp-pixel would you clear the CLA?

2022-08-09 11:15 UTC, sharp-pixel commented
CLA is now clear

2022-08-09 11:23 UTC, sharp-pixel commented
Fixed spelling of OpenSearch

2022-08-09 14:45 UTC, carlosalberto approved these changes

2022-08-09 15:12 UTC, reyang approved these changes

2022-08-09 15:52 UTC, sharp-pixel commented
I tried to run the `docker run --rm -v $PWD/semantic_conventions:/source -v $PWD/specification:/spec otel/semconvgen:0.12.1 -f /source markdown -md /spec --md-check` command on the `database.md` file manually and it seems that even the previous version (before my changes) returns the error.

Something must have changed in the `semconvgen` check. I also tried the newer 0.13.0 image without success.

The problem is that it is difficult to guess what I need to do to fix it as the error message is pretty useless:
> File /spec/trace/semantic_conventions/database.md contains a table that would be reformatted.

Can someone point me to the `semconvgen` source code?

2022-08-09 16:03 UTC, joaopgrassi requested changes

2022-08-09 16:03 UTC, joaopgrassi commented on specification/trace/semantic_conventions/database.md
> +| `opensearch` | OpenSearch |
Hey @sharp-pixel! thanks for the contribution. 

About the table here: I guess you added the new entry here manually? 

There's a tool that automatically takes the values from the `.yaml` file and updates the table (that's why there's these `<!-- semconv -->` annotations). You can read more about it here: [Generating markdown](https://github.com/open-telemetry/opentelemetry-specification/blob/main/semantic_conventions/README.md#generating-markdown).

One of the checks are failing because the new value is between `elasticsearch` and `memcached`, but the table here shows it at the end, so the check fails (as it expects it in between). 

I'd suggest to move `opensearch` to the end in the `yaml` file, and then run the tool to update the table. You can do so as:

```shell
make table-generation
```

The command run the tool as a docker container, so you will need that installed. Once you do that, you can verify that all works with:

```shell
make table-check
```
If all is well, it will show something like this `99 files left unchanged.` Let me know if you need help.

2022-08-09 16:13 UTC, sharp-pixel commented on semantic_conventions/trace/database.yaml
> +            - id: opensearch
done

2022-08-09 16:13 UTC, sharp-pixel commented on specification/trace/semantic_conventions/database.md
> +| `opensearch` | OpenSearch |
Thanks, after my modifications, I applied `make fix` and it passes the test locally.

2022-08-09 16:15 UTC, joaopgrassi commented on specification/trace/semantic_conventions/database.md
> +| `opensearch` | OpenSearch |
Great. Usually it works well if you modify the yaml, then `make table-generation`. It will apply the changed in the markdown file so you don't have to worry about it.

2022-08-09 16:15 UTC, joaopgrassi commented
Please, make sure to add an entry to the changelog under ` ## Unreleased > ### Semantic Conventions`

2022-08-09 17:37 UTC, sharp-pixel commented on specification/trace/semantic_conventions/database.md
> +| `opensearch` | OpenSearch |
Thanks for the info

2022-08-10 08:04 UTC, sharp-pixel commented
The `markdown-link-check` errors seem to be transient as the link(s) in error seems to be working fine.

2022-08-10 08:16 UTC, joaopgrassi approved these changes

2022-08-10 12:49 UTC, sharp-pixel commented on CHANGELOG.md
> +- Add OpenSearch in the database group.
done

2022-08-10 12:49 UTC, sharp-pixel commented on CHANGELOG.md
> +  ([#2718](https://github.com/open-telemetry/opentelemetry-specification/pull/2718))
done

2022-08-11 08:33 UTC, joaopgrassi commented
@open-telemetry/specs-trace-approvers I think this is good to go :)

2022-08-11 18:40 UTC, merged