Clarify per-message attributes usage in batching scenarios
open-telemetry/opentelemetry-specification pull request #2763
Opened 2022-08-30 21:40 UTC by lmolkova

Messaging instrumentation SIG is working on [spec changes](https://github.com/open-telemetry/oteps/pull/192) and this change is one of the first steps to bring the consensus we reached in SIG to the spec.

This change clarifies that per-message attributes should be set on links when the corresponding span represents a batching operation.

It also adds the `messaging.batch_size` attribute which intends to:
- denote a bathing operation
- record number of messages sent/received/processed - since links can be dropped or there can be some other links not describing messages, links count is not a reliable indicator of batch size. Assuming a high-scale scenario, users might want to opt out from per-message tracing, but then batch_size would still be useful

2022-08-31 07:14 UTC, blumamir reviewed
Thank you @lmolkova

2022-08-31 09:27 UTC, blumamir commented on specification/trace/semantic_conventions/messaging.md
> +corresponding span and SHOULD instead be set on link. See [Batch Receiving](#batch-receiving) and [Batch Processing](#batch-processing) for more information on correlation using links.
It is implied from the SHOULD wording, but I wonder if it is appropriate to document here that instrumentation is allowed to not create some or all links for reasons of volumes/costs or if the information is not available

For example, `message.id` is not always defined for all systems (redis pub-sub, sockeit.io).
Some attributes can be present but supply no value to the user in some cases - `messaging.message.payload_size_bytes` can be recorded but it can be considered noise for many users.
Maybe some attributes are simply too expensive or complicated to capture.

If instrumentation doesn't need or chooses not to store anything on links attributes, they may be dropped entirely IMO.

2022-08-31 09:27 UTC, blumamir commented on specification/trace/semantic_conventions/messaging.md
> +corresponding span and SHOULD instead be set on link. See [Batch Receiving](#batch-receiving) and [Batch Processing](#batch-processing) for more information on correlation using links.
Creating a link requires a context to set as the link target. This context might not always be available:
- producer is not instrumented
- no appropriate mechanism to propagate context in a specific system (redis pub-sub, socket.io for example)
- intermediaries and message routing mechanisms which drop the context.

However, using links is the only way to record per message information in batch operations, when might be desired even when context is not available.

Do you think we should also describe how to generate links in the absence of creation context? we discussed using an invalid (zeroed) context for that if I remember correctly. We can also add it in a future PR but I think it should eventually be speced.

2022-08-31 09:27 UTC, blumamir commented on specification/trace/semantic_conventions/messaging.md
> +corresponding span and SHOULD instead be set on link. See [Batch Receiving](#batch-receiving) and [Batch Processing](#batch-processing) for more information on correlation using links.
I think it is also appropriate to state here that each message should be captured as link only once and not more.
In the absence of clear systematic rules of how to differentiate specific messages by attributes, and the fact that links can be dropped, It will not be possible to tell if a span with `messaging.batch.size` of 2 and two links contains one link per message, or zero link for the first message and two for the seconds.

Constraining the messages to be recorded at most once as links, will allow UIs to derive a meaningful set of unique messages from links with no ambiguaty.

2022-08-31 10:43 UTC, Oberon00 commented on specification/trace/semantic_conventions/messaging.md
> +corresponding span and SHOULD instead be set on link. See [Batch Receiving](#batch-receiving) and [Batch Processing](#batch-processing) for more information on correlation using links.
> Do you think we should also describe how to generate links in the absence of creation context?

I don't think links are ideal then, maybe use events instead?

> Do you think we should also describe how to generate links in the absence of creation context? we discussed using an invalid (zeroed) context for that if I remember correctly.

I don't think SDKs (consistently?) support creating invalid links right now (tangentially related #753).

And also: How should this be handled on the sending side? A link (necessarily) always points to a parent, so I don't think it even makes sense semantically. This feels like a very important issue/inconsistency to me. Should span events be used instead?

2022-08-31 11:11 UTC, blumamir commented on specification/trace/semantic_conventions/messaging.md
> +corresponding span and SHOULD instead be set on link. See [Batch Receiving](#batch-receiving) and [Batch Processing](#batch-processing) for more information on correlation using links.
The problem with span events is that they don't capture a context, thus making it impossible to correlate a single message flow when producer and consumer are not in the same trace (or even when they are in the same trace sometimes?)

Links offer both the silo to store per-message attributes, and a way to "jump" from consumer to producer.

2022-08-31 13:39 UTC, Oberon00 commented on specification/trace/semantic_conventions/messaging.md
> +corresponding span and SHOULD instead be set on link. See [Batch Receiving](#batch-receiving) and [Batch Processing](#batch-processing) for more information on correlation using links.
I was talking about using events for where you don't have a context you can capture.

2022-08-31 14:31 UTC, Oberon00 commented on specification/trace/semantic_conventions/messaging.md
> +corresponding span and SHOULD instead be set on link. See [Batch Receiving](#batch-receiving) and [Batch Processing](#batch-processing) for more information on correlation using links.
I agree, it's not nice at all. And events don't really make sense semantically either, but IMHO more than links on the outgoing side

2022-08-31 16:06 UTC, joaopgrassi commented on specification/trace/semantic_conventions/messaging.md
> +Following attributes apply to links describing each message.
Somewhat related but maybe not: Should we remove the message-specific attributes from the general table and only have them here? Not sure but it might confuse people on why they are duplicated.

2022-08-31 22:44 UTC, lmolkova commented on specification/trace/semantic_conventions/messaging.md
> +| Link attributes |  |  |  |  | Span Prod1: `messaging.message.id`: `"a1"`  |
I'm as surprised as you, but current spec  does not use links on receive spans. The idea it has is:
- Receive  batch has ho links
- Receive process spans are its children and there is process span per child
- Process spans have links to message context

I.e. receive is still correlated to message, but via link on the child.

2022-08-31 22:48 UTC, lmolkova commented on specification/trace/semantic_conventions/messaging.md
> +Note that each or messaging operations (`send`, `receive`, or `process`) can describe a batch of messages. For batch operations per-message attributes cannot be set on
Let's discuss it tomorrow. It'd be great to clarify recommendations for the non-batching case.  I think it'd be overkill to use links for rabbit or other single-send systems. Also requiring attributes on links means that this spec will stop working for all backends.

2022-08-31 22:49 UTC, lmolkova commented on specification/trace/semantic_conventions/messaging.md
> +corresponding span and SHOULD instead be set on link. See [Batch Receiving](#batch-receiving) and [Batch Processing](#batch-processing) for more information on correlation using links.
all of the message attributes come with `recommended` requirement level which [explicitly](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/common/attribute-requirement-level.md#recommended) mentions they could be disabled.

2022-08-31 22:51 UTC, lmolkova commented on specification/trace/semantic_conventions/messaging.md
> +corresponding span and SHOULD instead be set on link. See [Batch Receiving](#batch-receiving) and [Batch Processing](#batch-processing) for more information on correlation using links.
I want to refrain from changing the current state of affairs in this PR. Current spec already uses links and not events and does not deal with the edge cases (missing context on the message). We'll nee to solve it in scope of all messaging work. but let's not do it in this PR and keep status quo for now.

2022-08-31 23:11 UTC, lmolkova commented on semantic_conventions/trace/messaging.yaml
> +            If available and only if the span describes operations that operate with message batches. It SHOULD NOT be set when
I figured `only if` is enough. `conditionally_required` implies MUST

2022-08-31 23:12 UTC, lmolkova commented on semantic_conventions/trace/messaging.yaml
> +            If available and only if the span describes operations that operate with message batches. It SHOULD NOT be set when
the same `only if` is enough, the second statement is redundunt

2022-08-31 23:12 UTC, lmolkova commented on specification/trace/semantic_conventions/messaging.md
> +Following messaging attributes apply to spans describing `send`, `receive`, and `process`  operations.
removed the sentence, as it does not clarify anything.

2022-08-31 23:17 UTC, lmolkova commented on specification/trace/semantic_conventions/messaging.md
> +corresponding span and SHOULD instead be set on link. See [Batch Receiving](#batch-receiving) and [Batch Processing](#batch-processing) for more information on correlation using links.
I ended up changing this to 

>  For batch operations per-message attributes cannot be set on the corresponding span and MAY instead be set on a link

this way events can also be used. 

Once we finalize the consensus in messaging SIG on span structure, we'll bring it here via different PR.

2022-09-01 08:32 UTC, Oberon00 commented on specification/trace/semantic_conventions/messaging.md
> +corresponding span and SHOULD instead be set on link. See [Batch Receiving](#batch-receiving) and [Batch Processing](#batch-processing) for more information on correlation using links.
> Current spec already uses links and not events and does not deal with the edge cases (missing context on the message).

The current spec doesn't use attributes on links, so I always interpreted that as creating links only for the messages you have context.
I don't think an incoming message without context is an edge case, it seems perfectly normal to me.

2022-09-01 12:07 UTC, joaopgrassi commented on specification/trace/semantic_conventions/messaging.md
> +Note that each or messaging operations (`send`, `receive`, or `process`) can describe a batch of messages. For batch operations per-message attributes cannot be set on
I will add to the agenda for today's meeting.

2022-09-01 18:00 UTC, lmolkova commented on specification/trace/semantic_conventions/messaging.md
> +corresponding span and SHOULD instead be set on link. See [Batch Receiving](#batch-receiving) and [Batch Processing](#batch-processing) for more information on correlation using links.
> The current spec doesn't use attributes on links, so I always interpreted that as creating links only for messages with context.

Right, but the current spec already uses links (and not events). The only thing I want to make with this change is to allow per-message attributes to appear on links.
This change makes current spec limitations more obvious but does not change the status quo.

We'll have another PR on when and how links are populated separately. We can discuss events/links/empty context there

2022-09-08 14:59 UTC, dpauls commented on specification/trace/semantic_conventions/messaging.md
> +**[4]:** If available and only if the span describes operations that operate with message batches.
```suggestion
**[4]:** If available within the messaging system, and only if the span describes operations that operate with message batches.
```
The reason for this change is that before it looked like the intent was to say "Available if and only if", except a mistake was made. I think this makes it clearer.

2022-09-08 14:59 UTC, dpauls commented on specification/trace/semantic_conventions/messaging.md
> +**[3]:** Instrumentation SHOULD always set it on batch `receive` operations regardless of the actual number of received messages (e.g. 0, 1, or more).
Is this note needed? I feel like note 4 below covers this. Perhaps if the desire is to express "SHOULD", this could be added at the beginning of note 4?

2022-09-08 14:59 UTC, dpauls commented on specification/trace/semantic_conventions/messaging.md
> +**[5]:** only if messaging.batch.size is not set or set to `1`.
```suggestion
**[5]:** Only if messaging.batch.size is not set or if the value applies to all messages in the batch.
```
The purpose for this suggestion is to leave the door open to the possibility all messages in a batch could be part of the same conversation. Regardless of whether any existing messaging systems behave this way, I see no reason to insist the batch size needs to be 1 for this to apply to a batch.

2022-09-08 14:59 UTC, dpauls commented on specification/trace/semantic_conventions/messaging.md
> +
Can note 5 be reused for all of these?

2022-09-15 04:22 UTC, lmolkova commented on specification/trace/semantic_conventions/messaging.md
> +**[3]:** Instrumentation SHOULD always set it on batch `receive` operations regardless of the actual number of received messages (e.g. 0, 1, or more).
This note describes `receive` specifically, while  note above applies to all possible messaging operations.
Receive is special because you can have 0 messages received and also it's common to request N messages and potentially receive M, so defaulting to 1 does not make sense. 

This is also a recommendation, while `conditionally_required` level on note [4] implies MUST.

2022-09-15 04:25 UTC, lmolkova commented on specification/trace/semantic_conventions/messaging.md
> +
The source of truth is messaging.yaml file, this notes are auto-generated and I feel it's important to have conditions specified on each attribute.

2022-09-27 08:24 UTC, joaopgrassi commented
Not stale

2022-09-29 12:24 UTC, joaopgrassi commented on semantic_conventions/trace/messaging.yaml
> +          Destination name SHOULD uniquely identify specific queue, topic, or other entity within broker. If
```suggestion
          The destination name SHOULD uniquely identify a queue, topic, or other entity within a broker. If
```

2022-09-29 12:24 UTC, joaopgrassi commented on semantic_conventions/trace/messaging.yaml
> +          broker does not have such notion, destination name SHOULD uniquely identify broker.
```suggestion
          the broker does not have such notion, the destination name SHOULD uniquely identify the broker.
```

2022-09-29 12:24 UTC, joaopgrassi commented on semantic_conventions/trace/messaging.yaml
> +          If destination name is the same for all messages being published,
```suggestion
          If the destination name is the same for all messages being published, 
```

2022-09-29 12:24 UTC, joaopgrassi commented on semantic_conventions/trace/messaging.yaml
> +          it MUST be set on corresponding publish, receive, process or other span.
Do we need to have `or other span` here? If so, maybe something like: 

```suggestion
          it MUST be set on the corresponding publish, receive and process span. It MAY also be set on other spans related to any of aforementioned operations.
```

2022-09-29 12:24 UTC, joaopgrassi commented on semantic_conventions/trace/messaging.yaml
> +            If available within the messaging system, and only if the span describes operations that operate with message batches.
```suggestion
            If available within the messaging system, and only if the span describes operations that involve a batch of messages.
```
Maybe? I mostly wanted to avoid:  "operations that operate"

2022-09-29 12:24 UTC, joaopgrassi commented on specification/trace/semantic_conventions/messaging.md
> +Note that attributes in `messaging.message` namespace describe message. It's recommended to use `messaging.{system}.message` namespace for specific messaging system attributes that describe individua
>namespace describe message

I'm a bit confused with this sentence. Should it also say?

>namespace describe an individual message.

2022-09-29 12:24 UTC, joaopgrassi commented on specification/trace/semantic_conventions/messaging.md
> +Following attributes apply to links describing each message.
```suggestion
The following attributes apply to links describing each message on a batch.
```
We want to say the following attributes apply to links when working with a batch right? Or regardless? I think we didn't reach a decision if we will _always_ record message-specific attributes on a link, regardless if it's a batch or not. Maybe we should pin this down, so we know how to phrase things here.

2022-10-08 09:19 UTC, joaopgrassi commented
Not stale

2022-10-12 23:56 UTC, pyohannes commented on specification/trace/semantic_conventions/messaging.md
>  | `messaging.destination` | `"Q"` | `"Q"` | `"Q"` | `"Q"` | `"Q"` |
We probably also need to fix attribute names throughout the examples (like changing this line to `messaging.destination.name`).

2022-10-12 23:56 UTC, pyohannes commented on specification/trace/semantic_conventions/messaging.md
> +| Link attributes |  |  |  |  | Span Prod1: `messaging.message.id`: `"a1"`  |
The idea to put message specific attributes on links works for the new span structure we worked out in the messaging workgroup, however, it will not fit with some of the examples in this spec (as there are cases like this one, where there are no links to hold attributes).

2022-10-20 15:32 UTC, lmolkova commented on specification/trace/semantic_conventions/messaging.md
> +Note that each or messaging operations (`send`, `receive`, or `process`) can describe a batch of messages. For batch operations per-message attributes cannot be set on
discussed on SIG meeting: don't be prescriptive for now, clarify links in future PRs along with link/event choice

2022-10-20 15:59 UTC, lmolkova commented on specification/trace/semantic_conventions/messaging.md
> +Note that attributes in `messaging.message` namespace describe message. It's recommended to use `messaging.{system}.message` namespace for specific messaging system attributes that describe individua
Discussed at SIG meeting:
- `messaging.{system}.message.attr` is preferable to keep all system-specific attr in the same namespace
- `{system}` should match exactly `messaging.system`
- we should also describe namespace pattern for messaging.destination and source.
- Perhaps we should standardize it across specs in https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/common/attribute-naming.md

2022-10-26 19:09 UTC, lmolkova commented on specification/trace/semantic_conventions/messaging.md
> +Following attributes apply to links describing each message.
We discussed attributes on span vs links on Thu meeting and decided to not be prescriptive in this PR just yet. So I rephrased it, LMK what you think

2022-10-26 19:10 UTC, lmolkova commented on semantic_conventions/trace/messaging.yaml
> +          it MUST be set on corresponding publish, receive, process or other span.
removed the sentence since we decided to address attribute placement (on spans or links) in a separate PR.

2022-10-27 15:42 UTC, lmolkova commented on specification/trace/semantic_conventions/messaging.md
> +Note that attributes in `messaging.message` namespace describe message. It's recommended to use `messaging.{system}.message` namespace for specific messaging system attributes that describe individua
* allow jms and amqp and specific system on the span
* messaging.system vs messaging.{system}.message needs further discussion, but keep it open for now.

2022-11-03 04:19 UTC, pyohannes commented on specification/trace/semantic_conventions/messaging.md
> +Note that attributes in `messaging.message` namespace describe message. It's recommended to use `messaging.{system}.message` namespace for specific messaging system attributes that describe individua
Sorry, I missed the discussion about multiple messaging system combinations last week. My take on this:
* AMQP qualifies more than a protocol than a system. So, you might have a `messaging.system` set to `kafka`, and `net.app.protocol.name` set to `amqp`.
* There's the case when AMQP is used without any messaging system on top. I think at one point there should be semantic conventions specific to AMQP that (probably) prescribe to dedicated spans for AMQP operations and can be combined with spans prescribed by these conventions. AMQP semantic conventions would model the transport layer.
* I think if messaging systems are used on top of each other (e. g. JMS and RabbitMQ) each of those will create spans independently. This causes other problems (@lmolkova treats them in https://github.com/open-telemetry/oteps/pull/172), however, I think it's the only reasonable way to model this reliable.

2022-11-03 17:02 UTC, blumamir commented on specification/trace/semantic_conventions/messaging.md
> +**[7]:** If the value applies to all messages in the batch.
I know it might be a bit too specific, but for a batch of messages the value can be the same by protocol (reading a batch of messages from a single queue), or it can be that we read a few arbitrary messages and they happen to have the same destination at a single invocation.
I think this attribute is required for the first case (same destination by definition), and SHOULD NOT be set for the second case.
WDYT?

2022-11-03 17:05 UTC, blumamir commented on specification/trace/semantic_conventions/messaging.md
> +For message producers, the following additional attributes may be set:
Here we say "**may** be set", but it's a bit confusing, as the required level for these attributes is not MAY.
They are not optional, they should be set if available.
Maybe replace the word may with something else?

2022-11-03 17:07 UTC, blumamir commented on specification/trace/semantic_conventions/messaging.md
> +| `messaging.source.template` | string | Low cardinality field representing messaging source | `/customers/{customerId}` | Conditionally Required: [2] |
for destination, we have this text describing what it means:

> Destination names could be constructed from templates. An example would be a destination name involving a user name or product id. Although the destination name in this case is of high cardinality, the underlying template is of low cardinality and can be effectively used for grouping and searching spans.

Maybe add it here so a user that landed on this section has the context as well? or extract to a common section and link both to the description?

2022-11-03 17:10 UTC, blumamir commented on specification/trace/semantic_conventions/messaging.md
> +| `messaging.source.anonymous` | boolean | denotes that the source is an anonymous source (could be unnamed or have auto-generated name) |  | Recommended: [4] |
for destination we wrote:

> A boolean that is true if the message destination is temporary and might not exist anymore after messages are processed.

maybe we should align both descriptions for consistency?

2022-11-03 17:13 UTC, blumamir commented on specification/trace/semantic_conventions/messaging.md
> +The following attributes describe individual messages. For batch operations per-message attributes cannot be set on the corresponding unless they are the same for all batch and MAY instead be set on
```suggestion
The following attributes describe individual messages. For batch operations per-message attributes cannot be set on the corresponding span attributes unless they are the same for all messages in the batch and MAY instead be set on a link. See [Batch Receiving](#batch-receiving) and [Batch Processing](#batch-processing) for more information on correlation using links.
```

2022-11-03 17:17 UTC, blumamir commented on specification/trace/semantic_conventions/messaging.md
> +<!-- endsemconv -->
Do we have to repeat the table here? 
Seems a bit confusing, as these attributes are now specified twice in the document.

Also, some attributes never makes sense in a batch or need clarification on their meaning for batch (`messaging.message.id`, `messaging.message.payload_size_bytes`, `messaging.message.payload_compressed_size_bytes`)

2022-11-03 17:19 UTC, blumamir commented on specification/trace/semantic_conventions/messaging.md
> +All attributes that are specific for a messaging system SHOULD be populated in `messaging.{system}` namespace. Message-, destination-, or source-specific attributes SHOULD be populated under correspo
What is the meaning of the hyphen? `Message-`, `destination-`?

2022-11-03 17:21 UTC, blumamir commented on specification/trace/semantic_conventions/messaging.md
> +* source-specific under `messaging.{system}.source`
These sentences are not consistent with the capital first letter.
Since they are found in attribute names in lower case, I suggest making them all lowercase.

2022-11-03 17:22 UTC, blumamir commented on specification/trace/semantic_conventions/messaging.md
>  | `messaging.kafka.consumer_group` | string | Name of the Kafka Consumer Group that is handling the message. Only applies to consumers, not producers. | `my-group` | Recommended |
Should this be changed to `messaging.kafka.source.consumer_group`?

2022-11-03 17:24 UTC, blumamir commented on specification/trace/semantic_conventions/messaging.md
>  | `messaging.kafka.partition` | int | Partition the message is sent to. | `2` | Recommended |
I wonder if the partition should be hosted under a namespace 🤔 (`source`, `destination`)

2022-11-06 19:52 UTC, ppatierno commented on specification/trace/semantic_conventions/messaging.md
> +| [`net.app.protocol.name`](span-general.md) | string | Application layer protocol used. The value SHOULD be normalized to lowercase. | `AMQP`; `MQTT` | Recommended |
The value should be normalized to lowercase but then the examples are uppercase. Should we use lowercase in the examples as well? To reinforce that the should be that way.

2022-11-09 00:22 UTC, pyohannes commented on specification/trace/semantic_conventions/messaging.md
>  In RabbitMQ, the destination is defined by an *exchange* and a *routing key*.
In the line below, `messaging.destination` should be changed to `messaging.destination.name`.

2022-11-09 00:23 UTC, pyohannes commented on specification/trace/semantic_conventions/messaging.md
> +All attributes that are specific for a messaging system SHOULD be populated in `messaging.{system}` namespace. Message-, destination-, or source-specific attributes SHOULD be populated under correspo
```suggestion
All attributes that are specific for a messaging system SHOULD be populated in `messaging.{system}` namespace. Attributes that are specific to the message, the message destination, or the message source SHOULD be populated under corresponding namespace:
```

2022-11-09 22:04 UTC, lmolkova commented on specification/trace/semantic_conventions/messaging.md
> +| `messaging.message.id` | string | A value used by the messaging system as an identifier for the message, represented as a string. | `452a7c7c7c7048c2f887f61572b18fc2` | Recommended |
I think we have to keep yml definition full and correct. We need to explain which per-message attributes are common (and can appear on every span), which of them apply only to publish/receive/etc.

2022-11-09 22:34 UTC, lmolkova commented on specification/trace/semantic_conventions/messaging.md
>  | `messaging.kafka.partition` | int | Partition the message is sent to. | `2` | Recommended |
moved both to `messaging.kafka.message` namespace and also did the same for `messaging.rabbitmq.message.routing_key` as it's message-specific

2022-11-09 23:02 UTC, lmolkova commented on specification/trace/semantic_conventions/messaging.md
> +Note that attributes in `messaging.message` namespace describe an individual message, `messaging.destination` namespace
do you mean that `messaging.message.conversation_id` can be used to describe the batch? I believe with your notes above, it's the only attribute in `message` namespace that can be shared between different messages? 

I guess the point here that `message` attributes describe message properties, but as an optimization, message properties can be populated once on the corresponding span. Do you think I should change the description so it's more clear?

2022-11-09 23:10 UTC, lmolkova commented on specification/trace/semantic_conventions/messaging.md
> +**[7]:** If the value applies to all messages in the batch.
> I know it might be a bit too specific, but for a batch of messages the value can be the same by protocol (reading a batch of messages from a single queue), or it can be that we read a few arbitrary messages and they happen to have the same destination at a single invocation.
I think this attribute is required for the first case (same destination by definition), and SHOULD NOT be set for the second case.

why SHOULD NOT? What if I'm sending 100 messages to a single destination on broker that supports per-message destination - do I pay more for this attribute repeated 100 times?  Probably not. I think instrumentation should do its best effort to avoid redundancy.

2022-11-09 23:18 UTC, lmolkova commented on specification/trace/semantic_conventions/messaging.md
> +<!-- endsemconv -->
If we want yaml to be accurate and strict, we need to specify per-message attributes for each span. We also need to specify attributes that can go on links.

2022-11-09 23:21 UTC, lmolkova commented on specification/trace/semantic_conventions/messaging.md
>  | `messaging.kafka.consumer_group` | string | Name of the Kafka Consumer Group that is handling the message. Only applies to consumers, not producers. | `my-group` | Recommended |
consumer group is a group of consumers, it does no describe source

2022-11-10 15:02 UTC, dpauls requested changes

2022-11-10 23:19 UTC, lmolkova commented on specification/trace/semantic_conventions/messaging.md
> +**[1]:** Instrumentation SHOULD always set it on batch `receive` operations regardless of the actual number of received messages (e.g. 0, 1, or more).
After discussion on SIG meeting, changed to `Instrumentations SHOULD NOT set `messaging.batch.size` on spans that operate with a single message. When client library supports batch and single-message API for the same operation, instrumentations SHOULD use `messaging.batch.size` for batching APIs and SHOULD NOT use it for single-message APIs.`

2022-11-10 23:23 UTC, lmolkova commented on specification/trace/semantic_conventions/messaging.md
> +| `messaging.message.id` | string | A value used by the messaging system as an identifier for the message, represented as a string. | `452a7c7c7c7048c2f887f61572b18fc2` | Recommended |
per-message attribute table is removed

2022-11-11 01:22 UTC, lmolkova commented on semantic_conventions/trace/messaging.yaml
>          brief: 'A value used by the messaging system as an identifier for the message, represented as a string.'
JMS message id is mapped to AMQP message id (https://www.oasis-open.org/committees/download.php/60574/amqp-bindmap-jms-v1.0-wd09.pdf), also JMS documentation describes it as `provider-assigned value`

https://docs.oracle.com/javaee/7/api/javax/jms/Message.html#setJMSMessageID-java.lang.String-

```
java.lang.String getJMSMessageID()

The JMSMessageID header field contains a value that uniquely identifies each message sent by a provider.

When a message is sent, JMSMessageID can be ignored. When the send or publish method returns, it contains a provider-assigned value.

A JMSMessageID is a String value that should function as a unique key for identifying messages in a historical repository. The exact scope of uniqueness is provider-defined. It should at least cover all messages for a specific installation of a provider, where an installation is some connected set of message routers.

All JMSMessageID values must start with the prefix 'ID:'. Uniqueness of message ID values across different providers is not required.

Since message IDs take some effort to create and increase a message's size, some JMS providers may be able to optimize message overhead if they are given a hint that the message ID is not used by an application. By calling the MessageProducer.setDisableMessageID method, a JMS client enables this potential optimization for all messages sent by that message producer. If the JMS provider accepts this hint, these messages must have the message ID set to null; if the provider ignores the hint, the message ID must be set to its normal unique value.

```

```
void setJMSMessageID([String](http://docs.oracle.com/javase/7/docs/api/java/lang/String.html?is-external=true) id)

This method is for use by JMS providers only to set this field when a message is sent. This message cannot be used by clients to configure the message ID. This method is public to allow a JMS provider to set this field when sending a message whose implementation is not its own.
```

If I understand JMS terminology correctly, the provider is a bridge between JMS and a specific client library, i.e. application does not generate Id and the provider guarantees uniqueness if the broker supports/needs it.

It seems that JMS does not intend message id to be a separate concept and providers are expected to map it to something the broker supports.

@dpauls do you believe that we can still have multiple message Ids on the same message? For the edge cases, it should be fine to have `messaging.specific-system.message.id`.

2022-11-16 13:16 UTC, blumamir approved these changes
Thank you so much @lmolkova for putting this up and for the great discussions.
All my previous comments are resolved.

I added a few minor non-blocking suggestions.

2022-11-16 13:17 UTC, blumamir commented on specification/trace/semantic_conventions/messaging.md
> +Note that attributes in `messaging.message` namespace describe an individual message, `messaging.destination` namespace
This is no longer relevant after latest changes. You can resolve it (I cannot resolve it myself)

2022-11-16 13:20 UTC, blumamir commented
Also, I support moving this PR out of draft and asking for reviews from the community so we can progress towards merging this.

2022-11-16 18:46 UTC, pyohannes commented on specification/trace/semantic_conventions/messaging.md
> +| `messaging.kafka.message.partition` | int | Partition the message is sent to. | `2` | Recommended |
I think it's right to have the partition as part of the `message` namespace. In Kafka, you can have message from different partitions in a single batch (see [here](https://stackoverflow.com/questions/64423092/consuming-kafka-batch-for-multiple-partitions)). This can't be modelled if the partition is part of the `source` or `destination` namespace.

2022-11-16 19:11 UTC, pyohannes approved these changes
I think this is ready for some wider discussion. We should open an issue, and if it's accepted, open a new clean PR based on this draft.

2022-11-16 19:18 UTC, lmolkova commented on semantic_conventions/trace/messaging.yaml
>          brief: 'A value used by the messaging system as an identifier for the message, represented as a string.'
we discussed with @dpauls that we might need more research in this space, but the discussion is not blocking this PR.
I added a new draft item to [project](https://github.com/orgs/open-telemetry/projects/20) linking to this discussion so we don't forget about it and going to resolve this thread.

2022-11-16 19:30 UTC, lmolkova commented on specification/trace/semantic_conventions/messaging.md
> +| `messaging.kafka.message.partition` | int | Partition the message is sent to. | `2` | Recommended |
agreed with @pyohannes  - partition is message property ([ProducerRecord](https://kafka.apache.org/24/javadoc/index.html?org/apache/kafka/clients/producer/ProducerRecord.html), [ConsumerRecord](https://kafka.apache.org/24/javadoc/index.html?org/apache/kafka/clients/consumer/ConsumerRecord.html))

2022-11-16 19:57 UTC, lmolkova commented on specification/trace/semantic_conventions/messaging.md
> +| `messaging.rabbitmq.message.routing_key` | string | RabbitMQ message routing key. | `myKey` | Conditionally Required: If not empty. |
Per Rabbit docs, [routing key is a message property](https://www.rabbitmq.com/tutorials/amqp-concepts.html#messages). It's [also available](https://www.rabbitmq.com/consumers.html#message-properties) on consumers

2022-11-16 20:03 UTC, lmolkova commented
Thanks everyone for the review! Per discussion at the last SIG meeting, I'm going to close this one and open a new PR (to simplify final review process).

2022-11-16 20:03 UTC, closed without merging