Allow fail-fast for invalid enum values
open-telemetry/opentelemetry-specification pull request #2766
Opened 2022-08-31 10:58 UTC by pellared

Fixes https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/issues/952

## Changes

Make the enum value description compatible with the basic error handling principle: https://github.com/open-telemetry/opentelemetry-specification/blob/1fd2db2ad56668959a2dc99551b76d0ff2fc1e9e/specification/error-handling.md?plain=1#L18

FYI @open-telemetry/dotnet-instrumentation-approvers

2022-08-31 11:02 UTC, pellared commented
PTAL @open-telemetry/dotnet-maintainers

2022-08-31 11:05 UTC, pellared commented
The `markdown-link-check` [build failures](https://github.com/open-telemetry/opentelemetry-specification/runs/8111863693?check_suite_focus=true) are not related to this PR.

2022-09-01 22:20 UTC, nrcventura commented
I think this ability to fail fast is particularly important for the .NET auto-instrumentation project, because it is the best way for us to provide something to our users to let them know that the configuration is bad and needs to be fixed. Alternative options would likely lead to potentially unexpected behavior, such as no telemetry data being available. With the .net auto-instrumentation project developers may not even have access to the warnings that could be generated from an invalid enum, depending on how their how responsibilities are separated (separate observability team vs direct control of observability).

2022-09-02 05:04 UTC, Kielek approved these changes

2022-09-02 16:33 UTC, reyang requested changes
I don't understand how would this proposal work - imagine the environment variable is used by some exporter, and that exporter is enabled at a later stage (e.g. the application is using some dynamic setting to allow exporters to be loaded and initialized), the wrong environment variable will cause the application to crash.

2022-09-02 16:42 UTC, pellared commented
@reyang PTAL https://github.com/open-telemetry/opentelemetry-specification/pull/2766/commits/8b28ee8d3dbd4daa3b91e2db44a718a2015d1b10

I made it explict that it cannot fail later at runtime; stolen from: https://github.com/open-telemetry/opentelemetry-specification/blob/1fd2db2ad56668959a2dc99551b76d0ff2fc1e9e/specification/error-handling.md?plain=1#L18

2022-09-02 17:38 UTC, cijothomas commented on specification/sdk-environment-variables.md
> +or _fail fast_ and cause the application to fail, but MUST NOT cause the application to fail later at run time.
```suggestion
or _fail fast_ and cause the application to fail at startup, but MUST NOT cause the application to fail later at run time.
```

2022-09-02 18:33 UTC, reyang approved these changes

2022-09-03 01:16 UTC, cijothomas approved these changes

2022-09-15 11:54 UTC, pellared commented
PTAL @open-telemetry/technical-committee @open-telemetry/specs-approvers

2022-09-15 13:51 UTC, scheler requested changes

2022-09-15 13:51 UTC, scheler commented on specification/sdk-environment-variables.md
> +or _fail fast_ and cause the application to fail at startup, but MUST NOT cause the application to fail later at run time.
What is the difference between `SDK implementations MAY support additional values not listed here` and `a value the SDK does not recognize`?  I think it may be better to explicitly write about each case of `allow_custom_values`.

Also, I suggest moving `NOT cause the application to fail later` closer to `gracefully ignore the setting`.

2022-09-15 15:52 UTC, pellared commented on specification/sdk-environment-variables.md
> +or _fail fast_ and cause the application to fail at startup, but MUST NOT cause the application to fail later at run time.
> What is the difference between `SDK implementations MAY support additional values not listed here` and a` value the SDK does not recognize`?

The first sentence says that SDK can support more values than the spec defines. The second is about handling a value not supported by the SDK.

> I suggest moving `NOT cause the application to fail` later closer `to gracefully ignore the setting`.

Can you please propose a suggestion? Take notice that  `NOT cause the application to fail` is just to put more stress that the instrumentation should never cause a crash at runtime (after initialization). This was added to address https://github.com/open-telemetry/opentelemetry-specification/pull/2766#pullrequestreview-1095114941

2022-09-15 16:54 UTC, scheler commented on specification/sdk-environment-variables.md
> +or _fail fast_ and cause the application to fail at startup, but MUST NOT cause the application to fail later at run time.
How about this:
```
For variables accepting an enum value, if the user provides a value the SDK does not recognize,
the SDK SHOULD either _fail fast_ and cause the application to fail at startup or generate a warning and gracefully ignore the setting but not cause the application to fail later at runtime.
```

Note the use of SHOULD - I do not know if MUST is really required but I do not have a strong opinion about it.

2022-09-15 17:32 UTC, pellared commented on specification/sdk-environment-variables.md
> +or _fail fast_ and cause the application to fail at startup, but MUST NOT cause the application to fail later at run time.
TBH it is less clear for me 😄 But I appreciate your feedback 👍

2022-09-20 06:59 UTC, pellared commented
> it is not clear to me if this is an allowed breaking change or no

I think it is a backward compatible change as the old functionality is still acceptable per spec. Personally, I see it more as clarification (or even fix) as this meets the basic error handling guidelines.

>  The document is marked as "Mixed" and there is no status in the "Enum value" section. For "Mixed" document do we implicitly assume unmarked sections to be "Stable" or "Experimental"?

This is a subject for a seperate PR.

2022-09-21 08:34 UTC, pellared commented
I updated the description to describe some background.

2022-09-21 13:51 UTC, tigrannajaryan commented
> The whole "Special configuration types" section is marked as "Stable". Then I would say that "Enum value" section is "Stable" as well.

I think this means this PR makes a breaking change to a "Stable" section of the spec. An application that previously would not fail can now fail after updating to a newer SDK that implements this change. That is not allowed.

Now, there is one argument that can be made to still allow this change: .NET SDK already works as this PR describes - it fails fast. Question: what do other language SDKs do currently? Do they fail fast or ignore the invalid values?

If all/most other SDKs also fail fast then I think we can say that the spec has a bug and what is written does not match the reality.

2022-09-21 14:22 UTC, pellared commented
> An application that previously would not fail can now fail after updating to a newer SDK that implements this change.

That would be indeed a breaking change but in the SDK 😉 But I do not have a strong opinion here.

2022-09-21 17:05 UTC, carlosalberto commented
As discussed in yesterday's Spec call, one alternative is to fail fast _when_ using a debug mode flag (maybe set through an environment variable). See #2817 

Would this help _at all_ for your considered case @pellared ?

2022-09-25 01:42 UTC, yurishkuro commented on specification/sdk-environment-variables.md
> +For variables accepting an enum value, if the user provides a value the SDK does not recognize,
I am not sure why this behavior is only under Enum values, shouldn't there be a common error behavior for all env values? What if integer var is set to `blah`?

2022-09-25 01:42 UTC, yurishkuro commented on specification/sdk-environment-variables.md
> +or _fail fast_ and cause the application to fail at startup, but MUST NOT cause the application to fail later at run time.
I don't think this change is necessary - https://github.com/open-telemetry/opentelemetry-specification/issues/2817#issuecomment-1257098051

2022-09-26 06:37 UTC, pellared commented on specification/sdk-environment-variables.md
> +For variables accepting an enum value, if the user provides a value the SDK does not recognize,
I was thinking about it as well, but I want to avoid scope creep in this PR. Even right now it is not clear how to proceed

2022-10-04 06:14 UTC, closed without merging