[Logs] Add semantic conventions for writing exceptions
open-telemetry/opentelemetry-specification pull request #2819
Opened 2022-09-21 20:53 UTC by CodeBlanch

## Changes

Defines how exceptions should be written when using the logs & events API.

/cc @jack-berg @scheler @MSNev

2022-09-21 20:59 UTC, reyang commented on specification/logs/semantic_conventions/exceptions.md
> +exceptions.
Curious, is there a reason to call out "_application_ exceptions"? (is it trying to hint that there are other exceptions such as library/runtime/system exceptions?)

2022-09-21 21:00 UTC, reyang commented on specification/logs/semantic_conventions/exceptions.md
> +exceptions.
For example https://learn.microsoft.com/en-us/dotnet/api/system.applicationexception

2022-09-21 21:02 UTC, reyang approved these changes
LGTM with a changelog entry.

2022-09-21 21:18 UTC, CodeBlanch commented on specification/logs/semantic_conventions/exceptions.md
> +exceptions.
Copy/paste from the tracing version 🤣 You think just drop "application" from it?

`This document defines semantic conventions for recording exceptions.`

2022-09-21 21:21 UTC, reyang commented on specification/logs/semantic_conventions/exceptions.md
> +exceptions.
Dropping "application" sounds better to me. Not sure why it was there originally and whether it was intentional, maybe `git blame` would tell 😺

2022-09-22 00:24 UTC, scheler requested changes
Interesting addition to Logs semantic conventions. Requires clarification on a few things.

2022-09-22 00:24 UTC, scheler commented on specification/logs/semantic_conventions/exceptions.md
> +context.
I understand how the semantic conventions for exceptions applies to "Events". For "Logs", are we saying the Log Appenders should follow these conventions when mapping exceptions to LogRecords?  In that case, should they record the attribute "event.name" as "exception" - otherwise, it may not be clear that the LogRecord is representing an Exception.

2022-09-22 00:24 UTC, scheler commented on specification/logs/semantic_conventions/exceptions.md
> +The event name MUST be `exception`.
I guess this semantic convention applies to all values of `event.domain`. In other words, we are *reserving* the event name `exception` for exceptions. If we agree, we should add that for additional clarity.

2022-09-22 00:24 UTC, scheler commented on specification/logs/semantic_conventions/exceptions.md
> +This document defines semantic conventions for recording exceptions.
```suggestion
This document defines semantic conventions for recording exceptions in `LogRecord`s and `Event`s.
```

2022-09-22 02:35 UTC, CodeBlanch commented on specification/logs/semantic_conventions/exceptions.md
> +The event name MUST be `exception`.
This line I really don't want to be there. It was added by the markdown table generator thing because the [exception.yaml has `type: event`](https://github.com/open-telemetry/opentelemetry-specification/blob/7a47bf9e1ed2f2aafacba423875578a83bc1e5e4/semantic_conventions/trace/exception.yaml#L4). Let me investigate a bit and see if there is a nice solve for this. I could just manually remove, but likely it will get put back when the generator is run again 😄

2022-09-22 02:37 UTC, CodeBlanch commented on specification/logs/semantic_conventions/exceptions.md
> +This document defines semantic conventions for recording exceptions.
Both "logs" and "events" use `LogRecord` so that seems a little misleading. I made it:

`This document defines semantic conventions for recording exceptions on "logs"
and "events" emitted through the [Logger API](../api.md#logger).`

LMK how you feel about that.

2022-09-22 02:56 UTC, CodeBlanch commented on specification/logs/semantic_conventions/exceptions.md
> +context.
The APIs I'm looking at in .NET sort of have shapes like this...

```csharp
logger.LogInformation(string message);
logger.LogInformation(string message, Attributes attributes);
logger.LogInformation(string message, EventId eventId, Attributes attributes);
logger.LogInformation(string message, Exception exception, Attributes attributes);
logger.LogInformation(string message, EventId eventId, Exception exception, Attributes attributes);
```

You always log a message (structured) with attributes (optional). If you have an EventId (which is name + optional id) you can pass it. If you have an exception you can also pass that.

Exceptions are really just more enrichment of the log so I _feel_ like just adding the attributes is enough. To say that another way...

> otherwise, it may not be clear that the LogRecord is representing an Exception.

I wouldn't say the log strictly represents an exception. It is just a data point which happens to have some exception data with it. It could have other stuff too.

Also I think the way the spec currently is `event.name` needs to also have `event.domain` specified so we need to change that to be more permissive or define the domain too?

2022-09-22 18:59 UTC, cijothomas commented on specification/logs/semantic_conventions/exceptions.md
> +operations. Exceptions MAY be recorded on "logs" or "events" depending on the
in the case of "events" being used for reporting exception, what would be the event name? (i.e value of the attribute "event.name"?)

2022-09-22 19:00 UTC, cijothomas commented on specification/logs/semantic_conventions/exceptions.md
> +* [`exception.type`](../../trace/semantic_conventions/exceptions.md)
did you intend to link to the trace/sem.conventions..? or this doc itself?

2022-09-22 19:03 UTC, cijothomas commented on specification/logs/semantic_conventions/exceptions.md
> +and "events" emitted through the [Logger API](../api.md#logger).
```suggestion
and [events](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/api.md#emit-event) emitted through the [Logger API](../api.md#logger).
```

2022-09-22 19:04 UTC, cijothomas commented on CHANGELOG.md
> +- Add exceptions to the logs semantic conventions
https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/data-model.md#errors-and-exceptions -- This is some language here which could be updated as part of this PR?

2022-09-22 19:05 UTC, cijothomas commented on CHANGELOG.md
> +- Add exceptions to the logs semantic conventions
Its tricky... as that doc is already marked stable, so this could be not allowed...

2022-09-22 19:07 UTC, CodeBlanch commented on specification/logs/semantic_conventions/exceptions.md
> +The event name MUST be `exception`.
Let's say I do this...

```
var logger = loggerProvider.GetLogger(name: "MyClientLibrary", eventDomain: "MyCompany.CloudService");

var logRecord = new() {
   severity = Severity.Information
};
logRecord.RecordException(myCaughtException);

logger.EmitEvent(eventName: "AddUserFailure", logRecord);
```

I want to emit an event named "AddUserFailure" which happens to have some exception details. In that case we wouldn't want to change the `event.name` to `exception` would we?

2022-09-22 19:39 UTC, cijothomas commented on specification/logs/semantic_conventions/exceptions.md
> +operations. Exceptions MAY be recorded on "logs" or "events" depending on the
resolving, as this is clear from https://github.com/open-telemetry/opentelemetry-specification/pull/2819#discussion_r977997111

2022-09-22 21:19 UTC, CodeBlanch commented on specification/logs/semantic_conventions/exceptions.md
> +* [`exception.type`](../../trace/semantic_conventions/exceptions.md)
What is going on here is I defined [log-exception which refs to the trace definition](https://github.com/open-telemetry/opentelemetry-specification/blob/8884de6ca6bb30beea65a8c16e3eb9d3c1022f06/semantic_conventions/logs/log-exception.yaml#L8-L10) and then the [markdown table generator](https://github.com/open-telemetry/opentelemetry-specification/tree/main/semantic_conventions#generating-markdown) automatically creates these links. Not sure if the reuse achieved is > the weird links or not 😄

2022-09-22 21:23 UTC, CodeBlanch commented on specification/logs/semantic_conventions/exceptions.md
> +This document defines semantic conventions for recording exceptions on "logs"
Updated

2022-09-22 21:24 UTC, CodeBlanch commented on specification/logs/semantic_conventions/exceptions.md
> +and "events" emitted through the [Logger API](../api.md#logger).
Updated

2022-09-22 21:43 UTC, CodeBlanch commented on CHANGELOG.md
> +- Add exceptions to the logs semantic conventions
I updated. We'll see if anyone objects!

2022-09-22 23:08 UTC, scheler commented on specification/logs/semantic_conventions/exceptions.md
> +The event name MUST be `exception`.
We could emit such an event even within Spans too. I wonder why the exception events within a Span MUST be named `exception`.  I thought there is a valid reason for that, but I don't know what it is.

2022-09-23 16:31 UTC, cijothomas approved these changes

2022-09-25 02:02 UTC, yurishkuro commented
Could you please explain why this change is needed, specifically why it needs to redefine how exceptions are logged instead of referring to the existing definition under `/trace/`, as this PR already does for `.stacktrace`?

2022-09-25 02:02 UTC, yurishkuro commented on specification/logs/semantic_conventions/exceptions.md
> +See [Trace Semantic Conventions for Exceptions - Stacktrace
Instead of "See ..." I would say "Same as ..."

2022-09-25 18:12 UTC, CodeBlanch commented
@yurishkuro 

> Could you please explain why this change is needed, specifically why it needs to redefine how exceptions are logged instead of referring to the existing definition under /trace/, as this PR already does for .stacktrace?

What I brought up on the Log SIG was that logging exceptions is common and the spec should define what to do. We could say "see trace exceptions" (which we kind of do) but the trace document is referencing spans & span events which are not applicable to logs. So the goal here is to prescribe what to do without ambiguity.

What perhaps might be better is to move exceptions.yaml up a level and then have traces + logs reference that?

2022-09-25 20:12 UTC, yurishkuro commented
Yes, I would support making exceptions top-level category (cf. https://bit.do/telemetry-temple) and referring to it from both traces and logs.

2022-09-26 23:14 UTC, CodeBlanch commented on specification/logs/semantic_conventions/exceptions.md
> +See [Trace Semantic Conventions for Exceptions - Stacktrace
Updated

2022-09-26 23:21 UTC, CodeBlanch commented
@yurishkuro I moved exceptions.yaml up a level and it is now referenced by traces & logs. LMK what you think about that.

2022-09-26 23:29 UTC, jack-berg approved these changes

2022-09-27 17:42 UTC, yurishkuro approved these changes

2022-09-27 17:54 UTC, djaglowski commented on specification/logs/semantic_conventions/exceptions.md
> +| `exception.stacktrace` | string | A stacktrace as a string in the natural representation for the language runtime. The representation is to be determined and documented by each language SIG. | `Exc
Have we considered whether `[]string` would be appropriate? Of course there will be language specific details beyond this, but perhaps each language can be minimally responsible for splitting the trace into frames?

2022-09-27 18:57 UTC, tigrannajaryan reviewed
I am confused about what this PR does. It seems like we have 3 different yaml files which define almost the same conventions (but not exactly the same).

Do we need the separate yaml files under traces and logs directories?

2022-09-27 19:56 UTC, CodeBlanch commented on specification/logs/semantic_conventions/exceptions.md
> +| `exception.stacktrace` | string | A stacktrace as a string in the natural representation for the language runtime. The representation is to be determined and documented by each language SIG. | `Exc
That discussion might warrant its own PR. What this PR does is use the existing trace definitions for logs. I think it is good for them to be consistent, and I wouldn't want to change trace definitions as part of this. Fair?

2022-09-27 20:02 UTC, CodeBlanch commented
@tigrannajaryan 

> Do we need the separate yaml files under traces and logs directories?

It depends I suppose on where you stand on the [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) principle 😄 The yaml files are set up so that the [Semantic Convention generator](https://github.com/open-telemetry/build-tools/tree/v0.14.0/semantic-conventions) can spit out the markdown tables from a single source of truth. There a couple subtle (maybe not so) differences between traces & logs wrt to exceptions. Traces use an event off of span and have the `escaped` attribute.

If we want to jettison the generator and just mirror content manually, that is fine by me. The risk is they might become out of sync for the shared stuff.

2022-09-27 20:07 UTC, tigrannajaryan commented
> @tigrannajaryan
> 
> > Do we need the separate yaml files under traces and logs directories?
> 
> It depends I suppose on where you stand on the [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) principle 😄 The yaml files are set up so that the [Semantic Convention generator](https://github.com/open-telemetry/build-tools/tree/v0.14.0/semantic-conventions) can spit out the markdown tables from a single source of truth. There a couple subtle (maybe not so) differences between traces & logs wrt to exceptions. Traces use an event off of span and have the `escaped` attribute.
> 
> If we want to jettison the generator and just mirror content manually, that is fine by me. The risk is they might become out of sync for the shared stuff.

I guess I am confused because I don't know how the generator works. Are you saying that the yaml files in traces and logs subdirectories reference the common yaml file?

2022-09-27 20:36 UTC, CodeBlanch commented
@tigrannajaryan 

> I guess I am confused because I don't know how the generator works. Are you saying that the yaml files in traces and logs subdirectories reference the common yaml file?

💯! In the subdirectories you'll see `ref` used in the yamls [like these in the log version](https://github.com/open-telemetry/opentelemetry-specification/blob/fd7c34c34b4b5d221cb67c7aa04f65aa6840772f/semantic_conventions/logs/log-exception.yaml#L8-L10). Then in the markdown you use the `semconv` tag thing [like this in the log version](https://github.com/open-telemetry/opentelemetry-specification/blob/fd7c34c34b4b5d221cb67c7aa04f65aa6840772f/specification/logs/semantic_conventions/exceptions.md?plain=1#L34) which tells the generator to build the table in that location. The table gets built following the refs to the shared yaml.

2022-09-28 14:33 UTC, tigrannajaryan approved these changes

2022-09-28 14:33 UTC, tigrannajaryan commented on specification/logs/semantic_conventions/exceptions.md
> +<!-- endsemconv -->
Is this section auto-generated from semantic_conventions/logs/log-exception.yaml or it is manually written?

2022-09-28 17:54 UTC, djaglowski approved these changes

2022-09-28 17:59 UTC, cijothomas approved these changes

2022-09-28 18:00 UTC, cijothomas commented on specification/logs/semantic_conventions/exceptions.md
> +The event name MUST be `exception`.
^ seems irrelevant now. Can you resolve this?

2022-09-28 18:18 UTC, CodeBlanch commented on specification/logs/semantic_conventions/exceptions.md
> +The event name MUST be `exception`.
@scheler Hey this is blocking PR LMK if you are good to resolve or you think some changes still need to be made.

2022-09-28 18:25 UTC, scheler commented on specification/logs/semantic_conventions/exceptions.md
> +The event name MUST be `exception`.
Yes, this can be resolved based on the conversation in the Log SIG today. Copying the conclusion text from the notes - 
Conclusion: the current PR is not about adding exception events to the log signal. Instead, it just adds the ability to include structured exception data to log records. We could potentially followup to this and add an exception event type, but it would still be useful to be able to include exception data on log records which are not exception events.

2022-09-28 18:57 UTC, lalitb approved these changes

2022-09-30 04:38 UTC, merged