Add `process.disk.operations` metric to semantic conventions
open-telemetry/opentelemetry-specification pull request #2845
Opened 2022-09-28 11:18 UTC by astencel-sumo

Fixes #2812

## Changes

Adds a new metric `process.disk.operations` to the semantic conventions.

## Context

Here's a related proposal to implement this metric in the OT collector's `hostmetrics` receiver: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/14084.

2022-10-04 12:54 UTC, jsuereth approved these changes

2022-10-13 12:43 UTC, astencel-sumo commented
What needs to happen for this pull request to be merged? (Other than me updating the branch again)

2022-10-31 19:40 UTC, jack-berg approved these changes

2022-10-31 19:45 UTC, reyang commented on specification/metrics/semantic_conventions/process-metrics.md
> +| `process.disk.operations`       | Counter                                            | {operations} | Number of disk operations performed by the process
What about "control" (e.g. seek, S.M.A.R.T. signal)?

2022-10-31 19:46 UTC, reyang requested changes
https://github.com/open-telemetry/opentelemetry-specification/pull/2845/files#r1009798522

2022-11-01 15:11 UTC, portertech commented on specification/metrics/semantic_conventions/process-metrics.md
> +| `process.disk.operations`       | Counter                                            | {operations} | Number of disk operations performed by the process
I like how this is inline with `process.disk.io`, w/ direction being either `read` or `write`. I suspect SMART capabilities would need their own metric(s). I don't how to address seek.

2022-11-01 18:57 UTC, reyang commented on specification/metrics/semantic_conventions/process-metrics.md
> +| `process.disk.operations`       | Counter                                            | {operations} | Number of disk operations performed by the process
There are lots and back-and-forth, e.g. #2617.

2022-11-07 11:34 UTC, astencel-sumo commented on specification/metrics/semantic_conventions/process-metrics.md
> +| `process.disk.operations`       | Counter                                            | {operations} | Number of disk operations performed by the process
@reyang I do recognize that this has been a much-discussed topic:

- the "direction" attribute was removed in favor of separate metric names https://github.com/open-telemetry/opentelemetry-specification/issues/2589
- the change was then reverted https://github.com/open-telemetry/opentelemetry-specification/issues/2726

The current state is that metrics very similar to the proposed `process.disk.operations` metric exist in the semantic conventions in the same shape as the proposed metric (with the "direction" attribute of either "read" or "write"):
- [system.disk.io](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.14.0/specification/metrics/semantic_conventions/system-metrics.md#systemdisk---disk-controller-metrics) has a [system.disk.operations](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.14.0/specification/metrics/semantic_conventions/system-metrics.md#systemdisk---disk-controller-metrics) counterpart
- [process.disk.io](https://github.com/open-telemetry/opentelemetry-specification/blob/v1.14.0/specification/metrics/semantic_conventions/process-metrics.md#process) does not have such counterpart

This proposal adds the `process.disk.operations` metric that is related to `process.disk.io` in the same was that the `system.disk.operations` is related to `system.disk.io` metric. I believe this is not a controversial change and there's no reason to not add this metric in the current shape.

If you want the discuss the shape of these metrics, I'd say it's better to open a separate issue.

2022-11-07 20:34 UTC, reyang commented on specification/metrics/semantic_conventions/process-metrics.md
> +| `process.disk.operations`       | Counter                                            | {operations} | Number of disk operations performed by the process
> I believe this is not a controversial change and there's no reason to not add this metric in the current shape.

I have different understanding - we already know the existing ones are wrong and will take breaking changes before they can be marked stable, it'll be better to avoid adding more things that require a fix.

2022-11-15 03:32 UTC, closed without merging