Add `process.signals_pending` metric to semantic conventions
open-telemetry/opentelemetry-specification pull request #2846
Opened 2022-09-28 11:28 UTC by astencel-sumo

Fixes #2826 

## Changes

Adds a new metric `process.signals_pending` to the semantic conventions.

## Context

Here's a related proposal to implement this metric in the OT collector's `hostmetrics` receiver: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/14084.

2022-10-04 12:52 UTC, jsuereth commented on specification/metrics/semantic_conventions/process-metrics.md
> +| `process.signals_pending`              | UpDownCounter                                      | {signals} | Number of pending signals for the process.
Signals are generally POSIX only.  Can you call out how this applies to non-POSIX systems (should they adapt signal-like things here?

Specifically:

- Is this *required* for POSIX systems or just recommended
- What does this mean for non-POSIX systems (or it shouldn't be filled out on those)

2022-10-04 15:11 UTC, astencel-sumo commented on specification/metrics/semantic_conventions/process-metrics.md
> +| `process.signals_pending`              | UpDownCounter                                      | {signals} | Number of pending signals for the process.
Yes, signals are a POSIX-only concept. I assume non-POSIX systems won't report this metric. I wouldn't say the metric is either required or recommended for any system (POSIX or not).

As I understand it, the OT specification only establishes a name for a specific information (a metric, an attribute, etc.), but does not specify weather a piece of information is required or recommended to be delivered by a system.

2022-10-10 16:51 UTC, arminru commented on specification/metrics/semantic_conventions/process-metrics.md
> +| `process.signals_pending`              | UpDownCounter                                      | {signals} | Number of pending signals for the process.
```suggestion
| `process.signals_pending`              | UpDownCounter                                      | {signals} | Number of pending POSIX signals for the process.                                                                                    |                                                                                                                                                                                                 |
```
I think it would be helpful to explicitly call them "POSIX signals" here to distinguish them from "telemetry signals" which are used a lot in this domain.

2022-10-11 15:27 UTC, astencel-sumo commented on specification/metrics/semantic_conventions/process-metrics.md
> +| `process.signals_pending`              | UpDownCounter                                      | {signals} | Number of pending signals for the process.
Agree, updated the wording.

2022-10-11 15:28 UTC, astencel-sumo commented on specification/metrics/semantic_conventions/process-metrics.md
> +| `process.signals_pending`              | UpDownCounter                                      | {signals} | Number of pending signals for the process.
@jsuereth does this answer your questions? Do you think it makes sense?

2022-10-31 17:14 UTC, jsuereth approved these changes

2022-10-31 19:40 UTC, jack-berg approved these changes

2022-10-31 19:47 UTC, reyang commented on specification/metrics/semantic_conventions/process-metrics.md
> +| `process.signals_pending`       | UpDownCounter                                      | {signals} | Number of pending POSIX signals for the process.
What about non-POSIX systems? Should they use this same metrics or they should invent a different name?

2022-10-31 19:47 UTC, reyang requested changes
https://github.com/open-telemetry/opentelemetry-specification/pull/2846/files#r1009799891

2022-10-31 21:49 UTC, portertech commented on specification/metrics/semantic_conventions/process-metrics.md
> +| `process.signals_pending`       | UpDownCounter                                      | {signals} | Number of pending POSIX signals for the process.
I wouldn't expect non-POSIX systems to use the same metric (and I don't know what they would use). That said, if there is a valid use-case down the road, we can change the description to accommodate. We are considering description changes to be a stable change https://docs.google.com/document/d/1Nvcf1wio7nDUVcrXxVUN_f8MNmcs0OzVAZLvlth1lYY/edit#heading=h.e71xzqqz0b5t

2022-11-01 18:53 UTC, reyang commented on specification/metrics/semantic_conventions/process-metrics.md
> +| `process.signals_pending`       | UpDownCounter                                      | {signals} | Number of pending POSIX signals for the process.
> I wouldn't expect non-POSIX systems to use the same metric (and I don't know what they would use).

Would it make sense to put it as `process.posix.signals_pending`?

2022-11-03 16:35 UTC, portertech commented on specification/metrics/semantic_conventions/process-metrics.md
> +| `process.signals_pending`       | UpDownCounter                                      | {signals} | Number of pending POSIX signals for the process.
@jsuereth WDYT?

2022-11-07 10:45 UTC, astencel-sumo commented on specification/metrics/semantic_conventions/process-metrics.md
> +| `process.signals_pending`       | UpDownCounter                                      | {signals} | Number of pending POSIX signals for the process.
> > I wouldn't expect non-POSIX systems to use the same metric (and I don't know what they would use).
> 
> Would it make sense to put it as `process.posix.signals_pending`?

I think I understand where this comes from. As described in the metrics semantic conventions' [General Guidelines](https://github.com/open-telemetry/opentelemetry-specification/tree/v1.14.0/specification/metrics/semantic_conventions#general-guidelines):

> Associated metrics SHOULD be nested together in a hierarchy based on their usage. Define a top-level hierarchy for common metric categories: for OS metrics, like CPU and network; for app runtimes, like GC internals. Libraries and frameworks should nest their metrics into a hierarchy as well. This aids in discovery and adhoc comparison. This allows a user to find similar metrics given a certain metric.

and further below:

> Semantic ambiguity SHOULD be avoided. Use prefixed metric names in cases where similar metrics have significantly different implementations across the breadth of all existing metrics. For example, every garbage collected runtime has slightly different strategies and measures. Using a single set of metric names for GC, not divided by the runtime, could create dissimilar comparisons and confusion for end users. (For example, prefer process.runtime.java.gc* over process.runtime.gc.*.) Measures of many operating system metrics are similarly ambiguous.

If I understand correctly, your point Reiley is that if a non-POSIX system has a different understanding of what a "signal" is, the metric `process.signals_pending` might have a different meaning, thus supporting the division into a `process.posix.signals_pending` metric a a `process.something-else-that-is-not-posix.signals_pending` or similar metric. This is similar to the `process.runtime.java.gc*` example in the documentation.

I have two concerns with this:
1. The `.posix.` namespace would be based on a feature of a system, not on a specific component, like the Java runtime, which in my view makes it less discoverable and harder to understand by users.
2. Most of the systems we run (definitely in the server world, given Linux dominance) are POSIX, which makes it the default setting. I'd be more in favor to give a separate namespace to a non-POSIX-specific concept, while keeping the POSIX-specific concepts - at least the most popular ones - in the default namespace.

2022-11-08 19:01 UTC, reyang commented on specification/metrics/semantic_conventions/process-metrics.md
> +| `process.signals_pending`       | UpDownCounter                                      | {signals} | Number of pending POSIX signals for the process.
> I have two concerns with this:
> 
> 1. The `.posix.` namespace would be based on a feature of a system, not on a specific component, like the Java runtime, which in my view makes it less discoverable and harder to understand by users.
> 2. Most of the systems we run (definitely in the server world, given Linux dominance) are POSIX, which makes it the default setting. I'd be more in favor to give a separate namespace to a non-POSIX-specific concept, while keeping the POSIX-specific concepts - at least the most popular ones - in the default namespace.

I think this requires more discussion, it's not a specific to this PR.

2022-11-08 22:18 UTC, astencel-sumo commented on specification/metrics/semantic_conventions/process-metrics.md
> +| `process.signals_pending`       | UpDownCounter                                      | {signals} | Number of pending POSIX signals for the process.
Good point. Unfortunately I wasn't able to join today's Specification SIG to put this under discussion.

2022-11-16 03:33 UTC, closed without merging