Support maps and heterogeneous arrays as attribute values
open-telemetry/opentelemetry-specification pull request #2888
Opened 2022-10-17 21:46 UTC by tigrannajaryan

Resolves https://github.com/open-telemetry/opentelemetry-specification/issues/376

Use cases where this is necessary or useful:

1. Specify more than one resource in the telemetry: https://github.com/open-telemetry/opentelemetry-specification/issues/579
2. Data coming from external source, e.g. AWS Metadata: https://github.com/open-telemetry/opentelemetry-specification/pull/596#issuecomment-628983680 or https://github.com/open-telemetry/opentelemetry-specification/issues/376#issuecomment-1227501082
3. Capturing HTTP headers: https://github.com/open-telemetry/opentelemetry-specification/issues/376#issuecomment-908493520
4. Structured stack traces: https://github.com/open-telemetry/opentelemetry-specification/pull/2841
5. Payloads as attributes: https://github.com/open-telemetry/oteps/pull/219#discussion_r971065645

This is a draft PR to see what the change looks like.

If this PR is merged it will be nice to follow it up with:
- A standard way of flattening maps and nested objects when converting from OTLP to formats that don't support maps/nested objects.
- Recommendations for semantic conventions to use/not use complex objects.

2022-10-18 11:54 UTC, tsloughter commented
> If so, I suspect a similar approach could be applied to structured stack traces.

That is what the current PR does, https://github.com/open-telemetry/opentelemetry-specification/pull/2841, but it requires splitting up each piece (filename, line number, etc) into a separate array of values which would then be put back together. It is hardly ideal even if it technically works with some deconstruction :)

2022-11-16 17:57 UTC, tigrannajaryan commented
I heard several times that we need this. Reopening and moving from a draft to a proper PR to discuss more widely.

2022-11-16 17:57 UTC, tigrannajaryan commented
@open-telemetry/specs-approvers PTAL.

2022-11-17 20:33 UTC, jmacd commented on specification/common/README.md
> +| key/value map                           | TBD                        |
Why TBD -- why not JSON-encoding?

2022-11-29 22:29 UTC, kentquirk commented on specification/trace/sdk_exporters/jaeger.md
> +Array and map values MUST be serialized to string like a JSON list as mentioned in
The "like a JSON list" part doesn't apply to both arrays and maps. This should probably be 2 statements: Arrays should look like a JSON list, and maps should look like a JSON object.

2022-11-30 14:38 UTC, tigrannajaryan commented on specification/trace/sdk_exporters/jaeger.md
> +Array and map values MUST be serialized to string like a JSON list as mentioned in
Reworded. PTAL.

2022-11-30 22:51 UTC, jack-berg commented
I did a [proof of concept](https://github.com/open-telemetry/opentelemetry-java/commit/8d82fdb3f44e3e0a905330232b2759da522a8951) in java to confirm that its possible to add support for map type attributes while maintaining backwards compatibility and good ergonomics. No problems turned up.

However, this adds complexity for backends and arguably just shifts the problem of flattening complex types from the opentelemetry specification to various backends. Vendors backends aside, jaeger, zipkin, and prometheus all do not support complex attributes (but to be fair also have varying support even the array attributes). Additionally, it adds potential confusion for users (e.g. when would a user choose to use complex attributes like `http={status_code=500}` versus just dot based namespacing like `http.status_code=500`). Therefore, I think the arguments for adding this type of feature need to be quite strong.

I know some folks from the Java SIG (@open-telemetry/java-approvers, @open-telemetry/java-instrumentation-approvers) have expressed concerns about this feature. It would be helpful if you could share your thoughts here. Whether this is ultimately accepted / rejected, we need to reach a conclusion.

2022-12-05 15:48 UTC, ronyis commented
> Vendors backends aside, jaeger, zipkin, and prometheus all do not support complex attributes

Isn't recording a serialized JSON (as proposed) good enough? I think that currently users already collect complex attributes like that, so at least we can improve the functionality in supported backends.
 
> Additionally, it adds potential confusion for users (e.g. when would a user choose to use complex attributes like `http={status_code=500}` versus just dot based namespacing like `http.status_code=500`)

Since this situation is not relevant for traces only, I think we can't escape users having to be aware of it (for example, logs attributes already support this). Nevertheless, IMO we could add a general clarification that relying on the flattening of nested fields doesn't convey the semantic conventions (`http={status_code=500}` isn't considered as `http.status_code=500` even if some backends may choose differently).

2022-12-06 15:49 UTC, MrAlias commented on specification/common/README.md
> +  - A key/value map, where key is string and value is any attribute value [since 1.15.0].
The inhomogeneity here will mean the Go type system will need to be side-stepped. Is there a reason we want to allow inhomogeneity here?

2022-12-06 15:49 UTC, MrAlias commented on specification/common/README.md
> +  - A key/value map, where key is string and value is any attribute value [since 1.15.0].
Does "any attribute value" here mean _any_ or does it mean a primitive type an array/map of these primitive types? Can I have a map with a Go `struct` as a value?

2022-12-06 16:48 UTC, tigrannajaryan commented on specification/common/README.md
> +  - A key/value map, where key is string and value is any attribute value [since 1.15.0].
`any` here refers to any vaid value type defined here in this spec. We need a recursive definition. It may be best to rewrite this whole paragraph to make it clear.

Take a look at how `any` is defined for logs: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/data-model.md#type-any

I can copy/paste from there if it is clearer.

2022-12-14 21:27 UTC, tigrannajaryan commented on specification/common/README.md
> +  - A key/value map, where key is string and value is any attribute value [since 1.15.0].
Re-worded to use `any` as a recursively defined type. PTAL.

2022-12-20 18:05 UTC, scheler commented
Consider the following 2 options - 


<details>
<summary>Sample PageView Event - Option 1</summary>

```json
    "log_record": {
        "timeUnixNano":"1581452773000000789",
        "attributes": [
        {
            "key": "event.domain",
            "value": {
            "stringValue": "browser"
            }
        },
        {
            "key": "event.name",
            "value": {
            "stringValue": "page_view"
            }
        },

        {
            "key": "event.data",
            "value": {
            "mapValue": {
                "http.url": "https://www.guidgenerator.com/online-guid-generator.aspx",
                "referrer": "http://google.com",
                "type": 0,
                "title": "Free Online GUID Generator"
            }
            }
        }
        ]
    }

```
</details>

<details>
<summary>Sample PageView Event - Option 2</summary>

```json
    "log_record": {
        "timeUnixNano":"1581452773000000789",
        "attributes": [
        {
            "key": "event.domain",
            "value": {
            "stringValue": "browser"
            }
        },
        {
            "key": "event.name",
            "value": {
            "stringValue": "page_view"
            }
        },

        {
            "key": "event.data",
            "value": {
                "nestedAttributes": [
                    {
                        "key": "http.url",
                        "value": {
                        "stringValue": "https://www.guidgenerator.com/online-guid-generator.aspx"
                        }
                    },
                    {
                        "key": "http.url",
                        "value": {
                        "stringValue": "https://www.guidgenerator.com/online-guid-generator.aspx"
                        }
                    },
                    {
                        "key": "type",
                        "value": {
                        "intValue": "0"
                        }
                    },
                    {
                        "key": "title",
                        "value": {
                        "stringValue": "Free Online GUID Generator"
                        }
                    },
                ]
            }
        }
        ]
    }

```
</details>

It's not clear to me if the spec will allow both these options or only option 2, with this PR. Can someone clarify?

When mapping external complex objects to attribute values, requiring to convert them into the nested attributes format may be tricky.

2023-01-01 17:49 UTC, ronyis commented
It seems to me that [attribute limits](https://github.com/alanwest/opentelemetry-specification/blob/eb551bc9cf50d93463f20585686194d62887e044/specification/common/README.md#attribute-limits) definition has to be updated respectfully to the proposed changes.

The current definition states:
> * if it is a string, if it exceeds that limit (counting any character in it as 1), SDKs MUST truncate that value, so that its length is at most equal to the limit,
> * if it is an array of strings, then apply the above rule to each of the values separately,
> * otherwise a value MUST NOT be truncated;

So it should probably at least be updated to refer to maps and heterogeneous arrays as well.

2023-01-03 17:17 UTC, tigrannajaryan commented
> Consider the following 2 options -
> 
> Sample PageView Event - Option 1
> ```json
>     "log_record": {
>         "timeUnixNano":"1581452773000000789",
>         "attributes": [
>         {
>             "key": "event.domain",
>             "value": {
>             "stringValue": "browser"
>             }
>         },
>         {
>             "key": "event.name",
>             "value": {
>             "stringValue": "page_view"
>             }
>         },
> 
>         {
>             "key": "event.data",
>             "value": {
>             "mapValue": {
>                 "http.url": "https://www.guidgenerator.com/online-guid-generator.aspx",
>                 "referrer": "http://google.com",
>                 "type": 0,
>                 "title": "Free Online GUID Generator"
>             }
>             }
>         }
>         ]
>     }
> ```
> 
> Sample PageView Event - Option 2
> ```json
>     "log_record": {
>         "timeUnixNano":"1581452773000000789",
>         "attributes": [
>         {
>             "key": "event.domain",
>             "value": {
>             "stringValue": "browser"
>             }
>         },
>         {
>             "key": "event.name",
>             "value": {
>             "stringValue": "page_view"
>             }
>         },
> 
>         {
>             "key": "event.data",
>             "value": {
>                 "nestedAttributes": [
>                     {
>                         "key": "http.url",
>                         "value": {
>                         "stringValue": "https://www.guidgenerator.com/online-guid-generator.aspx"
>                         }
>                     },
>                     {
>                         "key": "http.url",
>                         "value": {
>                         "stringValue": "https://www.guidgenerator.com/online-guid-generator.aspx"
>                         }
>                     },
>                     {
>                         "key": "type",
>                         "value": {
>                         "intValue": "0"
>                         }
>                     },
>                     {
>                         "key": "title",
>                         "value": {
>                         "stringValue": "Free Online GUID Generator"
>                         }
>                     },
>                 ]
>             }
>         }
>         ]
>     }
> ```
> 
> It's not clear to me if the spec will allow both these options or only option 2, with this PR. Can someone clarify?
> 
> When mapping external complex objects to attribute values, requiring to convert them into the nested attributes format may be tricky.

@scheler Conceptually the data that you want to represent will be representable, i.e. the "attributes" field will allow having an attribute named "event.data", which can contain multiple sub-attributes named "http.url", "type", etc.

2023-01-03 20:29 UTC, scheler commented
> @scheler Conceptually the data that you want to represent will be representable, i.e. the "attributes" field will allow having an attribute named "event.data", which can contain multiple sub-attributes named "http.url", "type", etc

@tigrannajaryan my question is a little different. The current protobuf definitions allow only the second option, not the first one. If we require the value in a key/value map to be only of type `any`, then that does not allow option 1. If this understanding is correct, then the question is will this PR enable option 1 by modifying the protobuf definitions accordingly?

2023-01-04 18:59 UTC, scheler commented
> @tigrannajaryan my question is a little different. The current protobuf definitions allow only the second option, not the first one. If we require the value in a key/value map to be only of type `any`, then that does not allow option 1. If this understanding is correct, then the question is will this PR enable option 1 by modifying the protobuf definitions accordingly?

@MSNev I discussed this in the Log SIG today. Looks like only option 2 will be supported by the current wire format. I hope option 2 is acceptable for the RUM use-case.  It increases the payload size, but option 1 is much harder to achieve.

2023-01-10 13:38 UTC, tsloughter approved these changes

2023-01-18 14:20 UTC, tigrannajaryan commented
@open-telemetry/specs-approvers please review and comment.

2023-01-18 18:07 UTC, yurishkuro approved these changes

2023-02-08 18:54 UTC, scheler approved these changes

2023-02-08 18:54 UTC, MSNev approved these changes

2023-02-08 18:56 UTC, djaglowski approved these changes

2023-02-08 20:12 UTC, tigrannajaryan commented
@open-telemetry/specs-trace-approvers please review.

2023-02-09 05:40 UTC, Aneurysm9 commented on specification/common/README.md
> +  - A key/value map, where key is string and value is `any` value [since 1.15.0].
```suggestion
  - An array of `any` values [since 1.19.0].
  - A key/value map, where key is string and value is `any` value [since 1.19.0].
```

2023-02-09 05:40 UTC, Aneurysm9 commented on specification/common/README.md
> +  - A key/value map, where key is string and value is `any` value [since 1.15.0].
Does a key/value map need to have unique keys or are multiple entries with the same key allowed?

2023-02-09 05:40 UTC, Aneurysm9 commented on specification/common/README.md
> +  - A homogeneous array of values of primitive type.
```suggestion
```

Does this need to be retained since it is covered by an array of `any` values?

2023-02-09 13:13 UTC, jsuereth approved these changes
Overall LGTM.  I think there's still some ambiguity that could be clarified which @Aneurysm9 points out, but that can also be done in a follow up.

I.e. I think we consistently treat maps as never having duplicate keys, but the verbage describing this may not be locally apparent, or we may have caveat/conditioned it such that one could interpret it not applying to this change.

2023-02-09 13:13 UTC, jsuereth commented on specification/common/README.md
> +  - A homogeneous array of values of primitive type.
Another way to phrase this:

Do we need specification ensuring that the distinction between "array of primitive" + "array of any" is preserved such that we need this specification language?

2023-02-09 18:41 UTC, scheler commented on specification/common/README.md
> +  - A key/value map, where key is string and value is `any` value [since 1.15.0].
The [Attribute Collections](https://github.com/open-telemetry/opentelemetry-specification/tree/main/specification/common#attribute-collections) section below says the keys have to be unique.

2023-02-09 19:11 UTC, jack-berg commented
I don't love the idea of complex attributes, but also don't like the inconsistency that currently exists between OTLP, which does allow them, and the API / SDK, which do not. It puts OTLP receivers in an awkward position as they must decide whether to potentially jump through hoops to support complex attributes which are valid OTLP, despite OpenTelemetry SDKs being unable to produce such data. Adding support for complex attributes to API / SDK sends a clear signal that OTLP receivers need to support these.

My main concern with complex attributes is ambiguity on when they are appropriate to use. I'm worried about a future whether complex types are used "accidentally" when dot-delimited version would be perfectly suitable. Backends supporting OTLP will have to try to provide tools for selecting and filtering on bits of data nested in complex types, which will certainly be less ergonomic (and probably less efficient) than if the data were represented in the flat alternative.

Still, there are valid use cases for complex attribute types.

I'd approve this PR if there was language that advised when users / instrumentation authors should use complex types. Here's an attempt: "Complex attribute types (such as homogenous arrays, arrays of any, and maps) SHOULD only be used in situations where their use minimizes manipulation of the data’s original structure." Not sure that language is inclusive of all the situations where we'd want to use complex types.

2023-02-09 19:29 UTC, tigrannajaryan commented on specification/common/README.md
> +  - A homogeneous array of values of primitive type.
I retained it so that it is clear what has changed since 1.19.0. I will add another label on this line to make it clearer.

2023-02-09 19:34 UTC, tigrannajaryan commented
> I'd approve this PR if there was language that advised when users / instrumentation authors should use complex types. Here's an attempt: "Complex attribute types (such as homogenous arrays, arrays of any, and maps) SHOULD only be used in situations where their use minimizes manipulation of the data’s original structure." Not sure that language is inclusive of all the situations where we'd want to use complex types.

@jack-berg Added. PTAL.

2023-02-09 19:40 UTC, jack-berg approved these changes

2023-02-09 19:45 UTC, reyang commented on specification/common/README.md
> +  - A key/value map, where key is string and value is `any` value [since 1.19.0].
```suggestion
  - A non-recursive key/value map, where key is string and value is `any` value [since 1.19.0].
```

2023-02-09 19:47 UTC, reyang commented on specification/common/README.md
> +  - A key/value map, where key is string and value is `any` value [since 1.19.0].
Consider putting this restriction, or call out in the later section that if the container is recursive (e.g. self-referencing), what's the expected behavior (could be a. stop at certain depth b. detect recursion and stop c. undefined d. unspecified).

2023-02-09 19:48 UTC, reyang commented on specification/common/README.md
> +  - A key/value map, where key is string and value is `any` value [since 1.19.0].
(if recursion is not possible - e.g. the array cannot contain another array, please ignore my comment).

2023-02-09 19:48 UTC, reyang approved these changes
LGTM.

2023-02-09 22:31 UTC, Aneurysm9 approved these changes

2023-02-14 11:02 UTC, arminru commented on specification/trace/sdk_exporters/jaeger.md
> +Array and map values MUST be serialized to a JSON and recorded as a tag of string type
Should this also be specified in the https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/common/mapping-to-non-otlp.md section in general?

2023-02-14 15:05 UTC, tigrannajaryan commented on specification/trace/sdk_exporters/jaeger.md
> +Array and map values MUST be serialized to a JSON and recorded as a tag of string type
I have it in line 40-44 of README.md. Do you think it is better to move from README.md to mapping-to-non-otlp.md?

2023-02-14 15:07 UTC, tigrannajaryan commented on specification/common/README.md
> +  - A key/value map, where key is string and value is `any` value [since 1.19.0].
Arbitrary deep nesting is allowed. Self-referencing or any other forms of reference loops are not allowed. Essentially the rules are the same as in JSON.

Do you want these to be explicitly called?

2023-02-14 15:47 UTC, reyang commented on specification/common/README.md
> +  - A key/value map, where key is string and value is `any` value [since 1.19.0].
Yes I would vote for making it explicit with either one of the following approaches:
1. The implementation should try to serialize as much data as possible, if recursion is detected, a special value can be used (e.g. a special string "#ERROR").
2. The implementation should be conservative, any recursion should result in the entire key-value pair to be dropped, and the SDK should leverage internal error reporting if feasible.
3. The exact behavior is undefined; however the SDK MUST NOT cause any dead loop or stack overflow.

2023-02-21 13:53 UTC, fstab commented
Sorry for the late comment, but I'm afraid that supporting maps and heterogeneous arrays as attribute values will move OpenTelemetry metrics further away from Prometheus metrics. We made some good progress in the resent months on compatibility: Exponential histograms can be converted 1-to-1 to Prometheus native histograms and back. The Prometheus team decided to investigate support for dots in label names, and there are ongoing discussions on aligning the base units (seconds vs milliseconds).
I think we should work towards eliminating the last bits of incompatibility, and I fear supporting maps and heterogeneous arrays as attribute values is a step in the opposite direction.

2023-02-21 16:00 UTC, bboreham commented
Is this really aimed at metrics?  I tried to read through the history of this and related issues, and the bits that make sense are all aimed at tracing.

[My understanding: I have performed some operation and want to report it in a span. I have some structured data that I want to attach which will be meaningful to someone studying that span.]

I didn't see anything where maps and array values made sense as metric (or log) attribute values.

2023-02-21 17:18 UTC, fstab commented
Great question @bboreham. I had the impression this is for all signals, including metrics. But maybe I got it wrong?

2023-02-21 17:24 UTC, tsloughter commented
@fstab @bboreham this does include metrics.

2023-02-21 18:15 UTC, arminru commented on specification/trace/sdk_exporters/jaeger.md
> +Array and map values MUST be serialized to a JSON and recorded as a tag of string type
I see. I think linking to it from there would still make sense to its easier for both exporter authors and telemetry consumers to find.

2023-02-21 20:12 UTC, bboreham commented
Is there a motivating example where you would need a map as a metric attribute value?

2023-02-24 15:37 UTC, tigrannajaryan commented
This technically will also allow metric attributes to be also complex. However, I am not aware of any use case that would require this in practice.

We also call out that:
>Complex attribute types (such as homogenous arrays, arrays of any, and maps) SHOULD be
>used sparingly, in situations where their use minimizes manipulation of the data’s
>original structure.

If we feel this is not a strong enough warning against abusing complex attribute value we can emphasize this even more.

We could exclude metrics from this change, but for consistency and simplicity reasons I would prefer to avoid crafting exceptions in the spec.

2023-02-27 15:09 UTC, jpkrohling commented
> However, I am not aware of any use case that would require this in practice.

I'm uneasy about having such a controversial feature without a concrete use case requiring it.

> If we feel this is not a strong enough warning against abusing complex attribute value we can emphasize this even more.

Even if one OTLP payload is generated with nested maps, it needs to be handled by the whole toolchain, no matter the warnings we give here in the spec. This includes the Prometheus exporters that SDKs must include to be declared stable.

2023-02-27 16:38 UTC, Aneurysm9 commented
> Let's figure out if we can play nice with Prometheus. If we cannot, we should leave metrics out.

Should we even make this change if we're not going to consolidate the requirements for all signals?  I'm not sure I see how going from having logs be the outlier to having metrics be the outlier is advantageous in any way.

2023-02-27 16:55 UTC, yurishkuro commented
> I'm not sure I see how going from having logs be the outlier to having metrics be the outlier is advantageous in any way.

There is a demand for complex attributes for logs and traces. Why should those be blocked because of metrics?

2023-02-27 16:58 UTC, Oberon00 commented
Because of the cognitive complexity of having something called "attribute" behave differently depending on the signal type. And also because particular semantic conventions might have to be defined differently for metrics if they use nested values?

2023-02-27 18:09 UTC, tigrannajaryan commented
> > However, I am not aware of any use case that would require this in practice.
> 
> I'm uneasy about having such a controversial feature without a concrete use case requiring it.

To be clear, there are concrete uses cases for other signals, just not for metrics. See PR description.

2023-02-27 18:15 UTC, TylerHelmuth commented
Even though we only have concrete use cases for other signals at this type, I agree with the PR implementation that the feature should apply to all signals. It feels to me for metrics it means "we MUST figure out a way for this feature and prometheus to play nice" because we need this feature.

2023-02-27 18:56 UTC, slim-bean commented
As a maintainer of a system that would need to support this change (Loki), I really struggle with this idea, I would argue in the other direction that the actual protos should be made more restrictive to support only key=value pairs for metadata.

It would be nearly impossible to guarantee any performance or consistency between databases who have to support this level of complexity as we decide if we should flatten values (inconsistent user experience), store complex serialized types (poor performance and queryability), or outright reject payloads (poor user experience). 

I also believe this should be considered as it is named: attributes(metadata), not payload data.

The result here IMO is that this would make it harder for OTel to deliver on cross platform portability as each backend system will handle these complex data structures differently.

I also think this highlights a fundamental challenge in trying to make a standardized protocol that can be consistently and well supported across many vastly different backend systems: 

The more ambiguous(flexible) you make the protocol, the less you can deliver on that promise.

2023-02-27 19:11 UTC, jpkrohling commented
> To be clear, there are concrete uses cases for other signals, just not for metrics. See PR description.

Yes, sorry, that's what I meant.

> It feels to me for metrics it means "we MUST figure out a way for this feature and prometheus to play nice" because we need this feature.

That's a pretty good summary. If we can't find a way to make this work nicely with Prometheus, this feature might need to go back to the drawing board and perhaps be a per-signal feature, if it still makes sense.

2023-02-27 19:24 UTC, tigrannajaryan commented
> I would argue in the other direction that the actual protos should be made more restrictive to support only key=value pairs for metadata.

The protocol (OTLP) is declared stable and only allows complex attributes for all data types. We are not allowed to change this (support primitive values only) because that would be a breaking change and is prohibited by our stability guarantees.

The discussion in this PR is solely about allowing or not allowing the Otel API/SDK to use complex attributes for signals other than logs (for logs we already allow it). Regardless of the outcome of this PR there will be no changes to the OTLP specification.

2023-02-28 18:43 UTC, jpkrohling commented
@tigrannajaryan, would you please assist me in finding more information about the Logging API/SDK parts showing the resource attributes as accepting `any` values? I found only references to the data model, which is unfortunately already solidified in the spec without considering the larger open-source ecosystem.

2023-02-28 19:44 UTC, tigrannajaryan commented
> @tigrannajaryan, would you please assist me in finding more information about the Logging API/SDK parts showing the resource attributes as accepting `any` values? 

It is not about resource attributes. It is about LogRecord attributes. Here is the relevant part of the API: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/bridge-api.md#logrecord

2023-03-03 18:22 UTC, jmacd commented
As mentioned in #3186, I see this as useful functionality especially for adding depth and richness to span events.

I also am wary of adding complexity to users of existing tracing and metrics infrastructure (and those vendors) which treats span and metric attributes as keys in a database. We should not force users and vendors into such complexity, but that's not what's being asked for in this PR.

I would be glad to see OTel APIs add support for dictionary and hetergenous-list valued attributes; however, I would equally specify that they should used with caution, as the nested fields may not be searchable or used to define aggregates.  For example, I don't like the idea of using slice-valued attributes on metrics, and since metrics are always aggregated, there's nothing I can do except drop the attributes. However, this can be done safely in a way that preserves the aggregate, it would be as if those attributes never existed at the call site.

On the other hand, for a span record, I don't see a problem in allowing span attributes to take on structure, e.g. for payloads. Importantly, as a user I would not expect to aggregate spans by sub-fields in a payload object, but I would use those attributes when studying an exemplar. 

In other words, I support adding these fields to the APIs, I would expect users to apply caution, I expect SDKs to handle them safely even if it means dropping them, and I expect to see them in exemplars. I do not expect vendors to support nested queries over structured attribute values.

2023-03-04 00:31 UTC, yurishkuro commented on specification/common/README.md
> +be encoded as `1.5`, and an empty array of any type will be encoded as `[]`.
Does this example refer to JSON encoding of complex types? If so I would keep it in the previous paragraph.

2023-03-04 00:34 UTC, yurishkuro commented on specification/common/README.md
> +When exporting to protocols that do not natively support a particular non-string
Alternatively / in addition, we could provide more guidelines:
  * complex attributes SHOULD be use sparingly
  * complex attributes SHOULD NOT be used with metrics
  * backends may not index complex attributes

2023-03-08 15:27 UTC, Oberon00 commented
>  We should not force users and vendors into such complexity, but that's not what's being asked for in this PR.

If we want to avoid this, we need to take explicit steps to protect users and vendors (preferably right in this PR). For example, banning it from semantic conventions for now, or adding special requirements / caveats if we choose to allow them there.

2023-03-08 15:34 UTC, jack-berg commented
> We should not force users and vendors into such complexity, but that's not what's being asked for in this PR.

@Oberon00 / @jmacd I felt the same way, and proposed language constraining use of these attributes, which has been [incorporated](https://github.com/open-telemetry/opentelemetry-specification/pull/2888/files#diff-ca7e4af1ac8a5f1973909b827d94a0b718751c694bc51e2f603803ad2eb64a56R36-R38) into the PR:

> Complex attribute types (such as homogenous arrays, arrays of any, and maps) SHOULD be used sparingly, in situations where their use minimizes manipulation of the data’s original structure.

Do you have additional thoughts on usage advice?

2023-03-08 16:27 UTC, Oberon00 commented on specification/common/README.md
> +Complex attribute types (such as homogenous arrays, arrays of any, and maps) SHOULD be
```suggestion
Complex attribute types (such as non-homogenous arrays, arrays of any, and maps) SHOULD be
```

2023-03-10 15:35 UTC, jack-berg commented on specification/common/README.md
> +Complex attribute types (such as homogenous arrays, arrays of any, and maps) SHOULD be
Oops yeah definitely a typo.

2023-03-17 19:10 UTC, jpkrohling commented
> I would equally specify that they should used with caution, as the nested fields may not be searchable or used to define aggregates.

Do we need to have this as part of our initial stable version? I feel like this is the type of thing that ~no users would care about in practice while still costing a lot of engineering resources from the entire ecosystem to support properly. Not having this as part of the initial stable version would allow us to record requests from users for this specific feature.

2024-01-10 19:06 UTC, tigrannajaryan commented
I am reopening this PR. The topic came up again, while implementing the Log Bridge API in Go. The limitations on the common attribute value type and its difference from log data model's `any` value cause pains.

I think we need this change.

2024-01-10 19:07 UTC, tigrannajaryan commented
Formally we have enough approvals to merge this. If anyone is against merging please bring good (especially new) arguments.

2024-01-10 19:33 UTC, tigrannajaryan commented
Rebased to resolve conflicts. No content changes so I am keeping existing approvals.

2024-01-10 19:42 UTC, tigrannajaryan commented on specification/common/README.md
> +When exporting to protocols that do not natively support a particular non-string
>complex attributes SHOULD be use sparingly
>complex attributes SHOULD NOT be used with metrics

Modified the text to include this.

>how they should be exporting nested maps to

Added in PR description that we need a follow-up PR to do this.

2024-01-10 19:42 UTC, tigrannajaryan commented on specification/common/README.md
> +be encoded as `1.5`, and an empty array of any type will be encoded as `[]`.
Yes, it is about JSON. Merged this with the previous paragraph.

2024-01-10 19:43 UTC, tigrannajaryan commented on specification/trace/sdk_exporters/jaeger.md
> +Array and map values MUST be serialized to a JSON and recorded as a tag of string type
Added a note in PR description to do a follow up PR that addresses it.

2024-01-10 19:44 UTC, tigrannajaryan commented on specification/common/README.md
> +Complex attribute types (such as homogenous arrays, arrays of any, and maps) SHOULD be
Fixed.

2024-01-10 19:50 UTC, tigrannajaryan commented on specification/common/README.md
> +  - A key/value map, where key is string and value is `any` value [since 1.19.0].
Added a note that reference loops are not allowed.

2024-01-10 22:55 UTC, bogdandrutu commented on specification/common/README.md
> +- The attribute value can be of `any` type, where any is defined as one of the following:
No equivalent of `null` correct? Do you want to explicitly call that?

2024-01-10 22:55 UTC, bogdandrutu commented on specification/common/README.md
> +- SHOULD NOT be used with metrics.
Do you think MUST NOT is better? If it is SHOULD may mean that metrics still has to support it.

2024-01-11 09:04 UTC, fstab commented on specification/common/README.md
> +- SHOULD NOT be used with metrics.
So, should JSON serialization of attributes it still be implemented in the Prometheus exporter? Asking because there's an open issue for that in the Java SDK https://github.com/open-telemetry/opentelemetry-java/issues/5987

2024-01-11 09:15 UTC, fstab commented on specification/common/README.md
> +- SHOULD NOT be used with metrics.
In terms of Prometheus compatibility I would love to see "MUST NOT" for metrics here.  If we leave it as "SHOULD NOT" we have yet another OpenTelemetry metrics feature that's not supported by Prometheus, and this will drive the communities further apart. So if there's any chance to avoid this let's do it.

2024-01-11 11:26 UTC, pellared commented on specification/common/README.md
> +    loops is disallowed. [since 1.29.0].
```suggestion
    cycle is disallowed. [since 1.29.0].
```

Loop is a special case of a cycle in topology  when end point returns to the start point.
I think NO reference cycle is allowed.

2024-01-11 11:26 UTC, pellared commented on specification/common/README.md
> +    loops is disallowed. [since 1.29.0].
I am not sure if will be possible to disallow it in all languages (e.g. Python).

Maybe we should say something

```suggestion
    cycle is MUST NOT be supported. [since 1.29.0].
```

Feel free to resolve the comment if you feel confident that the current form is OK.

2024-01-11 11:26 UTC, pellared commented on specification/common/README.md
> +- SHOULD NOT be used with metrics.
Are these are only guidelines for the users (consumers)? If so then I think it will be good to call it out explicitly that these are usage guidelines. Also I do not think it we should use normative wording as we "do not control the user".

2024-01-11 11:26 UTC, pellared commented on spec-compliance-matrix.md
> +| Non-homogeneous arrays and maps (including nested) for attribute values                                                                     |          |    |      |    |        |      |        |
Should we also add the same line to Logs and Traces?

2024-01-11 11:26 UTC, pellared commented on spec-compliance-matrix.md
> +| Non-homogeneous arrays and maps (including nested)                                                                                                                     |          |    |      |     |
Should it be?

```suggestion
| Non-homogeneous arrays and maps (including nested) for attribute values                                                                                                             |          |    |      |     |        |      |        |     |      |     |      |       |
```

2024-01-11 12:43 UTC, joe-elliott commented
This PR was marked stale and closed b/c there is no consensus and very limited use case. The value to support this does not exist for the complexity it introduces.

2024-01-11 15:03 UTC, pellared commented on specification/common/README.md
> +  - A key/value map, where key is string and value is `any` value. Any form of reference
Should we add some limit on the value depth?

2024-01-11 15:47 UTC, tigrannajaryan commented on specification/common/README.md
> +    loops is disallowed. [since 1.29.0].
I am not sure we need to specify where exactly (which place in code) this check happens. We only describe a valid data model here. How you enforce that data model is a particular SDK's design choice.

2024-01-11 15:50 UTC, tigrannajaryan commented on specification/common/README.md
> +- SHOULD NOT be used with metrics.
This is for producers and designers of semantic conventions. I am not sure how this can be interpreted to be guidelines for consumers. Consumers don't choose what attribute types to use, they consume what they receive.

>Also I do not think it we should use normative wording as we "do not control the user".

We do control Otel semantic conventions and I think we are in the position to make a strong recommendation to producers, even the ones we don't control.

2024-01-11 16:27 UTC, pellared commented on specification/common/README.md
> +    loops is disallowed. [since 1.29.0].
>  We only describe a valid data model here. How you enforce that data model is a particular SDK's design choice.

I totally agree but the current way it is worded suggests that it should be impossible to pass ("is disallowed") such attributes. This is why a propose to change the wording to "supported". This section does not says anything about the SDK so it can be interpreted that even the API disallows. Also I do not know how to interpret what "disallowed" means from programming perspective.

2024-01-11 16:30 UTC, pellared commented on specification/common/README.md
> +- SHOULD NOT be used with metrics.
Just for clarification: By consumers I had in mind "users of the API" 😉 Feel free to resolve the comment.

2024-01-11 16:31 UTC, pellared commented on spec-compliance-matrix.md
> +| Non-homogeneous arrays and maps (including nested) for attribute values                                                                     |          |    |      |    |        |      |        |
> Implementations of logs are already supposed to support it.

But they do not 😉

2024-01-11 16:38 UTC, jack-berg commented on specification/common/README.md
> +- SHOULD NOT be used with metrics.
I think part of the point of this update is to allow for SDKs to have a generalized Attributes representation to be used in all places where attributes appear in the API / SDK. This means you don't have to have specialized types to accommodate the (currently) looser restrictions on log attribute which support AnyValue. One attributes type can be used for resources, spans, span events, span links, metrics, logs. 

What would it mean to say "MUST NOT be used with metrics"? 

If this is advising the API / SDK author to _not_ allow complex types for metrics, then I would say "MUST NOT" defeats the point of this PR. 

Perhaps this would be telling API users that they "MUST NOT" record complex attribute types with metrics. If this is the case, then we should clarify for maintainers. And we should also define a standard string serialization for complex types because someone is going to break the rules. But also, a string serialization makes sense regardless because exporters will not have ubiquitous support for complex types. JSON serialization makes sense and should be easy to describe / implement.

2024-01-11 16:42 UTC, jack-berg commented on specification/common/README.md
> +- SHOULD NOT be used with metrics.
If this is guidelines for semantic conventions, we should move it to the semantic conventions repo. We recently [moved attribute naming docs](https://github.com/open-telemetry/semantic-conventions/pull/493) from the spec to semantic conventions. It doesn't make sense to have semantic convention advice interspersed in a document describing attributes for SDK implementers.

2024-01-11 16:55 UTC, tigrannajaryan commented
> LGTM, I still have concerns about this related to metrics and I don't love the fact that we have one thing in the spec that applies to everything except for one signal, but I can live with that.

@jpkrohling I agree, I don't love that either. However, currently we have a situation with one signal (logs) being an exception, so the status quo is not really much better.

2024-01-11 16:55 UTC, tigrannajaryan commented on specification/common/README.md
> +- SHOULD NOT be used with metrics.
I am fine with completely prohibiting complex attributes for metrics.

2024-01-11 17:03 UTC, bogdandrutu commented on specification/common/README.md
> +- SHOULD NOT be used with metrics.
Again, I am not suggesting one or the other (to support or not). I am saying that IF we support complex types (which means if the words there are not MUST NOT) then a serialization for Prometheus exporter MUST be present.

2024-01-11 17:18 UTC, tigrannajaryan commented on spec-compliance-matrix.md
> +| Non-homogeneous arrays and maps (including nested)                                                                                                                     |          |    |      |     |
Fixed, thanks.

2024-01-11 17:20 UTC, tigrannajaryan commented on specification/common/README.md
> +When exporting to protocols that do not natively support a particular non-string
Please take a look at the latest version. I used a stronger "MUST NOT" wording for metrics.

2024-01-11 17:33 UTC, tigrannajaryan commented on spec-compliance-matrix.md
> +| Non-homogeneous arrays and maps (including nested) for attribute values                                                                     |          |    |      |    |        |      |        |
I think it is best to treat the implementation divergence from the spec as a bug instead of adding additional items to the compliance matrix when they don't match the spec.

If we need to clarify the data model in the spec let's do it and then we can file bugs against implementations to fix the behavior to match the spec. 

We normally add new items to the matrix only when new functionality is added to the spec, which is not the case for logs here. There is no spec change from logs perspective.

What do you think?

2024-01-11 17:35 UTC, tigrannajaryan commented on specification/common/README.md
> +  - A key/value map, where key is string and value is `any` value. Any form of reference
Good question. I am not sure about it.

There is already a limitation for the size of the value (AttributeValueLengthLimit). It is not well-specified what it means for complex attributes (e.g. even for homogeneous arrays which are already allowed).

Perhaps instead of adding a new limit we clarify what the value length limit means for complex attributes and we consider it sufficient and don't need depth limit?

2024-01-11 17:48 UTC, pellared commented on spec-compliance-matrix.md
> +| Non-homogeneous arrays and maps (including nested) for attribute values                                                                     |          |    |      |    |        |      |        |
> I think it is best to treat the implementation divergence from the spec as a bug

It may be considered also as a "bug" in the specification taking into consideration that everyone implemented it differently.

> If we need to clarify the data model in the spec let's do it

I agree. We can follow-up here: https://github.com/open-telemetry/opentelemetry-specification/pull/3816

> We normally add new items to the matrix only when new functionality is added to the spec, which is not the case for logs here. There is no spec change from logs perspective.

I do not think it is a regular case as none implementation actually did it. I think the Logs Data Model might need retrospection.

2024-01-11 17:49 UTC, pellared commented on specification/common/README.md
> +  - A key/value map, where key is string and value is `any` value. Any form of reference
> Perhaps instead of adding a new limit we clarify what the value length limit means for complex attributes and we consider it sufficient and don't need depth limit?

Makes sense to me.

2024-01-11 18:09 UTC, tigrannajaryan commented on specification/common/README.md
> +- SHOULD NOT be used with metrics.
> Just for clarification: By consumers I had in mind "users of the API" 😉 Feel free to resolve the comment.

Ah, I misunderstood what you meant :-) Good question in that case.

I think we can do as @jack-berg suggests and move the usage recommendation to semconv and keep the strict API requirement here.

2024-01-11 18:17 UTC, tigrannajaryan commented on spec-compliance-matrix.md
> +| Non-homogeneous arrays and maps (including nested) for attribute values                                                                     |          |    |      |    |        |      |        |
Added a line for trace for now, since that is definitely needed. Let me think about logs.

2024-01-11 19:30 UTC, tigrannajaryan commented on specification/common/README.md
> +  - A key/value map, where key is string and value is `any` value. Any form of reference
https://github.com/open-telemetry/opentelemetry-specification/issues/3818

2024-01-11 19:42 UTC, pellared commented on specification/common/README.md
> +  - A key/value map, where key is string and value is `any` value. Any form of reference
Feel free to resolve.

2024-01-11 23:51 UTC, MrAlias requested changes
If the goal of this PR is to add functionality for log attributes it seems that ship has sailed. The logs signal is defined using `<string, any>` attributes. Changing that would be a breaking change.

Additionally, accepting this will also break existing signal telemetry expectations. I do not think this is viable as is.

2024-01-11 23:51 UTC, MrAlias commented on specification/common/README.md
> +Complex attribute types (such as arrays and maps) SHOULD be used sparingly. They may
This normative statement is meaningless. Users define attributes not OTel SDKs.

2024-01-11 23:51 UTC, MrAlias commented on specification/common/README.md
> +The following value types MUST NOT be used as metric attribute values:
This is not viable. Stable implementations have already been released for this signal. Those implementations already accept attributes. Adding this statement here is hiding a breaking change.

2024-01-12 00:22 UTC, tigrannajaryan commented on specification/common/README.md
> +Complex attribute types (such as arrays and maps) SHOULD be used sparingly. They may
This is for semantic convention authors. Will be moved to semconv repo.

2024-01-12 00:24 UTC, tigrannajaryan commented on specification/common/README.md
> +The following value types MUST NOT be used as metric attribute values:
@jack-berg actually [implemented](https://github.com/open-telemetry/opentelemetry-specification/pull/2888#issuecomment-1332837092) this and found it to be possible in non-breaking manner for Java.

Do you think it is impossible to do for Go in a non-breaking way?

2024-01-12 00:26 UTC, tigrannajaryan commented
> If the goal of this PR is to add functionality for log attributes it seems that ship has sailed. The logs signal is defined using `<string, any>` attributes. Changing that would be a breaking change.

@MrAlias you probably misunderstood the change. This is not to add functionality for log attributes. Logs [already require that](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/data-model.md#field-attributes). This changes nothing for logs.

This change allows Resources and Spans to use complex attribute values.

2024-01-12 01:02 UTC, MrAlias commented
> > If the goal of this PR is to add functionality for log attributes it seems that ship has sailed. The logs signal is defined using `<string, any>` attributes. Changing that would be a breaking change.
> 
> @MrAlias you probably misunderstood the change. This is not to add functionality for log attributes. Logs [already require that](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/data-model.md#field-attributes). This changes nothing for logs.
> 
> This change allows Resources and Spans to use complex attribute values.

I see. You are correct then, I don't think I fully understand the future plans for logs not being affected.

2024-01-12 01:05 UTC, MrAlias commented
I still think that extending the structure being sent down an telemetry pipeline is going to be breaking changes and likely cause incompatibilities and/or performance issues with telemetry storage systems.

I don't think we are going to be able to partition how attributes are used per signal to try and save this. Attributes have always been a common term across signals and resources and to try and split them at this point is going to be difficult at best but likely require breaking changes at worst.

2024-01-12 01:06 UTC, MrAlias commented on specification/common/README.md
> +Complex attribute types (such as arrays and maps) SHOULD be used sparingly. They may
> This is for semantic convention authors. Will be moved to semconv repo.

Makes sense. Can we track that with an issue if this merges?

2024-01-12 05:12 UTC, tigrannajaryan commented
> I still think that extending the structure being sent down an telemetry pipeline is going to be breaking changes and likely cause incompatibilities and/or performance issues with telemetry storage systems.

@MrAlias one more thing to consider: it was _always_ possible (and I would argue - valid too) to send signals with complex attributes via OTLP. OTLP explicitly allows this. It was just not possible/legal to do this using Otel API. But Otel API is not the only way to generate OTLP data, so anyone telemetry storage receiving OTLP must be prepared to receive such data.

>I don't think we are going to be able to partition how attributes are used per signal to try and save this. Attributes have always been a common term across signals and resources and to try and split them at this point is going to be difficult at best but likely require breaking changes at worst.

I am a bit confused by this comment. They _are_ already partitioned (before this PR). Logs already use a different definition of attributes than the rest. This difference is not new, it has been known for a very long time, discussed at length in many calls. That difference is one of the reasons why this PR exists in the first place: the PR was originally an attempt to make sure attributes are consistent across all signals. In the current form this PR makes an exception for metric attributes (only simple attributes are allowed), everything else according to this PR is now consistently using the same more complicated attribute definition as log have been using since day one.

2024-01-12 05:18 UTC, tigrannajaryan commented on specification/common/README.md
> +The following value types MUST NOT be used as metric attribute values:
OK, that is very important. If we think this is impossible to implement in non-braking way then it is a blocker, we can't accept the PR.

I would like to take a closer look at Go implementation and see if we can find a non-breaking way to apply this change.

Since this came I would also want to be more careful and check some other languages (strongly typed/compiled languages are most likely to be impacted).

2024-01-12 15:36 UTC, MrAlias commented
> In the current form this PR makes an exception for metric attributes (only simple attributes are allowed), everything else according to this PR is now consistently using the same more complicated attribute definition as logs have been using since day one.

Right, this is where the problem arises though. Previously traces, metrics, and resources signals shared this definition of attributes. Now trying say that the definition is going to be different for one of those things but not the others will be unimplementable without changing the definition used in the implementation. That type of change will break API stability.

2024-01-12 15:37 UTC, MrAlias commented
> @MrAlias one more thing to consider: it was _always_ possible (and I would argue - valid too) to send signals with complex attributes via OTLP. OTLP explicitly allows this. It was just not possible/legal to do this using Otel API. But Otel API is not the only way to generate OTLP data, so anyone telemetry storage receiving OTLP must be prepared to receive such data.

Gotcha :+1:

2024-01-12 15:38 UTC, tigrannajaryan commented on spec-compliance-matrix.md
> +| Non-homogeneous arrays and maps (including nested) for attribute values                                                                     |          |    |      |    |        |      |        |
Added a line for logs too, given past confusion it is best to track it explicitly.

2024-01-12 18:15 UTC, scheler approved these changes

2024-01-12 20:41 UTC, tigrannajaryan commented
Everyone: @MrAlias and I will be looking at feasibility of this for Go. We won't merge until we are confident about it.

I am going to ask some other language maintainers to check if this is implementable in non-breaking way.

2024-01-15 08:12 UTC, jpkrohling commented
Hearing from an implementor of the spec, I got the following concern: current implementations relying on the spec were promised that common attributes were "Stable, Feature-freeze". Currently, v1.29.0 of the spec reads:

> The attribute value is either:
> A primitive type: string, boolean, double precision floating point (IEEE 754-1985) or signed 64 bit integer.
> An array of primitive type values. The array MUST be homogeneous, i.e., it MUST NOT contain values of different types.

Changing this means that implementations will suddenly not be compliant with the published spec. Shouldn't the status of this feature then be changed to reflect that?

2024-01-15 13:52 UTC, slim-bean commented
I find this change deeply troubling at its core as I believe it fundamentally undermines the most compelling reason we see folks looking to adopt OTel: vendor neutrality.

Most, if not all of the arguments in support of this change are variants of attempting to customize the protocol for a specific/proprietary source or destination of telemetry data.

Attempts to point this out are met with what I would consider a fair bit of hand waving that at best shows a lack of understanding and empathy to the folks who have to build databases to support Open Telemetry, or worse, are complicit with what looks like attempts for vendors to build proprietary features on top of an open protocol which will be intentionally difficult for other databases to implement giving them a competitive advantage.

I do not think language like “should” or “should not” belongs here, the spec should be clear and rigid. 

Some of the arguments such as supporting payloads as attributes is allowing (and encouraging?) custom protocol implementations on OTLP, which will become tedious or impossible for all vendors to implement. Others such as transmitting complex objects to allow for UI object structure in the payload should be fairly obvious to really only benefit one vendor.

We are talking about metadata here, it should be intentionally forced to be simple in the spec such that the varying types of database vendors can have some hope of providing what we see our customers hold as the most valuable promise being made by OTel: vendor neutrality.

Merging this PR just feels like we are dooming ourselves to a world of compatibility matrices and frustrated users who are trying to switch vendors only to discover that their favorite feature isn’t implemented by any other vendor, or perhaps it is in a much different way with significantly different performance characteristics.

A specification that is meant to level a playing field cannot be a specification that supports infinite complexity.

2024-01-15 17:40 UTC, yurishkuro commented
@slim-bean it would be helpful if you point to specific technical difficulties. As a maintainer of Jaeger, whose backends are much simpler in comparison with commercial backends, I don't see a particular issue with this proposal. For instance, the current spec already allows arrays as attributes, and Jaeger does not support arrays in the backend schemas, so there would be some encoding applied (e.g. JSON) and the storage would treat arrays as a blob. I would do the same with more complex nested structures. There would be no search over these attributes, but search is not always required.

Philosophically, I don't agree with your compatibility matrix argument. The goal of OpenTelemetry is to _capture telemetry in the most effective and semantics-preserving way_, not to provide a level playing field for backend implementations. Vendor neutrality does not mean that you can switch your vendor and keep exactly the same capabilities, what would be the point of competition then. Compatibility matrix is always implicitly there, but it's not OpenTelemetry's concern. If a user has semantically structured telemetry data they want to capture, it would be much worse outcome if OTel would force the user to perform some encoding of that data (like flattening or JSON) just because _some_ backends do not support it. It would be punishing the users. Backends that don't support nesting can do the encoding themselves, and yes, may be less competitive than the more advanced backends (again, assuming that aspect is important to a user).

2024-01-15 20:49 UTC, tigrannajaryan commented
>I find this change deeply troubling at its core as I believe it fundamentally undermines the most compelling reason we see folks looking to adopt OTel: vendor neutrality.

>...or worse, are complicit with what looks like attempts for vendors to build proprietary features on top of an open protocol which will be intentionally difficult for other databases to implement giving them a competitive advantage.

>... should be fairly obvious to really only benefit one vendor.

@slim-bean you seem to be alluding to some malicious intent here. I am the author of this PR. Are you are accusing me of a dishonest behavior? What "one vendor" are you talking about?

2024-01-15 21:46 UTC, slim-bean commented
> @slim-bean you seem to be alluding to some malicious intent here. I am the author of this PR. Are you are accusing me of a dishonest behavior? 

There is significant frustration in my comment as I find myself bewildered as I watch this change progress despite the objections. Leading me to believe there is a lack of appreciation for the affects this has on telemetry databases, or that the goal for those who seek this change is to provide difficult to replicate product differentiation via complex protocol implementations.

I believe your intentions here to be good and that you are acting on behalf of requests made to the project, I'm questioning that the use cases truly benefit what I thought was a goal of open telemetry: portability between vendors.

However @yurishkuro has me questioning if I have a misunderstanding here?

But I do not think complexity like this belongs in metadata, imagine if HTTP headers were allowed by spec to support infinitely complex objects? Do we think that would have improved the the competitive landscape of HTTP servers or destroyed it?

2024-01-15 22:09 UTC, slim-bean commented
> They do - https://httpwg.org/specs/rfc8941.html (although not recursive).

I'm not sure that referencing an RFC submitted by employees at Fastly and Varnish Cache project more than 20 years after HTTP was created proves your point or mine?

This is also [still a Proposed Standard](https://www.rfc-editor.org/info/rfc8941), and has not made the status of `Draft Standard` or `Internet Standard`

2024-01-15 22:36 UTC, tigrannajaryan commented
>...that the goal for those who seek this change is to provide difficult to replicate product differentiation via complex protocol implementations.

@slim-bean Please consider commenting in a way that cannot be misconstrued as an insinuation of wrongdoing. Your words that I quoted can be read that way.

>Leading me to believe there is a lack of appreciation for the affects this has on telemetry databases.

This PR is open for discussion and as its author I appreciate feedback. If you have specific arguments that show how and why this implementation adds complexity please comment, particularly please explain how you think this affects telemetry databases.

Be aware that there is no expectation in this PR that backends must natively support complex attributes such as nested maps. There is a precedence in this specification that explains how backends that don't support a particular shape of data should treat such data, [see here](https://github.com/open-telemetry/opentelemetry-specification/tree/main/specification/common#attribute). The recommendation is that such values are represented as JSON strings and that recommendation remains unchanged.

Be also aware that if the backend receives OTLP it is already expected to deal with such complex data, since it is [already permitted by OTLP](https://github.com/open-telemetry/opentelemetry-proto/blob/34d29fe5ad4689b5db0259d3750de2bfa195bc85/opentelemetry/proto/common/v1/common.proto#L28). The fact that this specification does not allow such data in the API does not absolve the backends from dealing with it upon receiving since there can be other sources of telemetry other than OpenTelemetry SDKs that are governed by this specification.

If on the other hand the backend in question does not receive OTLP and instead requires a proprietary protocol then the conversion from OTLP to the proprietary protocol happens in an exporter (likely in a Collector exporter), where it is not hard to perform this translation to JSON string. I do not see where the complexity here is. If you do, please explain.

If, however, by "complexity" you mean it is hard for the backends to support complex data types natively then I can understand that. However as @yurishkuro correctly points OpenTelemetry is not supposed to be a lowest common denominator, so that is not a good enough sole argument against adding any particular feature.

2024-01-15 23:56 UTC, slim-bean commented
Thank you both @tigrannajaryan and @yurishkuro for responding and engaging in a discussion. I do apologize for anything that felt accusatory, I believe everyone is acting in good faith.

I will need a day or two to build a proper response with much more specifics/concrete examples.  I also wonder if there is a synchronous avenue to have this conversation?

2024-01-16 12:02 UTC, pellared commented
> Thank you both @tigrannajaryan and @yurishkuro for responding and engaging in a discussion. I do apologize for anything that felt accusatory, I believe everyone is acting in good faith.
> 
> I will need a day or two to build a proper response with much more specifics/concrete examples. I also wonder if there is a synchronous avenue to have this conversation?

Specification SIG meeting. See https://github.com/open-telemetry/community?tab=readme-ov-file#specification-sigs. We are meeting today.

2024-01-17 00:55 UTC, jmacd commented
This topic was debated in today's Specification SIG meeting, and was left with a few notes that might help alleviate some of the concerns.  Briefly,

1. Restrictions we could place on Metrics SDKs
2. Collector components we could require to be implemented as prerequisites
3. Developments around telemetry schema

Before I start, I find myself mainly agreeing with those who argue in favor of this PR. However, understand the difficult position this places metric databases in, which brings me to the first suggestion.

## Proposed metric SDK restrictions

Metrics databases cannot simply ignore attribute values, for doing so can easily break the [single-writer property](https://opentelemetry.io/docs/specs/otel/metrics/data-model/#single-writer). When multiple timeseries are distinguished only by a structured attribute value, as we might get from list-valued and map-valued `AnyValue` elements. Therefore, is not good enough to tell users to ignore attributes having structured values.

However, the SDK is in a position where removing attribute values is still a relatively inexpensive operation. As soon as the data passes to another stage in a collection pipeline, the problem becomes harder, and this is why metrics database implementors are rightly concerned. At the same time, the OpenTelemetry metrics data model supports exemplars, which are a safe place to store high-cardinality attribute values. I do not see a problem with structured attributes if they are confined to exemplars. Metrics SDKs could be required to aggregate away any structured attribute values, while leaving those attributes available for use in exemplars.

## Collector components that would help this issue along

Even if OTel SDKs are restricted from producing aggregates having structured attributes, this would not prevent an arbitrary sender from doing so. The protocol definition makes this possible, but we have no simplke way to remove those attributes. Unless you know that a timeseries is unique, removing an attribute can violate the single-writer property. In general, an aggregation step is requirede to remove attributes safely and correctly, but this is not a feature we offer as part of the OpenTelemetry pipeline--there is no collector component that does this today.

A telemetry database with only support for flat attributes is right to want to remove those attributes from indexing. The process they would be required to implement is one we as a project have not demonstrated. Perhaps it would help the parties who are opposed to this change if there were a standard component that could safely and correctly remove structured attributes from an aggregated metrics stream. Those parties would at least be able to run the OpenTelemetry component for safe attribute removal in their pipelines to avoid having to index structured attributes.

## Telemetry schema developments

One of the reasons database implementors are opposed to these changes is that they will require some kind of separate apparatus to identify the kind of structured telemetry being represented in particular fields. In my opinion, these concerns are largely addressed when telemetry carries descriptive information about the fields used within. 

One of the properties that could be usefully encoded in a schema has been discussed in the past ([for example](https://github.com/open-telemetry/opentelemetry-specification/issues/2775)), concerning whether an attribute can be classified as "descriptive". Relating to the discussion above, when an attribute is merely descriptive, then it is always safe to remove the attribute by simple erasure, meaning it can be removed without breaking the single-writer property, without an aggregation step. Perhaps, if we required schema support before introducing structured attribute values, we could include new annotations to help databases be successful when processing telemetry using these new features.

2024-01-17 09:12 UTC, jpkrohling requested changes
Following our insightful discussion during yesterday's Spec SIG meeting, I've been reflecting on the points raised and would like to reconsider my previous approval on the PR. I believe it would be beneficial to shift my stance to "request changes". Here's why:

- The current logging data model's support for map<string, any> appears to be limited in language compatibility, with JavaScript being a notable exception. @jack-berg's observation that Java lacks this feature due to limited demand prompts me to question the necessity of this specification at a broader level. Are we truly addressing a widespread user need here?
- @yurishkuro's proposal of storing arrays and complex types as blobs raises concerns about the expected user experience. Storing it but limiting the ability to search within these values seems counterintuitive. Wouldn't it be more user-friendly to instruct users to serialize data as JSON at the instrumentation level and perform string queries? Adding some API sugar to support this could lead to a more intuitive user experience.
- I'm keen to understand how this feature operates in a real-world scenario. It would be immensely helpful if we could demonstrate its application with at least one open-source tracing and logging databases, showcasing its practical utility. This step, although not typical for us, could significantly clarify its benefits and applicability for users like myself.
- The designation of this feature as not for metrics introduces a deviation in our project's unified approach to telemetry signals. If this is a first in our project, I'd cautiously suggest reevaluating this division to maintain a consistent and streamlined user experience. OTel's strength lies in its coherent mental model across different types of telemetry, and it's crucial to preserve this advantage.
- While the PR aims to align with OTLP, which supports the discussed feature, I propose a reconsideration. Given the limited support across various languages, it might be prudent in the long run to simplify attributes rather than expand them. We can let OTLP live as it is, but let's not increase the surface damage.

2024-01-17 14:25 UTC, tigrannajaryan commented
>However, the SDK is in a position where removing attribute values is still a relatively inexpensive operation.

@jmacd We can just make the API call fail immediately. This seems simpler to implement. Any reason not to do this?

>Perhaps it would help the parties who are opposed to this change if there were a standard component that could safely and correctly remove structured attributes from an aggregated metrics stream.

An alternate approach is to have a processor that converts complex attributes to strings according to rules we have for non-OTLP destinations - to JSON string.

2024-01-17 14:41 UTC, tigrannajaryan commented
>The current logging data model's support for map<string, any> appears to be limited in language compatibility, with JavaScript being a notable exception. @jack-berg's observation that Java lacks this feature due to limited demand prompts me to question the necessity of this specification at a broader level. Are we truly addressing a widespread user need here?

@jpkrohling are you asking about the need to support complex log attributes in the API or generally about the need to support such attributes by Otel at all?

2024-01-17 15:06 UTC, pellared commented on specification/common/README.md
> +- Key/value maps.
Can you add a rationale what are the reasons to have these constraints?

2024-01-17 15:10 UTC, pellared commented on specification/common/README.md
> +The following value types MUST NOT be used as metric attribute values:
I think the alternative could be to describe in metrics SDK specification how the SDK should/must handle such cases (when these types of attributes are passed).

2024-01-17 18:03 UTC, tigrannajaryan commented
All, I brought up this PR in the TC meeting today in order to clarify the following: should very old PRs like this (more than a year old) that get re-open retain existing approvals or they should be dismissed? The TC agreed that the approvals need to be dismissed, which I am going to do now.

2024-01-17 20:09 UTC, tigrannajaryan commented
>I'm keen to understand how this feature operates in a real-world scenario. It would be immensely helpful if we could demonstrate its application with at least one open-source tracing and logging databases, showcasing its practical utility. This step, although not typical for us, could significantly clarify its benefits and applicability for users like myself.

@jpkrohling Here is an example from Elastic's demo website readily available:
https://demo.elastic.co/app/discover#/doc/kibana-event-log-data-view/.ds-.kibana-event-log-ds-2024.01.17-000010?id=OKvwGI0BpiGkpO9Rapug (you may need to click the link twice to make it open the log record I am referring to directly).

See for example the "kibana.saved_objects" field. See how it is a map of arrays of strings:

![image](https://github.com/open-telemetry/opentelemetry-specification/assets/4194920/ff8e3fba-1172-41be-b9ff-dc24b4b8b3a1)

Another example to look at is this: https://demo.elastic.co/app/discover#/doc/filebeat-*/.ds-logs-apm.error-default-2023.12.22-000014?id=n7DyGI0BGTVq0q2e7pZw

See _source and how it contains an "error" which is a map of array of map of array of maps of primitives or maps.
![image](https://github.com/open-telemetry/opentelemetry-specification/assets/4194920/f01579cf-883d-401b-9099-0ad250f29cd5)

Complex, nested data happens all the time in the logging world.

2024-01-17 20:20 UTC, tigrannajaryan commented
>@yurishkuro's proposal of storing arrays and complex types as blobs raises concerns about the expected user experience. Storing it but limiting the ability to search within these values seems counterintuitive. 

@jpkrohling this is not a new proposal. It is already part of the spec, written in a Stable document. See here: https://github.com/open-telemetry/opentelemetry-specification/tree/main/specification/common#attribute

I am quoting the spec:

```
For protocols that do not natively support non-string values, non-string values SHOULD be 
represented as JSON-encoded strings.
```

2024-01-17 21:03 UTC, MSNev commented on spec-compliance-matrix.md
> +| Non-homogeneous arrays and maps (including nested) for attribute values| | | | |    |      |        |     |      |     |      |       |
JavaScript has this as experimental
https://github.com/open-telemetry/opentelemetry-js/blob/bf8714edcba8a2384db857696a1608215548d182/experimental/packages/api-logs/src/types/LogRecord.ts#L20-L22

2024-01-17 21:06 UTC, MSNev approved these changes

2024-01-17 21:21 UTC, jack-berg commented
I support this change in its current form, but prefer a slightly different option:

- In my view, this issue accomplishes:
  - Ensuring that we don't artificially limit what data can be recorded. Note that while attributes on metrics are best thought of as metadata, attributes on logs and spans certainly can be argued to constitute the data itself.
  - Allow a uniform attributes representation to be used in all places where attributes appear in the API / SDK.
- Adding support for complex types while carving out an exception for metrics is undesirable.
  - Either we have to have a metrics-specific attributes representation which prevents recording complex types. Or, the metrics SDK implementation has to validate that attributes do not contain complex types on the record hotpath, which incurs  unnecessary overhead. Can also check on the collect path as well, but that yields weird behavior.
- Why don't we say that attributes are the same everywhere, including metrics, but:
  - State that semantic conventions MUST not include complex types for metric attributes.
  - Heavily discourage use of complex types in metric attributes in docs.
  - Provide a fallback way to serialize complex attributes with JSON-string encoding if an exporter comes across a complex type. Note: this is the same thing that is expected today if prometheus exporter comes across an array attribute.

This design accomplishes symmetry while avoiding artificial constraints on how data can be represented for spans and logs where real use cases exist for complex types.

2024-01-17 22:09 UTC, pellared requested changes
https://github.com/open-telemetry/opentelemetry-specification/pull/2888#discussion_r1455816141

I also (currently) agree with https://github.com/open-telemetry/opentelemetry-specification/pull/2888#issuecomment-1896781540.

2024-01-18 17:18 UTC, rfratto commented
> The goal of OpenTelemetry is to capture telemetry in the most effective and semantics-preserving way, not to provide the lowest common denominator and call it a "level playing field" for backend implementations. Vendor neutrality does not mean that you can switch your vendor and keep exactly the same capabilities, what would be the point of competition then. Compatibility matrix is always implicitly there, but it's not OpenTelemetry's concern.

I found this comment to be particularly surprising, as it was not the definition of "vendor neutrality" I had in mind, and by some of the arguments on this issue, it seems that I'm not alone in my confusion. I wasn't able to easily find something on the OpenTelemetry website that clearly laid these expectations out. 

Should this be documented more explicitly (or if it's already documented, moved somewhere easier to find) to avoid reader misunderstanding?

2024-01-18 17:36 UTC, MrAlias commented
> * Why don't we say that attributes are the same everywhere

@jack-berg we have already defined attributes differently for logs than for all the other signals. The `Attributes` field for the logs bridge API [emit](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/bridge-api.md#emit-a-logrecord) operation is defined by the logs [data-model](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/data-model.md#field-attributes) (`map<string, any>`), not the [`Attributes`](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/common/README.md#attribute) all the other signals[^1][^2][^3][^4][^5] use.

As was pointed out [here](https://github.com/open-telemetry/opentelemetry-specification/pull/2888#issuecomment-1888447881), the purpose of this PR is not to change the logs definition. This change will only affect the existing signals and resources that already use these attributes. I don't think we can justify making a change to attributes used by the trace and metric signal and resources so that they can be "unified" with logs when logs already uses a different definition and will not be migrated.

[^1]: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/api.md#record-1
[^2]: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/api.md#record
[^3]: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/api.md#add-1
[^4]: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/api.md#measurement
[^5]: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#span

2024-01-18 17:39 UTC, MrAlias commented
Have there been any asks by users to add these attribute types to tracing or metrics?

2024-01-18 17:49 UTC, pellared commented
@MrAlias Isn't the [logs attribute type](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/data-model.md#type-any) semantically the same as the one proposed in this PR? If not then can you point out the difference?

Take notice that the common attributes specification already references log attributes (which in my opinion suggests that this is the same type):

https://github.com/open-telemetry/opentelemetry-specification/blob/65c7dffd03c312b0a92f3820f6432d71dcee6ca7/specification/common/README.md#L128

2024-01-18 18:26 UTC, tigrannajaryan commented
> Have there been any asks by users to add these attribute types to tracing or metrics?

@MrAlias Yes for traces, a couple issues are linked in the PR description - the stacktrace and the payload use cases.

2024-01-18 21:02 UTC, pellared commented
> Semantically equivalent is not the same as identical. 

I agree. This is why I do not want to release a stable OTel Go Logs API module until this issue/PR is resolved.

> Implementations that have developed a logs attribute type to conform with the specification cannot simply change out that type to another without breaking the API.

The this will "negatively" (breaking changes) affect some non-stable implementations (AFAIK [Rust](https://github.com/open-telemetry/opentelemetry-rust/blob/27d338dd954ef7681242ead47a8a61c964dcc428/opentelemetry/src/logs/record.rs#L79) and [JS](https://github.com/open-telemetry/opentelemetry-js/blob/main/experimental/packages/api-logs/src/types/LogRecord.ts#L81)).

CC @lalitb @scheler

But it could "positively" impact all stable implementations (and Python):

   - Java (stable logs): [reuses a common attribute type](https://github.com/open-telemetry/opentelemetry-java/blob/main/api/all/src/main/java/io/opentelemetry/api/logs/LogRecordBuilder.java) and [a map as value is not supported](https://github.com/open-telemetry/opentelemetry-java/blob/main/api/all/src/main/java/io/opentelemetry/api/common/AttributeType.java)
   - .NET (stable logs): [models attributes](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry.Api/Logs/LogRecordAttributeList.cs) (for all signals) as [`KeyValuePair<string, object?>`](https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.keyvaluepair-2) and [a map as value is not supported by OTLP exporter](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/Shared/TagTransformer.cs)
   - C++ (stable logs): [reuses a common attribute type](https://github.com/open-telemetry/opentelemetry-cpp/blob/main/api/include/opentelemetry/logs/log_record.h) and [a map as value is not supported](https://github.com/open-telemetry/opentelemetry-cpp/blob/main/api/include/opentelemetry/common/attribute_value.h)
   - Python (experimental logs): [reuses a common attribute type](https://github.com/open-telemetry/opentelemetry-python/blob/main/opentelemetry-sdk/src/opentelemetry/sdk/_logs/_internal/__init__.py) and [a map as value is not supported](https://github.com/open-telemetry/opentelemetry-python/blob/main/opentelemetry-api/src/opentelemetry/util/types.py)

2024-01-18 21:22 UTC, MSNev commented
> This will "negatively" (breaking changes) affect some non-stable implementations (AFAIK [Rust](https://github.com/open-telemetry/opentelemetry-rust/blob/27d338dd954ef7681242ead47a8a61c964dcc428/opentelemetry/src/logs/record.rs#L79) and [JS](https://github.com/open-telemetry/opentelemetry-js/blob/main/experimental/packages/api-logs/src/types/LogRecord.ts#L81)). CC @lalitb Lalit Kumar Bhasin FTE @scheler

I don't believe that this will be an issue for JS as we previously had a [`SpanAttributes`](https://github.com/open-telemetry/opentelemetry-js/blob/43e598e7c1a603129c6e92ee983c6bb82b50b9a6/api/src/trace/attributes.ts#L22-L27)  which is now just an alias for `Attributes`, so the same would be for the `LogAttributes`. JavaScript itself doesn't have any concept of runtime "type" checking, this is "added" by implementing using TypeScript and enforced at compile time (which you can be ignore with some additional casting), it is flexible enough to determine (mostly -- not always) that 2 different interface definitions which have the same set of properties / types are equivalent.

2024-01-18 21:24 UTC, MrAlias commented
> > Semantically equivalent is not the same as identical.
> 
> I agree. This is why I do not want to release a stable OTel Go Logs API module until this issue/PR is resolved.
> 
> > Implementations that have developed a logs attribute type to conform with the specification cannot simply change out that type to another without breaking the API.
> 
> This will "negatively" (breaking changes) affect some non-stable implementations (AFAIK [Rust](https://github.com/open-telemetry/opentelemetry-rust/blob/27d338dd954ef7681242ead47a8a61c964dcc428/opentelemetry/src/logs/record.rs#L79) and [JS](https://github.com/open-telemetry/opentelemetry-js/blob/main/experimental/packages/api-logs/src/types/LogRecord.ts#L81)). CC @lalitb @scheler
> 
> But it could "positively" impact all stable implementations (and Python):
> 
> * Java (stable logs): [reuses a common attribute type](https://github.com/open-telemetry/opentelemetry-java/blob/main/api/all/src/main/java/io/opentelemetry/api/logs/LogRecordBuilder.java) and [a map as value is not supported](https://github.com/open-telemetry/opentelemetry-java/blob/main/api/all/src/main/java/io/opentelemetry/api/common/AttributeType.java)
> * .NET (stable logs): [models attributes](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry.Api/Logs/LogRecordAttributeList.cs) (for all signals) as [`KeyValuePair<string, object?>`](https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.keyvaluepair-2) and [a map as value is not supported by OTLP exporter](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/Shared/TagTransformer.cs)
> * C++ (stable logs): [reuses a common attribute type](https://github.com/open-telemetry/opentelemetry-cpp/blob/main/api/include/opentelemetry/logs/log_record.h) and [a map as value is not supported](https://github.com/open-telemetry/opentelemetry-cpp/blob/main/api/include/opentelemetry/common/attribute_value.h)
> * Python (experimental logs): [reuses a common attribute type](https://github.com/open-telemetry/opentelemetry-python/blob/main/opentelemetry-sdk/src/opentelemetry/sdk/_logs/_internal/__init__.py) and [a map as value is not supported](https://github.com/open-telemetry/opentelemetry-python/blob/main/opentelemetry-api/src/opentelemetry/util/types.py)

If we are able to retroactively make breaking changes to a stable portion of the specification because no stable implementation is [compliant](https://github.com/open-telemetry/opentelemetry-specification/tree/main/specification#notation-conventions-and-compliance) I think we can just replace our [versioning and stability guidelines](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/versioning-and-stability.md) with:

```text
Do whatever, we'll fix it later.
```

:laughing: 

In all seriousness though, that is going to have to be a separate issue than this one. The TC and likely GC (cc @open-telemetry/governance-committee @open-telemetry/technical-committee ) will need to weight our representational loss in not doing what we say we will with the desire to correct this situation.

I just wanted to point this out as @jack-berg had mentioned conformity and reuse of the existing attribute definition as motivation for this change, but it has been pointed out by @tigrannajaryan and others that that is not the intent of this PR.

2024-01-19 10:21 UTC, jpkrohling commented
Thank you for your clarifications and patience, @tigrannajaryan. I also appreciate @jack-berg's options and I agree with them as well. We are also aligned that we shouldn't aim for the lowest common denominator, and I hope my previous messages didn't imply that.

One of my goals with my questions is to ensure that open-source users can take advantage of the solutions we are giving to the problems they have. And if they can't, what does it mean? That the open-source ecosystem doesn't care about this feature, because users don't care about them? Or that there are other easier ways to solve the same problem? In my opinion, what we shouldn't be doing is creating a feature without taking the broader open-source ecosystem in consideration.

My other major point was in having consistency among signals: if the use-case isn't strong enough, we probably shouldn't break the consistency we have now, even if we have inconsistencies elsewhere. I believe those inconsistencies are smaller compared to ruling out metrics for this proposal here.

Your example of Elastic helps in showing one open-source solution for logs using complex attribute values. While it isn't open-source, I take that it works for OpenSearch as well, although a confirmation would be desirable. And given that we have @yurishkuro's approval of this issue here, I believe Jaeger users are represented as well, so, I'm happy with the tracing side of things. It's still not clear to me whether users can use that information for their _observability_ scenarios ("show me how all traces containing stacktraces for the line 53 of KotlinExtensions.kt"), or if it's only for reference once the right data point (log or span) has been found. This is what I meant by an end-to-end example: how do we _envision_ things happening to solve the problem at hand.

We still have a situation regarding metrics, though, and the one thing I'd ask before moving forward is to sync with the Prometheus folks and come up with an agreement on how to handle this situation. Are they happy to just drop this data? Or to serialize it as JSON? Would they be open to implementing a different way to store this data and not keep it in TSDB? If we don't engage with them, I predict that they will be mad at us because we are specifying something we _know_ they don't support. Why Prometheus? Because it's one of the most relevant, if not _the_ most relevant, open-source metrics database out there, especially for our audience. If the Prometheus WG folks (@dashpole comes to mind) are OK with this change, I'm certainly OK with it as well.

2024-01-19 12:42 UTC, pellared commented on specification/common/README.md
> +  - An array of values of primitive type [before 1.29.0].
Should we also include a byte array (as for logs attributes)?

2024-01-19 15:05 UTC, dashpole commented
Prometheus only supports string label values, so we already need to deal with similar cases today for arrays. Thus far, we've followed https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/common/README.md#attribute, and serialized to json for all of those cases, rather than drop. TBH, I don't think I've ever seen a prometheus metric with an array-typed label from OTel, although I suspect it happens occasionally when we encode Resource as the `target_info` metric (e.g. if they have `process.command_args`).

I definitely agree with the sentiment that prometheus users don't want large, structured, json-encoded attribute values in their metrics. Even adding namespaces to metric labels is [seen as too verbose by prometheus folks](https://github.com/open-telemetry/opentelemetry-specification/issues/3634) (although I understand the rationale). In practice, many prometheus users set [`label_value_length_limit`](https://prometheus.io/docs/prometheus/latest/configuration/configuration/) to avoid ingesting very large label values. If they did encounter a large, structured json-encoded label value, it would cause scraping to fail, and the user would likely choose to drop that label anyways using prometheus relabel rules.

If, like arrays, maps are _rarely_ used for metric label values, I don't think this will be a huge issue. We can JSON-encode them when they do appear and let users deal with those strings. But I don't see this being useful for metrics, and would personally be against using these in semantic conventions for metrics.

@gouthamve @fstab

2024-01-22 21:54 UTC, tigrannajaryan commented
I spent a bit more time thinking about this issue and came to a conclusion that this change is non-trivial and likely warrants an OTEP. I don't think a PR is the right mechanism for a change like this. I am going to close the PR.

I don't plan to create the OTEP myself right now since I don't have time. If someone else wishes to create the OTEP, I can review it. 

If such an OTEP is proposed I think it needs to at least:
- Explain the current state of the spec. I see comments in this thread that indicate lack of knowledge of what we have today. It would be useful to describe it in the OTEP.
- Explain how the change is possible to implement in existing stable language API/SDKs within the compatibility promises those SDKs give their users. 
- Resolve an outstanding open question: should metrics discourage but in theory allow the same complex attribute value data type as all other signals and flatten it based destination limitations OR should metrics outright prevent complex data types (and whether to prevent it at runtime or compile time). 
- Attach prototype implementations in multiple languages proving the previous claim. Show what the performance impact (if any) of the change is. We have a Java prototype from @jack-berg and I believe @MrAlias has some preliminary sketches in Go.

To @pellared and @MrAlias, who are waiting on the resolution to this. I see 3 options:
- Do the OTEP yourself (if you are willing) to unblock yourself.
- Wait for someone else to do the OTEP.
- Don't wait and implement log attributes according to existing spec. This likely means a different data type and likely impossibility to later make the API uniform across signals.

There is probably some other alternative I am not seeing right now.

Thank you everyone for patience and for helpful feedback and comments.

2024-01-22 21:54 UTC, closed without merging