add convention attribute k8s cluster version
open-telemetry/opentelemetry-specification pull request #2937
Opened 2022-11-10 14:37 UTC by frzifus

Signed-off-by: Benedikt Bongartz <bongartz@klimlive.de>

Fixes #2913

## Changes

Please provide a brief description of the changes here.

For non-trivial changes, follow the [change proposal
process](../CONTRIBUTING.md#proposing-a-change) and link to the related issue(s)
and/or [OTEP(s)](https://github.com/open-telemetry/oteps), update the
[`CHANGELOG.md`](../CHANGELOG.md), and also be sure to update
[`spec-compliance-matrix.md`](../spec-compliance-matrix.md) if necessary.

Related issues #

Related [OTEP(s)](https://github.com/open-telemetry/oteps) #

2022-11-21 18:35 UTC, arminru commented on semantic_conventions/resource/k8s.yaml
> +          The version of the cluster.
```suggestion
          The version of the Kubernetes implementation of the cluster.
```
or
```suggestion
          The Kubernetes version of the of the cluster.
```
How about this to make clear this is about k8s and not the version of the installed app?

2022-11-21 18:35 UTC, arminru commented on semantic_conventions/resource/k8s.yaml
> +
You could add a `note:` saying how this value can be retrieved and/or reference the Kubernetes docs for it.

2022-11-21 18:35 UTC, arminru commented on semantic_conventions/resource/k8s.yaml
> +      - id: version
@jsuereth @reyang @jmacd Do you have any concerns about adding this (potentially high-cardinality over time) attribute to the resources?

2022-11-22 11:35 UTC, joaopgrassi commented on semantic_conventions/resource/k8s.yaml
> +
If you add it as a `note:` like in here https://github.com/frzifus/opentelemetry-specification/blob/add_convention_attribute_k8s_cluster_version/semantic_conventions/trace/faas.yaml#LL13C11-L13C34 then it will show `[1]` as in here https://github.com/frzifus/opentelemetry-specification/blob/add_convention_attribute_k8s_cluster_version/specification/trace/semantic_conventions/faas.md#general-attributes

You will also need to re-generate the tool to update the markdown.

2022-11-23 16:39 UTC, frzifus commented on semantic_conventions/resource/k8s.yaml
> +
let me check that :+1:

2022-11-23 16:56 UTC, frzifus commented on semantic_conventions/resource/k8s.yaml
> +
mh.. i made some changes. But after calling `make` again it failed with the following:

```bash
docker run --rm -v /home/frzifus/git/go/observability/opentelemetry-specification/semantic_conventions:/source -v /home/frzifus/git/go/observability/opentelemetry-specification/specification:/spec \
	otel/semconvgen:0.14.0 -f /source markdown -md /spec --md-check
usage: gen-semconv [-h] [--debug]
                   [--only {span,resource,event,metric,units,scope}]
                   [--yaml-root folder] [--exclude EXCLUDE]
                   [YAML_FILE [YAML_FILE ...]] {code,markdown} ...
gen-semconv: error: No semantic convention model found!
make: *** [Makefile:83: table-check] Fehler 2
```

Any idea whats wrong?

2022-11-23 20:30 UTC, frzifus commented on semantic_conventions/resource/k8s.yaml
> +
ok - seems its caused by `selinux`. https://docs.docker.com/storage/bind-mounts/#configure-the-selinux-label

2022-11-28 23:13 UTC, frzifus commented on semantic_conventions/resource/k8s.yaml
> +      - id: version
mh.. At least from the scenarios ive in mind, it doesnt change to often. Depending on your retention period you may have 2-3 different versions in your storage.

2022-12-02 00:33 UTC, frzifus commented on semantic_conventions/resource/k8s.yaml
> +      - id: version
any update here?

2022-12-06 16:07 UTC, MrAlias approved these changes

2022-12-06 16:44 UTC, tigrannajaryan commented on specification/resource/semantic_conventions/k8s.md
> +| `k8s.cluster.version` | string | The Kubernetes version of the of the cluster. [1] | `v1.21.11` | Recommended |
Adding a recommended attribute to the Resource potentially is a breaking change for exporters that turn Resource attributes into metric dimensions.
@jsuereth WDYT?

2022-12-14 09:04 UTC, frzifus commented
can someone re-open this pr? seems ive no permission :x: 

cc @open-telemetry/specs-approvers

2023-01-03 17:20 UTC, tigrannajaryan requested changes
I am temporarily blocking this to make sure we don't accidentally merge until my comment about this being a breaking change is addressed.

2023-01-11 18:41 UTC, tigrannajaryan commented on specification/resource/semantic_conventions/k8s.md
> +| `k8s.cluster.version` | string | The Kubernetes version of the of the cluster. [1] | `v1.21.11` | Recommended |
@jsuereth when you have a moment it would be great to have your opinion on this.

2023-02-08 03:17 UTC, closed without merging