Add RabbitMQ message headers to semantic conventions
open-telemetry/opentelemetry-specification pull request #2946
Opened 2022-11-14 17:41 UTC by samimusallam

Fixes #2895

## Changes

- Add semantic conventions for RabbitMQ message headers.

2022-11-15 15:42 UTC, carlosalberto commented
@samimusallam Your PR is empty (only Changelog was updated).

2022-11-15 19:41 UTC, samimusallam commented
> @samimusallam Your PR is empty (only Changelog was updated).

fixed :) it seems one of the lint commands I ran removed my changes without noticing

2022-11-16 19:55 UTC, lmolkova requested changes
@samimusallam can you please take a look at https://github.com/open-telemetry/opentelemetry-specification/pull/2763?

Messaging SIG is introducing `messaging.message` namespace.  Could you consider an option to put rabbitmq custom headers to `messaing.rabbitmq.message` namespace instead ?

2022-11-16 19:55 UTC, lmolkova commented on specification/trace/semantic_conventions/messaging.md
> -<!-- semconv messaging.rabbitmq -->
let's preserve attribute auto-generation - you can add headers as an additional section after the auto-generated table (maybe even as a continuation of it.

2022-11-16 19:55 UTC, lmolkova commented on specification/trace/semantic_conventions/messaging.md
> +| `messaging.rabbitmq.message.header.<key>` | string[] | RabbitMQ message headers. `<key>` being the normalized message header name (lowercase, with - characters replaced by _), the value being the h
can you please add a link to rabbitmq documentation here and specify what's considered to be a header. E.g. is content-type a header or only optional properties are headers?

2022-11-16 19:55 UTC, lmolkova commented on specification/trace/semantic_conventions/messaging.md
> +**[2]:** The attribute value MUST consist of either multiple header values as an array of strings or a single-item array containing a possibly comma-concatenated string, depending on the way the libr
does rabbitmq support array headers?

2022-11-16 20:10 UTC, samimusallam commented on specification/trace/semantic_conventions/messaging.md
> +**[2]:** The attribute value MUST consist of either multiple header values as an array of strings or a single-item array containing a possibly comma-concatenated string, depending on the way the libr
It does in the NodeJS client, not sure about other languages but should be similar

2022-11-16 20:13 UTC, samimusallam commented on specification/trace/semantic_conventions/messaging.md
> -<!-- semconv messaging.rabbitmq -->
Sounds good! I'll add the headers section as a continuation below the auto-generated table

2022-11-16 20:17 UTC, samimusallam commented
> @samimusallam can you please take a look at #2763?
> 
> Messaging SIG is introducing `messaging.message` namespace. Could you consider an option to put rabbitmq custom headers to `messaing.rabbitmq.message` namespace instead ?

I've added the headers to `messaging.rabbitmq.message.header.<key>` as agreed to [here](https://github.com/open-telemetry/opentelemetry-specification/issues/2895#issuecomment-1302384172) are you referring to using `messaging.rabbitmq.message.<key>` instead?

2022-11-16 20:46 UTC, samimusallam commented on specification/trace/semantic_conventions/messaging.md
> +| `messaging.rabbitmq.message.header.<key>` | string[] | RabbitMQ message headers. `<key>` being the normalized message header name (lowercase, with - characters replaced by _), the value being the h
The `content-type` property as an example exists outside the headers field. There are a couple more properties that are defined outside the headers field which I think could also be relevant to be captured in spans.
As written in the [docs](https://www.rabbitmq.com/publishers.html#message-properties) the headers field contains an arbitrary map so it's not something specific.

2022-11-17 18:43 UTC, jsuereth commented on semantic_conventions/trace/messaging.yaml
> -  - id: messaging.rabbitmq
Why was this removed?

2022-11-19 11:58 UTC, samimusallam commented on semantic_conventions/trace/messaging.yaml
> -  - id: messaging.rabbitmq
As mentioned in [this comment](https://github.com/open-telemetry/opentelemetry-specification/pull/2946#issuecomment-1315804525) I've had some issues with the table generator as I couldn't escape the `<` and `>` characters for the headers attribute. So I took the same approach that was done in the HTTP semantic conventions which is to manually write the table.

2022-11-19 12:39 UTC, samimusallam commented on specification/trace/semantic_conventions/messaging.md
> -<!-- semconv messaging.rabbitmq -->
I couldn’t manually add the headers below the generated table, it doesn't expand to the same table.
 Does it make sense to create a new table below the generated table just for the attribute headers?

2022-11-20 10:20 UTC, osherv approved these changes

2022-12-18 09:38 UTC, samimusallam commented
> This PR was marked stale due to lack of activity. It will be closed in 7 days.

Not stale, waiting on reviewers

2023-01-04 23:45 UTC, carlosalberto commented
Removed the stale label - it looks like a few people are still on holidays, but hopefully soon a final cycle of reviews comes.

2023-01-25 08:55 UTC, samimusallam commented
@open-telemetry/specs-approvers @open-telemetry/specs-trace-approvers Please take a look at this

2023-01-26 00:22 UTC, lmolkova commented on specification/trace/semantic_conventions/messaging.md
> +| `messaging.rabbitmq.message.header.<key>` | string[] | RabbitMQ message headers. `<key>` being the normalized message header name (lowercase, with - characters replaced by _), the value being the h
I believe this should be `optional`. Optional means that it's not populated by default, but users can opt-in. For example, instrumentation library may provide configuration for users to enable it. 

`Recommended` would mean that all instrumentation libraries SHOULD populate all headers by default. Since number and content of the headers is not known, they should not be populated by default.

2023-01-26 08:59 UTC, samimusallam commented on specification/trace/semantic_conventions/messaging.md
> +| `messaging.rabbitmq.message.header.<key>` | string[] | RabbitMQ message headers. `<key>` being the normalized message header name (lowercase, with - characters replaced by _), the value being the h
Oh I miss understood `Recommended`. Will update it to `optional`.

2023-01-26 09:56 UTC, samimusallam commented
Can this PR be reopened? It went stale for too long

2023-01-26 17:18 UTC, lmolkova commented on specification/trace/semantic_conventions/messaging.md
> +| `messaging.rabbitmq.message.header.<key>` | string[] | RabbitMQ message headers. `<key>` being the normalized message header name (lowercase, with - characters replaced by _), the value being the h
Thank you for sharing the docs! would you mind adding them to the md file too so instrumentation authors know precisely what they refer to?

2023-02-01 08:25 UTC, samimusallam commented on specification/trace/semantic_conventions/messaging.md
> +| `messaging.rabbitmq.message.header.<key>` | string[] | RabbitMQ message headers. `<key>` being the normalized message header name (lowercase, with - characters replaced by _), the value being the h
Added :)

2023-02-02 16:40 UTC, lmolkova commented on specification/trace/semantic_conventions/messaging.md
> +**[3]:** The attribute value MUST consist of either multiple header values as an array of strings or a single-item array containing a possibly comma-concatenated string, depending on the way the libr
The type mentioned above is `string[]` and this note suggests it can be either an array or a single string. 

Given that it's an optional attribute anyway, it may be reasonable to ask instrumentations to split comma-separated-string into array.

2023-02-02 16:57 UTC, samimusallam commented on specification/trace/semantic_conventions/messaging.md
> +**[3]:** The attribute value MUST consist of either multiple header values as an array of strings or a single-item array containing a possibly comma-concatenated string, depending on the way the libr
Please let me know if the updated note is clear

2023-03-19 12:31 UTC, samimusallam commented
Not stale, waiting for review @open-telemetry/technical-committee, @open-telemetry/specs-approvers, @open-telemetry/specs-trace-approvers and @open-telemetry/instr-wg

2023-03-20 09:26 UTC, Oberon00 commented on semantic_conventions/trace/messaging.yaml
> -  - id: messaging.rabbitmq
Hi, you can't remove the entry here, this will lead to breaking changes for all languages that use the YAML files to generate code.

2023-03-20 09:30 UTC, samimusallam commented on semantic_conventions/trace/messaging.yaml
> -  - id: messaging.rabbitmq
Hi, this is outdated. This is not removed anymore.

2023-03-20 09:33 UTC, samimusallam commented on semantic_conventions/trace/messaging.yaml
> -  - id: messaging.rabbitmq
Yes exactly, the `<>` are not supported yet so I had to write it manually :)

2023-03-20 12:37 UTC, Oberon00 commented on specification/trace/semantic_conventions/messaging.md
> +**[3]:** The attribute value MUST consist of either multiple header values as an array of strings or a single-item array containing a possibly comma-concatenated string, depending on the way the libr
Why split by comma? The comma rule is something that applies to HTTP, but why would it apply to messaging headers? Does any messaging system or RabbitMQ specifically support multiple values for the same header, or does an array maybe not make sense here? OTOH, are non-string values supported as headers?

2023-03-20 12:37 UTC, Oberon00 commented on specification/trace/semantic_conventions/messaging.md
> +| `messaging.rabbitmq.message.header.<key>` | string[] | RabbitMQ message headers [1]. `<key>` being the normalized message header name (lowercase, with - characters replaced by _), the value being t
I think message headers are supported in most messaging systems and the definition does also not contain anything RabbitMQ-specific. Should we make it a general `messaging.message.header.<key>` attribute instead?

CC @lmolkova @pyohannes

One thing I'm wondering about though is case sensitivity: Here, messaging systems might behave differently, probably case-insensitive systems should apply the transformation described here (IIUC, it is copied from HTTP), while others should report the key as-is.

2023-04-05 03:17 UTC, closed without merging