Refactor messaging attributes and specify per-message attributes
open-telemetry/opentelemetry-specification pull request #2957
Opened 2022-11-16 20:15 UTC by lmolkova

The final round of #2763

## Changes

Messaging instrumentation SIG is working on [spec changes](https://github.com/open-telemetry/oteps/pull/192) and this change is one of the first steps to bring the consensus we reached in SIG to the spec.

This change introduces different namespace for different kinds of attributes:
- `messaging.message` for message properties
- `messaging.destination` for producers to describe publish operations
- `messaging.source` for consumers to describe receive/deliver/process operations
- `messaging.batch` for to describe batch properties

It also introduces guidance for specific systems on namespaces.

Here's the list of breaking changes (attribute renames):
- `messaging.protocol`: `net.app.protocol.name`
- `messaging.protocol_version: net.app.protocol.version`
- `messaging.destination: messaging.destination.name`
- `messaging.temp_destination: messaging.destination.temporary`
- `messaging.destination_kind: messaging.destination.kind`
- `messaging.message_id`: `messaging.message.id`
- `messaging.conversation_id`: `messaging.message.conversation_id`
- `messaging.message_payload_size_bytes`: `messaging.message.payload_size_bytes`
- `messaging.message_payload_compressed_size_bytes`: `messaging.message.payload_compressed_size_bytes`
- `messaging.rabbitmq.routing_key`: `messaging.rabbitmq.message.routing_key`
- `messaging.kafka.message_key`: `messaging.kafka.message.key`
- `messaging.kafka.partition`: `messaging.kafka.message.partition`
- `messaging.kafka.tombstone`: `messaging.kafka.message.tombstone`
- `messaging.rocketmq.message_type`: `messaging.rocketmq.message.type`
- `messaging.rocketmq.message_tag`: `messaging.rocketmq.message.tag`
- `messaging.rocketmq.message_keys`: `messaging.rocketmq.message.keys`

It also adds the `messaging.batch.size` attribute which intends to:
- denote a bathing operation
- record number of messages sent/received/processed - since links can be dropped or there can be some other links not describing messages, link count is not a reliable indicator of batch size. Assuming a high-scale scenario, users might want to opt-out from per-message tracing, but then batch_size would still be useful

Related [OTEP(s)](https://github.com/open-telemetry/oteps) #
- https://github.com/open-telemetry/oteps/pull/192
- https://github.com/open-telemetry/oteps/pull/220

2022-11-17 15:58 UTC, dpauls requested changes

2022-11-17 15:58 UTC, dpauls commented on specification/trace/semantic_conventions/messaging.md
> +Following additional attributes describe message producer operations.
```suggestion
The following additional attributes describe message producer operations.
```
Besides the minor rewording suggestion, I have a comment that I don't think the destination attributes should be considered to be producer-only. For a message published to a topic, then stored on a queue for a consumer, when the consumer receives the message, the source is the queue itself, but the destination is the topic the message was published to. If all of this information is available, I think it's useful to provide it in a span since the topic provides more information about the message than just the queue it came from.

As written, the destination attributes are implied to be relevant only to producer spans.

2022-11-17 17:53 UTC, pyohannes commented on specification/trace/semantic_conventions/messaging.md
> +| `messaging.kafka.message.partition` | int | Partition the message is sent to. | `2` | Recommended |
Another point that occurred to me after the discussion is related to the granularity of how a distinct destination is defined. In my understanding, any different combination of `source` or `destination` attributes (name, kind, anonymous, temporary, template) identifies a different destination or source. However, if there's are destinations/sources with the same name and kind, but different partitions, I think one wouldn't see this as a different destination.

The main question then is, whether the definition of a destination should go beyond the granularity of a topic or queue, or if this additional granularity should be handled at the level of a message.

2022-11-17 17:57 UTC, blumamir commented on specification/trace/semantic_conventions/messaging.md
> +| `messaging.rabbitmq.message.routing_key` | string | RabbitMQ message routing key. | `myKey` | Conditionally Required: If not empty. |
Summarizing here my take on the discussion we had around this today at the SIG.

As written few lines above:
> In RabbitMQ, the destination is defined by an *exchange* and a *routing key*.

I think they are considered one unit that describes where the message is sent to and how it is routed when processed by rabbit broker, which are both a property of the "destination" (the rabbit broker that receives this message)

In rabbit [routing example](https://www.rabbitmq.com/tutorials/tutorial-four-python.html), the following code:
```py
channel.basic_publish(
    exchange='direct_logs', routing_key='info', body=message)
```

Would create the following attributes
```
messaging.destination.name: "direct_logs"
messaging.rabbitmq.message.routing_key: "info"
```

Storing the routing key as `messaging.rabbitmq.*destination*.routing_key: "info" `  makes more sense to me personally.

This is a minor issue and I am good with both options

2022-11-17 18:15 UTC, blumamir commented on specification/trace/semantic_conventions/messaging.md
> +| `messaging.kafka.message.partition` | int | Partition the message is sent to. | `2` | Recommended |
> Another point that occurred to me after the discussion is related to the granularity of how a distinct destination is defined. In my understanding, any different combination of `source` or `destination` attributes (name, kind, anonymous, temporary, template) identifies a different destination or source. However, if there's are destinations/sources with the same name and kind, but different partitions, I think one wouldn't see this as a different destination.
> 
> The main question then is, whether the definition of a destination should go beyond the granularity of a topic or queue, or if this additional granularity should be handled at the level of a message.

Interesting observation. It makes sense to me.
Maybe the criteria we are looking for to host something in the `destination`/`source` namespace is whether it affects the **logical** routing in the messaging system routing model? In contrast to `partition` which is implementation / technical detail?

In this criteria, I think the `messaging.kafka.consumer_group` attribute should belong to the `source` namespace

2022-11-19 13:58 UTC, ppatierno commented on specification/trace/semantic_conventions/messaging.md
> +| `messaging.kafka.message.partition` | int | Partition the message is sent to. | `2` | Recommended |
> However, if there's are destinations/sources with the same name and kind, but different partitions, I think one wouldn't see this as a different destination.

I am not getting this sentence if I think in terms of Kafka. You cannot have two topics with the same name and different number of partitions. I think I haven't got what you mean here.

2022-11-21 22:19 UTC, lmolkova commented on specification/trace/semantic_conventions/messaging.md
> +| `messaging.kafka.message.partition` | int | Partition the message is sent to. | `2` | Recommended |
> In this criteria, I think the messaging.kafka.consumer_group attribute should belong to the source namespace

Consumer group is not a `source` property - https://docs.confluent.io/platform/current/clients/consumer.html#consumer-groups. It's a pure consumer thing and the only thing that broker does wrt the group is the coordinator election. 

What do you folks think about adding `consumer` namespace? 
We also have `messaging.consumer_id` - should we move it to `messaging.consumer.id` and then the consumer group will be in `messaging.kafka.consumer.group`

2022-11-21 23:13 UTC, lmolkova commented on specification/trace/semantic_conventions/messaging.md
> +| `messaging.kafka.message.partition` | int | Partition the message is sent to. | `2` | Recommended |
> The main question then is, whether the definition of a destination should go beyond the granularity of a topic or queue, or if this additional granularity should be handled at the level of a message.

I believe it should describe the destination as precisely as possible. At the same time, backends can make sense of attributes in different ways. For example, service map probably should not show X nodes for kafka since there are X partitions, but when your monitor consumer lag or number of sent messages, you might want to see them per partition.

Do you think we need to change the definition of the destination to reflect it?

2022-11-22 00:06 UTC, pyohannes commented on specification/trace/semantic_conventions/messaging.md
> +| `messaging.kafka.message.partition` | int | Partition the message is sent to. | `2` | Recommended |
> I believe it should describe the destination as precisely as possible.

I think then the partition should go into the `destination`/`source`.

> At the same time, backends can make sense of attributes in different ways. For example, service map probably should not show X nodes for kafka since there are X partitions, but when your monitor consumer lag or number of sent messages, you might want to see them per partition.

Agreed.

> Do you think we need to change the definition of the destination to reflect it?

Yes. I think the directive of "describe the destination as precisely as possible" is vague enough, but still very useful.

2022-11-22 00:09 UTC, pyohannes commented on specification/trace/semantic_conventions/messaging.md
> +| `messaging.kafka.message.partition` | int | Partition the message is sent to. | `2` | Recommended |
> What do you folks think about adding consumer namespace?

That would make sense to me, looking at the `messaging.consumer_id` and `messaging.consumer_group` attributes.

I think we can then say that the `consumer` namespace is by definition not message-specific?

2022-11-22 00:12 UTC, pyohannes commented on specification/trace/semantic_conventions/messaging.md
> +| `messaging.kafka.message.partition` | int | Partition the message is sent to. | `2` | Recommended |
> > However, if there's are destinations/sources with the same name and kind, but different partitions, I think one wouldn't see this as a different destination.
>
> I am not getting this sentence if I think in terms of Kafka. You cannot 
> have two topics with the same name and different number of 
> partitions. I think I haven't got what you mean here.

Not at the same time, but if you increase the partition count, you can have this configuration at different points in time. But my point is, that one probably still would say that its' the same destination/source.

2022-11-22 01:43 UTC, lmolkova commented on specification/trace/semantic_conventions/messaging.md
> +Following additional attributes describe message producer operations.
thanks, I added destination attributes to consumer section

2022-11-22 01:43 UTC, lmolkova commented on specification/trace/semantic_conventions/messaging.md
> +| `messaging.rabbitmq.message.routing_key` | string | RabbitMQ message routing key. | `myKey` | Conditionally Required: If not empty. |
I moved routing_key to destination

2022-11-22 02:21 UTC, lmolkova commented on semantic_conventions/trace/messaging.yaml
> +      - id: batch.size
been thinking about batch namespace and naming. We'll probably want to add batch size in bytes at some point and  then batch.size will become misleading. So I suggest to rename this one to `batch.message_count`

2022-11-23 17:11 UTC, joaopgrassi reviewed
Did a first pass on the yaml file, looking great! I will take a look at the rest later and submit a new review then.

2022-11-23 17:11 UTC, joaopgrassi commented on semantic_conventions/trace/messaging.yaml
> +          recommended: when supported by messaging system and only if the source is temporary. If missing, assumed to be false.
```suggestion
          recommended: When supported by messaging system and only if the source is temporary. When missing, the value is assumed to be `false`.
```
So it's consistent with `destination.temporary` above :)

2022-11-23 17:11 UTC, joaopgrassi commented on semantic_conventions/trace/messaging.yaml
> +          recommended: when supported by messaging system and only if the source is anonymous. If missing, assumed to be false.
```suggestion
          recommended: When supported by messaging system and only if the source is anonymous. When missing, the value is assumed to be `false`.
```

2022-11-30 22:45 UTC, lmolkova commented on semantic_conventions/trace/messaging.yaml
> +        note: If a custom value is used, it MUST known to be of low cardinality.
agreed, created #2996 to track it.

2022-11-30 23:31 UTC, lmolkova commented on semantic_conventions/trace/messaging.yaml
> +      - id: destination.kind
sounds good, I moved destination and source to their own groups.

2022-12-01 15:00 UTC, joaopgrassi commented on specification/trace/semantic_conventions/messaging.md
> +* `messaging.{system}.destination` namespace describes destination a message (or a batch) are published to, and `messaging.{system}.source` describes source messages were received from. Combination o
```suggestion
* `messaging.{system}.destination` and `messaging.{system}.source`: Describes the destination and source a message (or a batch) are published to and received from respectively. The combination of attributes in these namespaces should uniquely identify the entity and describe it as precisely as possible. For example, if partitioning is supported, the attributes should include the partition or other important and visible to users entity properties.
```

I think the last sentence needs some love, but I was ensure of what the goal of it was. I left it as is we can discuss more.

2022-12-01 18:33 UTC, pyohannes commented on specification/trace/semantic_conventions/messaging.md
> +
I like that idea. I think it would be helpful to have the description of these high-level namespaces (`messaging.source`, `messaging.destination`, `messaging.consumer`, `messaging.message`), and then mention that all of them can be nested under `messaging.{system}`.

2022-12-01 19:14 UTC, dpauls approved these changes

2022-12-01 19:19 UTC, pyohannes commented on specification/trace/semantic_conventions/messaging.md
> +All attributes that are specific for a messaging system SHOULD be populated in `messaging.{system}` namespace. Attributes that describe message, destination, source, consumer, or batch properties SHO
We should avoid MUST statements in semantic conventions. A MUST doesn't allow any exceptions, a SHOULD allows exceptions if there's a well-grounded reason.

2022-12-01 19:23 UTC, pyohannes commented on specification/trace/semantic_conventions/messaging.md
> +set on links. Corresponding instrumentations MAY set source and destination attributes on the span if all messages in the batch share the same destination or source.
We shouldn't be too strict here.

Just an example: if this would be a MUST, then when receiving a batch of messages, one would need to go through all the messages and check whether all source attributes would be the same, before it's possible to decide whether to put attributes on the span or on links/events.

2022-12-01 19:32 UTC, pyohannes commented on semantic_conventions/trace/messaging.yaml
> +        brief: 'Low cardinality field representing messaging source'
```suggestion
        brief: 'Low cardinality representation of the messaging source name'
```
As this only refers to the name, and not to other attributes of the source.

2022-12-01 19:36 UTC, pyohannes commented on specification/trace/semantic_conventions/messaging.md
> +* `(anonymous) publish` (`(anonymous)` being a stable identifier for randomly generated, anonymous destination names)
```suggestion
* `(anonymous) publish` (`(anonymous)` being a stable identifier for automatically generated, anonymous destination names)
```

2022-12-01 19:39 UTC, pyohannes commented on specification/trace/semantic_conventions/messaging.md
> +Often such destinations are also  *anonymous* - unnamed or have an auto-generated name.
```suggestion
Often such destinations are also unnamed (anonymous) or have an auto-generated name.
```

2022-12-01 20:01 UTC, lmolkova commented on specification/trace/semantic_conventions/messaging.md
> +All attributes that are specific for a messaging system SHOULD be populated in `messaging.{system}` namespace. Attributes that describe message, destination, source, consumer, or batch properties SHO
We had a long discussion on the SIG meeting regarding some attributes, for example, routing_key on RabbitMQ, where it's not clear if it should be on `destination` or on `message` namespace. Given that it could be hard to classify attributes, it's impossible to be strict here.

2022-12-01 20:55 UTC, lmolkova commented on specification/trace/semantic_conventions/messaging.md
> +
I have a similar, but a non-normative sentence on general attributes. I updated it to mention that system-specific attributes must be on the corresponding namespace:

> Note that attributes in `messaging.message` namespace describe an individual message, `messaging.destination` namespace
contains attributes that describe the logical entity messages are published to, and `messaging.source` describes
logical entity messages are received from; attributes in `messaging.batch` namespace describe batch properties and `messaging.consumer` namespace
describes message consumer properties.
Messaging system-specific attributes MUST be defined in the corresponding `messaging.{system}` namespace
as described in [Attributes specific to certain messaging systems](#attributes-specific-to-certain-messaging-systems).

2022-12-01 20:56 UTC, lmolkova commented on specification/trace/semantic_conventions/messaging.md
> +* `messaging.{system}.destination` namespace describes destination a message (or a batch) are published to, and `messaging.{system}.source` describes source messages were received from. Combination o
I gave it a bit more love, lmk if you think it's enough :)

2022-12-02 00:06 UTC, pyohannes approved these changes

2022-12-02 16:44 UTC, joaopgrassi approved these changes
I will check the changelog and schema to see if no attribute is missing or wrong. But overall looks good to me!

2022-12-02 16:44 UTC, joaopgrassi commented on specification/trace/semantic_conventions/messaging.md
> +
I left a suggestion above. The text there is already good so feel free to follow the suggestion or not :)

2022-12-02 19:19 UTC, lmolkova commented on specification/trace/semantic_conventions/messaging.md
> +
Thank you, I like it!

2022-12-05 18:48 UTC, lmolkova commented on specification/trace/semantic_conventions/messaging.md
> +contains attributes that describe the logical entity messages are published to, and `messaging.source` describes
good catch, thank you!

2022-12-06 15:47 UTC, carlosalberto commented
@lmolkova is this ready to review from the general public?

2022-12-06 23:06 UTC, lmolkova commented on specification/trace/semantic_conventions/messaging.md
> +**[2]:** If the message destination is either a `queue` or a `topic`.
@ppatierno good point, we can discuss it at the messaging SIG meeting on Thursday. 

This PR though does not introduce anything new wrt `topic` and `queue` terminology and I'd prefer to address it separately.

2022-12-06 23:08 UTC, lmolkova commented
@carlosalberto yes, it's ready for review. Thanks!

2022-12-07 10:28 UTC, ppatierno commented on specification/trace/semantic_conventions/messaging.md
> +**[2]:** If the message destination is either a `queue` or a `topic`.
Ok. I will approve as it is for now ;-)

2022-12-07 10:29 UTC, ppatierno approved these changes

2022-12-08 21:55 UTC, blumamir approved these changes

2022-12-13 03:09 UTC, carlosalberto commented on schemas/1.16.0
> +  1.16.0:
This has to be moved to the (new) 1.17.0 schema file (almost this same file, aside the version change).

2022-12-13 03:12 UTC, carlosalberto commented
In general LGTM.

One small doubt I have is the usage of `source`, `destination` and `consumer` - in my mind, they map to `producer`, `broker` and `consumer`. Is this not the case always, I suspect, hence the usage of `source` and `destination` instead?

2022-12-14 19:17 UTC, lmolkova commented
> One small doubt I have is the usage of `source`, `destination` and `consumer` - in my mind, they map to `producer`, `broker` and `consumer`. Is this not the case always, I suspect, hence the usage of `source` and `destination` instead?

thanks for the review @carlosalberto !

`Producer` (if we add it) and `consumer`  namespaces describe the user app instances, while `destination` and `source` are remote addresses on broker.  If we add broker namespace, we'd still need to have separate `destination` and `source`  under it. 
E.g. `messaging.broker.destination.name` and `messaging.broker.destination.kind` (`messaging.broker.name` would be confusing and won't allow to express both original destination and actual source on consumer in one span).

[![](https://mermaid.ink/img/pako:eNotz8EKwjAMBuBXCTkp6AvsIDj3AIIeJtZDbaMrW5uRtoKo7251yymQ7w_JCw1bwgrvoscOjo0KUGp73gvbbEgusF5v3mO-Di52kBgsRRd0chygfUO9qIV7kuWUq_9aSDgngvbnTwVNw-a84xCzn5dCcYbcg-Am7CFyFkMzxxUW5rWz5bTXL64wdeRJYVVaq6VXqMKnOJ0TH57BYJUk0wrzaHWixunykcfqpodIny8orEyD?type=png)](https://mermaid.live/edit#pako:eNotz8EKwjAMBuBXCTkp6AvsIDj3AIIeJtZDbaMrW5uRtoKo7251yymQ7w_JCw1bwgrvoscOjo0KUGp73gvbbEgusF5v3mO-Di52kBgsRRd0chygfUO9qIV7kuWUq_9aSDgngvbnTwVNw-a84xCzn5dCcYbcg-Am7CFyFkMzxxUW5rWz5bTXL64wdeRJYVVaq6VXqMKnOJ0TH57BYJUk0wrzaHWixunykcfqpodIny8orEyD)

It also seems that all attributes we have so far on broker are covered with general span spec (`net.peer` namespace). 

Let's see if we have any additional thoughts on messaging WG.

2022-12-15 17:04 UTC, carlosalberto commented
@lmolkova We didn't have time to discuss this in the agenda today, but wanted to say your explanation makes sense. Can we include a small note about tour clarification? Better be safe than sorry IMHO (specially for people who lack messaging background ;) )

2022-12-19 18:46 UTC, lmolkova commented
> @lmolkova We didn't have time to discuss this in the agenda today, but wanted to say your explanation makes sense. Can we include a small note about tour clarification? Better be safe than sorry IMHO (specially for people who lack messaging background ;) )

@carlosalberto , makes sense! I added a few notes and references to the terminology section: https://github.com/open-telemetry/opentelemetry-specification/pull/2957/commits/b14f5bfa403daaab89f4b7358759bec129a06a2e

LMK what you think.

2022-12-20 15:44 UTC, joaopgrassi commented on specification/trace/semantic_conventions/messaging.md
>  A destination is usually identified by some name unique within the messaging system instance, which might look like a URL or a simple one-word identifier.
```suggestion
A destination is usually uniquely identified by name within the messaging system instance. Examples of a destination name would be a URL or a simple one-word identifier.
```

2022-12-20 15:44 UTC, joaopgrassi commented on specification/trace/semantic_conventions/messaging.md
>  A message that is sent (the send-operation is often called "*publish*" in this context) to a *topic* is broadcasted to all consumers that have *subscribed* to the topic.
Nit: Since the "queue" explanation is in a new line, would it make sense that the "topic" explanation follows the same? I ask because one is together with the other paragraph and the other not... one might think one is different than the other somehow?

2022-12-20 15:44 UTC, joaopgrassi commented on specification/trace/semantic_conventions/messaging.md
>  A message submitted to a queue is processed by a message *consumer* (usually exactly once although some message systems support a more performant at-least-once mode for messages with [idempotent][] p
```suggestion
A message that is sent to a *queue* is processed by a message *consumer* (usually exactly once although some message systems support a more performant at-least-once mode for messages with [idempotent][] processing).
```

Nit: So both "cases" use the same wording.

2022-12-20 15:44 UTC, joaopgrassi commented on specification/trace/semantic_conventions/messaging.md
> +Entity messages are received from is called **source** here. Messages can be routed within one or multiple brokers, so message's *source* and *destination* could be different.
I read the comment from @carlosalberto and your explanation and it all makes sense. But I'm a bit confused with the first sentence:

> Entity messages are received from is called **source** here. 

In this section, `destination` is clearly explained, but I feel `source` is not. Maybe we should describe it more? For ex, using the same line as `A source is usually...`?

And then at the end, we can have this sentence, to explain why we have `destination` and `source` (to address @carlosalberto concerns others might get confused as of why)? 

> Messages can be routed within one or multiple brokers, so message's *source* and *destination* could be different.

2022-12-20 15:44 UTC, joaopgrassi commented on specification/trace/semantic_conventions/messaging.md
>  A destination is usually identified by some name unique within the messaging system instance, which might look like a URL or a simple one-word identifier.
Just a nit/moving things around.

2022-12-20 16:05 UTC, jsuereth approved these changes

2022-12-22 02:34 UTC, lmolkova commented on specification/trace/semantic_conventions/messaging.md
> +Entity messages are received from is called **source** here. Messages can be routed within one or multiple brokers, so message's *source* and *destination* could be different.
@joaopgrassi, sure, I added a better explanation for the source.

2022-12-22 23:04 UTC, merged