Clarify specification compliance
open-telemetry/opentelemetry-specification pull request #2968
Opened 2022-11-18 19:38 UTC by reyang

Follow up https://github.com/open-telemetry/opentelemetry-go/issues/3399#issuecomment-1304056426 and https://github.com/open-telemetry/opentelemetry-go/issues/3399#issuecomment-1319009509.

2022-11-21 16:40 UTC, jack-berg approved these changes

2022-11-21 18:02 UTC, jsuereth approved these changes

2022-11-21 23:52 UTC, carlosalberto commented on specification/README.md
> +    or framework.
I'd even be more specific and mention which version from (1.16) - I think we mentioned something like this in the past for other features?

2022-11-21 23:52 UTC, carlosalberto commented
Also, let's mention this in the next Maintainers & Spec calls, so everybody is aware of this ;)

2022-11-21 23:52 UTC, carlosalberto approved these changes

2022-11-28 19:19 UTC, reyang commented on specification/README.md
> +    or framework.
Thanks for the suggestions! I've made the updates.

2022-11-28 19:23 UTC, ahayworth reviewed
This feels too broad to me - I would even go so far to say it's an overreaction.

I would feel much more comfortable if the specification instead carved out an exception for "experimental" work, so that we can encourage language SIGs to try new things to bring back to the broader community. Such experimental work should be clearly delineated as not part of the official SDK and subject to change / breakage at any point. We can put very stern warnings on such "experimental" extensions.

The language here is _very_ broad, and I'm worried that it'll have a significant chilling effect on experimentation by language groups. Oftentimes it's useful to have a working implementation of things proposed to spec groups, and we should not discount the useful benefits of having it easily installable alongside official SDKs. With sufficient warnings and segmentation, this can be safe and effective.

The proposal here will create more problems than it solves, because any SDK that attempts to still do experimental work now faces a very fuzzy test for compliance. I don't foresee this providing a lot of clarity to the group as a whole. I believe we should _not_ adopt this, and instead the Go SDK should simply not do what they were proposing to do. Does it really need to go farther?

2022-11-28 19:23 UTC, ahayworth commented on specification/README.md
> +  * Anything that is retrospecitive, for example, a feature/functionality which
```suggestion
  * Anything that is retrospective, for example, a feature/functionality which
```

2022-11-29 13:10 UTC, dyladan commented
I agree with ahayworth. By the current wording it is actually disallowed to do prototypes of unspecified features, experimental semantic conventions, etc. In the meeting before the holiday we discussed that the API may be very strict but the SDK should be allowed to do some experimentation.

This also disallows the types of "convenience API wrappers" which I know @tedsuo has been pushing for for a long time, but others also find quite valuable.

2022-11-29 13:31 UTC, dyladan requested changes
Requesting changes to indicate that I am not happy with the existing wording. I am not a spec approver so this is non-binding, but I am a maintainer. For details see my above comment.

2022-11-29 16:24 UTC, tedsuo commented on specification/README.md
> +* It MUST NOT provide additional features or functionalities that are not
I recommend that this section only apply to the instrumentation API.

2022-11-29 16:30 UTC, ahayworth commented on specification/README.md
> +* It MUST NOT provide additional features or functionalities that are not
> instrumentation API
By this you mean "the API" vs "the SDK", yes? "Instrumentation API" is a new term to me, and I want to make sure I understand what you mean by it. 😄

2022-11-30 08:47 UTC, cartermp commented on specification/README.md
> +    future.
It'd be good to understand what's meant by "very specific to a programming language, runtime or framework".

Two examples that comes to mind is how Java and Python both support annotations/decorators to make span creation nicer and how .NET and Python can tie ending a span to some notion of a scope with language constructs. Is each just "very specific to [the] programming language", or are these patterns to discuss and potentially add to the spec, since they're features available to multiple languages?

2022-11-30 17:10 UTC, tsloughter commented on specification/README.md
> +    future.
Personally I'd like to see those things proposed to the spec but in some new "convenience" (there was/is already a SIG and `#otel-convenience` channel on Slack) spec. Because not every language has decorators but those that do will all run into the same design decisions and it can help both users and developers.

2022-11-30 23:40 UTC, trask commented on specification/README.md
> +    future.
> Java and Python both support annotations/decorators to make span creation nicer

in Java at least, this functionality is not part of the OpenTelemetry API or SDK artifacts (instead they are provided by extensions), so my understanding is that this PR doesn't apply to them

2022-12-01 09:43 UTC, MikeGoldsmith commented
I also think that the wording is too limiting on experimentation and developing of features outside of the spec. There are many, many things that could potentially be added to the spec in the distant future so saying they cannot be added until the spec acknowledges them could be years apart. 

As others have said, there should be strict guidelines on how the API looks and what it does, but SDK features for convenience should be allowed. Otherwise we're going to have bare SDKs and promote everything else be some sort of extension which I think will lead to community confusion and frustration.

2022-12-01 20:22 UTC, cartermp commented on specification/README.md
> +    future.
A concern I have with this is that as we grow and get less innovators/early-adopters and more "normal" developers who are used to nice abstractions atop building blocks, it will be a must-have for opentelemetry to be successful here. If the answer is to pull in a bunch of extensions for each language, then that makes "extensions" a _de facto_ API in practice for a large developer population. I don't think that would be a good outcome.

2022-12-09 17:20 UTC, jmacd approved these changes

2023-01-26 04:30 UTC, reyang commented on specification/README.md
> +    future.
> It'd be good to understand what's meant by "very specific to a programming language, runtime or framework".
> 
> Two examples that comes to mind is how Java and Python both support annotations/decorators to make span creation nicer and how .NET and Python can tie ending a span to some notion of a scope with language constructs. Is each just "very specific to [the] programming language", or are these patterns to discuss and potentially add to the spec, since they're features available to multiple languages?

My suggestion is to not over specify things, instead we trust the judgement from maintainers. (Consider an example where a particular language has such specific feature at certain point, then later the feature got replicated/stolen by other languages - I don't think we want to cover all these cases in the spec)

2023-01-30 15:49 UTC, cartermp commented on specification/README.md
> +    future.
I think I'm comfortable with the current wording.

2023-02-22 17:30 UTC, reyang commented
@ahayworth @arminru @cartermp @dyladan @tedsuo @trask @tsloughter the PR has been updated to only enforce API (not SDK or anything else), PTAL.

2023-02-22 17:50 UTC, cartermp approved these changes
Looks good to me.

2023-02-22 18:16 UTC, arminru approved these changes

2023-02-22 18:16 UTC, arminru commented on specification/README.md
> +    formalized (release 1.16.0).
```suggestion
    formalized (release 1.19.0).
```

2023-02-22 20:00 UTC, trask approved these changes

2023-02-24 20:52 UTC, reyang commented
@dyladan you've blocked the PR, could you take a look at the updated version and see if that removes the concern you had?

@tedsuo @tsloughter does the PR look good to you after the updates?

2023-02-24 20:58 UTC, dyladan commented
I think this is an improvement but still doesn't allow for convenience APIs. Is that intentional? One example that is already available in several languages is `with_span`.

To be clear, I don't think that's a blocker but I want to make sure it was the intended outcome. In order to provide these features in the future I guess a "sugared API" module would need to be released separately that is specifically not a compliant API implementation?

2023-02-24 21:27 UTC, reyang commented
> I think this is an improvement but still doesn't allow for convenience APIs. Is that intentional? One example that is already available in several languages is `with_span`.

My thinking is that the convenience APIs might be scenario based and probably fit for separate components that users can optionally choose to use. If a particular programming language has some established pattern across majority of the scenarios, then it is already a "language specific" feature to me. I can give one example which is the "Dependency Injection" in .NET - there are folks who like the DI pattern and there are folks who do not, for ASP.NET Core applications it seems DI is the recommended path.

Regarding `with_span`, I actually consider this as "language specific", I treat "language specific" as the opposite of "language agnostic". `with_span` is useful for a subset of programming languages which leverage static scope or some syntactic sugar to make the code leaner.

2023-02-25 03:20 UTC, dyladan commented
> > I think this is an improvement but still doesn't allow for convenience APIs. Is that intentional? One example that is already available in several languages is `with_span`.
> 
> 
> 
> My thinking is that the convenience APIs might be scenario based and probably fit for separate components that users can optionally choose to use. If a particular programming language has some established pattern across majority of the scenarios, then it is already a "language specific" feature to me. I can give one example which is the "Dependency Injection" in .NET - there are folks who like the DI pattern and there are folks who do not, for ASP.NET Core applications it seems DI is the recommended path.
> 
> 
> 
> Regarding `with_span`, I actually consider this as "language specific", I treat "language specific" as the opposite of "language agnostic". `with_span` is useful for a subset of programming languages which leverage static scope or some syntactic sugar to make the code leaner.

IMO that is a dangerously broad definition of language specific and renders the rest of the text essentially meaningless.

2023-04-26 07:47 UTC, dyladan commented
> > > I think this is an improvement but still doesn't allow for convenience APIs. Is that intentional? One example that is already available in several languages is `with_span`.
> > 
> > 
> > My thinking is that the convenience APIs might be scenario based and probably fit for separate components that users can optionally choose to use. If a particular programming language has some established pattern across majority of the scenarios, then it is already a "language specific" feature to me. I can give one example which is the "Dependency Injection" in .NET - there are folks who like the DI pattern and there are folks who do not, for ASP.NET Core applications it seems DI is the recommended path.
> > Regarding `with_span`, I actually consider this as "language specific", I treat "language specific" as the opposite of "language agnostic". `with_span` is useful for a subset of programming languages which leverage static scope or some syntactic sugar to make the code leaner.
> 
> IMO that is a dangerously broad definition of language specific and renders the rest of the text essentially meaningless.

@reyang do you not agree?

2023-04-26 16:33 UTC, reyang commented
> @reyang do you not agree?

I disagree with the "dangerously broad definition" part, I personally feel it is _okay_ as an intentional ambiguity.
I agree that people could have different interpretations of what "language specific" means, I don't think we're in position to formally define what is "language specific".

2023-05-05 15:28 UTC, dyladan commented
If we're going to allow APIs to add helper methods specific to their langauge we should state that specifically. Also, what happens if the otel API adds a method with the same name in the future?

2023-05-21 03:16 UTC, closed without merging