[resource] add openshift platform to all supported cloud providers
open-telemetry/opentelemetry-specification pull request #2985
Opened 2022-11-24 08:02 UTC by frzifus

Signed-off-by: Benedikt Bongartz <bongartz@klimlive.de>

Fixes #2970

## Changes

Please provide a brief description of the changes here.

For non-trivial changes, follow the [change proposal process](https://github.com/open-telemetry/opentelemetry-specification/blob/main/CONTRIBUTING.md#proposing-a-change) and link to the related issue(s) and/or [OTEP(s)](https://github.com/open-telemetry/oteps), update the [`CHANGELOG.md`](https://github.com/open-telemetry/opentelemetry-specification/blob/main/CHANGELOG.md), and also be sure to update [`spec-compliance-matrix.md`](https://github.com/open-telemetry/opentelemetry-specification/blob/main/spec-compliance-matrix.md) if necessary.

Related issues #

Related [OTEP(s)](https://github.com/open-telemetry/oteps) #

2022-11-24 11:26 UTC, joaopgrassi requested changes

2022-11-24 11:26 UTC, joaopgrassi commented on CHANGELOG.md
> +- Extend Cloud Platform Enum with OpenShift entry for all supported cloud providers.
Could you please move this entry under the `### Resource` section?

2022-11-24 11:26 UTC, joaopgrassi commented on semantic_conventions/resource/cloud.yaml
> +              brief: Red Hat OpenShift on Azure Cloud
```suggestion
              brief: Azure Red Hat OpenShift
```

I'm not sure what we should put on `brief` but it looks like the "product name" to me. I saw for Alibaba you used the exact same name as state on their website, but for the others is a bit different. Should we stay with the "advertised" service/product name on the respective pages? If so, then the others also need to be adjusted.

2022-11-24 11:26 UTC, joaopgrassi commented on semantic_conventions/resource/cloud.yaml
> +              brief: Red Hat OpenShift on Google Cloud
I'm not familiar with this, but I noticed on GCP they have multiple "OpenShift options" like k8s engine, container platform, so I was wondering: With only this info here is it clear which one is being used?

2022-11-24 13:32 UTC, frzifus commented on CHANGELOG.md
> +- Extend Cloud Platform Enum with OpenShift entry for all supported cloud providers.
ups, that was a mistake

2022-11-24 13:32 UTC, frzifus commented on semantic_conventions/resource/cloud.yaml
> +              brief: Red Hat OpenShift on Azure Cloud
Ive here no strong opinion. Let me change that :+1:

2022-11-24 13:32 UTC, frzifus commented on semantic_conventions/resource/cloud.yaml
> +              brief: Red Hat OpenShift on Google Cloud
This are just different machine images for the same service with more or less installed things. calling it openshift should be fine. The internal Openshift api also only knows gcp.
![image](https://user-images.githubusercontent.com/10403402/203796164-3baf8abe-ac73-4e85-9e74-3d7d43552d56.png)

2022-11-25 09:53 UTC, joaopgrassi commented on semantic_conventions/resource/cloud.yaml
> +              brief: Red Hat OpenShift on Google Cloud
Thanks for explaining. Makes sense to me :)

2022-11-28 13:48 UTC, frzifus commented on semantic_conventions/resource/cloud.yaml
> +              brief: Red Hat OpenShift on Azure Cloud
i compared it with the others. Now it should fit :+1:

2022-11-29 09:53 UTC, joaopgrassi approved these changes
Looks good to the me!

2022-11-29 09:53 UTC, joaopgrassi commented on specification/resource/semantic_conventions/cloud.md
> +| `azure_openshift` | Azure Cloud Red Hat OpenShift |
Please re-generate the tables, so the build passes :)

2022-11-29 10:01 UTC, Oberon00 commented
This seems to be a non-native "Marketplace" feature. I don't really know how these work, is it built on top of other public-facing products of the platform? Do we actually need entries in the enum for that? If we include marketplace offerings, it might make the size of this enumeration potentially endless.

2022-11-29 16:54 UTC, frzifus commented
>  I don't really know how these work, is it built on top of other public-facing products of the platform?

Exactly, for example in aws openshift uses ec2 instances as nodes.

> Do we actually need entries in the enum for that?

I would argue - yes. Although openshift uses ec2 instances, they are abstracted away. Which in my view makes openshift the platform. Nothing else happens with eks, which uses ec2 instances and its is also listed as a platform on aws. In both cases its more beneficial to know the underlying platform that potentially caused issues is eks or openshift then ec2.

> If we include marketplace offerings, it might make the size of this enumeration potentially endless.

This depends very much on the definition of a platform. My feeling is that there are not many different platform solutions in the marketplaces.

2022-11-29 21:08 UTC, carlosalberto approved these changes

2022-11-29 21:09 UTC, carlosalberto commented
Overall LGTM although @Oberon00 raised a good point regarding the potential explosion of values here. Let's try to get more eyes on this, just to stay on the safe side.

2022-11-29 22:20 UTC, joaopgrassi commented
One could argue that we already have such things, for ex k8s managed service in cloud providers (Azure AKS). I think adding OpenShift is pretty much the same as those, so if we don't want this then should we keep Azure AKS and the like?

2022-12-01 17:10 UTC, frzifus commented
Whats need to move on?

2022-12-06 15:52 UTC, merged