Add tls semconv
open-telemetry/opentelemetry-specification pull request #2992
Opened 2022-11-30 13:55 UTC by svrnm

Fixes #1652

## Changes

Add trace/span semantic conventions for TLS/SSL.

I created a similar PR (#1854) a long while back that stalled eventually, I wanted to give it another try. Before doing so I did some scrubbing, added some references, removed some things where I was uncertain and updated a few things to match the APIs or RFCs (e.g. "not_before" and "not_after" are used for validity instead of valid_from and valid_to)

Reference implementation: https://github.com/open-telemetry/opentelemetry-js-contrib/blob/main/plugins/node/opentelemetry-instrumentation-net/src/instrumentation.ts#L121

References:
* [node.js tls api](https://nodejs.org/api/tls.html)
* [python api](https://docs.python.org/3/library/ssl.html)
* [SSL_get_version](https://www.openssl.org/docs/man1.1.1/man3/SSL_get_version.html#RETURN-VALUES)
* [rfc5246](https://datatracker.ietf.org/doc/html/rfc5246)
* [rfc5280](https://datatracker.ietf.org/doc/html/rfc5280)

2022-12-19 15:59 UTC, yurishkuro commented on semantic_conventions/trace/tls.yaml
> +      - id: peer.certificate.subject
So this becomes `tls.certificate.peer.certificate.subject`?

2022-12-19 16:01 UTC, yurishkuro approved these changes

2023-01-09 08:42 UTC, svrnm commented
anything missing, any additional feedback?

2023-01-10 09:14 UTC, joaopgrassi reviewed
Please also add a changelog entry: https://github.com/open-telemetry/opentelemetry-specification/blob/main/CHANGELOG.md?plain=1#L29

2023-01-10 09:14 UTC, joaopgrassi commented on semantic_conventions/trace/tls.yaml
> +      - id: protocol
Over all attributes, do you see any that would be `Required`? Because the requirement level is unspecified, all of them are `Recommended`. Is that intentional? I feel some of these could be Optional, as recommended should be added by default: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/common/attribute-requirement-level.md#recommended

2023-01-10 19:54 UTC, svrnm commented on semantic_conventions/trace/tls.yaml
> +      - id: protocol
thanks for calling this out, I added explicit levels to each attribute, here's my line of thinking:

* Required for `tls.protocol`, it's easy to collect, gives people an easy way to see that TLS was used, while having a low cardinality but still some good value (give me all services that use an outdated/insecure protocol version)
* Recommended for `tls.authorized`, since it is also helpful to find self-signed certificates
* Recommended for `*.certificate.serial_number`, since it allows to identify a certificate uniquely and could be used in a downstream processing to attach the other attributes as well (assuming the certificates are available) 
* Optional for everything else

Hope that makes sense, should such a rational be codified in the convention?

2023-01-18 14:24 UTC, svrnm commented on semantic_conventions/trace/tls.yaml
> +      - id: protocol
@joaopgrassi any more thoughts on that? TY.

2023-01-18 14:24 UTC, svrnm commented
> Please also add a changelog entry

done

2023-01-19 14:53 UTC, joaopgrassi commented on semantic_conventions/trace/tls.yaml
> +      - id: protocol
`tls.protocol` as required makes sense to me. 

`tls.authorized` and `*.certificate.serial_number` I'm not sure. Can they always be populated following the recommendations there? 

> if it's readily available and can be [efficiently populated](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/common/attribute-requirement-level.md#performance-suggestions). Instrumentations MAY offer a configuration option to disable Recommended attributes.

If we are sure they can, they I'd say it's OK.

2023-01-23 18:51 UTC, svrnm commented on semantic_conventions/trace/tls.yaml
> +      - id: protocol
@joaopgrassi thinking about it for some time I have to admit that I would not be able to make a generalized assumption here on if those fields would be able to be efficiently populated all the time. I have looked into some language docs on how to gather those attributes and overall it's possible to get them easily, but I am not sure for all the cases since TLS is often abstracted by a few layers and not everything might be accessible that easy.

2023-01-25 21:46 UTC, joaopgrassi commented on semantic_conventions/trace/tls.yaml
> +      - id: protocol
Yeah then I'd say Optional is probably a best bet.

2023-01-30 09:07 UTC, svrnm commented
@joaopgrassi thanks for your feedback!

2023-01-30 15:34 UTC, joaopgrassi approved these changes

2023-01-30 15:34 UTC, joaopgrassi commented on CHANGELOG.md
> +- Add semantic conventions for TLS/SSL encrypted communication
Can you please move it to the `Unreleased` section? I think now it's under `1.17`

2023-01-30 15:34 UTC, joaopgrassi commented on specification/trace/semantic_conventions/README.md
> +* [TLS/SSL](tls.md): Spans for TLS/SSL encrypted communication.
What do you think we call this: `For spans in TLS/SSL encrypted communication`?

2023-01-30 17:17 UTC, svrnm commented on CHANGELOG.md
> +- Add semantic conventions for TLS/SSL encrypted communication
oh, yes, thx! fixed

2023-02-01 19:16 UTC, svrnm commented
@open-telemetry/specs-trace-approvers PTAL, anything missing to finalize this?

2023-03-09 11:04 UTC, svrnm commented
updated from "optional" to "opt_in"

2023-03-21 07:46 UTC, svrnm commented
@open-telemetry/specs-trace-approvers any chance to get this merged or any further suggestions to improve?

2023-04-02 21:02 UTC, svrnm commented
unstale

2023-04-18 15:40 UTC, joaopgrassi commented
Now that the ECS OTEP was merged, do we also want maybe to adopt the attributes from there for these? https://www.elastic.co/guide/en/ecs/current/ecs-tls.html

2023-04-24 07:24 UTC, svrnm commented
> Now that the ECS OTEP was merged, do we also want maybe to adopt the attributes from there for these? https://www.elastic.co/guide/en/ecs/current/ecs-tls.html

@joaopgrassi 
makes sense to me, what would need to be done for that?

2023-04-25 02:57 UTC, trask commented
> > Now that the ECS OTEP was merged, do we also want maybe to adopt the attributes from there for these? https://www.elastic.co/guide/en/ecs/current/ecs-tls.html
> 
> 
> 
> @joaopgrassi 
> 
> makes sense to me, what would need to be done for that?

@joaopgrassi thx for bringing that up here!

@svrnm check out #3408 and #3409 for some examples, and see if it makes sense to rename the new attributes you've proposed to align with the ECS names.

We will bring over ECS attributes more proactively in the future, but for now we just want to avoid new divergence in cases where alignment makes sense.

2023-05-03 09:38 UTC, joaopgrassi approved these changes
LGTM, thanks for putting the effort on this! 

About the array attributes, I think we should be OK in adding them, as there's already some conventions using it like https://github.com/open-telemetry/opentelemetry-specification/blob/abf540c97c9f3cc901eb2d008df31f4797e3e871/semantic_conventions/resource/cloud_provider/aws/logs.yaml#L9 and also HTTP headers. 

I'm not an expert in this, so I don't know how crucial those array attributes are, but I guess the goal is to take over all ECS attributes. @trask @AlexanderWert what do you think?

2023-05-03 09:38 UTC, joaopgrassi commented on semantic_conventions/trace/tls.yaml
> +        brief: 'Also called an SNI, this tells the server which hostname to which the client is attempting to connect to. When this value is available, it should get copied to destination.domain.'
Not sure about the _it should be copied to destination.domain_. Should we maybe leave that part out for now? Also it somewhat contradicts with the `opt_in` as the text says if it's available it should be copied.

2023-05-03 09:38 UTC, joaopgrassi commented on specification/trace/semantic_conventions/tls.md
> +| `tls.version` | string | Numeric part of the version parsed from the original string of the negotiated [SSL/TLS protocol version](https://www.openssl.org/docs/man1.1.1/man3/SSL_get_version.html#RET
Nit/not blocking: Would be nice if the required attributes would show up first in the table.

2023-05-03 09:38 UTC, joaopgrassi commented on CHANGELOG.md
> +- Add semantic conventions for TLS/SSL encrypted communication
Should we also mention these are based on ECS in this title?

2023-05-03 12:01 UTC, svrnm commented on CHANGELOG.md
> +- Add semantic conventions for TLS/SSL encrypted communication
Agreed, this is lost in the spec itself but having it in the changelog would make this clear.

2023-05-04 08:42 UTC, svrnm commented on CHANGELOG.md
> +- Add semantic conventions for TLS/SSL encrypted communication
fixed via 3b47169

2023-05-04 08:43 UTC, svrnm commented on specification/trace/semantic_conventions/tls.md
> +| `tls.version` | string | Numeric part of the version parsed from the original string of the negotiated [SSL/TLS protocol version](https://www.openssl.org/docs/man1.1.1/man3/SSL_get_version.html#RET
done, fixed via 3b47169

2023-05-04 08:43 UTC, svrnm commented on semantic_conventions/trace/tls.yaml
> +        brief: 'Also called an SNI, this tells the server which hostname to which the client is attempting to connect to. When this value is available, it should get copied to destination.domain.'
Removed via 3b47169

2023-05-04 08:46 UTC, joaopgrassi commented on semantic_conventions/trace/tls.yaml
> +        brief: 'Also called an SNI, this tells the server which hostname to which the client is attempting to connect to. When this value is available, it should get copied to destination.domain.'
I saw you remove it completely which might be also OK, but I was more wondering if we could only remove the last part from the `brief`

>When this value is available, it should get copied to destination.domain.

But still leave the attribute in. What do you think? Sorry if I didn't communicate this clearly.

2023-05-04 08:57 UTC, svrnm commented on semantic_conventions/trace/tls.yaml
> +        brief: 'Also called an SNI, this tells the server which hostname to which the client is attempting to connect to. When this value is available, it should get copied to destination.domain.'
yup, that was a misunderstanding from my site, let me put it back then:-)

2023-05-04 09:00 UTC, svrnm commented on semantic_conventions/trace/tls.yaml
> +        brief: 'Also called an SNI, this tells the server which hostname to which the client is attempting to connect to. When this value is available, it should get copied to destination.domain.'
Reintroduced via 4e74727

2023-05-04 09:00 UTC, svrnm commented
> LGTM, thanks for putting the effort on this!
> 
> About the array attributes, I think we should be OK in adding them, as there's already some conventions using it like
> 
> https://github.com/open-telemetry/opentelemetry-specification/blob/abf540c97c9f3cc901eb2d008df31f4797e3e871/semantic_conventions/resource/cloud_provider/aws/logs.yaml#L9
> 
> and also HTTP headers.
> I'm not an expert in this, so I don't know how crucial those array attributes are, but I guess the goal is to take over all ECS attributes. @trask @AlexanderWert what do you think?

I added certificate and certificate_chain now, please give it a look.

2023-05-04 11:59 UTC, joaopgrassi approved these changes

2023-05-09 04:38 UTC, reyang commented
@svrnm heads up - most likely this PR will be closed, and we'll ask you to resubmit the PR in a new repo, please refer to https://github.com/open-telemetry/opentelemetry-specification/pull/3474#issuecomment-1539386505.

2023-05-11 12:50 UTC, svrnm commented
> @svrnm heads up - most likely this PR will be closed, and we'll ask you to resubmit the PR in a new repo, please refer to [#3474 (comment)](https://github.com/open-telemetry/opentelemetry-specification/pull/3474#issuecomment-1539386505).

I assumed that, let me find some time to bring it over to the new semconv repo!

2023-05-12 16:25 UTC, jsuereth requested changes
Please move this to https://github.com/open-telemetry/semantic-conventions

2023-05-15 08:58 UTC, closed without merging