Define "none" numeric value
open-telemetry/opentelemetry-specification pull request #3000
Opened 2022-12-02 09:03 UTC by Kielek

Fixes N/A

## Changes

Define "none" numeric value.

It will be useful to correctly set `OTEL_SPAN_ATTRIBUTE_COUNT_LIMIT` to no limit. For now, it should use int.maxvalue or similar values.

Related issues for enum handling #2102

2022-12-02 09:10 UTC, pellared approved these changes
👍

2022-12-02 15:08 UTC, Oberon00 requested changes
First, I don't think this is specific to numeric values. Booleans, strings, enums, etc., might accept "null" values just as well.
Second, there is no concept of "null value" in this environment specification, so this specification, as written now, has no meaning (or an unclear meaning).
Your goal seems to allow explicitly setting "no limit" in the limit configuration. You should add a more specific spec to that subsection, instead of the generic section here.

(PS: Congrats on creating PR #3000 🥳)

2022-12-02 18:31 UTC, reyang commented
> It will be useful to correctly set OTEL_SPAN_ATTRIBUTE_COUNT_LIMIT to no limit. For now, it should use int.maxvalue or similar values.

Why would someone want "no limit"? Related to https://github.com/open-telemetry/opentelemetry-specification/pull/2960#discussion_r1035360661.

2022-12-02 18:32 UTC, reyang requested changes
Need to understand why "no limit" is needed.

2022-12-05 10:29 UTC, pellared commented
> Need to understand why "no limit" is needed.

I agree that "unbounded limits" is a bad practice from "reliability" standpoint. But I do not see anything in the spec that disallows limitless configurations. Current default for `OTEL_ATTRIBUTE_VALUE_LENGTH_LIMIT` and `OTEL_SPAN_ATTRIBUTE_VALUE_LENGTH_LIMIT` is "no limit". Wouldn't changing it be a breaking change? 

If it is possible to have a unlimited configuration then we should allow setting it.

_I have no clear nor strong opinion 😆_

2022-12-15 07:20 UTC, Kielek commented
I am closing this issue per last .NET AutoInstrumentation Discussion with @carlosalberto.
For now, there will be no possibility to set no-limit options. It is considered as to unpredictable.

Instead we should consider to change default values for `OTEL_SPAN_ATTRIBUTE_VALUE_LENGTH_LIMIT` and `OTEL_ATTRIBUTE_VALUE_LENGTH_LIMIT `. I do not think that is is good practice to have default value which cannot be set by appropriate env. value.

2022-12-15 07:20 UTC, closed without merging