Update Tracing API: IsRecording wording
open-telemetry/opentelemetry-specification pull request #3020
Opened 2022-12-07 07:16 UTC by utezduyar

https://github.com/open-telemetry/opentelemetry-specification/issues/3006

Fixes #

## Changes

Please provide a brief description of the changes here.

For non-trivial changes, follow the [change proposal process](https://github.com/open-telemetry/opentelemetry-specification/blob/main/CONTRIBUTING.md#proposing-a-change) and link to the related issue(s) and/or [OTEP(s)](https://github.com/open-telemetry/oteps), update the [`CHANGELOG.md`](https://github.com/open-telemetry/opentelemetry-specification/blob/main/CHANGELOG.md), and also be sure to update [`spec-compliance-matrix.md`](https://github.com/open-telemetry/opentelemetry-specification/blob/main/spec-compliance-matrix.md) if necessary.

Related issues #

Related [OTEP(s)](https://github.com/open-telemetry/oteps) #

2022-12-09 16:15 UTC, MrAlias commented on specification/trace/api.md
> +Returns `true` if this `Span` has been started but not ended.
This statement does not take into account spans that are sampled to be non-recording. A span being started is not the only criteria for a span to be recorded.

2022-12-11 06:50 UTC, utezduyar commented on specification/trace/api.md
> +Returns `true` if this `Span` has been started but not ended.
Maybe I misinterpret your first sentence but I think sampled but non-recording is against the spec. https://opentelemetry.io/docs/reference/specification/trace/sdk/#shouldsample `The flag combination SampledFlag == true and IsRecording == false could cause gaps in the distributed trace, and because of this OpenTelemetry API MUST NOT allow this combination.`

My patch attempt is by me reverse engineering the golang SDK. Maybe the golang implementation is not complete but otherwise these 2 variants are how the API is implemented.

```
// IsRecording returns if this span is being recorded. If this span has ended
// this will return false.
func (s *recordingSpan) IsRecording() bool {
	if s == nil {
		return false
	}
	s.mu.Lock()
	defer s.mu.Unlock()

	return s.endTime.IsZero()
}
```

And if it is a non-recording span:

```
// IsRecording always returns false.
func (nonRecordingSpan) IsRecording() bool { return false }
```

Maybe something like this accounts the non-recording spans.
`Returns true for recording spans if this Span has been started but not ended. Returns false after the Span is ended or if the Span is a non recording span.`

Let me know what you think please.

2022-12-13 10:59 UTC, arminru requested changes

2022-12-13 10:59 UTC, arminru commented on specification/trace/api.md
> +Returns `true` if this `Span` has been started but not ended.
If you start a span but the sampler returns a negative sampling decision, the SDK will return a non-recording span that is not recording and not sampled. You still have a span in a "started" state, so the wording proposed here saying just "started but not ended" will not work, as it does not account for such non-recording spans (the second code snippet you cited).

See also https://opentelemetry.io/docs/reference/specification/trace/sdk/#recording-sampled-reaction-table and https://opentelemetry.io/docs/reference/specification/trace/sdk/#shouldsample ("Return value").

2022-12-13 13:04 UTC, utezduyar commented on specification/trace/api.md
> +Returns `true` if this `Span` has been started but not ended.
I believe I have updated the patch to reflect your comment. I believe it is you who will mark the conversation as "resolved".

2022-12-13 16:15 UTC, arminru commented on specification/trace/api.md
> +Returns `true` if this `Span` has been started but not ended.
Thanks, Umut!

While this is correct now, it references implementation details from the SDK specification and actually duplicates these statements, making the spec harder to maintain and breaking the distinction made on purpose. The API spec you are editing here defines what IsRecording means to users of the API, while the SDK spec defines what SDKs should do and return based on the sampling decision.
It might be a bit confusing at first but I think we should not mix these two together here.

If there is any clarification that can be made without referencing the SDK but defining better how to _interpret_ the values returned for IsRecording, feel free to propose something.

2022-12-13 18:10 UTC, jmacd approved these changes

2022-12-13 18:10 UTC, jmacd commented on specification/trace/api.md
> +using `SetAttributes`, status with `SetStatus`, etc will not perform if
```suggestion
using `SetAttributes`, status with `SetStatus`, etc will not perform when
```

2022-12-13 18:10 UTC, jmacd commented on specification/trace/api.md
> +`IsRecording` SHOULD consequently return `false` for ended Spans.
(side remark: The appearance of "usually" is ... unusual without a corresponding SHOULD statement. I wonder if we should replace "usually" with "SHOULD" and if not, why not?)

2022-12-13 18:30 UTC, yurishkuro requested changes

2022-12-14 07:31 UTC, utezduyar commented on specification/trace/api.md
> +`IsRecording` SHOULD consequently return `false` for ended Spans.
English is not my first language but shouldn't SHOULDs be SHALLS? And why upper case? 

I have been quite confused when I read this paragraph. What I got confused is "`it usually becomes non-recording...`" So there is an exception, seems like streaming applications. Then we have this: "`are one expected case where IsRecording cannot change after ending a Span.`" I have not seen this case in go SDK implementation. 

With my limited knowledge, I can agree with what you propose. "`After a Span is ended, it SHOULD become non-recording..`"

2022-12-14 07:36 UTC, utezduyar commented on specification/trace/api.md
> +Returns `true` if this `Span` has been started but not ended.
Thanks again. I just removed the the reference to the SDK. @yurishkuro has also suggested the same thing.

2022-12-14 07:48 UTC, utezduyar commented on specification/trace/api.md
> +Always returns `false` If this is a non-recording `Span` (Sampling
I am blank regarding how to address your comment. Any suggestions? 

We do mention about the behavior when recording and sampling flags are set under the section Sampling in the SDK. Maybe the SDK should be made more clear to reflect memory Vs export.

2022-12-14 10:09 UTC, Oberon00 commented on specification/trace/api.md
> +Always returns `false` If this is a non-recording `Span` (Sampling
IsRecording = false should mean that the data is discarded right away, i.e. nobody will (be able to) read it, not even in memory. It's an effectively no-op span.

2022-12-14 16:18 UTC, yurishkuro commented
My proposal to change the original lines 457-464:

A span is _**recording**_ (`IsRecording` returns `true`) when the data provided to it via functions like `SetAttributes`, `AddEvent`, `SetStatus` is captured in some form (e.g., in memory). When a span is not recording (`IsRecording` returns `false`), all this data is discarded right away, making the span effectively a no-op.

{move paragraph from L474 here}

After a `Span` is ended, it SHOULD become non-recording and its `IsRecording` SHOULD start consequently return `false`. The one known exception to this is streaming implementations of the API that do not keep local state and cannot change the value of `IsRecording` after ending the span.

2022-12-15 07:38 UTC, utezduyar commented
> 

I have mostly used your text, made couple of minor changes.

2022-12-15 17:54 UTC, arminru commented on specification/trace/api.md
> +`IsRecording` SHOULD consequently return `false` for ended Spans.
@utezduyar You can find details on the distinction and the casing in https://github.com/open-telemetry/opentelemetry-specification/tree/main/specification#notation-conventions-and-compliance and the RFCs it refers to.

2022-12-15 17:55 UTC, arminru commented on specification/trace/api.md
> +SHOULD start consequently return `false`. The one known exception to this is
```suggestion
SHOULD consequently return `false`. The one known exception to this are
```

2022-12-15 19:56 UTC, utezduyar commented on specification/trace/api.md
> +SHOULD start consequently return `false`. The one known exception to this is
This is & are twisting me. Are you sure it is "are"?

2022-12-15 20:12 UTC, yurishkuro approved these changes

2022-12-15 20:12 UTC, yurishkuro commented on specification/trace/api.md
> +This flag may be `true` despite the entire trace being sampled out. This
```suggestion
This flag may be `true` despite the entire trace not being sampled. This
```

2022-12-15 20:48 UTC, MrAlias commented on specification/trace/api.md
> +allows to record and process information about the individual Span without
```suggestion
allows information about the individual Span to be recorded and processed without
```

2022-12-15 20:48 UTC, MrAlias commented on specification/trace/api.md
> +SHOULD start consequently return `false`. The one known exception to this is
```suggestion
After a `Span` is ended, it SHOULD become non-recording and `IsRecording`
SHOULD always return `false`. The one known exception to this is
```

2022-12-15 20:48 UTC, MrAlias commented on specification/trace/api.md
> +SHOULD start consequently return `false`. The one known exception to this is
"The one known exception" is the singular subject, "is" correct in this case.

2022-12-15 21:12 UTC, MrAlias approved these changes

2022-12-16 00:46 UTC, yurishkuro commented
@arminru please re-check if you still require changes

2022-12-16 15:05 UTC, arminru approved these changes

2022-12-16 15:06 UTC, merged