Include effects of force flush in Sdk shutdown
open-telemetry/opentelemetry-specification pull request #3085
Opened 2023-01-09 03:44 UTC by legendecas

Fixes https://github.com/open-telemetry/opentelemetry-specification/issues/2983

## Changes

This aligns the metrics sdk spec with the trace spec that `Shutdown MUST include the effects of ForceFlush.`:  https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk.md#shutdown-1.

2023-01-12 16:22 UTC, MrAlias commented on specification/metrics/sdk.md
> +`Shutdown` MUST include the effects of `ForceFlush`.
This may not be appropriate as a requirement given there are already stable releases of the metric SDK. An audit of all the stable releases will be needed to ensure the already conform with this.

Otherwise.

```suggestion
`Shutdown` SHOULD include the effects of `ForceFlush`.
```

2023-01-12 16:47 UTC, jack-berg commented on specification/metrics/sdk.md
> +`Shutdown` MUST include the effects of `ForceFlush`.
I think this is in the wrong place. MeterProvider already needs to call `Shutdown` on all registered readers. I think its [MetricReader#Shutdown](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#shutdown-1) that should be updated with this clause. 

This would be consistent with tracing - the [link](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk.md#shutdown-1) included in the PR description is for `SpanProcessor#Shutdown`, rather than `TracerProvider#Shutdown`.

2023-01-13 06:08 UTC, legendecas commented on specification/metrics/sdk.md
> +`Shutdown` MUST include the effects of `ForceFlush`.
Thanks, fixed.

2023-01-13 06:08 UTC, legendecas commented on specification/metrics/sdk.md
> +`Shutdown` MUST include the effects of `ForceFlush`.
Thanks, fixed.

2023-01-13 13:48 UTC, jack-berg approved these changes

2023-01-15 23:39 UTC, reyang commented on specification/metrics/sdk.md
> +`Shutdown` SHOULD include the effects of `ForceFlush`.
Where is `ForceFlush`?

2023-01-15 23:40 UTC, reyang requested changes
It's unclear what/which `ForceFlush` does this PR refer to.

2023-01-16 06:03 UTC, legendecas commented on specification/metrics/sdk.md
> +`Shutdown` SHOULD include the effects of `ForceFlush`.
This statement is identical to the statement in [SpanProcessor.Shutdown](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk.md#shutdown-1) in trace sdk. Do you suggest that we should clarify the subject of the `ForceFlush` (and update the trace sdk spec too)?

2023-01-17 17:37 UTC, reyang commented on specification/metrics/sdk.md
> +`Shutdown` SHOULD include the effects of `ForceFlush`.
I mean, it's fair for SpanProcessor to say "Shutdown should include the effects of ForceFlush" because SpanProcessor has both Shutdown and ForceFlush. It is weird for MetricReader to say so because MetricReader doesn't have ForceFlush.

2023-01-18 02:00 UTC, legendecas commented on specification/metrics/sdk.md
> +`Shutdown` SHOULD include the effects of `ForceFlush`.
Thanks for the clarification. `MetricReader.ForceFlush` is being clarified at https://github.com/open-telemetry/opentelemetry-specification/pull/3084, since it is already mentioned in the spec.

2023-01-25 15:46 UTC, legendecas commented
Not stale, waiting for https://github.com/open-telemetry/opentelemetry-specification/pull/3084 landing first.

2023-02-09 03:17 UTC, closed without merging