Update Zipkin remoteEndpoint preferences
open-telemetry/opentelemetry-specification pull request #3087
Opened 2023-01-09 20:28 UTC by MrAlias

Do not reference semantic conventions that have been removed.

- The `net.peer.ip` attribute was removed: https://github.com/open-telemetry/opentelemetry-specification/pull/2614
  - Replace this with `net.sock.peer.addr` and or `net.sock.peer.name`
- The `http.host` attribute was removed: https://github.com/open-telemetry/opentelemetry-specification/pull/2469

2023-01-18 12:47 UTC, pellared approved these changes
Can you also update

https://github.com/open-telemetry/opentelemetry-specification/blob/025f8fc1a12dda35e42a25c96a0ca4e2c52e34c8/specification/logs/data-model.md?plain=1#L850

and 

https://github.com/open-telemetry/opentelemetry-specification/blob/025f8fc1a12dda35e42a25c96a0ca4e2c52e34c8/specification/logs/data-model.md?plain=1#L850

for consistency?

2023-01-18 15:56 UTC, MrAlias commented
> Can you also update
> 
> https://github.com/open-telemetry/opentelemetry-specification/blob/025f8fc1a12dda35e42a25c96a0ca4e2c52e34c8/specification/logs/data-model.md?plain=1#L850
> 
> and
> 
> https://github.com/open-telemetry/opentelemetry-specification/blob/025f8fc1a12dda35e42a25c96a0ca4e2c52e34c8/specification/logs/data-model.md?plain=1#L862
> 
> for consistency?

I would rather scope this PR to updating the Zipkin remote endpoint preferences. Maybe that is a good change for another PR?

2023-01-18 15:58 UTC, pellared commented
> I would rather scope this PR to updating the Zipkin remote endpoint preferences.

I am fine with this.

> Maybe that is a good change for another PR?

Let me know if you want to do it or I should create it.

2023-01-18 16:03 UTC, MrAlias commented
> Let me know if you want to do it or I should create it.

Yeah, please create one. Thanks!

2023-01-19 11:09 UTC, pellared requested changes

2023-01-19 11:09 UTC, pellared commented on specification/trace/sdk_exporters/zipkin.md
> +|4|net.sock.peer.addr & net.peer.port|[OpenTelemetry adopted attribute for remote socket address of the peer.](../semantic_conventions/span-general.md#general-network-connection-attributes)|
I am looking at this PR the second time and I have lost confidence in this line.
I think that if `net.peer.name` is will not defined then probably we won't have `net.peer.port` as well. Therefore use should probably use `net.sock.peer.addr` instead.

```suggestion
|4|net.sock.peer.addr & net.sock.peer.port|[OpenTelemetry adopted attribute for remote socket address of the peer.](../semantic_conventions/span-general.md#general-network-connection-attributes)|
```

2023-01-19 11:09 UTC, pellared commented on specification/trace/sdk_exporters/zipkin.md
> +|3|net.sock.peer.name|[OpenTelemetry adopted attribute for remote socket hostname of the peer.](../semantic_conventions/span-general.md#general-network-connection-attributes)|
You have forgotten to update https://github.com/open-telemetry/opentelemetry-specification/blob/638572cf21a94572a27810a29e463e24496388f9/specification/trace/sdk_exporters/zipkin.md?plain=1#L106

2023-01-27 09:22 UTC, pellared commented
@lmolkova PTAL

2023-01-27 17:19 UTC, lmolkova approved these changes
Thanks!

2023-01-27 17:29 UTC, reyang approved these changes

2023-01-27 18:46 UTC, carlosalberto commented
@pellared Is your changes request still valid?

2023-01-27 18:56 UTC, pellared approved these changes

2023-01-27 18:56 UTC, pellared commented
> @pellared Is your changes request still valid?

Comments addressed. Approved 👍

2023-02-07 06:20 UTC, Kielek approved these changes

2023-02-07 15:25 UTC, carlosalberto commented
cc @yurishkuro

2023-02-07 16:09 UTC, yurishkuro commented
tbh, I don't understand how to read that table. It gives OTEL names and OTEL definitions - how does that help in translating to Zipkin format? I would've expected either the equivalent Zipkin tag or the dedicated field in Zipkin data model.

2023-02-07 16:21 UTC, MrAlias commented
> tbh, I don't understand how to read that table. It gives OTEL names and OTEL definitions - how does that help in translating to Zipkin format? I would've expected either the equivalent Zipkin tag or the dedicated field in Zipkin data model.

The table is an ordered ranking. This PR does not introduce or advocate for the table, it only updates semantic conventions. The table currently contains semantic conventions that were removed. This removes the stale values and replaces them with the replacement semantic conventions. It is an editorial change.

cc @carlosalberto

2023-02-08 21:41 UTC, carlosalberto approved these changes

2023-02-09 16:39 UTC, merged