add SuppressTracing flag
open-telemetry/opentelemetry-specification pull request #3103
Opened 2023-01-13 21:20 UTC by tsloughter

Fixes #530 

## Changes

This PR proposes a new Context key to be used at Span creation time to disable creation of any child Spans. This feature is useful in cases like disabling tracing within an exporter when it calls the HTTP or grpc client.

The feature exists already in multiple implementations. 

Prior art:

- This PR is based on the PR from @dyladan but with the difference in how
  StartSpan operates when suppressed. https://github.com/open-telemetry/opentelemetry-specification/pull/1653

- Ruby: `untraced` https://github.com/open-telemetry/opentelemetry-ruby/pull/1412
- Javascript: `suppressTracing` / `unsuppressTracing` https://github.com/open-telemetry/opentelemetry-js/blob/main/packages/opentelemetry-core/src/trace/suppress-tracing.ts

### Why return the parent

My thinking here is that `Unsuppress` picks up where it left off. The user does
not end up with an invalid parent or, if valid spans were used in this PR
instead, with a parent that is not recorded.

I'm torn on the usefulness of this because usually the user would be instead
returning to the previous Context (Contexts being immutable) and have no need to
either `Unsuppress` or be tracking the parent.

### Why not suppress all signals

The plan I have is to add suppression for all signals, which can be wrapped in a
`SuppressSignals` or similar function. The reason is I think it would be very
common to want to suppress tracing and possibly metrics but would not want
suppression logging. In the example of not tracing an exporter you'd likely
still want any logs from the HTTP/grpc client in case something goes wrong.

### What about Propagation

That is an open question not covered by this PR yet. I think I've come around to
suppression not having an effect on propagation and leave it up to libraries to
support overriding the global propagator with a no-op propagator so the user is
able to disable propagation.

2023-01-13 22:03 UTC, reyang commented on specification/trace/api.md
> +- Set a `SuppressTracing` flag on a `Context` instance
Is there API to read/tell whether the `SuppressTracing` flag is set or not?

2023-01-13 22:11 UTC, tsloughter commented on specification/trace/api.md
> +- Set a `SuppressTracing` flag on a `Context` instance
Hehe, somehow missed that. Thanks :) -- adding a "Get the value ..." line to the spec.

2023-01-13 22:16 UTC, yurishkuro commented on specification/trace/api.md
> +MUST return the parent Span marked as non-recording, if one exists, otherwise
Parent span is not an input to StartSpan, so this MUST requirement imposes the need to keep some global registry of all open spans (instead of, as more common, making it the responsibility of the code to keep reference to the current span). The only viable implementation seems to be to return a new non-recording Span with _its context set to parent context_.

2023-01-13 22:16 UTC, yurishkuro commented on specification/trace/api.md
> +return an empty non-recording Span. Propagation MUST have the [Behavior of the
unclear what "Propagation" refers to - the actual propagation is not under the control of Tracer.StartSpan()

2023-01-13 22:16 UTC, yurishkuro commented on specification/trace/api.md
> +The `SuppressTracing` flag is for cases it may be useful to temporarily suppress
I would suggest to be more explicit with the scope of this flag: 
  * to suppress tracing of the current branch of the request workflow in the current process only
  * the flag must not be propagated to downstream services and must not affect their tracing decisions

2023-01-13 22:20 UTC, tsloughter commented on specification/trace/api.md
> +MUST return the parent Span marked as non-recording, if one exists, otherwise
StartSpan takes the parent Context which has the, if there is one, parent Span.

2023-01-13 22:21 UTC, tsloughter commented on specification/trace/api.md
> +return an empty non-recording Span. Propagation MUST have the [Behavior of the
Ah yup, I ended up deciding to remove that but forgot to actually do the removal.

2023-01-13 22:47 UTC, tsloughter commented on specification/trace/api.md
> +The `SuppressTracing` flag is for cases it may be useful to temporarily suppress
Ok. Yea, I took it as implied since there is no propagator for it, but probably a good idea to make it clear here.

2023-01-13 23:51 UTC, yurishkuro commented on specification/trace/api.md
> +return an empty non-recording Span.
> MUST return the parent Span marked as non-recording, if one exists, otherwise...

This is likely misleading. "if one exists" may be interpreted to refer to just "parent Span", not to "parent Span that is already not recording". Also, the otherwise part is underspecified because the new span must still present parent SpanContext. I would suggest

```suggestion
MUST return a non-recording Span with SpanContext equal to that of the parent Span (if one exists). If the parent Span exists and is already non-recording, it may be returned directly, as an optimization.
```

2023-01-13 23:52 UTC, yurishkuro commented on specification/trace/api.md
> +The `SuppressTracing` flag is for cases, within a single service, it may be
```suggestion
The `SuppressTracing` flag is for cases when, within a single service, it may be
```

2023-01-14 00:08 UTC, tsloughter commented on specification/trace/api.md
> +return an empty non-recording Span.
Thanks, agreed this reads better.

2023-01-17 16:39 UTC, reyang commented
Sharing what OpenTelemetry .NET has done:
1. A mechanism called SuppressInstrumentationScope.
2. SuppressInstrumentationScope can be used in exporters and other SDK components to prevent live-loop, e.g. the exporter calling HTTP stack which generates traces. https://github.com/open-telemetry/opentelemetry-dotnet/blob/ea5a25caac8217a71c4491b7a15ac02576b3e2cb/docs/trace/extending-the-sdk/MyExporter.cs#L32-L34
3. SuppressInstrumentationScope can also be used in a higher-level instrumentation library (e.g. gRPC) to suppress signals from a lower-level library (e.g. HTTP) https://github.com/open-telemetry/opentelemetry-dotnet/blob/ea5a25caac8217a71c4491b7a15ac02576b3e2cb/src/OpenTelemetry.Instrumentation.GrpcNetClient/Implementation/GrpcClientDiagnosticListener.cs#L90-L96

Related discussions https://github.com/open-telemetry/opentelemetry-dotnet/issues/809#issuecomment-658998836

2023-01-17 16:52 UTC, reyang requested changes
Can we do this in the SDK instead of the API?
In OpenTelemetry .NET the SDK has provided a mechanism which seems sufficient https://github.com/open-telemetry/opentelemetry-dotnet/pull/960.

2023-01-17 16:58 UTC, yurishkuro commented
@reyang the functionality may need to be available in instrumentation libraries, which are not supposed to be aware of the SDK

2023-01-19 04:14 UTC, trask commented
this is the mechanism that all of the Java Instrumentation uses: https://github.com/open-telemetry/oteps/pull/172

2023-01-19 07:14 UTC, Flarna commented
In JS some (but by far not all) instrumentations check the `suppress` context key and call `startSpan` only if it is not set.
SDK checks in `startSpan` and returns a `Noop(InvalidTraceId/SpanId)` in case it's set

In python it seems that the concrete instrumentations check if suppress context key is set and if if is set they do not even call `startSpan()`.
SDK seems to have no special handling of the suppressed context key.

I think we should add handling in SDK to avoid the needed that everyone has to check the context before calling `startSpan`.

We might also want to distinguish between suppressing nested/inner spans (e.g. HTTPS calls public, instrumented HTTP APIs internal) but keep child spans like DNS and propagation to other processes or suppress the complete subtrace which would include the need to propagate the suppress flag to avoid that receiver starts a new trace.

2023-01-19 10:02 UTC, reyang commented
> @reyang the functionality may need to be available in instrumentation libraries, which are not supposed to be aware of the SDK

Yep. I think there are two parts:
1. From the PR description "This feature is useful in cases like disabling tracing within an exporter when it calls the HTTP or grpc client." - I feel this part can be done purely in the SDK, without having to touch the API.
2. For instrumentation libraries - agree that it should not take dependency on the SDK. Based on the practice in OpenTelemetry .NET, it seems a combination of context API and some known "named slots" would also work. In addition, such approach seems to be addressing the problem for instrumentation authors while avoiding exposing an API and encouraging application developers from calling it.

2023-01-20 01:28 UTC, yurishkuro commented
@reyang a publicly accessible (via API) Context key to suppress tracing is a possible alternative, but the "obscurity" argument doesn't sit well with me (and it's also less type-safe than the dedicated methods). If someone has a valid need to suppress tracing this way, it seems strange to make the feature harder to find (i.e. it won't come up in auto-complete). It also bifurcates the way API users are asked to interact with the API, without actually reducing the mental model of the API surface.

2023-01-24 20:11 UTC, lmolkova commented
Based on the research I've done in 1767, each language SIG has (or had at the time I did it) has some version of a suppression flag 

(links are 1.5 years old)

- [python](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/63e7561931cd2d5e8edca9281c5156b9852eb348/instrumentation/opentelemetry-instrumentation-requests/src/opentelemetry/instrumentation/requests/__init__.py#L60)
- [.net](https://github.com/open-telemetry/opentelemetry-dotnet/blob/6b7f2dd77cf9d37260a853fcc95f7b77e296065d/src/OpenTelemetry/SuppressInstrumentationScope.cs) 
- [js](https://github.com/open-telemetry/opentelemetry-js/blob/c85fbe6682b9a8fd52e4b99bdbb079833b04e845/packages/opentelemetry-core/src/trace/suppress-tracing.ts)
- [java suppresses nested client spans by default](https://github.com/trask/opentelemetry-java-instrumentation/blob/9c1083b5410d2a1f2ece899bbcd0c933ac7f6bbd/instrumentation-api/src/main/java/io/opentelemetry/instrumentation/api/tracer/BaseTracer.java#L109) - changed to https://github.com/open-telemetry/oteps/pull/172
- [seems ruby does it](https://github.com/open-telemetry/opentelemetry-specification/issues/530#issuecomment-605462917)


Suppression flag works great to suppress the instrumentation of exporter calls, but for application/library instrumentation purposes, it's not expressive enough. 
E.g. ORM call instrumentation should only suppress DB spans, but not the protocol level (e.g. HTTP spans) underneath. At least there should be a way to achieve it. Hence the https://github.com/open-telemetry/oteps/pull/172

2023-02-09 03:17 UTC, closed without merging

2023-08-21 22:57 UTC, lathspell commented
Any chance that this gets re-opened as the problem is unsolved yet?

2024-04-23 09:09 UTC, dmathieu commented
As mentioned before, this is something that several SDKs are already doing. How about reopening the issue?

This would be interesting for Go as well, as we currently don't want to let folks override the `http.Transport` for OTLP HTTP exporters, to avoid having that exporter generate traces unexpectedly.
Being able to suppress tracing in the context would allow us to suppress tracing within the exporter, and to make the use of a custom exporter safe.