Fix typos and grammar in the OTLP spec
open-telemetry/opentelemetry-specification pull request #3121
Opened 2023-01-20 16:41 UTC by moonbox3

Fixes #3120 

## Changes

This PR fixes typos and grammatical errors in the OTLP spec. Additionally, there were several places where text contained passive voice. These were updated to active voice to make them easier to follow.

2023-01-20 16:41 UTC, moonbox3 commented
Does this change require a changelog?

2023-01-20 17:04 UTC, tigrannajaryan requested changes
Thank you for the fixes @moonbox3

Some of the changes DO change the meaning, so I am temporarily blocking to fix those.

2023-01-20 17:04 UTC, tigrannajaryan commented on specification/protocol/otlp.md
> -and implemented in a way that ensures that clients and servers that implement
What's wrong with "in a way that"?

2023-01-20 17:42 UTC, moonbox3 commented on specification/protocol/otlp.md
> +After sending the request, the client MAY wait until the server receives a response.
Will fix.

2023-01-20 17:43 UTC, moonbox3 commented on specification/protocol/otlp.md
> +network, such as when the client is an instrumented application and
"Such as" and "for example" are conveying the same thing.

2023-01-20 17:46 UTC, moonbox3 commented on specification/protocol/otlp.md
> +not yet acknowledge.
I'm trying to get away from passive voice, which the original was written in.

2023-01-20 17:47 UTC, moonbox3 commented on specification/protocol/otlp.md
> +not yet acknowledge.
Reverted to the original.

2023-01-20 17:49 UTC, moonbox3 commented on specification/protocol/otlp.md
> +network, such as when the client is an instrumented application and
You don't agree that "such as for example when the client is an instrumented application..." can be reduced to read better as: "such as when the client is an instrumented application..." ?

2023-01-20 18:01 UTC, moonbox3 commented on specification/protocol/otlp.md
> -and implemented in a way that ensures that clients and servers that implement
"In a way that ensures" felt too wordy so I wanted to rewrite it for clarity. I really want it to be "... OTLP must be designed and implemented to ensure that clients..." Do you agree?

2023-01-20 18:02 UTC, moonbox3 commented on specification/protocol/otlp.md
> -and implemented in a way that ensures that clients and servers that implement
I will just revert it...

2023-01-20 18:04 UTC, moonbox3 commented
> Thank you for the fixes @moonbox3
> 
> Some of the changes DO change the meaning, so I am temporarily blocking to fix those.

Thank you for your review, @tigrannajaryan. I appreciate it. I have addressed your comments/suggestions.

2023-01-23 17:36 UTC, moonbox3 commented
> Btw we don't use comma after `e.g.` nor `i.e.` in general - according to [Wiktionary](https://en.wiktionary.org/wiki/e.g.):
> 
> > "E.g." and its examples are typically set off from the rest of the sentence by punctuation. In US English, "e.g." is usually followed by a comma.[[2]](https://en.wiktionary.org/wiki/e.g.#cite_note-2) It is not followed by a comma in other English-speaking countries.
> 
> So we should probably stick to the comma-less form for now, given we already use that and, _technically_, it's not incorrect.

@carlosalberto Thank you for your comment. Is there a style guide I should be following?

2023-01-23 18:32 UTC, MrAlias commented on specification/protocol/otlp.md
> +If more appropriate, another gRPC status code MAY be used. Here is a
This changes "may" into a key word and changes semantic meaning. Is that intentional?

2023-01-23 18:32 UTC, MrAlias commented on specification/protocol/otlp.md
> +  client SHOULD record the error and may retry exporting the same data. For example, this can
This should follow the same wrapping length as the rest of the paragraph.

2023-01-23 18:32 UTC, MrAlias commented on specification/protocol/otlp.md
> +  client MUST NOT retry sending the same telemetry data. The client MUST drop the telemetry data.
This should follow the same wrapping length as the rest of the paragraph.

2023-01-23 18:32 UTC, MrAlias commented on specification/protocol/otlp.md
> +(i.e., when the server accepts only parts of the data and rejects the rest), the
```suggestion
(i.e. when the server accepts only parts of the data and rejects the rest), the
```

2023-01-23 18:32 UTC, MrAlias commented on specification/protocol/otlp.md
> +be treated according to HTTP specifications.
Are there multiple HTTP specifications?

2023-01-23 18:32 UTC, MrAlias commented on specification/protocol/otlp.md
> +In such a situation, the client SHOULD implement queuing, acknowledgment-handling
Adding the leading comma here makes the second sentence fragment appear as a contextual element. Which does not seem to be the original intent of the specification.

2023-01-23 19:08 UTC, moonbox3 commented on specification/protocol/otlp.md
> +destination (e.g., application -> agent -> collector -> backend). End-to-end
It seems it would be a good idea to add the "no comma needed after e.g." to some style guide in this project.

2023-01-23 19:13 UTC, moonbox3 commented on specification/protocol/otlp.md
> +If more appropriate, another gRPC status code MAY be used. Here is a
Didn't mean for may to be capitalized. Fixing.

2023-01-23 19:16 UTC, moonbox3 commented on specification/protocol/otlp.md
> +be treated according to HTTP specifications.
Sure, there exists more than one "specification." As an example, see: https://www.w3.org/Protocols/Specs.html

2023-01-23 19:58 UTC, moonbox3 commented on specification/protocol/otlp.md
> +In such a situation, the client SHOULD implement queuing, acknowledgment-handling
I don't agree that the comma makes the second sentence fragment appear as a contextual element. "In such situation" is an example of an introductory phrase or clause, which sets the stage for a sentence. A writer may use discretion to determine if the comma is needed.

2023-01-24 16:25 UTC, MrAlias commented on specification/protocol/otlp.md
> +In such a situation, the client SHOULD implement queuing, acknowledgment-handling
I think both can be true.

Is there a way to restructure this sentence to remove confusion and clarify the meaning? I'm still not 100% sure if this is a list of things that needs to be addressed "per destination" or if only the retry logic is "per destination".

2023-01-24 21:24 UTC, moonbox3 commented on specification/protocol/otlp.md
> +In such a situation, the client SHOULD implement queuing, acknowledgment-handling
I think that's a valid callout. This text is under the heading "Multi-Destination Exporting" so I understand it as:

"The client SHOULD implement (per destination): queuing, acknowledgement-handling, and retry logic."

2023-01-27 18:02 UTC, moonbox3 commented
@tigrannajaryan or @MrAlias can you please help review the final changes? Thank you.

2023-02-08 21:56 UTC, moonbox3 commented
I would prefer for this PR to not be closed due to lack of activity. Can I get some help on it, please? Thank you.

2023-02-16 23:43 UTC, MrAlias approved these changes

2023-02-20 15:52 UTC, carlosalberto approved these changes

2023-02-20 15:53 UTC, carlosalberto commented
Thanks @moonbox3 - looks good to go IMHO. 

cc @tigrannajaryan

2023-02-21 16:20 UTC, tigrannajaryan reviewed
Just 2 small comments left, the rest looks good to me.

2023-02-21 16:20 UTC, tigrannajaryan commented on specification/protocol/otlp.md
>  dependant. The server SHOULD choose a `retry_delay` value that is big enough to
>The server determines the value of the `retry_delay` and is implementation
>dependant.

Unclear what the `is` in the second part of the sentence refers to (the server? the value?).

2023-02-21 16:20 UTC, tigrannajaryan commented on specification/protocol/otlp.md
> +acknowledgment-handling, and retry logic. This ensures that servers do not
>In such a situation, the client SHOULD implement (per destination): queuing,  
>acknowledgment-handling, and retry logic.

I think this changed the meaning of what we want to say. The emphasis here is that all these capabilities must be implemented per destination, not that these capabilities must be implemented. Putting "per-destination" in parenthesis no longer conveys that important message.

2023-02-22 15:04 UTC, moonbox3 commented on specification/protocol/otlp.md
>  dependant. The server SHOULD choose a `retry_delay` value that is big enough to
I will revert to the original if it is confusing. I understand the "is" is referring to the value of the retry delay.

2023-02-22 15:07 UTC, moonbox3 commented on specification/protocol/otlp.md
> +acknowledgment-handling, and retry logic. This ensures that servers do not
I reverted to the original.

2023-02-22 15:09 UTC, moonbox3 commented
Thank you all for the help. @tigrannajaryan I addressed your final two comments. Thank you.

2023-02-22 15:49 UTC, tigrannajaryan approved these changes

2023-02-22 15:50 UTC, tigrannajaryan commented
Thank you @moonbox3 for making the spec clearer.

2023-02-22 17:27 UTC, merged