Add a recommendation to sanitize DB_STATEMENT in order to prever secu…
open-telemetry/opentelemetry-specification pull request #3127
Opened 2023-01-22 12:25 UTC by avzis

Add a recommendation to sanitize DB_STATEMENT in order to prevent security vulnerabilities.

Fixes #3104 

## Changes

Currently DB_STATEMENT parameter is collecting the full query that is being made to a DB.
I suggest adding a recommendation to sanitize this information by default, in order to prevent security vulnerabilities.

It is also possible to give users a way to disable the sanitization, if needed.

2023-01-23 13:30 UTC, joaopgrassi commented on CHANGELOG.md
> +- Add a recommendation to sanitize DB_STATEMENT by default.
I think this should be moved to the `Semantic Conventions` section of the changelog.

2023-01-23 13:30 UTC, joaopgrassi commented on semantic_conventions/trace/database.yaml
> +        note: The value may be sanitized to exclude sensitive information. It is recommended to sanitize the value by default in order to prevent security vulnerabilities.
I wonder if we shouldn't be more strict. Something like

> The value MUST be sanitized by default to avoid leaking sensitive information. Instrumentations may provide ways to turn off sanitation by the user.

2023-01-24 13:11 UTC, arminru commented on semantic_conventions/trace/database.yaml
> +        note: The value may be sanitized to exclude sensitive information. It is recommended to sanitize the value by default in order to prevent security vulnerabilities.
+1
I think leaking PII makes the intent clearer.
"prevent security vulnerabilities" sounds as if it was more about preventing SQL injection and such which is unrelated to this.

2023-01-24 13:16 UTC, arminru commented on semantic_conventions/trace/database.yaml
> +        note: The value may be sanitized to exclude sensitive information. It is recommended to sanitize the value by default in order to prevent security vulnerabilities.
It's not clear who this recommendation or even MUST is directed at.
Would this be the instrumentation's responsibility or should this be done by SDKs/processors/exporters/consumers?

2023-01-24 17:18 UTC, avzis commented on semantic_conventions/trace/database.yaml
> +        note: The value may be sanitized to exclude sensitive information. It is recommended to sanitize the value by default in order to prevent security vulnerabilities.
I was thinking it should be part of the instrumentation.

what do you think of the following:
`note: The value should be sanitized by default to exclude sensitive information. Instrumentations may provide ways to turn off sanitization by the user.`

2023-01-25 16:31 UTC, avzis commented on semantic_conventions/trace/database.yaml
> +        note: The value may be sanitized to exclude sensitive information. It is recommended to sanitize the value by default in order to prevent security vulnerabilities.
@arminru @joaopgrassi what do you think?

2023-01-25 17:33 UTC, arminru commented on semantic_conventions/trace/database.yaml
> +        note: The value may be sanitized to exclude sensitive information. It is recommended to sanitize the value by default in order to prevent security vulnerabilities.
How about this?

```suggestion
        note: This attribute may contain private or sensitive information. It is recommended to sanitize it to exclude such information. Ideally, this is already done by default by the instrumentation collecting it.
```

Note that a statement like this is not of any normative nature, however, but it stresses the problem to make instrumentation authors aware of it.

2023-01-27 16:46 UTC, joaopgrassi approved these changes

2023-01-27 16:49 UTC, joaopgrassi commented
@avzis I think this looks good.. I had my approve but then saw it's still in draft. Do you want to do more changes?

2023-01-27 18:54 UTC, carlosalberto approved these changes

2023-01-27 18:55 UTC, carlosalberto commented
This PR can stop being a draft btw (unless you plan to add more content, as Joao mentioned). That way you should way more reviews ;)

2023-01-29 08:48 UTC, yurishkuro requested changes
-1. 

I think this requirement is too onerous for the SDK implementors to support. The text does not even try to define what may constitute a sensitive information, because it is a hard problem, yet somehow the SDKs need to understand what's sensitive and what "sanitize" means.

In the issue discussion there was a suggestion to not log the statement by default and make the users opt-in into logging it. We could also make it their responsibility to provide a sanitizer function (with some basic choices possibly supported by the SDK). I think that would be a better approach.

2023-01-29 11:58 UTC, avzis commented
> -1.
> 
> I think this requirement is too onerous for the SDK implementors to support. The text does not even try to define what may constitute a sensitive information, because it is a hard problem, yet somehow the SDKs need to understand what's sensitive and what "sanitize" means.
> 
> In the issue discussion there was a suggestion to not log the statement by default and make the users opt-in into logging it. We could also make it their responsibility to provide a sanitizer function (with some basic choices possibly supported by the SDK). I think that would be a better approach.

This is phrased as a recommendation, therefor it is not a strict rule on how and how to implement it.
As a recommendation, it gives a guideline on the intended behavior that we want to achieve.
I agree that some implementations might decide to implement it in a bit different way, but I don't think that it collides with this recommendation.

I think that giving the users the responsibility to provide a sanitizer themself is quite a hard think to ask for.
And if we can come up with a general implementation that will work for most cases, and in this suggestion it is to hide the information on default, and display it on demand, is easy to manage.

On a side note, I opened another discussion about deciding how the sanitization should look like: #3150

2023-01-31 12:56 UTC, avzis commented
@yurishkuro 
This is the current state:
![image](https://user-images.githubusercontent.com/107620508/215764261-4a9e1a88-5cfb-4336-bb3c-4c0122935150.png)
So if I understand correctly, you want it to look something like this (not an official phrasing, just making sure):

[2] This attribute may contain private or sensitive information. It is recommended to sanitize it to exclude such information with either a custom-made sanitizer made by the client, or with a basic sanitizer provided by the SDK.
[3] Don't log the statement by default and make the users opt-in into logging it.

2023-02-08 14:16 UTC, avzis commented
not stale, updated the PR.

2023-02-08 14:53 UTC, yurishkuro approved these changes

2023-02-08 14:55 UTC, yurishkuro commented on specification/trace/semantic_conventions/database.md
> +**[2]:** This attribute may contain private or sensitive information. The instrumentation library should support receiving a sanitizer function that will handle said information.
Note: this description does not reflect the PR title. Should we actually say that collecting db statement should be explicitly opt-in (with a sanitizer function)?

2023-02-08 15:45 UTC, avzis commented on specification/trace/semantic_conventions/database.md
> +**[2]:** This attribute may contain private or sensitive information. The instrumentation library should support receiving a sanitizer function that will handle said information.
<img width="1168" alt="image" src="https://user-images.githubusercontent.com/107620508/217578092-9934b39e-eebd-41b2-a323-9300999065cb.png">


It is explained in the "Requierment Level" in section [3].
I can make it more explicit like;
`Disabled on default. If applicable, can be enabled via instrumentation configuration.`
What do you think?

2023-02-08 16:58 UTC, yurishkuro commented on specification/trace/semantic_conventions/database.md
> +**[2]:** This attribute may contain private or sensitive information. The instrumentation library should support receiving a sanitizer function that will handle said information.
ah, ok. "Conditionally required" sounds like the wrong classification though, elsewhere it's used to indicate "there may be an alternative attribute", which is true in the case too, but the "required" part feels wrong for an opt-in field.

2023-02-08 17:33 UTC, arminru commented on specification/trace/semantic_conventions/database.md
> +**[2]:** This attribute may contain private or sensitive information. The instrumentation library should support receiving a sanitizer function that will handle said information.
We also have `Optional` and I think that's exactly what you're looking for here:

> Instrumentations SHOULD populate the attribute if and only if the user configures the instrumentation to do so. Instrumentation that doesn't support configuration MUST NOT populate Optional attributes.

https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/common/attribute-requirement-level.md#optional

2023-02-08 17:33 UTC, arminru commented on CHANGELOG.md
> +- Disable DB_STATEMENT by default.
```suggestion
- Change `db.statement` to only be collected if explicitly configured.
```
Otherwise it looks as if this was about a configuration ENV_VAR.

2023-02-08 19:20 UTC, trask commented
Java instrumentation has a pretty aggressive default sanitization function.

It's not clear to me whether this PR is a recommendation against the Java instrumentation approach.

2023-02-08 21:51 UTC, yurishkuro approved these changes

2023-02-08 22:02 UTC, MrAlias commented on specification/trace/semantic_conventions/database.md
> +**[2]:** Not collected by default; can be enabled via instrumentation configuration. This attribute may contain private or sensitive information. The instrumentation library should support accepting
```suggestion
**[2]:** Not collected by default; can be enabled via instrumentation configuration. This attribute may contain private or sensitive information. The instrumentation library should support accepting a function that will sanitize the statement before recording it.
```

2023-02-08 22:09 UTC, MrAlias approved these changes

2023-02-09 03:43 UTC, trask commented on semantic_conventions/trace/database.yaml
> +          Not collected by default; can be enabled via instrumentation configuration.
I'd prefer more flexible language here to allow what Java Instrumentation is currently doing (which is to collect this by default using an aggressive sanitizer)

2023-02-09 08:07 UTC, Oberon00 commented on semantic_conventions/trace/database.yaml
> +          Not collected by default; can be enabled via instrumentation configuration.
This part of the note should be removed; it's already what "optional" means.

2023-02-12 11:42 UTC, blumamir commented on semantic_conventions/trace/database.yaml
> +          The instrumentation library should support accepting a function that will
Maybe "may" instead of "should"?
```suggestion
          The instrumentation library may support accepting a function that will
```

There are other legitimate options other than supplying sanitization function:
- [choosing a strategy from a close set of pre-implemented options](https://github.com/open-telemetry/opentelemetry-specification/issues/3104#issuecomment-1411297008) `"omit" \ "include" \ "obfuscate"`. This is friendly for configuring via file or environment variables where users cannot register a function.
- some libraries already give access to "sanitized" data by default so there might not be need to clean it further.
- instrumentation libraries can choose not to record the db statement at all if it's too complicated or risky.

2023-02-15 08:57 UTC, avzis commented
I think that with the current comments regarding making this suggestion more "friendly" to support every different instrumentation, it kinda missed the original idea - To have a stricter definition of how to handle db.statement in order to prevent leaks. 

Do you think there is a value in adding this PR in this form, or we should wait until there will be a WG for the DB Semantic Convention, and we will try to discuss this in a more formal way?

2023-02-17 12:00 UTC, carlosalberto commented on semantic_conventions/trace/database.yaml
> +          The instrumentation library should support accepting a function that will
I think `should` here is probably closer to the desired attempt (after all, a `should` is a strong recommendation only).

2023-02-17 12:01 UTC, carlosalberto commented
@avzis I will present this next Tuesday at our Spec SIG to discuss the last details and hopefully we can make progress soon after that.

2023-03-01 23:13 UTC, carlosalberto commented
Not stale - let's (finally) reserve cycles to discuss this next Tuesday in the Spec call.

2023-03-07 16:05 UTC, pellared approved these changes

2023-03-07 16:44 UTC, trask submitted a review, later dismissed
I'd prefer more flexibility in the language because currently this PR makes the existing Java instrumentation non-compliant (the existing Java instrumentation captures sanitized `db.statement` by default)

2023-03-07 16:48 UTC, pellared commented on semantic_conventions/trace/database.yaml
> +        requirement_level: optional
Side note: You never know if the sanitization is good enough for the user. E.g. I do not think you are sanitizing table names 😅

2023-03-07 17:01 UTC, trask commented on semantic_conventions/trace/database.yaml
> +        requirement_level: optional
> You never know if the sanitization is good enough for the user

ya, though this argument could be made for a lot of OTel attributes (e.g. `http.target`)

2023-03-07 19:30 UTC, dubonzi commented
At the moment the Go's MongoDB instrumentation doesn't sanitize the statement. I think having it disabled by default unless the instrumentation implements sanitization would be best.

As I mentioned in https://github.com/open-telemetry/opentelemetry-specification/issues/3104, I hard to warn another team at work about this since they deal with a lot of sensitive data and were in the process of migrating to open telemetry.

2023-03-28 13:57 UTC, carlosalberto commented
Trying to revive this PR so we get it along the finish line: in summary, what would make everyone happy _now_ would be: 

1. Optional AND
2. SHOULD not be collected by default if there's no sanitization AND
3. Include in all cases an option to completely disable its collection.

(Can later iterate on the `omit` / `obfuscate` / `include` options, or even more aggressive approaches)

2023-03-29 02:36 UTC, trask commented
Do we need 1 or 3?

Would 2 alone would make everyone happy for now?

> 2. SHOULD not be collected by default if there's no sanitization

2023-03-29 05:29 UTC, pellared commented
How about only:

> MUST not be collected by default if there's no sanitization

I am aware that it is not backwards compatible, but I find it as a security bug by design 😉

2023-03-30 04:23 UTC, trask commented
> > SHOULD not be collected by default if there's no sanitization
> 
> I would prefer to change it to a "MUST". I am aware that it is not backwards compatible, but I find it as a security bug by design.

This makes sense to me.

Also I think it the [Recommended](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/common/attribute-requirement-level.md#conditionally-required) attribute requirement level probably makes more sense now instead of [Conditionally Required](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/common/attribute-requirement-level.md#conditionally-required).

@avzis after making these last changes, I suggest to re-request all of the reviews, since the PR has changed significantly since the original approvals.

2023-03-30 11:46 UTC, joaopgrassi commented
Not a blocking comment but: if we go with recommended, I wonder if it wouldn't be clearer to change the text to something like: 

> Should only be collected by default when instrumentations have sanitization that excludes sensitive information

It might be just me, but I find this easier to read and interpret then the current version with multiple "negations" (not be collect... no sanitization..)

2023-04-02 22:08 UTC, pellared approved these changes

2023-04-04 02:19 UTC, trask commented on semantic_conventions/trace/database.yaml
>            conditionally_required: >
I think it the [Recommended](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/common/attribute-requirement-level.md#conditionally-required) attribute requirement level probably makes more sense now instead of [Conditionally Required](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/common/attribute-requirement-level.md#conditionally-required).

```suggestion
          recommended: >
```

2023-04-04 14:14 UTC, carlosalberto approved these changes

2023-04-04 15:00 UTC, trask approved these changes

2023-04-04 15:59 UTC, joaopgrassi approved these changes

2023-04-04 16:04 UTC, pellared approved these changes

2023-04-05 22:08 UTC, carlosalberto commented
@trask I will merge this and make it part of the April release, unless you think we should hold it for be May one. Let me know what you think.

2023-04-05 22:37 UTC, trask commented
> @trask I will merge this and make it part of the April release

👍

2023-04-06 17:35 UTC, merged