Document limitations on span recording
open-telemetry/opentelemetry-specification pull request #3152
Opened 2023-01-27 18:52 UTC by abitrolly

Fixes #

## Changes

Please provide a brief description of the changes here.

For non-trivial changes, follow the [change proposal process](https://github.com/open-telemetry/opentelemetry-specification/blob/main/CONTRIBUTING.md#proposing-a-change) and link to the related issue(s) and/or [OTEP(s)](https://github.com/open-telemetry/oteps), update the [`CHANGELOG.md`](https://github.com/open-telemetry/opentelemetry-specification/blob/main/CHANGELOG.md), and also be sure to update [`spec-compliance-matrix.md`](https://github.com/open-telemetry/opentelemetry-specification/blob/main/spec-compliance-matrix.md) if necessary.

Related issues #

Related [OTEP(s)](https://github.com/open-telemetry/oteps) #

2023-01-27 19:17 UTC, reyang requested changes
It's unclear what "real-time tracking" means.

The wording "impossible" seems inaccurate to me - when a span started, the span processor will be notified, it is just the current exporter and protocol which don't support the concept of having separate data that represents start and stop events (or the SpanEvent which is being added). Maybe something like "it is not currently supported".

2023-01-27 19:27 UTC, yurishkuro commented on specification/protocol/otlp.md
> +It is impossible to send incomplete spans, so if the span failed to complete for
Why is it impossible?

2023-01-27 19:28 UTC, reyang commented on specification/protocol/otlp.md
> +It is impossible to send incomplete spans, so if the span failed to complete for
I just asked the same question 😆 https://github.com/open-telemetry/opentelemetry-specification/pull/3152#pullrequestreview-1273314619

2023-01-27 19:42 UTC, abitrolly commented on specification/protocol/otlp.md
> +It is impossible to send incomplete spans, so if the span failed to complete for
> It's unclear what "real-time tracking" means.

Watching spans in real time. When you have a long running task, and you can see its span and parent span before they are finished. See them the middle of the run. To trace long running jobs.

2023-01-27 19:51 UTC, abitrolly commented on specification/protocol/otlp.md
> +It is impossible to send incomplete spans, so if the span failed to complete for
> Why is it impossible?

Like @reyang said "it is just the current exporter and protocol which don't support the concept of having separate data that represents start and stop events". Protocol doesn't support sending span with no end attribute. That's why it is impossible to trace spans that were not completed using this protocol.

2023-01-27 20:30 UTC, yurishkuro commented on specification/protocol/otlp.md
> +It is impossible to send incomplete spans, so if the span failed to complete for
First, separate concepts for start and stop events are not required for that. I feel like the only limitation is the restrictions placed on the `end_time_unix_nano` field, i.e. if it's allowed to be 0 to indicate an incomplete span, then no other changes in the protocol are required to support the use case you describe.

2023-01-27 21:29 UTC, abitrolly commented on specification/protocol/otlp.md
> +It is impossible to send incomplete spans, so if the span failed to complete for
@yurishkuro does protocol specify that 0 in end time indicates an incomplete span? Does it specify that incomplete spans are parents of all subsequent spans? Does it specify how to finish incomplete spans? If incomplete spans should be rendered?

2023-01-27 21:48 UTC, yurishkuro commented on specification/protocol/otlp.md
> +It is impossible to send incomplete spans, so if the span failed to complete for
It doesn't allow 0 as end time in the current version. it's in the field comments, which are technically not enforced at the protocol level, so is it _possible_ to export incomplete span and define the merge semantics. 

You are proposing a very strong and final-sounding clarification, and I don't think the current state of the protocol warrants that, it's not a fundamental limitation of the protocol. I would prefer a softer wording, like  "not currently supported" or "not defined yet", like @reyang said.

2023-01-27 22:33 UTC, reyang commented on specification/protocol/otlp.md
> +It is impossible to send incomplete spans, so if the span failed to complete for
> > It's unclear what "real-time tracking" means.
> 
> Watching spans in real time. When you have a long running task, and you can see its span and parent span before they are finished. See them the middle of the run. To trace long running jobs.
> 
> EDIT: Also to trace long running jobs that were in the end terminated by timeout or in any other way where end of span was not reached, not recorded, not sent.

Got it, thanks @abitrolly! Maybe this can be a solution https://github.com/open-telemetry/opentelemetry-specification/blob/main/experimental/trace/zpages.md?

I believe spans are not designed for long running operations (e.g. I don't feel span is the right tool to track a batch job which runs for 5 hours).

2023-01-28 05:48 UTC, abitrolly commented on specification/protocol/otlp.md
> +It is impossible to send incomplete spans, so if the span failed to complete for
@yurishkuro maybe there is a better page to document the OpenTelementry limitations? I thought that protocol encompasses all interactions between tools. I would actually prefer to define actual solution rather than document limitations. For me the good solution is that makes end time optional, not relying on specific value to be set.

2023-01-28 05:55 UTC, abitrolly commented on specification/protocol/otlp.md
> +It is impossible to send incomplete spans, so if the span failed to complete for
@reyang zPages is a bad alternative, because requires polling over HTTP. Not all long running processes that needs to be traced expose web server. Think  CI/CD pipelines for example.

If OpenTelemetry is a replacement for all other tracing protocols, it should support this tracing scenario firsthand (https://github.com/open-telemetry/opentelemetry-specification/pull/2930).

2023-01-29 10:42 UTC, abitrolly commented on specification/protocol/otlp.md
> +It is impossible to send incomplete spans, so if the span failed to complete for
@yurishkuro if OLTP is going to be labelled stable, this feature won't find its place in the spec, and spec limitations need to be described.

2023-02-13 03:18 UTC, closed without merging