Rename http.user_agent to user_agent.full
open-telemetry/opentelemetry-specification pull request #3190
Opened 2023-02-09 00:29 UTC by trask

Fixes #3180

## Changes

Renames `http.user_agent` to `user_agent.full`.

2023-02-14 03:18 UTC, reyang approved these changes

2023-02-14 10:25 UTC, arminru commented on schemas/1.18.0
> +              http.user_agent: user_agent.original
```suggestion
  1.19.0:
    spans:
      changes:
        # https://github.com/open-telemetry/opentelemetry-specification/pull/3190
        - rename_attributes:
            attribute_map:
              http.user_agent: user_agent.original
  1.18.0:
```

2023-02-14 10:26 UTC, arminru commented on schemas/1.18.0
> +              http.user_agent: user_agent.original
Ah sorry, that was too quick.
You'll actually need to leave the `1.18.0` file as-is, copy it over to a new `1.19.0` schema and there apply the change I suggested.

2023-02-14 16:23 UTC, MSNev approved these changes

2023-02-14 16:24 UTC, MSNev commented
Do we want to include removal / renaming of `browser.user_agent` as part of this or as a separate PR?

2023-02-14 16:39 UTC, trask commented
> Do we want to include removal / renaming of `browser.user_agent` as part of this or as a separate PR?

@MSNev I added to this PR, ptal 👍

2023-02-14 18:09 UTC, MSNev approved these changes

2023-02-15 13:07 UTC, carlosalberto commented on schemas/1.19.0
> +              browser.user_agent: user_agent.original
`browser.agent` should go into a `resources` section, rather than `spans` - see https://github.com/open-telemetry/oteps/blob/main/text/0152-telemetry-schemas.md#resources-section

2023-02-15 13:07 UTC, carlosalberto approved these changes

2023-02-16 01:10 UTC, trask commented on schemas/1.19.0
> +    Resources:
I have no idea why this has to be uppercase `Resources`, but schema validation fails with lowercase `resources`

2023-02-16 13:37 UTC, carlosalberto commented on schemas/1.19.0
> +    Resources:
Weird... it _seems_ the error comes from [build tools](https://github.com/open-telemetry/build-tools/blob/main/schemas/main.go#L30) which _seems_ to use [OTel Go schema parsing](https://github.com/open-telemetry/opentelemetry-go/blob/schema/v0.0.3/schema/v1.1/parser.go#L46) which reports this as a "simple" decoding problem.

Is `resources` a reserved keyword perhaps? Maybe @MrAlias @MadVikingGod know?

2023-02-16 23:22 UTC, MrAlias commented on schemas/1.19.0
> +    Resources:
Pretty sure it comes from this: https://github.com/open-telemetry/opentelemetry-go/blob/59daa05b19aa49f90f4b833871a89f3329b40872/schema/v1.1/ast/ast_schema.go#L45

There is no field tag specifying an alternate yaml identified so it uses the default field name "Resource". That could be updated to accept lowercase if needed (it would break existing uppercase though)

2023-02-16 23:57 UTC, trask commented on schemas/1.19.0
> +    Resources:
do u know why `spans` (lowercase) works currently, even though it's uppercase `Spans` in the linked code similar to `Resources`?

2023-02-17 00:07 UTC, MrAlias commented on schemas/1.19.0
> +    Resources:
Right. I think it's because it is the field type as well. I'd need to experiment to be sure though.

2023-02-17 01:03 UTC, MrAlias commented on schemas/1.19.0
> +    Resources:
There seems to be something more complex than I was thinking going on here. Our test data uses a lowercase `resource` and all our tests pass.

https://github.com/open-telemetry/opentelemetry-go/blob/59daa05b19aa49f90f4b833871a89f3329b40872/schema/v1.1/testdata/valid-example.yaml#L50

2023-02-17 16:55 UTC, MrAlias commented on schemas/1.19.0
> +    Resources:
Looking into this further, I think by switching to `Resources` you are entirely ignoring this section. I haven't verified this, but I did find the answer to why the original parsing was failing.

Originally you structured the `resource` section like this:

```yaml
    resources:
      changes:
        # https://github.com/open-telemetry/opentelemetry-specification/pull/3190
        - rename_attributes:
            attribute_map:
              browser.user_agent: user_agent.original
```

But the AST for the resource section doesn't have a "attribute_map" field like the spans do. If you updated to the following it should work:

```yaml
    resources:
      changes:
        # https://github.com/open-telemetry/opentelemetry-specification/pull/3190
        - rename_attributes:
          browser.user_agent: user_agent.original
```

2023-02-17 16:56 UTC, MrAlias commented on schemas/1.19.0
> +    Resources:
cc @tigrannajaryan

2023-02-17 17:04 UTC, MrAlias commented on schemas/1.19.0
> +    Resources:
> Looking into this further, I think by switching to `Resources` you are entirely ignoring this section. I haven't verified this ...

Ah, it does indeed look to silently drop the `Resources` section: https://github.com/go-yaml/yaml/issues/136

I think we may need to enable this: https://pkg.go.dev/gopkg.in/yaml.v3#Decoder.KnownFields

2023-02-17 17:28 UTC, MrAlias commented on schemas/1.19.0
> +    Resources:
https://github.com/open-telemetry/opentelemetry-go/issues/3742

2023-02-17 17:53 UTC, MrAlias commented on schemas/1.19.0
> +              browser.user_agent: user_agent.original
```suggestion
    resources:
      changes:
        # https://github.com/open-telemetry/opentelemetry-specification/pull/3190
        - rename_attributes:
          browser.user_agent: user_agent.original
```

2023-02-17 17:53 UTC, lmolkova approved these changes

2023-02-21 16:41 UTC, MSNev approved these changes

2023-02-21 17:38 UTC, pyohannes approved these changes

2023-02-22 15:08 UTC, carlosalberto commented
@open-telemetry/specs-approvers Please review. Hopefully this doesn't take anybody by surprise, etc.

2023-02-22 15:57 UTC, tigrannajaryan requested changes
Blocking briefly to decide what to do with https://github.com/open-telemetry/opentelemetry-specification/issues/3245 before merging this PR.

2023-02-24 18:49 UTC, tigrannajaryan commented
FYI, the schema checker tool is incorrect. I am fixing it now. Don't merge this.

2023-02-24 18:50 UTC, tigrannajaryan commented on schemas/1.19.0
> +          browser.user_agent: user_agent.original
This needs to be under a `attribute_map` subkey. The schema checker tools is incorrect, I am fixing it.

2023-02-27 18:08 UTC, tigrannajaryan commented
Fix submitted to build tools: https://github.com/open-telemetry/build-tools/pull/138

2023-02-27 22:38 UTC, tigrannajaryan commented
Here is the PR to update to latest build-tools which includes the fix to schema check tool: https://github.com/open-telemetry/opentelemetry-specification/pull/3259

Once that is merged this PR needs to be rebased.

2023-02-27 22:39 UTC, tigrannajaryan commented
This can be rebased now and the schema check should pass.

2023-02-27 22:58 UTC, trask commented
@tigrannajaryan thx for fixing this, schema check is passing now. can you remove your "request changes"? thx!

2023-02-28 15:57 UTC, carlosalberto commented
@trask Conflicts need to be solved but otherwise (it sounds like) we are ready to merge this.

2023-03-02 20:47 UTC, carlosalberto commented
Merging after letting this PR settle and get some more attention.

2023-03-02 20:47 UTC, merged