Add requirement to use X-Ray propagation for aws-sdk client calls
open-telemetry/opentelemetry-specification pull request #3212
Opened 2023-02-15 20:49 UTC by tylerbenson

X-Ray is necessary because it is the only format currently supported by AWS to allow context propagation through AWS managed services, for example SNS -> SQS -> Lambda, or S3 -> Lambda.

2023-02-15 23:10 UTC, yurishkuro approved these changes

2023-02-16 11:54 UTC, carlosalberto approved these changes

2023-02-16 11:54 UTC, carlosalberto commented
Changelog entry please ;)

2023-02-16 14:43 UTC, Oberon00 reviewed
> X-Ray is necessary because it is the only format currently supported by AWS to allow context propagation through AWS managed services, for example SNS -> SQS -> Lambda

At Dynatrace, we have actually been using W3C-tracecontext-based propagation successfully with this scenario, as SNS message attributes are mapped to SQS message attributes or
transported as part of the message body (JSON payload). Our backend relies on additional information in the tracestate field that cannot be transported over the X-Ray header.
So we rely on the fact that many existing implementations of this (e.g. [Node.Js](https://github.com/open-telemetry/opentelemetry-js-contrib/blob/main/plugins/node/opentelemetry-instrumentation-aws-sdk/src/services/MessageAttributes.ts), [Ruby](https://github.com/open-telemetry/opentelemetry-ruby-contrib/blob/main/instrumentation/aws_sdk/lib/opentelemetry/instrumentation/aws_sdk/handler.rb), Python)
use (non-system) message attributes and the configured global propagator for this.

If these were changed to only use X-Ray, it would break these scenarios for Dynatrace and our customers (the scenarios are documented e.g. here: https://www.dynatrace.com/support/help/shortlink/opentel-lambda#python-sqs-sns). For example the Python PR open-telemetry/opentelemetry-python-contrib#1673 that probably results from this Spec PR would be problematic for us (we'll also comment there).

> or S3 -> Lambda.

This is indeed only possible with using X-Ray headers (but doesn't invalidate the previous scenario)

I propose that we clarify that additional propagation mechanisms MAY be used where it makes sense (e.g. messaging operations).

Also, I think there is no need to use the strong MUST which basically bans instrumentations from offering an option to disable X-Ray propagation.

2023-02-16 16:31 UTC, tylerbenson commented on specification/trace/semantic_conventions/instrumentation/aws-sdk.md
> +When making outgoing calls using an aws-sdk, AWS X-Ray's propagation format MUST be used to add context propagation
@Oberon00 I assume you mean you are adding propagation to the sqs/sns message attributes?  I think it's important to always send the x-ray headers on the request, but I can add the following:
> Additional propagation formats MAY be applied to individual request types that support arbitrary attributes such as `SqsMessage`. This can allow for transporting additional context that may not be supported by x-ray, such as baggage. Documentation SHOULD advise that doing so is subject to attribute limits and billing impacts.

Under what circumstance do you think it should be disabled?

2023-02-16 16:50 UTC, tylerbenson commented on specification/trace/semantic_conventions/instrumentation/aws-sdk.md
> +When making outgoing calls using an aws-sdk, AWS X-Ray's propagation format MUST be used to add context propagation
I went ahead and added that paragraph.

2023-02-16 17:00 UTC, codeboten approved these changes

2023-02-16 17:04 UTC, Oberon00 commented on specification/trace/semantic_conventions/instrumentation/aws-sdk.md
> +When making outgoing calls using an aws-sdk, AWS X-Ray's propagation format MUST be used to add context propagation
I.e. the weakest wording we could add I think is "Instrumentations MAY offer an enabled-by-default option to control enabling/disabling X-Ray propagation"

2023-02-16 18:22 UTC, tylerbenson commented on specification/trace/semantic_conventions/instrumentation/aws-sdk.md
> +When making outgoing calls using an aws-sdk, AWS X-Ray's propagation format MUST be used to add context propagation
Ok, I added your suggested verbiage.

2023-02-17 18:59 UTC, tsloughter commented
I think for HTTP headers in AWS requests the Xray propagator should always be used (until a time AWS changes this).

For per-service instrumentation like MessageAttributes in SQS there is no need because it is invisible to AWS anyway.

What I'm not sure on is whether SQS instrumentation should be additionally inserting context into MessageAttributes or not.

@Oberon00 I notice dynatrace python guide has the user defining the extraction themselves because python's lambda instrumentation doesn't do it -- something I'd like to change but it would be a Link and not the parent, so not a replacement for what you have here. Would requiring similar for injection not be acceptable?

2023-02-17 19:01 UTC, tsloughter approved these changes

2023-02-21 13:27 UTC, Oberon00 commented
> Would requiring similar for injection not be acceptable?

For extraction this is conceptually required for batch processing. For injection, it would be a shame if the user would have to do it manually. That would also mean that they would have to create the span manually (since you can only do manual injection _before_ calling the function in which the span is created by the instrumentation). Basically we would not be able to use instrumentation at all anymore and instruct users to do everything manually, or create a fork.

2023-02-21 17:11 UTC, Aneurysm9 requested changes

2023-02-21 17:11 UTC, Aneurysm9 commented on CHANGELOG.md
> +- Add requirement to use X-Ray propagation for aws-sdk client calls.
```suggestion
- Add requirement to use X-Ray propagation as default for aws-sdk client calls.
```

2023-02-21 17:11 UTC, Aneurysm9 commented on specification/trace/semantic_conventions/instrumentation/aws-sdk.md
> +http headers of the outgoing request. Propagation headers MUST be added before the signature is calculated to prevent errors
```suggestion
http headers of the outgoing request unless another propagator is explicitly provided. Propagation headers MUST be added before the signature is calculated to prevent errors
```

The user needs to retain control to decide how propagation should happen.  Maybe they're using the AWS SDK with services that mimic AWS service APIs but expect w3c tracecontext propagation.

2023-02-21 17:11 UTC, Aneurysm9 commented on specification/trace/semantic_conventions/instrumentation/aws-sdk.md
> +When making outgoing calls using an aws-sdk, AWS X-Ray's propagation format MUST be used to add context propagation to
```suggestion
When making outgoing calls using an aws-sdk, an AWS service-supported propagation format MUST be used to add context propagation to
```

We need flexibility to react to a change in the set of supported propagation formats and thus should not mandate a single format.

2023-02-21 17:11 UTC, Aneurysm9 commented on specification/trace/semantic_conventions/instrumentation/aws-sdk.md
> +on signed requests. Instrumentations MAY offer an enabled-by-default option to control enabling/disabling X-Ray propagation.
```suggestion
on signed requests.
```

This isn't required if we allow the user to explicitly provide a (potentially no-op) propagator.

2023-02-21 17:11 UTC, Aneurysm9 commented on specification/trace/semantic_conventions/instrumentation/aws-sdk.md
> +[node](https://github.com/aws/aws-xray-sdk-node), and [python](https://github.com/aws/aws-xray-sdk-python).)
```suggestion
services, for example SNS -> SQS -> Lambda.
```

I'm not sure this is relevant or appropriate for inclusion in the spec.

2023-02-21 17:11 UTC, Aneurysm9 commented on specification/trace/semantic_conventions/instrumentation/aws-sdk.md
> +services, for example SNS -> SQS -> Lambda. Implementations of AWS X-Ray instrumentation for aws-sdk can be used as
I'm not sure this paragraph adds value and it is bound to become out-of-date and incorrect at some point.

2023-02-21 17:11 UTC, Aneurysm9 commented on specification/trace/semantic_conventions/instrumentation/aws-sdk.md
> +Documentation SHOULD advise that doing so is subject to attribute limits and billing impacts.
I don't think this is necessary if the user is allowed to provide their own propagator and we're only stating that X-Ray is the default rather than the global propagator.

2023-02-21 17:15 UTC, tsloughter commented on CHANGELOG.md
> +- Add requirement to use X-Ray propagation for aws-sdk client calls.
Should say that it is a default separate from the global propagator. So you should be able to override it as a user but simply saying "default" sounds the same as using the global.

2023-02-21 17:51 UTC, tylerbenson commented on specification/trace/semantic_conventions/instrumentation/aws-sdk.md
> +http headers of the outgoing request. Propagation headers MUST be added before the signature is calculated to prevent errors
Not sure I follow.  Could you elaborate on when this would be problematic?

2023-02-21 17:54 UTC, tylerbenson commented on specification/trace/semantic_conventions/instrumentation/aws-sdk.md
> +services, for example SNS -> SQS -> Lambda. Implementations of AWS X-Ray instrumentation for aws-sdk can be used as
I added it to provide justification on why this is necessary.  Key word here is *currently*.  I understand that much of this is subject to change as AWS evolves their support.  I think that when that assumption changes, the spec can be updated.

2023-02-21 18:27 UTC, Aneurysm9 commented on specification/trace/semantic_conventions/instrumentation/aws-sdk.md
> +http headers of the outgoing request. Propagation headers MUST be added before the signature is calculated to prevent errors
[min.io](https://min.io/product/s3-compatibility) provides an S3-compatible service API.  I have no idea whether it supports tracing or what context propagation formats it supports, but there is no reason to expect that they would only ever support exactly the same formats as AWS S3.  Not allowing a user to specify their own propagator will prevent them from using such an AWS-compatible service with anything other than the X-Ray propagator.

2023-02-21 18:29 UTC, Aneurysm9 commented on specification/trace/semantic_conventions/instrumentation/aws-sdk.md
> +services, for example SNS -> SQS -> Lambda. Implementations of AWS X-Ray instrumentation for aws-sdk can be used as
I don't think there's a need to include this and doing so risks the spec diverging from reality.  It is not normative and thus doesn't belong in normative spec language.

2023-02-21 19:38 UTC, carlosalberto commented
So trying to summarize the current state after the latest comments, just to be clear (please do correct me if I'm wrong):

* X-Ray seems to be the only propagated format _currently_, but we would like to keep the door open for future AWS approved/supported formats?
* Propagation support through message attributes: although the plan has been to _allow_ instrumentation to fallback to this, is this something that can be totally unnecessary by allowing custom propagation formats? Can `tracestate` really be propagated this way? Based on the previous comments, I'd say *no*? 

On a slightly related note, there's a (merged) OTEP around [Messaging Context Propagation](https://github.com/open-telemetry/oteps/blob/main/text/trace/0205-messaging-semantic-conventions-context-propagation.md#proposed-addition-to-the-messaging-semantic-conventions) which mentions that per-Message context should be propagated, rather than per-request context (cc @pyohannes in case you have two cents to add here, etc).

2023-02-22 17:05 UTC, tylerbenson commented on specification/trace/semantic_conventions/instrumentation/aws-sdk.md
> +http headers of the outgoing request. Propagation headers MUST be added before the signature is calculated to prevent errors
min.io seems to handle change events via pushing notifications to a queue or db: https://min.io/docs/minio/kubernetes/upstream/administration/monitoring.html

They don't support x-ray propagation or anything else that I can see.  That said, as long as AWS only supports X-Ray I don't think it makes sense to support other propagation mechanisms. When AWS adds support for something else, the spec can be updated at that point.

2023-02-22 18:01 UTC, Aneurysm9 commented on specification/trace/semantic_conventions/instrumentation/aws-sdk.md
> +http headers of the outgoing request. Propagation headers MUST be added before the signature is calculated to prevent errors
I don't think it makes sense to prohibit the user from making this choice.  What AWS supports is a different conversation entirely.  The user should be in control of what the system produces.

2023-02-22 18:19 UTC, tsloughter commented on specification/trace/semantic_conventions/instrumentation/aws-sdk.md
> +http headers of the outgoing request. Propagation headers MUST be added before the signature is calculated to prevent errors
I think it makes sense to allow the user to override the propagator so that when AWS does support W3C they can switch without any other changes necessary. No need to wait on an instrumentation upgrade and potential conflicts there if they want to switch.

2023-02-22 21:29 UTC, tylerbenson commented on specification/trace/semantic_conventions/instrumentation/aws-sdk.md
> +services, for example SNS -> SQS -> Lambda. Implementations of AWS X-Ray instrumentation for aws-sdk can be used as
I've reworded it.  Let me know if the updated version is ok.

2023-02-22 21:30 UTC, tylerbenson commented on specification/trace/semantic_conventions/instrumentation/aws-sdk.md
> +Documentation SHOULD advise that doing so is subject to attribute limits and billing impacts.
I think this is useful to point out because the carrier here is different compared to what is discussed above.

2023-02-24 01:21 UTC, Aneurysm9 commented on specification/trace/semantic_conventions/instrumentation/aws-sdk.md
> +Documentation SHOULD advise that doing so is subject to attribute limits and billing impacts.
```suggestion
```

I think the first paragraph says all that needs to be said here.  

The X-Ray docs are not normative for other AWS services and the link provided doesn't give details on supported propagation formats.  At best it says this, which tells a user looking for supported propagation formats nothing of value:

> AWS services that are [integrated with X-Ray](https://docs.aws.amazon.com/xray/latest/devguide/xray-services.html) can add tracing headers to incoming requests, send trace data to X-Ray, or run the X-Ray daemon. For example, AWS Lambda can send trace data about requests to your Lambda functions, and run the X-Ray daemon on workers to make it simpler to use the X-Ray SDK.

Saying that AWS service-supported context propagation is necessary for AWS services to propagate context is saying that `1 = 1`.  It provides no value.  Worse, it's misleading since context can be propagated in-band in the message sent through SNS or SQS without any AWS services being aware that it exists and a trace can be constructed just fine by users who don't care what the transport mechanism did.

That additional propagation formats may be used is already covered in the first paragraph.  The rest is guessing at implementation details that don't seem relevant to this specification.  If we're talking about the content sent through AWS services and not messages to AWS services then we're out of the realm of the AWS SDK instrumentation and semantic conventions.

I feel that we should specify as little as is necessary, and no more.

2023-02-24 01:21 UTC, Aneurysm9 commented on specification/trace/semantic_conventions/instrumentation/aws-sdk.md
> +context propagation to http headers on the outgoing request, unless another propagator is explicitly provided.
```suggestion
context propagation to HTTP headers on the outgoing request, unless another propagator is explicitly provided,
in which case the provided propagator MUST be used.
```

2023-02-24 01:27 UTC, tsloughter commented on specification/trace/semantic_conventions/instrumentation/aws-sdk.md
> +Documentation SHOULD advise that doing so is subject to attribute limits and billing impacts.
I think it is useful to include context around why XRay is used by default, over the global propagator, and the example of `S3->SQS` is the clearest way to give that context. The only way to include trace context in a request that writes to S3 and then creates a messages on an SQS queue is X-Ray headers on the HTTP request to S3, correct? There is no option for in-band. So it isn't misleading and helps to not have the question brought up over and over about why this requirement is in the spec.

2023-02-24 16:31 UTC, Oberon00 commented
@bogdandrutu 

> X-Ray seems to be the only propagated format currently, but we would like to keep the door open for future AWS approved/supported formats?

This is only true in the general case. Specific APIs will often provide other ways where you can transport extract/inject key-value-pairs, e.g. message attributes for SNS or SQS.

2023-02-24 21:12 UTC, tylerbenson commented on specification/trace/semantic_conventions/instrumentation/aws-sdk.md
> +This can allow for transporting additional context that may not be supported by x-ray, such as baggage or tracestate.
@Oberon00 Is this not sufficient to emphasize the point that other propagation formats may be used on some request types?

2023-02-27 16:59 UTC, Oberon00 commented on specification/trace/semantic_conventions/instrumentation/aws-sdk.md
> +This can allow for transporting additional context that may not be supported by x-ray, such as baggage or tracestate.
I think that is sufficient.

2023-02-27 17:02 UTC, Oberon00 commented on specification/trace/semantic_conventions/instrumentation/aws-sdk.md
> +* [AWS X-Ray](https://docs.aws.amazon.com/xray/latest/devguide/aws-xray.html)
```suggestion
Only the [AWS X-Ray](https://docs.aws.amazon.com/xray/latest/devguide/aws-xray.html) format is currently currently natively supported by AWS services.
```

2023-02-28 15:31 UTC, tylerbenson commented on specification/trace/semantic_conventions/instrumentation/aws-sdk.md
> +* [AWS X-Ray](https://docs.aws.amazon.com/xray/latest/devguide/aws-xray.html)
@Aneurysm9 which do you prefer?

2023-03-01 10:49 UTC, Oberon00 commented on specification/trace/semantic_conventions/instrumentation/aws-sdk.md
> +* [AWS X-Ray](https://docs.aws.amazon.com/xray/latest/devguide/aws-xray.html)
To add another alternative to the set:

```suggestion
The following formats are currently natively supported by AWS services for propagation:

* [AWS X-Ray](https://docs.aws.amazon.com/xray/latest/devguide/aws-xray.html)
```

(Current wording is also acceptable for me, I just think it's a bit confusing)

2023-03-03 00:03 UTC, Aneurysm9 commented
I continue to believe that the first paragraph of this change is all that is required and appropriate for the specification.  The rest is non-normative and only temporarily correct at best.  If @open-telemetry/specs-approvers wish to overrule my objections, that's their prerogative.

2023-03-03 18:34 UTC, jsuereth commented
I don't think this kind of recommendation belongs in semantic conventioins. This should be moved to a "compatibility" section, detailing AWS cloud compatibility.

2023-03-13 09:37 UTC, Oberon00 commented
@jsuereth 

> I don't think this kind of recommendation belongs in semantic conventioins. This should be moved to a "compatibility" section, detailing AWS cloud compatibility.

I object to that. This makes it unlikely that anybody will find it, and makes everything more complicated. The files are already in an instrumentation subfolder.

2023-03-15 20:50 UTC, jsuereth commented
@Oberon00 I think what @tylerbenson did has this just as discoverable, more-so in my opinion.

I don't think the use of propagator format is a Semantic Convention concern.  Semantic conventions are about *what* to produce and the meaning.  The details of how to propagate trace effectively on AWS is not a concern for semantic conventions.

2023-03-15 20:50 UTC, jsuereth approved these changes
LGTM.  Did this address @Aneurysm9's concerns?

2023-03-15 21:34 UTC, tsloughter commented
How to handle propagation in AWS is already part of the semantic conventions. Whether it should stay in semconv or move somewhere else should be separate from what the proper behaviour is.

2023-03-15 22:42 UTC, jmacd commented on specification/trace/semantic_conventions/instrumentation/aws-sdk.md
> +services, for example SNS -> SQS -> Lambda. Implementations of AWS X-Ray instrumentation for aws-sdk can be used as
The new paragraph looks better to me. @Aneurysm9, will you release your blocking comments now?

2023-03-16 13:04 UTC, jsuereth commented
> How to handle propagation in AWS is already part of the semantic conventions. Whether it should stay in semconv or move somewhere else should be separate from what the proper behaviour is.

Semantic conventions scope is defined [here](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/overview.md#semantic-conventions).

I'd argue having propagation requirements make its way into the semconv specification should never been accepted in the first place. I'm fine taking that discussion elsewhere and this PR does fix the issue.

2023-03-16 13:33 UTC, Oberon00 commented
> I'd argue having propagation requirements make its way into the semconv specification should never been accepted in the first place. 

You may want to review the messaging SIGs work then 😃  I think how to propagate and when to create a context is most of what they did. Currently it falls under semantic conventions, otherwise we'd have to invent a new term.

2023-03-16 15:10 UTC, tylerbenson commented on specification/compatibility/aws.md
> +* [AWS X-Ray](https://docs.aws.amazon.com/xray/latest/devguide/aws-xray.html)
@Aneurysm9 I understand that you feel constrained by explicitly listing the formats that AWS supports.  I think that it is important to do so because each sdk and lambda instrumentation must be explicitly modified to handle these individual formats.

At the point when AWS adds additional support, instrumentation will still need to be updated in a consistent manner with a specific consideration for backwards compatibility. Consequentially, I don't think it's safe to say that we can generically support any format that AWS chooses without appropriate consideration and a corresponding spec update.

Per @jsuereth's suggestion, I have moved the section from the semantic conventions to the compatibility section, where I think it makes more sense and also justifies additional explanation.

2023-03-16 18:18 UTC, Aneurysm9 commented on specification/compatibility/aws.md
> +* [AWS X-Ray](https://docs.aws.amazon.com/xray/latest/devguide/aws-xray.html)
It seems to me that this boils down to "context propagation requires coordination to ensure that both parties to an interaction are communicating effectively".  That is true for every instrumentation and every pair of systems that interact.  Why are we specifying particular behavior for this set of actors?  What other sets of actors require this type of specification?  Where is that documented?

I think all of this can be deleted and we will be no worse off than we were before.  Probably better off as we won't be stating the obvious in ways that can drift from reality absent vigilant maintenance.

2023-03-16 18:52 UTC, jsuereth commented on specification/compatibility/aws.md
> +* [AWS X-Ray](https://docs.aws.amazon.com/xray/latest/devguide/aws-xray.html)
@Aneurysm9 I'm trying to understand your concerns here.


- Is the objection here that this *requires* propagation format for every AWS SDK?
- Is the objection that this outlines x-ray specifically and would need to be updated once AWS backends support w3c?
- Is the objection that when AWS backends support w3c, this would make the migration harder?


For reference - Cloud Run / App Engine had proprietary propagation formats.  Our stance was to specify in the GCP-specific hooks, e.g. [here](https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/tree/main/propagator). This recommendation also allows swapping from proprietary -> W3c gracefully.

@lmolkova Do the Azure SDKs have any trace propgation formats you're looking to migrate to w3c?  Any advice for this particular PR?

If the concern here is about migration from x-ray to traceparent (or other format), I'd suggest we adjust the wording slightly.

- X-Ray propagation takes priority when attaching to parent traces from SDK instrumentation
- X-Ray + otel built in propagation are *both* used for outgoing request instrumentation  (allows backends to start ignoring one over time, existing OTEL users get complete traces)

This should give us:

- The best x-ray experience for OTEL users
- A path for migration of AWS services to w3c tracecontext if they want it.

WDYT?

2023-03-16 19:33 UTC, Aneurysm9 commented on specification/compatibility/aws.md
> +* [AWS X-Ray](https://docs.aws.amazon.com/xray/latest/devguide/aws-xray.html)
> @Aneurysm9 I'm trying to understand your concerns here.
> 
> * Is the objection here that this _requires_ propagation format for every AWS SDK?
> * Is the objection that this outlines x-ray specifically and would need to be updated once AWS backends support w3c?
> * Is the objection that when AWS backends support w3c, this would make the migration harder?

My concern is that this is making requirements of instrumentation that are either empty in the sense that context propagation inherently requires coordination and thus is not adding anything of value by stating the obvious, or are overspecified in that it codifies things that are temporarily true and not fundamental to the correct operation of the systems in question.  Everything we include in this specification has a cost to construct and a cost to maintain.  Why are we expending effort for no value?

> For reference - Cloud Run / App Engine had proprietary propagation formats. Our stance was to specify in the GCP-specific hooks, e.g. [here](https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/tree/main/propagator). This recommendation also allows swapping from proprietary -> W3c gracefully.

That seems to have worked out for you without requiring OTel to specify anything.  I think the same can be done here.

> If the concern here is about migration from x-ray to traceparent (or other format), I'd suggest we adjust the wording slightly.
> 
>    * X-Ray propagation takes priority when attaching to parent traces from SDK instrumentation
>    * X-Ray + otel built in propagation are _both_ used for outgoing request instrumentation  (allows backends to start ignoring one over time, existing OTEL users get complete traces)
> 
> 
> This should give us:
> 
>    * The best x-ray experience for OTEL users
>    * A path for migration of AWS services to w3c tracecontext if they want it.

`s/X-Ray/Format A/` and `s/trace(context|parent)/Format B/` and maybe we've got some general advice that can be offered to users looking to migrate propagation formats.  That _would_ have value, but that's not what we have here.

2023-03-16 20:14 UTC, tsloughter commented on specification/compatibility/aws.md
> +* [AWS X-Ray](https://docs.aws.amazon.com/xray/latest/devguide/aws-xray.html)
I'd argue GCP should have this same document in the spec.

I'm not sure how this isn't fundamental to getting correct traces. Just because it may be temporary doesn't mean it isn't.

2023-03-17 09:26 UTC, Oberon00 commented on specification/compatibility/aws.md
> +* [AWS X-Ray](https://docs.aws.amazon.com/xray/latest/devguide/aws-xray.html)
(Aside: GCP is actually more problematic because it breaks all traces, because the parent span ID will point into Google's proprieatary backend, replacing any parent span ID you sent in the request. The beauty of everybody agreeing to use the same header... See thread at https://github.com/open-telemetry/opentelemetry-specification/pull/1852#discussion_r726457056)

2023-03-17 13:36 UTC, jsuereth commented on specification/compatibility/aws.md
> +* [AWS X-Ray](https://docs.aws.amazon.com/xray/latest/devguide/aws-xray.html)
I'm more than happy to have a GCP-version of this kind of specification.  


To @Oberon00 -
Want to call out that we are actively migrating to w3c traceparent, so usage of these oneway attachments should go away soon. Additionally, regarding parent span ID and our traces, we are working on ways for these spans to be exported (in easier ways than today). The goal is users of GCP CR/AppEngine can see load-balancer spans in the end-to-end traces if they desire.

2023-03-17 22:23 UTC, jmacd approved these changes

2023-03-20 23:38 UTC, lmolkova commented on specification/compatibility/aws.md
> +* [AWS X-Ray](https://docs.aws.amazon.com/xray/latest/devguide/aws-xray.html)
It looks like this PR proposes that AWS SDK and Lambda instrumentations MUST use AWS propagator by default and ignore the propagator configured by the use on TracerProvider. Correct? 

This is what we do on Azure SDKs for HTTP - Azure supports a set of legacy correlation formats (that work without distributed tracing or otel enabled) and in some cases, W3C trace-context. 

We use W3C trace context for distributed tracing and ignore the propagator set on the TracerProvider - Azure services are unlikely to ever support anything but proprietary and w3c formats.

Essentially the propagator should be more granular than global since different endpoints can support different formats.

2023-03-20 23:38 UTC, lmolkova commented on specification/compatibility/aws.md
> +When making outgoing calls using an aws-sdk, an AWS service-supported propagation format MUST be used to add
it this document applied to AWS SDKs or to all HTTP requests done to AWS with or without SDK?

2023-03-20 23:38 UTC, lmolkova commented on specification/compatibility/aws.md
> +context propagation to HTTP headers on the outgoing request, unless another propagator is explicitly provided,
explicitly provided on the TraceProvider (global one) or to AWS instrumentation? I don't believe otel SDKs allow to check if propagator was explicitly provided or a default one.

Also setting AWS provider as global one for all HTTP client instrumentations and incoming HTTP requests does not make sense

2023-03-20 23:38 UTC, lmolkova commented on specification/compatibility/aws.md
> +Additional propagation formats MAY be applied to individual request types that support arbitrary attributes such as `SqsMessage`.
The context propagation format in queue message where application controls both the production and consumption should not be required to use AWS propagator. Ideally messaging SDKs should use the global propagator from TracerProvider.

2023-03-20 23:38 UTC, lmolkova commented on specification/compatibility/aws.md
> +* [AWS X-Ray](https://docs.aws.amazon.com/xray/latest/devguide/aws-xray.html)
> X-Ray propagation takes priority when attaching to parent traces from SDK instrumentation
X-Ray + otel built in propagation are both used for outgoing request instrumentation (allows backends to start ignoring one over time, existing OTEL users get complete traces)


I'm not sure if AWS services emit any telemetry to OTel and if the presence of traceparent header is even important.

In the case of Azure, this story is not clear yet and from the user side of things, they get very little from trace context being propagated. We still do it as a future-proof story though

2023-03-21 00:26 UTC, tsloughter commented on specification/compatibility/aws.md
> +When making outgoing calls using an aws-sdk, an AWS service-supported propagation format MUST be used to add
It is about the instrumentation of AWS SDKs.

2023-03-21 00:26 UTC, tsloughter commented on specification/compatibility/aws.md
> +context propagation to HTTP headers on the outgoing request, unless another propagator is explicitly provided,
Explicitly provided means provided to the instrumentation library.

2023-03-21 00:27 UTC, tsloughter commented on specification/compatibility/aws.md
> +* [AWS X-Ray](https://docs.aws.amazon.com/xray/latest/devguide/aws-xray.html)
So it sounds like this is defining to do for AWS what Azure is doing for instrumentation of their SDKs?

2023-03-21 00:48 UTC, lmolkova commented on specification/compatibility/aws.md
> +When making outgoing calls using an aws-sdk, an AWS service-supported propagation format MUST be used to add
Then I suggest changing

> This document highlights compatibility considerations when interacting with AWS managed services.

to something like 

> This document highlights compatibility considerations for AWS SDK instrumentations.

2023-03-21 00:50 UTC, lmolkova commented on specification/compatibility/aws.md
> +context propagation to HTTP headers on the outgoing request, unless another propagator is explicitly provided,
it's worth reflecting in the document ad I'd suggest to say something like "AWS SDK should use x-ray propagator and may allow users to explicitly configure a different one for AWS SDK instrumentation"

2023-03-21 00:56 UTC, lmolkova commented on specification/compatibility/aws.md
> +* [AWS X-Ray](https://docs.aws.amazon.com/xray/latest/devguide/aws-xray.html)
I have no opinion on what AWS SDKs should do, but I fully support the idea that instrumentations should use specific propagators if they know that their backend supports something specific. 

It feels like this document just wants to document what should be used by all AWS instrumentations and seems fine to me if fully clarified.

2023-03-21 11:39 UTC, Oberon00 commented on specification/compatibility/aws.md
> +* [AWS X-Ray](https://docs.aws.amazon.com/xray/latest/devguide/aws-xray.html)
>  I fully support the idea that instrumentations should use specific propagators if they know that their backend

Since instrumentations and backends are decoupled (because you can use any exporter with any instrumentation), instrumentations never know their backend.

2023-03-21 11:40 UTC, Oberon00 commented on specification/compatibility/aws.md
> +When making outgoing calls using an aws-sdk, an AWS service-supported propagation format MUST be used to add
> It is about the instrumentation of AWS SDKs.

Why is that. The reasoning seems to apply to the REST API exposed by AWS, regardless of calling technology.

2023-03-21 14:51 UTC, tylerbenson commented on specification/compatibility/aws.md
> +Additional propagation formats MAY be applied to individual request types that support arbitrary attributes such as `SqsMessage`.
Using arbitrary propagation only works in simple SQS architectures.  As soon as you have something like SNS -> SQS -> Lambda, the propagation fails because AWS is responsible for the context propagation through their managed systems.  Fixing a more complicated scenario is the primary motivation of this requirement.

2023-03-21 14:59 UTC, tylerbenson commented on specification/compatibility/aws.md
> +When making outgoing calls using an aws-sdk, an AWS service-supported propagation format MUST be used to add
@Oberon00 I don't think we are restricting "AWS SDK's" to only the SDK's published by AWS.  I see it as a more generic term for any SDK that interacts with AWS managed services. I think this should apply to other SDK's or libraries not published by AWS. If you think this needs to be more explicit, I'm open to rephrasing to make this clear.

Or perhaps your issue is with the HTTP specific portion... As far as I'm aware, the SDK's only interact with AWS managed services via HTTP interactions in a very specific request/response cycle.  Do you know of any other means of interaction that should be taken into consideration?

2023-03-21 15:04 UTC, Oberon00 commented on specification/compatibility/aws.md
> +When making outgoing calls using an aws-sdk, an AWS service-supported propagation format MUST be used to add
> I don't think we are restricting "AWS SDK's" to only the SDK's published by AWS. I see it as a more generic term for any SDK that interacts with AWS managed services

I think that is not obvious. Although IMHO it's also a bit of an unimportant discussion and probably not even worth clarifying.

> Or perhaps your issue is with the HTTP specific portion

No, I don't have any issue with that, AFAIK HTTP is the only way.

2023-03-21 15:07 UTC, Oberon00 commented on specification/compatibility/aws.md
> +Additional propagation formats MAY be applied to individual request types that support arbitrary attributes such as `SqsMessage`.
> Using arbitrary propagation only works in simple SQS architectures. As soon as you have something like SNS -> SQS -> Lambda, the propagation fails

That is not true. The SNS message attributes can be converted to SQS attributes or the Lambda can pick out the attributes from the payload JSON. We support both of these in Dynatrace, and also have submitted a PR for opentelemetry-dotnet-contrib to support exactly that scenario: https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/1051

2023-03-21 15:12 UTC, tylerbenson commented on specification/compatibility/aws.md
> +context propagation to HTTP headers on the outgoing request, unless another propagator is explicitly provided,
> unless another propagator is explicitly provided

@pyohannes:
> It's not clear to me who provides the propagator, but I assume it's the user who configures the instrumentation library? Does this mean that every instrumentation library that makes calls using AWS SDKs needs to provide mechanisms to specify a custom propagator?

I don't think there is a requirement to accept custom propagators, but allowing such is important to some SDK's like golang.  Per Anthony's request, we made this explicitly allowed.

2023-03-22 12:07 UTC, tsloughter commented on specification/compatibility/aws.md
> +Additional propagation formats MAY be applied to individual request types that support arbitrary attributes such as `SqsMessage`.
Right, S3 is the best example. Triggering a lambda for an SQS event created by an S3 operation needs x-ray used in order to propagate the context from the client to the lambda invocation.

2023-03-22 15:23 UTC, tylerbenson commented on specification/compatibility/aws.md
> +Additional propagation formats MAY be applied to individual request types that support arbitrary attributes such as `SqsMessage`.
Ok, apologies for the confusion.

2023-04-06 15:22 UTC, tylerbenson commented on specification/compatibility/aws.md
> +Additional propagation formats MAY be applied to individual request types that support arbitrary attributes such as `SqsMessage`.
I think this has been resolved...

2023-04-06 15:52 UTC, tylerbenson commented on specification/compatibility/aws.md
> +When making outgoing calls using an aws-sdk, an AWS service-supported propagation format MUST be used to add
I've clarified things a bit now.

2023-04-06 15:54 UTC, tylerbenson commented on specification/compatibility/aws.md
> +context propagation to HTTP headers on the outgoing request, unless another propagator is explicitly provided,
Added clarification.

2023-04-06 16:41 UTC, willarmiros approved these changes
Chiming in from X-Ray here, I am supportive of including this change in the spec. As others have pointed out, using the X-Ray propagator is essential to having a tracing experience through services like S3 Events, and even though other formats can be supported in SNS/SQS via message attributes, X-Ray is the only format that can be passed in using [Message System Attributes](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-message-metadata.html#sqs-message-system-attributes), which do NOT count against a user's limit of 10 attributes per message.

In the long term, we hope to support propagation of other common formats in these services natively, at which point this spec change will hopefully no longer be needed. But this improvement requires significant cross-service collaboration so it is likely far off, and I think this is the best way to preserve a good experience in the meantime.

As for the latest comment of semconv vs. spec, I am ok with either as long as the outcome is to implement this requirement across the SDKs :)

2023-04-13 22:11 UTC, carlosalberto commented
So the TC briefly discussed this and the proposed plan is:

* Dot not use normative language for this addition, as we don't consider this as part of the Spec, but more of a guide.
* Put this, instead of under the compatibility directory, in a top level one calling "supplementary-guidelines" or similar, where we can put non-normative documents that serve as general guides (and we can put later other similar documents in this directory). We can _later_ move it to a different repo, if/as needed (we can discuss this as a follow-up).

cc @tylerbenson @Aneurysm9

2023-04-13 23:47 UTC, tsloughter commented
It isn't spec if there aren't to be specs for what makes something an "otel compliant instrumentation library". Being non-normative would mean aws libraries could act differently in something as fundamental as propagation.

Maybe not a big deal since the user can technically modify the behaviour to get the same result, but that's my initial concern with the proposal.

2023-04-19 21:20 UTC, trask commented
/easycla

2023-04-20 03:45 UTC, nickmango commented
/easycla

2023-04-20 21:34 UTC, trask commented
/easycla

2023-04-21 17:33 UTC, jarias-lfx commented
/easycla

2023-04-24 23:12 UTC, carlosalberto commented
@jsuereth @Aneurysm9 @Oberon00 please review the updated PR - the content itself remains the same, albeit located now in the non-formal `supplementary-guides/` directory.

2023-04-25 14:41 UTC, Oberon00 approved these changes

2023-04-25 14:41 UTC, Oberon00 commented on specification/trace/semantic_conventions/instrumentation/aws-sdk.md
I think the frequent cross-referencing indicates that this split between semantic conventions and esp. the "instrumentation" subpart is very artificial and IMHO should be reconsidered.

As a less fundamental change, I think `specification/*/semantic_conventions/instrumentation`  actually belongs under `supplementary-guidelines/compatibility` (since an instrumentation is always about establishing compatibility of an existing library with OTel -- I feel like "compatibility" in general is a rather redundant term in this context)

2023-04-25 14:41 UTC, Oberon00 commented on supplementary-guidelines/compatibility/aws.md
> +This document highlights compatibility considerations when interacting with AWS
```suggestion
This document highlights compatibility considerations for OpenTelemetry instrumentations when interacting with AWS
```

2023-04-25 14:41 UTC, Oberon00 commented on supplementary-guidelines/compatibility/aws.md
> +When making outgoing calls to AWS managed services using an aws-sdk, a third-party
```suggestion
When making calls to AWS managed services using an AWS SDK, a third-party
```

2023-04-25 14:41 UTC, Oberon00 commented on supplementary-guidelines/compatibility/aws.md
> +the instrumentation, in which case the provided propagator must be used.
```suggestion
to propagate the context to services (AWS Lambda) indirectly triggered by such call.

Instrumentation may allow a different propagator to be explicitly configured for
the instrumentation (e.g. an explicitly provided propagator, or an option to use the
globally configured propagator for all or certain calls).
This will be useful for certain cases where the services allow transporting these
headers to a receiving side, for example SQS or SNS with message attributes.
Note that this also means that instrumentations providing this option cannot just
replace their call to the X-Ray propagator with a call to another propagator (as
that would only send HTTP headers in the API REST call that would be immediately
ignored by the receiving AWS service), but will need to introduce per-service-call
implementations where it makes sense (e.g., for SQS send and SQS receive).
This can allow for transporting additional context that may not be supported by X-Ray, such as baggage or tracestate, or supporting certain legacy propagation formats.
Documentation should advise that doing so is subject to attribute limits and billing impacts.
```

2023-04-25 14:41 UTC, Oberon00 commented on supplementary-guidelines/compatibility/aws.md
> +Documentation should advise that doing so is subject to attribute limits and billing impacts.
```suggestion
doc for details on how this context propagation is consumed by Lambda instrumentation.)
```

Remove this in favor of previous.

2023-04-25 14:41 UTC, Oberon00 commented on supplementary-guidelines/compatibility/aws.md
> +Propagation headers must be added before the signature is calculated to prevent errors on signed requests.
```suggestion
Propagation headers must be added before the signature is calculated to prevent errors on signed requests. If injecting into the request itself (not just adding additional HTTP headers), additional considerations may apply (for example, the .NET AWS SDK calculates a hash of the attributes it sends and compares it with the  `MD5OfMessageAttributes ` that it receives).
```

2023-04-25 14:43 UTC, Oberon00 commented
I realize I added a lot of suggestions despite approving -- but none of them are blocking, so I would actually be OK-ish with merging this as-is (but please do consider my suggestions nevertheless 🙂)

2023-04-25 16:26 UTC, Aneurysm9 commented on supplementary-guidelines/compatibility/aws.md
> +
```suggestion
```

2023-04-25 16:26 UTC, Aneurysm9 commented on supplementary-guidelines/compatibility/aws.md
> +Propagation headers must be added before the signature is calculated to prevent errors on signed requests.
I'm not sure we should include current implementation details of specific SDK implementations.

2023-04-25 16:26 UTC, Aneurysm9 commented on CHANGELOG.md
> +- Add requirement to use X-Ray propagation as default for aws-sdk client calls.
```suggestion
- Add recommendation to use service-supported propagation formats as default for AWS SDK client calls.
```

2023-04-25 16:26 UTC, Aneurysm9 commented on supplementary-guidelines/compatibility/aws.md
> +library, or a direct HTTP request, an AWS service-supported propagation format must
```suggestion
library, or a direct HTTP request, an AWS service-supported propagation format should
```

2023-04-25 16:36 UTC, Oberon00 commented on specification/trace/semantic_conventions/instrumentation/aws-sdk.md
> I'm not sure the cross-referencing is needed at all.

Think from a practical perspective: As an instrumentation writer, how should I find all these guidelines + conventions? With the current split, the cross-referencing is IMHO absolutely vital.

2023-04-25 21:34 UTC, tylerbenson commented on supplementary-guidelines/compatibility/aws.md
@Oberon00 @Aneurysm9 Your suggestions for this file were rather difficult to follow.  I've pasted it into a [Google Doc](https://docs.google.com/document/d/1wG1dJ-Hgg_3oaAn4zu7kx3aKnbOVx0iR6iHZ5pZeudc/edit). Please add your suggestions there.

2023-04-26 11:12 UTC, Oberon00 commented on supplementary-guidelines/compatibility/aws.md
> +Propagation headers must be added before the signature is calculated to prevent errors on signed requests.
I'm also not sure, but since this is now in a "supplementary-guidelines" directory, it might be fine to add such cookbook-style hints. I'm also totally fine with not applying this suggestion at all though.

2023-04-26 13:58 UTC, carlosalberto commented on supplementary-guidelines/compatibility/aws.md
> +Propagation headers must be added before the signature is calculated to prevent errors on signed requests.
> since this is now in a "supplementary-guidelines" directory, it might be fine to add such cookbook-style hints

+1 to this. We don't have to be so serious about details in this section.

2023-05-03 14:52 UTC, tylerbenson commented on specification/trace/semantic_conventions/instrumentation/aws-sdk.md
I also think the cross-referencing is important. I'd rather leave it for now.

2023-05-09 04:22 UTC, reyang commented
This PR has been existing for long time and already received multiple approvals, I will merge it once the CI is clear. The change would be released in the new https://github.com/open-telemetry/semantic-conventions (to be created) repository.

Related to https://github.com/open-telemetry/opentelemetry-specification/pull/3474#pullrequestreview-1415130195.

2023-05-09 04:22 UTC, merged