Add a RecordLink for Span.
open-telemetry/opentelemetry-specification pull request #3240
Opened 2023-02-21 16:44 UTC by carlosalberto

Alternative to #3186 

A new `RecordLink(SpanContext, Attributes)` operation is added, **very similar** to `RecordException`, which means we use `AddEvent` behind the scenes, storing the actual data as `Attributes`:

* Event name is `link`.
* trace and span ids are stored as hex strings.
* Trace State remains a string.
* The `Attributes` associated to a new `Link` are passed through to the newly created `Event`.

This effectively means these are _soft_ `Links`. Other details:

* As this is an optional operation, not all languages would have to add this (C++, Go, etc). However, this will require instrumentation authors to manually set the `Attributes` passed to `AddEvent` as shown above.
* (At least) OTLP consumers will have to process standard `Link`s **plus** check any event with the `link` name and containing the traceid, spanid and tracestate triplet.

2023-02-21 17:03 UTC, arminru commented on specification/trace/semantic_conventions/links.md
> +# Semantic Conventions for Links
Please add this new file to the TOC in README.md

2023-02-21 17:03 UTC, arminru commented on specification/trace/api.md
> +#### Record Link
Probably too early to spark a naming discussion but I think `span.RecordLink(ctx, attrs)` would be very misleading and should rather be called `RecordLinkAs(Span)Event` or the like, since the outcome will not be a `Span Link` as one might expect from the name.

2023-02-21 17:25 UTC, yurishkuro requested changes
I am strongly against this approach. A Link is a dedicated entity in the data model that is designed to capture causality between spans.  Reusing another entity from the data model (Event) for the same purpose is a very bad design.

2023-02-21 18:13 UTC, tsloughter commented
I agree with @yurishkuro.

There seem to be 2 use cases, one that is due to limitations of particular instrumentations (so don't conceptionally need the link added after start) and those like https://github.com/open-telemetry/opentelemetry-specification/issues/454 that describe non-causal relationships.

In the latter example I'd argue those shouldn't be Links in the first place. In which case maybe a definition for adding span contexts as Events to a Span makes sense, just not "Links".

So Links can stay as they are, and Events are used for non-causal relationships -- "at time T this span did something based on a message created during Span X".

2023-02-21 19:06 UTC, yurishkuro commented
> "at time T this span did something based on a message created during Span X".

why isn't this causal / happens-before?

2023-02-21 20:05 UTC, tsloughter commented
@yurishkuro just basing it on the example given in #454 and generally considering the idea that a span could cause an Event instead of a Span. I can't think of an example that describes the real world data/events that would need to be modeled like this.

2023-02-21 22:02 UTC, lmolkova commented on semantic_conventions/trace/link.yaml
> +      - id: tracestate
trace-flags? otherwise we don't know if it was recorded on the other service

2023-02-21 23:17 UTC, lmolkova commented on specification/trace/api.md
> +#### Record Link
I *think* if we go down the path of recording links as events after span starts, we'd eventually replace original links with events too. If that happens, we'd regret naming it as `RecordLinkAs(Span)Event`.

2023-02-22 12:19 UTC, Oberon00 commented on semantic_conventions/trace/link.yaml
> +      - id: tracestate
Sounds useful, although I think you could make the same argument for our normal parent-child relationships (maybe we should actually add a `parent_flags` to the OTLP span?)

2023-02-23 20:01 UTC, MrAlias commented
> I am strongly against this approach. A Link is a dedicated entity in the data model that is designed to capture causality between spans. Reusing another entity from the data model (Event) for the same purpose is a very bad design.

Can you link to the data model definition?

2023-02-23 22:54 UTC, pyohannes commented
> Can you link to the data model definition?

I guess one could see OTLP as a data model definition? There [links](https://github.com/open-telemetry/opentelemetry-proto/blob/main/opentelemetry/proto/trace/v1/trace.proto#L220) are a different entity than [events](https://github.com/open-telemetry/opentelemetry-proto/blob/main/opentelemetry/proto/trace/v1/trace.proto#L191).

One of the main drawbacks of this approach is, that it forces telemetry consumers (who want to properly support links) to look at two different places for them: as links and as events. Proper support for links created after span creation would then require modifications in a variety of backends and exporters.

2023-02-23 23:12 UTC, yurishkuro commented
> Can you link to the data model definition?

https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#specifying-links
https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/overview.md#links-between-spans

These two define the semantics and the data model of the links. The definition is not as strong as `happens-before`, it only says "causally related", but the point is that we have a distinct model entity defined for that, so as @pyohannes said above, using a different entity like Event, which is defined semantically to mean a very different thing, is a poor design choice, and a poor user experience (both production and consumption).

2023-02-24 00:06 UTC, lmolkova commented
> One of the main drawbacks of this approach is, that it forces telemetry consumers (who want to properly support links) to look at two different places for them: as links and as events. Proper support for links created after span creation would then require modifications in a variety of backends and exporters.

we have a precedent unifying [events and logs](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/README.md#events-and-logs). If we go down links-are-represented-as-events in OTLP, the original links would probably go away.


> using a different entity like Event, which is defined semantically to mean a very different thing, is a poor design choice, and a poor user experience (both production and consumption).

some people say that everything (including span is semantically an event). In any case, user experience and over-the-wire data representation are not strictly related and I'd love to see some explanation on what's bad about user experience.

2023-02-24 02:35 UTC, yurishkuro commented
> I'd love to see some explanation on what's bad about user experience.

Cognitive overhead, ambiguity. Production: do I record this as link or event? Consumption: do I read this from links or events? Production: I am capturing a relationship between two spans, why is the timestamp doing here?

> some people say that everything (including span) is semantically an event

some people say that everything is a sequence of bytes, why bother with semantics of the logical data model at all?

2023-02-24 18:50 UTC, lmolkova commented
> Production: do I record this as link or event?

You record it as link since that's what on the API and in the documentation without bothering much about over-the-wire format.

> Production: I am capturing a relationship between two spans, what is the timestamp doing here?

Counter: When I'm receiving multiple messages with a timeout and some of them are prefetched and other come at different points in time, how do I record when the message came without creating two things - link AND event?

Timestamp is there to say when the relationship was discovered and should also help answer questions like: why this link was not considered when I made sampling decision.

> Consumption: do I read this from links or events?

Users don't read it from over-the-wire format but from their backends. Cognitive load of a backend developer getting list of links from the span and transforming them is no different than extracting exceptions from events.

Counter: as a user, when I want to see if two spans are related and my backend stores links inside spans, I need to write a query like `span.links.filter(tracer_id => another_trace_id)`, how is this a good experience?

Having events that exists outside of span lifetime would at least require them to be stored separately improving the experience instead.

2023-02-24 18:54 UTC, lmolkova commented
> we can also say that everything is a sequence of bytes, why bother with semantics of the logical data model at all?

what I'm saying is that event is a base type for different things and I argues that links is one of this things

2023-02-24 19:46 UTC, yurishkuro commented
@lmolkova you argue that relationships can be recorded via events. I don't dispute that. A link is just a structured representation of the relationship that can be just as well encoded via semantic conventions. What I don't agree with is having two representations of links in the data model, as this PR is proposing. I can get behind the proposal to deprecate the concept of Links in favor of span events with specific semantic convention for capturing span/trace reference.

2023-03-08 15:21 UTC, Oberon00 commented
Long-term, didn't we want to deprecate the Span events API in favor of the global events?

2023-03-21 17:47 UTC, lmolkova commented
One more reason why link is a log record + remote trace context is https://github.com/open-telemetry/opentelemetry-specification/issues/2176#issuecomment-1478281447

Essentially,  link as it's [defined today](https://github.com/open-telemetry/opentelemetry-proto/blob/main/opentelemetry/proto/trace/v1/trace.proto#L220)

```proto
  message Link {
    // A unique identifier of a trace that this linked span is part of. The ID is a
    // 16-byte array.
    bytes trace_id = 1;

    // A unique identifier for the linked span. The ID is an 8-byte array.
    bytes span_id = 2;

    // The trace_state associated with the link.
    string trace_state = 3;

    // attributes is a collection of attribute key/value pairs on the link.
    // Attribute keys MUST be unique (it is not allowed to have more than one
    // attribute with the same key).
    repeated opentelemetry.proto.common.v1.KeyValue attributes = 4;

    // dropped_attributes_count is the number of dropped attributes. If the value is 0,
    // then no attributes were dropped.
    uint32 dropped_attributes_count = 5;
  }
```

mixes two concepts together: remote context and attributes. 

I think limiting link to 
```proto
  message Link {
    // A unique identifier of a trace that this linked span is part of. The ID is a
    // 16-byte array.
    bytes trace_id = 1;

    // A unique identifier for the linked span. The ID is an 8-byte array.
    bytes span_id = 2;

    // flags?

    // The trace_state associated with the link.
    string trace_state = 3;
  }
```

and adding link property (or list of them?)  to [LogRecord](https://github.com/open-telemetry/opentelemetry-proto/blob/main/opentelemetry/proto/logs/v1/logs.proto) would preserve two different concepts.

2023-04-06 03:16 UTC, closed without merging