BREAKING: Remove `messaging.consumer.id`, make `messaging.client_id` generic
open-telemetry/opentelemetry-specification pull request #3336
Opened 2023-03-23 00:32 UTC by pyohannes

Fixes #2015

## Changes

Based on discussions in the messaging workgroup and in issue #2015, this PR proposes to remove `messaging.consumer.id`, and to replace both `messaging.kafka.client_id` and `messaging.rocketmq.client_id` with a generic `messaging.client_id`.

`messaging.consumer.id` is defined to always be set to the `client_id` of the used messaging system, except for Kafka, where it was defined to be a combination of `messaging.kafka.client_id` and `messaging.kafka.consumer.group`, or just the latter if `messaging.kafka.client_id` is not available. With this definition, the semantics of `consumer.id` are different between messaging systems, and even different for different Kafka scenarios.

The proposed `messaging.client_id` has consistent semantics ("an unique client id, when it is available"), and can be used instead of `messaging.consumer.id` in almost all cases.

In addition to have consistent semantics, this also simplifies the semantic conventions, as instead of

`messaging.consumer.id`
`messaging.kafka.client_id`
`messaging.rocketmq.client_id`

there is now just:

`messaging.client_id`.

2023-03-23 02:31 UTC, lmolkova commented on semantic_conventions/trace/messaging.yaml
> +      - id: client_id
should it be a general attribute beyond messaging? E.g. we just got `db.cosmosdb.client_id`.

I think this is a resource attribute that belongs on [instrumentation scope](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#get-a-tracer) . It seems there are no scope conventions yet, but we can define a new one here https://github.com/open-telemetry/opentelemetry-specification/blob/main/semantic_conventions/scope

2023-03-23 08:01 UTC, Oberon00 commented on semantic_conventions/trace/messaging.yaml
> +      - id: client_id
> I think this is a resource attribute that belongs on [instrumentation scope](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md?rgh-link-date=2023-03-23T02%3A31%3A08Z#get-a-tracer) .

No. The instrumentation scope is "once-per-library". You may create more than one kafka client for example.

2023-03-23 14:29 UTC, kenfinnigan commented on semantic_conventions/trace/messaging.yaml
> +          A unique identifier for the client that consumes or produces a message.
Should we provide recommendations on where the value would come from for different messaging clients?

2023-03-23 16:05 UTC, pyohannes commented on semantic_conventions/trace/messaging.yaml
> +      - id: client_id
This was discussed in the messaging workgroup. There are benefits to having a generic attribute capturing client id which can be shared across semantic convention areas. This could be e. g. `client.id` in a new top-level namespace. However, a challenge might be to define this attribute in an unambiguous way so that the definition makes sense across all the semantic conventions areas that use the concept.

@Oberon00 what are your thoughts on this, as you brought up the issue in the first place? Do you see value in having this generalized across semantic convention areas?

Reverting this PR to draft until we have consensus on this question.

2023-03-23 16:06 UTC, pyohannes commented on semantic_conventions/trace/messaging.yaml
> +          A unique identifier for the client that consumes or produces a message.
I think that would make sense. I'll get back to that once we have concluded the discussion about `messaging.client_id` above.

2023-03-23 17:34 UTC, Oberon00 commented on semantic_conventions/trace/messaging.yaml
> +      - id: client_id
My comment was only about this being an attribute of the tracer (instrumentation scope) instead of the span. The PR as-is seems fine to me.

I think an even more general client.id that is used beyond messaging might make sense theoretically, but I wouldn't generalize unless you know concrete non-messaging use cases.

2023-04-13 19:44 UTC, pyohannes commented on semantic_conventions/trace/messaging.yaml
> +          A unique identifier for the client that consumes or produces a message.
I added some recommendations based on the information here:
https://kafka.js.org/docs/configuration#:~:text=The%20kafka%20documentation%20describes%20the,user%20principal%20and%20client%2Did
https://rocketmq.apache.org/docs/domainModel/08consumer/#internal-attributes

2023-04-13 20:12 UTC, kenfinnigan requested changes

2023-04-13 20:12 UTC, kenfinnigan commented on specification/trace/semantic_conventions/messaging.md
> -| `messaging.kafka.client_id` | string | Client Id for the Consumer or Producer that is handling the message. | `client-5` | Recommended |
The example on line 486 needs to be updated to use `messaging.client_id`

2023-04-14 00:49 UTC, pyohannes commented on specification/trace/semantic_conventions/messaging.md
> -| `messaging.kafka.client_id` | string | Client Id for the Consumer or Producer that is handling the message. | `client-5` | Recommended |
Good catch, I fixed it.

2023-04-14 13:40 UTC, kenfinnigan approved these changes

2023-04-14 17:35 UTC, pyohannes commented
@Oberon00 Could you please have a look whether this resolves #2015, and possibly approve?

2023-04-20 12:08 UTC, joaopgrassi commented on specification/trace/semantic_conventions/messaging.md
> +`messaging.client_id` SHOULD be set to the `client-id` of consumers, or to the `client.id` property of producers.
In the original PR and in the discussions in the issue it was discussed about `client-id` not always being there, and in that case `client_id` would be set to `consumer.group`. Did we change that approach? Should we say here that `client_id` must always be a combination of `consumer.group + client-id` and if one is missing, it should be left unset? (because many may have the same `consumer.group`?

2023-04-20 15:02 UTC, pyohannes commented on specification/trace/semantic_conventions/messaging.md
> +`messaging.client_id` SHOULD be set to the `client-id` of consumers, or to the `client.id` property of producers.
The concept of a client id is well defined for both Kafka and Rocket MQ. In both cases, it doesn't involve the consumer group.

I think combining the information from `consumer.group` with client id is confusing and leads to ambiguous semantics (in case one of the is not available). The proposal in this PR is, to have separate attributes for client id and consumer group, which are empty if the respective value is not available.

2023-04-20 15:15 UTC, joaopgrassi approved these changes

2023-04-21 06:03 UTC, Oberon00 approved these changes

2023-04-21 06:04 UTC, Oberon00 commented
Thanks, I think this should indeed solve #2015.

2023-04-21 18:46 UTC, lmolkova approved these changes

2023-04-24 13:28 UTC, carlosalberto approved these changes

2023-04-24 13:34 UTC, carlosalberto commented
CHANGELOG entry, please ;)

2023-04-24 16:44 UTC, pyohannes commented
> CHANGELOG entry, please ;)

@carlosalberto Done.

2023-04-24 23:13 UTC, merged