Attributes namespacing clarification
open-telemetry/opentelemetry-specification pull request #3342
Opened 2023-03-27 09:34 UTC by bertysentry

Fixes #3131

## Changes

Specification for attributes naming has been clarified with regards to namespaces, when to use namespaces or not:

* Namespaces for attribute names are mandatory for Resource, Trace, and Log. 
* Namespaces are optional for Metric.

Related issues: #3129 #2847 #2513 #585

2023-03-27 10:36 UTC, bertysentry commented
@jmacd @jack-berg @sebastien-rosset Namespaces for metric attributes are discussed in multiple issues, a clarification is needed. Please review and discuss, thank you!

2023-03-27 10:41 UTC, Oberon00 commented
Isn't there an implicit requirement to have metric and other attributes use the same names. Otherwise, metrics would need to use completely separate semantic conventions.

2023-04-01 10:21 UTC, sebastien-rosset commented on specification/common/attribute-naming.md
> +> Attribute names are also known as the "attribute keys". For brevity within
Would it make sense to have a generic section about naming conventions? Looking at this entire section, most of the content is generic and seems to apply to **instrument** names, **metric** names and **attribute** names. 

1. **Generic**: Unicode, namespaces, name reuse prohibition, recommendations for OpenTelemetry authors, Recommendations for application developers, `otel.*` namespace
1. **Specific**: pluralization guidelines.

2023-04-01 10:41 UTC, sebastien-rosset commented on specification/common/attribute-naming.md
> +| Metrics  | Optional    | Identical attribute names are unlikely to conflict across unrelated metrics. Identical attribute names for different metrics may be desirable (e.g. `state`, `direction`). N
> Identical attribute names are unlikely to conflict across unrelated metrics.

I'm unclear what this sentence means.

1. What does it mean to "conflict"? Does it mean the set of supported values for the same attribute across two metrics is different?
   1. As an example, suppose a `form_factor` attribute is added (whether in the spec itself or vendor-specific). This attribute could apply to multiple instruments: `hw.physical_disk` (SFF, LFF), `hw.` (e.g., "blade server", "rack-mount server", etc). Are they in conflict?
3. Does "unrelated" mean "metrics that are defined in different instruments"? Or something else? For example, are `hw.status`, `process.cpu.utilization` and `hw.physical_disk.endurance_utilization` metrics "unrelated"? They all have a `state` attribute?

2023-04-01 10:49 UTC, sebastien-rosset commented on specification/common/attribute-naming.md
> +Names SHOULD NOT coincide with namespaces. For example if `service.instance.id` is an attribute name then it is no longer valid to have an attribute named `service.instance` because `service.instance
Because namespacing is now optional for per-metric attributes, it makes it more likely that a standard OTEL attributes will indeed coincide with namespaces. The more flat attributes are defined, the more likely it is that namespaces will coincide with names.
I do see the sentence starts with "SHOULD NOT", which is not the same as "MUST NOT".

2023-04-01 11:01 UTC, sebastien-rosset commented
> @Oberon00 The requirement is actually explicit: when attributes apply to metrics and traces, they must be identical and thus use namespacing as required for trace attributes (like: `http.method`, etc.)
> 
> See "Recommendations for OpenTelemetry authors":
> 
> > Semantic conventions exist for four areas: for Resource, Span, Log, and Metric attribute names. In addition, for spans we have two more areas: Event and Link attribute names. Identical namespaces or names in all these areas MUST have identical meanings. For example the http.method span attribute name denotes exactly the same concept as the http.method metric attribute, has the same data type and the same set of possible values (in both cases it records the value of the HTTP protocol's request method as a string).

This may be a nitpick: the word "MUST" has a specific [compliance meaning](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/README.md#notation-conventions-and-compliance), it does not seem right to use it under a section titled "Recommendations":

> Recommendation: a suggestion or proposal as to the best course of action, especially one put forward by an authoritative body.

2023-04-03 17:10 UTC, bertysentry commented on specification/common/attribute-naming.md
>  Attribute names that start with `otel.` are reserved to be defined by
`otel.*` namespace is reserved for metrics and attributes pertaining to OpenTelemetry itself, like the collector, or the protocol, etc.

Please note this PR doesn't change anything in this section.

2023-04-03 17:13 UTC, bertysentry commented on specification/common/attribute-naming.md
> +> Attribute names are also known as the "attribute keys". For brevity within
Agreed, but this reshuffling must be done in a separate PR. We first need to fix the attributes naming part, and then try refactoring other parts of the specifications.

2023-04-03 17:44 UTC, bertysentry commented on specification/common/attribute-naming.md
> +| Metrics  | Optional    | Identical attribute names are unlikely to conflict across unrelated metrics. Identical attribute names for different metrics may be desirable (e.g. `state`, `direction`). N
Excellent questions!

The comment/explanation for *Metrics* can be improved, I'm sure.

Most implementations of metrics time series do filter the possible values (cardinality) of an attribute **per metric**.

Example:

You have these data points with the same attribute `state`:
* `hw.status{state="ok"}`
* `hw.status{state="failed"}`
* `system.filesystem.usage{state="free"}`

When querying `hw.status{state~=".*"}`, you will get 2 timeseries for `ok` and `failed`, and you will not get one empty for the value `free` of the `state` attribute. That's because `state="free"` is associated only to `system.filesystem.usage`.

This means that using `state` (with no namespace, and therefore possible semantic conflicts) with different meanings for 2 different and unrelated metrics is not a problem, so it should be allowed by the conventions.

For the same reason, in your example, it's not a problem if `form_factor` for one 3rd-party metric doesn't strictly follow the rules and meaning of the same `form_factor` attribute of another metric (3rd-party, or semantic convention).

Now, some time series server and query language allow querying the values of an attribute, independently from the metric it is associated (like using `__name__` in PromQL), but it's very easy to update such query to filter the attributes belonging to a given group of metrics (typically, belonging to the same namespace).

So, as attributes are defined for each metric, and that metric names **must** include a namespace, it is not required to have such namespace in the attributes themselves too: it's an unnecessary duplicate information.

The only case where using namespaces in metric attributes is when these attributes must match with the attributes of traces, which **must** contain a namespace.

I'm not sure how to summarize the logic in a couple sentences for the above table, though...

2023-04-03 22:57 UTC, bertysentry commented on specification/common/attribute-naming.md
> +Names SHOULD NOT coincide with namespaces. For example if `service.instance.id` is an attribute name then it is no longer valid to have an attribute named `service.instance` because `service.instance
TBH I don't see why names should not coincide with namespaces. What technical issue are we trying to prevent with this recommendation? I'm not sure...

2023-04-03 23:05 UTC, bertysentry commented on specification/common/attribute-naming.md
>  - All names that are part of OpenTelemetry semantic conventions SHOULD be part
Correct! At least it should be updated to properly explain when it's mandatory or not.

2023-04-11 10:44 UTC, bertysentry commented
@jsuereth @sebastien-rosset Any chance we can discuss the clarification on the requirement of namespaces for metric attributes?

2023-04-19 20:45 UTC, jsuereth requested changes
I think this PR needs a lot more justification.   As others have pointed out:

- We want to share attributes between metrics + other signals.  This is to aide in telemetry correlation, one of OTEL's core missions.  Why the disparity?
- There's a lot of title changes in this PR that are extraneous the actual meat of what you want to do.  Please pull that into a separate PR.
- Have you verified that all semconv attributes *are* part of a namespace before making this restriction?
- It would be a breaking change to go from SHOULD -> MUST for *general* attributes being part of a namespace.  Specifically, as worded this PR would require a major version bump of the specification if I'm reading it right (usage of `MUST`).

Overall, I'm really not sure what we gain here.

2023-04-27 23:56 UTC, bertysentry commented
@jack-berg Do you have any feedback on this proposed change on the use of namespaces for metrics attributes? Thanks!

2023-04-28 02:35 UTC, sebastien-rosset commented
[jsuereth](https://github.com/jsuereth) wrote:
> Overall, I'm really not sure what we gain here.

One crucial difference is this change:

```diff
- All names that are part of OpenTelemetry semantic conventions SHOULD be part
  of a namespace.
+ All attribute names that are part of OpenTelemetry semantic conventions for
  Resources, Traces, and Logs SHOULD be part of a namespace.
```

The spec states metric/attribute names are hierarchical: 

> Metric names and attributes exist within a single universe and a single hierarchy. Metric names and attributes MUST be considered within the universe of all existing metric names. When defining new metric names and attributes, consider the prior art of existing standard metrics and metrics from frameworks/libraries.

There are other parts of the spec that elaborate on the namespace hierarchy. However, many of the per-metric attributes in the semantic guidelines do not use a hierarchical structure, so it seems the spec is not following its own rules. Related issues/PRs are #3131, #3431.

The proposed change by @bertysentry is *technically* resolving the contradiction, but only because it omits "metric attribute" from the sentence. I'd like to see something more explicit, i.e. a sentence that states and explains why metric attribute are not subject to the hierarchical naming rule.

2023-05-01 22:44 UTC, bertysentry commented
@sebastien-rosset See @tigrannajaryan's [comment on PR #3431](https://github.com/open-telemetry/opentelemetry-specification/pull/3431#issuecomment-1520885889) on why metrics attributes don't need namespaces.

2023-05-09 04:38 UTC, reyang commented
@bertysentry heads up - most likely this PR will be closed, and we'll ask you to resubmit the PR in a new repo, please refer to https://github.com/open-telemetry/opentelemetry-specification/pull/3474#issuecomment-1539386505.

2023-05-12 16:23 UTC, jsuereth commented
> However, many of the per-metric attributes in the semantic guidelines do not use a hierarchical structure, so it seems the spec is not following its own rules. Related issues/PRs are https://github.com/open-telemetry/opentelemetry-specification/issues/3129, https://github.com/open-telemetry/opentelemetry-specification/issues/3131, https://github.com/open-telemetry/opentelemetry-specification/pull/3431. @jsuereth, I see you have approved https://github.com/open-telemetry/opentelemetry-specification/pull/3431. Does this mean the spec is actually going in the direction of using hierarchical names?


Not necessarily.  We're discussing the direction of this issue in the Technical Comittee ([notes](https://docs.google.com/document/d/1hOHPCu5TGenqTeWPB9qQB_qd33uITZBcvK1FnWxYJAw/edit#heading=h.qnpuj2mrtcts)).  It's a "hot topic".  That *is* my viewpoint, but we're likely to reach a bit of a compromise/middle ground here.

2023-05-24 03:08 UTC, trask commented
hey all, the https://github.com/orgs/open-telemetry/teams/technical-committee is reviewing this issue, and asked to create a summary of pros/cons. I have created https://github.com/open-telemetry/semantic-conventions/issues/51 based on the comments here, please comment further over there if I missed anything, thx!

2023-06-07 03:17 UTC, closed without merging