Add new runtime environment metrics
open-telemetry/opentelemetry-specification pull request #3352
Opened 2023-03-30 18:45 UTC by roberttoyonaga

## Changes
This PR adds `process.runtime.jvm.memory.allocation`, `process.runtime.jvm.cpu.monitor.wait`, `process.runtime.jvm.cpu.monitor.blocked`, `process.runtime.jvm.cpu.count`, and `process.runtime.jvm.cpu.context_switch` metrics to the runtime environment metrics. 

Metric gathering implementations for these new metrics already exist in a basic form in https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation/runtime-telemetry-jfr/library 
Once the details around these new metrics are decided, the implementations can be updated.
 
JFR streaming would be used to gather these metrics. This feature has only been available since JDK 14 so these metrics would only be supported for JDK17+. 

Please see original discussion in this [PR](https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/7886#discussion_r1123469044) and at the [Java + Instrumentation SIG](https://docs.google.com/document/d/1WK9h4p55p8ZjPkxO75-ApI9m0wfea6ENZmMoFRvXSCw/edit#heading=h.7khhmsx7w18m). 

Related issues #

2023-04-02 18:52 UTC, trask commented on specification/metrics/semantic_conventions/runtime-environment-metrics.md
> +|                                                |                                                                                                 |              |
I think both `thread` and `class` would need to be opt-in due to cardinality?

> For example, Metric attributes that may have high cardinality can only be defined with `Opt-In` level.

https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/common/attribute-requirement-level.md#attribute-requirement-levels-for-semantic-conventions

2023-04-02 18:52 UTC, trask commented on specification/metrics/semantic_conventions/runtime-environment-metrics.md
> +| process.runtime.jvm.cpu.monitor.wait           | Time thread time spend waiting at a monitor                                                     | Milliseconds | `ms`
probably should go ahead and change this from `ms` to `s`, see #3312 and https://github.com/open-telemetry/opentelemetry-specification/issues/2977#issuecomment-1489150771

2023-04-03 11:21 UTC, mateuszrzeszutek commented on specification/metrics/semantic_conventions/runtime-environment-metrics.md
> +| process.runtime.jvm.memory.usage               | Measure of memory used                                                                          | Bytes        | `By`
Aren't all of the "old" metrics JDK8+ though?

2023-04-03 13:19 UTC, roberttoyonaga commented on specification/metrics/semantic_conventions/runtime-environment-metrics.md
> +|                                                |                                                                                                 |              |
Yes, I was unsure of these attributes.  I think opt-in is a good idea.

2023-04-03 13:20 UTC, roberttoyonaga commented on specification/metrics/semantic_conventions/runtime-environment-metrics.md
> +| process.runtime.jvm.memory.usage               | Measure of memory used                                                                          | Bytes        | `By`
oh yes you're right, I confused the versions by accident

2023-04-05 14:01 UTC, jack-berg commented on specification/metrics/semantic_conventions/runtime-environment-metrics.md
> +| process.runtime.jvm.cpu.monitor.wait           | Time thread time spend waiting at a monitor                                                     | Seconds  | `s`
```suggestion
| process.runtime.jvm.cpu.monitor.wait           | Time thread was waiting at a monitor                                                     | Seconds  | `s`                                       | Histogram                                         | Int64      |               |                            | JDK 17+      | Required          |
```

2023-04-05 14:03 UTC, jack-berg commented on specification/metrics/semantic_conventions/runtime-environment-metrics.md
> +| process.runtime.jvm.cpu.count                  | Effective CPU count                                                                             | CPUs     | `{cpus}`
This metric was previously rejected in #2392. Should review those arguments and decide if something has changed to warrant reconsideration.

2023-04-05 14:15 UTC, reyang commented on specification/metrics/semantic_conventions/runtime-environment-metrics.md
> +| process.runtime.jvm.cpu.utilization            | Recent CPU utilization for the process [2]                                                      | 1        | 1
I have a question for @jack-berg which is not introduced by / directly related to this PR:

What does unit 1 mean? (what exactly do we want the instrumentation owner to put as the instrument unit argument?) Why is this 1 instead of `1`?

![image](https://user-images.githubusercontent.com/17327289/230108105-24ed38f4-b699-4d3e-940e-99545a6e6d30.png)

2023-04-05 19:02 UTC, jack-berg commented on specification/metrics/semantic_conventions/runtime-environment-metrics.md
> +| process.runtime.jvm.cpu.utilization            | Recent CPU utilization for the process [2]                                                      | 1        | 1
Looks like I originally added those [here](https://github.com/open-telemetry/opentelemetry-specification/commit/374c34c8fe53edee24a33c58ce11cd70d3e0b4c6), and was trying to follow the lead of [other utilization metrics](https://github.com/open-telemetry/opentelemetry-specification/blame/02d378a0586296b98daec2babcc6d57847c670ba/specification/metrics/semantic_conventions/system-metrics.md#L51). 

We also have [general guidance](https://github.com/open-telemetry/opentelemetry-specification/blame/02d378a0586296b98daec2babcc6d57847c670ba/specification/metrics/semantic_conventions/README.md#L181-L182) that utilization metrics should set the unit to be "the default unit `1` (the unity)". This language appears to come from [UCUM](https://unitsofmeasure.org/ucum#section-Character-Set-and-Lexical-Rules) (see section on "curly braces"), but also seems inconsistent with [our recommendation](https://github.com/open-telemetry/opentelemetry-specification/blame/main/specification/metrics/semantic_conventions/README.md#L191-L192) to use UCUM case insensitive variant, since there is no such variant for "the unity". We might be better suited recommending using the "percent" unit, with "%" recorded in the unit field.

2023-04-05 19:45 UTC, roberttoyonaga commented on specification/metrics/semantic_conventions/runtime-environment-metrics.md
> +| process.runtime.jvm.cpu.monitor.wait           | Time thread time spend waiting at a monitor                                                     | Seconds  | `s`
Oh I see. I'll update this

2023-04-05 19:51 UTC, roberttoyonaga commented on specification/metrics/semantic_conventions/runtime-environment-metrics.md
> +|                                                |                                                                                                 |          |
Ok I'm in favor of replacing the `class` attribute with `arena`

2023-04-05 19:53 UTC, roberttoyonaga commented on specification/metrics/semantic_conventions/runtime-environment-metrics.md
> +| process.runtime.jvm.cpu.monitor.blocked        | Time thread spend blocked at a monitor                                                          | Seconds  | `s`
Yes, these are not in the current implementation. I have added them here because I feel they could be useful. jdk.JavaMonitorWait and jdk.JavaMonitorEnter produce those metrics.

2023-04-05 20:16 UTC, roberttoyonaga commented on specification/metrics/semantic_conventions/runtime-environment-metrics.md
> +| process.runtime.jvm.cpu.count                  | Effective CPU count                                                                             | CPUs     | `{cpus}`
Thanks for linking that. Nothing has changed as far as I am aware so I will remove `process.runtime.jvm.cpu.count`.

2023-04-05 20:31 UTC, roberttoyonaga commented on specification/metrics/semantic_conventions/runtime-environment-metrics.md
> +|                                                |                                                                                                 |          |
With respect to `process.runtime.jvm.cpu.monitor.blocked` and  `process.runtime.jvm.cpu.monitor.wait` the `class` attribute references the monitor class. Do you agree that `class` can remain as opt-in here?

2023-04-06 03:49 UTC, reyang commented on specification/metrics/semantic_conventions/runtime-environment-metrics.md
> +| process.runtime.jvm.cpu.utilization            | Recent CPU utilization for the process [2]                                                      | 1        | 1
Now that you mentioned `%`, it seems the common practice in Prometheus is to use PromQL to calculate the percentage instead of directly emitting percentage gauge.

Also @Yun-Ting raised a good question here https://github.com/open-telemetry/opentelemetry-specification/issues/3200#issue-1578707001.

2023-04-06 03:51 UTC, reyang commented on specification/metrics/semantic_conventions/runtime-environment-metrics.md
> +| process.runtime.jvm.cpu.utilization            | Recent CPU utilization for the process [2]                                                      | 1        | 1
Anyways I don't intend to derail this PR.

2023-04-07 16:35 UTC, mateuszrzeszutek commented on specification/metrics/semantic_conventions/runtime-environment-metrics.md
> +| process.runtime.jvm.gc.duration                | Duration of JVM garbage collection actions                                                      | Seconds  | `s`
Note that we'll probably need to have #3216 first before we can switch to seconds

2023-04-07 17:18 UTC, jack-berg commented on specification/metrics/semantic_conventions/runtime-environment-metrics.md
> +| process.runtime.jvm.gc.duration                | Duration of JVM garbage collection actions                                                      | Seconds  | `s`
#3216 unlocks some cool options for the histograms we use in the jvm runtime domain. The default buckets don't do us much good - it will be cool to tune the buckets to have better defaults.

2023-04-08 01:36 UTC, roberttoyonaga commented on specification/metrics/semantic_conventions/runtime-environment-metrics.md
> +| process.runtime.jvm.gc.duration                | Duration of JVM garbage collection actions                                                      | Seconds  | `s`
Ok I see. So switching to seconds before tuning the buckets would make a lopsided, not so useful histogram. Ok I'll change the units back to milliseconds for all the time-based metrics.

2023-04-12 21:46 UTC, trask commented on specification/metrics/semantic_conventions/runtime-environment-metrics.md
> +| process.runtime.jvm.cpu.utilization            | Recent CPU utilization for the process [2]                                                      | 1        | 1
> Now that you mentioned `%`, it seems the common practice in Prometheus is to use PromQL to calculate the percentage (derive percentage from other metric streams) instead of directly emitting percentage gauge.
> 
> Also @Yun-Ting raised a good question here [#3200 (comment)](https://github.com/open-telemetry/opentelemetry-specification/issues/3200#issue-1578707001).

I think this case is different because it's not "average CPU over interval" (which could be calculated at query time).

see the footnote:

> **[2]**: These utilizations are not defined as being for the specific interval since last measurement (unlike `system.cpu.utilization`).

this is the source of data for this metric: https://docs.oracle.com/en/java/javase/17/docs/api/jdk.management/com/sun/management/OperatingSystemMXBean.html#getProcessCpuLoad()

2023-04-21 04:07 UTC, trask reviewed
can you add `note` sections and link to the Java APIs that would (typically) be used to collect these? (related to #3418)

2023-04-21 04:07 UTC, trask commented on specification/metrics/semantic_conventions/runtime-environment-metrics.md
> +| process.runtime.jvm.cpu.utilization            | Recent CPU utilization for the process [2]                                                      | 1        | 1
I believe @reyang's original concern is now addressed by #3393

2023-04-21 04:07 UTC, trask commented on semantic_conventions/metrics/process-runtime-jvm-metrics.yaml
> +    brief: "Size of object allocated by thread. Only available in JDK 17+."
I think(?) this could be implemented in Java 8 using https://docs.oracle.com/javase/8/docs/jre/api/management/extension/com/sun/management/ThreadMXBean.html#getThreadAllocatedBytes-long:A-

2023-04-21 04:07 UTC, trask commented on semantic_conventions/metrics/process-runtime-jvm-metrics.yaml
> +    brief: "Describes JVM monitor metric attributes. "
```suggestion
    brief: "Describes JVM monitor metric attributes."
```

2023-04-21 04:07 UTC, trask commented on semantic_conventions/metrics/process-runtime-jvm-metrics.yaml
> +    brief: "Describes JVM network IO metric attributes. "
```suggestion
    brief: "Describes JVM network IO metric attributes."
```

2023-04-21 13:16 UTC, roberttoyonaga commented on semantic_conventions/metrics/process-runtime-jvm-metrics.yaml
> +    brief: "Size of object allocated by thread. Only available in JDK 17+."
I think that's a little bit different. ThreadMXbean returns the cumulative allocation per thread, while the JFR event ObjectAllocationSample describes a single allocation instance (sampled to reduce overhead. Sampling only happens on the TLAB slow path). But now that I think about it, it might be more useful to know the total allocation per thread rather than have statistical data on allocation sizes per thread.  Additionally, the statistical data would be skewed because sampling is only done on the slow path when a new TLAB is required, or allocations won't fit into a TLAB (this is because the events purpose is to show where the allocations are happening, not how big they are).

2023-04-21 13:26 UTC, roberttoyonaga commented
> can you add `note` sections and link to the Java APIs that would (typically) be used to collect these? (related to #3418)

Hi @trask , do you mean in the note section of attributes? I'm having trouble figuring out how to get the note's to show for the metrics themselves. 

Additionally, I wasn't sure the best way to denote which metrics are available in JDK 17+ only. Based on https://github.com/open-telemetry/build-tools/blob/v0.17.0/semantic-conventions/syntax.md, maybe `note` ?(but notes only seem to be generated for attributes?

2023-04-21 13:42 UTC, jack-berg commented on semantic_conventions/metrics/process-runtime-jvm-metrics.yaml
> +    brief: "Size of object allocated by thread. Only available in JDK 17+."
> I think(?) this could be implemented in Java 8 using https://docs.oracle.com/javase/8/docs/jre/api/management/extension/com/sun/management/ThreadMXBean.html#getThreadAllocatedBytes-long:A-

That would be cool. 

> the JFR event ObjectAllocationSample describes a single allocation instance (sampled to reduce overhead. Sampling only happens on the TLAB slow path). 

If we continue to report this in JFR, we'll want to somehow communicate to users that thee allocations are sampled. 

> this is because the events purpose is to show where the allocations are happening, not how big they are

Presumably for building out a profile?

2023-04-21 13:45 UTC, jack-berg commented on semantic_conventions/metrics/process-runtime-jvm-metrics.yaml
> +    unit: "ms"
Will want to use `s` unit for all durations

2023-04-21 13:46 UTC, jack-berg commented on semantic_conventions/metrics/process-runtime-jvm-metrics.yaml
> +  - id: metric.process.runtime.jvm.cpu.monitor.blocked
Is it ever useful to sum together the time a monitor was blocked and waiting? Trying to think about whether blocked vs waiting makes sense as an attribute rather than a separate metric.

2023-04-21 13:48 UTC, roberttoyonaga commented on semantic_conventions/metrics/process-runtime-jvm-metrics.yaml
> +    brief: "Size of object allocated by thread. Only available in JDK 17+."
> Presumably for building out a profile?

Yup, you can generate flame graphs from the stack traces and other useful things like that. 

> If we continue to report this in JFR

I think that we should not report allocations with JFR because the purpose of those events is actually a little different than what we want to use them for. Also, the current implementation (jdk.ObjectAllocationInNewTLAB and jdk.ObjectAllocationOutsideTLAB) would result in too high an overhead for people to use in production. Those events are turned off by default in both monitoring and profiling JFR configurations. This is because they aren't throttled like jdk.ObjectAllocationSample is.

2023-04-21 13:49 UTC, jack-berg commented on semantic_conventions/metrics/process-runtime-jvm-metrics.yaml
> +      - id: thread
Let's reuse the general [thread.id](https://github.com/open-telemetry/opentelemetry-specification/blob/85810dbb6a6b5f339aad38adb776321cce17cbde/semantic_conventions/trace/general.yaml#L261) attribute for this.

2023-04-21 13:50 UTC, jack-berg commented on semantic_conventions/metrics/process-runtime-jvm-metrics.yaml
> +      - ref: thread
Does this mean that this inherits [all the thread](https://github.com/open-telemetry/opentelemetry-specification/blob/85810dbb6a6b5f339aad38adb776321cce17cbde/semantic_conventions/trace/general.yaml#L255-L270) attributes?

2023-04-21 13:53 UTC, roberttoyonaga commented on semantic_conventions/metrics/process-runtime-jvm-metrics.yaml
> +      - ref: thread
It seems to be using the `thread` definition in this file instead. Maybe its overridden.

2023-04-21 14:03 UTC, roberttoyonaga commented on semantic_conventions/metrics/process-runtime-jvm-metrics.yaml
> +      - id: thread
If I reuse `thread.id`, I'm not sure I can change the requirement level.

2023-04-21 15:16 UTC, trask commented
> Hi @trask , do you mean in the note section of attributes? I'm having trouble figuring out how to get the note's to show for the metrics themselves.

oh, you're right, let's just add a manual "Note" at the end of each metric section in the markdown for now, and I'll open an issue in build-tools about adding "note" to metrics in yaml

2023-04-21 15:20 UTC, trask commented on semantic_conventions/metrics/process-runtime-jvm-metrics.yaml
> +    unit: "ms"
should we add bucket recommendation at the same time?

2023-04-21 15:26 UTC, trask commented on semantic_conventions/metrics/process-runtime-jvm-metrics.yaml
> +  - id: metric.process.runtime.jvm.cpu.monitor.blocked
seems similar to [`process.cpu.time`](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/process-metrics.md#process) which has attribute

> `state`, if specified, SHOULD be one of: `system`, `user`, `wait`

so maybe `process.runtime.jvm.cpu.monitor.time` with attribute `state`?

2023-04-27 20:04 UTC, roberttoyonaga commented on semantic_conventions/metrics/process-runtime-jvm-metrics.yaml
> +  - id: metric.process.runtime.jvm.cpu.monitor.blocked
Yup I think that's a good idea

2023-04-28 15:53 UTC, trask commented on semantic_conventions/metrics/process-runtime-jvm-metrics.yaml
> +    metric_name: process.runtime.jvm.cpu.context_switch
```suggestion
    metric_name: process.runtime.jvm.context_switches
```

2023-04-28 16:59 UTC, jack-berg commented on semantic_conventions/metrics/process-runtime-jvm-metrics.yaml
> +      - id: class
Checkout the [code.namespace](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/span-general.md#source-code-attributes) field as an alternative to defining a new attribute.

2023-04-28 17:01 UTC, jack-berg commented on semantic_conventions/metrics/process-runtime-jvm-metrics.yaml
> +    unit: "s"
Covered in #3458.

2023-04-28 17:16 UTC, trask commented on semantic_conventions/metrics/process-runtime-jvm-metrics.yaml
> +      - id: mode
I think ok to change it proactively (that PR could take a while...)

2023-04-28 22:32 UTC, roberttoyonaga commented on semantic_conventions/metrics/process-runtime-jvm-metrics.yaml
> +    metric_name: process.runtime.jvm.cpu.context_switch
Hi @trask I checked the Hotspot code and it seems to me like the the JFR source of this metric does not account of virtual threads, only platform threads. However, it does look like `process.runtime.jvm.context_switches` is a little different because it reports a rate in Hz rather than a count.

2023-04-28 22:36 UTC, roberttoyonaga commented on semantic_conventions/metrics/process-runtime-jvm-metrics.yaml
> +    metric_name: process.runtime.jvm.cpu.context_switch
Also the description for `process.context_switches` says: "Number of times the process has been context switched."  Does this mean it's referring to process context switches rather than thread context switches?

2023-05-08 16:24 UTC, roberttoyonaga commented on semantic_conventions/metrics/process-runtime-jvm-metrics.yaml
> +      - id: mode
ok I changed it to `network.direction`

2023-05-08 16:36 UTC, roberttoyonaga commented on semantic_conventions/metrics/process-runtime-jvm-metrics.yaml
> +  - id: metric.process.runtime.jvm.cpu.monitor.blocked
updated with suggestion applied

2023-05-09 04:38 UTC, reyang commented
@roberttoyonaga heads up - most likely this PR will be closed, and we'll ask you to resubmit the PR in a new repo, please refer to https://github.com/open-telemetry/opentelemetry-specification/pull/3474#issuecomment-1539386505.

2023-05-12 16:20 UTC, jsuereth requested changes
Can you move this to https://github.com/open-telemetry/semantic-conventions ?

2023-05-19 18:14 UTC, roberttoyonaga commented
I've copied this PR over to the new repo here: https://github.com/open-telemetry/semantic-conventions/pull/44 @trask @jack-berg @mateuszrzeszutek

2023-05-19 19:38 UTC, jack-berg commented
Thanks @roberttoyonaga. Closing this PR and picking up the convo over there!

2023-05-19 19:38 UTC, closed without merging