Prototype: ECS adoption in HTTP and network specs
open-telemetry/opentelemetry-specification pull request #3355
Opened 2023-04-01 21:29 UTC by lmolkova

Fixes #3163

2023-04-04 20:51 UTC, trask commented
> * `net.protocol.name` -> `network.protocol.name`
> * `net.protocol.version` -> `network.protocol.version`
> * `net.sock.family` -> `network.type`
> * `net.transport` -> `network.transport`

hey @lmolkova, there was a request in the Spec SIG today that we remove the `net.*` -> `network.*` changes from this PR so that folks can weigh in on whether we should pick OTel or ECS semantics going forward in cases like this where there's no inherent improvement being brought in by the ECS semantics

2023-04-05 15:07 UTC, tigrannajaryan submitted a review, later dismissed
Blocking temporarily to make sure we agree on https://github.com/open-telemetry/opentelemetry-specification/issues/3362 before the breaking changes are done.

The work on this PR can of course continue, I just want to prevent merging this prematurely.

2023-04-07 19:53 UTC, lmolkova commented on semantic_conventions/http-common.yaml
> +        stability: deprecated
automates non-breaking semconv generation

2023-04-07 19:58 UTC, lmolkova commented on specification/trace/semantic_conventions/http.md
> +* `url.scheme`
should query be sampling-relevant?

2023-04-14 18:35 UTC, lmolkova commented on semantic_conventions/trace/http.yaml
> +      - ref: http.request.method
it's needed because we override `sampling-relevant` to `true` on the next line. Sampling-relevant should not be set in cross-signal yaml.

2023-04-14 18:37 UTC, trask approved these changes

2023-04-17 07:23 UTC, AlexanderWert commented
I have two general questions:

## 1. Making HTTP attributes signal agnostic
Currently only a very small subset of HTTP attributes is signal agnostic as defined in the `semantic_conventions/http-common.yaml` file (which makes sense when considering only spans and metrics). However, when considering logs and event, most of the HTTP attributes would be relevant there as well. Not necessarily proposing to make all the attributes signal agnostic with this PR, but just want to make sure it's something we consider at all and can still address later?

## 2. Missing ECS fields
There is a bunch of `http.*` and `url.*` fields in ECS that are not covered here, but that do NOT conflict with existing OTel SemConv attributes:

### Missing HTTP fields
- `http.request.body.content`
- `http.request.bytes`
- `http.request.id`
- `http.request.mime_type`
- `http.request.referrer`
- `http.response.body.content`
- `http.response.bytes`
- `http.response.mime_type`

### Missing URL fields
- `url.domain`
- `url.extension`
- `url.fragment`
- `url.original`
- `url.password`
- `url.port`
- `url.registered_domain`
- `url.subdomain`
- `url.top_level_domain`
- `url.username`

Do you think it makes sense to adopt these fields in this PR as well (as part of "Adopt ECS attributes in HTTP semantic conventions")? Otherwise, we can create a separate PR to add these fields.

2023-04-17 07:58 UTC, Oberon00 commented
> Do you think it makes sense to adopt these fields in this PR as well

We *removed* lots of redundant fields in the HTTP conventions https://github.com/open-telemetry/opentelemetry-specification/pull/2469. These fields seem to define alternative URL splits, which seems to go in the opposite direction.

Is there a general policy for our ECS alignment I could refer to, to see what our goals are with this alignment and how far and in which direction we can align?

2023-04-17 09:19 UTC, AlexanderWert commented
> The fields you mention @AlexanderWert seem to define alternative URL splits, which seems to go in the opposite direction.

Not sure it's defining alternative URL splits or introducing a lot of redundancy. In this PR the new namespace `url.*` is being introduced, but it only covers `scheme`, `path`, `query` and `full`. But other information such as `fragment`, `port`, etc. is missing. Since we are introducing this namespace to allow (optionally) describing a URL on a more fine-grained level, why not just adopting the full ECS `url.*` field set as is? It's not conflicting with other fields and also is not redundant (except for `url.full`, `url.original`, `url.domain`). But there are good reasons / use cases to have these fields separate (see [ECS definition for these fields](https://www.elastic.co/guide/en/ecs/current/ecs-url.html))

> Is there a general policy for our ECS alignment I could refer to, to see what our goals are with this alignment and how far and in which direction we can align?

In this OTEP we specified the following:

> - Long-term, ECS and OTel SemConv will converge into one open standard that is maintained by OpenTelemetry. To kick off this effort, Elastic will nominate several domain experts to join the OpenTelemetry Semantic Convention Approvers to help with maintaining the new standard.
> - OTel SemConv will adopt ECS in its full scope (except for individual adjustments in detail where inevitable), including the logging, observability and security domain fields, to make the new schema a true successor of ECS and OTel SemConv.

So, I would suggest if there are no strong reasons for leaving out certain fields from ECS (especially when they are not conflicting with others in OTel), let's try to adopt them. Otherwise, it would imply unnecessary breaking changes on ECS-based data.

> The only thing I'm wondering about is `url.original`. From the name, it sounds like a better fit for our old http.url than url.full.

[There is a difference](https://www.elastic.co/guide/en/ecs/current/ecs-url.html#field-url-original) between `url.full` and `url.original` in ECS. `url.original` is the value as it has been observed (can be a full URL or a partial URL). While the `url.full` field should actually contain the *full* url.

2023-04-17 12:11 UTC, Oberon00 commented
PR https://github.com/open-telemetry/opentelemetry-specification/pull/2469 was about "Remove alternative attribute sets from HTTP semantic conventions". So the goal was to provide "only one way" to do it. These attributes seem to provide alternative ways to store the same information. So I feel like risk going in circles with our semconv changes.

2023-04-17 15:08 UTC, trask commented
> Currently only a very small subset of HTTP attributes is signal agnostic as defined in the `semantic_conventions/http-common.yaml` file (which makes sense when considering only spans and metrics). However, when considering logs and event, most of the HTTP attributes would be relevant there as well. Not necessarily proposing to make all the HTTP attributes signal agnostic with this PR, but just want to make sure it's something we consider at all and can still address later?

ya, the current PR(s) are only doing the minimal that we need for HTTP tracing and metrics. as long as we don't change the attribute names, we can move them around in the yaml files and reuse them from logging sematic conventions in the future

> `http.request.body.content`, `http.response.body.content`, `http.request.bytes`, `http.response.bytes`

See https://github.com/open-telemetry/oteps/pull/219 (which I personally am very supportive of)

> `http.request.id`

is this different from span id?

> `http.request.mime_type` and `http.response.mime_type`

these would probably map to `http.request.header.content_type` and `http.response.header.content_type`

> `http.request.referrer`

this would probably map to `http.request.header.referer`

> `url.*`

as @Oberon00 mentions, we have intentionally restricted HTTP tracing and metrics to have a more "normalized" structure that makes the telemetry more consistent across all of the different languages and instrumentations

I personally suspect that HTTP logging semantic conventions will be "structure-less" with the ability to pull in a wide variety of attributes, and we could pull in the majority of the ECS attributes at that time. The General Semantic Convention WG is probably a good place to kick off that discussion if you are able to join at 10a Pacific Time today (in ~2 hours)

2023-04-17 15:44 UTC, tigrannajaryan commented
I believe logs should share many (most) of the semantic conventions with traces. There may be exceptions to this, but I would expect that the vast majority of conventions are the same for traces and logs. This includes http conventions, I don't see why logs need to have different conventions.

2023-04-17 18:13 UTC, trask commented
> I believe logs should share many (most) of the semantic conventions with traces. There may be exceptions to this, but I would expect that the vast majority of conventions are the same for traces and logs. This includes http conventions, I don't see why logs need to have different conventions.

I created #3405 to track this

2023-04-19 21:59 UTC, trask commented
@lmolkova should we add `url.fragment` in this PR?

2023-04-20 02:38 UTC, lmolkova commented
> @lmolkova should we add `url.fragment` in this PR?

done, however I don't think we can reference it from HTTP semconv - we don't collect URL components for clients and it's not available on server.

2023-04-20 02:42 UTC, lmolkova commented
wrt `url.full` vs `ur.original` - original in some rare (on client) cases could be relative one and then we still want to force client instrumentation to reconstruct the full (absolute) URL so it includes scheme, target, query, and components.

We'll need to figure out how to add per-component attributes, but they'd be optional (for clients) and `url.full` would remain required.

2023-04-24 16:03 UTC, jsuereth approved these changes
At a minimum:

- The clarity/consistency of `http.request.*` and `http.response.*` LGTM
- I really like the further fragmentation of `url`

I have (had) overall concerns around sensitive information and semantic conventions *specifically* `http.url` and now `url.*` that I think we need some special call out for.  However, that's orthogonal to this PR and we can clean up in another PR.  I think, overall, this PR helps the issue, but would love to hear your thoughts on best ways to address those concerns.

2023-04-24 16:03 UTC, jsuereth commented on semantic_conventions/url.yaml
> +          `url.full` SHOULD capture the absolute URL when it's available and SHOULD not validate or modify
I think it's more than likely that there could be other types of sensitive information in path/query.

I think we should make a general disclaimer about:

- Sensitive information CAN and WILL be redacted.
- In systems unable to identify sensitive information, the entirety of the field may be redacted.
- The existing callouts you have about dropping username/password from `url.full`.

2023-04-24 16:45 UTC, lmolkova commented on semantic_conventions/url.yaml
> +      - id: fragment
we don't have such property, but it's a great point. I created tools issue to track it https://github.com/open-telemetry/build-tools/issues/168

BTW, we only use `scheme` in metric - all other components have high cardinality in common case

2023-04-24 18:08 UTC, lmolkova commented on semantic_conventions/url.yaml
> +          `url.full` SHOULD capture the absolute URL when it's available and SHOULD not validate or modify
Agreed. I added `url.md` files with notes on this. I think we'll need to have a cross-convention section on this though - I don't see any clarity in the spec. Created https://github.com/open-telemetry/opentelemetry-specification/issues/3436.

2023-04-26 19:39 UTC, trask commented
@lmolkova based on https://github.com/open-telemetry/opentelemetry-specification/issues/3439#issuecomment-1523942508 (and offline discussion with @AlexanderWert and @ruflin) I'd suggest that we go ahead in this PR with:

* `http.request.body.size`
* `http.response.body.size`

2023-04-27 10:48 UTC, AlexanderWert approved these changes
LGTM, added only a few minor comments

2023-04-27 11:41 UTC, dyladan commented
> wrt `url.full` vs `ur.original` - original in some rare (on client) cases could be relative one and then we still want to force client instrumentation to reconstruct the full (absolute) URL so it includes scheme, target, query, and components.
> 
> We'll need to figure out how to add per-component attributes, but they'd be optional (for clients) and `url.full` would remain required.

Is it always possible to construct `url.full`? It seems to me that `url.original` is much easier and a lot less likely to get wrong. Especially since it will need to be done in many languages and many instrumentations, there is a lot surface area for it to be incorrectly reconstructed. There may even be multiple correct ways to construct `url.full` leading to seemingly different urls in your backend when they are actually the same. I would argue for whatever attribute is easier and more likely to be correct (`url.original`) and leave constructing `url.full` to backends which need it and can do it consistently.

2023-04-27 11:43 UTC, dyladan commented
> > wrt `url.full` vs `ur.original` - original in some rare (on client) cases could be relative one and then we still want to force client instrumentation to reconstruct the full (absolute) URL so it includes scheme, target, query, and components.
> > We'll need to figure out how to add per-component attributes, but they'd be optional (for clients) and `url.full` would remain required.
> 
> Is it always possible to construct `url.full`? It seems to me that `url.original` is much easier and a lot less likely to get wrong. Especially since it will need to be done in many languages and many instrumentations, there is a lot surface area for it to be incorrectly reconstructed. There may even be multiple correct ways to construct `url.full` (`https://example.com:443/` vs `https://example.com`) leading to seemingly different urls in your backend when they are actually the same. I would argue for whatever attribute is easier and more likely to be correct (`url.original`) and leave constructing `url.full` to backends which need it and can do it consistently.

Also, the fact that some http client was called with a relative URL vs an absolute one is a valuable signal that may be lost.

2023-04-27 12:41 UTC, Oberon00 commented
> Also, the fact that some http client was called with a relative URL

Oh, I didn't think of that use case... How do you do this today e.g. in Node.js where it is very common to supply hostname + target separately? Probably you need to already construct a full http.url?

2023-04-27 12:57 UTC, AlexanderWert commented on semantic_conventions/url.yaml
> +        examples: ["?q=OpenTelemetry"]
Good point. 
It should not!

2023-04-27 14:15 UTC, mateuszrzeszutek approved these changes

2023-04-27 14:15 UTC, mateuszrzeszutek commented on specification/trace/semantic_conventions/instrumentation/aws-lambda.md
> +| `url.full` | `https://foo.execute-api.us-east-1.amazonaws.com/pets/10` |  |
Since this is a SERVER span example, consider removing `url.full` (since HTTP server instrumentations don't report the full URL) and adding `net.host.(name|port)`

2023-04-27 14:51 UTC, trask commented
> Is it always possible to construct `url.full`? It seems to me that `url.original` is much easier and a lot less likely to get wrong. Especially since it will need to be done in many languages and many instrumentations, there is a lot surface area for it to be incorrectly reconstructed. There may even be multiple correct ways to construct `url.full` (`https://example.com:443/` vs `https://example.com`) leading to seemingly different urls in your backend when they are actually the same. I would argue for whatever attribute is easier and more likely to be correct (`url.original`) and leave constructing `url.full` to backends which need it and can do it consistently.

this PR doesn't change anything with regard to constructing the full url for HTTP client instrumentation, which was already the current state since #2469:

https://github.com/open-telemetry/opentelemetry-specification/blob/b5c6a6dc48752a3ea740f08bed0c2975bae19673/specification/trace/semantic_conventions/http.md?plain=1#L137

it's definitely ok to reconsider this, but just wanted to point out the previous discussions on it first, in particular https://github.com/open-telemetry/opentelemetry-specification/issues/2114#issuecomment-1079473468

2023-04-27 19:44 UTC, jonatan-ivanov requested changes

2023-04-27 19:44 UTC, jonatan-ivanov commented on semantic_conventions/url.yaml
> +          For network calls, URL usually has `scheme://host[:port]/path?query[#fragment]` format, where the fragment
Based on the RFC, the leading `/` is part of the path: https://www.rfc-editor.org/rfc/rfc3986#section-3

This means that if the url is `https://example.corg/test` then the path is `/test` (not `test`). So I guess this should look like:

```suggestion
          For network calls, URL usually has `scheme://host[:port][path][?query][#fragment]` format, where the fragment
```
This also means that `?` is not part of the query as well as `#` is not part of the fragment, I think the RFC make a good job making that more explicit:
```
   The following are two example URIs and their component parts:

         foo://example.com:8042/over/there?name=ferret#nose
         \_/   \______________/\_________/ \_________/ \__/
          |           |            |            |        |
       scheme     authority       path        query   fragment
          |   _____________________|__
         / \ /                        \
         urn:example:animal:ferret:nose
```

2023-04-28 01:23 UTC, lmolkova commented on semantic_conventions/url.yaml
> +          For network calls, URL usually has `scheme://host[:port]/path?query[#fragment]` format, where the fragment
great catch! fixed and  thank you

2023-04-28 01:31 UTC, lmolkova commented
wrt capturing/reconstructing full URL:
- we still need all URL components. While we can rely on server.address/port to be provided in attributes, scheme is not exposed 
- someone needs to reconstruct URL to normalize data:  it can be instrumentation, processor, collector, backend, or user query. Arguably, instrumentation has the most knowledge and should do it.

This does not block us from also capturing `url.original` (e.g. if different than full one or as an opt-in attribute) at any point in the future.

2023-04-28 01:52 UTC, lmolkova commented on semantic_conventions/trace/http.yaml
> +          conditionally_required: if available.
Good point!
Let's make it recommended. The rationale:
- recommended attributes can be opted-out from (if instrumentation supports it)
- common HTTP instrumentations libraries have no idea if the query has sensitive information and no way to check. So condition like "does not contain sensitive information" would mean that OTel-authored instrumentations should rather NOT capture query
- sensitive info is probably relatively rare (hello, query parameters auth) and can be scrubbed with in-proc or collector processor or a backend

2023-04-28 07:20 UTC, mateuszrzeszutek approved these changes

2023-04-28 07:20 UTC, mateuszrzeszutek commented on semantic_conventions/url.yaml
> +          In such case username and password should be redacted and attribute's value should be `https://[REDACTED]:[REDACTED]@www.example.com/`.
`[]` are reserved characters, and the user info component can not contain them according to the RFC: https://www.rfc-editor.org/rfc/rfc3986#section-3.2.1

We should use `REDACTED:REDACTED`, `_REDACTED_:_REDACTED_`, or anything else that produces a valid URL instead.

2023-05-02 08:49 UTC, Oberon00 commented
IMHO, url.original as currently described in ECS might be too loosely defined to be useful. E.g. if some library allows constructing an HttpClient that refers to a particular base URL, url.original might capture only the part after the base URL (e.g. .NET https://learn.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.baseaddress?view=net-8.0).

2023-05-08 23:21 UTC, reyang commented
> Blocking temporarily to make sure we agree on #3362 before the breaking changes are done.
> 
> The work on this PR can of course continue, I just want to prevent merging this prematurely.

@tigrannajaryan #3362 is now resolved/merged, unblocking the PR.

2023-05-09 02:55 UTC, merged