Add semantic conventions for Elasticsearch client instrumentation
open-telemetry/opentelemetry-specification pull request #3358
Opened 2023-04-03 11:14 UTC by estolfo

Fixes #3239

## Changes

Add semantic conventions for Elasticsearch client instrumentation span names and attributes.

Related [OTEP(s)](https://github.com/open-telemetry/oteps)

- #3239

2023-04-03 15:16 UTC, reyang commented on specification/trace/semantic_conventions/README.md
> +* [Elasticsearch](instrumentation/elasticsearch.md): For Elasticsearch spans.
nit: use alphabetical ordering

2023-04-04 13:36 UTC, estolfo commented on specification/trace/semantic_conventions/instrumentation/elasticsearch.md
> +| `db.elasticsearch.url`    | string | The exact url of the request, including the target and document id. | `'/test-index/_doc/123'`                                | Required               |
Good point, thanks for pointing that out.
In looking at the discussion [here](https://github.com/orgs/open-telemetry/projects/41?pane=issue&itemId=19832331), I propose that instead we use `url.path` and `url.query` instead of `db.elasticsearch.url` and `db.elasticsearch.params`. What do you think?

2023-04-04 13:37 UTC, estolfo commented on specification/trace/semantic_conventions/instrumentation/elasticsearch.md
> +| `db.elasticsearch.method` | string | The HTTP method of the request.                                     | `'GET'`                                                 | Required               |
ok, this makes sense as well. Thanks

2023-04-05 11:32 UTC, estolfo commented on specification/trace/semantic_conventions/instrumentation/elasticsearch.md
> +| `db.elasticsearch.url`    | string | The exact url of the request, including the target and document id. | `'/test-index/_doc/123'`                                | Required               |
Thanks both @reyang and @trask for your input.
I would like to proceed with getting this semantic conventions definition merged sooner rather than later, even if it means using an attribute (`db.elasticsearch.url.path`) that will eventually be changed (to `url.path`). The reason is that I've stalled [this PR](https://github.com/open-telemetry/opentelemetry-ruby-contrib/pull/357) to the Ruby OTel contrib repo for Elasticsearch client instrumentation so that semantic conventions could be defined first.
Instrumentation for the PHP Elasticsearch client is also currently in development, and I know they'd like to work from semantic conventions as well.

With that said, this would be the plan:
- I'll define `db.elasticsearch.url.path` and `db.elasticsearch.url.query` here
- This semantic conventions definition is experimental
- I'll watch #3355 and update this semantic convention when it's merged

How does that sound?

2023-04-05 13:09 UTC, reyang commented on specification/trace/semantic_conventions/instrumentation/elasticsearch.md
> +| `db.elasticsearch.url`    | string | The exact url of the request, including the target and document id. | `'/test-index/_doc/123'`                                | Required               |
Sounds like a plan to me 👍

2023-04-05 13:10 UTC, reyang approved these changes
LGTM with the understanding of the upcoming changes https://github.com/open-telemetry/opentelemetry-specification/pull/3358#discussion_r1158388283.

2023-04-05 15:44 UTC, trask commented
@estolfo can you post a comparison of this proposal with the existing Java and Python implementations? I think that would help us pull in and get feedback from Java and Python reviewers.

2023-04-06 12:05 UTC, estolfo commented on specification/trace/semantic_conventions/instrumentation/elasticsearch.md
> +| `db.elasticsearch.method` | string | The HTTP method of the request.                                     | `'GET'`                                                 | Required               |
Addressed in https://github.com/open-telemetry/opentelemetry-specification/pull/3358/commits/a0fa771497b11dff3ea9bb8e9c918e46f706a14e

2023-04-06 12:05 UTC, estolfo commented on specification/trace/semantic_conventions/instrumentation/elasticsearch.md
> +| `db.elasticsearch.url`    | string | The exact url of the request, including the target and document id. | `'/test-index/_doc/123'`                                | Required               |
Addressed in https://github.com/open-telemetry/opentelemetry-specification/pull/3358/commits/a0fa771497b11dff3ea9bb8e9c918e46f706a14e

2023-04-06 12:10 UTC, estolfo commented on specification/trace/semantic_conventions/README.md
> +* [Elasticsearch](instrumentation/elasticsearch.md): For Elasticsearch spans.
Fixed in https://github.com/estolfo/opentelemetry-specification/commit/4a1579323b7e6dd34707b2f34f51fb6d2fee2ed8

2023-04-11 11:40 UTC, estolfo commented
## Python
This is what I see from looking at the [source code](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/instrumentation/opentelemetry-instrumentation-elasticsearch/src/opentelemetry/instrumentation/elasticsearch/__init__.py) and the [tests](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/instrumentation/opentelemetry-instrumentation-elasticsearch/tests/test_elasticsearch.py):

Span name: `Elasticsearch/` + (url ||  method || “request”)
For example: `Elasticsearch/test-index/_doc/:id`
- doc id is replaced with `:id`
- If the request is `_search`, the target is replaced with `<target>`

### Special span attributes:
`elasticsearch.id` is the document id
`elasticsearch.method` is the http method
`elasticsearch.url` is the url (the path)
`elasticsearch.target` is the index or data stream
`elasticsearch.params` is query params

result fields:
`elasticsearch.found`
`elasticsearch.timed_out`
`elasticsearch.took`


Other fields
`db_system`
`db_statement`

cc @trask

2023-04-12 07:26 UTC, estolfo commented
## Java

Span name is http method, for example `GET`
http attributes
No special span attributes

### Other fields
`db_system` is `elasticsearch`
`db_operation` is the http method
`db_statement` is http method + path, for example `GET _cluster/health`

2023-04-12 12:09 UTC, estolfo commented
## .NET

I'm adding another one for good luck :)
Here is a summary of the .NET Elasticsearch client instrumentation, which is native to the client, in case it's helpful.

Span name: One of the URL template values listed [here](https://github.com/elastic/elasticsearch-net/blob/main/src/Elastic.Clients.Elasticsearch/_Generated/Api/ApiUrlLookup.g.cs). 

### Other fields
`db.system` is `elasticsearch` 
`db.statement` is request body

http attributes / net attributes

2023-04-16 16:34 UTC, trask reviewed
thx!

2023-04-16 16:34 UTC, trask commented on specification/trace/semantic_conventions/instrumentation/elasticsearch.md
> +When there is no target or document id, the span name will contain the exact url, as in `POST /_search`.
when looking at a given elasticsearch url, what's the best way for instrumentation to detect which part of it should be replaced by `{id}` and which part should be replaced with `{target}`? is there a limited set elasticsearch url patterns?

2023-04-16 16:34 UTC, trask commented on semantic_conventions/trace/database.yaml
> +        tag: call-level-tech-specific
otherwise I think the markdown generation will try to add this to the existing `call-level-tech-specific` table, which I think may be why one of the CI checks is failing
```suggestion
        tag: call-level-tech-specific-elasticsearch
```

2023-04-16 16:34 UTC, trask commented on specification/trace/semantic_conventions/instrumentation/elasticsearch.md
> +### Span Name
(this should fix one of the CI failures)
```suggestion
## Span Name
```

2023-04-16 16:34 UTC, trask commented on specification/trace/semantic_conventions/instrumentation/elasticsearch.md
> +### Span attributes
```suggestion
## Span attributes
```

2023-04-16 16:34 UTC, trask commented on specification/trace/semantic_conventions/instrumentation/elasticsearch.md
> +For example, a request to `/test-index/_doc/123` should have the span name `GET /{target}/_doc/{id}`.
(this should fix another CI issue)
```suggestion
For example, a request to `/test-index/_doc/123` should have the span name `GET /{target}/_doc/{id}`.
```

2023-04-16 16:34 UTC, trask commented on specification/trace/semantic_conventions/instrumentation/elasticsearch.md
> +| `db.elasticsearch.target`  | string | The name of the data stream or index that is targeted.               | `'users'`                                               | Conditionally Required |
is this also extracted from the path?
```suggestion
| `db.elasticsearch.target`  | string | The name of the data stream or index that is targeted, specified in the path.               | `'users'`                                               | Conditionally Required |
```

2023-04-17 10:34 UTC, estolfo commented on specification/trace/semantic_conventions/instrumentation/elasticsearch.md
> +| `db.elasticsearch.target`  | string | The name of the data stream or index that is targeted.               | `'users'`                                               | Conditionally Required |
That depends on the implementation of the client. It's possible that the client is written in way such that the target is specified as an argument or part of a hash passed to the function/method. The Ruby client, for example, has the target specified in the hash passed as an arg to the action method.
Example [source](https://github.com/elastic/elasticsearch-ruby/blob/v8.7.0/elasticsearch-api/lib/elasticsearch/api/actions/indices/split.rb#L37-L57) / [usage](https://github.com/elastic/elasticsearch-ruby/blob/v8.7.0/elasticsearch-api/spec/elasticsearch/api/actions/indices/split_spec.rb#L33)
So your suggested change makes sense; the target is determined not necessarily from the path, though it can appear as part of the path. I had this wording in there because I wanted to emphasize that the `db.elasticsearch.target` span attribute should match exactly what is in the path and what is replaced by `{target}` in the span name.

2023-04-17 10:40 UTC, estolfo commented on specification/trace/semantic_conventions/instrumentation/elasticsearch.md
> +When there is no target or document id, the span name will contain the exact url, as in `POST /_search`.
Yes, there is a [file](https://raw.githubusercontent.com/elastic/elasticsearch-specification/main/output/schema/schema.json) in the Elasticsearch specification repo that can be used.
As an example, the .NET client uses [this generator](https://github.com/elastic/elastic-client-generator-net/blob/5eb2b8154608f955ef02971ac333ba9b24f17204/src/Elastic.ClientGenerator/CodeGenerators/ApiUrlsCodeGenerator.cs#L15) to create this [path lookup file](https://github.com/elastic/elasticsearch-net/blob/main/src/Elastic.Clients.Elasticsearch/_Generated/Api/ApiUrlLookup.g.cs) that is used in the instrumentation.

2023-04-25 08:26 UTC, estolfo commented
@trask What are the next steps for this? Have I answered all your questions?

2023-04-25 14:06 UTC, trask commented
@open-telemetry/opentelemetry-python-contrib-approvers @open-telemetry/dotnet-contrib-approvers @open-telemetry/java-instrumentation-approvers any thoughts on this, since it affects existing instrumentation in these languages? thx

2023-04-28 13:32 UTC, estolfo commented
@trask We will bring it up at the Python, Java, and .NET SIGs next week if we don't hear from the teams before then.

2023-05-05 12:16 UTC, AlexanderWert commented on specification/trace/semantic_conventions/instrumentation/elasticsearch.md
> +The **span name** SHOULD be of the format `<db.elasticsearch.method> <db.elasticsearch.url *with placeholders*>`.
```suggestion
The **span name** SHOULD be of the format `<http.method> <db.elasticsearch.url *with placeholders*>`.
```

2023-05-08 14:36 UTC, estolfo commented
@trask 
The Python group said they have no concerns about using these semantic conventions. They don't consider their consent a blocker and aren't concerned about backwards compatibility. They don't consider the instrumentation stable so are open to changing it.

[Not relevant to the discussion in this PR] For what it's worth, they said they'd rather have the instrumentation done natively in the Elasticsearch python client, rather than in the contrib repo.

2023-05-09 04:38 UTC, reyang commented
@estolfo heads up - most likely this PR will be closed, and we'll ask you to resubmit the PR in a new repo, please refer to https://github.com/open-telemetry/opentelemetry-specification/pull/3474#issuecomment-1539386505.

2023-05-09 10:14 UTC, estolfo commented
@reyang Sure, no problem, thanks for letting me know. I see that the repo isn't created yet so I'll open a PR when it's available.

2023-05-12 16:19 UTC, jsuereth requested changes
Can you move this to https://github.com/open-telemetry/semantic-conventions?

2023-05-26 12:19 UTC, AlexanderWert commented on semantic_conventions/trace/database.yaml
> +        examples: [ '"{\"q\":\"test\"}", "{\"refresh\":true}"' ]
```suggestion
        examples: [ 'q=test&refresh=true' ]
```

2023-06-03 03:16 UTC, closed without merging