Mark logs bridge API / SDK as stable
open-telemetry/opentelemetry-specification pull request #3376
Opened 2023-04-08 15:48 UTC by jack-berg

All items in #2911 have been completed and I believe logs can now be marked stable.

2023-04-11 13:54 UTC, tigrannajaryan approved these changes

2023-04-11 13:58 UTC, djaglowski approved these changes

2023-04-11 15:17 UTC, MSNev approved these changes

2023-04-11 15:47 UTC, reyang commented on specification/logs/bridge-api.md
> +**Status**: [Stable](../document-status.md)
I have a question regarding the name of this file and the title.
Considering we're now saying "Therefore, Log Bridge API artifact, package, and class
names MUST NOT include the terms "bridge", "appender", or any other qualifier
that would prevent evolution into a user facing API." at the end of this spec, why do we still want to keep the name "bridge"? Do we want to just call it API? (and it's okay that we only have one API which is not intended to be user-facing, we can always add more APIs later).

2023-04-11 16:18 UTC, jack-berg commented on specification/logs/bridge-api.md
> +**Status**: [Stable](../document-status.md)
Without "bridge" in the title of the document, the paragraph at the end that says "MUST NOT include the terms "bridge", "appender", or any other qualifier that would prevent evolution into a user facing API" is unnecessary because there is nothing defined as the bridge API. This unwinds the conversations of #3187 and #3197 and requires a new approach for making it sufficiently clear that the API is not meant for end users.

Given the spirited debate over the API naming that's already occurred, I'm not excited about the prospect of revisiting the conversation.

2023-04-11 16:20 UTC, jack-berg commented on specification/logs/bridge-api.md
> +**Status**: [Stable](../document-status.md)
If we do one day change the scope to be user facing, can we not just change the document name from "Logs Bridge API" to "Logs API"?

2023-04-11 17:02 UTC, reyang approved these changes
LGTM with a non-blocking comment https://github.com/open-telemetry/opentelemetry-specification/pull/3376/files#r1163017575.

2023-04-11 17:09 UTC, tigrannajaryan commented on specification/logs/bridge-api.md
> +**Status**: [Stable](../document-status.md)
I think we can change it later. We can have for example this structure in the future:

### Logs API <-- document title
#### App Logs API <-- section with new content
#### Bridge API <-- section that contains all of what the document contains today

2023-04-12 17:02 UTC, zenmoto approved these changes

2023-04-12 18:33 UTC, tigrannajaryan requested changes
Must resolve https://github.com/open-telemetry/opentelemetry-specification/issues/3386 and https://github.com/open-telemetry/opentelemetry-specification/pull/3385 before merging.

2023-04-14 13:49 UTC, tigrannajaryan commented
Must also resolve https://github.com/open-telemetry/opentelemetry-specification/pull/3397 before merging.

Because of multiple last minutes changes we will have to extend the cooldown period on this PR. Let's not rush.

2023-04-14 20:54 UTC, jack-berg commented
This should be unblocked now. Agree with having a cooldown period given the recent changes.

2023-04-17 15:02 UTC, tigrannajaryan commented
@jack-berg I suggest we ask all prototype implementations to review the recent changes and confirm that they are implementable before we merge this.

2023-04-17 18:27 UTC, jack-berg commented
@tigrannajaryan good idea. Tracking feedback from maintainers in this [comment](https://github.com/open-telemetry/opentelemetry-specification/issues/2911#issuecomment-1511873478).

2023-04-20 00:44 UTC, tigrannajaryan commented
We have confirmation from all prototypes: https://github.com/open-telemetry/opentelemetry-specification/issues/2911#issuecomment-1511873478

Let's keep this open for another couple days and then merge.

@open-telemetry/specs-approvers and @open-telemetry/specs-logs-approvers we want to see a lot more approvals on this.

2023-04-20 13:30 UTC, jsirianni approved these changes

2023-04-20 13:34 UTC, carlosalberto approved these changes

2023-04-20 15:08 UTC, trask approved these changes

2023-04-20 15:26 UTC, tigrannajaryan approved these changes

2023-04-20 15:52 UTC, reyang approved these changes

2023-04-20 19:13 UTC, tigrannajaryan commented
We have enough approvals. We will merge this tomorrow, one week after the last changes to logs spec.

2023-04-21 08:26 UTC, codeboten approved these changes
🎉

2023-04-21 13:48 UTC, merged

2023-04-21 13:49 UTC, tigrannajaryan commented
Congrats everyone and thank you for proposing, reviewing, debating, arguing and contributing in some other way!

2023-04-26 16:51 UTC, pellared commented
@jack-berg @tigrannajaryan  Shouldn't there be a changelog line for this? 😉

2023-04-26 16:54 UTC, jack-berg commented
Oops thanks. See #3446.