Add detail for GCP Cloud Run Job version
open-telemetry/opentelemetry-specification pull request #3378
Opened 2023-04-10 17:58 UTC by damemi

## Changes

Add a note for Cloud Run Jobs on how to identify `faas.version`.

Related issues 
Downstream PR proposing this semconv change: https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/pull/465

Related [OTEP(s)](https://github.com/open-telemetry/oteps) #

2023-04-10 18:06 UTC, damemi commented
/cc @punya @jsuereth @aabmass @psx95

2023-04-10 18:12 UTC, punya approved these changes

2023-04-14 11:35 UTC, damemi commented
ping @carlosalberto ptal

2023-04-14 12:33 UTC, Oberon00 commented on semantic_conventions/resource/faas.yaml
> +              [execution](https://cloud.google.com/run/docs/managing/job-executions) and
This sounds like it would be faas.instance, no?

2023-04-14 14:15 UTC, damemi commented on semantic_conventions/resource/faas.yaml
> +              [execution](https://cloud.google.com/run/docs/managing/job-executions) and
On Cloud Run, Service Revisions and Job Executions are conceptually equivalent. Both values change with each new deployment of the application and refer specifically to that deployment. The only difference being that Services run continuously on a Revision (to serve requests) while Jobs run each Execution on-demand (since jobs are on-demand).

In practice, this makes the Job Execution functionally similar to Instance. But, Instance is its own concept which is used in both Services and Jobs (ie, all Cloud Run apps have the unique `instance` label like `00121789b34dc...`). So while Execution behaves similarly to Instance, it is not the Instance.

I don't think invocation_id is what we want either, because this label should apply to more than just traces. It also doesn't seem to match the intent here because we want to identify the deployment version, not the request.

2023-04-14 14:19 UTC, Oberon00 commented on semantic_conventions/resource/faas.yaml
> +              [execution](https://cloud.google.com/run/docs/managing/job-executions) and
> I don't think invocation_id is what we want either, because this label should apply to more than just traces.

While the invocation_is currently defined as a trace semantic convetion, of course it would make sense to also apply it to metrics or logs. Chances are, this will be restructured as part of a more general effort in the future (now that the generic attribute_group convention type was introduced).

But I understand that it is not semantically a good match. I just wanted to confirm you were aware of instance + invocation, I trust you to choose the right concept then.

2023-04-17 16:10 UTC, jsuereth approved these changes

2023-04-17 16:10 UTC, jsuereth commented on semantic_conventions/resource/faas.yaml
> +              [execution](https://cloud.google.com/run/docs/managing/job-executions) and
The thing Mike has defined here is definitely *not* an `invocation_id`.  If `invocation_id` is indeed:

>  An ID for a particular invocation of (request to) a function, each invocation will be dispatched to some particular instance, potentially (auto-)launching a new one (many cloud products will let instances handle multiple invocations one after each other or even in parallel).

Then there is no equivalent here in Cloud Run / Cloud Functions.   In fact, that invocation_id sounds more like a trace_id to me.

2023-04-17 21:03 UTC, damemi commented on semantic_conventions/resource/faas.yaml
> +              [execution](https://cloud.google.com/run/docs/managing/job-executions) and
think we can mark this resolved. but it was good to call out

2023-04-18 10:16 UTC, Oberon00 commented on semantic_conventions/resource/faas.yaml
> +              [execution](https://cloud.google.com/run/docs/managing/job-executions) and
@jsuereth

> In fact, that invocation_id sounds more like a trace_id to me

There should be a 1:n mapping between trace IDs and request IDs. A trace may involve many requests (different functions).

2023-04-18 10:21 UTC, Oberon00 requested changes
I read the linked page https://cloud.google.com/run/docs/managing/job-executions and it seems to confirm what I already suspected from the name "job execution". It does not really fit the version, it sounds like it would better fit the instance or invocation, or maybe cloud run jobs don't fit FaaS conventions at all.

A version should be something more or less permanent , that you can refer to, e.g. when you invoke a function (these conventions are about functions, not jobs), some version gets selected, and a particular version may be launched repeatedly.

E.g. when I read the docs here:

https://cloud.google.com/run/docs/managing/jobs#delete

> Deleting a job cancels all running job executions of that job.

A job execution is something running, that's what an instance or invocation is, a version is something that can be run (multiple times).

See also https://cloud.google.com/run/docs/resource-model#job-executions and https://cloud.google.com/run/docs/resource-model#jobs

So I would say that CloudRun jobs don't really fit FaaS conventions well, but if we want to force them into the FaaS conventions, the job execution would match both an invocation_id and instance. I'm leaning slightly towards invocation_id, but not sure

2023-04-18 12:23 UTC, damemi commented
Versions, instances, and invocations are all functionally similar (you could even argue they are the same) in the isolated context of Jobs, due to the inherent nature of Jobs. In effect, each `version` corresponds to one or more `instances` triggered by an `invocation`. So, you could map `Execution` to any one of version, instance, or invocation based solely on how it behaves. What's critical is what it represents.

In the broader context of Cloud Run, if you consider a job to be just a short-lived, single-request Service, then the concepts of version, instance, and invocation are equivalent:

* **Invocation:** User request made to the application.
* **Instance:** Container instance ID within the application.
* **Version:** Each new deployment of the application.

We can rule out invocation, because that is not what we want to represent with this attribute. This attribute is meant to represent the Job itself, not the request made to it.

Instance maps better to Execution (because each Task runs as its own instance).  But there are 2 problems: 1) the Instance ID does not represent the deployment, it represents a single container and 2) we also provide Instance as its own attribute. Mapping Instance to both `Version` and `Instance` is redundant and leaves no room for us to provide the Execution.

So with Invocation ruled out, and Instance mapped to Instance, that logically leaves (Job)Execution to map to (Service)Revision. We at the very least need *somewhere* to expose the Job Execution. And from a Cloud Run user's perspective, it would be expected in the same place as Service Revision. 

For users on Cloud Run, the same resource detector should be able to fill in the same fields whether for a Cloud Run Service or Cloud Run Job. If only for consistency with the existing Services conventions, we should not fill in fields based on different metadata sources within Cloud Run.

> So I would say that CloudRun jobs don't really fit FaaS conventions well

I understand that I'm being very self-referential by using the Service conventions to map to Jobs. I'm assuming that these existing conventions set a precedent for the inclusion of Cloud Run apps as FaaS concepts. So if the conventions for Services are valid, then this proposal for Jobs is also valid. Because you can, in theory, reduce a Service to a Job, and a Job to a Function.

2023-04-18 12:35 UTC, Oberon00 commented
Actually "invocation" was just recently renamed and used to be named "execution" https://github.com/open-telemetry/opentelemetry-specification/pull/3209. I think there is also not really a difference between "the Job itself" and "the request made to it". After all, the same applies to the invocation_id: It identifies the executing invocation, not the request causing the invocation.

Regarding "instance":

> But there are 2 problems: 1) the Instance ID does not represent the deployment, it represents a single container and 2) we also provide Instance as its own attribute.

What is that own attribute? The term "instance" has many meanings, but a "faas.instance" is an instance of a FaaS execution environment, whatever that encompasses (even multiple "instances" of something else). According to the Google Documentation, a job may invoke multiple containers, so container IDs cannot be used in that attribute anyway (since then a single faas.invocation_id would span multiple faas.instances which is not how these concepts are supposed to be used)

2023-04-18 13:21 UTC, damemi commented
> Actually "invocation" was just recently renamed and used to be named "execution" https://github.com/open-telemetry/opentelemetry-specification/pull/3209. 

I don't know the background for this change, but that PR description says it was changed because `execution` was "too generic and confusing". Maybe I'm misinterpreting, but that implies to me that the name change is intentionally meant to focus it on one thing (the request?)

Is there any discussion on how the term "invocation" was decided, or a definition of it for this context? Josh's https://github.com/open-telemetry/opentelemetry-specification/pull/3378#discussion_r1168970508 defined it as the request, so that's what I'm basing this on.

> I think there is also not really a difference between "the Job itself" and "the request made to it".

The Job is a resource that exists in the GCP Cloud Run API and handles requests. The request is an event initiated by a user to that resource. I think the fact that execution was renamed to invocation to make the term more specific means we should draw the distinction between the two, which I'm comparing to the [definition in this section on the difference between instance and invocation](https://github.com/open-telemetry/opentelemetry-specification/blob/90007a192ae8b06d40ee8c15f56256d69a330321/specification/trace/semantic_conventions/faas.md#difference-between-invocation-and-instance).

> > But there are 2 problems: 1) the Instance ID does not represent the deployment, it represents a single container and 2) we also provide Instance as its own attribute.

> What is that own attribute?

faas.instance

> The term "instance" has many meanings, but a "faas.instance" is an instance of a FaaS execution environment, whatever that encompasses (even multiple "instances" of something else).

A container is the instance of a Cloud Run execution environment. In Cloud Run Services, this container can serve multiple invocations. In Jobs, the container only lives for a single invocation but is technically still the execution environment.

> According to the Google Documentation, a job may invoke multiple containers, so container IDs cannot be used in that attribute anyway (since then a single faas.invocation_id would span multiple faas.instances which is not how these concepts are supposed to be used)

As a span attribute, does invocation_id cross multiple instances? eg, a user calls a function that calls another function, is that the same invocation_id across both of those instances, or is the invocation_id meant to change whenever it hits a new instance?

2023-04-18 14:34 UTC, Oberon00 commented
> that execution was renamed to invocation to make the term more specific means we should draw the distinction between the two

The renaming definitely did not have the intention to restrict the meaning of the attribute such that execution and invocation could now be two separate things. At least that is my interpretation. @tylerbenson do you agree? Or should we re-introduce execution (or execution_id) as an additional attribute? I don't think so...

But I can see that the current definition of invocation_id is unclear with regard to your use case. You could adapt it though.

2023-04-18 14:38 UTC, Oberon00 commented
> As a span attribute, does invocation_id cross multiple instances? eg, a user calls a function that calls another function, is that the same invocation_id across both of those instances, or is the invocation_id meant to change whenever it hits a new instance?

It would usually be different for each function, but that might depend on the cloud provider. The attribute was originally modeled after the AWS Lambda Request ID https://docs.aws.amazon.com/lambda/latest/dg/runtimes-api.html#runtimes-api-next.

2023-04-18 14:39 UTC, Oberon00 commented
>>> But there are 2 problems: 1) the Instance ID does not represent the deployment, it represents a single container and 2) we also provide Instance as its own attribute.
>>What is that own attribute?
> faas.instance

OK, now I get that I still don't get this aspect, sorry to keep bugging you here, but I think it might be important. So, what do you set as value here? The instance ID of the host that executes the container? Is it then possible that the same Job execution spans multiple instances?

2023-04-18 15:15 UTC, damemi commented
> OK, now I get that I still don't get this aspect, sorry to keep bugging you here, but I think it might be important. So, what do you set as value here?

No problem. We use the InstanceID() gce metadata function https://pkg.go.dev/cloud.google.com/go/compute/metadata#InstanceID which returns `the current VM's numeric instance ID`, which in Cloud Run is a `Unique identifier of the container instance` https://cloud.google.com/run/docs/container-contract#metadata-server, iow the container ID.

> Is it then possible that the same Job execution spans multiple instances?

Yes

> The renaming definitely did not have the intention to restrict the meaning of the attribute such that execution and invocation could now be two separate things. At least that is my interpretation. @tylerbenson do you agree? Or should we re-introduce execution (or execution_id) as an additional attribute?

I don't mean that the renaming meant to split execution and invocation. I mean that it meant to more clearly define invocation as a request, rather than the execution. My argument here is that the execution is already represented by the version in Cloud Run.

> It would usually be different for each function, but that might depend on the cloud provider. The attribute was originally modeled after the AWS Lambda Request ID https://docs.aws.amazon.com/lambda/latest/dg/runtimes-api.html#runtimes-api-next.

That doc convinces me more that invocation is meant to map to the request event.

2023-04-18 15:27 UTC, Oberon00 commented
>> Is it then possible that the same Job execution spans multiple instances?
>
> Yes

I think this is not correct then. You should probably use [host.id](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/resource/semantic_conventions/host.md#host) to store that. faas.instance is meant for the exectution environment of the function call, not part of it. That we even have to consider the difference, is a hint that faas conventions might really not be suited for CloudRun jobs.

> That doc convinces me more that invocation is meant to map to the request event.

You may be right.

2023-04-18 15:40 UTC, tylerbenson commented
(Can I suggest adding feedback as inline comments so it is easier to thread the conversation better.  This format makes it difficult to follow the conversation and respond to individual items.  I also suggest this would be a good topic for the FAAS SIG meeting later today.  Perhaps you both could attend or send a representative?)

2023-04-18 15:45 UTC, Oberon00 commented
Unfortunately that meeting is very late in my timezone, I won't be able to attend. But I'm very likely to accept the outcome reached there, if you discuss it and other FaaS SIG members had opinions on the topic. 😃

2023-04-18 15:52 UTC, tylerbenson commented
@Oberon00 understand.  Perhaps you could summarize your concerns into a single paragraph that I can paste into the meeting agenda? (Or you're welcome to add it directly yourself.)

2023-04-18 15:57 UTC, jsuereth commented
@Oberon00 My read of `invocation_id` is that it's a concept *way too* tightly tied to AWS lambda.  It does not fight the runtime model of Cloud Run, and it's not something we would want to promote or encourage OTEL users to assume our instance ID is actually a viable "invocation_id" as defined.


Specifically:

- `faas.instance.id` is described as `The execution environment ID as a string, that will be potentially reused for other invocations to the same function/function version.`

- You claim: `What is that own attribute? The term "instance" has many meanings, but a "faas.instance" is an instance of a FaaS execution environment, whatever that encompasses (even multiple "instances" of something else). According to the Google Documentation, a job may invoke multiple containers, so container IDs cannot be used in that attribute anyway (since then a single faas.invocation_id would span multiple faas.instances which is not how these concepts are supposed to be used)`

 You cannot just change this wording in your definition.  The way I read the description, everything Mike has proposed is inline with the current definition.   In fact given the `potentially reused for other invocation`, I'd argue your definition is strictly invalid here.  We *can* use an id that changes.
 
 Additionally, the term "execution environment" here is highly suspect.  Perhaps in AWS there's some abstraction between your deployment and a running container.  In cloud run that abstraction is NOT identified or called out as something you can look at.  There's just (deletable) does this function name / job name exist, or there's a running container instance.
 
 +1 to @tylerbenson comments.  Right now I'd like an ordered list of your concerns with this PR so that they can be discussed and addressed.

2023-04-19 07:37 UTC, Oberon00 commented
My concern is simple: A job execution ID sounds like a totally different concept from a function version.

Using invocation_id or instance were suggestions. I am also OK if you use another more fitting attribute, like `gcp.cloud_run.job_execution_id`.

2023-04-19 07:47 UTC, Oberon00 commented
@jsuereth

> Additionally, the term "execution environment" here is highly suspect. Perhaps in AWS there's some abstraction between your deployment and a running container.

Google cloud functions uses the same term: https://cloud.google.com/functions/docs/concepts/execution-environment.

Google cloud run as well, although I think in a more abstract way: https://cloud.google.com/run/docs/about-execution-environments

2023-04-19 14:10 UTC, jsuereth commented
@Oberon00 I'm not saying the generally the term "execution environment" is suspect, I meant the way you were defining it.    Specifically this:

> The term "instance" has many meanings, but a "faas.instance" is an instance of a FaaS execution environment, whatever that encompasses (even multiple "instances" of something else). According to the Google Documentation, a job may invoke multiple containers, so container IDs cannot be used in that attribute anyway (since then a single faas.invocation_id would span multiple faas.instances which is not how these concepts are supposed to be used)

In our case, the visible thing you have here is instance-id.  Instance-ID != container id.   I believe Mike may have misspoke when he claimed this was the container-id, so perhaps there was a misconception here.  I thought you were implying we needed some abstraction that was NOT cloud run instance-id.  

The id you get from calling `http://metadata.google.internal/computeMetadata/v1/instance/id` on any container will give you the execution environment instance id.   That's the ID we're proposing to use for instance on Cloud Run Jobs & Cloud Run Services.


To get back to this PR itself:

- We assume 
  - `faas.instance` will be filled out with the value from `http://metadata.google.internal/computeMetadata/v1/instance/id`
  - `faas.name` will be the name of the function or job (without a version number or identifier) 
    - `K_SERVICE` env variable for Cloud Run Services
    - `CLOUD_RUN_JOB` env variable for Cloud Run jobs
- We ignore:
   - `faas.revision_id` I think this field is pretty suspect. If we were to draw any value for it, it would actually be the `trace_id` sent to the CR method.
   - `cloud.resource_id` This would be a longer discussion.
- We would like to change:
  - `faas.revision` 
    - To be the value of `K_REVISION` (for cloud run services)
    - To be the value of `CLOUD_RUN_EXECUTION` (for cloud run jobs) combined with `CLOUD_RUN_TASK_INDEX`


See: https://cloud.google.com/run/docs/container-contract#env-vars for details on what self-discovery options you have.



The reasoning:

Cloud Run doesn't expose "version" for Cloud Run Jobs.  Instead the user-interactable identifier *is* Cloud run Execution (first) and Task index (second).   Many of the proposed alternative ids just aren't things Users *can* interact with on Cloud Run and from an o11y perspective I'd question the utility/value.  One of the reason for these identifiers is so users can go find a broken thing and fix it.  So, any proposed change here, at a minimum, should include *where* we can include an execution identifier so users *can* find cloud run jobs that are problematic.


An alternative:

There is no alternative in the current FAAS conventions for something like Cloud Run Job.  However we *could* just not fill out revision for cloud run jobs, and create  `gcp.cloud_run.execution` and `gcp.cloud_run.task_index` attributes if that makes more sense here.

2023-04-19 14:48 UTC, Oberon00 commented
> The id you get from calling http://metadata.google.internal/computeMetadata/v1/instance/id on any container will give you the execution environment instance id. That's the ID we're proposing to use for instance on Cloud Run Jobs & Cloud Run Services.

Thanks, that was indeed a misunderstanding from me! Because at https://cloud.google.com/run/docs/container-contract#metadata-server it says "Unique identifier of the **container** instance", but if this is actually shared across the containers participating in the same cloud run job, it should be a perfect fit for the faas.instance_id (also because it's always good if the concept names match).

>faas.revision_id I think this field is pretty suspect. If we were to draw any value for it, it would actually be the trace_id sent to the CR method.

I think you mean invocation_id (formely execution). The field was added because it has practical value in AWS and Azure where you have this separate request ID. It would be mostly equivalent not to the trace ID but the span ID of the FaaS span, but these environments provide separate IDs that are also used in platform-native logging and can thus be used to correlate things. It's totally fine not to fill it out if there is no suitable identifier.

> There is no alternative in the current FAAS conventions for something like Cloud Run Job. However we could just not fill out revision for cloud run jobs, and create gcp.cloud_run.execution and gcp.cloud_run.task_index attributes if that makes more sense here.

I would lean towards this. Do you see the job execution ID as semantically equivalent to a service revision / version, or did you just add use this field because no other field fits? If the latter, I would go with a separate field. If the former, since we now have discussed this thoroughly, I'm also OK with using version. It does seem wrong to me, but I'm not the GCP expert...

However, I'm wondering about this comment by @tylerbenson: https://github.com/open-telemetry/opentelemetry-specification/pull/3378#issuecomment-1513738607

>  We decided that the information that was going to version should be instead populated in some combination of faas. invocation_id or faas.instance instead. @damemi is going to provide more details on how this information is exposed to the user, and examples of what the values will look like in various scenarios.

What is now the actual status here?

2023-04-19 20:24 UTC, damemi commented
+1 to everything Josh said in https://github.com/open-telemetry/opentelemetry-specification/pull/3378#issuecomment-1514807427. 

I would add to:

> Cloud Run doesn't expose "version" for Cloud Run Jobs. Instead the user-interactable identifier is Cloud run Execution (first) and Task index (second). Many of the proposed alternative ids just aren't things Users can interact with on Cloud Run and from an o11y perspective I'd question the utility/value. One of the reason for these identifiers is so users can go find a broken thing and fix it. So, any proposed change here, at a minimum, should include where we can include an execution identifier so users can find cloud run jobs that are problematic.

The Instance ID is also an important identifier, mainly for logs but also for cross-signal correlation based on those logs. So we want to expose both Execution ID and Instance.

> There is no alternative in the current FAAS conventions for something like Cloud Run Job. However we could just not fill out revision for cloud run jobs, and create gcp.cloud_run.execution and gcp.cloud_run.task_index attributes if that makes more sense here.

I would be fine with this, but it will mean our [resource detectors](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/a39dfaa68b181d3578f61b2bd74f0d3f1c2e1491/processor/resourcedetectionprocessor/internal/gcp/gcp.go#L72) will have to be updated to handle Jobs and Services differently. Or, we just leave version empty in jobs and `gcp.execution` empty in services.

I'm going to be ooo the rest of the week, but feel free to continue the discussion and I'll catch back up on Monday. I did pull together some screenshots showing these fields in the GCP UI, but I think everyone has a good understanding at this point. Including them anyway to help:

<details>
<summary>Screenshots (collapsed because there are a lot)</summary>

## Services

This shows how Service details map to `faas.*` attributes today. These can't change without breaking.

![Screenshot 2023-04-19 at 7 41 03 AM](https://user-images.githubusercontent.com/1839101/233189024-5c0a718e-f902-43d0-95e7-8496448cbf65.png)
Here, `faas.name` is the name of the Service. This is what users reference when hitting the service.

![Screenshot 2023-04-19 at 7 45 45 AM](https://user-images.githubusercontent.com/1839101/233189148-f5312fb9-a0bb-4acc-be56-608a9c98f018.png)
Clicking on a Service brings up its Revisions. Each Revision is a `faas.version`, where every new Revision is a change to the Service definition.

![Screenshot 2023-04-19 at 8 06 04 AM](https://user-images.githubusercontent.com/1839101/233189489-2ff49473-23c4-4a03-950a-5d74c4ffc24f.png)
Logs from the Service, showing the signal metadata available to users.

## Jobs

These are the proposed new definitions for Jobs.

![Screenshot 2023-04-19 at 7 43 24 AM](https://user-images.githubusercontent.com/1839101/233190163-a964e609-8750-496f-aa82-bf00584f052d.png)
The name of the Job goes in `faas.name`. Similarly to Services, this is how the user will reference the Job.

![Screenshot 2023-04-19 at 7 47 36 AM](https://user-images.githubusercontent.com/1839101/233190263-5b40c51e-7b02-4276-83e7-3e33dd75f17f.png)
Clicking on a Job shows the Executions for that Job. Unlike Services, each Execution is not necessarily a change to the definition of the Job. There is an obscure `generation` label that references essentially the "real version" of the Job, but that label is not pictured in this screenshot and users do not interact with it.

![Screenshot 2023-04-19 at 7 57 30 AM](https://user-images.githubusercontent.com/1839101/233190956-7b266ee2-9aa5-4b70-8683-f92520839e08.png)
Logs from the Job,  showing metadata (`instance` and `execution`)

![Screenshot 2023-04-19 at 7 55 33 AM](https://user-images.githubusercontent.com/1839101/233191360-aa1de1d5-3482-46f4-b033-fae6a5f232b0.png)
Another example of Job logs showing the metadata available about the Resource.
</details>

2023-04-19 20:58 UTC, tylerbenson commented
(For Jobs, my vote is to have `faas.version` report the `generation` value, or not report version at all. The information labeled as `faas.version` should be moved to other attributes.)

2023-04-21 18:58 UTC, jsuereth commented
@cartersocha  gcp instanceID is what's recorded (by default) on logs the container generates and is used to correlate back to the origin.  This is exactly what Resource is about (log<->metric & log<->trace correlation).

2023-04-24 21:33 UTC, tylerbenson commented on semantic_conventions/resource/faas.yaml
> +              eg `execution/0`.
Reminder to move this from the `faas.version` section as was discussed in the prior meeting.

2023-04-25 14:42 UTC, damemi commented
Thanks for all the feedback so far. I do appreciate everyone's patience and help with this.

I pushed a new commit https://github.com/open-telemetry/opentelemetry-specification/pull/3378/commits/5b589465ffa095203ac27aa75140d8a5475cc706 that reverts the originally proposed Job Run version definition. I added a clarification that the existing version definition only applies to Services.

I then added a new cloud provider resource directory and 2 new attributes for Cloud Run based on Josh's suggestion https://github.com/open-telemetry/opentelemetry-specification/pull/3378#issuecomment-1514807427:
1. `gcp.cloud_run.job.execution`
2. `gcp.cloud_run.job.task_index`

We will need to update our resource detectors to [differentiate between Jobs and Services for Cloud Run](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/f7bb65f4e757ed35e039e44074a175e6285126b9/processor/resourcedetectionprocessor/internal/gcp/gcp.go#L72). These detectors are stable so we can't change how Services are handled, but I think we can add Jobs as a subset without breaking the existing Service workflow.

Thanks again for all the thoughtful input on this, hopefully we can reach a resolution soon.

2023-04-25 14:42 UTC, damemi commented on semantic_conventions/resource/faas.yaml
> +              eg `execution/0`.
Done

2023-04-25 14:53 UTC, Oberon00 commented
@tylerbenson @Aneurysm9 @jsuereth What do you think about reverting the renaming / redefinition of faas.execution to faas.invocation_id done in #3209, or adjusting the changes in such a way that they could also be used to store the Cloud Watch Job execution ID, so that we don't need a new attribute?

2023-04-25 19:45 UTC, damemi commented
@Oberon00 faas.invocation/execution is a span attribute, but what we want is a resource attribute so would that also involve generalizing it to the resource level?

2023-04-25 21:28 UTC, Oberon00 commented
We actually already have many FaaS attributes that can be set at either the Span or resource level (like faas.id). They are all "usualyl resource", so this would be the first "usually span" attribute explicitly being allowed in both positions, but I don't see a problem with it.
Note that you will still want at least one FaaS attribute on your FaaS root span that is always on the span, otherwise you can't determine which of your spans represents the FaaS invocation, if everything is on the resource.

2023-05-01 15:27 UTC, tylerbenson approved these changes

2023-05-02 08:32 UTC, Oberon00 approved these changes

2023-05-02 08:32 UTC, Oberon00 commented on specification/resource/semantic_conventions/cloud_provider/gcp/cloud_run.md
> +# Google Cloud Run
You should add a short text to recommend (require? additionally following FaaS and (certain) cloud conventions)

2023-05-02 08:32 UTC, Oberon00 commented on semantic_conventions/resource/cloud_provider/gcp/cloud_run.yaml
> +          [execution](https://cloud.google.com/run/docs/managing/job-executions)
Execution ID? Execution name?

2023-05-02 08:32 UTC, Oberon00 commented on semantic_conventions/resource/cloud_provider/gcp/cloud_run.yaml
> +          of the job.
Could you also recommend an environment variable or metadata URL to read this from here? IMHO having that is always nice since it also acts as an additional clarification of the definition

2023-05-02 18:58 UTC, damemi commented on semantic_conventions/resource/cloud_provider/gcp/cloud_run.yaml
> +          [execution](https://cloud.google.com/run/docs/managing/job-executions)
updated this description to match the environment variable (and added the link to the variable) https://cloud.google.com/run/docs/container-contract#jobs-env-vars

2023-05-02 18:58 UTC, damemi commented on semantic_conventions/resource/cloud_provider/gcp/cloud_run.yaml
> +          of the job.
done

2023-05-02 18:58 UTC, damemi commented on specification/resource/semantic_conventions/cloud_provider/gcp/cloud_run.md
> +# Google Cloud Run
Sorry, I'm not totally sure what you mean by this... added a brief description here that I think is what you meant?

2023-05-05 11:31 UTC, damemi commented
The [link check failure](https://github.com/open-telemetry/opentelemetry-specification/actions/runs/4864773426/jobs/8674231813?pr=3378#step:4:338) looks unrelated to this change, is this good to merge?

2023-05-09 04:18 UTC, reyang commented
FYI @damemi @jsuereth @reyang this is missing a changelog entry, we need to make sure the changelog entry is added in the new https://github.com/open-telemetry/semantic-conventions (to be created this week) repo.

Related to https://github.com/open-telemetry/opentelemetry-specification/pull/3474#pullrequestreview-1415130195.

2023-05-09 04:18 UTC, merged

2023-05-12 19:34 UTC, damemi commented
@reyang should the new repo have its own CHANGELOG.md just for semantic conventions?

2023-05-12 19:40 UTC, reyang commented
> @reyang should the new repo have its own CHANGELOG.md just for semantic conventions?

I think the new repo should have a single CHANGELOG.md file, if there isn't one, it should be created.

2023-05-12 19:50 UTC, damemi commented
> > @reyang should the new repo have its own CHANGELOG.md just for semantic conventions?
> 
> I think the new repo should have a single CHANGELOG.md file, if there isn't one, it should be created.

sounds good, opened that PR here https://github.com/open-telemetry/semantic-conventions/pull/18