Add namespace for process metric attributes
open-telemetry/opentelemetry-specification pull request #3431
Opened 2023-04-21 22:54 UTC by trask

Part of #3131

Note: I'm not sure what the best approach is here, so took a stab at it to see what this would look like.

## Changes

Adds namespace for process metric attributes:
* `process.cpu.time` and `process.cpu.utilization` metrics
  * `state` renamed to `cpu.state`
* `process.disk.io` metric
  * `direction` renamed to `disk.direction`
* `process.network.io` metric
  * `direction` renamed to `network.direction`
* `process.context_switches` (should we consider renaming to `process.cpu.context_switches`?)
  * `type` renamed to `cpu.context_switch.type`
* `process.paging.faults` (should we consider renaming to `process.memory.paging_faults`?)
  * `type` renamed to `memory.page_fault.type`

(I don't think [schema transformations](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/schemas/file_format_v1.1.0.md#rename_attributes-transformation-2) support this, since e.g. we don't want to rename the metric attribute `state` across all metrics, only the one for the `process.cpu.time` metric)

2023-04-21 23:10 UTC, reyang commented on CHANGELOG.md
> +  rename `process.context_switches` metric attribute `type` to `cpu.context_switch.type`,
Looks like I'm going to open a can of worms - CSwitch is an operating system concept rather than CPU concept IMHO.

https://en.wikipedia.org/wiki/Context_switch

2023-04-21 23:12 UTC, reyang commented on CHANGELOG.md
> +  rename `process.disk.io` metric attribute `direction` to `disk.direction`,
Not targeting this PR, I'll restate that disk direction is very weird, most operating systems model disks with read/write/control.

2023-04-21 23:33 UTC, trask commented on CHANGELOG.md
> +  rename `process.context_switches` metric attribute `type` to `cpu.context_switch.type`,
I tried to read that 😂
![image](https://user-images.githubusercontent.com/218610/233748885-d801f0f2-51ed-409c-a35e-90051ec39197.png)

2023-04-21 23:38 UTC, trask commented on CHANGELOG.md
> +  rename `process.context_switches` metric attribute `type` to `cpu.context_switch.type`,
changed it, now `type` -> `context_switch.type`

2023-04-21 23:43 UTC, reyang approved these changes
I'm supportive of this direction and I think the spirit is also well aligned with https://github.com/open-telemetry/oteps/blob/6b62348b280b82036e897781d49ac4f2c3a9d95e/text/0199-support-elastic-common-schema-in-opentelemetry.md.

Not a blocker for now - I think many of these attributes will be useful for other areas (e.g. for a different metrics stream, for logs and traces) so eventually they should be extracted to a common place.

2023-04-21 23:45 UTC, reyang commented
@AlexanderWert I want to get your input regarding metrics attributes (dimensions).

2023-04-21 23:56 UTC, Yun-Ting approved these changes

2023-04-24 16:56 UTC, tigrannajaryan commented
This breaks [hostmetrics receiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/hostmetricsreceiver) in the Collector, which is declared Beta and is likely one of the most used receivers in the Collector. FYI, @open-telemetry/collector-contrib-approvers @open-telemetry/collector-approvers 

What is the justification for this change?


> (I don't think [schema transformations](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/schemas/file_format_v1.1.0.md#rename_attributes-transformation-2) support this, since e.g. we don't want to rename the metric attribute `state` across all metrics, only the one for the `process.cpu.time` metric)

It does. You can use `apply_to_metrics` setting to limit attribute renaming to specific metrics.

2023-04-24 18:03 UTC, trask commented
> What is the justification for this change?

being able to share the same attributes across traces, metrics and logs

see @jsuereth's https://github.com/open-telemetry/opentelemetry-specification/pull/3342#pullrequestreview-1392853509:

> We want to share attributes between metrics + other signals. This is to aide in telemetry correlation, one of OTEL's core missions. Why the disparity?

2023-04-24 22:01 UTC, tigrannajaryan commented
> > What is the justification for this change?
> 
> being able to share the same attributes across traces, metrics and logs
> 
> see @jsuereth's [#3342 (review)](https://github.com/open-telemetry/opentelemetry-specification/pull/3342#pullrequestreview-1392853509):
> 
> > We want to share attributes between metrics + other signals. This is to aide in telemetry correlation, one of OTEL's core missions. Why the disparity?

Good point. I think we need to put some more thought into this this.

The purpose of namespacing is to avoid name conflicts.

Attributes that we define for only a particular metric are already in their own namespace, the name of the metric (e.g. `state` attribute of `process.cpu.time` metric). These attributes don't need any other help to ensure there are no conflicts. These attributes are also only used for metrics and never for other signals.

Generic attributes (e.g. `http.status_code`) that can be recorded on a span, on a log or on a metric need such namespacing.

I think we need to make it a rule that metric-only attributes defined for specific metrics don't need to be in a namespace. So, I would make this change only for attributes which we plan to also record for traces and logs or which are defined as general-purpose attributes which can be recorded on any metrics (and thus have higher probability of clashes with other such attributes). At a glance `cpu.state` does not make sense to me as a span or log attribute, but perhaps there is a use case for that?

@jsuereth thoughts?

2023-04-24 22:17 UTC, jack-berg commented
> I think we need to make it a rule that metric-only attributes defined for specific metrics don't need to be in a namespace. I would make this change only for attributes which we plan to also record for traces and logs or which are defined as general-purpose attributes which can be recorded on any metrics (and thus have higher probability of clashes with other such attributes)

This seems like an appealing way to think about it. I wonder how this would work with [code generation](https://github.com/open-telemetry/build-tools/blob/main/semantic-conventions/README.md#code-generator). Right now code generation produces [one big class](https://github.com/open-telemetry/opentelemetry-java/blob/main/semconv/src/main/java/io/opentelemetry/semconv/trace/attributes/SemanticAttributes.java) containing all the attributes for traces, metrics, and logs. If an attribute like cpu `state` were to be scoped to specific metrics `process.cpu.time` and `process.cpu.utilization`, we'd either need multiple copies of `state`, or some sort of documentation describing the different contexts in which it is used.

Something like:
```
public static final AttributeKey<String> PROCESS_CPU_TIME_STATE = stringKey("state");

public static final AttributeKey<String> PROCESS_CPU_UTILIZATION_STATE = stringKey("state");
```

Or:
```
/**
 * Used in multiple contexts:
 * <ul>
 *   <li>process.cpu.time: <description of meaning when used with process.cpu.time>
 *   <li>process.cpu.utilization:  <description of meaning when used with process.cpu.utilization>
 */
public static final AttributeKey<String> STATE = stringKey("state");
```

2023-04-25 00:33 UTC, trask commented
I agree that lots of metric attributes don't have a use on spans, but it seems like they could potentially be useful on logs, e.g.

* metrics could be derived from logs
* [raw measurements](https://github.com/open-telemetry/opentelemetry-specification/issues/617) could be emitted via logs

2023-04-25 01:03 UTC, trask commented
> > (I don't think [schema transformations](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/schemas/file_format_v1.1.0.md#rename_attributes-transformation-2) support this, since e.g. we don't want to rename the metric attribute `state` across all metrics, only the one for the `process.cpu.time` metric)
> 
> It does. You can use `apply_to_metrics` setting to limit attribute renaming to specific metrics.

nice, I added this, thx

2023-04-25 17:50 UTC, jsuereth approved these changes

2023-04-25 17:50 UTC, jsuereth commented on CHANGELOG.md
> +  rename `process.disk.io` metric attribute `direction` to `disk.direction`,
I understand wanting the consistency.  I, personally, view disk as "yet another type of network operation", thanks to years of SAN and DFS.

I think we SHOULD get together a semconv group to really look at these at some point, but unfortunately we have a ton of users right now.

Simple renames and namespacing, I think we can afford to do, especially given what this could provide us w/ Log -> Metric or Trace -> Metric generation.

Anything more semantically different, we need to be cautious about.

2023-05-01 22:33 UTC, bertysentry commented
TBH I don't like these changes.

As @tigrannajaryan mentioned, there is no possible conflict between attributes using the same name but for different metrics. Specifying `cpu.state` instead of just `state` for a `process.cpu.usage` metric doesn't add any information. Same goes for `disk.direction` vs `direction` for `process.disk.io`: we already know it's about the disk.

Also, metrics don't have the same hierarchical nature as logs and traces with inherited attributes and context. This justifies having different rules for metrics attributes.

Now, I hear the argument about correlation between spans, logs, and metrics. The goal is noble but adding too much constraints on attributes naming between traces and metrics is going to create a lot of discussion and tension between spec writers. There are cases where a span attribute will require a very long namespace, and a small rare use case where we may want to correlate that attribute with a metric, and then the metric should use the long namespace for the attribute name, causing migration issues, etc. 

While consistency is absolutely necessary, correlation between metrics and traces cannot be ensured by semantic conventions. Correlation engines will always require some mapping mechanisms, and in the age of AIOps, enforcing identical attribute names everywhere doesn't sound necessary.

Sorry for the long rant, I just mean: can't we keep it as simple as possible, while ensuring consistency in terms, and rely on implementation for correlation and other niceties?

2023-05-02 15:46 UTC, PeterF778 commented on specification/metrics/semantic_conventions/process-metrics.md
> +| `process.cpu.time`              | Counter                                            | s         | Total CPU seconds broken down by different states.
Typo: the last appearance of `state` should be also changed to `cpu.state`.

2023-05-02 15:47 UTC, PeterF778 commented on specification/metrics/semantic_conventions/process-metrics.md
> +| `process.cpu.utilization`       | Gauge                                              | 1         | Difference in process.cpu.time since the last measurement, divided by the elapsed time and number
Same here: last `state` --> `cpu.state`.

2023-05-09 04:37 UTC, reyang commented
@trask heads up - most likely this PR will be closed, and we'll ask you to resubmit the PR in a new repo, please refer to https://github.com/open-telemetry/opentelemetry-specification/pull/3474#issuecomment-1539386505.

2023-05-11 17:46 UTC, jack-berg approved these changes
Approving to indicate my support, even though I understand this PR will need to be re-opened against the new repo.

My reasons:
* Its very convenient to have a global set of attribute keys which mean the same thing in all contexts. This isn't strictly necessary, since we can say metric attributes are scoped to the metric name, but its a nicety I'm reluctant to give up.
* It will be hard to anticipate when an attribute will only be used in a metric (and not need a namespace) vs be used across signals (and need a namespace). Telemetry schemas would allow for renames if an attribute is initially limited to metrics and later is exposed in logs or traces, but IMO its better to not have to use telemetry schemas even if they _could be used_.
* Common rules for attributes in all signals is simpler than having an exception just for metrics. I don't share [the view](https://github.com/open-telemetry/opentelemetry-specification/pull/3431#issuecomment-1530457409) that using non-namespaced attributes for metrics is simpler. Consistency is simplicity.

2023-05-12 15:25 UTC, PeterF778 commented
Since there are good arguments for namespacing metric attributes as well as against, how about adding this requirement:

_For each metric, its attribute names must be unique even after stripping the namespacing prefix._

This will allow some flexibility with handling metric attributes by backends, and specifically UIs.

2023-05-12 16:17 UTC, jsuereth requested changes
Please move to https://github.com/open-telemetry/semantic-conventions

2023-05-24 03:07 UTC, trask commented
hey all, the https://github.com/orgs/open-telemetry/teams/technical-committee is reviewing this issue, and asked to create a summary of pros/cons. I have created https://github.com/open-telemetry/semantic-conventions/issues/51 based on the comments here, please comment further over there if I missed anything, thx!

2023-05-24 03:07 UTC, closed without merging