Messaging: remove source and other minor alignments with ECS
open-telemetry/opentelemetry-specification pull request #3450
Opened 2023-04-27 03:14 UTC by lmolkova

Fixes #3196

## Changes

- Removes `messaging.source` namespace. `Destination` and `source` namespaces are defined in ECS and unrelated to messaging. Removed to allow attribute reuse across signals (e.g. logs), to decrease confusion with ECS source, and resolve some usability issues with source/destination 
- Not removing `messaging.destination` because it's widely used in messaging 
- Introduces `destination_original`: in some cases when a message is routed,  consumer also knows the original destination and the destination it received a message from. With `messaging.source` removed, we need another namespace for the original destination.
- Renamed `messaging.message.payload_size_bytes` to `messaging.message.payload.size` (following HTTP lead #3439, https://github.com/open-telemetry/opentelemetry-specification/pull/3355#issuecomment-1523946746)
- Removed `messaging.message.payload_compressed_size_bytes` (following HTTP lead too #2028) and since it'd be uncommon for instrumentation to know if payload is compressed or not and have access to the uncompressed payload. This also resolves messaging portion of #1053

2023-05-03 23:07 UTC, pyohannes commented on semantic_conventions/trace/messaging.yaml
> +      These attributes should be used on the consumer side when original destination is available and different than destination message are consumed from.'
Maybe you could add some clarification the "original destination" refers to the destination the message was originally _published_ to?

2023-05-03 23:07 UTC, pyohannes commented on schemas/1.21.0
> +              messaging.source.anonymous: messaging.destination.anonymous
This is just a nit, but I wonder what the desired outcome would be in case both `messaging.source.*` and `messaging.destination.*` attributes were specified on consumer side.

2023-05-04 15:40 UTC, pyohannes approved these changes

2023-05-05 15:57 UTC, joaopgrassi commented on schemas/1.21.0
> +              messaging.source.anonymous: messaging.destination.anonymous
We will remove these from here right? From what I remember from our last SIG meeting.

2023-05-05 15:57 UTC, joaopgrassi commented on semantic_conventions/trace/messaging.yaml
> +      Destination attributes SHOULD be set on publish, receive, or other span describing messaging messaging operation
```suggestion
      Destination attributes SHOULD be set on publish, receive, or other spans describing messaging operations.
```

2023-05-05 15:57 UTC, joaopgrassi commented on semantic_conventions/trace/messaging.yaml
> +      if it operates with single message or if the attribute value applies to all messages in the batch.
```suggestion
      Destination attributes should be set when the messaging operation handles single messages. When the operation handles a batch of messages, the destination attributes should only be applied when the attribute value applies to all messages in the batch.
```

I feel this sentence was "merged" together with the above, so it was a bit confusing. I tried separating then so they can be read completely separately. 

I'm not sure about the `should` here, so I left it non-normative.

2023-05-05 15:57 UTC, joaopgrassi commented on specification/trace/semantic_conventions/messaging.md
> +A destination represents an entity within messaging system messages are published to and consumed from. A destination
I can't put my finger on it, but I find hard to understand the sentence. Here's some attempts I tried.. (not sure it's better)

```suggestion
A destination represents an entity within a messaging system. Messages are published to and consumed from a destination.
```

OR

```suggestion
A destination represents an entity within a messaging system. A destination can act as a producer or a consumer.
```

2023-05-05 15:57 UTC, joaopgrassi commented on specification/trace/semantic_conventions/messaging.md
> +> Note: Messages could be routed by brokers, destination a message is consumed from doesn't always match the destination it was published to. If original destination information is available on the c
```suggestion
> Note: Because messages could be routed by brokers, the destination a message is consumed from does not always match the destination it was published to. If information about the original destination is available on the consumer side, consumer instrumentations SHOULD populate the attributes about the original destination under the `messaging.destination_original` namespace.
```

2023-05-09 04:37 UTC, reyang commented
@lmolkova heads up - most likely this PR will be closed, and we'll ask you to resubmit the PR in a new repo, please refer to https://github.com/open-telemetry/opentelemetry-specification/pull/3474#issuecomment-1539386505.

2023-05-12 16:16 UTC, jsuereth requested changes
Please move to https://github.com/open-telemetry/semantic-conventions

2023-05-15 17:24 UTC, lmolkova commented
closing and will reopen in https://github.com/open-telemetry/semantic-conventions repo

2023-05-15 17:24 UTC, closed without merging