Mark HTTP semantic conventions as frozen
open-telemetry/opentelemetry-specification pull request #3451
Opened 2023-04-27 04:03 UTC by trask

This PR currently depends on the following four PRs to be merged first:
- [ ] #3355 
- [ ] #3402
- [ ] #3426
- [ ] #3443 

Fixes #3279

## Changes

Marks the HTTP semantic conventions as frozen

2023-04-27 10:51 UTC, Oberon00 commented on specification/metrics/semantic_conventions/http-metrics.md
> +**Status**: [Feature-freeze](../../document-status.md)
Feature-freeze does not replace the stability level, but is another dimension. Since we plan to do major changes at the moment, I think we should leave the overall status at experimental.

2023-04-27 10:51 UTC, Oberon00 commented on specification/metrics/semantic_conventions/http-metrics.md
> +**Status**: [Mixed](../../document-status.md)
```suggestion
**Status**: [Experimental, partial feature-freeze](../../document-status.md)
```

2023-04-27 18:00 UTC, lmolkova commented on specification/metrics/semantic_conventions/http-metrics.md
> +**Status**: [Feature-freeze](../../document-status.md)
After all the PRs in the description are merged, no major changes are planned and we'll need a way to express the status where no new features are accepted, but we're not yet ready to mark things stable (until a reasonable amount of instrumentations are onboarded, provided feedback, and it has been addressed).

It's easy to update doc status from frozen to stable if all the preconditions are met.

2023-04-27 20:47 UTC, Oberon00 commented on specification/metrics/semantic_conventions/http-metrics.md
> +**Status**: [Feature-freeze](../../document-status.md)
So, then:

```suggestion
**Status**: [Experimental, Feature-freeze](../../document-status.md)
```

2023-05-09 04:37 UTC, reyang commented
@trask heads up - most likely this PR will be closed, and we'll ask you to resubmit the PR in a new repo, please refer to https://github.com/open-telemetry/opentelemetry-specification/pull/3474#issuecomment-1539386505.

2023-05-12 16:16 UTC, jsuereth requested changes
Please reopen against https://github.com/open-telemetry/semantic-conventions

2023-05-27 03:16 UTC, closed without merging