Add spec resource container attributes
open-telemetry/opentelemetry-specification pull request #3468
Opened 2023-05-03 15:22 UTC by marcsanmi

## Changes

Update the container semantic conventions to add a couple of non-default resource attributes introduced in https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/21185.

2023-05-09 04:36 UTC, reyang commented
@marcsanmi heads up - most likely this PR will be closed, and we'll ask you to resubmit the PR in a new repo, please refer to https://github.com/open-telemetry/opentelemetry-specification/pull/3474#issuecomment-1539386505.

2023-05-09 09:42 UTC, arminru commented on specification/resource/semantic_conventions/container.md
> +| `container.command_line` | string | The full command executed by the container. | `nginx -g daemon off;` | Recommended |
Could this contain any credentials that would need to be redacted?

2023-05-09 09:42 UTC, arminru commented on specification/resource/semantic_conventions/container.md
You'll need to add these changes in the YAML definition from which these MD files are then generated.
See https://github.com/open-telemetry/opentelemetry-specification/tree/main/semantic_conventions for the YAMLs and the README there for instructions.

2023-05-11 14:43 UTC, marcsanmi commented on specification/resource/semantic_conventions/container.md
> +| `container.command_line` | string | The full command executed by the container. | `nginx -g daemon off;` | Recommended |
Good point. Yes, this would contain any command (+args) the container runs. By `need to be redacted` do you mean writing some advice here in the `Description` column itself?

Let me know your thoughts.

**Note**: considering the first comment, I'll do the changes in the new repository.

2023-05-12 08:31 UTC, Oberon00 commented on specification/resource/semantic_conventions/container.md
> +| `container.command_line` | string | The full command executed by the container. | `nginx -g daemon off;` | Recommended |
Anything added regarding that here should probably added also to the process.* semantic conventions. And I wonder if these could somehow be shared. At least they should be aligned, so consider also adding a container.command_args string array. https://github.com/open-telemetry/opentelemetry-specification/blob/b0a22680de561c2a7d45cf78aa65c65583f42ed2/specification/resource/semantic_conventions/process.md#process

2023-05-12 15:26 UTC, joaopgrassi commented
@marcsanmi the move of semconv to a new repo happened. Could you please rebase and submit the PR there? https://github.com/open-telemetry/semantic-conventions

2023-05-12 16:13 UTC, jsuereth requested changes
Please reopen this against: https://github.com/open-telemetry/semantic-conventions

2023-05-27 03:16 UTC, closed without merging