Rename trace context field names used in legacy logging formats to match ECS
open-telemetry/opentelemetry-specification pull request #3469
Opened 2023-05-03 15:24 UTC by trask

Fixes #3303

## Changes

Renames trace context field names used in legacy logging formats to match ECS:
* `trace_id` -> `trace.id`
* `span_id` -> `span.id`
* `trace_flags` -> `trace.flags`

2023-05-03 16:03 UTC, tigrannajaryan requested changes
Blocking since implications of the change are unclear. Please do some impact analysis and add the results the PR description.

2023-05-03 16:35 UTC, jsuereth commented
Agree with the block on this PR.

My "litmus test" on this change is as follows:

1. Is this an *opentelemetry* semantic convention?  No, this is about encoding things into legacy apps.  What's an equivalent compatibility?  Jaeger, Zipkin or Prometheus are examples.
2. Would I make the same change regarding Prometheus exemplar attributes (span_id/trace_id)?  

No.  That would break compatibility.


So outside of the fact that this is *not* a semantic convention, I'm fundamentally opposed to this change.

2023-05-03 19:55 UTC, tigrannajaryan commented on specification/compatibility/logging_trace_context.md
> +  "span.id":"abcdef1010"
This is a great point.

2023-05-09 04:36 UTC, reyang commented
@trask heads up - most likely this PR will be closed, and we'll ask you to resubmit the PR in a new repo, please refer to https://github.com/open-telemetry/opentelemetry-specification/pull/3474#issuecomment-1539386505.

2023-05-09 16:20 UTC, tigrannajaryan commented
> > @trask heads up - most likely this PR will be closed, and we'll ask you to resubmit the PR in a new repo, please refer to [#3474 (comment)](https://github.com/open-telemetry/opentelemetry-specification/pull/3474#issuecomment-1539386505).
> 
> Please remind me to block the PR when it is resubmitted. :-) I still think this change is not needed (a strong argument is in [#3469 (comment)](https://github.com/open-telemetry/opentelemetry-specification/pull/3469#discussion_r1184176602))

Actually I take that back. Looks like we are not actually using underscores in JSON (fix here https://github.com/open-telemetry/opentelemetry-proto/pull/468) so this argument is not applicable.

2023-05-09 16:21 UTC, tigrannajaryan commented on specification/compatibility/logging_trace_context.md
> +  "span.id":"abcdef1010"
Turns out the spec is inaccurate. We have an explicit rule that says JSON fields use lowerCamelCase. PR to fix the spec: https://github.com/open-telemetry/opentelemetry-proto/pull/468

2023-05-24 03:16 UTC, closed without merging

2023-05-24 14:52 UTC, tigrannajaryan commented
I am re-opening this for a somewhat different reason:

The trace_id/span_id fields use a different capitalization in OTLP/JSON, we use traceId/SpanId. Do we think that these need to use the same capitalization?

@open-telemetry/specs-logs-approvers thoughts?

2023-05-24 14:52 UTC, tigrannajaryan commented
Actually I am going close this again. I didn't realize it is a PR, I thought it is an issue we can use for discussion. I will open a new issue.