Clarification: metric namespaces are not allowed to be metric names
open-telemetry/opentelemetry-specification pull request #3476
Opened 2023-05-05 18:51 UTC by trask

Related to https://github.com/open-telemetry/opentelemetry-specification/issues/3457#issuecomment-1535001327

## Changes

Clarifies that metric namespaces are not allowed to be metric names.

2023-05-05 19:07 UTC, dyladan commented
Seems like a single issue with an emoji voting system would be an easier way to compare 2 proposals. In any case I thumbed up the other one

2023-05-05 19:12 UTC, trask commented
> I thumbed up the other one

can you approve it instead (or in addition)?

2023-05-08 16:23 UTC, tigrannajaryan approved these changes
I don't see any reasoning one way or another, so I support this approach purely for consistency reasons.

2023-05-08 16:25 UTC, trask commented
> I don't see any reasoning one way or another, so I support this approach purely for consistency reasons.

yeah, I'm not aware of (and couldn't find) what the reasoning is for attribute namespaces either, does anyone know?

2023-05-08 16:46 UTC, reyang approved these changes

2023-05-09 04:35 UTC, reyang commented
@trask heads up - most likely this PR will be closed, and we'll ask you to resubmit the PR in a new repo, please refer to https://github.com/open-telemetry/opentelemetry-specification/pull/3474#issuecomment-1539386505.

2023-05-09 12:08 UTC, pichlermarc commented
I think this will require us to keep the recommending the `.count` suffix or something of the like. As outlined in #3457, I don't think that `.total` is an adequate suffix for delta metrics which would be the replacement. Therefore I support the other proposal #3477

2023-05-09 15:29 UTC, djaglowski approved these changes
This restriction has generally been followed in the collector when defining metrics collected by "scraper" receivers.

I think there is at least some utility in this restriction. For example, one could autogenerate navigable documentation based on metric namespaces, where each page would contain _either_ a list of "sub" namespaces, _or_ metadata for a specific metric. Allowing collisions between namespaces and metrics would be manageable by having a page that shows _both_ a metric _and_ a list of "sub" namespaces. However, I think as a user traversing such documentation, I might find it a bit counterintuitive.

2023-05-09 17:10 UTC, trask commented
> I think there is at least some utility in this restriction. For example, one could autogenerate navigable documentation based on metric namespaces

this could apply to some metric UIs also

2023-05-12 10:03 UTC, jackshirazi approved these changes

2023-05-12 16:09 UTC, jsuereth requested changes
Please move this to https://github.com/open-telemetry/semantic-conventions

2023-05-19 17:35 UTC, tigrannajaryan commented
I found the initial PR that added the limitation: https://github.com/open-telemetry/opentelemetry-specification/pull/832

See here for why: https://github.com/open-telemetry/opentelemetry-specification/pull/832#discussion_r473223348

2023-05-23 15:46 UTC, djaglowski commented
Is it controversial that we should be able to convert bidirectionally between our dot-notation and common structured data formats such as json or yaml? If not, this would seem to be a clear reason to keep metric names and namespaces separate. e.g.

```yaml
metrics:
  hello.foo: 1
  hello.bar: 2

# equivalent to
metrics:
  hello:
    foo: 1
    bar: 2
```

If metrics names and namespaces are allowed to collide, this is problematic:
```yaml
metrics:
  hello: 1
  hello.bar: 2

# equivalent?
metrics:
  hello: # is this the value '1' or an object containing "bar: 2"?
```

2023-05-24 02:52 UTC, trask commented
hey all, the @open-telemetry/technical-committee is reviewing this issue, and asked to create a summary of pros/cons. I have created https://github.com/open-telemetry/semantic-conventions/issues/50 based on the comments here, please comment further over there if I missed anything, thx!

2023-05-24 02:52 UTC, closed without merging