Clarification: metric namespaces are allowed to be metric names
open-telemetry/opentelemetry-specification pull request #3477
Opened 2023-05-05 18:51 UTC by trask

Related to https://github.com/open-telemetry/opentelemetry-specification/issues/3457#issuecomment-1535001327

## Changes

Clarifies that metric namespaces are allowed to be metric names.

2023-05-05 19:42 UTC, dyladan approved these changes

2023-05-09 04:35 UTC, reyang commented
@trask heads up - most likely this PR will be closed, and we'll ask you to resubmit the PR in a new repo, please refer to https://github.com/open-telemetry/opentelemetry-specification/pull/3474#issuecomment-1539386505.

2023-05-09 10:21 UTC, pirgeo commented
One big upside to this proposal as compared to #3476 is that allowing it for metrics enables us to drop `.count` suffixes in metric names without "polluting" the attribute key space (since it is okay to have the same namespace). This would help with Prometheus compatibility (#3457) as well as conciseness. Additionally, similar to @jack-berg's comment here (although that thread is unrelated): https://github.com/open-telemetry/opentelemetry-specification/pull/3484#discussion_r1187957938, there might be a question about whether certain semantic conventions should be an UpDownCounter or a Gauge. The `.count` suffix makes it seem like it is always a counter, when it does not have to be (or the use-case would also make sense as a Gauge). Being able to drop the suffix would generally improve the flexibility of the OTel semantic conventions, in my opinion.

2023-05-09 10:22 UTC, pirgeo approved these changes

2023-05-09 11:01 UTC, joaopgrassi approved these changes
I'm also in favor of this for the many reasons others pointed in the discussions. I believe preventing "namespaces" to be metrics names themselves would be very limiting.

We anyway have to to apply judgment and good sense, because making this explicit now, doesn't mean adding a metric such as `process.runtime.jvm` is allowed, even though it "complies" with the wording added here. But that's what the review process is for anyway :)

2023-05-10 14:14 UTC, jack-berg approved these changes

2023-05-12 16:08 UTC, jsuereth requested changes
Please move this to https://github.com/open-telemetry/semantic-conventions

2023-05-24 02:52 UTC, trask commented
hey all, the @open-telemetry/technical-committee is reviewing this, and asked to create a summary of pros/cons. I have created https://github.com/open-telemetry/semantic-conventions/issues/50 based on the comments here, please comment further over there if I missed anything, thx!

2023-05-24 02:52 UTC, closed without merging