Add `process.runtime.jvm.available_processors` metric
open-telemetry/opentelemetry-specification pull request #3484
Opened 2023-05-08 22:26 UTC by trask

Fixes #3473

## Changes

Adds `process.runtime.jvm.available_processors` metric

2023-05-08 22:30 UTC, jack-berg commented on semantic_conventions/metrics/process-runtime-jvm-metrics.yaml
> +    instrument: updowncounter
updowncounter or gauge for this? There are no dimensions, so any spatial reaggregation will span different instances. Is it semantically meaningful to know the total number of available processors across all instances?

2023-05-09 04:34 UTC, reyang commented
@trask heads up - most likely this PR will be closed, and we'll ask you to resubmit the PR in a new repo, please refer to https://github.com/open-telemetry/opentelemetry-specification/pull/3474#issuecomment-1539386505.

2023-05-09 09:17 UTC, mateuszrzeszutek approved these changes

2023-05-09 19:27 UTC, trask commented on semantic_conventions/metrics/process-runtime-jvm-metrics.yaml
> +    instrument: updowncounter
maybe number of available processors across a cluster?

2023-05-09 20:33 UTC, reyang commented on semantic_conventions/metrics/process-runtime-jvm-metrics.yaml
> +    instrument: updowncounter
+1, it might make sense to get the total CPU cores across a distributed system (with the understanding that different cores might have different performance characteristics).

https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/supplementary-guidelines.md#additive-property

2023-05-09 22:30 UTC, PeterF778 commented on semantic_conventions/metrics/process-runtime-jvm-metrics.yaml
> +    instrument: updowncounter
Updowncounter makes sense to me, even if no meaningful aggregation will ever be made. Lack of dimensions is incidental here, it does not change the nature of the measured entity.

2023-05-09 22:44 UTC, jack-berg commented on semantic_conventions/metrics/process-runtime-jvm-metrics.yaml
> +    instrument: updowncounter
> maybe number of available processors across a cluster?

But its not really the number of available processors across the cluster, since the available processors always returns an integer number >= 1. 

I don't feel strongly about this, and probably would go with updowncount. Just thought it was worth calling out.

2023-05-09 22:44 UTC, jack-berg approved these changes

2023-05-11 16:33 UTC, jackshirazi approved these changes

2023-05-12 16:07 UTC, jsuereth requested changes
Please resubmit this against https://github.com/open-telemetry/semantic-conventions

2023-05-25 23:31 UTC, trask commented
Replaced by https://github.com/open-telemetry/semantic-conventions/pull/52

2023-05-25 23:31 UTC, closed without merging