Clarify that OTEL_SEMCONV_STABILITY_OPT_IN is a comma-separated list of values
open-telemetry/opentelemetry-specification pull request #3492
Opened 2023-05-09 21:56 UTC by trask

Fixes #3488

## Changes

Clarifies that OTEL_SEMCONV_STABILITY_OPT_IN is a comma-separated list of values

2023-05-09 22:34 UTC, reyang approved these changes

2023-05-09 22:49 UTC, pyohannes approved these changes

2023-05-10 11:16 UTC, arminru approved these changes

2023-05-10 11:16 UTC, arminru commented on specification/metrics/semantic_conventions/http-metrics.md
>  > * SHOULD introduce an environment variable `OTEL_SEMCONV_STABILITY_OPT_IN`
I think the env var should also be listed in https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/configuration/sdk-environment-variables.md - either in this PR or a follow-up.

2023-05-10 14:04 UTC, dyladan commented on specification/metrics/semantic_conventions/http-metrics.md
> +>   in the existing major version which is a comma-separated list of values.
```suggestion
>   in the existing major version which is a case-insensitive, comma-separated list of values with optional whitespace.
```

2023-05-10 16:58 UTC, carlosalberto approved these changes

2023-05-10 19:50 UTC, jsuereth approved these changes

2023-05-10 20:07 UTC, joaopgrassi approved these changes

2023-05-11 18:22 UTC, jsuereth requested changes
This PR needs to move to the new [Semantic Conventions](https://github.com/open-telemetry/semantic-conventions) repository.

2023-05-11 18:40 UTC, dyladan commented on specification/metrics/semantic_conventions/http-metrics.md
> +>   in the existing major version which is a comma-separated list of values.
ok fine with me

2023-05-12 15:58 UTC, arminru commented on specification/metrics/semantic_conventions/http-metrics.md
>  > * SHOULD introduce an environment variable `OTEL_SEMCONV_STABILITY_OPT_IN`
In lieu of a better place (that's the first instrumentation config env var we defined in the spec) I think it should be OK to add it there for now, so all spec-defined env vars are listed in one place.

2023-05-27 03:16 UTC, closed without merging