`.count` metric naming convention only applies to UpDownCounters
open-telemetry/opentelemetry-specification pull request #3493
Opened 2023-05-09 22:17 UTC by trask

Fixes #3457

## Changes

Update `.count` metric naming convention only apply to UpDownCounters.

2023-05-09 22:48 UTC, reyang approved these changes
LGTM, consider adding link to https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/compatibility/prometheus_and_openmetrics.md#otlp-metric-points-to-prometheus.

2023-05-09 22:49 UTC, reyang commented on specification/metrics/semantic_conventions/README.md
> +`_total` appended to their names when they are mapped to Prometheus, which would lead to
```suggestion
`_total` appended to their names when they are [mapped to Prometheus](../../compatibility/prometheus_and_openmetrics.md#otlp-metric-points-to-prometheus), which would lead to
```

2023-05-09 22:49 UTC, reyang commented on specification/metrics/semantic_conventions/README.md
> +Counters have `_total` appended to their names when they are mapped to Prometheus,
```suggestion
Counters have `_total` appended to their names when they are [mapped to Prometheus](../../compatibility/prometheus_and_openmetrics.md#otlp-metric-points-to-prometheus),
```

2023-05-09 22:55 UTC, jack-berg commented on specification/metrics/semantic_conventions/README.md
> +#### Use `count` Instead of Pluralization for UpDownCounters
Why keep this around for UpDownCounters? This section appears to include the only mentions of a metrics namespace. Getting rid this rule altogether would mean getting rid of a confusing and poorly defined concept.

2023-05-09 22:56 UTC, jmacd approved these changes

2023-05-09 23:01 UTC, MrAlias commented on specification/metrics/semantic_conventions/README.md
> +UpDownCounters should not use `_total` either because then they will look like
```suggestion
UpDownCounters SHOULD NOT use `_total` either because then they will look like
```

2023-05-09 23:01 UTC, MrAlias commented on specification/metrics/semantic_conventions/README.md
> +Counters have `_total` appended to their names when they are [mapped to Prometheus](../../compatibility/prometheus_and_openmetrics.md#otlp-metric-points-to-prometheus),
```suggestion
Counters SHOULD NOT append `_total`  to their names. Counters have `_total` appended to their names when they are [mapped to Prometheus](../../compatibility/prometheus_and_openmetrics.md#otlp-metric-points-to-prometheus),
```

2023-05-09 23:34 UTC, trask commented on specification/metrics/semantic_conventions/README.md
> +#### Use `count` Instead of Pluralization for UpDownCounters
> Getting rid this rule altogether would mean getting rid of a confusing and poorly defined concept.

I'd suggest let's start with this more obvious fix, and revisit removing the rule altogether depending on the outcome of #3476/#3477 (there are good arguments on both sides of that debate currently)

2023-05-10 11:24 UTC, joaopgrassi commented on specification/metrics/semantic_conventions/README.md
> +#### Use `count` Instead of Pluralization for UpDownCounters
Or maybe we decide which approach to take with the namespace, then we might not even need this? 🤔. I agree with @jack-berg I find the rules around this very confusing.

2023-05-10 11:40 UTC, gouthamve approved these changes
LGTM

2023-05-10 13:57 UTC, MrAlias approved these changes

2023-05-10 19:49 UTC, jsuereth approved these changes
This is a step in the right direction.

I'm supportive of this. I like what @jack-berg suggests, but I'm also a fan of merging this as-is and going further in the future.

2023-05-11 16:41 UTC, jack-berg approved these changes

2023-05-11 16:42 UTC, jack-berg commented on specification/metrics/semantic_conventions/README.md
> +#### Use `count` Instead of Pluralization for UpDownCounters
I think we should address this separately. Approved and voted for #3477.

2023-05-11 18:17 UTC, jsuereth requested changes
This PR needs to move to the Semantic Conventions repository.

2023-05-27 03:16 UTC, closed without merging