Make SDK Meter Creation more normative
open-telemetry/opentelemetry-specification pull request #3529
Opened 2023-06-02 10:11 UTC by pellared

## Changes

- Remove the `(optional)` and parameter names and simply say that the SDK MUST implement the API. This is done in order to minimize the confusion on what is "optional". It also makes the specification more normative.

2023-06-02 10:14 UTC, pellared commented on specification/metrics/sdk.md
> +(see [API](./api.md#meterprovider)).
I was considering to remove the

```
New `Meter` instances are always created through a `MeterProvider`
(see [API](./api.md#meterprovider)).
```

fragment as I am not sure if it provides value as it is not normative. Moreover, I imagine that in some  languages it may not be not possible to accomplish. 

If you agree please 👍 if not then 👎 . I will rather remove this in a separate PR.

2023-06-02 17:05 UTC, cijothomas commented on specification/metrics/sdk.md
> +The input provided by the user MUST be used to create
https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk.md#tracer-creation Would be good to get this consistent with trace too

2023-06-02 17:09 UTC, reyang requested changes
For small changes, I think the high order bit is to keep consistency across signals https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk.md#tracer-creation.

2023-06-02 18:19 UTC, pellared commented on specification/metrics/sdk.md
> +The input provided by the user MUST be used to create
Will do in same PR. ETA - Monday.

2023-06-05 11:33 UTC, pellared commented on specification/metrics/sdk.md
> +The input provided by the user MUST be used to create
Addressed via:
- https://github.com/open-telemetry/opentelemetry-specification/pull/3529/commits/c99692b4ab0d7f53341776209be48abee5c47060
- https://github.com/open-telemetry/opentelemetry-specification/pull/3529/commits/41b15558351e6cfaffe976477c34caeaf136045f

2023-06-05 11:44 UTC, pellared commented
> For small changes, I think the high order bit is to keep consistency across signals https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk.md#tracer-creation.

Done

2023-06-05 17:28 UTC, jack-berg commented on specification/metrics/sdk.md
> +(see [API](./api.md#meterprovider)).
Doesn't this directly conflict with a #3322, which aimed to make it allowable to directly obtain a noop meter?

2023-06-05 19:03 UTC, tigrannajaryan requested changes
These are changes to Stable part of the spec. For every change I believe we need to see an explanation about how this is allowed and is not breaking out stability guarantees.

2023-06-06 05:27 UTC, pellared commented on specification/metrics/sdk.md
> +(see [API](./api.md#meterprovider)).
This is a recommendation. Before #3322, it was a requirement. I think we can keep it as `SHOULD`. For reference from #3322:

> This change is desired by the Go SIG. We want to export these No-Op types so users can create them directly. This will allow them to embed these No-Op types in their SDKs to define default behaviour, and allow them to use them directly for testing (instead of having to go through the creation chain all starting with a MeterProvider).

2023-06-06 05:31 UTC, pellared commented
> These are changes to Stable part of the spec. For every change I believe we need to see an explanation about how this is allowed and is not breaking out stability guarantees.

I updated the description.

2023-06-08 07:01 UTC, pellared commented
@tigrannajaryan @jack-berg Have I addressed/answered your comments?

2023-06-08 13:22 UTC, tigrannajaryan commented on specification/logs/sdk.md
> +The `LoggerProvider` MUST implement the [Get a Logger Bridge API](bridge-api.md#get-a-logger).
```suggestion
The `LoggerProvider` MUST implement the [Get a Logger API](bridge-api.md#get-a-logger).
```

2023-06-08 13:22 UTC, tigrannajaryan commented on specification/logs/sdk.md
> +It SHOULD be possible to create `Logger` instances only through a `LoggerProvider`
I agree that this is not a breaking change. This deletes duplicate wording about parameters that was in this document and refers to the API definition in the `bridge-api.md` document, which already contains information about parameters and tells which parameters are optional.

I expect that nothing functional changes as a result of this editing of the spec. I would like a confirmation from one more spec approvers that that is also their understanding.

The same applies to the similar changes for `Meter` and `Tracer`.

2023-06-08 13:22 UTC, tigrannajaryan commented on specification/logs/sdk.md
> +It SHOULD be possible to create `Logger` instances only through a `LoggerProvider`
I would also delete the word "only" from this sentence. I don't see what value it adds. Can someone tell if there is a reason we are trying to prevent some other ways of creating `Logger` instances? (I am not aware of any other existing way).

2023-06-08 19:20 UTC, jack-berg reviewed
Can you add a changelog entry?

2023-06-12 07:02 UTC, pellared commented
> Can you add a changelog entry?

Done https://github.com/open-telemetry/opentelemetry-specification/pull/3529/commits/56b2bef414c16b057415c9a11e676a75851e8977

2023-06-16 05:37 UTC, pellared commented on specification/logs/sdk.md
> +It SHOULD be possible to create `Logger` instances only through a `LoggerProvider`
> Can someone tell if there is a reason we are trying to prevent some other ways of creating `Logger` instances? (I am not aware of any other existing way).

This is for symmetry with https://github.com/open-telemetry/opentelemetry-specification/pull/3529#discussion_r1218378452

2023-06-16 16:54 UTC, cijothomas approved these changes

2023-06-16 19:55 UTC, jack-berg approved these changes

2023-06-20 06:58 UTC, pellared commented on specification/logs/sdk.md
> +It SHOULD be possible to create `Logger` instances only through a `LoggerProvider`
@reyang Only for logs? Or for traces and metrics as well?

2023-06-24 15:38 UTC, yurishkuro commented on specification/metrics/sdk.md
> +It SHOULD be possible to create `Meter` instances only through a `MeterProvider`
```suggestion
It SHOULD only be possible to create `Meter` instances through a `MeterProvider`
```
I think this is what you're trying to say, the existing place of 'only' does not compute.

2023-06-24 15:38 UTC, yurishkuro commented on specification/metrics/sdk.md
> +It SHOULD be possible to create `Meter` instances only through a `MeterProvider`
But a better way to phrase it: is SHOULD NOT be possible ... other than through a provider.

2023-06-24 15:39 UTC, yurishkuro commented
> Moreover, I am not sure if possible to accomplish in all languages.

How come? Examples where it's not possible?

2023-06-26 07:27 UTC, pellared commented
> > Moreover, I am not sure if possible to accomplish in all languages.
> 
> How come? Examples where it's not possible?

Changed to 

> It is not desired in all languages (see https://github.com/open-telemetry/opentelemetry-specification/pull/3322).

Which is more clear and explicit

2023-06-26 07:28 UTC, pellared commented on specification/metrics/sdk.md
> +It SHOULD be possible to create `Meter` instances only through a `MeterProvider`
I prefer the first proposal (probably personal preference).

2023-06-26 07:28 UTC, pellared commented on specification/metrics/sdk.md
> +It SHOULD be possible to create `Meter` instances only through a `MeterProvider`
https://github.com/open-telemetry/opentelemetry-specification/pull/3529/commits/7d0e75fb3d5371735e1d04d782d84a8180ac6bbe

2023-06-26 12:52 UTC, yurishkuro approved these changes

2023-06-26 15:53 UTC, reyang approved these changes

2023-06-26 16:51 UTC, tigrannajaryan approved these changes

2023-06-26 16:52 UTC, merged