MetricReader.ForceFlush is concurrent safe
open-telemetry/opentelemetry-specification pull request #3563
Opened 2023-06-23 12:24 UTC by pellared

It looks like we have forgotten to mention `MetricReader.ForceFlush`

2023-06-23 12:32 UTC, jsuereth approved these changes

2023-06-23 15:24 UTC, reyang commented on specification/metrics/sdk.md
> +**MetricReader** - `Collect`, `ForceFlush` and `Shutdown` are safe to be called concurrently.
Where is this? https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#metricreader-operations

![image](https://github.com/open-telemetry/opentelemetry-specification/assets/17327289/2875b937-957e-476c-ac0a-3b1094b1f25b)

2023-06-23 15:24 UTC, reyang requested changes
https://github.com/open-telemetry/opentelemetry-specification/pull/3563/files#r1239953953

2023-06-24 06:41 UTC, pellared commented on specification/metrics/sdk.md
> +**MetricReader** - `Collect`, `ForceFlush` and `Shutdown` are safe to be called concurrently.
This fragment caused confusion:

https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md?plain=1#L171-L173

But you are right that the SDK does not explicitly require to have this method.

https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md?plain=1#L979-L983

But what is very strange is that ☝️  says that it accepts `OnShutdown callback functions.` and then we have https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md?plain=1#L1023-L1037

Do you have any proposal how to fix it?

My initial proposal would be to add a `ForceFlush` to the `MetricReader operations` section as I believe that deciding whether the operation is handled via callback or direct call is an implementation detail (but I may be wrong).

2023-06-26 20:32 UTC, reyang commented on specification/metrics/sdk.md
> +**MetricReader** - `Collect`, `ForceFlush` and `Shutdown` are safe to be called concurrently.
Similar to https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk.md#shutdown-1

_Shutdown MUST include the effects of ForceFlush._

I think we can change _"ForceFlush MUST invoke ForceFlush on all registered MetricReader and Push Metric Exporter instances"_ to _"ForceFlush MUST include the effects of Collect on all registered MetricReader instances, and ForceFlush on all Push Metric Exporter instances"_.

2023-06-27 15:37 UTC, jmacd approved these changes

2023-06-27 15:37 UTC, jmacd commented on specification/metrics/sdk.md
> +**MetricReader** - `Collect`, `ForceFlush` and `Shutdown` are safe to be called concurrently.
This conversation looks independent of the change in this PR, is that right?

2023-06-28 16:50 UTC, pellared commented on specification/metrics/sdk.md
> +**MetricReader** - `Collect`, `ForceFlush` and `Shutdown` are safe to be called concurrently.
I think it makes sense to address @reyang comment to make the PR more complete. These are "cohesive" changes.

2023-06-28 17:49 UTC, pellared commented on specification/metrics/sdk.md
> +**MetricReader** - `Collect`, `ForceFlush` and `Shutdown` are safe to be called concurrently.
@reyang Thanks for your suggestions. PTAL

2023-06-28 18:13 UTC, reyang commented on specification/metrics/sdk.md
> +#### ForceFlush
@pellared do you feel we have a clear understanding regarding "what's the difference between MetricReader.Collect and MetricReader.ForceFlush, and why do we need MetricReader.ForceFlush"? My gut feeling is that we don't.

2023-06-28 18:15 UTC, MrAlias commented on specification/metrics/sdk.md
> +#### ForceFlush
It doesn't make sense to define this for all `MetricReader`, it should only apply to the periodic exporting `MetricReader`. A pull based setup should not be required to implement this method as it will be a no-op and a user should call `Collect` instead.

2023-06-28 18:38 UTC, pellared commented on specification/metrics/sdk.md
> +#### ForceFlush
I moved it under `Periodic exporting MetricReader` section

https://github.com/open-telemetry/opentelemetry-specification/pull/3563/commits/2b8f91e5332c93a7f1c48c855b4b7266803b0abb

2023-06-28 18:39 UTC, pellared commented on specification/metrics/sdk.md
> +#### ForceFlush
I think this "kind of" duplicates. https://github.com/open-telemetry/opentelemetry-specification/pull/3563#discussion_r1245592766. Please resolve if you agree 😉 Otherwise I need more clarification.

2023-06-28 18:52 UTC, MrAlias approved these changes

2023-06-30 16:43 UTC, reyang commented on specification/metrics/sdk.md
> +#### ForceFlush
I feel we're heading towards the wrong direction:
1. The change proposed in this PR doesn't solve the problem in https://github.com/open-telemetry/opentelemetry-specification/blob/c07f4a2616ff50c7189f3365be20ef090ad53fc4/specification/metrics/sdk.md#L173-L175
2. It's unclear what's the responsibility of `Collect` and `ForceFlush` for periodic exporting MetricReader, and what exactly is expected from `MeterProvider.ForceFlush`.

2023-06-30 17:25 UTC, pellared commented on specification/metrics/sdk.md
> +#### ForceFlush
I agree with you.

I think that we should say that basically periodic reader's force flush does something like this:
Pseudocode:

```
metrics = this.Collect() 
this.exporter.Export(metrics)
this.exporter.ForceFlush()
```

Do you agree?

2023-06-30 17:27 UTC, pellared commented on specification/metrics/sdk.md
> +#### ForceFlush
Now I think I understand this https://github.com/open-telemetry/opentelemetry-specification/pull/3563#discussion_r1242732786 😅

2023-06-30 17:31 UTC, reyang commented on specification/metrics/sdk.md
> +#### ForceFlush
I disagree 😆

Export will yield the Success/Failure result, which means the subsequent call to exporter.ForceFlush would make no sense.

https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#exportbatch

2023-07-18 13:06 UTC, pellared commented
I have currently no bandwidth to work on it 😢 Also I am not sure if I understand @reyang suggestion. 

@reyang are you able to propose a PR yourself or make changes in this PR?

2023-07-18 13:13 UTC, pellared commented on specification/metrics/sdk.md
> +#### ForceFlush
I think it may be better if you address the issue in a separate PR. I think the comment is not conflicting with existing PR.

2023-07-18 13:27 UTC, pellared commented on specification/metrics/sdk.md
> +#### ForceFlush
Maybe https://github.com/open-telemetry/opentelemetry-specification/pull/3609 😉

2023-07-18 13:27 UTC, pellared commented
@carlosalberto I created https://github.com/open-telemetry/opentelemetry-specification/pull/3609

@reyang I think this is what you had in mind 😉 PTAL

2023-07-18 13:35 UTC, pellared commented
Closing. See https://github.com/open-telemetry/opentelemetry-specification/pull/3563

2023-08-02 08:42 UTC, pellared commented on specification/metrics/sdk.md
> +`ForceFlush` SHOULD collect metrics, call [`Export(batch)`](#exportbatch)
My preference is

```suggestion
`ForceFlush` MUST collect metrics, call [`Export(batch)`](#exportbatch)
```

2023-08-02 08:45 UTC, pellared commented on specification/metrics/sdk.md
> +[Periodic exporting MetricReader](#periodic-exporting-metricreader) instances.
Alternative version

```suggestion
`ForceFlush` MUST invoke `ForceFlush` on all registered
[MetricReader](#metricreader) instances that implement `ForceFlush`.
```

This would be more generic if the SDK provides more implementation of readers that handle `ForceFlush`. It may also be easier to interpret for SDK that prefer to add `ForceFlush` to the reader interface and implement it as a no-op e.g. for other reader implementations.

2023-08-02 09:00 UTC, pellared commented
Reopened per https://github.com/open-telemetry/opentelemetry-specification/pull/3609#issuecomment-1661755743.

I updated the PR, based on the feedback I got so far.

I added a comment here: https://github.com/open-telemetry/opentelemetry-specification/issues/1432#issuecomment-1661701778. I do not think that this PR conflicts with https://github.com/open-telemetry/opentelemetry-specification/issues/1432.

2023-08-02 21:06 UTC, Aneurysm9 commented on specification/metrics/sdk.md
> +[Periodic exporting MetricReader](#periodic-exporting-metricreader) instances.
I think that all `MetricReader` implementations should be required to implement `ForceFlush`, even if only as a no-op, and the `MeterProvider` must invoke that method on all registered readers.  This is the same thing we do for [`SpanProcessor` implementations](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk.md#forceflush-1).

2023-08-02 21:06 UTC, Aneurysm9 commented on specification/metrics/sdk.md
> +`ForceFlush` SHOULD collect metrics, call [`Export(batch)`](#exportbatch)
I believe this should be left as `SHOULD` to allow for no-op and pass-through implementations.

2023-08-03 12:59 UTC, pellared commented on specification/metrics/sdk.md
> +[Periodic exporting MetricReader](#periodic-exporting-metricreader) instances.
This is IMO language specific if metric readers have to implement it as a NOOP or just not implement it.  From PR description:

> The proposal does not require each MetricReader to implement ForceFlush (because it not needed for pull-based exporters) This is intended to support the following:
> 
> https://github.com/open-telemetry/opentelemetry-go/pull/4375
> https://github.com/open-telemetry/opentelemetry-php/issues/1086#issuecomment-1662140452

2023-08-03 15:43 UTC, MrAlias approved these changes

2023-08-04 19:22 UTC, jack-berg approved these changes

2023-08-07 09:19 UTC, pellared commented
@jsuereth @reyang PTAL

2023-08-08 06:21 UTC, brettmc commented on specification/metrics/sdk.md
> +so it can do as much as it could to collect and send the metrics.
This sounds clunky, how about this? 
```suggestion
This is a hint to a  periodic exporting MetricReader that it SHOULD do as much as possible
to collect and send metrics as soon as possible, preferably before returning from this method.
```

2023-08-08 07:53 UTC, pellared commented on specification/metrics/sdk.md
> +so it can do as much as it could to collect and send the metrics.
I would rather prefer to do it in a separate PR and also change similar sections like:

https://github.com/open-telemetry/opentelemetry-specification/blob/b2f923fb1650dde1f061507908b834035506a796/specification/metrics/sdk.md#L162-L164

Is it a blocker for you?

2023-08-08 15:07 UTC, dashpole approved these changes

2023-08-08 15:13 UTC, jsuereth approved these changes

2023-08-08 17:42 UTC, reyang approved these changes

2023-08-08 22:37 UTC, brettmc commented on specification/metrics/sdk.md
> +so it can do as much as it could to collect and send the metrics.
ok, it's not a blocker for me.

2023-08-08 22:57 UTC, merged