Remove jaeger exporter
open-telemetry/opentelemetry-specification pull request #3567
Opened 2023-06-26 13:46 UTC by marcalff

Fixes #3551

## Changes

Please provide a brief description of the changes here.

* [X] Removed the Jaeger exporter and related configuration
* [X] Removed the Jaeger Propagator
* [X] Removed entries from the spec compliance matrix.

2023-06-26 14:54 UTC, marcalff commented
To @open-telemetry/specs-trace-approvers @yurishkuro 

This PR removes the Jaeger Exporter from the specification, as it was scheduled for removal in July 2023, as announced by:
* https://github.com/open-telemetry/opentelemetry-specification/pull/2858

(1) In my understanding, now that trace data is no longer exported in Jaeger format (Jaeger can accept OTLP directly), there should no longer be a use case to have a Jaeger Propagator. As a result, this change removes the JaegerPropagator specifications as well.

(2) Also in my understanding, the mapping (`specification/trace/sdk_exporters/jaeger.md`) from OTLP to Jaeger format is no longer needed, as no code will ever perform this transformation, so the mapping is also removed from the specification.

(3) On a related topic, the specification also mention the Jaeger Remote Sampler. I left the spec for the remote sampler as is, assuming the remote sampler and the export format are orthogonal concerns, i.e., it still makes sense to have remote sampling even when traces are exported in OTLP, not Jaeger, format.

Please let me know if I missed something, in particular in (1), (2) and (3), and I will adjust the patch accordingly.

Some unresolved points, for which I need guidance:

File `specification/compatibility/opentracing.md` contains the following code:

```java
// Create a Tracer Shim relying on the global propagators.
createTracerShim(tracerProvider);

// Create a Tracer Shim using:
// 1) TraceContext propagator for TextMap
// 2) Jaeger propagator for HttPHeaders.
createTracerShim(tracerProvider, OTPropagatorsBuilder()
  .setTextMap(W3CTraceContextPropagator.getInstance())
  .setHttpHeaders(JaegerPropagator.getInstance())
  .build());
```

If the `JaegerPropagator` is indeed removed, not sure how to rewrite this part.

2023-06-26 15:56 UTC, reyang approved these changes

2023-06-26 16:44 UTC, yurishkuro requested changes
Jaeger propagator has no relation to the export data format. Once a propagation format is rolled out in a company, changing it is quite expensive and cannot be done without dual writing phase. In contrast, switching export format can be easily done incrementally.

2023-06-26 16:45 UTC, yurishkuro commented on experimental/trace/zpages.md
> +zPages are uniquely useful in a couple of different ways. One is that they're more lightweight and quicker compared to installing external tracing systems like Zipkin, yet they still share useful way
why remove Jaeger here?

2023-06-26 16:47 UTC, yurishkuro commented on specification/trace/sdk.md
> +  |     |              +---> Simple Span Processor   +--->  (ZipkinExporter) |
```suggestion
  |     |              +---> Simple Span Processor   +--->  (OTLPExporter) |
```

2023-06-26 21:19 UTC, marcalff commented on CHANGELOG.md
> +- Remove the Jaeger Exporter
Thanks, and fixed.

2023-06-26 21:22 UTC, marcalff commented on experimental/trace/zpages.md
> +zPages are uniquely useful in a couple of different ways. One is that they're more lightweight and quicker compared to installing external tracing systems like Zipkin, yet they still share useful way
Thanks for the comment.

Jaeger, regardless of the format used to send data to it, is still an external system part of the deployment, so yes, there is no need to change this.

Reverted.

2023-06-26 21:22 UTC, marcalff commented on specification/trace/sdk.md
> +  |     |              +---> Simple Span Processor   +--->  (ZipkinExporter) |
Thanks, fixed as indicated.

2023-06-26 21:46 UTC, marcalff commented on specification/trace/sdk_exporters/jaeger.md
> -The following table summarizes the major transformations between OpenTelemetry
Restored this file to preserve the mapping.

If it should move somewhere, please clarify where to exactly, or confirm if it can stay as is for now.

2023-06-26 21:56 UTC, marcalff commented
> Jaeger propagator has no relation to the export data format. Once a propagation format is rolled out in a company, changing it is quite expensive and cannot be done without dual writing phase. In contrast, switching export format can be easily done incrementally.

Thanks for the comments.

The PR is now revised as follows:
* the Jaeger Exporter is removed
* the Jaeger Propagator is untouched (previous changes are rolled back)
* the Jaeger Remote Sampler is untouched

Please take another look.

opentelemetry-cpp will also preserve the Jaeger Propagator then.

2023-06-27 00:53 UTC, yurishkuro approved these changes

2023-06-27 09:06 UTC, mateuszrzeszutek approved these changes
🎉

2023-06-27 11:51 UTC, arminru approved these changes

2023-06-27 14:41 UTC, merged