Do not require MetricReader to have ForceFlush
open-telemetry/opentelemetry-specification pull request #3609
Opened 2023-07-18 13:26 UTC by pellared

Supersedes (prior art) https://github.com/open-telemetry/opentelemetry-specification/pull/3563

Why: https://github.com/open-telemetry/opentelemetry-specification/pull/3563#discussion_r1245591156

By @reyang 

> "what's the difference between MetricReader.Collect and MetricReader.ForceFlush, and why do we need MetricReader.ForceFlush"? My gut feeling is that we don't.

After reading the a few times and reviewing Go Metrics SDK I think it is correct that it is not needed in the specification.

In Go Metrics SDK `ForceFlush` implementation is basically only delegating the calls to the push exporter or doing nothing.

`ForceFlush` is needed only for `MetricProvider` and `Push Metric Exporters`.

Take notice that [MetricReader operations](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#metricreader-operations) does not define `ForceFlush`. [OTel .NET SDK reader's](https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/src/OpenTelemetry/Metrics) DO NOT implement `ForceFlush`. As far as I understand the `MetricReader` can still have `ForceFlush`, but it is a detail which is left to the SDK implementation how metrics SDK accomplishes the goal of `MetricProvider.ForceFlush`.

Related (currently blocked) PR in Go SDK: https://github.com/open-telemetry/opentelemetry-go/pull/4375

2023-07-18 15:54 UTC, Oberon00 commented
It seems this part is "Stable" so we cannot remove functionality. I think it would be OK to recommend any new implementation to so though.

2023-07-18 16:20 UTC, pellared commented
> It seems this part is "Stable" so we cannot remove functionality. I think it would be OK to recommend any new implementation / major version to do so though.

What is `ForceFlush` doing for readers then? What is the functionality (from readers perpective)? It is never defined. I think it is a "fix" for a stable documentation. This is not removing any method from an interface as the specification does not define it.

> Also, if the two functions are redundant, my gut feeling would be to keep ForceFlush, since that name is consistent with other signals.

I am not changing any name.

2023-07-19 07:51 UTC, Oberon00 commented
OK, then probably I misunderstood something, I thought Collect was doing what ForceFlush would do. I'm not very familiar with metrics, please excuse the confusion.

2023-07-27 05:48 UTC, brettmc commented
> "what's the difference between MetricReader.Collect and MetricReader.ForceFlush, and why do we need MetricReader.ForceFlush"? My gut feeling is that we don't.

Wouldn't `MetricReader.ForceFlush` call `MetricReader.Collect` and _then_ call `ForceFlush` on any exporters associated with the reader?

2023-07-27 06:33 UTC, pellared commented
> > "what's the difference between MetricReader.Collect and MetricReader.ForceFlush, and why do we need MetricReader.ForceFlush"? My gut feeling is that we don't.
> 
> Wouldn't `MetricReader.ForceFlush` call `MetricReader.Collect` and _then_ call `ForceFlush` on any exporters associated with the reader?

@brettmc That was the original scope of https://github.com/open-telemetry/opentelemetry-specification/pull/3563 but it was rejected. As far as I understand the `MetricReader` can still have `ForceFlush`, but it is an implementation detail which is left to the SDK. The most important features are `ForceFlush` of metrics providers and `ForceFlush` of exporter.

2023-07-27 18:14 UTC, dashpole approved these changes

2023-07-27 18:30 UTC, reyang submitted a review, later dismissed

2023-07-28 09:18 UTC, Kielek approved these changes

2023-07-28 12:34 UTC, jsuereth commented
> In Go Metrics SDK ForceFlush implementation is basically only delegating the calls to the push exporter or doing nothing.

This is the design in MOST languages, and was the intention.   We need to require that exporters can be flushed, and mechanically that required a `ForceFlush` on `MetricReader` so that the `MeterProvider` could call it as `MetricReader`s are implemented.

Since `MetricReader` is exposed as something users could implement, how will you guarantee that `ForceFlush` sees exporters otherwise?


I.e. this is working as intended.

2023-07-28 12:38 UTC, jsuereth requested changes
This would be a breaking change to the specification.

Basically you're changing the registration requirements of the SDK form tracking `MetricReader`s registered to tracking `MetricExporter`s.  However,  this also doesn't expose any mechanism for `MetricExporter`s to be registered on the SDK.


See the "Configuration" section of the `MeterProvider`.

2023-07-28 15:24 UTC, pellared commented
@jsuereth 

> Since `MetricReader` is exposed as something users could implement

AFAIK it was never told nor specified. 

CC @open-telemetry/go-maintainers as the interface in Go SDK is "internal" (contains unexported methods that users cannot implement without hacking).

> This is the design in MOST languages, and was the intention.

I cannot confirm if this was the intention. The metrics SDK specification is extremely open to interpretation 🤷 

Do you think that https://github.com/open-telemetry/opentelemetry-specification/pull/3563 is the desired change?

2023-07-28 16:07 UTC, reyang commented
I think the current specification is _okay_ but not _great_.

Ultimately, we will have to revisit #1432, and IIRC Collect and ForceFlush were introduced with the future consideration that collection cycle _can_ be different than the export cycle.

@pellared would you be interested / have bandwidth to address #1432? If not, my gut feeling is that most likely we will just leave the spec "as-is" for now.

2023-07-28 19:15 UTC, jsuereth commented
> AFAIK it was never told nor specified.

I agree the specification is obtuse here.  See [this section](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#pull-metric-exporter) on Pull-based exporters:


```
Implementors MAY choose the best idiomatic design for their language. 
For example, they could generalize the [Push Metric Exporter interface](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#push-metric-exporter) design 
and use that for consistency, they could model the pull exporter as 
[MetricReader](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#metricreader),
or they could design a completely different pull exporter interface. 
If the pull exporter is modeled as MetricReader, implementors 
MAY name the MetricExporter interface as PushMetricExporter to prevent naming confusion.
```

2023-07-28 19:23 UTC, jsuereth commented
> Do you think that https://github.com/open-telemetry/opentelemetry-specification/pull/3563 is the desired change?

I did approve this change.  I'm also ok taking some time to untangle the specification here.   There are two pieces that are important to me:

1. All `MetricReader` instances are registered with a `MeterProvider`.  This allows the actual mechanism of storing/exporting metrics to be optimised based on configuration.
2. Users have a mechanism to `ForceFlush` metrics *through* whatever pipelines we've defined to `MetricExporter`s.  Yes this only makes sense for push-based, but the registration should be done using a `MeterProvider` and affect all configured push exporters.  This alleviates issues, e.g. w/ batch compute or FAAS where you want to flush-on-death or flush-after-request.

The way this current PR is implemented removes explicit wording for (1).

2023-07-30 21:05 UTC, pellared commented
> The way this current PR is implemented removes explicit wording for (1).

@jsuereth Makes sense. WDYT of https://github.com/open-telemetry/opentelemetry-specification/pull/3609/commits/6d3a25a09e0a98cfbf52782092ae76ed3d4086f4?

> Ultimately, we will have to revisit https://github.com/open-telemetry/opentelemetry-specification/issues/1432, and IIRC Collect and ForceFlush were introduced with the future consideration that collection cycle can be different than the export cycle.

> @pellared would you be interested / have bandwidth to address https://github.com/open-telemetry/opentelemetry-specification/issues/1432? If not, my gut feeling is that most likely we will just leave the spec "as-is" for now.

I think that https://github.com/open-telemetry/opentelemetry-specification/issues/1432 has a bigger scope. I would prefer to make a baby steps to improve the current state of the specification. I think it is better when I propose smaller changes as otherwise my contributions would be extremely ineffective because I was not participating in creating of the metrics SDK. At last, I am often unable to join the Specification SIG meeting. Still I will take a look at the issue 😉

2023-07-30 21:31 UTC, pellared commented on specification/metrics/sdk.md
> +[Push Metric Exporter](#push-metric-exporter) instances.
I was also thinking of something like

```suggestion
`ForceFlush` MUST invoke `ForceFlush` on all registered
[Push Metric Exporter](#push-metric-exporter) instances
and beforehand invoke `Collect` on their related
[MetricReader](#metricreader) instances.
```

But I am not sure if it would not be to much and it could conflict with https://github.com/open-telemetry/opentelemetry-specification/issues/1432

2023-07-31 12:49 UTC, jsuereth commented
> @jsuereth, makes sense. WDYT of https://github.com/open-telemetry/opentelemetry-specification/commit/6d3a25a09e0a98cfbf52782092ae76ed3d4086f4 + https://github.com/open-telemetry/opentelemetry-specification/commit/c538b91c7716875c6a19d6d7fab54bf39694a955?

I like the second, the first I think is as confusing as the existing specification on this.

2023-07-31 12:51 UTC, jsuereth commented on specification/metrics/sdk.md
> +`ForceFlush` MUST invoke `ForceFlush` on all registered
`MetricExporter`s are *not* registered on the `MeterProvider`, only `MetricReader`s.

I think my best cut at what you're trying to do here would be:

```md
`ForceFlush` MUST invoke `ForceFlush` on all [Push Metric Exporter](#push-metric-exporter) instances attached to all registered `MetricReader` instances.
```

2023-07-31 15:36 UTC, pellared commented on specification/metrics/sdk.md
> +`ForceFlush` MUST invoke `ForceFlush` on all registered
WDYT of https://github.com/open-telemetry/opentelemetry-specification/pull/3609/commits/8b517b3416da0bc75f0d1af2242a06a9f807e536?

I am open to any suggestions.

2023-07-31 15:37 UTC, pellared commented on specification/metrics/sdk.md
> +[Push Metric Exporter](#push-metric-exporter) instances.
Therefore (if you agree) I think it is better to leave as it is and resolve this comment.

2023-07-31 15:43 UTC, pellared commented on specification/metrics/sdk.md
> +`ForceFlush` MUST invoke `ForceFlush` on all registered
TBH I am not sure if your comment is valid.

> MetricExporters are not registered on the MeterProvider, only MetricReaders.

This assumes that exporters are also registered

https://github.com/open-telemetry/opentelemetry-specification/blob/dd386203489cf5db9aac3e088d5296f7256315b5/specification/metrics/sdk.md#L155-L156

Also the exporters are seen as part of the configuration

https://github.com/open-telemetry/opentelemetry-specification/blob/dd386203489cf5db9aac3e088d5296f7256315b5/specification/metrics/sdk.md#L124-L129

2023-07-31 20:51 UTC, jsuereth commented on specification/metrics/sdk.md
> +`ForceFlush` MUST invoke `ForceFlush` on all registered
The current language always says you reach `MetricExporter through its MetricReader`.

The specification ONLY requires registering `MetricReader` on the SDK:

https://github.com/open-telemetry/opentelemetry-specification/blob/dd386203489cf5db9aac3e088d5296f7256315b5/specification/metrics/sdk.md?plain=1#L1064-L1071


That's the only language that supports registration.  

So given precedence, I'd argue your wording should be:

```
`ForceFlush` MUST invoke `ForceFlush` on all [Push Metric Exporter](#push-metric-exporter) instances through their `MetricReader`s.
```

Which is basically why I was suggesting ForceFlush exists on MetricReader to begin with.

2023-07-31 21:01 UTC, pellared commented on specification/metrics/sdk.md
> +`ForceFlush` MUST invoke `ForceFlush` on all registered
PTAL https://github.com/open-telemetry/opentelemetry-specification/pull/3609/commits/8850ba9c93a9cab115e53c19a3e13183253189ed

2023-08-02 08:36 UTC, pellared commented
During the SIG meeting we agreed that this PR does not make the specification more "normative". While it was acceptable the "fuzziness" of the specification would remain. We decided to revisit https://github.com/open-telemetry/opentelemetry-specification/pull/3563 and make sure it does not conflict with https://github.com/open-telemetry/opentelemetry-specification/issues/1432. We also agreed that we should not to solve too much in a single PR (e.g. solve  https://github.com/open-telemetry/opentelemetry-specification/issues/1432) but just make sure to improve the `ForceFlush` descriptions.

2023-08-02 08:40 UTC, closed without merging