ForceFlush should have a disclaimer, rather than guidance in the spec
open-telemetry/opentelemetry-specification pull request #3620
Opened 2023-07-24 20:28 UTC by dashpole

## Changes

The spec for metric exporter's ForceFlush method doesn't currently have any guidance for the SDK authors.  Instead, it appears to provide guidance to users about when they should call ForceFlush.

I assume the intention is that the guidance about when to call ForceFlush be passed on to users.  This PR clarifies that the guidance should be passed on to users with documentation on the ForceFlush method.

2023-07-24 20:34 UTC, reyang commented
> The spec for metric exporter's ForceFlush method doesn't currently have any guidance for the SDK authors. Instead, it appears to provide guidance to users about when they should call ForceFlush.

Good point!

We have the same issue in other specs, e.g. https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk.md#forceflush-1.

2023-07-24 20:38 UTC, dashpole commented
> We have the same issue in other specs

Updated the trace and log SDK specs as well.

2023-07-24 20:39 UTC, reyang approved these changes

2023-07-24 20:39 UTC, reyang commented on specification/logs/sdk.md
> +`ForceFlush` SHOULD be documented with a disclaimer stating that it should only
This looks _okay_ to me. Just calling out loud, do we want to remove this line entirely? There are many similar APIs such as file.flush https://learn.microsoft.com/en-us/dotnet/api/system.io.filestream.flush.

I guess it could be helpful to explain the cost/consequence rather than saying "only call me when it is absolutely necessary" (part of the reason is that "necessary" is blurry). e.g. https://github.com/open-telemetry/opentelemetry-dotnet/blob/a808276efaf7e7a13420d993cea903cbff262996/src/OpenTelemetry/Logs/LoggerProviderExtensions.cs#L53-L54

2023-07-24 20:41 UTC, MrAlias approved these changes

2023-07-24 20:47 UTC, dashpole commented on specification/logs/sdk.md
> +`ForceFlush` SHOULD be documented with a disclaimer stating that it should only
I am also fine with removal, if we don't think the disclaimer is necessary.

2023-07-24 20:55 UTC, reyang commented on specification/logs/sdk.md
> +`ForceFlush` SHOULD be documented with a disclaimer stating that it should only
I personally would vote for removal, maybe let's gather more opinions?
Folks who prefer removal please give 👍, otherwise 👎.

2023-07-26 15:34 UTC, dashpole commented on specification/logs/sdk.md
> +`ForceFlush` SHOULD be documented with a disclaimer stating that it should only
Updated the PR to remove these sections.

2023-07-26 17:17 UTC, reyang approved these changes

2023-07-28 13:28 UTC, Oberon00 requested changes
> This PR removes that guidance because it is not relevant to the specification of the SDK.

Formally, you may be right, but I don't see any benefit in removing the guidance. Especially when  there is no alternative location to move it to.

2023-07-28 15:40 UTC, cijothomas commented
An alternative would be to do something similar to:
https://github.com/open-telemetry/opentelemetry-specification/pull/2383/files

2023-07-29 06:42 UTC, Oberon00 commented
I am OK with adding a documentation requirement, but it might be overkill. I can also see why the current wording with SHOULD is technically wrong. How about changing it to a non-normative "Note:" and using lowercase "should" or wording such as "is only meant for ..."?

2023-08-14 03:16 UTC, closed without merging