OTLP exporter: Describe protocol registration mechanism
open-telemetry/opentelemetry-specification pull request #3722
Opened 2023-10-17 08:42 UTC by pellared

Fixes https://github.com/open-telemetry/opentelemetry-specification/issues/3721

2023-10-17 08:52 UTC, pellared commented
@yurishkuro Do you think such changes would make the specification better? It is a draft because I would first would like you to review it.

2023-10-17 15:13 UTC, yurishkuro commented on specification/protocol/exporter.md
> +The exporter SHOULD NOT depend on any transport protocol driver.
I agree with this on principle, but what does it mean in practice for an average user? Do we already have defaults that will be undone by this requirement?

2023-10-17 20:23 UTC, pellared commented on specification/protocol/exporter.md
> +The exporter SHOULD NOT depend on any transport protocol driver.
> Do we already have defaults that will be undone by this requirement?

I do not think implementations having different approach should change it as in my opinion it would be a breaking change. Do you agree? Should we call it out explicitly?

2023-10-17 20:24 UTC, pellared commented
Based on @yurishkuro initial review I think this it is ready for wider feedback. "Undrafting"

2023-10-17 21:53 UTC, pellared commented on specification/protocol/exporter.md
> +The exporter SHOULD NOT depend on any transport protocol driver.
> I agree, but wouldn't this pretty much affect all implementations? 

This is the reason why I decided to go with "SHOULD" and not "MUST" normative wording. As changing the existing SDKs would be a breaking change. What do you think of adding soemthing like:

```

> If that's the case, then this addition is nice but has no practical impact, and breaking changes would be required for any SDK that would want to support this opt-in model.

2023-10-17 22:02 UTC, reyang commented on specification/protocol/exporter.md
> +SDKs MUST provide at least one of them. If they provide only one, it SHOULD be a driver for `http/protobuf`.
Does this make sense for JavaScript running inside a browser?

2023-10-17 22:06 UTC, pellared commented on specification/protocol/exporter.md
> +SDKs MUST provide at least one of them. If they provide only one, it SHOULD be a driver for `http/protobuf`.
1. This section is just moved from another location.
2. This should be a subject of a separate issue/PR

I do not think it should be addressed it in this PR.

2023-10-17 22:14 UTC, pellared commented on specification/protocol/exporter.md
> +SDKs MUST provide at least one of them. If they provide only one, it SHOULD be a driver for `http/protobuf`.
I created https://github.com/open-telemetry/opentelemetry-specification/issues/3724

2023-10-18 07:00 UTC, yurishkuro submitted a review, later dismissed

2023-10-18 13:43 UTC, tigrannajaryan requested changes
Blocking since I think it is a breaking change. Will lift the blocked once we clarify it is not breaking.

2023-10-18 13:59 UTC, tigrannajaryan commented
>In a stable SDK release, the properties described above can be different for backward compatibility reasons.

This assumes it is OK to make breaking changes to the "Stable" spec as long as we don't require stable SDKs to implement them. I don't think we discussed in the past and I am not sure we want to allow it.

@open-telemetry/specs-approvers I think we need to have a position on this: are breaking changes to the spec's "Stable" document allowed provided that we don't require stable SDK implementations to adopt such changes? My first thought is that this should not be allowed and a slippery slope, but I think it is worth discussing.

If we allow it then possibly we need to:
- Mark every spec change with a version number in which it was introduced.
- Label every SDK implementation with the version number of the spec it implements.

This may be doable but introduces complexity which I am not sure we want. 

There are probably also other approaches to handle such changes.

Thoughts?

2023-10-18 14:04 UTC, pellared commented
> > In a stable SDK release, the properties described above can be different for backward compatibility reasons.
> 
> This assumes it is OK to make breaking changes to the "Stable" spec as long as we don't require stable SDKs to implement them. I don't think we discussed in the past and I am not sure we want to allow it.

Just for reference I think it already happened before (but it was not clearly described). See https://github.com/open-telemetry/opentelemetry-specification/issues/3717.

2023-10-18 14:57 UTC, dyladan commented
JS provides gRPC, http/protobuf, and http/JSON for all signals. We were the first and may still be the only, aside from the collector, to support all 3 "drivers".

2023-10-18 16:02 UTC, tigrannajaryan commented
> Just for reference I think it already happened before (but it was not clearly described). See #3717.

Are you referring to https://github.com/open-telemetry/opentelemetry-specification/pull/3719 ?

I don't think that one is a breaking change. Looks like a clarification of what "still supported" means.

2023-10-18 17:25 UTC, yurishkuro commented
@pellared this was discussed at the TC meeting. The consensus was that we do not want that specific wording that allows stable SDKs to opt-out of the requirement, as this would lead to bifurcation of capabilities in different SDKs in the long term and set a negative precedent. Instead, it was noted that the current phrasing of the spec is intentionally vague such that it does not _require_ supporting every flavor that can be specified in the config. As an example, Zipkin/Jaeger exporters were cited which are required to be supported but not so that they always have to be statically linked. The proposal is to find a phrasing that double-clicks into this gray area to clarify that SDKs are _allowed_ to implement support for different capabilities via opt-in model (as some already do), but are not required to do so.

2023-10-19 18:32 UTC, pellared commented
I am changing this PR to a draft.

2023-10-25 15:05 UTC, pellared commented
Closing in favor of https://github.com/open-telemetry/opentelemetry-specification/pull/3730

2023-10-25 15:05 UTC, closed without merging