Specify allowed characters for Baggage keys and values
open-telemetry/opentelemetry-specification pull request #3801
Opened 2023-12-21 16:53 UTC by yurishkuro

## Changes

* Add missing spec language on what keys and values are allowed for the baggage.
* Definitions are aligned with W3C Baggage Spec, but provide a distinction between API representation and the wire encoding (done by W3C Propagator)

2023-12-21 18:02 UTC, reyang submitted a review, later dismissed

2023-12-21 18:02 UTC, reyang commented on CHANGELOG.md
> +- Specify allowed characters for Baggage keys and values.
```suggestion
- Specify allowed characters for Baggage keys and values.
([#3801](https://github.com/open-telemetry/opentelemetry-specification/pull/3801))
```

2023-12-21 19:27 UTC, yurishkuro commented
Note: this could be a breaking change e.g. for Go SDK (https://github.com/open-telemetry/opentelemetry-go/issues/3685), whose current implementation is wrong imo.

2023-12-28 09:42 UTC, pellared approved these changes
> Note: this could be a breaking change e.g. for Go SDK ([open-telemetry/opentelemetry-go#3685](https://github.com/open-telemetry/opentelemetry-go/issues/3685)), whose current implementation is wrong imo.

I would say that we chose the wrong decision in OTel Go. Still we might try to fix it in some backwards-compatible way (by extending the API). 

TL;DR; For me this is not a blocker for this PR.

2023-12-28 09:42 UTC, pellared commented on specification/baggage/api.md
> +Alpha-numeric names are strongly recommended. Language API MAY return
nit

```suggestion
Alpha-numeric names are strongly recommended. Language API SHOULD return
```

2023-12-29 10:18 UTC, pellared commented
I am working towards making a fix in OTel Go: https://github.com/open-telemetry/opentelemetry-go/pull/4804

2024-01-02 13:10 UTC, dyladan commented on specification/baggage/api.md
> +Baggage **names** are strings that satisfy the `token` definition from
The W3C is currently considering allowing UTF-8 strings for keys as well as values. The otel API can make their own decision, but I think the UTF-8 change is likely to go through in W3C at this point.

2024-01-02 15:39 UTC, yurishkuro commented on specification/baggage/api.md
> +Baggage **names** are strings that satisfy the `token` definition from
Please link a ticket. Such change in W3C will be seriously breaking.

2024-01-07 01:56 UTC, jkwatson commented
Java is also not compliant with this. Currently, we only propagate keys/values that meeting this definition, but we allow arbitrary keys for in-memory usage.

2024-01-10 22:44 UTC, ocelotl commented on specification/baggage/api.md
> +`Get` and `Set` operations are symmetrical with respect to name and value,
```suggestion
```

2024-01-11 01:04 UTC, yurishkuro commented on specification/baggage/api.md
> +Alpha-numeric names are strongly recommended. Language API SHOULD return
SHOULD is a normative word that does not apply to user-supplied values, it's not something that the OTEL SDK can control.

2024-01-11 01:22 UTC, yurishkuro commented on specification/baggage/api.md
> +Baggage **names** are strings that satisfy the `token` definition from
https://github.com/w3c/baggage/issues/99

There is no resolution there as of Jan 2024. I don't think it should block this PR - it makes changes to match the __current__ W3C spec. If we adopt ahead of time more extensive alphabet for keys, then OTEL simply won't be compatible w/ W3C spec.

2024-01-11 01:24 UTC, yurishkuro commented on specification/baggage/api.md
> +any valid UTF-8 string as baggage value. Language API MUST guarantee that
phrased it differently

2024-01-11 01:24 UTC, yurishkuro commented on specification/baggage/api.md
> +`Get` and `Set` operations are symmetrical with respect to name and value,
phrased it differently

2024-01-11 01:26 UTC, yurishkuro commented on specification/baggage/api.md
> +i.e. `Get` MUST return the same **value** string as received in `Set`.
"i.e." is not used to give an example, but to provide alternative wording. But you're right, "symmetrical" was unnecessary, I phrased it in simpler terms, and provided explicit examples (thanks for a good idea!)

2024-01-11 20:54 UTC, ocelotl approved these changes

2024-01-16 15:58 UTC, jack-berg commented on specification/baggage/api.md
> +an error when given a baggage name that is not a `token`.
> Java is also not compliant with this. Currently, we only propagate keys/values that meet this definition, but we allow arbitrary keys for in-memory usage.

➕ 

Our stance in java is that the API should never return an error. If anyone uses the API incorrectly, we log a warning and use a no-op implementation of the operation. Applying this logic to baggage and these new key constraints, when a invalid key / value is recorded in baggage, we would log an error and skip recording that key / value pair. Like @jkwatson said, this is not our behavior today and skipping recording those key / value pairs is a breaking behavioral change. But because we only propagate the valid key / values, the consequence of us not enforcing these constraints is only that other consumers of baggage in process (i.e. span processors, log processors) can access key / values that will not be propagated.

@jkwatson I propose that if this is merged, we keep the existing behavior which records the invalid key / values (since changing would be breaking) but add a check which logs if the key / value is invalid. If invalid, log a message indicating that the key / value won't be propagated, but record it for access by in-process consumers.

2024-01-16 16:07 UTC, yurishkuro commented on specification/baggage/api.md
> +an error when given a baggage name that is not a `token`.
I am fine changing SHOULD to MAY

2024-01-16 16:29 UTC, tedsuo commented on specification/baggage/api.md
> +an error when given a baggage name that is not a `token`.
Actually, API methods in OpenTelemetry MUST NOT return errors. A first principle of OpenTelemetry API design is that users should never have to wrap any OpenTelemetry API call in error or exception handling code.

https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/error-handling.md#basic-error-handling-principles

2024-01-16 16:55 UTC, pellared commented on specification/baggage/api.md
> +Baggage **names** are strings that satisfy the `token` definition from
@dyladan Would the change be breaking? 

As right now a key like: `%20` is valid and will not be encoded. I guess after https://github.com/w3c/baggage/issues/99 it would be still valid but the key will be encoded to a whitespace: ` `.

2024-01-16 17:12 UTC, yurishkuro commented on specification/baggage/api.md
> +an error when given a baggage name that is not a `token`.
> API methods in OpenTelemetry MUST NOT return errors

they must not raise exceptions, but they _can_ return errors when idiomatic in the language (e.g. Try in Scala)

2024-01-16 17:33 UTC, yurishkuro commented on specification/baggage/api.md
> +an error when given a baggage name that is not a `token`.
Proposed change:

> Language API MUST ignore baggage entries given a name that is not a `token`, e.g. they MAY return an error (if idiomatic for the language) or fallback to a no-op implementation.

2024-01-16 19:04 UTC, jack-berg commented on specification/baggage/api.md
> +an error when given a baggage name that is not a `token`.
> Applying this logic to baggage and these new key constraints, when a invalid key / value is recorded in baggage, we would log an error and skip recording that key / value pair. Like @jkwatson said, this is not our behavior today and skipping recording those key / value pairs is a breaking behavioral change.

Sorry if my message wasn't clear. Invalid key / values aren't propagated across application boundaries, but they are recorded in baggage such that they can be used by other baggage consumers like processors. 

I believe your intent here would be to say that not only should invalid key / value pairs not be propagated, but they also shouldn't be recorded in baggage in the first place. The "not recorded in baggage in the first place" part is what I think is a breaking change for java.

2024-01-16 19:13 UTC, yurishkuro commented on specification/baggage/api.md
> +an error when given a baggage name that is not a `token`.
I see. The question of how encoding restrictions impact in-process API is always a tricky one, especially since encodings technically could vary across propagators. But we want to ensure that at least w3c propagator works, hence the `token` restriction. The main function of baggage is not in-process propagation, but across processes - for in-process people should use Context API directly with no restrictions. The fact that Java Baggage implementation provided accidental feature of unrestricted in-process propagation should not be treated as a breaking change if that behavior is restricted, imo, as long as it still maintains its cross-process propagation capability (the primary function).

2024-01-23 16:03 UTC, dyladan commented on specification/baggage/api.md
> +Baggage **names** are strings that satisfy the `token` definition from
Im sorry I didn't follow up. We're working with the i11y group at w3c but it seems this change will in fact not go through in the baggage spec. It is not providing enough value to justify breaking our existing implementations.

2024-01-26 13:32 UTC, pellared commented on specification/baggage/api.md
> +Baggage **names** are strings that satisfy the `token` definition from
I think this conversation can be resolved.

2024-01-30 11:52 UTC, pellared requested changes

2024-01-30 11:52 UTC, pellared commented on specification/baggage/api.md
> +an error when given a baggage name that is not a `token`.
Should the Baggage API have the same constrains as W3C Baggage Propagator? Is this change not mixing different concerns?

The Baggage API can be used intra-process and then usage of UTF-8 keys would not be a problem.

Shouldn't the W3C Baggage Propagator report a problem (e.g. emit some logs) when it encounters a key that it cannot encode?

2024-01-30 11:58 UTC, pellared commented on specification/baggage/api.md
> +an error when given a baggage name that is not a `token`.
Should the Baggage API have the same constrains as W3C Baggage Propagator? Is this change not mixing different concerns?

The Baggage API can be used in-process and then usage of UTF-8 keys would not be a problem.

> The main function of baggage is not in-process propagation, but across processes - for in-process people should use Context API directly with no restrictions. 

I will say that is it "one" of the functions. Even the [spec](https://opentelemetry.io/docs/concepts/signals/baggage/) says:

> Baggage MAY be propagated across process boundaries or across any arbitrary boundaries

And [here](https://opentelemetry.io/docs/concepts/signals/baggage/#why-does-otel-baggage-exist):

> Baggage provides a uniform way to store and propagate information across a trace and other signals. For example, you may want to attach information from your application to a span and retrieve that information much later and use it later on with another span.

Shouldn't the W3C Baggage Propagator report a problem (e.g. emit some logs) when it encounters a key that it cannot encode?

2024-01-30 12:10 UTC, pellared requested changes
https://github.com/open-telemetry/opentelemetry-specification/pull/3801#discussion_r1471084605

2024-01-30 15:48 UTC, carlosalberto commented
I support @pellared comment on different concerns (the in-process API and the inter-process propagation). Maybe we can adjust this PR to only mention that invalid keys MUST NOT be propagated? Then we can spin off a separate issue/PR discussing on `Baggage` API part.

(Also this would be easy to do as it would align with what some SIGs _already_ do)

2024-02-07 06:18 UTC, yurishkuro commented
Updated to allow arbitrary strings in the API, but caution that Propagators may not allow some keys.

2024-02-07 07:55 UTC, pellared commented on specification/baggage/api.md
> +For example, the [W3C Baggage specification](https://github.com/w3c/baggage/blob/main/baggage/HTTP_HEADER_FORMAT.md#key)
When possible I think we should refer to [W3C Working Draft](https://www.w3.org/standards/types#WD)

```suggestion
For example, the [W3C Baggage specification](https://www.w3.org/TR/baggage/#key)
```

2024-02-07 07:55 UTC, pellared commented on specification/baggage/api.md
> +See also [W3C Baggage -- Case sensitivity of keys](https://github.com/w3c/baggage/blob/main/baggage/HTTP_HEADER_FORMAT_RATIONALE.md#case-sensitivity-of-keys).
I suggest to clearly say that this is from Rationale docs.

```suggestion
See also [W3C Baggage Rationale](https://github.com/w3c/baggage/blob/main/baggage/HTTP_HEADER_FORMAT_RATIONALE.md#case-sensitivity-of-keys).
```

2024-02-08 06:11 UTC, pellared approved these changes

2024-02-12 21:15 UTC, carlosalberto approved these changes

2024-02-12 21:16 UTC, reyang approved these changes

2024-02-12 21:23 UTC, yurishkuro commented on specification/baggage/api.md
> +an error when given a baggage name that is not a `token`.
Changed to allow any strings.

2024-02-12 21:26 UTC, yurishkuro commented
cc @open-telemetry/go-maintainers - the new wording makes Go implementation non-compliant, but it's not a breaking change for its API, you will just need to relax the checks (i.e. never return errors from `baggage.New`)

2024-02-16 01:41 UTC, carlosalberto commented
Let's remind maintainers in the call next Monday about this, but otherwise we are fine to go.

2024-02-22 15:26 UTC, yurishkuro commented
@carlosalberto are we good to merge?

2024-02-22 15:54 UTC, merged