Define sdk extension component support in file configuration
open-telemetry/opentelemetry-specification pull request #3802
Opened 2023-12-22 17:36 UTC by jack-berg

Part of incorporating [OTEP #225](https://github.com/open-telemetry/oteps/pull/225) into the specification.

Followup to #3744.

This defines how file configuration works with custom SDK extension components (Samplers, Exporters, etc). 

It defines the concept of a Component Provider:
- Component providers are registered with the type of extension component they provide and a name. Component providers are registered automatically or manually based on what is idiomatic in the language.
- Component providers have a Create Plugin method, which passes configuration properties as a parameter and returns the configured component
- When Create is called to interpret a file configuration model, and it comes across a reference to a extension component which is not built-in, it invokes Create Plugin on the corresponding component provider. If no corresponding component provider exists, or if Create Plugin returns an Error, Create returns an error.

Prototype implementation in java here: https://github.com/open-telemetry/opentelemetry-java-examples/pull/227

2024-01-02 09:21 UTC, pirgeo commented on specification/configuration/file-configuration.md
> +  possible to access properties in a type safe manor, based on what is idiomatic
```suggestion
  possible to access properties in a type safe manner, based on what is idiomatic
```

2024-01-03 17:00 UTC, jmacd approved these changes

2024-01-03 18:30 UTC, carlosalberto approved these changes

2024-01-10 16:45 UTC, jsuereth approved these changes
One NIT, but it's mostly about possible misunderstanding of the spec and is non-blocking.

2024-01-10 16:45 UTC, jsuereth commented on specification/configuration/file-configuration.md
> +The SDK MUST provide a mechanism to
I do feel like the term "SDK", with regards to API/interface, isn't super well defined.  I don't really have a better suggestion for verbage here, outside of perhaps claiming that this mechanism needs to be on the *builder* of the SDK, or prior to SDK construction, components need to be provided.

2024-01-10 16:57 UTC, jack-berg commented on specification/configuration/file-configuration.md
> +The SDK MUST provide a mechanism to
Maybe "the file configuration implementation"?

2024-01-18 13:24 UTC, marcalff reviewed
If I understand correctly, in case of SDK extensions:

* the component provider accepts a **_file_** configuration model (a.k.a a yaml parsed tree node for the extension point) as input, in the Create() operation

There is no way to parse yaml into a **_memory_** configuration model, or make up completely a memory configuration model programmatically, and then have the Create() operation take this memory model as input.

I am aware that supporting a memory configuration model for SDK extensions has some extra difficulties, like:

* have a generic representation of an "exporter extension" in the memory configuration model (which is built-in), that contains a representation of the yaml fragment for a given (generic, not built-in) exporter
* have the exporter extension Create() operation take this generic representation as input

Still, separating parse from create, as in:

* Parse takes a file configuration as input, returns a memory configuration as output
* Create takes a memory configuration as input, instantiates the proper objects in the SDK extension

is better, because it allows to:

* process and adjust the memory configuration model, if needed, between parse and create.
* build a memory configuration model programmatically, instead of parsing yaml.

A possibility is to also expand the SDK extension point to provide a CreateModel() operation, where the model returned is a subclass (per language idiomatic constructs) of an abstract extension point (for exporters, samplers, etc)

2024-01-18 13:29 UTC, marcalff commented
Also, please do not let this stall.

2024-01-18 21:26 UTC, marcalff commented
> > There is no way to parse yaml into a memory configuration model, or make up completely a memory configuration model programmatically, and then have the Create() operation take this memory model as input.
> 
> I don't understand. There is a way to do this. The `Create` operation accepts a `configuration` parameter, which is an in memory representation of the configuration model which is either parsed from yaml or created programmatically by some other means. If in the course of interpreting the `configuration` parameter, the `Create` operation comes across a reference to an extension component, it is expected to translate configuration for that component into a generic `properties` representation, and call `Create Plugin` of the respective component provider.
> 

Ok, so it seem we both agree on how it works, based of these clarifications, thanks for the details.

My comment is on the wording then, as some parts are unclear, at least to me.

In the PR, in section `SDK Extension Components`, the description gives some yaml with an extension point, and then jumps directly to talk about what `Create()` does.

I would like some details about what `Parse()` does first, when encountering an SDK extension, such as creating a `Properties` object in the in memory configuration model, that represents the extension configuration bits.

Then, `Create()` takes this `Properties` object and invokes the plugin as described.

Likewise, in the PR text: "When Create is called to interpret a file configuration model", this is a shortcut.

`Parse()` is called to interpret a file configuration model.
What `Create()` is invoked with is an in memory configuration model.

I think this will add clarity, unless I totally missed the picture.

Looking forward to implement this in C++.

2024-01-18 23:36 UTC, ocelotl commented
I think this PR tries to give special treatment to plugins when we could handle them in the same way that we handle the rest of the configuration components.

AFAIK what file configuration does is:

1. Load a schema.
2. Load a configuration file.
3. Check that the configuration file [matches](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/configuration/file-configuration.md?plain=1#L179-L180) the schema.
4. Create the objects using the information from the configuration.

What I think is being proposed here is:

1. Load a schema.
2. Load a configuration file.
3. Check that the configuration file matches the schema.
4. Load plugins which come with their own sub-schema.
5. Load the configurations from the plugin objects.
6. Create the non-plugin objects using the information from the configuration.
7. When a plugin object is created, the plugin object sub-schema is checked and an error is raised if there is a mismatch between the sub-schema and the plugin object configuration.

We could do something different:

1. Load a schema.
2. Load the plugin object subschemas.
3. Add the plugin object subschemas to the right point in the schema to make a new, bigger schema.
4. Load the configuraiton.
5. Load the plugin object configurations.
6. Add the plugin object configurations to the right point in the configuration to make a new, bigger configuration.
7. Check that the new, bigger configuration matches the new, bigger schema.
8. Create the objects using the information from the new, bigger configuration.

The value I see in this is that the approach is general for everything and not particular for plugins. Having create plugin methods would be troublesome for the current Python implementation because there are no particular places where create functions are called, but everything is treated in the same way when the configuration tree is being traversed recursively.

2024-01-18 23:39 UTC, ocelotl requested changes

2024-01-18 23:39 UTC, ocelotl commented on specification/configuration/file-configuration.md
> +Create Plugin SHOULD return an error.
This introduces a new, separate error checking process that is different and additional from the error checking process that was already defined [here](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/configuration/file-configuration.md?plain=1#L176).

2024-01-19 02:38 UTC, jack-berg commented
> 1. Load a schema.
> 2. Load a configuration file.
> 3. Check that the configuration file [matches](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/configuration/file-configuration.md?plain=1#L179-L180) the schema.
> 4. Create the objects using the information from the configuration.

In practice, at least in the java implementation I've been prototyping, there is no loading of a schema. Instead, types are generated statically corresponding to the schema, and the configuration file is parsed to those statically generated types using off the shelf tooling. 

This detail is important because you suggest having each plugin provide its own schema. Presumably they would provide their schemas using JSON schema for symmetry with the rest of the schema. This would necessitate interpreting JSON schemas at runtime. I think this is a bad idea because in my experience, the [implementations of JSON schema](https://json-schema.org/implementations) are all over the map in terms of quality and the JSON schema draft versions they support. I would not want to rely on the java implementations at runtime. 

If you buy that, then we don't have a reliable way for components to describe their schema which the parse operation can consume and conform to. This is what lead me down the path of instead having component providers be responsible for enforcing their schema during the "Create Plugin" operation. 

I think there's not a lot of difference from the users perspective:
- If a component provider describes its own schema, and parse is responsible for enforcing it, then a configuration that fails to conform to the schema triggers an error in parse. But some parts of a schema won't be able to be enforced until create is called anyway - imagine a component provider with an endpoint argument with a string type. Parse would be able to reject configurations which set the endpoint to a number, but you probably can't tell that a string endpoint is invalid until create plugin is called and tries to parse the string as a URL.
- If a component provider enforces its schema only during create plugin, then certain simple schema violations make it paste the parse operation, but trigger failures during create.

Most users will combine parse and create in a single operation, so they'll see an error in either case.

An additional argument is that requiring components to describe their schema in some syntax like JSON schema increases the threshold for writing one of these things. Its comparatively simpler to have a contract in which a component provider implementation is just expected to read config out of a generic properties container, and either succeed in returning a component or error.

2024-01-19 23:12 UTC, jack-berg commented
> If we don't have a reliable way of validating the schema, then what? Should we write our own JSON schema validator? (I really hope not)

The java implementation I've been working on generates static types from the JSON schema. There is no JSON schema artifact present at runtime. At runtime, we use a generic YAML parsing library to parse the incoming YAML to the statically generated types. If the YAML does not conform to the structure of the statically generated types, the binding to the static types will fail. 

> Do these 2 sentences above mean that it is possible for a plugin schema to be defined in a way that is not a JSON schema?

I'm imagining that a plugin expresses its schema by way of examples, and possibly in docs and internally using JSON schema, but it doesn't need to provide its schema to the implementation of file configuration at all as a part of being a Component Provider implementation. The component provider reads configuration from the `properties` file. If all the configuration it needs is present and passes any internal validation performed by the component provider passes, then you can say that the `properties` argument conformed to the schema. If a piece of required configuration is missing, or some internal validation fails, then the `properties` argument did not conform to its schema.

I suppose I would be open to adding an optional component provider operation where a particular implementation (like python) could require components providers to describe their schema in JSON schema format, but I think its important that this is not required across all implementations: OpenTelemetry implementations are low level libraries and should generally be extremely discerning about taking dependencies on external libraries. Its entirely reasonable that for a given language, there is not a ubiquitous JSON schema implementation available which supports the 2020-12 draft version [we've been using](https://github.com/open-telemetry/opentelemetry-configuration/blob/main/schema/opentelemetry_configuration.json#L3C47-L3C54). I think its critical that we don't force these languages to build json schema parsers. 

> It seems like once a configuration file is checked against the JSOM schema (and passes the checking) there can be additional checks (like checking a string is a proper URL). I was under the impression that the only checking that the configuration component was supposed to do was the checking against the JSON schema. Maybe there is a motivation to catch errors as soon as possible, but now I don't see a clearly defined set of responsibilities for the configuration component. SDK components do checking of input values too so who's supposed to do the checking now?

I was referring to the checks being done by the SDK components themselves. I don't think that the create operation needs to perform additional validation beyond those done by SDK components. My point was just that just because a piece of YAML conforms to the schema doesn't mean that we'll be able to generate configured SDK components without error.

2024-01-23 17:54 UTC, dashpole approved these changes
non-blocking comments

2024-01-23 17:54 UTC, dashpole commented on specification/configuration/file-configuration.md
> +The SDK supports a variety
```suggestion
The SDK supports a variety of
```

2024-01-23 17:54 UTC, dashpole commented on specification/configuration/file-configuration.md
> +* `type` - The type of plugin interface it provides (e.g. SpanExporter, Sampler,
Is this meant to be a string, or something else (like a reference to the SpanExporter/etc. interface)?

2024-01-23 21:07 UTC, ocelotl commented on specification/configuration/file-configuration.md
> +Create Plugin SHOULD return an error.
@jack-berg you can mark this conversation as resolved, please.

2024-01-23 22:57 UTC, jack-berg commented on specification/configuration/file-configuration.md
> +* `type` - The type of plugin interface it provides (e.g. SpanExporter, Sampler,
I think it will vary by language and should be whatever is idiomatic. For example in java we already SPIs for this purpose, like [ConfigurableSpanExporterProvider](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/autoconfigure-spi/src/main/java/io/opentelemetry/sdk/autoconfigure/spi/traces/ConfigurableSpanExporterProvider.java). We would say that any implementation of `ConfigurableSpanExporterProvider` is registered to provide `SpanExporter`s with the name identified by the `getName()` method. 

We might have designed it differently with a centralized registration mechanism where component providers could register themselves, but this wouldn't be idiomatic for the java ecosystem. We'd essentially be re-building the SPI mechanism.

But it could be a type literal (i.e. `Class<?>` in java speak), or a enum, etc. I think its important to be open ended here because its a concept that will vary greatly by language.

2024-01-24 15:16 UTC, dashpole commented on specification/configuration/file-configuration.md
> +* `type` - The type of plugin interface it provides (e.g. SpanExporter, Sampler,
Sounds good, thanks.

2024-01-25 16:39 UTC, jack-berg commented
> Now, for the Python implementation, I'm not sure how mandatory is to have Create Plugin or Component Provider. This doesn't fit our implementation where we don't have a function for the creation of any specific component but for every leaf in the schema tree. Can the way the component for plugins is created be left to the way that fits each language best?

What did you have in mind? This concept will definitely vary in implementation by language and I want to be sure that the language is specific enough to make it the intent clear (i.e. I don't want implementers to come away thinking this is impossible because there's no detail), but open enough to give implementers flexibility.

2024-01-25 17:45 UTC, ocelotl commented
Apparently I did something wrong while adding a comment yesterday so here I go again.

The Python prototype now supports SDK extension components.

> The java implementation I've been working on generates static types from the JSON schema. There is no JSON schema artifact present at runtime. At runtime, we use a generic YAML parsing library to parse the incoming YAML to the statically generated types. If the YAML does not conform to the structure of the statically generated types, the binding to the static types will fail.

The Python prototype uses a [JSON schema checker](https://github.com/open-telemetry/opentelemetry-python/blob/4b448cee15698df3afa6fd87dc3e731d16e94e31/_file_configuration/src/opentelemetry/file_configuration/_internal/__init__.py#L225) to check the configuration file. If it does not match, it will raise an exception.

> I'm imagining that a plugin expresses its schema by way of examples, and possibly in docs and internally using JSON schema, but it doesn't need to provide its schema to the implementation of file configuration at all as a part of being a Component Provider implementation.

the Python prototype doees [merge the subschema](https://github.com/open-telemetry/opentelemetry-python/blob/4b448cee15698df3afa6fd87dc3e731d16e94e31/_file_configuration/src/opentelemetry/file_configuration/_internal/__init__.py#L162) of the plugin into the larger OTel schema.

The component provider reads configuration from the `properties` file. If all the configuration it needs is present and passes any internal validation performed by the component provider passes, then you can say that the `properties` argument conformed to the schema.

> I suppose I would be open to adding an optional component provider operation where a particular implementation (like python) could require components providers to describe their schema in JSON schema format...

The Python prototye does not have a `properties` file. Each plugin specifies its schema with a dictionary that is equivalent to a JSON schema. This dictionary is then merged into the larger OTel schema and the resulting bigger schema is used to validate the configuration file. Here is an [example](https://github.com/open-telemetry/opentelemetry-python/blob/4b448cee15698df3afa6fd87dc3e731d16e94e31/_file_configuration/src/opentelemetry/file_configuration/_internal/__init__.py#L130-L139) of how this subschema is defined. Each plugin defines also a [path](https://github.com/open-telemetry/opentelemetry-python/blob/4b448cee15698df3afa6fd87dc3e731d16e94e31/_file_configuration/src/opentelemetry/file_configuration/_internal/__init__.py#L146-L152) that defines where in the larger OTel schema this subschema is to be added.

> I was referring to the checks being done by the SDK components themselves. I don't think that the create operation needs to perform additional validation beyond those done by SDK components. My point was just that just because a piece of YAML conforms to the schema doesn't mean that we'll be able to generate configured SDK components without error.

I agree, I intentionally am not adding any other check to the file configuration component that is not JSON schema checking.

2024-01-25 17:50 UTC, ocelotl commented
> @ocelotl What did you have in mind? This concept will definitely vary in implementation by language and I want to be sure that the language is specific enough to make it the intent clear (i.e. I don't want implementers to come away thinking this is impossible because there's no detail), but open enough to give implementers flexibility.

The Python prototype is using standard [entry points](https://packaging.python.org/en/latest/specifications/entry-points/) which is the normal Python mechanism to dynamically add some external component to a Python project. In this [example](https://github.com/open-telemetry/opentelemetry-python/blob/4b448cee15698df3afa6fd87dc3e731d16e94e31/_file_configuration/src/opentelemetry/file_configuration/_internal/__init__.py#L124-L159) I created a plugin that adds a [sampler that only samples on Mondays but only sometimes](https://github.com/open-telemetry/opentelemetry-python/blob/4b448cee15698df3afa6fd87dc3e731d16e94e31/_file_configuration/src/opentelemetry/file_configuration/_internal/__init__.py#L99-L121). This sampler is an example of a custom component any user may define and add for it to work with OpenTelemetry. We don't have any "Create Plugin"  or "Component Provider" per se, but we do have the plugin class `SometimesMondaysOnSamplerPlugin` which "adds" or "provides" this plugin. Does this fit what this PR is trying to specify?

2024-01-25 23:47 UTC, jack-berg commented
@ocelotl it looks like the implementation is similar. The `schema_path` in your implementation is akin to the `type` in this PR. The `name` in this PR is provided by the `schema` your implementation (i.e. the `sometimes_mondays_on` portion ensures that this plugin is only used when its selected). 

Wondering what kind of changes you envision for this PR such that you feel comfortable with your implementation? My point of view is that as long as the net affect is the same, I don't think it matters much that there is uniformity among languages with this API. Maybe I can adjust the normative language to only include very general "MUSTs", but leave the specifics with "MAY" such that implementations can vary as needed.

2024-01-26 13:27 UTC, marcalff reviewed
LGTM. Thanks for the clarifications on Parse().

2024-01-26 13:27 UTC, marcalff approved these changes

2024-01-26 19:55 UTC, ocelotl commented
> @ocelotl it looks like the implementation is similar. The `schema_path` in your implementation is akin to the `type` in this PR. The `name` in this PR is provided by the `schema` your implementation (i.e. the `sometimes_mondays_on` portion ensures that this plugin is only used when its selected).
> 
> Wondering what kind of changes you envision for this PR such that you feel comfortable with your implementation? My point of view is that as long as the net affect is the same, I don't think it matters much that there is uniformity among languages with this API. Maybe I can adjust the normative language to only include very general "MUSTs", but leave the specifics with "MAY" such that implementations can vary as needed.

Nice :v: I am now under the impression that your intention for things as component providers and such is to define a mechanism that adds components dynamically. I am ok with this PR right now as it is, I would only recommend to add a clarification that says the exact nature of component providers and the create plugin interface depends on the specific mechanisms every language has for this particular purpose. Thank you for the clarification :+1:

2024-01-26 21:02 UTC, jack-berg commented
Will merge Monday 1/29/24 if no further comments.

2024-01-29 19:55 UTC, merged