Define OTEL_CONFIG_FILE environment variable
open-telemetry/opentelemetry-specification pull request #3805
Opened 2024-01-05 19:43 UTC by jack-berg

Part of incorporating [OTEP #225](https://github.com/open-telemetry/oteps/pull/225) into the specification.

Resolves #3752.

2024-01-08 10:21 UTC, pyohannes commented on specification/configuration/sdk-environment-variables.md
> +reference in the configuration file
```suggestion
referenced in the configuration file
```

2024-01-08 16:21 UTC, codeboten approved these changes

2024-01-09 11:55 UTC, arminru approved these changes

2024-01-09 11:55 UTC, arminru commented on specification/configuration/sdk-environment-variables.md
> +**Status**: [Stable](../document-status.md) except where otherwise specified
Wouldn't [Mixed](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/document-status.md#mixed) be the best fit in that case?

2024-01-09 11:55 UTC, arminru commented on specification/configuration/sdk-environment-variables.md
> +| OTEL_CONFIG_FILE | The path of the configuration file used to configure the SDK. |         | See below |
```suggestion
| OTEL_CONFIG_FILE | The path of the configuration file used to configure the SDK. If set, the configuration in this file takes precedence over all other SDK configuration environment variables. |         | See below |
```

To make this very clear to all users.

2024-01-09 14:49 UTC, tigrannajaryan commented on specification/configuration/sdk-environment-variables.md
> +**Status**: [Stable](../document-status.md) except where otherwise specified
+1. Seems like explicitly specifying status for each section is clearer.

2024-01-09 15:57 UTC, jack-berg commented on specification/configuration/sdk-environment-variables.md
> +**Status**: [Stable](../document-status.md) except where otherwise specified
A while back I extended the metrics API with the the ability to specify histogram bucket boundary advice in #3216. At that point, the document was completely stable, except for the newly introduced experimental hint API. I [argued](https://github.com/open-telemetry/opentelemetry-specification/pull/3216#discussion_r1131709885) that calling the document "mixed" makes the document seem less stable than it deserves:

> Adjusted this document to be "mixed" status to reflect one new experimental API seems heavy handed.
> Instead, we might consider saying that the document status is "Stable, except where specified". This would allow us to add experimental annotations to only relevant sections. Also, doing so arguably inspires more confidence in the overall stability of the document since the whole thing isn't tainted with the somewhat ominous "mixed" status.

I think this is true in general for documents which are > 50% stable. 

However, we should be consistent so however we land on this, we should update docs with the outcome.

2024-01-11 17:27 UTC, jmacd approved these changes

2024-01-12 16:09 UTC, jack-berg commented
cc @tedsuo and @trask who had comments on #3744 related to this, which I summarized in #3752. There are several approvals on this so its theoretically ready to merge, but want to loop you in in case you missed this PR.

2024-01-22 23:28 UTC, trask commented
> cc @tedsuo and @trask who had comments on #3744 related to this, which I summarized in #3752. There are several approvals on this so its theoretically ready to merge, but want to loop you in in case you missed this PR.

thanks @jack-berg. Yeah, I still have reservations about this as we discussed in this morning's Configuration WG. I added an outline of an alternate proposal on the issue: https://github.com/open-telemetry/opentelemetry-specification/issues/3752#issuecomment-1905004136

2024-01-22 23:46 UTC, jack-berg commented
Thanks for the comment and concrete proposal @trask 🙏

2024-01-23 16:04 UTC, brunobat requested changes
I think there are many questions to clear before we can merge this. Please check this issue: https://github.com/open-telemetry/opentelemetry-java/issues/6170

2024-01-23 16:04 UTC, brunobat commented on specification/configuration/sdk-environment-variables.md
> +MUST be ignored. Ignoring the environment variables is necessary because
If other env. vars. apart from the file are ignored then the file configuration has precedence over all other configuration methods.

2024-01-23 16:04 UTC, brunobat commented on specification/configuration/sdk-environment-variables.md
> +model returned by `Parse` before `Create` is called. For example, a user may
This seems to supperceed the programatic interface concept defined here: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/configuration/sdk-configuration.md

2024-01-23 19:19 UTC, jack-berg commented
See #3840 for an alternative to this which defines merge semantics with the environment variable configuration scheme.

2024-01-25 21:48 UTC, marcalff approved these changes
LGTM.

This solution is better compared to the merge semantics PR in my opinion.

2024-01-30 16:02 UTC, jack-berg commented
Closing this PR, as I now believe that #3850 is the best way to go for the reasons discussed [here](https://github.com/open-telemetry/opentelemetry-specification/issues/3752#issuecomment-1915005820).

The fact of the matter is that users in our industry have come to expect the ability to be able to override configuration with environment variables. #3840 accommodates this expectation, but in a way that is sure to confuse users and annoy maintainers forever. #3850 accommodates expectations of users while maintaining coherence and matching intuition.

2024-01-30 21:20 UTC, closed without merging