Clarify Body representation in Log Bridge API
open-telemetry/opentelemetry-specification pull request #3814
Opened 2024-01-11 09:55 UTC by pellared

I noticed that [the Logs Data Model defines](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/data-model.md#field-body) Body to be [`any`](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/data-model.md#type-any) (not a `string`).

The spec also says:
> First-party Applications SHOULD use a string message.

The spec [here](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/README.md#new-first-party-application-logs) says that the application is First-Party App if it is using Bridge API. Therefore, the spec recommends exposing Body in Bridge API as `string`.

I find that this should be defined in Bridge API spec to make it easier to process.

Additionally, I think that the Bridge API can still accept a structured body (`any`). This would give more flexibility to the Bridge API consumer and also can be helpful when if we would like to pass events (structured logs).

Here is how the languages are currently representing Body in Bridge API:

- [Java](https://github.com/open-telemetry/opentelemetry-java/blob/main/api/all/src/main/java/io/opentelemetry/api/logs/LogRecordBuilder.java) (stable logs): Defines Body as `string`.
- [.NET](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry.Api/Logs/LogRecordData.cs) (stable logs): Defines Body as `string`.
- [C++](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry.Api/Logs/LogRecordData.cs) (stable logs): Defines Body as attribute value and [a map as value is not supported](https://github.com/open-telemetry/opentelemetry-cpp/blob/main/api/include/opentelemetry/common/attribute_value.h).
- [Python](https://github.com/open-telemetry/opentelemetry-python/blob/main/opentelemetry-sdk/src/opentelemetry/sdk/_logs/_internal/__init__.py) (experimental logs): Defines Body as `Any` (in Python sense which means it can be anything).

Related to https://github.com/open-telemetry/opentelemetry-go/pull/4809

## Changes

Clarify Body representation in Log Bridge API as to make interpretation of the specification easier.

2024-01-11 17:25 UTC, reyang approved these changes

2024-01-11 17:34 UTC, djaglowski commented on specification/logs/bridge-api.md
> +  The API MAY support passing Body as a type representing [`any`](./data-model.md#type-any).
Is there a particular logging library which motivates this change?

2024-01-11 17:39 UTC, pellared commented on specification/logs/bridge-api.md
> +  The API MAY support passing Body as a type representing [`any`](./data-model.md#type-any).
I do not understand the question.
The motivation is to clarify how Bridge API can represent Body.
Right now it is not clearly specified.

2024-01-11 17:52 UTC, djaglowski commented on specification/logs/bridge-api.md
> +  The API MAY support passing Body as a type representing [`any`](./data-model.md#type-any).
Since the purpose of the Bridge API is for authoring appenders for logging libraries, I'm wondering if there's any specific examples where the appender author actually needs to pass `any`?

2024-01-11 17:55 UTC, djaglowski commented on specification/logs/bridge-api.md
> +  The API MAY support passing Body as a type representing [`any`](./data-model.md#type-any).
Or even just a specific example which demonstrates why this is preferred in some situations.

I'm asking about this part in particular because I think this is a change of intention, rather than just a clarification.

2024-01-11 17:58 UTC, pellared commented on specification/logs/bridge-api.md
> +  The API MAY support passing Body as a type representing [`any`](./data-model.md#type-any).
I see. I may remove.

> The API MAY support passing Body as a type representing [`any`](./data-model.md#type-any).

This was something that @jack-berg and @tigrannajaryan suggested.

@jack-berg do you have any example in Java were it would be helpful?

2024-01-11 18:01 UTC, trask commented on specification/logs/bridge-api.md
> +  The API MAY support passing Body as a type representing [`any`](./data-model.md#type-any).
we are thinking to map structured logs in Java (log4j and logback) to the body, see https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/9536#issuecomment-1858547126

2024-01-11 18:03 UTC, tigrannajaryan commented on specification/logs/bridge-api.md
> +  The API MAY support passing Body as a type representing [`any`](./data-model.md#type-any).
I think the confusion is coming from the fact that the log data model says "First-party Applications SHOULD use a string message". What exactly is a first-party application? I believe this was added as a recommendation for greenfield developments that use Otel, telling them to put a string in the Body and use Attributes for anything that needs more structure.

The question is: should this be just a recommendation (as indicated by SHOULD clause) or should it be an actual limitation/enforcement of the Bridge API? Should it even be possible to create a structured Body using Bridge API?

My opinion is that it should be possible even if not needed right now by any logging library that calls the Bridge API. In the future the Bridge API may be used for example by Events API implementation, which according to our current understanding will need structured Body.

2024-01-11 18:04 UTC, tigrannajaryan commented on specification/logs/bridge-api.md
> +  The API MAY support passing Body as a type representing [`any`](./data-model.md#type-any).
> we are thinking to map structured logs in Java (log4j and logback) to the body, see [open-telemetry/opentelemetry-java-instrumentation#9536 (comment)](https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/9536#issuecomment-1858547126)

Thanks @trask. So, looks like there is actually a use-case for structured Body even for logging libraries.

2024-01-11 18:06 UTC, djaglowski commented on specification/logs/bridge-api.md
> +  The API MAY support passing Body as a type representing [`any`](./data-model.md#type-any).
Thanks for clarifying @tigrannajaryan, @trask. The rationale makes sense to me.

2024-01-11 18:07 UTC, djaglowski approved these changes

2024-01-11 18:25 UTC, tigrannajaryan requested changes

2024-01-11 18:25 UTC, tigrannajaryan commented on specification/logs/bridge-api.md
> +  The API MAY support passing Body as a type representing [`any`](./data-model.md#type-any).
This is a Stable document and we are not allowed breaking changes.

I think is a breaking change. It is not a choice to support `any` type. The reference to (also Stable) log data model clearly defines the type of Body and it is `any`, not a string.

I would like to hear arguments in favour of somehow considering this as an allowed change. Blocking until then.

2024-01-11 18:50 UTC, pellared commented on specification/logs/bridge-api.md
> +  The API MAY support passing Body as a type representing [`any`](./data-model.md#type-any).
There is no place in the specification that enforces the Bridge API to support the `any` type. 

From the PR description:

I noticed that [the Logs Data Model defines](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/data-model.md#field-body) Body to be [any](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/data-model.md#type-any) (not a string).

However, the spec in the same section later says:

First-party Applications SHOULD use a string message.

The spec [here](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/README.md#new-first-party-application-logs) says that the application is First-Party App if it is using Bridge API. Therefore, the spec recommends passing Body via Bridge API as string.

2024-01-11 19:01 UTC, pellared commented on specification/logs/bridge-api.md
> +  The API MAY support passing Body as a type representing [`any`](./data-model.md#type-any).
So far when working on [OTel Go Logs Bridge API prototype](https://github.com/open-telemetry/opentelemetry-go/pull/4725) I have not found any popular Go logging library when anything other than string would be needed.

This is also supported by:https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/data-model-appendix.md which allays suggests putting the log message as Body.

2024-01-11 19:14 UTC, pellared commented on specification/logs/bridge-api.md
> +  The API MAY support passing Body as a type representing [`any`](./data-model.md#type-any).
> First-party Applications SHOULD use a string message.

Why the Data Model even references "First-party Application" and uses normative language? It suggests that the API or SDK author should do something with information. How would someone reviewing the API+SDK conforms with this statement?

We could change to:

```suggestion
  The API MUST support passing Body as a type representing [`any`](./data-model.md#type-any).
```

But I am not sure if others would agree with such interpretation. I would rather do it as a separate PR as I think it is more controversial (based on how Java and .NET implemented Bridge API and that so far I see no need for it to support most Go logging libraries).

2024-01-11 22:38 UTC, lalitb commented on specification/logs/bridge-api.md
> +  The API MAY support passing Body as a type representing [`any`](./data-model.md#type-any).
> Right now there is no Bridge API that accepts Body as a type representing any defined in Logs Data Model.

As I understand, both [otel-rust](https://github.com/open-telemetry/opentelemetry-rust/blob/ff64e214064df438a09a5c1695ec73866925f981/opentelemetry/src/logs/record.rs#L27) and [otel-cpp ](https://github.com/open-telemetry/opentelemetry-cpp/blob/c4f39f2be8109fd1a3e047677c09cf47954b92db/api/include/opentelemetry/logs/log_record.h#L55) accept Body as a type representing `any` as per the Log Data Model. And otel-cpp logs signal is already stable.

2024-01-11 22:53 UTC, pellared commented on specification/logs/bridge-api.md
> +  The API MAY support passing Body as a type representing [`any`](./data-model.md#type-any).
Both may be interpreter as not compliant. Rust accepts anything (too broad). C++ does not accept "nested" values (too limited).

2024-01-12 20:37 UTC, lalitb approved these changes

2024-01-12 20:50 UTC, tigrannajaryan requested changes
@pellared  Did you dismiss my request to change? Please don't do that. I am going to block again until we have a resolution.

2024-01-12 20:53 UTC, tigrannajaryan commented
I would like other @open-telemetry/specs-approvers to assess this change and help interpret our spec stability guarantees. Do you think this change is inline with our "Stable" document promises?

2024-01-12 21:06 UTC, pellared commented
> @pellared Did you dismiss my request to change? Please don't do that. I am going to block again until we have a resolution.

Nope. I just did the following after adding some comments:

> [pellared](https://github.com/pellared) requested a review from [tigrannajaryan](https://github.com/tigrannajaryan) [yesterday](https://github.com/open-telemetry/opentelemetry-specification/pull/3814#event-11460474200)

The "requesting changes" is still there only the "icon" changes (the UI is misleading but the PR is still blocked from being merged).

I am not in a rush and  I do not insist on any concrete way to solve it. My main intention is to clarify the specification as I find currently misleading. 

We can e.g. also consider removing the following fragment which I find useless and only bringing confusion:

> First-party Applications SHOULD use a string message.
However, a structured body SHOULD be used to preserve the semantics of structured logs emitted by Third-party
Applications.
Can vary for each occurrence of the event coming from the same
source.

I plan to join next Specification SIG meeting to discuss it.

2024-01-16 11:52 UTC, pellared commented on specification/logs/bridge-api.md
> +  The API MAY support passing Body as a type representing [`any`](./data-model.md#type-any).
I created https://github.com/open-telemetry/opentelemetry-specification/pull/3827

2024-01-16 18:24 UTC, pellared commented
Superseded by https://github.com/open-telemetry/opentelemetry-specification/pull/3827

2024-01-25 07:30 UTC, closed without merging