Context propagation to client instrumentation
open-telemetry/opentelemetry-specification pull request #3825
Opened 2024-01-15 13:26 UTC by jpkrohling

## Changes

This spec change adds the notion of Client Propagators, needed for the use-cases described at #3811. It's not clear to me whether this change warrants an OTEP, and I'll gladly create one if needed. Once there's agreement about the feature, I'll prototype this change and update this PR to include the links to them.

* [x] Related issues #3811
* [ ] Related [OTEP(s)](https://github.com/open-telemetry/oteps): none
* [ ] Links to the prototypes (when adding or changing features): none yet
* [x] [`CHANGELOG.md`](https://github.com/open-telemetry/opentelemetry-specification/blob/main/CHANGELOG.md) file updated for non-trivial changes
* [x] [`spec-compliance-matrix.md`](https://github.com/open-telemetry/opentelemetry-specification/blob/main/spec-compliance-matrix.md) updated if necessary

Signed-off-by: Juraci Paixão Kröhling <juraci@kroehling.de>

2024-01-15 13:28 UTC, jpkrohling commented
cc @cedricziel, @pyohannes

2024-01-15 13:51 UTC, pyohannes commented on specification/context/api-propagators.md
> +when propagating the context back to the caller.
It's not SDKs who call propagators, but this is done by instrumentation libraries.

2024-01-15 16:55 UTC, yurishkuro commented on specification/context/api-propagators.md
> +near-future are W3C TraceContext's `traceresponse`.
```suggestion
near-future is W3C TraceContext's `traceresponse`.
```

2024-01-16 05:20 UTC, bogdandrutu commented on specification/configuration/sdk-environment-variables.md
> +| OTEL_CLIENT_PROPAGATORS  | Client propagators to be used as a comma-separated list                                                       |
Not sure if "client_propagator" is the right name, maybe "response_propagator" makes more sense, and will have a better chance to be align with "traceresponse"?

2024-01-16 05:20 UTC, bogdandrutu commented on specification/context/api-propagators.md
> +sends trace context back to the caller.
Are not both optional conceptually?

2024-01-16 05:20 UTC, bogdandrutu commented on specification/context/api-propagators.md
> +NOT call `Propagator`s when propagating the context back to the caller.
I think the name "response" would also clarify a bit this as well.

2024-01-16 05:20 UTC, bogdandrutu commented on specification/context/api-propagators.md
> +internet.
What do you mean by "Platforms" here? I like the idea that customer should enable this by default, but I want you to think of a very classic example that I don't know what the default behavior should be (Cloud providers LBs). I want to make sure we have somewhere explain how that can work, one of my idea before was that you have this Web Client -> Cloud LB -> Backend and you mostly want to make the "decision" (trace_id, sampling, etc.) in the Backend.

This may be an appendix or something, but I would like to have it as an example of how this would help with that.

2024-01-16 08:48 UTC, jpkrohling commented on specification/context/api-propagators.md
> +internet.
This is in relation to the previous paragraph, where ASP.NET was mentioned. The idea is that we shouldn't enable this by default like we do for W3C TraceContext. Allowing it via env vars, or via custom SDKs (like "golden libraries" often used by end-users) would still be allowed to add this if they want though. Does the reasoning make sense? If so, I'll rewrite the paragraph to make it clearer.

2024-01-16 08:50 UTC, jpkrohling commented
> It is effectively a one-hop mechanism

Good call, I think it was implied in one of the paragraphs, but explicit is better than implicit. I'm careful here to not prescribe too much, leaving room for the concrete implementations. I could add one example using Server-Timing, making sure to note that it's not an example that might end up in an implementation (given how things can still move on the W3C TraceContext spec).

2024-01-16 08:52 UTC, jpkrohling commented on specification/context/api-propagators.md
> +sends trace context back to the caller.
You got me: shouldn't SDKs implement the propagator API? I marked this as optional because this document is marked as "Stable, Feature freeze". As such, we shouldn't be adding new features, right? Adding as optional would still make implementations 100% compliant.

2024-01-16 08:53 UTC, jpkrohling commented on specification/configuration/sdk-environment-variables.md
> +| OTEL_CLIENT_PROPAGATORS  | Client propagators to be used as a comma-separated list                                                       |
Response implies a request/response pattern, which might not always be the case in messaging use-cases. Granted, "client propagator" is 100% targeted at this time towards HTTP/gRPC, but given that the rest of the spec is protocol agnostic, I thought we could use a more generic name here as well.

2024-01-16 08:55 UTC, jpkrohling commented
Of the suggested names, I think I prefer `BackwardsPropagator` the most. I'm just not sure whether it should be "backward" or "backwards"; perhaps a native speaker can help us here?

2024-01-16 09:25 UTC, pyohannes commented on specification/context/api-propagators.md
> +sends trace context back to the caller.
Although it might be a bit more cumbersome, I'd recommend adding specification around the client propagators in separate sections and mark those as "experimental". This would allow to apply iterative (breaking) changes before calling it stable.

When merging it as "stable" right away, you wouldn't technically be allowed to change it anymore.

2024-01-16 09:25 UTC, pyohannes commented on specification/context/api-propagators.md
> +the same trace conterxt it got from the initial document headers. This trace
```suggestion
the same trace context it got from the initial document headers. This trace
```

2024-01-16 09:25 UTC, pyohannes commented on specification/configuration/sdk-environment-variables.md
> +| OTEL_CLIENT_PROPAGATORS  | Client propagators to be used as a comma-separated list                                                       |
But doesn't backward propagation require a request/response pattern?

I don't immediately see applications for backwards propagation in messaging use-cases. Granted, some messages could be interpreted as "going back to the caller", however, that's a semantic nuance that can't be known by instrumentations most of the time.

Do you have any example in mind where backwards propagation could be used that doesn't involve a request/response pattern?

2024-01-16 09:28 UTC, pyohannes commented
> It is effectively a one-hop mechanism, since it is not possible to implement a multi-hop "backtrace" solution (e.g. sampling on errors) given the existing Context APIs.

@yurishkuro Would backpropagation im combination with [deferred sampling](https://github.com/w3c/trace-context/blob/main/spec/30-processing-model.md#load-balancer-deferred-sampling) qualify as a multi-hop solution, or do you have something else in mind?

With deferred sampling in place and the client changing its sampling decision based on back-propagated context, sampling decisions can eventually be back-propagated through multiple hops.

2024-01-16 09:46 UTC, jpkrohling commented on specification/configuration/sdk-environment-variables.md
> +| OTEL_CLIENT_PROPAGATORS  | Client propagators to be used as a comma-separated list                                                       |
I had a messaging use case (kafka), but you are right that, in the end, it's a response, even if it's a message in response to another message.

2024-01-16 14:37 UTC, jsuereth reviewed
This specification change needs stability markers (and clearly outline new sections from existing stable sections).

Additionally, I'd like to see a prototype implementation somewhere in any SDK language (branch/fork is fine) before approving.

2024-01-16 14:37 UTC, jsuereth commented on specification/context/api-propagators.md
> +* `ClientPropagator` (optional), a newer specialization of `Propagator`, which
I don't want to open the bikeshedding, but I really don't like the name `ClientPropagator`.


Some thoughts:

- `BackPropagator`
- `ReturnPropagator`
- `ResponsePropagator`

2024-01-16 14:37 UTC, jsuereth commented on specification/context/api-propagators.md
> +At the moment, no `ClientPropagator`s are available. A candidate for the
Do we have a prototype implementation of this?  Given history of our specification, I'm not a fan of adding specification prior to implementations.  Just a link to a working prototype branch would be enough, but additionally, I think it'd be ok for *experimental* specification to point at the experimental specification of w3c `traceresponse`.

Specifically -

- Can you update this to be marked Experimental (not stable)
- I'd also leave the specification calling out w3c `traceresponse` as a requirement (since both specs are in-progress).

2024-01-16 20:46 UTC, scheler requested changes

2024-01-16 20:46 UTC, scheler commented on specification/overview.md
> +concern values such as `Span`s (usually only the `SpanContext` portion) and
For completeness sake this PR should include any changes to the Trace spec as well. The Trace API uses the spanid from the propagated context as the parent of the span created further or create a root span when there is no context propagated. When a Client propagator is configured, what is the expected behavior for what used to be a root span previously?

2024-01-16 20:46 UTC, scheler commented on specification/context/api-propagators.md
> +
This last line should be included in the Trace spec as well. Specifically, the spec should define the behaviour of Trace API in the presence of a client/reverse propagator and also provide guidance as to when the context can be used as the parent of the new span.

2024-01-16 20:56 UTC, yurishkuro commented
> Of the suggested names, I think I prefer BackwardsPropagator the most. 

I would rather go for ResponsePropagator, to emphasize one-hop, not a transitive backwards prop.

2024-01-16 22:28 UTC, yurishkuro commented
> @yurishkuro Would back propagation in combination with [deferred sampling](https://github.com/w3c/trace-context/blob/main/spec/30-processing-model.md#load-balancer-deferred-sampling) qualify as a multi-hop solution, or do you have something else in mind?

@pyohannes yes, in theory, but there is no specification how that would work.

2024-01-17 13:24 UTC, jpkrohling commented on specification/context/api-propagators.md
> +At the moment, no `ClientPropagator`s are available. A candidate for the
Sort of. [We have this for PHP](https://github.com/open-telemetry/opentelemetry-php-contrib/pull/213), which triggered this spec change proposal when I realized that we must differentiate between forward and backward propagators. 

But given that the feedback on this has been mostly positive, I'll work on a prototype more aligned with this proposal.

2024-01-17 13:32 UTC, pyohannes commented on specification/context/api-propagators.md
> +* `ClientPropagator` (optional), a newer specialization of `Propagator`, which
I'd prefer the name `ResponsePropagator`, because (1) it aligns with the `traceresponse` header, and (2) it implies using a request/response protocol.

2024-01-23 13:08 UTC, jpkrohling commented on specification/context/api-propagators.md
> +* `ClientPropagator` (optional), a newer specialization of `Propagator`, which
ResponsePropagator it is!

2024-01-23 13:09 UTC, jpkrohling commented on specification/context/api-propagators.md
> +the same trace conterxt it got from the initial document headers. This trace
good catch, thank you!

2024-01-23 13:44 UTC, jpkrohling commented on specification/context/api-propagators.md
> +sends trace context back to the caller.
Can you please take a look and see if the "experimental" markings are enough? I left references to the response propagator in other places, as I really believe it has to mentioned on those places. Should I mark those places as "mixed"? In this specific location, I replaced "optional" with "experimental". The next session is covering the response propagator in details, and clearly marked as experimental, so, I think this might be sufficient, but let me know if you think otherwise, @pyohannes.

2024-01-23 13:45 UTC, jpkrohling commented on specification/context/api-propagators.md
> +
I'll mark this as resolved, and address the trace spec change in the other comment.

2024-01-23 13:47 UTC, jpkrohling commented
@jsuereth: 

> This specification change needs stability markers (and clearly outline new sections from existing stable sections).

Can you please take another look? I added stability markers to the new sections, but I think it's important to mention the new response propagator elsewhere. I marked the propagator as experimental there in one place but not in the overview. If you think it's not enough, let me know: I think the current state should be clear enough to determine what's experimental and what's stable, while still maintaining the readability.

2024-01-23 13:51 UTC, jpkrohling commented
>  I would make the one-hop nature explicit

I added a paragraph about this, let me know if you think it's sufficient: 

> The trace context obtained from response propagators are meant to be consumed
> only by the caller and shouldn't be propagated further back.

2024-01-23 22:30 UTC, yurishkuro reviewed
lgtm

2024-01-23 22:30 UTC, yurishkuro commented on specification/configuration/file-configuration.md
> +* `ClientPropagators`
rename?

2024-01-23 22:30 UTC, yurishkuro commented on specification/context/api-propagators.md
> +## Propagator Classes
I would use "categories" instead of "classes" to avoid confusion with OOP classes.

2024-01-23 22:30 UTC, yurishkuro commented on specification/context/api-propagators.md
> +trace context back to the caller. For instance, when a client has made an
suggest linking to W3C response header

2024-01-23 22:33 UTC, yurishkuro commented on specification/overview.md
> +concern values such as `Span`s (usually only the `SpanContext` portion) and
It is a valid question how a response received from the server is meant to be handled. For example, it cannot be stored in the context as that new context will immediately go out of scope. So while what's described in the PR now is reasonably abstract and stand-alone, it is not actually useful for the stated purposes without additional clarification.

2024-01-24 08:05 UTC, pyohannes commented on specification/context/api-propagators.md
> +sends trace context back to the caller.
This looks good to me.

Just a nit, but I guess we should remove the "Feature-Freeze" from the stability marker at the top?

> **Status**: [Stable, Feature-Freeze](../document-status.md)

2024-01-31 12:54 UTC, jpkrohling commented on specification/overview.md
> +concern values such as `Span`s (usually only the `SpanContext` portion) and
@yurishkuro, I can clarify that from a client perspective, but I'm interested in seeing if you have suggestions for the server-to-server scenario. Or perhaps this first version should exclusively be about client<-server, and not server<-server?

2024-01-31 14:38 UTC, jpkrohling commented on specification/context/api-propagators.md
> +trace context back to the caller. For instance, when a client has made an
I'd like to keep this section here more generic, with W3C TraceContext' `traceresponse` an implementation detail once it's ready. Otherwise, people might get the impression that response propagators should only be implemented once that spec is ready.

2024-01-31 17:35 UTC, trask commented on CHANGELOG.md
> +- Context propagation to client instrumentation.
(maybe)
```suggestion
- Add response propagators.
```

2024-01-31 17:35 UTC, trask commented on specification/configuration/sdk-environment-variables.md
> +| OTEL_RESPONSE_PROPAGATORS| Response propagators to be used as a comma-separated list                                                     |
do we need to mark this as experimental, or is it implicitly experimental since the underlying feature is experimental?

2024-02-01 08:53 UTC, jpkrohling commented on specification/configuration/sdk-environment-variables.md
> +| OTEL_RESPONSE_PROPAGATORS| Response propagators to be used as a comma-separated list                                                     |
Good point: I think it makes sense to create a new table for experimental options. I updated the PR to reflect that.

2024-02-01 15:13 UTC, jpkrohling commented on specification/context/api-propagators.md
> +At the moment, no `ClientPropagator`s are available. A candidate for the
@jsuereth, I scratched a PoC with Go, which could be implemented "as is" with a bit more work on data validation. It's all contained in this commit and it's really simple, but I'd recommend taking a look specifically at the example, as it shows the three places where this is relevant: setting the response propagator implementation to the text map response propagators, regular instrumentation, and the propagator being called by instrumentation libraries:

https://github.com/jpkrohling/opentelemetry-go/commit/c60efdff144f94da195a687ed2c1273c2193a6e5#diff-b10dee5922fceb25e03ff269b2665356209304f11e98d507c6bfdd2314e4b693

2024-02-01 15:16 UTC, jpkrohling commented on specification/context/api-propagators.md
> +internet.
I took another look at this, and I'm not sure how it can be better written when taken in consideration the context set by the previous paragraph. I'm marking this as resolved, but if you have suggestions, I'll gladly take them.

2024-02-01 15:23 UTC, jpkrohling commented on specification/overview.md
> +concern values such as `Span`s (usually only the `SpanContext` portion) and
@scheler, I've been thinking about this, but not sure what to change here. Could you point me to a place where a clarification is needed? For now, I'd just state that a server should NOT use the received context for anything other than adding a span link.

2024-02-01 15:26 UTC, jpkrohling commented
I think this is ready for a final review. I added a small PoC using the Go SDK as base, showing how this could work:

https://github.com/jpkrohling/opentelemetry-go/commit/c60efdff144f94da195a687ed2c1273c2193a6e5#diff-b10dee5922fceb25e03ff269b2665356209304f11e98d507c6bfdd2314e4b693

There's one open question, which I think we can handle as part of a follow-up discussion: what should a client do when there's already a trace context (like in a server<-server response). IMO, the incoming traceresponse should only be used to add a span link, but I'm not sure where this should be specified (if at all).

2024-02-02 04:34 UTC, scheler commented on specification/overview.md
> +concern values such as `Span`s (usually only the `SpanContext` portion) and
> For example, it cannot be stored in the context as that new context will immediately go out of scope.

I think the response propagator is applicable in situations where the caller doesn't have a context and the callee has started a trace. The Trace API can perhaps say that when it creates a root span it has an option to use a response propagator to propagate the context downstream. Not exactly sure where this can go, [span creation](https://github.com/open-telemetry/opentelemetry-specification/tree/main/specification/trace#span-creation) is one possibility.

Since we are considering this as a one-hop mechanism, I believe this means the downstream can create only one Context and make use ot it, without needing to propagate it further.

For the server<-server too, the response propagator aids linking of spans across trusted boundaries. When an upstream service outside the trusted boundary decides to start a new trace ignoring the incoming context if any, it has an option to respond back its context for the purpose of linking. [Ref](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/overview.md#links-between-spans).

2024-02-02 08:40 UTC, jpkrohling commented on specification/overview.md
> +concern values such as `Span`s (usually only the `SpanContext` portion) and
> For the server<-server too, the response propagator aids linking of spans across trusted boundaries

Do you mean like applications making calls to a SaaS, and the SaaS returns what's the trace ID for that request on their side?

2024-02-02 15:15 UTC, scheler commented on specification/overview.md
> +concern values such as `Span`s (usually only the `SpanContext` portion) and
Yes

2024-02-02 16:08 UTC, yurishkuro commented on specification/overview.md
> +concern values such as `Span`s (usually only the `SpanContext` portion) and
I personally would like to see a prototype. I do not see a working solution in this proposal, only a piece of it, the physical propagation of context upwards, but not how it can be used in the client, in which layers.

2024-02-02 16:38 UTC, scheler commented on specification/overview.md
> +concern values such as `Span`s (usually only the `SpanContext` portion) and
@jpkrohling  I'm okay with keeping the usage of the response propagator in a separate PR but it's up to the approvers.

2024-02-13 10:15 UTC, jpkrohling commented
@jsuereth, @trask, @yurishkuro and @pyohannes, could you please review this one again?

2024-02-13 18:29 UTC, trask commented on specification/configuration/sdk-environment-variables.md
> +| OTEL_RESPONSE_PROPAGATORS| Response propagators to be used as a comma-separated list                                                     |
it's not clear to me if this is ok given the env var moratorium? https://github.com/open-telemetry/opentelemetry-specification/issues/2891#issuecomment-1289241503

2024-02-15 15:29 UTC, jsuereth commented on specification/context/api-propagators.md
> +At the moment, no `ClientPropagator`s are available. A candidate for the
Thanks for adding this!!

Can you add this to the PR description?

2024-02-15 15:31 UTC, jsuereth commented on specification/context/api-propagators.md
> +the same trace context it got from the initial document headers. This trace
I'm not sure I understand this example.  Would you be able to add a diagram to expand this?

2024-02-15 15:33 UTC, jsuereth commented on specification/context/api-propagators.md
> +Platforms MUST NOT pre-configure `ResponsePropagator`s, those should be explicitly
Is the term `Platform` defined here?

I'd stick to terms we use here: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/glossary.md

2024-02-15 15:34 UTC, jsuereth commented on specification/context/api-propagators.md
> +near-future is W3C TraceContext's `traceresponse`.
Since this is still experimental specification, why not just use w3c traceresponse as our prototype impl?

2024-02-15 15:35 UTC, jsuereth commented on specification/context/api-propagators.md
> +**Status**: [Stable](../document-status.md)
This should be Mixed

2024-02-15 20:18 UTC, yurishkuro commented on specification/context/api-propagators.md
> +the same trace context it got from the initial document headers. This trace
this is why I suggested linking to W3C, it has the motivations / examples

2024-02-20 15:40 UTC, gareththackeray commented on specification/context/api-propagators.md
> +near-future is W3C TraceContext's `traceresponse`.
What if any use are you proposing should be made of the "child id" component of the `traceresponse` header?  Is this proposal solely regarding setting the `traceid` of the context?

2024-02-20 16:44 UTC, johnbley commented on specification/context/api-propagators.md
> +At the moment, no `ClientPropagator`s are available. A candidate for the
@jsuereth Also note the discission in https://github.com/open-telemetry/opentelemetry-specification/issues/3811 - particularly that multiple vendors are currently doing the `Server-Timing` version of this in more-or-less the same way, some even going so far as to model it as a "propagator".  For example, Splunk has implemented this in [Java](https://github.com/signalfx/splunk-otel-java/blob/00d7be9a427e5a707e62e319779ecdb974d309ed/custom/src/main/java/com/splunk/opentelemetry/servertiming/ServerTimingHeaderCustomizer.java#L31), [js](https://github.com/signalfx/splunk-otel-js/blob/ee90b71b73415ad4de5561b994e1d551acf23094/src/instrumentations/http.ts#L153), [ruby](https://github.com/signalfx/splunk-otel-ruby/blob/c3323e8a8c76472c05031e91953fd3fdedbf49c0/lib/splunk/otel/common.rb#L16), [python](https://github.com/signalfx/splunk-otel-python/blob/ecec32dc465d51732e0a332caa33bb42c27c6ac6/splunk_otel/propagators.py#L28), [C#/.NET](https://github.com/signalfx/splunk-otel-dotnet/blob/77ad279b15da4c295ef7e77109405bab927fa71b/src/Splunk.OpenTelemetry.AutoInstrumentation/ServerTimingHeader.cs#L25), and [go](https://github.com/signalfx/splunk-otel-go/blob/29298b1be5e427bbc3f3a3e6d1adfa343dee8ebb/instrumentation/net/http/splunkhttp/handler.go#L38), and we are very keen to donate, pool, and standardize this across the otel community.

2024-02-20 16:46 UTC, johnbley commented
This looks great to me!  Thanks so much @jpkrohling for spearheading this!

2024-02-20 16:50 UTC, johnbley commented on specification/context/api-propagators.md
> +near-future is W3C TraceContext's `traceresponse`.
> What if any use are you proposing should be made of the "child id" component of the `traceresponse` header? Is this proposal solely regarding setting the `traceid` of the context?

It's up to the receiver/client instrumentation!  From the spec: `... might be used as a link to/from a new trace, or might be directly reused as the parent of new spans`.  Splunk, for example, has all client-side instrumentation (ios, android, browser) attach the response context (trace and span id) as span links to the client instrumentation's span about the request.

2024-02-20 16:54 UTC, gareththackeray commented on specification/context/api-propagators.md
> +near-future is W3C TraceContext's `traceresponse`.
OK thanks I get it now.  It was throwing me that in `traceresponse` it is called "child id" rather than "parent id". I think it's probably worth spelling that out.

2024-02-22 09:32 UTC, jpkrohling commented on specification/context/api-propagators.md
> +trace context back to the caller. For instance, when a client has made an
I don't think we should wait: having this spec in place and support for Response Propagators allows contrib implementations of this following the current practice around ServerTiming.

2024-02-22 09:37 UTC, jpkrohling commented on specification/context/api-propagators.md
> +the same trace context it got from the initial document headers. This trace
I added the image from https://github.com/open-telemetry/opentelemetry-specification/issues/3811 here. I'm not 100% sure I should crop the image to show only the upper part of it, as the lower part shows why the current situation isn't adequate. What do you all think?

2024-02-22 09:39 UTC, jpkrohling commented on specification/context/api-propagators.md
> +Platforms MUST NOT pre-configure `ResponsePropagator`s, those should be explicitly
I'll open a PR to define it. This term was already part of the document on the paragraph above. The new paragraph is just to make it clear that while platforms are allowed to pre-configure propagators, they should not pre-configure _response_ propagators.

2024-02-22 09:42 UTC, jpkrohling commented on specification/context/api-propagators.md
> +near-future is W3C TraceContext's `traceresponse`.
Mostly because there's another discussion happening there around the name of the header: I'm strongly in favor of using traceresponse as a metric on ServerTiming, while the current version of the spec defines its own header, which would require browser vendors to add this new header to an allow-list before it can be used for our main use-case.

Reference: https://github.com/w3c/trace-context/issues/556

2024-02-22 09:51 UTC, jpkrohling commented on specification/context/api-propagators.md
> +near-future is W3C TraceContext's `traceresponse`.
I'm being careful on this PR to not tie response propagators too much with W3C TraceContext. While I think it's the primary user of this type of propagator, there's already a well-established practice around ServerTiming that we should keep in mind.

2024-02-22 10:11 UTC, jpkrohling commented on specification/context/api-propagators.md
> +Platforms MUST NOT pre-configure `ResponsePropagator`s, those should be explicitly
Opened #3897

2024-02-27 23:43 UTC, trask commented on specification/context/api-propagators.md
> +Platforms MUST NOT pre-configure `ResponsePropagator`s, those should be explicitly
maybe change Platforms to [Instrumentation Libraries](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/glossary.md#instrumentation-library)?

2024-02-28 09:13 UTC, jpkrohling commented on specification/context/api-propagators.md
> +At the moment, no `ClientPropagator`s are available. A candidate for the
Link to the prototype added to the issue's description. I'm marking this as resolved, but let me know if there still open questions.

2024-03-05 14:57 UTC, pyohannes commented on specification/context/api-propagators.md
> +only by the caller and shouldn't be propagated further back.
What about instrumented web servers, load balancers, or proxys between the original caller and the application? I assume those should forward the response context unaltered?

2024-03-05 14:57 UTC, pyohannes commented on specification/context/api-propagators.md
> +For historical reasons, whenever "Propagator" is used, a forward propagator is
```suggestion
For historical reasons, whenever the term "Propagator" is used, a forward propagator is
```

2024-03-05 14:57 UTC, pyohannes commented on specification/context/api-propagators.md
> +* `ResponsePropagator` (experimental), a newer specialization of `Propagator`, which
```suggestion
* `ResponsePropagator` (experimental), a specialization of `Propagator`, which
```

2024-03-05 14:57 UTC, pyohannes commented on specification/context/api-propagators.md
> +**Status**: [Mixed](../document-status.md)
```suggestion
**Status**: [Stable](../document-status.md), except where otherwise specified
```

Maybe better?

2024-03-05 15:50 UTC, johnbley commented on specification/context/api-propagators.md
> +only by the caller and shouldn't be propagated further back.
If they are just passthroughs, then, yes, they should just send along what they got.  If they are actually instrumented and produce spans/affect context propagation themselves, then they can be configured to response-propagate *their own* (root) span context rather than (confusingly) the next tier's.  In other words, if I'm trying to link
```
(A) browser -> (B) proxy/balancer that generates spans -> (C) "actual" server producing responses
```
then the browser in this example should see a response propagation from B containing B's self-generated trace id/root span id, even if (C) sent (B) a response context as well.

2024-03-05 15:59 UTC, pyohannes commented on specification/context/api-propagators.md
> +only by the caller and shouldn't be propagated further back.
> then the browser in this example should see a response propagation from B containing B's self-generated trace id/root span id, even if (C) sent (B) a response context as well.

Then this implies that the client instrumentation using the response header continues the proxy trace (B), and not the "actual" server trace (C)? Is this desired? Also given the fact that likely there's no correlation between the proxy's trace (B) and the server's trace (C) if the server starts a new trace?

2024-03-06 12:48 UTC, jpkrohling commented on specification/context/api-propagators.md
> +only by the caller and shouldn't be propagated further back.
Replacing proxy/load-balancer (B) here with "Istio", and knowing that Istio might start a new trace and that it would show spans from the (C) server, I believe that (A) should receive a traceresponse from (B), even if it feels a bit unintuitive at first. However, if the load-balancer/proxy is creating its telemetry disconnected from the server (C), then the traceresponse for (A) should come from (B).

I'll clarify what I meant on the spec text, but I'll leave out the discussion about load-balancers, as I believe this is an implementation detail.

2024-03-06 14:53 UTC, MrAlias commented on specification/context/api-propagators.md
> +**Status**: [Mixed](../document-status.md)
We already have an established policy of marking documents that contain both stable and experimental sections as [mixed](https://github.com/open-telemetry/opentelemetry-specification/blob/a88b0559b4dcf36b5db85189139ff3f09dbe984d/specification/document-status.md#mixed). This proposed comment would deviate from this. This suggestion should not be included.

2024-03-06 15:53 UTC, pyohannes commented on specification/context/api-propagators.md
> +**Status**: [Mixed](../document-status.md)
I see, I was just proposing the above because it is used in a few other places:
```sh
$ grep -r "except where otherwise" *
specification/trace/api.md:**Status**: [Stable, Feature-freeze](../document-status.md), except where otherwise specified
specification/metrics/sdk.md:**Status**: [Stable](../document-status.md) except where otherwise specified
specification/metrics/api.md:**Status**: [Stable](../document-status.md), except where otherwise specified
```

If we go with "Mixed", wouldn't we need to explicitly mark all stable sections as stable? I proposed the above to avoid that boilerplate.

2024-03-06 17:01 UTC, pyohannes commented on specification/context/api-propagators.md
> +only by the caller and shouldn't be propagated further back.
Thanks for the clarification.

Not being a client instrumentation expert I'm not sure about the relevance of this, and I'm still not sure about all the implications of adding "intermediary" services between clients and web servers. However, that also in previous discussions it was made clear that this is supposed to be a one-hop mechanism, so the spec wording looks good to me.

2024-03-11 16:22 UTC, jpkrohling commented on specification/context/api-propagators.md
> +**Status**: [Mixed](../document-status.md)
I added the missing markers, but had to move a few things around to not mark what's currently stable as experimental (see "Global Propagators").

2024-03-12 15:07 UTC, jack-berg commented on specification/context/api-propagators.md
> +**Status**: [Mixed](../document-status.md)
I prefer "stable, except where otherwise specified"

2024-03-14 13:20 UTC, jpkrohling commented on specification/context/api-propagators.md
> +**Status**: [Mixed](../document-status.md)
I'm fine either way, but I need you to all to come to an agreement on what's the path I should take :-)

2024-03-22 11:48 UTC, johnbley commented
> This PR was marked stale due to lack of activity. It will be closed in 7 days.

Just commenting here to keep this alive.

2024-03-22 14:44 UTC, MrAlias commented on specification/context/api-propagators.md
> +**Status**: [Mixed](../document-status.md)
If we would like to go with "stable, except where otherwise specified" we need to add that to the [documentation](https://github.com/open-telemetry/opentelemetry-specification/blob/a88b0559b4dcf36b5db85189139ff3f09dbe984d/specification/document-status.md). We currently define this as "Mixed". If we would like to use other terms there we need to ratifying it into our policies before adopting.

2024-03-28 18:19 UTC, jmacd reviewed
@jpkrohling I'd like to approve this so that we can move forward and begin to experiment with new response propagators. Before we do so, I think we need to make sure the concerns raised in this review as a whole are well documented, so it's clear that `ResponsePropagator` is introduced as an experiment.

For example, @yurishkuro wrote:
> since it is not possible to implement a multi-hop "backtrace" solution (e.g. sampling on errors) given the existing Context APIs.

@yurishkuro Have you written your thoughts on this in greater depth anywhere?  For "sampling on errors", maybe https://github.com/open-telemetry/opentelemetry-specification/issues/2986 or https://github.com/open-telemetry/opentelemetry-specification/issues/2918.

I'm interested in prototyping for "sample on addlink", and I believe we need a new Sampler `Decision` category to make real progress. I think there are more questions, I wonder if anyone is thinking about "return baggage", or whether there is a whole-trace backward propagation mechanism that anyone has proposed? 

One thing we lost from OpenCensus was a count of child spans in the parent. I wonder if we could record Span Links from a span to its children using information from the response propagator, in order to close this gap? Can we address https://github.com/open-telemetry/opentelemetry-specification/issues/3867, which asks for a way to establish linkage between say a span and its grandchild, when the intermediate span was not sampled.

2024-04-04 08:30 UTC, jpkrohling commented on specification/context/api-propagators.md
> +**Status**: [Mixed](../document-status.md)
Agreed. I'd stay with Mixed for now, but I'm open to changing it in the future once "stable, except where otherwise specified" is properly defined in the documentation.

2024-04-04 08:47 UTC, jpkrohling commented on specification/context/api-propagators.md
> +near-future is W3C TraceContext's `traceresponse`.
I'm resolving this, let me know if there's still something to clarify around this.

2024-04-04 08:47 UTC, jpkrohling commented on specification/context/api-propagators.md
> +near-future is W3C TraceContext's `traceresponse`.
I'm resolving this, let me know if further clarification is needed.

2024-04-04 08:47 UTC, jpkrohling commented on specification/context/api-propagators.md
> +the same trace context it got from the initial document headers. This trace
I'm resolving this, let me know if further clarification is needed.

2024-04-04 08:47 UTC, jpkrohling commented on specification/context/api-propagators.md
> +trace context back to the caller. For instance, when a client has made an
I'm resolving this discussion, let me know if you disagree with the reasoning.

2024-04-04 08:48 UTC, jpkrohling commented on specification/overview.md
> +concern values such as `Span`s (usually only the `SpanContext` portion) and
@yurishkuro, can you confirm you've seen this example? Or did you mean you expect a PoC with a browser-based example? 

https://github.com/jpkrohling/opentelemetry-go/commit/c60efdff144f94da195a687ed2c1273c2193a6e5#diff-b10dee5922fceb25e03ff269b2665356209304f11e98d507c6bfdd2314e4b693

2024-04-04 16:27 UTC, jsuereth commented on specification/context/api-propagators.md
> +Instrumentation Libraries MUST NOT pre-configure `ResponsePropagator`s, those
There's some oddities here.  Today the usage of Propagator is optional, if instrumentation decides it needs some custom/non-standard mechanism of passing context.

For this requirement to hold, you may ALSO need to call out that Instrumentation Lirbaries are NOT ALLOWED to propagate response context *but* through the use of ResponsePropagator.

2024-04-04 16:33 UTC, jsuereth commented
The specification itself is much cleared up and easier to follow.  Thanks for all the fixes and explicit stability markers.

The current prototype only include the propagator itself but not interaction with instrumentation.  I *would* like to see a prototype of this against an HTTP framework via instrumentation, including showcasing some of the configuration portions of the specification (enabling/disabled-by-default).

Basically an end-to-end demo including showing the value of the data itself.

Getting into the specification means expansion into multiple languages and attempting to get users leveraging the feature.  I'm not sure we're there yet (but I'm willing to be overruled here).

2024-04-05 22:07 UTC, jack-berg commented on specification/overview.md
> +concern values such as `Span`s (usually only the `SpanContext` portion) and
> @yurishkuro, I can clarify that from a client perspective

I don't see see any indication or what an SDK or instrumentation should do, or can be configured to do when it encounters receives context encountered backwards. So this seems like something that could be theoretically useful without a practical way to be useful. Without some corresponding spec on what should happen when these are received, its not clear what we gain by standardizing this.

I know this is experimental and would evolve, but would be good to include some sort of hint on how this is expected to evolve. Do we imagine this SDKs or instrumentation or something else to handle these? Presumably the behavior would vary by configured ResponsePropagator on the client side. What might the receiver of W3C `tracesponse` be expected to do?

2024-04-05 22:09 UTC, jack-berg reviewed
Its clear that more work is needed to research this area so that this spec could be iterated on. Is there a project plan and some group of people who are intending on continuing to drive this?

2024-04-11 17:10 UTC, johnbley commented
> Its clear that more work is needed to research this area so that this spec could be iterated on. Is there a project plan and some group of people who are intending on continuing to drive this?

Count me in to that working group, please.

2024-04-12 00:02 UTC, trask commented
the OTel Java agent may be a good place to prototype this as there's already a [hook to add response headers](https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/8421#issuecomment-1536080899) to all of the HTTP server instrumentation (which I believe is already being used by the Splunk distro to do something similar to this PR)

2024-04-19 12:28 UTC, jpkrohling commented
Status update: I'm totally swamped right now, and asked for the Faro Web SDK folks here at Grafana Labs to help me with the PoC (cc @codecapitano). @johnbley , I shared your offer with them as well, I'd love to see some collaboration there :-) 

Since I don't have any new events on my schedule until OTel Community Day, I should be able to clear my queue by the time the PoC gets done.

2024-04-29 22:49 UTC, scheler commented
@jpkrohling Client Instrumentation SIG would be a good place to take this forward. We discussed this topic in the Client SIG with @johnbley a few weeks ago and we realized a couple things - 
1. That the [traceresponse spec](https://w3c.github.io/trace-context/#traceresponse-header) supports only span linking across browser span and server span, and not help with a parent-child relationship.
2. The current [document-load instrumentation](https://github.com/open-telemetry/opentelemetry-js-contrib/tree/main/plugins/web/opentelemetry-instrumentation-document-load#optional-send-a-trace-parent-from-your-server) suggests setting up a parent-child relationship in a single trace by having the server send its span's parent context in a meta tag by name `traceparent`. 

While both have their pros and cons, it would be good to discuss how we want to take this forward.

2024-04-30 08:36 UTC, jpkrohling commented
Based on this latest information, I'm marking this as draft.

2024-05-29 07:07 UTC, codecapitano commented
Small update: 
@jpkrohling handed the task over and we ([@codecapitano](https://github.com/codecapitano, https://github.com/codecapitano, [@cedricziel](https://github.com/cedricziel)) will continue the PoC work.

2024-06-22 03:17 UTC, closed without merging

2025-07-28 00:29 UTC, brettmc commented
Hello! I'm wondering if this will get picked back up? In my SIG (php) somebody is very interested in implementing some custom response propagation. Their investigations show that a couple of SIGs ( [python](https://github.com/open-telemetry/opentelemetry-python-contrib/blob/main/opentelemetry-instrumentation/src/opentelemetry/instrumentation/propagators.py#L42), [ruby](https://github.com/open-telemetry/opentelemetry-ruby-contrib/blob/main/instrumentation/rack/lib/opentelemetry/instrumentation/rack/instrumentation.rb#L30) and [js](https://github.com/open-telemetry/opentelemetry-js/blob/main/experimental/packages/opentelemetry-instrumentation-http/src/types.ts#L74) ) have implemented an experimental response propagator. We'll probably go down the same path and drop an experimental implementation into contrib based on this PR.

Is there any benefit to us implementing in core as a PoC of this PR to help it along? We've already got experimental implementations of server-timing and trace-response, so we're a good candidate to make them all work in a more spec-oriented way.