Define OTEL_CONFIG_FILE with placeholder for new environment variable override scheme
open-telemetry/opentelemetry-specification pull request #3850
Opened 2024-01-30 15:55 UTC by jack-berg

Resolves #3752.

An alternative to #3805 which ignores the existing environment variable scheme, and leaves a placeholder for defining a new environment variable scheme specific to file configuration, with names derived from the configuration model. 

This is the proposal I suggested [here](https://github.com/open-telemetry/opentelemetry-specification/issues/3752#issuecomment-1915005820). To restate the advantages:

- Avoid the messy merge semantics associated with merging the existing environment variable scheme
- Provide environment variable overrides, which users have come to expect
- We can soften the [sharp edges](https://docs.google.com/document/d/1yPfdf6fsxWY7onWU_PLmIIPs14H6pTYbyI7OboiODCw/edit?pli=1#heading=h.r8b09z6u7mwh) associated with a environment variable scheme derived from the model by refactoring the configuration model to be more friendly to the rules (i.e. by avoiding object arrays)

To understand exactly what a refactored configuration model might look like, I've put together https://github.com/open-telemetry/opentelemetry-configuration/pull/69 to review along side of this.

2024-01-30 17:52 UTC, brunobat commented on specification/configuration/sdk-environment-variables.md
> +logger.debug("Effective configuration: \n" + toString(modelWithEnvironment));
Please beware that printing config values can expose passwords and secrets. If there is no way to opt-out specific config values, the values should not be printed at all.

2024-01-30 17:57 UTC, jack-berg commented on specification/configuration/sdk-environment-variables.md
> +logger.debug("Effective configuration: \n" + toString(modelWithEnvironment));
In this example the user is opting out by default, since we use a verbose / non-default log level. The user opts in by configuring their log level to be more verbose. If they happen to use the verbose log level by default, they can opt increasing the threshold log level or turning off logs altogether from the relevant logger. The comment above this line explains this.

2024-01-30 18:17 UTC, brunobat commented on specification/configuration/sdk-environment-variables.md
> +logger.debug("Effective configuration: \n" + toString(modelWithEnvironment));
ok, thanks

2024-01-30 18:39 UTC, trask commented on specification/configuration/sdk-environment-variables.md
> +the [configuration model](./file-configuration.md#configuration-model).
I didn't follow why emit a warning for this?

2024-01-30 18:44 UTC, trask approved these changes
I still have questions around the existing env vars, but I support this PR as a good incremental step forward 👍

2024-01-31 17:39 UTC, jack-berg commented on specification/configuration/sdk-environment-variables.md
> +the [configuration model](./file-configuration.md#configuration-model).
I think its important to draw attention to the fact that the contents of the file don't reflect the configuration of the SDK. I imagine the workflow being something like:
- Include an overriding environment variable
- Receive a warning that the configuration file is different (warning doesn't mean a problem in this context - more like a notification): "Environment variables were set that overrode the configuration specified at /path/to/config.yaml"
- If opted in, log the entire effective configuration after applying overrides so you can deduce what changed

2024-01-31 18:31 UTC, trask commented on specification/configuration/sdk-environment-variables.md
> +the [configuration model](./file-configuration.md#configuration-model).
I'd suggest limiting this to a debug message. It could be worth looking at Spring for prior art.

2024-02-01 16:22 UTC, jack-berg commented on specification/configuration/sdk-environment-variables.md
> +the [configuration model](./file-configuration.md#configuration-model).
> I'd suggest limiting this to a debug message

That's fine. I can relax the language to say "The implementation SHOULD emit a log if calling Merge Environment results in change...". Leave it to implementations to decide the appropriate log level.

2024-02-01 16:27 UTC, MrAlias approved these changes

2024-02-03 22:35 UTC, marcalff requested changes
I would like to make a radical suggestion.

Yes, the configuration is expressed in a config.yaml file, to be consumed by each runtime for each SIG, no change.

Yes, the configuration can be merged with additional environment variables if we really want to. This is a separate discussion, but no change as far as this PR is concerned.

However, now that it is established that this merge operation is independent of the existing environment variables implemented by each SIG SDK, the merge operation becomes SIG agnostic.

Hence, I don't see why the merge should be implemented in each language, in each sdk, and embedded in each runtime.

The proposal is to perform the merge operation in a separate process, and only feed the merged configuration yaml to the opentelemetry sdk.

This as the benefit of:

* only implement merge once, not for each language SIG
* implement the merge as a separate process, and not bloat every runtime
* provide more stability to runtimes

In short, the output of a merge is a final config.yaml, and no merge operation is to occur in memory with the configuration model inside each SDK.

This has another far reaching consequence:

* for extension points, the merge is done up front, in yaml
* the implementation of each extension point (custom exporter, sampler, etc) will not have to implement a merge operation on the custom model either, making things much simpler for people providing extension points.

2024-02-06 07:40 UTC, tedsuo commented
@marcalff unfortunately running a separate process is a non-starter for many end user environments that OpenTelemetry needs to support.

2024-02-06 07:43 UTC, tedsuo approved these changes
I agree that this is the correct approach for moving forwards. Thanks for threading the needle on this one.

2024-02-06 13:54 UTC, marcalff reviewed
Previous suggestion withdrawn - it does not work for all SIG.

The is unfortunate, as a lot of complexity will be pushed to every SIG runtime.

2024-02-06 13:55 UTC, marcalff approved these changes

2024-02-07 11:51 UTC, brunobat requested changes

2024-02-07 11:51 UTC, brunobat commented on specification/configuration/sdk-environment-variables.md
> +| OTEL_CONFIG_FILE | The path of the configuration file used to configure the SDK. If set other environment variables defined in this file are ignored. |         | See below |
>  If set other environment variables defined in this file are ignored.

It needs to be clarified in which file will the environment variables be ignored. The file defined in OTEL_CONFIG_FILE?

2024-03-07 03:15 UTC, closed without merging