Refine description of InstrumentationScope in Logs
open-telemetry/opentelemetry-specification pull request #3855
Opened 2024-01-31 12:15 UTC by pellared

Fixes https://github.com/open-telemetry/opentelemetry-specification/issues/3841

## Changes

2024-01-31 13:28 UTC, pellared commented
@open-telemetry/specs-logs-approvers PTAL

2024-01-31 14:31 UTC, arminru commented on specification/glossary.md
> +  * [Tracer Name / Meter Name / Logger Name](#tracer-name--meter-name--logger-name)
@chalin I can't find any reference to "tracer-name--meter-name" in https://github.com/open-telemetry/opentelemetry.io so I should be safe to assume this won't break any links on the website, right?

2024-01-31 15:39 UTC, chalin commented on specification/glossary.md
> +  * [Tracer Name / Meter Name / Logger Name](#tracer-name--meter-name--logger-name)
Right, the new anchor name won't break anything. The link checker might still complain if there are URL hashes that still refer to the old id. I hope that answers your question.

2024-01-31 16:31 UTC, MrAlias approved these changes

2024-02-01 06:39 UTC, cijothomas approved these changes
LGTM

2024-02-01 18:11 UTC, reyang commented on specification/common/README.md
> +Metrics [data points](../metrics/data-model.md#metric-points),
```suggestion
[Metric points](../metrics/data-model.md#metric-points),
```

2024-02-13 15:41 UTC, jack-berg commented on specification/logs/bridge-api.md
> +  the Logger Name should be recorded as the instrumentation scope name.
This is a bit strange. We use the same language for [get a tracer](Should that be enough without having to provide a SdkTracerProvider#updateTracerConfigProvider too? ) and [get a meter](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/api.md#get-a-meter), and the name of a logger is conceptually the same. The only difference for the bridge API is that it is normally not defined by the user, and is instead another property that is bridged.

How about  we keep the the first part, which describes the type of value we'd typically expect to find in a logger name, drop the bit about instrumentation library and instrumented library "may refer to the same library", and add the special text that logger name should be used if available:

```
* `name`: This name uniquely identifies the [instrumentation scope](../glossary.md#instrumentation-scope),
  such as the [instrumentation library](../glossary.md#instrumentation-library)
  (e.g. `io.opentelemetry.contrib.mongodb`), package, module or class name.
  For log sources which define
  a logger name (e.g. Java [Logger Name](https://docs.oracle.com/javase/7/docs/api/java/util/logging/Logger.html#getLogger(java.lang.String)))
  the Logger Name should be recorded as the instrumentation scope name.
```

2024-02-14 19:51 UTC, pellared commented on specification/logs/bridge-api.md
> +  the Logger Name should be recorded as the instrumentation scope name.
From the PR  description:

> Update the name description in Get a Logger as it was clearly a copy-paste and it does not make sense for a Bridge API. Bridge API is not intended to be used by instrumentation libraries nor directly in application code.

Do you see any use case that an instrumentation library would use the Bridge API? Shouldn't the instrumentation libraires rather use the Event API?

2024-02-15 15:33 UTC, jack-berg commented on specification/logs/bridge-api.md
> +  the Logger Name should be recorded as the instrumentation scope name.
Yes, since as of today, the Event API is built directly on top of logger. [Create EventLogger](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/event-api.md#create-eventlogger) expects a delegate `logger` as an argument.

It seems like this could change in #3878, but it seems likely that the implementation of Event API will delegate to the logs bridge API in some fashion.

2024-02-19 14:14 UTC, pellared commented on specification/logs/bridge-api.md
> +  the Logger Name should be recorded as the instrumentation scope name.
PTAL https://github.com/open-telemetry/opentelemetry-specification/pull/3855/commits/40494cb0cab7d2131a882b14f88a2e5aa55baa73

2024-02-20 21:45 UTC, tigrannajaryan commented on specification/logs/bridge-api.md
> -  name within that library or application.
Do we have this deleted paragraph elsewhere?

2024-02-20 21:52 UTC, pellared commented on specification/logs/bridge-api.md
> -  name within that library or application.
The removal is intentional. Bridge API is not supposed to be used by instrumented/instrumentation libraries. Or am I missing something?

2024-02-27 15:55 UTC, pellared commented on specification/logs/bridge-api.md
> -  name within that library or application.
@tigrannajaryan PTAL

2024-02-27 16:14 UTC, tigrannajaryan requested changes

2024-02-27 16:14 UTC, tigrannajaryan commented on specification/logs/data-model.md
> +they all have the same value of `InstrumentationScope`. This field is required.
>This field is required.

I think this is a breaking change. For externally provided log records the scope may be empty.

Blocking because of this.

2024-03-06 15:14 UTC, carlosalberto commented on specification/logs/bridge-api.md
> -  name within that library or application.
@tigrannajaryan opinion?

2024-03-12 09:33 UTC, pellared commented
@tigrannajaryan PTAL. I addressed your comment.

2024-03-13 07:18 UTC, pellared commented on specification/logs/bridge-api.md
> -  name within that library or application.
I reverted the change. I think it is still possible that an instrumentation library uses a bridge.

2024-03-14 20:28 UTC, tigrannajaryan approved these changes
LGTM

2024-03-15 14:35 UTC, merged