Mark exemplars as stable.
open-telemetry/opentelemetry-specification pull request #3870
Opened 2024-02-08 15:01 UTC by jsuereth

Fixes #3756

Note: This is still draft for two reasons:

1. Would like to get the `ExemplarReservoir` configuration of views in some languages.
2. Would still like to override the specification so, by-default, if Traces are enabled and sampled, then Exemplars are enabled for otel metrics.  See #3756 TODOs.

## Changes

- Marks Exemplar specification as stable.

For non-trivial changes, follow the [change proposal process](https://github.com/open-telemetry/opentelemetry-specification/blob/main/CONTRIBUTING.md#proposing-a-change).

* [X] Related issues #3756
* [X] Related [OTEP(s)](https://github.com/open-telemetry/oteps) [#113](https://github.com/open-telemetry/oteps/pull/113)
* [ ] Links to the prototypes (when adding or changing features)
* [ ] [`CHANGELOG.md`](https://github.com/open-telemetry/opentelemetry-specification/blob/main/CHANGELOG.md) file updated for non-trivial changes
* [X] [`spec-compliance-matrix.md`](https://github.com/open-telemetry/opentelemetry-specification/blob/main/spec-compliance-matrix.md) updated if necessary

2024-02-08 15:13 UTC, jack-berg commented on specification/metrics/sdk.md
> +**Status**: [Stable](../document-status.md)
A while back we talked about how changing the default exemplar reservoir shouldn't be considered a breaking change when exemplars are stable. The context was that we might find a better default for exponential histogram aggregation.

Can you confirm this is your understanding? If so, what do you think about adding a note to the defaults section explaining that they can change without it being breaking because from a data consumer perspective, the result is unchanged (i.e. the exemplar reservoir selection doesn't change the shape of the data exported by an SDK)?

2024-02-08 17:24 UTC, jsuereth commented on specification/metrics/sdk.md
> +**Status**: [Stable](../document-status.md)
We did discuss this.  

I was under the impression this would be implicitly obvious from other aspects of the specification, but reading through the details I don't think it is.

We should add a section denoting preserving Exemplars is "best-effort" and changing defaults is non-breaking.

Can you add that as a task to https://github.com/open-telemetry/opentelemetry-specification/issues/3756?

I wasn't planning on changing this PR from draft until after all aspects of that issue are completed.

2024-02-08 17:44 UTC, jack-berg commented on specification/metrics/sdk.md
> +**Status**: [Stable](../document-status.md)
Added. Will close this conversation for now as its being tracked.

2024-02-09 00:21 UTC, cijothomas commented
Are we in need of the usual 3 languages implemented before calling this stable? The spec matrix shows only Java, though .NET has most of the implementation (in preview). I can send an update to spec matrix to reflect .NET's status.

2024-02-14 03:52 UTC, reyang commented
> Are we in need of the usual 3 languages implemented before calling this stable? The spec matrix shows only Java, though .NET has most of the implementation (in preview). I can send an update to spec matrix to reflect .NET's status.

* Swift https://github.com/open-telemetry/opentelemetry-swift/tree/main/Sources/OpenTelemetrySdk/Metrics/Stable/Exemplar
* PHP https://github.com/open-telemetry/opentelemetry-php/tree/main/src/SDK/Metrics/Exemplar
* JavaScript https://github.com/open-telemetry/opentelemetry-js/blob/main/packages/sdk-metrics/src/exemplar/index.ts

2024-02-14 17:13 UTC, cijothomas commented
> > Are we in need of the usual 3 languages implemented before calling this stable? The spec matrix shows only Java, though .NET has most of the implementation (in preview). I can send an update to spec matrix to reflect .NET's status.
> 
> * Swift https://github.com/open-telemetry/opentelemetry-swift/tree/main/Sources/OpenTelemetrySdk/Metrics/Stable/Exemplar
> * PHP https://github.com/open-telemetry/opentelemetry-php/tree/main/src/SDK/Metrics/Exemplar
> * JavaScript https://github.com/open-telemetry/opentelemetry-js/blob/main/packages/sdk-metrics/src/exemplar/index.ts

Those link does not tell much...For example, in JavaScript some exemplar related classes are there, but its not connected to SDK - its as good as saying JS does not support Exemplars... Which is why I was hoping every languages who implemented it will update the matrix, so we know if we have 3 languages implementing the spec. (or we can ask around as well :) ) 

OTel C++ also has some exemplars..

2024-02-14 17:16 UTC, MrAlias commented
Go has an [experimental implementation](https://github.com/open-telemetry/opentelemetry-go/tree/main/sdk/metric/internal/x). It does not expose any API for configuration outside of environment variables.

2024-03-15 19:58 UTC, reyang commented
The TC discussed this during the Mar. 13th meeting:

1. There is only one blocking issue (more details can be found from #3756), @jack-berg is working on it #3943.
2. After PR #3943 is merged, we should be ready to move this PR forward. We're targeting mid Apr. for the Metrics Exemplar spec to be marked Stable (spec release will happen early May).

2024-03-21 15:02 UTC, jack-berg reviewed
Was giving the exemplar spec a final read and noticed an issue.

2024-03-21 15:04 UTC, cijothomas commented
What is the default behavior with respect to Exemplars?

There is this language _"Exemplar sampling SHOULD be turned off by default."_ under https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#exemplar.
Does this mean, the default ExemplarFilter should be `AlwaysOff`? The https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#exemplarfilter
section talks about the 3 possible values of `ExemplarFilter`, but does not specify which one is default. However, the linked env variable section (https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/configuration/sdk-environment-variables.md#exemplar) says `TraceBased` is the default.

This should be clarified (like editorial change only).

I also want to run some perf numbers from .NET, and share another *related* concern shortly.

2024-03-21 17:02 UTC, cijothomas requested changes
Glad to see Exemplars moving to Stable!
I'd like to request we resolve the below before merging.

Likely an editorial change only:
https://github.com/open-telemetry/opentelemetry-specification/pull/3870#issuecomment-2012545386

https://github.com/open-telemetry/opentelemetry-specification/pull/3943 allows changing defaults, but I am not sure if that also allows changing the default from Simple to NoOp/similar. Hence, I consider this blocking issue:
https://github.com/open-telemetry/opentelemetry-specification/issues/3952

This is not blocking, given https://github.com/open-telemetry/opentelemetry-specification/pull/3943, but worth considering:
https://github.com/open-telemetry/opentelemetry-specification/issues/3953

Additionally, it is not clear how many languages have implemented the current spec. From what I see, Java,. NET and Golang has implemented fully. Not a blocker, but it'd be nice if spec matrix is updated, so its easy to tell who has implemented.

2024-04-11 02:39 UTC, reyang commented
#3994 would hopefully be the last piece before we mark Exemplar spec stable. Please refer to the #3944 PR description for the Technical Committee discussion details.

@cijothomas would you check if it unblocks this PR? Thanks!

2024-04-11 02:52 UTC, reyang commented on specification/metrics/sdk.md
>  ## Exemplar
Trying to address this via #3994.

2024-04-11 17:22 UTC, cijothomas commented
> #3994 would hopefully be the last piece before we mark Exemplar spec stable. Please refer to the #3944 PR description for the Technical Committee discussion details.
> 
> @cijothomas would you check if it unblocks this PR? Thanks!

Sure. Will check and post back here.

2024-04-13 02:58 UTC, cijothomas approved these changes
Based on https://github.com/open-telemetry/opentelemetry-specification/pull/3994#issue-2236799318, languages are free to chose a different default, and changing the default is considered non-breaking.
All the blocking issues are hence, addressable post stable as well.

2024-04-16 15:56 UTC, reyang approved these changes

2024-04-16 15:59 UTC, reyang commented
@open-telemetry/specs-approvers @open-telemetry/specs-metrics-approvers @open-telemetry/technical-committee PTAL, I think this is ready to be merged by end of Fri. this week (Apr. 19th, 2024, PT).

@jack-berg @jmacd @jsuereth FYI

2024-04-17 20:46 UTC, jack-berg approved these changes

2024-04-19 16:00 UTC, cijothomas commented
https://github.com/open-telemetry/opentelemetry-dotnet/pull/5545#issue-2249411523 OTel .NET's performance hit when enabling exemplars is shown here. And OTel .NET is planning to make Exemplars **opt-in for now**.

@jack-berg Do you have some perf numbers from Java handy that can be shared?

2024-04-19 18:25 UTC, jmacd approved these changes

2024-04-19 18:30 UTC, jmacd commented
I measured the Lightstep metrics SDK implementation of exemplars [here](https://github.com/lightstep/otel-launcher-go/pull/576) and the performance hit is consistent with what has been reported for .NET. For example, a fast-path that was 45ns becomes 60ns, for a 33% hit. I believe this is acceptable, and if there are applications for which a few 10s or 100s of nanoseconds of additional cost per metrics event are limiting, there may be other paths to optimization other than simply disabling exemplars.

https://github.com/lightstep/otel-launcher-go/pull/576#issuecomment-2067088223

2024-04-19 20:38 UTC, jack-berg commented
Here are the benchmarks from the java repo. Sharing these without having recently dug into what elements of the exemplar implementation drive perf.

The benchmark tests a variety of dimension:
- Single thread vs. multiple threads (in "Benchmark" column)
- Configuration of attributes which receive measurements (in "Benchmark" column)
- The instrument being recorded to (counter, histogram, etc, in the "(opBuilder)" column)
- The sdk configuration (noop api, exemplars enabled, examplars disabled, temporality, in the "(sdk)" column)
```
Benchmark                                                                     (opBuilder)             (sdk)  Mode  Cnt     Score     Error   Units
MetricsBenchmarks.eightThreadsCommonLabelSet                               LongCounterAdd          API_ONLY  avgt   10     0.982 ±   0.034   ns/op
MetricsBenchmarks.eightThreadsCommonLabelSet:gc.alloc.rate                 LongCounterAdd          API_ONLY  avgt   10     0.004 ±   0.001  MB/sec
MetricsBenchmarks.eightThreadsCommonLabelSet:gc.alloc.rate.norm            LongCounterAdd          API_ONLY  avgt   10    ≈ 10⁻⁶              B/op
MetricsBenchmarks.eightThreadsCommonLabelSet:gc.count                      LongCounterAdd          API_ONLY  avgt   10       ≈ 0            counts
MetricsBenchmarks.eightThreadsCommonLabelSet                               LongCounterAdd  SDK_NO_EXEMPLARS  avgt   10  1241.016 ±  11.347   ns/op
MetricsBenchmarks.eightThreadsCommonLabelSet:gc.alloc.rate                 LongCounterAdd  SDK_NO_EXEMPLARS  avgt   10     0.004 ±   0.001  MB/sec
MetricsBenchmarks.eightThreadsCommonLabelSet:gc.alloc.rate.norm            LongCounterAdd  SDK_NO_EXEMPLARS  avgt   10     0.001 ±   0.001    B/op
MetricsBenchmarks.eightThreadsCommonLabelSet:gc.count                      LongCounterAdd  SDK_NO_EXEMPLARS  avgt   10       ≈ 0            counts
MetricsBenchmarks.eightThreadsCommonLabelSet                               LongCounterAdd    SDK_CUMULATIVE  avgt   10  1235.555 ±  21.709   ns/op
MetricsBenchmarks.eightThreadsCommonLabelSet:gc.alloc.rate                 LongCounterAdd    SDK_CUMULATIVE  avgt   10     0.004 ±   0.001  MB/sec
MetricsBenchmarks.eightThreadsCommonLabelSet:gc.alloc.rate.norm            LongCounterAdd    SDK_CUMULATIVE  avgt   10     0.001 ±   0.001    B/op
MetricsBenchmarks.eightThreadsCommonLabelSet:gc.count                      LongCounterAdd    SDK_CUMULATIVE  avgt   10       ≈ 0            counts
MetricsBenchmarks.eightThreadsCommonLabelSet                               LongCounterAdd         SDK_DELTA  avgt   10   983.321 ±  12.307   ns/op
MetricsBenchmarks.eightThreadsCommonLabelSet:gc.alloc.rate                 LongCounterAdd         SDK_DELTA  avgt   10     0.004 ±   0.001  MB/sec
MetricsBenchmarks.eightThreadsCommonLabelSet:gc.alloc.rate.norm            LongCounterAdd         SDK_DELTA  avgt   10     0.001 ±   0.001    B/op
MetricsBenchmarks.eightThreadsCommonLabelSet:gc.count                      LongCounterAdd         SDK_DELTA  avgt   10       ≈ 0            counts
MetricsBenchmarks.eightThreadsCommonLabelSet                             DoubleCounterAdd          API_ONLY  avgt   10     1.006 ±   0.072   ns/op
MetricsBenchmarks.eightThreadsCommonLabelSet:gc.alloc.rate               DoubleCounterAdd          API_ONLY  avgt   10     0.004 ±   0.001  MB/sec
MetricsBenchmarks.eightThreadsCommonLabelSet:gc.alloc.rate.norm          DoubleCounterAdd          API_ONLY  avgt   10    ≈ 10⁻⁶              B/op
MetricsBenchmarks.eightThreadsCommonLabelSet:gc.count                    DoubleCounterAdd          API_ONLY  avgt   10       ≈ 0            counts
MetricsBenchmarks.eightThreadsCommonLabelSet                             DoubleCounterAdd  SDK_NO_EXEMPLARS  avgt   10   961.077 ±   9.234   ns/op
MetricsBenchmarks.eightThreadsCommonLabelSet:gc.alloc.rate               DoubleCounterAdd  SDK_NO_EXEMPLARS  avgt   10     0.004 ±   0.001  MB/sec
MetricsBenchmarks.eightThreadsCommonLabelSet:gc.alloc.rate.norm          DoubleCounterAdd  SDK_NO_EXEMPLARS  avgt   10     0.001 ±   0.001    B/op
MetricsBenchmarks.eightThreadsCommonLabelSet:gc.count                    DoubleCounterAdd  SDK_NO_EXEMPLARS  avgt   10       ≈ 0            counts
MetricsBenchmarks.eightThreadsCommonLabelSet                             DoubleCounterAdd    SDK_CUMULATIVE  avgt   10  1235.765 ±  16.153   ns/op
MetricsBenchmarks.eightThreadsCommonLabelSet:gc.alloc.rate               DoubleCounterAdd    SDK_CUMULATIVE  avgt   10     0.005 ±   0.001  MB/sec
MetricsBenchmarks.eightThreadsCommonLabelSet:gc.alloc.rate.norm          DoubleCounterAdd    SDK_CUMULATIVE  avgt   10     0.001 ±   0.001    B/op
MetricsBenchmarks.eightThreadsCommonLabelSet:gc.count                    DoubleCounterAdd    SDK_CUMULATIVE  avgt   10       ≈ 0            counts
MetricsBenchmarks.eightThreadsCommonLabelSet                             DoubleCounterAdd         SDK_DELTA  avgt   10  1224.222 ±  27.974   ns/op
MetricsBenchmarks.eightThreadsCommonLabelSet:gc.alloc.rate               DoubleCounterAdd         SDK_DELTA  avgt   10     0.004 ±   0.001  MB/sec
MetricsBenchmarks.eightThreadsCommonLabelSet:gc.alloc.rate.norm          DoubleCounterAdd         SDK_DELTA  avgt   10     0.001 ±   0.001    B/op
MetricsBenchmarks.eightThreadsCommonLabelSet:gc.count                    DoubleCounterAdd         SDK_DELTA  avgt   10       ≈ 0            counts
MetricsBenchmarks.eightThreadsCommonLabelSet                        DoubleHistogramRecord          API_ONLY  avgt   10     2.716 ±   0.085   ns/op
MetricsBenchmarks.eightThreadsCommonLabelSet:gc.alloc.rate          DoubleHistogramRecord          API_ONLY  avgt   10     0.004 ±   0.001  MB/sec
MetricsBenchmarks.eightThreadsCommonLabelSet:gc.alloc.rate.norm     DoubleHistogramRecord          API_ONLY  avgt   10    ≈ 10⁻⁶              B/op
MetricsBenchmarks.eightThreadsCommonLabelSet:gc.count               DoubleHistogramRecord          API_ONLY  avgt   10       ≈ 0            counts
MetricsBenchmarks.eightThreadsCommonLabelSet                        DoubleHistogramRecord  SDK_NO_EXEMPLARS  avgt   10  1276.578 ±  10.122   ns/op
MetricsBenchmarks.eightThreadsCommonLabelSet:gc.alloc.rate          DoubleHistogramRecord  SDK_NO_EXEMPLARS  avgt   10     0.004 ±   0.001  MB/sec
MetricsBenchmarks.eightThreadsCommonLabelSet:gc.alloc.rate.norm     DoubleHistogramRecord  SDK_NO_EXEMPLARS  avgt   10     0.001 ±   0.001    B/op
MetricsBenchmarks.eightThreadsCommonLabelSet:gc.count               DoubleHistogramRecord  SDK_NO_EXEMPLARS  avgt   10       ≈ 0            counts
MetricsBenchmarks.eightThreadsCommonLabelSet                        DoubleHistogramRecord    SDK_CUMULATIVE  avgt   10  1270.384 ± 114.901   ns/op
MetricsBenchmarks.eightThreadsCommonLabelSet:gc.alloc.rate          DoubleHistogramRecord    SDK_CUMULATIVE  avgt   10    14.956 ±  12.737  MB/sec
MetricsBenchmarks.eightThreadsCommonLabelSet:gc.alloc.rate.norm     DoubleHistogramRecord    SDK_CUMULATIVE  avgt   10     2.439 ±   2.380    B/op
MetricsBenchmarks.eightThreadsCommonLabelSet:gc.count               DoubleHistogramRecord    SDK_CUMULATIVE  avgt   10     1.000            counts
MetricsBenchmarks.eightThreadsCommonLabelSet:gc.time                DoubleHistogramRecord    SDK_CUMULATIVE  avgt   10     2.000                ms
MetricsBenchmarks.eightThreadsCommonLabelSet                        DoubleHistogramRecord         SDK_DELTA  avgt   10  1292.251 ±   4.334   ns/op
MetricsBenchmarks.eightThreadsCommonLabelSet:gc.alloc.rate          DoubleHistogramRecord         SDK_DELTA  avgt   10     0.004 ±   0.001  MB/sec
MetricsBenchmarks.eightThreadsCommonLabelSet:gc.alloc.rate.norm     DoubleHistogramRecord         SDK_DELTA  avgt   10     0.001 ±   0.001    B/op
MetricsBenchmarks.eightThreadsCommonLabelSet:gc.count               DoubleHistogramRecord         SDK_DELTA  avgt   10       ≈ 0            counts
MetricsBenchmarks.eightThreadsCommonLabelSet                          LongHistogramRecord          API_ONLY  av [...]

2024-04-19 20:45 UTC, jack-berg commented
Benchmark after optimizing accessing the current nano time from the VM below. Much more in line with what we're seeing from .NET and Go.
```
Benchmark                                                 (opBuilder)             (sdk)  Mode  Cnt   Score    Error   Units
MetricsBenchmarks.oneThread                            LongCounterAdd  SDK_NO_EXEMPLARS  avgt   10  17.323 ±  0.309   ns/op
MetricsBenchmarks.oneThread                            LongCounterAdd    SDK_CUMULATIVE  avgt   10  28.126 ±  1.143   ns/op
MetricsBenchmarks.oneThread                     DoubleHistogramRecord  SDK_NO_EXEMPLARS  avgt   10  33.842 ±  1.248   ns/op
MetricsBenchmarks.oneThread                     DoubleHistogramRecord    SDK_CUMULATIVE  avgt   10  55.855 ±  2.418   ns/op
```

2024-04-20 00:15 UTC, merged