Add EventEmitterProvider to the Event API
open-telemetry/opentelemetry-specification pull request #3878
Opened 2024-02-15 01:01 UTC by martinkuba

Fixes https://github.com/open-telemetry/opentelemetry-specification/issues/3086

## Changes

The Event API will be used by instrumentations to generate events. Currently, the API takes an instance of a logger as a direct dependency. This means that instrumentations would need to be aware of the Log API, which is in conflict with the intent of using the Log API only to bridge logging frameworks. Furthermore, each instrumentation would need to construct an instance of an EventEmitter, which is also inconsistent with the pattern of using a globally-registered provider.

This PR adds the `EventEmitterProvider` class to the API, making it consistent with other APIs.

2024-02-15 03:07 UTC, scheler approved these changes

2024-02-15 15:39 UTC, jack-berg commented on specification/logs/event-api.md
> +## EventEmitterProvider
Currently, the Event API delegates directly to a logger provided by the user. As you note, this is problematic because users aren't supposed to directly interact with loggers. 

This PR aims to fix that problem, but the "Implementation Requirements" section of the "Emit Event" operation still express a dependency on `Logger` without describing where that logger comes from. Without a definition of how `EventEmitterProvider` is implemented and how it obtains access to a `Logger`, this proposal is incomplete.

2024-02-15 16:02 UTC, tigrannajaryan commented
@martinkuba can you clarify what is the final intent? Do you plan to have an Events SDK that is configured separately from Logs SDK? Will Events SDK have its own pipeline of processors and exporters independently from Logs? Or is the plan to still rely on Logs SDK in some way?

2024-02-15 18:15 UTC, martinkuba commented
> @martinkuba can you clarify what is the final intent? Do you plan to have an Events SDK that is configured separately from Logs SDK? Will Events SDK have its own pipeline of processors and exporters independently from Logs? Or is the plan to still rely on Logs SDK in some way?

The intent is to remove the direct dependency on the Log API from the Event API. Introducing the provider is a first step, and as I understood the outcome of https://github.com/open-telemetry/opentelemetry-specification/issues/3086.

I agree that we need to specify how the API should be implemented as the next step. There were a few proposals in https://github.com/open-telemetry/opentelemetry-specification/issues/3086. I think we do need to add a spec for Event SDK. My proposal would be to document that the default Event SDK should (or must) be implemented using the Log API. This would make it clear that, from OTel perspective, events are built on top of logs. And the Event SDK would not need to introduce any other concepts such as its own processors/exporters. I can add it to this PR, and I am also open to other suggestions.

2024-02-15 19:18 UTC, MrAlias requested changes
There are structural specification issues with this PR that need to be addressed.

2024-02-15 19:18 UTC, MrAlias commented on specification/logs/event-api.md
> +The Event API consist of these main classes:
Please do not use object oriented programming language in the specification.

2024-02-15 19:18 UTC, MrAlias commented on specification/logs/event-api.md
> +* [EventEmitterProvider](#eventemitterprovider) is the entry point of the API. It provides access to `EventEmitter`s.
All other signals use single terms for this type of object. For example, we do not provide a `LogEmitter`.

Why not can this `Eventer`?

2024-02-15 19:18 UTC, MrAlias commented on specification/logs/event-api.md
> +In implementations of the API, the `EventEmitterProvider` is expected to be the stateful
Do not include how the API is expected to be implemented in the API specification. OTel implementations of the API need to be specified directly in their own documentation. And we do not control third party implementations.

2024-02-15 19:18 UTC, MrAlias commented on specification/logs/event-api.md
> +  variable number of attributes, including none.
The use of the term `optional` her is ambiguous. Please follow the other signal definitions of parameters to clarify what is meant by this term in this use.

2024-02-15 19:18 UTC, MrAlias commented on specification/logs/event-api.md
> +instances where at least one identifying field has a different value.
Why is this being added here? There is no use of the identity of an `EventEmitter` in this PR. Please remove this.

2024-02-15 19:29 UTC, martinkuba commented on specification/logs/event-api.md
> +The Event API consist of these main classes:
I followed the example from the Log Bridge and Trace APIs; they both mention classes.

2024-02-15 19:33 UTC, martinkuba commented on specification/logs/event-api.md
> +* [EventEmitterProvider](#eventemitterprovider) is the entry point of the API. It provides access to `EventEmitter`s.
IMO, we should use terminology that is intuitive. EventEmitter is a term commonly used for things that emit events, while I Eventer is not (I don't think).

2024-02-15 19:34 UTC, MrAlias commented on specification/logs/event-api.md
> +The Event API consist of these main classes:
Understood. Those should be corrected. Let's not add to the misuse here.

2024-02-15 19:35 UTC, martinkuba commented on specification/logs/event-api.md
> +In implementations of the API, the `EventEmitterProvider` is expected to be the stateful
I copied this from the [Trace API](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#tracerprovider)

2024-02-15 19:40 UTC, MrAlias commented on specification/logs/event-api.md
> +The Event API consist of these main classes:
https://github.com/open-telemetry/opentelemetry-specification/issues/1569

2024-02-15 19:50 UTC, MrAlias commented on specification/logs/event-api.md
> +* [EventEmitterProvider](#eventemitterprovider) is the entry point of the API. It provides access to `EventEmitter`s.
The same could be said for a `Logger` vs a `LogEmitter`, `Tracer` vs `SpanCreater`, or a `Meter` vs a `InstrumentCreater`. We have always used the singular term in our other signal, I think we need more objective reasoning to diverge here.

2024-02-15 19:55 UTC, MrAlias commented on specification/logs/event-api.md
> +In implementations of the API, the `EventEmitterProvider` is expected to be the stateful
Please follow the metric API: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/api.md#get-a-meter

The trace API has a pending clean-up task: https://github.com/open-telemetry/opentelemetry-specification/pull/3171#issuecomment-1430274042

2024-02-15 19:58 UTC, MrAlias commented on specification/logs/event-api.md
> +In implementations of the API, the `EventEmitterProvider` is expected to be the stateful
Please follow the metric API: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/api.md#get-a-meter. This is a known [issue](https://github.com/open-telemetry/opentelemetry-specification/issues/3071) with prior specifications that was addressed in that signal's development. We should not carry forward prior mistakes.

2024-02-16 17:50 UTC, MrAlias commented on specification/logs/event-api.md
> +  variable number of attributes, including none.
"optional" is defined below: https://github.com/open-telemetry/opentelemetry-specification/blob/94abf11ab632063e7123e6698af89ebf01633183/specification/logs/event-api.md#optional-and-required-parameters

2024-02-16 18:34 UTC, trask commented on specification/logs/event-api.md
> +* [EventEmitterProvider](#eventemitterprovider) is the entry point of the API. It provides access to `EventEmitter`s.
`Logger` = thing that logs
`Tracer` = thing that traces

...these work great

`Meter` = thing that metes(?)

...this one is kinda confusing to me

@MrAlias is there a specific benefit we get from these being a single word?

2024-02-16 18:55 UTC, MrAlias commented on specification/logs/event-api.md
> +* [EventEmitterProvider](#eventemitterprovider) is the entry point of the API. It provides access to `EventEmitter`s.
* consistency: No other signal type at this level includes an operation of the type within the type name.
* extensibility: If operations are added in the future other than `Emit` the name will not be appropriate
* conciseness: typing `Eventer` is shorter than typing `EventEmitter`

2024-02-16 23:01 UTC, martinkuba commented on specification/logs/event-api.md
> +* [EventEmitterProvider](#eventemitterprovider) is the entry point of the API. It provides access to `EventEmitter`s.
I am not going to change the name with this PR, so that it does not block introducing the provider. I have another PR https://github.com/open-telemetry/opentelemetry-specification/pull/3869 open to change the name - I think we should discuss there.

2024-02-16 23:22 UTC, martinkuba commented on specification/logs/event-api.md
> +In implementations of the API, the `EventEmitterProvider` is expected to be the stateful
Even the Metric API includes this statement, but I have removed it from here.

2024-02-16 23:29 UTC, martinkuba commented on specification/logs/event-api.md
> +instances where at least one identifying field has a different value.
This same language is used in the Log and Meter APIs when creating a logger or meter using the providers. Can you please clarify why it should not be included here?

2024-02-16 23:33 UTC, MrAlias commented on specification/logs/event-api.md
> +instances where at least one identifying field has a different value.
Copying something from other specification sections is not justification for including this. Is this used? If not, it should not be added. If it is, it needs to be included along with it's use.

2024-02-16 23:34 UTC, MrAlias commented on specification/logs/event-api.md
> +* [EventEmitterProvider](#eventemitterprovider) is the entry point of the API. It provides access to `EventEmitter`s.
I would say this PR is blocked on this given it will impact the name of the provider.

I'm happy to have the discussion in the other PR, but I do not think this can be merged without the resolution to the question.

2024-02-18 18:34 UTC, martinkuba commented on specification/logs/event-api.md
> +instances where at least one identifying field has a different value.
The reason I included this is because it appears to be a pattern for creating Tracer/Logger/Meter such that "it is a user error to create EventEmitters with different`attributes` but the same identity". I assume we want to follow this pattern here as well. Can you please clarify why we shouldn't follow this pattern, or should I add additional details about usage here that is included in the other APIs?

2024-02-23 11:42 UTC, tedsuo commented on specification/logs/event-api.md
> +* [EventEmitterProvider](#eventemitterprovider) is the entry point of the API. It provides access to `EventEmitter`s.
We should move the discussion to the other PR just to get out of this comment thread, but I agree we should just pick something and have one PR. I've commented there.

(I don't agree with the notion that we set some kind of requirement that it must be a single word)

2024-02-23 11:50 UTC, tedsuo approved these changes
Thank you for conforming to the spec and going with a Provider.

2024-02-23 16:01 UTC, MrAlias commented on specification/logs/event-api.md
> +instances where at least one identifying field has a different value.
I see. That makes sense.

I suggest removing:

> The term *identical* applied to `EventEmitter`s describes instances where all identifying fields are equal. The term *distinct* applied to `EventEmitter`s describes instances where at least one identifying field has a different value.

That is the unused part I am having issue with. It is copy of something originally from the metric specification that was subsequently moved from that API to the [place it is used](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#duplicate-instrument-registration). Defining the terms "identical" and "distinct" is not needed in this API.

2024-02-27 16:57 UTC, MSNev approved these changes

2024-03-05 16:18 UTC, martinkuba commented on specification/logs/event-api.md
> +* [EventEmitterProvider](#eventemitterprovider) is the entry point of the API. It provides access to `EventEmitter`s.
Decision was made in the Specification SIG meeting on 3/5/24 to keep the name as EventLogger.

2024-03-05 16:54 UTC, martinkuba commented on specification/logs/event-api.md
> +## EventEmitterProvider
I have added a draft of Event SDK spec to this PR. I moved the implementation details that were originally in the API there.

2024-03-05 16:55 UTC, martinkuba commented on specification/logs/event-api.md
> +instances where at least one identifying field has a different value.
I have removed the paragraph

2024-03-05 17:14 UTC, patrickhousley commented on specification/logs/event-api.md
>    well-defined `Payload`.
Do we define how these attributes add or override the attributes on the `EventLogger` instance?

2024-03-05 17:17 UTC, patrickhousley approved these changes

2024-03-05 18:18 UTC, breedx-splk commented on specification/logs/event-sdk.md
> +All language implementations of OpenTelemetry MUST provide an SDK.
```suggestion
All implementations of the OpenTelemetry API MUST provide an SDK.
```

Minor change. I think the use of "language" here is a little inside baseball. It's implementations of the API that need to provide an SDK, right?

2024-03-05 18:21 UTC, breedx-splk approved these changes
This seems like a good start to me.

2024-03-06 00:37 UTC, martinkuba commented on specification/logs/event-api.md
>    well-defined `Payload`.
The attribute that are given to the EventLogger when it's created are in the [instrumentation scope](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/glossary.md#instrumentation-scope), while these are on individual events.

2024-03-06 21:30 UTC, MrAlias approved these changes
:rocket:

2024-03-06 22:48 UTC, patrickhousley approved these changes

2024-03-07 07:46 UTC, pellared approved these changes

2024-03-07 13:00 UTC, jack-berg commented on specification/logs/event-api.md
> +## EventEmitterProvider
I see the implementations details are restored so I'll resolve this comment. No need to wait on my approval!

2024-03-12 15:00 UTC, jmacd approved these changes

2024-03-12 21:11 UTC, merged