Clarify legacy logs format trace context flags and tracestate
open-telemetry/opentelemetry-specification pull request #3923
Opened 2024-03-06 00:24 UTC by jmacd

Part of #3303.

## Changes

Clarifies how the trace flags are represented when placing trace context in log records.
Clarifies that `tracestate` is not encoded when placing trace context in log records.

For non-trivial changes, follow the [change proposal process](https://github.com/open-telemetry/opentelemetry-specification/blob/main/CONTRIBUTING.md#proposing-a-change).

* [ ] Related issues #
* [ ] Related [OTEP(s)](https://github.com/open-telemetry/oteps) #
* [ ] Links to the prototypes (when adding or changing features)
* [ ] [`CHANGELOG.md`](https://github.com/open-telemetry/opentelemetry-specification/blob/main/CHANGELOG.md) file updated for non-trivial changes
* [ ] [`spec-compliance-matrix.md`](https://github.com/open-telemetry/opentelemetry-specification/blob/main/spec-compliance-matrix.md) updated if necessary

2024-03-06 00:26 UTC, reyang approved these changes
LGTM with a changelog entry.

2024-03-06 02:32 UTC, dashpole approved these changes

2024-03-06 09:02 UTC, pellared requested changes

2024-03-06 09:02 UTC, pellared commented on specification/compatibility/logging_trace_context.md
> +`flags` field is 32-bits wide.  When interpreting `trace_flags` from
What `flags` are you referring to? The `TraceFlags` in data model are also a byte. See https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/data-model.md#field-traceflags

2024-03-06 18:13 UTC, jmacd commented on specification/compatibility/logging_trace_context.md
> +`flags` field is 32-bits wide.  When interpreting `trace_flags` from
I was looking at https://github.com/open-telemetry/opentelemetry-proto/blob/9d139c87b52669a3e2825b835dd828b57a455a55/opentelemetry/proto/logs/v1/logs.proto#L183 which talks about reserving bits 8-31 of the flags.

2024-03-06 18:13 UTC, jmacd commented on specification/compatibility/logging_trace_context.md
> +`flags` field is 32-bits wide.  When interpreting `trace_flags` from
(https://github.com/open-telemetry/opentelemetry-proto/blob/9d139c87b52669a3e2825b835dd828b57a455a55/opentelemetry/proto/logs/v1/logs.proto#L129)

2024-03-06 18:32 UTC, pellared commented on specification/compatibility/logging_trace_context.md
> +`flags` field is 32-bits wide.  When interpreting `trace_flags` from
This is a spec for Trace Context in non-OTLP Log Formats

2024-03-06 23:49 UTC, jmacd commented on specification/compatibility/logging_trace_context.md
> +`flags` field is 32-bits wide.  When interpreting `trace_flags` from
Ah! It looks like there is a disagreement between the specification `data-model.md` and the protocol's `logs.proto`. One says `trace_flags` (8-bits), one says `flags` (32 bits w/ an 8-bit mask for trace_flags).

2024-03-06 23:58 UTC, jmacd commented on specification/compatibility/logging_trace_context.md
> +`flags` field is 32-bits wide.  When interpreting `trace_flags` from
@pellared would https://github.com/open-telemetry/opentelemetry-specification/pull/3923/commits/1148595aac4aee5c0b4673f2106d857b8aadad1e help?

2024-03-06 23:58 UTC, jmacd commented on specification/compatibility/logging_trace_context.md
> +`flags` field is 32-bits wide.  When interpreting `trace_flags` from
@open-telemetry/specs-logs-approvers PTAL

2024-03-15 12:07 UTC, carlosalberto commented
@pellared maybe re-review this? Or still blocked?

2024-03-21 13:46 UTC, tigrannajaryan requested changes

2024-03-21 14:40 UTC, jmacd commented on specification/logs/data-model.md
> +### Field: `Flags`
This is not a new flag in the data model. The data model describes a flag we do not really have, so I've fixed it to describe the field we do have (Flags) and explain that the documented field we do not have (TraceFlags) is not real, but instead TraceFlags is a conceptual part of the Flags field.

See? This document describes TraceFlags and the proto does not have TraceFlags. https://github.com/open-telemetry/opentelemetry-proto/blob/main/opentelemetry/proto/logs/v1/logs.proto

2024-03-21 14:54 UTC, tigrannajaryan commented on specification/logs/data-model.md
> +field is optional.
>I'm clarifying that it's not real.

I am not sure I agree with that. It seems pretty real from data model perspective. In the data model we do have a TraceFlags field, as real as it gets in data models. The fact that OTLP uses a Flags field to encode this information is not important from the perspective of this document.

It seems we are bringing the implementation details of OTLP into the data model doc and I don't understand why.

2024-03-25 22:10 UTC, jmacd commented on specification/logs/data-model.md
> +field is optional.
My intention here was to clarify what may be internal confusion of mine -- I was recently surprised to learn how the W3C Trace Context defines propagation of unknown flags. Specifically, participants MUST zero the flags they do not recognize. I bring this up because the link on "as defined in W3C Trace Context" links to an overview section, whereas if you read https://www.w3.org/TR/trace-context/#other-flags you may question what it means to be "as defined in". It looks to me that if any flag besides the two we know about (Sampled, 0x1 and Random, 0x2) makes an invalid trace flags value, and perhaps the data model should say something about this.

However, my only intention was to be very clear that if TraceFlags arrives as a string like "ffff" we do not consider it valid TraceFlags, because it is too wide. I think we mean "syntactically defined as trace flags are defined" but that we are not forbidding legacy logs formats from creating logs data with unrecognized flags set as I speculated about above.

2024-03-25 22:12 UTC, jmacd commented on specification/logs/data-model.md
> +### Field: `Flags`
I removed "Flags". I see now why it is excluded from the data model (at least for now, since there are no flags defined by OpenTelemetry). In tracing, span flags would be part of the data model, I think (because it has defined two flags now). https://github.com/open-telemetry/opentelemetry-specification/issues/1929

2024-04-09 03:17 UTC, closed without merging