Change map to key-value pair collection in Logs Data Model
open-telemetry/opentelemetry-specification pull request #3938
Opened 2024-03-13 13:22 UTC by pellared

## Why

Fixes https://github.com/open-telemetry/opentelemetry-specification/issues/3931

## What

Change 

## Remarks

It is not planed to change anything in OTLP.

2024-03-13 13:41 UTC, pellared commented
@open-telemetry/specs-logs-approvers PTAL

2024-03-13 15:05 UTC, TylerHelmuth commented on specification/logs/data-model.md
> +Type: [`[]keyval<string, any>`](#type-keyvalstring-any).
I've not spent much time in the spec, but changing the data type of a field in a stabilized data format feels like a breaking change to me.  The data model is more explicit than the proto that `Attributes` are a map and since the model is stable I feel like we should assume implementations are depending on this fact (even though we know some are not).

2024-03-13 15:29 UTC, MrAlias commented on specification/logs/data-model.md
> +Type: [`[]keyval<string, any>`](#type-keyvalstring-any).
I'm not sure this is changing the data-type as much as renaming it to account for implementations that don't implement this as a map.

2024-03-13 15:30 UTC, MrAlias approved these changes

2024-03-13 15:40 UTC, TylerHelmuth commented on specification/logs/data-model.md
> +Type: [`[]keyval<string, any>`](#type-keyvalstring-any).
> renaming it to account for implementations that don't implement this as a map.

But not implementing as a map was technically against specification right?

> Any implementation that was compatible prior to this change, will still be compatible after it.

Agreed, but it allows 2 different implementation to generate incompatible data right? If 1 data source generates attributes as a map and another generates data as a list, when the data comes together, either in the collector or some backend, I anticipate problems, or at least unexpected/undefined behavior.

2024-03-14 15:14 UTC, austinlparker commented on specification/logs/data-model.md
> +Type: [`[]keyval<string, any>`](#type-keyvalstring-any).
unresolving per @TylerHelmuth request

2024-03-14 15:38 UTC, pellared commented on specification/logs/data-model.md
> +Type: [`[]keyval<string, any>`](#type-keyvalstring-any).
> But not implementing as a map was technically against specification right?

Not really as it was not using normative language.

2024-03-14 15:40 UTC, TylerHelmuth commented on specification/logs/data-model.md
> +Type: [`[]keyval<string, any>`](#type-keyvalstring-any).
If this is a instrumentation-only concern and does not change how the exporters emit the data using OTLP please let me know.

It does feel like a breaking change to me to change a data type.  I'd like to stick as closely as possible to semver as possible so that any implementers of our spec are not unexpectedly affected.

2024-03-14 16:00 UTC, pellared commented on specification/logs/data-model.md
> +Type: [`[]keyval<string, any>`](#type-keyvalstring-any).
> If 1 data source generates attributes as a map and another generates data as a list, when the data comes together, either in the collector or some backend, I anticipate problems, or at least unexpected/undefined behavior.

The exporter should deduplicate the key-values if it is required.

Additionally, the user can always use a processor which deduplicates key-values.

2024-03-14 16:19 UTC, mx-psi commented on specification/logs/data-model.md
> +may require deduplication (removing pairs so that none of them have the same key).
My assumption was that the OTLP proto was meant to reflect the Data Model and I assumed the semantics of the OTLP proto were documented in the data model. Is that not the case? Are the semantics of each completely independent?

Specially the sentence "The type representation is language-dependent" makes it seem like this document is exclusively referring to the in-memory representation of logs in the SDK.

2024-03-14 16:40 UTC, pellared commented on specification/logs/data-model.md
> +Type: [`[]keyval<string, any>`](#type-keyvalstring-any).
> If this is a instrumentation-only concern and does not change how the exporters emit the data using OTLP please let me know

Yes it is. I explicitly write in the description that OTLP exporters still have to send deduplicated key-values.

2024-03-14 17:35 UTC, pellared commented on specification/logs/data-model.md
> +may require deduplication (removing pairs so that none of them have the same key).
> Specially the sentence "The type representation is language-dependent" makes it seem like this document is exclusively referring to the in-memory representation of logs in the SDK.

This is a good comment.

I thought that is describing the model for the SDK. I guess I was wrong. Maybe I should change the [Logs SDK](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/sdk.md) specification instead? I would need guidance from approvers/maintainers.

2024-03-14 18:30 UTC, pellared commented on specification/logs/data-model.md
> +may require deduplication (removing pairs so that none of them have the same key).
> Are the semantics of each completely independent?

For the SDK it makes sense to support other log exporters than OTLP which can have better performance when there is no de-duplication involved. I believe that there are even backends which are able to support key-values with duplicated keys (without losing the duplicates). There is a lot of software using OTel APIs and SDK for instrumenting application and NOT exporting these via OTLP. I would say that tightly coupling the model to OTLP is against OpenTelemetry "promise":

> OpenTelemetry is vendor- and tool-agnostic, meaning that it can be used with a broad variety of Observability backends

2024-03-15 10:44 UTC, mx-psi commented on specification/logs/data-model.md
> +may require deduplication (removing pairs so that none of them have the same key).
To be clear: I am not against the 'spirit' of this change, I am just not sure what is the best way to word it :)

2024-03-15 17:01 UTC, tigrannajaryan requested changes

2024-03-15 17:01 UTC, tigrannajaryan commented on specification/logs/data-model.md
> +It is implementation-specific whether the collection can contain duplicated keys.
I think this is a breaking change. We can't allow this. It expands the possible shape of the data that recipients should be able to deal with. This is also not possible to represent in OTLP, so I think this is a no go.

2024-03-15 17:25 UTC, pellared commented on specification/logs/data-model.md
> +It is implementation-specific whether the collection can contain duplicated keys.
Just to confirm. All receipents possibe? Would it also be seen as breaking if OTLP exporters would handle the deduplication?

2024-03-15 18:34 UTC, tigrannajaryan commented on specification/logs/data-model.md
> +It is implementation-specific whether the collection can contain duplicated keys.
>Just to confirm. All possibe receipents (processors, exporters)? 

This document is the logical data model and applies to anyone who creates the data and who reads the data, so yes  it applies to processors, exporters, SDKs, Collector, backends.

>Would it also be seen as breaking if in SDKs the OTLP exporters would handle the deduplication?

I think it is fine to do the deduplication anywhere you want as long as _externally observable_ data complies with this document.

>I have an idea to propose adding an option like WithoutKeyValueDeduplication to Go Logs SDK for users who favor performance over the danger of potentially losing some log records. By default the SDK would get rid of duplicates.

I think it is fair to provide non-default options like this, with a clear warning that the caller is responsible for ensuring there are no duplicates, assuming there is a _need_ for such high performance. 

Provided that such option option is possible to add later in non-breaking manner to Go SDK I would not do it right now and will only add it after we gather evidence from real-world usage that it is really needed by the users.

2024-03-15 19:26 UTC, pellared commented on specification/logs/data-model.md
> +It is implementation-specific whether the collection can contain duplicated keys.
> I think it is fair to provide non-default options like this, with a clear warning that the caller is responsible for ensuring there are no duplicates, assuming there is a need for such high performance.

> Provided that such option option is possible to add later in non-breaking manner to Go SDK I would not do it right now and will only add it after we gather evidence from real-world usage that it is really needed by the users.

@tigrannajaryan, sounds like a good plan 👍 Do you think that the specification should be updated before we introduce such option?

CC @open-telemetry/cpp-maintainers @open-telemetry/rust-maintainers  @open-telemetry/dotnet-maintainers

2024-03-15 19:36 UTC, tigrannajaryan commented on specification/logs/data-model.md
> +It is implementation-specific whether the collection can contain duplicated keys.
>Do you think that the specification should be updated before we introduce such option?

Probably, no, if it is only for Go. Likely, yes, if multiple languages will use it.

2024-03-15 19:54 UTC, pellared commented
Changing to draft per https://github.com/open-telemetry/opentelemetry-specification/pull/3938#discussion_r1526582541

I plan to close this PR in a few days.

2024-03-21 13:58 UTC, tigrannajaryan commented
> I plan to close this PR in a few days.

@pellared  Any reason we need to keep this open?

2024-03-21 21:42 UTC, closed without merging

2024-03-21 22:10 UTC, hdost commented
FYI @open-telemetry/rust-approvers  to inform our discussions in the future.