Define OTEL_CONFIG_FILE to ignore other env vars, add env var substitution default syntax
open-telemetry/opentelemetry-specification pull request #3948
Opened 2024-03-18 16:18 UTC by jack-berg

Fixes #3752.

Implementation of the configuration working group recommendation as [described here](https://github.com/open-telemetry/opentelemetry-specification/issues/3752#issuecomment-1995582317).

- Adds definition for `OTEL_CONFIG_FILE`, which ignores other env vars when evaluating, except env var substitution references
- Adds new env var substitution default syntax `${ENVVAR:-defaultValue}`
- Paired with https://github.com/open-telemetry/opentelemetry-configuration/pull/76, which defines a new [sdk-config.yaml](https://github.com/jack-berg/opentelemetry-configuration/blob/starter-template/examples/sdk-config.yaml) starter template referencing all env vars that map cleanly.

2024-03-18 20:12 UTC, marcalff approved these changes
LGTM

2024-03-18 20:12 UTC, marcalff commented on specification/configuration/file-configuration.md
> +if `ENV_NAME` is null or undefined. `DEFAULT_VALUE` is consists of 0 or more non
```suggestion
if `ENV_NAME` is null or undefined. `DEFAULT_VALUE` consists of 0 or more non
```

2024-03-20 02:10 UTC, lmolkova requested changes
As described in this - https://github.com/open-telemetry/opentelemetry-specification/issues/3752#issuecomment-2000406239 and other comments on the discussion:

This would break the mechanism AWS lambda, otel-operator and potentially other providers/environments outside of otel repositories already use to specify default service name, resource attributes, propagators, and maybe other settings (like exporters).

The alternative suggested in the discussion  (asking users to keep boilerplate for env vars in the file) is fragile. It also removes incentive from cloud providers to integrate with otel and provide common env vars. They would rather ask users to handle their custom list of env vars resulting in degraded user experience.

2024-03-20 03:10 UTC, jack-berg commented
I can think of two ways to accommodate the requirement for platforms / distributions to customize configuration:

1. There is language in this PR that states "Implementations MAY provide a mechanism to customize the configuration model parsed from `OTEL_CONFIG_FILE`." In java, this would be a SPI akin to [AutoConfigurationCustomizer](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/autoconfigure-spi/src/main/java/io/opentelemetry/sdk/autoconfigure/spi/AutoConfigurationCustomizer.java), which would give the implementer the ability to customize the parsed in memory representation of the configuration model with any platform specific requirements. The downside of this is approach is the language specific implementation requirement. But if you're already packaging up some sort of distribution, you probably already are used to language specific customizations so maybe not such a bad thing. The language could be strengthened from "MAY" to "MUST".
2. A platform could detect the presence of `OTEL_CONFIG_FILE`. If set, copy the contents to a new path, modify the contents to include the platform customizations, and update `OTEL_CONFIG_FILE` to point to the new location. This should be straight forward to do and in a language agnostic way. This has the benefit of allowing the customizer to have much more control over the configuration than is available with updating env vars. When you view the problem through this lens, the idea that platforms can only customize through the existing env var scheme seems very limiting.

2024-03-20 04:05 UTC, lmolkova commented
Ability to customize SDK behavior does not help cloud provider. Azure Functions don't know which distro uses wants to use and can't inject the distro for them. 

I see some problems with the second approach as well:
- complexity. Cloud providers would deal with messy merges we tried to 'avoid'  on otel side
- permissions. User would need to give providers permissions to modify the file
- sensitive content. I might store auth keys in the file  and don't want my provider to even see it
- breaking. This is the change of existing behavior - providers will need to **change their existing code to adopt the file proposal** -  if it's not breaking, then what is?

2024-03-20 15:50 UTC, jack-berg commented
> complexity. Cloud providers would deal with messy merges we tried to 'avoid' on otel side. I don't trust them us to do it well or consistently

Here's an example of merging a custom resource attribute into a config file using an open source command line YAML processor called [yq](https://github.com/mikefarah/yq) (i.e. YAML equivalent of the popular [jq](https://jqlang.github.io/jq/)). 

Given `config.yaml` with contents:

```
resource:
  attributes:
    service.name: my-service
```

To add a new resource attribute `foo = bar`, we can call `yq eval-all '.resource.attributes.foo = "bar"' ./config.yaml > config-new.yaml`. The output in `config-new.yaml` is:

```
resource:
  attributes:
    service.name: my-service
    foo: bar
```

Its a trade off. A bit more complex than setting `OTEL_RESOURCE_ATTRIBUTES`, but much more powerful since file configuration is much more expressive and there are many knobs of configuring how merge works.

> permissions. User would need to give providers permissions to modify the file
> secret management. I might store auth keys in the file and don't want my provider to even see it

I propose writing to a new file and reassigning `OTEL_CONFIG_FILE` to the new location rather than modifying in place. I don't buy the secret management piece. Code that already has access to read and write env vars which are expected to contain secrets is already implicitly trusted. Reading and overwriting env vars vs reading / modifying a config file are two sides of the same coin.

> breaking. This is the change of existing behavior - providers will need to change their existing code to adopt the file - if it's not breaking, then what is?

You've said that azure functions doesn't know or control which distro a user wants to use. Its entirely possible for a user to choose a distribution that ignores `OTEL_RESOURCE_ATTRIBUTES`, and the azure functions implementation would be powerless to ensure those attributes are present. Just as its entirely possible for a user to choose a distribution to ignore `OTEl_RESOURCE_ATTRIBUTES`, a user can choose to set a new env var `OTEL_CONFIG_FILE` which changes the behavior of existing env vars.

I'll refer to the arguments I previously made about breaking changes for env vars: https://github.com/open-telemetry/opentelemetry-specification/issues/3752#issuecomment-1998810830 We should not consider a change in behavior resulting from a user opting into something new to be a breaking change. Consider another example:

A vendor provides a distribution of otel which sets env vars to export OTLP to their endpoint, i.e. `OTEL_OTLP_EXPORTER_ENDPOINT=https://some-vendor:4318`. They support explicit bucket histograms and the SDK produces them by default. We stabilize exponential histograms, and introduce a new env var to opt in `OTEL_EXPORTER_OTLP_METRICS_DEFAULT_HISTOGRAM_AGGREGATION=base2_exponential_bucket_histogram`. A user sets this new env var. The vendor doesn't support exponential histograms, and fails to ingest the data. Should otel not be permitted to add `OTEL_EXPORTER_OTLP_METRICS_DEFAULT_HISTOGRAM_AGGREGATION` for fear of breaking the distribution? No, of course we should be allowed to add that. The distribution is expected to adapt, and either: 1. Add support for exponential histograms. 2. Document that users should not set the new env var. 3. Detect the new env var, and override it to revert to explicit bucket histograms. 

This convo is reminiscent of the debate we had over whether extending the span interface to include a new `addLink` operation was breaking. Some argued that extending interfaces breaks custom SDK implementations, which would not compile unless they published a new version implementing the new surface area. We decided this interpretation is wrong, and would jeopardize our ability to innovate and evolve the project. In #3695 we [codified](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/upgrading.md#sdk-implementors) that SDK implementers need to keep their implementations up to date. "It is inevitable that OpenTelemetry will release new features, and that application developers and library maintainers will make use of these features." Its not exactly the same as what were talking about, but there are striking similarities: This PR aims to introduce a new features which are opt in, and which platforms like Azure functions would need to adapt to in order to keep the same behavior in the event that a user does opt in.

2024-03-20 16:21 UTC, lmolkova commented
there is a problem of conflict resolution. By pushing it away to cloud providers, we don't solve it, but make it worse. Azure will decide to do it differently in every SaaS, PaaS, FaaS, AWS will do it in yet another way. 

I do think it makes user experience worse. 
If we made a few common env vars interop with the config, it would be easy for us, it would be easy for cloud providers and also easy for users. Dead-simple rule looks like "if property that could come from env var was not specified in the config, SDK MUST check corresponding env var". I still don't understand what's controversial here.

> I propose writing to a new file and reassigning OTEL_CONFIG_FILE to the new location rather than modifying in place.

Can you elaborate? User specifies `OTEL_CONFIG_FILE` value - do you want cloud providers to change its value?
What if user sets OTEL_CONFIG_FILE inside dockerfile and it's not even visible to the cloud provider?

>  I don't buy the secret management piece. Code that already has access to read and write env vars which are expected to contain secrets is already implicitly trusted. Reading and overwriting env vars vs reading / modifying a config file are two sides of the same coin.

I don't agree. I can use key-vaults to retrieve my secrets from, I can dynamically format my config file in the startup scripts/dockerfile to retrieve data from configuration services. If the config file is inside the container or otherwise protected from access, cloud providers  won't be able to access it. 


> You've said that azure functions doesn't know or control which distro a user wants to use. Its entirely possible for a user to choose a distribution that ignores OTEL_RESOURCE_ATTRIBUTES, and the azure functions implementation would be powerless to ensure those attributes are present. Just as its entirely possible for a user to choose a distribution to ignore OTEl_RESOURCE_ATTRIBUTES, a user can choose to set a new env var OTEL_CONFIG_FILE which changes the behavior of existing env vars.

Virtually all OTel SDKs support OTEL_SERVICE_NAME and OTEL_RESOURCE_ATTRIBUTES env vars. Distro that choses to ignore them would not have a great experience on Azure functions (AWS lambda or in otel-operator). there are problems now, but this proposal would make things worse. From supported virtually everywhere, env vars would be degraded to "supported until user accidentally opts opt"

> back-compat

The subject of back-compat is cloud providers, not users here. The breaking change affects them. Users would opt-in without realizing that it will break their cloud provider integration with otel.


I want to emphasize, that I don't understand why this is necessary. Why we can't make critical env vars work. I understand there was a procedure a decision was made. I respect the decision and the procedure, but I feel it's easy to accommodate my feedback. I also feel that if we did it we provided much better integration and user experience. 
So I feel like my feedback is being dismissed only because the procedure/vote has already happened and not because of any other substantial reasons.

2024-03-20 16:44 UTC, lmolkova commented
> I think its more correct to frame your argument as: merging the set of env vars which can be cleanly merged is a better user experience and that this improved user experience should be given high priority as an evaluation criteria. Framing it as "not doing this is breaking" while cherry-picking which env vars it applies to is self-contradicting.

I'm glad you've heard me. Let's frame it as overarching "better user experience" if it makes my point more understandable.

2024-03-21 03:29 UTC, RohitRanjanMS commented
Hello @jack-berg , I'm part of the Azure Functions team, and we're currently adding support for OpenTelemetry. Our architecture consists of a host process and a worker process, with customer code running in the worker process. We handle the host process, while customers have full control over the worker process.

In the host process, we are developing providers for logs, traces, and metrics that will send telemetry data to the OTLP endpoint. This setup is influenced by environment variables that signal us to connect the OTLP exporter and resources. We expect customers to set up something similar in the worker process. 

The configuration seems promising, aiming to offer customers more flexibility in setting up providers in the host process. I appreciate the convenience of using both configuration files and environment variables simultaneously. For instance, customers can use configuration files to establish providers and environment variables like OTEL_EXPORTER_OTLP_ENDPOINT for setting the endpoint. Unlike configurations, environment variables are accessible in both host and worker processes.

However, the proposed changes could significantly affect our implementation. If customers switch to using configurations by setting OTEL_CONFIG_FILE, it might disrupt the host process. We will have to come-up with a solution to resolve the conflict between config and env variables.

I understand the complexities and reasons behind your proposal, but it could significantly complicate our operations. Ideally, I'd like to see a solution where both environment variables and configuration files can exist together.

2024-03-21 08:51 UTC, marcalff commented
> If customers switch to using configurations by setting OTEL_CONFIG_FILE, it might disrupt the host process.

Could you provide more details on this ?

Once the `OTEL_CONFIG_FILE` feature, namely parsing a configuration from yaml, is supported in every language SIG SDK, why would this host process be impacted in particular ?

2024-03-21 19:17 UTC, RohitRanjanMS commented
Hi @marcalff , environment variables are accessible by both the host and worker processes. If the customer chooses to use OTEL_CONFIG_FILE, the OTel SDK operating within the host process will disregard all OTEL related environment variables.

2024-03-21 20:27 UTC, jack-berg commented
@RohitRanjanMS I don't understand the problem. I'll summarize my understanding, and leave you to correct anything I misinterpret:

- The architecture runs two processes: 1. Host process managed by azure. 2. Worker process running user code.
- Env vars are shared between these two processes.
- The host process detects whether `OTEL_EXPORTER_OTLP_ENDPOINT` (and other `OTEL_*` env vars) is set. If so, the host process exports telemetry data according to these env vars. This allows the host process and worker process to export telemetry data according to the same config.
- If a user sets `OTEL_CONFIG_FILE` to configure the worker process and stops setting other `OTEL_*` env vars, then the host process won't be able to export telemetry according to config in `OTEL_CONFIG_FILE` because it can't access the file contents. As a result, the telemetry export config between the host process and worker process will diverge. 

Is that right?

2024-03-21 21:29 UTC, lmolkova commented
BTW I just realized that `OTEL_CONFIG_FILE` is experimental. Even if could providers could access the file and could do the merge conflict resolution that otel cannot, you can't reasonably tell ~~them~~ us to implement the integration until the config is stable.

And also I realized that the full backward compatibility through default values results in this config (please correct me if I'm wrong)

Do you expect all users to keep it?!

```yaml
file_format: "0.1"
disabled: ${OTEL_SDK_DISABLED:-false}
resource:
  attributes:
    service.name: ${OTEL_SERVICE_NAME:-unknown_service}

attribute_limits:
  attribute_value_length_limit: ${OTEL_ATTRIBUTE_VALUE_LENGTH_LIMIT}
  attribute_count_limit: ${OTEL_ATTRIBUTE_COUNT_LIMIT:-128}

propagator:
  composite: [tracecontext, baggage]

tracer_provider:
  processors:
    - batch:
        schedule_delay: ${OTEL_BSP_SCHEDULE_DELAY:-5000}
        export_timeout: ${OTEL_BSP_EXPORT_TIMEOUT:-30000}
        max_queue_size: ${OTEL_BSP_MAX_QUEUE_SIZE:-2048}
        max_export_batch_size: ${OTEL_BSP_MAX_EXPORT_BATCH_SIZE:-512}
        exporter:
          otlp:
            protocol: ${OTEL_EXPORTER_OTLP_PROTOCOL:-http/protobuf}
            endpoint: ${OTEL_EXPORTER_OTLP_PROTOCOL:-http://localhost:-4318}
            certificate: ${OTEL_EXPORTER_OTLP_CERTIFICATE}
            client_key: ${OTEL_EXPORTER_OTLP_CLIENT_KEY}
            client_certificate: ${OTEL_EXPORTER_OTLP_CLIENT_CERTIFICATE}
            compression: ${OTEL_EXPORTER_OTLP_COMPRESSION:-gzip}
            timeout: ${OTEL_EXPORTER_OTLP_TIMEOUT:-10000}
  limits:
    attribute_value_length_limit: ${OTEL_SPAN_ATTRIBUTE_VALUE_LENGTH_LIMIT}
    attribute_count_limit: ${OTEL_SPAN_ATTRIBUTE_COUNT_LIMIT:-128}
    event_count_limit: ${OTEL_SPAN_EVENT_COUNT_LIMIT:-128}
    link_count_limit: ${OTEL_SPAN_LINK_COUNT_LIMIT:-128}
    event_attribute_count_limit: ${OTEL_EVENT_ATTRIBUTE_COUNT_LIMIT:-128}
    link_attribute_count_limit: ${OTEL_LINK_ATTRIBUTE_COUNT_LIMIT:-128}

meter_provider:
  readers:
    - periodic:
        interval: ${OTEL_METRIC_EXPORT_INTERVAL:-60000}
        timeout: ${OTEL_METRIC_EXPORT_TIMEOUT:-30000}
        exporter:
          otlp:
            protocol: ${OTEL_EXPORTER_OTLP_PROTOCOL:-http/protobuf}
            endpoint: ${OTEL_EXPORTER_OTLP_PROTOCOL:-http://localhost:-4318}
            certificate: ${OTEL_EXPORTER_OTLP_CERTIFICATE}
            client_key: ${OTEL_EXPORTER_OTLP_CLIENT_KEY}
            client_certificate: ${OTEL_EXPORTER_OTLP_CLIENT_CERTIFICATE}
            compression: ${OTEL_EXPORTER_OTLP_COMPRESSION:-gzip}
            timeout: ${OTEL_EXPORTER_OTLP_TIMEOUT:-10000}
            temporality_preference: ${OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE:-cumulative}
            default_histogram_aggregation: ${OTEL_EXPORTER_OTLP_METRICS_DEFAULT_HISTOGRAM_AGGREGATION:-explicit_bucket_histogram}

logger_provider:
  processors:
    - batch:
        schedule_delay: ${OTEL_BLRP_SCHEDULE_DELAY:-1000}
        export_timeout: ${OTEL_BLRP_EXPORT_TIMEOUT:-30000}
        max_queue_size: ${OTEL_BLRP_MAX_QUEUE_SIZE:-2048}
        max_export_batch_size: ${OTEL_BLRP_MAX_EXPORT_BATCH_SIZE:-512}
        exporter:
          otlp:
            protocol: ${OTEL_EXPORTER_OTLP_PROTOCOL:-http/protobuf}
            endpoint: ${OTEL_EXPORTER_OTLP_PROTOCOL:-http://localhost:-4318}
            certificate: ${OTEL_EXPORTER_OTLP_CERTIFICATE}
            client_key: ${OTEL_EXPORTER_OTLP_CLIENT_KEY}
            client_certificate: ${OTEL_EXPORTER_OTLP_CLIENT_CERTIFICATE}
            compression: ${OTEL_EXPORTER_OTLP_COMPRESSION:-gzip}
            timeout: ${OTEL_EXPORTER_OTLP_TIMEOUT:-10000}
  limits:
    attribute_value_length_limit: ${OTEL_LOGRECORD_ATTRIBUTE_VALUE_LENGTH_LIMIT}
    attribute_count_limit: ${OTEL_LOGRECORD_ATTRIBUTE_COUNT_LIMIT:-128}
```

2024-03-21 21:40 UTC, jack-berg commented
> BTW I just realized that OTEL_CONFIG_FILE is experimental.

Its not even experimental! It doesn't exist at all yet! 😁 But yes, file configuration as a whole is still experimental. That's part of the motivation behind the "wait and see" approach of this PR. Since its experimental, we'd be free to evolve the spec if there is strong user feedback.

> And also I realized that the full backward compatibility with existing env vars results in this config (please correct me if I'm wrong)
> Do you expect all users to keep it?!

Not full backwards compatibility - see this [list of env vars not referenced](https://github.com/jack-berg/opentelemetry-configuration/blob/3681cdce4502bc1a9d643e155834ed44d038de16/examples/sdk-config.yaml#L18-L39). Its true that not all users will keep it. The idea is that by providing a starter template [complete with comments describing the env var behavior](https://github.com/jack-berg/opentelemetry-configuration/blob/3681cdce4502bc1a9d643e155834ed44d038de16/examples/sdk-config.yaml#L4-L16), and funneling users to it by referencing prominently in docs and bundling it with distributions, that it will be harder for users to misinterpret. I.e. most users should intuit that explicitly deleting a reference to `${OTEL_SDK_DISABLED:-false}` will cause `OTEL_SDK_DISALBED` to be ignored.

2024-03-21 21:58 UTC, lmolkova commented
> Its not even experimental! It doesn't exist at all yet! 😁 But yes, file configuration as a whole is still experimental. That's part of the motivation behind the "wait and see" approach of this PR. Since its experimental, we'd be free to evolve the spec if there is strong user feedback.

Yeah and I'd be totally ok with "wait and see" approach if we didn't have existing specific cases where it would be problematic. 
Or if the spec language would tell that existing integrations that rely on a TBD list of env vars, will be able to keep using them regardless of user choice to opt in into the config. 

>  I.e. most users should intuit that explicitly deleting a reference to ${OTEL_SDK_DISABLED:-false} will cause OTEL_SDK_DISALBED to be ignored.

So I'm a user. I look into these 70 lines of config and keep only the things I care about, which could be something like 

```yaml
file_format: "0.1"
disabled: ${OTEL_SDK_DISABLED}
resource:
  attributes:
    service.name: ${MY_SERVICE_NAME}

tracer_provider:
  processors:
    - batch:
        exporter:
          otlp:
            protocol: protobuf
            endpoint: http://localhost:-4318
            client_key: ${OTEL_EXPORTER_OTLP_CLIENT_KEY}

meter_provider:
  readers:
    - periodic:
        interval: 5000
        exporter:
          otlp:
            protocol: protobuf
            endpoint: http://localhost:-4318
            client_key: ${OTEL_EXPORTER_OTLP_CLIENT_KEY}
            default_histogram_aggregation: explicit_bucket_histogram

logger_provider:
  processors:
    - batch:
        exporter:
          otlp:
            protocol: protobuf
            endpoint: http://localhost
            client_key: ${OTEL_EXPORTER_OTLP_CLIENT_KEY}
```


Now I have an incident, and I realize I need to specify `OTEL_BSP_MAX_QUEUE_SIZE`. 

1. In my environment changing env vars is significantly easier than redeploying the config (not a rare case_
2. I didn't read the docs or forgot that config overwrites everything - I try adding `OTEL_BSP_MAX_QUEUE_SIZE` env var and restarting my service - it does not help
3. Or even if I read the docs, now I need to redeploy the config

Isn't it enough evidence that env var support is kinda necessary?

2024-03-21 22:26 UTC, lmolkova commented
Back-compat path forward I can think of is the following:
- In presence of any existing `OTEL_` env var the config is ignored - there is a warning that tell users they have a conflict.
- We agree that we need spend more time figuring out env var story: we might want to deprecate some and figure out merge conflict issues.
- Once we figure out the story for variable X, we allow it to coexist with the config. 
- Eventually we get to the point that we only have env vars that interop with the config well.

2024-03-21 22:27 UTC, jack-berg commented
At this point we're repeating the same conversations that have taken place the the config SIG pretty much verbatim. See my explanation to this critique in the [recommendation post](https://github.com/open-telemetry/opentelemetry-specification/issues/3752#issuecomment-1995582317):

> Users looking for env var overrides of YAML config shouldn’t be too surprised. Kubernetes users are familiar with manifest files to express config. And while there’s a syntax for patching resources, in my experience (Jack Berg) it’s unintuitive and I haven’t heard people using it in their workflows. The collector pretty exclusively uses file based configuration. There is a syntax for overriding select properties, but I haven’t heard of people using it and had to dig into source code to find out how it works, so I assume it’s not popular. Modern users of systems like kubernetes are quite familiar with using [ConfigMaps](https://kubernetes.io/docs/concepts/configuration/configmap/) to define configuration and mount the content in a file in a deployment. Modifying a ConfigMap which is maintained alongside your kubernetes env vars, and redeploying is a hardly different workflow than modifying env vars. And with option 2.b, there will be much less surprise since there is no error prone merge or new complex env var override syntax. What you see is what you get.

Also note that the long term goal is to use file config as the format for dynamic SDK config via OpAmp. Uses should be able to remotely manage their SDK config without any sort of reploy, env var update, etc.

2024-03-21 22:33 UTC, lmolkova commented
somehow your reply

>Users looking for env var overrides of YAML config shouldn’t be too surprised. Kubernetes users...

does not take existing configuration systems into account - MicroProfile, ASP.NET Core. I can find more examples when many users will be REALLY surprised that env vars are not interoperable with the config.

Also, it ignores the fact that configuration comes from multiple places - cloud provides, application configs, application code and conflict resolution is inevitable.

You can't control whether user apps can be configured dynamically or not - this is up to the application. But env vars is extremely poplar and easy way to configure apps - why sacrifice it to enable something that it's much less popular?

2024-03-21 22:47 UTC, lmolkova commented on specification/configuration/sdk-environment-variables.md
> +| OTEL_CONFIG_FILE | The path of the configuration file used to configure the SDK. If set, the configuration in this file takes precedence over all other SDK configuration environment variables. |
would something like this unblock the config work and allow us to spend more time figuring out interop story?

```suggestion
| OTEL_CONFIG_FILE | The path of the configuration file used to configure the SDK. It's mutually exclusive with all other SDK configuration environment variables. If any stable environment variable is provided, the config is ignored. |         | See below |
```

2024-03-21 23:51 UTC, marcalff commented on specification/configuration/sdk-environment-variables.md
> +| OTEL_CONFIG_FILE | The path of the configuration file used to configure the SDK. If set, the configuration in this file takes precedence over all other SDK configuration environment variables. |
Doing this de facto kills any environment variable substitution done from the config.yaml file itself.

The SDK can not refuse to use the config file because OTEL_EXPORTER_OTLP_PROTOCOL is set, and at the same time load the config file which contains:

```
            endpoint: ${OTEL_EXPORTER_OTLP_PROTOCOL:-http://localhost:-4318}
```

2024-03-22 00:00 UTC, lmolkova commented on specification/configuration/sdk-environment-variables.md
> +| OTEL_CONFIG_FILE | The path of the configuration file used to configure the SDK. If set, the configuration in this file takes precedence over all other SDK configuration environment variables. |
See my comment here - https://github.com/open-telemetry/opentelemetry-specification/pull/3948#issuecomment-2013958967

This is a first step to make env vars and config work together. 
I hope I explained why it's important and I hope eventually we can find a way for them to interop.

For now, env vars are stable and easy to use. The config is experimental. New experimental feature should not affect what's already working.

2024-03-22 00:13 UTC, lmolkova commented on specification/configuration/sdk-environment-variables.md
> +| OTEL_CONFIG_FILE | The path of the configuration file used to configure the SDK. If set, the configuration in this file takes precedence over all other SDK configuration environment variables. |
Another approach: ignore the config whenever conflict is detected as a first step - this way back-compat with env vars is guaranteed.
Over time this can change to a different conflict-resolution mechanism. But then changes and damage from them is self-contained within the experimental part of the spec and does not affect how stable parts of the spec work.

2024-03-22 01:44 UTC, jack-berg commented
> somehow your reply does not take existing configuration systems into account

I can assure you your arguments are not lost on me or new to me. I've made them myself: In #3840 I argued for merging env vars. In #3850 I argued for introducing a new env var scheme allowing users to precisely target any node in YAML, and used ASP.NET Core, Java Spring, and others as [examples of prior art](https://docs.google.com/document/d/1yPfdf6fsxWY7onWU_PLmIIPs14H6pTYbyI7OboiODCw/edit?pli=1#heading=h.e4090qtl530) for the syntax.

The problem with merging existing environment variables, in a nutshell:
- For certain env vars (more than you think), there is no merge logic which is intuitive.
- This mean we're stuck either merging all env vars including the unintuitive ones, or merging some env vars excluding those which are unintuitive.
  - If we merge all, then we don't actually have backwards compatibility - we have a crude attempt at compatibility which breaks down when you give it more than a passing glance. You keep setting the same env vars, but the behavior changes. Its the worst of both worlds: You write a config file and are find materially different and surprising behavior at runtime as someone else overrides the config with env vars. OR you write a config file, try to override it at runtime, and are surprised because the env vars don't interop in the way you thought they would. 
  - If we merge some, then users using ones that are skipped will raise hell because as you mention, they won't read the docs. What's the litmus test for why we merged one but not another? You might say that its the important ones that have an intuitive merge semantic, but looking closer would show that there are quite important ones with no intuitive merge (i.e. `OTEL_EXPORTER_OTLP_ENDPOINT`). If we only merge the ones with an intuitive merge, there will be so few remaining that we'll ask why we even bothered in the first place.
- And what about the parts of file config that have no equivalent env vars? We've set users up to expect env var overrides, but won't be able to break the modeling mismatch between flat env vars and structured YAML. And so file config will be constantly dragged down with continuous questions about whether each new property needs an equivalent env var, and whether the property should be modeled in a suboptimal way for a better env var interop story. 
- The existing env vars were designed sloppily. You can see this plainly when you compare them to the programmatic surface area and find glaringly obvious mismatches with concepts. The env var moratorium in favor of defining file config is a tacit acknowledgement subpar design. We can double down on them and let good money follow bad money, or evolve to a better future. If user feedback dictates we absolutely need env var overrides, then we should start with a clean slate with something like #3850, and have a syntax that is derived from the model and exhaustive.

> Also, it ignores the fact that configuration comes from multiple places - cloud provides, application configs, application code and conflict resolution is inevitable.

We can not and should not attempt to have SDK implementations of file config be fully exhaustive of all the complex config scenarios that are out there. We need to solve _most_ use cases easily, while providing escape hatches for the others. To this end, file config was designed with components that can be composed together. The `parse` operation reads YAML and produces an in memory configuration model. You can modify this model, or produce it from other formats, or take two models and define a merge semantic, etc, etc. Its all very flexible because the `create` operation accepts a configuration model and spits out configured SDK components. If the simple flow of setting `OTEL_CONFIG_FILE` doesn't work for your situation, customize away. But even `OTEL_CONFIG_FILE` (as defined in this PR) has extensibility in mind, since there's language to allow SDKs to provide hooks for customizing the parsed model before calling `create`. And if all this flexibility isn't enough, there's always the programmatic APIs.

2024-03-22 10:06 UTC, tigrannajaryan commented
@RohitRanjanMS can you please provide more details about how the host/worker processes use OTEL_ env variables? It is not entirely clear to me how it all works.

2024-03-22 10:27 UTC, marcalff commented
When talking about existing environment variables, I think it is beneficial for this discussion to reset expectations, and take a hard look at the situation today.

For example, the [spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/exporter.md#configuration-options) defines a variable `OTEL_EXPORTER_OTLP_TRACES_INSECURE`.

This variable is a boolean ... how hard could it be to evaluate a boolean ?

This is the actual code in opentelemetry-cpp that evaluates it.

https://github.com/open-telemetry/opentelemetry-cpp/blob/a799f4aed9c94b765dcdaabaeab7d5e7e2310878/exporters/otlp/src/otlp_environment.cc#L78-L95

https://github.com/open-telemetry/opentelemetry-cpp/blob/a799f4aed9c94b765dcdaabaeab7d5e7e2310878/exporters/otlp/src/otlp_environment.cc#L210-L266

The result is actually mind blowing.

It takes:

* `OTEL_EXPORTER_OTLP_TRACES_ENDPOINT`
* `OTEL_EXPORTER_OTLP_ENDPOINT`
* `OTEL_EXPORTER_OTLP_TRACES_INSECURE`
* `OTEL_EXPORTER_OTLP_INSECURE`
* `OTEL_EXPORTER_OTLP_TRACES_SSL_ENABLE`
* `OTEL_EXPORTER_OTLP_SSL_ENABLE`

including parsing for the internal format (`http:` or `https:`) of some variables, to decide a boolean value, not to mention the arcane priority rules.

Over time, there was a good reason for each changes that lead to this state.

As the saying goes, the road to hell is paved with good intentions.

Meanwhile, opentelemetry-java does not even support `OTEL_EXPORTER_OTLP_TRACES_INSECURE`, because it requires the `http:` or `https:` scheme to be present, even for gRPC endpoints.

```
| otel.exporter.otlp.endpoint                              | OTEL_EXPORTER_OTLP_ENDPOINT                              | The OTLP traces, metrics, and logs endpoint to connect to. Must be a URL with a scheme of either `http` or `https` based on the use of TLS. If protocol is `http/protobuf` the version and signal will be appended to the path (e.g. `v1/traces`, `v1/metrics`, or `v1/logs`). Default is `http://localhost:4317` when protocol is `grpc`, and `http://localhost:4318/v1/{signal}` when protocol is `http/protobuf`.                                          |
```

This is a deviation from the specs, although I agree it makes a lot of sense.

The end result is that:

* a given configuration, expressed with environment variables, is not portable from one SIG SDK to another: there is no portability here.
* there is no hope to provide a reasonable mapping to anything from existing SDK environment variables, and the issue here is not what to map to (config.yaml) but really what to map from (confusing variables with complex dependencies and priorities)

What this work proposes is instead:

```yaml
tracer_provider:
  processors:
    - batch:
      exporter:
        otlp:
          insecure: false
```

or

```yaml
tracer_provider:
  processors:
    - batch:
      exporter:
        otlp:
          insecure: true
```

Setting a boolean to `true` or `false` looks like a sane way to set a boolean.

So that, this is what the part "Define OTEL_CONFIG_FILE to ignore other env vars" from the PR title actually means.

For use cases when the insecure flag is not hard coded but needs to be decided elsewhere, the syntax also allows:

```yaml
tracer_provider:
  processors:
    - batch:
      exporter:
        otlp:
          insecure: ${OTEL_EXPORTER_OTLP_TRACES_INSECURE:-false}
```

This is what the part "add env var substitution default syntax" from the PR title means.

The `OTEL_CONFIG_FILE` provides extra architectural qualities that are not fully taken into account in my opinion.

First, there is a json schema for the configuration file, which is common to every SDK implementation.

Enforcing that every SDK supports the same schema is much more effective to guarantee interoperability between languages, compared to tracking specifications, specification changes, and the compatibility matrix for every SIG SDK.

The later has clearly failed, as seen in the cpp / java discrepancy here.

Second, it is much simpler for an end-user to understand which environment variable is used here:

What you see in the yaml file:

```
          insecure: ${OTEL_EXPORTER_OTLP_TRACES_INSECURE:-false}
```

is what you get at runtime.

Both are huge improvements compared to the current state, in my opinion.

2024-03-22 17:32 UTC, lmolkova commented
Let me try to summarize my understanding:
- there is a number of env vars we can't find a perfect conflict resolution mechanism for
- if we designed env vars from the scratch, we would do it differently (and probably won't do some of them at all)
- we don't want to provide env vars for every possible config option
(missed something important?)

My interpretation of the current approach:  as a solution to this problems
- we want to ignore some env vars that can't interop with the config if config is chosen
- we don't want to do conflict resolution and want users to explicitly tell how to use env vars in config
- we don't want to introduce new env vars for future properties

-----
My side of the story: the outcome is also not great
  - 70 lines of boiler plate config that does not include future env vars and that I'd try to clean up if I was a user the moment I see it
  - no consistent env vars - anyone using config can ignore `OTEL_` names and do random stuff
  - existing integrations will need to change
  - and it will be much-much-much harder to do native integration for cloud providers than today. 
-----
The approach I'm suggesting:
- start with no conflict resolution (this is the first step, not an eventual state): 
  - if there is a conflict (e.g. the `OTEL_RESOURCE_ATTRIBUTES` is present and the config is present too) - ignore the file, warn, use what's in the env var
- next step: decide what to do with `OTEL_RESOURCE_ATTRIBUTES`
  - can we find not perfect but reasonable conflict resolution for it?
    - yes: it stays. We can either merge values, or decide on the priority if there is a collision. 
      -  My position: while config is experimental, it should always have lower priority. It can change during stabilization process. Motivation: if user opted into the experimental config, all issues with it should be obvious to them. They should be ready to do more work to make it work (i.e. remove `OTEL_RESOURCE_ATTRIBUTES`)
    - no, we can't find reasonable conflict resolution: - we're deprecating env var
      - we can come up with a new env var or some other substitute
      - we need to keep cloud provider integration in mind and have a prototype showing how it will work. The complexity of native cloud provider integration should be taken into account.

-----
The eventual state as I see it:
  - there are some core env vars that survive the above process. They are sufficient for common cloud provider integrations.
  - we can add more as long as there is a good interop story with the config (not 70 lines of the boilerplate that also ignores future additions)
  - we don't try to add env var for all config properties

2024-03-22 17:55 UTC, lmolkova commented on specification/configuration/sdk-environment-variables.md
> +| OTEL_CONFIG_FILE | The path of the configuration file used to configure the SDK. If set, the configuration in this file takes precedence over all other SDK configuration environment variables. |
> Doing this de facto kills any environment variable substitution done from the config.yaml file itself.

would it still be necessary if there is interop with existing env vars? The placeholders are still super-cool and useful, just not as a way to interop with `OTEL_` env vars

2024-03-26 17:27 UTC, tedsuo commented
Per the spec meeting we just had, I recommend that we elevate this to the TC, but first we clean up what precisely we are asking them to decide. If we send them a hairball I fear that it risks a third round of this where the TC asks all of the same questions again. I will try to take @lmolkova's summary and see if I can boil it down even further. Please let me know what you think of this.

## Request for TC decision

### Please decide what level of platform support should be required.

There is overwhelming support for the new config syntax. However, it may break support for automatically applying ENV vars. Our concerns specifically relate to platform support (Kubernetes, Lambda, etc).

* It may be the case that users do not always know which ENV vars platforms will apply to their applications.
* It may be the case that platforms cannot be updated to provide mechanisms to keep current support.
* It may be the case that platforms will be slow to update documentation, warning users that they must change their behavior if they adopt config files.

EVIDENCE AND EXAMPLES SUPPLIED FOR THESE POINTS.

### Please pick a strategy for supporting the automatic application of ENV vars.

**No support.** 
Users must explicitly reference all ENV vars in their config files. All unreferenced ENV vars are ignored and a warning is logged.

  * This does not solve the problem of platform support. Telemetry will break unless the user understands how to apply ENV vars set by platforms.
  * In general, dropping support is a clean break from our messy world of ENV vars, which could be useful.
  * Some users may be confused and expect ENV vars to continue working.

**Partial but reliable support.** 
Resources can always be reliably set by ENV vars. Therefore, these ENV vars always continue to work. All remaining unreferenced ENV vars are ignored and log a warning, even when they are compatible with a particular config file.

  * This partially solves the problem of platform support. 
  * In general, resources can be applied to applications without needing to push new config files, which could be useful.
  * Some users may be confused and expect non-resource ENV vars.

**Complete but unreliable support.**
All ENV vars have a set path they will be applied to. If this path is invalid, the ENV var is ignored and a warning is logged.

  * This partially solves the problem of platform support. Many types of simple configurations will continue to work.
  * In general, users with simple configurations can continue to automatically apply ENV vars, which may be useful.
  * Some users may be confused about which config changes will break support for a particular ENV var.

Thank you,
    - Everyone banging their heads against this issue.

2024-03-26 19:17 UTC, reyang commented
I've added this to the upcoming TC meeting (which will happen on Mar. 27th, 2024) agenda.

2024-03-26 19:47 UTC, trask commented
I would like to conditionally approve this PR, with the following changes requested:

* Rename `OTEL_CONFIG_FILE` to `OTEL_EXPERIMENTAL_CONFIG_FILE`
  * I think this will help make it super clear to everyone that this is an opt-in experimental feature for now, allowing us to make incremental progress in this PR
* Add a TODO in the markdown somewhere to note that we are planning to eventually deprecate any env vars that don't interop with yaml config
* Add a TODO in the markdown to add (potentially new) env vars that support the existing opentelemetry operator use cases (and which do interop with yaml config): https://github.com/open-telemetry/opentelemetry-operator/blob/dab898f6bb45d654fb138eb6c4860e15ee5eb59b/pkg/constants/env.go#L18-L23

2024-03-26 20:50 UTC, lmolkova commented
> I would like to conditionally approve this PR, with the following changes requested:
> 
> * Rename `OTEL_CONFIG_FILE` to `OTEL_EXPERIMENTAL_CONFIG_FILE`
>   
>   * I think this will help make it super clear to everyone that this is an opt-in experimental feature for now, allowing us to make incremental progress in this PR
> * Add a TODO in the markdown somewhere to note that we are planning to eventually deprecate any env vars that don't interop with yaml config
> * Add a TODO in the markdown to add (potentially new) env vars that support the existing opentelemetry operator use cases (and which do interop with yaml config): https://github.com/open-telemetry/opentelemetry-operator/blob/dab898f6bb45d654fb138eb6c4860e15ee5eb59b/pkg/constants/env.go#L18-L23

thanks for putting it up, it works for me

2024-03-26 21:23 UTC, jack-berg commented
> Rename `OTEL_CONFIG_FILE` to `OTEL_EXPERIMENTAL_CONFIG_FILE`

This makes sense to me. To my knowledge, we don't have any prior art for env vars in the spec which control experimental behavior subject to change. As long as the section denoting `OTEL_EXPERIMENTAL_CONFIG_FILE` is experimental, we can later change it to `OTEL_CONFIG_FILE` when we're ready to stabilize.

> Add a TODO in the markdown somewhere to note that we are planning to eventually deprecate any env vars that don't interop with yaml config

👍 

> Add a TODO in the markdown to add (potentially new) env vars that support the existing opentelemetry operator use cases (and which do interop with yaml config): https://github.com/open-telemetry/opentelemetry-operator/blob/dab898f6bb45d654fb138eb6c4860e15ee5eb59b/pkg/constants/env.go#L18-L23

I think we ought to add a TODO to ensure that we accommodate the operator / cloud provider use cases without being prescriptive about what that looks like (i.e. don't state that its via env vars). It could be that we support this use case with env vars, or though supporting a comma separated list of config files in `OTEL_EXPERIMENTAL_CONFIG_FILE` and merging with last win semantics (note there are limitations to this that may make it not suitable), or though some other mechanism. I agree with needing to ensure we support it - not convinced its not supported with this PR as is, but open to learning more and being wrong.

2024-03-27 05:55 UTC, tedsuo commented
I've updated my [TC request](https://github.com/open-telemetry/opentelemetry-specification/pull/3948#issuecomment-2021052830) to include evidence provided by @lmolkova.

2024-03-27 06:48 UTC, lmolkova commented
> I agree with needing to ensure we support it - not convinced its not supported with this PR as is, but open to learning more and being wrong.

Thank you for the confirmation @jack-berg! If you could call it out explicitly, it would be great. The worst that could happen is that the note would be redundant.

2024-03-27 14:52 UTC, tigrannajaryan commented
@lmolkova if you know can you clarify the part about how host/work processes in Azure functions work and how exactly they currently use OTEL_ env variables? I don't fully understand it and I think it is important to know so that we can support it properly going forward.

2024-03-27 17:51 UTC, lmolkova commented
> @lmolkova if you know can you clarify the part about how host/work processes in Azure functions work and how exactly they currently use OTEL_ env variables? I don't fully understand it and I think it is important to know so that we can support it properly going forward.

Here's my understanding of what Azure Functions are implementing:
- Functions populate OTEL_SERVICE_NAME and OTEL_RESOURCE_ATTRIBUTES to set [FaaS and Cloud resource attributes](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/resource/faas.md). 
  - It's possible to avoid using those and write a detectors, but Azure Functions are available for [many languages](https://learn.microsoft.com/en-us/azure/azure-functions/supported-languages?tabs=isolated-process%2Cv4&pivots=programming-language-csharp#language-support-details) and having to create detectors in each language is a lot of work
- Users can override env vars and/or configure OpenTelemetry in the code or Function config files
- Functions support two modes: in-process (.NET only) and isolated worker process (any language).  In case of isolated worker, the telemetry comes from both - the host AND worker process.
  - If isolated mode is used:
    - users can't provide config file and could only express configuration as env vars.
    - users can do anything they want in the isolated process - configure otel, etc

Assuming user opts into file config (in the current version of this PR):
- they can't do it consistently for the host and worker process - host does not support adding files. Worker files are not visible to the host process in a general case (e.g. you can run your worker process [in a container](https://learn.microsoft.com/en-us/azure/azure-functions/functions-how-to-custom-container?tabs=core-tools%2Cacr%2Cazure-cli2%2Cazure-cli&pivots=azure-functions))
- `OTEL_RESOURCE_ATTRIBUTES` will be ignored along with other env vars that [don't have any mapping](https://github.com/jack-berg/opentelemetry-configuration/blob/3681cdce4502bc1a9d643e155834ed44d038de16/examples/sdk-config.yaml#L18-L39)

---------------------------

How it could work without env vars and with file:
- Functions use OTEL_ or their own env vars to let users configure otel. 
- They create a file from these env vars
- If user provided another config, they merge two configs

Now we have other problems:
- Conceptual: 
  - OTEL_ env vars are no longer a consistent standard - why set them if you can use existing `X_MS_WEBSITE_NAME`?
  - We push conflict resolution between platform config and user config onto Functions. They might do an excellent job, but AWS will do the excellent job in a different way.  If we could not agree on it, different cloud providers would make different decisions as well.
- Technical:
  - Functions need to be able to detect that user prefers a config and at least read the userr config file. It may be solvable, but not in every case
  - Functions will need to modify the user config or create merged config and update env var to point to the new place
    - Modifying or even reading user config that may contain secrets is a questionable practice.
  - Functions will need to figure out how and if to apply isolated worker config to the host process

So while processing yaml is easy, other pieces of this story are hard. With env vars none of these problems exist today. 
Moreover, Functions don't have any alternative than to keep onboarding onto env vars even if they wanted to switch to the config since it's experimental.

I hope this makes sense. The core ask I have to configuration group is to prototype how it will work e.g. for [OTel AWS lambda integration](https://github.com/open-telemetry/opentelemetry-lambda), share with the community and seek feedback.

2024-03-27 18:13 UTC, tigrannajaryan commented
>isolated worker process (any language)

@lmolkova to clarify, in isolated mode the host process launches the worker process, injecting env variables like OTEL_SERVICE_NAME and OTEL_RESOURCE_ATTRIBUTES?

>In case of isolated worker, the telemetry comes from both - the host AND worker process.

Can you please also clarify what telemetry is the host process emitting? Does host process also use Otel SDK and emits telemetry about itself? What values does the host process use for OTEL_SERVICE_NAME and OTEL_RESOURCE_ATTRIBUTES? Are they the same values as injected into worker process or different values? Does user control what destination to use for host's telemetry or is it controlled by cloud provider?

>Worker files are not visible to the host process in a general case (e.g. you can run your worker process [in a container](https://learn.microsoft.com/en-us/azure/azure-functions/functions-how-to-custom-container?tabs=core-tools%2Cacr%2Cazure-cli2%2Cazure-cli&pivots=azure-functions)) and the file can be inside the image

I think this is a key limitation. In this case supposedly the config file provided by the user via OTEL_CONFIG_FILE should reside inside the container and [the patching approach](https://github.com/open-telemetry/opentelemetry-specification/pull/3948#issuecomment-2009901042) @jack-berg suggested seems impossible to perform for the host process since host process can't write to container's filesystem (unless the filesystem is mapped between the host and container?).

2024-03-27 18:18 UTC, RohitRanjanMS commented
Hi @tigrannajaryan 
Currently, our support extends only to ApplicationInsights, and it's implemented through a close integration between Functions and AI. 
We handle the host process, which you can think of as a service that manages the worker process. This worker process is where customers' code is executed. Customers maintain complete control over this worker process and have the liberty to instrument it as desired.
It's important to note that environment variables are shared between the Host and Worker processes, but configurations are not.
We plan to set up tracing, logging, and metrics providers in the host process using environment variables. Since these variables are shared, they can also be leveraged by customers in the worker process.
Our system looks for either an ApplicationInsights connection string or an OTEL endpoint in the environment variables. Depending on what is found, we then connect to the appropriate exporter.

2024-03-27 18:20 UTC, lmolkova commented
> @lmolkova to clarify, in isolated mode the host process launches the worker process, injecting env variables like OTEL_SERVICE_NAME and OTEL_RESOURCE_ATTRIBUTES?

AFAIK yes, but users can override/specify env vars as well

> Can you please also clarify what telemetry is the host process emitting?  Does host process also use Otel SDK and emits telemetry about itself? 

Host process is doing work on behalf of worker process. E.g. worker can return a byte array, but Function is configured to store this data in an database or object store. Or worker can be triggered by queue message and host process is the one that interacts with the queue and passes the content of the message to worker.  These things are called 'bindings' - they are part of user app, but done on behalf of user.

Host collects telemetry from these bindings using OTel instrumentation libraries and OTel SDK

> What values does the host process use for OTEL_SERVICE_NAME and OTEL_RESOURCE_ATTRIBUTES? Are they the same values as injected into worker process or different values? Does user control what destination to use for host's telemetry or is it controlled by cloud provider?

Resource attributes describe Function name (as service name), and the cloud resource. They are the same for both  processes. 
Users can control the destination - they are expected to set OTEL_EXPORTER_OTLP_ENDPOINT (once but for both processes)

2024-03-27 18:25 UTC, lmolkova commented
>> Worker files are not visible to the host process in a general case (e.g. you can run your worker process [in a container](https://learn.microsoft.com/en-us/azure/azure-functions/functions-how-to-custom-container?tabs=core-tools%2Cacr%2Cazure-cli2%2Cazure-cli&pivots=azure-functions)) and the file can be inside the image

> I think this is a key limitation. In this case supposedly the config file provided by the user via OTEL_CONFIG_FILE should reside inside the container and https://github.com/open-telemetry/opentelemetry-specification/pull/3948#issuecomment-2009901042 @jack-berg suggested seems impossible to perform for the host process since host process can't write to container's filesystem (unless the filesystem is mapped between the host and container?).

I think this is the hardest limitation, but given that there are other services, cloud meshes, instrumentations for web servers and whatnot, there could be others. We can't assume config is accessible or modifiable. 

And even if it is, I argue that softer limitations are even more severe: reading/modifying user data without explicit consent is a red flag for me and I'd have to bring it up with Microsoft legal and privacy folks to guide us if it's possible.

2024-03-28 18:11 UTC, jack-berg commented
Per @tedsuo’s [request](https://github.com/open-telemetry/opentelemetry-specification/pull/3948#issuecomment-2021052830), we discussed this issue in the 3/24/27 TC meeting and have made a decision:

Generally, we will follow [@trask’s](https://github.com/open-telemetry/opentelemetry-specification/pull/3948#issuecomment-2021332565) comment, proceeding with this PR with a few changes:

- Rename `OTEL_CONFIG_FILE` to `OTEL_EXPERIMENTAL_CONFIG_FILE`, reflecting the fact that the semantics around how the value of env var are subject to breaking changes as the file configuration spec and schema continue to evolve.
- Ensure that env vars which don’t interop with file config are deprecated when file config is ready for stabilization, reflecting that we do not want to recommend multiple competing configuration stories. This could be ensured via an explicit note in the markdown, or a blocking issue - both achieve the same effect. 
- Ensure that file config has an interop where platforms (i.e. Azure functions, otel operator, etc) contribute to config. We should proceed with [this PR](https://github.com/open-telemetry/opentelemetry-specification/pull/3948#issuecomment-2023422648) without being prescriptive about how that mechanism works. In the TC meeting, 4 distinct solutions were discussed which had different tradeoffs and limitations. It is clear that we still need to learn more about the requirements and constraints of this use case and let the findings inform the solution. The config working group should prioritize this discussion, but an answer shouldn’t block this PR. We should open a new issue to track the requirements and discuss solutions, and ensure that we treat that issue as blocking for any sort of stabilization effort (although it should ideally be solved much sooner).

I've updated this PR to reflect this decision. @open-telemetry/technical-committee, @open-telemetry/configuration-maintainers, and participants in this conversation, please take review.

2024-03-28 21:59 UTC, marcalff commented
@jack-berg nit: the PR text still contains a reference to `OTEL_CONFIG_FILE`.

2024-03-28 23:05 UTC, trask approved these changes

2024-03-28 23:05 UTC, trask commented on specification/configuration/sdk-environment-variables.md
> +ignored.
I would personally prefer not to have a starting point that references the (to be) deprecated env var names, as I think that will only further propagate the impression that those specific env vars still have some meaning.

(we could definitely provide a migration guide that contains a separate `sdk-migration-config.yaml` which references those deprecated env vars)

2024-03-29 08:07 UTC, pyohannes commented on specification/configuration/sdk-environment-variables.md
> +call [Parse](file-configuration.md#parse). The
What is the recommended behavior when `Parse` fails (if for example the specified file doesn't exist, or contains errors)?

Should SDKs raise an exception or error (which needs to be caught or otherwise stops the program), or should the program continue without initialized SDK and just try to notify the user via SDK-specific logging?

2024-03-29 12:06 UTC, carlosalberto commented on specification/configuration/sdk-environment-variables.md
> +ignored.
+1 as I also can see people being confused by this.

2024-03-29 12:06 UTC, carlosalberto approved these changes

2024-03-29 12:12 UTC, carlosalberto commented on specification/configuration/sdk-environment-variables.md
> +call [Parse](file-configuration.md#parse). The
From https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/configuration/file-configuration.md#parse

> Parse SHOULD return an error if:
> * The file doesn't exist or is invalid
> * The parsed file content does not conform to the [configuration model](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/configuration/file-configuration.md#configuration-model) schema.

2024-03-29 13:04 UTC, pyohannes commented on specification/configuration/sdk-environment-variables.md
> +call [Parse](file-configuration.md#parse). The
> Parse SHOULD return an error if:

I wonder if a call to `Parse` is necessary when `OTEL_EXPERIMENTAL_CONFIG_FILE` should be used, I'm not exactly sure how those two should work together.

As far as I understand, `Parse` requires a `file` parameter. I assume that when `Parse` is called with a valid `file` parameter, then `OTEL_EXPERIMENTAL_CONFIG_FILE` is ignored? So I wonder how SDKs should implement the usage of `OTEL_EXPERIMENTAL_CONFIG_FILE`.

2024-03-29 14:40 UTC, jack-berg commented on specification/configuration/sdk-environment-variables.md
> +ignored.
I had the same thought. Can provide both I think.

2024-03-29 15:20 UTC, jack-berg commented on specification/configuration/sdk-environment-variables.md
> +call [Parse](file-configuration.md#parse). The
> And I assume this will throw an exception if OTEL_EXPERIMENTAL_CONFIG_FILE is set to a non-existent or invalid file?

Yes, since doing so would cause an error when calling `Parse` or `Create`. Then, an application [MAY fail fast](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/error-handling.md#basic-error-handling-principles):

> The API or SDK MAY fail fast and cause the application to fail on initialization, e.g. because of a bad user config or environment, but MUST NOT cause the application to fail later at run time, e.g. due to dynamic config settings received from the Collector.

2024-03-29 15:30 UTC, lmolkova approved these changes
Non-blocking

2024-03-29 16:04 UTC, pyohannes approved these changes

2024-03-29 21:47 UTC, jack-berg commented on specification/configuration/sdk-environment-variables.md
> +MUST be ignored. Ignoring the environment variables is necessary because
I _think_ so. The arguments to ignore env vars configuration are:
- The merge with other configuration produces unintuitive results, and can't be done consistently
- "what you see if what you get" semantics is easy to wrap your head around and implement

It seems likely those same arguments would apply to other the question of merging other .NET configuration mechanisms, but I would leave it to that group to decide what is best for the ecosystem.

2024-04-01 14:57 UTC, jack-berg commented on specification/configuration/sdk-environment-variables.md
> +ignored.
I've updated https://github.com/open-telemetry/opentelemetry-configuration/pull/76 to include starter templates with and without env vars.

2024-04-01 14:59 UTC, jack-berg commented on specification/configuration/sdk-environment-variables.md
> +| OTEL_CONFIG_FILE | The path of the configuration file used to configure the SDK. If set, the configuration in this file takes precedence over all other SDK configuration environment variables. |
Resolving since the discussion has moved quite a bit since this comment.

2024-04-01 16:00 UTC, jack-berg commented
@open-telemetry/configuration-maintainers PTAL. I'll plan on merging once I get a couple of approvals from you all.

2024-04-01 16:36 UTC, dashpole approved these changes

2024-04-02 16:36 UTC, codeboten approved these changes

2024-04-04 21:50 UTC, jack-berg commented
Will merge tomorrow if there are no other comments.

2024-04-05 15:21 UTC, merged

2024-04-05 15:25 UTC, yurishkuro commented on specification/configuration/sdk-environment-variables.md
> +Users are encouraged to use the `sdk-config.yaml` (TODO: Add link when
I think it should be `otel-config.yaml`, there can be plenty of SDKs.