Remove the Jaeger Exporter
open-telemetry/opentelemetry-specification pull request #3964
Opened 2024-03-26 10:11 UTC by pellared

Fixes https://github.com/open-telemetry/opentelemetry-specification/issues/3551

Leftover after https://github.com/open-telemetry/opentelemetry-specification/pull/3567

2024-03-26 10:12 UTC, pellared commented
@marcalff  Can you double-check please?

2024-03-26 10:57 UTC, marcalff commented
> @marcalff Can you double-check please?

I tried to remove file `specification/trace/sdk_exporters/jaeger.md` before, but Yuri had concerns about preserving the content.

See https://github.com/open-telemetry/opentelemetry-specification/pull/3567#discussion_r1242479148

Please check with @yurishkuro

2024-03-26 12:21 UTC, pellared commented
> See [#3567 (comment)](https://github.com/open-telemetry/opentelemetry-specification/pull/3567#discussion_r1242479148)

>> I don't think we should delete this, rather it should be moved somewhere collector-related.

1. AFAIK Collector has also removed this exporter. CC @open-telemetry/collector-approvers 
2. Having it as listed as a Tracing SDK exporter feels wrong.

2024-03-26 13:44 UTC, marcalff commented
> > See [#3567 (comment)](https://github.com/open-telemetry/opentelemetry-specification/pull/3567#discussion_r1242479148)
> 
> > > I don't think we should delete this, rather it should be moved somewhere collector-related.
> 
>     1. AFAIK Collector has also removed this exporter. I guess the comment is outdated. CC @open-telemetry/collector-approvers
> 
>     2. Having it as listed as a Tracing SDK exporter feels wrong.

To clarify, I am fine with this cleanup, which I support, as the Jaeger exporter is no longer used.

However, I am not in a position to formally approve it, having no voice for specs.

2024-03-26 13:58 UTC, trask commented on specification/trace/sdk_exporters/jaeger.md
> -**Status**: [Stable](../../document-status.md)
another option would be to keep the doc and mark it Deprecated

2024-03-26 14:12 UTC, tigrannajaryan commented on specification/trace/sdk_exporters/jaeger.md
> -**Status**: [Stable](../../document-status.md)
+1

2024-03-26 15:22 UTC, yurishkuro requested changes
So the situation today is that because in the past OTEL needed to transform to Jaeger format we wrote this transformation spec and there is a transformer in collector-contrib matching that spec. Even though the exporters in both SDK and collector may be safely removed now, the transformer is still actively used by Jaeger itself. So the simplest solution is to move the transformer spec to the transformer dir in collector-contrib. Longer term we can consider migrating that code completely to Jaeger, but the transformer is technically a public API in the contrib, we don't know if other people are also using it. 

Requesting changes.

2024-04-02 08:47 UTC, pellared commented
@open-telemetry/collector-maintainers, what do you think of @yurishkuro proposal: https://github.com/open-telemetry/opentelemetry-specification/pull/3964#pullrequestreview-1960788192?

2024-04-02 08:48 UTC, pellared commented
@open-telemetry/collector-contrib-maintainer, what do you think of @yurishkuro proposal: https://github.com/open-telemetry/opentelemetry-specification/pull/3964#pullrequestreview-1960788192? Are you fine moving the spec to collector-contrib? If so then I think this PR should blocked until the spec is added to collector.

2024-04-02 09:03 UTC, mx-psi commented
Per our [CODEOWNERS](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/92d3e8e26335348b2607e529f29421f14b728057/.github/CODEOWNERS#L148) `pkg/translator/jaeger` is owned by @open-telemetry/collector-approvers and @frzifus. As part of said group I am in favor of moving the spec to collector-contrib for now, though personally I would like to see collector-contrib eventually be exclusively for components and move this library to some other repository

2024-04-02 14:17 UTC, yurishkuro commented
I'd be fine with hosting the lib as a standalone repo in the jaeger org. At some point, if we convert the main jaeger repo into multi-module monorepo we could move it there.

2024-04-03 06:53 UTC, pellared commented
@mx-psi I created https://github.com/open-telemetry/opentelemetry-specification/issues/3980 for tracking

2024-04-05 18:40 UTC, pellared commented
Ready to review as https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/32187 is already merged.

2024-04-05 18:43 UTC, reyang approved these changes

2024-04-06 15:01 UTC, yurishkuro approved these changes

2024-04-08 08:52 UTC, astencel-sumo approved these changes

2024-04-08 09:57 UTC, mx-psi approved these changes

2024-04-08 17:48 UTC, merged