Add Enabled method to Logger
open-telemetry/opentelemetry-specification pull request #4020
Opened 2024-04-29 19:47 UTC by MrAlias

Fixes #3917 

Knowing if a `LogRecord` will be dropped prior to performing computationally expensive operations helps developers using the Logs Bridge API avoid wasted and expensive work. This adds and `Enabled` API to the `Logger` to provide this functionality.

This is related to https://github.com/open-telemetry/opentelemetry-specification/pull/3877. In that PR `Loggers` may become entirely disabled. The `Enabled` method included here will help users determine this state.

### Prototypes

- [Go](https://pkg.go.dev/go.opentelemetry.io/otel/log#Logger)
- [Rust](https://github.com/open-telemetry/opentelemetry-rust/pull/1147)
- [C++](https://github.com/open-telemetry/opentelemetry-cpp/blob/07f6cb54ece56691dbd2a94b0cbeec722ff6a631/api/include/opentelemetry/logs/logger.h#L259)

2024-04-29 20:16 UTC, jack-berg reviewed
Nice! Was coincidentally just working on a local branch for this. I think we ought to have symmetry across metrics and traces, but fine pursuing that in a separate PR.

2024-04-29 20:16 UTC, jack-berg commented on specification/logs/bridge-api.md
> +  default behavior.
What do implementations use this for?

2024-04-29 20:16 UTC, jack-berg commented on specification/logs/bridge-api.md
> +
Should mention that callers of this API should call this method continuously since the result may change at runtime. This probably doesn't happen today, but we anticipate it happening and designed scope config to be updatable.

2024-04-29 20:34 UTC, MrAlias commented on specification/logs/bridge-api.md
> +  default behavior.
This parameter is useful to determine if some tracing information will be included. Or, in languages with more expansive definitions of context, other dynamic values included in a context (i.e. HTTP header information).

2024-04-29 20:40 UTC, reyang approved these changes
LGTM. Thanks @MrAlias!

2024-04-29 20:45 UTC, MrAlias commented on specification/logs/bridge-api.md
> +
Updated. Please take another look.

2024-04-29 22:18 UTC, jack-berg commented on specification/logs/bridge-api.md
> +At a minimum, the API MUST accept the following parameters:
Not blocking for this PR:

I wonder how this idea of the enabled API accepting arguments translates to Tracer / Meter.

2024-04-29 22:20 UTC, jack-berg commented on specification/logs/bridge-api.md
> +  default behavior.
How do you imagine an SDK utilizing these parameters? Currently, there is no way for an SDK to specify configuration based on context or severity number.

2024-04-29 23:14 UTC, MrAlias commented on specification/logs/bridge-api.md
> +  default behavior.
That's worth exploring. In Go, in the default SDK, a processor will be passed these and is responsible for responding. The SDK combine all responses. 

I could see adding this to configuration as well. 

By default, they are not used by the default SDK or No-Op SDK.

2024-04-30 02:04 UTC, yurishkuro commented on specification/logs/bridge-api.md
> +The `Logger` SHOULD provided functions to:
```suggestion
The `Logger` SHOULD provide functions to:
```

2024-04-30 07:09 UTC, pellared commented on specification/logs/bridge-api.md
> +  default behavior.
It could e.g. determine the result based on baggage

2024-04-30 07:20 UTC, dmathieu commented on specification/logs/bridge-api.md
> +generating a `LogRecord`, a `Logger` SHOULD provide this and `Enabled` API.
```suggestion
generating a `LogRecord`, a `Logger` SHOULD provide this `Enabled` API.
```

2024-04-30 14:59 UTC, jack-berg commented on specification/logs/bridge-api.md
> +  default behavior.
It looks like go [LogRecordProcessor](https://github.com/open-telemetry/opentelemetry-go/blob/main/sdk/log/processor.go#L49) interface does indeed have an `Enabled` method accepting the same argument. Couple of thoughts:

1. Do you intend to land this enabled method into the SDK specification? The proposed arguments for this new enabled method don't make sense without this corresponding functionality in the SDK. I.e. the arguments would be unused for a language that follows the spec contract for LogRecordProcessor.

2. What are the semantics for `LogRecordProcessor#Enabled`? Will a LogRecordProcessor only receive log records for which `LogRecordProcessor#Enabled` returns true? If `Logger#Enabled` is added, will it only return false if all of the registered `LogRecordProcessors#Enabled` return false?

2024-05-01 14:45 UTC, MrAlias commented on specification/logs/bridge-api.md
> +  default behavior.
> 1. Do you intend to land this enabled method into the SDK specification? The proposed arguments for this new enabled method doesn't make sense without this corresponding functionality in the SDK. I.e. the arguments would be unused for a language that follows the spec contract for LogRecordProcessor.

I would like to go that direction, yes. I don't know if adding methods to a stable SDK specification is possible though. What do you think?

> 2\. What are the semantics for `LogRecordProcessor#Enabled`? Will a LogRecordProcessor only receive log records for which `LogRecordProcessor#Enabled` returns true?

The `Enabled` method is not called by the SDK prior to sending `LogRecord`s to the processor. The intention is it is only there for the end-user. If the end-user didn't call this, but sent a `LogRecord`, it will just be passed to `OnEmit`.

>  If `Logger#Enabled` is added, will it only return false if all of the registered `LogRecordProcessors#Enabled` return false?

Correct.

2024-05-01 14:46 UTC, MrAlias commented on specification/logs/bridge-api.md
> +  default behavior.
@jack-berg to help progress this PR do you think I should just remove the argument list? Instead just say the arguments are left up to the language implementation?

My only worry there is that will result in inconsistencies across languages.

2024-05-01 14:47 UTC, MrAlias commented on specification/logs/bridge-api.md
> +At a minimum, the API MUST accept the following parameters:
I'm guessing for the trace API it would be helpful to know if the sampler is going to drop the span so maybe include those parameters there.

2024-05-01 15:42 UTC, reyang commented on specification/logs/bridge-api.md
> +At a minimum, the API MUST accept the following parameters:
Tracer - Span.IsRecording? https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#isrecording

Meter - I think instrument APIs are designed to be extremely efficient, having an extra check during each invocation will make it less efficient.

2024-05-07 15:47 UTC, lmolkova commented on specification/logs/bridge-api.md
> +At a minimum, the API MUST accept the following parameters:
`Span.IsRecording` happens too late after sampling-relevant params are colelcted

`Tracer.IsEnabled` would show that tracer instrumentation scope is enabled and can be used to avoid collecting sampling-relevant attributes as an optimization - https://github.com/open-telemetry/opentelemetry-specification/blob/821814575195dca0ff237027a4c24719e97921e6/specification/trace/sdk.md?plain=1#L167

Same on meter, collecting attributes is much more expensive than not collecting them. So I'd argue it's also important for meters.

I'd consider having somewhat consistent story for Logger/Meter/Tracer a prereq for stability

2024-05-07 20:56 UTC, jack-berg commented on specification/logs/bridge-api.md
> +At a minimum, the API MUST accept the following parameters:
> Span.IsRecording happens too late after sampling-relevant params are collected

👍 

> Same on meter, collecting attributes is much more expensive than not collecting them. So I'd argue it's also important for meters.

👍 Yes. The instrument APIs are designed to be extremely efficient. But efficiency is limited in cases where the attributes are computed at the time of measurement recorded (i.e. they are not known ahead of time and cannot be pre-allocated). In this case, checking if `meter.isEnabled()` allows the caller to avoid computing the attributes, and is therefore valuable.

2024-05-07 21:27 UTC, jack-berg commented on specification/logs/bridge-api.md
> +  default behavior.
> @jack-berg to help progress this PR do you think I should just remove the argument list? Instead just say the arguments are left up to the language implementation?

Something like that - I think we should omit the arguments and mention that arguments may be added in the future. This sends a signal to API authors that this is an open question and may change in the future without actively encouraging languages to decide their own arguments.

As discussed in the 5/7/24 spec SIG, I believe the answer to which arguments `Enabled` accepts intersects with the question of whatever solution we agree on for sampling / filtering in logs. From the perspective of a java maintainer, I'm not sure I understand the need for SDK users / processors to configure a severity level. The typical way java users use the otel log API / SDK can be seen in the docs for our [log4j2 appender](https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation/log4j/log4j-appender-2.17/library). You configure log4j2 to include the `OpenTelemetryAppender` in the XML config:
```
<?xml version="1.0" encoding="UTF-8"?>
<Configuration status="WARN" packages="io.opentelemetry.instrumentation.log4j.appender.v2_17">
  <Appenders>
    <Console name="Console" target="SYSTEM_OUT">
      <PatternLayout
          pattern="%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} trace_id: %X{trace_id} span_id: %X{span_id} trace_flags: %X{trace_flags} - %msg%n"/>
    </Console>
    <OpenTelemetry name="OpenTelemetryAppender"/>
  </Appenders>
  <Loggers>
    <Root>
      <AppenderRef ref="OpenTelemetryAppender" level="All"/>
      <AppenderRef ref="Console" level="All"/>
    </Root>
  </Loggers>
</Configuration>
```
Then in the application code, we have a helper method for installing the SDK into the `OpenTelemetryAppender` specified in the xml: `OpenTelemetryAppender.install(openTelemetrySdk)`.

This results in Log4j routing logs to otel java log API / SDK. Only logs which exceed the log level configured in the log4j xml are routed to the otel java log API / SDK. 

If we make severity based filtering a key component of the log SDK, there are two ways to accomplish the same: you can set the severity level in your upstream log config where you setup the otel appender, or you can specify the severity level in the otel log SDK. 

If you config severity level upstream in the log config, then logs lower than the severity level never make it to the log appender, which is good from a perf standpoint. If you config severity level in the otel log SDK, then we need optimizations like this to allow the appender to short-circuit logs with a low severity level. The benefit of doing it in the otel log SDK vs. the upstream log config is that an otel user can manage all of the otel related config in one place after initial configuration of the log config.

Thinking this through, I'm coming around to the go log processor design where each processor specifies the min severity level they're interested in. Some thoughts:
- Adding this `LogProcessor#Enabled` method to account for severity and not introducing a separate "sampling" concept to logs seems to best reflect the extensive prior art in the log ecosystem. Its near ubiquitous to have a severity level concept in log frameworks. I haven't come across a sampling concept in any log frameworks I've worked with. 
- In some ways it mirrors the metric SDK concept where MetricReader has the ability to specify preferences for default aggregation and aggregation temporality as a function of instrument kind. Here, LogProcessor is the analog of MetricReader and is specifying its preferences for the severity of log records its interested in.
- I think the log design is missing the ability for log processors to express different severity thresholds based on logger name / instrumentation scope. Its very common to say logs from the "foo" logger have severity level warn while logs from every other logger have severity level info.
- If we do want to add a log sampling concept, then it should probably lean into probablistic sampling concepts rather than the rule based filtering we're discussing here, where logs are deterministically included / excluded based on their severity level and scope.

What I would do:
- Introduce a new `LogProcessor#Enabled` method which accepts severity, scope, and context as argument. 
- Introduce `Logger#Enabled` which optionally accepts a severity and context argument. These are optional for the user to provide, but the API should be structured to allow them to be passed. 
- We now have scope config and `LogProcessor#Enabled` which can include `Logger#enabled`. `Logger#Enabled` returns `true` if all the following are true:
  - The logger is enabled (i.e LoggerConfig is enabled via the scope config mechanism)
  - At least one `LogProcessor#Enabled` returned true for the given severity and context arguments.
- Only call `LogProcessor#onEmit` for processors which returned true when `LogProcessor#Enabled` was called.
- Later, consider introducing a severity level property to `LoggerConfig`. Need to determine the cost / benefit of having multiple ways to config the severity level for a particular logger.

2024-05-08 14:40 UTC, jmacd commented on specification/logs/bridge-api.md
> +At a minimum, the API MUST accept the following parameters:
I agree that all providers should have an enabled method.

2024-05-10 15:34 UTC, MrAlias commented on specification/logs/bridge-api.md
> +  default behavior.
> * Introduce a new `LogProcessor#Enabled` method which accepts severity, scope, and context as argument.
> * Introduce `Logger#Enabled` which optionally accepts a severity and context argument. These are optional for the user to provide, but the API should be structured to allow them to be passed.

@jack-berg you mean to do this in the follow up PR, right?

2024-05-10 15:35 UTC, MrAlias commented on specification/logs/bridge-api.md
> +At a minimum, the API MUST accept the following parameters:
I'm going to resolve this as it is unrelated to the PR.

If we want to further discuss this, an issue can be opened.

2024-05-13 21:24 UTC, jack-berg commented on specification/logs/bridge-api.md
> +  default behavior.
> @jack-berg you mean to do this in the follow up PR, right?

Yes.

2024-05-13 21:31 UTC, jack-berg approved these changes

2024-05-13 21:31 UTC, jack-berg commented on specification/logs/bridge-api.md
> +they need. If an implementation does not need this flexibility, it SHOULD
> The ambiguity when disabled allows implementation that want to optimize memory or handle indeterminable states the flexibility they need.

This phrasing is a bit hard to understand.

2024-05-15 04:12 UTC, cijothomas commented on specification/logs/bridge-api.md
> +they need. If an implementation does not need this flexibility, it SHOULD
The return value of the `Enabled` should be `true` or `false`, reflecting whether logging is enabled for the provided arguments. To optimize memory and performance, implementations may choose not to evaluate the enablement status on every call and instead return cached values temporarily. This approach allows for efficient resource usage while maintaining functional accuracy in most scenarios.

^ Was this the intended idea?

2024-05-16 17:20 UTC, dashpole approved these changes

2024-05-21 15:13 UTC, tsloughter approved these changes

2024-05-21 15:19 UTC, jack-berg commented on specification/logs/bridge-api.md
> +for the provided arguments. The ambiguity when disabled allows implementation
```suggestion
for the provided arguments. The ambiguity when disabled allows implementations
```

2024-05-21 15:45 UTC, MrAlias commented on specification/logs/bridge-api.md
> +they need. If an implementation does not need this flexibility, it SHOULD
Updated. PTAL.

2024-05-21 15:48 UTC, trask commented on specification/logs/bridge-api.md
> +Implementations of this API SHALL return `true` when logging is enabled or
(I had to look up [what SHALL meant](https://datatracker.ietf.org/doc/html/rfc2119), at first I thought it meant SHOULD 😅)
```suggestion
Implementations of this API MUST return `true` when logging is enabled or
```

2024-05-21 16:23 UTC, MrAlias commented on specification/logs/bridge-api.md
> +Implementations of this API SHALL return `true` when logging is enabled or
I was trying to express in the future tense the requirement of the API will be returning. Saying something must return something means that it has control over that return value. Given this is an interface, and it actually doesn't decide what is returned I felt SHALL the more appropriate.

This is a valid term from RFC  2119, as you mention. Why not use it given it is providing the editorial intent and has normative value?

2024-05-21 17:34 UTC, trask commented on specification/logs/bridge-api.md
> +Implementations of this API SHALL return `true` when logging is enabled or
> Given this is an interface, and it doesn't actually decide what is returned I felt SHALL the more appropriate.
>
> Why not use it given it is providing the editorial intent and has normative value?

my only thought is that we're not doing this anywhere else in the specification: https://github.com/search?q=repo%3Aopen-telemetry%2Fopentelemetry-specification%20SHALL&type=code

maybe propose introducing SHALL consistently across the specification in this way as a separate change?

2024-05-21 17:45 UTC, MrAlias commented on specification/logs/bridge-api.md
> +Implementations of this API SHALL return `true` when logging is enabled or
I mean ... [we already did adopted this](https://github.com/open-telemetry/opentelemetry-specification/tree/main/specification#notation-conventions-and-compliance):

> The keywords "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT", "SHOULD", "SHOULD NOT", "RECOMMENDED", "NOT RECOMMENDED", "MAY", and "OPTIONAL" in the [specification](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/overview.md) are to be interpreted as described in [BCP 14](https://tools.ietf.org/html/bcp14) [[RFC2119](https://tools.ietf.org/html/rfc2119)] [[RFC8174](https://tools.ietf.org/html/rfc8174)] when, and only when, they appear in all capitals, as shown here.

I'm not really sure what to say if other authors don't use applicable keywords. I don't think it should preclude correct usage based on past mistakes. That would mean incorrect term usage is preventing correct term usage from being added, right?

2024-05-21 17:54 UTC, MrAlias commented on specification/logs/bridge-api.md
> +Implementations of this API SHALL return `true` when logging is enabled or
If we would like to change the policies of this repository regarding its notation conventions, that seems like a separate discussion. I would ask that we address that in its own Issue or PR. I think this PR should not be held up because it uses a keyword term within the scope of the already adopted policy.

2024-05-21 18:44 UTC, tigrannajaryan approved these changes

2024-05-22 07:25 UTC, marcalff commented on specification/logs/bridge-api.md
> +Implementations of this API SHALL return `true` when logging is enabled or
In https://datatracker.ietf.org/doc/html/rfc2119, `SHALL` and `MUST` are equivalent.

Now, for non English speakers, the subtle difference between `SHALL` and `SHOULD` can cause a lot of confusion in my opinion: not everyone will know the difference.

Using `SHALL` is perfectly legal according to previous decisions, but do we really need to go there ?

2024-05-22 14:22 UTC, MrAlias commented on specification/logs/bridge-api.md
> +Implementations of this API SHALL return `true` when logging is enabled or
I'm going to resolve this comment thread. I do not plan to make this change until there is a policy change, and it seems to be fueling an tangential discussion that should happen it its own Issue or PR.

2024-05-22 14:39 UTC, pellared commented on specification/logs/bridge-api.md
> +Implementations of this API SHALL return `true` when logging is enabled or
I also find that `SHALL` can be misleading. I thought that it equivalent to `SHOULD`. Can you please change to `MUST`? I find it less confusing for the readers.

2024-05-22 14:39 UTC, trask commented on specification/logs/bridge-api.md
> +Implementations of this API SHALL return `true` when logging is enabled or
@MrAlias I'm fine leaving this discussion resolved, but I'm not really clear why are you ignoring a simple feedback from 3 community members (myself @reyang and @marcalff) who are suggesting that `MUST` would be clearer to people reading the spec who are not deeply versed in RFC 2119 (which let's be honest is almost everyone), especially given that we haven't used `SHALL` anywhere else in the specification?

2024-05-22 14:45 UTC, pellared approved these changes
LGTM. 

PS. I created https://github.com/open-telemetry/opentelemetry-specification/pull/4055

2024-05-22 14:48 UTC, pellared commented on specification/logs/bridge-api.md
> +Implementations of this API SHALL return `true` when logging is enabled or
I created https://github.com/open-telemetry/opentelemetry-specification/pull/4055

2024-05-22 15:10 UTC, MrAlias commented on specification/logs/bridge-api.md
> +Implementations of this API SHALL return `true` when logging is enabled or
This, unfortunately (given it has nothing to do with this content of this PR), would set a precedence. We should not write specification to the lowest common denominator, and we should not put unnecessary restrictions on authors for things we have already agreed on and are codified in our policies.

The specification has stated we comply with RFC 2119 for many years. If "everyone" (4 out of the 536 people in the community) is not familiar with it, then at this point they need to be. It seems like a prerequisite given that is what defines our compliance requirements. By correctly using terms in our specification that those not aware of can be exposed to, these things become known. Not using the terms would just be appeasing readers ignorant of these terms and allowing them to continue in this ignorance.

As for this being the only use, there are other instances of use[^1][^2], as you pointed out in you links above.

Grammatically, using SHALL here makes more sense then MUST. MUST implies an obligation for the API that is not logically possible: it needs to ensure a return value. SHALL implies a strong assertion or intention of what is going to happen based on the API contract. I believe that is the correct English word to use here when given the choice between the two.

I am happy to discuss the grammatical significance here. I'm not looking to renegotiate our notation convention policies though. 

[^1]: https://github.com/open-telemetry/opentelemetry-specification/blob/6b5e9404a3c574c1239230d0753665b4add0b977/specification/versioning-and-stability.md?plain=1#L44
[^2]: https://github.com/open-telemetry/opentelemetry-specification/blob/6b5e9404a3c574c1239230d0753665b4add0b977/specification/versioning-and-stability.md?plain=1#L286

2024-05-23 08:18 UTC, marcalff requested changes

2024-05-23 08:18 UTC, marcalff commented on specification/logs/bridge-api.md
> +designed for performance that cache the logging state MAY return stale values.
Independently of the `SHALL` versus `MUST` discussion, this requirement is broken in my opinion.

If the implementation can return stale values, then it can return `false` when logging is enabled, correct ?

This makes it a `SHOULD` requirement, otherwise the implementation does not comply with the spec.

2024-05-23 14:28 UTC, MrAlias commented on specification/logs/bridge-api.md
> +designed for performance that cache the logging state MAY return stale values.
I think an implementation can still faithfully report `true` or  `false` based on its understanding, just its understanding may be outdated.

2024-05-23 15:24 UTC, MrAlias commented on specification/logs/bridge-api.md
> +designed for performance that cache the logging state MAY return stale values.
I have updated and removed normative statements about implementation return logic. Leaving that to the SDK specification to follow.

2024-05-23 15:32 UTC, cijothomas approved these changes

2024-05-23 15:33 UTC, cijothomas commented on specification/logs/bridge-api.md
> +SHOULD be documented that users needs to call this API each time they generate
_the users_  -- we are referring to the people who author log bridges, and *not* the end users, right?

2024-05-23 15:37 UTC, MrAlias commented on specification/logs/bridge-api.md
> +SHOULD be documented that users needs to call this API each time they generate
Correct.

2024-05-23 15:38 UTC, MrAlias commented on specification/logs/bridge-api.md
> +SHOULD be documented that users needs to call this API each time they generate
@cijothomas are you thinking something like this would be better?

```suggestion
SHOULD be documented that Logs Bridge API users needs to call this API each time they generate
```

2024-05-23 15:45 UTC, cijothomas commented on specification/logs/bridge-api.md
> +SHOULD be documented that users needs to call this API each time they generate
yes!

_SHOULD be documented that Logs Bridge API **developers** needs to call this API each time they generate_

Maybe "developers" instead of "users" is more apt!

2024-05-23 15:53 UTC, marcalff approved these changes

2024-05-23 18:18 UTC, carlosalberto approved these changes

2024-05-23 18:21 UTC, cijothomas commented
Re-requested review from @jack-berg and @reyang as the contents have changed since their approvals.

2024-05-23 19:23 UTC, jack-berg approved these changes

2024-05-23 20:45 UTC, reyang commented on specification/logs/bridge-api.md
> +SHOULD be documented that Logs Bridge API developers needs to call this API each time they generate
Is this really needed by all Logs Bridge API developers? Sounds too strong to me.
For example, if the return value is true, a developer might want to cache the value for 60 seconds before checking again (and it is okay to generate some data then drop them on the floor).

2024-05-23 22:26 UTC, MrAlias commented on specification/logs/bridge-api.md
> +SHOULD be documented that Logs Bridge API developers needs to call this API each time they generate
I think the dev can do with this information what they want. I think we need to recommend the API needs to be documented about the contract it proves though.

If an language implementation explicitly does not allow this behavior they could ignore this recommendation. It seems they would have valid reason to.

2024-05-28 15:49 UTC, jmacd approved these changes

2024-05-28 16:24 UTC, merged