Add ability for SpanProcessor to mutate spans on end
open-telemetry/opentelemetry-specification pull request #4024
Opened 2024-04-30 08:53 UTC by JonasKunz

Fixes #1089.

In addition to the comments on the issue, this was discussed in the spec SIG Meeting on 2024/23/04:
 * The filtering use-case explained in [this comment](https://github.com/open-telemetry/opentelemetry-specification/issues/1089#issuecomment-2061289086) should rather be solved by the upcoming samplerV2 instead of `SpanProcessor`s due to better conceptual fit
 * The buffering use-case also explained in [this comment](https://github.com/open-telemetry/opentelemetry-specification/issues/1089#issuecomment-2061289086) seems to be not relevant enough to influence the design decision
 * Apparently there was a discussion around building the `SpanProcessor`s in a chaining fashion during the initial SDK spec design and it was actively decided against it. However, no one could recall the reason why.
 
Based on this input, I decided to not move the chaining-based solution forward and stay with the original proposal of adding a new callback to be invoked just before a span is ended.

I also decided to name the new callback `OnEnding` instead of `BeforeEnd` as suggested in [this comment](https://github.com/open-telemetry/opentelemetry-specification/issues/1089#issuecomment-2045556103). The name `OnEnding` is more precise about when the callback is invoked.

A big discussion point in the SIG Meeting on 2024/23/04 also was the problem of evolving SDK plugin interfaces without breaking backwards compatibility. This PR contains a proposal to clarify how this should be handled: If the language allows it, interfaces should be directly extended. If not possible, implementations will need to introduce new interfaces and accept them in addition to the existing ones for backwards compatibility. I feel like this allow every language to implement changes to interfaces in the best way possible. Of course, changes to interfaces should still be kept to a necessary minimum. 

## Changes

 * Adds a new `OnEnding` callback to `SpanProcessor`
 * Add a paragraph on clarifying how languages should deal with interface extensions

* [x] Related issues #1089
* [ ] ~Related [OTEP(s)](https://github.com/open-telemetry/oteps) #~
* [x] Links to the prototypes (when adding or changing features)
   * [Java](https://github.com/open-telemetry/opentelemetry-java/pull/6367/files) (Callback is still called `beforeEnd` in that PoC)
* [ ] [`CHANGELOG.md`](https://github.com/open-telemetry/opentelemetry-specification/blob/main/CHANGELOG.md) file updated for non-trivial changes
* [ ] [`spec-compliance-matrix.md`](https://github.com/open-telemetry/opentelemetry-specification/blob/main/spec-compliance-matrix.md) updated if necessary

2024-04-30 09:07 UTC, dmathieu commented on specification/versioning-and-stability.md
> +When the major version of the SDK is bumped, the interfaces SHOULD be merged back to a single interface.
I wonder if this should be extracted into its own PR?

Also, I would be less prescriptive about how languages should handle those changes. This section is kinda specific to Go, which already did additive changes to interfaces before (the latest one being [span.AddLink](https://github.com/open-telemetry/opentelemetry-go/pull/5032)).

This is explicitly documented in Go for [the API](https://pkg.go.dev/go.opentelemetry.io/otel/trace#hdr-API_Implementations).
For me, if the Go API allows additive changes, the SDK should be able to allow them as well.

2024-04-30 09:07 UTC, dmathieu commented on CHANGELOG.md
> +  ([#4024](https://github.com/open-telemetry/opentelemetry-specification/pull/4024))
If we keep the versioning/stability change in this PR, the changelog should mention it.

2024-04-30 09:16 UTC, JonasKunz commented on specification/versioning-and-stability.md
> +When the major version of the SDK is bumped, the interfaces SHOULD be merged back to a single interface.
I've added this section due to the discussions in the SIG meeting around adding a new method to `SpanProcessor` being not possible with breaking things. If you (and the other Go folks) feel like this is not necessary, I can remove it.

2024-04-30 09:18 UTC, JonasKunz commented on CHANGELOG.md
> +  ([#4024](https://github.com/open-telemetry/opentelemetry-specification/pull/4024))
I'll wait on more input regarding the versioning/stability change and update the changelog afterwards accordingly.

2024-04-30 09:27 UTC, dmathieu commented on specification/versioning-and-stability.md
> +When the major version of the SDK is bumped, the interfaces SHOULD be merged back to a single interface.
cc @open-telemetry/go-approvers

2024-04-30 13:43 UTC, dashpole commented on specification/versioning-and-stability.md
> +When the major version of the SDK is bumped, the interfaces SHOULD be merged back to a single interface.
The Go API can make additive changes because it uses the types in the interfaces: https://pkg.go.dev/go.opentelemetry.io/otel/metric#hdr-API_Implementations.  The Go SDK does not do that, and thus cannot make additive changes to interfaces, and would need to release a v2

2024-04-30 15:01 UTC, jack-berg commented on specification/versioning-and-stability.md
> +When the major version of the SDK is bumped, the interfaces SHOULD be merged back to a single interface.
> The Go SDK does not do that, and thus cannot make additive changes to interfaces, and would need to release a v2

Or introduce a new version of the interface while retaining v1 from a versioning standpoint.

2024-04-30 16:05 UTC, dmathieu commented on specification/versioning-and-stability.md
> +When the major version of the SDK is bumped, the interfaces SHOULD be merged back to a single interface.
I think that still makes this comment too prescriptive.
How the implementation happens should be made by the SIG, in accordance with the spec and stability guarantees.

2024-04-30 16:16 UTC, jack-berg commented on specification/versioning-and-stability.md
> +When the major version of the SDK is bumped, the interfaces SHOULD be merged back to a single interface.
I agree that this is necessary (or minimally useful) but should be split out into a separate PR. I'm kind of amazed that this type of extension / evolution of an SDK plugin interface doesn't appear to have come up before. @JonasKunz can you open a new PR for this?

In terms of the language, the "Extending Existing API Calls" section above seems to be the exact type of thing we need. Maybe we find a way to generalize it so its clear that the language applies to both API and SDK evolution.

2024-04-30 16:17 UTC, jack-berg commented on specification/trace/sdk.md
> +#### OnEnding
We'll want to call this out as experimental, and stabilize after some number of languages have implemented.
```suggestion
#### OnEnding

**Status**: [Experimental](../document-status.md)
```

2024-05-02 10:09 UTC, JonasKunz commented on specification/versioning-and-stability.md
> +When the major version of the SDK is bumped, the interfaces SHOULD be merged back to a single interface.
new PR: #4030

2024-05-02 10:23 UTC, pyohannes commented on specification/trace/sdk.md
> +`OnEnding` is called just before a span is ended. The span is still mutable, but the end timestamp is already set.
> The span is still mutable, but the end timestamp is already set.

While `OnEnding` executes, can the span still be mutated by application code (running in a different thread)?

2024-05-02 10:26 UTC, JonasKunz commented on specification/trace/sdk.md
> +therefore it should not block or throw an exception.
Do you want me to
 * spec out that `SpanProcessor`s are invoked in the order they are registered
 * or explicitly state that the order is implementation dependent and users need to be aware of that?
 
Also the same thing already applies to `OnStart`, therefore I'd add this to the `SpanProcessor` interface description instead of the method definitions. The only difference here for `OnEnding` is that users also need to be aware that the span might be concurrently modified because it has already escaped into the wild (e.g. into OpenTelemetry-Contexts).

2024-05-02 10:27 UTC, JonasKunz commented on specification/trace/sdk.md
> +`OnEnding` is called just before a span is ended. The span is still mutable, but the end timestamp is already set.
Yes, that would be the case. See also https://github.com/open-telemetry/opentelemetry-specification/pull/4024#discussion_r1587402818.

2024-05-02 10:31 UTC, JonasKunz commented on specification/trace/sdk.md
> +therefore it should not block or throw an exception.
> The only difference here for OnEnding is that users also need to be aware that the span might be concurrently modified because it has already escaped into the wild (e.g. into OpenTelemetry-Contexts).

Should we maybe spec out that the SDK should prevent concurrent modifications here? E.g. the span might be modified by application code before or after `OnEnding` is invoked , but not during the invocation?

2024-05-08 14:43 UTC, jack-berg commented on specification/trace/sdk.md
> +`OnEnding` is called just before a span is ended. The span is still mutable, but the end timestamp is already set.
I think I disagree @JonasKunz. `OnEnding` should only be called once `Span.End()` is called. The [Span.End()](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#end) specification is ambiguous on whether calls to update a span are ignored after `Span.End()` is called, but in the java implementation we do ignore any subsequent updates.

When `Span.End()` is called, we should be able to:
- Atomically update the state of the span to ignore subsequent updates, whether those calls come from the thread that called `Span.End()` or another thread
- Synchronously call `SpanProcessor#onEnding()`, such that only SpanProcessors are the only thing which can update the span

Alternatively, we could flip the order, and say that when `Span.End()` is called:
- Synchronously call `SpanProcessor#onEnding()`, such that SpanProcessors and any other threads with access to the span can concurrently mutate the span
- After calling all `SpanProcessor#onEnding()`, atomically update the state of the span to ignore subsequent updates

2024-05-08 14:45 UTC, Flarna commented
What is the benefit of `onEnding()` compared to pass the read/write span to `onEnd()`?
Both are sync, both are called at the same time (within the `Span.End()` api).

To my understanding both changes are breaking for `SpanProcessor` implementers. Either they have to add a method or change the type.

2024-05-08 14:45 UTC, jack-berg commented on specification/trace/sdk.md
> +therefore it should not block or throw an exception.
> spec out that SpanProcessors are invoked in the order they are registered

This.

> Also the same thing already applies to OnStart, therefore I'd add this to the SpanProcessor interface description instead of the method definitions.

Makes sense.

> Should we maybe spec out that the SDK should prevent concurrent modifications here? E.g. the span might be modified by application code before or after OnEnding is invoked , but not during the invocation?

Let's discuss this over in the [other thread](https://github.com/open-telemetry/opentelemetry-specification/pull/4024/files#r1587399477).

2024-05-14 10:09 UTC, JonasKunz commented on specification/trace/sdk.md
> +`OnEnding` is called just before a span is ended. The span is still mutable, but the end timestamp is already set.
> When Span.End() is called, we should be able to:

> * Atomically update the state of the span to ignore subsequent updates, whether those calls come from the thread that called Span.End() or another thread
> * Synchronously call SpanProcessor#onEnding(), such that only SpanProcessors are the only thing which can update the span

Agree, I think this is the best approach. It means `SpanProcessor` implementors don't need to worry about concurrent modifications and can be sure that the state seen by the last `SpanProcessor.onEnding` is the final state of the span.

2024-05-22 07:24 UTC, LikeTheSalad commented
> In my opinion, it would be better if the changes made on-end applied to only the exporter associated with the processor making the change.

I agree that, in the spirit of keeping consistency around the expected behavior of the SDK, it does make sense to follow a similar approach for whether to make processors affect other processors vs only their associated exporter. And I think #4010  has good points on it, to be honest, the existing behavior is quite strange so I think it's great that it's being revisited there. 

However, I'm wondering if this PR is the right place to have this discussion, as it seems to affect SpanProcessors in a broader way, given that, should we decide in #4010 to switch to processors with independent pipelines, wouldn't it mean that (for SpanProcessors) we should address `OnStart()` as well? At least if we wanted to keep consistency in the overall SDK behavior anyway.

My understanding is that this PR is focusing on adding some extra functionality while keeping consistency with the existing patterns used in the rest of `SpanProcessor`, hence the "read write span" and the fact that a processor affects others down in the chain, even if it's not ideal, I think it's important to keep a consistent behavior. Now, this would also mean that, if in the future we decide to go with the changes proposed in #4010, then both `OnStart()` and `OnEnding()` should adapt to it imo.

2024-05-22 08:03 UTC, Flarna commented
I think there are usecases for both variants
* I might have two backends and enrich spans depending on the backend
* I might want to enrich spans in general

I guess something like a processing pipeline would be more flexible to allow putting one processor after the other.
This would avoid that meed to implement a `BatchEnrichingProcessor` next to a `SimpleEnrichingProcessor` just to get enrichment and batching/non batching. If there are more orthogonal functionalities this can get quite cumbersome.

There are already SpanProcessors which mutate in `onStart` without exporting, e.g. [here](https://github.com/open-telemetry/opentelemetry-js-contrib/tree/main/packages/baggage-span-processor).

2024-05-22 11:12 UTC, JonasKunz commented
> @JonasKunz I am curious to know whether you think it is essential for the on-end handler being discussed in this PR to make changes that are visible to other processors. In my opinion, it would be better if the changes made on-end applied to only the exporter associated with the processor making the change.

@jmacd In my opinion, this would remove the benefits this PR is intending to add: Making it easier for users to enrich spans in span processors before they are exported.

There is already a workaround for doing this with the existing `onEnd()` callback: Users can decorate/wrap the `SimpleSpanProcessor` / `BatchSpanProcessor` and wrap the incoming `ReadableSpan`s in order to pass the mutated ones to the span processor invoking the exporter.
We actually implemented this exact mechanism to provide a span processor which collects stacktraces as attributes for long running spans [here](https://github.com/open-telemetry/opentelemetry-java-contrib/pull/1255). The problem with this approach that it requires a big amount of boilerplate code and doesn't play well with SDK autoconfiguration. This PR was an example use-case for why we wanted to drive #1089 forward for providing a simpler, SDK-native approach for enriching spans on end.

So the problem I see with making changes in `onEnding` not visible to other users is that it again pushes the responsibility to setup bootstrap pipelines to the user.

My take here is that there are two viable classes of solutions for allowing easy enrichment of spans via the SDK:
 1. Adding a callback which mutates the actual span (like `onStart`)
 2. Adding the capability to build pipelines which pass around immutable (but wrappable) span data where the terminal stage of the pipeline is some consumer (e.g. a span exporter)

This PR specs out solution category 1.
In [this comment](https://github.com/open-telemetry/opentelemetry-specification/issues/1089#issuecomment-2061289086) I discussed both solution classes and also provided backwards-compatible PoC implementations for Java for both.
However, the arguments for 2.) seemed to not be convincing enough (this was also discussed in a spec-SIG Meeting), I went for 1. in this PR.

We can definitely revisit this decision! However, if we do go for a pipelining approach, I'd propose to rather enhance the `onEnd` callback for it instead of introducing a new `onEnding` callback.

However, if we go for the pipeline approach, I'd propose to separate the construction of processors from the assembly of the pipeline by either:
 * Passing the next pipeline stage to call on invocation as a `Function` to `onEnd`
 * Introducing a separate `init` callback which receives the next pipeline stage as a function

The reason why I'm suggesting is that if we leave the pipeline assembly to the user via decoration/wrapping, this makes the pipeline structure a blackbox for the SDK.

If instead the pipeline assembly is controlled by the SDK, it has more control over it: e.g. it could insert logging or telemetry between the pipeline stages if necessary. It also plays much better with autoconfiguration.

> However, I'm wondering if this PR is the right place to have this discussion, as it seems to affect SpanProcessors in a broader way, given that, should we decide in #4010 to switch to processors with independent pipelines, wouldn't it mean that (for SpanProcessors) we should address OnStart() as well? At least if we wanted to keep consistency in the overall SDK behavior anyway.

I'm not sure whether `onStart` is a good candidate for pipelining. Pipelines make sense if you have some consumer at the end. While `onStart` might have such consumers (e.g. creating a metric about started spans), it usually is used to mutate spans before they are visible to the user/application code. I don't see how the second aspect fits nicely into a pipeline model vs just invoking `onStart` on all `SpanProcessor`s in a loop.

2024-05-22 19:26 UTC, jack-berg commented on specification/trace/sdk.md
> +The SDK MUST guarantee that the span cannot be modified anymore by any other thread
```suggestion
The SDK MUST guarantee that the span can no longer be modified by any other thread
```

2024-05-22 19:27 UTC, jack-berg approved these changes

2024-05-23 17:39 UTC, jmacd requested changes
Thank you @JonasKunz. I understand the motivation and agree with this change. Also, you've helped me understand how the change I'm looking for can be made orthogonally.

I added suggestions because I think `OnEnd()` becomes less-well specified without adding more text, given the new and similarly-named `OnEnding()`. Presently, nothing is said about the execution model for `OnEnd()`--for example whether or not the first call to `OnEnd()` is required to return before the second processor's `OnEnd()` is called.

Reading into the `OnEnd()` text below your changes here, I find that lines 613/614 (in your change, lines 592/593 prior) are problematic, given the question posed in #4010. The `OnEnd()` callback (which I'd like to be named `OnExport()`) should not receive a mutable Span, so "modifying is not allowed" is redundant. For us to add pipeline capabilities, the `OnEnd()` callback should be allowed to change the data, which is distinct from modifying it -- only its own exporter would see the changes.

Finally, if there is desired per-pipeline processing that needs to happen when a span starts, there w

2024-05-23 17:39 UTC, jmacd commented on specification/trace/sdk.md
> +`OnEnding` is called just before a span is ended. The span is still mutable, but the end timestamp is already set.
```suggestion
`OnEnding` is called during the span `End()` operation, after the end timestamp has been set. The Span object is still mutable (i.e., `SetAttribute`, `AddLink`, `AddEvent` can be called) while `OnEnding` is called.
```

2024-05-23 17:39 UTC, jmacd commented on specification/trace/sdk.md
> +are only allowed synchronously from within the invoked `OnEnding` callbacks.
```suggestion
are only allowed synchronously from within the invoked `OnEnding` callbacks.  All registered SpanProcessor `OnEnding` callbacks are executed before the first SpanProcessor's `OnEnd` callbacks are invoked.
```

2024-05-24 11:30 UTC, JonasKunz commented
> Thank you @JonasKunz. I understand the motivation and agree with this change. Also, you've helped me understand how the change I'm looking for can be made orthogonally

@jmacd so if my understanding is correct, you are planning to add some kind of pipelining / chaining capabilities to `OnEnd` (or renamed `OnExport`), right?

I wonder if the addition of such pipelines would render the `OnEnding` callback proposed here useless and whether we should flesh out the pipelining first before moving ahead with this PR.

The main differences in terms of capabilities between `OnEnding` and the pipelining I can think of are the following:
 * `OnEnding` mutates the original span, these changes are therefore visible to anyone holding a reference to that span. I don't know if this has any effect though: The user application might be holding onto API-`Spans`, but those are write-only anyway to my understanding. So there wouldn't be any way for the application to actually observe those changes made in `OnEnding`
  * `OnEnding` is guaranteed to be executed on the application thread ending the span. We might not guarantee this for the pipeline stages
  * `OnEnding` is guaranteed to be invoked for every span (unless there is a bug in the instrumentation with dangling spans of course), this might not be the case for pipeline stages if we allow filtering there
  
So what do you think? Should we move ahead with this PR and get it merged or should we wait and check the overlap with the pipeline approach you are coming up with?

2024-05-24 15:23 UTC, jmacd commented
@JonasKunz I assumed that you mean for `OnEnding()` to receive a "read/write span object" the same as is passed to `OnStart()`. I think it means that processors can read (the data object) and write (the span object).

> OnEnding mutates the original span, these changes are therefore visible to anyone holding a reference to that span.

The requirements, as written, I think ensure that callers are not permitted to use the span reference after `End()` is called, though the processors are still permitted to via direct access from `OnEnding()`. There's a bit of conflict with:

>   It SHOULD be possible to keep a reference to this span object and updates to the span
>  SHOULD be reflected in it.

I'd probably tack on "SHOULD be reflected in it until End() is called on the Span".

For the last two bullets, I don't see a problem. I expect the OnEnd() callbacks all to execute before the export begins (a.k.a. OnEnd()).  Nothing is stated about when the OnEnd happens, but after your change it should be clear that pipelining effects (whatever they are) begin with the OnEnd call. I think OnEnding() makes sense the way you have it -- and there are real use cases so we don't need to block for future design work.

2024-05-24 15:23 UTC, jmacd approved these changes

2024-05-28 15:43 UTC, pellared submitted a review, later dismissed
I see this as [blocked](https://github.com/open-telemetry/opentelemetry-specification/pull/4024#discussion_r1585149627) by https://github.com/open-telemetry/opentelemetry-specification/pull/4030.

2024-05-29 22:11 UTC, jmacd commented
@pellared Would you say that if #4030 is accepted, this PR should be approached differently? (To me, it seems like the answer is yes.) I've speculated about what the solution might look like in https://github.com/open-telemetry/opentelemetry-specification/pull/4062#pullrequestreview-2086466483, which is briefly for SDKs to support a "FanoutProcessor" that gives users control over whether mutations are private to their export pipeline and/or visible to the next processor.

2024-05-31 16:06 UTC, tylerbenson commented on specification/trace/sdk.md
> +`OnEnding` is called just before a span is ended. The span is still mutable, but the end timestamp is already set.
I'm curious how you plan to implement this in Java.  Perhaps save the thread ID that finished the span and only allow that thread to mutate it during the `onEnding` execution with thread ID checks on each of the mutating methods?

2024-05-31 16:25 UTC, pellared commented on specification/trace/sdk.md
> +#### OnEnding
I think we should mark that this method as optional as the spec is already stable and existing SDKs may not want to immediately support this.

2024-05-31 16:28 UTC, pellared commented
> @pellared Would you say that if #4030 is accepted, this PR should be approached differently? 

I think this PR is fine and it is a logical extension. We should only highlight that processor does not need to implement the newly added method for backwards compatibility.

2024-06-03 10:19 UTC, JonasKunz commented on specification/trace/sdk.md
> +#### OnEnding
What is the correct way of marking this as optional in the spec? Should I simply add ` (optional)` to the heading or is there a standard phrase to include here like for `Experimental`?

And I guess optional means I should add it to the spec-compliance-matrix too?

2024-06-05 14:02 UTC, pellared reviewed
Suggestions per https://github.com/open-telemetry/opentelemetry-specification/pull/4061

2024-06-05 14:02 UTC, pellared commented on specification/trace/sdk.md
> +**Status**: [Experimental](../document-status.md)
```suggestion
**Status**: [Development](../document-status.md)
```

2024-06-05 14:02 UTC, pellared commented on CHANGELOG.md
> +- Add `OnEnding` callback to SDK `SpanProcessor` interface
```suggestion
- Add in-development `OnEnding` callback to SDK `SpanProcessor` interface.
```

2024-06-19 08:13 UTC, JonasKunz commented on specification/trace/sdk.md
> +#### OnEnding
@pellared friendly ping because my previous response might have gotten lost in the noise

2024-06-27 07:02 UTC, pellared commented on specification/trace/sdk.md
> +are only allowed synchronously from within the invoked `OnEnding` callbacks.  All registered SpanProcessor `OnEnding` callbacks are executed before any SpanProcessor's `OnEnd` callback is invoked.
I am not sure how and SDK can provide such guarantee. It looks like more like a hint for the user.

2024-06-27 07:51 UTC, JonasKunz commented on specification/trace/sdk.md
> +are only allowed synchronously from within the invoked `OnEnding` callbacks.  All registered SpanProcessor `OnEnding` callbacks are executed before any SpanProcessor's `OnEnd` callback is invoked.
The typical pattern to implement this would be to simply hold the lock for modifications of the span while executing the `OnEnding` callbacks. After the those are finished, the span is set to an immutable state. So if anyone concurrently tries to modify the span, they will wait on the lock and afterwards fail the modification due to the span now being immutable.

If you want concurrent modification attempts to fail eagerly, you can instead mark the span as immutable before executing the `OnEndings`. While `OnEnding` callbacks are executed a second lock is held and mutation are still allowed when a thread is holding that second lock.

I'd expect all languages dealing with concurrency to also have mutexes/locks, so I don't see why any SDK shouldn't be able to provide this guarantee? Everything else is likely to make the `OnEnding` callbacks prone to race conditions.

2024-06-27 08:34 UTC, JonasKunz commented on specification/trace/sdk.md
> +are only allowed synchronously from within the invoked `OnEnding` callbacks.  All registered SpanProcessor `OnEnding` callbacks are executed before any SpanProcessor's `OnEnd` callback is invoked.
> Exception (this would be rather against the OTel spec policy to not throw exception at runtime)

I think this would also violate the API-spec, because API methods would suddenly start throwing exceptions.

For the other two options: Do you think that this is required to be part of the spec and should not just be left to the SDK implementors to decide whats best/idiomatic? I don't really see the benefit in specifying this

2024-06-27 09:27 UTC, pellared commented on specification/trace/sdk.md
> +are only allowed synchronously from within the invoked `OnEnding` callbacks.  All registered SpanProcessor `OnEnding` callbacks are executed before any SpanProcessor's `OnEnd` callback is invoked.
> Do you think that this is required to be part of the spec and should not just be left to the SDK implementors to decide whats best/idiomatic? I don't really see the benefit in specifying this

It makes implementors think on how to do notify about giving feedback to the caller rather than just doing no-op.

Example from the same document:

> There SHOULD be a message printed in the SDK's log to indicate to the user that an attribute, event, or link was discarded due to such a limit. To prevent excessive logging, the message MUST be printed at most once per span (i.e., not per discarded attribute, event, or link).

I also want to indicate that there are operations' definitions of [the Span interface](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#span-operations). Maybe we should update the definition of https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#updatename from

> Updates the Span name. 

To e.g.

> A `Span` MUST have the ability to update its name. 

PS. I feel like this is a confusing design and I need to think more about it before approving.

2024-06-27 09:37 UTC, pellared commented on specification/trace/sdk.md
> +are only allowed synchronously from within the invoked `OnEnding` callbacks.  All registered SpanProcessor `OnEnding` callbacks are executed before any SpanProcessor's `OnEnd` callback is invoked.
Besides, I think we should add a similar paragraph/sentences to `OnStart` to keep the symmetry.

2024-06-27 10:55 UTC, JonasKunz commented on specification/trace/sdk.md
> +are only allowed synchronously from within the invoked `OnEnding` callbacks.  All registered SpanProcessor `OnEnding` callbacks are executed before any SpanProcessor's `OnEnd` callback is invoked.
> Besides, we should add a similar paragraph/sentences/requirement to OnStart to keep the symmetry.

You mean that concurrent modifications are forbidden/prevented?
I don't feel like this is necessary, because when `OnStart` is called the Span hasn't escaped into the wild (e.g. `Context`s) yet and is not accessible by application code.
Yes, one could construct an example where a `SpanProcessor` performs some task asynchronously on a span it received via `OnStart`, but that feels too constructed/unrealistic imo to be spec worthy. That would be SDK-users trying to explicitly shoot themselves into the foot which I don't think is worth the effort to prevent.

On the other side for `OnEnding`, the span can have easily escaped to other threads via `Contexts` and it is easy to accidentally try to mutate it while being added (e.g. adding some attribute to the span in the current context). So here it is easy to shoot yourself into the foot as an user, which is something we want to prevent IMO.

Regarding the logging of span mutations being NoOp after end, I feel like if you want to specify it, [this location](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#span-operations) you linked would be the correct one, because it already has a statement about mutations not being allowed after the span has ended:
> With the exception of the function to retrieve the Span's SpanContext and IsRecording, none of the below may be called after the Span is finished.

But IMO this should be done in a separate PR like you said. And IMO it shouldn't block this one.

2024-06-27 11:55 UTC, pellared commented on specification/trace/sdk.md
> +are only allowed synchronously from within the invoked `OnEnding` callbacks.  All registered SpanProcessor `OnEnding` callbacks are executed before any SpanProcessor's `OnEnd` callback is invoked.
> Yes, one could construct an example where a SpanProcessor performs some task asynchronously on a span it received via OnStart, but that feels too constructed/unrealistic imo to be spec worthy. 

One can create a batch processor which starts the batching/processing during `OnStart`. ..

> the span can have easily escaped to other threads via `Contexts` 

This is language specific. E.g. in Go context is not a global - it is passed as value to all function. So for Go SDK it is equally complex to run into the same problem for `OnStart` and `OnEnding`. 

However,  I am not certain if this is not too restrictive and if this section is even needed:

Notice that we have already in the API specification here https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#concurrency: 

> Span - All methods of Span are safe to be called concurrently.

```suggestion
All registered SpanProcessor `OnEnding` callbacks are executed before any SpanProcessor's `OnEnd` callback is invoked.
```

2024-06-27 12:35 UTC, pellared commented on specification/trace/sdk.md
> +are only allowed synchronously from within the invoked `OnEnding` callbacks.  All registered SpanProcessor `OnEnding` callbacks are executed before any SpanProcessor's `OnEnd` callback is invoked.
@jack-berg, @jmacd PTAL at my suggestion to make sure that you fine with it as you already approved the PR

2024-06-27 13:27 UTC, JonasKunz commented on specification/trace/sdk.md
> +are only allowed synchronously from within the invoked `OnEnding` callbacks.  All registered SpanProcessor `OnEnding` callbacks are executed before any SpanProcessor's `OnEnd` callback is invoked.
> > the span can have easily escaped to other threads via Contexts
>
> This is language specific. E.g. in Go context is not a global - it is passed as value to all function. So for Go SDK it is equally complex to run into the same problem for OnStart and OnEnding.

What I meant here is that to my understanding for any SDK implementation has no choice but to invoke `SpanProcessor.OnStart` synchronously during [Tracer span creation](https://opentelemetry.io/docs/specs/otel/trace/api/#span-creation). However, the resulting Span is returned from this span creation method, meaning that when `SpanProcessor.OnStart` is executed, the span has not been returned yet to the the caller creating the span.

So the only way for the span to escape to be modified concurrently while any `SpanProcessor.OnStart` is running, would be to let it escape from a `SpanProcessor.OnStart` call. This is different from `SpanProcessor.OnEnding`, because there the Tracer-API caller has already received the created span and could have passed it to an asynchronous task in any way it likes (e.g. stored on the heap anywhere or passed on the stack).

Let's take a step back on why these restrictions have been proposed:

> The SDK MUST guarantee that the span can no longer be modified by any other thread
before invoking `OnEnding` of the first `SpanProcessor`. From that point on, modifications
are only allowed synchronously from within the invoked `OnEnding` callbacks.  All registered SpanProcessor `OnEnding` callbacks are executed before any SpanProcessor's `OnEnd` callback is invoked.

The goal is not to make the Span itself concurrency safe, which

> Span - All methods of Span are safe to be called concurrently.

already does.

The goal is to provide stronger guarantees to implementors of `SpanProcessor.OnEnding`:
As an implementor you know that you are the exclusive modifier of this span and no one can override your modifications (except for SpanProcessors running after you).

Without this guarantee, it is impossible to safely code something like this in `OnEnding`:
```
if (span.getAttribute(keyA) == ABC) {
   span.setAttribute(keyB, foobar)
}
```

This would be racey, because the span could be concurrently modified between the evaluation of the`if` condition and the evaluation of the block.

In addition, saying that spans cannot be modified after `OnEnding` guarantees that the last `SpanProcessor` has the last word: The modifications done by it will define the final state of the span.

These paragraphs were added as a result of [this discussion](https://github.com/open-telemetry/opentelemetry-specification/pull/4024#discussion_r1594162897).

>> Yes, one could construct an example where a SpanProcessor performs some task asynchronously on a span it received via OnStart, but that feels too constructed/unrealistic imo to be spec worthy.

> One can create a batch processor which starts the batching/processing during OnStart. ..

But would that processor concurrently write the spans? I still fail to see a relevant enough use case for this. Like I said, this is just about the guarantees provided to `SpanProcessor` implementors, which are fine for `OnStart` as is imo.

2024-06-27 13:31 UTC, JonasKunz commented on specification/trace/sdk.md
> +`OnEnding` is called just before a span is ended. The span is still mutable, but the end timestamp is already set.
@tylerbenson sorry, I missed you comment. In this [comment](https://github.com/open-telemetry/opentelemetry-specification/pull/4024#discussion_r1656642686) I gave an outline how to do it for I think any language based on locks. For the second approach in the comment a non-blocking check of whether a Thread is holding a lock is needed (like [Thread.holdsLock](https://docs.oracle.com/javase/8/docs/api/java/lang/Thread.html#holdsLock-java.lang.Object-). If that isn't available, I guess one could use your approach of storing the thread-id and checking against it instead of a secondary lock.

2024-06-27 13:38 UTC, pellared commented on specification/trace/sdk.md
> +are only allowed synchronously from within the invoked `OnEnding` callbacks.  All registered SpanProcessor `OnEnding` callbacks are executed before any SpanProcessor's `OnEnd` callback is invoked.
> So the only way for the span to escape to be modified concurrently while any SpanProcessor.OnStart is running, would be to let it escape from a SpanProcessor.OnStart call.

Yes. If it is possible and if we are concerned about it then we should add the same restrictions in `OnStart`.

2024-06-27 13:52 UTC, JonasKunz commented on specification/trace/sdk.md
> +are only allowed synchronously from within the invoked `OnEnding` callbacks.  All registered SpanProcessor `OnEnding` callbacks are executed before any SpanProcessor's `OnEnd` callback is invoked.
> Yes. If it is possible and if we are concerned about it then we should add the same restrictions in OnStart.

I personally think it an edge case here not important enough. What we could do is state that for `OnStart` processors must not concurrently modify the spans. So impose a restriction on implementors, which however is not enforced through any code in the SDK. More like don't do this, or bad things may happen.

> At this point, I would rather add a general guideline that the processors should not modify the spans asynchronously to avoid race conditions and indeterministic behavior.

For `OnStart`, I agree to go this route (like stated in my paragraph above) if we deem it important enough. For `OnEnding`, this doesn't solve the problem of concurrent modifications performed by application code and not SpanProcessors (which is impossible for `OnStart`).

> Moreover, I am concerned that such restrictions on SDK would produce additional computational overhead.

I'm trying to understand what computational overhead you are thinking of: Isn't locking already involved anyway to make spans concurrency safe, so this shouldn't impose additional cost?

2024-06-27 13:58 UTC, JonasKunz commented on specification/trace/sdk.md
> +are only allowed synchronously from within the invoked `OnEnding` callbacks.  All registered SpanProcessor `OnEnding` callbacks are executed before any SpanProcessor's `OnEnd` callback is invoked.
> Changing a span asynchronously is also rather something very uncommon.

I personally don't agree with that statement. Getting the current span (from the context) and adding an attribute to it or changing the name doesn't seem to uncommon to me. And the current span might have been started and ended on another thread. I think this shouldn't be to uncommen in go too, because you could easily pass the current context/span to a goroutine, right?

2024-06-27 14:02 UTC, pellared commented on specification/trace/sdk.md
> +are only allowed synchronously from within the invoked `OnEnding` callbacks.  All registered SpanProcessor `OnEnding` callbacks are executed before any SpanProcessor's `OnEnd` callback is invoked.
> concurrent modifications performed by application code

Is not an edge case as well? I never saw any application or instrumentation library doing asynchronous span modification that could run in parallel while ending a span.

> Isn't locking already involved anyway to make spans concurrency safe, so this shouldn't impose additional cost?

It would be a more complex locking logic. I guess the overhead would be minimal, but never sure before you measure it.

2024-06-27 14:20 UTC, JonasKunz commented on specification/trace/sdk.md
> +are only allowed synchronously from within the invoked `OnEnding` callbacks.  All registered SpanProcessor `OnEnding` callbacks are executed before any SpanProcessor's `OnEnd` callback is invoked.
>> concurrent modifications performed by application code
>>
> Is not an edge case as well? I never saw any application or instrumentation library doing asynchronous span modification that could run concurrently while ending a span.

Looks like we commented at the same time, I think I answered that in [my previous comment](https://github.com/open-telemetry/opentelemetry-specification/pull/4024#discussion_r1657194063)

> Getting the current span (from the context) and adding an attribute to it or changing the name doesn't seem too uncommon to me. And the current span might have been started and ended on another thread. I think this shouldn't be to uncommen in go too, because you could easily pass the current context/span to a goroutine, right?

At least in Java it is very common that the current context (and therefore current span) is passed around to different threads / asynchronous tasks.

2024-07-04 11:07 UTC, pellared commented
I just saw the [Java prototype](https://github.com/open-telemetry/opentelemetry-java/pull/6367).

2024-07-04 11:56 UTC, JonasKunz commented
> I just saw the https://github.com/open-telemetry/opentelemetry-java/pull/6367.
It would be great if we also have a prototype in Go (currently I have no cycles to work on it).

@pellared Note that this prototype is outdated does not have the protection agains concurrent modifications we discussed.
It will actually make the implementation even simpler. I'll update it to have the intended protection.

2024-07-04 12:24 UTC, JonasKunz commented
@pellared Nevermind my previous comment, my prototype already had the protection even though it wasn't there intentionally.
I didn't notice we were already holding the lock while invoking `onEnding`. I just updated the prototype to reflect the naming of the callback suggested in this spec-PR.

2024-07-12 10:32 UTC, carlosalberto commented
@pellared I'd say we are ready to merge as this is in-development - but yes, once we want to go stable, we will need a few prototypes actually. WDYT?

2024-07-12 12:59 UTC, pellared approved these changes

2024-07-15 08:00 UTC, dmathieu commented on spec-compliance-matrix.md
> +| [SpanProcessor.OnEnding](specification/trace/sdk.md#onending) callback supported                 | X        | -   | -    | -   | -      | -    | -      | -   | -    | -   | -    | -     |
The `callback supported` mention seems superfluous, since the entire point of this matrix is to say that things are supported (it's also not the wording used by the other table lines)

```suggestion
| [SpanProcessor.OnEnding](specification/trace/sdk.md#onending)                                    | X        | -   | -    | -   | -      | -    | -      | -   | -    | -   | -    | -     |
```

2024-07-15 11:37 UTC, dmathieu approved these changes

2024-07-15 20:56 UTC, jmacd approved these changes

2024-07-25 16:32 UTC, merged