Minor clarification on BatchExportingProcessor behavior
open-telemetry/opentelemetry-specification pull request #4164
Opened 2024-07-26 05:53 UTC by cijothomas

## Changes

I am unsure of the meaning of the current wording, so trying to clarify here. It looks like the current wording was intended to convey that export() should not be triggered until previous export() finished, even if the triggers (batch-size met etc.) are ready. But the current wording is confusing. I hope I interpreted it correctly and this fix address the confusing aspect. If not, happy to correct myself.

For non-trivial changes, follow the [change proposal process](https://github.com/open-telemetry/opentelemetry-specification/blob/main/CONTRIBUTING.md#proposing-a-change).

* [ ] Related issues #
* [ ] Related [OTEP(s)](https://github.com/open-telemetry/oteps) #
* [ ] Links to the prototypes (when adding or changing features)
* [ ] [`CHANGELOG.md`](https://github.com/open-telemetry/opentelemetry-specification/blob/main/CHANGELOG.md) file updated for non-trivial changes
* [ ] [`spec-compliance-matrix.md`](https://github.com/open-telemetry/opentelemetry-specification/blob/main/spec-compliance-matrix.md) updated if necessary

2024-07-26 06:29 UTC, pellared approved these changes
That is a lot more readable and AFAIK it is indeed what the authors had in mind.

2024-07-26 11:06 UTC, tsloughter requested changes

2024-07-26 11:06 UTC, tsloughter commented on specification/trace/sdk.md
> +previous export operation has finished (for additional concurrency details see
```suggestion
previous export call has returned (for additional concurrency details see
```

This change fixes the wording to be clear that the call to the export method/function must return but that does not mean the actual export has finished.

2024-07-26 11:09 UTC, tsloughter commented on specification/trace/sdk.md
> +previous export operation has finished (for additional concurrency details see
To be clear, since this wording can be confusing, the particular instance of `SpanProcessor#Export()` must have "finished", but finished here is to vague and may imply to a reader that the actual data has been sent. To support concurrency the `Export()` could return while the actual export of the data is still ongoing and whether that send actually was successful is sent out of band.

2024-07-26 16:20 UTC, jmacd approved these changes

2024-07-29 17:55 UTC, lzchen approved these changes

2024-07-30 17:57 UTC, lalitb approved these changes

2024-07-30 18:59 UTC, trask approved these changes

2024-07-30 18:59 UTC, trask commented on specification/trace/sdk.md
> +the [Export() specification](#exportbatch)):
> AND the previous export call has returned

this seems redundant with the text below:

> If any of the above events occurs before `Export()` returns, the span processor
should wait until `Export()` returns before exporting the next batch.

2024-07-30 19:12 UTC, cijothomas commented on specification/trace/sdk.md
> +the [Export() specification](#exportbatch)):
Good point. Removing the redundant sentence.

2024-07-30 19:13 UTC, cijothomas commented
@tsloughter Could you take another look to see if the wording looks good?

2024-08-05 18:27 UTC, cijothomas commented
Still need review by @open-telemetry/technical-committee , could you help?

2024-08-16 15:10 UTC, cijothomas commented
@open-telemetry/technical-committee @arminru Gentle reminder to look at this when you get a chance!

2024-08-19 13:43 UTC, arminru approved these changes

2024-08-19 13:45 UTC, merged