Define Enabled parameters for Logger
open-telemetry/opentelemetry-specification pull request #4203
Opened 2024-09-09 08:20 UTC by pellared

Follows https://github.com/open-telemetry/opentelemetry-specification/pull/4020

During 7/5/24 OTel Specification SIG meeting it was decided to move the discussion about parameters to a separate PR;  a little cleaned up transcript:

> We're essentially trying to foresee with this is like what arguments will need to be present, for this Enabled method. Is it just severity? Is it no arguments at all? Are we going to want to evolve the arguments over time. I don't have the answers to those questions.
I wonder if we can do something [...] just to progress this because there's kind of [...] chicken in the eggs problems here. [...] we want to get this merged. [...]
This API should be structured so that the arguments you pass to it are evolvable. [...] we can leave ourselves room to evolve it from multiple standpoints. There's explicit text that says that the arguments can change and it's experimental.
I think I'd feel good about it then, because then we could [...] get this valuable thing in now [...]
[...]
And maybe we open some sort of issue [...] as a prerequisite for stability, we should [...] more thoughtfully consider what arguments are required for this.

This is needed for stabilization of `Logger.Enabled` in the spec which is need for the stabilization of Go Logs API.

Related issue: https://github.com/open-telemetry/opentelemetry-go/issues/5769

## Changes

Add a minimal (and maybe even sufficient?) set of parameters for `Logger.Enabled`.

Add guidelines/rules for the `Enabled` parameters.

2024-09-09 15:59 UTC, reyang commented on specification/logs/bridge-api.md
> +- [Severity Number](./data-model.md#field-severitynumber)
I wonder if we should clarify the behavior here. For example, what does it mean when the API returned true for a given severity number (e.g. should the caller assume that logs with the same or higher severity are enabled?)

2024-09-09 16:01 UTC, pellared commented on specification/logs/bridge-api.md
> +- [Severity Number](./data-model.md#field-severitynumber)
It means that for given level it is not enabled. No more than that.

2024-09-09 16:44 UTC, lmolkova commented on specification/logs/bridge-api.md
> +- The [Context](../context/README.md) associated with the `LogRecord`. The API
I imagine someone would check if logger + level is enabled before creating log record, so maybe

```suggestion
- The [Context](../context/README.md) to be associated with the `LogRecord`. The API
```

2024-09-09 16:44 UTC, lmolkova commented on specification/logs/bridge-api.md
> +  MAY implicitly use the current Context as a default behavior.
it's probably implementation (SDK) concern to use current context

```suggestion
- The [Context](../context/README.md) associated with the `LogRecord`. The implementation
  MAY implicitly use the current Context as a default behavior.
```

2024-09-09 16:44 UTC, lmolkova commented on specification/logs/bridge-api.md
> +  MAY implicitly use the current Context as a default behavior.
why MAY and not SHOULD ? I think it's good to have consistency between different implementations and SHOULD would give it.

2024-09-09 16:44 UTC, lmolkova commented on specification/logs/bridge-api.md
> +- The [Context](../context/README.md) associated with the `LogRecord`. The API
Is my understanding correct that `IsEnabled(Context)` primary use-case is sampling?

2024-09-09 17:31 UTC, MrAlias commented on specification/logs/bridge-api.md
> +  MAY implicitly use the current Context as a default behavior.
No all languages have a concept of a "current context". For example, Go requires an explicit context to be passed otherwise there is no context to reference.

2024-09-09 17:33 UTC, MrAlias commented on specification/logs/bridge-api.md
> +All parameters MUST be optional.
What does this mean?

2024-09-09 17:38 UTC, lmolkova commented on specification/logs/bridge-api.md
> +  MAY implicitly use the current Context as a default behavior.
it can still be SHOULD (when implicit context is supported)

2024-09-09 17:40 UTC, MrAlias commented on specification/logs/bridge-api.md
> +  MAY implicitly use the current Context as a default behavior.
> it can still be SHOULD (when implicit context is supported)

That clarification SGTM.

2024-09-09 19:05 UTC, pellared commented on specification/logs/bridge-api.md
> +- The [Context](../context/README.md) associated with the `LogRecord`. The API
For filtering, e.g. to set a minimum severity level.

2024-09-09 19:19 UTC, pellared commented on specification/logs/bridge-api.md
> +- The [Context](../context/README.md) associated with the `LogRecord`. The API
Addressed ee68460

2024-09-09 19:19 UTC, pellared commented on specification/logs/bridge-api.md
> +  MAY implicitly use the current Context as a default behavior.
Addressed ee68460

2024-09-09 19:19 UTC, pellared commented on specification/logs/bridge-api.md
> +  MAY implicitly use the current Context as a default behavior.
Addressed ee68460

2024-09-09 19:25 UTC, MrAlias commented on specification/logs/bridge-api.md
> +All parameters MUST be optional.
Does this mean that the intended audience of this specification, the OpenTelemetry API and SDK developer, can interpreter this as it required for them to decide if they want to support this in their APIs and SDKs? Because as this is currently written, it would be a justified interpretation.

If this is intended to state that these developers instead need to build an API where users have the option to pass things, this needs to be re-worded.  I would suggest following the [pattern used in other parts of the specification](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#view):

```
Users can provide a `severity`, but it is up to their discretion. Therefore, the parameter needs to be structured to accept a `severity`, but MUST NOT obligate a user to provide one.
```

2024-09-09 19:26 UTC, MrAlias commented on specification/logs/bridge-api.md
> +All parameters MUST be optional.
Also, it seems like you intend to require the context when it is explicit. It seems like this statement is an over-generalization because of that.

2024-09-09 19:35 UTC, pellared commented on specification/logs/bridge-api.md
> +All parameters MUST be optional.
This document already specifies what optional mean [here](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/bridge-api.md#optional-and-required-parameters): 

> The operations defined include various parameters, some of which are marked optional. Parameters not marked optional are required.
>
> For each optional parameter, the API MUST be structured to accept it, but MUST
NOT obligate a user to provide it.

2024-09-09 19:45 UTC, pellared commented on specification/logs/bridge-api.md
> +All parameters MUST be optional.
PTAL b916c0f

2024-09-09 19:52 UTC, lmolkova commented on specification/logs/bridge-api.md
> +- The [Context](../context/README.md) associated with the `LogRecord`. The API
Yeah, I understand the severity use-case, my question is specifically about the Context

2024-09-09 19:55 UTC, pellared commented on specification/logs/bridge-api.md
> +- The [Context](../context/README.md) associated with the `LogRecord`. The API
Yes, it could be used for sampling but also for any other "contextual" logic (also user-defined, custom behaviors).

2024-09-09 19:56 UTC, cijothomas commented on specification/logs/bridge-api.md
> +- The [Context](../context/README.md) associated with the `LogRecord`. The API
I think one use case is to allow dropping (or keeping) logs, based on the sampling decision of active span, if any?

2024-09-09 20:22 UTC, lmolkova commented on specification/logs/bridge-api.md
> +- The [Context](../context/README.md) associated with the `LogRecord`. The API
thanks for the context!

@jmacd curious if there is any prior art for log sampling

2024-09-10 14:59 UTC, lmolkova approved these changes

2024-09-10 16:03 UTC, jack-berg requested changes
These parameters were included in the original PR, and we had a (long) conversation about their values [here](https://github.com/open-telemetry/opentelemetry-specification/pull/4020#discussion_r1583688495).

In a nutshell, my critique is that the SDK has to provide an implementation of this `Logger#enabled` method, but there is currently nothing in the SDK spec which would allow the `Logger#enabled` to do anything differently based on the `context` / `severity` arguments.

In its current form, this is half of a feature. SDKs will always response with `Logger#enabled` based on the logger's associated [LoggerConfig.disabled](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/sdk.md#loggerconfig), ignoring the `severity` / `context` arguments.

2024-09-10 16:19 UTC, pellared commented
> In a nutshell, my critique is that the SDK has to provide an implementation of this Logger#enabled method, but there is currently nothing in the SDK spec which would allow the Logger#enabled to do anything differently based on the context / severity arguments.

Cannot this be proposed as a separate PR? In Go SIG, we are indeed experimenting how to best model it on the SDK level. We have an experimental feature, but we would like to have some more feedback before we propose something to the specification. 

I think we can separately work on specifying the API and how SDK is implementing the API.

2024-09-10 16:27 UTC, pellared commented on specification/logs/bridge-api.md
> +the API MUST be structured in a way for optional parameters to be added.
```suggestion
Additional optional parameters can be added in the future, therefore,
the API MUST be structured in a way for these parameters to be added.
```

2024-09-10 17:13 UTC, jack-berg commented
> Cannot this be proposed as a separate PR?

I'm fine splitting this out in a way that allows iteration. But we need a way to not loose track of this - maybe a TODO in the spec and a new issue upon merging? Resolving this discrepancy between the API and SDK should be a blocker to stability.

2024-09-10 17:18 UTC, pellared commented
> > Cannot this be proposed as a separate PR?
> 
> I'm fine splitting this out in a way that allows iteration. But we need a way to not loose track of this - maybe a TODO in the spec and a new issue upon merging? Resolving this discrepancy between the API and SDK should be a blocker to stability.

Good idea. I created:
- https://github.com/open-telemetry/opentelemetry-specification/issues/4207
- https://github.com/open-telemetry/opentelemetry-specification/issues/4208

Feel free to update description or even create more issues.

2024-09-10 17:53 UTC, cijothomas commented on specification/logs/bridge-api.md
> +- [Timestamp](./data-model.md#field-timestamp) (optional)
this is unrelated to *this* PR, can that be separately submitted, if intended?

2024-09-10 17:56 UTC, MrAlias approved these changes

2024-09-10 17:57 UTC, pellared commented on specification/logs/bridge-api.md
> +- [Timestamp](./data-model.md#field-timestamp) (optional)
Correct. There were concerns about using the same patterns for `Enabled` that were already used in `Emit a log record` so I decided to address the feedback in both places at once.

2024-09-12 01:41 UTC, trask commented
may also want to consider blocking stability on whether we want to include "event name" in the enabled parameters, e.g. see @lmolkova's https://github.com/open-telemetry/oteps/pull/265#issuecomment-2344112029

2024-09-12 06:22 UTC, pellared commented
> may also want to consider blocking stability on whether we want to include "event name" in the enabled parameters, e.g. see @lmolkova's [open-telemetry/oteps#265 (comment)](https://github.com/open-telemetry/oteps/pull/265#issuecomment-2344112029)

If you want you can add it to https://github.com/open-telemetry/opentelemetry-specification/issues/4208.

However, I do not think that it should block the stability of Enabled as:
1. Adding a parameter would not be a breaking change
2. I feel that there is no conclusion if we want to add an "event name" do the LogRecord model or if we just want to use an `event.name` log attribute for it. It may be better to add "attributes" to enabled parameters. I think we would rather use just an attribute for that. See https://github.com/open-telemetry/oteps/pull/265#issuecomment-2339082984

2024-09-12 19:25 UTC, reyang commented
> 1. Adding a parameter would not be a breaking change

💯 

> 2. I feel that there is no conclusion if we want to add an "event name" do the LogRecord model or if we just want to use an `event.name` log attribute for it. It may be better to add "attributes" to enabled parameters. I think we would rather use just an attribute for that. See [Event basics oteps#265 (comment)](https://github.com/open-telemetry/oteps/pull/265#issuecomment-2339082984)

There might be more to consider (definitely not for this PR):
1. Comparing strings could be very inefficient, many systems used integers (e.g. Event Id = 1001) in combination with user-friendly names.
2. For platforms with very limited resource or mission critical software (e.g. IoT device, kernel drivers), folks might want to just emit the integer, then enrich the data in the pipeline/backend using the integer -> string name mapping.

2024-09-17 08:33 UTC, pellared commented on specification/logs/bridge-api.md
> +- The [Context](../context/README.md) associated with the `LogRecord`. The API
This is my personal proposal how "filtering" (which I think is a better term than sampling for logging) could be designed/implemented: https://github.com/open-telemetry/opentelemetry-specification/issues/4207#issuecomment-2354859647

2024-09-20 05:26 UTC, pellared commented on specification/logs/bridge-api.md
> +value like 0 for [Severity Number](./data-model.md#field-severitynumber).
```suggestion
```

By @jack-berg in https://github.com/open-telemetry/opentelemetry-specification/issues/4207#issuecomment-2362290968:

> I'm suspicious of the idea of introducing the concept of an expandable set of `EnabledParameters`, since requiring users to create a new struct / object to check if code should proceed to emitting a log seems non-optimal from a performance and ergonomics standpoint. I understand the desire to want to retain flexibility to evolve the API, but I think getting the arguments right in the initial stable version and not trying to retain the ability to evolve is likely to produce the most ergonomic API.

I think that in many languages expandable set of parameters for `Logger.Enabled` with acceptable performance and ergonomics standpoint can be achieved by using optional function/method arguments. But, for Go you are correct having `Logger.Enabled` to accept only context and severity would make the API more ergonomic. I am worried that is may be hard to get the arguments right in the initial version. For instance, should we allow filtering based on attributes or body? Do we want to close the doors for such possibility? On the other hand, from my experience having only context and severity would cover 99% of use cases and having a better ergonomics and easier design is also desirable.

2024-09-20 14:24 UTC, cijothomas commented on specification/logs/bridge-api.md
> +value like 0 for [Severity Number](./data-model.md#field-severitynumber).
> On the other hand, from my experience having only context and severity would cover 99% of use cases

Agree on this. Most logging frameworks I am familiar with provide IsEnabled/equivalent by using minimal arguments, and in particular, those arguments that are known easily (`static` in some languages like Rust). The usual goal of `IsEnabled` is optimize performance, so minimal arguments meets the goal here.
Examples:
.NET ILogger allows filtering based on Severity, Scope only.
Rust's `tracing` (logging solution!), only allows filtering based on Severity,Scope,Name (event name)

For filtering based on attributes/body (or anything that is dynamic in nature) - these are typically done *not* for Perf savings, but for saving backend storage costs. These are better handled by `LogRecordProcessor` (in-proc) or Collector (out-of-proc).

2024-09-20 16:21 UTC, pellared commented on specification/logs/bridge-api.md
> +value like 0 for [Severity Number](./data-model.md#field-severitynumber).
> only allows filtering based on Severity,Scope,Name (event name)

The scope will be known by the SDK - no need to add it to `Enabled` as the parameter.

Question if we would need event name as a parameter. @cijothomas do you know if this is frequently used and what are the use cases when it is used? I think a prerequisite for it would be to to add it as a field to LogRecord (it could be defined in the same way as `Body` and named `ID` or `Name`).

2024-09-20 16:24 UTC, cijothomas commented on specification/logs/bridge-api.md
> +value like 0 for [Severity Number](./data-model.md#field-severitynumber).
> The scope will be known by the SDK - no need to add it to Enabled as the parameter.
Oh that is correct!

2024-09-20 16:31 UTC, cijothomas commented on specification/logs/bridge-api.md
> +value like 0 for [Severity Number](./data-model.md#field-severitynumber).
Regd. EventName being used for EnabledCheck:
1. It is very important (actually the EventId, the numerical, machine friendly version of EventName that is most important to do ultra fast checks!) for scenarios we are working on in OTel Rust, C++. I don't know if it is something every language/implementation cares about. Given spec does not prohibit an implementation from allowing more parameters, I am totally okay if spec does not mention it, as  OTel C++/Rust can offer this as extras.
2. From the Event Oteps, there were mention of scenarios where Loggers can filter based on EventName, route things to different places based on EventName etc. It'd be good to wait to see the progress on Events before we can really say if EventName is a important parameter for the `Enabled` check.

2024-09-20 16:34 UTC, cijothomas approved these changes

2024-09-20 17:22 UTC, reyang commented on specification/logs/bridge-api.md
> +value like 0 for [Severity Number](./data-model.md#field-severitynumber).
Not a blocker for this PR

2024-09-20 17:22 UTC, merged