Use Logs API to emit Events
open-telemetry/opentelemetry-specification pull request #4225
Opened 2024-09-25 08:22 UTC by pellared

Follows https://github.com/open-telemetry/oteps/pull/265

Key changes:
1. Rename Logs Bridge API -> Logs API
2. Add languages the possibility to have separate APIs for Logs Bridge API and Logs API if Logs API needs different ergonomics than existing Logs Bridge API. This may be needed e.g. for Java, but also for other languages that do not find their current Logs Bridge API design well suited for "direct" usage.
3. Call out that instrumentation libraries are supposed use the Logs API directly and applications can also use it directly if preferred.

2024-09-25 13:54 UTC, MSNev requested changes
Whatever form the new Logs API takes will be a merging (not a removal) of the existing Event API.

If there is any "Rename" (IMHO) it would be that the Event API is renamed and have functionality added to it.

ALthough, I still prefer having these as separate API's where the SDK's can implement more than one.

2024-09-25 14:54 UTC, cijothomas commented on specification/logs/api.md
> +It is provided for application developers to emit structured log recors
```suggestion
It is provided for application developers to emit structured log records
```

2024-09-25 14:54 UTC, cijothomas commented on specification/logs/api.md
> +ergonimics for consumers that are building log appenders/bridges.
```suggestion
ergonomics for consumers that are building log appenders/bridges.
```

2024-09-25 14:56 UTC, cijothomas commented on specification/logs/README.md
> +  ship a feature-rich logging library. However, nothing prevents application
the part where OTel's Log API bridges into external logging library - this is not in the scope for this PR, right?

2024-09-25 18:24 UTC, pellared commented on specification/logs/README.md
> +  ship a feature-rich logging library. However, nothing prevents application
Correct.

2024-09-25 21:17 UTC, trask commented on specification/logs/api.md
> +This document defines a log *backend* API.
I think part of the decision in the OTEP is to remove "backend" (by calling it a user-facing Logs API)

```suggestion
This document defines a log API.
```

2024-09-26 02:10 UTC, reyang commented on specification/logs/api.md
> +Languges MAY provide a separate Logs Bridge API if they need different
```suggestion
Languages MAY provide a separate Logs Bridge API if they need different
```

2024-09-26 02:10 UTC, reyang commented on specification/logs/api.md
> +The Logs API consist of these main components:
```suggestion
The Logs API consists of these main components:
```

2024-09-26 06:35 UTC, pellared commented
> I still prefer having these as separate API's where the SDK's can implement more than one.

@MSNev, I did my best to make it acceptable (key change numer 2)

2024-09-26 21:44 UTC, trask commented on specification/logs/README.md
> +  It is provided for library authors to build [log appender](../glossary.md#log-appender--bridge),
```suggestion
  It is provided for library authors to build [log appenders](../glossary.md#log-appender--bridge),
```

2024-09-26 21:44 UTC, trask commented on specification/logs/README.md
> +  records following semantic conventions (also known as OpenTelemetry Events).
or is the problem that we haven't defined what events are yet in the spec?

```suggestion
  The [API](./api.md) is also provided for instrumentation libraries to emit events.
```

2024-09-26 21:44 UTC, trask commented on specification/logs/api.md
> +(e.g. custom events).
```suggestion
It is provided for application developers to emit events.
```

2024-09-27 04:36 UTC, pellared commented on specification/logs/README.md
> +  records following semantic conventions (also known as OpenTelemetry Events).
>  is the problem that we haven't defined what events are yet in the spec

Correct. I prefer to be a little more verbose for now. We can refine it later.

2024-09-27 04:39 UTC, pellared commented on specification/logs/api.md
> +(e.g. custom events).
https://github.com/open-telemetry/opentelemetry-specification/pull/4225/files#r1777996355 + they can still emit any log record. The application developers can create their own semantic log records which they may want to be different than events.

2024-09-27 06:03 UTC, pellared commented on specification/logs/README.md
> +  records following semantic conventions (also known as OpenTelemetry Events).
Maybe 
```suggestion
  The [API](./api.md) is also provided for instrumentation libraries to emit log
  records following semantic conventions (also known as [OpenTelemetry Events](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/general/events.md)).
```

2024-09-27 16:07 UTC, trask commented on specification/logs/README.md
> +  records following semantic conventions (also known as OpenTelemetry Events).
> We can refine it later.

👍

2024-09-27 16:08 UTC, trask commented on specification/logs/api.md
> +(e.g. custom events).
```suggestion
It is provided for application developers to emit structured log records
(including OpenTelemetry Events).
```

2024-09-27 16:47 UTC, MSNev requested changes
> To support it we do not need to have a dedicated API. There is/was also a debate whether event name should be as a LogRecord field instead of an attribute, but this is out of scope for this PR.

YES WE DO!

2024-09-27 17:00 UTC, MSNev commented on specification/logs/event-api.md
> -<!-- toc -->
This file must either be merged into the logs or kept separate

2024-09-27 17:01 UTC, MSNev commented on spec-compliance-matrix.md
> -| Feature                                                                    | Optional | Go | Java | JS | Python | Ruby | Erlang | PHP | Rust | C++ | .NET | Swift |
This table is (was) incomplete, several languages already have this capability and users of this API.

JS, Java (Android) and recently Python

2024-09-27 18:26 UTC, MSNev commented on CHANGELOG.md
> +- Remove Events API and SDK. Rename Logs Bridge API to Logs API and do not discourage from direct usage.
Merge Events API and SDK

2024-09-27 18:42 UTC, pellared commented
SIG meeting notes:
There are use cases where languages would want to have dedicated API just for emitting events. Therefore, the plan is to bring back the Events API. If a language provides Events API then the Logs SDK SHOULD implement it. Some languages (e.g. Go) do not want to provide a separate Events API therefore Logs API can be used for emitting events. 👍, 👎, and comments are welcome before I make changes in the PR 😉

2024-09-27 18:48 UTC, trask commented
> Therefore, the plan is to bring back the Events API

this would contradict the OTEP (https://github.com/open-telemetry/oteps/blob/main/text/0265-event-vision.md#api):

> OpenTelemetry SHOULD provide a (user-facing) Logs API that includes the capability to emit OpenTelemetry Events.

2024-09-27 19:09 UTC, pellared commented
Alternative proposal

1. Add the OpenTelemetry Events descriptions (model, use cases) from Events API
2. Add OPTIONAL `EmitEvent` method to `Logger`

2024-09-27 19:17 UTC, reyang commented
> If a given language API wanted to create a wrapper around the logging API for emitting events, wouldn't that be fine? It's not like we can't have exceptions to the API, as long as they're documented. As long as the sugared call and the specced API have the same result, then I'm not sure how much it matters.
> 
> Pseudocode example -
> 
> No wrappers:
> 
> ```
> let logger = OpenTelemetry.API.GetLogger()
> logger.EmitEvent({
>   name: "sessionStart",
>   attributes: ...,
>   resources: ...,
> })
> ```
> 
> sugared -
> 
> ```
> let sessionInstrument = new OpenTelemetry.SessionEventInstrument()
> sessionInstrument.start(attributes, resources)
> ```

Another example https://github.com/open-telemetry/opentelemetry-dotnet/blob/cc0b9e9d0f874d4cbafd801d4af343f02e4ffbfe/docs/logs/complex-objects/Program.cs#L17-L26


```csharp
var foodRecallNotice = new FoodRecallNotice
{
    BrandName = "Contoso",
    ProductDescription = "Salads",
    ProductType = "Food & Beverages",
    RecallReasonDescription = "due to a possible health risk from Listeria monocytogenes",
    CompanyName = "Contoso Fresh Vegetables, Inc.",
};


logger.FoodRecallNotice(foodRecallNotice);

internal static partial class LoggerExtensions
{
    [LoggerMessage(LogLevel.Critical)]
    public static partial void FoodRecallNotice(
        this ILogger logger,
        [LogProperties(OmitReferenceName = true)] in FoodRecallNotice foodRecallNotice);
}
```

What you will get:

```text
LogRecord.Timestamp:               2024-01-12T19:01:16.0604084Z
LogRecord.CategoryName:            Program
LogRecord.Severity:                Fatal
LogRecord.SeverityText:            Critical
LogRecord.FormattedMessage:
LogRecord.Body:
LogRecord.Attributes (Key:Value):
    CompanyName: Contoso Fresh Vegetables, Inc.
    RecallReasonDescription: due to a possible health risk from Listeria monocytogenes
    ProductType: Food & Beverages
    ProductDescription: Salads
    BrandName: Contoso
LogRecord.EventId:                 252550133
LogRecord.EventName:               FoodRecallNotice
```

2024-09-27 19:38 UTC, austinlparker commented
> Alternative proposal
> 
> 1. Add the OpenTelemetry Events descriptions (model, use cases) from Events API
> 2. Add OPTIONAL `EmitEvent` method to `Logger`

Yes, I think we need to bring the model and use cases in, no question. I do think it'd be good to explore options for the 'EmitEvent' part -- for example, why not take inspiration from the Metrics API and have LogProviders which create Loggers which can create LogInstruments, and a type of those could be named Events?

2024-09-27 20:38 UTC, austinlparker commented
One thing to consider would be this pattern, even (ignore that the syntax isn't exactly right) --

```typescript
class SessionEventEmitter extends BaseEventEmitter {
  startSession(sessionId: string, userId: string): void {
    this.emitEvent('session.start', {
      attributes: { sessionId, userId },
      body: 'User session started',
    });
  }

  endSession(sessionId: string): void {
    this.emitEvent('session.end', {
      attributes: { sessionId },
      body: 'User session ended',
    });
  }
}

class UserInteractionEventEmitter extends BaseEventEmitter {
  buttonClick(buttonId: string, userId: string): void {
    this.emitEvent('user.interaction.button_click', {
      attributes: { buttonId, userId },
      body: 'User clicked a button',
    });
  }

  pageView(pageUrl: string, userId: string): void {
    this.emitEvent('user.interaction.page_view', {
      attributes: { pageUrl, userId },
      body: 'User viewed a page',
    });
  }
}```

These event generators could be distributed through contrib or other places.

2024-09-27 20:54 UTC, MSNev commented on specification/logs/api.md
> +This document defines a log API.
As part of OTep #265 it was determined that there SHOULD be a public facing "Logging" API to enable the emitting of "Events" (as a type of OpenTelemetry Log) as well as other general "Logs" <- I'm implicitly inferring based on discussions that occurred as part of #265 (ie. while all `events` can be represented as Logs, not all Logs are `events`) 

One of the key words here is `type`, there are many `types` of Logs and each type fundamentally defines the "intent" (or the "why") the log is being emitted.

These can include "Event", "Audit", "Security", "Transaction", "Message", "Server", "File" and many, many more, and just as "Events are a `type` of Log", several of these can also be sub-classified as a type of `event`.

As part of any Logging API we SHOULD provide a front-end API and guidance for all of the CORE fundamental concepts to "try" to make it clear about what will and won't occur when you do or don't use the specific API. 
(Right NOW we don't have this clearly defined (because we are always trying to take small steps) which always lands us into the argument of "But it's just a Log", which is not a productive argument as it ignores the requirements by different teams / use cases that there are different needs and different `types` of Logs that should have some uniform structure (Semantic Conventions / processing) around them.

2024-09-27 20:57 UTC, MSNev commented on specification/logs/api.md
> +The API serves following use cases.
There are many additional features / requirements that exist and are yet to be defined as we move this API forward (some of which was starting to occur in the Event API) as it was moving (or trying to move) towards stability.
Some of these will include different processing requirements for the different `types` and as it moves towards a stabilized state it may cause implementation changes, so for now (as a small step) I'll try to define a starting point.

2024-09-27 21:14 UTC, MSNev commented on specification/logs/api.md
> +OpenTelemetry Semantic Conventions).
It should include an `emitEvent` function which MUST include the `name` as a first-class concept as the specific value of the `name` defines the Semantic-Definition of any provided `body` for the specific `event`.

As the `name` is a required argument / property for this function it MUST also enforce that the `name` conforms to the OpenTelemetry general semantic conventions (ie. it is fully qualified -- just like an Attribute name (this doesn't mean a complete list of valid "registered" events), e.g. it just needs to have a leading domain and then name `domain.eventName` where the domain may have multiple separators.

And it should also
 - Be used only to emit a well-structured, well defined `event` as per the definitions from an OpenTelemetry and application perspective.
  - These `events` will include the fundamental log `types` like "Application", "User", "Client", "Device", "Security".
  - Which ["It signals that "this thing happened at this time" and provides additional specifics about the occurrence"](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/general/events.md#semantic-conventions-for-events)
  - Should be used by Applications (Adopters) and Instrumentations only.
  - Because the exact structure and semantic meaning of the `body` of the `event` is driven and defined by the `name`, this allows for SDK's (or applications) to extend and provide (if required)
    - explicit validation of the content
    - explicit sampling / rules governing that specific "instance"
    - explicit delivery mechanism (Send NOW, Don't Drop, Create Metric, as some possible examples)
    - The exact location of the "where" and "when" of any rules is up to the specific application / implementation (eg. it "MAY" occur on the client, in the SDK, at the aggregation point (Collector) or at rest and queried as required.

And (if) future versions of OpenTelemetry evolve to change the internal representation of the `event` as a `LogRecord` all of the "changes" can be limited to the SDK implementation/version of the API, so that all existing users of the API have zero change when it's just an internal "representation" within the `LogRecord` (not-withstanding that this would have downstream implementations)

2024-09-27 21:22 UTC, MSNev commented on specification/logs/api.md
> +It is provided for application developers to emit structured log records
This should call out the "difference" between the processing / handling / semantics of an `event` vs a structured log

- `emitLog`
  - Used to emit a structured Log (without (necessarily) any implicit meaning
  - These `logs` will include type "Server", "Transaction", "Message", "Audit", "Debug", "Diagnostic" etc.
  - To be used to provide "Detailed Information" which may be used to understand operational issues, often used for post mortem analysis rather than operational dashboards or monitoring.
    - Should be used by Applications, Instrumentations and SDK implementations.
  - If there is any explicit `event` processing, this API won't perform any explicit processing beyond general common Log Processors

Problem Statement and confusion
 - As "structured" logs generally also need some form of "identifier" about the "type", so these will also need some form of `name`, `schema` or `identifying` attributes as these (vs general unstructured logging) generally have some semantic conventions on their structure and beyond just have "OTLP" `AnyValues` processors will likely want a simple mechanism for identifying them.
 - The MUST however, NOT be identified in the same manner as `events`, as then there is no deterministic mechanism for identifying "How" the type of `LogRecord` was produced (as an Event or as a Detailed Information record).
 - As such should this include or be restricted to have a general (optional) `name`
 - If a Language / runtime has a standard logging library with a supported log appender then there will be confusion between using this API vs their specific (preferred) logging library.
   - The difference should be isolated around configured specific Log Processing (if any) -- which of course doesn't exist today.

2024-09-27 21:33 UTC, MSNev commented on specification/logs/api.md
> +It is provided for logging library authors to build
- `emitBridgeLog` (just making the name different from above -- needs a better one), just here to have the distinction explicit.
  - Exists to "bridge" into the OpenTelemetry `Logs` pipeline only
  - Used by log Appenders ONLY to create OpenTelemetry `LogRecords` and have them processed
  - NO special processing (beyond existing Log Processors ??)*
    - (*)There may be some special use cases where some Log Processors may be required to be skipped (like a processor that links OTel Logs -> Native Logging)
    - Should we change this and have "explicit" Appender/Bridge Log Processors
  - IF an existing language / logging library supports the creation of "Events" or specific "Structured" Logs then this API MAY be used to "Simulate" (generate) a `LogRecord` that looks like those created by the above API's.
    - HOWEVER, this WILL NOT re-apply / perform any special processing that may be configured by the SDK instance for the other API methods
    - So it's entirely 100% up to the appender (caller of this API) to ensure that it is complying with any necessary semantic conventions to avoid any downstream complications around deterministically identifying / processing the resulting `LogRecord`.
    - It also MUST NOT just convert everything into an Event UNLESS
      - it can EXPLICITLY identify that the intent of the `LogRecord` was to identify (signal) that the specifically named `event` occurred vs general Detailed Logging
      - or it create a general semantic convention that identifies that this `LogRecord` that looks like an `event` was created by or follows the semantic conventions of X. ie. it has a specific `name` like `log.*`, `applog.*` or `event.ilogger` again so the intent (type) can be deterministically evaluated AND it would avoid any "clashes" with defined semantic conventions.
      - To phrase another way as long as the Appender "Knows" that the user emitting the `LogRecord` WANTS this specific  log to be called `XXXXX` then this is 100% acceptable as long as the control (setting) of this name is explicitly defined by the user. eg. Application has their own logger for their own events, but they want to explicitly `emit` an OpenTelemetry defined `event` with a Specific name via their own logger and not via the OpenTelemetry `emitEvent` with the understanding (implicit or otherwise) that any configured OpenTelemetry "Event" processing will NOT be performed via this path.

2024-09-27 21:55 UTC, MSNev commented
While I agree that some languages (.Net being one of the primary examples) will not "want" (or necessarily need) to provide a separate API (which is one of the reasons for "accepting" it as an optional API.

For this specific example though assuming that the `LogRecord.EventName` is what you are proposing as the OpenTelemetry `event.name` then there are a couple of issues / questions

> ```
> LogRecord.EventId:                 252550133
> LogRecord.EventName:               FoodRecallNotice
> ```

1) This is not actually a valid OpenTelemetry `event.name`, granted you could "add" the namespace of the "logger" to "make" it valid, so that not really an issue. As long as the "Application" (for this specific case) has defined it's own semantic conventions for this "event" (which they really have via code).
2) If rather than a "FoodRecallNotice" event name, the application owner wanted to emit a "standard" OpenTelemetry (or any common externally defined event) which has a specific "EventName"
- say for example `safety.recall.notice` which had a attribute / body field containing the type (Food / Automotive / etc as examples). Would they be required to create a unique Logger with this specific namespace / name or can / should they be able to just define (add an additional attribute / property) onto the function. Something like this perhaps

```c#
[LoggerMessage(LogLevel.Critical)]
[OTelEventName("safety.recall.notice")]
    public static partial void FoodRecallNotice(
```

2024-09-27 22:52 UTC, cijothomas commented
> While I agree that some languages (.Net being one of the primary examples) will not "want" (or necessarily need) to provide a separate API (which is one of the reasons for "accepting" it as an optional API.
> 
> For this specific example though assuming that the `LogRecord.EventName` is what you are proposing as the OpenTelemetry `event.name` then there are a couple of issues / questions
> 
> > ```
> > LogRecord.EventId:                 252550133
> > LogRecord.EventName:               FoodRecallNotice
> > ```
> 
> 1. This is not actually a valid OpenTelemetry `event.name`, granted you could "add" the namespace of the "logger" to "make" it valid, so that not really an issue. As long as the "Application" (for this specific case) has defined it's own semantic conventions for this "event" (which they really have via code).
> 2. If rather than a "FoodRecallNotice" event name, the application owner wanted to emit a "standard" OpenTelemetry (or any common externally defined event) which has a specific "EventName"
> 
> * say for example `safety.recall.notice` which had a attribute / body field containing the type (Food / Automotive / etc as examples). Would they be required to create a unique Logger with this specific namespace / name or can / should they be able to just define (add an additional attribute / property) onto the function. Something like this perhaps
> 
> ```cs
> [LoggerMessage(LogLevel.Critical)]
> [OTelEventName("safety.recall.notice")]
>     public static partial void FoodRecallNotice(
> ```

If OTel .NET's ILogger EventName is *not* what we envision as OTel LogRecord's "event.name", then I am unsure what are OTel Events. It meets the OTep definition of OTel Events.
Is it a type of OpenTelemetry Log - Yes
Does it require an event name - Yes
Does it follow a specific structure implied by that event name - Yes. All events of that name will have same structure
(In well behaved applications. Nothing preventing user from sending another with same name but differing in structure. The same is the case with any new Event specific API too)

From OTEP:
```
What are OpenTelemetry Events? OpenTelemetry Events are a type of OpenTelemetry Log that requires an event name and follows a specific structure implied by that event name.
```



> This is not actually a valid OpenTelemetry `event.name`

What is the reason for this?

> Would they be required to create a unique Logger with this specific namespace

Same logger if it is same instrumentation scope. Different if different instrumentation scope. No enforcement from us, end users are the best person to decide the scope. Some use a single scope for entire application. Some uses different scopes per module or class. Don't think OTel should enforce anything different here.

2024-09-27 22:55 UTC, cijothomas commented
> One thing to consider would be this pattern, even (ignore that the syntax isn't exactly right) --
> 
> ```ts
> class SessionEventEmitter extends BaseEventEmitter {
>   startSession(sessionId: string, userId: string): void {
>     this.emitEvent('session.start', {
>       attributes: { sessionId, userId },
>       body: 'User session started',
>     });
>   }
> 
>   endSession(sessionId: string): void {
>     this.emitEvent('session.end', {
>       attributes: { sessionId },
>       body: 'User session ended',
>     });
>   }
> }
> 
> class UserInteractionEventEmitter extends BaseEventEmitter {
>   buttonClick(buttonId: string, userId: string): void {
>     this.emitEvent('user.interaction.button_click', {
>       attributes: { buttonId, userId },
>       body: 'User clicked a button',
>     });
>   }
> 
>   pageView(pageUrl: string, userId: string): void {
>     this.emitEvent('user.interaction.page_view', {
>       attributes: { pageUrl, userId },
>       body: 'User viewed a page',
>     });
>   }
> }```
> 
> These event generators could be distributed through contrib or other places.
> ```

Yes, and hopefully, **Weaver** will be able to do this for us automatically from semantic conventions!

2024-09-27 23:16 UTC, trask commented
@MSNev @cijothomas I don't think the discussion about .Net logger is relevant to this specific PR, and I'm hoping we can focus on getting small, incremental spec PRs landed, focusing on one contentious remaining event issue at a time.

2024-09-27 23:35 UTC, trask commented on specification/logs/api.md
> +It is provided for logging library authors to build
@MSNev can you highlight any specific blocking concerns you have about this PR beyond https://github.com/open-telemetry/opentelemetry-specification/pull/4225#issuecomment-2379899009, and open tracking issues for the rest? Once we get this initial restructuring PR landed then we'll be able to start sending PRs to try to address those. Thanks.

2024-09-28 00:09 UTC, MSNev commented
@cijothomas 

> > This is not actually a valid OpenTelemetry `event.name`
> 
> What is the reason for this?
> 

See the [Event Semantic convention](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/general/events.md#event-definition) point [1]

"[1]: Event names are subject to the same rules as [attribute names](https://github.com/open-telemetry/semantic-conventions/blob/main/docs/general/attribute-naming.md). Notably, `event names are namespaced to avoid collisions` and provide a clean separation of semantics for events in separate domains like browser, mobile, and kubernetes."

> If OTel .NET's ILogger EventName is not what we envision as OTel LogRecord's "event.name", then I am unsure what are OTel Events. It meets the OTep definition of OTel Events.

And see the points I made in [this comment](https://github.com/open-telemetry/opentelemetry-specification/pull/4225#discussion_r1779178035), I'm not saying you can't I'm saying there should be semantic conventions / ruls around when / how this is done. 

I'm fine having some "auto-naming" as long as 
- it's explicit that the thing being record (the intent) is that this is expected to be an `event` and not a just a Detailed log record used solely for the purpose of Debugging 
- OR there is some level of understanding that something called name X should NOT be considered to be an event. (The naming to ensure that the event is namespaced to avoid collisions)

As mentioned [above in this comment](https://github.com/open-telemetry/opentelemetry-specification/pull/4225#discussion_r1779152864) 

> while all `events` can be represented as structured Logs, not all Logs are `events`


@trask 
> discussion about .Net logger is relevant to this specific PR

Considering, this is one of the primary reasons that we are where we are, I believe it is relevant as the expectations around how .Net will comply with the generation of `events` and how it SHOULD conform to the general Semantic Conventions (with or with a specific API implementation) is part of the shape and rules around each API definition.

I was also attempting to point out that there WILL be cases where some adopters will WANT to emit a pre-defined event using their own logger. However, if auto-code generation via weaver constructing a new specifically named Logger instance IS the approach that .Net wants to enforce then that is their choice, but I believe it's necessarily the optimal or best choice.

At the end of the day it MUST conform to all of the Semantic Conventions of an `event` and it MUST provide the "Required" set of functionality (and that functionality today is currently limited)

This is also why I tried to provide some concrete guidance and expectations in my comments above around how each API should be viewed from both the SDK implementers and adopters -- to "try" and remove some of the ambiguity that keeps arising from "Everything is a Log".

2024-09-28 00:22 UTC, MSNev commented
Another general comment on this 

> If OTel .NET's ILogger EventName is not what we envision as OTel LogRecord's "event.name", then I am unsure what are OTel Events. It meets the OTep definition of OTel Events.

Just because it looks like an `event` and quacks like an `event` DOESN'T make it and `event`.

If you are uncertain that it is an event then you are just emitting a Detailed (structured) Log record. See the ["What is being produced section in this comment"](https://github.com/open-telemetry/oteps/pull/265#pullrequestreview-2291119633)

2024-09-28 00:26 UTC, trask commented
@MSNev I think we need to find a way to tease apart all of these ideas and threads into manageable pieces (issues) that we can tackle one PR at a time.

2024-09-28 00:44 UTC, lmolkova commented
> Just because it looks like an event and quacks like an event DOESN'T make it an event.

> If you are uncertain that it is an event then you are just emitting a Detailed (structured) Log record. 

@Nev, let's recognize that that's your opinion and it's not documented in the spec or shared by the whole community. There is no formal definition of what you consider to be an event (at least the one that we can put into the spec. 

According to the current definition - any log record with `event.name` is an event. If you don't agree, please send a PR against the spec and drive the consensus in the community.

2024-09-28 01:24 UTC, MSNev commented
@trask, I agree -- we need to tackle these ideas and threads separately and it should be done in manageable pieces, and these are the discussions that we "should" be having in the new Logs Sig (not here).

But we should also NOT be just wiping the slate clean, to just "simplify" the problem into non-existence / a problem to be solved later, because some people don't understand the need or are overly simplifying the problem space because of their lack of exposure to the problem space.

The Client SIG has worked long and hard and we "where" finally starting to make progress, by removing one of the foundational support pieces just to simplify the problem is not moving forward or listening to all of the relevant concerns. It causing already stilted progress to get worse.

IMHO, this PR (or any PR) which simply alters what has previously been agreed upon (ie. already exists in the Semantic Conventions / Specifications / SDKs / Prototypes), should NOT exist until we have resolved (or at least come to general agreement) around the following open questions (order from the 9/20 Events SIG notes) -- The primary reason I was pushing to explicitly "order" these open questions as they NEED to be answered to provide the foundations to move forward.

- What kind of capabilities should the Logs API have now that it's user-facing (The API's I proposed above)
- What kind of ergonomic improvements make sense now that Logs API is user-facing (The rules / conventions on those API's)
- How to support routing logs from Logs API (The bridge API above)

These are not necessarily easy problems, but there are grounds for agreement and I believe that we have talked past it several times. And I don't believe that these specific issues can be simply "deferred" as they represent the core part of the contentious issues already "deferred" by the Otep.

If we want to "move" forward with PRs, then they should not (yet) be removing either the Bridge API or the Events API definitions but instead they should be creating and refining the new "User-facing" Logs API specification enabling us to build on existing and future agreements with all of the relevant answers to the above (and other) questions taken into consideration and once we have some official prototypes and implementations for people to play with, review we can then remove the any unnecessary specifications.

I would also suggest that as part of this approach that the existing Specs / SDK definitions have added to them references that a "New" common unified user-facing Logs API is being defined (please join new Logs Sig) which will incorporate all of the existing agreed upon functionality, maybe even marking as deprecated as we go, so that we can document the path forward rather than just pulling up all stakes and throwing out the baby with the bath water and starting all over again.

Some existing timelines
- [Current Events Semantic convention](https://github.com/open-telemetry/semantic-conventions/blame/main/docs/general/events.md#event-definition) checked in Aug 31, 2022 (released in v1.13.0 2022-09-19)
- [Current Events API Specification](https://github.com/open-telemetry/opentelemetry-specification/blame/main/specification/logs/event-api.md) checked in Nov 14, 2022 (Split out Logs / Event API - released in v1.16.0 2022-12-08)
- The original combined Logs / Event API (released also in v1.13.0 2022-09-19)

2024-09-28 02:00 UTC, MSNev commented
@lmolkova @trask 

> According to the current definition any log record with `event.name` is an event. If you don't agree, please send a PR against the spec and drive the consensus in the community.

This was part of the compromise that the Client Sig agreed upon to break down the "threads into manageable pieces (issues)" because we understand that everyone is different and has their own problem spaces. This is ALSO why the [spec compliance matrix has the Events API](https://github.com/open-telemetry/opentelemetry-specification/blob/main/spec-compliance-matrix.md#events) explicitly listed as OPTIONAL as not ALL languages / runtimes (at that time) needed to deal with `events`

That has now changed, as of the OTep, Events now exist and have their "role" enhanced so Events ARE now a first class citizen, they still happen to be a "type" of Log Record and the [Log Data Model](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/data-model.md#design-notes) even calls out that it "supports" events. And we are starting to have the difficult discussions around HOW they will or should be used.

We (as OpenTelemetry) have chosen to "Support" the "handling" of Events as a `type` of `LogRecord` (now that Logs exist), prior to Logs existing the Span `addEvent` or worse zero length spans were used to "simulate" the need for `events`. And as part that technical representation choice (which was needed to "share" the same transport) was to represent these `events` as a `LogRecord` WITH and `event.name` attribute -- that part is NOT under debate (but it keeps getting brought back because "Everything is a Log")

- All log `events` ARE Structured Logs, but this does NOT imply that ALL Logs are `events.

Or are you trying to state that a memory dump / file log is an `event` and therefore should have an `event.name` and be treated by ALL providers as `events`

And as I have [already stated in this PR](https://github.com/open-telemetry/opentelemetry-specification/pull/4225#discussion_r1779178035) anything can "Simulate" (generate) a `LogRecord` that "Looks" like an `event` (whether we do it or some application does) but that does not "necessarily" mean that the "simulated" `event` will (or should) comply with any processing rules / semantics that get defined. In fact I explicitly state that they SHOULD NOT (when simulated), therefore (trying) to help define and answer the productive question of "Why" should I use this API vs that and not just boiling the problem down to "Everything is a Log" so it doesn't matter...

Right now in the Application Insights SDK's (Internal and external), technically, EVERYTHING is an Event and we "simulate" EVERYTHING (logs, traces, metrics and events) as a well formed structured Event (message) - it works because we retain the semantic meaning behind everything that is sent so that when received and processed they are handled as required.

So I'm not here proposing that hey lets throw away logs and make everything an `event` (because they are not), what I'm proposing is that we retain and enforce the required Semantic conventions / rules for each "type" of thing that is sent (as a `LogRecord`).

2024-09-28 02:05 UTC, trask commented
@MSNev would you agree to move forward with this PR if (in addition to https://github.com/open-telemetry/opentelemetry-specification/pull/4225#issuecomment-2379899009) it marks the Event API and Event SDK as deprecated instead of deleting them?

2024-09-28 02:53 UTC, MSNev commented
@trask 

This is effectively what I stated with these 2 comments

> If we want to "move" forward with PRs, then they should not (yet) be removing either the Bridge API or the Events API definitions but instead they should be creating and refining the new "User-facing" Logs API specification enabling us to build on existing and future agreements with all of the relevant answers to the above (and other) questions taken into consideration and once we have some official prototypes and implementations for people to play with, review we can then remove the any unnecessary specifications.

> I would also suggest that as part of this approach that the existing Specs / SDK definitions have added to them references that a "New" common unified user-facing Logs API is being defined (please join new Logs Sig) which will incorporate all of the existing agreed upon functionality, maybe even marking as deprecated as we go, so that we can document the path forward rather than just pulling up all stakes and throwing out the baby with the bath water and starting all over again.

As we need to come to an agreement on what IS an `Event` and therefore in terms of the now public API what Semantic processing / rules should be applied to an `event` to continue the work required to correctly identify and handle them.

From my perspective, I keep getting asked to "validate" what I have been calling the "HOW" (how are events Sent / Represented), that is the WRONG question, from my perspective we have NO disagreements (you might even say that we are actually in violent agreement). 

So, to state this part of the discussion explicitly and CLEARLY

- I have not stated ANYWHERE in this PR or in any of the MANY comments in the OTep that contradicts the agreed upon technical "HOW" which has been defined for around 2 years ago.
- Events ARE sent via OTLP Logs represented as a `LogRecord` with an `event.name` attribute -- game over, end of discussion.

Can we move onto the REAL set of questions that need to be answered (and which I keep trying to redirect back to) around the Semantics and meaning of Events.

Especially, now that we have a 1st class citizen (called Events as per OTep # 265) and a new "Public Log API" we need to agree upon the HOW (yes technical) they are (CREATED, EMITTED, HANDLED, PROCESSED - Note: Explicitly NOT packaged as a `LogRecord` and Sent as a Log), so that they retain their Semantic meaning across the entire pipeline.

So that when an application / instrumentation chooses (clarification needed and in my comments above try to start the process) to Send an `event` via the `emitEvent` API they have a clear set of expectations vs just sending a structured `LogRecord` (`emitLog`) vs Using the `Bridge API` (`emitLogBridge`) vs `Simulating` any representation (Event or Structured Log) via the `Bridge API` or any runtime specific Logging framework. All of which have proposals above for us to discuss and agree apon.

As specifically `events` CAN, SHOULD and WILL have different Semantic meanings between applications, instrumentation, adopters and processors and therefore needs to have some clarity beyond "it's just a `LogRecord`

2024-09-28 03:03 UTC, trask commented
>> @MSNev would you agree to move forward with this PR if (in addition to [#4225 (comment)](https://github.com/open-telemetry/opentelemetry-specification/pull/4225#issuecomment-2379899009)) it marks the Event API and Event SDK as deprecated instead of deleting them?

>@trask
>
> This is effectively what I stated with these 2 comments

great! I don't see any problem with going that route, and it will allow us to make some incremental progress here, and we can split your other concerns out into separate issues and work on addressing them in follow-up PRs

2024-09-30 09:41 UTC, pellared commented on CHANGELOG.md
> +- Remove Events API and SDK. Rename Logs Bridge API to Logs API and do not discourage from direct usage.
I decided to simply bring back the Events API and SDK. We can address it later as a separate PR.

2024-09-30 10:07 UTC, pellared commented on specification/logs/api.md
> +This document defines a log API.
I changed the PR so that  Logs API can be used to emit events but I have not removed the Events API.

2024-09-30 10:07 UTC, pellared commented on specification/logs/api.md
> +The API serves following use cases.
I think this should rather require refining the SDK and not the API.

2024-09-30 10:10 UTC, pellared commented on specification/logs/api.md
> +It is provided for logging library authors to build
It is up to the bridge implementation how the logging library would be mapped to OTel Logs Data Model. I think we should rather create some "guidance" / "recommendations" for log bridge authors. We cannot control how the bridges are going to be implemented.

For sure this should be out of scope of this PR.

2024-09-30 10:15 UTC, pellared commented on specification/logs/api.md
> +It is provided for application developers to emit structured log records
> This should call out the "difference" between the processing / handling / semantics of an event vs a structured log

I find it as out of scope. We need such mechanism for all log records. From last SIG meeting agenda:

> We need filtering and separate log processing pipelines. E.g. distinct processing for different exporters or different processing for events and other log records. Also needed for [Specify how Logs SDK implements Enabled #4207](https://github.com/open-telemetry/opentelemetry-specification/issues/4207)

2024-09-30 10:16 UTC, pellared commented on specification/logs/event-api.md
> -<!-- toc -->
Kept separate.

2024-09-30 10:26 UTC, pellared commented
> maybe even marking as deprecated as we go

I decided to make smaller steps and leave Events API and SDK. I made some little changes in Events API so that it should "fit" to the changes applied in this PR. I would prefer to have a separate PR regarding deprecating Events API+SDK as I think there may be also other options like keep Events API but remove Events SDK, maybe even further rename Events API to Events Library (a library for emtting events which is backed up by Logs API). At this point of time, I do not feel comfortable deprecating a concept/API that may be wanted by other languages.

2024-09-30 10:52 UTC, pellared commented
@MSNev, @lmolkova, @trask, @reyang, @cijothomas: PTAL

2024-09-30 14:57 UTC, MSNev commented on CHANGELOG.md
> +- Make Logs Bridge API as the Logs API and do not discourage from direct usage.
No, this PR should be about either
- Merging the entire Logs Bridge API AND the Events API (as is) and marking ALL as in-progress
- Creating a new EMPTY Logs API stating with comments in the Events and Bridge API stating that the new Logs API will encompass ALL of the functionality from the currently represented in the current API's (with the exact details to be worked on)

2024-09-30 14:59 UTC, MSNev commented on specification/logs/README.md
> +- OpenTelemetry defines a Logs API for [emitting LogRecords](./api.md#emit-a-logrecord).
This NEEDS to include comments about also emitting events as that is the intention

2024-09-30 15:00 UTC, MSNev commented on specification/logs/README.md
> +* [Logs API](./api.md)
How about having links to the old API's stating that the this new API will encompass the existing functionality.

2024-09-30 15:06 UTC, MSNev commented on specification/logs/api.md
> +## Convenience
This is PART of the issue with this process.

## Events are MORE than just a Convenience!

I would be fine with wording along the lines of

For languages that do not need or want to provide any OpenTelemetry Event support because they have their own native or common libraries, then they MAY choose to not implement the `emitEvent` functionality and support.

2024-09-30 15:09 UTC, MSNev commented on specification/logs/data-model.md
> +of LogRecord, not a separate concept.
Remove the `not a separate concept` or rephase that OpenTelemetry encapsulates and transmits as a `LogRecord` 


From OpenTelemetry's perspective LogRecords and Events are both represented
using the same [data model](./data-model.md). As such an Event is sent as a `LogRecord`
with an identifying `event.name` attribute.

2024-09-30 15:16 UTC, MSNev commented on specification/logs/data-model.md
> +logs to have a common format within that structure. When OpenTelemetry
And this is the crux of the problem

> When OpenTelemetry instrumentation emits logs, those logs SHOULD be formatted as Events.

While Events are represented as `LogRecords` not all Logs are `Events`

2024-09-30 15:17 UTC, MSNev requested changes
Still needs work

2024-09-30 15:29 UTC, trask commented on CHANGELOG.md
> +- Make Logs Bridge API as the Logs API and do not discourage from direct usage.
creating a new `logs/api.md` and leaving both the existing (stable) `logs/bridge-api.md` and (experimental) `logs/event-api.md` alone sounds like a good path forward.

the `logs/api.md` page can explain that one of its goals is to replace the Event API and possibly also the Bridge API.

2024-09-30 16:28 UTC, pellared commented on specification/logs/api.md
> +## Convenience
> Events are MORE than just a Convenience

I find this as an opinionated statement based on the current definition of Opentelemetry Events

2024-09-30 16:30 UTC, pellared commented on specification/logs/data-model.md
> +of LogRecord, not a separate concept.
No. This is an extract from Events API. I have not changed a single word. Out of scope.

2024-09-30 16:31 UTC, pellared commented on specification/logs/data-model.md
> +logs to have a common format within that structure. When OpenTelemetry
I do not follow

2024-09-30 16:33 UTC, pellared commented on specification/logs/README.md
> +* [Logs API](./api.md)
I do not want to create yet another API.

2024-09-30 16:37 UTC, pellared commented on CHANGELOG.md
> +- Make Logs Bridge API as the Logs API and do not discourage from direct usage.
I would prefer not creating yet another API. The specification was foreseeing that Logs Bridge API may be evolved into Logs API. I thing that having them separated in the specification will make it harder to follow and maintain. This is the main motivation behind this PR. I would rather prefer having a separate, alternate PR instead of changing this one

2024-09-30 16:41 UTC, pellared commented on specification/logs/README.md
> +- OpenTelemetry defines a Logs API for [emitting LogRecords](./api.md#emit-a-logrecord).
It is described in API and Data Model. Do we need to repeat it? Can you suggest a change?

2024-09-30 17:12 UTC, pellared commented on CHANGELOG.md
> +- Make Logs Bridge API as the Logs API and do not discourage from direct usage.
If there are good reasons to have the changes as Development then yes. I did my best to limit the scope so that it may be seen as acceptable in the Stable portion of the specification.

2024-09-30 17:26 UTC, pellared commented on CHANGELOG.md
> +- Make Logs Bridge API as the Logs API and do not discourage from direct usage.
Maybe I should mark Convenience section as Development as this is a new "functional' addition to logs.

2024-09-30 17:52 UTC, trask commented on CHANGELOG.md
> +- Make Logs Bridge API as the Logs API and do not discourage from direct usage.
I've added a topic to tomorrow's Spec SIG agenda:

* Any gotchas to renaming the “Logs Bridge API” to “Logs API” inside of a stable document?

2024-09-30 18:08 UTC, MSNev commented on specification/logs/api.md
> +## Convenience
> I find this as an opinionated statement based on the current definition of Opentelemetry Events

## And THAT is the crux of the disagreement

You (and several others) DON'T believe and either DON'T understand or WANT to understand that "Events" are NOT JUST Logs, so your Opinionated view / statement is to remove something that you DON'T understand.

As stated in the Oel (this portion I agree with)

> OpenTelemetry Events are a **type** of OpenTelemetry Log that requires an event name and follows a specific structure implied by that event name.

They are a TYPE of Log, it does not state that ALL Logs are Events and it does not state the there is ONLY 1 TYPE of Log (Events). Calling Every LOG and `Event` destroys the Semantic meaning of what is an `Event`.

That does not mean that there isn't room to "define" the appropriate Semantics to keep Both, but that is the discussions and part of the agreements that we need to make BEFORE we can conclude this PR (as I've mentioned eariler)

2024-09-30 18:11 UTC, MSNev commented on specification/logs/data-model.md
> +of LogRecord, not a separate concept.
In the framing of the Event API as a separate entity and therefore the creation and sending of the resulting Event as a `LogRecord` (and not a separate `Event` concept) it make sense there. If does NOT make sense as part of folding into a SINGLE Api which emits both because now they ARE 2 separate concepts that are emitted from the same API.

2024-09-30 18:13 UTC, reyang commented
> @MSNev, @lmolkova, @trask, @reyang, @cijothomas: PTAL
> 
> Let me know if you are OK to "undraft" the PR (mark is as "Ready for review").

+1 on removing the "Draft" status.

2024-09-30 18:15 UTC, lmolkova commented on specification/logs/api.md
> +## Convenience
Could we call this section "Optional methods" so it works for everyone?

2024-09-30 18:18 UTC, trask commented
> > @MSNev, @lmolkova, @trask, @reyang, @cijothomas: PTAL
> > Let me know if you are OK to "undraft" the PR (mark is as "Ready for review").
> 
> +1 on removing the "Draft" status.

👍 I think it will be good to widen the circle of reviewers, and I plan to raise this PR in the Spec meeting tomorrow, so will be good if more people take a look at it before then

2024-09-30 18:18 UTC, MSNev commented on specification/logs/data-model.md
> +logs to have a common format within that structure. When OpenTelemetry
See not just my comments but also @jkwatson https://github.com/open-telemetry/oteps/pull/265#discussion_r1734960546 in the OTep.

2024-09-30 18:24 UTC, MSNev commented
> > > @MSNev, @lmolkova, @trask, @reyang, @cijothomas: PTAL
> > > Let me know if you are OK to "undraft" the PR (mark is as "Ready for review").
> > 
> > 
> > +1 on removing the "Draft" status.
> 
> 👍 I think it will be good to widen the circle of reviewers, and I plan to raise this PR in the Spec meeting tomorrow, so will be good if more people take a look at it before then

Why the push to RAM this change through?

We have not answered some of the basic fundamental questions and not had the first official meeting to even start to address some the basic mis-understandings and concepts that you are preparing to throw out.

There is LOTS of common ground that we can build one and the SHOULD be documented, but this PR (in it's current state) is not doing that

2024-09-30 18:24 UTC, lmolkova commented on specification/logs/api.md
> +[OpenTelemetry Events](data-model.md#events).
I believe by making Otel Logs API user-facing, we should not limit instrumentation to events. It should be fine to emit nameless log records. 

So maybe 

```suggestion
logs.
```

?

2024-09-30 18:26 UTC, lmolkova commented on specification/logs/data-model.md
> +logs to have a common format within that structure. When OpenTelemetry
It seems to be a copy-paste from the existing 

https://github.com/open-telemetry/opentelemetry-specification/blob/fbaf8468c599d858df515c88bac58d02c9afdb29/specification/logs/event-api.md?plain=1#L44-L48

but I wonder if we should allow instrumentations to emit logs or events now that logging api is going to be user-facing. 

Left another comment on it  - https://github.com/open-telemetry/opentelemetry-specification/pull/4225/files#r1781573289

2024-09-30 18:29 UTC, MSNev commented on specification/logs/api.md
> +[OpenTelemetry Events](data-model.md#events).
> I believe by making Otel Logs API user-facing, we should not limit instrumentation to events. It should be fine to emit nameless log records.
> 
> So maybe
> 
> ?

ABSOLUTELY!

And whether that are called "nameless" or there is some other "name" (not `event.name`) that describes that `type` (options discussed include `log.name`, `log.record.name` maybe even a new `log.type` (But the enumeration of this is extremely problematic as what "level" do you define)) of Log entry is specifically being written is just part of the unanswered questions.

2024-09-30 18:29 UTC, trask commented
> Why the push to RAM this change through?

No one is ramming anything through, we're just adding it to the Spec meeting agenda because there are some tricky questions around stability that could benefit from discussion with the @open-telemetry/technical-committee

2024-09-30 18:30 UTC, lmolkova commented on specification/logs/event-api.md
> +[events](data-model.md#events) without needing to depend on a third party logger.
Perhaps this part is changing now. 

Maybe

```suggestion
The Events API was designed to allow shared libraries and applications to emit named and structured logs with consistent semantics.
```

?

Or maybe just remove this sentence?

2024-09-30 18:37 UTC, lmolkova commented
> We have not answered some of the basic fundamental questions and not had the first official meeting to even start to address some the basic mis-understandings and concepts that you are preparing to throw out.

The way this PR is written now it does not seem to change anything around event definition. The wording around events is copy-pasted with no change. So the only fundamental questions it raises now are around log API and it's stability.  Let's try to review it from this perspective and if there are any concerns around **existing** wording in the spec, let's create issues and proposals separately from this PR.

2024-09-30 18:55 UTC, pellared commented on specification/logs/api.md
> +[OpenTelemetry Events](data-model.md#events).
It is about OTel instrumentation libraries (not any "instrumentation").

> When OpenTelemetry instrumentation emits logs, those logs SHOULD be formatted as Events. 

from https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/event-api.md#event-data-model

as well as https://github.com/open-telemetry/oteps/blob/58d6420237091bcfb739f329e09adaa7ec03f702/text/0265-event-vision.md#L29-L32

The next paragraph is about using the API to emit any logs.

2024-09-30 19:00 UTC, pellared commented on specification/logs/event-api.md
> +[events](data-model.md#events) without needing to depend on a third party logger.
LGTM. We can the apply your suggestion if there are no counter arguments.

2024-09-30 19:04 UTC, MSNev commented on specification/logs/event-api.md
> +[events](data-model.md#events) without needing to depend on a third party logger.
It was designed to emit named and structured EVENTS that happen to be sent / represented as a `LogRecord`, they are still EVENTS and not JUST A LOG!

2024-09-30 19:06 UTC, pellared commented on specification/logs/api.md
> +## Convenience
I would rather remove the whole section. 

I think it is needed not only for sake of events but e.g. Java may want to have convenient methods like `Info`, `Warn`, `Error`.

> Calling Every LOG and Event destroys the Semantic meaning of what is an Event.

Nobody does it. Currently, just call every log with `event.name` attribute as an Event. For the SDK/Data Model/Collector perspective it does not matter how it was created. This is currently the way an Event is defined and I am not making any change to it.

2024-09-30 19:07 UTC, MSNev commented
> > We have not answered some of the basic fundamental questions and not had the first official meeting to even start to address some the basic mis-understandings and concepts that you are preparing to throw out.
> 
> The way this PR is written now it does not seem to change anything around event definition.

Please see my review comments.

> The wording around events is copy-pasted with no change. So the only fundamental questions it raises now are around log API and it's stability. Let's try to review it from this perspective and if there are any concerns around **existing** wording in the spec, let's create issues and proposals separately from this PR.

This is more than just Copying and pasting, "moving" changes context, AND I provided my review comments on the basis of moving forward and ensuring that the reasoning originally provided for the wording and definitions is not lost in the process.

2024-09-30 19:10 UTC, pellared commented on specification/logs/data-model.md
> +of LogRecord, not a separate concept.
>  they ARE 2 separate concepts

They are not. Event is a specialization of a LogRecord. I never have seen in spec that Events and Logs are separate signals (this would mean for me that these are separate concepts).

2024-09-30 19:14 UTC, MSNev commented on specification/logs/api.md
> +[OpenTelemetry Events](data-model.md#events).
And both of those links talked about them be "represented" by the same Data Model, or as a "type" of Log, it is NOT stating that this makes them the SAME thing (beyond the transport / representation), they still HAVE different Semantics.
Circling back to the OTep this is the HOW are they SENT not WHAT are they.

What is an Event https://github.com/open-telemetry/semantic-conventions/blob/main/docs/general/events.md
What is a Log https://github.com/open-telemetry/semantic-conventions/blob/main/docs/general/logs.md

Nowhere is it saying that a Log is an Event

2024-09-30 19:19 UTC, MSNev commented on specification/logs/api.md
> +It is provided for application developers to emit structured log records
Am I stating anywhere that we don't -- NO.
But I am stating that we ALSO need this for Events (The Event API has this for that exact purpose), we could have "just" ignored it and said hey go just use a genera Log processor on your Log definition.

2024-09-30 19:20 UTC, pellared commented on specification/logs/api.md
> +## Convenience
Another problem, I see in defining `Emit an Event` method (in scope of this PR) is that there would be an ambiguity what should happen if a user adds an additional `event.name` attribute. Should the `name` parameter or `event.name` attribute have precedence?

PS. The same problem currently exists  in https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/event-api.md#emit-event

2024-09-30 19:21 UTC, MSNev commented on specification/logs/api.md
> +[OpenTelemetry Events](data-model.md#events).
And as an example of additional cases where I'm saying that we are talking past each other on the possible solutions, 
Please go and see my comment from Sept 9th IN THE OTEP
https://github.com/open-telemetry/oteps/pull/265#issuecomment-2339337199, in the design section and the "Combining API's" (the exact thing you are trying to define here)

Nothing over there was "simply" ranting, it was about trying to inform and provide workable solutions that will work for ALL of US and the community.

2024-09-30 19:22 UTC, pellared commented on specification/logs/api.md
> +[OpenTelemetry Events](data-model.md#events).
@lmolkova PTAL https://github.com/open-telemetry/opentelemetry-specification/pull/4225/commits/d3aefef7b4f62448e4d4302fdba9833691afa484

2024-09-30 19:31 UTC, MSNev commented on specification/logs/api.md
> +[OpenTelemetry Events](data-model.md#events).
Oh and a specific call out on this

> It is about OTel instrumentation libraries (not any "instrumentation").

Are we or are we not defining an Open Common API for Everyone -- not JUST "OTel instrumentation libraries", at least that is what I'm trying to do -- https://opentelemetry.io/docs/what-is-opentelemetry/

> Focused on the generation, collection, management, and export of telemetry. A major goal of OpenTelemetry is that you can easily instrument your applications or systems, no matter their language, infrastructure, or runtime environment. The storage and visualization of telemetry is intentionally left to other tools.

With the mission / vision of  https://opentelemetry.io/community/mission/

> OpenTelemetry’s Mission: to enable effective observability by making high-quality, portable telemetry ubiquitous.

2024-09-30 19:36 UTC, lmolkova commented on specification/logs/event-api.md
> +[events](data-model.md#events) without needing to depend on a third party logger.
@MSNev can you make a suggestion that would work for you? The original sentence is no longer applicable, what would  be a good replacement?

2024-09-30 19:41 UTC, pellared commented on specification/logs/event-api.md
> +[events](data-model.md#events) without needing to depend on a third party logger.
But they are still logs 😉

2024-09-30 19:43 UTC, MSNev commented on specification/logs/event-api.md
> +[events](data-model.md#events) without needing to depend on a third party logger.
Why is it no longer applicable, the original sentence is still valid. If the Events API is being merged into a new common Log API then nothing has changed.

2024-09-30 19:46 UTC, lmolkova commented on specification/logs/api.md
> +[OpenTelemetry Events](data-model.md#events).
Let's get back to the original comment - we're making log API user-facing so that OTel instrumentations or user applications could emit logs or events using it directly. 

There could be many reasons to use OTel log api directly (bridge overhead, lack of structured logging, not being able to record structured body with 3rd party API,  ambiguity in how bridge maps properties from 3rd party logging facade to otel). There is nothing specific about events here, so I'm suggesting not to mention them in the motivation to behind user-facing logging API/

2024-09-30 19:49 UTC, lmolkova commented on specification/logs/api.md
> +It is provided for application developers to emit structured log records
based on the current version of spec, it's totally valid to emit events using log bridge. We don't have a requirement to support separate pipelines today and this PR does not change status quo 

https://github.com/open-telemetry/opentelemetry-specification/blob/fbaf8468c599d858df515c88bac58d02c9afdb29/specification/logs/event-api.md?plain=1#L79-L81

2024-09-30 19:58 UTC, pellared commented on specification/logs/api.md
> +## Convenience
I created https://github.com/open-telemetry/opentelemetry-specification/issues/4233

And also  committed https://github.com/open-telemetry/opentelemetry-specification/pull/4225/commits/cc0f26289786620e9708a15f7534347c777cb9b9 to avoid this issue in scope of this PR

2024-09-30 20:04 UTC, pellared commented on specification/logs/api.md
> +[OpenTelemetry Events](data-model.md#events).
> There is nothing specific about events here, so I'm suggesting not to mention them in the motivation to behind user-facing logging API/.

The reason I mentioned them is that currently the specification says that OpenTelemetry instrumentation libraries SHOULD emit well-defined events (and not just random log records). I think it would be bad if an instrumentation library emit log records that are not defined in https://github.com/open-telemetry/semantic-conventions. Or maybe we anticipate that the semantic conventions will define conventions for log records which will not be events?

I think also that this description is in the spirit of the OTEP: https://github.com/open-telemetry/oteps/blob/58d6420237091bcfb739f329e09adaa7ec03f702/text/0265-event-vision.md?plain=1#L29-L32

2024-09-30 20:07 UTC, pellared commented on specification/logs/event-api.md
> +[events](data-model.md#events) without needing to depend on a third party logger.
I agree with @MSNev that the current sentence is still applicable/valid. @lmolkova, how about resolving?

2024-09-30 20:54 UTC, lmolkova commented on specification/logs/api.md
> +[OpenTelemetry Events](data-model.md#events).
Imagine I'm instrumenting kafka:
- there could be some events I'd emit - e.g. cluster leader is unreachable - which are documented in the semconv
- there could also be things I just want to let my users know of via logs. E.g. certain configuration was picked, connection has dropped, etc. I could use 3rd party logging library, but why if I can use OTel logging API without adding a new dependency?

The library logs are emitted with is not relevant to users - they'd get the same logs if lib used 3rd party logger or OTel API. So I don't see why we should limit instrumentations from using OTel API to emit undocumented regular (but structured) logs.

2024-09-30 20:58 UTC, lmolkova commented on specification/logs/event-api.md
> +[events](data-model.md#events) without needing to depend on a third party logger.
I think it's not relevant since with this PR we will have user-facing logging API.

I.e. we have user-facing logging API and the second part of this sentence no longer makes sense: "The Events API was designed to allow shared libraries to emit events __without needing to depend on a third party logger__"

2024-09-30 21:12 UTC, pellared commented on specification/logs/event-api.md
> +[events](data-model.md#events) without needing to depend on a third party logger.
Maybe

```suggestion
The Events API was designed to allow shared libraries to emit
[events](data-model.md#events).
```

2024-09-30 21:16 UTC, lmolkova commented
> This is more than just Copying and pasting, "moving" changes context, AND I provided my review comments on the basis of moving forward and ensuring that the reasoning originally provided for the wording and definitions is not lost in the process.

To clarify, you don't agree with moving [Event Data Model](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/event-api.md#event-data-model) section (as is) from event-api.md file to [data-model.md](https://github.com/open-telemetry/opentelemetry-specification/blob/47468d49e37778925369af35f3211886b5c4b297/specification/logs/data-model.md#events) file?

2024-09-30 21:28 UTC, lmolkova commented on specification/logs/api.md
> +[OpenTelemetry Events](data-model.md#events).
> How would the instrumentation library report a problem if the OTel Logs Provider is not configured?

it won't - I mean someone could configure default provider (stdout), but in general case if you use 3rd party logging library, it's not a lib responsibility to notify you that your logging provider is not configured. 

We can borrow some ideas from logging libs. E.g. SLF4J notifies you if provider is not configured with something like this in stderr:

<img width="809" alt="image" src="https://github.com/user-attachments/assets/11118058-7daf-444a-98e1-b24c67607b6c">

--------------------

I agree that it's not a viable choice for instrumentation today to rely on OTel logs being configured as a main source of logging, but 3 years from now it could be a nice option to report all telemetry with otel instead of taking dependency on something else.  

And we're not restricting anything - we're adding more options.

In any case, I'd like to have this discussion tomorrow on the spec call, but if you feel strongly about making progress on this PR without addressing it, I'm fine doing it as a follow up.

2024-09-30 21:32 UTC, pellared commented on specification/logs/api.md
> +[OpenTelemetry Events](data-model.md#events).
I created https://github.com/open-telemetry/opentelemetry-specification/issues/4234

2024-09-30 21:35 UTC, austinlparker commented on specification/logs/api.md
> +[OpenTelemetry Events](data-model.md#events).
> Imagine I'm instrumenting kafka:
> 
> - there could be some events I'd emit - e.g. cluster leader is unreachable - which are documented in the semconv
> 
> - there could also be things I just want to let my users know of via logs. E.g. certain configuration was picked, connection has dropped, etc. I could use 3rd party logging library, but why if I can use OTel logging API without adding a new dependency?
> 
> 
> 
> The library logs are emitted with is not relevant to users - they'd get the same logs if lib used 3rd party logger or OTel API. So I don't see why we should limit instrumentations from using OTel API to emit undocumented regular (but structured) logs.

I think this is a good example. You can emit an untyped event (which is a nameless logrecord), and it would bypass any event pipelines set up, but it would still give you a single api surface at the low level.

2024-09-30 21:39 UTC, lmolkova commented on specification/logs/api.md
> +[OpenTelemetry Events](data-model.md#events).
BTW @pellared my main focus with this is native instrumentations where now I need to pick one API for logging and use OTel for everything else. I.e. I don't mean instrumentation logs, I mean the underlying library logs.

2024-09-30 21:41 UTC, trask commented on specification/logs/data-model.md
> +### Events
should this section be marked with stability `Development`?

2024-09-30 22:10 UTC, trask commented on specification/logs/api.md
> +Languages MAY provide additional ergonomics and convinence APIs. For instance,
```suggestion
Languages MAY provide additional ergonomics and convenience APIs. For instance,
```

2024-09-30 22:10 UTC, trask commented on specification/logs/event-api.md
> +Instrumentation authors and application developers are encouraged can call this
```suggestion
Instrumentation authors and application developers are encouraged to call this
```

2024-10-16 03:18 UTC, closed without merging