Rename Logs Bridge API to Logs API and do not discourage from direct usage
open-telemetry/opentelemetry-specification pull request #4235
Opened 2024-09-30 22:59 UTC by trask

Part of https://github.com/open-telemetry/oteps/pull/265

Extracted from @pellared's #4225

2024-09-30 23:17 UTC, cijothomas commented on specification/logs/api.md
> +to reflect that it is now a user-facing API.**
```suggestion
to reflect that it is now also a user-facing API.**
```

2024-09-30 23:18 UTC, cijothomas approved these changes
LGTM, and aligned with the [OTEP](https://github.com/open-telemetry/oteps/pull/265/files)

2024-09-30 23:37 UTC, lmolkova approved these changes

2024-10-01 00:18 UTC, tedsuo approved these changes
Baby steps :)

2024-10-01 00:42 UTC, MSNev commented on specification/logs/event-sdk.md
> +to [emit a logRecord](./api.md#emit-a-logrecord) as follows:
This is still part of the open questions around the Logs API, and I have the same set of concerns around the bait and switch that this could lead to.

IMHO: We SHOULD have a `emitEvent` as part of the public API and which this is the Event-SDK (that we have general agreement on that this is going away), this has other context implications that are being "bypassed" by not addressing the Open questions around the "public" Logs API FIRST!

2024-10-01 00:44 UTC, MSNev commented on specification/logs/event-api.md
> -[Logs Bridge API](./bridge-api.md), instrumentation authors and application
While I'm happy to see the kluge get deleted (because it was the ONLY Logs API that existed), it really should be that we are "merging" this functionality into the new "Logs API" and not just "bypassing" the harder questions.

2024-10-01 00:48 UTC, MSNev commented on specification/logs/api.md
>  **Status**: [Stable](../document-status.md), except where otherwise specified
And this is really part of the problem, as we (general OpenTelemetry community) have agreed that
- [OpenTelemetry SHOULD provide a (user-facing) Logs API](https://github.com/open-telemetry/oteps/blob/main/text/0265-event-vision.md#api)

We have not agreed that the existing Stable Bridge API is that API.

2024-10-01 00:49 UTC, MSNev requested changes
See comments, this is hidden implications that need to be explicitly addressed.

2024-10-01 00:50 UTC, MSNev commented
> Baby steps :)

These are not the baby steps, I'm looking for. This is a bit of a side-step and has broader implications.

2024-10-01 01:19 UTC, trask commented on specification/logs/api.md
>  **Status**: [Stable](../document-status.md), except where otherwise specified
> We have not agreed that the existing Stable Bridge API is that API.

this PR is explicitly asking for that agreement

fwiw, this was already in the spec:

> [in the event OpenTelemetry were to add a user facing API, the Logs Bridge API would be a natural starting point](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/bridge-api.md#artifact-naming)

2024-10-01 01:24 UTC, trask commented on specification/logs/event-sdk.md
> +to [emit a logRecord](./api.md#emit-a-logrecord) as follows:
we have to find a way to make incremental progress

let's see if we can get agreement here that the Logs Bridge API is the starting point for the Logs API

after that we can tackle:

> [OpenTelemetry SHOULD provide a (user-facing) Logs API that includes the capability to emit OpenTelemetry Events.](https://github.com/open-telemetry/oteps/blob/main/text/0265-event-vision.md#api)

2024-10-01 01:30 UTC, MSNev commented
@trask @tedsuo

This is baby ~steps~ crawling and MORE aligned with the OTep

[https://github.com/open-telemetry/opentelemetry-specification/pull/4236](Introduce the new user-facing Logs API as a placeholder)

2024-10-01 01:33 UTC, MSNev commented on specification/logs/api.md
>  **Status**: [Stable](../document-status.md), except where otherwise specified
Then I current reject this option, and have #4236 and [OTep # 267](https://github.com/open-telemetry/oteps/pull/267) as the reasons why -- because we don't have agreement.

2024-10-01 01:36 UTC, MSNev commented on specification/logs/api.md
>  **Status**: [Stable](../document-status.md), except where otherwise specified
As I believe the Events API would be a more natural starting point because we are introducing the ability to emit Log Records as this new things we called Event in the OTep, But we didn't agree to anything in the OTep beyond that there is Something called an Event (which is a type of Log) and there will be a user-facing Logs API that will provide the ability to Emit these things called Events.

2024-10-01 03:33 UTC, reyang approved these changes

2024-10-01 04:33 UTC, tedsuo commented on specification/logs/api.md
>  **Status**: [Stable](../document-status.md), except where otherwise specified
@MSNev , the log is declared stable. There's no going back from that. There's also no technical requirement that the current API fails to solve as a starting point, so continuing from our current stable starting point does not actually create a problem.

I completely understand that the approach we are taking is not your favorite approach. But we have to make personal compromises in order to move the project forward. Not everything we do in the spec matches the exact way I would like it to be. But if it matches the technical requirements, has buy in from the community, and is backwards compatible, then I will work to polish that approach. And after it's all done I end up liking it anyways, because we did the hard work to cleanly meet the requirements and at the end of the day, that's what matters.

All I'm asking is that you do the same for us. After incredibly extensive discussion there are 21 approvals for https://github.com/open-telemetry/oteps/pull/265, that is community agreement to continue with the approach we are taking. You can't block the entire project as a lone vote when you haven't convinced anyone that there is actually a problem!

Honestly, I'm not even sure what you are objecting to! It sounds like you are incredibly against the chosen course of action, but when I see your PRs, they appear to just be continuing on that course! It feels like there is a huge amount of philosophizing mixed in with your technical proposals, and it's really making it difficult for me to understand what you actually want. Is it just a reframing of what we are doing? It sounds like on the one hand you're trying to blow everything up and on the other hand stay the course. I really want to make this work but I don't know what to do.

2024-10-01 05:43 UTC, pellared approved these changes

2024-10-01 13:34 UTC, jack-berg commented
It feels odd to remove the "not user facing" bits of the stable document before adding the portions that users are intended to call. I understand that the goal is to make incremental progress, but releasing in this state produces a confusing read for the uninformed reader.

Should we commit to completing the followup steps before the next release?

Can we add a "not user facing" qualification to the "emit log record" operation?

2024-10-01 14:09 UTC, jack-berg commented
> Why? This is one of the goals to make it user facing.

I thought the goal was to extend the log API with an "emit event" operation with the types of ergonomics expected out of a user facing API. The lower level (and bad ergonomics) "emit log record" operation should still be targeted at log appenders.

2024-10-01 15:05 UTC, MSNev commented
> > Why? This is one of the goals to make it user facing.
> 
> I thought the goal was to extend the log API with an "emit event" operation with the types of ergonomics expected out of a user facing API. The lower level (and bad ergonomics) "emit log record" operation should still be targeted at log appenders.

And this is WHY I created my version of this PR with an EMPTY (to be worked on) section of the user API and not inherit and re-use any existing API that has not been agreed or started to be defined.

2024-10-01 19:43 UTC, trask commented
Closing in favor of #4236 where we are implementing @tigrannajaryan's https://github.com/open-telemetry/opentelemetry-specification/pull/4235#issuecomment-2386373209

2024-10-01 19:43 UTC, closed without merging