[WIP] Add MeasurementProcessor specification to Metrics SDK
open-telemetry/opentelemetry-specification pull request #4318
Opened 2024-12-03 10:32 UTC by Blinkuu

Fixes #4298

## Changes

TODO

For non-trivial changes, follow the [change proposal process](https://github.com/open-telemetry/opentelemetry-specification/blob/main/CONTRIBUTING.md#proposing-a-change).

* [ ] Related issues #
* [ ] Related [OTEP(s)](https://github.com/open-telemetry/oteps) #
* [ ] Links to the prototypes (when adding or changing features)
* [ ] [`CHANGELOG.md`](https://github.com/open-telemetry/opentelemetry-specification/blob/main/CHANGELOG.md) file updated for non-trivial changes
* [ ] [`spec-compliance-matrix.md`](https://github.com/open-telemetry/opentelemetry-specification/blob/main/spec-compliance-matrix.md) updated if necessary

2024-12-03 10:42 UTC, Blinkuu commented on specification/metrics/sdk.md
> +
The big question is whether we want to make `MeasurementProcessor` a more fundamental concept and symmetrically to `LogRecordProcessor` and `SpanProcessor`.

If not, then `Shutdown` and `ForceFlush` are not really needed, making `MeasurementProcessor` a slightly more capable version of Java's experimental `AttributesProcessor`.

https://github.com/open-telemetry/opentelemetry-java/blob/d61a5c3b37cf149ab87d1a1e2ec05dc44af20998/sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/view/AttributesProcessor.java#L31

However, there is also another route where these processors become a more fundamental concept. We could provide built-in processors that facilitate views and aggregations and push data to exporters.

2024-12-03 11:05 UTC, pellared commented
Please sign the CLA.

2024-12-03 11:07 UTC, pellared commented on specification/metrics/sdk.md
> +
```suggestion

**Status**: [Development](../document-status.md)

```

2024-12-03 16:36 UTC, reyang commented on specification/metrics/sdk.md
> +* `context` - the resolved `Context` (the explicitly passed `Context` or the current `Contex`)
```suggestion
* `context` - the resolved `Context` (the explicitly passed `Context` or the current `Context`)
```

2024-12-03 16:39 UTC, reyang commented on specification/metrics/sdk.md
> +
Do we allow the processor to "drop" the measurement (e.g. the processor decided that it doesn't want the measurement) or other operations beyond modifications on the value and attributes?

2024-12-03 16:40 UTC, reyang commented on specification/metrics/sdk.md
> +`Shutdown` SHOULD be called only once for each`MeasurementProcessor` instance. After the call to `Shutdow`, subsequent calls to `OnMeasure` are not allowed. SDKs SHOULD ignore these calls gracefully,
```suggestion
`Shutdown` SHOULD be called only once for each `MeasurementProcessor` instance. After the call to `Shutdown`, subsequent calls to `OnMeasure` are not allowed. SDKs SHOULD ignore these calls gracefully, if possible.
```

2024-12-03 16:43 UTC, reyang commented on specification/metrics/sdk.md
> +In particular, if any `MeasurementProcessor` has any associated exporter, it SHOULD try to call the exporter's `Export` with all `Measurements` for which this was not already done and then invoke `Fo
This is going to be tricky, what about MetricReader and the pull-based exporter? (e.g. Prometheus Exporter)

2024-12-03 16:46 UTC, reyang commented on specification/metrics/sdk.md
> +
Due to the nature of preaggregation, metrics work differently than logs/traces. MetricReader is the one which has Collect/Shutdown and ForceFlush (only push exporters have ForceFlush).

2024-12-03 17:16 UTC, pellared commented on specification/metrics/sdk.md
> +
Related question (thus decided to put it here). Shouldn't the processor also be used when evaluating `Enabled`? See: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/api.md#enable

2024-12-04 10:24 UTC, Blinkuu commented on specification/metrics/sdk.md
> +In particular, if any `MeasurementProcessor` has any associated exporter, it SHOULD try to call the exporter's `Export` with all `Measurements` for which this was not already done and then invoke `Fo
Agreed, hence my comment. I referenced the `Exporter` here, but in the context of the Metrics SDK, it only makes sense to connect `MeasurementProcessor` and `MetricReader`.

To make it work, the `MeasurementProcessor` pipeline needs to exist between calls that record a new measurement, aka. `Add()` and `Record()` APIs defined on the `Instrument`, but before the actual aggregation happens, as at that point, we lose reference to `Attributes`.

So something along the lines of:

`Instrument ---Record()/Add()---> MeasurementProcessor(s) ---> Views -> Aggregations -> MetricReader`

However, I'm still trying to figure out if Views and Aggregations could somehow become built-in processors and whether it would even make sense.

2024-12-04 23:01 UTC, jmacd commented on specification/metrics/sdk.md
> +#### ForceFlush
I wonder if ForceFlush is required or even meaningful. I looked over our API and SDK specification, and I see no text explaining how a SDK should respond if there are metric events concurrent with flush and shutdown operations. Since I view MeasurementProcessor as a synchronous processor, all the same ambiguity applies. If a user is calling metric events while  flushing or shutting down, the measurement processor may or may not have completed.

Since the processor is synchronous, it should have no buffered state to flush, it should just be synchronous.

2024-12-04 23:04 UTC, reyang commented on specification/metrics/sdk.md
> +#### ForceFlush
+1, related to https://github.com/open-telemetry/opentelemetry-specification/pull/4318#discussion_r1868070642

2024-12-04 23:44 UTC, jack-berg commented on specification/metrics/sdk.md
> +
> the measurement processor does not change the instrument definition, and the measurement does not include a unit. Are there really use-cases for modifying the value?

Providing this feature without the ability to do unit conversion or drop measurements would be a miss. Can solve the lack of knowledge about unit by providing the processor access to instrument metadata. I think it could make sense to allow measurements processors to be configurable at the view level, in which case we might also consider allowing views to modify the unit of the resulting stream. Users could then compose a view which: 1. Adds a processor for unit conversion. 2. Adjusts the resulting stream's unit.

2024-12-06 11:27 UTC, Blinkuu commented on specification/metrics/sdk.md
> +#### ForceFlush
Agree on the simplification, removed these methods from the spec [(60adbd3)](https://github.com/open-telemetry/opentelemetry-specification/pull/4318/commits/60adbd3265005cd8cbf4e897075182245d1097f6).

2024-12-06 12:46 UTC, Blinkuu commented on specification/metrics/sdk.md
> +
Outdated - [60adbd3](https://github.com/open-telemetry/opentelemetry-specification/pull/4318/commits/60adbd3265005cd8cbf4e897075182245d1097f6).

2024-12-19 12:57 UTC, Blinkuu commented
> This PR was marked stale due to lack of activity. It will be closed in 7 days.

Still working on this; will try to provide another iteration early next year.

2025-01-02 12:08 UTC, Blinkuu commented
I have updated the PR. The current proposal should facilitate all use cases we talked about.

2025-01-06 18:29 UTC, reyang commented on specification/metrics/sdk.md
> +A `MeasurementProcessor` MUST invoke `OnMeasure` on the next registered processor.
How would a MeasurementProcessor do this? Is there a mechanism for the processor to get the "next registered processor"?

2025-01-06 18:30 UTC, reyang commented on specification/metrics/sdk.md
> +This is an implementation of `MeasurementProcessor` which calculates an in-memory state from incoming `Measurements`.
Sounds like the intention is to have a "DefaultProcessor" rather than emphasizing "Simple"?

2025-01-07 17:13 UTC, reyang commented on specification/metrics/sdk.md
> +* `next` - the `OnMeasure` function from the next processor in the chain
Is `next` the "next processor" or "the OnMeasure function of the next processor"?

2025-01-07 17:14 UTC, reyang commented on specification/metrics/sdk.md
> +* `context` - the resolved `Context` (the explicitly passed `Context` or the current `Context`)
Do we want `context` to be the 1st parameter? I think we want it to be the last one.

2025-01-07 17:16 UTC, reyang commented on specification/metrics/sdk.md
> +A `MeasurementProcessor` SHOULD invoke `OnMeasure` on the next registered processor. A `MeasurementProcessor` MAY decide to drop the `Measurement` by not invoking the next processor.
How would a MeasurementProcessor do that? For example, if it needs to invoke OnMeasure (which requires "next"), how would it figure out all the arguments?

2025-01-14 19:49 UTC, cijothomas commented on specification/metrics/sdk.md
> +`MeasurementProcessors` can be registered directly on SDK `MeterProvider` and they are invoked in the same order as they were registered.
> they are invoked in the same order as they were registered.

Unclear how is this part works with the later wording "_The SDK MUST inject the `OnMeasure` function from the next processor in the chain into the current processor_"

Who is invoking the MeasurementProcessors in the order? Is that MeterProvider/SDK ? Or is it the responsibility of each `MeasurementProcessor` to invoke the next one in the chain?

2025-01-14 19:52 UTC, cijothomas commented on specification/metrics/sdk.md
> +This is an implementation of `MeasurementProcessor` which does nothing. It can be used to entirely disable processing of `Measurements` or to safely terminate a chain of processors.
why is this required? View already allow users to disable any individual instrument, so is there a need for this NoopProcessor?

2025-01-15 08:20 UTC, dmathieu commented on specification/metrics/sdk.md
> +Each processor registered on the `MeterProvider` is part of a pipeline. The SDK MUST inject the `OnMeasure` function from the next processor in the chain into the current processor. It is RECOMMENDED
> It is RECOMMENDED that the SDK adds a `NoopProcessor` at the end of a pipeline.

What is the purpose of that? How would that be different from the SDK knowing a processor is the last one and stopping its processing? (this phrase feels like an implementation detail).

2025-01-15 08:20 UTC, dmathieu commented on specification/metrics/sdk.md
> +`MeasurementProcessor` is an interface which allows hooks when a `Measurement` is recorded by an `Instrument`.
In the context of tracing, a [processor](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk.md#span-processor) is somewhat of a different thing (it's not a filterer of data, it sits on top of exporters).

Should we name this differently than `Processor` to differenciate the two?
Or should we make both behaviors similar?

2025-01-22 10:41 UTC, Blinkuu commented on specification/metrics/sdk.md
> +This is an implementation of `MeasurementProcessor` which does nothing. It can be used to entirely disable processing of `Measurements` or to safely terminate a chain of processors.
Agreed that we can leave this out of specification. I've removed the recommendation to implement `NoopProcessor`.

2025-01-22 10:51 UTC, Blinkuu commented on specification/metrics/sdk.md
> +`MeasurementProcessors` can be registered directly on SDK `MeterProvider` and they are invoked in the same order as they were registered.
> Unclear how is this part works with the later wording "The SDK MUST inject the OnMeasure function from the next processor in the chain into the current processor"
>
> Who is invoking the MeasurementProcessors in the order? Is that MeterProvider/SDK ? Or is it the responsibility of each MeasurementProcessor to invoke the next one in the chain?

I have changed the wording around the `next` parameter, as the previous spec was confusing. The `next` parameter is a callback that MUST NOT require a reference to the next processor in the chain. On the implementation level, it will most likely end up as a closure. I see it as the SDK's responsibility to ensure processors are executed in the order they were configured on the `MeterProvider`.

That being said, every processor is able to decide whether it wants to invoke a chain of processors that follow it (by calling `next(context, measurement)`). Each processor can decide to call `next` either `0` (drop measurement), `1` (default flow), or `N` (custom use cases) times.

2025-01-22 11:00 UTC, Blinkuu commented on specification/metrics/sdk.md
> +`MeasurementProcessor` is an interface which allows hooks when a `Measurement` is recorded by an `Instrument`.
> In the context of tracing, a [processor](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk.md#span-processor) is somewhat of a different thing (it's not a filterer of data, it sits on top of exporters).

The `MeasurementProcessor` is more than a filter of data. It can modify the measurement, decide to drop it, or even emit it multiple times.

> Should we name this differently than Processor to differentiate the two?
Or should we make both behaviors similar?

To me, they are semantically similar. The difference is in the architecture of the Metrics SDK, which makes it hard to fit and connect the new processor pipeline directly with exporters. We could revisit this in the future and try to align the behavior between Logs, Traces, and Metrics SDKs. To keep an open door for such ideas, I'm purposefully specifying that:

`Built-in measurement processors are responsible for Measurement Processing.`

Where `Measurement Processing` is currently _vaguely_ defined in this spec by using the word `SHOULD`.

2025-01-22 11:04 UTC, Blinkuu commented on specification/metrics/sdk.md
> +* `next` - the `OnMeasure` function from the next processor in the chain
See https://github.com/open-telemetry/opentelemetry-specification/pull/4318#discussion_r1925111998

2025-01-22 17:56 UTC, jmacd commented on specification/metrics/sdk.md
> +`MeasurementProcessor` is an interface which allows hooks when a `Measurement` is recorded by an `Instrument`.
I support @Blinkuu's reasoning above. In my thinking, we can use "processor" across OpenTelemetry when a component in a program receives and outputs the same type of data. Trace SDK processors input/output span data. Collector processors input/output pipeline data. Things that are not processors (e.g., Metric reader, Trace sampler, Exporters, Receivers) generally have different types of input and output.

Here, MeasurementProcessor is appropriate because the input and the output types are the same.

2025-01-22 17:56 UTC, jmacd commented on specification/metrics/sdk.md
> +
@Blinkuu About view-attached processors: I am generally wary of making the metrics SDK more complex, and the idea of making measurement processors view-specific has me vaguely worried. One fear is that this will limit the potential for MeasurementProcessors to be optimized.

If there are multiple readers and multiple measurement processors, do we evaluate the chain of processors per reader or once? I would prefer once.

---

I fear we're letting implementation details into the specification, if we dictate the use of a "next" processor here. I don't think a next processor is required. A better API for the processor IMO would be to _return_ a measurement, so a signature like

```
type Processor interface {
  Process(context.Context, Measurement) (_ Measurement, valid bool)
}
```

In other words, the return value is an optional Measurement. I suggest the specification use pseudo-code such as the following, to answer the question raised in https://github.com/open-telemetry/opentelemetry-specification/pull/4318/files#r1915514480 about the order of operations, and this makes the drop-behavior clear:

```
func (sdki *sdkInstrument) onEvent(ctx context.Context, m Measurement) {
  for _, processor in sdki.processors() {
    if mr, valid := processor.Process(ctx, m); valid {
      m = mr
    } else {
      // measurement was dropped
      return
    }
  }
  // instrument-specific logic for final processed measurement `m`
  // ...
}
```

If there's an argument in favor of view-specific measurement processors, I would suggest surveying the implementors of the various metrics SDKs view mechanisms for their opinion. Otherwise, I think it's much simpler to explain to users what's happening with measurement processors: they literally change the events that enter the SDK and are seen by all metric readers alike.

---

@Blinkuu regarding an array of measurements. This is another question that could impact performance. Unless we need it, I don't think one measurement should be allowed to become >1 measurement, in other words. In the example I gave of translating an UpDownCounter into two Counters, one input event becomes one output event.

2025-01-23 03:32 UTC, reyang commented on specification/metrics/sdk.md
> +`MeasurementProcessor` is an interface which allows hooks when a `Measurement` is recorded by an `Instrument`.
> Here, MeasurementProcessor is appropriate because the input and the output types are the same.

+1

2025-01-23 03:40 UTC, reyang approved these changes
LGTM assuming we'll add a changelog entry here @Blinkuu.

2025-01-23 03:50 UTC, reyang commented on specification/metrics/sdk.md
> +* `next` - a callback to invoke `OnMeasure` on the next processor in the chain. It MUST be callable without a reference to the next processor.
I feel this might be too restrictive; we might want to give more flexibility here so different programming languages can find their own idiomatic way or performant way.

How about this?

```suggestion
* `next` - this allows the MeasurementProcessor to pass the measurements to the next MeasurementProcessor in the chain. It can be a reference to the next MeasurementProcessor, a bound callback to invoke `OnMeasure` on the next processor in the chain without an explicit reference to the next processor, or something else. [OpenTelemetry SDK](../overview.md#sdk) authors MAY decide the language idiomatic approach.
```

2025-01-23 16:40 UTC, cijothomas commented on specification/metrics/sdk.md
> +This is an implementation of `MeasurementProcessor` which calculates an in-memory state from incoming `Measurements`.
should the SDK ensure that this is the last processor in the chain?

2025-01-29 17:43 UTC, Blinkuu commented on specification/metrics/sdk.md
> +This is an implementation of `MeasurementProcessor` which calculates an in-memory state from incoming `Measurements`.
I didn't specify this to keep it in line with other Logs and Traces SDKs. Do we have good argument to make SDK ensure this processor is included in the pipeline?

2025-01-29 18:06 UTC, cijothomas commented on specification/metrics/sdk.md
> +This is an implementation of `MeasurementProcessor` which calculates an in-memory state from incoming `Measurements`.
if this is not included in the pipeline (and ensure it is the last one), how does MeasurementProcessors work ?
For example: User adds a measurement processor. In the OnMeasure(), it will receive a handle to invoke the next. if the user calls next.OnMeasure(), aggregation/default is expected to occur. But without having the default processor already there, this will not work right? 
Also, the DefaultProcessor should be the last, otherwise, if user's intention was to "drop" the measurement, it will be pointless if DefaultProcessor is not the last one.

2025-01-29 18:18 UTC, cijothomas commented on specification/metrics/sdk.md
> +This is an implementation of `MeasurementProcessor` which calculates an in-memory state from incoming `Measurements`.
For Logs,Traces, the processor was not responsible for invoking the next processor. But the MeasurementProcessor proposed here is different in the sense it is responsible for calling the next (or not calling) processor. This is why I asked who is responsible for ensuring that the last MeasurementProcessor is the DefaultProcessor.

2025-01-29 23:26 UTC, jack-berg reviewed
Couple of notes I think shouldn't be controversial, but pretty close. This is definitely something I'll be prototyping in opentelemetry-java.

2025-01-29 23:26 UTC, jack-berg commented on specification/metrics/sdk.md
> +* `measurement` - a [Measurement](./api.md#measurement) that was recorded
I'm planning on exposing all the components of a measurement (i.e. value, attributes, instrument descriptor) as individual parameters, since in java, bundling them up in a measurement carrier would require allocating measurement. I don't think anything needs to be done in this PR. Just mentioning. 

I will note that the API definition of measurement only includes value and attributes, so as it stands, there's not way for a processor to perform logic based on the instrument. I think the conclusion of this [conversation](https://github.com/open-telemetry/opentelemetry-specification/pull/4318/files#r1925726339) was that we wanted to include a parameter which encapsulates instrument metadata (name, description, unit, type).

2025-01-29 23:26 UTC, jack-berg commented on specification/metrics/sdk.md
> +Each processor registered on the `MeterProvider` is part of a pipeline.
Should note that the pipeline always concludes with built in DefaultProcessor.

2025-02-13 14:39 UTC, Blinkuu commented on specification/metrics/sdk.md
> +Each processor registered on the `MeterProvider` is part of a pipeline.
I updated this in [e6eec36](https://github.com/open-telemetry/opentelemetry-specification/pull/4318/commits/e6eec36d0207562123b1c529b33bd7c974474fec).

CC @jack-berg @cijothomas 

The alternative was to have SDK implement and ensure that a `NoopProcessor` (removed [here](https://github.com/open-telemetry/opentelemetry-specification/pull/4318/commits/f57fe00625586e9438b972943a2a407fc01bcd13)) is always the last in the chain. The `NoopProcessor`, by definition, does not call `next()`. This would align with other SDKs where users have to explicitly add a processor that connects the pipeline to the exporter - otherwise, they wouldn't see any data.

My only argument against making the `SDK` ensure that the pipeline ends with the `DefaultProcessor` is that removing this requirement will be difficult going forward.

2025-02-13 14:39 UTC, Blinkuu commented on specification/metrics/sdk.md
> +This is an implementation of `MeasurementProcessor` which calculates an in-memory state from incoming `Measurements`.
Moving the conversation to https://github.com/open-telemetry/opentelemetry-specification/pull/4318#discussion_r1934793288.

2025-02-13 16:50 UTC, pellared commented on specification/metrics/sdk.md
> +**Parameters:**
Shouldn't  the `MeasurementProcessor` have also access to instrumentation scope (connected with the instrument) and resource (used by the provider)? The LogRecord and Span processors have access to this data.

2025-02-14 13:58 UTC, pellared commented on specification/metrics/sdk.md
> +**Parameters:**
> The primary reason is we don't want to impose implementation details, allowing for optimal/idiomatic approaches.

The languages do not need to copy/implement the abstractions one to one. 

> The high-level idea is that the Measurement type should be defined as a 3-tuple (Value, Attributes, Instrument).

I totally agree with it and I feel that it must be defined. Otherwise languages may not support all of the data which is relevant for processing.

2025-02-14 14:22 UTC, pellared commented on specification/metrics/sdk.md
> +SDK MUST ensure that the pipeline concludes with the built-in [DefaultProcessor](#defaultprocessor).
This conflicts with

> A `MeasurementProcessor` SHOULD invoke `next`. A `MeasurementProcessor` MAY decide to drop the `Measurement` by not invoking the next processor.

I think we should say something like the SDK pass DefaultProcessor to the chain. 

I am not sure if with the current design the SDK would  know how/when to pass the DefaultProcessor to the processing chain.

I have a feeling that we would need something like a http.Handler middleware pattern popular in Go https://pkg.go.dev/github.com/gorilla/mux#MiddlewareFunc. The DefaultProcessor does not need to be exposed by the SDK. Hard to validate without a prototype 😉

2025-02-19 10:31 UTC, pellared commented on specification/metrics/sdk.md
> +SDK MUST ensure that the pipeline concludes with the built-in [DefaultProcessor](#defaultprocessor).
Discussed offline. The design of Go HTTP middlewares is different as it is primary goal to compose nicely with `http.Handler` (which is like a sink interface which we do not provide). The  design sketched out by @Blinkuu https://go.dev/play/p/wPZRm5xk3nO looks nice.

2025-02-19 15:49 UTC, jack-berg commented
> I could gladly use some help.

I'm pretty excited about this idea and will try to find some time to build a prototype implementation in opentelemetry-java. Hopefully won't be too difficult.

2025-02-19 16:22 UTC, pellared commented
> I could gladly use some help

When I finish some things related to logs I can try prototyping it in Go.

2025-02-19 17:35 UTC, aabmass reviewed
This is super cool to see. It would be relatively simple to implement in Python since the internal impl already behaves like this, e.g. [`Counter.add()`](https://github.com/open-telemetry/opentelemetry-python/blob/947aa74bb6d70cb455cd4cfa81835a4db61cae75/opentelemetry-sdk/src/opentelemetry/sdk/metrics/_internal/instrument.py#L171-L179)

2025-02-19 17:35 UTC, aabmass commented on specification/metrics/sdk.md
> +* `next` - this allows the `MeasurementProcessor` to pass the measurements to the next `MeasurementProcessor` in the chain. It can be a reference to the next `MeasurementProcessor`, a bound callback
Not sure how liberally we can interpret the "language idiomatic approach". For example, would it be reasonable to allow `OnMeasure()` return a new Measurement and have the SDK chain them together instead of recursing?

```python
for mp in mps:
  measurement = mp.on_measure(measurement)
  if measurement == "DROP":
    break
```

2025-02-19 17:35 UTC, aabmass commented on specification/metrics/sdk.md
> +A `MeasuremenetProcessor` MAY freely modify `measurement` for the duration of the `OnMeasure` call.
```suggestion
A `MeasurementProcessor` MAY freely modify `measurement` for the duration of the `OnMeasure` call.
```

2025-02-19 17:35 UTC, aabmass commented on specification/metrics/sdk.md
> +Each processor registered on the `MeterProvider` is part of a pipeline.
Could this be implicit and not something the user has to configure? I'm wondering if we need to expose the DefaultProcessor at all.

2025-02-19 17:35 UTC, aabmass commented on specification/metrics/sdk.md
> +A `MeasurementProcessor` SHOULD invoke `next`. A `MeasurementProcessor` MAY decide to drop the `Measurement` by not invoking the next processor.
I imagine some possible use cases where users would expect the whole pipeline to run regardless. For example, a self observability processor that counts the number of dropped measurements.

2025-02-19 17:35 UTC, aabmass commented on specification/metrics/sdk.md
> +* `next` - this allows the `MeasurementProcessor` to pass the measurements to the next `MeasurementProcessor` in the chain. It can be a reference to the next `MeasurementProcessor`, a bound callback
May a processor create new measurements by invoking `next()` multiple times? Dumb example

```py
def on_measure(measurement, next)
  measurement_squared = measurement.copy()
  measurement_squared.attributes["is_squared"] = True
  measurement_squared.value = measurement2.value**2
  
  next(measurement)
  next(measurement_squared)
```

2025-02-20 11:29 UTC, Blinkuu commented on specification/metrics/sdk.md
> +* `next` - this allows the `MeasurementProcessor` to pass the measurements to the next `MeasurementProcessor` in the chain. It can be a reference to the next `MeasurementProcessor`, a bound callback
The current design with `next()` allows duplicating measurements into downstream processors. For example, you can take one measurement and transform it into two. We discussed an API like this where the `OnMeasure()` function would return a list of measurements. The conclusion was that such an API would be slightly confusing.

2025-02-20 11:34 UTC, Blinkuu commented on specification/metrics/sdk.md
> +* `next` - this allows the `MeasurementProcessor` to pass the measurements to the next `MeasurementProcessor` in the chain. It can be a reference to the next `MeasurementProcessor`, a bound callback
Yes, this is intentional in design to cover some custom use cases, like mapping a measurement into two measurements of different instrument types.

2025-02-20 11:35 UTC, Blinkuu commented on specification/metrics/sdk.md
> +A `MeasurementProcessor` SHOULD invoke `next`. A `MeasurementProcessor` MAY decide to drop the `Measurement` by not invoking the next processor.
> I imagine some possible use cases where users would expect the whole pipeline to run regardless.
I'm not following. Run regardless of what?

2025-02-20 11:40 UTC, Blinkuu commented on specification/metrics/sdk.md
> +* `next` - this allows the `MeasurementProcessor` to pass the measurements to the next `MeasurementProcessor` in the chain. It can be a reference to the next `MeasurementProcessor`, a bound callback
Yes, this is currently possible. I see some conflicting views regarding this. The use cases I wanted to cover do not require it, but it's been raised in this PR before. I'm happy to revisit this.

2025-02-20 11:43 UTC, Blinkuu commented on specification/metrics/sdk.md
> +
I'm happy to revisit the API. I think the one you're proposing aligns more with my original idea but doesn't allow duplicate measurements.

My personal use case does not require duplicating measurements. Furthermore, I don't work with metrics so much to have a strong opinion on this subject.

> In the example I gave of translating an UpDownCounter into two Counters, one input event becomes one output event.

Could you expand on this? How would you implement the split of counters in a `MeasurementProcessor` that implements your API:

```go
type Processor interface {
  Process(context.Context, Measurement) (_ Measurement, valid bool)
}
```

2025-02-20 11:47 UTC, Blinkuu commented on specification/metrics/sdk.md
> +Each processor registered on the `MeterProvider` is part of a pipeline.
Yes, the current spec says:

```
SDK MUST ensure that the pipeline concludes with the built-in [DefaultProcessor](#defaultprocessor).
```

It says nothing about making `DefaultProcessor` public - it very well can be hidden from the user. If SDK adds it automatically, I don't see a reason for exposing it and breaking the encapsulation.

2025-02-20 11:48 UTC, Blinkuu commented on specification/metrics/sdk.md
> +**Parameters:**
This is the reason it's not explicit: https://github.com/open-telemetry/opentelemetry-specification/pull/4318#discussion_r1934789623

2025-02-20 12:10 UTC, pellared commented on specification/metrics/sdk.md
> +* `next` - this allows the `MeasurementProcessor` to pass the measurements to the next `MeasurementProcessor` in the chain. It can be a reference to the next `MeasurementProcessor`, a bound callback
I think it makes sense, but similarly to e.g. logs we should document what a measurement processor can mutate when dealing with measurements. For instance, I think that instrumentation scope and resource should come as arguments to `OnMeasure` but `next` should not accept neither instrumentation scope and resource. This way the processor could not be able to change the instrumentation scope nor resource (similarly to LogRecordProcessor and SpanProcessor)

2025-02-20 12:14 UTC, pellared commented on specification/metrics/sdk.md
> +* `next` - this allows the `MeasurementProcessor` to pass the measurements to the next `MeasurementProcessor` in the chain. It can be a reference to the next `MeasurementProcessor`, a bound callback
> I see some people arguing we shouldn't allow duplication of measurements

Can you link to the comments? Are there any reasons why it should be disallowed? If there is no good reason I think that the design should be open to different advanced use cases (e.g. like this for logs: https://github.com/open-telemetry/opentelemetry-specification/pull/4407).

2025-02-20 12:18 UTC, pellared commented on specification/metrics/sdk.md
> +**Parameters:**
I think we should explicitly call out them as separate parameters in the specification. Then it is the language SIG decision if they want to combine them into individual types or keep them separated. I think this would be fine for both @jack-berg (https://github.com/open-telemetry/opentelemetry-specification/pull/4318#discussion_r1934789623) and me (https://github.com/open-telemetry/opentelemetry-specification/pull/4318#discussion_r1963454443).

@jack-berg Does it sound reasonable?

@Blinkuu Please do not make any changes until at least @jack-berg agrees :wink:

2025-02-20 16:43 UTC, aabmass commented on specification/metrics/sdk.md
> +Each processor registered on the `MeterProvider` is part of a pipeline.
Since it is called out as a top-level thing in this PR, I assumed it is public.

2025-02-28 05:40 UTC, aabmass commented on specification/metrics/sdk.md
> +A `MeasurementProcessor` SHOULD invoke `next`. A `MeasurementProcessor` MAY decide to drop the `Measurement` by not invoking the next processor.
Run regardless of if the point is dropped

2025-03-27 10:51 UTC, Blinkuu commented on specification/metrics/sdk.md
> +* `next` - this allows the `MeasurementProcessor` to pass the measurements to the next `MeasurementProcessor` in the chain. It can be a reference to the next `MeasurementProcessor`, a bound callback
@pellared Please see https://github.com/open-telemetry/opentelemetry-specification/pull/4318/files#r1925726339

2025-05-14 14:34 UTC, Blinkuu commented
I will prepare a prototype for the Python SDK in the coming weeks.

2025-06-16 13:41 UTC, pellared commented
I spend a few hours trying to prototype in OTel Go. 
Unfortunately, decided to abandon the effort as it seems to require substantial code changes.

2025-06-17 12:25 UTC, Blinkuu commented
I've implemented a simple PoC in Python: https://github.com/open-telemetry/opentelemetry-python/pull/4642

CC @reyang @pellared @jmacd @jack-berg

2025-06-17 16:41 UTC, cijothomas commented
A draft prototype in OTel Rust (not actively being worked on, but still a reference.)
https://github.com/open-telemetry/opentelemetry-rust/pull/2797/files

2025-07-01 15:40 UTC, jmacd commented
@axw has written drafts for the Collector which would add a similar feature directly to the Collector instead of via SDK integration. I think that is a loss for us, and would like to encourage us to move forward here.  See:

https://github.com/open-telemetry/opentelemetry-collector/pull/13295
https://github.com/open-telemetry/opentelemetry-collector/pull/13307

2025-07-01 15:49 UTC, jmacd commented on specification/metrics/sdk.md
> +
I'll retract my comment above. To achieve split counters, IMO a natural way to proceed would be to let each processor know the next processor--to split a metric you will create multiple Measurement types and call the next processor multiple times.

2025-07-08 13:56 UTC, tsloughter commented on specification/metrics/sdk.md
> +
What is the use case for turning a measurement into multiple measurements?

2025-07-08 16:06 UTC, jack-berg commented on specification/metrics/sdk.md
> +**Parameters:**
> @jack-berg Does it sound reasonable?

Sorry I obviously haven't looked at this in a while. I'm not opinionated on how we accomplish it, but I agree with @pellared that we'll want to make scope and resource available.

2025-07-08 16:08 UTC, jack-berg commented on specification/metrics/sdk.md
> +**Parameters:**
Maybe worth saying that implementations should ensure that add additional resource, scope, and instrument metadata should be accessible to `onMeasure`

2025-07-08 16:10 UTC, jack-berg approved these changes
Approving because I think based on conversation, there is consensus about a couple of the key open convos ([scope and resource](https://github.com/open-telemetry/opentelemetry-specification/pull/4318/files#r1934789623) and [instrument descriptor](https://github.com/open-telemetry/opentelemetry-specification/pull/4318/files#r1934789623) access)., but I think the text would benefit from some additional notes to make expectations clear to SDK maintainers.

2025-07-08 16:29 UTC, jmacd commented on specification/metrics/sdk.md
> +Each processor registered on the `MeterProvider` is part of a pipeline.
I consider this topic resolved (feel free to correct me).

2025-07-09 08:21 UTC, Blinkuu commented on specification/metrics/sdk.md
> +**Parameters:**
@jack-berg Do you expect any changes, or should we defer it and/or update the `Measurement` definition to include instrument metadata?

2025-07-10 11:40 UTC, pellared commented on specification/metrics/sdk.md
> +This is an implementation of `MeasurementProcessor` which calculates an in-memory state from incoming `Measurements`.
Related to https://github.com/open-telemetry/opentelemetry-specification/pull/4318/files#r1963423516

Can we add something like

```md
The `DefaultProcessor` implementation MUST be private.
```

or if "private" term is unclear

```md
The `DefaultProcessor` implementation MUST be private;
meaning it MUST NOT be possible for the user to create an instance of `DefaultProcessor`.
```

As rule of thumb if we define a type/abstraction in the specification we implicitly assume that it is publicly available. Without such statement this would be confusing for most languages implementation contributors.

2025-07-10 14:14 UTC, Blinkuu commented on specification/metrics/sdk.md
> +This is an implementation of `MeasurementProcessor` which calculates an in-memory state from incoming `Measurements`.
Specified in [756de83](https://github.com/open-telemetry/opentelemetry-specification/pull/4318/commits/756de836c6128ce340263184ea215d0b31ce359d). I used the `SHOULD` / `SHOULD NOT`, as in some languages it's impossible to make types private by design.

2025-07-10 14:29 UTC, Blinkuu commented on specification/metrics/sdk.md
> +**Parameters:**
@jack-berg After giving this some thought, I think we should not include this prematurely and only introduce it as we realize it's really necessary and/or we decide to do so while going up the maturity model.

The argument I'm making is that we're merging this in `Development` status anyway and I'd like to avoid feature creep.

To not leave this conversation at void, I have two proposals for how this could be addressed in the future:

1. Define the `Measurement` concept more concretely and specify that it should expose the implicit association with the `Resource`, `Scope` and perhaps other `Instrument` metadata.
2. Add guidelines only in this concrete example, such as:

```
A function receiving a `measurement` MUST also be able to
access the `Resource`, `Scope` and `Instrument` information (implicitly) associated with the `Measurement`.
```

2025-07-11 06:34 UTC, pellared commented
We discussed this proposal during the last OTel Go SIG meeting ([notes](https://github.com/open-telemetry/opentelemetry-go/issues/6648#issuecomment-3060747994)).

We have concerns about introducing the ability to drop or modify measurements:

- **Narrow use case:** We could not find concrete examples in either the issue or the PR description that demonstrate where such a feature is necessary. Meanwhile, implementing it would require significant refactoring, at least on the OTel Go side.
- **Risk to statistical correctness:** Modifying measurements poses risks from a statistical and mathematical perspective, making it easier to accidentally introduce [rounding/quantization] errors.
- **Alternative approach:** Instead of dropping measurements deemed unimportant, we suggest adding dedicated attributes (e.g., `healthcheck=true`) so they can be aggregated separately. This ensures potentially important measurements are not lost.

Given these concerns, we would like to push back on this part of the proposal and suggest limiting its scope to focus solely on modifying and dropping attributes. As we understand it, this would still address the primary motivation behind https://github.com/open-telemetry/opentelemetry-specification/issues/4298.

2025-07-14 21:27 UTC, jsuereth approved these changes

2025-07-15 15:28 UTC, tylerbenson commented
@pellared While I agree with the general reasoning about not allowing value to be changed without valid uses cases, I think the proposed API design is fairly clean and restricting to just modifying attributes would complicate things quite a bit.

2025-07-15 15:35 UTC, reyang commented
> Therefore, I suggest to remove the part related to modifying/dropping measurements from the scope of this PR. I think it is worth mentioning that the Rust prototype is following our proposal and it does NOT allow modifying nor dropping measurements:

I disagree.

I have couple scenarios that I need to drop/modify measurements.
One example - we have critical metrics (e.g. security, SLA) that we have carefully designed the attributes and values to control the cardinality centrally. There are cases where people made mistakes so we get measurements that didn't not follow the rule and we ended up with cardinality overflow. One approach is to wrap the API to check the value, this only works if all the instrumentation code is controlled by the same team. MeasurementProcessor would allow such outliers to be captured and reported (e.g. via audit logs + exception callback), and the policy owner can decide what to do (e.g. drop the measurement, aggregate the value using a special dimension, or something else).

2025-07-15 15:35 UTC, pellared commented
> just modifying attributes would complicate things quite a bit.

@tylerbenson, how would it complicate things?

2025-07-15 15:36 UTC, pellared commented
> There are cases where people made mistakes so we get measurements that didn't not follow the rule and we ended up with cardinality overflow.

Wouldn't modifying attributes for these measurements be also a viable solution?

> One approach is to wrap the API to check the value,

Wouldn't the ability to only read the measurement value be enough (without the ability to modify it)?

2025-07-15 15:40 UTC, reyang commented
> > One approach is to wrap the API to check the value,
> 
> Wouldn't the ability to only read the measurement value be enough (without the ability to modify it)?

No, as the policy owner, you want to have the ability to drop illegal value.

2025-07-15 16:25 UTC, pellared commented
> No, as the policy owner, you want to have the ability to drop illegal value.

What about the alternative approach of adding an attribute instead e.g. `illegal=true`?
From https://github.com/open-telemetry/opentelemetry-specification/pull/4318#issuecomment-3060811955
Why would it not be acceptable?

2025-07-15 16:32 UTC, reyang commented
> > No, as the policy owner, you want to have the ability to drop illegal value.
> 
> What about the alternative approach of adding an attribute instead e.g. `illegal=true` (from [#4318 (comment)](https://github.com/open-telemetry/opentelemetry-specification/pull/4318#issuecomment-3060811955))? Why would it not be acceptable?

Compliance/contractual requirement.

2025-07-15 22:31 UTC, MrAlias commented
> > Therefore, I suggest to remove the part related to modifying/dropping measurements from the scope of this PR. I think it is worth mentioning that the Rust prototype is following our proposal and it does NOT allow modifying nor dropping measurements:
> 
> I disagree.
> 
> I have couple scenarios that I need to drop/modify measurements. One example - we have critical metrics (e.g. security, SLA) that we have carefully designed the attributes and values to control the cardinality centrally. There are cases where people made mistakes so we get measurements that didn't not follow the rule and we ended up with cardinality overflow. One approach is to wrap the API to check the value, this only works if all the instrumentation code is controlled by the same team. MeasurementProcessor would allow such outliers to be captured and reported (e.g. via audit logs + exception callback), and the policy owner can decide what to do (e.g. drop the measurement, aggregate the value using a special dimension, or something else).

Please clarify how this is a measurement filter problem, not an attribute filter problem.

If you measure 0.826, does this get dropped?

2025-07-15 23:36 UTC, reyang commented
> Please clarify how this is a measurement filter problem, not an attribute filter problem.
> 
> If you measure 0.826, does this get dropped?

Yes, it gets dropped. The value is considered illegal due to compliance/contractual requirement and will be independently escalated via an auditing system.

2025-07-16 00:00 UTC, MrAlias commented
> > Please clarify how this is a measurement filter problem, not an attribute filter problem.
> > If you measure 0.826, does this get dropped?
> 
> Yes, it gets dropped. The value is considered illegal due to compliance/contractual requirement and will be independently escalated via an auditing system.

What criteria is used to evaluate this choice? Just the number?

How does this centralized cardinality control factor in?

2025-07-16 00:08 UTC, MrAlias commented
Why are we not trying to solve the use-cases with views?

2025-07-18 12:55 UTC, Blinkuu commented
Thanks, everyone, for chiming in and for the healthy debate. I will add my two cents here for why the MeasurementProcessor should be as flexible as we currently define it.

Let me capture a *few* real-world use cases that fit the functionality I described in the original PR comment.

> Adding attributes, e.g., injection of additional attributes to measurements based on `Context`

This is probably the easiest to justify. From a high level, this is the last missing piece to allow great flexibility in correlation between all three telemetry signals: Metrics, Logs, and Traces. 

Use cases here are infinite. In the past, @jsuereth shared a [critical user interaction](https://github.com/GoogleCloudPlatform/scala-o11y-cui-showcase) use case with me, which is very appealing. 

I am personally excited about being able to isolate data from tests, such as [k6](https://github.com/grafana/k6), where a load generator would embed a "test id" inside the baggage. If the entire system under test is instrumented with OpenTelemetry, this baggage would propagate across all the services that are part of the tested path, and we can dynamically inject it as an attribute. Today, we can only easily isolate Traces and Logs, which both support the processor pattern. Metrics are opaque, and without MeasurementProcessor, this tight correlation will not be possible.

I also know of people who would be interested in being able to inject, e.g., dynamically, a tenant_id -- for obvious reasons.

I also want to stress that none of these would be possible if the processor concept were only implemented in the collector. It must be available via the SDK.

> Modifying attributes and Dropping attributes

I grouped these two. The use cases here are also easy to spot. I'll just share a few from the top of my head that I had to deal with in the past. 

First, modify attributes. Imagine you already have a tenant_id dimension on your metric, but you may have a contractual argument to anonymise it. The Measurement Processor makes it very easy to do that. Another use case -- you may want to collapse attributes into just a tiny set, controlling your cardinality this way. I'll skip listing use cases for dropping attributes, as they are similar and pretty obvious. 

> Dropping individual measurements

I think @reyang nicely captures the need for this above. Let's say we have an instrument that reports several measurements for different tenants (tenant_id is a dimension). Now, a customer asks you not to track any metadata associated with their tenant. What do you do then? You want to drop measurements for that particular tenant, as dropping the metric after it's been sent over the wire violates a contract. Again, this cannot be facilitated with Views today, as they can only drop attributes.

> Modifying measurements

This one is interesting too. Modyfing measurements allows e.g., to clamp values. I think there's a lot of use cases around this too, where the underlying instrument reports real numbers, but perhaps you're only interested in `0` or `1`. Again, Measurement Processor allows to do this in the simplest possible way.

---------

The best thing about this solution is that we can facilitate all this and more with a beautifully simple and concise design.

2025-07-18 14:46 UTC, dashpole commented on specification/metrics/sdk.md
> +`MeasurementProcessors` can be registered directly on SDK `MeterProvider` and they are invoked in the same order as they were registered.
It seems like it would be good to specify how these are meant to be registered, similar to what we have for span processors.  Can they be provided when the MeterProvider is instantiated (similar to span processors)?  Does it need to be possible to dynamically register/unregister them (similar to callbacks)?

2025-07-18 14:49 UTC, dashpole commented on specification/metrics/sdk.md
> +The following diagram shows `MeasurementProcessor`'s relationship to other components in the SDK:
Please include Views in this diagram. Importantly, is View configuration applied before the Measurement processor, or after, or both? We clearly want it to be applied before the aggregation portion of views is applied, but it would be nice if it was applied after the View's attribute filter so processors don't need to consider attributes that aren't going to be kept.

2025-07-18 14:56 UTC, dashpole commented on specification/metrics/sdk.md
> +Each processor registered on the `MeterProvider` is part of a pipeline.
Did we consider making processors part of the View configuration? Many of the use-cases seem to apply to specific metrics (e.g. changing the unit of a metric), or aggregating specific attribute values together. It also fits nicely within the scope of what Views are meant to be able to do: Make pre-aggregation adjustments to metrics.

2025-07-18 15:07 UTC, cijothomas commented on specification/metrics/sdk.md
> +`MeasurementProcessors` can be registered directly on SDK `MeterProvider` and they are invoked in the same order as they were registered.
My suggestion is to use the same wording as we use for Provider configuration in general.
i.e It MUST be possible to add measurement_processor as part of MeterProvider creation.
Implementations MAY allow modifications *after* MeterProvider is created. If they do, then all existing meter/instruments should reflect the effect of this.

2025-07-18 16:53 UTC, reyang commented
> Why are we not trying to solve the use-cases with views?

The original ask is to understand the usage scenario. @MrAlias do you think we're still collecting scenarios, or we agree with scenarios and now we want to discuss about the right design?

I don't think View is the right place.

View is designed to handle very specific scenarios via user-provided configurations. MeasurementProcess gives the user ability to plug their own logic (e.g. code).

Think about this - if the policy requires you to drop measurements for tenants that match certain a given list of names/ids, do you think it makes sense to add such feature to View and make it such complicated? Do you think View will eventually have a callback mechanism?

2025-07-18 17:53 UTC, MrAlias commented
> The original ask is to understand the usage scenario. @MrAlias do you think we're still collecting scenarios, or we agree with scenarios and now we want to discuss about the right design?

No, I'm still not following your example: https://github.com/open-telemetry/opentelemetry-specification/pull/4318#issuecomment-3076190176

2025-07-18 17:54 UTC, MrAlias commented
> do you think it makes sense to add such feature to View

yes

2025-07-18 18:24 UTC, reyang commented
> > The original ask is to understand the usage scenario. @MrAlias do you think we're still collecting scenarios, or we agree with scenarios and now we want to discuss about the right design?
> 
> No, I'm still not following your example: [#4318 (comment)](https://github.com/open-telemetry/opentelemetry-specification/pull/4318#issuecomment-3076190176)

> > do you think it makes sense to add such feature to View
> 
> yes

Sorry, would you summarize your position and thinking?
I'm confused as it sounds like you don't understand the scenario, and yet you think it should be solved by View?

2025-07-18 21:28 UTC, MrAlias commented
> > > The original ask is to understand the usage scenario. @MrAlias do you think we're still collecting scenarios, or we agree with scenarios and now we want to discuss about the right design?
> > 
> > 
> > No, I'm still not following your example: [#4318 (comment)](https://github.com/open-telemetry/opentelemetry-specification/pull/4318#issuecomment-3076190176)
> 
> > > do you think it makes sense to add such feature to View
> > 
> > 
> > yes
> 
> Sorry, would you summarize your position and thinking? I'm confused as it sounds like you don't understand the scenario, and yet you think it should be solved by View?

I have no idea if you're situation needs a solution, or what that solution is. Please clarify the problem your trying to address so I can respond effectively.

2025-07-18 21:32 UTC, MrAlias commented
>  I'm confused as it sounds like you don't understand the scenario, and yet you think it should be solved by View?

None of the understandable use-cases provided so far have presented a problem that we couldn't solve by extending our existing View definition.

Adding a competing processing pipeline has yet to be justified.

2025-07-21 11:15 UTC, Blinkuu commented on specification/metrics/sdk.md
> +`MeasurementProcessors` can be registered directly on SDK `MeterProvider` and they are invoked in the same order as they were registered.
I used the exact same wording we use for [LogRecordProcessor](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/sdk.md#logrecordprocessor) and [SpanProcessor](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk.md#span-processor).

I think it should be consistent, it's the same concept.

2025-07-21 11:18 UTC, Blinkuu commented on specification/metrics/sdk.md
> +The following diagram shows `MeasurementProcessor`'s relationship to other components in the SDK:
Views are meant to be applied after Measurement Processors. They operate on a higher level of abstraction.

2025-07-21 11:20 UTC, Blinkuu commented on specification/metrics/sdk.md
> +Each processor registered on the `MeterProvider` is part of a pipeline.
Yes, it was considered. It looks similar, but in my opinion, Views are meant to work on a higher level of abstraction, not with individual measurements. The existing design is also deeply rooted in analysis of existing SDK implementations, where incorporating this concept into Views would be extremely difficult.

2025-07-21 16:13 UTC, dashpole commented on specification/metrics/sdk.md
> +Each processor registered on the `MeterProvider` is part of a pipeline.
Can you explain further?  Attribute filters from views are applied very early in the SDK's handling of a measurement.  They apply even [prior to cardinality limit enforcement](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#cardinality-limits). Implementing both of those features post-aggregation (i.e. not on measurements) would defeat one of their primary purpose, which is to limit memory consumption of the SDK, so I would be very surprised if they were not applied to individual measurements.

2025-07-21 16:14 UTC, dashpole commented on specification/metrics/sdk.md
> +The following diagram shows `MeasurementProcessor`'s relationship to other components in the SDK:
I realized cardinality limits should probably also be included, but we can wait until the [discussion below](https://github.com/open-telemetry/opentelemetry-specification/pull/4318#discussion_r2216274649) is resolved.

2025-07-21 17:10 UTC, cijothomas commented
> Narrow use case: We could not find concrete examples in either the issue or the PR description that demonstrate where such a feature is necessary. Meanwhile, implementing it would require significant refactoring, at least on the OTel Go side.

Concrete examples are covered in this [comment](https://github.com/open-telemetry/opentelemetry-specification/pull/4318#issuecomment-3089400831) now, perhaps make it very explicit in the PR description itself to avoid confusion about the use-cases?

Sharing two common requests I have been encountering:
1. Ability to add extra attributes to measurements. (eg: could be from Context/Baggage, like a "is_synthetic" setting in Baggage)
2. Ability to "collapse" attributes to reduce cardinality. (eg: /route/user/user1 -> /route/user/{userid})
Both the above, assuming we have no control on the instrumentation side.

2025-07-21 21:02 UTC, MrAlias requested changes
Adding an additional processing pipeline to the metric signal (in addition to views) will negatively impact the usability of the metric SDK APIs and impose global performance degradation across SDKs. It will add a competing stream processing configuration endpoint for users to understand and use in concert with all views and it will require all streams be passed through the new Metric processor (imposing non-zero overhead in the process) instead of just matching instruments (as would be the case with a view).

I do not think this proposal should be accepted. We should look into how we can make Views support use-cases we would like to support.

There are already two proof-of-concepts for how to support attribute mutation in a view that will address the original concern of this PR:

- [Java](https://github.com/open-telemetry/opentelemetry-java/blob/9a0bfb23115a5c4d22f4c36fe4d4df19342d37bb/sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/View.java#L35)
- [Go](https://github.com/MrAlias/opentelemetry-go/pull/1092)

I see moving forward in the direction proposed by this PR as a misstep and I do not think it should be taken at this point in time.

2025-07-22 08:54 UTC, Blinkuu commented on specification/metrics/sdk.md
> +Each processor registered on the `MeterProvider` is part of a pipeline.
I'm not an expert on the Metrics SDKs, but after looking into the code when preparing this PR I concluded that supporting all the use cases we envisioned would require major overhaul of how Views work.

Please see https://github.com/open-telemetry/opentelemetry-specification/issues/4298#issuecomment-2486438111

Perhaps I'm wrong, and there's a neat way to make Views fully programmable. 

Regarding performance - MeasurementProcessor, like LogRecordProcessor and SpanProcessor is an opt-in feature.  If it's not used, the cost is a single if-statement, exactly the same as with https://github.com/MrAlias/opentelemetry-go/pull/1092/files#diff-2c6f5806e27a5ab81eeba6f9d6fff1a80ac35188c8e22deea1c97a77fdb04634

2025-07-22 09:00 UTC, Blinkuu commented on specification/metrics/sdk.md
> +Each processor registered on the `MeterProvider` is part of a pipeline.
CC @MrAlias

2025-07-22 14:10 UTC, dashpole commented on specification/metrics/sdk.md
> +Each processor registered on the `MeterProvider` is part of a pipeline.
My suggestion would be to apply measurement processors immediately after the view's attribute filter, and prior to cardinality limit enforcement.  The benefit of this would be that the measurement processor could reduce cardinality, and prevent hitting the limit by merging attribute values together, which is one of the intended uses.

In terms of implementation, this means you would just keep the measurement processor very close to the attribute filter (e.g. pass them to the same functions).  The existing attribute filter could be thought of as a measurement processor that always comes first, and has more limited capabilities. In go, we would probably extend, or add something similar to [this function](https://github.com/open-telemetry/opentelemetry-go/blob/186def7c5634585af79120fbe7cd4e685e8d1f98/sdk/metric/internal/aggregate/aggregate.go#L62) to add the measurement processor in addition to the existing filter.

2025-07-22 14:14 UTC, dashpole commented on specification/metrics/sdk.md
> +`MeasurementProcessors` can be registered directly on SDK `MeterProvider` and they are invoked in the same order as they were registered.
We should specify how MeterProviders are configured in the MeterProvider spec, not in the MeasurementProcessors spec.  See this section of TracerProvider: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk.md#configuration that @cijothomas quoted above. Make sure anything related to MeasurementProcessor is marked as Development status.

2025-07-22 14:55 UTC, MrAlias commented on specification/metrics/sdk.md
> +Each processor registered on the `MeterProvider` is part of a pipeline.
> Regarding performance - MeasurementProcessor, like LogRecordProcessor and SpanProcessor is an opt-in feature. If it's not used, the cost is a single if-statement, exactly the same as with https://github.com/MrAlias/opentelemetry-go/pull/1092/files#diff-2c6f5806e27a5ab81eeba6f9d6fff1a80ac35188c8e22deea1c97a77fdb04634

The if statement you are referencing is in the build path. The hot-path performance has no additional branch points for the views implementation.

2025-08-06 03:46 UTC, closed without merging