Editorial: Add type column to all environment variables
open-telemetry/opentelemetry-specification pull request #4336
Opened 2024-12-11 23:21 UTC by jack-berg

Related to #4284.

A [comment](https://github.com/open-telemetry/opentelemetry-specification/pull/4331#discussion_r1878558291) adding a "type" column to each env var, but didn't feel appropriate to extend scope of #4331.

2024-12-11 23:27 UTC, reyang approved these changes
LGTM.

2024-12-13 02:32 UTC, trask reviewed
this is great, just typographical thoughts

2024-12-13 02:32 UTC, trask commented on specification/protocol/exporter.md
> +  - [Type](../configuration/sdk-environment-variables.md#configuration-types): `string`
the backticks make it look to me like `string` is a well-known enum value

```suggestion
  - Type: [String](../configuration/sdk-environment-variables.md#string)
```

2024-12-13 02:32 UTC, trask commented on specification/configuration/sdk-environment-variables.md
> +| OTEL_SDK_DISABLED        | Disable the SDK for all signals                                                                                                                             | false
(if you agree with above comment then I'd change everywhere, also in this case I'd suggest using reference links, e.g. `[Boolean][boolean]` with `[boolean]: ../configuration/sdk-environment-variables.md#boolean`)
```suggestion
| OTEL_SDK_DISABLED        | Disable the SDK for all signals                                                                                                                             | false                                                                                                                                                                                              | [Boolean](../configuration/sdk-environment-variables.md#boolean)                    | If "true", a no-op SDK implementation will be used for all telemetry signals. Any other value or absence of the variable will have no effect and the SDK will remain enabled. This setting has no effect on propagators configured through the OTEL_PROPAGATORS variable.                |
```

2024-12-13 02:32 UTC, trask commented on specification/configuration/sdk-environment-variables.md
> +| Name                     | Description                                                                                                                                                 | Default
(continuation of above, and just slight preference)
```suggestion
| Name                     | Description                                                                                                                                                 | Default                                                                                                                                                                                            | Type | Notes                                                                                                                                                                                                                                                                                    |
```

2024-12-13 02:32 UTC, trask commented on specification/configuration/sdk-environment-variables.md
> +* [duration](#duration)
```suggestion
* [Integer](#integer)
* [Float](#float)
* [Duration](#duration)
```

2024-12-13 04:25 UTC, carlosalberto commented on specification/configuration/sdk-environment-variables.md
> +* [duration](#duration)
Switch the Float/Integer positions, given their actual order in this document?

2024-12-13 04:28 UTC, carlosalberto commented on specification/configuration/sdk-environment-variables.md
> +| OTEL_TRACES_SAMPLER_ARG  | String value to be used as the sampler argument                                                                                                             |
Wouldn't using string here would simplify things? After all, the description says "String value to be used..." etc.

2024-12-13 16:04 UTC, jack-berg commented on specification/configuration/sdk-environment-variables.md
> +| OTEL_TRACES_SAMPLER_ARG  | String value to be used as the sampler argument                                                                                                             |
Maybe, but the type is contextual, since its `float` when sampler is `traceidratio`. 

If we keep the "`float` or `string`", I should definitely update the description to something omitting "string", like "Value to be used as the sampler argument".

2024-12-13 16:05 UTC, jack-berg commented on specification/configuration/sdk-environment-variables.md
> +| OTEL_SDK_DISABLED        | Disable the SDK for all signals                                                                                                                             | false
Sure works for me. More explicit for the user.

2024-12-13 21:57 UTC, trask approved these changes

2024-12-13 21:57 UTC, trask commented on specification/metrics/sdk_exporters/otlp.md
> +| `OTEL_EXPORTER_OTLP_METRICS_DEFAULT_HISTOGRAM_AGGREGATION` | Configure the exporter's `default_aggregation` option (see above) for Histogram instrument kind.   | `explicit_bucket_histogram` | `enum
```suggestion
| Name                                                       | Description                                                                                            | Default                     | Type |
|------------------------------------------------------------|--------------------------------------------------------------------------------------------------------|-----------------------------|------------------------------------------------------------------------------|
| `OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE`        | Configure the exporter's aggregation `temporality` option (see above) on the basis of instrument kind. | `cumulative`                | [Enum][]                                                                       |
| `OTEL_EXPORTER_OTLP_METRICS_DEFAULT_HISTOGRAM_AGGREGATION` | Configure the exporter's `default_aggregation` option (see above) for Histogram instrument kind.   | [Enum][]                                                                        |
```

2024-12-13 21:57 UTC, trask commented on specification/configuration/sdk-environment-variables.md
> +Normally, string values includes notes describing how they are interpreted by
```suggestion
Normally, string values include notes describing how they are interpreted by
```

2024-12-16 09:51 UTC, pellared requested changes

2024-12-16 09:51 UTC, pellared commented on specification/configuration/sdk-environment-variables.md
> +| OTEL_TRACES_SAMPLER_ARG  | Value to be used as the sampler argument                                                                                                                    |
```suggestion
| OTEL_TRACES_SAMPLER_ARG  | Value to be used as the sampler argument                                                                                                                    |                                                                                                                                                                                                    | [String][] | The specified value will only be used if OTEL_TRACES_SAMPLER is set. Each Sampler type defines its own expected input, if any. Invalid or unrecognized input MUST be logged and MUST be otherwise ignored, i.e. the implementation MUST behave as if OTEL_TRACES_SAMPLER_ARG is not set. |
```

I strongly suggest to not introduce a new `Float` type in the scope of this PR. This PR would not longer be just editorial.

The `Float` type does not say anything about the syntax/representation of the value which should be specified if we would introduce a new type.

2024-12-16 09:53 UTC, pellared commented on specification/configuration/sdk-environment-variables.md
> +| OTEL_TRACES_SAMPLER_ARG  | String value to be used as the sampler argument                                                                                                             |
I agree with @carlosalberto. Further would be better suited as a separate PR.

2024-12-16 13:54 UTC, jack-berg commented on specification/configuration/sdk-environment-variables.md
> +| OTEL_TRACES_SAMPLER_ARG  | Value to be used as the sampler argument                                                                                                                    |
> This PR would not longer be just editorial.

It is editorial because it doesn't change the semantics of of the property in any way. The PR is ascribes the most intuitive type to properties which have already existed. If this property isn't a float, what is it? `string` is not correct and would seem like we're going needlessly out of our way to avoid calling it `float`.

> The Float type does not say anything about the syntax/representation of the value which should be specified if we would introduce a new type.

I don't think so. I'm not defining a new type. I'm giving a name to a type that has already been in use for years with a self-explanatory definition. `OTEL_TRACES_SAMPLER_ARG` has included the following definition, which has been sufficient. Its obvious that implementations need to interpret this as a floating point, and they've been doing so successfully without any further clarifications about the syntax/representation.

> For traceidratio and parentbased_traceidratio samplers: Sampling probability, a number in the [0..1] range, e.g. "0.25". Default is 1.0 if unset.

2024-12-16 15:43 UTC, pellared commented on specification/configuration/sdk-environment-variables.md
> +| OTEL_TRACES_SAMPLER_ARG  | Value to be used as the sampler argument                                                                                                                    |
> a number in the [0..1] range, e.g. "0.25".

This already defines an implicit syntax.

The  `Float` type definition proposed in this PR does not define any syntax 

I would say that `parentbased_traceidratio` is a special-case type.

Should the float type parse e-notation? Notice that the `Boolean` type value syntax is well-defined.

2024-12-16 18:52 UTC, jack-berg commented on specification/configuration/sdk-environment-variables.md
> +| OTEL_TRACES_SAMPLER_ARG  | Value to be used as the sampler argument                                                                                                                    |
> This already defines an implicit syntax.

Yes and I'm just giving this a name. 

> Should the float type parse e-notation?

Should integer or duration? Note that these types also lack specification about the syntax / representation and have been just fine. Can always further clarify in the future, and this goes for `float` as well.

Better to call `parentbased_traceidratio` the type we obviously all know it to be and clarify syntax later if issues arise, than to not assign it a type for fear of lacking an exhaustive description.

2024-12-16 19:35 UTC, pellared commented on specification/configuration/sdk-environment-variables.md
> +| OTEL_TRACES_SAMPLER_ARG  | Value to be used as the sampler argument                                                                                                                    |
How will a changelog entry look like? I still think it is better to split this into two PRs.

2024-12-16 23:42 UTC, jack-berg commented on specification/configuration/sdk-environment-variables.md
> +| OTEL_TRACES_SAMPLER_ARG  | Value to be used as the sampler argument                                                                                                                    |
Pushed a commit to remove refs to float. I think this is a worse outcome for the specs readers, but don't have any more time to argue. I will not be opening a followup.

2024-12-16 23:42 UTC, jack-berg commented on specification/configuration/sdk-environment-variables.md
> +| OTEL_TRACES_SAMPLER_ARG  | String value to be used as the sampler argument                                                                                                             |
See latest commit.

2024-12-18 23:01 UTC, pellared approved these changes

2024-12-18 23:03 UTC, pellared commented
> Related to #4284.

#4283?

2024-12-20 00:35 UTC, carlosalberto approved these changes

2024-12-21 01:20 UTC, merged