Add error.hint semantic convention
open-telemetry/opentelemetry-specification pull request #822
Opened 2020-08-18 02:25 UTC by mwear

## Changes

This PR adds an `error.hint` semantic convention, and updates the span.RecordException API method to optionally set it. 

The purpose of this attribute is to convey an instrumentation author's best guess as to whether an exception represents an error condition. This will be a flag that tracing backends can use to identify candidate spans where an error may have been observed.

Tracing backends can use this information:

* for tail-based sampling decisions
* to compute an application's error rate
* as a cue to do more analysis on a span's attributes / events
* to highlight a span in a trace

It serves a similar purpose to the`error: true` tag from OpenTracing. It's called `error.hint` rather than `error` in order to impart that this is not a definitive decision and a tracing backend may override it.

If we remove the `Span.status` API as proposed in in #706 a similar semantic convention will be needed as Jaeger exporters from a number of projects use it as a proxy for the `error = true` OpenTracing semantic convention. 

See:
* https://github.com/open-telemetry/opentelemetry-python/blob/5aa1d811039de774f4a84db4c9c656afe11827dd/exporter/opentelemetry-exporter-jaeger/src/opentelemetry/exporter/jaeger/__init__.py#L216-L218
* https://github.com/open-telemetry/opentelemetry-go/blob/576a1315774d4670bc85e2a0efbc0fcb06350746/exporters/trace/jaeger/jaeger.go#L245-L249

Related issues #599 #706

2020-08-18 07:01 UTC, Oberon00 commented
How do you see the relation of this PR to #784's `exception.escaped`? Why do you specifically add `error.hint` to RecordException, while it seems to be a generally useful event attribute? I think we should find a more general solution to record non-exception-specific attributes with RecordException, see #814.

2020-08-18 07:53 UTC, iNikem commented
Btw, @Oberon00 are you aware that there is a [meeting of Errors WG every week](https://docs.google.com/document/d/1HgUI69rBridFzCXxXuTjQrkG6jb-YcFQnZjPcyBcK1U/edit#heading=h.2hz10p1trufx)? As it seems that you have great interest in this topic, care to join us there for real-time discussion?

2020-08-18 08:42 UTC, Oberon00 commented
I copied the meeting into my calendar.

2020-08-18 13:29 UTC, Oberon00 commented on specification/trace/semantic_conventions/exceptions.md
> +An `error.hint` attribute can be added to a span to indicate that an error
I think we agreed that exceptions and errors should be handled separately, e.g. see your comment at https://github.com/open-telemetry/opentelemetry-specification/issues/706#issuecomment-661307917. I see no reason why this error.hint attribute should only be used with exceptions. Please move it to a separate semantic convention.

2020-08-18 13:30 UTC, Oberon00 commented
Based on https://github.com/open-telemetry/opentelemetry-specification/issues/706#issuecomment-664457764, I'm marking this after-ga for now.

2020-08-18 15:26 UTC, mwear commented on specification/trace/semantic_conventions/exceptions.md
> +An `error.hint` attribute can be added to a span to indicate that an error
The reason I made this part of the exception spec, and added a way to set it using the `Span.RecordException` API is to accommodate the common use case where a user will do:

```
Span.RecordException(exception: e)
Span.SetAttribute('error.hint': true)
```

This would be more convenient, and encourage a developer to ask the question, is this is likely to be an error condition?

```
Span.RecordException(exception: e, errorHint: true)
```

I'm mostly concerned with having a semantic convention for an `error.hint`, and flexible about how we end up setting it. I think it's worth considering making it part of the `RecordException` API, but would be ok with keeping them separate. Are there any other opinions?

2020-08-18 15:29 UTC, mwear commented
> Based on [#706 (comment)](https://github.com/open-telemetry/opentelemetry-specification/issues/706#issuecomment-664457764), I'm marking this after-ga for now.

If we don't have this (or something similar) for GA, we cannot remove span status. At the very least, Jaeger exporters depend on this information as I linked in the description (repeated below):


* https://github.com/open-telemetry/opentelemetry-python/blob/5aa1d811039de774f4a84db4c9c656afe11827dd/exporter/opentelemetry-exporter-jaeger/src/opentelemetry/exporter/jaeger/__init__.py#L216-L218
* https://github.com/open-telemetry/opentelemetry-go/blob/576a1315774d4670bc85e2a0efbc0fcb06350746/exporters/trace/jaeger/jaeger.go#L245-L249

2020-08-18 15:32 UTC, iNikem commented
@mwear Is this "error" tag in Jaeger somehow specified? Or is it just a de facto convention?

2020-08-18 15:38 UTC, mwear commented
> @mwear Is this "error" tag in Jaeger somehow specified? Or is it just a de facto convention?

It's a semantic convention from OpenTracing that Jaeger has built functionality around: https://github.com/opentracing/specification/blob/master/semantic_conventions.md#span-tags-table,

2020-08-18 16:01 UTC, Oberon00 commented
From the SIG mtg: We have Jaeger in our GA requirements and Jaeger more or less requires the ability to mark errored spans, so marking this as required for GA.

2020-08-18 16:07 UTC, Oberon00 commented on specification/trace/semantic_conventions/exceptions.md
> +An `error.hint` attribute can be added to a span to indicate that an error
I agree that it would be helpful to make users aware of this when they record an exception, so I'm not really against adding this to the exception recording API. My main complaint is that the Span attribute is in the exceptions.md document. I think it should be it's own top-level semantic convention.

But adding parameters to RecordExceptions seems also problematic for different reasons, see , see #814.
Another point for RecordException is that it records an event. You can call it multiple times with different values for errorHint on the same span. This will lead to non-straightforward behavior like what if I explicitly set errorHint to false and then record an exception with errorHint true? What if I record multiple exceptions, some of which have errorHint true? Does the last call win? Does true always win except for an explicit SetAttribute call?

2020-08-18 16:47 UTC, bogdandrutu commented
@Oberon00 we have required to support exporting Jaeger which does not require to support a way to record error in the API. You can argue that we have OpenTracing -> OpenTelemetry bridge to support which require a solution for "error = true".

2020-08-18 22:06 UTC, tigrannajaryan commented on specification/trace/semantic_conventions/exceptions.md
> +An `error.hint` attribute can be added to a span to indicate that an error
I agree with @Oberon00 that it would be better to define `error.hint` in the regular semantic conventions list, especially given that it is a Span attribute and we already have a `https://github.com/open-telemetry/opentelemetry-specification/tree/master/specification/trace/semantic_conventions` for them.

I also agree that it is a bit strange that `RecordException` both adds an event and populates a Span attribute. 

Finally, I agree that the requirement to make 2 calls for erroneous exceptions (which likely is going to be a frequent case) is also not good.

Perhaps worth thinking a bit more end-to-end how error reporting should work and come up with an ergonomic API? I have a feeling we are adding this piece by piece and end up with pieces that don't really work very well together.

2020-08-19 16:57 UTC, mwear commented on specification/trace/semantic_conventions/exceptions.md
> +An `error.hint` attribute can be added to a span to indicate that an error
I can move the semantic convention to the top level. Ideally we can improve the `RecordException` API to facilitate recording an exception and providing an error hint. @Oberon00, your points about multiple calls to the `RecordException` API are valid. Ideally, once `error.hint` is set to true using the API, it would not be set to false even if a subsequent call passed in a false value. I don't think there is anything we can do about someone explicitly setting `error.hint` to false using `SetAttribute`. Perhaps that can be seen as an escape hatch for some. 

Would documenting that RecordException should not change an `error.hint` from true to false would be reasonable, or is there perhaps another approach that could work better?

2020-08-19 17:30 UTC, Oberon00 commented on specification/trace/semantic_conventions/exceptions.md
> +An `error.hint` attribute can be added to a span to indicate that an error
>  documenting that RecordException should not change an error.hint from true to false would be reasonable

Yes, I think that would be acceptable.
One thing I wonder about is that we probably what to know which recorded exception(s) was the cause for error.hint=true. I would suggest to simply duplicate any error.hint=true on the exception event.

2020-08-24 05:57 UTC, iNikem commented on specification/trace/api.md
> +The API SHOULD accept a parameter for an error hint and set the `error.hint`
If we all agree on adding new semantic convention for `error.hint` (both on span and on event?), but still have concerns about changing `RecordException` API, then it makes sense to split this PR into two. Let us proceed with new attribute (which allows to safely proceed with open-telemetry/oteps#134 as well) and discuss APIs separately.

@mwear what do you think?

2020-08-24 16:48 UTC, mwear commented on specification/trace/api.md
> +The API SHOULD accept a parameter for an error hint and set the `error.hint`
I can go either way on how we choose to divide this PR up. The API changes logically go with this work, and I worry that if we split the work, the convention could make it to GA without the corresponding API, which, would be unfortunate. At the same time, I don't want this work to get held up if we can't agree on the API.

@Oberon00 Would it be sufficient to add `exception.escaped` as an optional parameter to the `RecordException` API, or did you have something else in mind?

2020-08-25 11:42 UTC, Oberon00 commented on specification/trace/api.md
> +The API SHOULD accept a parameter for an error hint and set the `error.hint`
You should not add exception.escaped in this PR, but the worry is that we will get a lot of (optional) parameters here since we already have two PRs to add parameters. That said, I just proposed #874, which would completely remove the need to change the API for exception.escaped #784, but is not sufficient for this PR which also adds a span attribute. However, I think that this is a special enough behavior that an additional special optional argument to RecordException might be warranted, since I believe #874 should cover most other attributes.

Another option would be to bake this behavior into AddEvent/RecordException SDKs: If an event attribute error.hint is added and it is not set on the span, duplicate it there. If it is set to true, set it on the span even if it's already there.

Yet another option (after GA) would be to introduce the concept of an EventProcessor or an OnEvent callback in the existing SpanProcessor which could do such things in a more decoupled (and optionally (de)activable) way.

2020-08-25 15:13 UTC, iNikem commented on specification/trace/api.md
> +The API SHOULD accept a parameter for an error hint and set the `error.hint`
As this PR seems to be a blocker for open-telemetry/oteps#134, I would like to reiterate my proposal of splitting this PR in two. @Oberon00 @mwear Can you agree on that and make it happen?

2020-08-25 15:23 UTC, Oberon00 commented on specification/trace/api.md
> +The API SHOULD accept a parameter for an error hint and set the `error.hint`
👍 As said, I approve of the remainder of this PR.

2020-08-25 15:42 UTC, mwear commented on specification/trace/api.md
> +The API SHOULD accept a parameter for an error hint and set the `error.hint`
#874 looks reasonable to me. My only question is how you would see `error.hint` working with it. I think an argument can be made for it to be its own optional parameter, or it could be a special attribute in additional attributes. Do you have a preference?

2020-08-25 15:55 UTC, Oberon00 commented on specification/trace/api.md
> +The API SHOULD accept a parameter for an error hint and set the `error.hint`
> My only question is how you would see error.hint working with it.

I don't think #874 alone is enough for that and we would still need the special errorHint parameter you suggest in this PR. But #874 should shield us from all (most) other requests to change the RecordException API.

> Do you have a preference?

I think both are OK, see also my comment above https://github.com/open-telemetry/opentelemetry-specification/pull/822#discussion_r476383354.

2020-08-25 18:32 UTC, mwear commented on specification/trace/api.md
> +The API SHOULD accept a parameter for an error hint and set the `error.hint`
I think my preference would be to keep `error.hint` as a separate, but optional parameter. That way we can avoid having special attributes, which could lead to surprise for some users. Either this or #874 will have to rebase and integrate the changes that are introduced by both of the PRs. In the end,  we'll have an API that looks something like:

```
RecordException(e: Exception, errorHint?: Boolean, additionalAttributes?: Attributes)
```

2020-08-26 08:40 UTC, Oberon00 commented on specification/trace/api.md
> +The API SHOULD accept a parameter for an error hint and set the `error.hint`
> Either this or #874 will have to rebase

Actually I think that this will have to rebase, because I don't think these PRs are independent. As long as #874 is not merged and this PR still contains the API changes, I will keep my Request Changes here. Since #874 already has enough approvals, I expectt will be merged timely so I can approve this PR.

2020-08-27 22:10 UTC, mwear commented on specification/trace/api.md
> +The API SHOULD accept a parameter for an error hint and set the `error.hint`
I rebased and refactored the `RecordException` API description. PTAL.

2020-08-27 22:18 UTC, Oberon00 approved these changes
LGTM!

2020-08-27 23:20 UTC, carlosalberto approved these changes

2020-08-27 23:23 UTC, carlosalberto commented
@open-telemetry/specs-approvers Please review this PR. It has been improved after feedback has been applied.

cc @bogdandrutu

2020-08-27 23:35 UTC, tigrannajaryan commented on specification/trace/api.md
> +  calls to `RecordException` MUST not change the value.
>Once a span has `error.hint` set to true, subsequent
>  calls to `RecordException` MUST not change the value.

Does this mean that if I call RecordException twice, first time with error.hint=true, the second time with error.hint=false I will get 2 events and both with have error.hint=true?

2020-08-27 23:37 UTC, tigrannajaryan commented on specification/trace/semantic_conventions/span-general.md
> +was encountered, but the decision is not definitive. Tracing backends can use
>but the decision is not definitive

I think this phrase does not add much value. I think this paragraph works better without it.

2020-08-28 02:45 UTC, cxhansen commented
I think this is a good addition. After GA, we should add richer information about the reason for the error hint, but this is a good efficient way to flag the span for further inspection (machine or human).

2020-08-28 04:43 UTC, iNikem commented on specification/trace/api.md
> +  calls to `RecordException` MUST not change the value.
I read it that you will get two events, one with `error.hint=true`, another with `error.hint=false` and your span will have `error.hint=true`

2020-08-28 06:50 UTC, Oberon00 commented
We already have richer information often, e.g. exception events and http.status_code

2020-08-28 08:49 UTC, arminru reviewed
@mwear Please add a changelog entry.

2020-08-28 08:49 UTC, arminru commented on specification/trace/api.md
> +  calls to `RecordException` MUST not change the value.
@iNikem That's also my understanding.

2020-08-28 08:49 UTC, arminru commented on specification/trace/api.md
> +  calls to `RecordException` MUST not change the value.
@mwear Maybe add 
```suggestion
  calls to `RecordException` MUST not change the value of the span attribute.
```
for further clarification.

2020-08-28 08:49 UTC, arminru commented on specification/trace/semantic_conventions/span-general.md
> +`error.hint` attributes set to `true`. It's possible for more than one exception
```suggestion
If there are [exception events](exceptions.md) on a span, the span attribute `error.hint`
SHOULD be set to `true`, if at least one of the event's `error.hint` attribute is `true`.
It's possible for more than one exception
```
I think this explains the case of multiple events with potentially different hints better.

2020-08-28 08:49 UTC, arminru commented on specification/trace/semantic_conventions/span-general.md
> +| error.hint     | A boolean value that represents an instrumentation author's best judgement as to whether an error condition was observed |
```suggestion
| error.hint     | A boolean value that represents an instrumentation author's best judgement as to whether an error condition was observed. |
```

2020-08-28 14:35 UTC, tigrannajaryan commented on specification/trace/api.md
> +  calls to `RecordException` MUST not change the value.
>subsequent calls to `RecordException` MUST not change the value.

"value" recorded in the Span or recorded in the first Event or in the subsequent Events? This is ambiguous.

2020-08-31 05:31 UTC, iNikem commented
@open-telemetry/specs-approvers @open-telemetry/technical-committee Accepting and merging this PR is one of the ways to speed up open-telemetry/oteps#134. Is it possible to expedite this?

2020-08-31 07:01 UTC, Oberon00 commented on specification/trace/api.md
> +- A boolean error hint, as defined by the
There is a question I'd like to have an answer to before merging this: Why is this additional parameter in the RecordException spec instead of the AddEvent spec. Do we expect more intelligent guesses (beyond exception.escaped / #784) to be more likely for exceptions than any other event? Personally, I don't see a reason for that to be true, but there may be one.

I would thus propose to move this parameter to AddEvent. The "Note: `RecordException` may be seen as a variant of `AddEvent` with additional exception-specific parameters and all other parameters being optional" then implicitly already allows languages to add error.hint (as well as event name and timestamp) as additional optional parameters, though I would be fine with making these more explicit or even SHOULD requirements here (I'm also OK with a specific MUST requirement for error.hint for RecordException that references the actual spec wording in AddEvent.

The rationale being, that I'd like to see error.hint not unnecessarily coupled with exceptions.

2020-08-31 09:47 UTC, carlosalberto commented on specification/trace/api.md
> +- A boolean error hint, as defined by the
> I would thus propose to move this parameter to AddEvent. 

Why? I imagine two main cases for this semantic convention:

1) There was some exception and you want to mark it as an actual irrecoverable error, thus you call `RecordException(error_hint=true)`
2) There was something wrong with some parameters, a validation failed, or some timeout happened, and you want to set the convention directly (no need for an event to happen), without an actual event, so you call `SetAttribute()` for it. 

If users actually want to have a `error_hint` parameter for `AddEvent()` we will know for sure, and we can add it in the future. It's easier to add it than to remove it later on IMHO.

2020-08-31 09:50 UTC, carlosalberto commented
@open-telemetry/specs-approvers Please review/approve this PR. As @iNikem said, this is blocking an OTEP, so your help is needed (and I *don't* want to play the dictator by approving/merging this based on my own judgment ;) )

2020-08-31 10:45 UTC, Oberon00 commented on specification/trace/api.md
> +- A boolean error hint, as defined by the
> 1. There was some exception and you want to mark it as an actual irrecoverable error, thus you call `RecordException(error_hint=true)` 

First, I don't think that it is usual to know whether an exception is irrecoverable or not, usually you only know if it escaped. Second, I would be OK with leaving the parameter a MUST for RecordException, I just don't want the primary definition to be associated with exceptions more than required. I fear that error.hint could become a more widely used but less consistent synonym for exception.escaped, and am happy about every bit of distance it has from exceptions.

> 2. There was something wrong with some parameters, a validation failed, or some timeout happened, and you want to set the convention directly (no need for an event to happen), without an actual event, so you call `SetAttribute()` for it.

It's true that with the current semantic conventions, exceptions are special in that they are the only AFAIK semantic convention for events yet (besides gRPC stream messages). Yet no one is arguing to remove AddEvent. I just think that error.hint is more logical there but I agree that currently there is no use case for having it in AddEvent (other than manually building an exception event).

> It's easier to add it than to remove it later on IMHO.

As far as that goes, since #874 it is possible to have any additional attributes in RecordException, so the ` errorHint` parameter could be replaced by calling RecordException with that additional attribute and then calling `SetAttribute("error.hint", true)` (except for the "only set to false if not set yet" part, which would have to be substituted by "only call SetAttribute if true"). The main thing we accomplish by having this parameter, is guiding users to use the semantic attribute. And personally I am not sure if having an "intelligent guess" that goes beyond exception.escaped is common enough to have it baked into the API. To that end, I would be fine with removing the API changes without replacement (instead of moving/copying the parameter to AddEvent) too, maybe it would be even better after all to move the API changes to a separate PR.

2020-08-31 14:38 UTC, tigrannajaryan commented
Looks like the are still disagreements about how the API should look like. In order to make progress I suggest that we split this PR into 2 parts:
1. Introduction of "error.hints" semantic convention. I think everybody is in agreement about this part. I do not see unresolved comments and this can be merged quickly. This will be also sufficient to unblock and move forward https://github.com/open-telemetry/oteps/pull/134
2. Discussion around API whether it needs to be RecordException or AddEvent and what the parameters should look like. This can take a bit more time will no longer block OTEP 134.

2020-08-31 16:23 UTC, tigrannajaryan commented
@Oberon00 can you please attend the Error WG meeting this Thursday 8am PT? We want to make the final call on this PR and on the error.hint (provided that is not resolved offline in this thread before that).

2020-08-31 16:54 UTC, mwear commented
I appreciate the willingness to split this up to facilitate moving this and related PRs forward, but am conflicted in that I think it's essential that we have an API to help manage the interplay between spans and events when setting the `error.hint` semantic convention. My concern with splitting this PR is that we could end up with the `error.hint` semantic convention included in GA, without the corresponding API. The other consideration, is that we are proposing a replacement for span status. We should ensure that the replacement is actually an improvement. I'm not sure that the semantic convention alone would be an improvement.

2020-08-31 16:59 UTC, Oberon00 commented
> we could end up with the error.hint semantic convention included in GA, without the corresponding API

I don't think that's all that concerning. We also don't have an API for any other semantic convention. OpenTracing also did not have an API for setting the error attribute AFAIK.

2020-08-31 19:54 UTC, mwear commented
I had to main objectives when opening this PR:

* To have a span level attribute to indicate whether an error was (likely) observed during the execution of span
* Encourage a user to think about, and set that attribute when recording an exception (via the RecordException API).

As a result of the discussions on the PR, we realized that if you also add the an `error.hint` attribute to the exception event, it would be possible to link exceptions that were a cause of the `error.hint` on the span. This added some additional complexity as it requires setting attributes in multiple places. This makes the API all that more important as it will be easy for a user to forget, or simply be unaware that the attribute should be recorded in one place.

To answer your questions @Oberon00:

Why is the API important?

* The API has always been important since the beginning of this PR, even when it was just recording a span level `error.hint` attribute. The initial reason was to improve on the situation that existed in OpenTracing, which had the `error: true` semantic convention. It was common to record an error as a log (event in Otel), but forget to record the `error: true` span tag.

* Since this PR evolved to setting the matching `error.hint` tags on span and their corresponding events, we've introduced additional complexity that the API shields the user from. 

* It will help backends that want to be able to build functionality on the existence of matching `error.hint` tags between spans and events, and it will likely be correct, most of the time. Requiring users to a) know about and b) use multiple API methods will be error prone

Why might we want to keep span status without the API component of this PR?

Revisiting the two objectives for this PR mentioned above, one was having a span level indication of whether or not an error (likely) was observed, and the other was an API to encourage users to think about, and set that attribute when recording an exception. Without the API we are left with the span level indicator of (likely) error. A non-ok span status can be used as a proxy for that situation. One benefit is that it is more nuanced than a boolean, another benefit is that is has a first class API method on the span to help and encourage users to set it. One downside, is that the API method doesn't encourage a user to to consider setting it when recording an exception, as the current proposal does, but given the choice between an `error.hint` convention (without an API) and span status, span status looks more appealing.

2020-08-31 21:05 UTC, tedsuo commented
Regardless of whether it is `error.hint` or `span.status`, I think we need to extend the Event/Exception API to include the option of setting this marker. It will be inevitable that users fail to set it if we don't.

2020-09-01 11:02 UTC, Oberon00 reviewed
One thing that could convince me that the API is useful would be concrete examples of instrumentations that would set error.hint different from exception.escaped.

2020-09-01 11:50 UTC, iNikem commented
> One thing that could convince me that the API is useful would be concrete examples of instrumentations that would set error.hint different from exception.escaped.

Easy: servlet auto-instrumentation which sets `error.hint=true` whenever returned http status is >500

2020-09-01 11:57 UTC, Oberon00 commented
That makes sense, but would it call RecordException for that?

2020-09-01 12:27 UTC, iNikem commented
> That makes sense, but would it call RecordException for that?

Oi, sorry, of course not :) I forgot for a second that we are talking about `RecordException` API here.

Regarding `error.escaped`: I have a service, which queries some data. Data query throws some network exception, I catch it, log it and throw another, service-specific exception. Now, manual instrumentation inside that service method can record data querying exception with `RecordException` API setting `error.hint=true` but `error.escaped=false`. If I understand correctly the meaning of `error.escaped`.

2020-09-01 12:54 UTC, Oberon00 commented
It's exception.escaped, not error.escaped, but I think you described the meaning correctly. #761 has an example and a definition of "escaped".

2020-09-01 12:58 UTC, iNikem commented
> You would probably record another exception for the service exception with exception.escaped=true

Yes, I think so.

2020-09-03 10:34 UTC, Oberon00 commented
@bogdandrutu Probably it is too late for you to see this now, but maybe you can jump into today's (8 AM Pacific) error WG meeting? https://www.google.com/calendar/event?eid=MXM5Y3QydWhhdGltZjY3cDNiOHNxN2szaWJfMjAyMDA5MDNUMTUwMDAwWiBnb29nbGUuY29tX2I3OWUzZTkwajdiYnNhMm4ycDVhbjVsZjYwQGc&ctz=America/Los_Angeles

2020-09-03 16:17 UTC, Oberon00 requested changes
Based on the error WG meeting just now, I think we should not merge this PR, not even just the error.hint convention without API change, currently. The reason is that it is unclear when you are supposed to set error.hint:
* Is it a "weak" hint that is to be used by backends as a **fallback** when it cannot determine whether this was an error 
otherwise? I.e. is this a helper hint for backends which do not interpret http.status_code and I should set it on an HTTP span whenever I have a status >=400?
* Is it a "strong" hint that should **override** the backends' decision on whether this is an error? For example I might have an "delete_user_account" or "force_abort_operation" operation that I want to treat as an error even when it has a status of 200, or I might have a low priority "is this ready" API where a 503 is not considered an error.
* There is the third case, that @mwear pointed out, that you are tracing some operation for which there are no other semantic conventions to tell whether it is an error or not (for example I want to trace some internal function in my code). In that case, it would not matter if you have a strong or a weak hint.

It seems that jaeger/OpenTelemetry error tag was used mostly as a "weak" hint and was expected to be set whenever there was an indication of an error. But maybe we want both things. I'd say it would be best if we did not put the burden of providing a weak hint on instrumentations. And a strong hint *can* usually not be supplied by generic instrumentations but only by application's manual instrumentation (if at all).

One more thought: We may even think about a convention ` error.hint.<priority-integer/enum>`. Or maybe we should record an indicator on whether this is a generic or application instrumentation in the InstrumentationLibraryInfo. Lot's of things to be considered...

2020-09-03 17:02 UTC, tigrannajaryan commented
I agree. This is not ready for merging, still too much disagreement. I believe @tedsuo is going to come up with an alternate proposal.

2020-09-03 17:05 UTC, tigrannajaryan commented
>We may even think about a convention error.hint.<priority-integer/enum>.

Do I sense that this is gravitating towards my earlier [proposal](https://github.com/open-telemetry/opentelemetry-specification/pull/698) to use SeverityNumber? :-)

2020-09-03 17:09 UTC, Oberon00 commented
We would have a severity linked with a success value. So you could have a success with a high "severity". More a decision weight / probability of being right. But this is just an idea I threw out, probably too complex to be useful anywy.

2020-09-17 16:32 UTC, mwear commented
Closing this in favor of: https://github.com/open-telemetry/opentelemetry-specification/issues/965.

2020-09-17 16:32 UTC, closed without merging