Add description of TraceState operations
open-telemetry/opentelemetry-specification pull request #905
Opened 2020-09-01 11:48 UTC by iNikem

Fixes #759

## Changes

Add description of TraceState operations.

2020-09-01 12:01 UTC, Oberon00 commented on specification/trace/sdk.md
> +In both cases `Propagators` and `SpanExporters` may modify `TraceState` before serializing it to the wire.
```suggestion
In both cases `Propagators` and `SpanExporters` may create a modified `TraceState` copy before serializing it to the wire.
```

2020-09-01 12:16 UTC, Oberon00 commented on specification/trace/sdk.md
> +Tracing SDK MUST provide at least the following operations on `TraceState` which return a new `TraceState` with the modifications applied:
Why in the SDK? The TraceState is defined in the API. If these are utility functions it would indeed make sense to have them in the SDK or a separate artifact, but we should be a bit more explicit here.

2020-09-01 12:19 UTC, iNikem commented on specification/trace/sdk.md
> +Tracing SDK MUST provide at least the following operations on `TraceState` which return a new `TraceState` with the modifications applied:
Because user is not going to change `TraceState`. These operations are for SDK only and even only for some parts of SDK. I am not even sure that we should expose `TraceState` in API in the first place.

2020-09-01 12:20 UTC, Oberon00 commented on specification/trace/sdk.md
> +Tracing SDK MUST provide at least the following operations on `TraceState` which return a new `TraceState` with the modifications applied:
Since SpanContext is a final class in the API, it will be difficult to not expose it.

2020-09-01 12:22 UTC, iNikem commented on specification/trace/sdk.md
> +Tracing SDK MUST provide at least the following operations on `TraceState` which return a new `TraceState` with the modifications applied:
That's why I have not blown the scope and am proposing only those changes that were discussed in the ticket. Do you see any need for TraceState mutation operations to be present in API?

2020-09-01 12:27 UTC, Oberon00 commented on specification/trace/sdk.md
> +Tracing SDK MUST provide at least the following operations on `TraceState` which return a new `TraceState` with the modifications applied:
No. I'm just wondering about implementability.

2020-09-01 14:10 UTC, arminru approved these changes

2020-09-01 14:10 UTC, arminru commented on specification/trace/api.md
> +systems to participate in the same trace. It is fully described in [W3C
```suggestion
systems to participate in the same trace. It is fully described in the [W3C Trace Context
```
There are many specifications by the W3C 🙂

2020-09-01 14:10 UTC, arminru commented on specification/trace/sdk.md
> +`TraceState` is a part of [`SpanContext`](./api.md#spancontext), represented by a list of string key-values pairs and
```suggestion
`TraceState` is a part of [`SpanContext`](./api.md#spancontext), represented by a list of string key-value pairs and
```

2020-09-01 14:10 UTC, arminru commented on specification/trace/sdk.md
> + formally defined by [W3C specification](https://www.w3.org/TR/trace-context/#tracestate-header).
```suggestion
formally defined by the [W3C Trace Context specification](https://www.w3.org/TR/trace-context/#tracestate-header).
```

2020-09-01 14:10 UTC, arminru commented on specification/trace/sdk.md
> +* Add a new key/value pair
```suggestion
* Add a new key/value pair
* Update an existing value
```

"Update key value" sounds like changing the value of the key itself to me.

2020-09-01 14:10 UTC, arminru commented on specification/trace/sdk.md
> +These operations MUST follow rules described in [W3C specification](https://www.w3.org/TR/trace-context/#mutating-the-tracestate-field).
```suggestion
These operations MUST follow the rules described in the [W3C Trace Context specification](https://www.w3.org/TR/trace-context/#mutating-the-tracestate-field).
```

2020-09-01 14:10 UTC, arminru commented on specification/trace/sdk.md
> +Please note, that as `SpanContext` is immutable, it is not possible to update `SpanContext` with a new `TraceState`.
```suggestion
Please note, since `SpanContext` is immutable, it is not possible to update `SpanContext` with a new `TraceState`.
```

2020-09-01 14:10 UTC, arminru commented on specification/trace/sdk.md
> +In both cases `Propagators` and `SpanExporters` may create a modified `TraceState` copy before serializing it to the wire.
```suggestion
In both cases, `Propagators` and `SpanExporters` may create a modified `TraceState` copy before serializing it to the wire.
```

2020-09-01 14:41 UTC, iNikem commented on specification/trace/sdk.md
> +* Add a new key/value pair
This was copy-pasted from W3C spec :)

2020-09-01 15:39 UTC, reyang commented on specification/trace/sdk.md
> +These operations MUST follow the rules described in the [W3C Trace Context specification](https://www.w3.org/TR/trace-context/#mutating-the-tracestate-field).
If the operation is invalid (e.g. adding a new key/value pair which has illegal characters), what should be the return value? Here are the options:
1. Return a special NULL value (e.g. null reference, nullptr, NULL pointer or a special INVALID_TRACE_STATE).
2. Return the previous value (basically making the function no-op).
3. Have a mechanism reporting error (e.g. error code, exception).

2020-09-01 15:52 UTC, Oberon00 commented on specification/trace/sdk.md
> +These operations MUST follow the rules described in the [W3C Trace Context specification](https://www.w3.org/TR/trace-context/#mutating-the-tracestate-field).
I think we should not apply any limitations until we extract/inject. The tracestate on the SpanContext may actually end up in a propagator that has a different defintion of "illegal".

2020-09-01 16:06 UTC, arminru commented on specification/trace/sdk.md
> +* Add a new key/value pair
I see. We can still do better here in our spec as long as it's just about wording, however 😉

2020-09-01 16:08 UTC, reyang commented on specification/trace/sdk.md
> +These operations MUST follow the rules described in the [W3C Trace Context specification](https://www.w3.org/TR/trace-context/#mutating-the-tracestate-field).
I think this part needs to be clarified. For example: `UpdateTraceContext(traceContext, key, invalid_value)` in this case will end up with `invalid_value`.

2020-09-01 16:10 UTC, Oberon00 commented on specification/trace/sdk.md
> +These operations MUST follow the rules described in the [W3C Trace Context specification](https://www.w3.org/TR/trace-context/#mutating-the-tracestate-field).
It is invalid only for W3C (de)serialization however. The two cases for invalid values would be overly long and containing `,`, right?

2020-09-01 16:12 UTC, Oberon00 commented on specification/trace/sdk.md
> +These operations MUST follow the rules described in the [W3C Trace Context specification](https://www.w3.org/TR/trace-context/#mutating-the-tracestate-field).
Definitely needs to be clarified though, I would even call it "decided" 😃

2020-09-01 16:15 UTC, Oberon00 commented on specification/trace/sdk.md
> +These operations MUST follow the rules described in the [W3C Trace Context specification](https://www.w3.org/TR/trace-context/#mutating-the-tracestate-field).
A disadvantage of allowing some kinds of invalid keys/values (I think only keys containing `=` and values containing `,` is that it makes storing the tracestate unmodified as a single string impossible (it at least requires auxilary storage in case someone modifies the tracestate in-between)

2020-09-01 19:23 UTC, iNikem commented on specification/trace/sdk.md
> +These operations MUST follow the rules described in the [W3C Trace Context specification](https://www.w3.org/TR/trace-context/#mutating-the-tracestate-field).
I prefer more strict approach. If we reference the spec, which contains validation rules, then every operation on `TraceState` must preserve invariant of having valid value and to discard invalid ones as soon as possible. This means every attempt of invalid operation must signal an error in the language specific way (exception in Java, error code in Go etc).

2020-09-01 19:34 UTC, Oberon00 commented on specification/trace/sdk.md
> +These operations MUST follow the rules described in the [W3C Trace Context specification](https://www.w3.org/TR/trace-context/#mutating-the-tracestate-field).
I assume you want to define "valid on OpenTelemetry TraceState" as "valid on W3C TraceState"? What about transporting jaeger baggage? Would it be transported over this TraceContext too? Would it be OK to discard non-W3C compliant values?

2020-09-01 19:40 UTC, Oberon00 commented on specification/trace/sdk.md
> +These operations MUST follow the rules described in the [W3C Trace Context specification](https://www.w3.org/TR/trace-context/#mutating-the-tracestate-field).
I guess it's OK with me. Relaxing restrictions later is a non-breaking change (as long as implementations take care not to expose any internal representation as a string too directly), but not the other way round. If you write that down in the spec, then it's OK for me. Being vague with error handling is OK, this is a thing where languages differ wildly and we have general error handling guidelines already. So just writing "Keys and values MUST be valid for W3C tracestate. All functions MUST keep the W3C tracestate valid." I wonder if we also want to observe length limitations. If so I'd add "This includes dropping the oldest tracestate key-value pairs until the new key-value pair fits in if the length would be exceeded and ignoring any key-value pairs that would be too long." I would prefer "The only exception is the length of both individual keys and values as well as the complete trace state, which is unlimited in-process (the propagator is responsible for dropping overly long values, etc)." This is to allow using TraceState for in-process storage (since that's the only way to propagate custom information with the SpanContext that may be needed by custom propagators or samplers).

2020-09-01 20:03 UTC, SergeyKanzhelev commented on specification/trace/sdk.md
> +* Update key value
Also Get key value pair?

2020-09-01 20:04 UTC, SergeyKanzhelev commented on specification/trace/sdk.md
> +* Update key value
For the consistency with other two items:

```suggestion
* Update key/value
```

2020-09-01 20:12 UTC, SergeyKanzhelev commented on specification/trace/sdk.md
> +Tracing SDK MUST provide at least the following operations on `TraceState` which return a new `TraceState` with the modifications applied:
One theoretical example I have for TraceState manipulation from API is when Instrumentation Library needs to propagate an extra context to the backend. For example, it can be library-defined operation ID (or retry cunt), or some sort of debug flag/flight ID. Which is totally valid use of TraceState and should not necessarily require a reference to an SDK. These flags would be valid with any SDK/exporter configuration.

I don't think though we need to force to implement this operations in API now, we can always introduce it later when needed. So this comment is not blocking

2020-09-01 20:14 UTC, SergeyKanzhelev commented on specification/trace/sdk.md
> +These operations MUST follow the rules described in the [W3C Trace Context specification](https://www.w3.org/TR/trace-context/#mutating-the-tracestate-field).
I agree that starting with strict requirement would be better.

2020-09-01 20:16 UTC, Oberon00 commented on specification/trace/sdk.md
> +* Update key value
Definitely required. Enumerating them might not be necessary, but updating often makes no sense without a get operation.

2020-09-02 08:22 UTC, iNikem commented on specification/trace/sdk.md
> +These operations MUST follow the rules described in the [W3C Trace Context specification](https://www.w3.org/TR/trace-context/#mutating-the-tracestate-field).
Done.

2020-09-02 08:24 UTC, arminru commented on specification/trace/sdk.md
> +* Update key value
This section lists modifications permitted on TraceState, which also return a new, modified instance, so this enumeration itself is complete. Specifying the get operation as required makes sense, however.

2020-09-02 08:35 UTC, Oberon00 requested changes

2020-09-02 08:35 UTC, Oberon00 commented on specification/trace/sdk.md
> +and SHOULD signal an error situation in a language specific way (e.g. throw an exception in java, return error value in Go, etc).
It MUST NOT throw an exception, see https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/error-handling.md#basic-error-handling-principles

```suggestion
and MUST follow the [general error handling guidelines](../error-handling.md) (e.g. it usually most not return null or throw an exception).
```

2020-09-02 08:45 UTC, iNikem commented on specification/trace/sdk.md
> +and SHOULD signal an error situation in a language specific way (e.g. throw an exception in java, return error value in Go, etc).
damn :)

2020-09-02 09:03 UTC, Oberon00 approved these changes

2020-09-02 09:07 UTC, Oberon00 commented
Note that as @anuraaga suggested in https://github.com/open-telemetry/opentelemetry-specification/pull/875#issuecomment-685457279 an alternative design would be to replace TraceState with a `Map<Key<T>, T>`. This could have multiple advantages:

* W3C tracestate could be stored as a single string under one key on that map.
* Custom propagators (also W3C-based) and samplers after #856 would be able to parse certain values out of W3C tracestate or other sources (including newly generated, e.g. random numbers for routing) and put them under specific keys to avoid re-parsing a tracestate (entry) every time the information is needed.
* #510 would become less a pressing issue.

2020-09-02 09:32 UTC, iNikem commented
It may be so, indeed.

To avoid confusion: I still think this PR is useful for clarifying current state of the API and should be merged. I doubt we decide on removing TraceState completely very soon :)

2020-09-02 09:44 UTC, Oberon00 commented
The alternative approach would not be removing TraceState, it would just move it from a first-class member of SpanContext to being implemented with that more generic `Map<Key<T>, T>`. But that should also be doable later as a non-breaking change (given a careful implementation of TraceState).

2020-09-02 16:28 UTC, SergeyKanzhelev commented
I think this PR makes things better. Switching to map may be a separate discussion. The worst things about the map is that it is looses the order which is critical for the specification. This is why I wouldn't suggest to jump into this discussion in this PR

2020-09-02 16:29 UTC, SergeyKanzhelev commented
@iNikem I will let this PR sit for some time for cool off period for new comments. Otherwise it looks good and will be merged if not objections received by tomorrow PT

2020-09-02 16:38 UTC, Oberon00 commented
> The worst things about the map is that it is looses the order

There are ordered maps, but my suggestion would anyway be to have the current W3C tracestate as a single unparsed string under a single key in that map.

>  This is why I wouldn't suggest to jump into this discussion in this PR

Right, this discussion is already going on at https://github.com/open-telemetry/opentelemetry-specification/pull/875#issuecomment-685457279

2020-09-02 18:45 UTC, carlosalberto approved these changes

2020-09-03 18:37 UTC, iNikem commented
@SergeyKanzhelev can we merge? :)

2020-09-03 18:44 UTC, merged