Add yaml semantic conventions for Exception
open-telemetry/opentelemetry-specification pull request #927
Opened 2020-09-07 11:54 UTC by thisthat

# Changes

Updated Exception semantic convention to the YAML format.

Related issues #547

2020-09-08 13:44 UTC, carlosalberto approved these changes

2020-09-08 14:53 UTC, arminru approved these changes

2020-09-08 14:53 UTC, arminru commented on semantic_conventions/trace/exception.yaml
> +        - "exception.message"
```suggestion
        - "exception.message"

```
Missing newlines at the end of files cause follow-up diffs adding to them to mistakenly show the last line as edited.

2020-09-08 14:53 UTC, arminru commented on semantic_conventions/trace/exception.yaml
> +        brief: "The exception message"
```suggestion
        brief: The exception message.
```

2020-09-08 20:53 UTC, tigrannajaryan commented on semantic_conventions/trace/exception.yaml
> +        examples: "Exception in thread \"main\" java.lang.RuntimeException: Test exception\\n at com.example.GenerateTrace.methodB(GenerateTrace.java:13)\\n at com.example.GenerateTrace.methodA(Gener
Do we expect `exception.stacktrace` to be an backlash-escaped, double-quotted string literal like shown in this example?

I understand that this is a copy/paste from exceptions.md so we don't need to solve this in this PR, just checking if this is the intent.

2020-09-10 12:31 UTC, arminru commented on semantic_conventions/trace/exception.yaml
> +        examples: "Exception in thread \"main\" java.lang.RuntimeException: Test exception\\n at com.example.GenerateTrace.methodB(GenerateTrace.java:13)\\n at com.example.GenerateTrace.methodA(Gener
This is just for the YAML syntax, the expected attribute value should conform to the syntax as it is shown in the resulting markdown (no extra quotes, no escaping).

2020-09-11 12:06 UTC, carlosalberto commented
@thisthat Please rebase and resolve the conflicts ;)

2020-09-11 12:08 UTC, Oberon00 commented on semantic_conventions/trace/exception.yaml
> +        examples: "Exception in thread \"main\" java.lang.RuntimeException: Test exception\\n at com.example.GenerateTrace.methodB(GenerateTrace.java:13)\\n at com.example.GenerateTrace.methodA(Gener
I think we should use some other YAML string syntax then (e.g. the `>` syntax also used for brief above) to avoid escaping.

2020-09-11 12:22 UTC, thisthat commented on semantic_conventions/trace/exception.yaml
> +        examples: "Exception in thread \"main\" java.lang.RuntimeException: Test exception\\n at com.example.GenerateTrace.methodB(GenerateTrace.java:13)\\n at com.example.GenerateTrace.methodA(Gener
I have changed to use single quotes. This way, escaping is not necessary :)

2020-09-11 12:23 UTC, thisthat commented
@carlosalberto done in 22bbb9b :)

2020-09-11 12:26 UTC, Oberon00 commented on semantic_conventions/trace/exception.yaml
> +          there is an exception active just before ending the span). Note that an
I think the "Note that..." part should be put into the note, not the brief.

2020-09-11 12:53 UTC, Oberon00 approved these changes

2020-09-11 19:47 UTC, tigrannajaryan commented on semantic_conventions/trace/exception.yaml
> +        examples: "Exception in thread \"main\" java.lang.RuntimeException: Test exception\\n at com.example.GenerateTrace.methodB(GenerateTrace.java:13)\\n at com.example.GenerateTrace.methodA(Gener
I still see \n in the rendered markdown.

![image](https://user-images.githubusercontent.com/4194920/92966592-d3b50c80-f445-11ea-9850-bd85755f233a.png)

I don't think this is the intent. This will confuse people and instead of sending the multiline stacktrace string as-is people will incorrectly do escaping before sending.

If this is the intent and we want the attribute to arrive as a single-line escaped string then we need to clearly specify it in this document, but I think that would be wrong.

2020-09-11 19:48 UTC, tigrannajaryan requested changes
Blocking just to understand clearly the intent regarding `exception.stacktrace`. The PR itself is highly welcome, but I think the way the example is rendered makes it confusing.

2020-09-11 20:30 UTC, Oberon00 commented
Indeed it seems like the \n are not doing what they should inside the ''.

2020-09-14 07:10 UTC, thisthat commented
@tigrannajaryan could you please explain better the problem? Do you want the example to be encapsulated in quotes?

2020-09-14 07:33 UTC, Oberon00 commented
@thisthat You are right: https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/semantic_conventions/exceptions.md#attributes

2020-09-14 15:18 UTC, tigrannajaryan commented
I think the original example was also misleading. I expect not to see any literal \n characters in the example and I expect not to see backslaches before double quote characters.
It needs to be fixed, but I am fine if it is fixed in a future PR.

2020-09-14 15:19 UTC, tigrannajaryan approved these changes

2020-09-15 12:25 UTC, thisthat commented
@tigrannajaryan I've created #951 to track the example change

2020-09-15 13:30 UTC, merged