Specify Span ID creation with sampling.
open-telemetry/opentelemetry-specification pull request #998
Opened 2020-09-24 15:26 UTC by Oberon00

Partial fix for #864 (remainder would require an API change to not pass a trace ID to the sampler if there is none).

## Changes

* Clarififies how span IDs are generated for DRO and RECORD_ONLY.

2020-09-24 16:24 UTC, Oberon00 commented on specification/trace/sdk.md
> +3. If the decision is `DROP`, use the parent span ID or all-zero if there is none.
That means: If there is no parent *and* the decision is drop, we will have a span with the new trace ID but an invalid span ID. The SpanContext as a whole is thus invalid. We could also specify that the generated trace ID should be discarded in that case.

2020-09-24 16:26 UTC, Oberon00 commented on specification/trace/sdk.md
> +   Otherwise (if the decision is not `DROP`) a new span ID MUST be generated.
That means: RECORD_ONLY spans get a new span ID, always. I don't know what the purpose of RECORD_ONLY is (should we remove it?), but having different spans with the same trace+span ID seems worse than breaking the trace in case any children of the RECORD_ONLY span become RECORD_AND_SAMPLE .

2020-09-25 16:29 UTC, andrewhsu commented
from the issue triage mtg today, labelling this as `after-ga` since the corresponding i up.ssue is `after-ga`.

however, if this is just a editorial change that does not affect the trace freeze, please speak

2020-09-25 16:35 UTC, Oberon00 commented
As stated in the issue, this PR is exactly the part of the issue that is *not* doable after-ga.

2020-09-25 18:08 UTC, tigrannajaryan commented
@Oberon00 will you be able get the approvals today? Other options are not doing this in 1.0 at all or asking for an exception from spec freeze.

2020-09-25 18:54 UTC, Oberon00 commented
@tigrannajaryan I won't. In that case, it seems we will have to look around after GA and document all the paths taken by any SDKs as allowed and maybe introduce some options.

2020-10-06 09:09 UTC, Oberon00 commented
I changed the corresponding issue to a new issue #1060, so we can re-evaluate what to do here for GA.

2020-10-06 09:13 UTC, Oberon00 commented on specification/trace/sdk.md
> +3. If the decision is `DROP`, use the parent span ID or all-zero if there is none.
Actually this may be worth re-considering: Generating trace+span ID for an unsampled root has implications if the span is injected. If we generate an invalid spancontext (with zero span ID), we will inject nothing as we have an invalid traceparent header as per W3C (cf. also #753). This causes downstream components to potentially create traces / run sampling logic that they would not if they got an incoming unsampled traceparent header.

2020-10-06 16:15 UTC, Oberon00 commented
Relabeled to allowed-for-ga to match #1060.

2020-10-06 20:45 UTC, bogdandrutu submitted a review, later dismissed

2020-10-07 16:13 UTC, arminru commented on specification/trace/sdk.md
> +   (sometimes called a `NoOpSpan` or `DefaultSpan`).
```suggestion
   `Span` is created with no API-implementation installed (i.e., a [Propagated Span](api.md#propagated-span-creation)).
```

2020-10-07 22:26 UTC, carlosalberto commented on specification/trace/sdk.md
> +3. If the decision is `DROP`, use the parent span ID or all-zero if there is none.
> We could also specify that the generated trace ID should be discarded in that case.

I'd be fine with this.

> we will inject nothing as we have an invalid traceparent header as per W3C (cf. also #753). This causes downstream components to potentially create traces

Could you elaborate?

2020-10-12 08:55 UTC, Oberon00 commented on specification/trace/sdk.md
> +3. If the decision is `DROP`, use the parent span ID or all-zero if there is none.
@carlosalberto We never inject an invalid SpanContext, at least using W3C. If we would generate a new ID instead of using zero, we would inject a valid spancontext with unset sampled flag. This will likely cause the receiver to suppress the trace. On the other hand, if we use zero, the downstream component will not receive any tracestate and will likely start a new trace.

Now that I write, this, I realize that this even applies to local child spans: Normally if the root span is not sampled, local child spans would be unsampled too, but with this they would become root spans.

This is bad. I think we will have to create Span *and* Trace ID even for "dropped" root spans after all. It seems there is a dependency of #864 "Option to allow "default" IDs for unsampled traces" on #753 "https://github.com/open-telemetry/opentelemetry-specification/issues/753". We would have to have some sentinel SpanContext that is "valid, unsampled, but without any IDs". That's out of scope here of course.

2020-10-12 12:12 UTC, Oberon00 commented on specification/trace/sdk.md
> +3. If the decision is `DROP`, use the parent span ID or all-zero if there is none.
Updated in 4006816. Maybe this demonstrates how easy it is to mess up here and that it is thus important to have this specified clearly? 😃

2020-10-22 11:20 UTC, arminru commented on specification/trace/sdk.md
> +   a valid trace Id as input).
```suggestion
1. If there is a valid parent trace ID, use it. Otherwise generate a new one
   (note: this must be done before calling `ShouldSample`, because it expects
   a valid trace ID as input).
```

2020-10-22 11:20 UTC, arminru commented on specification/trace/sdk.md
> +### SDK Span creation
I doubt that all of our SDK implementations are aligned here so it would make sense to add a spec compliance matrix entry "Trace and Span IDs are created as defined in [this section]".

2020-10-22 11:20 UTC, arminru commented on specification/trace/sdk.md
> +   a new span ID MUST be generated.
The current state of this PR sounds like the right thing to do to me, but I'm not entirely sure of the consequences.
Fellow @open-telemetry/technical-committee, please take a look (especially at previous comments https://github.com/open-telemetry/opentelemetry-specification/pull/998#discussion_r503141158) as well. We might need to sort this out before GA.

2020-10-22 11:35 UTC, Oberon00 commented on specification/trace/sdk.md
> +### SDK Span creation
Done in bfd652f.

2020-10-28 05:51 UTC, jmacd approved these changes

2020-10-28 05:51 UTC, jmacd commented on specification/trace/sdk.md
> +1. If there is a valid parent trace ID, use it. Otherwise generate a new one
nit: replace "new one" with "new trace ID"?

2020-10-28 05:51 UTC, jmacd commented on specification/trace/sdk.md
> +3. If the decision is `DROP` and there is a valid parent span ID, use it.
nit: I suggest more verbosity: "... and there is a valid parent span ID, use it as the new context's span ID".

2020-10-28 05:51 UTC, jmacd commented on specification/trace/sdk.md
> +   a new span ID MUST be generated.
Yes. This is tricky, but I like @Oberon00's proposal that DROP sampling decisions at the root of a trace should generate a new trace ID and new span ID without the sampled bit set. Am I understanding?

2020-10-28 09:27 UTC, Oberon00 commented on specification/trace/sdk.md
> +   a new span ID MUST be generated.
> Am I understanding?

Yes, "no valid parent span ID" is equivalent to a root span.

2020-10-28 09:28 UTC, Oberon00 commented on specification/trace/sdk.md
> +1. If there is a valid parent trace ID, use it. Otherwise generate a new one
```suggestion
1. If there is a valid parent trace ID, use it. Otherwise generate a new trace ID
```

2020-10-28 09:29 UTC, Oberon00 commented on specification/trace/sdk.md
> +3. If the decision is `DROP` and there is a valid parent span ID, use it.
```suggestion
3. If the decision is `DROP` and there is a valid parent span ID, reuse it as the new `Span`'s span ID.
```

2020-10-28 15:45 UTC, yurishkuro approved these changes

2020-10-28 16:29 UTC, carlosalberto approved these changes

2020-10-28 16:30 UTC, carlosalberto commented
@open-telemetry/specs-approvers Please review this one. We bumped its related issue as "Required-for-GA" so we definitely needs reviews ;)

2020-10-28 20:54 UTC, jkwatson commented on specification/trace/sdk.md
> +3. If the decision is `DROP` and there is a valid parent span ID, reuse it as the new `Span`'s span ID.
Doesn't this mean two spans with the same id? I can imagine this could become extremely confusing to someone trying to debug things. As a user, I think I'd be super confused if I saw a new Span created with the same ID as the parent, even if that span might not end up going any where.

2020-10-28 21:02 UTC, Oberon00 commented on specification/trace/sdk.md
> +3. If the decision is `DROP` and there is a valid parent span ID, reuse it as the new `Span`'s span ID.
It's two spans with the same ID the same way as calling extract and then inject creates a copy of the injected span (with the same ID). It is more of a hollow shell of a span than an actual span.

> even if that span might not end up going anywhere

This span cannot end up going anywhere. A dropped span is always non-recording, so there is nothing that could end up anywhere beside the span+trace ID itself (not even a parent span ID). What is more, SpanProcessors are not invoked with dropped spans.

RECORD_ONLY spans are a different story, and they do get a new ID, see https://github.com/open-telemetry/opentelemetry-specification/pull/998#discussion_r494451985

All that being said, I think I could agree that this may make the mental model of sampling a bit more complicated than just always creating a new ID. But I hope that the benefits, namely ability to resume sampling in a child and having the closes sampled span as parent, and a slight(?) performance improvement would be worth it.

2020-10-28 21:34 UTC, jkwatson commented on specification/trace/sdk.md
> +3. If the decision is `DROP` and there is a valid parent span ID, reuse it as the new `Span`'s span ID.
Personally, I think I'd prefer attacking this problem via a smarter SpanContext that allowed propagation of the relevant bits, rather than generating weird internal spans for the sake of propagating the SpanContext.

2020-10-28 21:35 UTC, jkwatson commented on specification/trace/sdk.md
> +3. If the decision is `DROP` and there is a valid parent span ID, reuse it as the new `Span`'s span ID.
Or, better yet, move the TraceState and TraceFlags out of the span altogether and propagate them separately in the Context, rather than hanging them off a span.

2020-10-28 21:47 UTC, Oberon00 commented on specification/trace/sdk.md
> +3. If the decision is `DROP` and there is a valid parent span ID, reuse it as the new `Span`'s span ID.
What should startSpan return for a dropped span then?

2020-10-28 22:08 UTC, jkwatson commented on specification/trace/sdk.md
> +3. If the decision is `DROP` and there is a valid parent span ID, reuse it as the new `Span`'s span ID.
Just the "invalid" span that it does today. all zeros for both of the ids.

2020-10-29 09:15 UTC, Oberon00 commented on specification/trace/sdk.md
> +3. If the decision is `DROP` and there is a valid parent span ID, reuse it as the new `Span`'s span ID.
That would not work for the reasons outlined in https://github.com/open-telemetry/opentelemetry-specification/pull/998#discussion_r503141158, (the sampled-flag would be ignored). Also, Java always generates a new span ID currently (https://github.com/open-telemetry/opentelemetry-java/blob/34953d5feee5129b64c8cec04d23dc3be07a9be8/sdk/tracing/src/main/java/io/opentelemetry/sdk/trace/SpanBuilderSdk.java#L204-L209), and the spec says nothing at all.

2020-10-29 14:50 UTC, jkwatson commented on specification/trace/sdk.md
> +3. If the decision is `DROP` and there is a valid parent span ID, reuse it as the new `Span`'s span ID.
I agree with that. That's why I think we could solve this by moving the TraceState and flags out of the span, so samplers can use that information from the context, rather than having just the span to work with.

2020-10-29 15:59 UTC, Oberon00 commented on specification/trace/sdk.md
> +3. If the decision is `DROP` and there is a valid parent span ID, reuse it as the new `Span`'s span ID.
Not sure if I follow. The TraceState and Flags are already in the SpanContext, not the Span. The problem is that we say that if trace OR span ID is zero, then we should disregard traceflags and tracestate. If we wanted to change that, the easiest and IMHO best way would be to simply say that only *the* invalid, empty SpanContext is invalid, and all others are valid, even if they have neither trace nor span ID. But this is discussed in #753 and I think out of scope in this PR.

2020-10-29 16:11 UTC, jkwatson commented on specification/trace/sdk.md
> +3. If the decision is `DROP` and there is a valid parent span ID, reuse it as the new `Span`'s span ID.
well, I think of "SpanContext" as just being a piece of the Span, so same same. I was suggesting a more radical change, rather than hacking it with some id generation rules.

2020-10-30 19:17 UTC, cijothomas commented on specification/trace/sdk.md
> +3. If the decision is `DROP` and there is a valid parent span ID, reuse it as the new `Span`'s span ID.
If the decision is `DROP`, we don't need to create a Span at all, right? So why we care about the spanid of the span which is not going to be created?

2020-10-30 19:22 UTC, Oberon00 commented on specification/trace/sdk.md
> +3. If the decision is `DROP` and there is a valid parent span ID, reuse it as the new `Span`'s span ID.
> we don't need to create a Span at all

We need to return a Span instance from the function. And if we use that span as parent, the sampled flag (unset) must be available for the (parent-based) sampler to decide whether to sample the child span. This is required even if that span is in another process, i.e. propagators must have something to propagate.

2020-10-30 19:28 UTC, Oberon00 commented on specification/trace/sdk.md
> +3. If the decision is `DROP` and there is a valid parent span ID, reuse it as the new `Span`'s span ID.
E.g. let's say we do `A = startSpan()` and A is dropped. Now we create span `B = startSpan(parent=currentContextWith(A))`. If A has no span ID, then this is equivalent to just `B = startSpan()`. However, this would be wrong, since an unsampled parent often causes the child to short-circuit sampling logic and go straight to DROP.

Similarly, if we do `inject(A, httpRequest); httpRequest.execute()` and then in another process `AExtracted = extract(httpRequest); C = startSpan(parent=AExtracted)` we want to know that AExtracted is a unsampled, existing span.

2020-10-31 00:06 UTC, cijothomas commented on specification/trace/sdk.md
> +3. If the decision is `DROP` and there is a valid parent span ID, reuse it as the new `Span`'s span ID.
Thanks @Oberon00 for clarifying!

2020-11-03 13:15 UTC, Oberon00 commented on specification/trace/sdk.md
> +3. If the decision is `DROP` and there is a valid parent span ID, reuse it as the new `Span`'s span ID.
@jkwatson I don't know what I could do in this PR to resolve your concerns. Should this discussion maybe be a separate issue?

2020-11-03 13:57 UTC, anuraaga commented on specification/trace/sdk.md
> +3. If the decision is `DROP` and there is a valid parent span ID, reuse it as the new `Span`'s span ID.
@Oberon00 Is there a downside to using an invalid span ID? I think this isn't really the same case as an extracted non-recording span since that exists for a very short amount of time before creating a real span. In this case, log messages in two different processes will have the same span ID added to them, IIUC, and it does seem like it could cause problems for correlation.

2020-11-03 14:00 UTC, Oberon00 commented on specification/trace/sdk.md
> +3. If the decision is `DROP` and there is a valid parent span ID, reuse it as the new `Span`'s span ID.
The downside is that a span with invalid ID is indistinguishable from no span, #753

2020-11-03 14:04 UTC, anuraaga commented on specification/trace/sdk.md
> +3. If the decision is `DROP` and there is a valid parent span ID, reuse it as the new `Span`'s span ID.
Ah - yeah how to handle trace state for this is interesting. I agree it's probably a good idea to decouple OTel from w3c by allowing it to be propagated if it exists, similar to what we do for sampling decision (why not). I think it does have to be addressed separately from the span ID though.

2020-11-03 14:08 UTC, Oberon00 commented on specification/trace/sdk.md
> +3. If the decision is `DROP` and there is a valid parent span ID, reuse it as the new `Span`'s span ID.
The main topic of #753 is the trace state (which is unrelated to this PR here), but the problem is still that if span ID = 0 then isValid = false, so for example in Java, it would not be injected, and the sampler would ignore it.

2020-11-03 14:08 UTC, Oberon00 commented on specification/trace/sdk.md
> +3. If the decision is `DROP` and there is a valid parent span ID, reuse it as the new `Span`'s span ID.
> Currently, we consider a SpanContext invalid if the trace or span ID is invalid (i.e. it is invalid unless both are valid), and this is exposed with an API function. As a result, for example in Java, an invalid span context is not inherited by child spans (a fresh context with new span and trace ID is generated, discarding any TraceState or TraceFlags).

2020-11-03 14:11 UTC, Oberon00 commented on specification/trace/sdk.md
> +3. If the decision is `DROP` and there is a valid parent span ID, reuse it as the new `Span`'s span ID.
I do not want to change the definition of isValid in this PR and I think relying on an invalid span being propagated is bad. Also, even if we did this, we also want to have sampling working with the W3C propagator (with sampled flag=false being propagated), so even if we relax isValid, I still think we need a valid span ID.

2020-11-03 15:01 UTC, anuraaga commented on specification/trace/sdk.md
> +3. If the decision is `DROP` and there is a valid parent span ID, reuse it as the new `Span`'s span ID.
Ah also I think generating a span ID that's not exported is fine - but similar to @jkwatson's concern sharing the ID (without native support for it, don't forget we already said no to the Zipkin model :) ) is concerning to me from a correlation perspective.

2020-11-03 15:10 UTC, Oberon00 commented on specification/trace/sdk.md
> +3. If the decision is `DROP` and there is a valid parent span ID, reuse it as the new `Span`'s span ID.
> sharing the ID (without native support for it, don't forget we already said no to the Zipkin model :) ) is concerning to me from a correlation perspective.

I would argue that:

1. Nothing is shared, as a DROP-ed span is not really a span, only a wrapped SpanContext. The span returned by startSpan after a DROP decision where a parent ID is reused will typically be the same spancontext that the parent had wrapped in a SpanContext (for the typical case where we already get an unsampled span when extracting, it can be the same Span instance as in the parent Context even). Backends will never see this span.
2. There is no "native support" for *not* sharing the span ID. The trace will break if a child span becomes sampled again. This is also concerning to me.

For these reasons, I think this is not comparable to the Zipkin model, where information for the same span ID is exported from different places/processes.

2020-11-03 17:06 UTC, Oberon00 commented on specification/trace/sdk.md
> +3. If the decision is `DROP` and there is a valid parent span ID, reuse it as the new `Span`'s span ID.
So in 2. I mentioned the concrete problem we have with generating a new trace ID. I don't know of any real problem that could result from re-using the parent span ID for non-recording spans (unexported but recording spans might cause trouble, but we are talking about really non-recording spans). If you know of a real problem that might result from this PR, please tell me.

From my POV, this change should be invisible to backends, unless a child-span becomes sampled again, in which case it will be a direct child of the nearest previously sampled parent for the backend, instead of having a missing parent.

2020-11-03 17:46 UTC, jkwatson commented on specification/trace/sdk.md
> +3. If the decision is `DROP` and there is a valid parent span ID, reuse it as the new `Span`'s span ID.
My concern is not for backends, but for local developer experience. If someone is trying to debug their instrumentation and sees that they are getting duplicate span ids, they're going to scream bloody murder, if they haven't very carefully read the spec and/or documentation.

2020-11-03 17:51 UTC, Oberon00 commented on specification/trace/sdk.md
> +3. If the decision is `DROP` and there is a valid parent span ID, reuse it as the new `Span`'s span ID.
> If someone is trying to debug their instrumentation and sees that they are getting duplicate span ids, they're going to scream bloody murder, if they haven't very carefully read the spec and/or documentation.

I don't know in which scenario you would usually stumble upon this. I do agree that it may make it a bit harder to debug instrumentations, but I think it might make it easier to debug the monitored systems (because of not breaking the trace).
I fear debugging a dropped span may be difficult anyway, because you need to know about sampling first and if someone sends you something with a `0` sampled flag, you might start scratching your head why your instrumentation is not working for *some* requests.

2020-11-03 17:54 UTC, jkwatson commented on specification/trace/sdk.md
> +3. If the decision is `DROP` and there is a valid parent span ID, reuse it as the new `Span`'s span ID.
I literally thinking of someone stepping through their code in a debugger. If they don't know the spec well (and most won't!), and they see a newly created span has the same ID as the previous one, there will be an issue logged about it.

2020-11-03 18:08 UTC, Oberon00 commented on specification/trace/sdk.md
> +3. If the decision is `DROP` and there is a valid parent span ID, reuse it as the new `Span`'s span ID.
They should also notice the strange type of the Span though. And isn't it better to make a dropped span stand out here?

2020-11-03 19:03 UTC, jkwatson commented on specification/trace/sdk.md
> +3. If the decision is `DROP` and there is a valid parent span ID, reuse it as the new `Span`'s span ID.
Sure, by not having the same span id as another span!  

I'm not going to block this change, but I do think it's a bad idea.

2020-11-03 20:02 UTC, Oberon00 commented on specification/trace/sdk.md
> +3. If the decision is `DROP` and there is a valid parent span ID, reuse it as the new `Span`'s span ID.
OK, so you would prefer to always generate a new span + trace ID, i.e. treat DROP the same as all other decisions? I think this *is* the other sensible option, although I would prefer the one in this PR. In the end, we need a decision here and I feel the current approvals on this PR are insufficient as this is an important topic.

2020-11-03 20:19 UTC, yurishkuro commented on specification/trace/sdk.md
> +1. If there is a valid parent trace ID, use it. Otherwise generate a new trace ID
> If there is a valid parent trace ID, use it.

This is actually not compatible with how many cloud providers treat external trace ID coming from a customer - providers may or may not trust such external IDs. So MUST is too strong here, there is an option for configurable behavior.

2020-11-03 20:21 UTC, yurishkuro commented on specification/trace/sdk.md
> +2. Query the `Sampler`'s [`ShouldSample`](#shouldsample) method.
This could be interpreted that a sampling decision MUST always be made. Perhaps worth clarifying that some samplers may retain/respect the propagated sampling decision instead of making a new one.

2020-11-03 20:26 UTC, yurishkuro commented on specification/trace/sdk.md
> +3. If the decision is `DROP` and there is a valid parent span ID, reuse it as the new `Span`'s span ID.
My vote is to reuse span ID, that's the only way I can see to keep the trace structure sensible when some spots in the graph decide not to record - if they don't record, they effective should look like a simple relaying proxy, which _does not_ change span ID.

2020-11-03 20:36 UTC, Oberon00 commented on specification/trace/sdk.md
> +1. If there is a valid parent trace ID, use it. Otherwise generate a new trace ID
I think MUST is exactly right here. We currently MUST reuse the parent trace ID, or otherwise not extract it at all at the extract level so that it does not even get to the Tracer/SDK. A configurable option to ignore a remote trace ID would be another concern and maybe a good argument for fusing the configurable ID generation into Sampler (#896)

2020-11-03 20:37 UTC, Oberon00 commented on specification/trace/sdk.md
> +2. Query the `Sampler`'s [`ShouldSample`](#shouldsample) method.
Why do you think this could be interpreted this way? We do specify the ParentBased sampler below which will respect the parent's sampled flag in it's decision (translating sampled=true to RECORD and sampled=false to DROP is also a decision).

2020-11-03 20:42 UTC, yurishkuro commented on specification/trace/sdk.md
> +2. Query the `Sampler`'s [`ShouldSample`](#shouldsample) method.
Yes, but you're using "forward reference" :-) When someone's reading this for the first time, and doesn't know about ParentBased sampler discussed later, they can easily interpret this as "make a sampling decision".

2020-11-03 21:02 UTC, yurishkuro commented on specification/trace/sdk.md
> +1. If there is a valid parent trace ID, use it. Otherwise generate a new trace ID
I would disagree. Extracting and sampling are well-encapsulated functionalities, which are orthogonal to the decision on reusing or regenerating a trace ID. Trying to put this aspect into extraction/sampling is an abstraction leak. There are already multiple implementations of both extractors and samplers, they would all have to deal with this extra concern, consistently. I think it belongs to the Tracer, and be configurable.

2020-11-03 21:24 UTC, Oberon00 commented on specification/trace/sdk.md
> +1. If there is a valid parent trace ID, use it. Otherwise generate a new trace ID
So basically, if SpanContext.IsRemote, drop the SpanContext? Or add an additional ParentFilter component that is queried before the Sampler and before deciding whether to generate a new ID?
I think this is out of scope here though. If such a component is added, we would add an additional step before the first like

> 1. Check if the parent span is valid for use by querying the configured ParentFilter.ShouldAccept with the parent Context as input. If the decision is REJECT, proceed as if no valid parent trace and span ID had been passed. Otherwise continue with the passed-in span and trace ID.

But this is really a separate issue. Right now if one wants to implement this the propagator is usable for that (even though you might argue it is not responsible). Other points to consider:
1. You cannot reject every IsRemote parent, that would make your distributed tracing non-distributed. You probably need some cryptographic signatures in place.
2. If, instead of cryptographic signatures, you want to rely on the origin of the span ID (e.g. source IP, etc) this would need to be done somewhere else where this information is still available, or the propagators would need to be adapted to enrich the context with such information
3. Do you want to forward an untrusted (Span)Context if you extract, then inject without creating a Span in-between? If not, then this check would need to be done on extract() (thus in a Propagator-(sub)component).

I think this is a separate, most-likely after-GA issue.

2020-11-03 21:30 UTC, Oberon00 commented on specification/trace/sdk.md
> +2. Query the `Sampler`'s [`ShouldSample`](#shouldsample) method.
I added a note in eb989b7.

2020-11-03 22:07 UTC, yurishkuro commented on specification/trace/sdk.md
> +1. If there is a valid parent trace ID, use it. Otherwise generate a new trace ID
> So basically, if SpanContext.IsRemote, drop the SpanContext? Or add an additional ParentFilter component that is queried before the Sampler and before deciding whether to generate a new ID?

Not drop, I think cloud providers would capture it on the span, but they will start a new internal trace, whose ID may then be returned to the caller using (future) w3c response header.

> I think this is a separate, most-likely after-GA issue.

I don't mind this being addressed post-GA, my main concern was that the current MUST wording dictates that respecting the inbound trace ID is the only possible processing model. However, maybe that's OK for SDK v1.

Booked https://github.com/open-telemetry/opentelemetry-specification/issues/1188

2020-11-04 20:37 UTC, yurishkuro commented on specification/trace/sdk.md
> +3. If the decision is `DROP` and there is a valid parent span ID, reuse it as the new `Span`'s span ID.
This issue was discussed at the TC meeting today. The TC recommendation is to generate a new span ID even for non-recording spans.

Motivation: @SergeyKanzhelev explained that there are other telemetry use cases that rely on a unique span ID, like log correlations. 

Generating new ID for non-recording span and using that ID as parent ID for subsequent spans will result in broken traces. However, this can be alleviated by extending the logic in the SDK to capture the "last sampled span ID" and using it as a parent.

2020-11-04 21:01 UTC, Oberon00 commented on specification/trace/sdk.md
> +3. If the decision is `DROP` and there is a valid parent span ID, reuse it as the new `Span`'s span ID.
> However, this can be alleviated by extending the logic in the SDK to capture the "last sampled span ID" and using it as a parent.

How is that logic going to work across the W3C propagator?

2020-11-11 01:15 UTC, carlosalberto commented
Ping @yurishkuro

2020-11-11 16:29 UTC, bogdandrutu commented
@SergeyKanzhelev you mentioned during the specification sig that you will document the decision that was discussed during the TC meeting.

2020-11-11 16:29 UTC, bogdandrutu commented
@Oberon00 please rebase.

2020-11-11 18:45 UTC, SergeyKanzhelev requested changes
> @SergeyKanzhelev you mentioned during the specification sig that you will document the decision that was discussed during the TC meeting.

sorry for delay. This comment summarizes it: https://github.com/open-telemetry/opentelemetry-specification/pull/998#discussion_r517616726 but I was thinking to expand a bit.

2020-11-11 18:50 UTC, SergeyKanzhelev commented on specification/trace/sdk.md
> +3. If the decision is `DROP` and there is a valid parent span ID, reuse it as the new `Span`'s span ID.
the idea is that instrumented library needs a reliable unique ID of the operation to associate with logs, exceptions or even return to user as to get support help. Is there is a spanID reuse - library will need to generate an alternative ID for this purposes.

Also platforms may now know all the time if there is a span consumer if has some tricky implementation optimized for hot path execution (like moving all sampling to the end).

The ida is that we will GA with the regenerated spanID and discuss how to improve on it using things like propagating spanID via tracestate. Since we do not have specific design, regeneration looks like a safer choice that will not break SDK going forward and is easier to explain.

2020-11-11 18:50 UTC, SergeyKanzhelev commented on specification/trace/sdk.md
> +3. If the decision is `DROP` and there is a valid parent span ID, reuse it as the new `Span`'s span ID.
I planned to write more but forgot it's a veterans day with schools closed today

2020-11-11 19:27 UTC, Oberon00 commented on specification/trace/sdk.md
> +3. If the decision is `DROP` and there is a valid parent span ID, reuse it as the new `Span`'s span ID.
> regeneration looks like a safer choice that will not break SDK going forward

I think changing from any of them to the other will break some uses.

> and is easier to explain

Fair enough.

> the idea is that instrumented library needs a reliable unique ID of the operation 

If you have an ID that is not associated with any trace on the tracing backend, will that be more helpful than the "inexact" ID of the parent operation? Note, you will have a valid span ID in any case.

I would say we go GA with this, and discuss how to improve on it using things like adding a `GetUniqueOperationId` function to `Span` that returns the span ID if it was generated for that span or generates a new ID that is cached and propagated to children if it is not. I recon propagating this ID cross-process may be difficult, but the same goes for propagating the ID of the last sampled span, and it seems unlikely that you call GetUniqueOperationId on an extracted span directly (it would not be very unique, since the parent's process would have the same ID if it was sampled at least).

2020-11-11 19:38 UTC, SergeyKanzhelev commented on specification/trace/sdk.md
> +3. If the decision is `DROP` and there is a valid parent span ID, reuse it as the new `Span`'s span ID.
> > regeneration looks like a safer choice that will not break SDK going forward
> 
> I think changing from any of them to the other will break some uses.
> 
> > and is easier to explain
> 
> Fair enough.
> 
> > the idea is that instrumented library needs a reliable unique ID of the operation
> 
> If you have an ID that is not associated with any trace on the tracing backend, will that be more helpful than the "inexact" ID of the parent operation? Note, you will have a valid span ID in any case.
> 
> I would say we go GA with this, and discuss how to improve on it using things like adding a `GetUniqueOperationId` function to `Span` that returns the span ID if it was generated for that span or generates a new ID that is cached and propagated to children if it is not. I recon propagating this ID cross-process may be difficult, but the same goes for propagating the ID of the last sampled span, and it seems unlikely that you call GetUniqueOperationId on an extracted span directly (it would not be very unique, since the parent's process would have the same ID if it was sampled at least).

The assumption that there is a trace backend may not be true for everybody. And having trace backend of your caller having a record of a parent span Id is not helpful to solve your problem. So the decision we made at @open-telemetry/technical-committee is to go with span ID regeneration. This creates a nice guarantee of local uniqueness of a spanID that various telemetry signals may take a dependency on.

How strongly do you disagree?

2020-11-11 20:31 UTC, Oberon00 commented on specification/trace/sdk.md
> +3. If the decision is `DROP` and there is a valid parent span ID, reuse it as the new `Span`'s span ID.
Not very strongly. I do think my proposed solution is the better trade-off but I concede that always generating a new ID is also a reasonable option.

2020-11-12 22:01 UTC, carlosalberto commented on specification/trace/sdk.md
> +3. If the decision is `DROP` and there is a valid parent span ID, reuse it as the new `Span`'s span ID.
@Oberon00 Thanks for the answer. I think we will go with the TC decision for now then - if you have time, would you mind updating this PR to match the proposal? Else, I can help by creating a spin-off of this PR. Let me know ;)

2020-11-12 22:11 UTC, Oberon00 commented on specification/trace/sdk.md
> +3. If the decision is `DROP` and there is a valid parent span ID, reuse it as the new `Span`'s span ID.
I think it would be best to create a spin-off PR. That way we clearly document that this option was rejected.

2020-11-16 16:17 UTC, closed without merging